### ISSUE TITLE
add-editor difference between theme EKRDark and EKRLight

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#1000]
When use EKRDark: atfer run add-editor, the leftmost editor can **not** input text.
When use EKRLight: atfer run add-editor, the leftmost editor can input text.

So I use EKRLight now. But I want to use EKRDark theme.

***

Leo Log Window
Leo 5.8.1 devel, build 20181010215307, Wed Oct 10 21:53:07 PDT 2018
Git repo info: branch = devel, commit = 542b7bc9015f
Python 3.6.6, PyQt version 5.11.1
linux
isPython3: True
redefining abbreviation html;; 
from '<html>\n<head>\n<title><|title|></title>\n<style>\n</style>\n</head>\n<body>\n<|content|>\n</body>\n</html>' to '@first <!DOCTYPE html>\n@language html\n@tabwidth -4\n@others\n'
redefining abbreviation ,, 
from "{|{x='__NEXT_PLACEHOLDER'}|}" to '__NEXT_PLACEHOLDER'
loadOnePlugin: leo.plugins.livecode.init() returned False
read outline in 0.75 seconds
can not delete leftmost editor

**Comment by wangzhaohe** [comment]
> technatica commented on 7 Jul •
This is likely a PyQt 5.10 issue: #804 Read the comments for the workaround. A fix will either be new code in Leo to handle notifications or QT fixing the bug. Another workaround would be to use =<QT5.7.

Still wait for QT bug fix?

**Comment by edreamleo** [comment]
Please try devel now.  The EKRDark theme has been changed to put the dangerous ~= css at the end.  This should fix the problem unless a "user" stylesheet follows the qt stylesheet.
