### ISSUE TITLE
Bogus clone icons.

### ISSUE THREAD

**Issue by SegundoBob** [leo-editor/leo-editor#1001]
## Overview

Cut-node (Shift+Ctrl+X) followed by paste-retaining-clones (Shift-Alt-V) leaves the node marked with the clone icon even when the node is NOT a clone.  This is the only bad effect I noticed.  The erroneous clone mark lasts till the file is closed.  When the file is reopened, the erroneous clone icon has disappeared.

## Bisect Results

This problem exists in the latest release (commit 16011ec6148e).
```
e72122d8cf8871816ec23da9d63d26b14b18120c is the first bad commit

commit e72122d8cf8871816ec23da9d63d26b14b18120c
Author: Edward K. Ream <edreamleo@gmail.com>
Date:   Thu Jun 21 04:08:55 2018 -0500

    A milestone: all tests pass without sax read code.

    - Deleted fc.readSaxFile and fc.getLeoFileHelper.
    - FastRead.readFile does not change c.hiddenRootNode.
    - Improved traces in c.checkGnxs.
```
## Test System

Leo 5.8.1 devel, build 20181013173725, Sat Oct 13 17:37:25 PDT 2018
Git repo info: branch = devel, commit = 16011ec6148e
Python 3.6.6, PyQt version 5.9.5
linux
isPython3: True
import-jupyter-notebook requires nbformat package

**Comment by edreamleo** [comment]
On Mon, Oct 15, 2018 at 2:54 PM SegundoBob <notifications@github.com> wrote:

> Cut-node (Shift+Ctrl+X) followed by paste-retaining-clones (Shift-Alt-V)
> leaves the node marked with the clone icon even when the node is NOT a
> clone. This is the only bad effect I noticed. The erroneous clone mark
> lasts till the file is closed. When the file is reopened, the erroneous
> clone icon has disappeared.
>
Thanks for this report.  This is surely a problem with the global dict of
gnx's. It will be fixed before the next release.

Edward

**Comment by vitalije** [comment]
Fixed at ff08fe733

**Comment by edreamleo** [comment]
I am going to close this issue. The fix is simple and elegant.

**Comment by SegundoBob** [comment]
Thanks vitalije.  Fix confirmed in
```
Leo 5.8.1 devel, build 20181225152842, Tue Dec 25 15:28:42 UTC 2018
Git repo info: branch = devel, commit = ff08fe733127
Python 3.6.7, PyQt version 5.11.1
linux
isPython3: True
```
