### ISSUE TITLE
self.assertEqual in a @test node is not comparing lists properly

### ISSUE THREAD

**Issue by beetleb** [leo-editor/leo-editor#1002]
I'm running Leo 5.7 on Windows on Python 3.5.2

If I make an @test node with:

``self.assertEqual(1, 2)``

it correctly fails. However, if I do:

``self.assertEqual(['a'], ['b'])`` 

it passes. It should not pass.

**Comment by edreamleo** [comment]
On Fri, Oct 19, 2018 at 6:11 PM beetleb <notifications@github.com> wrote:

> I'm running Leo 5.7 on Windows on Python 3.5.2
>
> If I make an @test <https://github.com/test> node with:
>
> self.assertEqual(1, 2)
>
> it correctly fails. However, if I do:
>
> self.assertEqual(['a'], ['b'])
>
> it passes. It should not pass.
>
Fixed at f66638963 in devel.  This was a strange one.  Happily, the fix was
easy.

Edward

**Comment by beetleb** [comment]
Thanks. 

Curious: Do any of Leo's unit tests rely on this? Are all Leo's unit tests still OK after this fix?

**Comment by edreamleo** [comment]
On Mon, Oct 22, 2018 at 11:38 AM beetleb <notifications@github.com> wrote:

> Thanks.
>
> Curious: Do any of Leo's unit tests rely on this?
>
No, for two reasons.  First, tests in @test nodes can just use assert.
Second, the fix affected only tests against lists.  This is an unusual
special case in unittest.TestCase. Most of the time unittest.TestCase does
*not* call fail, so GeneralTestCase.fail did not have to raise an
exception.  Now it always does, which should handle all future situations.

> Are all Leo's unit tests still OK after this fix?
>
That was the first thing I checked.

Edward
