### ISSUE TITLE
Data Loss:  External file, orphan node

### ISSUE THREAD

**Issue by SegundoBob** [leo-editor/leo-editor#1003]
## My Experience

I lost 30-minutes of work, writing one small function, to this bug.

## Procedure to Reproduce Problem:

Create a new Leo-Editor file:  loss.leo.

Add a second root node with headline "@file x.py".  Leave the body of this node empty.

Add a child node to this second root node.  Put anything you want in the headline and body.  This is the data that will be lost.

Save (Ctrl-S) the new Leo-Editor file.  Note the errors:
```
errors writing: /sec/tmp/x.py
Orphan node:  func()
parent node: @file x.py
not written: x.py
```
Exit Leo-Editor.

Reopen loss.leo.  Note that no data has been lost.  The @file node still has a child.

Save (Ctrl-S).  No error this time.

Exit Leo-Editor.

Reopen loss.leo. Note that the second root node now has no children.  Data has been lost.

## Test system
```
Leo 5.8.1 devel, build 20181013173725, Sat Oct 13 17:37:25 PDT 2018
Git repo info: branch = devel, commit = 883bde09aa40
Python 3.6.6, PyQt version 5.9.5
linux
isPython3: True
```
## Bisect
```
$ git bisect bad
62017436e970122e20bc4c16763b0549fd50c23b is the first bad commit
commit 62017436e970122e20bc4c16763b0549fd50c23b
Author: Edward K. Ream <edreamleo@gmail.com>
Date:   Thu Jun 7 16:27:30 2018 -0500

    Removed tracing code and disabled some pylint complaints

:040000 040000 352b004fbda51f488beedcee5f7de6391e92ebe5 767f42779fa1e315386589e9b251cf52b2b2e9ba M	leo
```

**Comment by maphew** [comment]
Ouch. Replicated on my linux laptop, same Leo version (current devel branch).

After 1st save:
```xml
(leo-dev) matt@dell-xps ~/code/leo-editor $ cat loss-1003-save01.leo 
<?xml version="1.0" encoding="utf-8"?>
<!-- Created by Leo: http://leoeditor.com/leo_toc.html -->
<leo_file xmlns:leo="http://leoeditor.com/namespaces/leo-python-editor/1.1" >
<leo_header file_format="2"/>
<globals/>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="matt.20181022215210.1"><vh>empty first root node</vh></v>
<v t="matt.20181022215259.1"><vh>@file x.py</vh>
<v t="matt.20181022215312.1"><vh>1st child node to x.py</vh></v>
</v>
</vnodes>
<tnodes>
<t tx="matt.20181022215210.1"></t>
<t tx="matt.20181022215259.1"></t>
<t tx="matt.20181022215312.1"></t>
</tnodes>
</leo_file>
```
After 2nd save:
```xml
(leo-dev) matt@dell-xps ~/code/leo-editor $ cat loss-1003-save02.leo 
<?xml version="1.0" encoding="utf-8"?>
<!-- Created by Leo: http://leoeditor.com/leo_toc.html -->
<leo_file xmlns:leo="http://leoeditor.com/namespaces/leo-python-editor/1.1" >
<leo_header file_format="2"/>
<globals/>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="matt.20181022215210.1"><vh>empty first root node</vh></v>
<v t="matt.20181022215259.1"><vh>@file x.py</vh></v>
</vnodes>
<tnodes>
<t tx="matt.20181022215210.1"></t>
</tnodes>
</leo_file>
```

**Comment by maphew** [comment]
Putting a `@file` node with an orphan as 1st node in file there is no data loss. The log messages follow the same pattern (on 1st save there is a warning, on subsequent saves no warning).

```xml
(leo-dev) matt@dell-xps ~/code/leo-editor $ cat loss-1003-1st-node-file-save01.leo
<?xml version="1.0" encoding="utf-8"?>
<!-- Created by Leo: http://leoeditor.com/leo_toc.html -->
<leo_file xmlns:leo="http://leoeditor.com/namespaces/leo-python-editor/1.1" >
<leo_header file_format="2"/>
<globals/>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="matt.20181022220622.2"><vh>@file x-first-node-file.py</vh>
<v t="matt.20181022220646.1"><vh>1st node 1st child headline</vh></v>
</v>
</vnodes>
<tnodes>
<t tx="matt.20181022220622.2"></t>
<t tx="matt.20181022220646.1"></t>
</tnodes>
</leo_file>
```

```
$ diff -s loss-1003-1st-node-file-*.leo
Files loss-1003-1st-node-file-save01.leo and loss-1003-1st-node-file-save02.leo are identical
```

**Comment by edreamleo** [comment]
I doubt that commit 62017436e97 is the culprit.  It does not pertain to the this issue in any significant way.

In any case, I shall fix this bug from first principles, without worrying about ancient history.

**Comment by edreamleo** [comment]
The fix has lead into unexpected directions.  The work will be done in the "change" branch.

There are expected fixes to at.writeAllHelper and at.read. But there were several surprises:

- The tree produced by the git-diff command must have an `@ignore` directive. 
- at.readAll did not handle `@ignore` correctly.
- c.setChanged is substantially trickier than I imagined.

**Comment by edreamleo** [comment]
An elegant solution does exist! Leo should just an `@ignore` directive to the body text to the root node of orphaned external files.  This instantly guarantees that Leo will save the at-risk code to the .leo file! Furthermore, Leo *already* warns when attempting to save an external file containing an `@ignore` directive.

**Summary**: This is simple, safe, and effective.  It is way better than messing with orphan bits.

**Comment by edreamleo** [comment]
On Tue, Oct 23, 2018 at 5:26 AM Edward K. Ream wrote:

> Without doubt, Leo should leave the @file x.py marked dirty after
reporting an orphan node.

For those not subscribed to #1003
<https://github.com/leo-editor/leo-editor/issues/1003>, here is a summary
of recent comments:

1. My initial plan for a fix was way too complex to be safe.

2. The simple, safe and Leonine solution will be to add the @ignore
directive to the root node of any external file that can't be successfully
written. Leo *already* warns when files contain @ignore, and Leo *already*
saves such trees in the .leo file.  The user can remove the @ignore at
their leisure, and Leo will then re-insert @ignore if problems persist.

Edward

**Comment by edreamleo** [comment]
The change2 branch uses `@ignore` instead of the orphan bit.  The change2 branch has been merged into devel.

The orphan bit has been deprecated. It will remain for compatibility. Neither Leo's core nor Leo's official plugin use the orphan bit now.
