### ISSUE TITLE
Move Node Bug Includes Data Loss

### ISSUE THREAD

**Issue by SegundoBob** [leo-editor/leo-editor#1004]
## Procedure to Reproduce the Problem

See moveNodeBug.leo and external.txt at:

https://gist.github.com/SegundoBob/8a2a959633b73aba1c422d0c9e20a103

Put moveNodeBug.leo and external.txt in a directory you can write to.

Open moveNodeBug.leo.

Select the node with headline "Ctrl+B" and then Ctrl+B.

Open the body of the node with headline "Problem Node".  Change the body contents.

Save (Ctrl+S) moveNodeBug.leo.

Exit Leo-Editor.

Open moveNodeBug.leo.

Note that "Problem Node" is now a clone because it has come back into existence in the external file; and all your changes to the body of "Problem Node" have disappeared.

## Test Systems
```
Leo 5.8.1 devel, build 20181013173725, Sat Oct 13 17:37:25 PDT 2018
Git repo info: branch = devel, commit = c1f7ce06e628
Python 3.6.6, PyQt version 5.9.5
linux
isPython3: True
```
```
Leo 5.8.1 devel, build 20181013173725, Sat Oct 13 17:37:25 PDT 2018
Git repo info: branch = devel, commit = 883bde09aa40
Python 3.6.6, PyQt version 5.9.5
linux
isPython3: True
```

**Comment by edreamleo** [comment]
This is a bug in the script, not in Leo.  The following script works:
```python
pList = c.find_h('Problem Node')
pFrom = pList[0]
pList = c.find_h('New Parent')
pToP = pList[0]
pFrom.parent().setDirty()
pNew = pFrom.moveToNthChildOf(pToP, 0)
pToP.setDirty()
pNew.setDirty()
c.redraw()
```
HTH.

**Comment by SegundoBob** [comment]
Thanks that does fix the problem.

I noticed the problem using a Leo-Editor command that I wrote at least five years ago.  That is, I'm fairly sure that until recently, it was not necessary to make the three calls to setDirty() that you now say are required.  If this change in requirements is intended, then this issue is closed.

If you want backward compatibility in this case and in this case do not want to change requirements, I would be happy to do a bisect to determine where the change occurred.

**Comment by SegundoBob** [comment]
I was wrong.

I confirmed the current behavior of p.moveToNthChildOf() as far back as 2014-08-05.  What changed recently, was the "recovered nodes" behavior.  I guess that until recently when my buggy function caused node resurrection, I saw the "recovered nodes" and was puzzled how it happened, wondered why the newer node was labeled as the "old" node, and dismissed it as a "recovered nodes" problem because there has been much talk of such problems over the years.

Thanks for pointing out my bug.

Issue closed as far as I'm concerned.

**Comment by edreamleo** [comment]
On Fri, Oct 26, 2018 at 1:00 PM SegundoBob <notifications@github.com> wrote:

> I confirmed the current behavior of p.moveToNthChildOf() as far back as
> 2014-08-05. What changed recently, was the "recovered nodes" behavior. I
> guess that until recently when my buggy function caused node resurrection,
> I saw the "recovered nodes" and was puzzled how it happened, wondered why
> the newer node was labeled as the "old" node, and dismissed it as a
> "recovered nodes" problem because there has been much talk of such problems
> over the years.
>
> Thanks for pointing out my bug.
>
> Issue closed as far as I'm concerned.
>
Thanks for the update.

Edward
