### ISSUE TITLE
Leo-Babel Source should reside in only one directory, not two

### ISSUE THREAD

**Issue by SegundoBob** [leo-editor/leo-editor#1008]
I raised this issue on the forum a few days ago [Leo-Babel source files](https://groups.google.com/forum/?fromgroups#!topic/leo-editor/7AaL96_qGEA).  Please read my thoughts there. 

Since git  mostly ignores directories, git considers the duplicate files in leo/plugins to be renamed versions of the files in leo/plugins/leo_babel.  Yet the files in leo/plugins/leo_babel still exist.  So git has a slightly inconsistent view of the current state.  Deleting the Leo-Babel source from either directory would probably fix any possible source control problems.

The latest version on which I have verified this problem is ('devel', '58ee2216dd09') Date:   Wed Oct 31 16:32:40 2018 -0500.

**Comment by edreamleo** [comment]
On Wed, Oct 31, 2018 at 5:26 PM SegundoBob <notifications@github.com> wrote:

> I raised this issue on the forum a few days ago Leo-Babel source files
> <https://groups.google.com/forum/?fromgroups#!topic/leo-editor/7AaL96_qGEA>.
> Please read my thoughts there.
>
Sorry for the delay in responding.  Misplacing the files was likely a
mistake on my part.  Please file a PR for the correct organization.

Edward

**Comment by edreamleo** [comment]
Fixed via PR #1014.
