### ISSUE TITLE
Deep in  bridge.openLeoFile(fpn) TypeError: 'NoneType' object does not support item assignment

### ISSUE THREAD

**Issue by SegundoBob** [leo-editor/leo-editor#1017]
I'm seeing this error fairly often and fairly repeatably when using a script I wrote to grep Leo-Editor files.  Because the error occurs so deep in bridge.openLeoFile(), I doubt that I'll be able to discover a simple repeatable test case.   If the error is in my script, I doubt that I'll find that error any time soon.

Perhaps someone with more knowledge of Leo-Editor, can look at the stack trace and conclude something useful.

In case anyone wants to try reproducing the error using my script, I attach it and a library I wrote that it uses.
## Stack Trace
```
$ leogrep earthquake *.leo
Traceback (most recent call last):
  File "/pri/bin/leogrep", line 151, in <module>
    main()
  File "/pri/bin/leogrep", line 135, in main
    cmdr = bridge.openLeoFile(fpn)
  File "/pri/git/leo-editor/leo/core/leoBridge.py", line 262, in openLeoFile
    c = self.createFrame(fileName)
  File "/pri/git/leo-editor/leo/core/leoBridge.py", line 293, in createFrame
    c = g.openWithFileName(fileName)
  File "/pri/git/leo-editor/leo/core/leoGlobals.py", line 3694, in openWithFileName
    return g.app.loadManager.loadLocalFile(fileName, gui, old_c)
  File "/pri/git/leo-editor/leo/core/leoApp.py", line 3093, in loadLocalFile
    previousSettings = lm.getPreviousSettings(fn)
  File "/pri/git/leo-editor/leo/core/leoApp.py", line 1999, in getPreviousSettings
    c = lm.openSettingsFile(fn)
  File "/pri/git/leo-editor/leo/core/leoApp.py", line 2164, in openSettingsFile
    readAtFileNodesFlag=False, silent=True)
  File "/pri/git/leo-editor/leo/core/leoFileCommands.py", line 652, in openLeoFile
    silent=silent,
  File "/pri/git/leo-editor/leo/core/leoFileCommands.py", line 515, in getLeoFile
    v = FastRead(c, self.gnxDict).readFile(fileName)
  File "/pri/git/leo-editor/leo/core/leoFileCommands.py", line 68, in readFile
    return self.readWithElementTree(path, s)
  File "/pri/git/leo-editor/leo/core/leoFileCommands.py", line 91, in readWithElementTree
    hidden_v = self.scanVnodes(gnx2body, self.gnx2vnode, gnx2ua, v_elements)
  File "/pri/git/leo-editor/leo/core/leoFileCommands.py", line 312, in scanVnodes
    v_element_visitor(v_elements, hidden_v)
  File "/pri/git/leo-editor/leo/core/leoFileCommands.py", line 297, in v_element_visitor
    uaDict[key] = self.resolveUa(key, val)
TypeError: 'NoneType' object does not support item assignment

[leogrep.zip](https://github.com/leo-editor/leo-editor/files/2593365/leogrep.zip)
```
## Test System
```
Leo 5.8.1 devel, build 20181103230124, Sat Nov  3 23:01:24 PDT 2018
Git repo info: branch = devel, commit = d9686cecf53f
Python 3.6.6, PyQt version 5.11.1
linux
isPython3: True
```
[leogrep.zip](https://github.com/leo-editor/leo-editor/files/2593369/leogrep.zip)

**Comment by SegundoBob** [comment]
This probably isn't a very interesting or important bug, if it is a bug.

Both Leo-Bridge and the Leo GUI report the same exception and fail to open the same files.  That is, the problem is caused by Leo-Editor file contents.

I had 7 files with this problem.  They were all last changed 2012-02-07.  The problem is the first v-node entry:
```
<v t="bob.20091018134940.3301" str_leo_pos="1,2"><vh>@chapters</vh></v>
```

Removing | str_leo_pos="1,2"| (not including the | end markers) makes Leo-Editor happy.

Attached is a copy of my smallest file that shows the problem.

[NoneTypeError.zip](https://github.com/leo-editor/leo-editor/files/2597031/NoneTypeError.zip)

The problem string varies.  For example, | str_leo_pos="1,1,3"|

**Comment by tbnorth** [comment]
I guess I don't know how Leo reads XML, but it seems unnecessary to fail on
what has presumably become an unknown attribute.  Attribute in the XML
sense, not the Leo "unknown attribute" sense :).  In most contexts reading
XML completely ignores unknown attributes.

Cheers -Terry

**Comment by edreamleo** [comment]
On Mon, Nov 19, 2018 at 3:44 PM Terry Brown <notifications@github.com>
wrote:

> I guess I don't know how Leo reads XML, but it seems unnecessary to fail on
> what has presumably become an unknown attribute.


I agree.  This is presumably a bug in Leo.  I'll fix it when I'm done with
leoflexx.py.

Edward

**Comment by vitalije** [comment]
Fixed at 9fbd1a47b

It was wrong usage of defaultdict. It doesn't create new items if accessed by get method. For example:

```
gnx2ua = defaultdict(dict)
a = gnx2ua['a'] # this will put newly created dict in a
a['test'] = 1
b = gnx2ua.get('b') # this won't create a new dict. Now b is None 
assert b is None
```

**Comment by edreamleo** [comment]
Thanks, once again, Vitalije, for this fix.

**Comment by SegundoBob** [comment]
Thanks vitalije.  Fix confirmed in
```
Leo 5.8.1 devel, build 20181225152842, Tue Dec 25 15:28:42 UTC 2018
Git repo info: branch = devel, commit = ff08fe733127
Python 3.6.7, PyQt version 5.11.1
linux
isPython3: True
```
