### ISSUE TITLE
External files no longer retain marks

### ISSUE THREAD

**Issue by SegundoBob** [leo-editor/leo-editor#1018]
## Test Procedure

1.  Create a new Leo-Editor file, mark.leo.
2. Add a node with "@file xxx.txt" as its headline (without double quotes).
3. Add a child node of the "@file xxx.txt" node and mark this node (Ctrl-M).
4. Save the Leo-Editor file (Ctrl-S).
5. Exit Leo-Editor.
6. Re-open mark.leo and note that the child node is not marked.

**EKR Notes**
- I see the behavior described.
- The problem is that fc.putVnode only puts the top-level node for `@file` trees, so
  fc.compute_attribute_bits is never called for the child node.
- The solution will be to duplicate the logic in fc.compute_attribute_bits in the atFile code.
- Likely a similar problem exists with 'expanded bits', though most people would never notice it.
  However, that problem should also be corrected.

## Most Recent Revision Tested:
```
Leo 5.8.1 devel, build 20181103230124, Sat Nov  3 23:01:24 PDT 2018
Git repo info: branch = devel, commit = 1bdc9e4bdf07
Python 3.6.7, PyQt version 5.11.1
linux
isPython3: True
import-jupyter-notebook requires nbformat package
```
## Bisect Results
```
$ git bisect bad
75ee4b00fa95dbf9c09534d5964177af54afd1df is the first bad commit
commit 75ee4b00fa95dbf9c09534d5964177af54afd1df
Author: Edward K. Ream <edreamleo@gmail.com>
Date:   Sun Jun 24 13:36:37 2018 -0500

    A milestone: The cache now contains all marked/expanded bits.
    The root @file node no longer contains these bits.
    The c.fixed switch will soon be retired.

:040000 040000 6f21c7aad8e2fed7ba09aeff861b898de696275a 2c0d6eb8ae22216d9c8b5e920102e7e12cbd9f06 M	leo
```
## Observation:

While bisecting, I noted that a "good" revision created a file with the marks in the external file, but the "bad" revision failed to show those marks.  Maybe the "bad" revisions make the marks and writes the marks, but the bug is that the file read ignores the marks.

## Other Possible Problem

While bisecting, I noted that these revisions retain marks in external files, but not in the Leo-Editor file:
```
9daa7e0fee4e2455d161993f3b5679c3af512fac
87616a4c1d35f14bcba33294c0b7374fe3872ff9
```

**Comment by vitalije** [comment]
By looking at the revision 75ee4b00fa9 (the first bad), it seems to me that the marked bits are stored in the cache db rather than in the external file itself. IIRC at some point lots of cache functionalities related to external files were switched off.

**Comment by edreamleo** [comment]
On Sun, Nov 25, 2018 at 5:29 PM SegundoBob <notifications@github.com> wrote:

> Test Procedure
>
>    1. Create a new Leo-Editor file, mark.leo.
>    2. Add a node with "@file <https://github.com/file> xxx.txt" as its
>    headline (without double quotes).
>    3. Add a child node of the "@file <https://github.com/file> xxx.txt"
>    node and mark this node (Ctrl-M).
>    4. Save the Leo-Editor file (Ctrl-S).
>    5. Exit Leo-Editor.
>    6. Re-open mark.leo and note that the child node is not marked.
>
> Hmm.  Marks are restored for me as I expect.

Who else sees this problem?

Edward

**Comment by SegundoBob** [comment]
This bug still exists in the latest revision of Leo-Editor:
```
Leo Log Window
Leo 5.8.1-b2 devel, build 20190227233831, Wed Feb 27 23:38:31 PST 2019
Git repo info: branch = devel, commit = b5017f610b6e
Python 3.6.7, PyQt version 5.11.1
linux
isPython3: True
```
See the "Test Procedure" section in the bug report.

**Comment by xavierguarch** [comment]
> Who else sees this problem?

@edreamleo: I've just also checked with the latest revision, and following exactly the "Test Procedure" I can also reproduce the issue.

```text
Leo Log Window
Leo 5.8.1-b2 devel, build 20190227233831, Wed Feb 27 23:38:31 PST 2019
Git repo info: branch = devel, commit = b5017f610b6e
Python 3.6.2, PyQt version 5.6.2
Windows 10 AMD64 (build 10.0.17134) SP0
isPython3: True
```

**Comment by xgid** [comment]
> Who else sees this problem?

@edreamleo: I've just also checked with the latest revision, and following exactly the "Test Procedure" I can also reproduce the issue.

```text
Leo Log Window
Leo 5.8.1-b2 devel, build 20190227233831, Wed Feb 27 23:38:31 PST 2019
Git repo info: branch = devel, commit = b5017f610b6e
Python 3.6.2, PyQt version 5.6.2
Windows 10 AMD64 (build 10.0.17134) SP0
isPython3: True
```

**Comment by maphew** [comment]
When I follow the test procedure I get a popup warning that the external file was not written because of errors. 

When re-opening the mark-1018.leo file the child node and it's contents are gone. 

The file on disk does not contain the child node or contents either (not surprising, the error said 'not written').

In the error log below the first "wrote @file test-bug-1018.txt" is after I added `@file` node and before the child node and marking it. 

> \---------------------------
> Not Written
> \---------------------------
> The following were not written because of errors:
> 
> @file test-bug-1018.txt
> 
> Warning: changes to these files will be lost
> unless you can save the files successfully.
> \---------------------------
> Ok   
> \---------------------------
> 

```
Leo Log Window
Leo 5.8.1-b2 devel, build 20190227233831, Wed Feb 27 23:38:31 PST 2019
Git repo info: branch = devel, commit = b5017f610b6e
Python 3.6.2, PyQt version 5.9.3
Windows 10 AMD64 (build 10.0.17134) SP0
isPython3: True
created: C:/Users/mattw/Documents/GitHub/test-bug-1018.txt
finished
saved: mark-1018.leo
wrote: test-bug-1018.txt
finished
saved: mark-1018.leo
errors writing: test-bug-1018.txt
Orphan node:  child node
parent node: @file test-bug-1018.txt
Orphan node: @file test-bug-1018.txt
not written: test-bug-1018.txt
finished
saved: mark-1018.leo
```

**Comment by maphew** [comment]
Contents of Leo file (copied with ctrl-shift-c on `@file` node) after creating child node:
```
<?xml version="1.0" encoding="utf-8"?>
<!-- Created by Leo: http://leoeditor.com/leo_toc.html -->
<leo_file xmlns:leo="http://leoeditor.com/namespaces/leo-python-editor/1.1" >
<leo_header file_format="2"/>
<vnodes>
<v t="mhw-debug-1081.20190228231741.2"><vh>@file test-bug-1018.txt</vh>
<v t="mhw-debug-1081.20190228233706.1"><vh>child node</vh></v>
</v>
</vnodes>
<tnodes>
<t tx="mhw-debug-1081.20190228231741.2">External files no longer retain marks #1018
https://github.com/leo-editor/leo-editor/issues/1018
</t>
<t tx="mhw-debug-1081.20190228233706.1">some text for body of child node
</t>
</tnodes>
</leo_file>
```
```

**Comment by xgid** [comment]
> When I follow the test procedure I get a popup warning that the external file was not written because of errors.

@maphew: You are right! If I follow "exactly" the test procedure I see the same error! 
I inadvertently added an "@others" at the body of the first node in the leo file for this to work. I do it so automatically that I don't realise!

So the corrected test procedure to reproduce the bug should be:

1. Create a new Leo-Editor file, mark.leo.
1. Add a node with "@file xxx.txt" as its headline (without double quotes).
1. Add `@others` to the body of this node
1. Add a child node of the "@file xxx.txt" node and mark this node (Ctrl-M).
1. Save the Leo-Editor file (Ctrl-S).
1. Exit Leo-Editor.
1. Re-open mark.leo and note that the child node is not marked.

Thanks Matt for your verification!

**Comment by edreamleo** [comment]
Fixed at rev 29b5ade in devel.

**Comment by SegundoBob** [comment]
Fix confirmed in
```
Leo Log Window
Leo 5.8.1-b2 devel, build 20190227233831, Wed Feb 27 23:38:31 PST 2019
Git repo info: branch = devel, commit = 58a09402d417
Python 3.6.7, PyQt version 5.11.1
linux
isPython3: True
import-jupyter-notebook requires nbformat package
```

**Comment by edreamleo** [comment]
On Fri, Mar 29, 2019 at 1:11 PM SegundoBob <notifications@github.com> wrote:

> Fix confirmed
>
Thanks.

Edward
