### ISSUE TITLE
After run add-editor, the leftmost body pane have nothing

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#1021]
After add-editor, the leftmost body pane contains nothing.

**Git bisect**: First bad commit: 5417f87, 2018-02-23 05:30:47, Fixes #690.

The problem is that `@bool user-gutter = True` causes dw.createBodyPane to insert another parent.  The bad code tried (and failed) to account for the new parent.

**Partial fix**: rev 022ad38 adds editor panes properly, but only the leftmost has line numbers.  See #1061.

**Comment by edreamleo** [comment]
Again, the recent changes to the EKRDark theme should fix this problem.

**Comment by edreamleo** [comment]
I see this behavior.  This must be fixed immediately.

**Comment by edreamleo** [comment]
The "add-editor" branch has been fully merged into "devel".
