### ISSUE TITLE
"Node expanded" and "Node Marked" information lingering without effect in .leo files

### ISSUE THREAD

**Issue by SegundoBob** [leo-editor/leo-editor#1023]
## Bug or Enhancement

It is up to Edward whether this is a bug or an enhancement request.

## Description

I don't completely understand this problem so there more than the usual danger that some or all of what I claim is wrong.

I think that fairly recently, Leo-Editor caching was completely and drastically changed reducing the amount of data cached from significant to insignificant.  I think the documentation has not caught up.  In particular, the following from Leo Settings:
```
@bool put_expansion_bits_in_leo_files = True

True (recommended):
    Write "E" attribute bits in <v> elements.
    Leo outlines will record the expansion state of all nodes.

False: (Good for files like unitTest.leo)
    Suppress "E" attribute bits in <v> elements.
    Only the ancestors of the presently selected node will
    be expanded when Leo opens an outline.
```

I think put_expansion_bits_in_leo_files now has no effect, has no reasonable use, and should be dropped. All the expansion information about nodes in the .leo file have already been moved to the cache.

Some people either wrongly assume the parameter is still effective or they disagree with me. See [1022](https://github.com/leo-editor/leo-editor/issues/1022#issuecomment-445977627) and [Don't save expansion bit in distribution .leo files?](https://groups.google.com/forum/#!msg/leo-editor/kL4EOrJFqTA/jMfF9l7rBAAJ)

Independent of how put_expansion_bits_in_leo_files is set, the only remaining node expansion information lingering in the .leo file is "expanded=" on @file nodes (and possibly other directive nodes).  I think the "expanded=" is not used at all, because when there is no cache information the "expanded=" does NOT cause the node to be expanded.  Perhaps, it triggers the code to use the information in the cache, but surely no trigger is necessary.  Maybe the node-UUID's for the expanded nodes are not put in the cache, but surely they could be.

### Example:
```
$ diff code*
17c17,18
< <v t="bob.20181102125559.1"><vh>@file m/json_model.py</vh></v>
---
> <v t="bob.20181102125559.1"
> expanded="bob.20181102125714.1,bob.20181122141846.1,"><vh>@file m/json_model.py</vh></v>
```
Note that expanding two nodes in an external file caused the addition of: new line +
```
expanded="bob.20181102125714.1,bob.20181122141846.1,"
```
That is, the node-UUID of the expanded node in the external file.

## Issue of Consistency

The node expansion information about all nodes in the .leo file is kept in the cache, is it really necessary treat the nodes in the external file differently?

## A similar problem exists for Marks

Marking two nodes in an external file caused the addition of a new line + 
```
marks="bob.20181125143301.1,bob.20181210122524.1,"
```
Again, these are the node-UUIDs of the nodes in the external file.

Yet, when I close and reopen a .leo file, I lose all marks and expansions on nodes in external files.  See. [1018](https://github.com/leo-editor/leo-editor/issues/1018.)  I have not figured out why I see this behavior and Edward does not, but I suspect it is caused by an option setting.

## Why this matters

Taking all node expansion and node marking information out of the .leo file will eliminate the annoying expansion and marking differences reported by git and other source control programs.  Then I could stop taking care to collapse all nodes before committing a revision.

## Two Test Systems
```
Leo Log Window
Leo 5.8.1 devel, build 20181103230124, Sat Nov  3 23:01:24 PDT 2018
Git repo info: branch = devel, commit = 1bdc9e4bdf07
Python 3.6.7, PyQt version 5.11.1

Leo Log Window
Leo 5.8.1 devel, build 20181204214531, Tue Dec  4 21:45:31 PST 2018
Git repo info: branch = devel, commit = 5bee46d48348
Python 3.6.7, PyQt version 5.11.1
linux
isPython3: True
import-jupyter-notebook requires nbformat package
```

**Comment by edreamleo** [comment]
On Mon, Dec 10, 2018 at 6:06 PM SegundoBob <notifications@github.com> wrote:

Many thanks for this thorough report.  Imo, this is a bug, it's a good
catch, it matters, and it should be fixed immediately.

- There is no longer any reason to pollute a .leo file with marked and
expansion bits.
  It will take some sleuthing to discover how this happens.

- @bool put-expansion-bits-in-leo-files is no longer used, and neither is
the corresponding ivar, c.putBitsFlag.

I'll do the work in a "bits" branch, based on devel.  Before making the
branch, I'll remove the unused setting from leoSettings.leo in devel.  I'll
also investigate whether there is a setting that controls whether marked
bits are ever placed in .leo files.

Edward

**Comment by edreamleo** [comment]
Rev e7b6cbd is the proposed fix.  The fix itself was simple, but more testing is needed.

**Comment by edreamleo** [comment]
This branch has been merged into devel and skeleton.

Please reopen if any problems are found.

**Comment by SegundoBob** [comment]
## Save .leo file Versus Save the Leo-Editor cache for the .leo file

Leo-Editor always writes the .leo file when Ctrl-S is hit.  This based on the file's "date modified" being updated.  If the contents of the .leo file has not been changed, this write is unnecessary.  The only effective thing the Ctrl-S does is to update the Leo-Editor cache for the .leo file with among other things the expanded node, marked node, and current focus information.

In the past, some effort was made to avoid writing the .leo file when the write would not change the .leo file.  Currently, external files are written only when their contents have been changed.  Not doing unnecessary writes is desirable, but this is not very important to me.

Since Ctrl-S does write the Leo-Editor cache and this affects what is preserved between Leo-Editor sessions, a "Cache updated" message in the Log Pane seems desirable to me.

## Test Procedure

In a .leo file containing an external file specified with an @file directive, expand and/or mark some nodes. Ctrl-S to update the Leo-Editor cache.  Close the .leo file.  Then re-open the .leo file and node which node expansion and node marks were preserved between the Leo-Editor sessions.

## Results

Nodes in a .leo file are expanded if and only if they were expanded when the .leo file was last saved.  The current focus does NOT affect which nodes in a .leo file are expanded.

Nodes in an external file are expanded if and only if the current focus requires it.  That is, nodes are expanded from the root down to the node with the current focus.

All marks on nodes in a .leo file are preserved between sessions.

No marks on nodes in an external file are preserved between sessions.  Even marks on nodes that are expanded due to the focus are lost.

## Suggestion

Node expanded and node marked should be preserved between Leo-Editor sessions for all nodes, even nodes in external files.

## Test System
```
Leo Log Window
Leo 5.8.1 devel, build 20181204214531, Tue Dec  4 21:45:31 PST 2018
Git repo info: branch = devel, commit = a24a8be6ba07
Python 3.6.7, PyQt version 5.11.1
linux
isPython3: True
import-jupyter-notebook requires nbformat package
```

**Comment by SegundoBob** [comment]
## Unnecessary writes to .leo

This is probably caused by marking the .leo dirty when a node expansion or node mark is changed.  But since this information is no longer put in the .leo, these operations should not mark the .leo dirty.

## Best Cache Updating Policy

Ideally the node expansions and marks at the end of the previous Leo-Editor session would be restored at the start of the next session.   Then there would be no need for a "Cache Updated' message to the Log Pane.

That is, session termination should update the cache.  Ctrl-S should not update the cache, but I don't feel strongly about this.
