### ISSUE TITLE
@openwith neovim = Alt+Shift+Ctrl+V

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#1024]
### node:
@openwith neovim = Alt+Shift+Ctrl+V

### body:
\# 'subprocess.Popen','C:/Program Files/Microsoft Office/Office/WINWORD.exe',None
ext:    
kind:   subprocess.Popen
arg:    "gnome-terminal -- nvim"

First I use nvim-qt, but only one nvim-qt window can be created. The 2nd nvim-qt can not run.
Then I want to use "gnome-terminal -- nvim", but log is **/bin/sh: 1: gnome-terminal -- nvim: not found**

Could you teach me how to realize this? Thanks!

run this:???
        subprocess.Popen(args = ["gnome-terminal", "--", "nvim"]

***

Leo Log Window
Leo 5.8, build 20180902142730, Sun Sep  2 14:27:30 PDT 2018
Git repo info: branch = master, commit = 83f54408d29a
Python 3.6.7, PyQt version 5.11.2
linux
isPython3: True

**Comment by edreamleo** [comment]
It seems like you are on the right track, as far as the `@openwith` node is concerned. If that doesn't work, you can create an `@button` or `@command` node containing something like:
```python
import subprocess
subprocess.Popen(args = ["gnome-terminal", "--", "nvim"]
```
As usual, you can bind anything you like to the `@button` or `@command` node use `@key`.

HTH.
