### ISSUE TITLE
Leo's unique and essential features

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#1025]
A **defining feature** of Leo is:

- Missing in other editors such as vim, emacs, atom, eclipse, etc.
- Implemented in Leo's core, not in gui code.

Leo's defining features _embolden programmers_. Programmers can refactor and re-imagine their code much more easily than with any other editor.

**Leo's defining features**

- Clones.
- The connection between the outline and body panes.
- Persistent outline state: c.p, gnx's, marks, expansion bits.
- Outline-oriented directives, features & settings, including abbreviations & chapters.

**Leo's defining commands and related features**

- Advanced outline commands, including hoist, dehoist, parse-body, etc.
- Chapter-related commands.
- clone-find, and other outline-related find commands.
- Abbreviations that create outlines.
- `@rst` and other PIM features.

**Leo's defining file features**

- The format of .leo files.
- `@file` and their sentinel comments.
- `@clean` and its update algorithm, in leo.core.leoShadow.
- `@auto` and related importers.

**Leo's defining scripting features**

- Leo's DOM:
  - Leo's Position and VNode classes.
  - Leo's generators.
- Pre-defined c, g and p vars.
- `@others` and section references.
- `@button` & `@command`.

**Features that do *not* define Leo**

None of the following features define Leo. They are found in typical IDE's and editors:
- Text editing commands and features, including auto-completion & syntax coloring.
- Printing,  monitoring external files and running code in external processes.
- Support for tools such as debuggers, IPython, pylint, pyflakes, rope, etc.
- Key bindings and ways of modifying them.

**Comment by edreamleo** [comment]
@ranvik14 `@rst` is on the borderline.  Emacs org mode has strong support for various kinds of markup.  Afaik, neither vimoutline nor pyzo has such features.

How to host Leo's essential features on another editor will always be a question that depends strongly on the host.  To repeat, this is a design document, not a tutorial or intro to Leo. It's purpose is to list those features that _might_ have to be implemented in Leo.

**Comment by boltex** [comment]
This post is a foundational inspiration, and reference, for developing LeoInteg and LeoJs!

**Comment by edreamleo** [comment]
@boltex Glad this issue was helpful.  I have been thinking about your remark on zoom that Leo is a new notation. I would encourage you to make a post on this topic in Leo's forum.

**Comment by boltex** [comment]
@edreamleo I'm talking about this very post! (scroll up to the original post)

**Comment by edreamleo** [comment]
@boltex Hehe.  I see.  I have dropped the word "gui" from one heading in the first topic, and made a few other small features.
