### ISSUE TITLE
Embed Leo in Emacs

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#1026]
This is the design document for embedding Leo in emacs. There is no need to dwell on code details here: this will be a typical gui in many respects.

**Feasibility**: pymacs was designed for exactly this purpose. Substantial parts of this project will be written in elisp, but as much as possible will be written in python.

**Importance**: Many [org mode](https://orgmode.org/manual/index.html#) users will be happy with org mode as it is. Otoh, emacs, including org mode, lacks all the essentials discussed in #1025. Embedding Leo in emacs will ensure Leo's continued existence.

**Overlapping features**: The rest of this items discusses gui elements, commands, key bindings and other settings that overlap between Leo and emacs, including org mode.

**Gui elements**: Leo in org mode must use emacs's buffers. There is no other choice.  Ditto for the minibuffer, log messages, etc. Leo in emacs will use emacs's menus. `@menus`, `@menu` and `@item` settings will not be supported. Emacs users can customize menus using `.emacs` or `init.el` as usual.

**Commands**: Leo in emacs will prefer emacs versions of commands where there is a conflict.  This is particularly true of yank/kill. No need for #337. Undo could require substantial work. The emacs minibuffer must, somehow, be made to know about all commands unique to Leo.

**Key bindings**: Leo in emacs will use emacs's key bindings. `@shortcuts` will not be supported.

**Settings**: Leonine settings will come from `@settings` trees in .leo files, as usual.  Settings relating to "native" emacs will continue to come from emacs-style settings in [init files](https://www.gnu.org/software/emacs/manual/html_node/emacs/Init-File.html).

**org mode**: [Org mode](https://orgmode.org/manual/index.html#) is widely used and has many powerful features. Org mode users will likely prefer org mode to the corresponding Leonine features:
- No need for Leo's todo.py plugin. No need for #775.
- No need for Leo's tables.py plugin. No need for #443.

*Some* org mode users will prefer the `#+BEGIN_SRC` syntax. This is one way to simulate Leo's Ctrl-B. [Header arguments](https://orgmode.org/manual/Header-arguments.html#Header-arguments) do not (yet) have any direct analog in Leo.

Org mode (via the outline-regexp setting of [outline mode](https://www.gnu.org/software/emacs/manual/html_node/emacs/Outline-Format.html#Outline-Format)) can be made to embed sentinel comments in any desired format, thereby simulating `@file`. However, `@clean` is impossible without the Mulder/Ream update algorithm.

**Comment by JohnLunzer** [comment]
I definitely agree with your decision to backburner this. I'm sorry to say I've been using emacs as my daily driver for about a year now. It would be absolutely wonderful to have true outline/tree/node style editing in emacs, but I believe the level of effort for trying to get Leo into emacs is not worth the time. For many reasons.

Anecdotally, emacs is the deepest and widest rabbit hole I've ever jumped down; well beyond what I experienced when learning/using Leo. 

One issue not bolded in your proposal is **performance**. emacs is not the speediest editor. I'm not sure how efficient pymacs is but I expect there is non-negligible overhead. Add Leo to that and you've got a recipe for focusing way more on performance issues than you ever planned to.

Sadly, I don't think it will be appreciated. emacs is a paradigm away from Leo and emacs users have found their own way to navigate projects/files/code. I'm not saying it's better or the same, just that the emacs user base may not see the benefit of any other "outliner" besides org-mode. I would provide [emacs hyperbole](https://www.gnu.org/software/hyperbole/) as a primary example of a failed attempt wrest control of the "outliner" space from org. 

I'd much rather see your time be spent polishing LeoWapp and potentially strapping LeoWapp and LeoVue together somehow (or at least borrowing the nice flashy bits from LeoVue). That has a much better potential to increase the Leo user-base and improve the community.

**Comment by edreamleo** [comment]
I agree with John.  This is almost certainly a bad idea.

**Comment by symbiont-matthew-piziak** [comment]
I've just discovered Leo, and this passage is brilliant:
>...**clones** create views: when you gather cloned nodes together for a project, you are, in effect, creating a project-oriented view of the outline. This view focuses your attention on only those nodes that are relevant to the task at hand.

Well said!

Many enterprise task management systems are completely bloated with features, whereas I've believed for a while that DAGs, tags, and tag inheritance are satisfy to emulate most usecases.

I'm an Emacs gargoyle and an Org user, but Org mode unfortunately does not support DAGs. I know that Leo has other features not present in Org, but this is the one that I miss the most. I've asked [a question](https://emacs.stackexchange.com/questions/51061/directed-acyclic-graphs-in-org-mode-and-cloned-nodes) to see if there isn't some way of getting some version of cloned tasks into the fold.

I'm hesitant to jump wholly into Leo. If cloned tasks don't shake out in Org-mode, then I'll probably give [this integration](https://leoeditor.com/emacs.html#controlling-leo-from-emacs-using-pymacs) a try, and and thence a full migration where my agenda views in Org mode simply become top-level _views_ in Leo.

Thank you for your work on this project, and particularly for your _precise_ vision in designing it. My first impressions are that it cuts laudably close to the underlying abstractions. Bravo!

**Comment by edreamleo** [comment]
On Mon, Jun 17, 2019 at 3:34 PM symbiont-matthew-piziak <
notifications@github.com> wrote:

> Thank you for your work on this project, and particularly for your
> *precise* vision in designing it. My first impressions are that it cuts
> laudably close to the underlying abstractions. Bravo!
>
Thanks for these kind words.  I look forward to your comparison of Leo and
org mode.

Edward
