### ISSUE TITLE
Embed Leo in vim

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#1028]
This is the design document for embedding Leo in vim. There is no need to dwell on code details here: this will be a typical gui in many respects.

**Feasibility**: vim supports plugins written in python. Substantial parts of this project will be written in [vimscript](https://devhints.io/vimscript), but as much as possible will be written in python.

**Importance**: Many [vimoutline](https://www.vim.org/scripts/script.php?script_id=3515) users will be happy with vimoutline as it is. Otoh, vimoutline lacks all the essentials discussed in #1025. Embedding Leo in vim will ensure Leo's continued existence.

**Overlapping features**: The rest of this items discusses gui elements, commands, key bindings and other settings that overlap between Leo and vim and vimoutline.

**Gui elements**: Leo in vim must use vim's gui elements, including menus. `@menus`, `@menu` and `@item` settings will not be supported. vim users can customize menus as usual.

**Commands**: Leo in emacs will prefer vim versions of commands where there is a conflict.  Undo could require substantial work. The vim minibuffer must, somehow, be made to know about all commands unique to Leo.

**Key bindings**: Leo in emacs will use vim's key bindings. `@shortcuts` will not be supported.

**Settings**: Leonine settings will come from `@settings` trees in .leo files, as usual.  Settings relating to "native" vim  will continue to come from vim's usual settings. 

**vimoutline**: [vimoutine](https://www.vim.org/scripts/script.php?script_id=3515) is widely used and has many powerful features. vimoutline *might* be able to simulate `@file`, but `@clean` is impossible without the Mulder/Ream update algorithm.

**Comment by tbnorth** [comment]
The NerdTree :-} plugin is quite a featureful Tree widget file browser - I think it's written in Vim's language, wonder if there's a layer of separation between ui and file system binding that could be leveraged for other tree UI applications.

**Comment by edreamleo** [comment]
On Sun, Dec 30, 2018 at 3:33 PM Terry Brown <notifications@github.com>
wrote:

> The NerdTree :-} plugin is quite a featureful Tree widget file browser - I
> think it's written in Vim's language, wonder if there's a layer of
> separation between ui and file system binding that could be leveraged for
> other tree UI applications.
>

Thanks for this link.  I've bookmarked it.

Just now I'm having trouble confronting Leo in vim, emacs or anywhere
else.  I'm not sure whether any such embedding project (#1016, #1018 or
#1019) is really in the same category as writing a new gui. I'll let this
rest on the back burner awhile, but these embedding projects definitely
will get some attention in 2019.

Edward

**Comment by edreamleo** [comment]
This is almost certainly a bad idea.
