### ISSUE TITLE
TypeError: markdown() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#1030]
After press Alt + 0 with @language md, the error displayed.

hook failed: idle, <bound method ViewRenderedController.update of <leo.plugins.viewrendered.ViewRenderedController object at 0x7f5278b62168>>, <no module>
Traceback (most recent call last):

   File "/home/swot/leo-editor/leo/core/leoPlugins.py", line 324, in callTagHandler
    result = handler(tag, keywords)

   File "/home/swot/leo-editor/leo/plugins/viewrendered.py", line 757, in update
    f(s, keywords)

   File "/home/swot/leo-editor/leo/plugins/viewrendered.py", line 1017, in update_md
    s = self.convert_to_markdown(s)

   File "/home/swot/leo-editor/leo/plugins/viewrendered.py", line 1038, in convert_to_markdown
    s = markdown(s, mdext)

TypeError: markdown() takes 1 positional argument but 2 were given

***

Leo Log Window
Leo 5.8.1 devel, build 20181204214531, Tue Dec  4 21:45:31 PST 2018
Git repo info: branch = devel, commit = 0037fbf042d8
Python 3.6.7, PyQt version 5.11.2
linux
isPython3: True
import-jupyter-notebook requires nbformat package
setting leoID from os.getenv('USER'): 'swot'
current dir: /home/swot/leo-editor
load dir: /home/swot/leo-editor/leo/core
global config dir: /home/swot/leo-editor/leo/config
home dir: /home/swot
reading settings in /home/swot/leo-editor/leo/config/leoSettings.leo
reading settings in /home/swot/.leo/myLeoSettings.leo

**Comment by vitalije** [comment]
Fixed in  950a94a.
The second argument must be passed as keyword argument.

**Comment by wangzhaohe** [comment]
Thanks! Run well now!
