### ISSUE TITLE
Tree Window Resizes on Paste Node

### ISSUE THREAD

**Issue by technatica** [leo-editor/leo-editor#1047]
I use a layout that has the body on the left (80% of screen width) and the tree and log window on the right.

Whenever I copy/paste a node the windows are resized to the equivalent of equal-sized-panes. It doesn't matter how long the node headline is. This is annoying.

**EKR**: I see this behavior on the latest devel version (Jan 19) on Windows.  So this happens regardless of platform or layout. That should make it easier to fix.

Leo 5.8.1 devel, build 20190102102352, Wed Jan 2 10:23:52 CST 2019
Git repo info: branch = devel, commit = 364d2bbd2bca
Python 3.6.7, PyQt version 5.11.2, linux

**Comment by edreamleo** [comment]
Fixed at 04796e4.  The following must save/restore the ratios because FastRead.readFile (properly) changes them:
    
- fc.getLeoOutlineFromClipBoard.
- fc.getLeoOutlineFromClipBoardRetainingClones.
- fc.getPos/VnodeFromClipboard.

Added NullFrame.getActualRatios(), to avoid crashes during startup.
