### ISSUE TITLE
Use qt.py wrapper

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#1052]
From Reinhard: [Qt.py](https://github.com/mottosso/Qt.py) is a Minimal Python 2 & 3 shim around all Qt bindings - PySide, PySide2, PyQt4 and PyQt5.

This would add an extra build dependency. Worse, it blesses one wrapper and removes flexibility from leoQt.py.  See https://xkcd.com/927/ Also, doing this assumes that qt.py remains up-to-date with PyQt.

Instead, my plan is to evolve leoQt.py as needed. It's ugly, but it's flexible.

**Comment by edreamleo** [comment]
This is unlikely to happen unless Anaconda bundles qt.py.

**Comment by maphew** [comment]
From the docs, it's available on conda-forge and pypi: https://github.com/mottosso/Qt.py#install
(i haven't tried either install method)
