### ISSUE TITLE
Wishlist: brew install for MacOS

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#106]
This item has gotten unwieldy.  I've moved most notes to leoDist.leo.

**Comment by edreamleo** [comment]
The milestone says 5.1 b2, but in fact I'll do this just after releasing 5.1 final.

**Comment by edreamleo** [comment]
Whew.  Added this [pull request](https://github.com/Homebrew/homebrew/pull/38980) We'll see what happens...

Here is the updated leo.rb file that passes ``brew audit --strict Leo``:

```ruby
class Leo < Formula
  homepage "http://leoeditor.com/"
  url "https://downloads.sourceforge.net/projects/leo/files/Leo/5.1-final/Leo-5.1-final.zip"
  sha256 "2d742f9825959ba5c7624d1179b9f3065e14e055c90272fbce199f91770de826"

  depends_on "pyqt"
  depends_on "enchant" => :recommended

  def install
    # Obtain information on Python installation
    python_xy = "python" + `%x(python -c "import sys;print(sys.version[:3])")`.chomp
    python_site_packages = lib + "#{python_xy}/site-packages"
    python_site_packages.install "leo"
    bin.install ["launchLeo.py", "profileLeo.py"]
    ln_s "#{bin}/launchLeo.py", "#{bin}/leo"
  end

  test do
    # Create, run in and delete a temporary directory.
    if system "python" "-c" "import leo"
      onoe "Leo FAILED"
    else
      ohai "Leo OK"
    end
  end
end
```

It took quite awhile to grok what was going on.  Here are my notes:

```bash
brew update
  # updates formulae.
brew doctor
# Clone homebrew into ~/leo.repo/homebrew
cd ~/leo.repo
git clone https://github.com/leo-editor/homebrew.git
brew create http://sourceforge.net/projects/leo/files/Leo/5.1-final/Leo-5.1-final.zip
    # This Downloaded the file and opened vim:
    # ==> Downloading http://sourceforge.net/projects/leo/files/Leo/5.1-final/Leo-5.1-
    # The second time I did this I simply replaced the file with the proper leo.rb.
brew audit --strict Leo
  # Caught various problems.
cd homebrew
  # Not part of the instructions.
git checkout -b Leo
  # Switched to a new branch 'Leo'
git add Library/Formula/leo.rb
  # Not part of the instructions.
git commit Library/Formula/leo.rb ### && git push
git push
  # (within SourceTree) using my normal GitHub username and password.
```

**Comment by edreamleo** [comment]
The homebrew people have made many suggestions for improving Leo's formula.  I'll make another attempt later today.

Here, I'd like to add to the previous post, to show the big picture.  Creating a pull request is actually pretty simple, as the [homebrew readme](https://github.com/Homebrew/homebrew/tree/master/share/doc/homebrew#readme) suggests:

    1. Fork Homebrew.
    2. brew create http://example.com/foo-0.1.tar.gz
    3. git checkout -b foo
    4. git commit Library/Formula/foo.rb && git push
    5. Pull Request: links to https://github.com/Homebrew/homebrew/pulls

This kind of abbreviated list strikes a good balance for those who know the big picture.  But for those who don't, a few more details would be helpful:

**Directories**

The instructions don't mention directories, which was confusing:

- I forked homebrew in ~/leo.repo, my standard place for repos.  This created all kinds of stuff in /usr/local, but **those places don't matter**.  Everything actually should happen in ~/leo.repo/homebrew. It took me awhile to realize I could ignore everything in /usr/local.

- Steps 2, 3 and 4 happened, iirc, in ~/leo.repo or in ~/leo.repo/homebrew, which, in *retrospect*, makes sense, but did not at the time.

**Pushing & the pull request**

The following may be blindingly obvious to those with more experience with git, but this was the first time I had used git in a more collaborative way:

- The push happens in **my** fork, so I can (must) use my *own* GitHub credentials to do the push.  I'm simply modifying my *own* fork.
- The link in the step 5, pull request, isn't really helpful.  Instead, after the push, a button in **my** fork of homebrew appeared called something like "submit pull request".  I pressed the button, added a few comments, and off we went.  Next time, I'll add a link to Leo's home page.  The email link was redundant, but it may have encouraged the helpful comments that I received...

**Changing the pull request**

The first pull request had problems, so I assume it won't be pulled.  I also assume that I can simply make the changes in leo.rb in my already existing branch, push them, and then issue a new pull request

**Summary**: This is actually a straightforward process, but nobody knows better than I that describing a straightforward process is anything but straightforward!

**Comment by ludwigschwardt** [comment]
Hi Edward,

Good luck with the formula! Homebrew is awesome but also a bit of a moving
target. No wonder they expect you to update every 24 hours :-) The Formula
Cookbook
<https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md#formula-cookbook>
is
a must-read (and has changed a bit since I created the original formula,
especially the Python-related parts!)

On Fri, Apr 24, 2015 at 11:54 AM, Edward K. Ream <notifications@github.com>
wrote:

> *Directories*
>
> The instructions don't mention directories, which was confusing:
>
>    -
>
>    I forked homebrew in ~/leo.repo, my standard place for repos. This
>    created all kinds of stuff in /usr/local, but *those places don't
>    matter*. Everything actually should happen in ~/leo.repo/homebrew. It
>    took me awhile to realize I could ignore everything in /usr/local.
>
> These instructions for contributing to Homebrew (specifically calling brew
commands) assume that you are actually *using* Homebrew, and normally the
Homebrew repo then lives in /usr/local. I normally work in that repo and
would then copy the formula elsewhere for pushing (typically to my tap
repo).

> *Changing the pull request*
>
> The first pull request had problems, so I assume it won't be pulled. I
> also assume that I can simply make the changes in leo.rb in my already
> existing branch, push them, and then issue a new pull request
>
You don't have to issue a new pull request. Just add your changes to the
same branch and push them, and they will remain associated with the same
pull request. This is a great feature of the PR: you can commit, discuss,
commit some more, discuss, etc. until everyone is happy and the PR then
gets accepted.

I would rename the pull request "leo 5.1 (new formula)". :-)

Regards,

Ludwig

**Comment by edreamleo** [comment]
On Fri, Apr 24, 2015 at 5:23 AM, Ludwig Schwardt <notifications@github.com>
wrote:


> The Formula
> Cookbook
> <
> https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md#formula-cookbook
> >
> is
> ​ ​
> a must-read
> ​...
>

​It will be easier to read now that I have made a first start.  In
particular, I missed the "testing" section the first time around.  That
should reduce the number of iterations.

> These instructions for contributing to Homebrew (specifically calling brew
> commands) assume that you are actually *using* Homebrew, and normally the
> Homebrew repo then lives in /usr/local. I normally work in that repo and
> would then copy the formula elsewhere for pushing (typically to my tap
> repo).
>

​Interesting.

You don't have to issue a new pull request. Just add your changes to the
> same branch and push them, and they will remain associated with the same
> ​ ​
> pull request. This is a great feature of the PR: you can commit, discuss,
> ​ ​
> commit some more, discuss, etc. until everyone is happy and the PR then
> ​ ​
> gets accepted.
>
> I would rename the pull request "leo 5.1 (new formula)". :-)
>

​Thanks for these tips.  I'll issue a new PR soon.

Edward

**Comment by edreamleo** [comment]
Here is the latest leo.rb:

```ruby
class Leo < Formula
  homepage "http://leoeditor.com/"
  url "http://sourceforge.net/projects/leo/files/Leo/5.0-final/Leo-5.0-final.zip"
  sha256 "2d742f9825959ba5c7624d1179b9f3065e14e055c90272fbce199f91770de826"
  head "https://github.com/leo-editor/leo-editor", :using => :git

  depends_on "pyqt"
  depends_on "enchant" => :recommended
  depends_on :python if MacOS.version <= :snow_leopard

  def install
    (lib+"python2.7/site-packages").install "leo"
    bin.install "launchLeo.py" => "leo"
  end

  test do
    system bin/"python", "-c", "import leo"
  end
end
```

This passes the following::

```bash
brew audit --strict Leo
brew install --verbose --debug Leo
```

However, after:

```bash
brew uninstall Leo
brew install Leo
```

I get the following:

```bash
sh: -c: line 0: syntax error near unexpected token `python'
sh: -c: line 0: `%x(python -c "import sys;print(sys.version[:3])")'
```

This looks like an old version of leo.rb is being used, but a thorough search shows no such file.  Any help would be appreciated.

Edward

**Comment by edreamleo** [comment]
I think this would be a good thing for Leo, but I do not seem able to do this.

I am going to mark this item as "Waiting" until such time as somebody competent volunteers to do the job.

**Comment by edreamleo** [comment]
I'll give this another try after Leo 5.4 final goes out the door.

**Comment by edreamleo** [comment]
**How to compute sha256 hash**

http://stackoverflow.com/questions/32673943/how-to-update-homebrew-sha256

After editing the formula, you can run:

    brew fetch your-formula --build-from-source

to fetch the tarball and display the new checksum.

If you've already downloaded the tarball somewhere, you can calculate the hash with:

    openssl sha256 < some_tarball.tar.gz

or:

    shasum -a 256 some_tarball.tar.gz

**Comment by edreamleo** [comment]
**Status report**:  I worked several hours yesterday on a new formula.  It may turn out to simple.

The top-level leo-editor folder can go _anywhere_.  There there seems to be no need for the formula put the folder in `lib/site-customize`!  Wherever it goes, we want the formula to put a symlink on the desktop (or in the home folder), which when double-clicked will execute `python launchLeo.py`.

The documentation must tell the user where `launchLeo.py` is so they can make aliases that open Leo.

**Comment by ludwigschwardt** [comment]
Brew already installs all the package files in its cellar in e.g. /usr/local/Cellar/leo/5.4, so I find that the natural place to find the Leo files.

On top of that I would just make launchLeo.py a normal executable script in /usr/local/bin via the Brew machinery, so that the user does not need to know where it is - it's on the path!

The symlink is then an icing on the cake. What about an App-like way to get to launchLeo?

**Comment by edreamleo** [comment]
@ludwigschwardt Thanks for these comments!  Not sure I know enough to put them in action.  Here is what I had last night:
```ruby
class LeoEditor < Formula
  desc "The Leo IDE/Outliner/PIM"
  homepage "http://leoeditor.com/"
  url "https://github.com/leo-editor/leo-editor/archive/5.4.1.tar.gz"
  sha256 "2cf0f598aa46e8ced6dd7da0229157e7b523704d0a03604a4da14b715c0a232f"

  depends_on :python if MacOS.version <= :snow_leopard
  depends_on "pyqt"
  depends_on "enchant" => :recommended

  def install
    python_xy = "python2.7"
    # There is a syntax error somewhere on the next line
    # python_site_packages = lib + "#{python_xy}/site-packages"
    python_site_packages.install "leo"
    bin.install ["launchLeo.py", "profileLeo.py"]
    ln_s "#{bin}/launchLeo.py", "#{bin}/leo"
  end

  test do
    # Create, run in and delete a temporary directory.
    if system "python", "-c", "import", "leo"
      onoe "Leo FAILED"
    else
      ohai "Leo OK"
    end
  end
end
```
Some questions for you:

1. How should the formula install Leo in the regular place?
2. How should the formula create the symlink you suggest?
3. Is the test section bogus if leo already is installed on the user's system?

I think we may be close.

**Comment by edreamleo** [comment]
Progress!  Just guessing, I changed:
```ruby
    python_site_packages.install "leo"
```
to:
```ruby
    bin.install "leo"
```
and now the build works:
```
leo-editor$ brew install leo-editor
...
🍺  /usr/local/Cellar/leo-editor/5.4.1: 2,327 files, 27.7M, built in 5 seconds
```
More importantly, the following opens Leo:
```
python /usr/local/Cellar/leo-editor/5.4.1/bin/launchLeo.py
```
So it seems that question 1 is answered.  That still leaves:

2. How should the formula create the symlink you suggest?
    Maybe the symlink exists in a "regular" spot, but I have no idea what this does:

    `ln_s "#{bin}/launchLeo.py", "#{bin}/leo"`
3. Is the test section bogus if leo already is installed on the user's system?

**Comment by edreamleo** [comment]
> Maybe the symlink exists in a "regular" spot

Again, just guessing (I'm a complete MacOS noob), I found launchLeo.py in `/usr/local/bin`  And, hurray!, the following works:
```
python /usr/local/bin/launchLeo.py
```
So now we are down to the last question:

3. Is the test section bogus if leo already is installed on the user's system?

We may be getting close to creating a Tap and issuing a PR.

**Comment by edreamleo** [comment]
@ludwigschwardt Your comments have made everything much clearer.

When running the brew Leo, Leo's log pane shows:
```
load dir: /usr/local/Cellar/leo-editor/5.4.1/bin/leo/core
global config dir: /usr/local/Cellar/leo-editor/5.4.1/bin/leo/config
home dir: /Users/edward
reading settings in /usr/local/Cellar/leo-editor/5.4.1/bin/leo/config/leoSettings.leo
reading settings in /Users/edward/.leo/myLeoSettings.leo
reading settings in /Users/edward/.leo/workbook.leo
```
So `/usr/local/bin/launchLeo.py` actually launches `/usr/local/Cellar/leo-editor/5.4.1/bin`. At last things are starting to make sense.

Many thanks for your help.

**Comment by edreamleo** [comment]
Before I forget, [this homebrew tutorial](http://formalfriday.club/2015/01/05/creating-your-own-homebrew-tap-and-formula.html) has been very helpful. I'll be using it next while I try to create the PR.

The other difference from two years ago is that whenever I have a question I google it.  It's amazing how easy this usually is.

**Comment by ludwigschwardt** [comment]
In my incarnation of the formula I just made ```launchLeo.py``` executable and then added a symlink called ```leo``` so that I could really just run it on the command line as ```leo```. No need to remember the path to it :-)

I still wonder if we can attach a ".app bundle" or some such thing to turn Leo into a proper app which can then be linked via ```brew linkapps```. Then it will appear in /Applications or ~/Applications like all other GUI apps, which is the least surprising thing to a Mac user (although Homebrew is already off the beaten track...).

**Comment by ludwigschwardt** [comment]
A new development...

The `pyqt` formula and soon the whole Qt4 edifice will be shipping off to the Homebrew boneyard... More info in Homebrew PR [#1705](https://github.com/Homebrew/homebrew-core/issues/1705). It appears that Qt4 has reached end-of-life in December 2015, nearly a year ago now, and the writing is on the wall. Qt5 is the only option going forward.

Since `leo` depends on `pyqt` it will have to move over to `pyqt5` in order to get accepted into Homebrew. Not sure how much work that entails, although [this page](http://pyqt.sourceforge.net/Docs/PyQt5/pyqt4_differences.html) claims the effort is "not great".

**Comment by edreamleo** [comment]
On Fri, Nov 18, 2016 at 3:12 AM, Ludwig Schwardt <notifications@github.com>
wrote:

> A new development...
>
> The pyqt formula and soon the whole Qt4 edifice will be shipping off to
> the Homebrew boneyard... More info in Homebrew PR #1705
> <https://github.com/Homebrew/homebrew-core/issues/1705>. It appears that
> Qt4 has reached end-of-life in December 2015, nearly a year ago now, and
> the writing is on the wall. Qt5 is the only option going forward.
>
> Since leo depends on pyqt it will have to move over to pyqt5 in order to
> get accepted into Homebrew. Not sure how much work that entails, although this
> page <http://pyqt.sourceforge.net/Docs/PyQt5/pyqt4_differences.html>
> claims the effort is "not great".
>
​There is no effort at all for Leo.  Leo can use either Qt4 or Qt5.  That's
the purpose of the leo.core.leoQt module.​

Some plugins may not work with Qt4, but that should not affect the homebrew
formula.

Edward
