### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#1062]
Leo hangs with splashscreen and (not responding) message.
build 04796e438 on win10 python 3.7.2

Leo 5.8.1 devel, build 20190102102352, Wed Jan  2 10:23:52 CST 2019
Traceback (most recent call last):
  File "N:\git\leo-editor\launchLeo.py", line 8, in <module>
    leo.core.runLeo.run()
  File "N:\git\leo-editor\leo\core\runLeo.py", line 72, in run
    g.app.loadManager.load(fileName, pymacs)
  File "N:\git\leo-editor\leo\core\leoApp.py", line 2281, in load
    ok = lm.doPostPluginsInit()
  File "N:\git\leo-editor\leo\core\leoApp.py", line 2359, in doPostPluginsInit
    c.redraw()
  File "N:\git\leo-editor\leo\core\leoCommands.py", line 2730, in redraw
    p2 = c.frame.tree.redraw(p)
  File "N:\git\leo-editor\leo\plugins\qt_tree.py", line 290, in full_redraw
    old_r1, old_r2 = frame.getActualRatios()
  File "N:\git\leo-editor\leo\plugins\qt_frame.py", line 2525, in getActualRatios
    r2 = get_ratio(layout.get_secondary_splitter(), 'r2')
  File "N:\git\leo-editor\leo\plugins\qt_frame.py", line 2515, in get_ratio
    f1, f2 = w.sizes()
ValueError: too many values to unpack (expected 2)

**Comment by edreamleo** [comment]
On Sun, Jan 20, 2019 at 1:58 AM LewisNeal <notifications@github.com> wrote:

> Leo hangs with splashscreen and (not responding) message.
> build 04796e4
> <https://github.com/leo-editor/leo-editor/commit/04796e43806febf7d08ef9b5f51f7523650d78b6>
> on win10 python 3.7.2
>
...

> File "N:\git\leo-editor\leo\plugins\qt_frame.py", line 2525, in
> getActualRatios
> r2 = get_ratio(layout.get_secondary_splitter(), 'r2')
> File "N:\git\leo-editor\leo\plugins\qt_frame.py", line 2515, in get_ratio
> f1, f2 = w.sizes()
> ValueError: too many values to unpack (expected 2)
>
Thanks for this report.  I'll fix it today, with an quick fix in minutes.

Edward

**Comment by edreamleo** [comment]
On Sun, Jan 20, 2019 at 6:01 AM Edward K. Ream wrote:

> I'll fix it today, with an quick fix in minutes.

Done at 7f6304223. This may be enough, but I'm not sure.

Neal, were you using a layout with extra panes inserted?

Edward

**Comment by edreamleo** [comment]
> Neal, were you using a layout with extra panes inserted?

Sorry Lewis, I should have used your first name.

Edward

**Comment by edreamleo** [comment]
Rev b5d275b solves this problem at its source: qtFrame.getActualRatios is no longer used and has been moved to the attic.

**Comment by LewisNeal** [comment]
Moot it is....
For the record, the file did not have any extra panes.
