### ISSUE TITLE
Debian install instructions broken

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#1063]
The docs for installing to debian have fallen too far behind and don't work anymore (http://leoeditor.com/installing.html#installing-from-a-debian-package)

**Comment by maphew** [comment]
I've pinged @vivainio to ask if the PPA building  process is something someone else could pick up easily. I expect it might be non-trivial or everyone would be doing it though.

@edreamleo  in the meantime it's probably best to remove the debian-specific section and direct them to installing from source. Inside an `@rst` tree will `@ignore` keep the the node from the html output? Including it's referring points from table of contents etc?

**Comment by edreamleo** [comment]
On Mon, Jan 21, 2019 at 12:39 AM matt wilkie <notifications@github.com>
wrote:

> @edreamleo <https://github.com/edreamleo> in the meantime it's probably
> best to remove the debian-specific section and direct them to installing
> from source. Inside an @rst tree will @ignore keep the the node from the
> html output? Including it's referring points from table of contents etc?
>

Done at b61a1aca4b.  I added an @rst-ignore-tree to the  'Installing Leo on
Linux' node, and moved the 'Installing from sources (Linux)' node out of
that tree.

Edward

**Comment by edreamleo** [comment]
@maphew I'm going to close this issue, because the documentation has been updated.  Feel free to create a new issue for your own work.  Please give it the "pip" label to indicate it's not for me.
