### ISSUE TITLE
refresh-from-disk creates a duplicate node when adding an @file node

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#1065]
- Add a new `@file x` node.
- Do refresh-from-disk.

The original  `@file x` node now has a child  `@file x` node.

**Comment by largo84** [comment]
Thought it was just me. Same thing happens when I open a file (Ctrl-o) that was created by @file somewhere else. It creates an @file node with the full path to the files. Then also a child @file node with just the name of the file (no path). Very odd behavior, I thought. Hadn't had a chance to further investigate before posting as a bug here (you beat me to it).

**Comment by edreamleo** [comment]
On Tue, Jan 22, 2019 at 10:30 AM Rob Keeney <notifications@github.com>
wrote:

> Thought it was just me. Same thing happens when I open a file (Ctrl-o)
> that was created by @file <https://github.com/file> somewhere else. It
> creates an @file <https://github.com/file> node with the full path to the
> files. Then also a child @file <https://github.com/file> node with just
> the name of the file (no path).
>
Thanks for this update.  I didn't know about it.

Edward

**Comment by edreamleo** [comment]
The problem occurs when the gnx in the root node in the .leo file does not match the gnx in the external file. So this is a bug in the `<< handle node_start >>` section fast_at.scan_lines.

**Comment by edreamleo** [comment]
Fixed at rev 448cc77 in the "refresh" branch.

**Comment by edreamleo** [comment]
"refresh" has been merged into "devel"

**Comment by largo84** [comment]
Initial testing suggests this fixed the problem I saw.
Rob...

**Comment by edreamleo** [comment]
On Tue, Jan 22, 2019 at 5:52 PM Rob Keeney <notifications@github.com> wrote:

> Initial testing suggests this fixed the problem I saw.
>
Thanks for the confirmation.  The work has been merged into "devel" for
wider testing.

Edward
