### ISSUE TITLE
Travis-ci to PyPi fails with Invalid or non-existent authentication

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#1066]
https://travis-ci.org/leo-editor/leo-editor/builds/482881258

Relevant bit seems to be _"HTTPError: 403 Client Error: Invalid or non-existent authentication information. for url: https://upload.pypi.org/legacy/"_

```
...snip...
Writing leo-5.8.1b1.post2/setup.cfg
creating dist
Creating tar archive
removing 'leo-5.8.1b1.post2' (and everything under it)
Uploading distributions to https://upload.pypi.org/legacy/
Uploading leo-5.8.1b1.post2.tar.gz
100%|██████████████████████████████████████| 7.15M/7.15M [00:01<00:00, 5.09MB/s]
NOTE: Try --verbose to see response content.
HTTPError: 403 Client Error: Invalid or non-existent authentication information. for url: https://upload.pypi.org/legacy/
leo.egg-info/PKG-INFO already exists, no checkout
leo.egg-info/SOURCES.txt already exists, no checkout
leo.egg-info/dependency_links.txt already exists, no checkout
leo.egg-info/entry_points.txt already exists, no checkout
leo.egg-info/requires.txt already exists, no checkout
leo.egg-info/top_level.txt already exists, no checkout
leo/__init__.pyc already exists, no checkout
leo/core/__init__.pyc already exists, no checkout
leo/core/leoGlobals.pyc already exists, no checkout
leo/core/leoVersion.pyc already exists, no checkout
Could not restore untracked files from stash entry
PyPI upload failed.
failed to deploy
```

**Comment by maphew** [comment]
This might be related to the difficulty I had last August understanding the command line syntax for travis yaml encryption (https://github.com/travis-ci/travis-ci/issues/10051). It's difficult to verify one is encrypting what one thinks they are. Seeking Travis support at https://travis-ci.community/t/deploy-to-pypi-fails-with-authentication-error/1964

**Comment by edreamleo** [comment]
On Tue, Jan 22, 2019 at 11:37 PM matt wilkie <notifications@github.com>
wrote:

> This might be related to the difficulty I had last August understanding
> the command line syntax for travis yaml encryption (
> travis-ci/travis-ci#10051
> <https://github.com/travis-ci/travis-ci/issues/10051>). It's difficult to
> verify one is encrypting what one thinks they are. Seeking Travis support
> at
> https://travis-ci.community/t/deploy-to-pypi-fails-with-authentication-error/1964
>
I've given this the "pip" label to indicated it's related to installation.

Edward

**Comment by maphew** [comment]
No bites in community forum; I emailed Travis support.

**Comment by maphew** [comment]
Finally resolved. Lessons learned:

- only use command line `travis encrypt mypassword --add.deploy` to update the password. Other means such as interactive mode `travis encrypt <enter>` have too many possible failure points and the road to identify them is very long

- be very careful when restoring comments to `.travis.yml` that you don't mess with the secret.
