### ISSUE TITLE
"Refresh from disk" can not refresh from disk

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#1067]
Context menu _"Refresh from disk"_ on `@asis ../../.gitattributes` (in leoDist.leo) does not show the contents of the file on disk. Log window reports "can not refresh from disk". 

_"Edit ... in notepad"_ on same node works.

~~~
Leo Log Window
Leo 5.8.1-b2 devel, build 20190120223507, Sun Jan 20 22:35:07 PST 2019
Git repo info: branch = devel, commit = 8551b9d7a5bb
Python 3.7.1, PyQt version 5.11.2
unchanged: README.md

isPython3: True
read 3 files in 0.07 seconds
read outline in 0.10 seconds
found 5 matches for travis
can not refresh from disk
'@asis ../../.gitattributes'
Edit: notepad "D:/code-maphew/leo-editor/.gitattributes"
can not refresh from disk
'@asis ../../.gitattributes'
Edit: notepad "D:/code-maphew/leo-editor/.gitattributes"
finished
~~~

![image](https://user-images.githubusercontent.com/486200/51635774-7258c680-1f0c-11e9-9495-41fc52371bc4.png)

**Comment by maphew** [comment]
Additional issues:

* UX: I missed the the error report in log for some minutes. If I didn't know with surety the external file was different from body pane I might have carried on blissfully ignorant and overwritten it.
* To test above I changed `.gitattributes` in Leo and saved. The external file **was** updated with Leo's body pane contents, losing the external data.
  * furthermore, Leo's log pane did **not** report the file was written.

~~~
can not refresh from disk
'@asis ../../.gitattributes'
Edit: notepad "D:/code-maphew/leo-editor/.gitattributes"
finished
saved: leoDist.leo
finished
# --- edited @asis node here ---
saved: leoDist.leo
# --- end of log window  ---
~~~

**Comment by edreamleo** [comment]
On Wed, Jan 23, 2019 at 2:51 PM matt wilkie <notifications@github.com>
wrote:

> Context menu *"Refresh from disk"* on @asis ../../.gitattributes (in
> leoDist.leo) does not show the contents of the file on disk. Log window
> reports "can not refresh from disk".
>
> *"Edit ... in notepad"* on same node works.
>
I'm not sure I understand what the issue is.  Are you saying that the log
message is not sufficient to avoid possible data loss?  Leo could put up a
dialog, but people are pretty good at ignoring those too.

Edward

**Comment by maphew** [comment]
The log message is a secondary but real issue (but I don't know that anything meaningful can be done about it, as you say we're good at ignoring things that get in the way).

The issue is why does refresh from disk fail at all? "Edit in notepad" on same node works, so the path is correct and the file exists.

**Comment by edreamleo** [comment]
Fixed at rev 87cc9fc.

**Comment by maphew** [comment]
thank you :)

**Comment by edreamleo** [comment]
You're welcome.

On 2/2/19, matt wilkie <notifications@github.com> wrote:
> thank you :)
>
> --
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/leo-editor/leo-editor/issues/1067#issuecomment-460007330


-- 
------------------------------------------------------------------------------------------
Edward K. Ream: edreamleo@gmail.com Leo: http://leoeditor.com/
------------------------------------------------------------------------------------------
