### ISSUE TITLE
Importing markdown to an @clean file, leaves tree with orphan nodes

### ISSUE THREAD

**Issue by vitalije** [leo-editor/leo-editor#1069]
I have noticed that importing README.md or other md files using c.recursiveImport creates tree without at-others directive in the top level node. After trying to save the outline Leo reports a lot of orphan nodes.

It also drops all headings from the file. Importing as `kind="clean"` produces tree like at-auto, so when later user saves outline, all headings are lost from the external file.

**Comment by edreamleo** [comment]
Markdown is a special case, best handled with `@auto-md`.  Expecting `@clean` to work is not reasonable.  In fact, the markdown importer and writer plugins are working correctly.

My suggestion:  Create `@auto-md` nodes by hand, then use refresh-from-disk to update.  Alternatively, create `@auto` nodes using a recursive import script, save the file _without_ saving, and then reload.
