### ISSUE TITLE
Command line `leo newfile.leo` yields unexpected headline name

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#1070]
On the command line when passing a filename that doesn't exist the new headline that's created is the name of the file. It's not a big deal but is a little disconcerting because it's different from what happens with _"File >> New"_  and raises question as to what's going to happen when saved. (Am I going to get two leo files?) 

**`leo newfile.leo`** creates an empty file with a headline called "newfile.leo"
![image](https://user-images.githubusercontent.com/486200/51719390-2a19d100-1ffe-11e9-86d5-edf65112bf55.png)

**File >> New** creates an empty file with a headline called "NewHeadline"
![image](https://user-images.githubusercontent.com/486200/51719330-e757f900-1ffd-11e9-915b-9f7a3976266b.png)

I could see logic in using the first part of the supplied name, `newfile` instead of `NewHeadline`, but would drop the file extension regardless.

_(bonus points: apply smart word splitting and Title Case to both cmd filename and file>>new, so `New File` and `New Headline`)_

**Comment by edreamleo** [comment]
Fixed at rev 1cfd7ba.
