### ISSUE TITLE
@auto fails in org-file when headline has more then one leading whitespace

### ISSUE THREAD

**Issue by scriptmode** [leo-editor/leo-editor#1074]
When using "@auto test.org" where test.org has this content "*  Test", a "@auto failed: test.org" get's thrown and the node is on @ignore. In the example there are two whitespaces after the *, which seems to create the problem. Works fine with just one whitespace.

In the original file the error was more verbose, maybe this helps finding the origin:
('\n===== PERFECT IMPORT FAILED =====', u'Log.org')
len(s1): 94 len(s2): 94
first mismatched line: 73
s1...
*   73 *****  15.07.2018
s2...
*   73 ***** 15.07.2018

**Comment by edreamleo** [comment]
Fixed at rev a4b297c.
