### ISSUE TITLE
Refresh / audit MANIFEST.in excludes and includes

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#1077]
- [x] carefully compare results of `pip install leo` in a fresh environment with code repository and ensure:
  - [x] everything that can be left out is left out
  - [ ] everything that should be included is in
- [ ] Update LeoDocs.leo accordingly (_"PyPi vs Github install"_, doc-update branch)

Related to #603 Missing files when installing with pip

----
_I'll be updating this post as I study, so files will move from one suggestion to another. I've created the branch [`clean-up-root`](https://github.com/leo-editor/leo-editor/tree/clean-up-root) for carrying out, testing and discussing the suggestions._

_**2020-03-16**: the easy and medium stuff has been dealt with and merged into `devel` with PR#1432. Momentum on this project has slowed and it's now on a low simmer. Accordingle the milestone has been removed._

## Root Folder
_Checked items mean they've been verified as belonging in that category._

### Must stay for packaging or external tools
_Relied on by setuptools, pip, NSIS, etc. for distribution and re-use; git for development; etc. We can't change these without changing upstream, which means never._
- [ ] `git-manifest.txt`
- [ ] `Makefile`
- [ ] `MANIFEST.in`
- [x] `pyproject.toml`
- [x] `README.md`
- [x] `setup.py`
- [x] `setup.cfg`
- [x] `.travis.yml`
- [x] `.gitattributes`
- [x] `.gitconfig`
- [x] `.gitignore`

### Good in root :
_Files which must kept, but maybe could live somewhere else._
- [x] `branches.md`
- [x] `LICENSE`
- [x] `PKG-INFO.TXT`

### Must stay for Leo
_Important parts of Leo and/or it's dev scripts rely on these living here. Can't be moved without careful internal cross referencing and extensive testing._
- [x] `launchLeo.py` - when all else fails fallback launcher (e.g. leo.exe or batch doesn't work)
- [x] `launchLeo-console.py` - as previous, but for console mode
- [ ] `flake8-leo.py` - 
- [ ] `profileLeo.py` - 
- [ ] `pyflakes-leo.py` - 
- [ ] `pylint-leo.py` - 
- [ ] `leo-commands.cfg` - 
- [ ] `leo-core.cfg` - 
- [ ] `leo-plugins.cfg` - 

### Referred to externally (leoeditor.com)
_These published to website root, but don't need to be in src code root._

Moved to `./tools/webroot`

- [x] `do-leo.php` -  only referenced from `load-leo.html`
- [x] `leo_to_html.xsl` - used by do-leo.
- [x] `load-leo.html` - ref from LeoDocs & LeoReleaseNotes, but only as information to it's published location on web. Haven't found out how it get's pushed **to** the website yet.
- [x] `xslt-test.leo` - ref in release_notest.txt, doesn't appear to be used by anything directly

Identifying references. Other side of pipe is to ignore .git folder:
`findstr /i /s "load-leo.html" * | findstr /v "^.git"`

### Candidates to move

- [ ] `ekr-spellpyx.txt` - 
- [x] `leo-editor.desktop` - mv to `./eo/dist`, pending feedback from Chris
- [ ] `run_pytest_tests.py` - mv to `./test`, but needs code change and testing 
- [ ] `run_travis_unit_tests.py` - mv to `./test`, but needs code change and testing 

### Delete
- [x] `About leo.exe.TXT` - is just wrong now.
- [x] `INSTALL.TXT` - largely out of date; I doubt anyone installs without refering to web page instead
- [x] `Makefile` - for bzr checkout and build, not used for years, no discussion needed
- [x] `optional-tools.txt` - these tools not readily available or applicable anymore
- [x] `stderr.txt` - 0 bytes, no discussion needed
- [x] `_config.yml` - for publishing to GitHub pages, should be in different branch, fork, or repo

## `Manifest.in`, `git-manifest.txt`
_After all the above has been worked out we can look at manifests._
### Verify must stay
_...TBD..._
### Delete
_...TBD..._

**Comment by maphew** [comment]
Current list of folders in `leo-editor/leo` that will not exist in a `site-packages/leo` :
~~~
./test
./doc/html
~~~
_Left out for space conservation reasons. They're not needed by normal users. Html are on the website and can be regenerated locally by Leo if desired._

Files:
~~~
./plugins/aspell.pyd
~~~
_I don't think aspell is left out on purpose(?)_

**Comment by maphew** [comment]
_I'll be updating this post as I study, so files will move from one suggestion to another._

Must stay in root folder:
~~~
git-manifest.txt
launchLeo-console.py
launchLeo.py
Makefile
MANIFEST.in
pyproject.toml
README.md
setup.py
setup.cfg
.travis.yml
.gitattributes
.gitconfig
.gitignore
~~~

Are good in root:
~~~
branches.md
INSTALL.TXT
LICENSE
PKG-INFO.TXT
~~~

Candidates for moving (tool/script adjustment needed for some. The scale of that effort might negate the suggestion.):
~~~
do-leo.php
ekr-spellpyx.txt
flake8-leo.py
leo-commands.cfg
leo-core.cfg
leo-editor.desktop
leo-plugins.cfg
leo_to_html.xsl
load-leo.html
profileLeo.py
pyflakes-leo.py
pylint-leo.py
run_pytest_tests.py
run_travis_unit_tests.py
xslt-test.leo
~~~

Delete?
~~~
About leo.exe.TXT
optional-tools.txt
stderr.txt
.viminfo
_config.yml
~~~

**Comment by edreamleo** [comment]
@maphew I'll make my comments here, if you don't mind.

**Deleting files**: I'm good with deleting all the files in the "delete" list.

**Moving files**

Please do not move the following files. I have scripts that refer to them in their present locations:

flake8-leo.py
profileLeo.py 
pyflakes-leo.py
pylint-leo.py

The following files are for testing.  Afaik, you are responsible for them. Put them where you like:

run_pytest_tests.py
run_travis_unit_tests.py

I am good with moving any .cfg file.  I don't know or have forgotten why they exist at all, let alone in their present location.

profileLeo.py This 


leo-editor.desktop
leo_to_html.xsl
load-leo.html



xslt-test.leo -

do-leo.php -

xslt-test.leo

**Comment by maphew** [comment]
Comments here are fine. Thanks for highlighting files needing hyper awareness. I've re-ordered the lists and added more categories.  Thank you for catching the milestone; I have no intention of moving quickly as I recognize it will take time to backtrack references, on the order of weeks to months. When I've done all the simple stuff like the deletes and easy-moves I'll issue a PR (from a sub-branch?).

**Comment by edreamleo** [comment]
@maphew Good work, and you're welcome :-)

**Comment by maphew** [comment]
@technatica does `leo-editor.desktop` need to live in project root for Snap? 
I'm thinking it's logically part of `./leo/dist`

**Comment by technatica** [comment]
You can move it to /leo/dist

I am still taking a break from snap. :-)

Chris

**Comment by maphew** [comment]
@edreamleo it looks to me like the `leo/dist/leoDist.leo#Startup-->Installer/Distribution bugs & to-do` node can be deleted.

**Comment by edreamleo** [comment]
@maphew Good catch.  Removed at c552e0a in devel.

**Comment by maphew** [comment]
9ca48970c moves the 4 website files into a new folder, `tools/webroot`, with corresponding note added to Distribution checklist. I think that's the end of the easy ones.

In my head, the other root files not related to packaging and distribution would go to `/tools` also. Remains to be seen if that's practical.

**Comment by edreamleo** [comment]
@maphew What's the status of this? I have cleared the milestone.

**Comment by maphew** [comment]
My progress on this has slowed down and it's appropriate to clear the milestone, thanks. I'll update the top post.

**Comment by maphew** [comment]
Putting to sleep until I or someone else has time and initiative to finish it.
