### ISSUE TITLE
Spellcheck library replacement (pyenchant not maintained)

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#1080]
[PyEnchant](https://github.com/rfk/pyenchant) is officially unmaintained  (Side note: the author's [signing off notice](https://rfk.id.au/blog/entry/archiving-open-source-projects/) is a worth a read for it's openness and honesty.) 

Possible replacements I've seen mentioned:

- Pyhunspell - https://github.com/blatinier/pyhunspell
- Pyspellchecker - https://github.com/barrust/pyspellchecker

This issue created because pyenchant is one of the libraries I disabled for pip because of inconsistent platform availability. (Meaning: I'm not personally lobbying to change Leo's spell check engine.)

**Comment by JohnWang1023** [comment]
There seem to be a new maintainer for pyenchant. https://github.com/pyenchant/pyenchant/issues/129 https://github.com/pyenchant/pyenchant/issues/140

**Comment by edreamleo** [comment]
@JohnWang1023 Thanks.  That's good to know.

**Comment by aks2161989** [comment]
I second this. Pyenchant also fails to install on Windows with Python 64 bit.

**Comment by maphew** [comment]
I assigned myself to add Windows-specific enabling of pyenchant via pip install. 

The readme says other platforms need to install pyenchant using the OS package manager. I'm not sure what the best way to handle that might be. A note in the docs and emit a message in the console maybe?

And is this a Core or Plugin feature?

**Comment by edreamleo** [comment]
@maphew It depends on your point of view. The LeoQtSpellTab class, in leo/plugins/qt_frame.py, contains the relevant code. When using the Qt gui, this file is, in essence, part of Leo's core. But it could also be called a plugin, because spell checking is only supported in the Qt gui.

**Comment by maphew** [comment]
Hmm, okay. I will add or freshen the notes for all platfroms to install pyenchant seperately.

**Comment by maphew** [comment]
Closing this by adding fixing the Pyenchant link in the Docs. I only found 2 relevant places to change text (2efd24e).

---
Windows English users: `pip install pyenchant` is all that's needed. For languages other than English you need to compile the _enchant C library_ with MingW (see [Pyenchant install docs](http://pyenchant.github.io/pyenchant/install.html)).

Other platforms: install _libenchant_ using `apt` or `yum` or whatever followed by `pip install pyenchant`.

---
I elected not to add these details to Leo docs because they'll inevitably drift out of date and it's better to go to the source anyway (but this note is here to provide a trail).

When working `show-spell-info` in Leo's `Alt-X` command buffer log pane shows something like:

~~~
pyenchant spell checker
user dictionary:   C:/Users/matt/.leo/spellpyx.txt
main dictionaries: en_BW, en_AU, en_BZ, en_GB, en_JM, en_DK, en_HK, en_GH, en_US, en_ZA, en_ZW, en_SG, en_NZ, en_BS, en_AG, en_PH, en_IE, en_NA, en_TT, en_IN, en_NG, en_CA
~~~
