### ISSUE TITLE
@asis internal data overwriting newer external data

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#1081]
#1347 supersedes this issue.  I am closing this issue because it contains too much noise.

Leo is not recognizing changes in `@asis` files made externally by git and overwrites them with it's internal representation.

Recipe that reliably reproduces behaviour on my machine:

1. Ensure git repo is up to date and checkout current devel branch as it exists on Github.
2. Open .leo file, make a trivial edit in a node outside of @ file, @ asis, ... (add and delete one space), 
3. Save (`ctrl-s`) and Exit.
4. Examine file system: 
   - external files were changed
   - the .leo file was changed in a different node from the add-delete-character node

```
# Exit Leo if running
git fetch
git checkout origin/devel
leo leo\dist\leoDist.leo
   # add-remove a character, then save, and exit Leo
git status
```
```
> git status
HEAD detached at origin/devel
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   .gitattributes
        modified:   .travis.yml
        modified:   leo/dist/leoDist.leo

no changes added to commit (use "git add" and/or "git commit -a")
```

_**Edit 2019-02-10**: Recipe updated with extra details. No change in results observed._
_**Edit 2019-02-12**: Removed chatty preamble and put in executive summary._ 

----

Log window shows 2 external files written.

![image](https://user-images.githubusercontent.com/486200/52530753-864b4900-2cbe-11e9-96a3-086485293248.png)

Inspecting one of the files simultaneously in Leo and file-system after git reset*. Leo's content is different from external. Nothing has been done in Leo since opening other navigation.

_*  using Git Extensions and [R]esetting each modified file. I don't know if this differs from `git reset` on commandline_

![image](https://user-images.githubusercontent.com/486200/52530620-1c7e6f80-2cbd-11e9-84d8-e709b52e4007.png)

The .leo file is changed in a place untouched by me in this session. Not even looked at in navigation.

![image](https://user-images.githubusercontent.com/486200/52530771-125d7080-2cbf-11e9-82cc-73b471efadea.png)

**Comment by maphew** [comment]
This looks intimately related to **"can't refresh from disk" #1067**  from a few weeks ago.
Strongly reminds me of  **@ clean parsing error: some functions are empty! #973** 
And makes me wonder about  **@ auto re-asserts over @ file #580**

**Comment by maphew** [comment]
Forgot to include log:
```
Leo Log Window
Leo 5.8.1-b2 devel, build 20190209161014, Sat Feb  9 16:10:14 PST 2019
Git repo info: branch = devel, commit = 599dbffa1400
Python 3.6.2, PyQt version 5.9.3
Windows 10 AMD64 (build 10.0.17134) SP0
isPython3: True
current dir: C:/Users/mattw/code/leo-editor
load dir: C:/users/mattw/code/leo-editor/leo/core
global config dir: C:/users/mattw/code/leo-editor/leo/config
home dir: C:/Users/mattw/code/leo-editor
reading settings in C:/users/mattw/code/leo-editor/leo/config/leoSettings.leo
reading settings in C:/Users/mattw/code/leo-editor/leo/dist/leoDist.leo
reading settings in C:/Users/mattw/code/leo-editor/leo/dist/leoDist.leo
read 5 files in 0.09 seconds
read outline in 0.17 seconds

wrote recent file: C:/Users/mattw/code/leo-editor/.leo/.leoRecentFiles.txt
wrote: .gitattributes
unchanged: INSTALL.TXT
wrote: .travis.yml
unchanged: LICENSE
unchanged: PKG-INFO.TXT
unchanged: README.md
unchanged: About leo.exe.TXT
unchanged: setup.py
unchanged: setup.cfg
unchanged: pyproject.toml
unchanged: optional-tools.txt
finished
saved: leoDist.leo
```

**Comment by edreamleo** [comment]
Hmm.  Would you agree that Leo is not recognizing changes made externally by git?  If so, the workaround is to quit Leo before using git to change files.

**Comment by maphew** [comment]
It happens between Leo sessions, ie: _Exit leo >> git reset >> start Leo, edit, save, exit >> inspect: data lost_.

I tried moving HOME `.leo` out of the way, creating a new profile, and then repeating the recipe above: bang! data is still overwritten. I guess this proves the old data isn't being pulled out of my personal leo profile somehow.

Leo log:

```
Leo Log Window
Leo 5.8.1-b2 devel, build 20190210153938, Sun Feb 10 15:39:38 EST 2019
Git repo info: branch = None, commit = b6854ab
Python 3.6.2, PyQt version 5.9.3
Windows 10 AMD64 (build 10.0.17134) SP0
isPython3: True
created directory: C:/Users/mattw/.leo
leoID='mhw-debug-1081'
.leoID.txt created in C:/Users/mattw/.leo
current dir: C:/Users/mattw/code/leo-editor
load dir: C:/users/mattw/code/leo-editor/leo/core
global config dir: C:/users/mattw/code/leo-editor/leo/config
home dir: C:/Users/mattw
reading settings in C:/users/mattw/code/leo-editor/leo/config/leoSettings.leo
reading settings in C:/Users/mattw/code/leo-editor/leo/dist/leoDist.leo
reading settings in C:/Users/mattw/code/leo-editor/leo/dist/leoDist.leo
created: C:/Users/mattw/.leo/spellpyx.txt
read 5 files in 0.14 seconds
read outline in 0.21 seconds

creating: C:/Users/mattw/.leo/.leoRecentFiles.txt
wrote: .gitattributes
unchanged: INSTALL.TXT
wrote: .travis.yml
unchanged: LICENSE
unchanged: PKG-INFO.TXT
unchanged: README.md
unchanged: About leo.exe.TXT
unchanged: setup.py
unchanged: setup.cfg
unchanged: pyproject.toml
unchanged: optional-tools.txt
finished
saved: leoDist.leo
```
Command shell:

```
(leo-dev) matt@ENV-SURFACE-MHW C:\Users\mattw\code\leo-editor
> leo-messages leo\dist\leoDist.leo

created directory: C:/Users/mattw/.leo
leoID='mhw-debug-1081'
.leoID.txt created in C:/Users/mattw/.leo
Leo 5.8.1-b2 devel, build 20190210153938, Sun Feb 10 15:39:38 EST 2019
created: C:/Users/mattw/.leo/spellpyx.txt
creating: C:/Users/mattw/.leo/.leoRecentFiles.txt
wrote recent file: C:/Users/mattw/.leo/.leoRecentFiles.txt
```

Close Leo.


```
(leo-dev) matt@ENV-SURFACE-MHW C:\Users\mattw\code\leo-editor
> git status
HEAD detached at origin/devel
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   .gitattributes
        modified:   .travis.yml
        modified:   leo/dist/leoDist.leo
```
 
This was done in a current devel checkout:
```
> git log -1
commit b6854ab2d25206ecf8c413d0e5b181bfb780604d (HEAD, origin/devel)
Author: Edward K. Ream <edreamleo@gmail.com>
Date:   Sun Feb 10 15:39:37 2019 -0500

    Investigated #290.  Made only style changes.

    Leo build: 20190210153938
```

**Comment by maphew** [comment]
Ahhh, my ignorance of how data are stored led me astray and caused a lot of extra traffic in this thread. The old data is in the .leo file itself. I thought it was outside, in `%HOME%\.leo\{some_cache}`. Sorry the noise.  I'll edit the post and delete the noise after I know you've read this.

With that revised understanding:

> Hmm. Would you agree that Leo is not recognizing changes made externally by git? [...]

Yes.

How does Leo track time of internal data vs external? The time stamp in the .leo `<t ...>` xml element is YEARS different from the external file timestamp.

If we narrow down to the smallest change to easily find, it's the `MANIFEST.in` line in `.gitattributes`. That's in node: `leo/dist/leoDist.leo#Distribution files-->@asis ../../.gitattributes`

XML element is dated 2014:
```
<t tx="ekr.20141016105045.2119"># .gitattributes file for Leo distribution
[...]
MANIFEST.in                     export-ignore
[...]
leo/core/commit_timestamp.json merge=ours
</t>
```

File is dated 2019:
```
> dir .gitattributes
[...]
02/10/2019  06:12 PM             1,067 .gitattributes
```

**Comment by edreamleo** [comment]
@maphew Glad to hear you are on the right track.  Remember that Leo now only caches non-essential data like marks, expanded "bits" and the selected position.

**Comment by edreamleo** [comment]
I am going to close this.  Please reopen if necessary.

**Comment by maphew** [comment]
I'm afraid my zeal to include as much information as possible in order to help solve the problem has only succeeded in obscuring it up entirely! It's still a problem, and that problem is:

Leo is overwriting `@asis` external files even though the external content is newer than the internal content.

There is no warning to the user about the mismatch and no chance to choose an alternate action.

**Comment by edreamleo** [comment]
**Summary**:

1. It is *not possible* to update `@asis` and `@nosent` nodes from changes to external files.  Indeed, such files have no sentinels, and so can not possibly carry any outline-related data.  There is no way to change this fact.  Leo's docs should be updated to emphasize what is going on.

2. The on-idle code in leoExternalFiles.py should warn when `@asis` and `@nosent` nodes change outside of Leo.

**Comment by edreamleo** [comment]
The warning is all that can be done.  Please reopen only if there are new bugs to report.

**Comment by maphew** [comment]
Ok, that's very good to know. Thank you.

**Comment by edreamleo** [comment]
@maphew You're welcome.

**Comment by maphew** [comment]
I did not get this warning today _Leo 6.1-devel, devel branch, build f6e16c37c0 2019-09-06 15:21:50 -0500_

**Recipe:**

```
git reset --hard f6e16c37c02afc1a40d1c1e2c17bd138e9dbf6d5
leo leo\dist\leoDist.leo
```
Change 1 line in travis.yml and save.
There is popup warning:

> **Overwrite existing file?**
>
> @asis C:/Users/mattw/code/leo-editor/.travis.yml
> 
> already exists.
> Overwrite this file?
>
> [Cancel (No To All)]   [Yes]   [Yes To All]   [No]   

But not a corresponding _"Warning: Because the external file contains no sentinels, [such] trees can not be updated from changes made outside of Leo. If you want this capability, use @clean instead."_

If I [save] over a dozen lines in .travis.yml are changed, including line deletions.

Complete Log window for the session:
```
Leo Log Window
Leo 6.1-devel, devel branch, build f6e16c37c0
2019-09-06 15:21:50 -0500
Python 3.6.2, PyQt version 5.12.3
Windows 10 AMD64 (build 10.0.17134) SP0
current dir: C:/Users/mattw/code/leo-editor
load dir: C:/users/mattw/code/leo-editor/leo/core
global config dir: C:/users/mattw/code/leo-editor/leo/config
home dir: C:/Users/mattw
reading settings in C:/users/mattw/code/leo-editor/leo/config/leoSettings.leo
reading settings in C:/Users/mattw/.leo/myLeoSettings.leo
reading settings in C:/Users/mattw/code/leo-editor/leo/dist/leoDist.leo
reading settings in C:/Users/mattw/code/leo-editor/leo/dist/leoDist.leo
read 4 files in 0.10 seconds
read outline in 0.26 seconds

wrote recent file: C:/Users/mattw/.leo/.leoRecentFiles.txt
wrote: .travis.yml
finished
saved: leoDist.leo
```

Console messages for the session:
```
> leo-m leo\dist\leoDist.leo

--global-docks: False

Leo 6.1-devel, devel branch, build f6e16c37c0
2019-09-06 15:21:50 -0500
wrote recent file: C:/Users/mattw/.leo/.leoRecentFiles.txt
```

I think it's too easy for \@asis to make unwanted changes, changes that are unseen if you're not using version control. Now that we have \@clean maybe it should be removed from Leo?

**Comment by edreamleo** [comment]
@maphew `@asis` has limited utility, but imo it should not be removed.  It does things that `@clean` can't.  Not sure why you didn't get a warning. Perhaps the check is only made for .py files...

**Comment by edreamleo** [comment]
@maphew Your workaround is obvious: use `@clean` and just forget about `@asis` and `@nosent`.

**Comment by maphew** [comment]
Yeah, I'm not going to use @`asis` and `@nosent` anymore. Note that the scenario which prompted re-opening this issue came from using leoDist.leo which I've contributed to but didn't create. It's `@asis` nodes predated my involvement.

I'm concerned that `@asis` and `@nosent` are dangerous and should be harder to get to; perhaps like a default setting `@bool enable-asis=False`.  [Later] After re-reading the [`@asis` reference](https://leoeditor.com/directives.html#asis-path) I see that it's clear it's a special circumstance directive, although the why is (perhaps unavoidably) hard to absorb without using it.

A safer-than-present response that doesn't involve a new setting might be a confirmation dialog:

> "Warning: the external file {`filename.ext}` is newer than the leo node `@asis {headline}`.
> Read up on _safe `@asis` use_ {doc link}. 
> Overwrite anyway? [Yes] [No]"

I'll try tackle this if you're okay with that.

**Comment by edreamleo** [comment]
@maphew Please go ahead.  I'll leave this scheduled for 6.1 for now, but it can move to 6.2 if you like.

**Comment by maphew** [comment]
Ok, thanks. I'm going to try finish menu and desktop links first.
