### ISSUE TITLE
yaml syntax coloring problems

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#1082]
From [this post](https://groups.google.com/forum/#!topic/leo-editor/E4Nt-n_iSmA):

1. Set a node to @language yaml

2. Enter some YAML items.

3. The syntax coloring works only if there is at least one white space before the descriptor (perhaps the wrong word). If no white space, the descriptor is normal color; with white space the descriptor is colored.

I tried reading and deciphering the modes file for the yaml language, but my lack of Python fluency fails me here as I can't figure out what's going on. There's a comment from Edward (EKR) at lines 143-4 which are possible clues, but no indication if this is fixable, and if so, how.

**Comment by largo84** [comment]
Thanks, Edward.
I think the correct word is 'key' instead of 'descriptor' (as in key:value pair). I should have known that when I posted the original message.

**Comment by largo84** [comment]
Just updated from devel branch and confirmed that the yaml.py was updated. However, I still see the previous behavior. See screenshot.

![190211 yaml](https://user-images.githubusercontent.com/9388145/52573246-bb06ef80-2de7-11e9-89e7-95df20bd19f9.PNG)

**Comment by largo84** [comment]
Reopening this issue. However, it's likely that perhaps I'm missing something that I should be doing.

**Comment by edreamleo** [comment]
Fixed at rev 33691f in devel.
