### ISSUE TITLE
@auto fails in org-file when headline has tailing whitespace

### ISSUE THREAD

**Issue by scriptmode** [leo-editor/leo-editor#1087]
Node with "@auto Test.org" where Test.org is

> \* Test1\<whitespace\> 
> \* Test2

leads to

> ('\n===== PERFECT IMPORT FAILED =====', u'Test.org')
> len(s1): 2 len(s2): 2
> first mismatched line: 1
> s1...
> *    1 * Test1 
>      2 * Test2
> 
> s2...
> *    1 * Test1
>      2 * Test2
> 

Reason is that Test1 has an whitespace at the end of the line (which seems to be filtered by Github too, so I wrote it out). leo/plugins/importers/org.py has several str.strip() which seems to modify the parsed text. The content will still be imported, but an @ignore will be added and leo complains on export, making unidirectional usage pointless.

Note: github seems to filter the tailing whitespace in te

**Comment by edreamleo** [comment]
Fixed at e0f1ab6.
