### ISSUE TITLE
command line--script relative path is relative to `leo/core` instead of file-system

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#1090]
When running Leo with the `--script=../some/path/here.py` command line parameter Leo interprets the path as relative to Leo's core directory instead of the file-system current directory.

```
(leo-dev) matt@ENV-SURFACE-MHW C:\Users\mattw\code\leo-editor
> python launchLeo.py --script .\leo\scripts\win-unregister-leo.leox

script not found:C:/users/mattw/code/leo-editor/leo/core/leo/scripts/win-unregister-leo.leox
```

Note in the error message path the fragment `leo/core/leo/scripts` should be just `leo/scripts`

**Comment by maphew** [comment]
thanks!

**Comment by edreamleo** [comment]
On Tue, Apr 2, 2019 at 2:44 PM matt wilkie <notifications@github.com> wrote:

> thanks!
>
You're welcome.

Edward
