### ISSUE TITLE
Add pyzo features to Leo

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#1093]
The **pyzo_in_leo plugin** embeds [pyzo](https://pyzo.org/) within Leo!

[This repo](https://github.com/edreamleo/pyzo) contains pyzo.leo, EKR's private study outline for all of pyzo's sources.  pyzo.leo contains "live" `@clean` nodes for all pyzo files.

The pyzo_start method and its helpers show the proper way to init all of pyzo within Leo itself.  This work is ready for testing.

**Later**

- #1384: Inject a two-way comm bridge into pyzo.

**Won't do**

There would be no great advantage to having pyzo open files in Leo outlines.
Indeed, opening files in a flat editor view is the gist of #1279.

So the following will probably never happen:
- Have the pyzo file browser understand .leo files.
- Integrate pyzo's debugger with Leo.

**History**

- March 28:  Work started at rev d9f7bc359db
- April 10: An initial prototype declared complete.
- #1150 (docks) started May 5, 2019 and completed May 29.
- May 31: The pyzo_in_leo plugin will use *copies* of all pyzo code.
  These copies eventually migrated to the leo/plugins/pyzo folder.
- August 16: I see [the proper way to handle pyzo's imports](https://groups.google.com/d/msg/leo-editor/Dz_KECGA4Y4/YbLArlwsDQAJ).
  - "import pyzo" is safe, provided the code never calls pyzo.start.
  - The proper way to init pyzo code is to use *exactly* the same order as in pyzo.start.
- August 17: [Leo must use singleton docks](https://groups.google.com/d/msg/leo-editor/99t3D1cJ0ig/EZQaMh1VDQAJ). #1289.
- September 30: pyzo's gui fully integrated with Leo.
- October 8: use find_exec to discover the external version of pyzo.
  Remove leo/plugins/pyzo directory.

**Comment by edreamleo** [comment]
Completed at dd9d643 in devel.

**Comment by edreamleo** [comment]
Reopening: the plugin doesn't save shell info.

**Comment by edreamleo** [comment]
Rev bc14ec1 just contains small tweaks.

Leo's configs are slightly different from pyzo's, but in practice that shouldn't matter.  I'm going to close this issue again.

**Comment by aihuasxy** [comment]
where is the document?

**Comment by edreamleo** [comment]
The documents are in the [various issues](https://github.com/leo-editor/leo-editor/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+milestone%3A6.2+label%3Apyzo), including this one.
