### ISSUE TITLE
py2 compatible Windows file-type registration settings

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#1099]
sub-task to #1012, do what's needed to make the Windows (un)registration scripts work on python 2.7

**Comment by maphew** [comment]
I don't have the appetite for ensuring py2 compatibility. The effects of the scripts can be done with stock Windows command lines, which are in the Docs (http://leoeditor.com/installing.html#creating-windows-file-associations, Method 2).
If there's demand we can re-open.

**Comment by edreamleo** [comment]
On Fri, May 17, 2019 at 12:40 AM matt wilkie <notifications@github.com>
wrote:

> I don't have the appetite for ensuring py2 compatibility. The effects of
> the scripts can be done with stock Windows command lines, which are in the
> Docs (
> http://leoeditor.com/installing.html#creating-windows-file-associations,
> Method 2).
> If there's demand we can re-open.
>

Py2 is dead.  Don't spend another minute on it.

Edward

**Comment by edreamleo** [comment]
On Fri, May 17, 2019 at 5:15 AM Edward K. Ream <edreamleo@gmail.com> wrote:

Py2 is dead.  Don't spend another minute on it.
>

But feel free to remove any py2 related cruft in the distribution and
testing chain.

Edward
