### ISSUE TITLE
AttributeError: 'LeoQtLog' object has no attribute 'createCanvas'

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#1101]
Leo Log Window
Leo 5.8.1-b2 devel, build 20190227233831, Wed Feb 27 23:38:31 PST 2019
Git repo info: branch = devel, commit = b2a88971f4fd
Python 3.6.7, PyQt version 5.11.2
linux
isPython3: True

***

http://leoeditor.com/scripting-miscellany.html

    log = c.frame.log ; tag = 'my-canvas'
    w = log.canvasDict.get(tag)
    if not w:
        w = log.createCanvas(tag)
        w.configure(bg='yellow')
    log.selectTab(tag)

exception executing script
AttributeError: 'LeoQtLog' object has no attribute 'createCanvas'
\--------------------
   line 5: if not w:
\* line 6:     w = log.createCanvas(tag)
   line 7:     w.configure(bg='yellow')
   line 8: log.selectTab(tag)

**Comment by edreamleo** [comment]
Fixed at b7df6755.  The new code is:
```python
from leo.core.leoQt import QtWidgets
log = c.frame.log
w = log.createTab('My Tab', createText=False, widget=QtWidgets.QFrame())
log.selectTab('My Tab')
```
