### ISSUE TITLE
Cannot run Leo: `ValueError: PyCapsule_GetPointer called with incorrect name`

### ISSUE THREAD

**Issue by nocibambi** [leo-editor/leo-editor#1106]
Hi, I have been reading about Leo and would like to try it out because it seems to be a great concept.

However, I have some issues with running. Whenever I try to run it, I got the following error message:

```shell
$ python launchLeo.py
Traceback (most recent call last):
  File "launchLeo.py", line 7, in <module>
    import leo.core.runLeo
  File "/home/andras/leo_editor/leo/core/runLeo.py", line 27, in <module>
    leoGlobals.app = leoApp.LeoApp()
  File "/home/andras/leo_editor/leo/core/leoApp.py", line 336, in __init__
    import leo.core.leoFrame as leoFrame
  File "/home/andras/leo_editor/leo/core/leoFrame.py", line 13, in <module>
    import leo.core.leoColorizer as leoColorizer
  File "/home/andras/leo_editor/leo/core/leoColorizer.py", line 9, in <module>
    from leo.core.leoQt import Qsci, QtGui, QtWidgets # isQt5, QtCore
  File "/home/andras/leo_editor/leo/core/leoQt.py", line 127, in <module>
    import PyQt5.QtWebKitWidgets as QtWebKitWidgets
ValueError: PyCapsule_GetPointer called with incorrect name
Segmentation fault (core dumped)
```

Following up on the error message, I tried to implemented the configuration instructions [here][1], but that did not help.

Based on posts about similar issues, I suspected that it might be a problem between pip and conda versions of pyqt. I have little knowledge of these issues so what I tried to do is to create a separate conda environment just for leo with the following commands:

```shell
$ conda create -n leo
$ source activate leo
$ pip install leo
```
However this produced the very same error message.

Following that I tried to install leo (within the same environment) with python, but it required `setuptools`:
```shell
$ sudo python setup.py install
Traceback (most recent call last):
  File "setup.py", line 12, in <module>
    from setuptools import setup, find_packages # Always prefer setuptools over distutils
ImportError: No module named setuptools
```
I installed setuptools with `conda install setuptools` but it still does not find(!) setuptools...

Well, any suggestions? :)

p.s. I am on Ubuntu 18.04

[1]: https://stackoverflow.com/questions/51693993/pyqt5-error-pycapsule-getpointer-called-with-incorrect-name

**Comment by edreamleo** [comment]
On Tue, Apr 9, 2019 at 4:44 AM András Novoszáth <notifications@github.com>
wrote:

> Hi, I have been reading about Leo and would like to try it out because it
> seems to be a great concept.
>
> However, I have some issues with running. Whenever I try to run it, I got
> the following error message:
>
> [snip]
>   File "/home/andras/leo_editor/leo/core/leoQt.py", line 127, in <module>
>     import PyQt5.QtWebKitWidgets as QtWebKitWidgets
> ValueError: PyCapsule_GetPointer called with incorrect name
> Segmentation fault (core dumped)
>
>
This clearly is a bug in PyQt5 itself, presumably for your individual
version of Linux.

Indeed, this statement occurs inside a Python try/except block, so there is
nothing Leo can do about it directly.

Happily, there is an easy workaround. In your favorite text editor, just set
    QtWebKit = None

at line 127 in leoQt.py, commenting out the import lines that crashed.

There is a good chance that all will then be well...

Edward

**Comment by edreamleo** [comment]
@nocibambi I am going to close this issue.  Please reopen if you need more help.

**Comment by nocibambi** [comment]
Well, it just strikes me how I did not even think about looking at the actual source of the error.

Finally, based on your advice, I solved it in the following way:
```python
    try:
        import PyQt5.QtWebKitWidgets as QtWebKitWidgets
#...
    except ValueError:
        QtWebKitWidgets = None 
```

Thanks a lot!

**Comment by edreamleo** [comment]
On Tue, Apr 9, 2019 at 10:59 AM András Novoszáth <notifications@github.com>
wrote:

> Well, it just strikes me how I did not even think about looking at the
> actual source of the error.
>
> Finally, based on your advice, I solved it in the following way:
>
>     try:
>         import PyQt5.QtWebKitWidgets as QtWebKitWidgets#...
>     except ValueError:
>         QtWebKitWidgets = None
>
> Thanks a lot!
>
You're welcome.  And welcome to Leo.

Edward
