### ISSUE TITLE
Ctrl+- messes up if focus is in the Tree pane or Minibuffer

### ISSUE THREAD

**Issue by SegundoBob** [leo-editor/leo-editor#1108]
## Test Procedure

Create a new file.  In the only node put "abc" (no quotes) in each of the first three lines.  Prepare to find abc and replace it with "defghi" (no quotes). That is, Ctrl+F, abc, Tab, defg.  Find the first "abc".  Now change focus to the tree pane by hitting Ctrl+T.  Now do the replacement by hitting Ctrl+-.

Note the message on the status line
```
not found: (ignore-case) abc
```

That is, even though there are two abc's in the node, Ctrl+- failed to find them.

Even worse, if you make a following node containing abc, the Ctrl+- will skip the two remaining abc's in the first node and find the first abc in the second node.

This bug has caused me to unintentionally fail to do many replacements that I wanted to do.

This bug has annoyed me for months.  Till just a few days ago, I couldn't figure out how to reliably reproduce it.  Then I discovered that focus in the tree pane or Minibuffer triggers the bug.  The bug also sometimes happens when the focus is in the body pane or the Log pane, but I can't reliably make it occur in those circumstances.

## Test System
```
Leo Log Window
Leo 5.8.1-b2 devel, build 20190409061733, Tue Apr  9 06:17:32 UTC 2019
Git repo info: branch = devel, commit = 9bb5c2c156a2
Python 3.6.7, PyQt version 5.11.1
linux
isPython3: True
import-jupyter-notebook requires nbformat package
setting leoID from os.getenv('USER'): 'bob'
current dir: /pri/bob/1/Leo
load dir: /pri/git/leo-editor/leo/core
global config dir: /pri/git/leo-editor/leo/config
home dir: /home/bob
reading settings in /pri/git/leo-editor/leo/config/leoSettings.leo
reading settings in /home/bob/.leo/myLeoSettings.leo
reading settings in /pri/bob/1/Leo/Leo.leo
reading settings in /pri/bob/1/Leo/Leo.leo
```

**Comment by edreamleo** [comment]
@SegundoBob I do not see this with either on any of these platforms:

- Python 3.6.4, PyQt version 5.6.2, linux.
- Python 3.6.3, PyQt version 5.8.0, Windows 10 AMD64 (build 10.0.17134) SP0.

I wonder whether there is a problem in PyQt 5.11.1 or Python 3.6.7.

Does this problem happen with, say, PyQt 5.8?

**Comment by SegundoBob** [comment]
## Now I can't reliably reproduce the problem

I reliably reproduced the problem last Saturday (Leo-Editor commit 9e42b2e5d620) and last Tuesday (Leo-Editor commit 9bb5c2c156a2).  Both days with Python 3.6.7 and PyQt 5.11.1.

Now with the same Leo-Editor as Tuesday (9bb5c2c156a2) Python 3.6.7 and PyQt 5.11.1, I am not able to **reliably** reproduce the problem.  But I am able to unreliably reproduce the problem every five or ten minutes of trying.

I think trying other versions of Python and PyQt is not worthwhile until I can reliably reproduce the problem.

## Second Problem Encountered by my tests

From the beginning I've seen a second problem which I did not report because I was never able to reliably reproduce it; and I still can't reliably reproduce it, but now I'm seeing it about as often as the problem I did report.

### Test Imprecisely Described

New Leo-Editor file with one node.  "abc" (without quotes) on the first three lines of the body.  Ctrl+- to replace "abc" (without quotes) with "newnew" (without quotes).  This replaces the "abc" on the first line with newnew and it leaves the "c" on the second line, the "\n", and the "a" on the third line selected.  If you replace again, you replace the "c\na".   That is, the selection placement is incorrectly placed by (length of replacement string) - (length of replaced string).

**Comment by edreamleo** [comment]
I am going to remove this from the 5.9 to-do list.  This has the feel of an installation problem, or even defective hardware.

**Comment by edreamleo** [comment]
I am going to close this.  Please reopen if you find more clues.
