### ISSUE TITLE
Crash on @language lisp directive with multiple @language and activated pygments

### ISSUE THREAD

**Issue by scriptmode** [leo-editor/leo-editor#1113]
> Traceback (most recent call last):
>   File "/path/to/leo/editor/leo/core/leoColorizer.py", line 2307, in highlightBlock
>     self.colorizer.recolor(s)
>   File "/path/to/leo/editor/leo/core/leoColorizer.py", line 2753, in recolor
>     self.mainLoop(s)
>   File "/path/to/leo/editor/leo/core/leoColorizer.py", line 2611, in mainLoop
>     for token, text in lexer.get_tokens(s):
>   File "/usr/lib/python2.7/dist-packages/pygments/lexer.py", line 191, in streamer
>     for _, t, v in self.get_tokens_unprocessed(text):
>   File "/path/to/leo/editor/leo/core/leoColorizer.py", line 2945, in get_tokens_unprocessed
>     statetokens = tokendefs[statestack[-1]]
> KeyError: 'body'

With @bool use-pygments = True

Situation:
 - Nodes has "@language lisp" in the first line. 
 - Add a new empty line above the directive. 
 - Now the color of the directive changes. 
 - Write a new @language-directive with a parameter in the empty first line (for example: "@language python")
 - Leo crashs

Notable: It does not crash with "@language lisp" or any other text/directive in first line. It seems specifically be triggered by an @language which is no lisp.

**Comment by edreamleo** [comment]
Fixed at 67f497 in devel. There might be subtle problems in the pygments parser, but imo the present code is likely to be fine.
