### ISSUE TITLE
Plugin bigdash.py is not loading (global-search)

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#1114]
Plugin bigdash.py has stopped loading recently, so there are no log error messages if you use the global-search command. Start leo to trace import of plugins:
launchleo.py --trace-plugins

Leo Log Window
Leo 5.8.1-b2 devel, build 20190409061733, Tue Apr 9 06:17:32 UTC 2019
Git repo info: branch = devel, commit = add35de668c2
Python 3.7.2, PyQt version 5.12.2
Windows 10 AMD64 (build 10.0.17134) SP0
isPython3: True
current dir: N:/git/leo-editor
load dir: N:/git/leo-editor/leo/core
global config dir: N:/git/leo-editor/leo/config
home dir: C:/Users/lewis
reading settings in N:/git/leo-editor/leo/config/leoSettings.leo
reading settings in C:/Users/lewis/.leo/myLeoSettings.leo
[snip]
loadOnePlugin: leo.plugins.bigdash.init() returned False
[snip]

**Comment by edreamleo** [comment]
Fixed at db5787a in devel.  Please reopen if there are further problems.
