### ISSUE TITLE
viewrendered 'NoneType' object has no attribute 'QWebView'

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#1116]
I have a url in an @jupyter node. Running the vr command on the node gives :

Leo Log Window
Leo 5.9-final-devel, build 20190409061733, Tue Apr 9 06:17:32 UTC 2019
Git repo info: branch = devel, commit = 124d81794282
Python 3.7.2, PyQt version 5.12.2
Windows 10 AMD64 (build 10.0.17134) SP0
isPython3: True
hook failed: idle, <bound method ViewRenderedController.update of <leo.plugins.viewrendered.ViewRenderedController object at 0x0000024C54DC2168>>, <no module>
Traceback (most recent call last):

   File "N:\git\leo-editor\leo\core\leoPlugins.py", line 324, in callTagHandler
result = handler(tag, keywords)

   File "N:\git\leo-editor\leo\plugins\viewrendered.py", line 757, in update
f(s, keywords)

   File "N:\git\leo-editor\leo\plugins\viewrendered.py", line 913, in update_jupyter
if pc.must_change_widget(QtWebKitWidgets.QWebView):

AttributeError: 'NoneType' object has no attribute 'QWebView'

**Comment by edreamleo** [comment]
Fixed in both devel and py3.

**Comment by LewisNeal** [comment]
Updated to Latest commit 3674019. Running vr command on the node gives:

Leo Log Window
Leo 5.9-final-devel, build 20190409061733, Tue Apr 9 06:17:32 UTC 2019
Git repo info: branch = devel, commit = 367401990250
Python 3.7.3, PyQt version 5.12.2
Windows 10 AMD64 (build 10.0.17134) SP0
isPython3: True
current dir: N:/git/leo-editor
load dir: N:/git/leo-editor/leo/core
global config dir: N:/git/leo-editor/leo/config
home dir: C:/Users/lewisneal
reading settings in N:/git/leo-editor/leo/config/leoSettings.leo
reading settings in C:/Users/lewisneal/.leo/myLeoSettings.leo
Empty setting name in False
[snip]
hook failed: idle, <bound method ViewRenderedController.update of <leo.plugins.viewrendered.ViewRenderedController object at 0x0000029243C31B88>>, <no module>
Traceback (most recent call last):

   File "N:\git\leo-editor\leo\core\leoPlugins.py", line 324, in callTagHandler
result = handler(tag, keywords)

   File "N:\git\leo-editor\leo\plugins\viewrendered.py", line 757, in update
f(s, keywords)

   File "N:\git\leo-editor\leo\plugins\viewrendered.py", line 925, in update_jupyter
w.hide() # This forces a proper update.

AttributeError: 'NoneType' object has no attribute 'hide'

**Comment by edreamleo** [comment]
Recent revs in both devel and py3 attempt a more general fix, taking into account that QWebView may not exist, and falling back to a QTextBrowser in that case.  Please reopen if problems remain.
