### ISSUE TITLE
LeoWapp: duplicate headlines in treepane

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#1127]
**EKR**: It appears that item.dispose works intermittently. Traces in flx_tree.action.clear_tree are as expected. The previous code works intermittently with both chrome and firefox, regardless of whether any top-level nodes are clones. It may be time to report a flexx problem.

**Lewis**: Only the 2nd set of nodes are active. Clicking into the 1st set of nodes does not display any body text.

If I specify edge browser, running `launchleo.py --gui=browser-edge-browser​` I see the nodes as expected, no duplicates.  **EKR**: but it's hard to say for sure, given the intermittent operation.

**Comment by edreamleo** [comment]
@LewisNeal I see the behavior you describe.

**Comment by edreamleo** [comment]
Rev cc038b3 in devel *might* fix this by calling self.tree._redraw_dom().  It's hard to know for sure, because the previous code worked intermittently.  Please reopen if problems remain.

**Comment by edreamleo** [comment]
I am reopening this, because it still happens occasionally.

**Comment by edreamleo** [comment]
Rev d30b40 in devel contains another possible fix.  clear_tree deletes all references to tree items before disposing of each item.  I'll leave this open while testing goes on.

**Comment by edreamleo** [comment]
Rev 42f6ab1 in devel contains a more plausible fix. Let me know if problems remain.  I'll leave this item open for further testing.

Upgrading flexx had nothing to do with the problem!  Indeed, I have been using flexx 0.6.2, not 0.8 as I thought.  LeoWapp now reports the flexx version in the log.

**The bug**: A seemingly innocent change to app.finish_create caused a duplicate redraw early in startup.  Apparently, the flx.TreeWidget never got inited properly.  Or so I think now.

**Comment by LewisNeal** [comment]
Thanks for the fix. Reporting the flexx version is a nice touch.

**Comment by edreamleo** [comment]
I'll close this now.  Please reopen if necessary.
