### ISSUE TITLE
Confused about getting leo in Debian

### ISSUE THREAD

**Issue by pitchforks** [leo-editor/leo-editor#113]
README.TXT advertises that "Leo is now a debian package".

I am running Debian:

    $ lsb_release -a
    No LSB modules are available.
    Distributor ID:	Debian
    Description:	Debian GNU/Linux 7.7 (wheezy)
    Release:	7.7
    Codename:	wheezy

I have assumed that the quoted statement means that leo made it into the debian repository, but after I did `$ apt-cache search leo` and couldn't find anything related to leo there, I'm not sure my assumption was correct.

I have also looked at the leo documentation on http://leoeditor.com , which claims to be for leo-5.0. http://leoeditor.com/installing.html?highlight=debian#installing-from-a-debian-package has a short HOWTO, but it is about using an Ubuntu PPA. While Ubuntu is using .deb packages as well, it is completely another distribution. This causes additional confusion.

I could try installing leo through pip, especially because README.TXT promises it's possible. Yet the install documentation on the official site doesn't mention pip at all. This is an additional reason for confusion.

How do people get leo-5.0 in Debian? I'll be happy with the stable release, so I won't have to deal with the git repository directly or with the source code tarball for installing it using setup.py (because this way it'll be outside the package management frameworks that Debian and pip provide).

**Comment by edreamleo** [comment]
I'm going to close this because of the clarifying comments.
