### ISSUE TITLE
Fix key handling in leoflexx.py

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#1131]
- [x] Alt-x works in both Mozilla and Chrome.
- [x] Click in minibuffer is the equivalent of Alt-x.
- [x] Ctrl-S works in Mozilla and Chrome.
- [x] Ctrl-F works in both Mozilla and Chrome.
- [x] Ctrl-H works in both Mozilla and Chrome, but throws an error in Chrome.

**History**

At one point it was possible to use the minibuffer in LeoWapp.  Almost all of Leo's keys worked, with the exception of Ctrl-H and Ctrl-F. Now, very few incoming keys make their way to Leo's core.  Testing many intermediate commits finds *no* revs that work.  Something outside of Leo seems responsible.

**A change to flexx**

The previous leoflexx code handled *only* the key_press events.  However, the latest [docs for flexx.ui.Widget.key_press](https://flexx.readthedocs.io/en/stable/ui/widget.html#flexx.ui.Widget.key_press) say: "**this event does not fire for the pressing of modifier keys, and some browsers will also not fire for the arrow keys, backspace, etc.**"

This surely must be a change to previous flexx operation!

**Solution**

Adding jse.key_up and key_down emitters catches more events.  This is progress.

Alas, handling up/down events is tricky, because multiple up/down events will be generated for Alt and Ctrl keys.  In addition, key_press events are (sometimes!) also generated.

**Comment by LewisNeal** [comment]
I notice the Tab key is the only on which is active and moves the cursor. Maybe a clue.

**Comment by LewisNeal** [comment]
Tried both chrome and edge, but I'm still unable to enter any text into the minibuffer.

**Comment by edreamleo** [comment]
@LewisNeal Key handling is inherently browser specific.  The new code is still experimental.

I am going to ask Almar Klein for clarification of what recent changes to flexx were intended to do.

**Comment by edreamleo** [comment]
@LewisNeal Chrome works for me on Windows when I start Leo as follows:

leo --no-splash --no-plugins --trace-keys --gui=browser:chrome-browser leo\test\unitTest.leo %*

**Comment by LewisNeal** [comment]
Aahh, I see now :)
<Alt-X> key press activates the minibuffer, however clicking directly into minibuffer does not activate to allow text entry.
This is slightly different than Leo which immediately displays 'full-command: ' once you click the minibuffer.

**Comment by technatica** [comment]
I see the exact same thing on Firefox in linux.

Clicking into the minibuffer with the mouse doesn't work, alt-x works great.

Chris

**Comment by edreamleo** [comment]
On Sat, May 4, 2019 at 6:57 AM LewisNeal <notifications@github.com> wrote:

> Aahh, I see now :)
> key press activates the minibuffer, however clicking directly into
> minibuffer does not activate to allow text entry.
> This is slightly different than Leo which immediately displays
> 'full-command: ' once you click the minibuffer.
>

Yes.  I've just added a to-do item to fix this:  A click in an empty
minibuffer should be the same as Alt-X.

Edward

**Comment by LewisNeal** [comment]
A click into the empty minibuffer works fine. Useability is now much better :)

**Comment by edreamleo** [comment]
I am going to close this.  The exception on Ctrl-H with Chrome does not appear to be significant.
