### ISSUE TITLE
Update TravisCI to require Python 3

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#1133]
And maybe Python 3.6.

Can only be done once Leo 5.9 is released.

**Comment by maphew** [comment]
Travis using py3.6 is used in Py3 branch and unit tests are happy. (There're some setup.py version reporting errors, but I'll follow up on those in the relevant existing issue.)

**Comment by edreamleo** [comment]
On Thu, May 2, 2019 at 11:20 AM matt wilkie <notifications@github.com>
wrote:

> Travis using py3.6 is used in Py3 branch and unit tests are happy.
> (There're some setup.py version reporting errors, but I'll follow up on
> those in the relevant existing issue.)
>

Thanks, Matt.  Greatly appreciated.

Edward
