### ISSUE TITLE
Travis: Attempt to `git describe` failed with IndexError

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#1139]
Version parsing errors reported in Travis.  The same error isn't reported on my machine, but it's Windows. All tests pass including `leo-console --version` later on so this isn't serious. I'm still going to try fix it.

```
[...]
$ python setup.py --quiet bdist_wheel
fatal: No names found, cannot describe anything.
Attempt to `git describe` failed with IndexError
 No module named 'semantic_version'
*** Failed to parse Semantic Version from git tag '6.0-devel'.
        Expecting tag name like '5.7b2', 'leo-4.9.12', 'v4.3' for releases.
        This version can't be uploaded to PyPi.org.
Creating entry_points for [OS name - system]: posix - Linux
/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/setuptools/dist.py:358: UserWarning: The version specified ('6.0-devel') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  "details." % self.metadata.version
warning: no previously-included files matching '__pycache__' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
warning: no files found matching 'pylint-leo.bat'
warning: no files found matching '*.nsi'
The command "python setup.py --quiet bdist_wheel" exited with 0.
[...]
$ leo-console --version
Leo 6.0-devel
```
-- from https://travis-ci.org/leo-editor/leo-editor/builds/527416429

Note Leo's self-reported version number at end doesn't include build number/date.

**Comment by edreamleo** [comment]
@maphew Thanks for your work on this.  Let me know if version names in leoVersion.py should change.

**Comment by maphew** [comment]
@edreamleo I'll have more to say on version reporting once I've finished working out some ideas in code. One thing that would help is when a release tag is created on Master it's merged to Devel quickly. For instance right now the closest-to-HEAD-on-devel is v5.8.1-b2 according to branch history but v5.9 is actually the newest/most current release coming from Devel.

**Comment by edreamleo** [comment]
On Sat, May 4, 2019 at 4:14 PM matt wilkie <notifications@github.com> wrote:

> @edreamleo <https://github.com/edreamleo> I'll have more to say on
> version reporting once I've finished working out some ideas in code. One
> thing that would help is when a release tag is created on Master it's
> merged to Devel quickly. For instance right now the
> closest-to-HEAD-on-devel is v5.8.1-b2 according to branch history but v5.9
> is actually the newest/most current release coming from Devel.
>

I've just updated the distribution checklist in leoDist.leo with this item.

Edward
