### ISSUE TITLE
LeoWapp: 'LeoBrowserLog' object has no attribute 'logWidget'

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#1140]
Running commit 8b6939a
launchleo.py --no-splash  --no-plugins --gui=browser-edge-browser

Starts fine. Run Ctrl-B on a line-review script
I get this traceback triggered at line 10:
Traceback (most recent call last):

  File "N:\git\leo-editor\leo\core\leoCommands.py", line 642, in executeScript
    c.executeScriptHelper(args, define_g, define_name, namespace, script)

  File "N:\git\leo-editor\leo\core\leoCommands.py", line 691, in executeScriptHelper
    exec(compile(script, scriptFile, 'exec'), d)

  File "C:/Users/lewis/.leo/scriptFile.py", line 10, in <module>
    w = c.frame.log.logWidget

AttributeError: 'LeoBrowserLog' object has no attribute 'logWidget'
  [end]

**Comment by edreamleo** [comment]
@LewisNeal As I read the traceback, this is a compatibility issue.  The "official" ivar, log.logWidget does not exist.  I'll see what I can do.

**Comment by edreamleo** [comment]
Fixed at dc20f3f in devel.  Note, however, that c.frame.log.put('whatever') is simpler.
