### ISSUE TITLE
LeoWapp: 'insert-child' command copies body text in the new node.

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#1142]
Running LeoWapp. When using the 'insert-child' command existing body text is repeated in the new node. Python 3.7.2, PyQt version 5.12.2

**EKR**: I see this behavior with the latest code in devel.

**Comment by edreamleo** [comment]
Fixed in 3480cc in devel. All expected unit tests pass.

- app.tree.select sets d ['s'].
- flx.body.update_body_dict sets d['s'] only if it doesn't already exist.

Please reopen if problems remain.

**Comment by edreamleo** [comment]
The proposed fix doesn't work in all cases.

**Comment by edreamleo** [comment]
Fixed at 3d2348e in devel.  Please reopen if necessary.

**Comment by edreamleo** [comment]
I am going to reopen this, for several reasons.  #1143 probably relates.  In addition, insert point and selection ranges may not be preserved when changing nodes.

**Comment by edreamleo** [comment]
I have just created #1146 to handle the focus issues.
