### ISSUE TITLE
LeoWapp: Ctrl-S without clicking minibuffer

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#1143]
Running LeoWapp firefox browser. After typing body text and without clicking into minibuffer, I do Ctrl-S keypress.
I see a message in log pane 'saved: workbook.leo' and also the date of the file changes (date modified).
Close the Leowapp session. However when I reopen the leo file it has not actually saved. I followed this process twice to confirm the bug.

Leo Log Window
flexx version: 0.8.0
Leo 6.0-devel, devel branch
Python 3.7.3, LeoGui: dummy version
Windows 10 AMD64 (build 10.0.17134) SP0

**EKR**: I suspect this is the same as, or similar to, #1142.  We shall see.

**Comment by LewisNeal** [comment]
Running latest commit 3d2348e I see a similar bug when doing a subsequent save in a LeoWapp session.
Edit file and do save-file command. The save completes fully.
In the same LeoWapp session edit file and then save a second time by Alt-X save-file command. Again you see a message in log pane 'saved: workbook.leo' and also the date of the file changes (date modified).
The file does not actually save.
I have seen this several times recently.

**Comment by edreamleo** [comment]
Rev 9e220f completes work for now.  Leo's save-as and save-to commands don't work because they can't get a filename from a dialog.  But that's another issue...

**Comment by edreamleo** [comment]
On Sat, May 11, 2019 at 10:17 AM LewisNeal <notifications@github.com> wrote:

> Running latest commit 3d2348e
> <https://github.com/leo-editor/leo-editor/commit/3d2348eb3ae398ba1b3c4278da68527b073d6dfe>
> I see a similar bug when doing a subsequent save in a LeoWapp session.
> Edit file and do save-file command. The save completes fully.
> In the same LeoWapp session edit file and then save a second time by Alt-X
> save-file command. Again you see a message in log pane 'saved:
> workbook.leo' and also the date of the file changes (date modified).
> The file does not actually save.
>
Does any part of the file save?  The recent work attempted to sync p.b just
before saving.  Other changes should "take".

Edward

**Comment by edreamleo** [comment]
I am going to reopen this, because there are doubts that it has been completed.

**Comment by LewisNeal** [comment]
running commit 3d2348e only the first save-file worked correctly. The second save-file did not work at all despite 'saved:workbook.leo' message.

**Comment by LewisNeal** [comment]
Retested with commit f10c86c. I can confirm both the first and second saves in the same LeoWapp session worked correctly. Tested on chrome, edge and firefox.
Observation: In the firefox test I noted that Alt-X did not transfer the cursor fully to the minibuffer. The minibuffer flashed quickly with the cursor but when I started typing 'save-file' it was appearing in body pane.
I had to click into the minibuffer to activate it.

**Comment by edreamleo** [comment]
On Sun, May 12, 2019 at 3:38 AM LewisNeal <notifications@github.com> wrote:

> Retested with commit f10c86c
> <https://github.com/leo-editor/leo-editor/commit/f10c86c887f992e00ca4deb814ed29f84387eea4>.
> I can confirm both the first and second saves in the same LeoWapp session
> worked correctly. Tested on chrome, edge and firefox.
>

Thanks for the confirmation.

> Observation: In the firefox test I noted that Alt-X did not transfer the
> cursor fully to the minibuffer. The minibuffer flashed quickly with the
> cursor but when I started typing 'save-file' it was appearing in body pane.
> I had to click into the minibuffer to activate it.
>
I've seen this too.  I'll look at this next.

Edward

**Comment by edreamleo** [comment]
I've just created #1146 to handle all focus issues.
