### ISSUE TITLE
[@auto-md] generat soooo many nested placeholder nodes

### ISSUE THREAD

**Issue by ZoomQuiet** [leo-editor/leo-editor#1148]
![ScreenShot 2019-05-16 11 48 49](https://user-images.githubusercontent.com/22494/57825475-a57fd800-77d1-11e9-9faa-e37b3c9ccdd1.jpg)

## env.

- macOS 10.12.6 (16G1918)
- Leo:
    + Leo 5.9-b2, build 20190409061733, Tue Apr  9 06:17:32 UTC 2019
        * Not running from a git repo
        * Python 3.7.0, PyQt version 5.12.3
        * install by pip in Pyenv Python 3.7.0
    + Leo 5.4, Sat Oct 22 06:39:42 2016
        * Git commit: after ff
        * Python 2.7.10, PyQt version 4.8.7
        * install by git clone in Pyenv Python 2.7.15

## err.

- in Leo creat @auto-md node
- edit/logging some thing
    + if copy many CLI message
    + include some Ubuntu apt install log
    + ...
- close Leo
- re-boot leo
- some times there is auto gen. soooo mant nest node
    + most them is only the `placeholder` empty node

## guess

- @auto-md include some markdown parser
- when re-boot Leo
- @auto-md try to re-parser all sub-node
    + try to make them all good-markdown
- but, if there is some chaos logging text
    + the markdown parser will confuse
    + and try fix them all
    + so auto gen. so many err. nodes, and nest them

## suggest

- kill the inter. markdown parser
- @auto-md is better as one-way taggle-out:
    + only export Leo's nest-nodes as base markdown files
    + if some not good-structure markdown contents
    + that is the author's duty
    + do not gen. anything out control nodes.

**Comment by edreamleo** [comment]
@ZoomQuiet Please send me an example file.

I can't do much about this bug until I know how the example file came to be the way it is.

**Comment by edreamleo** [comment]
@ZoomQuiet Imo, killing @auto-md is not a good idea.  If want one-way operation, use `@nosent`!

I'll experiment with limiting the number of intermediate nodes to, say, three.  I don't understand all the implications of doing this, but it's worth experimenting with it.

**Comment by edreamleo** [comment]
Something very strange is going on.  Within `@auto-md` the placeholders should be called 'INSERTED NODE', not 'placeholder'.  Indeed, only the `@auto-rst` and `@auto-org` importers insert 'placeholder'.

I am not going to do anything with this until I get the imported file.

**Comment by ZoomQuiet** [comment]
@edreamleo thanx for suggest;
i'd del these error nested nodes,
next auto nested soooo many nodes, i 'll backup , and atta. here;

BTW:

- in my remember for trigger this kinds of error
- step as:

0: copy many CLI print message, such as apt install software
1: save and close leo
2: open leo
--> discover some nested "placeholders" nodes

**Comment by edreamleo** [comment]
I am going to close this.  Please reopen only if you can provide more data.

**Comment by ZoomQuiet** [comment]
@edreamleo Sayeahooo ;-)

got them, i waiting the bug re-shine.
