### ISSUE TITLE
Search/Replace Problem

### ISSUE THREAD

**Issue by technatica** [leo-editor/leo-editor#1152]
I have a file with 52,655 lines.

Each line is about 100 characters and the file is 2.8mb.

Each line ends with ,,,, (four commas)

I select the ,,,, from the first line, and hit Ctrl-f.

I hit Replace All.

Within 1 minute my workstation was entirely unresponsive. No mouse, no Alt-Tab, nothing. So I reboot.

I select the ,,,, from the first line, and hit Ctrl-f.

I hit "Find All".

Top reports 3.2% memory use and 100% CPU. It held there for 17 minutes before I killed the process.

The same procedure in kwrite completed in less than the blink of an eye.

Then I replicated both conditions.

Let me know if you want the file for your own testing. It is a directory listing of a bunch of files.

**Comment by edreamleo** [comment]
Rev d0067fe in the "replace" branch speeds up the code dramatically.

Making the code faster still is possible, but that would be a lot of work.

I'll leave this issue open "replace" is merged into "devel"

**Comment by edreamleo** [comment]
I am going to close this item.  Rev 675fc49 in devel contains all the new code.

Alas, the "replace" branch was based on "dock", not "devel", so merging it into devel is not a good idea.

**Comment by technatica** [comment]
Works much better for me.

changed 49605 instancess in 6.03 sec.

Chris

**Comment by edreamleo** [comment]
On Sun, Jun 2, 2019 at 5:59 PM Chris George <notifications@github.com>
wrote:

> Works much better for me.
>
> changed 49605 instancess in 6.03 sec.
>

Thanks for the confirmation.  The present code is roughly the best that can
be done.

Edward
