### ISSUE TITLE
Raise dockwidget with focus to top of tabified dock.

### ISSUE THREAD

**Issue by technatica** [leo-editor/leo-editor#1159]
Raise the dockwidget that currently has the focus to the top of a tabified dockwidget stack.

See here: https://stackoverflow.com/questions/1290882/focusing-on-a-tabified-qdockwidget-in-pyqt

To me, this is the last bit required to make tabs complete.

**Comment by edreamleo** [comment]
So, for example, g.es('hi') will show the Log pane/dock.  Should be fairly easy to do.

**Comment by edreamleo** [comment]
Rev dbba3a2 fixes this issue so far as I understand it.

- LeoQtLog.selectHelper raises any parent QDockWidget when selecting a tab.
- qt_gui.set_focus raises any parent QDockWidget when selecting any QWidget.

Please reopen if I have neglected any other cases.

**Comment by technatica** [comment]
When the Find tab is under the body tab and I hit Ctrl-f it switches to a
blank find tab in the Tab dockwidget.

Chris

**Comment by edreamleo** [comment]
Rev 5c2fcf0 passes all my tests.

**Comment by technatica** [comment]
Ctrl-f now reliably sets focus in the find tab and raises it to the top of
the pile.

Thanks,

Chris

**Comment by edreamleo** [comment]
On Sat, Jun 1, 2019 at 8:55 AM Chris George <notifications@github.com>
wrote:

> Ctrl-f now reliably sets focus in the find tab and raises it to the top of
> the pile.
>

Thanks for the confirmation.

Edward
