### ISSUE TITLE
Tips window does not open

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#1160]
I have in myLeoSettings file:
@bool show-tips = True
but the tip window does not show when leo starts.

commit eb6a60c
Leo Log Window
Leo 6.0-devel, dock branch
Python 3.7.3, PyQt version 5.12.3
Windows 10 AMD64 (build 10.0.17134) SP0

**Comment by edreamleo** [comment]
@LewisNeal Thanks for this report.

**Comment by edreamleo** [comment]
Hmm.  `@bool show-tips = True` works for me, with or without --no-dock. Please check your settings.

**Comment by edreamleo** [comment]
Iirc, only the setting in the first loaded file applies.

**Comment by LewisNeal** [comment]
I have @bool show-tips = True in myLeoSettings. If I hide the myLeoSettings file, Leo uses default leoSettings and the Tips window appears.
However if myLeoSettings is active, then the Tips window does not appear.

Updated myLeoSettings file to delete the node @bool show-tips = True
Again the Tips window does not appear.

**Comment by edreamleo** [comment]
On Sun, Jun 2, 2019 at 8:59 AM LewisNeal <notifications@github.com> wrote:

> I have @Bool <https://github.com/Bool> show-tips = True in myLeoSettings.
> If I hide the myLeoSettings file, Leo uses default leoSettings and the Tips
> window appears.
>

Whenever there are setting mysteries, it's good to do the show-settings
command.  This will tell you where settings are coming from.

Edward

**Comment by LewisNeal** [comment]
Note - leoSettings file has the default: @bool show-tips = True
        - myLeoSettings file has no entry for : @bool show-tips
Running commit 9eab102, I loaded one file workbook.leo 

The tip window does not show when leo starts.
Searched the show-settings output and found one entry only:
[F] @bool showtips = False

legend:
leoSettings.leo
@ @button, @command, @mode
[D] default settings
[F] loaded .leo File
[M] myLeoSettings.leo

The only loaded file has no setting at all of
@bool showtips = False
or 
@bool show-tips = False

**Comment by LewisNeal** [comment]
I have confirmed this behaviour on another PC.

**Comment by edreamleo** [comment]
@LewisNeal The entry: `[F] @bool showtips = False`

This line means that that there is a setting `@bool showtips = False` in one of your open .leo files that is *neither* myLeoSettings.leo *nor* leoSettings.leo.  Search for this setting in your open .leo files!

**Comment by edreamleo** [comment]
One more thing.  Because of how Leo munges (regularizes) setting names, be careful how you search for settings.  You might have written any of the following:
```
@bool showtips
@bool show_tips
@bool _show-tips
```
etc., etc.

**Comment by LewisNeal** [comment]
Found it :)
The false setting was not in the single open file, but a theme file read during startup.

**Comment by LewisNeal** [comment]
The source file was \git\leo-editor\leo\themes\LeoBlackSolarized.leo
This seems an odd place for such a setting as it's unrelated to themes.

**Comment by edreamleo** [comment]
On Tue, Jun 4, 2019 at 8:23 AM LewisNeal <notifications@github.com> wrote:

> The source file was \git\leo-editor\leo\themes\LeoBlackSolarized.leo
> This seems an odd place for such a setting as it's unrelated to themes.
>
My apologies for the confusion. Rev 4ca1a1e removes this setting.

Edward
