### ISSUE TITLE
Focus problems in Find tab

### ISSUE THREAD

**Issue by technatica** [leo-editor/leo-editor#1166]
Leo 6.0-devel, dock branch, build 56488a87c5
2019-06-03 08:26:29 -0500
Python 3.6.7, PyQt version 5.12.0
linux

**Focus problem**

When unchecking "Ignore case" (or clicking any of the other check boxes) the focus goes to the body dock widget immediately necessitating either a click to go back to the find dock widget or a ctrl-f.

I see this behavior, but I don't understand why it is problematic.  This behavior has likely existed from day one, as you can see with --no-dock and `@bool minibuffer_find_mode = False`

**Search problem (fixed)**

There was a blunder in the recent code that lowercased the *result* of a search when "ignore case" was in effect.

**Comment by edreamleo** [comment]
@technatica Apparently the new replace-all code is pre-alpha state.

**Comment by edreamleo** [comment]
Fixed at 58f205e in devel.

**Comment by technatica** [comment]
Clicking on any checkbox item in the find window transfers the focus to the
body pane. Do you want that as a separate issue?

Chris

**Comment by edreamleo** [comment]
I am going to close this.  This behavior has existed for many years, and imo does not cause significant problems.

**Comment by technatica** [comment]
It was only a problem if Body and Find were nested. If Find is visible at the same time as Body it isn't a problem.

It will continue to come up with Outline as the central widget unless Body is blocked from nesting.
