### ISSUE TITLE
Can't reopen a closed dock

### ISSUE THREAD

**Issue by technatica** [leo-editor/leo-editor#1167]
The Find Dock Widget and the Spell Dock Widget both have x close buttons in their title bar. And of course, I just had to close the Find dock while working with LeoPyRef.leo and now it is gone completely with no way readily apparent to get it back.

Deleting the two cache directories got it back. But it also removed the layouts from all of my other files. :-(

**Comment by edreamleo** [comment]
Rev 52f7e62 disables close buttons while I work on adding the necessary commands and menu items.

**Comment by edreamleo** [comment]
I'm going to delay this until 6.1.

**Comment by edreamleo** [comment]
Rev fed7f7b in devel​ makes all docks closeable except the central widget.  You can reopen any widget by right clicking the title bar of any open dock.  Qt automagically hides any hidden docks when you last closed Leo.  So this issue is complete!
