### ISSUE TITLE
Colorize lua long brackets properly

### ISSUE THREAD

**Issue by dalcolmo** [leo-editor/leo-editor#1175]
A Lua long literal string is any sequence of characters enclosed within:
[[ and ]]
[=[ and ]=]
[==[ and ]==]
...
In fact any number of equal signs are allowed. The closing sequence must match the opening sequence. That way it is possible to enclose any of the closing sequences in a literal string - just use a differing pair of delimiters.
Leo's colorizer recognizes the pair [[ and ]], but not the others.

We use Lua is often as a data markup language, and in that case it is not unusual to want to include the sequence ]] in a literal string. 
It would be great if the colorizer would at least recognize the pair [=[ and ]=], even if it would not recognize any longer pairs, which may be a bit more difficult to implement.

**Comment by edreamleo** [comment]
Fixed at 9d50ffe
