### ISSUE TITLE
Changing git branches can break clones

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#1183]
Closed via PR #3468. `c.checkVnodeLinks` *repairs* the link-related problems that underlie this issue.

This problem doesn't happen often, but it *does* happen occasionally and is very confusing when it does happen.

**Workaround**:  close leoPy.leo and leoPlugins.leo before switching branches.

**Comment by maphew** [comment]
how does one recognize when this has happened? (I'm not sure what you mean by "break clones")

**Comment by edreamleo** [comment]
On Tue, Jun 11, 2019 at 8:41 AM matt wilkie <notifications@github.com>
wrote:

> how does one recognize when this has happened? (I'm not sure what you mean
> by "break clones")
>
Two nodes that used to be clones in one branch become disconnected.

This can be really confusing in my work flow because I use top-level clones
to change code in files.  But the changes don't happen, and I didn't
understand why until I saw that the clone wasn't ;-)

Edward

**Comment by edreamleo** [comment]
I am going to close this item. Leo's new behavior ( #1240) should suffice.

**Comment by edreamleo** [comment]
I am reopening this issue. Leo's new vnode checks are now giving useful warnings.

**Comment by edreamleo** [comment]
Closed via PR #3468. `c.checkVnodeLinks` *repairs* the link-related problems that underlie this issue.
