### ISSUE TITLE
Duplicate Minibuffer/Nav panels after moving them

### ISSUE THREAD

**Issue by technatica** [leo-editor/leo-editor#1185]
In search of screen real estate, I moved the minibuffer and the nav panel to a more convenient place to the right of the main menu. I then closed Leo. When I reopened Leo the minibuffer and the nav panel were right where I left them. All good so far.

The problem is that Leo decided to create a new minibuffer and a new nav panel, both in their traditional spots.

These can be removed by right-clicking their handle and unchecking them. They can be restored the same way. But it can only be accessed via right-clicking the handle on one of these two features. Once I unclicked both of them I was unable to access the popup menu to restore them again.

The ones I moved to new locations cannot be cleared as no handle right-click popup exists for them. And neither can be moved back to their original positions or deleted.

The floating minibuffer and nav panel exist in all files that were open when I moved them.

![Screenshot_20190608_094625](https://user-images.githubusercontent.com/5809169/59150063-6872c400-89d2-11e9-8e32-301792bc80f2.png)

**Comment by edreamleo** [comment]
This will be fixed for Leo 6.0 beta 2, or beta 1 if there is time.

**Comment by technatica** [comment]
In the legacy UI I can move the Iconbar, but not the Minibuffer.

In my search for more screen space, it would be desirable to be able to move the minibuffer up to the upper right beside the main menu. It frees up an entire line of the screen. Moving it in the dock UI caused it to shorten the input space considerably.

The "bleed through" from one open file to another happens the same way as the dock UI.

**Comment by technatica** [comment]
This is interesting.

I floated the Minibuffer and the Nav panel and after exiting Leo and reopening the file those panels really float. On top of everything.

![Screenshot_20190612_155929](https://user-images.githubusercontent.com/5809169/59392090-44451900-8d2b-11e9-9342-7de8c6450dff.png)

**Comment by edreamleo** [comment]
On Wed, Jun 12, 2019 at 6:01 PM Chris George <notifications@github.com>
wrote:

> This is interesting.
>
> I floated the Minibuffer and the Nav panel and after exiting Leo and
> reopening the file those panels really float. On top of everything.
>
The same would happen for any dock if they were floatable.

Edward

**Comment by edreamleo** [comment]
I'll get to this for Leo 6.0 final, but it need not delay beta 1.

**Comment by technatica** [comment]
The docks never floated above other applications. As soon as Leo was below
the browser they shared their order in the OS window manager with Leo.
These ones don't do that. They take the "always on top" position.



Chris

**Comment by technatica** [comment]
I am probably the only one who ever thought to move them to a non-docked
position.

Chris

**Comment by edreamleo** [comment]
I am going to downgrade this issue to "Maybe".  The workarounds are obvious, and I don't understand what more Leo should be doing in this regard.

**Comment by edreamleo** [comment]
I'll see whether the save/restore machinery for layouts can be made to remember minibuffer location.

**Comment by edreamleo** [comment]
I am going to close this issue. Qt seems to handle most use cases well, and I don't think this will ever be worth fussing with.
