### ISSUE TITLE
toggle-split-direction should work with docks

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#1186]
Imo, this command does not make much sense when using docks.  See #1199.

See also: #1165: Flow elements in dock widgets.

**Comment by LewisNeal** [comment]
A related issue: If I start Leo with --no-dock option, then run toggle-split-direction I still get message:
_toggle-split-direction does nothing
when --dock is in effect_

**Comment by edreamleo** [comment]
Fixed at 974cd65 in devel.

**Comment by LewisNeal** [comment]
see new issue #1194
