### ISSUE TITLE
Retire "recent files" settings or make them work

### ISSUE THREAD

**Issue by largo84** [leo-editor/leo-editor#1188]
`@bool recent_files_group_always = True`

The default of this setting is 'False'. If set to 'True', an unexpected result is to list the recent files across the top menu bar instead of in the File>Recent Files list as before.

EKR: This bug happens regardless of --no-dock.

**Comment by edreamleo** [comment]
@largo84 I don't see this, regardless of --no-dock, on Windows.

What platform are you on?

**Comment by edreamleo** [comment]
Rev 468f32507, May 5, 2019, created this bug.  This rev changed how menu names are "canonicalized".  

Fixed at 3afff37 by undoing those changes.

**Comment by edreamleo** [comment]
I am going to reopen this issue now that the actual bug has been fixed.

**Comment by edreamleo** [comment]
I am going to close this issue.  Rob says, "I use the setting because I have a number of .leo files withe the same name, but different file paths. By grouping them, it reduces clutter and makes it easier to see which path version I'm opening."
