### ISSUE TITLE
Random dock layout for new users

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#1190]
First run of Leo when simulating a new user. The screen is all cramped, scroll bars everywhere, and almost no visible phrase is complete. Windows 10 on an MS Surface Pro tablet/notebook. 

Maximizing window improves things, but the body pane is hidden. Spell panel contents are indecipherable. Overall font size seems to be slightly on the large size, relative to menu fonts etc. (Admittedly this could be considered a feature.) 

This might be something peculiar to the Surface environment (or my profile). For instance sometimes when I take and past a screenshot the image is larger than the original, and some programs have disproportionately small icons.

**First run:**
![image](https://user-images.githubusercontent.com/486200/59278496-ee7f4c80-8c16-11e9-8da8-ffcad033ed2e.png)

**Maximized (no body pane):**
![image](https://user-images.githubusercontent.com/486200/59281518-440a2800-8c1c-11e9-8cfc-664d709418d8.png)

```
> set HOME=%temp%\not-exist-dir
> leo
```

```
Leo 6.0-devel, devel branch, build 948f87d276
2019-06-11 07:13:38 -0500
Using default leo file name:
C:/Users/mattw/AppData/Local/Temp/leo-new-user/.leo/workbook.leo
wrote recent file: C:/Users/mattw/code/leo-editor/.leo/.leoRecentFiles.txt
wrote C:/Users/mattw/code/leo-editor/.leo/leo.session
```

**Comment by edreamleo** [comment]
@maphew Good catch.  This is a release blocker.

**Comment by edreamleo** [comment]
My plan for fixing this bug is to create a script which creates a reasonable initial layout to be used if there are no other stored layouts.  It should be easy to test this script by clearing the cache.

The script will check that g.app.docks is True and that only standard plugins are in effect.

**Comment by edreamleo** [comment]
Fixed at a79c2a in devel.

**Comment by edreamleo** [comment]
Please reopen if problems remain.

**Comment by maphew** [comment]
That's better.  Next problem is that for me the window opens slightly offscreen to the top left, with the Tips dialog centered to the display. (This is a workstation with large display). 

![image](https://user-images.githubusercontent.com/486200/59453707-4956a680-8dc5-11e9-9a7d-1df6eb67f975.png)

**Comment by edreamleo** [comment]
e86b1c8 should fix this.

**Comment by maphew** [comment]
On a machine with dual displays the Tips dialog and Leo window show up on different displays.

**Comment by edreamleo** [comment]
@maphew I don't think the dual-display problem is worth fixing.

Please open a separate issue if you strongly disagree, but I'm likely to label in "Maybe" :-)

**Comment by maphew** [comment]
It would be good to see what Leo's first load looks like on other systems (e.g. is this only a MS Surface issue).

**Comment by edreamleo** [comment]
I have just opened #1377 for this.
