### ISSUE TITLE
How to change theme?

### ISSUE THREAD

**Issue by levirs565** [leo-editor/leo-editor#1191]
I'am is new to leo-editor. I do not know how to use leo. I've read leo-editor FAQ about how to change theme to dark. But, i not understant the documentation. Then, i try to use __Settings -> Open A Theme File__. But it does not work. How to change theme?

**Comment by edreamleo** [comment]
On Wed, Jun 12, 2019 at 6:01 AM Levi Rizki Saputra <notifications@github.com>
wrote:

> I'am is new to leo-editor. I do not know how to use leo. I've read
> leo-editor FAQ about how to change theme to dark. But, i not understant the
> documentation. Then, i try to use *Settings -> Open A Theme File*. But it
> does not work. How to change theme?
>

Does this FAQ entry
<http://leoeditor.com/FAQ.html#how-can-i-use-a-dark-theme-in-leo> help?

Edward

**Comment by maphew** [comment]
_Re-opening as a 'doc-update'. Below paraphrased from: https://groups.google.com/d/topic/leo-editor/WFrTF4A9jaE/discussion_

Target sections:
- https://leoeditor.com/customizing.html#theme-files
- http://leoeditor.com/FAQ.html#how-can-i-use-a-dark-theme-in-leo

----
Suggest to put this procedure in the document something like a best practice(for newbie?)..  I was not able to config theme successfully following the instructions at 
https://leoeditor.com/customizing.html#theme-files Until I found this email:

----
Here is how I use themes.

In the directory leo-editor/leo/themes are a number of theme files. These can be loaded using the File, Open Outline menu option in Leo. Opening an outline automatically loads it. Keep opening outlines until you find one you like.

Then close all of the theme files.

Copy the theme file you chose from leo-editor/leo/themes to ~/.leo/themes (you will have to create the themes folder here) and rename it something like this: Original file is BreezeDarkTheme.leo rename to BreezeDarkThemeLocal.leo

Now open your myLeoSettings.leo file.

Add the following to the headline of a new node as a child of your @settings node:
`@string theme-name = BreezeDarkThemeLocal`

Now save the file and restart Leo.

You should now be using the theme of your choice. From here you need to open the local theme file with Leo. The font sizing and colors are under Theme Settings in the tree.

HTH,

Chris

----

**Comment by edreamleo** [comment]
Completed at cb01d4f in devel.
