### ISSUE TITLE
Experiment without any central widget

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#1192]
The ["no-central-widget"](https://github.com/leo-editor/leo-editor/tree/no-central-widget) branch contains this work.

This issue arises from #1181.

**Comment by technatica** [comment]
Leo 6.0-devel, no-central-widget branch, build 6ecd73c8af
2019-06-12 12:39:39 -0500
Python 3.6.8, PyQt version 5.12.3
linux

Beautiful.

This allows every single configuration I can think of and if I avoid nesting with the Body widget I don't lose any functionality.

This is even better than a central body widget. I can put whatever I want under or over Outline or Body without having to use 100% of the width and I can use a 2x2 grid and resize the cells individually either horizontally or vertically.

Now if only we could get rid of the title bars on the docks but only once the preferred layout has been reached. Until then they are useful. After they waste screen real estate.

![Screenshot_20190612_145803](https://user-images.githubusercontent.com/5809169/59389167-83bb3780-8d22-11e9-8043-070ac1a178ea.png)

The only limitation here is that I cannot pick up the Outline dock by its title bar and move it. And I cannot drop anything to the left of the Outline tab which means the only place it can go in a left-right sense is on the left, period. 

So if the Outline widget can be totally freed up then the flexibility to use any layout is achieved. It would be prudent to simply not allow nesting in the Body widget but don't make it the central widget please as the ability to put something above or below it at less than 100% width would be lost.

**Comment by technatica** [comment]
My initial success was based on the default layout. Body and Outline are side by side and if I plan carefully I can get to the 2x2 arrangement. But if I ever allow a Body above Outline layout I am stuck there as I cannot put anything to the left or right of any of the widgets.

![Screenshot_20190612_150946](https://user-images.githubusercontent.com/5809169/59389797-245e2700-8d24-11e9-9e9e-4556f6f0efc8.png)

**Comment by edreamleo** [comment]
On Wed, Jun 12, 2019 at 5:01 PM Chris George <notifications@github.com>
wrote:

> Beautiful.
>
Glad you like it.

Now if only we could get rid of the title bars on the docks but only once
> the preferred layout has been reached. Until then they are useful. After
> they waste screen real estate.


This can be done, but let's wait a bit.

> The only limitation here is that I cannot pick up the Outline dock by its
> title bar and move it.
>
Fixed in b7e071f2 in no-central-widget. Let me know the results.

> And I cannot drop anything to the left of the Outline tab which means the
> only place it can go in a left-right sense is on the left, period.
>
I think that can't be helped.  Without a central widget there is no such
thing as the left area.

Edward

**Comment by technatica** [comment]
I think you can change the "Tab" dock's name to "Log" now that all plugins are out of it.

Nothing can be dropped to the left of Outline or to the right of Body and Outline will always be on the left and Body will always be on the right.

Unless I put either above the other in which case I can never go back without deleting the cache as you cannot put anything to the left of Outline or to the right of Body. :-(

The "toggle-split-direction" might solve that. But right now there is no way back from a one above the other layout without deleting the cache.

**Comment by edreamleo** [comment]
On Wed, Jun 12, 2019 at 5:57 PM Chris George <notifications@github.com>
wrote:

> I think you can change the "Tab" dock's name to "Log" now that all plugins
> are out of it.
>

Not really.  The Completion tab would have to be a dock, and that might
cause focus problems.

> Nothing can be dropped to the left of Outline or to the right of Body and
> Outline will always be on the left and Body will always be on the right.
>
> Unless I put either above the other in which case I can never go back
> without deleting the cache as you cannot put anything to the left of
> Outline or to the right of Body. :-(
>
I'm not surprised.  Not having a central widget is more than a bit of a
hack.  At one time the QMainWindow docks said that there *must* be a
central widget.  Clearly, this is not strictly true, but you are seeing the
problems.

I have been willing to let you play around with not having a central
widget, but for most people, maybe even including you, it is safest to use
a central widget.

> The "toggle-split-direction" might solve that. But right now there is no
> way back from a one above the other layout without deleting the cache.
>
And afaik there is nothing that Leo can do about that.

Edward

**Comment by technatica** [comment]
Then I would lobby for Body to be that central widget. At least then it would totally avoid all of the focus problems with nested Spell/Find/Log and all the other plugins.

Can we try that? Perhaps with a setting to switch back and forth?

**Comment by edreamleo** [comment]
Done at rev fe53577 in devel.  Leo now supports two new settings, with the default as shown:

**@string central-dock-widget = outline**

valid values are: outline, body, tabs
Warning: you may have to clear the caches in .leo/db after changing this setting.

**@bool dockable-log-tabs = False**

False: (recommended) Plugins create areas in the Tabs dock.
True: create separate docks for plugins that used to be in Log pane.

**Comment by edreamleo** [comment]
I am going to close this issue.  Imo, nothing more can reasonably be done.

The new settings did not greatly complicate the code.  Still, they add complexity.  Otoh, newbies will not notice this complexity ;-)

**Comment by edreamleo** [comment]
On Wed, Jun 12, 2019 at 6:19 PM Chris George <notifications@github.com>
wrote:

> Then I would lobby for Body to be that central widget. At least then it
> would totally avoid all of the focus problems with nested Spell/Find/Log
> and all the other plugins.
>
> Can we try that? Perhaps with a setting to switch back and forth?
>
As mentioned in a recent post, use @string central-dock-widget = body

Edward
