### ISSUE TITLE
VR Pane Isn't a Dock Widget

### ISSUE THREAD

**Issue by technatica** [leo-editor/leo-editor#1193]
The VR pane has a lovely, full-featured OS window. It can be resized, moved anywhere, set to stay on top and moved to a different session on the same linux box. But it isn't a dock widget and so it cannot be nested into the Outline/Find/Spell/Tabs/Tags window.

**EKR**: Ouch.  Without docks the VR pane appears alongside the body pane.  With docks, the VR pane *must* be a dock (or a Log pane tab).

**Comment by edreamleo** [comment]
Rev 953cd08 creates a Rendering dock, but I am having second thoughts.  Instead, it might be better to define dw.createRenderingArea.  I suppose this should be an option, and I'm not sure what default I would prefer.

**Comment by edreamleo** [comment]
Rev c3455bb4 in devel completes this issue.

**Note**: You may have to clear Leo's caches after changing the `@bool use-vr-dock` setting.  This can't be helped at present.
