### ISSUE TITLE
toggle-split-direction not working when --no-dock start option is used

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#1194]
Start Leo with --no-dock option:
_launchleo.py --no-dock_
then run toggle-split-direction command. Nothing changes at all in the layout.
Log pane message is  _toggle-split-direction works only when
--no-dock is in effect_ 

Leo Log Window
Leo 6.0-devel, devel branch (commit 974cd65d5)
Python 3.7.3, PyQt version 5.12.3
Windows 10 AMD64 (build 10.0.17134) SP0

**Comment by edreamleo** [comment]
Fixed at a79c2a72 in devel.
