### ISSUE TITLE
launchleo.py --version does not report full commit number

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#1195]
According to http://leoeditor.com/running.html#leo-s-command-line-options
 -v, --version         should print version number and exit

But this only reports:
Leo 6.0-devel, devel branch

The leo log pane used to report the commit number. 
Running commit 60d7aca98 it displays:
_Leo Log Window
Leo 6.0-devel, devel branch
Python 3.7.3, PyQt version 5.12.3
Windows 10 AMD64 (build 10.0.17134) SP0_

Is there a command that actually reports the commit number?

**Comment by edreamleo** [comment]
On Thu, Jun 13, 2019 at 5:03 AM LewisNeal <notifications@github.com> wrote:

> According to http://leoeditor.com/running.html#leo-s-command-line-options
> -v, --version should print version number and exit
>

It still does, provided the .leo file resides in a git repo.

Edward

**Comment by LewisNeal** [comment]
I tried this with test.leo which is in my git repo
launchleo.py --version N:/git/leo-editor/leo/test/test.leo

I do not see the full version reported and Leo does not exit.

**Comment by edreamleo** [comment]
@LewisNeal I find your report difficult to believe.  --version is going to short-circuit everything.

**Comment by LewisNeal** [comment]
Maybe we are expecting different reports :)
Here is a screenshot of the log pane showing
_Leo 6.0-devel, devel branch_
If that is what is meant by version number then it is working. My point was Leo used to report the commit number, but it no longer does. Maybe that is intended.

![Capture_vers_test](https://user-images.githubusercontent.com/6681711/59492344-1d721880-8ecc-11e9-93cf-357bab0f66d8.JPG)

Can you explain what is meant by "--version is going to short-circuit everything."?

**Comment by edreamleo** [comment]
On Fri, Jun 14, 2019 at 2:47 AM LewisNeal <notifications@github.com> wrote:

Can you explain what is meant by "--version is going to short-circuit
> everything."?


--version should halt Leo, printing the version in the console.  There
shouldn't be a Leo visible for a screen shot!

Edward
