### ISSUE TITLE
Phantom Dock Widget

### ISSUE THREAD

**Issue by technatica** [leo-editor/leo-editor#1196]
**Note**: I have hidden some screen shots and comments to reduce the load on future readers of this thread.   Rev d533a4c in devel fixes this problem.

**EKR: Summary of the problem**

The culprit was using a default layout (a magic number, namely g.app.defaultWindowState) in g.app.restoreWindowState.

Pyzo can use a magic number because it has only one kind central widget.  But a single magic number will seriously confuse Qt if the actual central widget is not the same as the central widget used when computing the magic number.

**Changes to g.app.restoreWindowState**:

1. Don't init the window state when --init-docks is in effect.  This should work regardless of which central widget the user has chosen.

2. [fallback] Otherwise, use g.app.defaultWindowState only as a last resort and *only* if the central widget is the outline widget, which was true when computing g.app.defaultWindowState. 

*Important*: The fallback logic is required to fix #1190: Random dock layout for new users. By definition, first-time users will not have changed any settings, so g.app.defaultWindowState will be correct.

**Changes to ViewRenderedController.create_pane**: 

If the central widget is the body pane, the code creates a stand-alone dock in the Qt.RightDockWidgetArea dock area.  Otherwise, the code splits the body widget.

**Original report**:

Leo 6.0-devel, devel branch, build a79c2a72aa
2019-06-13 06:54:57 -0500
Python 3.6.8, PyQt version 5.12.3
linux

This behaviour is the same using @string central-dock-widget = outline or @string central-dock-widget = body.

1. Change settings.
2. Close Leo. 
3. Delete cache manually.
4. Start Leo.

This is the default layout with a central body.

[Screenshot_20190613_055320](https://user-images.githubusercontent.com/5809169/59434035-9a53a400-8d9f-11e9-89c1-377bbac5700d.png)

Above the minibuffer is a line that contains the phantom. It flickers when I mouse over it showing me that it is the title bar of the Body widget (or Outline widget, depending which is central). Moving a few things around makes it plainer to see the problem.

[Screenshot_20190613_054857](https://user-images.githubusercontent.com/5809169/59434323-2d8cd980-8da0-11e9-9be1-c907b62d56a0.png)

When I drag another dock widget over the phantom wants to let me nest with it. If I do so the dock widget I was dragging nests and has a tab as a nest member but I can never actually activate it by clicking the tab in the nest. It is in essence gone until I delete the cache again.

**Comment by technatica** [comment]
Correction: This only happens with "Body" as the central widget. There is still something different between the Body and Outline dock widgets.

**Comment by edreamleo** [comment]
I'll schedule this for 6.0, to be able to track it easily.  However, I'm not promising anything until I get more info.

**Comment by edreamleo** [comment]
I am going to downgrade this issue to "Maybe". The workarounds are obvious, and I don't understand what more Leo should be doing in this regard.

**Comment by technatica** [comment]
When I change the set central widget setting to body or tabs the UI becomes unstable with a flickering ghost of the central dock widget taking up space in the bottom row. It is worse with Tabs than Body as Tabs has a higher number of minimum rows and the ghost takes up more space.

The only workaround is to use the Outline widget as the central widget which puts us right back to where we started. With Outline as the central widget, a two-pane configuration is impossible and users will have to be cautioned to not nest the Body dock widget with Find, Spell, or Tabs. At that point, a three-pane layout becomes the bare minimum for functionality.

Setting the Body dock widget as the central widget solves a number of UI inconsistencies. Pyzo takes this approach. 

I urge you to try one of the other choices for the central widget and see what I mean. There is something different in how the Outline dock widget and the Body/Tabs dock widgets are treated in the code.

**Comment by technatica** [comment]
Now even the Outline widget as central causes the ghost.

I am stumped. Am I the only one seeing this behaviour?

**Comment by largo84** [comment]
I just changed the setting to Body as central widget. I see the 'phantom' widget at the bottom. If I dock something there, I can't undock it.

**Comment by technatica** [comment]
If I clear the cache before choosing body as central widget or choosing tabs as central widget, I get the ghost.

If I do not clear the cache after body or tabs and then try outline (I use an external editor to make changes to myLeoSettings.leo), outline also has a ghost.

If clear the cache and then load outline it works correctly.

**Comment by technatica** [comment]
I checked out rev. 948f87d276b562efcec74288fa88cb7a471dcd3e and changed
`if name == 'outline':
                self.setCentralWidget(dock)
            else:
                self.addDockWidget(area, dock)`
in qt_frame.py to

`if name == 'body':
                self.setCentralWidget(dock)
            else:
                self.addDockWidget(area, dock)`

and the Body widget now works as the central widget without the ghost.

**Comment by edreamleo** [comment]
On Fri, Jun 14, 2019 at 9:11 PM Chris George <notifications@github.com>
wrote:

> I checked out rev. 948f87d
> <https://github.com/leo-editor/leo-editor/commit/948f87d276b562efcec74288fa88cb7a471dcd3e>
> and changed
> if name == 'outline': self.setCentralWidget(dock) else:
> self.addDockWidget(area, dock)
> in qt_frame.py to
>
> if name == 'body': self.setCentralWidget(dock) else:
> self.addDockWidget(area, dock)
>
> and the Body widget now works as the central widget without the ghost.
>

Hmm.  The version in devel has this code:

if name == central_widget:
    self.setCentralWidget(dock)

Edward

**Comment by technatica** [comment]
Rev. 974cd65

Change outline to body in dw.createAllDockWidgets

`# Remember the dock.
        setattr(self, '%s_dock' % (name), dock)
        if name == 'body':`

And reverse the trues and falses between outline and body here:

`table = (
        (False, True, 100, lt, 'outline', self.createOutlineDock),
        (False, False, 100, bottom, 'body', self.createBodyPane),
        (False, True, 20, rt, 'tabs', self.createTabsDock),
        (True, True, 20, rt, 'find', self.createFindDock),
        (True, True, 20, rt, 'spell', self.createSpellDock),
    )`

Save changes, close Leo.

Clear cache manually by deleting the two directories under .leo/db

Open Leo.

This works just fine. Body becomes the central widget, stacking problems go away and there is no ghost.

Follow the exact same procedure with Rev. fe53577d2 except choosing the setting that should make the Body widget central instead of changing the code and the ghost appears.

And I do not know enough about python to spot why.

**Comment by edreamleo** [comment]
Thanks for all these experiments.  I see strange things as well.  It's a mystery that should be fixed before 6.0 b1.

**Comment by edreamleo** [comment]
I found one bug: there were *two* calls `w = creator(parent=None)` in the main loop of dw.createAllDockWidgets.  That might have caused some phantoms.

However, this does not cure the weirdness.  I suspect the viewrendered plugin may be at fault.  It thinks that the body pane can be split.  But this is a weird edge case when the body pane is the central widget.

**Comment by technatica** [comment]
The weirdness was happening before the Rendered dock existed.

Hopefully, the one bug cures what ails me.

I was really happy with Rev. 974cd65 with the body as the central dock. No
nesting visibility issues and I could get pretty much every useful
configuration of windows without limitations.

The Rendered dock is a bit of a bear. It either owns the entire layout or
it goes away. There doesn't seem to be a happy medium.

Chris

**Comment by edreamleo** [comment]
I wonder whether the state-restoring logic could be the problem.  --init-docks uses a hard-coded value which I created with the *outline* pane as the central widget.

**Comment by edreamleo** [comment]
@technatica I checked out 974cd65, but I couldn't set the body pane as the central dock!  Anyway, there has been too many changes for me to consider going back.  I am out of ideas.  I'll try again tomorrow.

**Comment by edreamleo** [comment]
Making restoreWindowState a no-op solves most of the problems!

Not sure what to do next...

**Comment by technatica** [comment]
Thanks. My surmise is that there is something wrong with Rev. fe53577.

This was the first Rev. where I see the ghost with a central body widget.
There is something different about body and tabs when compared to outline
in the logic of the substitution. This behaviour still exists in the latest
Rev. in devel when I choose body or tabs as the central widget and clear
the cache by deleting the files. The only difference with the latest devel
is that the Rendered tab adds to the confusion.

Chris

**Comment by technatica** [comment]
dw.createLogPane and dw.createBodyPane both atart with c = self.leo_c.

dw.createOutlinePane does not.

One of these things is not like the others.

Chris

**Comment by edreamleo** [comment]
Fixed at d533a4c in devel.
