### ISSUE TITLE
Find and Spell tabs do not show with dock active

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#1197]
Run commit a79c2a72a with default leosettings - there is no Find tab. The find-tab-open command does nothing.

However run 
_launchleoleo.py --no-dock_
and the Find tab is visible next to the log pane

**EKR**: Oops.  This is a recent blunder.  The Spell tab is gone too.

**Comment by LewisNeal** [comment]
I see the same behaviour if myLeoSettings file is active.
The Find tab only appears if I use _--no-dock_ option at startup.

**Comment by edreamleo** [comment]
On Thu, Jun 13, 2019 at 8:55 AM LewisNeal <notifications@github.com> wrote:

> Run commit a79c2a7
> <https://github.com/leo-editor/leo-editor/commit/a79c2a72aa4ada8f47b04f407bf3875b5970e00c>
> with default leosettings - there is no Find tab. The find-tab-open command
> does nothing.
>

Oops.  This is a recent blunder.

Edward

**Comment by edreamleo** [comment]
Fixed at c816063 in devel.
