### ISSUE TITLE
New documents have collapsed body pane

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#1198]
On creation of a new document with `Ctrl-N` the body panel is collapsed. 

![image](https://user-images.githubusercontent.com/486200/59453961-f2050600-8dc5-11e9-9493-59569f26d65c.png)

Secondarily, the [Tabs] panel can be expanded by dragging with the mouse, but it collapses as soon as I click anywhere else except the Outline pane.

```
Leo Log Window
Leo 6.0-devel, devel branch, build 49073170aa
2019-06-13 10:29:02 -0500
Python 3.7.1, PyQt version 5.11.2
Windows 10 AMD64 (build 10.0.17134) SP0
```

**Comment by edreamleo** [comment]
Fixed at 80412a4.

**Comment by maphew** [comment]
confirmed fixed for me. I also had to delete `%HOME%\.leo\db`

**Comment by edreamleo** [comment]
Thanks for the confirmation.
