### ISSUE TITLE
"File > Open outline" defaults to *.* not [*.leo, *.db]

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#1200]
The menu "File >> Open outline" opens a file chooser dialog with the _file-type filter set to `*.*`. 

I expected it filter for Leo outlines by default (which are `*.leo, *.db` in the file-type choose list).

**Comment by edreamleo** [comment]
Fixed at adddb9f. This is actually a bit debatable, because Leo can open any kind of file here.  However, I'll let it stand.  Otoh, the command is open-outline, and the menu item is Open Outline, so it's not unreasonable.
