### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'contract'

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#1201]
Totally baffled. I was testing new user experience.

```
md t
cd t
set home=%cd%
leo
:: resize Leo window, click a few things but no changes to Workbook.leo, no save
:: close Leo
```
Then run Leo again. Immediate fatal crash with traceback:

```
(leo-dev) matt@SURFACE C:\Users\mattw\t
> leo-m

Leo 6.0-devel, devel branch, build e86b1c87b6
2019-06-13 17:47:36 -0500
Using default leo file name:
C:/Users/mattw/t/.leo/workbook.leo
OleSetClipboard: Failed to set mime data (text/plain) on clipboard: COM error 0xffffffff800401d0  (Unknown error 0x0800401d0) (The parameter is incorrect.) selectPosition Warning: no p run,load,doPostPluginsInit,openEmptyWorkBook
Traceback (most recent call last):
  File "c:\apps\miniconda3\envs\leo-dev\Scripts\leo-m-script.py", line 11, in <module>
    load_entry_point('leo', 'console_scripts', 'leo-m')()
  File "c:\users\mattw\code\leo-editor\leo\core\runLeo.py", line 73, in run
    g.app.loadManager.load(fileName, pymacs)
  File "c:\users\mattw\code\leo-editor\leo\core\leoApp.py", line 2375, in load

    ok = lm.doPostPluginsInit()
  File "c:\users\mattw\code\leo-editor\leo\core\leoApp.py", line 2433, in doPostPluginsInit
    c1 = lm.openEmptyWorkBook()
  File "c:\users\mattw\code\leo-editor\leo\core\leoApp.py", line 2488, in openEmptyWorkBook
    p.contract()
AttributeError: 'NoneType' object has no attribute 'contract'
```

**Comment by edreamleo** [comment]
Thanks for all this new-user testing!

**Comment by maphew** [comment]
You're welcome :)

3rd run, Leo was ok, but emits warning about another copy possibly running:

![image](https://user-images.githubusercontent.com/486200/59487774-7c834f00-8e32-11e9-9086-1a171de73174.png)

**Comment by edreamleo** [comment]
On Fri, Jun 14, 2019 at 1:25 AM matt wilkie <notifications@github.com>
wrote:

> You're welcome :)
>
> 3rd run, Leo was ok, but emits warning about another copy possibly running:
>
Sure.  That's what typically happens after crashing.

Edward

**Comment by maphew** [comment]
note the status bar says the open doc is `C:/Users/mattw/t/.leo/workbook.leo` while the warning dialog says `Users/mattw/code/leo-editor/leo/doc/CheatSheet.leo`.

`....\.leo\workbook.leo` doesn't exist in file system.

**Comment by edreamleo** [comment]
I'll get to this later.  Time for sleep.

**Comment by maphew** [comment]
Sleep well. (me too!)

Tried again from beginning but didn't reproduce the crash. Workbook.leo continues to not exist, though Leo continues to insist that's what it has open. This is stable through multiple exits and restarts.

**Comment by edreamleo** [comment]
Rev b83f0de adds a guard so the AttributeError you report can not happen.​

Whether this fixes all related is an open question.  Please open a new issue if further problems remain.
