### ISSUE TITLE
Log pane does not report full commit number

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#1209]
Running commit db3495950 my Leo log pane is missing the commit number. I can only get this number from git_pull records.

_Leo Log Window
Leo 6.0-devel, devel branch
Python 3.7.3, PyQt version 5.12.3
Windows 10 AMD64 (build 10.0.17134) SP0_

I have searched leosettings/myLeoSettings files to see if there is any toggle for this number and have been unable to find one.
Other Leo user reports indicate that the commit number appears in their log pane.

It is only a minor issue but I am completely baffled as to why it has stopped appearing.

**Comment by edreamleo** [comment]
On Mon, Jun 17, 2019 at 7:36 AM LewisNeal <notifications@github.com> wrote:

> Running commit db34959
> <https://github.com/leo-editor/leo-editor/commit/db349595087f895bf83879891ea6fd42fc2af154>
> my Leo log pane is missing the commit number. I can only get this number
> from git_pull records.
>
...

> It is only a minor issue but I am completely baffled as to why it has
> stopped appearing.
>
It works for me.  It's probably related to the current directory in effect
when Leo starts.  But this is a guess.

Edward

**Comment by LewisNeal** [comment]
I reverted to commit 124d817. Why? I had an old log pane saved which showed the commit details....

Here is the log pane after the checkout:
Leo Log Window
Leo 5.9-final-devel, build 20190409061733, Tue Apr 9 06:17:32 UTC 2019
Git repo info: branch = None, commit = 124d817
Python 3.7.3, PyQt version 5.12.3
Windows 10 AMD64 (build 10.0.17134) SP0
isPython3: True

So at some point after this build the reporting behaviour has changed.

**Comment by edreamleo** [comment]
On Mon, Jun 17, 2019 at 9:32 AM LewisNeal <notifications@github.com> wrote:

> I reverted to commit 124d817
> <https://github.com/leo-editor/leo-editor/commit/124d81794282a781e8821c3b6cebfd1bfd68f007>.
> Why? I had an old log pane saved which showed the commit details....
>
That's a commit from April 12?

Presumably this is related to #1126
<https://github.com/leo-editor/leo-editor/issues/1126>: Reform how Leo
handles git time stamps.

I'm not sure if there is a problem. I won't delay b1 for this.

Edward

**Comment by edreamleo** [comment]
I'll reopen this while we figure out what is going on.

**Comment by LewisNeal** [comment]
Running commit 0bddac609 here is log from the console.

N:\git\leo-editor>launchleo.py --trace=startup

reading settings in N:/git/leo-editor/leo/config/leoSettings.leo
reading settings in C:/Users/lewis/.leo/myLeoSettings.leo
Empty setting name in False
set parent @settings
reading settings in C:/Users/lewis/.leo/LeoBlackGraySolarized.leo
getGitVersion return code 1
getGitVersion value b''
getGitVersion return code 1
getGitVersion value b''
Leo 6.0-b2-devel, devel branch
livecode.py: can not import meta
you can install meta with `pip install meta`
rss.py: can not import feedparser
load_session loading: C:/Users/lewis/OneDrive - Efficiency Filters Pty Ltd/workbook.leo
reading settings in C:/Users/lewis/OneDrive - Efficiency Filters Pty Ltd/workbook.leo
DynamicWindow.__init__ workbook.leo
restoreWindowState workbook.leo found key: windowState:C:/Users/lewis/OneDrive - Efficiency Filters Pty Ltd/workbook.leo
load_session loading: C:/Users/lewis/.leo/workbook.leo
reading settings in C:/Users/lewis/.leo/workbook.leo
DynamicWindow.__init__ workbook.leo
restoreWindowState workbook.leo found key: windowState:C:/Users/lewis/.leo/workbook.leo
startup time:  4.88 sec
[end]

**Comment by edreamleo** [comment]
@LewisNeal Hmm. I see you are running Leo from a top-level directory called git:

N:\git\leo-editor>launchleo.py --trace=startup

I suspect that's the problem: perhaps the git directory is getting confused with the git command.

**Comment by edreamleo** [comment]
@LewisNeal please run the following from the console and report the results:

    git log -n 1 --date=iso

I may have asked for this already, but I can't remember where.

**Comment by LewisNeal** [comment]
$ git log -n 1 --date=iso
commit 9afc8ca191849464ca7c4e70bb4b0f7fb4367c3d (HEAD -> devel, origin/devel)
Author: Edward K. Ream <ed.....@gmail.com>
Date:   2019-06-21 20:28:12 -0500

    Cleanups complete #1211

lewis@Argon MINGW64 /n/git/leo-editor (devel)
[end]

**Comment by edreamleo** [comment]
On Fri, Jun 21, 2019 at 9:05 PM LewisNeal <notifications@github.com> wrote:

> $ git log -n 1 --date=iso
> commit 9afc8ca
> <https://github.com/leo-editor/leo-editor/commit/9afc8ca191849464ca7c4e70bb4b0f7fb4367c3d>
> (HEAD -> devel, origin/devel)
> Author: Edward K. Ream ed.....@gmail.com
> Date: 2019-06-21 20:28:12 -0500
>
> Cleanups complete #1211
>
> lewis@Argon MINGW64 /n/git/leo-editor (devel)
> [end]
>

Thanks.  This is the missing piece of the puzzle.

For some reason your commit number has only 7 digits, whereas mine has many
more. I'm investigating, but this is still a mystery.

Edward

**Comment by edreamleo** [comment]
On Sat, Jun 22, 2019 at 2:53 AM Edward K. Ream <edreamleo@gmail.com> wrote:

For some reason your commit number has only 7 digits, whereas mine has many
> more. I'm investigating, but this is still a mystery.
>

Please pull 81a96b1.  It contains better tracing in your case.

Please run `leo --trace=startup` from a console and report the results.
Thanks.

Edward

**Comment by LewisNeal** [comment]
EKR: For some reason your commit number has only 7 digits,

During posting the commit number was modified and truncated back to 7digits . Here is a rerun from git (added spaces to commit number to stop formatting):
$ git log -n 1 --date=iso
commit 842c 9649 d24b 4e3e 4d3a 42b1 e75c 8d37 7f54 ae3a (HEAD -> devel, origin/devel)
Author: Edward K. Ream <ed.....@gmail.com>
Date:   2019-06-22 14:30:36 -0500

    Added first draft of 'How to use Leo's bridge in Vim

lewis@Argon MINGW64 /n/git/leo-editor/leo/core (devel)

**Comment by LewisNeal** [comment]
And here are results of starting leo with '--trace=startup' from a console:

N:\git\leo-editor>launchleo.py --trace=startup

reading settings in N:/git/leo-editor/leo/config/leoSettings.leo
reading settings in C:/Users/lewis/.leo/myLeoSettings.leo
Empty setting name in False
set parent @settings
reading settings in C:/Users/lewis/.leo/LeoBlackGraySolarized.leo
getGitVersion return code 1
getGitVersion value b''
Exception in g.getGitVersion
Traceback (most recent call last):

  File "N:\git\leo-editor\leo\core\leoGlobals.py", line 5076, in getGitVersion
    shell=True,

  File "C:\Users\lewis\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 395, in check_output
    **kwargs).stdout

  File "C:\Users\lewis\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 487, in run
    output=stdout, stderr=stderr)

subprocess.CalledProcessError: Command 'git log -n 1 --date=iso' returned non-zero exit status 1.

getGitVersion return code 1
getGitVersion value b''
Exception in g.getGitVersion
Traceback (most recent call last):

  File "N:\git\leo-editor\leo\core\leoGlobals.py", line 5076, in getGitVersion
    shell=True,

  File "C:\Users\lewis\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 395, in check_output
    **kwargs).stdout

  File "C:\Users\lewis\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 487, in run
    output=stdout, stderr=stderr)

subprocess.CalledProcessError: Command 'git log -n 1 --date=iso' returned non-zero exit status 1.

Leo 6.0-b2-devel, devel branch
livecode.py: can not import meta
you can install meta with `pip install meta`
rss.py: can not import feedparser
load_session loading: C:/Users/lewis/.leo/workbook.leo
reading settings in C:/Users/lewis/.leo/workbook.leo
DynamicWindow.__init__ workbook.leo
restoreWindowState workbook.leo found key: windowState:C:/Users/lewis/.leo/workbook.leo
startup time: 13.94 sec
[end]

**Comment by edreamleo** [comment]
To repeat.  I am troubled by you placing the leo-editor folder in the git directory.  This is the only thing that I can think of that might cause confusion.

**Comment by tbnorth** [comment]
If you're referring to the `N:\git` path, I don't think that would be a problem.  I always used
`/home/tbrown/t/Package/leo/git/leo-editor`.  It's not *the* git directory, which would be
`N:\git\leo-editor\.git`, it's just a directory that happens to be called "git".

**Comment by edreamleo** [comment]
On Tue, Jun 25, 2019 at 10:11 AM Terry Brown <notifications@github.com>
wrote:

> If you're referring to the N:\git path, I don't think that would be a
> problem. I always used
> /home/tbrown/t/Package/leo/git/leo-editor. It's not *the* git directory,
> which would be
> N:\git\leo-editor\.git, it's just a directory that happens to be called
> "git".
>

In that case, I am out of ideas.

Edward

**Comment by vitalije** [comment]
I think you have to add `shell=True` argument in calling `subprocess.Popen` when executing git command.
Most probably this is the reason why executing command directly in command prompt works fine, but executing with subprocess fails.
HTH

**Comment by vitalije** [comment]
I see now that `shell=True` is in effect. There is one more thing I can think of.

@LewisNeal  you can try to replace call in N:\git\leo-editor\leo\core\leoGlobals.py line 5073:
```
'git log -n 1 --date=iso'
```
replace `git` with the full path to `git.exe` on your machine.

If Leo reports commit properly, then the problem is that your git.exe is not on your %PATH% and subprocess can't find it.

**Comment by LewisNeal** [comment]
Vitalije your suggestion worked :)
It took a while as there are 3 git.exe files to choose from. The correct full path to git.exe is:
'C:\Progra~1\Git\mingw64\libexec\git-core\git log -n 1 --date=iso'

Note that replacing _C:\Program Files\_ with _C:\%ProgramFiles%\_ did not work.

Here is the log reporting the build number:
_Leo Log Window
Leo 6.0-b2-devel, devel branch, build 679fc6047c
2019-06-25 23:32:30 -0700
Python 3.7.4, PyQt version 5.12.4
Windows 10 AMD64 (build 10.0.17134) SP0_

**Comment by edreamleo** [comment]
Whew!  Many thanks, Vitalije, for figuring this out.

**Comment by LewisNeal** [comment]
Vitalije your suggestion worked :)
It took a while as there are 3 git.exe files to choose from. The correct full path to git.exe is:
'C:\Progra~1\Git\mingw64\libexec\git-core\git log -n 1 --date=iso'

Note that replacing _C:\Program Files\_ with _C:\%ProgramFiles%\_ did not work.

Here is the log reporting the build number:
Leo Log Window
Leo 6.0-b2-devel, devel branch, build 679fc6047c
2019-06-25 23:32:30 -0700
Python 3.7.4, PyQt version 5.12.4
Windows 10 AMD64 (build 10.0.17134) SP0

**Comment by LewisNeal** [comment]
I reinstalled Git to correct my Path issue.
During install there is a selection step required:
[Adjusting your PATH environment]
* Use Git from Bash only
* Git from the command line and also from 3rd-party software

I had always selected 'Use Git from Bash only' which did not modify the PATH at all. 

The preferred choice is now
* Git from the command line and also from 3rd-party software

**Comment by maphew** [comment]
added myself as assignee because I think this intersects with something I was struggling with awhile ago, but details are hazy. Now this issue will show up in the 'assigned to me' filter when I next look for it.
