### ISSUE TITLE
Fix segfaults in python_terminal.py

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#1212]
This plugin can segfaulting *at startup* on Linux (I presume).  The platform:

​Leo 6.0-b2-devel, devel branch, build 0e86a7bf76
2019-06-19 21:25:33 -0500
Python 3.6.8, PyQt version 5.12.3
linux

**Update**: Chris George has found the culprit:

`from rlcompleter import Completer`

As of rev 81a2f1e, PyInterp.doEnter & helpers has been rewritten.  It handles all my test cases without hacks.  This is a milestone.  EKR, not Jake, is fully responsible for previous problems.

**Comment by edreamleo** [comment]
Fixed at b937f02 in devel.

**Comment by edreamleo** [comment]
I'll reopen this because segfaults still happen on Linux.

**Comment by edreamleo** [comment]
Test program.  Put this in a separate file, say segfault_test.py and run it with python, not Leo:

```python

import code
import pdb
import sys
from rlcompleter import Completer
assert Completer
from PyQt5 import Qt, QtWidgets
        
class Test (QtWidgets.QTextEdit):
    
    class InteractiveInterpreter(code.InteractiveInterpreter):

        def __init__(self, locals, c):
            print('(InteractiveInterpreter)', c)
            self.c = c
            loc = locals
            loc['c'] = self.c
            super().__init__(loc)
            
    # End of InteractiveInterpreter class.
    
    def __init__(self, c, parent):
        print('(Test)', repr(c), repr(parent))
        pdb.set_trace()
        super().__init__(parent)
        self.interpreterLocals = {}
        self.c = None
        self.initInterpreter(locals())
    
    def initInterpreter(self, interpreterLocals=None):

        if interpreterLocals:
            # when we pass in locals, we don't want it to be named "self"
            # so we rename it with the name of the class that did the passing
            # and reinsert the locals back into the interpreter dictionary
            selfName = interpreterLocals['self'].__class__.__name__
            interpreterLocalVars = interpreterLocals.pop('self')
            self.interpreterLocals[selfName] = interpreterLocalVars
        else:
            self.interpreterLocals = interpreterLocals
        self.interpreter = self.InteractiveInterpreter(self.interpreterLocals, self.c)
    
def main():
    Qt.QApplication(sys.argv)
    Test(c=None, parent=None)
    
if __name__ == '__main__':
    main()
```

Very strange things happen on my Windows machine.  The call to super().__init__(parent) never returns!

**Comment by technatica** [comment]
The exact same thing happens here.

It places me at the PDB prompt and when I hit n, enter it crashes with the
same old crash.

Then about thirty seconds after the crash I get this in the terminal:

QSocketNotifier: Invalid socket 8 and type 'Read', disabling...


Chris

**Comment by edreamleo** [comment]
On Thu, Jun 20, 2019 at 8:32 AM Chris George <notifications@github.com>
wrote:

> The exact same thing happens here.
>
> It places me at the PDB prompt and when I hit n, enter it crashes with the
> same old crash.
>

That's big progress!  We have found the proximate cause of the bug.

Edward

**Comment by edreamleo** [comment]
On Thu, Jun 20, 2019 at 8:48 AM Edward K. Ream <edreamleo@gmail.com> wrote:

That's big progress!  We have found the proximate cause of the bug.
>

Rev 591ed03 changes this behavior for me, even though I never segfault.

Do you still get the segfault?

Edward

**Comment by technatica** [comment]
Still with the segfault.

But here is the difference for me.

Leo 6.0-b2-devel, devel branch, build 3973f6fae1
2019-06-20 09:31:49 -0500
Python 3.6.8, PyQt version 5.12.3
linux

Before the segfault would generate this message in the terminal:
*QSocketNotifier:
Invalid socket 8 and type 'Read', disabling... *about 30 seconds after the
crash.

Now it generates this:

QSocketNotifier: Invalid socket 10 and type 'Read', disabling...
QSocketNotifier: Invalid socket 16 and type 'Read', disabling...
QSocketNotifier: Invalid socket 10 and type 'Read', disabling...
QSocketNotifier: Invalid socket 16 and type 'Read', disabling...

Chris

**Comment by edreamleo** [comment]
On Thu, Jun 20, 2019 at 9:59 AM Chris George <notifications@github.com>
wrote:

> Still with the segfault.
>
> But here is the difference for me.
>

OK.  I'm going to disable rlcompleter by default.  This has a chance of
being a workaround.  If somebody really wants it, which I doubt, they can
set the switch.

Edward

**Comment by edreamleo** [comment]
On Thu, Jun 20, 2019 at 11:20 AM Edward K. Ream <edreamleo@gmail.com> wrote:

OK.  I'm going to disable rlcompleter by default.  This has a chance of
> being a workaround.  If somebody really wants it, which I doubt, they can
> set the switch.
>

Try 78cbd02.  This is just a more complete way of not importing rlcompleter.

Edward

**Comment by technatica** [comment]
That works just fine.

Python terminal creates a dock and loads with no errors.

Chris

**Comment by edreamleo** [comment]
On Thu, Jun 20, 2019 at 11:32 AM Chris George <notifications@github.com>
wrote:

> That works just fine.
>
> Python terminal creates a dock and loads with no errors.
>

Hurray!  Thanks for the confirmation.

Edward
