### ISSUE TITLE
Bookmarks Plugin Doesn't Create Dock

### ISSUE THREAD

**Issue by technatica** [leo-editor/leo-editor#1214]
I was looking at testing the bookmark stylesheet and discovered that the plugin doesn't create a bookmarks dock.

It works, as I can create a bookmark and it tells me via the log window that it exists when I try to create another but that is about the extent of interaction.

**Comment by edreamleo** [comment]
On Tue, Jun 18, 2019 at 12:34 PM Chris George <notifications@github.com>
wrote:

> I was looking at testing the bookmark stylesheet and discovered that the
> plugin doesn't create a bookmarks dock.
>
I looked at bookmarks.py.  As I have just verified, when using the legacy
gui, bookmarks.py doesn't create a tab in Log pane. So it can create a dock
in the new default gui.

**Comment by edreamleo** [comment]
I am going to reopen this issue.  Iirc, the bookmarks plugin uses the Easter Egg plugin in the legacy gui.  Perhaps in the new gui the bookmarks plugin should automatically open a corresponding dock.

**Comment by edreamleo** [comment]
Fixed at b04f959 in devel.
