### ISSUE TITLE
free-layout plugin with docks

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#1216]
Running (with docks enabled) commit 2463eced3.
enter _free-layout-context-menu_ command:
Leo 6.0-b2-devel, devel branch
Python 3.7.4, PyQt version 5.12.3
Windows 10 AMD64 (build 10.0.17134) SP0
Traceback (most recent call last):

  File "N:\git\leo-editor\leo\core\leoCommands.py", line 2077, in executeAnyCommand
return command(event)

  File "N:\git\leo-editor\leo\plugins\free_layout.py", line 404, in free_layout_context_menu
handle = splitter.handle(1)

AttributeError: 'NoneType' object has no attribute 'handle'

The Toggle-Split-Direction command is hidden when docks are active, and if the command is entered in minibuffer, message 'toggle-split-direction works only when --no-dock is in effect' is displayed.
Should the free-layout plugin should be disabled when docks are active?

**Comment by edreamleo** [comment]
Fixed (for all free-layout-* commands) at rev 9ebfdd2 in devel.
