### ISSUE TITLE
`@auto-rst` should add an empty line after a heading

### ISSUE THREAD

**Issue by joonro** [leo-editor/leo-editor#122]
Currently `@auto-rst` do not add an empty line after a heading. 

The problem is that when one generates a node (call it `Placeholder`) without any contents, then the resulting `rst` file is written like:

```rst
Placeholder
***********
Summary
*******
```

That is, there is no space between the two headings. Then if I do `Refresh from disk`, `@auto-rst` yields an error. This should not happen if `@auto-rst` automatically writes an empty line after each heading.

**Comment by edreamleo** [comment]
I am hoping that @nosent will replace @auto-rst will in the near future.  As a result, this issue is about to become moot.

**Comment by edreamleo** [comment]
I was mistaken.  @clean can not replace @auto-rst.  So I'm removing the "minor" label and targeting this bug for b1.

**Comment by joonro** [comment]
Thanks!

**Comment by edreamleo** [comment]
Rev 4ee37fc attempts a fix, but more testing is needed in a more realistic environment.
I'll close this bug for now.  Please reopen if there are further problems.
