### ISSUE TITLE
gui=console. delete line command d is not working

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#1224]
running commit 3c01565e2
launchleo.py --gui=console

The delete line command d is not working.
Edits to lines are saved, but deleting of lines is not saved.

Leo 6.0-b2-devel, devel branch
Python 3.7.4, PyQt version 5.12.3
Windows 10 AMD64 (build 10.0.17134) SP0

**Comment by LewisNeal** [comment]
Open a leo file. Edit by deleting line/s only.
Select Quit. Leo fully exits and does not give the Yes/No save option. It has not recognised the file has changed.

**Comment by LewisNeal** [comment]
There is one exception. I have confirmed that if you add text after deleting a line, then that line stays deleted.
Running commit 7eb66267d

**Comment by edreamleo** [comment]
Fixed at efb4b7e in devel.

**Comment by LewisNeal** [comment]
Fix confirmed. Thanks.
