### ISSUE TITLE
Render widget not visible: Plugins

### ISSUE THREAD

**Issue by technatica** [leo-editor/leo-editor#1230]
Choosing a plugin from the Plugins menu sends the docstring to the render widget but doesn't make it visible if it is in a nest.

**Comment by edreamleo** [comment]
@technatica Good catch.

**Comment by edreamleo** [comment]
Fixed at d96a2b9 in devel.

**Comment by edreamleo** [comment]
**Important**:  The new code allows the user to move the VR pane only if:
1. @bool use-vr-dock = True and
2. --init-docks appears on the command line.

**Comment by btheado** [comment]
I'm not sure your commit link is correct. I don't see anything related to VR pane in d96a2b9. I wanted to look at the code change to understand why the VR pane is a special case.

I'm using docks for the first time and am trying to understand all the rules.

By playing around for a long while I've been able to puzzle out 4 cases:

1. The outline dock is unchangable
1. The body and tab docks can be moved around every where and are targets for dock nesting
1. The icon bar and minibuffers can be moved only around the edges
1. The VR dock is a target for nesting but isn't allowed to be moved anywhere

Can you explain the reason for case 4?

**Comment by technatica** [comment]
>
>    1. The outline dock is unchangable
>
>
@string central-dock-widget = body

The valid choices are body, tabs, and outline. I spend most of my time in
body so outline and tabs are nesting targets.

HTH,

Chris

**Comment by edreamleo** [comment]
On Fri, Aug 9, 2019 at 4:42 PM btheado wrote:

> 4. The VR dock is a target for nesting but isn't allowed to be moved
anywhere.
> Can you explain the reason for case 4?

The VR dock *can* be moved, but only if --init-docks is in effect.  Here's
why:

By default the VR dock shares area with the body pane, using
QMainWindow.splitDockWidget.  Afaik, there is no way to "redo" this split
operation after you move the VR dock out of the body pane.

So if you really do want to move the VR dock, you can do so, but if later
you decide that's not what you want you have to use --init-docks again.
Clear?

Edward

**Comment by btheado** [comment]
Thanks for the explanation.

> By default the VR dock shares area with the body pane, using QMainWindow.splitDockWidget.

I don't understand what this means. Since you've chosen this as the default, I'm guessing it must be providing some benefit. I'm looking for an explanation like 'if the VR dock doesn't share area with the body pane, then you can't do X' or 'when the VR dock shares area with the body pane, you don't have to do Y'.

I'm having trouble thinking of those explanations on my own.

**Comment by edreamleo** [comment]
On Sat, Aug 10, 2019 at 11:06 AM btheado <notifications@github.com> wrote:

> Thanks for the explanation.
>
> By default the VR dock shares area with the body pane, using QMainWindow.
> splitDockWidget.
>
> I don't understand what this means. Since you've chosen this as the
> default, I'm guessing it must be providing some benefit. I'm looking for an
> explanation like 'if the VR dock doesn't share area with the body pane,
> then you can't do X' or 'when the VR dock shares area with the body pane,
> you don't have to do Y'.
>
I had no choice in the matter.  Afaik, the only way to split a dock is to
use splitDockWidget. That is, the user can't split a dock, only code can.
This appears to be a hole in the gui.  For example, one might want Qt to
allow the user to split a dock with, say, a control-click.  Afaik, this is
not possible.

Edward

**Comment by tbnorth** [comment]
On Sat, 10 Aug 2019 09:28:27 -0700
"Edward K. Ream" <notifications@github.com> wrote:

> On Sat, Aug 10, 2019 at 11:06 AM btheado <notifications@github.com>
> wrote:
> 
> > Thanks for the explanation.
> >
> > By default the VR dock shares area with the body pane, using
> > QMainWindow. splitDockWidget.
> >
> > I don't understand what this means. Since you've chosen this as the
> > default, I'm guessing it must be providing some benefit. I'm
> > looking for an explanation like 'if the VR dock doesn't share area
> > with the body pane, then you can't do X' or 'when the VR dock
> > shares area with the body pane, you don't have to do Y'.
> >
> I had no choice in the matter.  Afaik, the only way to split a dock
> is to use splitDockWidget. That is, the user can't split a dock, only
> code can. This appears to be a hole in the gui.  For example, one
> might want Qt to allow the user to split a dock with, say, a
> control-click.  Afaik, this is not possible.

I think your flags must be limiting what the user can do.  With all
features enabled the user can drop a dock in the top / left /
right / bottom third of another dock to split the other dock and
place the dropped dock adjacent to the other dock.

Just grabbed https://github.com/leo-editor/leo-editor/archive/devel.zip
and could only drag docks between existing docks.

I'm 96% sure this is the case, will try and find my Qt dock branch and
see what it allowed.

Cheers -Terry

**Comment by tbnorth** [comment]
On Sat, 10 Aug 2019 11:59:33 -0500
Terry Brown <terrynbrown@gmail.com> wrote:

> On Sat, 10 Aug 2019 09:28:27 -0700
> "Edward K. Ream" <notifications@github.com> wrote:
>  
> > I had no choice in the matter.  Afaik, the only way to split a dock
> > is to use splitDockWidget. That is, the user can't split a dock,
> > only code can. This appears to be a hole in the gui.  For example,
> > one might want Qt to allow the user to split a dock with, say, a
> > control-click.  Afaik, this is not possible.  
> 
> I think your flags must be limiting what the user can do.  With all
> features enabled the user can drop a dock in the top / left /
> right / bottom third of another dock to split the other dock and
> place the dropped dock adjacent to the other dock.
> 
> Just grabbed
> https://github.com/leo-editor/leo-editor/archive/devel.zip and could
> only drag docks between existing docks.
> 
> I'm 96% sure this is the case, will try and find my Qt dock branch and
> see what it allowed.

Just grabbed 9762778 and indeed you can drop docks on top /
left / right / bottom third of a dock to split.  First you need to go 
Window -> Change Window Layout -> Dockify.

Cheers -Terry

**Comment by btheado** [comment]
I'm not understanding at all. Maybe I need to read the QT documentation in order to understand. What is a dock? What is a pane? What does it mean to "split a dock"?

When I drag the `tabs` UI component and drop it somewhere else, am I splitting a dock? What about when I similarly drag the `body` UI component around?

Could you explain the term "split a dock" from the perspective of dragging and dropping parts of the UI? Or from the perspective of behaviors a user can see.

**Comment by btheado** [comment]
I found this post: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/leo-editor/RSxReAGElbM/zO6goggLBAAJ which says:

> Note that --init-docks puts the Render dock appears alongside the body pane.  This is necessary, because at present there is no way to do so by dragging.  If (and only if!) @bool use-vr-dock is True you may then move the Render dock where you like.

So the render UI component is a special case because otherwise it couldn't be placed alongside the body pane? But that doesn't make sense to me. I can put the tabs UI component alongside the body, so why can't the render component be the same? I guess I'm still missing something. Something special about the render component that isn't obvious to me.

**Comment by edreamleo** [comment]
On Sat, Aug 10, 2019 at 2:09 PM btheado <notifications@github.com> wrote:

So the render UI component is a special case because otherwise it couldn't
> be placed alongside the body pane? But that doesn't make sense to me. I can
> put the tabs UI component alongside the body, so why can't the render
> component be the same? I guess I'm still missing something.


You can place tabs *alongside* other tabs, but there is no way (via
dragging) to place tabs *inside* another tab.  That's what splitDockWidget
does.

Edward

**Comment by btheado** [comment]
Thanks, Edward. What does it help to have the Render component inside the body component? From the word "inside" I would expect that when I drag the body component, then maybe the render component would move along with it, but that doesn't happen. The body component moves around independent of render. The render component can be opened and closed, but when opened it is locked in place.

Am I missing some other behavior which being "inside" provides?

**Comment by edreamleo** [comment]
On Mon, Aug 12, 2019 at 6:29 AM btheado <notifications@github.com> wrote:

> Thanks, Edward. What does it help to have the Render component inside the
> body component?
>
Compatibility with Leo's legacy look and feel.  To see this, run Leo with
--no-docks.

Edward

**Comment by btheado** [comment]
Thanks. If I run leo with `--no-dock` and execute the `vr` command, then I see 4 panes the same as when I run without `--no-dock`.

If I run leo without `--no-dock` and use `--init-docks` and add the `@bool use-vr-dock = True` setting, then I am able to drag the 4 docks into the same 4 pane layout as above.

So are you saying when the VR component is a separate dock, then user actions are permitted to get this 4 pane layout, but programmatically the same cannot be achieved? And that is why you had to treat the VR component as a special case?

**Comment by tbnorth** [comment]
I still think it's worth looking at how freely docks can be re-arranged in 9762778.

You have to remember to enable the dock_layout.py plugin, forgetting that is really confusing :-)

Then after

Window -> Change Window Layout -> Dockify

any dock can be split vertically or horizontally by dropping another dock close to an edge.

You can't mix tabbing and splitting, docks that are tabbed together cannot be split, but that's true of code as well as UI.

Also I think devel's tab pane is a QTabWidget, in 9762778 it's just a group of tabbed docks, so you can tear them of and put them anywhere, create multiple groups of tabbed widgets, etc.

Can't think of any reason the VR widget would need to be a special case - but then again I don't think you want a QMainWindow in the mix at all either, having only docks within just one of the dock areas seems to give the most flexibility.
