### ISSUE TITLE
Picture can not be shown in markdown when using viewrendered

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#1231]
Leo Log Window
Leo 6.0-b2-devel, devel branch, build aaba312c4f
2019-06-26 09:19:58 -0500
Python 3.7.3, PyQt version 5.12.3
darwin

**The same as Ubuntu1804.**

Example:

!\[profile1.png](/home/swot/pyenv/Xservice/XService/doc/pic/md/profile1.png)

**Comment by edreamleo** [comment]
It works for me.  Make sure you use `@language md`. For example:

```
@language md

https://github.com/leo-editor/leo-editor/issues/1231

![bubbles](c:\leo.repo\leo-editor\leo\Icons\bubbles.svg)

![leo icon](C:\leo.repo\leo-editor\leo\Icons\SplashScreen.ico)
```

**Comment by edreamleo** [comment]
Hmm.  You may have to control-click the url's to get them to render the first time...
