### ISSUE TITLE
Disallow multiple section references on a single line in @clean files

### ISSUE THREAD

**Issue by XCaminhante** [leo-editor/leo-editor#1232]
Using fresh install from git tag v5.9 (last stable), reproduction:

1. Create a new outline file (using an existent outline works too)
2. Create a "@clean file" node
"@clean file" node body: `Test <<sect1>> test <<sect2>> test <<sect2>> test <<sect1>>`
3. Create the respective sections as children of "@clean file" (the content doesn't matter)
The @clean tree will looks like this:
```
@clean test.txt
| Test <<sect1>> test <<sect2>> test <<sect2>> test <<sect1>>
`- <<sect1>>
   | Section 1
`- <<sect2>>
   | Section 2
```

4. Close and reopen the .leo file: the outline tab will become unresponsive.

@file trees don't demonstrate the same problem. May be related to #950 

Logs:
[log.txt](https://github.com/leo-editor/leo-editor/files/3355840/log.txt)

**Comment by edreamleo** [comment]
@XCaminhante Thanks for this report.  I'll investigate when I return from vacation.

**Comment by edreamleo** [comment]
@XCaminhante The problem likely arises from having multiple section references on a single line.

**Comment by edreamleo** [comment]
Rev f772c50 completes this issue. I'll leave this issue open during testing.
