### ISSUE TITLE
Display Headline in TitleBar of Body Dock Widget.

### ISSUE THREAD

**Issue by technatica** [leo-editor/leo-editor#1234]
An option to display the headline of a node in the title bar of the body dock widget.

**Summary**: The desired title only appears if there are multiple body editors.  The OP would like an option to have the title bar always visible.

**Comment by technatica** [comment]
Leo already does this!

1. Open Leo. Note that there is no headline displayed below the body titlebar.
2. Alt-x, add-editor. Note that not only does the new editor have the headline displayed below its titlebar but the main body editor also displays it.
3. Close the new body editor. Note that the main body editor continues to display the headline below the titlebar.
4. This functionality continues until you end the session and restart Leo.

**Comment by edreamleo** [comment]
Thanks for the report.

**Comment by technatica** [comment]
So the add-editor command calls self.packLabel(widget) from dw.packLabel and the primary body editor does not. So by default, Leo does not display the headline in or near the titlebar. I must open a new editor and close it every time I want this behaviour and it only lasts for the session.

I cannot figure out how to make this the default. Ideally, this should be an @bool setting.

**Comment by edreamleo** [comment]
> So by default, Leo does not display the headline in or near the titlebar. I must open a new editor and close it every time I want this behaviour and it only lasts for the session.

I am going to reopen this to add this behavior.

**Comment by technatica** [comment]
Also, it would be more intuitive if the headline were to replace the label on the widget and appeared in the title bar.

ie. instead of Body or in the case of the add-editor, Body-2.

**Comment by edreamleo** [comment]
This issue is moot. Leo no longer uses Qt docks.
