### ISSUE TITLE
Active Path Plugin is Broken

### ISSUE THREAD

**Issue by technatica** [leo-editor/leo-editor#1237]
e288502 works.
af17f9e  doesn't.

Changes were made to the active path plugin to make pylint happy.

Except the plugin now doesn't work.

**Comment by edreamleo** [comment]
On Fri, Jul 5, 2019 at 2:11 PM Chris George <notifications@github.com>
wrote:

> e288502
> <https://github.com/leo-editor/leo-editor/commit/e288502180ed757ebed5b1c9211054696cb145e5>
> works.
> af17f9e
> <https://github.com/leo-editor/leo-editor/commit/af17f9ee4a120be785e961056f323133ad8ed0bf>
> doesn't.
>
> Changes were made to the active path plugin to make pylint happy.
>
> Except the plugin now doesn't work.
>

Oops.  Sorry about that.  I'll revert to the old code when I can, and just
suppress the pylint warnings.

Edward

**Comment by edreamleo** [comment]
On Sat, Jul 6, 2019 at 6:09 AM Edward K. Ream <edreamleo@gmail.com> wrote:

>
>
> On Fri, Jul 5, 2019 at 2:11 PM Chris George <notifications@github.com>
> wrote:
>
>> e288502
>> <https://github.com/leo-editor/leo-editor/commit/e288502180ed757ebed5b1c9211054696cb145e5>
>> works.
>> af17f9e
>> <https://github.com/leo-editor/leo-editor/commit/af17f9ee4a120be785e961056f323133ad8ed0bf>
>> doesn't.
>>
>
Oops.  Sorry about that.  I'll revert to the old code when I can

Done at 5692765.

Edward

**Comment by edreamleo** [comment]
Code reverted at 5692765. Pylint warnings suppressed at ec638cb.

**Comment by maphew** [comment]
Thank you. I have had active_path turned off while troubleshooting other stuff, for a few weeks now, but it's something I use quite a bit, albeit episodically.
