### ISSUE TITLE
gui=console. Backspace, delete keys not working.

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#1238]
e to edit line, backspace to delete text. Press esc and the line highlights but is unchanged.

Select Quit. Leo fully exits and does not give the Yes/No save option. It has not recognised the file has changed.

Leo Log Window
Leo 6.0-b2-devel, devel branch, build 12f7a1bb6d 2019-07-05 10:48:53 -0700
Python 3.7.4, LeoGui: dummy version Windows 10 AMD64 (build 10.0.17134) SP0

**Comment by edreamleo** [comment]
The del key does not appear to work anywhere.  I'll do this only if you can convince me that it is necessary.

The backspace key works in both the body and headlines, but you may have to futz with it.

**Comment by edreamleo** [comment]
Fixed at 3cc35fc in devel.

**Comment by LewisNeal** [comment]
Noted. Delete key works if other edits are made.

**Comment by edreamleo** [comment]
I'll take another look.
