### ISSUE TITLE
my-leo-settings-leo command not working

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#1239]
my-leo-settings-leo command does not open myLeoSettings.leo file.
The leo-settings-leo command works.

Leo Log Window
Leo 6.0-b2-devel, devel branch, build cd52639077
2019-07-07 06:26:07 -0700
Python 3.7.4, PyQt version 5.13.0
Windows 10 AMD64 (build 10.0.17134) SP0

**Comment by technatica** [comment]
The command is my-leo-settings, not my-leo-settings-leo.

It is inconsistent with leo-settings-leo but it works.

Chris

**Comment by LewisNeal** [comment]
The command is referred to in the Tips window:
LeoDocs.leo#Leo's Documentation-->Tutorials-->@rst html\tutorial-tips.html-->Learning to use Leo-->Put personal settings myLeoSettings.leo

- The my-leo-settings-leo command opens myLeoSettings.leo.

Chris is right, command _my-leo-settings_ does open myLeoSettings.leo file.
Either the command or LeoDocs needs updating.

**Comment by technatica** [comment]
Changing the name of the command would be more consistent.

At that point though, changing the name of the leo-settings-leo command by
dropping the -leo off the end of it and changing the documentation would
also be consistent and wins by being simpler as well seeing as someone will
need to be addressing the issue anyway.

I will see what I can do.

Chris

**Comment by technatica** [comment]
Fixed at c5dc9d8.

Please test and let me know if it works for you.

**Comment by LewisNeal** [comment]
The fix is simpler and works fine. Thanks

**Comment by edreamleo** [comment]
On Mon, Jul 8, 2019 at 8:42 AM Chris George <notifications@github.com>
wrote:

> The command is my-leo-settings, not my-leo-settings-leo.
>
> It is inconsistent with leo-settings-leo but it works.
>

This kind of inconsistency shouldn't cause real problems.  The Aha, dating
back to emacs itself, is that you can use tab-completion on all command.  I
use <Alt-x>my<tab><return>, so the "tail" doesn't matter.

This is a truly important point.  There is no need ever to memorize (or
type!) full command names.  Just remember a unique prefix, and then type
<tab><return>.

Edward
