### ISSUE TITLE
restore leo-console wrapper launch script

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#1241]
the `leo-console` wrapper script for `python launchLeo-console.py` was dropped from setup.py awhile ago when troubleshooting. Re-instate it.

**Comment by edreamleo** [comment]
@maphew Let's do this for 6.0.

**Comment by maphew** [comment]
Fixed in 0a08fb6d6077576823624b26352e9cf45ec6afad, was easier than expected. I was replacing the script wrapper list instead of adding to it.
