### ISSUE TITLE
Harmonize Leo and Pip version numbers

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#1242]
Leo's self reported and Pip's reported version numbers should agree with each other and they don't.

A chicken and egg problem. Part of this is because pip doesn't have (guaranteed) access to Git. 

Currently this issue is a sign-post for Matt, a place to come back to later. I don't expect to spend attention on it in the near future.

```
$ pip show leo
Name: leo
Version: 6.0b1.dev76
Summary: An IDE, PIM and Outliner
Home-page: http://leoeditor.com
Author: Edward K. Ream
Author-email: edreamleo@gmail.com
License: MIT License
Location: d:\code-maphew\leo-editor
Requires: PyQtWebEngine, docutils, meta, nbformat, pylint, pyflakes, sphinx, future, six, PyQt5, flexx
Required-by:
```
```
$ leo-messages --version

Leo 6.0-b2-devel, desktop-links branch, build 47d7d8802c
2019-07-09 12:34:41 -0700
```

**Comment by maphew** [comment]
**Notes:**
_I'll be revising this comment continually instead of replying._ 

- `leo-m --version` returns _version_ var from `leoversion.py` (a static string), plus some other info if available:
  - branch (from _g.gitBranchName()_ ?)
  - build (from `leoGlobals.py` _g.getGitVersion()_, which is parsed from `git log -n 1`
- `setup.py` (and thus pip) version is built from _g.gitDescribe()_, which is parsed from `git describe`.

**Mismatches:**
Git describe returns different version tag from the static version in `leoversion.py`. Why?
...because the workflow is:
 1.  update static to `v6.0-b1` (a master branch release) [b1d9a0ec]
 2. create git tag for that v: `v6.0-b1-rel` [445dfa14]
 3. Initiate development: update static to `v6.0-b2-devel` to reflect that _"we're now working on the next version"_ [84afef0b]

Leo self reports version from 3. Git reports from it's tag log, which doesn't know about "initiate development" step. Put another way, Leo is forward looking and git is backward looking.


```
$ leo-m --version

Leo 6.0-b2-devel, devel branch, build 72128bce61
2019-07-24 11:00:48 -0500

$ git log -n 1 --date=iso
commit 72128bce61ed79d453a161d89d78fb86d3b56d20 (HEAD -> devel, origin/devel)
Author: Edward K. Ream <edreamleo@gmail.com>
Date:   2019-07-24 11:00:48 -0500

    Fixed #1257 and removed disabled code

$  git describe --long --tags
v6.0b1-110-g72128bce6
```

**Comment by maphew** [comment]
_moving the thinking out loud stuff to the mailing list:https://groups.google.com/d/topic/leo-editor/CWPOS4AxD5Y/discussion_

**Comment by maphew** [comment]
done in 7ce1b76. Now it's waiting for the next release cycle to see if it holds together.

**Comment by edreamleo** [comment]
@maphew Looks good.  I'll close this now to mark the end of the present work.  You can always reopen if necessary.
