### ISSUE TITLE
Desktop integration: Scripts for creating and removing Menu and Desktop links

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#1243]
sub-task to #1012 

Investigate 

* shortcutter - https://github.com/kiwi0fruit/shortcutter - _Easy cross-platform creation of shortcuts supporting virtual and Anaconda environments_
* install_freedesktop - https://github.com/welshjf/install_freedesktop - circa 2015, Linux _Setuptools extension to install freedesktop.org app icons_
* pyshortcuts - https://github.com/newville/pyshortcuts/ - _create desktop shortcuts to python scripts on Windows, Mac, or Linux_. small project so far, but does icons and has both GUI and command line

## Status
_2019-08-20_
Decided to try Shortcutter first. If it works well enough might just stop here.

- [x] Script to add shortcuts
- [x] Script to remove shortcuts _(done, with caveat)_ 
- [ ] Add icons to shortcuts
  - [x] icon support to Shortcutter fork
  - [ ] icon support PR merged to Shortcutter main
- [ ] merge to devel

**Comment by maphew** [comment]
3e2987b62 adds a Shortcutter script to Desktop-Integration.leo. 
Works on Win 10, maybe more.

What's Next:

 [ ] Record location of the created shortcuts so they can be removed later with a script
 [ ] Add icons (this will be more work as Shortcutter doesn't have that concept yet)

**Comment by maphew** [comment]
on record location of shortcuts front: https://stackoverflow.com/questions/57311988/where-is-pips-list-of-files-to-remove-for-a-package/

**Comment by edreamleo** [comment]
On Thu, Aug 1, 2019 at 11:17 AM matt wilkie <notifications@github.com>
wrote:

> on record location of shortcuts front:
> https://stackoverflow.com/questions/57311988/where-is-pips-list-of-files-to-remove-for-a-package/
>
Good.  I'll look forward to the results.

Edward

**Comment by maphew** [comment]
As of 171f32341b79d56368c6cbdab8707b4e96d5bd33 the scripts to add and remove desktop and menu links now includes icons as well. Only in desktop-links branch so far because it relies on my fork of Shortcutter. To test:

```
git clone https://github.com/maphew/shortcutter.git
pip install -e shortcutter

cd leo-editor
git pull
git checkout desktop-links
```

then:

Run Leo >> Settings >> Open desktop integration >> [add-desktop-links] button.

Or any combination of:

```
python leo\scripts\add-desktop-links.leox
python leo\scripts\remove-desktop-links.leox

leo --script leo\scripts\add-desktop-links.leox
leo --script leo\scripts\remove-desktop-links.leox
```

**Comment by maphew** [comment]
Now working on Linux as well as Windows. Waiting for PR to pass review and be accepted into upstream project - https://github.com/kiwi0fruit/shortcutter/pull/14 before merging with devel

**Comment by edreamleo** [comment]
On Tue, Aug 20, 2019 at 11:19 PM matt wilkie <notifications@github.com>
wrote:

> Now working on Linux as well as Windows. Waiting for PR to pass review and
> be accepted into upstream project - kiwi0fruit/shortcutter#14
> <https://github.com/kiwi0fruit/shortcutter/pull/14> before merging with
> devel
>

Thanks for all this work.

Edward

**Comment by maphew** [comment]
Thanks. It's been fun, one of the few code projects I've attempted that I get a sense of momentum from and progress to the goal. My vision usually far outstrips my capacity!

**Comment by maphew** [comment]
This complete. Whew, a long journey, but much learning and growth along the way. Merged into devel
