### ISSUE TITLE
Desktop integration: Document how to use the scripts

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#1244]
sub-task to #1012 

Update/write the user facing instructions for how to use the scripts

**Comment by maphew** [comment]
part way there with 19aef04dead2242f7633b0f80fdfde. Also see discussion at https://groups.google.com/d/msg/leo-editor/h7ViCFo2J84/V0VVm9KLAgAJ

**Comment by maphew** [comment]
I moved the Windows registration scripts into their own .leo file and created buttons for them. 
See `leo\scripts\Desktop-integration.leo`

Merged into devel branch with commit 986810e6929ea5821fac9f9430c023aba2c74c5e

This is changing the focus of this issue title, since I'm changing behaviour as well as writing instructions. They're both the same thing though: helping users understand how to accomplish the task, with minimum of fuss.

Next thing is to decide how to expose this .leo file to users. Discussion thread at:
https://groups.google.com/d/topic/leo-editor/XtO_Ke3nQn4/discussion

**Comment by maphew** [comment]
91ca5fe461267f823508c6ab1add47028fb3fb81 adds "Open Desktop-integration" to Settings menu.

The text feels too long, wordy, but I don't know what to use instead.

This is totally new ground for me. I don't if this the recommended approach, but it works. Mostly I just tried to copy what "Open specific leo file >> scripts.leo" does.

**Comment by edreamleo** [comment]
On Sun, Jul 14, 2019 at 4:42 AM matt wilkie <notifications@github.com>
wrote:

> 91ca5fe
> <https://github.com/leo-editor/leo-editor/commit/91ca5fe461267f823508c6ab1add47028fb3fb81>
> adds "Open Desktop-integration" to Settings menu.
>
I don't see this rev.  Did you push it to devel?

Edward

**Comment by maphew** [comment]
it's in `desktop-links` branch. Being cautious because it touches `LeoPy.leo` and `leoSettings.leo` and I don't know those well.

**Comment by edreamleo** [comment]
On Sun, Jul 14, 2019 at 10:03 PM matt wilkie <notifications@github.com>
wrote:

> it's in desktop-links branch. Being cautious because it touches LeoPy.leo
> and leoSettings.leo and I don't know those well.
>

Looks good to me.

Edward

**Comment by maphew** [comment]
Thanks for looking! Merged to devel with c81fa9b

**Comment by maphew** [comment]
Commit b39dd59 revises "Installing on Windows" docs. Please review.

I removed the entirety of using `assoc` and `ftype` as Microsoft removed the ability to set ftype from command line with Win10. The commands are still useful for reporting on the settings and might want to be shelved somewhere for possible re-use and troubleshooting, but they don't need to be in Getting Started style docs.

**Comment by edreamleo** [comment]
I am going close this issue.  It appears that the desktop-links branch is up to date with devel.

**Comment by edreamleo** [comment]
On Tue, Jul 23, 2019 at 2:01 AM matt wilkie <notifications@github.com>
wrote:

> Commit b39dd59
> <https://github.com/leo-editor/leo-editor/commit/b39dd59f0dbbc7f96f063b66f0e5764e5fa8a7ee>
> revises "Installing on Windows" docs. Please review.
>
The "Settings:Desktop Integration" item is excellent.

Edward

**Comment by maphew** [comment]
thank you :)
