### ISSUE TITLE
descendentVnodeUnknownAttributes now polluting the .leo file

### ISSUE THREAD

**Issue by SegundoBob** [leo-editor/leo-editor#1245]
## Background

Fairly recently temporary data of no long-term interest such as node marks were moved out of the .leo file an into the cache.  This eliminated node marking differences from git diffs.

I believe the descendentVnodeUnknownAttributes data shown in the git diff below is temporary data of interest only to Leo-Editor code and is of no long-term interest.  Or it is pure garbage that should never have been created. Hence, it should not pollute the .leo file.  It should be eliminated or moved to the cache.
```
-<v t="bob.20180801113522.1"><vh>@file txt/to-do.txt</vh></v>
+<v t="bob.20180801113522.1" descendentVnodeUnknownAttributes="7d7100285803000000302e3071017d7102580b0000005f5f626f6f6b6d61726b7371037d7104580700000069735f6475706571054930300a73735803000000302e3171067d710768037d710868054930300a73735803000000302e3271097d710a68037d710b68054930300a73735803000000302e33710c7d710d68037d710e68054930300a73735803000000302e34710f7d711068037d711168054930300a73735803000000302e3571127d711368037d711468054930300a73735803000000302e3671157d711668037d711768054930300a7373752e"><vh>@file txt/to-do.txt</vh></v>
```
I have no idea why this data was suddenly added to my .leo file.  The "descendant vnodes" do not have any attributes that I can see.

This grep doesn't suggest anything to me:
```
2019-07-11 15:35:27 /pri/git/leo-editor/leo/core
$ grep -i descendentVnodeUnknownAttributes *.py
leoFileCommands.py:        'descendentVnodeUnknownAttributes',
leoFileCommands.py:                    s = d.get('descendentVnodeUnknownAttributes')
leoFileCommands.py:            'descendentVnodeUnknownAttributes', # New in Leo 4.5.
leoFileCommands.py:    # New in Leo 4.5: @thin & @shadow vnodes have descendentVnodeUnknownAttributes field.
leoFileCommands.py:            torv=p.v, val=d, tag='descendentVnodeUnknownAttributes') or ''
2019-07-11 15:35:41 /pri/git/leo-editor/leo/core
```

I don't know when I'll have time to spend on this problem.

## Test Systems
```
Leo Log Window
Leo 6.0-b2-devel, devel branch, build aaba312c4f
2019-06-26 09:19:58 -0500
Python 3.6.8, PyQt version 5.11.1
linux
import-jupyter-notebook requires nbformat package
```

**Comment by edreamleo** [comment]
@SegundoBob I'll look into this.

**Comment by edreamleo** [comment]
This is likely related to #1247.

**Comment by edreamleo** [comment]
The show-all-uas command should help you see what is going on.

**Comment by edreamleo** [comment]
I am going to close this issue.  Please reopen if it's not possible to prevent pollution by disabling various plugins.

**Comment by SegundoBob** [comment]
## show-all-uas

show-all-uas shows **NO** uas in the last three commits of the .leo file that caused me to report this issue.


## Disable bookmarks plugin

I will disable the bookmarks plugin.  I will use clear-all-uas and clear-node-uas to clear all bookmarks plugin uas shown by show-all-uas.  If despite these measures, this issue continues to bother me, I will make a report here.

**Comment by SegundoBob** [comment]
## __bookmarks= in Leo-Editor Project files
Since EKR seemed to indicate that he has never used the bookmarks plugin, this may be of interest.

In Revision
```
Leo 6.0-b2-devel, devel branch, build aaba312c4f
2019-06-26 09:19:58 -0500
```
There are nine occurrences of __bookmarks= in the leo-editor/leo/themes/ directory.

## descendentVnodeUnknownAttributes= in Leo-Editor Project files

The following may be expected and all right.

In Revision
```
Leo 6.0-b2-devel, devel branch, build aaba312c4f
2019-06-26 09:19:58 -0500
```
There are 4 occurrences of descendentVnodeUnknownAttributes= in directory leo-editor/build/.
There is 1 occurrence of descendentVnodeUnknownAttributes= in directory  leo-editor/scripts/.
There are 2 occurrences of descendentVnodeUnknownAttributes= in directory leo-editor/test/.
There are 2 occurrences of descendentVnodeUnknownAttributes= in directory leo-editor/doc/.
There are 3 occurrences of descendentVnodeUnknownAttributes= in directory leo-editor/core/.

**Comment by edreamleo** [comment]
I am going to reopen this and assign it to 6.0.  The bookmarks plugin is not likely the culprit.

**Comment by edreamleo** [comment]
@SegundoBob You misunderstood me.  I enable the bookmarks plugin often for testing purposes.

Thanks for your investigation into the __bookmarks uas in the themes directory.  I have just verified that none of the .leo files in leo/themes contain an `@enabled-plugins` node.  As a result, they all use the plugins in leoSettings **and** myLeoSettings.leo.

So disabling bookmarks.py in your personal copy of myLeoSettings.leo should end the "pollution".

I am going to close this issue once again.  As always, feel free to reopen.
