### ISSUE TITLE
gui=console. Crash when vr commands given

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#1248]
I understand that the viewrendered plugin is not functional in console gui mode.
However if a vr command is given, Leo crashes completely.

[snip]
loading npyscreen
Leo 6.0-b2-devel, devel branch, build d96a2b9eff
2019-07-11 17:03:10 -0500
QWidget: Must construct a QApplication before a QWidget

**Comment by edreamleo** [comment]
@LewisNeal Should be easy to fix.

**Comment by LewisNeal** [comment]
Also occurs in gui=browser mode. LeoWapp closes with message 'lost connection with server'.

**Comment by edreamleo** [comment]
Fixed at a54793f in devel.
