### ISSUE TITLE
print-buttons command missing or renamed

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#1249]
at http://leoeditor.com/commands.html it says:

>print-buttons
>    Print all @button and @command commands, their bindings and their source.

but that command doesn't seem to exist anymore. 

```
Leo 6.0-b2-devel, desktop-links branch, build 0a08fb6d60
2019-07-11 14:46:11 -0700
Python 3.6.2, PyQt version 5.12.3
Windows 10 AMD64 (build 10.0.17134) SP0
```

**Comment by edreamleo** [comment]
The command's name has been changed to show-buttons.

Fixed the docs at a94dcab in devel.
