### ISSUE TITLE
website docs have mixed version numbers

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#1250]
http://leoeditor.com/scripting.html says it's "Leo 4.11 documentation" and not 6.0.  Might apply to other pages too.

(should version number even be mentioned unless we have different version manuals online at the same time? probably not.)

**Comment by edreamleo** [comment]
@maphew Imo, version numbers *should* be mentioned.  It is a check against links to ancient web sites.

**Comment by edreamleo** [comment]
On Fri, Jul 12, 2019 at 1:46 AM matt wilkie <notifications@github.com>
wrote:

> http://leoeditor.com/scripting.html says it's "Leo 4.11 documentation"
> and not 6.0. Might apply to other pages too.
>

As I said in the issue, version numbers are important.  Indeed, the link
you mention is very old.  The modern link is tutorial-scripting.html.

The old links appear in the tutorial slideshow, and in the wikipedia
entry.  I'll fix them immediately.

Edward

**Comment by edreamleo** [comment]
Fixed

Fixed at 062e027 in devel:

- The wikipedia entry in LeoDocs.leo is ancient.  I've updated it from wikipedia.
- Also fixed links in slideshow.txt.
