### ISSUE TITLE
Support asciidoc syntax coloring

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#1253]
- [x] Add asciidoc to the list of all language directives in @rst html/directives.html in LeoDocs.leo.
- [x] Add leo/modes/asciidoc.py.
- [x] Create proper leo/modes/asciidoc.py.
  Used @button jEdit2Py (in scripts.leo) applied to [asciidoc.xml](https://github.com/salchint/asciidoc4jedit/blob/master/asciidoc.xml).

**Comment by edreamleo** [comment]
@maphew Good catch.  Leo needs to syntax color asciidoc correctly.  This will be done in 6.1.

**Comment by edreamleo** [comment]
Completed at rev 3c1f5b8 in devel.
