### ISSUE TITLE
switch setupext-janitor source

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#1255]
the fix for #1055 was to bundle a patched 3rd party module **setupext-janitor**. Upstream [has been fixed](https://github.com/dave-shawley/setupext-janitor/pull/14) so we don't need to bundle anymore.

Used in setup.py to extend clean command (namely: adds `--all` parameter to get rid of more stuff). Might have to add to `setup_requires` list instead.

**Comment by maphew** [comment]
No, not `setup_requires`, this goes into `pyproject.toml` instead, see https://www.python.org/dev/peps/pep-0518/.

However I do a concern with this course. I think I've observed, but not measured, that putting small things like setupext-janitor into a "fetch at install time" process instead of just including it adds significantly to the time it takes to install. Especially as more things are added to the build requirements. I don't think these are saved, so the downloads are invoked every time.

**Comment by maphew** [comment]
Ok, we add janitor to both `setup.py: user_requires[]` AND `pyproject.toml`. Setup, so that it is installed in the system and available for future re-use, and `.toml` so that it is installed in virgin environment build systems (e.g. Travis CI).

I am so looking forward to the day I spend my lunch hour improving UX and adding features instead of reading the endlessly confusing packaging docs.

**Comment by maphew** [comment]
re: 74cbfdeb - In order to build wheels in Travis we need to premptively install setupext-janitor. Pip is okay because it reads the requirement from the `.toml`, but `python setup.py bdist_wheel` doesn't know about that route.

**Comment by edreamleo** [comment]
On Thu, Jul 18, 2019 at 3:38 PM matt wilkie <notifications@github.com>
wrote:

> Ok, we add janitor to both setup.py: user_requires[] AND pyproject.toml.
> Setup, so that it is installed in the system and available for future
> re-use, and .toml so that it is installed in virgin environment build
> systems (e.g. Travis CI).
>
> I am so looking forward to the day I spend my lunch hour improving UX and
> adding features instead of reading the endlessly confusing packaging docs.
>

Many thanks for this work.  It's an ugly, highly important part of Leo.

Edward

**Comment by maphew** [comment]
Thanks for the thanks :)  Looking at some of my Leo history I see I've been polishing this install-experience stone for a very long time now.  Hopefully the inner beauty is starting to show through!
