### ISSUE TITLE
vr-lock gets overwritten.

### ISSUE THREAD

**Issue by technatica** [leo-editor/leo-editor#1256]
Leo 6.0-b2-devel, devel branch, build 98b0f97aea
2019-07-14 08:34:03 -0700
Python 3.6.8, PyQt version 5.12.3
linux

1. Load an html page in Leo.
2. Bring the Render dock to the foreground.
3. Choose Plugins, Viewrendered, vr-lock.
4. Select another node.

The first node remains (it is locked) in the rendered dock and the second node is rendered over top.

It worked in the legacy gui because the second node wouldn't be rendered into a dock unless the user opened another vr pane. Now that all nodes are pushed into the only rendered pane the UI is allowed the vr-lock feature is useless.

**Comment by technatica** [comment]
nb. Alt-0 does nothing.

**Comment by technatica** [comment]
Now I am really confused as to how the whole vr-lock thing is supposed to work.

Under the old UI I would choose a node and vr-lock it. Then I would navigate somewhere else and use the vr-lock as a source for info to copy/paste or type into another node. At any time I could hit Alt-0 to open a new vr pane and lock some other node into it.

Now I can vr-lock a node and navigate somewhere else and do what I used to do. But I cannot unlock so the render dock widget remains stuck on the locked node. Alt-0 opens the quick nav panel. In fact, I can see no way to open a new vr pane. Closing the existing vr-locked render pane doesn't really close it, it just hides it. It remains locked, preventing any other node from being rendered.

**Comment by edreamleo** [comment]
On Fri, Jul 26, 2019 at 4:50 PM Chris George <notifications@github.com>
wrote:

> Now I am really confused as to how the whole vr-lock thing is supposed to
> work.
>
Perhaps I am the one confused. At any rate, vr-lock is working as I expect,
and as the viewrendered sources lead me to expect.

Afaik, there has always only been one official "rendering" pane, though I
suppose one could use the Easter Egg interface to open multiple rendering
panes.  That's not possible with docks: there is only ever one Render dock.

Edward
