### ISSUE TITLE
Hard crash in @contextmenu plugin if file not found

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#1257]
My leo file has a node [no body text]:
@mime >@path example.pdf

Right-click over the node to open the example.pdf file.
There are 2 options:
  Create dir C:\Users\lewis\...\example.pdf
  Open C:\Users\lewis\...\example.pdf

Select Open and leo hard crashes:
Traceback (most recent call last):
  File "N:\git\leo-editor\leo\plugins\contextmenu.py", line 260, in openfolder_rclick_cb
    g.os_startfile(path)
  File "N:\git\leo-editor\leo\core\leoGlobals.py", line 7159, in os_startfile
    os.startfile(quoted_fname)
FileNotFoundError: [WinError 2] The system cannot find the file specified: '"C:/Users/lewis/OneDrive - Efficiency Filters Pty Ltd/example.pdf"'
[end]

Leo Log Window
Leo 6.0-b2-devel, devel branch, build c81fa9b10f
2019-07-16 16:25:41 -0700
Python 3.7.4, PyQt version 5.13.0
Windows 10 AMD64 (build 10.0.17134) SP0

**Comment by LewisNeal** [comment]
The fix works. Leo now gives log pane message 'file not found:'

**Comment by edreamleo** [comment]
@LewisNeal Thanks for the confirmation.
