### ISSUE TITLE
A nit with @outline-data tree-abbreviations

### ISSUE THREAD

**Issue by technatica** [leo-editor/leo-editor#1259]
I use these extensively in my work.

When creating a new one I usually start with an @clean node:

`@clean /home/chris/Working/Music/ASinging/<|title|>.txt`

My nit is that when I save the .leo file with this abbreviation (whether it is in the applicable .leo file or in myLeoSettings.leo) it saves this @clean node as a file <|title|>.txt which while not technically a bug is annoying.

**Comment by edreamleo** [comment]
On Sun, Jul 21, 2019 at 10:01 AM Chris George <notifications@github.com>
wrote:

> I use these extensively in my work.
>
> When creating a new one I usually start with an @clean
> <https://github.com/clean> node:
>
> @clean /home/chris/Working/Music/ASinging/<|title|>.txt
>
> My nit is that when I save the .leo file with this abbreviation (whether
> it is in the applicable .leo file or in myLeoSettings.leo) it saves this
> @clean <https://github.com/clean> node as a file <|title|>.txt which
> while not technically a bug is annoying.
>

I assume you have an abbreviation that creates this line.  Just after
writing <the abbreviation>;; you are supposed to type ,, (two comments).
Does that not work in headlines?

Edward

**Comment by technatica** [comment]
Rereading this, I wasn't very clear.

The @clean headline is the abbreviation and it works perfectly as an abbreviation. My beef is that when I save the myLeoSettings.leo file that it saves <|title|>.txt as a file when I don't actually want it to.

Deleting it from the file system doesn't work as it then leads to endless carping about the "file not found" everytime I open the settings file.

The desired behaviour, for me, would be to have abbreviations like this *not* save the abbreviation itself as an actual file.

**Comment by vitalije** [comment]
You can put `@ignore` in the parent body `@outline-data`  and Leo will ignore `@clean` children when saving outline.

**Comment by technatica** [comment]
Works perfectly.

Thanks.
