### ISSUE TITLE
Add window panel on/off to Window Menu

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#1261]
Toggling the various panels on - Render, Tabs, Body, ... - is in the hidden easter egg menu of right-click on menu-bar area. It  would be  good to expose this in the Window menu also (or instead).

see https://groups.google.com/d/topic/leo-editor/AAAb3blAFI8/discussion

**Comment by edreamleo** [comment]
Added the show-hide-*-dock commands and corresponding items in the Windows menu.
