### ISSUE TITLE
Command-line arg to open a window at a given location

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#1263]
Paul Jackson:  From [this thread](https://groups.google.com/forum/#!topic/leo-editor/vdyPcWokqcg). I would like Leo to startup with its main window at a specific location (upper left corner at <x,y> == <245, 162>, size of <hor,ver> == <2315, 1276>).

How do I do that?

I am seeing various potentially relevant variables and names in the code, documentation, settings and command line arguments,  such as
```
fixedwindow
fixed_window
fixedWindow
fixedWindowPosition
fixedWindowPositionData
windowPosition
--window-size=...
--session-restore
--session-save
```
including a comment in the change history for some release in 2018 that I vaguely recall reading that some of the above no longer mattered, and the above apparent conflicting naming of the {fixedwindow, fixed_window, fixedWindow} boolean that apparently must be True to enable the {fixedWindowPosition, fixedWindowPositionData} setting, and another comment that EKR was unsure whether the {--session-save, --session-restore} worked.

**Comment by technatica** [comment]
This has the makings of a can of worms. Each platform has its own window manager and its own way of positioning an application. My feeling is that the window manager is the right place for this, not the app.

Examples of problems are easy to think of. What if I want Leo to display maximized on screen number four of my array? What if I want Leo to display over the network using X11 to display on a remote screen? What if I prefer Leo on screen two at a certain size?

Trying to pre-guess all the different possibilities seems to be a problem.

**Comment by ThePythonicCow** [comment]
Thanks for considering this, Ed.  May the Gods of simplicity and doability be with you.

The Zim wiki-like Notebook software, https://zim-wiki.org/index.html, handles this, at least for Linux, BSD and Windows, with a --geometry command line option:
`--geometry       window size and position as WxH+X+Y`
This makes no effort to decide which display panel to use ... but only tries to place the Zim window on whatever is the current or default panel (whatever that means.)  Zim is written in Python and Gtk.

The Dillo web browser, nedit text editor, and various ImageMagick and X11 utilities also have similar --geometry options, but I don't know if that's relevant here.

If the Leo command line option "--window-size=..." works as it's name suggests, then it seems to me that Leo is already doing half of this --geometry option, and perhaps could also be able to place the window at some <X, Y> position with little or no further assumptions as to the underlying system or its capabilities.  The following Qt discussion appears to consider some of this in more detail: https://doc.qt.io/archives/4.3/geometry.html

But I am no expert in such matters ... so I leave the fate of this in your good hands.

**Comment by edreamleo** [comment]
Thanks for the recent comments.  I am going to delay this to 6.1.  The various pieces of the puzzle are too complex to handle in 6.0.

**Comment by edreamleo** [comment]
Completed at 6eb5b39 in devel.  Example: `--window-spot=50x100`

**Comment by ThePythonicCow** [comment]
Thanks

**Comment by edreamleo** [comment]
On Mon, Sep 23, 2019 at 5:37 PM Paul Jackson <notifications@github.com>
wrote:

> Thanks
>
You're welcome.  This will be useful.

Edward
