### ISSUE TITLE
Persistent body editors

### ISSUE THREAD

**Issue by technatica** [leo-editor/leo-editor#1268]
Body editors created using "add-editor" should be saved between sessions.

**Aha**: Qt does *not* create frames automatically. It simply positions them, presumably by objectName, when/if they *are* created. 

Rev bf16967 in the docks2 branch appears to work. More testing is needed.

- app.saveEditorDockState saves the dock name and its associated archived position.
- app.restoreEditorDockState creates a new editor dock from the saved data.

**Note**: The objectName property of all docks and tool bars must be unique for Qt's save/restore magic to work.

**Comment by edreamleo** [comment]
I am going to close this issue. Please reopen if necessary.
