### ISSUE TITLE
Bracket matching is buggy

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#127]
Bracket matching should take into account the language in effect.

For example, JavaScript regular expressions are not handled properly.

**Comment by CandyAngel** [comment]
Not sure if this is related, but quite often when using Perl's regular expressions (with "@language perl"), Leo will stop responding for a long time (seems to get exponentially worse the more braces are in the node's body) as I write or modify it.

For example, if I attempt to change:
> my $regex = qr/test matching something/;

to:

> my $regex =  qr{test matching something};

Leo will freeze for just a couple of seconds. However, if I try to change:

> my $regex = qr/test (matching) something/;

to:

> my $regex =  qr{test (matching) something};

Leo will freeze for ~10 seconds.

The more braces in the node body, the longer the freeze is (in the instance I just got, there are 4 "()" pairs and 2 "{}" pairs and I force-closed Leo after more than 20 minutes waiting).

**Comment by edreamleo** [comment]
@CandyAngel Thanks for this report.  Please create a separate bug: the issue you report concerns different code than the bracket matching code.

**Comment by edreamleo** [comment]
Rev b42e8b5 *partially* fixes this bug.

Bracket matching and match-brackets now do nothing for perl and javascript.

Imo, that's good enough for now. I am going to mark this as a minor bug and remove any target date.

**Comment by edreamleo** [comment]
[This discussion on leo-editor](https://groups.google.com/forum/#!topic/leo-editor/TuNYaI_sEkY) discusses a surprising problem with back scanning and the solution.  The final code will be elegant, but a bit slower, than the buggy code.
