### ISSUE TITLE
Clones lost with @auto files

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#1275]
I'm still narrowing in on the exact recipe to recreate this, but I'm seeing Cloned Nodes in `@auto` files forgetting they are clones. Active Path plugin may be involved. It goes something like this:

 - create node, add a `@path`
 - run `active-path-load-recursive`
 - navigate to `@auto somefile.py`, double-click to load contents
 -  copy a node somewhere down the tree, might need to be in a Class
 - `paste-as-clone` somewhere outside the above tree
 - repeat 2 or 3 times with different source nodes
 - save .leo file and exit Leo
 - re-open Leo:
    - some of the clones are now just normal nodes. Edits to their body text are NOT reflected in the clone sources.

![image](https://user-images.githubusercontent.com/486200/62735367-df7f0580-b9df-11e9-8251-6f75cfa7ded2.png)

```
Leo 6.1-devel, devel branch, build 3cd45df95c
2019-08-08 12:57:29 -0700
Python 3.7.1, PyQt version 5.13.0
Windows 10 AMD64 (build 10.0.17134) SP0
```

**Comment by maphew** [comment]
https://github.com/maphew/studies/commit/8ea64ad97313862de9205a2cde910e2b952a70de has a Leo file that I've experienced this problem with several times today.

Assumes path structure of:

    code\studies
    code\shortcutter
    code\leo-editor

where each of those is a clone of:

    https://github.com/maphew/studies.git
    https://github.com/maphew/shortcutter
    https://github.com/leo-editor/leo-editor.git

**Comment by edreamleo** [comment]
On Thu, Aug 8, 2019 at 3:25 PM matt wilkie <notifications@github.com> wrote:

> I'm still narrowing in on the exact recipe to recreate this, but I'm
> seeing Cloned Nodes in @auto files forgetting they are clones.
>
Do you have @persistence enabled?

Edward

**Comment by maphew** [comment]
Altix _show-settings_ says `@bool   createatpersistencenodesautomatically = False`. There's no other `persist` strings in the report.

**Comment by edreamleo** [comment]
On Thu, Aug 8, 2019 at 10:04 PM matt wilkie <notifications@github.com>
wrote:

> Altix *show-settings* says @bool createatpersistencenodesautomatically =
> False. There's no other persist strings in the report.
>
Yes, that was what I was talking about.  Set it to True.

Edward

**Comment by edreamleo** [comment]
I am going to close this item.  Please reopen if changing the setting doesn't help.

**Comment by maphew** [comment]
Ah I see know. I've re-read https://leoeditor.com/directives.html `@persistence` section and now understand things that weren't altogether conscious before. I mean I knew clones need GNX in order to exist but hadn't put that together with `@auto` nodes don't and can't have GNX.

I think a log warning that clones-from-@auto nodes will not be saved when persistence is not enabled is a good idea.

(And active_path plugin should default to clean instead of auto, but that's a different issue, shortly to be made)

**Comment by edreamleo** [comment]
On Fri, Aug 9, 2019 at 6:01 PM matt wilkie wrote:

> Ah I see now. I've re-read https://leoeditor.com/directives.html
> @persistence section and now understand things that weren't altogether
> conscious before. I mean I knew clones need GNX in order to exist but
> hadn't put that together with @auto nodes don't and can't have GNX.
>
Yeah, it's a lot for anyone to grok, especially a newbie.

> I think a log warning that clones-from-@auto <https://github.com/auto>
> nodes will not be saved when persistence is not enabled is a good idea.
>
Hmm. Such a warning would quickly become unpleasant, and I don't want to
create yet another user setting to turn it off ;-)  The alternative would
enabled the @persistence setting by default...

Edward

**Comment by maphew** [comment]
Yeah, too many messages is a problem. This is probably the 10th time I've said "oh, this and this confused me and should have a message because I didn't get it (and lost work or something)".  ;-) The only workaround I've thought of is to emit messages for these kinds of scenarios intermittently, every dozen times or something. That would mean keeping track through; probably a fair bit of work.

Back to main topic: would there be problems with default persistence?

**Comment by edreamleo** [comment]
On Sun, Aug 11, 2019 at 8:15 PM matt wilkie <notifications@github.com>
wrote:

> Back to main topic: would there be problems with default persistence?
>
Not usually.  But @persistence nodes do increase the size of .leo files.

Edward
