### ISSUE TITLE
clear-node-uas doesn't dirty file

### ISSUE THREAD

**Issue by largo84** [leo-editor/leo-editor#1276]
1. Create a uA using either the backlinks or nodetags plugins (perhaps others as well).
2. Save the file.
3. The command show-node-uas will display the uAs in the log pane.
4. Invoke the command clear-node-uas, then show-node-uas to confirm the uAs are now gone.
5. The file has not been dirtied to prompt to save. Seems like it should.

Discussed [here](https://groups.google.com/d/msg/leo-editor/OveQ-5mp2w0/_Gb4B4OvAAAJ).

**Comment by edreamleo** [comment]
@largo84 I agree, the .leo file should be marked dirty.

**Comment by edreamleo** [comment]
Fixed at f5986d8 in devel.
