### ISSUE TITLE
show-settings with filter

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#1277]
`show-settings` command produces a lot of output, 817 lines at last count. It would be nice if the command would accept parameters to filter the output. 

I'm imagining something like `show-settings {pattern}`, with {pattern} being whatever you'd use with _grep_ or _findstr_ on the command line. (Without needing to use quotes.)

I am going to close this.  #852 should suffice.

**Comment by edreamleo** [comment]
I have assigned this to 6.1 to keep in on my radar.  It probably could be done easily.

Having said that, there are several workarounds to not having this enhancement:

1. Use any Leo search you like, including regex, in LeoSettings.leo.  That should reveal relevant settings.

2. Copy the results of the command into a Leo node, and then use any Leo search you like.

**Comment by technatica** [comment]
I start Leo using a bash script.

Add >sessionlog.txt to the command string ie. python3 launchLeo.py $1 $2 $3
>sessionlog.txt

You can open sessionlog.txt using an @file node and search away.

Chris

**Comment by maphew** [comment]
Thanks for the workarounds. I especially like the session log trick and then opening it.

**Comment by technatica** [comment]
I tumbled to the idea trying to figure out how to run a bash script from
Leo and get the output into a node.

I quickly realized the idea could be used to capture the output of Leo
itself.

Chris
