### ISSUE TITLE
Active Path plugin default to @clean instead of @auto

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#1280]
I think the Active Path plugin should default to creating `@clean` nodes instead of `@auto` nodes when loading files from a directory. (I don't think clean existed when AP was made.)

It would help avoid situations like _#1275 Clones lost with auto files_

**Comment by edreamleo** [comment]
Imo, this would be reasonable in general.  However, when many files are created using `@clean` might bloat the .leo file.  So there should be a setting for this.
