### ISSUE TITLE
Integrate Leo with Visual Studio Code

### ISSUE THREAD

**Issue by boltex** [leo-editor/leo-editor#1281]
**EKR**: [This page](https://github.com/boltex/leointeg) contains working code.

(Question about running / driving leo 'headless' to integrate it in my own GUI)

Hi! Long time leo user here. I use it mainly for the 'core' features: outline organisation of my code : @clean nodes, structure with @others. And I alt-tab leo alongside with another editor/IDE for running/debugging/compiling/linting/beautifying/etc...

I dont care so much about vim/emacs integration nor dont even understand what those buffers/minibuffers are and all around feel like that qt-gui framework didnt age very well. (no offence meant here, as I would be devastated to think I offended edream, he's like my programming 'idol')
I also do not use @buttons and internal scripting in leo altough i can see its use for some people. 

I mainly use Leo for its 'file-generation'/'file-reading' (mainly @clean) feature via the outline structure that it provides. Organising a program with an outline, clones and @others is the best! Which also, if I may say so, is Leo's 'killer feature'.

So i'd like to try and integrate, or 'roll my own' leo in my other favorite editor so that I have the subset of leo's features that I just defined as its 'killer features' available without having Leo 'opened'. 
Is leoBridge the way to go? ...or is there a way to start leo with no GUI and have it listen for commands on a specific port for input/output of commands and answers? 

Many thanks in advance!!

**Comment by maphew** [comment]
Discussion here: https://groups.google.com/d/topic/leo-editor/GQ6yV6nHqQo/discussion

**Comment by boltex** [comment]
Indeed lets continue the discussion at google groups, this reply is just a 'flag' for people who would like to follow up on a possible expansion being created: I've started a project at https://github.com/boltex/leointeg

**Comment by edreamleo** [comment]
Great stuff! I've just reopened this so it will be more visible.

**Comment by edreamleo** [comment]
On Wed, Aug 28, 2019 at 8:34 AM Felix <notifications@github.com> wrote:

> First working version (allows to browse outline for now) at
> https://github.com/boltex/leointeg
>

Great stuff!

Edward

**Comment by boltex** [comment]
I have started Making the body editable this weekend. I have not succeded yet. Wrapping my head around what is possible/allowed in vsCode, and how to actually do it is not as straightforward as I would have hoped. That being said: I feel i'm pretty close to getting it done. I'll push a commit this week as soon as I succeed.

**Comment by edreamleo** [comment]
On Tue, Sep 3, 2019 at 3:20 PM Felix <notifications@github.com> wrote:

> I have started Making the body editable this weekend. I have not succeded
> yet. Wrapping my head around what is possible/allowed in vsCode, and how to
> actually do it is not as straightforward as I would have hoped. That being
> said: I feel i'm pretty close to getting it done. I'll push a commit this
> week as soon as I succeed.
>

Thanks for the status report.

Edward

**Comment by boltex** [comment]
Before I reach that point in my development I'm going to ask here: does leoBridge / leo headless have triggers to latch on to for getting alerted when a derived file was changed by another process? ( leo does show a modal screen asking you if you want to reload the derived files from disk) Also other events I want to 'latch' on to is focusing on a particular node/body position when a search is done (find next/previous)

**Comment by edreamleo** [comment]
On Wed, Sep 4, 2019 at 1:36 PM Felix <notifications@github.com> wrote:

> Before I reach that point in my development I'm going to ask here: does
> leoBridge / leo headless have triggers to latch on to for getting alerted
> when a derived file was changed by another process?
>
It can be done.  It probably could be made easier. Take a look at
leoBackground.py.

Edward

**Comment by boltex** [comment]
Thanks, I've been out of town for this long weekend catching up with friends from 20 years ago :) 
I'll continue where I left off and bring the editable capabilities (body and headline) i've made in vscode affect the underlying leo file opened via leoBridge very soon. Afterwards I'll add outline structure editing  easily I think. 
I'm so eager to use Leo naturally and generate/refresh my @clean & such from inside vscode! This will be great!

**Comment by boltex** [comment]
Hello,

About a month ago I did a bunch of tests with vscode's extension capabilities along with tests with leoBridge's control of Leo. Mostly throwing spaghetti at the wall and seeing what sticks. I got excited, you guys kind of liked it I guess, but it all added up to a whole bunch of spaghetti code mess as you may have noticed if you browsed my sources. Mostly so in the 'communication' between vscode and the python script (Leo) part.

I sincerely apologize for this and present you now instead with a cleaned up version, where code-duplication was eliminated and all processes are now streamlined and simplified!

I think this is a great moment for testing that "basic browsing" works fine before adding outline editing, and map mostly all or the rest of Leo's functionality to be used seamlessly from vscode...

https://github.com/boltex/leointeg
![image](https://user-images.githubusercontent.com/847716/66251053-4cc9c100-e719-11e9-94f7-221e61f41b23.png)

Please try it out (browsing along with headline and body editing for now) and ask about anything I may have overlooked in this short invitation to beta-test my stuff for free ;) 

here is the last changelog entry:

- Major 'Browsing' update before adding outline editing and file saving & derivation
- Refactored and simplified communication between vscode and leoBridge
- Stabilized browsing with multiple simultaneous (and different) body panes
- Added Leo Outline into explorer view (in addition to the dedicated Leo sidebar view)
- Supports new command to open a node on the side from the context menu
- Multiple configuration options: Open Settings with CTRL+',' type 'leo', or look for 'leo integration' in extensions

Many thanks!!
--
Félix

**Comment by boltex** [comment]
Support for windows has been fixed! 

If pulling to update this repository make sure to re-run 'npm install' as a small dependency (hasbin) was added.

Many thanks to anyone testing this expansion and to Edward for reporting this bug!

**Comment by boltex** [comment]
Hello to all Leo and vsCode users out there! 🦁

I made another release of leoInteg intended this time again for asking all of you to try out and test more features: Full outline and body editing! 

Checkout the welcome screen that lets you change settings, all outline and body editing commands, undo, ... and a lot more, see the readme at the projects home page: https://github.com/boltex/leointeg

Sorry : Save / Derive files is only coming next release! 

Many thanks to any of you that try it out and give me feedback. Any positive or negative feedback about any issue is greatly appreciated! 
--
Félix

**Comment by boltex** [comment]
Hello again to all Leo and vsCode users! 🦁

I just pushed a new version on the master branch of LeoInteg. ...I made sure it runs well under Windows this time! ;) 

(lol honestly feel a bit silly I didnt even made sure my pasts releases even worked outside of ubuntu)

All main issues with the last version have been resolved, many new features have been added,  and as ar-jan puts it, it's now possible to edit a derived file and smoothly keep it in sync with Leo, in both directions.

I've got all that and more on the master branch for you to try at https://github.com/boltex/leointeg 

And if you're so enclined, I've even made a handy "Test-sheet" for you to use when you're trying out LeoInteg:  https://docs.google.com/spreadsheets/d/1M7TA3J0hkBpU4BkyChThrhzwKxhTPtQHacXDYRvEQes/edit?usp=sharing

It's just a small grid of yellow checkboxes (from rows E to I) to help keep track of what features can be interacted with.

I hope you like it and also to get some feedback as you try it out! :)

Félix

**Comment by edreamleo** [comment]
@boltex Many thanks for your continuing work. Your work might inspire similar work for emacs, vim, etc.

**Comment by boltex** [comment]
>Your work might inspire similar work for emacs, vim, etc.

I just wanted to add, if it wasn't already known by observers of this project, that the 'leobridgeserver.py' server script is totally agnostic about it's clients nature and could be used as-is in any other integration target.

**Comment by edreamleo** [comment]
@boltex Thanks for the clarification!

**Comment by boltex** [comment]
I'm adding this comment to this historic thread to mark the event of the first official release of LeoInteg!

https://marketplace.visualstudio.com/items?itemName=boltex.leointeg

Cheers and thanks to all who have contributed! Even simple comments and suggestions did help greatly!

Félix

**Comment by edreamleo** [comment]
@boltex Congratulations on this great work. I see that leoInteg 1.0.1 updated automatically. So easy!!

I'll be spending 5 or 10 minutes each day playing with vs-code/leoInteg. I'll report any problems on leoInteg's issues page.

**Comment by boltex** [comment]
@edreamleo Three years after completing [LeoInteg](https://github.com/boltex/leointeg), I'm commenting again on this historic thread to celebrate with you and the leo-editor community both my 50th birthday 🥳, and the point in time where all of my intended projects for Leo integration into VSCode are _finally_ realized:

- A complete rewrite of Leo in typescript as a VSCode extension: [LeoJS](https://github.com/boltex/leojs)
- Video tutorials that [introduces the Leo-Editor](https://www.youtube.com/watch?v=j0eo7SlnnSY), and demonstrates [cool LeoJS features](https://www.youtube.com/watch?v=M_mKXSbVGdE)
- Sample repositories for [Leo scripts examples](https://github.com/boltex/scripting-samples-leojs) and a [plugin-extension example](https://github.com/boltex/extension-sample-leojs) running in LeoJS
- A rewrite of the original [website](https://boltex.github.io/leojs/) documenting all of Leo's Editor usage and history, along with its LeoJS implementation details.

I want to give thanks to Edward and all those who have contributed to the Leo Editor! All of this would not be possible without you, so thank you again very much for your efforts! 😁

Félix

**Comment by edreamleo** [comment]
@boltex Congratulations on your big five-oh! And congratulations on all your recent milestones. They are a *huge* contribution to Leo.
