### ISSUE TITLE
Leo-Editor fails to warn the user when he opens a file using a symlink and then opens the same file using its real path.

### ISSUE THREAD

**Issue by SegundoBob** [leo-editor/leo-editor#1282]
## How I encountered this problem
I have a directory Leo containing hundreds of Leo-Editor files.  Some files I use every day.  Years pass between uses of some files.  This directory gives me one place to search when I remember that I made a note, but I can't remember where that note is.

A few of the files are important enough to source contol using git.  Of course, there are many ways this could be done.  After considering many of these ways, and trying several, I decided that I prefer a separate repository for each source controlled file; and for the real Leo-Editor file to reside in work directory of the repository and not use the git init option --separate-git-dir.

Hence, I have several symlinks in my Leo directory, so I can still easily search all my note files.

I soon noticed that if I opened a Leo-Editor file using its symlink (real path) and then
opened the same Leo-Editor file using its real path (symlink), Leo-Editor did **not** warn me:
```
The following files may already be open
in another copy of Leo:
```

This warning is very useful to me.  Hence, this problem is moderately important to me.

## What to show the user?
Do you want to show the user the symbolic link or the real pathame?  I have no opinion about this.  Both are reasonable.  Neither is ideal.

The file pathname display that I care about is the "Window Title" displayed by the window manager i3.  Currently this is:

for_window [class=".*"] title_format "%instance - %title"

I doubt that i3 could be talked into displaying both a symlink and a real pathname when there is a symlink.  So for me, it is one or the other, not both.

## Library pathlib

I recommend the pathlib library, but either os.path or pathlib can easily be used to deal with symlinks--at least for Linux systems.  I know Windows has what Microsoft calls "Symbolic Links" and I know that they are substantially different from Linux symbolic links, but I don't know the details, so I don't know how this problem appears or doesn't appear under Windows, much less how to fix it if it occurs under Windows.

## os.path vs. pathlib Example Program
```
from icecream import ic
import os.path
import pathlib

softLink = '/pri/bob/1/Leo/Brenda Projects.leo'
pathSoftLink = pathlib.Path(softLink)
realFile = '/pri/git/leo_files/Brenda_Projects/Brenda Projects.leo'
pathReal = pathlib.Path(realFile)
ic(softLink, realFile)

ic(pathSoftLink.is_symlink())
ic(pathSoftLink.samefile(pathReal))

ic(pathSoftLink.absolute())
ic(os.path.abspath(softLink))

ic(pathSoftLink.resolve())
ic(os.path.realpath(softLink))
```
## Example Program Output
```
2019-08-10 10:51:43 /sec/tmp
$ python3 soft_link.py
ic| softLink: '/pri/bob/1/Leo/Brenda Projects.leo'
    realFile: '/pri/git/leo_files/Brenda_Projects/Brenda Projects.leo'
ic| pathSoftLink.is_symlink(): True
ic| pathSoftLink.samefile(pathReal): True
ic| pathSoftLink.absolute(): PosixPath('/pri/bob/1/Leo/Brenda Projects.leo')
ic| os.path.abspath(softLink): '/pri/bob/1/Leo/Brenda Projects.leo'
ic| pathSoftLink.resolve(): PosixPath('/pri/git/leo_files/Brenda_Projects/Brenda Projects.leo')
ic| os.path.realpath(softLink): '/pri/git/leo_files/Brenda_Projects/Brenda Projects.leo'
2019-08-10 10:55:48 /sec/tmp
```

## Test System
```
Leo Log Window
Leo 6.1-devel, devel branch, build f5986d8016
2019-08-09 10:23:41 -0500
Python 3.6.8, PyQt version 5.11.1
linux
```

**Comment by edreamleo** [comment]
@SegundoBob Thanks for your thorough report and exploration of possible fixes.

**Comment by vitalije** [comment]
Fixed at dc72b05e5

**Comment by SegundoBob** [comment]
Vitalije,

Thank you.  The fix works for me.

SegundoBob

**Comment by vitalije** [comment]
SegundoBob, glad to here it.

**Comment by edreamleo** [comment]
@vitalije Many thanks for this work.
