### ISSUE TITLE
Font setting overridden by new workbook

### ISSUE THREAD

**Issue by lf94** [leo-editor/leo-editor#129]
If you go into Startup -> @settings, and add @font DejavuSans, close Leo, re-open it, the new font will have taken affect, until you open a new leo workbook. Then it everything goes back to the original Leo font. This is the latest git version.

**Comment by edreamleo** [comment]
I'm not sure this is unexpected.  If you want a setting to apply everywhere, you should put it in your myLeoSettings.leo file.  Have you tried that?

**Comment by edreamleo** [comment]
I am going to close this item. On second reading, the behavior described is the expected behavior.

With some exceptions, including plugins, settings in one .leo file do not affect other .leo files.  If you want settings to apply generally, put them in myLeoSettings.leo.
