### ISSUE TITLE
QApplication: invalid style override passed, ignoring it.

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#1291]
Probably not serious, but I got a warning from Qt on Linux when running Leo:
```
setting leoID from os.getenv('USER'): 'matt'
QApplication: invalid style override passed, ignoring it.
    Available styles: Windows, Fusion
Leo 6.1-devel, desktop-links branch, build f396181cf5
2019-08-18 22:23:01 -0700
```

```
$ pip show PyQt5
Name: PyQt5
Version: 5.13.0
Summary: Python bindings for the Qt cross platform UI and application toolkit
Home-page: https://www.riverbankcomputing.com/software/pyqt/
Author: Riverbank Computing Limited
Author-email: info@riverbankcomputing.com
License: GPL v3
Location: /home/matt/miniconda3/envs/leo-dev/lib/python3.6/site-packages
Requires: PyQt5-sip
Required-by: PyQtWebEngine, leo
```
**Update**: first version of this report said this was a new user profile, that was a mistake. This is actually an old Leo profile.

**Comment by edreamleo** [comment]
On Mon, Aug 19, 2019 at 12:30 AM matt wilkie <notifications@github.com>
wrote:

> Probably not serious, but I got a warning from Qt on Linux when running
> Leo under a new profile:
>
> setting leoID from os.getenv('USER'): 'matt'
> QApplication: invalid style override passed, ignoring it.
>     Available styles: Windows, Fusion
>
> The relevant code is setQtStyle, a variant of pyzo's code.  By default, it
seems this should do nothing, because @string qt-style-name is None in
leoSettings.leo.

Edward

**Comment by maphew** [comment]
not seeing this anymore
