### ISSUE TITLE
render window is not cleared when switching from @html node

### ISSUE THREAD

**Issue by xu4wang** [leo-editor/leo-editor#1292]
Dear Leo Developer,

I met an issue regarding rendering HTML node. 

For a simple leo file with only two nodes,one is html node, another is normal text node.

If I set focus on the html node, the html content will be rendered as expected in the render window.  Switch the focus to the other node. The render window is still in HTML rendering status. The text from the normal node is overlapped to the HTML text from the previous html node.

BR,Xu

![html_node](https://user-images.githubusercontent.com/311397/63257957-25bc4a80-c2a5-11e9-9fc8-9db7522d875e.jpg)

**Comment by edreamleo** [comment]
If I remember correctly, the behavior you describe is what I intended.   Is this a big problem for you?

**Comment by xu4wang** [comment]
> If I remember correctly, the behavior you describe is what I intended. Is this a big problem for you?

Sorry, Maybe I was not making it clear...
1) I clicked @html node, the html body was rendered.
2) I clicked anthor item "newHeadline", the html body was still rendered, and on top of that html page, the body text of "newHeadline" overlapped.

Is it expected behaviour?

I was expecting when I click one node, only the body of that node will be rendered.

**Comment by edreamleo** [comment]
@xu4wang "I clicked another item "newHeadline", the html body was still rendered, and on top of that html page, the body text of "newHeadline" overlapped."

Clearly, this is a bug.  I've just assigned it to 6.1.

**Comment by LewisNeal** [comment]
On my system I do not experience this rendering problem. The render pane updates as expected if I toggle between @html and text node.

Leo Log Window
Leo 6.1-devel, devel branch, build cbbe8b38c1
2019-08-19 07:52:28 -0500
Python 3.6.8, PyQt version 5.13.0
Windows 10 AMD64 (build 10.0.17134) SP0

**Comment by xu4wang** [comment]
My configuration:

Leo Log Window
Leo 6.0-final, master branch, build db55bd00c9
2019-08-02 11:24:36 -0500
Python 3.7.4, PyQt version 5.13.0
darwin
read outline in 0.02 seconds


> On my system I do not experience this rendering problem. The render pane updates as expected if I toggle between @html and text node.
> 
> Leo Log Window
> Leo 6.1-devel, devel branch, build [cbbe8b3](https://github.com/leo-editor/leo-editor/commit/cbbe8b38c1f4e3d93b761d7e199939f5c5e58c84)
> 2019-08-19 07:52:28 -0500
> Python 3.6.8, PyQt version 5.13.0
> Windows 10 AMD64 (build 10.0.17134) SP0

**Comment by xu4wang** [comment]
> On my system I do not experience this rendering problem. The render pane updates as expected if I toggle between @html and text node.
> 
> Leo Log Window
> Leo 6.1-devel, devel branch, build [cbbe8b3](https://github.com/leo-editor/leo-editor/commit/cbbe8b38c1f4e3d93b761d7e199939f5c5e58c84)
> 2019-08-19 07:52:28 -0500
> Python 3.6.8, PyQt version 5.13.0
> Windows 10 AMD64 (build 10.0.17134) SP0


I just switch to devel, the issue is still there. I guess it's related to Mac.

Leo Log Window
Leo 6.1-devel, devel branch, build bd22ab811a
2019-08-15 06:09:00 -0500
Python 3.7.4, PyQt version 5.13.0
darwin
read outline in 0.02 seconds

**Comment by technatica** [comment]
This happens to me on linux but only when I use "vr-lock" on the first
node. vr-unlock clears the first render.

Chris

**Comment by edreamleo** [comment]
@technatica Ah, the vr-lock strikes again.  This is an important clue.

**Comment by edreamleo** [comment]
Everything works as expected on both Windows and Ubuntu Linux.  I'll investigate on MacOS.

**Comment by edreamleo** [comment]
Everything works as expected on MacOS.  I am going to close this issue.  Perhaps vr-lock was in effect.
