### ISSUE TITLE
resize the image to fit the render window

### ISSUE THREAD

**Issue by xu4wang** [leo-editor/leo-editor#1293]
Dear Leo Developer,

I have one image node with headline @image
In the body, there is only one image file name.

The image is rendered as expected in the render window.  
However, since it's a large image and the render window is small, only a small portion of the image is displayed. There are vertical/horizontal around the render window.

I'd like to have the image resized to fit the render window.

Checking the plugin source code(viewrendered.py), I made below modification:

```
image_template = '''\
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <style>
        * {
            margin: 0;
            padding: 0;
        }
        .imgbox {
            display: grid;
            height: 100%%;
        }
        .center-fit {
            max-width: 100%%;
            max-height: 100vh;
            margin: auto;
        }
    </style>
</head>
<body>
<div class="imgbox">
    <img class="center-fit" src="%s">
</div>
</body>
</html>
'''

```

but it doesn't work. the image is still not resized.

Please If you have any suggestion...

BR,Xu

**Comment by edreamleo** [comment]
@xu4wang Thanks for your work on this issue.  I've schedule this for 6.1.

**Comment by tbpassin** [comment]
Actually, this only works on VR3, not on VR.  That's because VR uses a TextEditWidget to display the image, while VR3 uses a QWebBrowser.  Apparently the TextEdit doesn't understand that style attribute.

I'll have to study VR for a while to see how to adjust this.
