### ISSUE TITLE
Interactive and editable "show-settings"

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#1294]
See also: #852, Add an active settings *outline*.

Blue sky: I'd like to be able to run `show-settings` into a Leo panel. This panel has category buttons like "Look/feel", "Keyboard", "Abbreviations", etc. plus a text field for "find as you type" filtering.

In this panel I can double-click or [enter] on any given setting and: 

(a) be taken to the location where that is currently defined (LeoSettings, myLeoSettings, MyCoolTheme.leo, ThisLeofile.leo) where I can edit and save as I like. Or:

(b) Edit in place. If this place happens to be a System setting (not MySettings or local leo file) then my there's a prompt which asks at which level to save the setting.

**Comment by tbnorth** [comment]
The Settings -> Edit settings menu item does large parts of this.  No panel, but it works out where settings are set and takes you there, or creates a shadowing myLeoSettings.leo setting if appropriate.

It seems to be somewhat broken now in that it asks the same thing twice (do you want to edit the general or specific setting), but it does cover a lot of the ground you describe.

**Comment by technatica** [comment]
For some reason I do not have such a menu entry.

Settings/Edit Settings does not exist.

I do not use a local settings menu, just the one in LeoSettings.leo.

**Comment by maphew** [comment]
Thanks Terry. Maybe I know enough now to be able to figure out how to wire _clickable urls in log pane_ to _Edit Settings_. I'll find out soon I s'pose. ;-)

**Comment by tbnorth** [comment]
On Tue, 20 Aug 2019 14:58:49 -0700
Chris George <notifications@github.com> wrote:

> For some reason I do not have such a menu entry.
> 
> Settings/Edit Settings does not exist.
> 
> I do not use a local settings menu, just the one in LeoSettings.leo.

I think it must be the enabled by default settings_finder.py plugin,
which perhaps you have disabled?

Cheers -Terry

**Comment by technatica** [comment]
That was it.

Chris

**Comment by edreamleo** [comment]
I am going to close this in favor of #852.
