### ISSUE TITLE
Leo PIM for desktop and mobile app

### ISSUE THREAD

**Issue by xu4wang** [leo-editor/leo-editor#1296]
Dear Leo Developers,

I'm planning to use Leo as my daily PIM.  One major desired feature is to have both mobile and Desktop app  accessing the PIM data.  

1) Desktop app will be the major tool for organising nodes and processing data.
2) Mobile app will be used to collect ideas, photos, voice recodings, videos when on the go.

I am quite convinced by the extensibility and functionality of Leo for desktop app.  I'm looking for a solution for mobile app.  My initial idea is:

1) Put the desktop.leo file under git control, whenever the file is changed by leo, commit and push a new version to the remote server(by a plugin maybe).
2) Setup a simple backend for mobile app in the remote server. The backend check out the latest desktop.leo file from git, and provide data via leoBridge interface to the mobile app. 
3) The mobile app can also collect photos, texts  and sync to desktop leo for further processing.

Is it too complicated? Does anyone use .leo data on mobile?

BR,Xu

**Comment by largo84** [comment]
I've been trying different approaches over the last few years as I would like to have mobile and desktop 'play well together' as well. What I've been doing lately is simply use external @auto-md files to store data in DropBox (or other equivalent syncing tool) and open and edit them in mobile w/ text editors like DroidEdit or Jota+.

Also now experimenting w/ Joplin and Orgzly (for org-mode files), but the jury is still out.

Ideally, I would use Leo natively in mobile, but I don't see that possibility anytime soon. I certainly don't have the programming chops to do that!

Rob...

**Comment by maphew** [comment]
Terry (@tbnorth) published a plugin and/or method for saving .leo files to dropbox automatically. And Joe Orr's (@kaleguy) [LeoVue ](https://github.com/kaleguy/leovue )does amazing stuff with displaying and interacting with server-hosted .leo files.

**Comment by technatica** [comment]
Here is a can of worms if someone is bored. :-)

https://github.com/kivy/python-for-android

Chris

**Comment by xu4wang** [comment]
> I've been trying different approaches over the last few years as I would like to have mobile and desktop 'play well together' as well. What I've been doing lately is simply use external @auto-md files to store data in DropBox (or other equivalent syncing tool) and open and edit them in mobile w/ text editors like DroidEdit or Jota+.
> 
> Also now experimenting w/ Joplin and Orgzly (for org-mode files), but the jury is still out.
> 
> Ideally, I would use Leo natively in mobile, but I don't see that possibility anytime soon. I certainly don't have the programming chops to do that!
> 
> Rob...

thanks Rob for sharing your experience. 
I guess using external file will be a good choice for now as the external file can be updated by mobile when Leo desktop is running.

**Comment by xu4wang** [comment]
> Terry (@tbnorth) published a plugin and/or method for saving .leo files to dropbox automatically. And Joe Orr's (@kaleguy) [LeoVue ](https://github.com/kaleguy/leovue)does amazing stuff with displaying and interacting with server-hosted .leo files.

Thanks Maphew for the info.. I am still exploring leo and last night, I also find the built-in flexx app amazing.

There are two use cases I want to handle:

1) I am in the office, working with Leo on my computer and need to go out without computer. I will need my phone have the ability to access the data inside the leo file of my computer.

2) I am out of office with my mobile, I take a photo, when I go back to my office, I want to see the photo appears in the leoeditor(maybe under a node named "inbox_mobile") .

The challenge is to have two apps(desktop and mobile) update the same leo file.

**Comment by xu4wang** [comment]
> Here is a can of worms if someone is bored. :-) https://github.com/kivy/python-for-android Chris

It's a can of snake... ;-)

But as a potential end user of leo mobile,  I don't think porting whole leo to mobile is a good way to go for now. given the mobile screen is still too limited to use leo.

The most desired feature of leo mobile is to conveniently collect information(photos, ideas, ...) and send back to leo desktop for further processing.

The easy to use UI for accessing desktop leo data from mobile is not so important, as long as the data can be accessed, an unfriendly interface is acceptable. Since the scenario doesn't happen every often.

**Comment by technatica** [comment]
The ultimate goal for me would be to have Leo/flexx running on a server and
then it doesn't matter where you are or which device you have you would
have access to Leo via a web browser.

For your use case, I would use dropbox or mega (highly recommended).

They both have clients for android that do exactly what you want. ie.
upload a file from Android to their server and have that file automatically
sync with desktop at home.

HTH,

Chris

**Comment by maphew** [comment]
[Joplin](https://joplinapp.org/) is the best I've seen by far in the "use and add notes and pictures across all my devices" activity domain. (Though I've only really used across computers so far and not my phone beyond "yup it works".)

It's native format is markdown so Leo can read what Joplin writes straightforwardly. The hard part would be mapping the unique-id-as-filename.md to "Headline Name" and parent-id (Notebook a.k.a. Folder), thence to Leo nodes and notebook. All the info needed is in every file though. Plus there's a Rest API if you wanted to fetch through web calls.

**Comment by xu4wang** [comment]
> [Joplin](https://joplinapp.org/) is the best I've seen by far in the "use and add notes and pictures across all my devices" activity domain. (Though I've only really used across computers so far and not my phone beyond "yup it works".)
> 
> It's native format is markdown so Leo can read what Joplin writes straightforwardly. The hard part would be mapping the unique-id-as-filename.md to "Headline Name" and parent-id (Notebook a.k.a. Folder), thence to Leo nodes and workbook. All the info needed is in every file though. Plus there's a Rest API if you wanted to fetch through web calls.

Thanks for the info..Just checked Joplin, it looks good. The Electron editor and ReactNative client are with many features.

I'm using one home made tool for now, the server side is an XMPP robot, created using https://github.com/fritzy/SleekXMPP. the client side I am using are:
- https://conversations.im/
- https://conversejs.org/fullscreen.html

The conversations for Android is good for me. I created one contact for each list, and self-talk with the list. All the message(pictures, strings, locations..) will be recorded by the SleekXMPP robot on the server side.

I'm planning to integrate my current XMPP based workflow with leo desktop.

BR,Austin
