### ISSUE TITLE
Support global settings in .ini files

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#1298]
A text file, say **leo_global_settings.ini**, would contain *just a few* global settings.  Leo would look for this file first in ~/.leo, and then in Leo's config directory.

**Rationale**

At present, Leo's theme files must load *after* myLeoSettings.leo, because myLeoSettings.leo specifies which theme to use.  Instead, leo_global_settings.ini would specify the theme.  Leo could then load the theme file before myLeoSettings.leo.

This feature has been requested before.  There is now a real reason to allow this extra complication.

leo_global_settings.ini *might* replace *some* settings in g.app.db.  This would make those settings more visible to the user, at the likely cost of complicating the affected code.

**Comment by maphew** [comment]
Maybe it should just be `theme.ini`. Yet another place to look for a _what-the-heck-is-doing-this!_ setting sounds like a recipe to make what's already a confusing situation even more confusing.  Though I do agree there needs to be some mechanism to float the settings people are most likely to want to change upwards.

**Comment by edreamleo** [comment]
On Fri, Aug 23, 2019 at 12:20 PM matt wilkie <notifications@github.com>
wrote:

> Maybe it should just be theme.ini.
>
Conceivable.

> Yet another place to look for a *what-the-heck-is-doing-this!* setting
> sounds like a recipe to make what's already a confusing situation even more
> confusing.
>
Yes, that's a problem.  Let me reconsider this.  Perhaps g.app.db can be
pressed into service...

Edward

**Comment by edreamleo** [comment]
I'm going to close this issue after marking it "Won'tDo".  As Matt says, this would just add to the settings confusion. I have just created #1301 Open theme files before myLeoSettings.leo, suggesting that `@string theme-name`  should be replaced by a setting in g.app.db or c.db.
