### ISSUE TITLE
Implementation bug in fix to Issue #35

### ISSUE THREAD

**Issue by SegundoBob** [leo-editor/leo-editor#130]
The two scripts in repository https://github.com/SegundoBob/leo_bridge_gnx_2.git demonstrate this bug.  I believe this is a bug in the fix to Issue #35.  I believe this is an implementation bug, not a design bug.

I encountered this bug while using Leo-Bridge to determine the differences between my Android Outliner version and my Leo-Editor version of each of many outlines.

Unrelated Bug also Demonstrated
-------------------------------

Please note also that despite options "gui='nullGui'" and "verbose=False" Leo-Bridge still writes many lines to the terminal.  These lines do not help and only confuse users of the scripts that I write which use Leo-Bridge.  Consequently, I think that with these options Leo-Bridge should only write errors to the terminal.  That is, Leo-Editor should NOT write:

```
file not found: /home/ldi/git/leo_bridge_gnx_2/foo.leo. creating new window

** isPython3: False
Leo 5.0-final, build 20141127165348, Thu Nov 27 16:53:48 CST 2014
Git repo info: branch = master, commit = bffb0e1bce65
Python 2.7.3, LeoGui: dummy version
linux2
reading settings in /home/ldi/git/leo_bridge_gnx_2/foo.leo
traverse no settings tree for foo.leo
wrote recent file: /home/bob05/.leo/.leoRecentFiles.txt
```

Bug Analysis
------------

The current Leo-Editor passes the test for Issue #35.  This implies that when an existing Leo-Editor file is opened, the "set Max node index" works as intended.

On the other hand, the master.py-slave.py test seems to show that "set Max node index" always sets the maximum node index to zero.

These two tests are very similar.  I don't know what the crucial difference is.  But it might be an "off by one" bug.  That is, the last node in the outline may be ignored.

On 2014-10-22 at 16:08 EKR committed b4c7bac90b4164dd0a9bfedb7631e0b3f9b82d26 which "Replaced the post-pass by a smarter gnx-allocation scheme."  This new scheme probably contains the bug.

Bug Demonstration Outline
-------------------------

File master.py uses the subprocess library to spawn a process to run slave.py.  First in a loop master.py "calls" slave.py with each "index" in idxList.

When slave.py is called with index K, it uses Leo-Bridge to add a new last child node to the root node of foo.leo and it sets the headline of this new node to K.

Then master.py uses Leo-Bridge to check that foo.leo contains exactly the expected nodes with the expected headlines.  When master.py detects an error, it prints useful error information to the terminal.

How to Run the Bug Demonstration
--------------------------------

Put master.py and slave.py in one directory.

Execute master.py.

Either master.py will run to completion, or it will hang forever.

For me now, master.py has been hanging four to six times in a row between each run to completion.

Hanging Forever
---------------

Hanging forever indicates a bug in Leo-Editor, but I don't know what that bug is.  However, it may be a bug that is only encountered when the bug in "set initial node index" causes a new node to get the same GNX as an existing node.  This hang bug should probably be investigated before fixing the "set initial node index" bug.  But if the hang bug turns out to be very hard to fix, it might be acceptable to just cover it up by fixing the "set initial node index" bug.

When slave.py hangs forever, you can see that it takes a large percentage of the CPU (50% on my system) and that Ctrl-C terminates it.  Canceling slave.py leaves foo.py in a corrupt state.  When Leo-Editor opens this foo.py, Leo-Editor hangs.

Runs to Completion
------------------

When master.py runs to completion without error, it prints to the terminal:

```
Test Passed.  No Error Detected.
```

When it detects an error, it prints to the terminal an error message like:

```
*** Problem:  Probably duplicate GNXs ***
headline "NewHeadline" gnx bob05.20150113124857.1
headline "0" gnx bob05.20150113124857.2
headline "1" gnx bob05.20150113124859.1
headline "2" gnx bob05.20150113124900.1
headline "2" gnx bob05.20150113124900.1
```

Test System
-----------

Xubuntu32 12.04 (precise)
kernel:  3.2.0-75-generic

Python 2, old build:
Leo 5.0-final, build 20141127165348, Thu Nov 27 16:53:48 CST 2014
Git repo info: branch = master, commit = bffb0e1bce65
Python 2.7.3, LeoGui: dummy version

Python 3, old build:
Leo 5.0-final, build 20141127165348, Thu Nov 27 16:53:48 CST 2014
Git repo info: branch = master, commit = bffb0e1bce65
Python 3.2.3, LeoGui: dummy version

Python 2, latest build:
Leo 5.0-final, build 20150107092423, Wed Jan  7 09:24:23 CST 2015
Git repo info: branch = master, commit = aacf05b1b513
Python 2.7.3, LeoGui: dummy version

Python 3, latest build:
Leo 5.0-final, build 20150107092423, Wed Jan  7 09:24:23 CST 2015
Git repo info: branch = master, commit = aacf05b1b513
Python 3.2.3, LeoGui: dummy version

Note: Commit aacf05b1b513 is the commit to my local repo of the merge of the latest github master commit
```
commit cac740601b9c8176dc2eed9626f2db9f9c724153
Author: Edward K. Ream <edreamleo@gmail.com>
Date:   Tue Jan 13 10:39:13 2015 -0600
```

**Comment by edreamleo** [comment]
@SegundoBob 
> Please note also that despite options "gui='nullGui'" and "verbose=False" Leo-Bridge still writes many lines to the terminal.

The ctor is::

controller = leoBridge.controller(gui='nullGui',
    loadPlugins=True,  # True: attempt to load plugins.
    readSettings=True, # True: read standard settings files.
    silent=False,      # True: don't print signon messages.
    verbose=False)     # True: print informational messages.

Have you tried setting silent = True?

**Comment by SegundoBob** [comment]
On 03/02/2015 04:51 AM, Edward K. Ream wrote:
> Have you tried setting silent = True?

Yes, I have tried silent=True.  Yes, it helps a lot, but even with
silent=True there are unwanted output lines.

I thought that I was always using silent=True, but at some point I
forgot to put it in, then copy and paste propagated the error.  Sorry
about that.

With silent=True added, to both master.py and slave.py, I get:


2015-03-02 08:51:02 /home/ldi/git/leo_bridge_gnx_2
$ ./master.py
file not found: /home/ldi/git/leo_bridge_gnx_2/foo.leo. creating new window
wrote recent file: /home/bob05/.leo/.leoRecentFiles.txt
wrote recent file: /home/bob05/.leo/.leoRecentFiles.txt
wrote recent file: /home/bob05/.leo/.leoRecentFiles.txt
*** Problem:  Probably duplicate GNXs ***
headline "NewHeadline" gnx bob05.20150302085109.1
headline "0" gnx bob05.20150302085109.2
headline "1" gnx bob05.20150302085110.1
headline "1" gnx bob05.20150302085110.1
headline "3" gnx bob05.20150302085111.1
2015-03-02 08:51:11 /home/ldi/git/leo_bridge_gnx_2
$

I think all the following lines are unwanted:

file not found: /home/ldi/git/leo_bridge_gnx_2/foo.leo. creating new window
wrote recent file: /home/bob05/.leo/.leoRecentFiles.txt
wrote recent file: /home/bob05/.leo/.leoRecentFiles.txt
wrote recent file: /home/bob05/.leo/.leoRecentFiles.txt

-- 
Segundo Bob
SegundoBob@gmail.com

**Comment by edreamleo** [comment]
Rev c6c14ef fixes this bug completely, but it may be possible to eliminate the ugly "gnx holding" logic in ni.getNewIndex.  For this reason I shall leave this issue open.

Rev c6c14ef suppresses the "wrote recent file" message when "silent=True" is passed to the ctor for the BridgeController class. All the other messages arose because the "silent" argument was missing in slave.py.

master.py and slave.py were helpful.  I modified both. At present I can't make them fail.  Here are my versions...

master.py::

    #!/usr/bin/python
    #coding=utf-8
    
    # master.py
    
    import os
    import subprocess
    import sys
    
    import leo.core.leoBridge as leoBridge
    import leo.core.leoGlobals as g
    
    # print('master: leoBridge: %s' % (leoBridge))
    Target = 'foo.leo'
    
    def main_master():
        g.cls()
        if os.path.isfile(Target):
            os.remove(Target)
        idxList = range(4)
        if sys.version_info.major == 2:
            # pyVer = 'python2'
            pyVer = 'c:/python27/python.exe'
        else:
            pyVer = 'python3'
        for idx in range(4):
            returnCode = subprocess.call([pyVer, 'slave.py', str(idx)])
            if returnCode:
                print('subprocess return code = {0}'.format(returnCode))
                return
        if False: # Setting this to False is a more strenuous test.
            bridge = leoBridge.controller(gui='nullGui',
                silent=True,
                verbose=False,
                loadPlugins=False, readSettings=False)
            leoG = bridge.globals()
            c = bridge.openLeoFile('foo.leo')
        if False: # now done in slave.
            expList = ['NewHeadline'] + [str(idx) for idx in idxList]
            for idx, posx in enumerate(c.all_positions_iter()):
                if posx.h != expList[idx]:
                    print('*** Problem:  Probably duplicate GNXs ***')
                    for posx in cmdr1.all_positions_iter():
                        print ('headline "{hdl}" gnx {gnx}'.format(
                                hdl=posx.h, gnx=posx.v.gnx))
                    break
            else:
                print('Test Passed.  No Error Detected.')
    
    if __name__ == "__main__":
        main_master()

slave.py::

    #!/usr/bin/python
    #coding=utf-8
    
    import sys
    import leo.core.leoBridge as leoBridge
    Target = 'foo.leo'
    
    def main_slave():
        trace = True
        idx = sys.argv[1]
        print('slave: idx: %s' % (idx))
        bridge = leoBridge.controller(gui='nullGui',
            silent=True,
            verbose=False,
            loadPlugins=False, readSettings=False)
        leoG = bridge.globals()
        assert leoG.app.inBridge,leoG.app
        c = bridge.openLeoFile(Target)
        ni = leoG.app.nodeIndices
        rp = c.rootPosition()
        p = rp.insertAsLastChild()
        p.h = '{idx}'.format(idx=idx)
        print('slave v.fileIndex: %s h: %r' % (p.v.fileIndex,p.h)) # EKR
        
        # Test here before saving.
        seen = set()
        p = c.rootPosition()
        while p:
            gnx = p.v.fileIndex
            if trace: print('check %20s %s' % (gnx,p.h))
            if not gnx:
                print('slave: ===== no gnx: %s' % (p.h))
                c.close()
                sys.exit(1)
            if gnx in seen:
                print('slave: ===== duplicate gnx: %s %s' % (gnx,p.h))
                c.close()
                sys.exit(1)
            else:
                seen.add(gnx)
            p.moveToThreadNext()
        c.save()
        c.close()
    
    if __name__ == "__main__":
        main_slave()

**Comment by edreamleo** [comment]
I am going to close this issue.  The holding logic is essential.

A comment in  ni.end_holding explains why.  New nodes *can* be allocated while reading a .leo file.  This can happen when the @auto read logic finds a node that has been allocate outside of Leo.  Therefore, ni.end_holding must call ni.compute_last_index.  It can't be called any earlier.  Or any later.

Traces show that ni.compute_last_index takes between 0.01 and 0.05 sec. for typical.leo files.  This is a price well worth paying.

**Comment by SegundoBob** [comment]
Thanks.  My tests and your tests now pass for me on my system using
Python 2 and Python 3 on Leo-Editor commit
42a5207833e08ff37e767d60e1020f6151b3a70b.	

But, tracing is not fully disabled.  When I run the tests, I get these
trace outputs, for example:

compute_last_index ========== time 0.00 lastIndex: old: 0 new: 2
compute_last_index ========== time 0.00 lastIndex: old: 0 new: 3
compute_last_index ========== time 0.00 lastIndex: old: 0 new: 1

-- 
Segundo Bob
SegundoBob@gmail.com

**Comment by edreamleo** [comment]
On Mon, Mar 2, 2015 at 5:00 PM, SegundoBob <notifications@github.com> wrote:

> Thanks. My tests and your tests now pass for me on my system using
> Python 2 and Python 3 on Leo-Editor commit
> 42a5207833e08ff37e767d60e1020f6151b3a70b.
>

​Glad to hear it.​


>
> But, tracing is not fully disabled.


​Now it is.  Iirc, I left this trace enabled because it will rarely happen
outside your special circumstances.

Thanks for continuing to stress these edge cases.  This bug was a release
blocker.  One more to go...

Edward
