### ISSUE TITLE
Desktop-links: sqlite import fails for non-conda-activated CMD shell

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#1300]
This happens on one of my 3 Windows machines

- open a stock CMD shell, python isn't in path, conda is not activated
- run a Leo launch .exe using full path

This has big implications for the Desktop-links project, #1243, if this means the links only works for some compters.

```
C:\Users\Matt
>C:\apps\Miniconda3\envs\leo-dev\scripts\leo-messages.exe
Traceback (most recent call last):
  File "C:\apps\Miniconda3\envs\leo-dev\scripts\leo-messages-script.py", line 11, in <module>
    load_entry_point('leo', 'console_scripts', 'leo-messages')()
  File "c:\apps\miniconda3\envs\leo-dev\lib\site-packages\pkg_resources\__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\apps\miniconda3\envs\leo-dev\lib\site-packages\pkg_resources\__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "c:\apps\miniconda3\envs\leo-dev\lib\site-packages\pkg_resources\__init__.py", line 2434, in load
    return self.resolve()
  File "c:\apps\miniconda3\envs\leo-dev\lib\site-packages\pkg_resources\__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "d:\matt\code\leo-editor\leo\core\runLeo.py", line 27, in <module>
    import leo.core.leoApp as leoApp
  File "d:\matt\code\leo-editor\leo\core\leoApp.py", line 22, in <module>
    import sqlite3
  File "c:\apps\miniconda3\envs\leo-dev\lib\sqlite3\__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "c:\apps\miniconda3\envs\leo-dev\lib\sqlite3\dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: DLL load failed: The specified module could not be found.
```

### Work arounds
- ensure sqlite3.dll is in PATH, e.g. install from https://www.sqlite.org/ or with chocolatey*, or
- Activate base conda shell for _all_ new CMD shells with `conda init cmd.exe` (important note: see linked upstream discussion below), or
- Activate conda shell before calling Leo (each time)

_(\* `choco install sqlite3`, and might need to follow up with creating a symbolic link: `mklink c:\Shims\sqlite3.dll C:\ProgramData\chocolatey\lib\SQLite\tools\sqlite3.dll`)_

**Comment by maphew** [comment]
Specifically, the file `sqlite3.dll` is not in PATH. I've likely not had this problem on my other machines because some other tool has installed it in `Windows\System32` or similar. Even on my problem machine there are 35(!) copies of it scattered all over C: drive, just none in PATH.

Invoking python.exe interactively without activating an env warns us things like this might happen:
~~~
Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 14:00:49) [MSC v.1915 64 bit (AMD64)] on win32

Warning:
This Python interpreter is in a conda environment, but the environment has
not been activated. Libraries may fail to load.  To activate this environment
please see https://conda.io/activation
~~~

And indeed, `import sqlite3` fails with same error as in OP. It's curious to me that regularly installed python (not using conda) doesn't do this, even though it's not in PATH either.

A workaround might be to have launcher try extending sys.path based on location of starting script. This might run afoul of how python works on distributions where Lib and Scripts don't share the same folder tree.

**Comment by edreamleo** [comment]
@maphew The message is [conda issue #9242](https://github.com/conda/conda/issues/9242), which I created.  Some workarounds are discussed there.

Iirc, this doesn't happen if you ignore the installer's advice and *do* set the path.

**Comment by maphew** [comment]
Thanks Edward. Interesting reading.

(I had totally forgotten about `doskey`. At one point a very long time ago I had pages of macros I'd set up. Hard to believe I'd forgotten about them. Kind of cool to know that venerable nigh on 3 decades old utility is still there and working.)

I'm going to close this as "not a Leo problem" unless more people bring it up. Three workarounds are listed here.
