### ISSUE TITLE
Ipython Kernel dies, restarts repeatedly

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#1311]
Run Ipython with:
launchleo.py --ipython

Leo starts and the Jupyter QtConsole launches however the kernel repeatedly dies and restarts.

_Jupyter QtConsole 4.5.4
Python 3.7.4rc1 (tags/v3.7.4rc1:b26441ee1f, Jun 18 2019, 23:26:33) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.8.0 -- An enhanced Interactive Python. Type '?' for help.

Kernel died, restarting

Kernel died, restarting

Kernel died, restarting_
[snip]

Leo Log Window
Leo 6.1-devel, devel branch, build 7d8c77b022
2019-08-29 21:51:51 -0700
Python 3.7.4, PyQt version 5.13.0
Windows 10 AMD64 (build 10.0.18362) SP0

**Comment by edreamleo** [comment]
@LewisNeal Thanks for this report.

**Comment by edreamleo** [comment]
@LewisNeal Please look into [this thread](https://stackoverflow.com/questions/39652946).  Do any of the suggestions there help?

**Comment by LewisNeal** [comment]
Since I reported Jupyter QtConsole has been updated to 4.5.5
launchleo.py --ipython

Leo starts, Jupyter QtConsole launches and is now working fine.

**Comment by edreamleo** [comment]
@LewisNeal Glad to hear all is well.
