### ISSUE TITLE
The history_tracer plugin animates git commits

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#1315]
This plugin animates git commits, showing, in a browser, what each commit did. [This post](https://groups.google.com/d/msg/leo-editor/wM38DuOxvGA/Y7o1T6VIAwAJ) announces the plugin.

[Here](https://www.youtube.com/watch?v=apqc1iri1hA&feature=youtu.be&t=174) is Vitalije's initial demo.

**Comment by vitalije** [comment]
Actually history_tracer plugin doesn't animate git commits nor it has anything to do with git. It is more powerful than that :-).

It animate edit session with much finer resolution. Every 5 seconds of user inactivity, complete outline version is stored. Web application allows browsing every stored version. It would be like animating git commits if user had been doing `git commit` every five seconds.

**Comment by edreamleo** [comment]
@vitalije Thanks for the clarification.

**Comment by edreamleo** [comment]
I am going to close this.  It's likely good enough.
