### ISSUE TITLE
bug: rst viewrender not working for 6.0

### ISSUE THREAD

**Issue by jeremy886** [leo-editor/leo-editor#1317]
I recently installed Leo in a new laptop so I got the latest version **6.0 final** and I notice that my rst viewrender stopped working (just showing the same text).

After I downgraded my leo to 5.9, I got viewrender working again. I reckon it's a bug?

**Comment by edreamleo** [comment]
@jeremy886 This would be a very serious bug.  However, everything appears to work.  I would have expected many bug reports before this if there actually were a problem.

Make sure `@language rest` is actually in effect.

**Comment by jeremy886** [comment]
Thanks. I put @language rest in, then the preview works again. Interesting that I didn't need to do it in older version.

**Comment by edreamleo** [comment]
@jeremy886 Glad that worked.  Not sure why you had to make the change.
