### ISSUE TITLE
Paste text maintains text color

### ISSUE THREAD

**Issue by technatica** [leo-editor/leo-editor#1319]
I copy and paste text a fair bit between applications. When using a dark theme for Leo the text is white. When I paste into an application with a white background, bye-bye visible text. It is still there, just not visible. I must then either highlight it and change the color or paste it into nano or kwrite and then copy/paste it again. Annoying.

When pasting from another application like kwrite, the pasted text is always black, no matter the theme in force or the color of the text.

I see this as a bug as rich text of any description should NOT be part of the workflow of a text editor.

**Comment by edreamleo** [comment]
I'm not sure how the behavior you describe could possibly happen. The relevant code is qt_gui.replaceClipboardWith, which always pastes plain text into the clipboard:
```python
 def replaceClipboardWith(self, s):
    '''Replace the clipboard with the string s.'''
    cb = self.qtApp.clipboard()
    s = g.toUnicode(s)
    QtWidgets.QApplication.processEvents()
    cb.setText(QString(s))
    QtWidgets.QApplication.processEvents()
```

**Comment by technatica** [comment]
Further examination shows that it only applies to text copied from the log
pane.

But it definitely happens. It is easily reproduced by using a dark theme
and copying the log info to github issues, google groups or gmail.

Pasting into a text editor that does not support rich text works as
expected.

Chris

**Comment by edreamleo** [comment]
@technatica The log pane might use different code.  I'll look into it.

**Comment by edreamleo** [comment]
I'm not going do this so-called enhancement.  Regardless of the reason, or the code, maintaining the coloring of the log pane when pasting will be useful in some cases.

There is an easy workaround: copy from log pane, paste to body pane, copy from body pane.
