### ISSUE TITLE
Section Reference causes clone on Leo-Editor file open

### ISSUE THREAD

**Issue by SegundoBob** [leo-editor/leo-editor#132]
Bug Description
---------------

A cloned node reappears every time a particular Leo-Editor file is opened, no matter how many times you delete the clone and save the file without the clone, the clone reappears when the file is opened.

Bug Analysis
------------

My best guess is that the crucial circumstances causing the bug are: (1) The triggering syntax must be in an @file.  The type of the @file doesn't matter. (2) The section reference must be in the grandparent of the section node.

No errors are reported to the log pane.  No errors are reported to the terminal.

Bug Demonstration
-----------------

Put the following two files into any one folder.
Open sectionCausesClone.leo.
Note that node "Child" is cloned.  This is the bug.  In these two files, node "Child" is NOT cloned.  This clone was created when sectionCausesClone.leo was opened.  You can prove this to yourself by deleting either of the cloned nodes, save, exit, and reopen.  Note that once again "Child" is cloned.

sectionCausesClone.leo
----------------------
```
<?xml version="1.0" encoding="utf-8"?>
<!-- Created by Leo: http://leoeditor.com/leo_toc.html -->
<?xml-stylesheet ekr_test?>
<leo_file xmlns:leo="http://leoeditor.com/namespaces/leo-python-editor/1.1" >
<leo_header file_format="2" tnodes="0" max_tnode_index="0" clone_windows="0"/>
<globals body_outline_ratio="0.5" body_secondary_ratio="0.5">
	<global_window_position top="50" left="50" height="500" width="700"/>
	<global_log_window_position top="0" left="0" height="0" width="0"/>
</globals>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="bob05.20150117111055.4"><vh>@file sectionCausesClone.py</vh></v>
</vnodes>
<tnodes>
</tnodes>
</leo_file>
```

sectionCausesClone.py
---------------------
```
#@+leo-ver=5-thin
#@+node:bob05.20150117111055.4: * @file sectionCausesClone03.py
#@+<< imports >>
#@+middle:bob05.20150117111055.5: ** Child
#@+node:bob05.20150117111055.6: *3* << imports >>
#@-<< imports >>
#@+others
#@+node:bob05.20150117111055.5: ** Child
#@+others
#@-others
#@-others
#@-leo
```

Test Systems
------------

Xubuntu32 12.04

I first noted this bug on 2014-12-31 Wed using commit ad0392f8b69824cf19441f9ff9636e654341d536
and Python 2.

I have verified that the bug still exists using commit f6cdb2bccb1a7ca8812f49f0da951cec5617279f
and
Python 2.7.3, PyQt version 4.8.1
and
Python 3.2.3, PyQt version 4.8.1

**Comment by edreamleo** [comment]
The original bug report clearly demonstrates that the bug is in the write logic. The .leo file contains:
    
```
- @file sectionCausesClone.py
  - Child
    - <<imports>>
```
As you can see from the given .py file, there are two @+node sentinels for Child, so the read logic is perfectly justified in creating the clones.  This is pretty good news. In general, the write code is the easier to fix.

**Comment by edreamleo** [comment]
[This discussion](https://groups.google.com/d/msg/leo-editor/HlVEnP7eg6M/x256dWL0AwAJ) shows that the problem is far more serious than accidental cloning.

The proposed solution: eliminate @+middle sentinels.

**Comment by edreamleo** [comment]
rev e10a989 appears to fix this bug, completely and safely:

1. The write code no longer writes @+middle or @-middle sentinels. In fact, it double-checks that it doesn't.

2. The read code warns when reading @+middle sentinels, but otherwise is completely unchanged.

3. The new code passes every test I can think of. In particular, LeoPy.leo loads properly without caching, and write-at-file-nodes leaves all of Leo's sources and plugins unchanged.

4. The new code handles sectionCausesClone.leo/.py exactly as expected in the new scheme of things:

- The code warns about @+middle nodes.
- The code reads the file as expected, putting the << imports >> node in a better place.
- The code writes sectionCausesClone.py as desired.
- The code re-reads sectionCausesClone.leo/.py without further changes or warnings.

Imo, this is a fairly minor change to Leo's read/write code, as far as such major changes go ;-)  Please report any problems, no matter how seemingly small.

**Comment by edreamleo** [comment]
Just for the record, this also resolves what is, in essence, a duplicate issue:

[#89: Spontaneous clones when using sections](https://github.com/leo-editor/leo-editor/issues/89)

**Comment by SegundoBob** [comment]
Your fix appeals to me.

I have verified that now Leo-Editor handles test sectionCausesClone.leo in a reasonable manner.

```
Leo 5.3-devel, build 20160406093412, Wed Apr  6 09:34:12 CDT 2016
Git repo info: branch = None, commit = 653af30ab842
Python 3.4.3, PyQt version 5.2.1
linux
```

But it is unfortunate that Leo-Editor does not display a warning when it changes the tree structure.

In the sectionCausesClone.leo case, the "section" node is moved up one level in the tree.

The other case that I've noticed was when I wanted four or five "section" nodes to be in an order different from the order of the "section" references in their parent node.  No matter how many times I wrote the .leo with the nodes in my desired order, when I re-opened the file, they were in a different order.

As you pointed out they were in the order of the "section" references and that is the only node order information in the .leo file.  So Leo-Editor can't notice the change on the read, but would it be too much trouble to notice the problem on the write?

In the sectionCausesClone.leo case, would it be too much trouble to display a warning on the write or read?

So far I'm one of only two people who have reported noticing unrequested tree structure changes.  Consequently, I would give adding warning messages very low priority.

**Comment by edreamleo** [comment]
> Leo-Editor [now] handles test sectionCausesClone.leo in a reasonable manner.

Thanks for this confirmation.  I appreciate it.

> ...when I wanted four or five "section" nodes to be in an order different from the order of the "section" references in their parent node. No matter how many times I wrote the .leo with the nodes in my desired order, when I re-opened the file, they were in a different order.

I don't believe this can ever change.  The present read code is not simple, and it does honor the data in the external file.  Once can imagine "heroic" attempts to retain existing outline structure, but I've already gone down that road with the ill-fated "View" project.  See:
```leoNotes.txt-->Unused code: do not delete-->leoViews stuff (keep)```
I'm not going down that road again.

Yes, I know that there are languages for which sections must substitute for proper classes and methods. But I am not going to make any major changes to Leo's read code.

> In the sectionCausesClone.leo case, would it be too much trouble to display a warning on the write or read?

Easy enough, but pretty much pointless, imo.  The warning would quickly become noise, as all such warnings do.  The only solution, it seems to me, is to put section definitions where they logically belong in the @file tree.  If you want to manage those sections in other ways, do so in an organizer node _outside_ the @file tree.  You then have complete freedom.

HTH.
