### ISSUE TITLE
beautify commands create pet peeves

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#1324]
Previously, beautifier commands presently generate some of the [pet peeves](https://www.python.org/dev/peps/pep-0008/#pet-peeves) discussed in [pep8](https://www.python.org/dev/peps/pep-0008/). 

Recent revs correct this.  Strong new unit tests have been added.

**Comment by tbnorth** [comment]
black doesn't abide by all the pet peeves rules either, see the peeve
starting:

"If operators with different priorities are used..."

PEP8: hypot2 = x*x + y*y
black: hypot2 = x * x + y * y

Which is trivial, just an observation.

Cheers -Terry

**Comment by edreamleo** [comment]
On Tue, Sep 10, 2019 at 11:52 AM Terry Brown <notifications@github.com>
wrote:

> black doesn't abide by all the pet peeves rules either, see the peeve
> starting:
>
> "If operators with different priorities are used..."
>
> PEP8: hypot2 = x*x + y*y
> black: hypot2 = x * x + y * y
>
> Which is trivial, just an observation.
>

Hehe.  Good to know.

Edward
