### ISSUE TITLE
@others etc. not work in Elixir 

### ISSUE THREAD

**Issue by ZoomQuiet** [leo-editor/leo-editor#1326]
The second (hidden) comment contains the original report, for reference.

#1258 added support for syntax coloring for elixir, and it *did* add entries for elixir to Leo's language dictionaries. 

Both @clean and @file work for me for .ex files.

**Comment by edreamleo** [comment]
Here is the original report.  I've copied it to a new comment so I can hide it :-)

## env.

> ༄  screenfetch

```
                 -/+:.          zoomq@ZQ160626rMBP
                :++++.          OS: 64bit Mac OS X 10.12.6 16G2128
               /+++/.           Kernel: x86_64 Darwin 16.7.0
       .:-::- .+/:-``.::-       Uptime: 3d 6h 24m
    .:/++++++/::::/++++++/:`    Packages: 235
  .:///////////////////////:`   Shell: bash
  ////////////////////////`     Resolution: 2560x1600
 -+++++++++++++++++++++++`      DE: Aqua
 /++++++++++++++++++++++/       WM: Quartz Compositor
 /sssssssssssssssssssssss.      WM Theme: Blue
 :ssssssssssssssssssssssss-     CPU: Intel Core i7-5557U @ 3.10GHz
  osssssssssssssssssssssssso/`  GPU: Intel Iris Graphics 6100
  `syyyyyyyyyyyyyyyyyyyyyyyy+`  RAM: 9010MiB / 16384MiB
   `ossssssssssssssssssssss/
     :ooooooooooooooooooo+.
      `:+oo+/:-..-:/+o+/-
```



> Leo 5.9-b2, build 20190409061733, Tue Apr  9 06:17:32 UTC 2019

- Not running from a git repo
- Python 3.7.3, PyQt version 5.12.3
- darwin
- isPython3: True
- setting leoID from os.getenv('USER'): 'zoomq'
- current dir: /Users/zoomq
- load dir: /Users/zoomq/miniconda3/envs/leo373/lib/python3.7/site-packages/leo/core
- global config dir: /Users/zoomq/miniconda3/envs/leo373/lib/python3.7/site-packages/leo/config
- home dir: /Users/zoomq
- ...

## error.

as norm. Leo edit:
![ScreenShot 2019-09-12 23 07 53](https://user-images.githubusercontent.com/22494/64796410-3d3fd800-d5b2-11e9-9393-cdec8882bb62.jpg)

try `<<hello>>`

![ScreenShot 2019-09-12 23 08 05](https://user-images.githubusercontent.com/22494/64796412-3d3fd800-d5b2-11e9-85d1-f476bd3f3072.jpg)

and `@others` with same code:

![ScreenShot 2019-09-12 23 08 12](https://user-images.githubusercontent.com/22494/64796413-3dd86e80-d5b2-11e9-928b-f03a9a74dfc3.jpg)

but wrote: nn.ex

```elixir
defmodule Nn do
  @moduledoc """
  Documentation for Nn.
  """
  
  @doc """
  Hello world.
  
  ## Examples
  
      iex> Nn.hello()
      :world
  
  """
  def hello do
    :world
  end
  
  # Hello world.
  # 
  # ## Examples
  # 
  #     iex> Nn.hello()
  #     :world
  # 
  # """
  # def hello do
  #   :world
  # end
  # 
  
  # Hello world.
  # 
  # ## Examples
  # 
  #     iex> Nn.hello()
  #     :world
  # 
  # """
  # def hello do
  #   :world
  # end
  # 
  
  
end
```

the `<<hello>>` and `@others` all export as auto comment;

## guess:

- `@doc` ~ the function document macro is conflict with Leo's ?
- means Elixir is real not same Erlang
- Leo need real support Elixir

**Comment by vitalije** [comment]
@edreamleo  it seems to me that you didn't understand what was the issue here. @ZoomQuiet was not complaining that section references or at-others directives don't work as expected. The issue is that it seems elixir's macro has the same spelling as Leo directive `@doc` and causes that remaining text of node is written in external file prefixed with the comment marker. 

Perhaps the solution would be to allow renaming directives per language or user setting `@data leo-directives` and value can be list of pairs:
```
@doc = @ddoc
@code = @_elixir_code
...
```
with defaults as normal Leo directive spellings.

**Comment by ZoomQuiet** [comment]
> @edreamleo it seems to me that you didn't understand what was the issue here. @ZoomQuiet was not complaining that section references or at-others directives don't work as expected. The issue is that it seems elixir's macro has the same spelling as Leo directive `@doc` and causes that remaining text of node is written in external file prefixed with the comment marker.
> 
> Perhaps the solution would be to allow renaming directives per language or user setting `@data leo-directives` and value can be list of pairs:
> 
> ```
> @doc = @ddoc
> @code = @_elixir_code
> ...
> ```
> 
> with defaults as normal Leo directive spellings.

@vitalije thanx for u suggest
i feel base config, for support elixir only is enough ;-)
but: `@data leo-directives`
this config node is where ? and how to re-define only for Elixir projects?

**Comment by edreamleo** [comment]
@vitalije Thanks for the clarification!

Leo supports plain "@" for "@doc" and "@c" for "@code".  Would these be useful workarounds?

**Comment by edreamleo** [comment]
On Tue, Sep 24, 2019 at 8:25 AM Zoom.Quiet <notifications@github.com> wrote:


>    - but, g.globalDirectiveList is the plug-in-api build-in Leo?
>
> Yes.  However, you don't need to use it.  If you can, just use @ instead
of @doc.  Or just avoid @doc in Leo and use plain # comments instead.

Edward
