### ISSUE TITLE
Missing outline for non-existent files

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#1327]
From [this post](https://groups.google.com/d/msg/leo-editor/ncjp0aYvmVA/l7a3MQ2tCQAJ) from Brian Theado:

I found some strange behavior when launching leo with a non-existent file on the command line. If I don't give any files on the command line or if I give the path to an existing file, then it is fine.

But with the new file on command line, the tips windows appears and leo is still running, but there is no other window and I can only exit by hitting ctrl-c. This is on linux.

**EKR**: To see this bug, just execute leo xyzzy.leo.

I used git bisect and found the bad behavior is introduced by commit 313f9e99af.

**EKR**: Thanks, Brian.  This commit was indeed the culprit.  Isolating it was very helpful.

**Comment by edreamleo** [comment]
Fixed at 2ce0f4d in devel.

**Comment by btheado** [comment]
Confirmed I no longer see the issue. Thanks.

**Comment by edreamleo** [comment]
@btheado Thanks for the confirmation.
