### ISSUE TITLE
leo/extensions/asciidoc.py only works with python 2

### ISSUE THREAD

**Issue by jiapei100** [leo-editor/leo-editor#1330]
leo/extensions/asciidoc.py was not Python3 compatible.

[asciidoctor](https://asciidoctor.org/) is a ruby tool.  [asciidoc3](https://asciidoc3.org/) is a python tool. 

asciidoc3 can *not* be run as a python module.  It can *only* be run as an external tool. As a result, I see no reason to include the leo/extensions/asciidoc3 folder.

**Comment by edreamleo** [comment]
@jiapei100 Thanks for this report.  To my knowledge, this incompatibility has never been reported before.

**Comment by maphew** [comment]
There asciidoc python3 landscape is confusing; here's a summary of my findings.

(A) There is [**asciidoc-py3**](https://github.com/asciidoc/asciidoc-py3), an active project with recent commits and under the umbrella of @asciidoc, and http://asciidoc.org. So the orginal. However in the project header they state _"AsciiDoc development is being continued under @asciidoctor"_, a ruby based project. I [asked for clarification](https://github.com/asciidoc/asciidoc-py3/issues/67) about the mixed message:

>"So if you are starting a new project its almost certainly better to start with Asciidoctor, its heavily supported and usually faster, and the implementation language shouldn't matter unless you are going to hack extensions and tooling that will tie you to that specific implementation whichever you choose."

Asciidoc-py3 is not available on pypi and not installable via `pip install https://github.com/asciidoc/asciidoc-py3/archive/master.zip`.

(B) And [**asciidoc3**](https://gitlab.com/asciidoc3/asciidoc3) under the roof of @asciidoc3. The asciidoc3 install process looks [pretty involved](https://asciidoc3.org/pypi.html), but maybe that's about enabling command line use and using as a module like Leo does is okay.

`pip install asciidoc3` on Windows works fine, though the scripts it installs don't work out of the box. `import asciidoc3` in python works but the resultant object doesn't have any functions or obvious things to use.

(C) **Asciidoctor** _"is a drop-in replacement for its predecessor, AsciiDoc Python (asciidoc.py). The Asciidoctor test suite has > 2,350 tests to ensure compatibility with the AsciiDoc syntax."_, however it's programmed in Ruby not Python, so it's not a drop-in replacement for Leo. I don't think anyway.

that's all for now.

**Comment by maphew** [comment]
Related issues: #1253, #1147, #856

**Comment by edreamleo** [comment]
@maphew Thanks, Matt, for your researches.

**Comment by asciidoc3** [comment]
Hi, this is asciidoc3 speaking, the maintainer of - you guessed it - AsciiDoc3 (100% Python 3.5+, Repo on [Gitlab](https://gitlab.com/asciidoc3/asciidoc3) or visit https://asciidoc3.org).
Yes, pip/PyPI looks a little 'unusual' at first glance, but works fine. The reason of this behavior may be seen in the bundle of conf-files and directories, which causes some explicit pathing.
To enhance and smooth this procedure is included in our TODO-list. And to enable the use of asciidoc3 as a module, too.
I confess, I did not realize the leo-editor until last month (shame on me), but this post and this (german) [article](https://www.linux-community.de/ausgaben/linuxuser/2014/10/merken-planen-programmieren/) worked up curiosity.

**Comment by edreamleo** [comment]
On Fri, Sep 20, 2019 at 11:04 AM Berthold Gehrke <notifications@github.com>
wrote:

> Hi, this is asciidoc3 speaking, the maintainer of - you guessed it -
> AsciiDoc3 (100% Python 3.5+, Repo on Gitlab
> <https://gitlab.com/asciidoc3/asciidoc3> or visit https://asciidoc3.org).
> Yes, pip/PyPI looks a little 'unusual' at first glance, but works fine.
> The reason of this behavior may be seen in the bundle of conf-files and
> directories, which causes some explicit pathing.
> To enhance and smooth this procedure is included in our TODO-list. And to
> enable the use of asciidoc3 as a module, too.
>
Thanks for the link.  I've downloaded the .zip file and will play with it
soon.

Is it usual to put the Asciidoc3 folder in site-packages?

> I confess, I did not realize the leo-editor until last month (shame on
> me), but this post and this (german) article
> <https://www.linux-community.de/ausgaben/linuxuser/2014/10/merken-planen-programmieren/>
> worked up curiosity.
>
Welcome aboard.  A lot has happened since 2014 (!), including @clean,
clone-find and git-diff commands, themes, the console gui and LeoWapp (Leo
in a web browser, using flexx) <https://flexx.readthedocs.io/en/stable/>.
And don't forget to check Joe Orr's demo
<https://kaleguy.github.io/leovue/#/t/2/>.

Edward

**Comment by edreamleo** [comment]
I am going to close this issue.  Users, and the VR pane, will use asciidoc3 only as an external program.

asciidoctor claims to be 100 times faster than asciidoc3.  Imo, asciidoctor produce better looking html.
