### ISSUE TITLE
varible name is not defined after run ipython-exec

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#1331]
Only one leo file opened. There is one line code in leo node.

a = 1 + 2

But can not get varible **a** after run ipython-exec.

***

Leo Log Window
Leo 6.1-devel, devel branch, build 860cdd3247
2019-09-15 02:08:23 -0500
Python 3.7.3, PyQt version 5.12.3
darwin

Jupyter QtConsole 4.4.4
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 16:52:21) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.5.0 -- An enhanced Interactive Python. Type '?' for help.

a
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-1-3f786850e387> in <module>
----> 1 a

NameError: name 'a' is not defined

**Comment by edreamleo** [comment]
On Sun, Sep 15, 2019 at 5:43 AM wangzhaohe <notifications@github.com> wrote:

> Only one leo file opened. There is one line code in leo node.
>
> a = 1 + 2
>
> But can not get variable *a* after run ipython-exec.
>
You should be able to assign a value to something that is available from
the ipython side:

g.app.permanentScriptDict['a'] = 'Test'

Alas, it looks like the dreaded software rot has set in.  See the issue
#1336 <https://github.com/leo-editor/leo-editor/issues/1336>.

Edward

**Comment by wangzhaohe** [comment]
I am confused with using **ipython-exec** command.

I want to run **ipython-exec** in Leo command, then check variable in ipython.(Jupyter QtConsole)

For example:

python launchLeo.py --ipython

run a = 1 using ipython-exec, then check print(a) in ipython shell.

Could you teach me to how to accomplish this? Thanks!

**Comment by edreamleo** [comment]
@wangzhaohe I'm not sure ipython-exec works at present.  See #1336.
