### ISSUE TITLE
Plugins:About does not show VR pane

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#1332]
Works in master.  Works with --no-dock.

**Comment by technatica** [comment]
Works or me in devel.

Leo 6.1-devel, devel branch, build cc6b9faa61
2019-09-18 04:59:30 -0500
Python 3.6.8, PyQt version 5.12.3
linux

**Comment by edreamleo** [comment]
@technatica Thanks for the data point ;-)  There are various settings and command-line args involved.

**Comment by edreamleo** [comment]
Fixed at e17363f.
