### ISSUE TITLE
Find Next in Find Tab gives incomplete results

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#1337]
Create nodes:
ABC_1234
     child node> ABC_1234xxx (body text plus ABC_1234)
node_x
node_y (body text ABC_1234)

Running a [Find Next:] search for 'ABC_1234' finds parent node. It then skips the child node headline and body text.
Reverse the search direction, switching to [Find Previous:]
This now finds the  'ABC_1234' which was not found with [Find Next:]

I have Entire outline button ticked.

_Leo Log Window
Leo 6.1-devel, devel branch, build 8c7dc404ab
2019-09-19 08:03:31 -0500
Python 3.6.8, PyQt version 5.13.0
Windows 10 AMD64 (build 10.0.17134) SP0_

**Comment by LewisNeal** [comment]
I see that this is a duplicate of #194 
The problem is only with Find Next in Find Tab.
F3 button works correctly.

**Comment by LewisNeal** [comment]
I'm switching to use the F3 key.
Question is - how to advise new users the Find Next button is problematic?

**Comment by edreamleo** [comment]
On Fri, Sep 20, 2019 at 9:09 PM LewisNeal <notifications@github.com> wrote:

> I'm switching to use the F3 key.
> Question is - how to advise new users the Find Next button is problematic?
>
Relying on documentation is hopeless.

How about replacing the buttons with labels?  This will force users to use
key bindings, or command names.

Edward

**Comment by LewisNeal** [comment]
I'm not familiar at all with how a label functions in Leo.

**Comment by technatica** [comment]
Right now the button has text on it: Find Next: F3

A label is simply text on the background. Remove the button and you remove
complexity. Replacing the button bank in the find dock could reduce space
requirements, making the find dock less of a pain in the ass. We would need
to assign permanent key bindings to all of the choices that don't have one
displayed and include them in the labels.

Chris

**Comment by edreamleo** [comment]
@LewisNeal  Labels don't do anything.  They are just labels.

@technatica The existing code computes the button text by looking for the appropriate key bindings.  The same can be done for labels.

**Comment by edreamleo** [comment]
I am going to leave this issue closed.  Instead, #1342 suggests replacing the buttons in the Find tab with labels.
