### ISSUE TITLE
Smaller minimum size for Leo's main window

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#1339]
This can be a problem for low-resolution screens.

**Comment by maphew** [comment]
Thank you. I didn't want to make an issue of it when there are so many other bigger ones in the air, and one's I've complained about but not contributed to doing something about ;-)

**Comment by edreamleo** [comment]
I am going to downgrade this to Maybe.  My tests show that the present minimum sizes do not, in fact, make any difference.  On both Windows and Linux it is possible to shrink the screen down to next to nothing.

**Comment by edreamleo** [comment]
I am going to close this issue.  It seems that windows can be made very small with the present code.
