### ISSUE TITLE
'chapter-select' command broken

### ISSUE THREAD

**Issue by gatesphere** [leo-editor/leo-editor#134]
Running the 'chapter-select' command gives the following in the console:

Traceback (most recent call last):
  File "C:\cygwin\home\PeckJ\repos\leo\leo-editor\leo\plugins\qt_events.py", line 127, in eventFilter
    k.masterKeyHandler(event)
  File "C:\cygwin\home\PeckJ\repos\leo\leo-editor\leo\core\leoKeys.py", line 3410, in masterKeyHandler
    done = k.doMode(event,state,stroke)
  File "C:\cygwin\home\PeckJ\repos\leo\leo-editor\leo\core\leoKeys.py", line 3490, in doMode
    val = k.callStateFunction(event) # Calls end-command.
  File "C:\cygwin\home\PeckJ\repos\leo\leo-editor\leo\core\leoKeys.py", line 3464, in callStateFunction
    val = k.state.handler(event)
  File "C:\cygwin\home\PeckJ\repos\leo\leo-editor\leo\core\leoKeys.py", line 2616, in fullCommand
    ok = k.callAltXFunction(k.mb_event)
  File "C:\cygwin\home\PeckJ\repos\leo\leo-editor\leo\core\leoKeys.py", line 2674, in callAltXFunction
    func(event)
  File "C:\cygwin\home\PeckJ\repos\leo\leo-editor\leo\core\leoChapters.py", line 418, in selectChapter
    g.es('Chapters:\n' + '\n'.join(names))
TypeError: sequence item 5: expected string or Unicode, QString found

Version info:

Leo 5.0-final, build 20150123105824, Fri, Jan 23, 2015 10:58:24 AM
Git repo info: branch = master, commit = ea695c251c16
Python 2.7.6, PyQt version 4.8.5
Windows 7 x86 (build 6.1.7601) SP1

**Comment by gatesphere** [comment]
It appears something is making 'main' a QString rather than a string.  Running this code from another .leo file with many chapters:

cc = c.chapterController
g.es(cc.chaptersDict.keys())

I get:

[u'RSS Feeds', u'Long-term Projects', u'Web Bookmarks', u'Notes', u'Ideas', u'Reports', 'main', u'Recurring', PyQt4.QtCore.QString(u'main')]

**Comment by gatesphere** [comment]
Apparently, it creates the 'main' chapter twice:

(I enabled the g.trace line in leoPy.leo#Code-->Core classes-->@file leoChapters.py-->class Chapter--> ctor: chapter)

__init__ (chapter) calling cc.tt.createTab(main)
__init__ (chapter) calling cc.tt.createTab(Web Bookmarks)
__init__ (chapter) calling cc.tt.createTab(main)
__init__ (chapter) calling cc.tt.createTab(RSS Feeds)
__init__ (chapter) calling cc.tt.createTab(Recurring)
__init__ (chapter) calling cc.tt.createTab(Long-term Projects)
__init__ (chapter) calling cc.tt.createTab(Ideas)
__init__ (chapter) calling cc.tt.createTab(Notes)
__init__ (chapter) calling cc.tt.createTab(Reports)

**Comment by gatesphere** [comment]
There's a simple patch for this to get chapter-select working again:

Use:

names = cc.setAllChapterNames()

in leoPy.leo#Code-->Core classes-->@file leoChapters.py-->class ChapterController-->Commands (chapters)-->cc.selectChapter & helper

However, this is caused by a possible memory-leak in LeoQtTreeTab -- whenever a chapter is selected, a new QString key is added to cc.chaptersDict.  Investigating.

**Comment by gatesphere** [comment]
Fixed in f61d4f3eae74.

c.cc.tt.selectTab would occasionally be called with a QString as the 'tabName' parameter, instead of a string or unicode string, so a simple guard of 'tabName = g.u(tabName)' fixed the issue and prevented the memory leak.

chapter-select is working as intended, and c.cc.tt.selectTab no longer adds dumb keys to cc.chapterDict.

**Comment by edreamleo** [comment]
On Tue, Jan 27, 2015 at 10:09 AM, Jacob Peck <notifications@github.com>
wrote:

> Closed #134 <https://github.com/leo-editor/leo-editor/issues/134>.
>

​Thanks for this work, Jake.

Edward
