### ISSUE TITLE
no command for @item 'open-leo-settings-leo'

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#1343]
Menu:

+ Settings --> Open LeoSettings.leo 
+ File --> Open Specifc Leo File --> LeoSettings.leo 

return

>no command for @item 'open-leo-settings-leo'

**Comment by edreamleo** [comment]
Strange.  This works for me.

In any case, rev 817ec2e in devel probably will fix this for you.  It adds two new spellings for existing commands: open-leo-settings-leo and open-my-leo-settings-leo.

Please reopen if necessary.

**Comment by wangzhaohe** [comment]
I have tested it. It Run well. Thanks!

**Comment by edreamleo** [comment]
@wangzhaohe You're welcome.  Thanks for the confirmation.
