### ISSUE TITLE
writing an external file failure

### ISSUE THREAD

**Issue by vitalije** [leo-editor/leo-editor#1346]
[bug1332.zip](https://github.com/leo-editor/leo-editor/files/3647212/bug1332.zip)
Attached Leo outline contains two top-level nodes. One that comes from external file,
and the other that contains original copy of the outline that produced external file `a.txt`.

By opening this file one can notice that directives `@first, @code and @comment` all got one extra `@` character, text of the first line is gone and also the comment definition has changed.

I was inspired to make this example while looking at the leo.core.leoAtFile.FastRead code. Inspecting the content of the external file `a.txt` we can see that the file was written incorrectly.
Perhaps reading code is correct, but the external file is incorrect.

the attached file should be named bug1346, but while I was writing this, I expected that the this will be issue 1332.

**Comment by edreamleo** [comment]
@vitalije I see.  The fast read code doesn't handle the @comment directive correctly.

After writing the file, the @comment directive disappears.  After that, the file reads correctly.

Clearly, this is an edge case in one or more places.  Vitalije, if you are willing, I'll delegate this to you.
