### ISSUE TITLE
Unpredictable "NewHeadline" using LeoBridge

### ISSUE THREAD

**Issue by SegundoBob** [leo-editor/leo-editor#1348]
### Bug Symptom:

Sometimes unpredictably when one process uses LeoBridge to create a Leo-Editor file and immediately after this process ends, another process uses LeoBridge to open the just created Leo-Editor file, Leo-Bridge sees an outline with exactly one node with a headline of "NewHeadline" and an empty-string body.  But the file on disk has on the order of ten nodes and none of these nodes has a headline of "NewHeadline."

When the "NewHeadline" symptom occurs, the root node has two parents (both parents are the hidden root node).

The capital letter beginning "NewHeadline" is now unusual.  At least in most cases Leo-Editor now sets new node headlines to "newHeadline".  I believe in the past the capitalized "NewHeadline" was more common.

### Initial "In the Wild" Symptom Observation:

The bug occurs when I run my unit tests for my program that compares two Leo-Editor files.  I have 41 unit tests.  The bug occurs about once every 30 tests, but there is slight tendency for occurrences to cluster in twos and even threes.

I ran these unit tests in 2014 and did not see this Symptom.  The next time I ran these unit tests was now.  So this bug was probably introduced some time after 2014.

### Best Current Intentional Recipe for Reproducing the Symptom:
[test03](https://gist.github.com/SegundoBob/c52f070da864448003dccbc8dc7f2303) is a gist containing three scripts that together are the best current method for reproducing the symptom.
To use this gist, make the three .py files executable in a directory, then run ./test03.py.

test03 produces the bug about 60% of the time.  Here are the statistics for two runs:
```
31 loops 18 errors 58% errors/loops

51 loops 32 errors 62% errors/loops
```
### Test Systems (most recent first):
```
Leo 6.1-devel, devel branch, build 53cf6d1bb1
2019-09-23 10:35:13 -0500
Python 3.6.8, PyQt version 5.11.1
linux
---------
('devel', 'c4c440a6392d')
-----------
('devel', 'f5986d8016ec')

**Comment by edreamleo** [comment]
@SegundoBob  A cff for NewHeadline (case significant) shows that only frame.createFirstTreeNode creates such a headline.

A cff for createFirstTreeNode shows 5 relevant calls to createFirstTreeNode (We can ignore the git-diff methods).  HTH.

**Comment by vitalije** [comment]
After some more testing I am quite convinced that the issue has nothing to do with Leo, but rather with OS and/or Python low level implementation details. I haven't noticed at first that the error outline actually contains no other nodes but a single top level node with empty body and headline 'NewHeadline'. That happens when Leo cannot parse given file. Although process create_file.py exits it doesn't mean it is fully finished. It seems that created file is still being written when subprocess.call returns. Why is that happening I don't know but it is happening. 

Here is a slightly changed main function from check_file.py, which doesn't make any error on my machine.
```
def main():
    args = cmdLineHandler()
    leoPfn = pathlib.Path(args.pathLeo).resolve()
    outlinePfn = pathlib.Path(args.pathOutline).resolve()
    with open(outlinePfn, 'rb') as fdm:
        outline = marshal.load(fdm)
    bridge = leoBridge.controller(gui='nullGui', silent=True,
        verbose=False, loadPlugins=False, readSettings=False)
    time.sleep(0.5)
    cmdrT = bridge.openLeoFile(str(leoPfn))
    checkOutline(cmdrT, outline)
    exit(0)
```
As you can see I've just added time.sleep(0.5) before opening Leo file. I tried with smaller waiting times 0.1, 0.2, 0.3 but it didn't work. With pause of 0.5 seconds on my machine test03.py doesn't find any error. 

There is nothing we can really do about this issue. It is operating system (and/or python implementation) lying that either process create_file.py has finished or the file has been fully written on disk.

[Here](https://gist.github.com/vitalije/e1ae0a9c42459b4e9c659a91e97a9410) is a test rewritten to work in a single python process.  I suggest you to redesign your tests to use a single process if possible or if you are using a sequence of processes then connect them using pipes. The output of one goes to the next as its input. Obviously one can't trust subprocess.call to return after everything is fully written. If you still need to use files to communicate between processes then you'll have to insert some time.sleep(...) calls between processes to let the system fully finish one job before starting another.

Vitalije

**Comment by edreamleo** [comment]
On Thu, Sep 26, 2019 at 3:33 AM Виталије Милошевић <notifications@github.com>
wrote:

> After some more testing I am quite convinced that the issue has nothing to
> do with Leo, but rather with OS and/or Python low level implementation
> details.
>
Vitalije, this is outstanding work.  Many thanks for your investigations.

Here <https://gist.github.com/vitalije/e1ae0a9c42459b4e9c659a91e97a9410> is
> a test rewritten to work in a single python process. I suggest you to
> redesign your tests to use a single process if possible or if you are using
> a sequence of processes then connect them using pipes. The output of one
> goes to the next as its input. Obviously one can't trust subprocess.call to
> return after everything is fully written. If you still need to use files to
> communicate between processes then you'll have to insert some
> time.sleep(...) calls between processes to let the system fully finish one
> job before starting another.


Without looking at the details, this seems like a good way forward.

In my --leo-id post I had originally planned to say that the problems were
*analogous* to a race condition.  And here you are saying that the problems
*are* the result of a race condition.

Edward

**Comment by SegundoBob** [comment]
Vitalije,

Thank you.  Well done.

Edward,

If Vitalije is correct and I think he is, the general problem is as follows.

The problem arises because Unix and Linux associate the cache with file descriptors, not files.  Hence, none of the changes to a file X  by file descriptor A that are in the cache, but not on yet on disk, can be seen by file descriptor B for file X.

In the case of #1348, the fix I recommend is to flush the cache to disk while closing the Leo-Editor file.  Hopefully, Leo-Editor already explicitly closes the Leo-Editor file before terminating?

Suppose a Leo-Editor file (or a writable external file) has file discriptor fdT.  Sometime after the last write to fdT and before fdT is closed, the following should be done:

```
fdT.flush()
os.fsync(fdT.fileno())

```
See [Python 3 - os.fsync() Method](https://www.tutorialspoint.com/python3/os_fsync.htm)



Finally, thanks to my wife who dealt with this problem many times in her work as a communications programmer.

SegundoBob

**Comment by edreamleo** [comment]
@SegundoBob Afaik, the new standard in the the python world is:
```python
with open(path, 'w') as f:
    << write to f >>
```
This is supposed to close f when the "with" statement ends.  Again afaik, flushing f should not be needed, but I'll look into this further.

**Comment by vitalije** [comment]
I've just tried os.fsync but it didn't solve the issue.
instead of cmdrT.save() I wrote:
```
    ...
    fc = cmdrT.fileCommands
    fc.write_Leo_file('', True, True)
    with open(str(leoPfn), 'wt', encoding='utf8') as out:
        out.write(bridge.g.app.write_Leo_file_string)
        out.flush()
        os.fsync(out.fileno())
```

**Comment by SegundoBob** [comment]
Vitalije,

I believe you changed create_file.py.  I believe while your code executes the "Python File Descriptor" underlying cmdrT is still open.  You create a second "Python File Descriptor" for the Leo-Editor file and you use this file descriptor to write the correct data to the file and then to flush this second file descriptor's cache.

I don't know how Linux deals with this conflict.  The first file descriptor has written to the file, but all the data is in cache.  Then you use a second file descriptor to write data to the same bytes of the file that the first file descriptor wrote.  Does the cache now contain two sets of data destined for the same place on disk?  Which one wins?  Is the flush and fsync honored?

Then what happens when the first file descriptor is closed and its cache is eventually flushed to disk?

My first, uninformed guess, about how Linux works would be that it doesn't care or notice that two file descriptor caches are in conflict.  So your flush() and fsync() are honored, and it doesn't matter when the cache for Leo's file descriptor gets written to disk because it is writing exactly the same data.  But if Linux really works this way, your code should fix the problem.

But your code does not change the symptoms at all.  The test still fails about 55% of the time and it always fails because the test file is seen as empty.

Maybe I'm wrong about how the Linux cache works.  Maybe I'm wrong about what causes #1348.

How about using the Leo-Editor file descriptor for the flush() and fsync()?

SegundoBob

**Comment by vitalije** [comment]
@SegundoBob there is no other file descriptor inside open commander. For commander being open it doesn't mean that the file is still open. Commander on start opens file for reading if the file exists, reads it, parses it, builds the outline and then closes it. It then can operate on the outline without opening original file. During the operation c.save the file is opened again but now for writing, and Leo opens it inside the `with` block. Inside this block Leo puts the content in the output file, and `with` block automatically closes the file once it is finished. 

Your proposition was to do `fd.flush();os.fsync(fd.fileno())` inside `c.save`. Before changing Leo's core I wanted to test your hypothesis by writing Leo to string, and then using your method for ensuring the data is properly synchronized with disk. As you had witnessed yourself, it didn't solve the issue. Therefore I see no reason for implementing this change in Leo's core.

I've found this [thread](https://stackoverflow.com/questions/7127075/what-exactly-the-pythons-file-flush-is-doing) on the stackoverflow. Among other comments there is the following one:

> fsync is necessary for atomicity. you can't expect to close a file, reopen it and find your content without a fsync in the middle. It often works, but it doesn't on linux with ext4 and default mount options for example. Also fsync is not guaranteed to really magnet-flip the iron on the platters, because 1: fsync can be disabled (by laptop-mode), and 2: the hard disk internal buffering might not be instructed to flush. – v.oddou Sep 9 '14 at 6:48

It seems to me this gives us rather good explanation of the issue with test03.py. Even if you force system to do fsync, there is no guarantee that this will happen immediately because your hard disk may delay it a bit.

**Comment by SegundoBob** [comment]
[Edward's comment](https://github.com/leo-editor/leo-editor/issues/1348#issuecomment-535668005)
>@SegundoBob Afaik, the new standard in the the python world is:
> 
> ```python
> with open(path, 'w') as f:
>     << write to f >>
> ```

Good point.  The well-defined  implicit-closure point in a with statement is at least as good as an explicit close, and is probably better in almost every case.

To insure that flush() and fsync() are called even on error termination, you would need to define a custom "with statement context manager" with the flush and fsync() in the __exit__() method.

SegundoBob

**Comment by vitalije** [comment]
Given that `fsync`
> often works, but it doesn't on linux with ext4 and default mount options for example. Also fsync is not guaranteed to really magnet-flip the iron on the platters, because 1: fsync can be disabled (by laptop-mode), and 2: the hard disk internal buffering might not be instructed to flush. – v.oddou Sep 9 '14 at 6:48

I am going to close this issue. I hope you don't mind. There is nothing we can do about it in Leo, except to put `time.sleep(0.5)` after closing file. But that would be wasteful.

**Comment by edreamleo** [comment]
@vitalije I agree with you decision to close this issue.  Many thanks to you and Bob for your work on this issue.

**Comment by SegundoBob** [comment]
[Vitalije,](https://github.com/leo-editor/leo-editor/issues/1348#issuecomment-535814519)

I agree.  flush() and fsync() do not fix the problem.

I think that caching internal to a disk is unlikely to cause the stale data problems that Linux caching causes.  A disk internal cache is based on disk block/sector address.  There is one cache for all disk users.  Both write and read first check the cache and when possible set or return data without going to the "hard' media.  In the #1348 test scenario, disk caching would not cause any problems.

I can't point to any very good descriptions of disk caching, but these give minimal information:

https://www.webopedia.com/TERM/D/disk_cache.html

https://www.techjunkie.com/what-is-hard-drive-cache/

I believe Vitalije's guess about the cause of #1348 is wrong.  #1348 is not caused by Linux caching by file descriptor nor by disk caching.

I will put the delay workaround in my unit tests, but I will continue to investigate #1348.

SegundoBob

**Comment by SegundoBob** [comment]
Edward and Vitalije,

I don't care if you close #1348 or leave it open.  I think it is a bug in Leo-Editor and that it can probably be fixed in Leo-Editor.  But I have other things to do, and if I ever make any progress on it, it will be after you both have done tens or hundreds of others things.

SegundoBob

**Comment by vitalije** [comment]
I suggest you to try to create a ram-disk somehow (I've never done it in linux). It might be that /tmp by default on Ubuntu is a ram-disk. And then try to execute your test inside ram-disk. If the probelm doesn't appear again, then you can be sure that it is the disk related and not Leo/Python issue.

**Comment by SegundoBob** [comment]
### Test Programs and Procedures:
My public gist [test03](https://gist.github.com/SegundoBob/c52f070da864448003dccbc8dc7f2303) Rev 5 contains the three scripts I used in the testing I'm reporting here in.  To use this gist, make the three .py files executable in a directory, then run ./test03.py.

The basic strategy and structure of test03 is unchanged.  Some tests have been simplified.  Some additional checks have been added.

### Bug Symptoms:

1) About half the time test03_check_file.py sees test.leo containing one node with headline "NewHeadline" and an empty body.

2) About one time out of 200 or 300 test03_check_file.py sees test.leo containing 5 nodes with headlines:
```
0 Headline
NewHeadline
0.1 Headline
0.2 Headline
0.2.0 Headline
```
Analysis:  In this case the unpredictable (asynchronous) bug happened to hit the second node in the outline, instead of the root.

3) Inserting a half-second sleep reduces the failure rate to about 10% (1 in 10 tests fail):  Open test.leo, write test.leo, close test.leo, sleep half-second, open test.leo.

4) Every time test03_check_file.py sees a node with headline "NewHeadline", this "NewHeadline" node has two parents.  It should only have one parent.  When the root node is the "NewHeadline" node, both parents are the hidden root node.  When the "NewHeadline" node is not the root node, I don't know what the parents are.

### Using the Known Symptoms to Chase the Bug

Hitting the root node occurs orders of magnitude more often than hitting the second node.  It is easy to find the root node given a Leo-Editor commander.  It is easy to test the number of parents given a position.  For test03, every node should always have exactly one parent.

So I tried to find the code responsible for giving the root node two parents, by placing the following code at various places in the Leo-Editor core in leoBridge.openLeoFile():
```
        if len(c.rootPosition().v.parents) != 1:
            import pdb; pdb.set_trace()
```

When I placed the above "conditional breakpoint" in bridge.createFrame() just before it returns, and in bridge.openLeoFile() right after the return from bridge.createFrame(), test03 broke in bridge.openLeoFile() every time.  It never broke in bridge.createFrame().

Every time test03 broke and I continued, test02_check_file() saw an outline consisting of just a root with headline "NewHeadline."

These conditional breakpoints did not change the failure rate.  About half the tests failed.

Analysis:  A return statement does not change the number of parents of the root node.  Only Leo-Editor code knows about nodes and parents, so only Leo-Editor code can change the number of parents of the root node.  Hence, a Leo-Editor process other than the main Leo-Editor process, is giving the root node a second parent.

### Test Systems (most recent first):
```
Leo 6.1-devel, devel branch, build da55f3fbad
2019-10-06 16:53:59 -0500
Python 3.6.8, PyQt version 5.11.1
linux

Leo 6.1-devel, devel branch, build 53cf6d1bb1
2019-09-23 10:35:13 -0500
Python 3.6.8, PyQt version 5.11.1
linux
---------
('devel', 'c4c440a6392d')
-----------
('devel', 'f5986d8016ec')

**Comment by btheado** [comment]
@SegundoBob, 

> When I placed the above "conditional breakpoint" in bridge.createFrame() just before it returns

>  test03 broke in bridge.openLeoFile() every time. It never broke in bridge.createFrame().

`bridge.createFrame` has 2 returns. The early return is the one which will be called in your case. Did you put the conditional breakpoint before both returns?

**Comment by SegundoBob** [comment]
Oops.  I missed the two-statements-on-one-line return. 

Thanks.  Now I have more testing to do, and hopefully only one process is involved in the problem.

**Comment by SegundoBob** [comment]
## Conclusions
The bad behavior occurs during the open Leo-Editor file done by test03_check_file.py.   Within this open the bad behavior occurs during the call to self.readWithElementTree(path, s) from FastRead().readFile().  s is the binary XML string representing test.leo and it is correct.  That is, the problem is **not** caused by Linux or Python failing to deliver the correct XML to Leo-Editor.

## How to Confirm these Conclusions
Add checks to Leo-Editor core code but only use this modified Leo-Editor code to run test03.py, because the checks fail on most Leo-Editor files and drop into the debugger pdb.

You can easily restore your Leo-Editor with this command:
```
git checkout HEAD -- leo/core/leoFileCommands.py
```
In leoFileCommands.py replace FastRead().readFile() with the following:
```
def readFile(self, path):
    """Read the file, change splitter ratiors, and return its hidden vnode."""
    with open(path, 'rb') as f:
        s = f.read()
    if len(s) != 838:
        import pdb; pdb.set_trace()
    if len(self.c.rootPosition().v.parents) != 1:
        import pdb; pdb.set_trace()
    v, g_element = self.readWithElementTree(path, s)
    if len(self.c.rootPosition().v.parents) != 1:
        import pdb; pdb.set_trace()
    self.scanGlobals(g_element)
        # Fix #1047: only this method changes splitter sizes.
    #
    # Fix bug #1111: ensure that all outlines have at least one node.
    if not v.children:
        new_vnode = leoNodes.VNode(context=self.c)
        new_vnode.h = 'newHeadline'
        v.children = [new_vnode]
    return v
```
My public gist [test03](https://gist.github.com/SegundoBob/c52f070da864448003dccbc8dc7f2303) Rev 5 contains the three scripts I used in the testing I'm reporting here in. To use this gist, make the three .py files executable in a directory, then run ./test03.py.

The check code added to Leo-Editor leaves the frequency of occurrence of bad behavior unchanged at about 50% of the time.

Checking that string s is in fact the correct XML, is complicated because each loop creates a new test.leo with new GNX's.  I have checked the correctness several times, and you may want to check it also.  The length does not change, so that is what the code above tests.

## Unknown
I have no idea why the bad behavior is unpredictable instead of occurring every time.

## Personal
I will be unavailable for about the next three weeks.

**Comment by btheado** [comment]
I'm curious to know if a given xml string which failed will fail again. Is it easy for you to test that? You say you will be gone for 3 weeks, so maybe not :-).

It seems unlikely that xml with only different gnx values could cause a problem, but who knows?

**Comment by SegundoBob** [comment]
It is impossible to reproduce the problem without changing the GNX's, because Leo-Editor produces a new Universally Unique Identifiers (UUID's a.k.a. GNX's), except for the case of "paste retaining GNX."

Simply launching a process over and over to check an existing Leo-Editor file never fails.

Reproducing the failure requires:  1) launch a process to create a Leo-Editor file, then 2) launch a process to check the Leo-Editor file.    Every Leo-Editor file create produces new GNX's.

**Comment by btheado** [comment]
I'm seeing a gnx clash causing the issue. The generated outline contains several nodes all with properly unique gnx. This outline is saved to test.leo. The 'create' process exits and the 'check' process is launched.

The new process can start quickly, within the same second the old process was running. So the date/time part of the gnx is the same in the new and old process.

The test.leo with proper gnx is read by leo, but for some reason, before it is read, some code within leo startup is generating a gnx into the gnx dict. This gnx clashes with one of the gnx in test.leo (usually the first one). When the nodes from the xml are processed, the code finds the gnx is already there and thinks it is a clone of and already existing node.

Here is the call stack I found where the conflicting gnx is generated before the xml file is read:

```
(Pdb) bt
  .../leo-editor/check_file.py(122)<module>()
-> main()
  .../leo-editor/check_file.py(56)main()
-> cmdrT = bridge.openLeoFile(str(leoPfn))
  .../leo-editor/leo/core/leoBridge.py(271)openLeoFile()
-> c = self.createFrame(fileName)
  .../leo-editor/leo/core/leoBridge.py(304)createFrame()
-> c = g.openWithFileName(fileName)
  .../leo-editor/leo/core/leoGlobals.py(3916)openWithFileName()
-> return g.app.loadManager.loadLocalFile(fileName, gui, old_c)
  .../leo-editor/leo/core/leoApp.py(3271)loadLocalFile()
-> previousSettings = lm.getPreviousSettings(fn)
  .../leo-editor/leo/core/leoApp.py(2231)getPreviousSettings()
-> c = lm.openSettingsFile(fn)
  .../leo-editor/leo/core/leoApp.py(2390)openSettingsFile()
-> c = g.app.newCommander(fn)
  .../leo-editor/leo/core/leoApp.py(1616)newCommander()
-> relativeFileName=relativeFileName,
  .../leo-editor/leo/core/leoCommands.py(79)__init__()
-> c.finishCreate()
  .../leo-editor/leo/core/leoCommands.py(405)finishCreate()
-> c.frame.finishCreate()
  .../leo-editor/leo/core/leoFrame.py(1753)finishCreate()
-> self.createFirstTreeNode()
  .../leo-editor/leo/core/leoFrame.py(706)createFirstTreeNode()
-> v = leoNodes.VNode(context=c)
  .../leo-editor/leo/core/leoNodes.py(1959)__init__()
-> g.app.nodeIndices.new_vnode_helper(context, gnx, self)
  .../leo-editor/leo/core/leoNodes.py(100)new_vnode_helper()
-> v.fileIndex = ni.getNewIndex(v)
  .../leo-editor/leo/core/leoNodes.py(87)getNewIndex()
```

Add the following g.es_print statements in FastRead.v_element_visitor to see the gnx clash get detected as a clone:

```python
def v_element_visitor(parent_e, parent_v):
    """Visit the given element, creating or updating the parent vnode."""
    for e in parent_e:
        assert e.tag in ('v','vh'), e.tag
        if e.tag == 'vh':
            parent_v._headString = g.toUnicode(e.text or '')
            continue
        gnx = e.attrib['t']
        g.es_print(gnx)
        v = gnx2vnode.get(gnx)
        if v:
            g.es_print(f'clone found for gnx {gnx}')
```

**Comment by edreamleo** [comment]
@btheado Thanks, Brian, for this sleuthing.

**Comment by SegundoBob** [comment]
[btheado](https://github.com/leo-editor/leo-editor/issues/1348#issuecomment-542014635),

Great.  Impressive.  Thanks.

SegundoBob

**Comment by vitalije** [comment]
@SegundoBob can you repeat your tests  with the a57a57996d95920. I hope it will solve this issue too.
