### ISSUE TITLE
Find - Status

### ISSUE THREAD

**Issue by technatica** [leo-editor/leo-editor#1349]
In the Find dock widget, there is a text input field with the label "Status".

This appears to have no function.

The text input field can be typed in but hitting enter does nothing.

The status of search operations seems to go to the status bar which works well.

Is this redundant? Can it be removed?

**Comment by edreamleo** [comment]
On Wed, Sep 25, 2019 at 10:42 AM Chris George <notifications@github.com>
wrote:

> In the Find dock widget, there is a text input field with the label
> "Status".
>
Good catch.  This appears to be cruft, related to quite a bit of other
cruft, including logic involving qtGui.globalFindDialog.  I'll clean this
up soon.

Edward

**Comment by edreamleo** [comment]
Fixed at d51ad2b in devel.
