### ISSUE TITLE
LeoBridge option to not use the cache

### ISSUE THREAD

**Issue by SegundoBob** [leo-editor/leo-editor#1350]
So far as I know, the only information in the Leo-Editor cache that might be of interest to LeoBridge or a user of LeoBridge is which vnodes are marked.  In all my uses of LeoBridge thus far, I have never cared which vnodes are marked.  Consequently, I would like to be able to cause LeoBridge to not read or use the cache in any way.  I suggest a new keyword argument "nocache=False" to method leoBridge.controller().

SegundoBob

**Comment by edreamleo** [comment]
@SegundoBob I'll look into this immediately.

**Comment by edreamleo** [comment]
@SegundoBob rev ff3deb in the bridge branch adds the "useCaches" kwarg to the ctor of the BridgeController class.  This is experimental code.

I don't want to change any file except leoBridge.py.  Caching is iffy enough as it is without adding more "if" statements throughout Leo's core.  

The new code sets both g.app.db and c.db to a g.NullObject.  That might cause crashes.  Please check.  

Note that c.db is set to g.NullObject *after* creating c.  That's a result of the constraint that only leoBridge.py can change.  So the code might use the "real" c.db while creating c.  Not sure whether that matters.

**Comment by edreamleo** [comment]
@SegundoBob In view of recent discoveries, this item seem unnecessary.

With your permission, I would like to move the new code in the "bridge" branch to Leo's attic.  I'll then kill the bridge branch.

**Comment by SegundoBob** [comment]
Edward,

My request has nothing to do with #1348.

I hoped that it would make LeoBuild simpler and more stable.  It might make LeoBuild faster, but that seems unlikely.

LeoBuild is obviously your stepchild.  As long as I'm the only visible user of LeoBuild, your priorities are very sensible.

SegundoBob

**Comment by edreamleo** [comment]
Completed at a4733b6 in devel.  All unit tests pass when run directly, or from the bridge.

The only changes made outside of leoBridge.py were in leoGlobals.py:
- g.toUnicode doesn't warn if the supposed string is a NullObject or TracingNullObject.
- Tweaked the NullObject and TracingNullObject classes:
  `__delattr__` and `__setattr__` return None, not self.

**Comment by edreamleo** [comment]
@SegundoBob This project has been worthwhile, if only for the tweaks to leoGlobals.py mentioned above.  Having said that, I'm not sure using useCaches=False is going to help.

**Comment by SegundoBob** [comment]
### Bug Symptom

Set useCaches=False option on call leoBridge.controller(), then use this controller to create and save a .leo file, then close this controller. An exception occurs in the close because g.app.global_cacher is None.

If the controller is not explicitly closed, then no exception occurs when the test program terminates.

### Test Program

[useCaches01](https://gist.github.com/SegundoBob/f86f5f1ec5fa3a539a72d0bd13e4d0e8)

### Test System
```
Leo 6.1-devel, devel branch, build 3dc83b4d61
2019-10-03 06:30:08 -0500
Ubuntu 18.04
```

### Test Program Execution
```
2019-10-03 16:25:50 /pri/git/leo_bug_demos/2019-10-03-useCaches
$ ./useCaches01.py
Leo 6.1-devel, devel branch, build 3dc83b4d61
2019-10-03 06:30:08 -0500

Traceback (most recent call last):
  File "./useCaches01.py", line 41, in <module>
    main()
  File "./useCaches01.py", line 36, in main
    cmdrT.close()
  File "/pri/git/leo-editor/leo/commands/commanderFileCommands.py", line 56, in close
    g.app.closeLeoWindow(self.frame, new_c=new_c)
  File "/pri/git/leo-editor/leo/core/leoApp.py", line 1348, in closeLeoWindow
    g.app.finishQuit()
  File "/pri/git/leo-editor/leo/core/leoApp.py", line 1380, in finishQuit
    g.app.global_cacher.commit_and_close()
AttributeError: 'NoneType' object has no attribute 'commit_and_close'
2019-10-03 16:27:00 /pri/git/leo_bug_demos/2019-10-03-useCaches
```

**Comment by edreamleo** [comment]
Rev 915d63 should be the fix.  Please reopen if it isn't.
