### ISSUE TITLE
Headline click commands throw exception

### ISSUE THREAD

**Issue by btheado** [leo-editor/leo-editor#1351]
I stumbled across some commands which throw exceptions when executed.

AttributeError: 'LeoQtTree' object has no attribute 'onHeadlineRightClick'

`onDoubleClickHeadline, onHeadlineClick, onHeadlineRightClick` - were all removed in commit 8e35e492a3c13, but the corresponding commands which call those methods still exist.
`double-click-headline, click-headline, right-click-headline`

`simulate-begin-drag` and `simulate-end-drag` fail in a similar way

I have no desire to use any of these commands...just wanted to share what I noticed in case you want to either clean up the broken code or restore the functionality.

**Comment by edreamleo** [comment]
Fixed at 8d5f991 in devel.
