### ISSUE TITLE
end-of-line command on blank last line moves cursor up a line

### ISSUE THREAD

**Issue by btheado** [leo-editor/leo-editor#1354]
With #1353, I'm now using the `end-of-line` command more often and I found if the last line in a node body is blank and the cursor is on that last line, then the `end-of-line` command will move the cursor to the end of the previous line. I expect the cursor to stay where it was as the `end-of-line` command should never cause the cursor to change lines.

I have some failing unit tests and a fix (which I'm not 100% confident about) for this issue. I will submit it in a pull request.

**Comment by edreamleo** [comment]
Thanks for this work.  It has been merged into devel.  We may as well test it in devel.
