### ISSUE TITLE
Cursor in Replace Text Input Disables Alt-x

### ISSUE THREAD

**Issue by technatica** [leo-editor/leo-editor#1356]
1. Highlight word in body of a node.
2. Ctrl-f to open Find widget and place word in Find text input.
3. Tab, enter Replace word.
4. Alt-x does nothing.

**Comment by edreamleo** [comment]
@technatica It works for me.

**Comment by technatica** [comment]
More specifically, if you enter the replacement string into the text input
field and the hit Alt-x, nothing happens.

If there is no string in the text input field, it works just fine.

Chris

**Comment by edreamleo** [comment]
@technatica What is your platform?  I can not duplicate the behavior you describe on Windows.

**Comment by technatica** [comment]
Leo 6.1-devel, devel branch, build dc72b05e56

2019-09-28 22:28:17 +0200

Python 3.6.8, PyQt version 5.12.3

linux

**Comment by edreamleo** [comment]
This works for me on Ubuntu linux.  It may be a key binding problem on your end.

**Comment by technatica** [comment]
Okay.

I disabled all shortcuts in myLeosettings.leo and the behavior persists.

If there is anything in the replace text box and the cursor is in it, Alt-x
puts an x at the end of the string and nothing else. Both Alt-r and Alt-l
do the same thing. 'xmodmap -pke' reports that both are mapped as alt.

I don't know what to try next.

Chris

**Comment by edreamleo** [comment]
On Mon, Sep 30, 2019 at 10:58 AM Chris George <notifications@github.com>
wrote:

I don't know what to try next.
>

Ctrl-G followed by Alt-x should be the workaround.

Edward

**Comment by technatica** [comment]
That will do it. It isn't like that particular action is something I do a
lot. I just happened to notice it while trying to figure out why I can't
replace all.

Chris
