### ISSUE TITLE
Replace All - Doesn't Work

### ISSUE THREAD

**Issue by technatica** [leo-editor/leo-editor#1357]
1. Open Find widget. (Ctrl-F)
2. Enter a search string in the Find text input field. Hit tab to advance to the replace text input field.
3. Enter a replacement string in the Replace text input field. 

Now what?

I do not want to replace and find next. I have 174 changes to make. 

Trying to execute replace-all doesn't work. Alt-x replace-all puts the find string in the mini-buffer, hitting enter selects the next instance. Ctrl-Shift-r does the same.

All of the other find/replace functions work as per the docs. The following is the extent of the documentation for this command.

"``replace-all``
    Changes all occurrences of the 'find' text with the 'change' text."

I follow the 'def - foo' procedure in the docs exactly but there is no specific step to 'replace-all'.

**Comment by edreamleo** [comment]
Just do <alt-x>replace-all<return>.

You will be prompted for a search pattern.  Enter it and hit <tab>, just as for Leo's incremental search command.  Now enter the replacement pattern.

Hit <return> to do the replacements.  Do <escape> or Ctrl-G to abort the command.

**Comment by technatica** [comment]
1. Alt-x, replace-all
2. Enter search pattern and hit enter (this selects the first instance of
the search pattern in the file)
3. Hit , (this replaces the first instance of the search pattern with a ,)
4. Enter the replacement string (this enters the replacement string after
the , where the first instance of the search string was)

Alternatively,

1. Alt-x, replace-all
2. Enter search pattern and hit , (this adds a , after the search pattern
in the mini-buffer)
3. Enter the replacement pattern (which ends up after the , in the
mini-buffer)
4. Hit enter (pattern not found as it is one string with two patterns
separated by a comma.

I am honestly not trying to be obtuse but the documentation isn't helpful
at all. I can find nothing about incremental search and a , at all in
LeoDocs.leo.

As usual, I am on Linux.

Chris

**Comment by edreamleo** [comment]
My apologies for the lack of proper documentation.  I have just created #1391 for this.
