### ISSUE TITLE
copy and rename @file node wrongly wants to overwrite original

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#1359]
_Copy and paste of at-file node gets mixed up between original and target external files' name and/or path._

I was able to reproduce the occurences below about ten times as I tried various things to narrow the scope and create a recipe that someonelse could try. Then the problem just disapeared.  

Recipe, original encounter:

- open Desktop-integration.leo
- copy node _#scripts-->Any-->_#scripts-->Any-->@file **add**-desktop-links.leox_.leox_ 
- paste node at same place in tree
- rename to _#scripts-->Any-->@file **remove**-desktop-links.leox_
- edit contents of the copied _remove links_ node, adding and removing body lines
- Save:
   - warning dialog (not verbatim): "@file add-desktop-links.leox has changed. Overwrite?" - this is the source node. It was not changed but I answered "Yes"
   - warning message: "Path has changed for @file remove-desktop-links.leox" - the copied node.

**Result: the source external file on disk is now empty, it's contents wiped!**. The 2nd external file is ok, it reflects the expected edits.

Basic troubleshooting method was to reset the code repo to the prior commit, e035a658, delete some other nodes in the .leo file, save and exit, restart Leo and open the file, try recipe again, answer the overwrite Yes, then repeat recipe with No. Rinse, lather, repeat.

Somewhere in the course of experimenting the problem disappeared completely and I haven't been able to reproduce again. This makes me think the problem wassn't directly in the files from the source code repo but somewhere in my local ~/.leo folder. 

I'm closing this bug report even though it wasn't clearly identitied or fixed because I can no longer reproduce it and I don't think anyone else is likely too either. I'm still creating the report so there is something to refer to just in case does re-occur someday.

**Comment by vitalije** [comment]
What was the revision you encountered this bug? I had similar problems and I fixed them yesterday and pushed. Perhaps some change I made caused this bug, or perhaps it is fixed with the same fix from yesterday?

**Comment by maphew** [comment]
@vitalije it was before your work, [desktop-links](https://github.com/leo-editor/leo-editor/tree/desktop-links) branch, between e035a6580c874b2d86bd4c39d8b10938449af062 and f20b257b36d0f4699b26f271b0a3f3d0929bebcb

**Comment by edreamleo** [comment]
On Sun, Sep 29, 2019 at 12:57 PM matt wilkie <notifications@github.com>
wrote:

> *Copy and paste of at-file node gets mixed up between original and target
> external files' name and/or path.*
>
> I was able to reproduce the occurences below about ten times as I tried
> various things to narrow the scope and create a recipe that someonelse
> could try. Then the problem just disapeared.
>

I wonder whether a recent fix for #1347
<https://github.com/leo-editor/leo-editor/issues/1347> may have helped.
The fix checks a warning and issues a warning if appropriate.  The fix
applies to most (all?) external files.

Edward
