### ISSUE TITLE
Viewrendered2 chokes on displaying @html nodes

### ISSUE THREAD

**Issue by gatesphere** [leo-editor/leo-editor#136]
Viewrendered2 enters a terribly broken state upon selection of an @html node when the vr pane is open:

```
hook failed: select2, <bound method ViewRenderedController.update of <leo.plugins.viewrendered2.ViewRenderedController object at 0x0908E080>>, <no module>
Traceback (most recent call last):
  File "C:\cygwin\home\PeckJ\repos\leo\leo-editor\leo\core\leoPlugins.py", line 357, in callTagHandler
    result = handler(tag,keywords)
  File "C:\cygwin\home\PeckJ\repos\leo\leo-editor\leo\plugins\viewrendered2.py", line 1691, in update
    f(s,keywords)
  File "C:\cygwin\home\PeckJ\repos\leo\leo-editor\leo\plugins\viewrendered2.py", line 1835, in update_html
    w.setHtml(s)
AttributeError: 'WebViewPlus' object has no attribute 'setHtml'
```

After this, the auto-update functionality is broken, and Leo requires a reload to fix VR2's usability.

Version info:

Leo 5.0-final, build 20150127110559, Tue, Jan 27, 2015 11:05:59 AM
Git repo info: branch = master, commit = e4b9b05e377f
Python 2.7.6, PyQt version 4.8.5
Windows 7 x86 (build 6.1.7601) SP1

**Comment by edreamleo** [comment]
Fixed at rev e11f6f0.
Please do not reopen this issue.  If other problems are found, please contact the author, Peter Mills.

**Comment by tbnorth** [comment]
On Thu, 11 Jun 2015 14:30:14 -0700
"Edward K. Ream" <notifications@github.com> wrote:

> Fixed at rev e11f6f0.
> Please do not reopen this issue.  If other problems are found, please
> contact the author, Peter Mills.

On my list of things I want to do for Leo, although not at the top, is
"merge" the two viewrendered plugins - I started the functionality
checking (pseudo unit testing) needed, but haven't got further.  Anyway
I hope that this confusing division can be resolved eventually.

**Comment by edreamleo** [comment]
@tbnorth I'll probably do the merge within a week, unless you object ;-)

**Comment by tbnorth** [comment]
Not at all, please go ahead :-)  my leo time is still very limited and it's not top of the list. 
Cheers -Terry
