### ISSUE TITLE
Can't change some vertical heights running --global-docks

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#1363]
Run Leo using --global-docks

I can't change the vertical size of the Leo window by clicking/dragging the edge.
I can change the horizontal width.
**EKR**: it works for me.

Within the Shells of the pyzo file browser, I am unable to drag any borders to change the vertical heights. Within the Leo side however, I can drag borders vertically.
**EKR**: The pyzo file browser works within Leo just as it does within pyzo itself.

Leo Log Window
Leo 6.1-devel, devel branch, build aef7ecffa2
2019-10-01 09:10:53 -0500
Python 3.7.4, PyQt version 5.13.1
Windows 10 AMD64 (build 10.0.18362) SP0
NoneType: None

**Comment by edreamleo** [comment]
@LewisNeal Thanks for testing the new code.  I'll look into this, but there are no guarantees.

**Comment by edreamleo** [comment]
@LewisNeal What do you mean by "Within the Shells of the pyzo file browser" ?

**Comment by LewisNeal** [comment]
Updated to Leo 6.1-devel, devel branch, build cb01d4f193
I can now change the vertical size of the Leo window by clicking/dragging the edge. 

On the RHS of the Body pane, in the Pyzo file browser, I was not able to drag the bars vertically between:

File Browser
---------------------
History viewer
---------------------
Interactive help
---------------------
Logger
---------------------
Workspace
---------------------

After updating Leo that is no longer a problem.

**Comment by LewisNeal** [comment]
I'm reopening this as I notice I have limited ability changing the vertical size of the Leo window by clicking/dragging the top and bottom edge.
I cannot reduce the height of window by more than about 20mm. It then stops even as I continue dragging the mouse.
