### ISSUE TITLE
@file write fails after file rename

### ISSUE THREAD

**Issue by largo84** [leo-editor/leo-editor#1367]
1. Create new @file node (eg. @file Test.txt).
2. Save Leo creates file as expected.
3. Rename file to @file Test-2.txt (change node headline).
4. Save Leo saves the ..leo file but does *not* create the new file.

Tested on @clean and @auto-md and these work as expected.

Environment:
`Leo 6.1-devel, devel branch, build be8e36d21a
2019-10-04 07:27:12 -0500
Python 3.7.4, PyQt version 5.13.0
darwin`

**Comment by SegundoBob** [comment]
[largo84](https://github.com/leo-editor/leo-editor/issues/1367#issue-502652214),

Thanks.  I intended to report this bug this morning.

SegundoBob

**Comment by edreamleo** [comment]
Fixed at d470b8f in devel.  Notes:

- The culprit: os.path.samefile will throw IOError if the old and new files do not both exist.
  This was masked, because the caller catches IOError!
- This rev fixes a related bug in fc.saveAs.  The finally block must set c.ignoreChangedPaths to False!
