### ISSUE TITLE
Using an emoji messes up cursor position

### ISSUE THREAD

**Issue by ar-jan** [leo-editor/leo-editor#1368]
I pasted some text containing an emoji into a Leo body pane (e.g. 👓), in an `@file` tree. Afterwards the cursor position for all following characters in that node is messed up. For example you can no longer navigate the cursor after the final character of a line using arrow keys or `end`. I guess it's because visually it's one character while being counted as two bytes or something like that?

> Leo 6.0-final, master branch, build 11fa7311b7
> 2019-09-01 00:20:09 -0700
> Python 3.7.3, PyQt version 5.9.6

**Comment by edreamleo** [comment]
@ar-jan Leo uses unicode internally, so this kind of thing should not be a problem.  This may Qt problem.

**Comment by edreamleo** [comment]
@ar-jan I see some strange behavior, similar to what you describe.

This emoji is apparently a [.png image](https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/microsoft/209/eyeglasses_1f453.png).

I'm not sure what, if anything, Leo can do about this.

**Comment by ar-jan** [comment]
I originally copied the emoj from Twitter, and it does show as a black-and-white emoji in Leo. It looks like Github is transforming the html here and adding a `fallback-src` png image, but that may be Github-specific?
