### ISSUE TITLE
A clone with a subtree is sometimes displayed as a leaf

### ISSUE THREAD

**Issue by SegundoBob** [leo-editor/leo-editor#1369]
### I can't intentionally produce this bug symptom
I have seen it three or four times, and I panicked every time thinking that I had lost important information.  The first time or two I went about trying to recover the lost information before discovering that the information was still in my .leo file.

I'm reporting this problem, even though I can't reproduce it, because I think it is a very serious bug in the sense that when a user encounters it, the user will be very upset.

### All but the last observed occurrence
 All I'm sure about for all the occurrences of this symptom is that a clone that should have had a subtree was displayed as a leaf and there was no way to expand the clone to see the subtree.
### My last observed occurrence
The following is based on the last time I saw this symptom.

When I opened the .leo file, the currently selected node was the clone.  The clone should have had a subtree, but it was shown as a leaf node.  Clicking on the clone, once, twice, many times did not show the subtree.  Selecting another node and then selecting the clone, did not show the subtree.  Scrolling the clone off the screen and back on the screen did not show the subtree.

Alt+N (next clone) moved the focus to an occurrence of the node much earlier in the outline.  This occurrence was shown with its subtree!

Alt+N (next clone) moved the focus back to where the node had been shown as a leaf, but now it was correctly shown with its subtree!

### This occurred with Leo-Editor version
 ('devel', 'dc72b05e5609')  running under Ubuntu 18.04

**Comment by edreamleo** [comment]
The next time this happens, try <alt-x>redraw

**Comment by edreamleo** [comment]
qtree.drawChildren is a bit strange, presumably as an optimization.  I would rather not touch this code, if I can help it.

**Comment by edreamleo** [comment]
Rev d7319ba explicitly sets each item's DontShowIndicatorWhenChildless bit. This might help in a platform-dependent manner.

I am going to close this item.  Please reopen as necessary.
