### ISSUE TITLE
Detachable Body Editor

### ISSUE THREAD

**Issue by technatica** [leo-editor/leo-editor#137]
I quite often use a detached vr pane on my second monitor screen when I am writing a heavily formatted text in order to check my text from time to time by refreshing the vr pane.

What I would love to see would to be able to detach a body editor, leaving the tree and main body editor where it is on screen one, while using screen two for writing in. I find that as I am trying to use Leo to manage more and more information that having the tree available at all times while writing is important. I currently work like this for short work, 750-2000 words, using my word processor as the floating editor, but for longer papers it is important to keep my work in Leo until I am ready to build the document.

**Comment by edreamleo** [comment]
You can already do this with the so-called Easter-Egg menu:

1. Position the cursor between the outline and body panes.

The cursor will change, indicating that you can reposition the panes by dragging.

2. Right-click the mouse, bringing up the Easter-Egg menu.

3. From the "Open Window" submenu, select "Body"

This detaches the body pane into a separate window.

You can also play around with various layout options in the Easter-Egg menu.  There may be bugs involving restoring layouts.  In my test right now reopening the Leo file did not reopen the detached body pane, but that's a relatively minor issue.

HTH.

Edward

**Comment by technatica** [comment]
Hi Edward,

This does detach the body pane, but it doesn't allow me to create a
separate body pane. Using the Easter Egg menu again to Insert a body window
back into the main Leo window eliminates the floating pane. It would be
great to have the floating body pane and the main window body pane
available at the same time. Allowing the floating body pane to be be locked
to a node and the body pane in the main window to continue to display the
tree contents is what I was after.

Chris

**Comment by tbnorth** [comment]
On Tue, 03 Feb 2015 12:28:53 -0800
technatica <notifications@github.com> wrote:

> Hi Edward,
> 
> This does detach the body pane, but it doesn't allow me to create a
> separate body pane. Using the Easter Egg menu again to Insert a body
> window back into the main Leo window eliminates the floating pane. It
> would be great to have the floating body pane and the main window
> body pane available at the same time. Allowing the floating body pane
> to be be locked to a node and the body pane in the main window to
> continue to display the tree contents is what I was after.

Well, what your looking for Chris is a feature I've wanted to implement
for a long time, and is on my list of projects.  I'm still not sure how
hard it will be.

Having not seen the above response initially, I did just fix a niggle
in nested_splitter, it now copies the main windows stylesheet and
applies it to the newly opened window.

> On Tue, Feb 3, 2015 at 3:32 AM, Edward K. Ream
> <notifications@github.com> wrote:

[snip]

> > You can also play around with various layout options in the
> > Easter-Egg menu. There may be bugs involving restoring layouts. In
> > my test right now reopening the Leo file did not reopen the
> > detached body pane, but that's a relatively minor issue.

You have to explicitly save a layout for it to persist, but even if you
had, secondary windows aren't persisted.  So if you had saved the
layout, Leo would have restored the bodyless layout and then added
the body as a tab in the tab pane (log pane), which is what it does with
non-closeable widgets (body, tree, log) with nowhere else to go.

Cheers -Terry

**Comment by technatica** [comment]
To be clear: I would like to be able to select a node and create a detached body editor that is locked to that node while leaving the core body editor tied to the tree and embedded in the editor. It should be functionally equivalent to the primary body editor.
