### ISSUE TITLE
Controller class mentioned in tutorial but not introduced

### ISSUE THREAD

**Issue by metaperl** [leo-editor/leo-editor#1370]
In [the markup section of the tutorial](https://leoeditor.com/tutorial-basics.html#markup), we read: 

> Child nodes must define the << import >> node and the methods of the Controller class.

This leads to confusion because the text did not state anything about a `Controller` class. Presumably that is what is being built by the `@file` node but that is not stated anywhere.

**Comment by edreamleo** [comment]
Fixed at rev 0d4294e in devel.
