### ISSUE TITLE
goto-global-line doesn't work properly in @nosent files

### ISSUE THREAD

**Issue by vitalije** [leo-editor/leo-editor#138]
For quite a long time I have noticed that command goto global line (Alt+G) doesn't work properly on @nosent files. It seems that it counts non-existing sentinel lines so it positions cursor few lines before the requested. The exact difference between required line number and found one depends on size of file and number of nodes, and also grows with required line number.

You can exhibit this by looking in attached Leo file. For example Alt+g 45 should position cursor on the declaration line of function temp7(a), but it positions cursor on line 39.

https://groups.google.com/group/leo-editor/attach/63f325cf79f6b2e9/nosent-goto-line-bug.leo?part=0.1

**Comment by edreamleo** [comment]
Fixed at rev 5ff5be0.  The problem was that a bare '@' was not treated as a Leo directive.

**Comment by vitalije** [comment]
There is still some case(s) when goto-global-line doesn't work as I expect.
Here is a slightly changed Leo file that demonstrate bug. Try in this Leo file, under the '@clean test.js' node goto-global-line command with any line number.

https://groups.google.com/group/leo-editor/attach/e9f84113b2db0242/nosent-goto-line-bug.leo?part=0.1

**Comment by edreamleo** [comment]
The new code passes minimal tests.  Please reopen if any problems are found.
