### ISSUE TITLE
Create a comm bridge between VS Code and Leo

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#1390]
Delegated to Felix.

We may want to execute Leo commands (in VS Code) on Leo outlines (in the Leo bridge).

**Comment by boltex** [comment]
just a note I tought of adding here: currently, the dev branch of leointeg has a working, but limited, http server using websockets. (More to come in the current week! Stay tuned :) )

**Comment by edreamleo** [comment]
I am going to close this because leoInteg does what Félix and I both want.
