### ISSUE TITLE
Allow shutil.which('leo')

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#1397]
This would be helpful for #1384: pyzo comm bridge.

Leo doesn't have an executable file.  which('leo') might return a .bat file, but that doesn't help to compute the path to Leo's directory.

One possibility would be to use, say, a LEO_DIRECTORY environment var.

**Comment by maphew** [comment]
I believe this should work already provided:
- if using conda or pyvenv or ... the env has been activated before launching Leo
- Leo has been `pip install`ed, or user has done the work of pip and put a `leo` launcher cmd in PATH

The recent work with `leo\scripts\add-desktop-links.leox` has been about the activation part. We use **pyshortcuts** module to create the menu links, and it ([soon will be](https://github.com/newville/pyshortcuts/pull/18#issuecomment-542504602) with next release) smart enough to add the activation wrapper. (Though it occurs to me as I write this that it might only work with conda envs right now.)

**Comment by edreamleo** [comment]
@maphew Thanks for these comments.  I use a .bat file to launch Leo, and in that case there are problems.  These probably shouldn't be your problems :-)

**Comment by maphew** [comment]
it'll work with bat files too, they just need to be in PATH

**Comment by edreamleo** [comment]
@maphew I think you misunderstood the problem.  Yes, it's possible to execute .bat files using which.  However, what I want to do is to calculate the path to Leo using which.  If a .bat file is involved, Leo would have to parse the .bat file.

**Comment by maphew** [comment]
Ohhhh. I get it now! 

IMO `pip install --editable` is easier than managing env vars. Then leo.exe is in `PYTHONHOME\Scripts` and your code is still wherever you like to keep and work on it, and python can import it like any other module (via `PYTHONHOME\Lib\site-packages\leo.egg-link`).

But just like I didn't understand the purpose of finding the bat file, there's probably other things I'm missing too.
