### ISSUE TITLE
auto-justify body text

### ISSUE THREAD

**Issue by tbnorth** [leo-editor/leo-editor#14]
Leo can wrap or not wrap body text, but this is just a visual rendering relative to the body  editor window size.  It would be nice if Leo could also automatically justify (insert newlines) in text as you type.

**Comment by edreamleo** [comment]
There are several ways Leo could insert newlines.  After a specified column, or when the line would exceed the width of the body pane.  On first thought, at a specified column seems more useful.

Comments, please.

**Comment by calvertvl** [comment]
Nearly all other text editors--if they offer this feature--use the specified column method, as far as I am aware. Normally it is described as wrap or rewrap, which comes into conflict with the `@wrap`/`@nowrap` directives in Leo.

I think terminology may be the biggest issue here.

For clarity, when I refer to wrap/rewrap below I am describing the insertion of newlines, or removal and re-insertion to change the length of the lines. I think of justify as a purely visual (formatting) option (e.g. stretching character width so left and right appear to end at the same place) in the same general category as the existing `@wrap` behavior (known in some cases as word wrap).

Providing a rewrap-text command and using a specified number of columns to wrap seems to be much more flexible than only wrapping at the width of the body pane. The behavior is also consistent if the user switches between different screen resolutions that would affect maximum visible line length (e.g. laptop with external display).

In other editors, the rewrap-text command generally does the following:

- Two consecutive newlines are treated as a paragraph break.
- The operation is executed for selected text or current paragraph (I'd suggest selected text or current node for Leo).
- The implementation often retrieves number of columns (N) from clipboard, using global config as a fallback (for Leo, perhaps a new node-body directive similar to `@pagewidth`?).
- Upon execution: rewrap each paragraph to N columns (for Leo, use [Python library textwrap.TextWrapper](https://docs.python.org/3.5/library/textwrap.html) for each paragraph?)

Obviously, the above doesn't exactly work well for code, but it is ideal for documentation or other prose. To work for code, it may only be necessary to change the definition of the paragraph break, but I'm not sure...I usually use language-aware code reformatting programs in that case, and they usually offer similar max-line-length options when appropriate.

**Comment by edreamleo** [comment]
Rev 8ae11ae adds experimental support for auto indentation for programming.  The only new code is in the newPlainChar method in leoEditCommands.py. Let me know what you think.

When the new setting `@int autojustify`  is greater than zero, Leo will insert a newline before the present word if it would exceed the given column number. A newline is added only if the user is typing at the end of a line.

The code uses the auto indent feature to add indentation.

**Important**: Leo's reformat-paragraph and unformat-paragraph commands use whatever `@pagewidth` setting is in effect, so imo the only thing that is needed is to add hard newlines when programming.

I'll close this now.  Please reopen if there are problems.

**Comment by edreamleo** [comment]
I already don't like this feature.  It would take AI to know how to split lines properly.

For example, the user will want to insert comment delims when extending comments.

**Comment by tbnorth** [comment]
My guess is the OP wanted this for prose, not code.  I'd like it for prose too - my experiments weren't very successful when I tried it though (some time ago).  It should certainly be possible.

**Comment by edreamleo** [comment]
On Sun, Sep 25, 2016 at 7:44 AM, Terry Brown <notifications@github.com>
wrote:

> My guess is the OP wanted this for prose, not code. I'd like it for prose
> too - my experiments weren't very successful when I tried it though (some
> time ago). It should certainly be possible.
>
​Have you tried reformat-paragraph and unformat-paragraph?  I use them all
the time.

EKR

**Comment by tbnorth** [comment]
Yes but that's intrusive, having to hit something at the end of every para., other than return, to type fixed width text, or letting the window wrapping handle it until you're done typing, then go back and reformat all the paras.

**Comment by tbnorth** [comment]
To finish the discussion above, this actually works well for prose - I'd forgotten it was done already.  So I think it's a valuable feature.  It should probably get a toggle command though, so you can toggle it on and off, and I guess a setting to determine if it's on by default.

**Comment by tbnorth** [comment]
Done in 05df9a
