### ISSUE TITLE
Malformed leoID when editing myLeoSettings.leo renders Leo unable to launch at all

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#1402]
I somehow broke myLeoSettings.leo file. I added a setting (`@string active_path_attype = clean`), saved, used _Settings >> Reload all settings_. And then proceeded to do a few other things I've forgotten about. There were 3 open workbooks. 

At some point the Outline pane went blank, while the Body, Render and Log panes all showed normal content. Ctrl-T to put focus in Outline and then arrow keys caused the Body and Render to change content, so I could still navigate the tree even if I couldn't see it.

I closed Leo and now it won't launch, emitting this error: 
~~~
> leo-m

--global-docks: False


bad .leo file: myLeoSettings.leo
g.toUnicode: unexpected argument of type ParseError
toUnicode openLeoFile,getLeoFile,readFile,readWithElementTree


leo_excepthook Uncaught Python exception: 'NoneType' object is not iterable

NoneType: None
~~~

~~~
(leo-dev) matt@ENV-SURFACE-MHW C:\Users\mattw\code\leo-editor
> git status
On branch devel
Your branch is up to date with 'origin/devel'.

nothing to commit, working tree clean

(leo-dev) matt@ENV-SURFACE-MHW C:\Users\mattw\code\leo-editor
> git log -1
commit b8f9d28b24dfe96a6b37046b27e45ca52007b389 (HEAD -> devel, origin/devel)
Author: Edward K. Ream <edreamleo@gmail.com>
Date:   Wed Oct 16 09:11:14 2019 -0500

    Fix #1400. Replace time.clock by time.process_time.
~~~

I'm about to try edit the .leo file by hand and see if I can fix what's broken.

**Comment by maphew** [comment]
Notepad++ XML Tools plugin says: `XML Parsing error at line 21: Extra content at the end of the document`. Line 21 is `<tnodes>`. There are 212 lines.

Found the broken part, still have NO idea what could have happened though. My ID is double quoted `<t tx=""mhw".20191016213522.1"></t>` instead of `<t tx="mhw.20191016213522.1"></t>`.

Also the other workbooks I had open are broken in the same way. I probably hit save all when exiting, though I don't really remember.

~~~
...snip...
<v t="lkj.20190915154028.1"><vh>@string central-dock-widget = body</vh></v>
<v t="lkj.20190915154114.1"><vh>@bool dockable-log-tabs = True</vh></v>
<v t=""mhw".20191016213522.1"><vh></vh></v>
</v>
</vnodes>
<tnodes>
<t tx=""mhw".20191016213522.1"></t>
<t tx="lkj.20190811182459.1">myLeoSettings.leo personal settings file created Sun Aug 11 18:24:59 2019
...snip...
~~~

**Comment by maphew** [comment]
[myLeoSettings-broken.leo.txt](https://github.com/leo-editor/leo-editor/files/3737505/myLeoSettings-broken.leo.txt)

**Comment by maphew** [comment]
Reproduced! Recipe:

1. Open myLeoSettings
2. create a new node under @settings, `Ctrl-i`
3. `Ctrl-h`, delete the headline text, don't enter body text
4. Save and exit.
5. Run Leo --> can't! .leo is malformed as per above.

**Comment by maphew** [comment]
_sigh._ self-inflicted wound!

I had manually created the `.leoID.txt` using echo (https://github.com/leo-editor/leo-editor/issues/1385#issuecomment-541457061), mistakenly putting in the quotes. It's curious that I've been able to use Leo since then without apparent damage. Maybe this was the first time I created a new node since then, rather than just editing existing ones. {shrug}

Not sure if "`"` in ID breaks .leo files" still qualifies as a bug or not. Maybe there are other characters which could cause havoc.

**Comment by edreamleo** [comment]
On Thu, Oct 17, 2019 at 12:56 AM matt wilkie <notifications@github.com>
wrote:

> *sigh.* self-inflicted wound!
>
This is good news. There are two takeaways:

1. Catching all exceptions with sys.excepthook (a recent "innovation",
following pyzo) is a bad idea. The traces produced are worse than without
it.  Either way, Leo will exit.  There is no helping that.  That said, Leo
should catch all exception while reading .leo files, and do something more
reasonable if unexpected errors occur.  #1403
<https://github.com/leo-editor/leo-editor/issues/1403>.

2. Leo should make sure to clean the contents of .leoID.txt. #1404
<https://github.com/leo-editor/leo-editor/issues/1404>, and more generally,
gnx's.

I'll do both today.

Edward

**Comment by edreamleo** [comment]
I am closing this issue.  #1403 and #1404 should suffice.
