### ISSUE TITLE
ENB: About comm bridges

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#1409]
This ENB entry summarizes my present thinking about all [comm-bridge](https://github.com/leo-editor/leo-editor/issues?q=is%3Aissue+label%3Acomm-bridge+is%3Aopen) projects.  An **external host** is an external IDE or other tool that uses a comm bridge to add Leonine features.

**Reasons *not* to do comm bridges**

- I could spend my time improving Leo, using other IDE's and tools as inspiration.
- #906 (Dubious major projects) gives further reasons.

**Reasons to *do* comm bridges**

- To demonstrate to the world Leo's capabilities.
- To bring the capabilities of external hosts into Leo.

Imo, the reasons to do comm outweigh the reasons not to do so.

**Essential features**

 It's not enough to *look* like Leo, the comm-bridge must *act* like Leo. The bridge must provide Leo's **essential features** into external hosts. These include:

- The ability to read and write .leo files from the host.
- Outline commands.
- Clone-oriented commands.
- Importer commands.
- Support for Leonine settings.

**Summary**

- ~~I plan a comm bridge between Leo and pyzo.~~ 
- I welcome the [leointeg](https://github.com/boltex/leointeg/tree/master) project, and would welcome help on the other comm-bridge projects.

**Comment by boltex** [comment]
(pre-announcement) I Updated master version last night before bed but am going to retest everything today after work before announcing/requesting another round of testing from anybody who'd like to try on google group forum.

**Comment by edreamleo** [comment]
@boltex Thanks for this work!

**Comment by edreamleo** [comment]
I am going to close this issue. leoInteg has done all the work!
