### ISSUE TITLE
Leo pyqt requirement conflicts with Anaconda Spyder

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#1423]
Should we pin pyqt version to be >=5.12 and <5.13 to allow Leo to be installed side by side with Spyder?

See https://groups.google.com/d/topic/leo-editor/KDCeOW-Mnzw/discussion

**Comment by edreamleo** [comment]
On Mon, Oct 28, 2019 at 12:21 AM matt wilkie <notifications@github.com>
wrote:

> Should we pin pyqt version to be >=5.12 and <5.13 to allow Leo to be
> installed side by side with Spyder?
>
I'll leave this up to you.  As I said, I know of no dependencies on any
particular qt 5.x version, except the one you cite.

Edward
