### ISSUE TITLE
Limiters don't work in replace-all

### ISSUE THREAD

**Issue by technatica** [leo-editor/leo-editor#1428]
1. Open Leo.
2. Alt-x, replace-all.
3. Enter search string, TAB, enter replacement string, hit enter.

Leo will find and replace all instances of the search string with the replacement string. All good so far.

But what if I only want to search/replace in a particular sub outline? Or in this node only?

Selecting these options in the find pane does nothing. Leo still finds and replaces ALL instances of the search string in the entire outline. Selecting these options using commands also has no effect.

Tested using both minibuffer replace-all and the find pane string boxes.

Leo 6.1-b1-devel, devel branch, build b6a76cb9b2
2019-10-27 06:15:34 -0500
Python 3.6.8, PyQt version 5.13.1
linux

**Comment by technatica** [comment]
That works great.

Except it was committed to the beautify2 branch.

Thanks for this. It really caught me off guard the first time. I was changing a handful of instances in a node and it changed the whole outline. Then I, brilliant user, saved t and went on with my day.

A week or so later I noticed that the rest of the file was munged and started to figure out what went wrong..

**Comment by edreamleo** [comment]
@technatica Oops! Good catch. Fixed at dbc3685 in devel. Actually, fstrings contained the fix.

I'm kinda glad this happened. You encouraged me to merge devel into both fstrings and beautify2 branches.  There was a merge conflict which was easy to fix because I wrote the new code yesterday.
