### ISSUE TITLE
beautify and blacken handle triple quoted `.format()` a bit strangely

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#1429]
`beautify-*` adds extended whitespace, 9 spaces, after a triple quoted string that uses format(). The result still works so it's not 'wrong', but looks a bit weird.
`blacken-*` looks more 'correct' but less appealing (IMO).

I don't know that anything need be done about this, so feel free to close, but I figured it should be noted, and now it is.

BEFORE
~~~
def get_semver(tag):
    """Return 'Semantic Version' from tag string"""
    try:
        import semantic_version
        version = str(semantic_version.Version.coerce(tag, partial=True))
            # tuple of major, minor, build, pre-release, patch
            # 5.6b2 --> 5.6-b2
    except(ImportError, ValueError) as err:
        print('\n', err)
        print('''*** Failed to parse Semantic Version from git tag '{0}'.
        Expecting tag name like '5.7b2', 'leo-4.9.12', 'v4.3' for releases.
        This version can't be uploaded to PyPi.org.'''.format(tag))
        version = tag
    return version
~~~

AFTER `beautify-node` (snipped)
~~~
        print('''*** Failed to parse Semantic Version from git tag '{0}'.
        Expecting tag name like '5.7b2', 'leo-4.9.12', 'v4.3' for releases.
        This version can't be uploaded to PyPi.org.'''         .format(tag))
~~~

AFTER `blacken-node` (snipped)
~~~
        print(
            '''*** Failed to parse Semantic Version from git tag '{0}'.
        Expecting tag name like '5.7b2', 'leo-4.9.12', 'v4.3' for releases.
        This version can't be uploaded to PyPi.org.'''.format(
                tag
            )
        )
~~~

**Comment by edreamleo** [comment]
@maphew Thanks for this.  I am in the midst of a thorough review of token handling, and this might affect this issue.  It's way too late to make any changes for Leo 6.1.  We'll look into this for 6.2.

**Comment by edreamleo** [comment]
I don't see this in the latest code. Rev 2274da2 adds a unit test, TestOrange.test_bug_1429, for this.

Leo no longer has black* commands, but some unit tests for leoAst.py do use black. The new unit test merely assert that Leo's beautify code leaves the test code unchanged when the split/join logic is suppressed.
