### ISSUE TITLE
Flash matching brackets don't

### ISSUE THREAD

**Issue by largo84** [leo-editor/leo-editor#1434]
@bool flash-matching-brackets=true

All other related settings are default values. I don't recall ever seeing brackets flash. Not even sure I know what to expect. Should they flash whenever I type inside matching brackets?

`Leo 6.1-b1-devel, devel branch, build c552e0abff`
`2019-11-08 06:37:27 -0600`
`Python 3.7.3, PyQt version 5.9.6`
`Windows 10 AMD64 (build 10.0.18362) SP0`

**Comment by edreamleo** [comment]
@largo84 This is unlikely to be a Leo problem directly. This is likely either a user error or a Qt problem.

**Comment by largo84** [comment]
1. If user error (me), then what could I possibly be doing wrong? Type a left bracket (e.g. `[`), then Leo automatically adds closing bracket (`]`) with cursor between. Then start typing... No apparent visual change to the brackets. I have experimented w/ different values of timing. Next will experiment w/ color changes. Wonder if I'm the only one who doesn't see it?
2. Not sure it can be a Qt problem as this has never worked for me over a multitude of Qt versions.
3. Could it possibly be theme related? I don't see how, though.

**Comment by tbpassin** [comment]
I have never had Leo adding closing brackets (I don't even know what setting causes that).  Through many versions of Leo, I've always seen the same behavior:  type some kind of opening bracket;  then when you type a closing bracket, Leo flashes the corresponding opening bracket.  This helps you make sure that you have the right number of closing brackets.  By "bracket", I mean any of the usual ones: ), ], }.  The flashing seems to be done by briefly highlighting the bracket several times.

So maybe when you have Leo automatically inserting a closing bracket, there is no need to flash the opening one.  The flashing is presumably triggered on a keystroke, and you never typed the closing bracket so there was no keystroke to trigger the flash.

**Comment by largo84** [comment]
The setting to autocomplete brackets is `@bool autocomplete-brackets`  and the default is `= False`. 

Following your suggestion, I reverted my setting to false and now I see the flashing brackets.

I suppose this is not actually a bug, but perhaps an enhancement request to somehow show the corresponding bracket even if autocomplete is on. In deeply nested code, it would be nice to see where the 'sister' bracket is when the cursor is adjacent to a bracket. I believe other editors do that, but am not sure.

Thanks for the tip, though.

**Comment by tbpassin** [comment]
The Windows editor I use a lot, Editplus, jumps between matching brackets when you press <CNTRL-]>.  I like this feature, which is just about what you are asking for.  There is actually is a Leo command for this - match-brackets - and it is already bound to <CNTRL]> (at least on my system - if it isn't on yours you could add that binding).

Thanks for the autocomplete setting.  I can never decide if I like automatic bracket completion or not.    Right now I'm in my "don't like it" phase, but that could change.

**Comment by tbpassin** [comment]
I just checked my myLeoSettings.leo file, and sure enough, I had added a line to the @shortcut node for the binding:
```
match-brackets = Ctrl+]
```

**Comment by largo84** [comment]
That's a great idea and I will use that. However, what I'm looking for is more of debugging tool to help find matching brackets, not to create them when writing.

**Comment by tbpassin** [comment]
Well actually, I think that the match-brackets command will do what you want.  If you place the cursor in the code between two brackets and activate the command, it will find both of the closest matching brackets and highlight the code between them.  If you keep repeating the command, it will expand the highlighted region until it has consumed all the outer matching brackets.  If one of the outer ones is missing, say a trailing "]", it won't be included in the highlighted region, and so it stands out clearly.  I haven't tested this yet across line breaks, but at least on a single line, it works nicely.

**Comment by largo84** [comment]
Just tested this in a multi-line environment and it looks like what I need. Thanks for the suggestion!

**Comment by largo84** [comment]
Closing issue as I think this solves my original problem.
