### ISSUE TITLE
mod_http plugin error

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#1435]
mod_http plugin enabled, open http://localhost:8130/ in a browser. The page does not load.

Console output:
```
error: uncaptured python exception, closing channel <leo.plugins.mod_http.RequestHandler connected 127.0.0.1:60397 at 0x22c87d4de80> (<class 'AttributeError'>:module 'cgi' has no attribute 'parse_qs' [N:\git\leo-editor\leo\plugins\mod_http.py|a_read|1181] [N:\git\leo-editor\leo\plugins\mod_http.py|handle_read_event|1108] [C:\Users\lewis\AppData\Local\Programs\Python\Python38\lib\asyncore.py|handle_read_event|420] [C:\Users\lewis\AppData\Local\Programs\Python\Python38\lib\asynchat.py|handle_read|171] [N:\git\leo-editor\leo\plugins\mod_http.py|found_terminator|1138] [N:\git\leo-editor\leo\plugins\mod_http.py|handle_request_line|1121])

_Leo Log Window
Leo 6.2-b1-devel, devel branch, build a52b6d87b5
2019-11-08 12:46:02 -0600
Python 3.8.0, PyQt version 5.13.2
Windows 10 AMD64 (build 10.0.18362) SP0_
```

**Comment by technatica** [comment]
Works here on Linux.

Chris

Leo 6.2-b1-devel, devel branch, build a52b6d87b5

2019-11-08 12:46:02 -0600

Python 3.6.8, PyQt version 5.12.3

linux

**Comment by edreamleo** [comment]
@LewisNeal Your traceback shows that you are using Python 3.8.  Python 3.8 [removes parse_qs, parse_qsl, and escape from the cgi module.](https://docs.python.org/3/whatsnew/3.8.html#api-and-feature-removals).

They have been deprecated since Python 3.2. They should be imported from the urllib.parse and html modules instead.

**Comment by LewisNeal** [comment]
Edward, Thanks for setting me the challenge :)
I updated my local mod_http.py and the plugin is working again.
Since Leo requires 3.6 or later I would not expect my changes to break the plugin for others..... Ha.

**Comment by edreamleo** [comment]
@LewisNeal Not sure I know what you mean.  Did you change mod_http so it works with 3.8?  If so, please create a new branch for the changes.  I'll merge it into devel.  Or just issue a PR.

**Comment by LewisNeal** [comment]
Yes I changed mod_http so it works with 3.8 and I'm reading how to create a new branch/issue a PR.

**Comment by edreamleo** [comment]
@LewisNeal Excellent.  Thanks for this.

**Comment by LewisNeal** [comment]
This is the first time I have tackled posting a PR. I'm working through this guide:
https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github
which recommends creating a new branch off master. 
What is preferred for Leo - should I create a new branch off master or devel ?

**Comment by edreamleo** [comment]
On Tue, Nov 12, 2019 at 4:44 AM LewisNeal <notifications@github.com> wrote:

> What is preferred for Leo - should I create a new branch off master or
> devel ?
>
All branches should be based on devel.  Creating a branch from master would
be a serious mistake.

Edward

**Comment by LewisNeal** [comment]
I did create the branch from master so I will create another PR using devel.
Can you confirm I should delete the closed PR.

**Comment by edreamleo** [comment]
Can you really delete PR's?  Closing them should suffice.

**Comment by LewisNeal** [comment]
My typo, I meant the branch mod_http_py38.

**Comment by LewisNeal** [comment]
@technatica has the plugin update caused any issue on your linux platform?

**Comment by technatica** [comment]
It works fine.

Chris

**Comment by edreamleo** [comment]
@LewisNeal Thanks for this work!
