### ISSUE TITLE
compound @path expression returns trailing characters

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#1443]
A node with `@path g.os_path_join(g.app.loadDir, '../../tools/webroot')` followed by `@clean somefile.ext` yields a wrong path.
~~~
[ ] organizer node
    @path g.os_path_join(g.app.loadDir, '../../tools/webroot')
     [ ] @clean leo_to_html.xsl
~~~

I get:
`not found: C:/users/mattw/code/leo-editor/leo/core/tools/webroot')/leo_to_html.xsl`
Note the `')` in middle.

Expected:
`C:/users/mattw/code/leo-editor/leo/core/../../tools/webroot/leo_to_html.xsl`

Other expressions I tried that also failed with similar results:

    import os
    @path os.path.join(g.app.loadDir, '../../tools/webroot')

and 

    @path g.app.loadDir + '../../tools/webroot'

Leo Log Window
Leo 6.2-b1-devel, clean-up-root branch, build 9ca48970cb
2019-11-11 22:00:08 -0800
Python 3.6.2, PyQt version 5.12.3
Windows 10 AMD64 (build 10.0.17134) SP0

**Comment by maphew** [comment]
This is the syntax which finally worked, in that the `@clean` file loads properly:

     @path g.app.loadDir + /../../../tools/webroot

BUT, it requires an extra `../` which is incorrect.

Print the above to log panel, then copy paste that into cmd shell with cd:

    g.es_print(g.app.loadDir + '/../../../tools/webroot')

    > cd C:/users/mattw/code/leo-editor/leo/core/../../../tools/webroot
    The system cannot find the path specified.

Try again by manually removing `../`:

    > cd C:/users/mattw/code/leo-editor/leo/core/../../tools/webroot`
    :: works ::

**Comment by edreamleo** [comment]
The proper way is to use {{ and }} to specify the expression:

    @path {{g.os_path_join(g.app.loadDir, '../../tools/webroot')}}

It works for me. Does it work for you?

**Comment by edreamleo** [comment]
I am going to close this issue. Please reopen if necessary.

**Comment by maphew** [comment]
Thank you, yes using `{{...}}` works for me.  Does this syntax have a name?

For benefit of future searchers:
https://leoeditor.com/directives.html#path-expressions

**Comment by edreamleo** [comment]
@maphew I think "path expression" can be used for this syntax. It's discussed in the "path expression" link you cite above.
