### ISSUE TITLE
Leo 6.1 Spews Out Many Similar Error messages During Startup

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#1444]
OS: Windows 10
Python 3.7
Installation via either pip or git clone.

My installation of Leo 6.1 emits a stream of many error messages similar to the following during startup:

```
hook failed: after-create-leo-frame2, <bound method FreeLayoutController.loadLayouts of <leo.plugins.free_layout.FreeLayoutController object at 0x00000248F6C65548>>, <no module>
Traceback (most recent call last):

  File "C:\Documents and Settings\tom\leo-editor\leo\core\leoPlugins.py", line 324, in callTagHandler
    result = handler(tag, keywords)

  File "C:\Documents and Settings\tom\leo-editor\leo\plugins\free_layout.py", line 213, in loadLayouts
    d = g.app.db.get('ns_layouts') or {}

  File "C:\Documents and Settings\tom\leo-editor\leo\core\leoCache.py", line 607, in get
    val = self[key]

  File "C:\Documents and Settings\tom\leo-editor\leo\core\leoCache.py", line 522, in __getitem__
    obj = self.loader(row[0])

  File "C:\Documents and Settings\tom\leo-editor\leo\core\leoCache.py", line 483, in loadz
    val = pickle.loads(zlib.decompress(data))

ModuleNotFoundError: No module named 'PyQt4'
```

These are not coming from plugins, because I removed them and got the same results.  They happen when I load outlines. I don't know if they happen for other events.  Since there isn't a pyqt4 package for Python 3.x, this can't be cured by simply installing one.

I uninstalled leo and reinstalled it, both using pip and git clone, but got the same behavior.

On the plus side, Leo 6.1 seems to be working normally except for these messages.

**Comment by tbpassin** [comment]
I finally solved this by by deleting Leo's database.  This also cleared up a few other anomalies, like a missing main menu bar for a fresh installation of Leo.

**Comment by edreamleo** [comment]
@tbpassin Thanks for this report.

I am going to close this issue. There were several significant changes in Leo's code base moving from Leo 6.0 to 6.1.  Each might have contributed to your woes in an installation-dependent way.
