### ISSUE TITLE
Leo 6.1 Crashes After Right-Clicking On Panel Divider In --no-dock Mode

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#1445]
OS: Windows 10 64-bit
Python: 3.7

When I start Leo 6.1 with --no-dock, and then right-click on the border between the right and left panels, Leo usually crashes without emitting an error message to the console.  It just goes away quietly.  This has happened every time I tried it.  I was intending to arrange the panels as I have done in earlier versions of Leo (i.e., "body-right" layout), but this behavior makes that impossible.

This has occurred for both pip and git clone installations.

**Comment by edreamleo** [comment]
On Tue, Nov 19, 2019 at 9:28 PM tbpassin <notifications@github.com> wrote:

> OS: Windows 10 64-bit
> Python: 3.7
>
> When I start Leo 6.1 with --no-dock, and then right-click on the border
> between the right and left panels, Leo usually crashes without emitting an
> error message to the console. It just goes away quietly.
>
Thanks for this testing.  It looks like a 6.1.1 release will be coming soon.

Edward

**Comment by edreamleo** [comment]
@tbpassin I don't see this either on Windows 10 nor on Ubuntu Linux.

A careful review of the git logs shows no significant change in the last year or so to leo/plugins/nested_splitter.py, which presumably contains the code in question.

**Comment by tbpassin** [comment]
I may have found the problem.  Here's the stack trace:
```
Traceback (most recent call last):
  File "C:\Users\tom\leo-editor\leo\plugins\nested_splitter.py", line 356, in splitter_menu
    load_items(menu, provider.ns_context())
  File "C:\Users\tom\leo-editor\leo\plugins\free_layout.py", line 255, in ns_context
    d = g.app.db.get('ns_layouts', {})
  File "C:\Users\tom\leo-editor\leo\core\leoCache.py", line 607, in get
    val = self[key]
  File "C:\Users\tom\leo-editor\leo\core\leoCache.py", line 522, in __getitem__
    obj = self.loader(row[0])
  File "C:\Users\tom\leo-editor\leo\core\leoCache.py", line 483, in loadz
    val = pickle.loads(zlib.decompress(data))
ModuleNotFoundError: No module named 'PyQt4'
```

Looking at the nearest precipitating line, line 483:
```
    def loadz(data):
        if data:
            try:
                val = pickle.loads(zlib.decompress(data))
            except (ValueError, TypeError):
                g.es("Unpickling error - Python 3 data accessed from Python 2?")
                return None
            return val
        return None
```
I sometimes run Leo 5.9 using Python 2.7 as well as as well as 6.1 using Python 3.7..  Could these pickles be left over from running 5.9?  If this were the case, it would also explain https://github.com/leo-editor/leo-editor/issues/1444

Is there a way to get Leo to dump the pickles and start without them?  Otherwise, are they all in some specific directory?  I could manually delete them.

**Comment by tbpassin** [comment]
I found the problem (aside from the obsolete cache values):  It's an unhandled exception for an undeclared variable.  Around line 484 in leoCache.py, the actual exception isn't handled:
```
    def loadz(data):
        if data:
            try:
                val = pickle.loads(zlib.decompress(data))
            except (ValueError, TypeError):
                g.es("Unpickling error - Python 3 data accessed from Python 2?")
                return None
            return val
        return None
```
The exception that isn't getting handled is
```
UnboundLocalError: local variable 'val' referenced before assignment
```
If we initialize *val* before use, the crash doesn't happen, and the split menu appears:
```
        if data:
            val = None
            try:
                val = pickle.loads(zlib.decompress(data))
            # .....
```
But we're not home free yet, because when I try to save a new layout, we crash because *None* doesn't have the method the code uses.

**Comment by edreamleo** [comment]
@tbpassin Deleting everything inside the ~/.leo/db should work.  Note that Leo will tell you where it thinks ~ is in the log pane.

Thanks for this sleuthing. It's helpful. "Forcing" this error by returning None from loadz should help me make this code less brittle.

**Comment by tbpassin** [comment]
I found the db directory and renamed it.  Now the crash doesn't happen when I try to save the pane layout.  That's good.  It seems that there is a residual robustness problem, as you mention.  If the pickling/unpickling doesn't work because the wrong pickle format is in play, the code doesn't seem to be able to adjust to that.  Maybe there should something analogous to the different extensions that Python 3 now gives to .pyc files for different versions of Python.

As long as you are thinking about *loadz*, I suggest a small restructuring to make the code a bit easier to read:

```
    def loadz(data):
        if not data:         # Return right away
           return None
        val = None
        try:
            val = pickle.loads(zlib.decompress(data))
        except (ValueError, TypeError):
            # .....
```
Also, don't forget there is another code block that is very similar in the *PickleShareDB* class.

**Comment by edreamleo** [comment]
@tbpassin Glad to hear it. I'll leave the 6.1.1 milestone for now, but there doesn't seem to be a need for an actual bug-fix release.
