### ISSUE TITLE
Leo Does Not Recognize Numeric Keypad Keystrokes in <ALT-G> Go To Line Number

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#1448]
Operating System: Windows 10
Leo Versions: 5.9, 6.1 (maybe more, but I didn't try to check).

I just noticed that when I activate Go To Line Number (with <ALT-G>) Leo does not see any keystrokes from the numeric keypad.  I tried it with both settings of the NUMLOCK key, and neither way worked.

In a body node, these keystrokes are recognized properly.

**Investigation**

Alt-x handles these keys; Alt-g does not. k.handleUnboundKeys contains special-case code for numpad keys related to #868.

**The Fix**

Previously, k.handleUnboundKeys contained special-case code for numpad keys related to #868. Now, k.handleUnboundKeys contains yet another special case for #1448. A subtle side effect is that key bindings to numpad keys will have no effect when getting arguments. Imo, this is reasonable.

**Comment by edreamleo** [comment]
@tbpassin Thanks for this report.  My laptop does not have a numeric keypad, so work on this issue must wait until I get back home.

**Comment by tbpassin** [comment]
There might be something more going on.  On my new computer, copy/paste of nodes using cntl-shift-c/v doesn't work either.  It does on my old laptop.  I have a wireless Logitek keyboard on the new machine.  I wonder if there is something slightly different about how it reports those combination keystrokes.  Maybe the way that QT listens for them has a bug, probably about the shift state.  I don't think I have  a similar keystroke combo that I use outside Leo to try it out.

I don't really want to buy another keyboard just to try this out, though.  I did find out that QT5.5 had a similar issue, but they apparently fixed that.

**Comment by edreamleo** [comment]
Fixed at 2c610ac in devel.
