### ISSUE TITLE
Problems creating non-existent directories

### ISSUE THREAD

**Issue by level323** [leo-editor/leo-editor#1450]
**EKR**: I see the problems reported here.  There are subtleties involved, which can only be resolved at the code level.  Describing various scenarios won't help.  For that reason I am hiding various comments. 

Leo version 6.1, Debian 10.2 (Buster), amd64 architecture.

Attempts to save the leo file successfully generates file-in-base-dir, but fails to generate file-in-subdir, throwing an error. 

```
Traceback (most recent call last):

  File ".../leo/core/leoGlobals.py", line 293, in new_cmd_wrapper
    func(self, event=event)

  File ".../leo/core/leoFileCommands.py", line 1827, in writeMissingAtFileNodes
    c.atFileCommands.writeMissing(c.p)

  File ".../leo/core/leoAtFile.py", line 1327, in writeMissing
    at.default_directory = c.expand_path_expression(at.default_directory) # #1341.
AttributeError: 'AtFile' object has no attribute 'default_directory'
```

**Test file**

```
+ @settings
  - @bool create_nonexistent_directories = True
+ Files
  - @nosent file-in-base-dir
  + @path testsubdir
    - @nosent file-in-subdir
```

**Comment by level323** [comment]
I just want to add that I've been able to work around these issues for the time being by creating my own Leo script button which is summarised by the following pseudocode (for brevity):

```
For each node in the subtree that is a file node:
  Determine the output path
  Create the output path if it doesn't already exist
  Mark the node as dirty

Execute  writeDirtyAtFileNodes()
```

So I can keep working on my project for the time being while this issue gets squashed.

Please let me know if there is any more info you need.

**Comment by edreamleo** [comment]
What is the value of `@bool create-nonexistent-directories`? Does setting this to True help?

**Comment by level323** [comment]
`@bool create-nonexistent-directories` is already set to `True` in my leo file. Based on your question I'm guessing you may have overlooked the example leo outline I proposed in my original issue report? I believe you can use that example to replicate the issue(s) errors I reported there. That example also includes a settings node with `@bool create-nonexistent-directories = True`

**Comment by edreamleo** [comment]
@level323 Thanks for the clarification.

**Comment by tbpassin** [comment]
I can confirm this, and with a few extra wrinkles.  I tried it with the @path subdir nested under the @file node, and then hoisted to be a sibling of the first @path node.  Somewhere along the way, after multiple attempts to save these files, I found that Leo could no longer import myLeoSettings.leo.  It failed with errors that were strange to me and that I didn't capture.  Closing and re-starting leo restored the ability to load the .leo file.  I haven't been able to reproduce this last behavior, though.

When I manually created the nested subdir, then Leo saved its subdir file, but not until I had added text before saving - before I added the text, Leo claimed that the file had been saved, but it had not been.

**Comment by edreamleo** [comment]
**EKR: Additional data from the first report**

Weirdly, if I manually create testsubdir and try File | Read/Write Files | Write missing @<file> nodes again (*without* changing the body of the file-in-subdir node), file-in-subdir is still NOT written!!! As an aside to my issue submission, that behaviour strikes me as incorrect - it seems that leo's internal state tracking has incorrectly assumed file-in-subdir has already been correctly generated and therefore it isn't even bothering to attempt a re-write.

If I alter the body of file-in-subdir (after having manually created the directory testsubdir) then save the leo file, file-in-subdir is correctly written.

As one last diagnostic test, if I manually delete testsubdir then attempt to save the leo file, I get the following error:

```
Traceback (most recent call last):

  File "/usr/local/lib/leo/latest/leo-editor/leo/core/leoGlobals.py", line 4152, in writeFile
    with open(fileName, 'wb') as f:

FileNotFoundError: [Errno 2] No such file or directory: '/home/jwclark/Documents/Downloads/testsubdir/file-in-subdir'

finished
```

I also get a popup dialog warning me that there were errors encountered while trying to write the file.

**Comment by level323** [comment]
@edreamleo I just realised that this fix is not in the master branch yet. I have the opportunity to test it now but I'm not sure what commit I should pull down and run. Not sure if this commit is likely to be stable (or at least usable) because it appears to be just one small part of multiple big changes under the hood. If you want me to test it on my leo file that was previously encountering this error, please advise what commit I should pull down and try. Cheers!

**Comment by edreamleo** [comment]
@level323 It should be in devel at rev 02bdf41, as shown above.

**Comment by level323** [comment]
Thanks @edreamleo 
I tested that commit and it appears to fix the bug.
Thanks again.

**Comment by edreamleo** [comment]
On Wed, Feb 5, 2020 at 3:15 AM level323 <notifications@github.com> wrote:

> Thanks @edreamleo <https://github.com/edreamleo>
>
You're welcome.

> I tested that commit and it appears to fix the bug.
>
Thanks for the confirmation.

Edward
