### ISSUE TITLE
Installing Leo with git instructions do not mention dependencies

### ISSUE THREAD

**Issue by metaperl** [leo-editor/leo-editor#1452]
The [Installing Leo with git instructions](https://leoeditor.com/installing.html#installing-leo-with-git) state:

> First, you need to get git from http://git-scm.com/.
> Get Leo from GitHub by doing:
> And that’s it! You can run launchLeo.py directly. 

However on Windows 10 when I then type `python launchLeo.py` I get the error message:  "Can not import Qt"

Therefore, these instructions should state that

`pip install -r requirements.txt` is also required before  `python launchLeo.py` will work.

**Comment by maphew** [comment]
There may be some pip knock-on effects, as `requirements.txt` is older than current release. Go ahead and make the doc change and close the issue at your pleasure though Edward.  I added pip label to keep the issue in my view.

**Comment by maphew** [comment]
Docs fixed in 0f44a02cf47f020d8ac9a55f20569bb0126cda9b. Most significant change:

> 3. Install dependencies and create leo script launcher::
> 
>         pip install --editable path/to/leo-editor
>         
> And that's it! You can run leo with `PYTHONHOME/Scripts/leo` or `python leo-editor/launchLeo.py`. When you want to refresh the code with latest modifications from GitHub, 'run git pull'.
> 

Note: @edreamleo there were two almost identical text blocks which I converted into a clone. A consequence of this is that the one in FAQ is no longer a phrased as a question. Not sure if this was a good idea.
