### ISSUE TITLE
Remove 'python -Wd' warnings

### ISSUE THREAD

**Issue by btheado** [leo-editor/leo-editor#1454]
Per [the python docs](https://docs.python.org/2/library/warnings.html#updating-code-for-new-versions-of-python), with Python 3.6 or 3.7, the following generates lots of warnings:

`python -Wd launchLeo.py leo\test\unitTest.leo`

- [x] The imp module is deprecated. Replace imp with importlib.
  - [x] Changed imp.reload to importlib.reload in unitTest.leo.
  - [x] Replaced g.import* by g.import_module.
  - [x] Rewrote imports in cursesGui2.py so they work with python 3.
- [x] DeprecationWarning: invalid escape sequence \S
    - Removed all `pylint:disable=anomalous-backslash-in-string`, using raw strings instead.
- [x] ResourceWarnings when opening unitTest.leo.

**Warnings from library modules**

These are not Leo's responsibility:

- docutils\io.py opens files in 'rU' mode.
- nbconvert\exporters\exporter_locator.py:
    DeprecationWarning:  .exporter_locator` is deprecated  in favor of `nbconvert.exporters.base` .
- site-packages\win32\lib\pywintypes.py:
   DeprecationWarning: the imp module is deprecated.

**Comment by edreamleo** [comment]
@btheado Thanks for this.  I've updated #1446 as well.

**Comment by edreamleo** [comment]
All work is complete.

**Comment by btheado** [comment]
Thanks. I'm no longer seeing any warnings from leo code.

**Comment by edreamleo** [comment]
@btheado You're welcome.  The -Wd warnings were valuable.
