### ISSUE TITLE
Show math symbols in Viewrendered

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#1455]
As of Leo 5.9, the viewrendered plugin rendered math symbols in @rst nodes via mathjax.  Now, in Leo 6.1/Windows 10/Python 3.8, it doesn't - only the RST is displayed.  This is an important feature for me, so I would really like it to work as it used to.  If this could work for @md nodes, too, so much the better.

See also #1810.

**Comment by tbpassin** [comment]
I've learned how to fix this.  Maybe EKR knows a better way.  The problem is that the rendering is not being displayed by a QTextBrowser, which isn't able to run the MathJax scripts.  So:

1. Use a _QWebEngineView_ for @rst nodes.  EKR sets up the imports so that would be called a QWebView, but it's really a _QWebEngineView_.

2. Save the HTML for the rendering to a temporary file, and load that file:/// URL into the QWebEngineView using _w.load(QtCore.QUrl('file:///' + pathname))_.  (using _setHtml()_  instead, sends the rendering as a _data:_ URL, and that won't work).

Also, I'm not sure that the _math_output_ setting is actually getting sent to the RsT processor.  That needs to be checked.  I have it working in my modified code, but I've made a lot more changes - see also my post at

https://groups.google.com/forum/#!topic/leo-editor/_HY9IbzXd8g

**Comment by edreamleo** [comment]
On Fri, Dec 27, 2019 at 7:05 PM tbpassin <notifications@github.com> wrote:

> I've learned how to fix this. Maybe EKR knows a better way.
>
Not likely :-)

> QTextBrowser [can't] run the MathJax scripts. So:
>
>    1.
>
>    Use a *QWebEngineView* for @rst <https://github.com/rst> nodes...
>    2.
>
>    Save the HTML for the rendering to a temporary file...
>
> Excellent.  If possible, please get symbols from leoQt.py. Whatever its
faults, it's the recommended way. Otherwise, use whatever imports you like.

Edward

**Comment by tbpassin** [comment]
I did in fact use the import from leoQt.  

I'm not sure what to do about getting this working in the _viewrendered_ plugin.  This change is just one of the changes I've been making to my new _viewrendered3_.  I could pull this part out and retrofit to _viewrendered_.  If you'd like me to do that, I'll set up to do a pull request.

**Comment by edreamleo** [comment]
@tbpassin Please leave VR alone for now. Do whatever you like in VR2. Later we can think about merging VR and VR2.
