### ISSUE TITLE
doc updates: couple of outdated myLeoSettings.leo instructions

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#1456]
1. https://leoeditor.com/tutorial-basics.html#configuring-leo should say using _Settings >> Open myLeoSettings_ will create the file if it doesn't exist.

2. https://leoeditor.com/customizing.html#configuration-directories could say that Leo's log window reports HOME being used.

From: https://groups.google.com/d/topic/leo-editor/ikVRKibC1Ws/discussion

**Comment by edreamleo** [comment]
@maphew Thanks for creating this item.
