### ISSUE TITLE
Recursive import script may add extra declaration lines

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#146]
A serious problem, which does not seem to be caught by the perfect import logic.  I discovered this problem when git reported changes. For example::

    c.recursiveImport(
        dir_ = r'<path to mypy>/mypy',
        kind = '@clean',
        one_file = False,
        safe_at_file = False,
        theTypes = ['.py',],
    )

It's not clear whether importing to @clean nodes is part of the problem.

**Comment by edreamleo** [comment]
This is a release blocker.  A few days ago I spent several happy hours importing files, and I am starting to think that perhaps there is an edge case relating to the update algorithm and section references.  Whatever the cause, we can not let Leo's import/@clean logic duplicate lines!

**Comment by edreamleo** [comment]
It appears that all problems were due to bug #140.  I have just carefully imported all files of mypy into @clean nodes.  Aside from inserted/deleted blank lines, all files round trip perfectly.

A few files could not be written due to bogus section references such as <<|>>, but that has nothing to do with this bug, and besides, Leo did not overwrite the files.

**Comment by clean** [comment]
Stop sending these emails Github!

Regards,

Adriel Kloppenburg
022 603 3595
http://adriel.co.nz
http://500px.com/HDPhotos

**Comment by edreamleo** [comment]
@clean It is up to you to manage the notifications.  Look to the left of this page, and click unsubscribe.
