### ISSUE TITLE
Retire running unit tests externally?

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#1463]
Not sure this is desirable.  However, I never run external unit tests.

Now that running unit tests locally uses a null gui, running unit tests externally is no longer significantly faster than running tests locally.

**Comment by maphew** [comment]
Travis continual integration tests?

**Comment by edreamleo** [comment]
Vitalije suggests this would be a bad idea.

**Comment by edreamleo** [comment]
This issue became moot when Leo started using traditional unit tests.
