### ISSUE TITLE
LeoApp fails to load if running python 3.8.1

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#1479]
Running python 3.8.1 LeoApp fails to load with command:
_launchleo.py --gui=browser_

The problem is not due to Leo code.
My system:
_Leo 6.2-b1-devel, devel branch, build b51bcaa8b5
Python 3.8.1, PyQt version 5.14.0
Windows 10 AMD64 (build 10.0.18362) SP0_

Using a basic example, I reported on the Flexx site - see issue [#619](https://github.com/flexxui/flexx/issues/619)
Almar advised a fix and I have updated leoflexx.py as suggested. Let me know you if you want me to issue a PR.

**EKR**: re [#619](https://github.com/flexxui/flexx/issues/619), Almar is now taking a wait and see approach. I am going to schedule this for Leo 6.3.

**Comment by edreamleo** [comment]
@LewisNeal Thanks for this, Lewis. Please do create a PR.

Edward

**Comment by LewisNeal** [comment]
Almar has updated and closed Flexx issue [#619](https://github.com/flexxui/flexx/issues/619).
The suggested fix to leoflexx.py is no longer required.

**Comment by edreamleo** [comment]
On Mon, Sep 7, 2020 at 8:36 PM LewisNeal <notifications@github.com> wrote:

> Almar has updated and closed Flexx issue #619
> <https://github.com/flexxui/flexx/issues/619>.
> The suggested fix to leoflexx.py is no longer required.
>

Thanks for this notification.

Edward
