### ISSUE TITLE
@auto style parse on first @clean 'Refresh From Disk'

### ISSUE THREAD

**Issue by ktenney** [leo-editor/leo-editor#148]
Wishlist feature:

A @clean node is created which points to an external file.
rclick -> 'Refresh From Disk' populates the node.

For known file types, create the nodes ala @auto

**Comment by edreamleo** [comment]
As we have discussed, refresh-from-disk should do this only if the @clean node is empty.  Otherwise, refresh-from-disk uses the update algorithm as expected.

**Comment by edreamleo** [comment]
Done at e5e5761.  Please reopen if there are problems.
