### ISSUE TITLE
@@ In headline causes @asis to fail

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#1480]
**John Hutchinson**
Running the latest version from Git 
```
Leo 6.2-b1-devel, devel branch, build b51bcaa8b5
2020-01-05 19:47:27 -0500
Python 3.6.1, PyQt version 5.8.0
Windows 10 AMD64 (build 10.0.18362) SP0
```
Having a tree
```
@asis _foo.txt
    @@ Headline
        Some text
```
and trying to save the file gives the error
```
exception writing: C:/Users/jrhut/Documents/Active/My Maps/_foo.txt
Traceback (most recent call last):
  File "C:\cygwin64\home\jrhut\src\leo-editor\leo-editor\leo\core\leoAtFile.py", line 1291, in asisWrite
    at.writeAsisNode(p)
  File "C:\cygwin64\home\jrhut\src\leo-editor\leo-editor\leo\core\leoAtFile.py", line 1307, in writeAsisNode
    at.outputFile.write(s)
AttributeError: 'AtFile' object has no attribute 'outputFile'
```
Removing the "@@" from the headline generates _foo.txt, but I'm looking to include the headline text in the file exported, so not quite what I need.

**Comment by edreamleo** [comment]
Fixed at b62da96 in devel.

I doubt if anyone has ever used the '@@' escape before. It seems reasonable to write newlines before and after the headline. Let me know if you disagree.

**Comment by jrhutchinson5359** [comment]
Hi: Thanks for fixing this. Re Newlines, I'm sort-of "neutral" but when I read the documentation for AsIs, it sort-of implies there are none ("complete control" over the resulting file)

So I think I'd vote for no new lines if possible, since then I can control the appearance in detail by the end or the previous body or the start of this body. But no big deal either way.

Thanks again -- Leo is a very useful tool in my toolchest, and has been for a long, long time!

**Comment by edreamleo** [comment]
On Wed, Feb 5, 2020 at 10:16 AM jrhutchinson5359 <notifications@github.com>
wrote:

> Hi: Thanks for fixing this. Re Newlines, I'm sort-of "neutral" but when I
> read the documentation for AsIs, it sort-of implies there are none
> ("complete control" over the resulting file)
>
> So I think I'd vote for no new lines if possible, since then I can control
> the appearance in detail by the end or the previous body or the start of
> this body. But no big deal either way.
>
I can do that, but then why use @@ at all?

> Thanks again -- Leo is a very useful tool in my toolchest, and has been
> for a long, long time!
>
You're welcome.

Edward

**Comment by jrhutchinson5359** [comment]
The use is to let me clone @@ nodes, and re-use them in multiple parts of (multiple) files. I tend to use Leo in a workflow where the Leo file itself is the "master" source of a variety of scripts, in a variety of languages / tools. So @ asis / @ nosent files are my default types, and I heavily use clones between elements of the same Leo file (I'm very much a "single user" user, so inter-file dependencies are manageable from a clone perspective).

I (want to) use "@@" nodes to avoid duplicating the headline as the first line of the body, for sections of text / pictures etc. where the headline is a directive to the ultimate domain-specific language (which is often an awk script, or something.

Hopefully this makes sense, so
@ asis foo.text
    @@Headline 1

           Body

@ asis baz.txt
   @@Headline 1 (cloned from above)
           Body

gives two files, with the text 
  Headline 1
  Body

**Comment by edreamleo** [comment]
@jrhutchinson5359 Without at least a newline after the headline, the result would be:

Headline1Body.

**Comment by jrhutchinson5359** [comment]
Agree, But if a newline is needed, I can have a blank line as the first line of the body, can't I?

**Comment by jrhutchinson5359** [comment]
Hi: After a bit more thought and experimentation, I can very much live with the way it's set up now -- so if you'd prefer to leave it as it currently is in Devel, that's 100% workable for me. Thanks again!

**Comment by edreamleo** [comment]
@jrhutchinson5359 Ok. Let's leave it the way it is for now. If you find a use case for having no newlines I'll add a user setting.

**Comment by jrhutchinson5359** [comment]
OK, thanks.

**Comment by spykelion** [comment]
Sure I think newlines are gonna act somehow. But nevertheless we expect the
best from leo

On Wednesday, February 5, 2020, jrhutchinson5359 <notifications@github.com>
wrote:
> OK, thanks.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci4.googleusercontent.com/proxy/wE74D2FnQTCojqaq1UrDDbUUSdIZM9DZOsNXHBm7o_0emtzwyHsi2JbAFv6zqWT_jBTaxmcNAEIkmxRau26m4OgP6fg-gyei7tZjR8Ms_A2LU_gPHcKKeJ6eWrzxJUCPJBOf50bIBCE_ngx74RCqOwxNcGIK6PkL7UTmSiSua63-OCdMxdYwIGIbfxDuA0HIPBsAi1wxIUBa4TcuPCfCMr8aD6zPMMn6Y-wS5sdCTg=s0-d-e1-ft#https://github.com/notifications/beacon/AODRKCBOHUOKJMRQRCAB42DRBMT73A5CNFSM4KKY6RT2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEK5AIVA.gif>
