### ISSUE TITLE
Create a Zettlekasten plugin

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#1482]
I've been dithering whether to do this for 6.1.1. I am likely to do this issue only if it can be done without substantially changing Leo's gui.

Links:
- [Original post](https://groups.google.com/d/msg/leo-editor/JCxqS0XSOoM/GG2Ye-NNDAAJ).
- [Follow on post with links](https://groups.google.com/d/msg/leo-editor/JCxqS0XSOoM/0l2L-ws6EgAJ).
- [Syntax](https://zettelkasten.de/).
- [Principles](https://writingcooperative.com/zettelkasten-its-like-gtd-for-writing-and-here-s-why-you-should-consider-it-7dddf02be394).

**Comment by largo84** [comment]
Looks interesting, can't wait to see it.

**Comment by edreamleo** [comment]
I am delegating this issue, and clearing its milestone.
