### ISSUE TITLE
Is there a way to Resize images in markdown node

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#1487]
Is there a way to Resize images in @language md node?

![](image_path]

or

<img src="image_path" \>

**Comment by wangzhaohe** [comment]
I found it. And it can be used in Typora too.

<img src="static/pic/vscode_justMyCode2.png" width="600" />

**Comment by edreamleo** [comment]
Right. Markdown should allow any embedded html.
