### ISSUE TITLE
Copy-node Shortcut Ctrl+Shift+c Fails

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#1488]
Leo: 6 .1-final from pip install
Python version: 3.8 64-bit
QT: Qt 5.14
OS - Windows 10

On my computer, Ctrl+Shift+c does not copy a node.  Ctrl+Shift+v does paste a copied node, and Ctrl+Shift+x does copy-delete as expected.

On the same computer, running Leo 5.9 under Python 2.7/Qt4, Ctrl+Shift+c does copy  nodes as expected.

I can create an @shortcut binding to, e.g., Alt+F11 and that works, but creating a similar shortcut using Ctrl+Shift+c does not.  Using an alternate binding like Alt+F11 is not appealing to me.

**Comment by edreamleo** [comment]
On Thu, Feb 6, 2020 at 11:10 AM tbpassin <notifications@github.com> wrote:

> Leo: 6 .1-final from pip install
> Python version: 3.8 64-bit
> QT: Qt 5.14
> OS - Windows 10
>
> On my computer, Ctrl+Shift+c does not copy a node. Ctrl+Shift+v does paste
> a copied node, and Ctrl+Shift+x does copy-delete as expected.
>
I use these bindings frequently on a Windows 10 machine. There is likely an
issue with your keyboard.

Try running Leo (from a console) with --trace=keys. That will tell you
a) whether Ctrl-Shift-c is generating any key at all and,
b) what Leo thinks it is doing with the key.

Edward

**Comment by edreamleo** [comment]
I am going to close this issue. It is likely confined to a single user.
