### ISSUE TITLE
Clones can revert changes made by git discard even with --no-cache

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#149]
This just happened to me.  I had a my local leoPy.leo open and pulled Terry's fixes to #145.  I then quit Leo and reopened it (with caching enabled).  There was *no* message about changed nodes, so I was concerned.  I wrote all files with ctrl-shift-w, and yes, leoApp.py was changed.  Git diff confirmed that I had just undone Terry's work.  Naturally, I undid the reversion in git.  The only way to force the changes into leoPy.leo was to use --no-cache.

This is not the first time something like this has happened.

It  *might* be related to #145: I had played around with yes-to-all and no-to-all.  BTW, I did a no-to-all first, and then the next time, iirc, I didn't need to do a yes-to-all!  I had two copies of all my files open without another warning.

Caching is great.  We can't live without it, but it seems it isn't safe in some situations.  I'd like to fix this before b1.

**Comment by tbnorth** [comment]
On Thu, 05 Mar 2015 15:35:20 -0800
"Edward K. Ream" <notifications@github.com> wrote:

> This just happened to me.  I had a my local leoPy.leo open and pulled
> Terry's fixes to #145.  I then quit Leo and reopened it (with caching
> enabled).  There was *no* message about changed nodes, so I was
> concerned.  I wrote all files with ctrl-shift-w, and yes, leoApp.py
> was changed.  Git diff confirmed that I had just undone Terry's
> work.  Naturally, I undid the reversion in git.  The only way to
> force the changes into leoPy.leo was to use --no-cache.

I wonder if I messed things up.  I was making a lot of little tweaks to
my changes to make the diff as clean as possible.  I.e. not committing,
just editing, and then looking at the diff.  Could have done 
`git diff leo/core/leoApp.py`, but instead I did
`git checkout leo/core/LeoPyRef.leo then git diff`, both achieve the
same goal of showing only leoApp.py diffs.

But I thought it was irritating to have to checkout LeoPyRef.leo every
time, so I started saving my changes with `Write dirty @<file> nodes`
instead of just Ctrl-s like I usually do.  That meant LeoPyRef.leo
wasn't changing, but then so does doing a checkout on it all the time,
as I usually do, so I'm not sure there's any difference.

Just wanted to mention it seeing I never used `Write dirty @<file>
nodes` before.

**Comment by edreamleo** [comment]
On Thu, Mar 5, 2015 at 5:53 PM, tbnorth <notifications@github.com> wrote:

>
> I wonder if I messed things up. I was making a lot of little tweaks to
> my changes to make the diff as clean as possible. I.e. not committing,
> just editing, and then looking at the diff. Could have done
> `git diff leo/core/leoApp.py`, but instead I did
> `git checkout leo/core/LeoPyRef.leo then git diff`, both achieve the
> same goal of showing only leoApp.py diffs.
>

​I don't this can affect things.  All that matters is that leoApp.py
changed.​


>
> But I thought it was irritating to have to checkout LeoPyRef.leo every
> time


​I never touch LeoPyRef.leo unless I add or delete @<file> nodes.

I don't see how *any* git work flow can be the culprit.  leoApp.py changed,
but Leo didn't get it. Simple as that. The next time I loaded leoPy.leo the
*old* contents of leoApp.py reappeared in the outline.  Distressing.

I'm studying the cacher in detail...

Edward

**Comment by edreamleo** [comment]
I can find nothing suspicious in the caching code.  Furthermore, the obvious tests of caching pass.  This is expected--caching mostly works.  For now, I am willing to call this a minor bug.  It is not a release blocker.

My plan: add caching-related traces enabled when --debug is in effect. If/when this bug bites again I shall be able to investigate without suppressing the bug's symptoms.

The worst actions would be to make changes to the code without first knowing exactly what the original problem was.  I have made some changes to the code, but imo they can not possibly affect the caching scheme.  Most of the changes are related to tracing.  I also added g.readFileIntoEncodedString to make clearer what was happening.

During my studies I saw that at.read actually reads uncached files twice: once to determine the caching key and a second time to actually read the file.  Clearly, this is unnecessary, but "full" reads happen so seldom that it isn't a serious issue.  I may leave the code as it is...

**Comment by edreamleo** [comment]
I can now produce a similar problem that exists *regardless* of the --no-cache option.  I think this is a clone update problem instead.  I may have to revise this FAQ entry:
How does Leo handle clone conflicts? http://leoeditor.com/FAQ.html#id30.

Start with this outline structure::
    
    To do:
        @file ../doc/leoToDo.txt
            (clone) To do: Leo 5.1 b1
                Docs
    (clone) To do: Leo 5.1 b1
        Docs

- In the Docs node write changed.  Save .leo file and quit.
- Revert the change in git.
- Reload Leo.  The change reappears **regardless** of --no-cache option!

**Comment by edreamleo** [comment]
I am removing the "minor" label and targeting the bug for b1.  This behavior is too confusing to tolerate.

**Comment by edreamleo** [comment]
Early this morning I spent more than an hour carefully rewriting the << detecting clone changes >> section in leoAtFile.py.  Here it is:

QQQ

The read code uses the following *temporary* ivars to compute v.b and to detect clone conflicts:

- **v.tempBodyList**: accumulates lines of body text during reading.
- **v.tempBodyString**: contains the previous value of v.b, if any.

The vnode ctor must not create these two ivars!

A **post-pass** (at.readPostPass and its helpers) computes the new value of v.b for each vnode and detects clone conflicts. A clone conflict exists if and *only* if::

    hasattr(v,'tempBodyString') and v.b != v.tempBodyString.
    
The post pass adds an entry in c.nodeConflictList for each clone conflict. Later, fc.handleNodeConflicts creates a 'Recovered Nodes' node for each entry in c.nodeConflictList.

QQQ

I see two possible bugs with the present code (more investigation needed):

1. cacher.readFile & helpers should test for conflicts as shown above.  Clones in cached files *could* conflict with nodes in non-cached files.  At present, the post-pass doesn't get called for cached reads so no checks are made. 

2. at.readPostPass itself contains dubious-looking code, but this code must not be changed without the most careful thought and testing.

In any event, the next step will be to recreate the bug in a small test file.  We shall then be in a much better position to see what is going on.

P.S. Rev 23b514f renamed at.copyAllTempBodysToVnode to at.readPostPass.

**Comment by edreamleo** [comment]
Rev 5c6cb97 contains leo/test/clone-test.leo, a minimal .leo files demonstrating the bug as described before.  **Important**: The *initial* body text of Doc must be empty, and committed in git.

clone-test.leo will allow voluminous traces to determine exactly what is going on.

**Comment by edreamleo** [comment]
The essence of this bug: reloading the .leo file retains the old body text in the Doc node, without any warning.  In particular, no "Recovered Nodes" node is created and no nodes are marked dirty. There is therefore *no* indication that ctrl-shift-w will overwrite data in the external file!

What should always happen is this:

1. Data in external files should always take precedence over data in the outline.
2. If two external files contain clones with different bodies, the last external file read should "win".

Separate wishlist possibilities, not directly affecting this bug.

1. Editors such as scite reload changed files when they regain focus.
2. If two external files contain different timestamps, Leo might choose the data with the latest timestamp.

**Comment by edreamleo** [comment]
This bug was fixed at rev 6439440.  There are several remaining issues re recovered nodes, but they do not affect this bug.
