### ISSUE TITLE
Enhancement Request - Additional Body Editors Should Display Line Numbers

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#1492]
I have configured Leo to show line numbers.  I noticed that when I open a second body editor, the new one does not show line numbers.  IMO, it should if the base editor does.

I see that this duplicates #1061, so please consider this to show that someone else cares about this issue, too.

**Comment by edreamleo** [comment]
I have scheduled #1061 for 6.3.  I am going to close this issue because it is a duplicate.
