### ISSUE TITLE
Drag-Cloning (with ctrl-drag-and-drop) crashes leo.

### ISSUE THREAD

**Issue by Yaakov-Belch** [leo-editor/leo-editor#1495]
After a fresh install of the leo editor (on ubuntu 18.04), ctrl-drag-and-drop of any node (to clone it) crashes leo with the following stack trace:

    Traceback (most recent call last):
      File "/home/yaakov/.local/share/virtualenvs/ypy-kTRUv9tR/lib/python3.8/site-packages/leo/plugins/qt_frame.py", line 4008, in dropEvent
        self.nodeDrop(md, p)
      File "/home/yaakov/.local/share/virtualenvs/ypy-kTRUv9tR/lib/python3.8/site-packages/leo/plugins/qt_frame.py", line 4025, in nodeDrop
        self.intraFileDrop(fn, c.p, p)
      File "/home/yaakov/.local/share/virtualenvs/ypy-kTRUv9tR/lib/python3.8/site-packages/leo/plugins/qt_frame.py", line 4113, in intraFileDrop
        z.setAllAncestorAtFileNodesDirty(
    TypeError: setAllAncestorAtFileNodesDirty() got an unexpected keyword argument 'setDescendentsDirty'
    Aborted

I would expect the node to be cloned --- without errors.

**Comment by Yaakov-Belch** [comment]
Searching the leo source for `setAllAncestorAtFileNodesDirty` and `setDescendentsDirty` shows:

The only place where `setAllAncestorAtFileNodesDirty` is called with arguments is in the node `LeoQTreeWidget.intraFileDrop (changed)`:

            ...
            if cloneDrag:
                # Set dirty bits for ancestors of *all* cloned nodes.
                # Note: the setDescendentsDirty flag does not do what we want.
                for z in p1.self_and_subtree():
                    z.setAllAncestorAtFileNodesDirty(
                        setDescendentsDirty=False)
            ...

The definition of `setAllAncestorAtFileNodesDirty` appears in `p.setAllAncestorAtFileNodesDirty` and starts with these lines:

    def setAllAncestorAtFileNodesDirty(self): # setDescendentsDirty=False
        """
        Rewritten by Виталије Милошевић (Vitalije Milosevic).
        """

The body of this function does no longer use the `setDescendentsDirty` flag. This seems to indicate that at some point in the past, the flag `setDescendentsDirty` was removed (and refactored) --- but left in one call.

Removing the superfluous flag `setDescendentsDirty=False` from that last use case seems to work --- but I do not have enough experience to be sure that it always does what is intended.

**Comment by edreamleo** [comment]
The code you reference exists in Leo's "master" branch, but not in Leo's "devel" branch.

Therefore, the bug has already been fixed.

gitk leo/plugins/qt_frame.py shows that the fix was made at rev 49ad01 on December 13, 2019.

**Comment by Yaakov-Belch** [comment]
Thank you very much.

**Comment by edreamleo** [comment]
@Yaakov-Belch  You're welcome.
