### ISSUE TITLE
Create an importer for todo.txt files

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#1499]
The home page is [here](http://todotxt.org/). [This page](https://github.com/todotxt/todo.txt) describes the text format in words. Imo, the regex's in The ToDoImporter and ToDoTask classes are significantly clearer.

**Ready for testing**

As of recent revs in devel, the following commands and code are ready for testing:

The 'import-todo-text-files' command prompts for one or more .txt files and shows the tasks in each file. At present, this command just prints the calculated list of ToDoTask objects.

Scripts or plugins can use the list of ToDoTask objects as follows:
```python
import leo.core.leoImport as leoImport
# path should be a full path to a todo.txt file
tasks = leoImport.ToDoImporter(c).get_tasks_from_file(path)
g.printObj(tasks, tag=f"tasks from {path}")
```
**Comment and blank lines**

At present, the ToDoImporter class ignores blanks lines.

**Comment by xu4wang** [comment]
https://github.com/EpocDotFr/todotxtio

I found above Python module for read/write the todo.txt file, it is being used by https://github.com/EpocDotFr/webtodotxt

A good feature for most of the todo.txt client software is they can filter tasks by "Project" or "Context", is there any recommendation to filter under Leo?

**Comment by xu4wang** [comment]
Is it possible to hide/show some items under the selected node?  I'm thinking to create several buttons for the filter scenarios:

1) One "ShowAll" button to show all the items under the todo.txt node;
2) One "Project XXX" button to show only the sub-items with the +XXX in headline
3) One "Context home" button to show only the sub-items with the @home headline
...

**Comment by edreamleo** [comment]
On Wed, Feb 19, 2020 at 10:04 AM Austin (Xu) Wang <notifications@github.com>
wrote:

> https://github.com/EpocDotFr/todotxtio
>
> I found above Python module for read/write the todo.txt file, it is being
> used by https://github.com/EpocDotFr/webtodotxt
>
> A good feature for most of the todo.txt client software is they can filter
> tasks by "Project" or "Context", is there any recommendation to filter
> under Leo?
>
I'd have to play with the product before making any recommendations.

Edward

**Comment by edreamleo** [comment]
On Wed, Feb 19, 2020 at 10:43 AM Austin (Xu) Wang <notifications@github.com>
wrote:

> Is it possible to hide/show some items under the selected node?
>
It depends on what you want to do. At present, #1499 deals only with
importing data into nodes. Creating a to-do plugin would be a separate
project, possibly an enhancement to the present todo.py plugin.

Edward

**Comment by xu4wang** [comment]
OK fair enough.. this is for the importing feature.

**Comment by edreamleo** [comment]
I'll work on this while we test 6.2. It may make Leo 6.2.
