### ISSUE TITLE
Importing file to @clean produces section references following class constructor

### ISSUE THREAD

**Issue by slzatz** [leo-editor/leo-editor#150]
If you use File-> Import File ... every class has <<class XXXXX methods>> on the line after the class declaration.  These section references don't have corresponding sections defined and so are not helpful.  It requires either programmatically or manually going through the code and changing all those class method section references to @others.  Apparently, using c.recursiveImport doesn't have this problem (have not tested it).

**Comment by edreamleo** [comment]
Fixed at rev 4ab250c.  Please reopen if there are further problems.
