### ISSUE TITLE
Render does not display relative path picture

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#1501]
Leo Log Window
Leo 6.2-b1-devel, devel branch, build e5d2a41822
2020-02-21 16:40:01 -0600
Python 3.7.3, PyQt version 5.12.3
darwin

***

Not work:

    ![Belonging2Friend.png](./doc/pic/Belonging2Friend.png)

    ![Belonging2Friend.png](doc/pic/Belonging2Friend.png)

Work ok:

    ![Belonging2Friend.png](/Users/swot/Desktop/learn/django/doc/pic/Belonging2Friend.png)

**Comment by edreamleo** [comment]
Rev fe91b27 adds the following to the VR docstring:
```
Relative file names
===================

vr.convert_to_html resolves relative paths using whatever @path directive
is in effect for a particular node. It also does `os.chdir(path)` for that
path.
```

In other words, if you want to use relative paths, the nodes to be rendered should be descendants of an `@path` node.
