### ISSUE TITLE
history tracer plugin: urllib connection refused errors

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#1502]
My first run at using History Tracer plugin. Machine is Linux Mint 18.2 Xfce 64-bit.

 - added history_tracer.py to myLeoSettings.leo#@settings-->@enabled-plugins
(btw, HT isn't in the master list of LeoSettings plugins)
 - installed rustup, cargo, as per Groups thread [here](https://groups.google.com/d/msg/leo-editor/bGS1P42ppOM/XDUuvetzCAAJ)
 - and leo-ver-serv as per [it's readme](https://github.com/vitalije/fossil-delta/tree/master/leo-ver-serv)

1. run `leo-ver-serv ~/.leo/.leoRecentFiles.txt 8088` in terminal
2. point browser at http://localhost:8088/. Use chooser to select _myLeoSettings.leo_
3. run Leo, open my settings, create a new node and start typing.

Leo's log pane:
~~~
Leo Log Window
Leo 6.2-b1-devel, devel branch, build e5d2a41822
2020-02-21 16:40:01 -0600
Python 3.6.8, PyQt version 5.12.6
linux
read outline in 0.05 seconds
snap 2 myLeoSettings.leo
snap 2 myLeoSettings.leo
snap 2 myLeoSettings.leo
snap 2 myLeoSettings.leo
snap 2 myLeoSettings.leo
snap 2 myLeoSettings.leo
snap 2 myLeoSettings.leo
snap 2 myLeoSettings.leo
wrote recent file: /home/matt/.leo/.leoRecentFiles.txt
 saved: myLeoSettings.leo
snap 2 myLeoSettings.leo
~~~

Leo's terminal (edited, full log attached):
~~~
--global-docks: False
setting leoID from os.getenv('USER'): 'matt'
QApplication: invalid style override passed, ignoring it.
    Available styles: Windows, Fusion
Leo 6.2-b1-devel, devel branch, build e5d2a41822
2020-02-21 16:40:01 -0600
don't forget to launch leo-ver-serv!!!
Exception in thread snapshot-saver:
Traceback (most recent call last):
  File "/home/matt/miniconda3/envs/leo-dev/lib/python3.6/urllib/request.py", line 1318, in do_open
[...]  
create_connection
    raise err
  File "/home/matt/miniconda3/envs/leo-dev/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/matt/miniconda3/envs/leo-dev/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
[...]
  File "/home/matt/miniconda3/envs/leo-dev/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>
~~~

leo-ver-serv terminal shows nothing:
~~~
matt@dell-xps ~ $ leo-ver-serv ~/.leo/.leoRecentFiles.txt 8088

~~~

**Comment by maphew** [comment]
[history-tracer-log.txt](https://github.com/leo-editor/leo-editor/files/4238921/history-tracer-log.txt)

**Comment by maphew** [comment]
Replicated on Win10 Pro x64. I used the native Windows "rustup-init.exe" and not subsystem for linux when installing Rustup. Error is the same except for the the number:

>urllib.error.URLError: <urlopen error [WinError 10061] No connection could be made because the target machine actively refused it>

**Comment by maphew** [comment]
AHA! _Read the source luke!_  The docstring in history_tracer.py says 

> The second argument for leo-ver-serv is a port number. The same port
>    number must be in your settings.
>    `@int history-tracer-port=8087`

After adding that to myLeoSettings.leo and restarting the connection errors are gone from the terminal, and both terminals show status messages as I would expect:

**Leo terminal**
~~~
Leo 6.2-b1-devel, devel branch, build cbc62e12e6
2020-02-22 18:23:31 -0600

pyzo_in_leo not loaded: requires --global-docks

can not open D:/code-maphew/leo-editor/leo/plugins/pretty_print.py
don't forget to launch leo-ver-serv!!!
save_snapshot: C:/Users/mhwilkie/.leo/myLeoSettings.leo Ok in 2078.24ms
save_snapshot: C:/Users/mhwilkie/.leo/myLeoSettings.leo Ok in 2021.36ms
wrote recent file: C:/Users/mhwilkie/.leo/.leoRecentFiles.txt
save_snapshot: C:/Users/mhwilkie/.leo/myLeoSettings.leo Ok in 2028.08ms
save_snapshot: C:/Users/mhwilkie/.leo/myLeoSettings.leo Ok in 2027.50ms
save_snapshot: C:/Users/mhwilkie/.leo/myLeoSettings.leo Ok in 2027.37ms
save_snapshot: C:/Users/mhwilkie/.leo/myLeoSettings.leo Ok in 2024.87ms
save_snapshot: D:/code-maphew/leo-editor/leo/plugins/leoPluginsRef.leo Ok in 2133.71ms
~~~

**leo-ver-serv terminal**
~~~
$ leo-ver-serv .leo\.leoRecentFiles.txt 8088
post snapshot 5919 bytes at 2020-02-23T01:14:39.000000
post snapshot 5977 bytes at 2020-02-23T01:14:59.000000
post snapshot 6015 bytes at 2020-02-23T01:15:34.000000
post snapshot 6043 bytes at 2020-02-23T01:16:59.000000
post snapshot 6081 bytes at 2020-02-23T01:17:14.000000
post snapshot 6173 bytes at 2020-02-23T01:17:49.000000
post snapshot 2179471 bytes at 2020-02-23T01:20:34.000000
~~~

HOWEVER, the browser window is still not showing any activity:
![image](https://user-images.githubusercontent.com/486200/75101856-4f2d9a00-5598-11ea-9886-2bbac0988492.png)

**Comment by maphew** [comment]
I created a PR in fossil-delta to improve the docs, which would have helped me avoid this issue. However I'm leaving open @vitalije so you can decide whether that is enough of a fix (perhaps you'd like to add some logic that tests a few obvious ports or something).

**Comment by vitalije** [comment]
@maphew what should we do with this issue? I have accepted and merged your PR in fossil-delta. Is there anything more to be fixed? Can I close this issue?
Vitalije

**Comment by vitalije** [comment]
I am going to close this issue. If the problem occurs again please reopen.
