### ISSUE TITLE
Leo File Title in Window Title Bar Missing When  Started With --global-docks

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#1506]
Leo: Leo 6.2-b1-devel
OS: Windows 10 64-bit
Python: 3.8

The name and path of the current Leo outline is missing from the window's title bar when I start Leo with --global-docks.  When I start it with no options, the outline name/path is displayed.

I have been starting Leo with
```python
python -m leo.core.runLeo
```
I find the display helpful, and I would also like to keep using ``--global-docks``

**Comment by edreamleo** [comment]
Fixed at 911bb47 in devel.
