### ISSUE TITLE
Find Tab is missing when --no-dock start option is used

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#1507]
The Find Tab is missing if leo is started with
launchleo.py --no-dock

_Leo Log Window
Leo 6.2-b1-devel, devel branch, build cbc62e12e6
2020-02-22 18:23:31 -0600
Python 3.8.1, PyQt version 5.14.0
Windows 10 AMD64 (build 10.0.18362) SP0_

**Comment by wangzhaohe** [comment]
And body panel size can not be adjusted after add-editor command with --no-dock.

Still like version 5.9 which have many commands to adjust layout.

**Comment by edreamleo** [comment]
@LewisNeal I see this behavior. Something strange is going on, because the Find tab *is* visible when I launch Leo from one of my scripts.

**Comment by edreamleo** [comment]
Fixed at rev b341d9c in devel

**Comment by edreamleo** [comment]
@wangzhaohe I have just created #1513 to restore commands that adjust layout.

**Comment by edreamleo** [comment]
I am reopening this. The supposed one-line change has bizarre consequences.

**Comment by edreamleo** [comment]
Fixed at 91eb04c in the docks branch. From the checkin log:

Add detailed comments re @bool minibuffer-find-mode and @bool use-find-dialog. These settings work like a single tri-state setting.
