### ISSUE TITLE
why can I not use the toctree

### ISSUE THREAD

**Issue by wisdom1972** [leo-editor/leo-editor#1509]
I write a node name "@rst html/productdoc.html
the node body is as follows: 

**Chapter2**: 
**content**

.. toctree::
   :maxdepth: 3
         
   datasheet.html
   RISCV.html
   DDR3
   MIPI
   VideoBox

My question is , why the LEO render told me the  "sysem Message: ERROR/3 (<string>, line9
Unknown directive type "toctree"

How should I use the toctree.  

Thank you
Wisdom

**Comment by edreamleo** [comment]
toctree is sphinx markup, not reStructuredText markup.
