### ISSUE TITLE
Errors Installing leo system-wide

### ISSUE THREAD

**Issue by brobr** [leo-editor/leo-editor#1512]
Hi, thanks for the ongoing development of leo. As might have been clear from previous posts I try to make a leo package that can be installed via distribution install/upgrade tools which is using the setup.py route (not pip). This works but I encounter a) a couple of warnings during building and b) some errors when running leo, which are the most serious.
ad a) some warnings during building:

> /usr/lib64/python3.8/site-packages/leo/external/npyscreen/npyspmfuncs.py:37: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if rtn is not 0: return False
byte-compiling /tmp/SBo/package-leo/usr/lib64/python3.8/site-packages/leo/external/npyscreen/npyssafewrapper.py to npyssafewrapper.cpython-38.pyc
byte-compiling /tmp/SBo/package-leo/usr/lib64/python3.8/site-packages/leo/external/npyscreen/proto_fm_screen_area.py to proto_fm_screen_area.cpython-38.pyc
/usr/lib64/python3.8/site-packages/leo/external/npyscreen/proto_fm_screen_area.py:171: SyntaxWarning: "is" with a literal. Did you mean "=="?
  self.show_from_y is 0 and
/usr/lib64/python3.8/site-packages/leo/external/npyscreen/proto_fm_screen_area.py:172: SyntaxWarning: "is" with a literal. Did you mean "=="?
  self.show_from_x is 0 and

ad b) then during running from the command line it becomes clear that not all files that leo needs are getting installed via the setup.py script. I am not too familiar with python-development but it appears that things like Icons, ToDo.ui and all files not ending in '.py' (should these be mentioned in 'SOURCES.txt' after install: [SOURCES.txt](https://github.com/leo-editor/leo-editor/files/4261311/SOURCES.txt) ?) are not ending up in python/3/site-packages/leo.  

How can this be corrected in the setup.py (or elsewhere) so that this route yields a full leo install?

Thanks,

rob

**Comment by edreamleo** [comment]
@brobr Matt Wilkie is handling distribution-related issues, so I've assigned this issue to him.

**Comment by maphew** [comment]
How are you using setup.py? `python setup.py` ?

A crude but failsafe method should be to:

- download a release zipball (https://github.com/leo-editor/leo-editor/archive/v6.1.zip) 
- extract somewhere disposable, e.g. `/tmp/leo-scratch`
- run whatever setup procedures are needed for your systems (e.g. `python setup.py`)
- copy `/tmp/leo-scratch/leo-editor-6.1/leo/*` to `$SYSTEM/python/3/site-packages/leo/*`

**Comment by brobr** [comment]
Well, with 5.9 and previous versions, as with all python packages created with our build-scripts,  this goes via the commonly used line `python setup.py install`. Hardly anything else needs normally be done in the case of most python-based software. 

With 6.1 'python setup.py install' does not result in a correct installation of leo which was the reason to raise this issue (and why I suggested whether something could be missing from the 'SOURCES.txt', although it could be that another file needs to be corrected). 

You propose a non-python solution. Which is fine, as it can easily be done, but does not resolve a breakage of a normal python-install command introduced in the current version of leo, and apparently not carried over when using pip. So what has been done differently since 5.9? And (how) can it be repaired so that leo remains 'python-consistent'?

**Comment by maphew** [comment]
I started learning about python packaging a little after `pip install {thing}` became mainstream and the recommended path so never learned much about the older `python setup.py install` method. I don't know how to test it effectively.

As for "what is done differently?" and SOURCES.TXT: as I understand it this text file is built by tools using setup.py (e.g. pip and python's setuptools) from the patterns in `MANIFEST.in`. Looking at it's [blame history](https://github.com/leo-editor/leo-editor/blame/master/MANIFEST.in) my suspicion is the commented out line:

    #recursive-include leo *.*     # not needed when using `graft`

Perhaps the _graft_ and _prune_ keywords are not something the version of setuptools on your platform understands? I don't see anything on https://packaging.python.org/guides/using-manifest-in/ which indicates when those terms were introduced. At least 4 years ago though.

**Comment by brobr** [comment]
Well I have far less experience with python installs, but I think you hit the point, as there is no `MANIFEST.in` in the leo-6 source at all. Copying it from the 5.9 source as it is (without any changes) into the 6.1 tree before `python setup.py install` is run makes it all work again (i.e. the program starts up with the leo-logo etc. and without any error messages when run from the console)!

Just restore that file to the source-tarball and Bob's your uncle.

**Comment by maphew** [comment]
umm, it's right here https://github.com/leo-editor/leo-editor/blob/master/MANIFEST.in ?
How are you retrieving the source tarball?

**Comment by brobr** [comment]
On 26 Feb I got the source from the github releases page (https://github.com/leo-editor/leo-editor/archive/v6.1.tar.gz), which gave a 9.1 MiB leo-editor-6.1.tar.gz (md5sum e32780ea56916dab5c273fb4dd5cf58c) after saving. 
No `MANIFEST.in` in there (but with `LICENSE`).

Just now, I also tried the 7.2 MiB leo-6.1.tar.gz (md5sum 560be785741cc11baa26a99ca5c9ad06) from pypi as source, which has a `MANIFEST.in` (but no `LICENSE`). This built fine and runs fine too.

So one always need to get the source from pypi?

**Comment by maphew** [comment]
Missing manifest.in in release tarballs is a bug. Looking into how it happens...

**Comment by maphew** [comment]
I'm confused. Setting my local git repo to the v6.1 release with `git checkout v6.1` the `MANIFEST.in` file is present. However if I `git archive -o dist\local-6.1.tar.gz v6.1` and inspect the tarball `MANIFEST.in` is NOT there. I don't know what to make of this.

**Comment by maphew** [comment]
Believe fixed in 77f4000. We'll know for sure when the next dot release comes out. Please re-open if needed.

**Comment by brobr** [comment]
Ok, thanks. Just checked leo-editor-6.2.tar.gz from GitHub, which still lacks the Manifest; but I assume you mean 6.3 as 6.2 was released prior your update.

BTW the 6.2.-install using the pypi-source went fine. One hitch though, in the setup.py requires section the the versions for PyQt and PyQtWebEngine are defined rather narrow. As my system is on 5.13.3 now I had to patch the setup.py file to get compilation to work (a slightly newer version would not break the bank I assumed...):
>diff -Naur leo-6.2/setup.py leo-6.2b/setup.py
--- leo-6.2/setup.py	2020-03-27 10:15:40.000000000 +0000
+++ leo-6.2b/setup.py	2020-03-29 15:11:00.456264992 +0100
@@ -107,8 +107,8 @@
     # setup_requires no longer needed with PEP-518 and pip >v10
 #@+node:maphew.20171120133429.1: ** User requirements
 user_requires = [
-    'PyQt5 >= 5.12, < 5.13',  # v5.12+ to close #1217
-    'PyQtWebEngine < 5.13',  # #1202 QtWebKit needs to be installed separately starting Qt 5.6
+    'PyQt5 >= 5.12, < 5.13.3',  # v5.12+ to close #1217
+    'PyQtWebEngine < 5.13.3',  # #1202 QtWebKit needs to be installed separately starting Qt 5.6
     'asttokens',  # abstract syntax tree text parsing
     'docutils',  # used by Sphinx, rST plugin
     'flexx',  # for LeoWapp browser gui

Thanks again, for all the work and keep well.

Rob

PS on pypi/leo there are two ways to download leo: the pypi-specific 'Download-files' button and a separate 'Download' button next to the 'Homepage' button. This 'Download' button directs the user to an outdated looking leo-webpage page referring to leo-5.7. Maybe that connection should be removed -or the leo-webpage updated- as it is confusing.

**Comment by maphew** [comment]
The fix will be in v6.2.1, which Edward expects to release tomorrow. It is in the _devel_ branch now though (https://github.com/leo-editor/leo-editor/archive/devel.zip).

Thanks for heads up about narrow PyQt and webengine versions. I tested v.5.14 with py3.7.6 and 3.8.2 on linux and both worked fine. So I've now removed the upper version limit in setup.py requires. This will also be in v6.2.1 release.

**Comment by brobr** [comment]
Fab ;-) 
Will test this tomorrow

rob

**Comment by edreamleo** [comment]
@brobr Thanks for testing. I'll await your verdict before releasing 6.2.1.

**Comment by brobr** [comment]
No need to wait afaiac; install of the linked zip-archive works fine at my end ;-)

![6-3dev-Screenshot_2020-03-30_11-32-32](https://user-images.githubusercontent.com/3693709/77903262-77d13f80-727a-11ea-82ba-bd8abac0e930.png)

**Comment by edreamleo** [comment]
On Mon, Mar 30, 2020 at 5:36 AM brobr <notifications@github.com> wrote:

> No need to wait afaiac; install of the linked zip-archive works fine at my
> end ;-)
>
Thanks for the confirmation.

Edward
