### ISSUE TITLE
Leo 6.2-b1-devel add-editor body size too small

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#1517]
I remembered that add-editor body was equal to main body in Leo 5.x version.

But in Leo 6.2, add-editor body is so small and fixed. So add-editor is no useful.

***

Leo Log Window
Leo 6.2-b1-devel, devel branch, build 5da736ea4d
2020-02-29 06:19:36 -0600
Python 3.7.3, PyQt version 5.12.3
darwin

**Comment by tbpassin** [comment]
Leo: 6.2-b2-devel
OS: Windows 10

Well, for me it's coming up bigger than it usually does in 6.1. That's using docks. But its size is strangely variable. If you are using docks, you can drag it into a docking station, and it will change size to fill that dock. In 6.1, the size of the free-floating new editor window wasn't adjustable, either.

I think it should be adjustable when free-floating, in case anyone wants to use it that way.

Running without docks, I agree that the width is too small to be usable, and it can't be adjusted.
