### ISSUE TITLE
Restore Leo's pane commands

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#1518]
no command for @item 'contract-body-pane'
no command for @item 'expand-body-pane'
no command for @item 'expand-outline-pane'

***

Leo Log Window
Leo 6.2-b1-devel, devel branch, build 5da736ea4d
2020-02-29 06:19:36 -0600
Python 3.7.3, PyQt version 5.12.3
darwin

**Comment by edreamleo** [comment]
This is a subset of #1513. Given the interest, I'll do the expand/contract commands for 6.2. Macro commands will wait until 6.4.

**Comment by edreamleo** [comment]
Rev d4a52a9 restores these commands. They work only when not using docks.

**Comment by edreamleo** [comment]
These commands work only when --use-docks is in effect:

These commands work only when --use-docks is *not* in effect:

- contract-body-pane, same as expand-outline-pane.
- contract-log-pane and expand-log pane.
- contract-outline-pane, same as expand-body-pane.
- hide-body-pane, hide-log-pane and hide-outline-pane.

**Comment by edreamleo** [comment]
Completed at 5e4066c.
