### ISSUE TITLE
Parse the clipboard to support "Paste As RST"

### ISSUE THREAD

**Issue by technatica** [leo-editor/leo-editor#152]
This is a feature request.

The idea is to parse the text in the clipboard (rich-text, html etc.) and present the user with the option to "Paste As" rst source.

**Comment by tbnorth** [comment]
On Tue, 10 Mar 2015 13:15:51 -0700
technatica <notifications@github.com> wrote:

> This is a feature request.
> 
> The idea is to parse the text in the clipboard (rich-text, html etc.)
> and present the user with the option to "Paste As" rst source. 

The paste_as_headlines plugin sort of does this with indented text.  It
can be very handy at times.  Parsing HTML and additional formats for
structure is a big deal though, http://johnmacfarlane.net/pandoc/ does
it I guess, but that would be too large to be a dependency.

If you'd be happy with only parsing HTML... hmmm, maybe "richtext" is
HTML on the clipboard?  Anyway, restricting the feature to parsing HTML
would certainly make it more doable.  Only thing is handling loose
HTML which isn't valid XML, lxml has a forgiving HTML parser, but that
again would be a dependency.  Not sure if base Python has a parser that
would do the work easily.

**Comment by technatica** [comment]
I only included html as an idea to increase the likelihood of it being
useful to others. My primary use is rst.

Chris

**Comment by technatica** [comment]
Pandoc works with the xclip utility as packaged for Debian Sid.

xclip -o -selection clipboard -t text/html | pandoc -r html -w rst

Chris

**Comment by edreamleo** [comment]
@technatica Any suggestions about how to create the rST sources?

**Comment by technatica** [comment]
My use case is was this:

I was writing an rst document in Leo. I research using Chrome and copy a
selection of text (bold, italic, URLs etc.) and paste it into my document
and have to add in the rst markup. I think "Wouldn't it be brilliant if I
could paste the html snippet from Chrome directly as rst into Leo" and
filed the enhancement request.

The pandoc snippet above also works to create markdown, simply by changing
the "rst" to "markdown". I have pretty much transitioned to using markdown,
so it works for me, but is still exceptionally clunky, as I must fill the
clipboard, open a terminal window, type the command, and copy/paste the
results into my document. I find myself using this solution very rarely,
usually only with larger bits of complex text that would take longer to
manually markup than using the solution. The solution also only works with
html snippets. A copy/paste from a pdf, for example, doesn't hit the
clipboard as html/text, so it isn't translated. I am not sure if the use
case is worth the time and effort as I can't think of many instances when a
programmer would find it handy, but writers of all kinds might find it
useful.

Ideally, there would be a Leo command that could be mapped to a key combo
to perform the conversion and paste. The xclip solution is very niche, as
it requires a specific version of an abandoned utility and would likely
only ever work on Linux. Pandoc, as Terry points out, is a very large
dependency. Whether it would be worthwhile for you to recreate this
functionality within Leo or not can only be determined by you, I guess. It
seems like it would be nifty, but also a lot of work.

Chris

**Comment by edreamleo** [comment]
Thanks for the data.  I've targeted it for 5.4.  No guarantees, though.

**Comment by edreamleo** [comment]
This feature can degrade (or be disabled) if pandoc is not available.  With Anaconda (the recommended way to install IPython/Jupyter), it takes seconds to install.

This is on the list for 5.5.

**Comment by technatica** [comment]
On reflection, this won't be as useful as I first thought. I am closing it unless anyone else is interested.

There are simple workarounds that are probably more robust in the long run. Reading the clipboard using xclip and using a bash script to convert the html to rst and piping the result into a file that has its own @file node in Leo comes to mind.

**Comment by xgid** [comment]
> Reading the clipboard using xclip and using a bash script to convert the html to rst and piping the result into a file that has its own @file node in Leo comes to mind.

In that same spirit, you could also use [CopyQ](https://github.com/hluk/CopyQ) which also supports Python as scripting language. Once I discovered CopyQ, I've never had the need for any other clipboard manager: it's simply fantastic!

**Comment by xgid** [comment]
By the way, regarding your original use case: I preciselly have a CopyQ command which I activate with a global key combination (Ctrl+Alt+H) that simply runs this in CopyQ:

```python
python:
from plumbum import local
from xutil.audio import play_sound

py = local['python']
py(r'D:\proj\code\scripts\html2md.py', retcode=0)
play_sound(1630,0.05)
```

and the `html2md.py` script just calls pandoc to convert the Clipboard from HTML to Markdown and copies the result back into de Clipboard. I've found this to be the best approach for me (instead of writing all the Python script in CopyQ itself) so I can edit and test the conversion Python scripts using my favorite editor. 😄

**Comment by technatica** [comment]
Wow! Lots there to ponder.

I think we should start putting together a Leo file full of recipes like
this.

Chris

**Comment by edreamleo** [comment]
On Mon, Aug 19, 2019 at 7:54 PM Chris George <notifications@github.com>
wrote:

> Wow! Lots there to ponder.
>

Yes.  Following this CopyQ page <https://github.com/hluk/CopyQ> lead me to
CMake <https://cmake.org/>. I've been frustrated with build tools on
Windows.  Perhaps CMake will be better.  Or perhaps we'll get some
rust-based tools.

I think we should start putting together a Leo file full of recipes like
> this.
>

What's wrong with leo/scripts/scripts.leo? Open it with leo-scripts-leo, or
in practice, <alt-x>leo-sc<tab><return>

Edward

**Comment by technatica** [comment]
That would be a good place to keep them.

I have a couple of recipes that really only touch on scripts but are mainly
Leo in conjunction with bash and other commands which work together to get
things done. The idea behind piping stdout back into a Leo via an @file
node is an example that really doesn't have any scripting component at all.

I think that having someplace for users to put @button/@command and
descriptions of workflow and other tools would be valuable for sparking new
ideas with other users. I am sure that everyone using Leo for some time
will accumulate quite a pile of useful tools that other users (like me)
could benefit from.

Chris

**Comment by maphew** [comment]
There's also https://github.com/leo-editor/snippets
