### ISSUE TITLE
Import Any File Failed For .txt File Import

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#1522]
Leo 6.2-b1-devel, devel branch, build 5da736ea4d
2020-02-29 06:19:36 -0600
Python 3.8.0, PyQt version 5.14.0
Windows 10 AMD64 (build 10.0.18362) SP0

I tried to import two different text files using Files/Import Files/Import Any File.  The result was that no new node was created.  One of the files was about 15 MB long, and Leo thought about it for a long time (showing the "Wait" cursor).  The other was only about a KB in size.

No error message was displayed in the Log pane.

**Comment by edreamleo** [comment]
Fixed in devel. As always, the import logic special cases files that have Leo sentinels. Otherwise, the code now uses new code that creates a single `@edit` for the entire file.
