### ISSUE TITLE
bundled npyscreen is out of date

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#1525]
spawned from #1512 
~~~
/usr/lib64/python3.8/site-packages/leo/external/npyscreen/npyspmfuncs.py:37: SyntaxWarning: "is not" with a literal. Did you mean "!="?
if rtn is not 0: return False
byte-compiling /tmp/SBo/package-leo/usr/lib64/python3.8/site-packages/leo/external/npyscreen/npyssafewrapper.py to npyssafewrapper.cpython-38.pyc
byte-compiling /tmp/SBo/package-leo/usr/lib64/python3.8/site-packages/leo/external/npyscreen/proto_fm_screen_area.py to proto_fm_screen_area.cpython-38.pyc
/usr/lib64/python3.8/site-packages/leo/external/npyscreen/proto_fm_screen_area.py:171: SyntaxWarning: "is" with a literal. Did you mean "=="?
self.show_from_y is 0 and
/usr/lib64/python3.8/site-packages/leo/external/npyscreen/proto_fm_screen_area.py:172: SyntaxWarning: "is" with a literal. Did you mean "=="?
self.show_from_x is 0 and
~~~

**Comment by maphew** [comment]
I assigned myself as this started as being distribution related, however I don't have any idea at present why we bundle npyscreen or if this is still necessary. (My preference is to avoid bundling.)

**Comment by edreamleo** [comment]
@maphew We "bundle" npyscreen because I patched some of its code.

The cursesGui2 plugin contains: `import leo.external.npyscreen as npyscreen` rather than importing npyscreen itself.

Imo, this should not change. Please see if you can disable the warning. Thanks.

**Comment by brobr** [comment]
Sorry to but in, but the deprecation warnings about  using `==` instead of `is` also popped up when compiling/installing other python-software. 

I noticed this after the upgrade to python 3.8 on my box, so could just indicate that usage of `is` in the flagged source-code lines will not be tolerated in a future python release. Changing the `is` to `==` would disable the warning, I guess.

**Comment by edreamleo** [comment]
Rev 3fae157 in devel fixes the three lines involved, with comments referring to this issue.

I am going to close this issue.
