### ISSUE TITLE
Leo acts on some operator input when the Leo window is NOT the top window

### ISSUE THREAD

**Issue by SegundoBob** [leo-editor/leo-editor#153]
This problem is discussed in the Leo-Editor forum thread:
```
https://groups.google.com/forum/?fromgroups#!topic/leo-editor/3PPObn4JRik
```
I can't reliably reproduce this problem, so I can't give you a test case that demonstrates it.

The symptom that I first noticed was unexpected, unpredictable changes in what the tree pane showed when I switched back to Leo-Editor after switching away from Leo-Editor by executing open-url.

Sometimes the node selected was unchanged, but it had been scrolled up in the tree pane; and sometimes it had been scrolled all the way out of the tree pane.

Sometimes the node selected had been changed to a sibling node after the node that was selected when I switched away from Leo-Editor.

In all cases, the body pane correctly showed the contents of the currently selected node.

Sometimes an Alt-F4 when a non-Leo-Editor window is the only window showing, causes Leo-Editor to exit or display its "Save changes before exit?" query.

Edward K. Ream currently believes:  "The culprit is likely a delayed action (on the order of 0.5 sec) that Leo takes on focus-in events. If the user responds to a focus-in event before that time there will be problems."

My test system:
```
Xubuntu32 12.04
Python 2.7.3, PyQt version 4.8.1
```
The problem has been observed on Leo-Editor commit f6cdb2bccb1a7ca8812f49f0da951cec5617279f.  It seems to occur slightly more frequently on more recent commits such as 42a5207833e08ff37e767d60e1020f6151b3a70b.

**Comment by edreamleo** [comment]
I am going to close this.  It does not seem to be a major problem, and it may have been fixed by 8b02e2d.

Please reopen if you are sure that the problem remains
