### ISSUE TITLE
6.3 Body right click mouse pop up outline context menu

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#1531]
Leo 6.3-devel, devel branch, build cf46ae40b7
2020-03-13 08:28:45 -0500
Python 3.7.3, PyQt version 5.12.3
darwin

**EKR**: [This post](https://groups.google.com/d/msg/leo-editor/29AOIWP0P38/Ge8fS3NtBAAJ) describes the situation, and proposed fixes.

[Original screen shot](https://user-images.githubusercontent.com/2628013/76670300-c1f3c900-65ca-11ea-8c55-a776520930d7.png)

**Comment by edreamleo** [comment]
On Fri, Mar 13, 2020 at 7:08 PM wangzhaohe <notifications@github.com> wrote:

> Leo 6.3-devel, devel branch, build cf46ae4
> <https://github.com/leo-editor/leo-editor/commit/cf46ae40b7612d374c411de02fc92749abdb4d83>
> 2020-03-13 08:28:45 -0500
> Python 3.7.3, PyQt version 5.12.3
> darwin
>
I'm not sure what the problem is. Everything seems to work as expected.
Are you saying that Leo inserts the text shown in pink?

Edward

**Comment by edreamleo** [comment]
On Sat, Mar 14, 2020 at 6:48 AM Edward K. Ream <edreamleo@gmail.com> wrote:

>
> I'm not sure what the problem is. Everything seems to work as expected.
> Are you saying that Leo inserts the text shown in pink?
>

What plugins do you have enabled?

Edward

**Comment by wangzhaohe** [comment]
leo.plugins.plugins_menu    leoSettings.leo
leo.plugins.free_layout     leoSettings.leo
leo.plugins.contextmenu     leoSettings.leo
leo.plugins.leo_to_html     leoSettings.leo
leo.plugins.mod_scripting   leoSettings.leo
leo.plugins.nav_qt          leoSettings.leo
leo.plugins.nodetags        leoSettings.leo
leo.plugins.quicksearch     leoSettings.leo
leo.plugins.screen_capture  leoSettings.leo
leo.plugins.settings_finder leoSettings.leo
leo.plugins.stickynotes     leoSettings.leo
leo.plugins.todo            leoSettings.leo
leo.plugins.viewrendered    leoSettings.leo

**Comment by edreamleo** [comment]
The screen shot you show is what is intended. Yes, the popup shows *tree* operations. That is intended.

**Comment by wangzhaohe** [comment]
Then Edit in body panel will be only operated by Ctrl+C or Ctrl+X.

The following image is the old operation:

![image](https://user-images.githubusercontent.com/2628013/76692972-21200f00-6699-11ea-9dcd-afb043010ea0.png)

**Comment by edreamleo** [comment]
On Sat, Mar 14, 2020 at 7:46 PM wangzhaohe <notifications@github.com> wrote:

> Then Edit in body panel will be only operated by Ctrl+C or Ctrl+X.
>
Yes. It would be possible to add new entries to the popup menu created by
contextmenu.py.

Edward

**Comment by maphew** [comment]
I'm seeing this too. The r-click context menu when the click location is *within the body pane* is showing Tree operations instead of showing Body context operations.

**Comment by maphew** [comment]
Show-plugins-info:

leo.plugins.plugins_menu    myLeoSettings.leo
leo.plugins.free_layout     myLeoSettings.leo
leo.plugins.contextmenu     myLeoSettings.leo
leo.plugins.leo_to_html     myLeoSettings.leo
leo.plugins.livecode        myLeoSettings.leo
leo.plugins.nav_qt          myLeoSettings.leo
leo.plugins.mod_scripting   myLeoSettings.leo
leo.plugins.nodetags        myLeoSettings.leo
leo.plugins.quicksearch     myLeoSettings.leo
leo.plugins.screen_capture  myLeoSettings.leo
leo.plugins.settings_finder myLeoSettings.leo
leo.plugins.stickynotes     myLeoSettings.leo
leo.plugins.todo            myLeoSettings.leo
leo.plugins.viewrendered    myLeoSettings.leo
leo.plugins.history_tracer  myLeoSettings.leo
leo.plugins.active_path     myLeoSettings.leo

**Comment by maphew** [comment]
Here's a screenshot showing expected behaviour of Body context menu, from Leo v6.1:

![Screenshot_2020-03-22_11-06-50](https://user-images.githubusercontent.com/486200/77256777-7d50d900-6c2d-11ea-8277-dbfa8f292238.png)

**Comment by maphew** [comment]
and screenshot in 6.3 devel body-context-click is showing Tree context menu:

![Screenshot_2020-03-22_11-15-52](https://user-images.githubusercontent.com/486200/77256995-d2d9b580-6c2e-11ea-899a-3d8be8f4a479.png)

Console log:
~~~
(leo-dev) matt@dell-xps ~/code/leo-editor $ leo

setting leoID from os.getenv('USER'): 'matt'
QApplication: invalid style override passed, ignoring it.
    Available styles: Windows, Fusion
Leo 6.3-devel, devel branch, build 674edd2027
2020-03-20 10:53:31 -0500
registerCommand redefining history <function ScriptingController.registerAllCommands.<locals>.registerAllCommandsCallback at 0x7f4520935e18> -> <function install_qt_quicksearch_tab.<locals>.nodehistory at 0x7f450dfb4d90>
don't forget to launch leo-ver-serv!!!
QXcbClipboard: SelectionRequest too old
~~~

**Comment by edreamleo** [comment]
My memory is playing tricks on me. I remember (I think) changing this recently in the contextmenu plugin. However, I do not see any relevant diffs.

Looking in Leo's core, I see a reference to g.tree_popup_handlers in qt_gui.onContextMenu. Again, I don't see any relevant diffs.

I suspect I did something simple, and hard to find.

**Comment by vitalije** [comment]
@edreamleo I see where the problem is. In the method `qt_gui.onContextMenu` there is a comment mark refering the issue #1286.
Inside this method handlers for popup menu are `g.tree_popup_handlers`, regardless of which widget has requested context menu.

**Comment by vitalije** [comment]
I don't see anywhere `body_popup_handlers`, perhaps there were never body handlers. Maybe just letting the `QTextWidget` to show its own context menu will solve the issue?

**Comment by edreamleo** [comment]
@vitalije Mystery solved. @data contextmenu-commands in leoSettings.leo contains default additional menu items. Perhaps that @data setting changed.

The setting was hard to find because the docstring for configuredcommands_rclick in contextmenu.py is misleading. I am going to play with this for awhile...

**Comment by vitalije** [comment]
I have just do `git bisect` and found that the commit responsible is a781a0335388

**Comment by edreamleo** [comment]
@vitalije Thanks!

**Comment by edreamleo** [comment]
@vitalije Imo, the popup should contain a mixture of both outline and text operations, and they should be configurable with `@data contextmenu-commands. The name g.tree_popup_handlers probably should be changed to g.pop_handlers...

**Comment by vitalije** [comment]
Perhaps if a widget is qtb then it should show first handlers related to body editing, followed by the handlers for tree operations, and when the widget is tree to show first tree handlers and than body handlers.

**Comment by edreamleo** [comment]
@vitalije Reasonable. Maybe the `data` setting should create everything, or almost everything.

Let me sleep on this. It's the middle of the night here. Good chatting with you :-)

**Comment by vitalije** [comment]
For example in `qt_gui.onContextMenu`:

```
if w.objectName() == 'treeWidget':
    handlers = g.tree_popup_handlers + g.body_popup_handlers
else:
    handlers = g.body_popup_handlers + g.tree_popup_handlers
...
```

**Comment by vitalije** [comment]
@edreamleo deleting the two lines in:
```
LeoPy.leo#Code-->Qt gui-->@file ../plugins/qt_text.py-->class LeoQTextBrowser (QtWidgets.QTextBrowser)--> lqtb.ctor
```
will do the trick. It would restore context menu as it used to be until the recent change.
The two lines are:
```python
self.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
self.customContextMenuRequested.connect(self.onContextMenu)
```

**Comment by edreamleo** [comment]
Recent revs in the devel and 6.2 branches complete this project.

**Comment by edreamleo** [comment]
On Tue, Mar 24, 2020 at 10:57 AM Виталије Милошевић <
notifications@github.com> wrote:

> @edreamleo <https://github.com/edreamleo> deleting the two lines in:
>
> LeoPy.leo#Code-->Qt gui-->@file ../plugins/qt_text.py-->class LeoQTextBrowser (QtWidgets.QTextBrowser)--> lqtb.ctor
>
> will do the trick. It would restore context menu as it used to be until
> the recent change.
> The two lines are:
>
> self.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)self.customContextMenuRequested.connect(self.onContextMenu)
>
>
Thanks for this. It clears up a nagging mystery.

I have just closed this issue. The new code is much more flexible than
before, and the defaults are more useful. They now include undo/redo.

Edward
