### ISSUE TITLE
Stand-alone distro for leoAst.py

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#1532]
Non-Leo users should be able to use this code fairly easily.

- [x] Document the code in LeoDocs.leo and on the web.
- [x] Make leoAst.py stand-alone by support command-line arguments.
    See python leoAst.py -h for the present args.
- [x] Announce the project. This has been delegated to #1565.

There is no need for a separate package. An announcement should suffice.

**Comment by maphew** [comment]
Re: packaging: The structure of https://github.com/leo-editor/ast-token-tools is approximately correct but I've run into difficulty cleanly importing the commit history. It's okay for the first import but attempting to merge or import subsequent development yields disconnected branches and/or dulpicate commits with different IDs. There's probably a way to do this using git magic but I don't know it. Does anyone else?

This has me pondering the leo plugin ecosystem in general, for which I'm about to open a discussion thread.

**Comment by edreamleo** [comment]
I am going to close this issue.

@maphew Matt, there is nothing more you need to do.

**Comment by maphew** [comment]
ok, I will delete the ast-token-tools repository. No point in having it around and possibly generating confusion

**Comment by edreamleo** [comment]
On Wed, Jul 22, 2020 at 3:08 PM matt wilkie <notifications@github.com>
wrote:

> ok, I will delete the ast-token-tools repository. No point in having it
> around and possibly generating confusion
>
Thanks. I am going to announce the tool this week.

Edward
