### ISSUE TITLE
V6.3 Data Lost with @file and @@file

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#1534]
2020-03-13 08:28:45 -0500
Python 3.7.3, PyQt version 5.12.3
darwin

I use Leo as a version control function when learning and developing codes. I found data losts when reopen Leo several times. Is the reason about @file or @@file?

<img width="1692" alt="datalost" src="https://user-images.githubusercontent.com/2628013/76693231-a8bb4d00-669c-11ea-9d51-db897ab05569.png">

**Comment by wangzhaohe** [comment]
Now I can not recover my data easily in Leo-editor. But thanks for files in disks are not changed.

**Comment by edreamleo** [comment]
On Sat, Mar 14, 2020 at 8:16 PM wangzhaohe <notifications@github.com> wrote:

> 2020-03-13 08:28:45 -0500
> Python 3.7.3, PyQt version 5.12.3
> darwin
>
> I use Leo as a version control function when learning and developing
> codes. I found data lists when reopen Leo several times. Is the reason
> about @file <https://github.com/file> or @@file <https://github.com/file>?
>

Yes. This is *your* problem. You are creating two copies of the same data.
When you change *any* node to an @file node, you will be replacing the
file's contents with the new @file node. Leo probably warned you that the
file already existed.

The general principle is that's dangerous to have two copies of the same
data. Sometimes there are reasons for doing so, but you have to be careful.
Managing your data with git or other SCCS should suffice to recover data.

Edward

**Comment by wangzhaohe** [comment]
Yes, I have a Subversion in developement ubuntu1804 server.

I use @@file to distinguish @file. And it seems work well before. But since yesterday, I lost data.

I think you did not understand what I meant. The problem is not to overwrite an existent file.

Thanks for your reply quickly.

**Comment by edreamleo** [comment]
On Sun, Mar 15, 2020 at 5:35 AM wangzhaohe <notifications@github.com> wrote:

> Yes, I have a Subversion in development ubuntu1804 server.
>
That's good, because I have no way of knowing what happened.

Edward

**Comment by maphew** [comment]
@wangzhaohe from looking at your screenshot I think you were:

- using `@file settings.py` for _currently active or live_ code that you are editing and want saved to external files on disk
- using `@@file settings.py` for _old versions_ of code that you are keeping for reference and **do not want saved to disk**

is my understanding correct?

In other words you expect double-at-symbol, `@@`, to disable the at-command?

And that the issue you are attempting to report here and #1535 is that this disable trick used to work, but in v6.3 it doesn't anymore?

**Comment by edreamleo** [comment]
@maphew I agree that your summary might be accurate, but Leo *does* distinguish between `@file` and `@@file`. Absent any other data, I see no way for me to make progress.

**Comment by wangzhaohe** [comment]
> @wangzhaohe from looking at your screenshot I think you were:
> 
> * using `@file settings.py` for _currently active or live_ code that you are editing and want saved to external files on disk
> * using `@@file settings.py` for _old versions_ of code that you are keeping for reference and **do not want saved to disk**
> 
> is my understanding correct?
> 
> In other words you expect double-at-symbol, `@@`, to disable the at-command?
> 
> And that the issue you are attempting to report here and #1535 is that this disable trick used to work, but in v6.3 it doesn't anymore?

Yes, your understanding is my thought.

Yes , it used to work for somedays. The data in disk file is not changed, only display not correct in Leo-editor or refresh-from-disk command not working correctly. I plan to review the Leo source code to discover the problem after my project being finished.

Thanks for reply.

**Comment by wangzhaohe** [comment]
And now I wrote a command `@button swot` to replace *@@file* with *@@swot*.

It can works now without *@file* and *@@file* in one outline together.

    for node in p.children():

        if "@@swot" in node.h:
            node.h = node.h.replace("@@swot", "@file")

        elif "@file" in node.h:
            node.h = node.h.replace("@file", "@@swot")

        elif "@file" not in node.h:
            node.h = "@file " + node.h

This is  a temporary solution for me.

**Comment by edreamleo** [comment]
@wangzhaohe Thanks for your report. Glad you are making progress.
