### ISSUE TITLE
v6.3 Lost 3 lines of @file node

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#1535]
2020-03-13 08:28:45 -0500
Python 3.7.3, PyQt version 5.12.3
darwin

<img width="1035" alt="lost3lines" src="https://user-images.githubusercontent.com/2628013/76693647-adcfca80-66a3-11ea-84ee-edc0612ec5d1.png">

vim urls.py --- souce file

    #! /usr/bin/env python
    # -*- coding: utf-8 -*-
    #@+leo-ver=5-thin
    #@+node:swot.20200312084526.9: * @file rest/urls.py
    #@@first
    #@@first
    #@@language python
    #@@tabwidth -4
    #@+others
    #@+node:swot.20200312084526.10: ** import
    from django.contrib import admin
    from django.urls import path, include

Now only two lines in Leo-editor:

    #! /usr/bin/env python
    # -*- coding: utf-8 -*-

**Comment by wangzhaohe** [comment]
I think I found the reason:

@file call/urls.py `refresh from disk` run well after DELETED all @@file call/urls.py nodes.

    (traffic) ➜  traffic grep call/urls.py traffic.leo.20200315
    <v t="swot.20200227204341.1"><vh>@@file call/urls.py</vh>
    <v t="swot.20200303104036.91"><vh>@@file call/urls.py</vh>
    <v t="swot.20200313095119.1"><vh>@@file call/urls.py</vh>
    <v t="swot.20200312084526.114"><vh>@@file call/urls.py</vh>
    <v t="swot.20200313081913.117"><vh>@file call/urls.py</vh></v>

There are no same nodes. Does the source code not distinguish @file&&@@file ???

**Comment by wangzhaohe** [comment]
And I find that all will be ok, if there is no @file samename.py because the disk file will not be analysed.

**Comment by wangzhaohe** [comment]
The reason which I copy so many same @@file samename.py nodes in outline is that I can change to each Django version to run when I show the code to students step by step. Only need change @@file to @file.

It likes a version control system, but I can change each version content without commit it(committing will produce a new version number)

Now it seems that I should not use @@file, and I will use another string instead.

**Comment by edreamleo** [comment]
On Sun, Mar 15, 2020 at 7:34 AM wangzhaohe <notifications@github.com> wrote:

> And I find that all will be ok, if there is no @file
> <https://github.com/file> samename.py because the disk file will not be
> analysed.
>
Glad you found the problem. Do you think this could be a bug in Leo? If so,
please file a report.

Edward

**Comment by wangzhaohe** [comment]
> Glad you found the problem. Do you think this could be a bug in Leo? If so, please file a report. Edward

Yes, I think so. I will try to learn the `refresh from disk` command in leo-editor source code.

And I just don't know how to file a report, let me learn the source code first.

**Comment by edreamleo** [comment]
On Sun, Mar 15, 2020 at 9:22 PM wangzhaohe <notifications@github.com> wrote:

> Glad you found the problem. Do you think this could be a bug in Leo? If
> so, please file a report. Edward
>
> Yes, I think so. I will try to learn the refresh from disk command in
> leo-editor source code.
>
> And I just don't know how to file a report, let me learn the source code
> first.
>
Good. There is no rush.

Edward

**Comment by edreamleo** [comment]
I am going to close this report. It's likely a user error.
