### ISSUE TITLE
Using @bool tree-declutter = True puts a lot of noise in the .leo files

### ISSUE THREAD

**Issue by vitalije** [leo-editor/leo-editor#1536]
It is obvious that Edward doesn't use tree decluttering features. I have found that a lot of declutter functionality has been disabled lately. That creates a huge diffs in the .leo files. The way it used to work was like this:
1. when drawing the nodes, declutter code finds nodes whose headlines match declutter_patterns and adds appropriate icons, shortens the headline displayed etc. To achieve this it adds unknownAttributes to matched nodes.
2. before save command, this code removes all icons which were added by the decluttering code and if the remaining unknownAttributes are an empty dict, deletes it. It also sets declutter_update to True.
3. during idle time, this code checks if the declutter_update is True and if so, it redraws tree, which means it adds icons again to the unknownAttriubtes.

It is easy to just remove disabling code and restore previous functionality, but I am thinking it may be better to store decluttering icons somewhere else not in unknownAttributes. That way it would not require this clean-before-save/restore-later cycle.

For example it could be stored in the tree.declutter_icons_dict which can map v-nodes to their computed declutter icons.

**Comment by edreamleo** [comment]
@vitalije Good catch.

**Comment by vitalije** [comment]
@edreamleo I suspect you didn't fully understand this issue because you labeled it to 6.3.

You have disabled some calls in the `qtree.__init__` method:

```python
self.declutter_patterns = None  # list of pairs of patterns for decluttering
self.declutter_update = False  # true when update on idle needed
if 0:  # EKR: This looks like a bad idea.
    g.registerHandler('save1', self.clear_visual_icons)
    g.registerHandler('headkey2', self.update_appearance)
    g.registerHandler('idle', self.update_appearance_idle)
```
This might seem to you as bad idea but with this few lines disabled every user
who has `@boll tree-declutter=True` in settings, saves each Leo file with a lot
of noise in the form of `descendantUnknownAttributes='.....long ascii str'`.

I think that for now it would be enough just to enable those calls, and later in 6.3 work on refactoring this machinery.

**Comment by edreamleo** [comment]
@vitalije Thanks for this advice. I have re-enabled the code for now.

Your suggestion is part of the 6.2 and devel branches.
