### ISSUE TITLE
viewrendered is dead, long live viewrendered...

### ISSUE THREAD

**Issue by tbnorth** [leo-editor/leo-editor#154]
viewrendered.py and viewrendered2.py should be merged so that only one remains. viewrendered2.py adds some useful functionality which should be kept. First step might be defining exactly the required behavior, which is perhaps simply that using viewrendered2.py should be no different from using viewrendered.py except for the additional functionality.

I'm going to create a new label for this, "cleanup", seeing it isn't really anything else.

There's no specific urgency for this.

**Comment by edreamleo** [comment]
Careful.  vr2 may not be a superset of vr.  For experimentation, I would suggest a vr3 plugin.

**Comment by tbnorth** [comment]
Note: Make sure #96 is not resurrected.

**Comment by edreamleo** [comment]
Recent work with VR3 closes this item.
