### ISSUE TITLE
viewrendered3 'NoneType' object has no attribute 'QWebView'

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#1542]
I have enabled viewrendered3.py plugin but running vr I get this message:

Leo Log Window
Leo 6.3-devel, devel branch, build 643bfd7a20
2020-03-19 10:50:41 -0500
Python 3.8.2, PyQt version 5.14.0
Windows 10 AMD64 (build 10.0.18362) SP0
current dir: N:/git/leo-editor
load dir: N:/git/leo-editor/leo/core
global config dir: N:/git/leo-editor/leo/config
home dir: C:/Users/lewis
reading settings in N:/git/leo-editor/leo/config/leoSettings.leo
reading settings in C:/Users/lewis/.leo/myLeoSettings.leo
Empty setting name in False
reading settings in C:/Users/lewis/.leo/LeoGraySolarized.leo
Traceback (most recent call last):

  File "N:\git\leo-editor\leo\core\leoPlugins.py", line 515, in loadOnePluginHelper
__import__(moduleName)

  File "N:\git\leo-editor\leo\plugins\viewrendered3.py", line 357, in <module>
QWebView = QtWebKitWidgets.QWebView

AttributeError: 'NoneType' object has no attribute 'QWebView'

**Comment by edreamleo** [comment]
Fixed in 6.2 and devel branches.
