### ISSUE TITLE
toggle-split-direction can not run from menu

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#1544]
Leo Log Window
Leo 6.3-devel, devel branch, build 674edd2027
2020-03-20 10:53:31 -0500
Python 3.7.3, PyQt version 5.12.3
darwin

It can run from command but not from menu.

<img width="233" alt="image" src="https://user-images.githubusercontent.com/2628013/77231273-d5a7bc80-6bd4-11ea-9ec8-f9a9a36e951d.png">

**Comment by edreamleo** [comment]
This command only works with Leo's legacy gui. It does not work when using Qt docks.

**Comment by wangzhaohe** [comment]
It still can not work with Leo's legacy gui.

**Comment by edreamleo** [comment]
On Sat, Mar 21, 2020 at 8:02 PM wangzhaohe <notifications@github.com> wrote:

> It still can not work with Leo's legacy gui.
>
I'll investigate on the Mac.

Edward

**Comment by edreamleo** [comment]
It works for me on MacOS with the latest code in the 6.2 branch.
