### ISSUE TITLE
Declutter should be simplified

### ISSUE THREAD

**Issue by vitalije** [leo-editor/leo-editor#1545]
In the current implementation declutter code stores its temporary data in the p.u dict.
Before saving the outline, those temporary data must be cleaned to prevent writing them in the output file. Then it needs to be recreated again.

There is really no need for this temporary data to be stored in p.u when it might be stored in simple instance field for example: `self.nodeIconsDict`.

I will work on this in the new branch simplify-declutter

**Comment by edreamleo** [comment]
On Fri, Mar 27, 2020 at 5:37 AM Виталије Милошевић <notifications@github.com>
wrote:

> In the current implementation declutter code stores its temporary data in
> the p.u dict.
> Before saving the outline, those temporary data must be cleaned to prevent
> writing them in the output file. Then it needs to be recreated again.
>
> There is really no need for this temporary data to be stored in p.u when
> it might be stored in simple instance field for example:
> self.nodeIconsDict.
>
> I will work on this in the new branch simplify-declutter
>
Thank you for working on this. It's been off my radar.

Edward

**Comment by vitalije** [comment]
@edreamleo, I believe 2b0051555cf0f0bd108bda78adae15bd24493572 is ready to be merged in the devel branch if you don't mind.

**Comment by edreamleo** [comment]
@vitalije Done at 0eefa64 in devel.
