### ISSUE TITLE
Canonical download Leo link?

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#1550]
Readme.md says:
- Download - http://sourceforge.net/projects/leo/files/, but the files there are ancient, v5.8 circa 2018.
- leoeditor.com - Front page links to http://leoeditor.com/download.html which mentions v5.7 as new, plus a few other things that could be freshened.

I suggest:

- [x] the canonical url used in Readme, website, and elsewhere be [leoeditor.com/download.html](https://leoeditor.com/download.html) 
    - [x] Already correct on Leo's home page.
    - [x] EKR: Fixed README.md in leoDist.leo, *with* the .html extension in the link itself.

- [x] that url redirect to https://github.com/leo-editor/leo-editor/releases for now. It can be redirected elsewhere in future as needed.

- [x] Readme be updated with the short pip install recipe [as per @btheado](https://groups.google.com/d/msg/leo-editor/-2GmAzq3Z4k/R-60VCDcBgAJ), with link to docs for fuller explanation.

>     Install python3
>     if not using git:
>         pip install leo
>     If using git:
>         git clone ....
>         pip install --editable leo-editor

- ~~The _nightly snapshots_ info of the current download page be moved into the docs somewhere and the page removed (with _301 moved permanently_ redirect).~~ _reconsidered._

I'm willing to do the work.

**Comment by edreamleo** [comment]
On Sun, Mar 29, 2020 at 10:34 PM matt wilkie <notifications@github.com>
wrote:

> I'm willing to do the work.
>
Please do.  In both 6.2 and devel.

Let me know when you are finished. I'll then start afresh on the
distribution checklist and release 6.2.1.

Edward

**Comment by maphew** [comment]
working in mhw-dnld-pages branch. 

I won't be able to do the first one, putting in a 301 redirect as that needs to happen on the web-host, which means @edreamleo or @technatica I think.

**Comment by edreamleo** [comment]
On Tue, Mar 31, 2020 at 10:35 AM matt wilkie <notifications@github.com>
wrote:

> working in mhw-dnld-pages branch.
>
> I won't be able to do the first one, putting in a 301 redirect as that
> needs to happen on the web-host, which means @edreamleo
> <https://github.com/edreamleo> or @technatica
> <https://github.com/technatica> I think.
>
I've just assigned this to 6.3.

Edward

**Comment by edreamleo** [comment]
@maphew I have just fixed the link in README.md. I like the web pages the way they are. However, I don't mind you adding the pip install script.

**Comment by maphew** [comment]
I'm ok with that. Removing the .html extension idea was coming from a webmaster's style guide sense of what's idiomatic, a pep8-ism if you will. (Makes it easier when migrating to different CMS for example. One ends in .html, a 2nd .php, the other in .do. None of which actually applies here.)

I've also changed my mind about moving the snapshots section. That doesn't make any sense, "downloads" is where a person goes when looking for such a thing. 

This can be closed as far as I'm concerned.

**Comment by edreamleo** [comment]
@maphew Thanks for your comments.
