### ISSUE TITLE
mark command can not work after b68685abee3466bf1ad0f29efa48dea8996d39fd

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#1553]
Leo Log Window
Leo 6.2.1 final, devel branch, build 49c5e4fa3c
2020-03-30 08:39:10 -0500
Python 3.7.3, PyQt version 5.12.3
darwin

**Comment by vitalije** [comment]
@wangzhaohe Can you give some more details here. What do you mean that mark command does not work? It works for me both on the latest ced8b2ec53ce69f81f33da875dad931e43a9a655 and on yours 49c5e4fa3cd617524f167e2e114f89d76549bbda version.

**Comment by wangzhaohe** [comment]
mark command can work now. I still don't know the reason.

Thanks for your reply.
