### ISSUE TITLE
Headline icons doubled

### ISSUE THREAD

**Issue by largo84** [leo-editor/leo-editor#1559]
I suspect this is related to recent work on the declutter code. For the last several weeks (don't recall when it started) I've noticed that headline icons are now duplicated. I have the declutter option set to 'true' as I use a variety of declutter modes.

I can show screenshot if that's helpful. Environment:

`Leo 6.3-devel, devel branch, build 20358484cf`
`2020-04-02 06:07:57 -0500`
`Python 3.7.3, PyQt version 5.9.6`
`Windows 10 AMD64 (build 10.0.18362) SP0`

**Comment by vitalije** [comment]
@largo84 I don't see this. Can you share a small outline where you see it. And your `@data declutter-patterns` setting?

**Comment by vitalije** [comment]
I believe I fixed it in 269d953
@largo84 please confirm.

**Comment by largo84** [comment]
It's weird as I see the icon doubling in some places and not in others; even within the same outline. I will see if I can isolate the problem better today so I can share useful screenshots (will be later today). BTW, this after pulling the latest rev.
Rob...

**Comment by edreamleo** [comment]
@vitalije I may be wholly or partly responsible. At rev 7cc4157d8 in devel I changed getIcon to fix a pylint complaint.  Old code:
```python
p.v.iconVal = iv = p.v.computeIcon()
self.getCompositeIconImage(p, iv)
```
new code:
```python
p.v.iconVal = iv = p.v.computeIcon()
return self.getCompositeIconImage(p, iv)
```
Note that the rev also removed an "unnecessary" else clause, which is the new style. However, to be exactly equivalent to the old code the proper new code is:
```python
p.v.iconVal = iv = p.v.computeIcon()
self.getCompositeIconImage(p, iv)
return None
```
The improper change was an exceptionally stupid thing for me to do.

**Comment by edreamleo** [comment]
Rev 8869b3c changes getIcon as described above.

**Comment by edreamleo** [comment]
On Fri, Apr 3, 2020 at 7:53 AM Rob Keeney <notifications@github.com> wrote:

> It's weird as I see the icon doubling in some places and not in others;
> even within the same outline. I will see if I can isolate the problem
> better today so I can share useful screenshots (will be later today). BTW,
> this after pulling the latest rev.
>
I've just made some changes as described in #1559
<https://github.com/leo-editor/leo-editor/issues/1559>. Let me know if they
improve matters.

Edward

**Comment by largo84** [comment]
Still seeing it. So far I...
1. Deleted the cache.sqlite file in g_app_db and restarted (didn't help).
2. Disabled @bool tree-declutter, then re-enabled (didn't help).

What's odd is that the icon doubling appears in some outlines and not in others (none of which include custom settings).

![2020 0402 Leo Icons](https://user-images.githubusercontent.com/9388145/78369233-dc4e1080-7592-11ea-8dab-d1b8fb9b1e72.png)

**Comment by vitalije** [comment]
@edreamleo, you were right to add return statement. In 3fc8e336edc8, I've added it again.

@largo84 what plugins do you use?

How does this happen? Is it when you open outline that the icons are doubled or is it after some action you perform? What was your last action when you noticed doubled icons?

Also it would be helpful if you would create a button with the following code:
```python
g.es(c.editCommands.getIconList(p))
g.es(c.frame.tree.nodeIconsDict.get(p.gnx))
g.es(c.frame.tree.declutter_data.get((p.h, p.v.computeIcon())))
```
and then select any doubled icon node and click this button. Resulting output would tell us where does the doubled icon come from.

**Comment by largo84** [comment]
I created the @button in two different outlines; one which shows icon doubles, the other not. From the former I get this output from the button:

`[{'type': 'file', 'file': 'D:/Synced/github repos/leo/leo/Icons/Tango/16x16/actions/stop.png', 'relPath': 'Tango/16x16/actions/stop.png', 'where': 'beforeHeadline', 'yoffset': 0, 'xoffset': 2, 'xpad': 1, 'on': 'VNode', 'visualIcon': '1'}]
['box00.png', 'D:/Synced/github repos/leo/leo/Icons/Tango/16x16/actions/stop.png', 'Tango/16x16/actions/stop.png']
('**Hot**', ['Tango/16x16/actions/stop.png'])`

From the latter I get this output:

`[]

['box00.png', 'Tango/16x16/actions/stop.png']
('**Hot**', ['Tango/16x16/actions/stop.png'])`

Not sure what to make of it and why it would be different in two different outlines. HTH

Rob...

**Comment by edreamleo** [comment]
On Fri, Apr 3, 2020 at 10:28 AM Виталије Милошевић <notifications@github.com>
wrote:

> @edreamleo <https://github.com/edreamleo>, you were right to add return
> statement. In 3fc8e33
> <https://github.com/leo-editor/leo-editor/commit/3fc8e336edc88e4a34bab126ad1ce41280e1fabd>,
> I've added it again.
>
Ok. I'll leave this issue to you.

Edward

**Comment by vitalije** [comment]
There are two cached list of icons. One is list of icons produced by decluttering node according to your declutter patterns. This list depends only on p.h. The other list of icons comes from p.v.u['icons']. This part depends on the commands from the outline menu: Insert Icon, Delete First Icon, Delete Icons, ...

The second list is persistent, it is saved when you save your file. From the output you provided it is clear that in the doubled icon outline the node contains `stop.png` icon in both lists. One comes from the loaded outline and the other comes from decluttering your node. That is the reason it shows two icons. 

How did this happened? Recently Edward disabled some part of decluttering code in the qt_tree. He didn't use decluttering features, so he hasn't noticed that Leo started to save those decluttering icons in the output file. The disabled code was looking wrong and unnecessary. Later this part of code was enabled again. However, the outlines you saved using the version of Leo between these two events contain the list of decluttered icons. The solution is to execute the following script:
```python
for p in c.all_positions():
    ilist = [x for x in c.editCommands.getIconList(p) if not x.get('visualIcon')]
    c.editCommands.setIconList(p, ilist)
c.save()
```
This will clean your outline from the old declutter icons.

@largo84 please report if this solves your problem.

**Comment by largo84** [comment]
Yes, that worked, and thanks for the explanation and the script!
Rob...

**Comment by vitalije** [comment]
I'm glad it worked.
