### ISSUE TITLE
Leo 6.3-devel auto dehoist when insert-node/insert-child/paste-node

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#1560]
Run hoist command then (insert-node/insert-child/paste-node), Immediately it auto `dehoist`.

Leo Log Window
Leo 6.3-devel, devel branch, build 20358484cf
2020-04-02 06:07:57 -0500
Python 3.7.3, PyQt version 5.12.3
darwin

**Comment by vitalije** [comment]
It seems that I'm responsible for this. My commit with "improved c.positionExists" causes this bug. I'll look at it immediately.

**Comment by vitalije** [comment]
Fixed at 7679e544400d599ddcd37f0b7b21c5b107755ac2.

Method c.positionExists had one extra dot.
```python
len(rstack) > len(p.stack)
```
...instead of...
```python
len(rstack) > len(pstack)
```

**Comment by wangzhaohe** [comment]
> Fixed at [7679e54](https://github.com/leo-editor/leo-editor/commit/7679e544400d599ddcd37f0b7b21c5b107755ac2).
> 
> Method c.positionExists had one extra dot.
> 
> ```python
> len(rstack) > len(p.stack)
> ```
> 
> ...instead of...
> 
> ```python
> len(rstack) > len(pstack)
> ```

Tested. It run well now. Thanks for your commit.
