### ISSUE TITLE
--ipython option doesn't show ipython's qt console

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#1561]
See [this thread](https://groups.google.com/forum/#!topic/leo-editor/Ag56FjI-cB0).

**Comment by LewisNeal** [comment]
launchleo.py --ipython
is working again with ipython version 7.14.0, and QtConsole version 4.7.4
and the Jupyter QtConsole appears.

_Leo Log Window
Leo 6.3-devel, devel branch, build e7f2e02cc6
2020-05-18 06:55:35 -0500
Python 3.8.2, PyQt version 5.14.2
Windows 10 AMD64 (build 10.0.18362) SP0_

Lewis

**Comment by edreamleo** [comment]
@LewisNeal Thanks for this update! I'll close this issue when I confirm the fix at my end.

**Comment by edreamleo** [comment]
I confirm that everything works as expected after the following:
```
pip install --upgrade ipython
pip install --upgrade qtconsole
```

**Comment by edreamleo** [comment]
I am going to close this issue. Please reopen if upgrading to ipython 7.14.0 and qtconsole 4.7.4 does not work.
