### ISSUE TITLE
Could anyone teach me how to open leo-editor's debug  mode?

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#1562]
I want to collect enough message if something run error.

--listen-to-log

or

--trace-xxx ?

**Comment by edreamleo** [comment]
On Sat, Apr 4, 2020 at 4:07 AM wangzhaohe <notifications@github.com> wrote:

> I want to collect enough message if something run error.
>
I always run Leo in a console window
<http://leoeditor.com/running.html#running-leo-from-a-console-window>.  That
way I am sure to see messages that arise from python crashes. This is
simple, good, and highly recommended.

> --listen-to-log
>
This option is primarily for the console gui.

> --trace-xxx ?
>
These options print traces in the console window.

HTH.

Edward

**Comment by wangzhaohe** [comment]
Thanks for your reply! And is there a way to trace command when it runs error or has no response? Only Debug source code?

**Comment by edreamleo** [comment]
On Sat, Apr 4, 2020 at 10:04 AM wangzhaohe <notifications@github.com> wrote:

> Thanks for your reply!
>
You're welcome.

> And is there a way to trace command when it runs error or has no response?
> Only Debug source code?
>
There's no automatic way. What I do myself is insert g.trace statements.
They print to the console window.

Edward
