### ISSUE TITLE
Abbreviations may fail with non-English keyboards

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#1563]
See the ekr-abbrev branch and PR #1862.

From [this comment](https://groups.google.com/d/msg/leo-editor/s2gCfAhb97M/3NvaEefzCAAJ):

I'm running Leo 6.2.1 from the sources on a Windows 10 laptop and I have the same problem as Viktor: abbreviations don't work for me. In my case I'm using a Spanish keyboard. Cloning nodes with Ctrl+` fails too. When I change the keyboard layout to English everything works fine. Back to Spanish layout and abbreviations fail again. 

**Summary of the fixes**

The fix was to filter.doAltTweaks.
- Add `@bool use-german-keyboard = False`.
- Add `@bool use-spanish-keyboard = False`.

From https://en.m.wikipedia.org/wiki/German_keyboard_layout:
- The positions of the "Z" and "Y" keys are switched.
- Part of the keyboard is adapted to include umlauted vowels (ä, ö, ü) and the sharp s (ß).
- German keyboards change the right Alt key into an Alt Gr key to access a third level of key assignments.

Similar problems have been reported for Spanish keyboards. I am investigating. See:
https://en.wikipedia.org/wiki/QWERTY#Spanish

**United-States International keyboard**

[This post](https://answers.microsoft.com/en-us/windows/forum/all/us-international-keyboard-for-windows-10/f0dc89e9-2373-42af-bb2e-f50b8a69a13a) shows how to enable the US-international keyboard.

See also the following pictures from [this post](https://groups.google.com/g/leo-editor/c/QaiIbfq2cgM/m/CQ3ZlpLZAAAJ):

![image](https://user-images.githubusercontent.com/592928/114274271-3faf2180-99e3-11eb-9b44-8c23ceda6672.png)

**Comment by ranvik14** [comment]
@edreamleo : Is there anything that can be done from my side to support your analysis on this issue?

**Comment by edreamleo** [comment]
@ranvik14 Not at this time. I'll get to this soon.

**Comment by edreamleo** [comment]
I am going to close this issue. Please reopen as necessary.

**Comment by ranvik14** [comment]
@edreamleo : Please re-open this issue. I can't do it!

The details are documented here:

* https://groups.google.com/d/msg/leo-editor/6gvB2WUOW7Y/I3eTZ1rUAQAJ

**Comment by edreamleo** [comment]
On Mon, May 11, 2020 at 2:10 PM ranvik14 <notifications@github.com> wrote:

> @edreamleo <https://github.com/edreamleo> : Please re-open this issue. I
> can't do it!
>
Done.

Edward

**Comment by edreamleo** [comment]
I am reopening this issue because the proposed fix fails on Shift-Tab.

**Comment by edreamleo** [comment]
Rev 0a5f036 in devel attempts the most minimal kind of fix.

**Comment by edreamleo** [comment]
I am reopening this issue because bindings to shift-colon and shift-semicolon will fail on English keyboards. The solution will likely involve a new setting.

**Comment by edreamleo** [comment]
Rev 167e333 fixes this issue by supporting `@bool` use-german-keyboard. You should set this setting to True when using a German keyboard.

**Comment by edreamleo** [comment]
There are issues with Spanish keyboards. I am reopening this issue while I investigate.
