### ISSUE TITLE
zoom-in & zoom-out can not keep fonts size

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#1569]
The fonts size in body panel changes to original size with clicking the body panel after run zoom-in or zoom-out command.

Leo Log Window
Leo 6.3-devel, devel branch, build 8051ecd172
2020-04-05 05:55:36 -0500
Python 3.7.3, PyQt version 5.12.3
darwin

**Comment by edreamleo** [comment]
Rev 729691 in devel adds support for --trace=zoom. As of this rev, Leo's zoom commands do work, and the zoom factors persist when changing nodes. As a result, I am going to close this issue.

With a standard usb mouse, MacOS does not ctrl-wheel actions, but this is unlikely to be something that Leo can do anything about.
