### ISSUE TITLE
Tab pane disappears when starting with fresh .leo directory

### ISSUE THREAD

**Issue by btheado** [leo-editor/leo-editor#1570]
While testing #1568, I used a blank home directory so that all the default settings and plugins are used. I discovered when I run leo that way, the tab pane disappears.

When the leo window is first drawn, I can see the outline pane on the left with the tab pane beneath it. On the right I see the body pane. But then the tab pane disappears. After that the Leo Tips dialog box appears.

Steps to reproduce on linux:
1. mkdir -p ~/tmp/blank
2. HOME=~/tmp/blank python launchLeo.py

```
Leo 6.3-devel, devel branch, build 8390038749
2020-04-11 17:34:16 +0200
Python 3.7.5, PyQt version 5.13.0
linux
```

I used `git bisect` and found 307a4a9432 "Completed #1514 by setting @string initial-split-orientation = horizontal as the default" to be the first bad commit.

**Comment by btheado** [comment]
Now I notice the tab pane is still there, just that it is zero size. IOW, the splitter bar is still visible and I can drag it up to make the tab pane visible again. So somehow the tab pane size is getting reduced to zero.

**Comment by btheado** [comment]
I've looked into this a little more and I'm seeing many calls to  `LeoQtFrame.divideAnySplitter` during startup. On the 4th call,  `frac = 1.0` is being passed in and I suspect that is when it goes wrong.

That call is coming from this call stack:
```
leoApp->openFileByName()
  leoApp->initWrapperLeoFile()
    frame.resizePanesToRatio(frame.ratio, frame.secondary_ratio)
```

`frame.secondary_ratio` is indeed equal to 1.0 in this case.

I'm thinking at startup when a new leo file is opened, frame.secondary_ratio is being initialized to 1.0? I'm not sure as I don't understand it yet.

**Comment by edreamleo** [comment]
PR #1660 contains the fix. Please report any further problems.

**Comment by btheado** [comment]
Fix confirmed. I no longer see the issue in branch bug-1570.

**Comment by edreamleo** [comment]
On Thu, Sep 10, 2020 at 7:19 PM btheado <notifications@github.com> wrote:

> Fix confirmed. I no longer see the issue in branch bug-1570.
>
Thanks for the confirmation.

Edward
