### ISSUE TITLE
Headline box icon grows when task icon is added

### ISSUE THREAD

**Issue by btheado** [leo-editor/leo-editor#1571]
The headline box icon becomes about 25% larger when a task icon is added to that headline. The task icon looks larger than it should be also. I noticed this a few weeks ago and forgot to mention it until noticing it again while looking at #1568.

The issue reproduces for me with my normal .leo directory and a fresh .leo directory.

**Comment by vitalije** [comment]
Different icons are drawn to have common height. This might enlarge icons which are originally smaller. Until recently all icons were centered on the height of the tallest icon. But smaller icons were not enlarged. This used to produce strange effects when combining icons from different sets. Some icons were reduced to size of a pixel. For example you have two icons 16x16 and then add the third which is 64x64. The resulting icon displayed used to have two 4x4 icons, followed by one normal size icon.
I have intentionally changed this to first resize all images to the common height, and then place them one after another. The result of this is that some smaller icons are enlarged after combining with other icons.

One possible solution would be to resize all Leo icons to have common height.

**Comment by btheado** [comment]
Seems tricky to find a solution which satisfies all or most situations.

Are there any drawbacks to resizing all the icons to have a common height?

Another idea. Is it possible to normalize the height of the icons based on the font height of the headline text?

**Comment by technatica** [comment]
When designing the themes I start with:
*
{
color: @dark-base0;
background: @dark-base3;
font: 12px @dark-base0 @font-family;
}

Under @data qt-gui-plugin-style-sheet
Universal Style

As each individual widget is identified using Gammaray (some still aren't
due to poor coding conventions) they are assigned their own styles and the
Universal Style no longer applies to them.

Under Tree, headline font and icon height ar set as two different thing but
could quite easily be tied together as part of the design,

Feel free to ask questions. I designed Beeze Dark and Zephyr Dark so I have
a pretty good idea of how they are put together.

Chris

**Comment by wangzhaohe** [comment]
Still like normal size. Bigger looks not comfortable.

**Comment by vitalije** [comment]
Try aa86ba1. It uses different strategy instead to enlarge smaller icons, it reduces larger icons to the smallest height

**Comment by wangzhaohe** [comment]
Will it be better if you adjust icon height which is equal to Font size?

<img width="326" alt="iconsize" src="https://user-images.githubusercontent.com/2628013/79173688-e55c9e80-7e2a-11ea-8fc7-16cff8332bad.png">

**Comment by vitalije** [comment]
In revision 463a927 all images are resized to be as tall as `treeWidget.iconSize().height()`. Presumably this value is defined through user settings.

**Comment by edreamleo** [comment]
@vitalije The new code in devel looks terrible on my machine compared with master.

Reverting:

`height =self.treeWidget.iconSize().height()`

to:

`height = max([i.height() for i in images])`

makes everything look properly, at least on my machine.

**Comment by wangzhaohe** [comment]
>height =self.treeWidget.iconSize().height()

<img width="345" alt="image" src="https://user-images.githubusercontent.com/2628013/79308615-7f0b7500-7f2b-11ea-8571-25c2acdee962.png">

***

>height = max([i.height() for i in images])

<img width="343" alt="image" src="https://user-images.githubusercontent.com/2628013/79308586-6bf8a500-7f2b-11ea-8b82-c7ffe906f1bd.png">

***

>(5.9-final-rel) **I think this is better**

<img width="340" alt="image" src="https://user-images.githubusercontent.com/2628013/79308671-9a768000-7f2b-11ea-9d98-a1117a36d132.png">

**Comment by edreamleo** [comment]
@vitalije I am going to revert devel to the code I showed above. Please do any further work in a separate branch. Thanks.

**Comment by edreamleo** [comment]
I am going to close this issue for now. Please feel free to reopen it if you have new ideas.
