### ISSUE TITLE
Correction to LeoDocs

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#1572]
Although there are plenty of updates that probably should be made to LeoDocs, there is one bit that really should be changed soon.  

In the section "Installing Leo on Windows/Using the single-click installer", it says:
```
Leo has a binary installer for Windows, available at the `SourceForge download page`_.
```

Well, no. Not for quite a while, and the latest installer there is pre-Leo 6.  Let's at least change this one.

**Comment by maphew** [comment]
Thanks Thomas. Docs have been updated.
