### ISSUE TITLE
add cycle-editor-focus & rename delete-editor

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#1574]
used no docks

I like `cycle-editor-focus` command. I think it is useful for me.

Would a chance to change `delete-editor` to other name? I have run `delete-node` several times
and again, again...  I think I am the dumbing down man.

**Comment by edreamleo** [comment]
On Tue, Apr 14, 2020 at 12:12 AM wangzhaohe <notifications@github.com>
wrote:

> used no docks
>
> I like cycle-editor-focus command. I think it is useful for me.
>
I'll see what restoring this command would entail. I've just created #1575
<https://github.com/leo-editor/leo-editor/issues/1575>for this.

> Would a chance to change delete-editor to other name? I have run
> delete-node several times
> and again, again... I think I am the dumbing down man.
>
You can use @command to create your own aliases. The following is tested
code:

@command de
c.k.simulateCommand('delete-editor)

You can also add a keyboard shortcut:

@command de @key=whatever

Edward

**Comment by edreamleo** [comment]
I am going to close this. See #1575.
