### ISSUE TITLE
leo-desktop-integration on linux

### ISSUE THREAD

**Issue by brobr** [leo-editor/leo-editor#1577]
Hi Maphew,
I always run Leo from a menu (in Xfce) with a terminal open. This can be set in a 'launcher' or in a `leo.desktop` file; this is the one put in my leo package:
>[Desktop Entry]
Name=Leonine Editor with Outlines (leo)
Name[he]= Leo
Comment=Developer's Text Editor
Exec=leo
Icon=leo
Terminal=false
Type=Application
MimeType=application/x-leo-outline;
Categories=Development;TextEditor

When you set the `Terminal` to `true`, starting leo from a drop-down menu (or desktop-icon) would do this with a terminal open, catching all errors (if any).  This would be the 'ux'-way anyway, something doesn't start from the DE?, start a terminal and run 'something' from the command line.
 
This `leo.xml` file is also packaged with the program so that leo documents are linked to leo:
>\<?xml version="1.0"?>
\<mime-info xmlns="http://www.freedesktop.org/standards/shared-mime-info">
\<mime-type type="application/x-leo-outline">
\<comment>leo-outline file</comment>
\<glob pattern="*.leo"/>
\</mime-type>
\</mime-info>

To get the `leo.desktop` and `leo.xml` files immediately used, these commands are run after installing leo:
>if [ -x /usr/bin/update-desktop-database ]; then
   /usr/bin/update-desktop-database -q usr/share/applications >/dev/null 2>&1
fi
>
>if [ -x /usr/bin/update-mime-database ]; then
  /usr/bin/update-mime-database usr/share/mime >/dev/null 2>&1
fi

If you think this could be useful, feel free to include them with leo (although it's specific for linux)

Cheers,
Rob

PS My 'unoffical' leo package for Slackware is available on github: 
"https://github.com/brobr/SLACKBUILDtrees.git"

_Originally posted by @brobr in https://github.com/leo-editor/leo-editor/issues/1547#issuecomment-616130807_

**Comment by maphew** [comment]
Putting to sleep until I or someone else has time and initiative to finish it.
