### ISSUE TITLE
realloc(): invalid old size

### ISSUE THREAD

**Issue by jiapei100** [leo-editor/leo-editor#1578]
Both **leo-c** and **leo-console**  are working properly, from within my **zsh**. However, **leo** brings me the following ERROR message:

```
➜  bin ./leo

setting leoID from os.getenv('USER'): 'longervision'
realloc(): invalid old size
[1]    22322 abort (core dumped)  ./leo
```

I installed **leo** via **pip** , the command is `pip install -U --user leo`. My OS ENV:
```console
➜  ~ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
➜  ~ python --version
Python 3.6.9
➜  ~ uname -r    
5.3.0-46-generic
```

**Comment by edreamleo** [comment]
Core dumps like this indicate installation problems. There is no way for me to debug your qt/python installation with only this information. Please reinstall qt. And please feel free to ask for help on leo-editor.
