### ISSUE TITLE
Install from AUR segfaults

### ISSUE THREAD

**Issue by xircon** [leo-editor/leo-editor#1580]
```
leo

setting leoID from os.getenv('USER'): 'steve'
read only: /usr/lib/python3.8/site-packages/leo/config/leoSettings.leo

(process:325535): GLib-CRITICAL **: 14:50:20.061: g_hash_table_contains: assertion 'hash_table != NULL' failed

(process:325535): GLib-CRITICAL **: 14:50:20.061: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
[1]    325535 segmentation fault (core dumped)  leo
```
Also cloned and it has the same problem.
```
 ./launchLeo.py

setting leoID from os.getenv('USER'): 'steve'

(process:343789): GLib-CRITICAL **: 15:00:57.452: g_hash_table_contains: assertion 'hash_table != NULL' failed

(process:343789): GLib-CRITICAL **: 15:00:57.452: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
[1]    343789 segmentation fault (core dumped)  ./launchLeo.py
```

**Comment by maphew** [comment]
What is "AUR"?

**Comment by technatica** [comment]
Arch User Repository

**Comment by gatesphere** [comment]
You should take it up with the maintainer of that package.  As far as I
know, it's not one of us -- but I could be very wrong :)

(I'm an arch user, and I didn't know there was an AUR package for Leo.)

**Comment by xircon** [comment]
AUR just automates the build process.

I get the error from AUR and when I clone the repo - see original post.

**Comment by maphew** [comment]
Oh look at that: https://aur.archlinux.org/packages/leo/. The package goes back to 2015. There are some recent comments about build problems and seeking advice on how to maintain the package. I didn't see anything that suggests there's anything we can do to fix it from here.

@technatica, @gatesphere how do you install Leo on Arch?

**Comment by gatesphere** [comment]
Sorry to be late to the conversation here.

I did not install Leo from AUR on my Arch boxes.  I installed from git, after pulling the required python packages from the Arch repos.

**Comment by edreamleo** [comment]
@xircon Hi, I am going to close this issue because Leo has lost the services of Matt Wilkie, our distribution and installation guru.

The only thing I can suggest is to install the Anaconda3 distribution of python 3. Millions of scientists and other non-programmers use Anaconda3.
