### ISSUE TITLE
Leo 6.2.1 pip install fails on PyQt (wheel) dependency install

### ISSUE THREAD

**Issue by daveuu** [leo-editor/leo-editor#1584]
Installation via pip (using poetry) for Leo 6.2.1 fails with:

```
poetry install
...
    /usr/bin/qmake -recursive PyQtWebEngine.pro
    _in_process.py: '/usr/bin/qmake -recursive PyQtWebEngine.pro' failed returning 3
    Info: creating stash file /tmp/tmpa9hynybx/.qmake.stash
    Reading /tmp/tmpa9hynybx/QtWebEngineCore/QtWebEngineCore.pro
    Project ERROR: Unknown module(s) in QT: webenginecore
```

The pyproject.toml contained:

```
[tool.poetry.dependencies]
python = "^3.8"
black = "19.10b0" # had to pin a version hint because failed on 'no versions of black match *'
leo = "^6.2.1"
pendulum = "^2.1"
jinja2 = "^2.11"
sortedcontainers = "^2.1"
```

A separate attempt using pip directly fails with:
```
$ python --version
Python 3.8.0
$ cd ~
$ python -m venv venv_etl
$ ~/venv_etl/bin/pip install leo pendulum jinja2 sortedcontainers
...
Collecting PyQtWebEngine (from leo)
  Using cached https://files.pythonhosted.org/packages/47/9f/60e630711fd1dd14ef3bd95c86c733c86b8c0853749c7a03691f681f13fd/PyQ
tWebEngine-5.14.0.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /home/play/venv_etl/bin/python /home/play/venv_etl/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp6hq0p4u4
         cwd: /tmp/pip-install-_8ungd6k/PyQtWebEngine
    Complete output (6 lines):
    Querying qmake about your Qt installation...
    /usr/bin/qmake -query
    These bindings will be built: QtWebEngineCore, QtWebEngine, QtWebEngineWidgets.
    Generating the QtWebEngineCore bindings...
    _in_process.py: Unable to find file "QtCore/QtCoremod.sip"
```

OS is Arch Linux. I don't know enough about Python packaging (and wheels in particular) to know how to fix this.

I realise the problem is likely to be within the wheel for PyQtWebEngine, but as this also prevents a major way of installing Leo, it seems appropriate to raise this here?

**Comment by maphew** [comment]
Possibly related is #1580, which also about Arch Linux. You might try pinning to an earlier version of PyQt.

**Comment by tbpassin** [comment]
I have seen a few cases where SIP had to be installed separately (using pip).  I don't know if that could apply to any current versions of PyQt5 or not.

I also encountered a Python installation on Linux Mint where I had to install - using pip - both setuptools and even wheel.

**Comment by XCaminhante** [comment]
I don't know how it's related to the problem of this issue, but in Debian I needed to install the python3-pyqt5 package using apt for Leo to work.
I also needed to comment the lines about PyQt5 and PyQtWebEngine in setup.py to be able to install the rest of the dependencies with pip

**Comment by edreamleo** [comment]
@daveuu Hi David. Leo has apparently lost the services of Matt Wilkie, our installation guru.

I am going to close this issue now. The only thing I can suggest is to use the Anaconda3 distribution of python, if that is at all possible.
