### ISSUE TITLE
Leo 6.3-devel Ctrl+P deleted?

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#1586]
Ctrl + P is noneffective.

***

Leo Log Window
Leo 6.3-devel, devel branch, build a2a434902c
2020-04-27 09:53:13 -0700
Python 3.7.3, PyQt version 5.12.3
darwin

**Comment by LewisNeal** [comment]
Confirmed using Ctrl+P gives message in log pane:
no previous command

_repeat-complex-command_ is still working in the mini-buffer.

Leo 6.3-devel, devel branch, build a2a434902c
Python 3.8.2, PyQt version 5.14.2
Windows 10 AMD64 (build 10.0.18362) SP0

**Comment by edreamleo** [comment]
On Tue, Apr 28, 2020 at 7:02 PM wangzhaohe <notifications@github.com> wrote:

> Ctrl + P is noneffective.
>

It works for me.  It repeats only the last *complex* command, that is, the
last command entered by name. It does not repeat commands invoked via
control-keys (for example).

Edward

**Comment by LewisNeal** [comment]
It may help if the error message be changed to:
 no previous command in mini-buffer

This gives a helpful hint that the command must have been given via the mini-buffer.

**Comment by edreamleo** [comment]
On Wed, Apr 29, 2020 at 6:37 AM LewisNeal <notifications@github.com> wrote:

> It may help if the error message be changed to:
> no previous command in mini-buffer
>

Done in rev d45bb1f: "no previous minibuffer command".

Edward
