### ISSUE TITLE
No errors installing Leo and dependencies but Leo hangs at splash image

### ISSUE THREAD

**Issue by Dan-Stevenson** [leo-editor/leo-editor#1587]
_Hello_,

I've installed Leo several different ways but always encounter the same problem when attempting to run it - namely, Leo "hangs" at the "splash image" of the lion, i.e., the main window never opens. I've repaired my python 3.6 installation. I also double-checked that all of Leo's dependencies were correctly installed. 

Methods attempted: I downloaded the archive (leo-editor-master), then ran _launchleo.py_ from the windows command prompt. After that I installed Leo using pip, then typed: _python_, _import leo_, _leo.run()_ from the same terminal window. I tried everything as Administrator as well as from a standard user account.

I also tried running Leo with the "--show-log" option (I know that's not the exact option but I can't remember what it really is and I also can't find the post where I originally found it, so now I'm unable to correct myself here). Running Leo with the (actual) "show log" option did not produce any errors or warnings, however.

Whenever I run Leo all that appears in the console window is: "Leo 6.2.1 final," then "nodeActions: Init."

_**UPDATE 1**_: I just did: "pip install –editable C:\path\to\leo-editor" (with the correct path, of course) - result: "ERROR: ditable is not a valid editable requirement..." Interestingly, now when I run Leo the same text still occurs in the terminal and the splash image still appears, but then the image disappears and the command prompt in the terminal window regains focus (Leo no longer hangs at the splash image).

_**UPDATE 2**_: It has been five hours since I originally posted this so I looked through the docs again. I found the git installation method and followed the directions. There were no warnings or errors. All dependencies were already satisfied and the installation was (reported as) successful. At the end of the list of satisfied dependencies the following appeared in the terminal window (see below)... 

Installing collected packages: leo
  Attempting uninstall: leo
    Found existing installation: leo 6.2.1
    Uninstalling leo-6.2.1:
      Successfully uninstalled leo-6.2.1
  Running setup.py develop for leo
Successfully installed leo

(_As I mentioned, I have already installed Leo. After that I did (I thought) uninstall Leo using pip before reinstalling using other methods, but obviously it was still there somehow_).

I then attempted to execute Leo as directed. Result: splash screen appeared, then disappeared within 1-2 seconds (same as before). The output in the terminal was different, though (see below)...

Leo 6.2.1 final, master branch, build 49c5e4fa3c
2020-03-30 08:39:10 -0500
nodeActions: Init

**UPDATE THREE**: At six hours now. I'm beginning to suspect that sometimes things aren't easy. I found a variation of the git method under "Installing Leo From Sources" (in the documentation) and followed the instructions. Once again, no errors or warnings. Same result when attempting to run Leo, unfortunately.

**MY INFORMATION**:

**Computer**: Lenovo Ideapad 310
**OS**: Windows 10 64 bit

**Information from the python prompt:**

Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)] on win32

**Information from pip regarding the dependencies:**

Name: PyQt5
Version: 5.14.2
Summary: Python bindings for the Qt cross platform application toolkit
Home-page: https://www.riverbankcomputing.com/software/pyqt/
Author: Riverbank Computing Limited
Author-email: info@riverbankcomputing.com
License: GPL v3
Location: c:\program files\python36\lib\site-packages
Requires: PyQt5-sip
Required-by: PyQtWebEngine, leo

Name: PyQtWebEngine
Version: 5.14.0
Summary: Python bindings for the Qt WebEngine framework
Home-page: https://www.riverbankcomputing.com/software/pyqtwebengine/
Author: Riverbank Computing Limited
Author-email: info@riverbankcomputing.com
License: GPL v3
Location: c:\users\tsc\appdata\roaming\python\python36\site-packages
Requires: PyQt5-sip, PyQt5
Required-by: leo

_I apologize for the lengthy post. Because I've been working on this a long time and have added numerous updates the text has really "piled up."_

Thanks for any assistance!

_Dan_

**Comment by tbpassin** [comment]
Just to make sure that there is nothing messed up with your current Python installation (I know you said you had "repaired" it), I'd suggest installing Python 3.8 too.   It's available (that's what I have on my Win 10 machine), and the installer will (I'm pretty sure) install it separately so that the "py" command will run 3.8 by default but you can still run 3.6 if you want to.  Leo runs with no problem with Python 3.8.0.

Oh, and' I'd suggest making sure that Python installs for all users, if you get that choice.

Then install Leo using pip.  If you still have the same problem, we can go on from there.

**Comment by Dan-Stevenson** [comment]
tbpassin: thank-you for your welcome reply.

I will address your concerns. Please review the following:

_...I know you said you had "repaired" it..._

By "repairing" python I meant only that I had employed the built-in repair function included in the python installer (Control Panel/Add-Remove Programs, right-click Python 3.6, select "Change", then "Repair").

_...I'd suggest installing Python 3.8 too._

As a matter of fact, Python 3.8 was (and is) already installed! I have now run "Repair" on it, as well. I then ran Leo again, taking care to explicitly specify Python 3.8 on the command line, but the results did not differ in the slightest from those which preceded them. I am still unable to make Leo spring to life, using either the windows command line _or_ the python prompt.

_...I'd suggest making sure that Python installs for all users..._

Because I have been running Leo using both my customary user account _and_ the Administrator account every time I install Leo using a different method, it appears to me that installing Python 3.8 for _all_ users may not necessarily solve the problem in this case. If I am mistaken in that assumption please correct me!

_...install Leo using pip._

I did install again using pip, this time after verifying that the previous version of Leo had been uninstalled. I regret to report that the events which succeeded any subsequent attempts to run Leo followed the same pattern as I had already encountered: the splash screen momentarily appeared, then disappeared; focus then returned to the command window.

**Suggestion**: _perhaps the documentation should reflect that Leo (_apparently_ - I have only inferred this from your post) may not work with Python 3.6 (I believe the current online instructions specify that Leo requires Python versions "3.6 or later")._

**Comment by tbpassin** [comment]
"perhaps the documentation should reflect that Leo (apparently - I have only inferred this from your post) may not work with Python 3.6".

But Leo *does* work with Python 3.6 (for most people).

I only suggested Python 3.8 so as to have a separate version that had not needed to have a "repair" operation done on it.  If both your 3.6 and 3.8 Python installs needed repair, then I would think something else was wrong.

I suggested installing for "all users" to avoid any problems of not having permissions (for pip, for example) to write something to the intended install directory.  I've seen this on Linux, though I don't know if it ever shows up on Windows.  You haven't mentioned any error messages like that, but I thought it would be good to cover the possibility anyway.

I don't have much else to suggest at this point, but it's surprising that you haven't gotten any error messages on the launching console.  I'd suggest looking in the Windows application log, but I hardly every find anything useful there.  Worth a look, I suppose.

Your problems might be explained if you were running out of memory, but that seems very unlikely.

**Comment by LewisNeal** [comment]
From your terminal try running Leo with the console gui, which does not use PyQt5:
_launchleo.py --gui=console_

Refer http://leoeditor.com/console-gui.html
You may need to install windows-curses
_pip3 install windows-curses_

Regards Lewis

**Comment by tbpassin** [comment]
Just to be complete, would you also run Leo with ``--no-splash`` and also with ``--use-docks``?

**Comment by maphew** [comment]
Dan your perserverence and note taking to this point is commendable, much detail yet also conise. I've never seen anything quite like what you report. I'm pretty sure the problem lies within python setup itself and not Leo per se. 

One item that stands out for me is that PyQt5 reports being installed under `c:\program files` while PyQtWebEngine is under `c:\users`.  This isn't necessarily a problem but might be a fruitful lead. 

`pip list` will show what's installed under Program Files, a.k.a.  the system install  
`pip list --user` will show what's in your profile,  the user space installs

Follow similar pattern for `pip show` and so on. You could try `pip uninstall` everything listed by `pip show` in both system and user (keep the list for later re-install if needed), getting close to blank slate, and then try pip install leo from there.

Docs: https://pip.pypa.io/en/latest/user_guide/#user-installs
Some more info: https://stackoverflow.com/a/58619629/14420

**Comment by maphew** [comment]
I'm removing myself as assignee as I'm not available to help at this time, and closing as localized / time sensitive. Do re-open if there is further information or insights to add that might help resolve it.
