### ISSUE TITLE
Create all in one Windows Leo.exe automatically with GitHub Actions

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#1589]
`gh-act` branch is now successfully using GitHub Actions to 

- [x] automatically build a new everything-included Leo.exe on every push to that branch. 
- [x] copy the results somewhere so people can download and use it.
- [x] set so that builds only happen on tagged commits
- [x]  merge to `devel` branch
- [ ] document for developers
- [x] add user-facing instructions to Leo docs (and website)

https://help.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts

_part of #229 ._

**Comment by maphew** [comment]
**Works!** but getting to the archive in order to download is a bit of work. There isn't a stable url[0]

Getting to the latest leo.exe:

1. Navigate to **Actions**
2. Select **Pyinstaller** from workflow list in the left table of contents (url: https://github.com/leo-editor/leo-editor/actions?query=workflow%3APyinstaller)
3. Look for a recent event with a green checkmark and click on it
4. Look for **Artifacts** heading and under it: **leo-windows-exe** in blue.

![image](https://user-images.githubusercontent.com/486200/81561885-c5949980-9348-11ea-8cbd-cc41e25bcb4f.png)

[0]: Pending this upstream feature request https://github.com/actions/upload-artifact/issues/21#issuecomment-562662657

**Comment by maphew** [comment]
@edreamleo The user facing instructions are done, see comment before this one. I'm not sure about the best place to put it in the docs.

**Comment by edreamleo** [comment]
@maphew Put the new instructions wherever you like. I'll review the changes, if you like.

**Comment by maphew** [comment]
Ok, added to download.html in d9943f88e688f7413199087415be45053b97a42f.

**Comment by maphew** [comment]
Putting to sleep until I or someone else has time and initiative to finish it. What's here so far does work.
