### ISSUE TITLE
paste-as-template command

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#1593]
Vitalije has implemented this command in the "devel" branch. I have retired the "template" branch.

I'll close this issue when Vitalije declares that work is complete.

**John Clark**: Let's say we have a tree like below. Note that all nodes are *not* clones unless specifically stated:
```
- Node A
  - Node A1
  - Node A2
  - Node A3
- Node B
  - Node A1 (a clone)
  - Node B2
    - Node A3 (a clone)
```
I want to *copy* Node B and have the following result:
```
- Node A
  - Node A1
  - Node A2
  - Node A3
- Node B
  - Node A1 (a clone)
  - Node B2
    - Node A3 (a clone)
- Node B (but this is a copy, not a clone)
  - Node A1 (still a clone)
  - Node B2
    - Node A3 (still a clone)
```
I would love this functionality, but currently it's not present. I think there are many use cases for this. I use it for templating-like tasks. But at the moment it's really clunky to achieve, as I have to use Paste-node then reinstate the clones. I often miss some and then chaos ensues.

**Comment by edreamleo** [comment]
The "template" branch contains Vitalije's excellent implementation, for testing only.

I *wont'* merge this code into devel. Vitalije should do the actual commits, so that, for example, he gets credit for the commits, and also so his gnx's appear in the outline.

**Comment by tbpassin** [comment]
I just tried out the new command in ``devel``.  It worked just as I wanted, correctly creating a mixture of copied and cloned nodes.  Undo and Redo also worked as expected.  Nice work!

I did notice that ``paste-retaining-clones``  did not mark the outline as dirty after the copied tree was pasted.

**Comment by edreamleo** [comment]
@tbpassin Thanks for the report.

**Comment by edreamleo** [comment]
@tbpassin Rev 569fae in devel completes this issue.
