### ISSUE TITLE
no command function for 'About...' keys branch

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#1595]
Running> About on any plugin gives an error:
no command function for 'About...'

Leo 6.3-devel, keys branch, build 93d77deb6e
2020-05-24 18:04:11 -0500
Python 3.8.2, PyQt version 5.14.2

**Comment by tbpassin** [comment]
Works fine on my system using
```
Leo 6.3-devel, devel branch, build 90d4825f9f
2020-05-12 10:17:16 -0400
Python 3.8.2, PyQt version 5.12.7
```
Viewrendered3 is responsible for showing the plugin ``About`` information, but the ``keys``  branch may contain on older version that has this bug (it would have to be quite a few revisions old, but that's possible).

I'll see about updating PyQt on my system and see if this functionality still works.

**Comment by tbpassin** [comment]
After updating to ``PyQt version 5.14.2`` on Windows, the ``About`` Info displays as expected on my system.  So it's probably just the ``keys`` branch that has an old version of viewrendered3.

**Comment by LewisNeal** [comment]
Running mvc-prototype branch the plugin About info also works. It appears it's only the keys branch with an old version of viewrendered3.

**Comment by edreamleo** [comment]
Thanks for these comments. Imo, this is a bug in the new code. Iirc, I fixed it once, but then had to revert some code.

**Comment by edreamleo** [comment]
Fixed at aaaf49 in keys.
