### ISSUE TITLE
'Commands' object has no attribute 'executeMinibufferCommand' keys branch

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#1596]
Any @button command using c.executeMinibufferCommand
gives an error. For example:
c.executeMinibufferCommand('save-file')

_AttributeError: 'Commands' object has no attribute 'executeMinibufferCommand'_

Leo 6.3-devel, keys branch, build efbadd5006
2020-05-25 14:37:22 -0500
Python 3.8.2, PyQt version 5.14.2
Windows 10 AMD64 (build 10.0.18362) SP0

**Comment by edreamleo** [comment]
@LewisNeal Thanks for this. The recommended way now is c.doCommandByName. I'll make an alias for the old "spelling".

**Comment by edreamleo** [comment]
Fixed at 0aaaf55 in "keys". Please reopen if problems remain.

**Comment by edreamleo** [comment]
Oops. c.executeMinibufferCommand takes no event arg. I'll have to re-implement it.

**Comment by edreamleo** [comment]
Rev 2507a1f in keys re-implements c.executeMinibufferCommand.

**Comment by LewisNeal** [comment]
Leo 6.3-devel, keys branch, build 2507a1fcc7
I changed some @buttons to use the new c.doCommandByName which now give error:

_TypeError: doCommandByName() missing 1 required positional argument: 'event'
only 0 lines_

Which seems odd as c.executeMinibufferCommand appears to call c.doCommandByName

**Comment by edreamleo** [comment]
@LewisNeal c.doCommandByName does indeed take two arguments. c.executeMinibufferCommand takes only one. There is no need to change your calls to c.executeMinibufferCommand.
