### ISSUE TITLE
Regular Expression DoS vulnerabilities in plugins/importers/dart.py

### ISSUE THREAD

**Issue by IncyLiu** [leo-editor/leo-editor#1597]
We are working on the [ReDoS](https://www.owasp.org/index.php/Regular_expression_Denial_of_Service_-_ReDoS) problem and detected a vulnerable regex from your code.

`^\s*([\w_]+\s*)+\(` in [link](https://github.com/leo-editor/leo-editor/tree/master/leo/plugins/importers/dart.py) takes forever to match the string
`"0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000\b"`
We suggest you change the structure `([\w_]+\s*)+`, to `[\w_][\w_\s]*`.

We didn’t create a pull request because we're not sure if this case is possible to take place in your program, we also do not understand the functionality of the regex as you do. Thank you for your understanding.

**Comment by edreamleo** [comment]
@IncyLiu Thanks for this report. The things we never dream of...

@vitalije Thanks for the fix.

**Comment by edreamleo** [comment]
@abergmann Thanks for this update.

Can someone please explain to me why slowing down Leo poses a problem? The "attacker" would have to get Leo to import a dart file. If they attacker can do that, the attacker could just as easily wipe the hard drive.
