### ISSUE TITLE
@settings / @font-family does not work in local file

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#160]
Specifying fonts using @settings and @font-family = <font-name> does not work. Create a simple leo file with @settings and one node with some bodytext:

@settings
    @font-family = DejaVu Sans Mono
sample_node / (bodytext) will this font change?

There is no change to the font at all.
Rule 3. from the Basics of Leo>Configuring Leo does not override other settings.
... "3. Any other .leo file may also contain local settings. Local settings apply only to that file and override all other settings. It’s best to use local settings sparingly."

Regards
Lewis

**Comment by tbnorth** [comment]
On Wed, 18 Mar 2015 06:11:08 -0700
LewisNeal <notifications@github.com> wrote:

> Specifying fonts using @settings and @font-family = <font-name> does
> not work. Create a simple leo file with @settings and one node with
> some bodytext:
> 
> @settings
>     @font-family = DejaVu Sans Mono
> sample_node / (bodytext) will this font change?

Try

    @string font-family = DejaVu Sans Mono

There might have been a `@font` setting at some point, but I think the
above is what's used currently.

Cheers -Terry

**Comment by edreamleo** [comment]
This bug is invalid, although this area of the settings is confusing.

From leoSettings.leo#About this file, leoSettings.leo--> Basic setting nodes-->@font::

    **Important**: these nodes **only** specify fonts used by Leo's syntax colorizer.
    To set fonts in Leo's widgets, change Leo's master style sheet::
        
        @data qt-gui-plugin-style-sheet 
    
    Valid values for the body of @font nodes::
        
        family: a font family name
        size:   an integer
        weight: bold, normal, None
        slant: roman, italic, None
    
    Use the show-fonts command to pick fonts, then copy the values shown by the
    show-fonts command to the values here.
