### ISSUE TITLE
In log pane at startup : "import-jupyter-notebook requires nbformat package"

### ISSUE THREAD

**Issue by boltex** [leo-editor/leo-editor#1601]
This message has been showing up in the log pane at startup since a few versions back (cant remember when exactly) 

Just thought I'd make a note of this because I feel there shouldn't be "warning/error" type messages  with a simple default Leo install in log at startup. 

Although, I'm not sure maybe I also am the only one who sees this because my system is not installed properly with regards to python/Leo/ect. ... so feel free to dismiss ! :)

**Comment by edreamleo** [comment]
@boltex The importers/ipynb.py generates this message. The importer plugins are "always on", so arguably this message should not be given by default.

**Comment by edreamleo** [comment]
Fixed at 63e48ab in devel.
