### ISSUE TITLE
Mouse click can not close tip

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#1609]
Leo Log Window
Leo 6.3-devel, devel branch, build bcc4438b48
2020-06-21 14:28:23 -0500
Python 3.7.3, PyQt version 5.15.0
darwin

<img width="420" alt="image" src="https://user-images.githubusercontent.com/2628013/85244272-bbe97000-b476-11ea-93ca-9703bd2477cf.png">

**Comment by edreamleo** [comment]
On Sun, Jun 21, 2020 at 9:56 PM wangzhaohe <notifications@github.com> wrote:

Just click the ok button :-) But I see your point. The dialog should have a
close box.

Edward

**Comment by edreamleo** [comment]
I am going to close this issue. Imo, it's not wrong to use a modal dialog for tips. Such dialogs do not have window-level close areas.  Just choose the "OK" button, by typing Enter.

**Comment by wangzhaohe** [comment]
only press `Enter` ok
click "OK" button no response

**Comment by edreamleo** [comment]
@wangzhaohe I'm afraid you will have to live with this behavior. It's not something that Leo can change.
