### ISSUE TITLE
Which version of pyqt are you using?

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#1612]
Leo 6.2.1 final, master branch, build 49c5e4fa3c
2020-03-30 08:39:10 -0500
Python 3.7.3, **PyQt version 5.15.0**
darwin

I only can press Esc and Enter key, mouse click has no effect, so button `No` can not be used.

<img width="420" alt="image" src="https://user-images.githubusercontent.com/2628013/86351748-53c93400-bc97-11ea-8389-d2fb28b7d91a.png">

**Comment by tbpassin** [comment]
Leo 6.3-devel, devel branch, build 6a92120f1a
2020-06-23 09:38:53 -0500
Python 3.8.2, PyQt version 5.14.2

No QT problems like yours.

**Comment by wangzhaohe** [comment]
> Leo 6.3-devel, devel branch, build [6a92120](https://github.com/leo-editor/leo-editor/commit/6a92120f1acdda29b69c85079ed74c1a0abcce75)
> 2020-06-23 09:38:53 -0500
> Python 3.8.2, PyQt version 5.14.2
> 
> That's on Windows 10.
> 
> No QT problems like yours.

I can click `Cancel No Yes` by mouse left button after run `pip install PyQt5==5.14.2`.

Thanks!

**Comment by edreamleo** [comment]
@wangzhaohe Thanks for the report. Glad to hear all is well now.
