### ISSUE TITLE
Leo crashes when entering "@language R" in body section of a node

### ISSUE THREAD

**Issue by ipofanes** [leo-editor/leo-editor#1614]
Leo 6.0:

* create new outline (with Ctrl-N)
* enter "@language " (without the inverted commas) into Body pane of current node
* Press 'shift-r' on a Keyboard capable of latin letters.

Leo crashes.

Leo will not crash if I enter a small r instead of capital R.

**Comment by edreamleo** [comment]
I do not see a crash with Leo 6.2.1 final, even with a German keyboard.

Please install the latest development version of Leo using: `git clone  https://github.com/leo-editor/leo-editor`. If Leo crashes, please provide the traceback.

**Comment by tbpassin** [comment]
Python 3.8.2, PyQt version 5.14.2
Windows 10 AMD64 (build 10.0.18362) SP0

Not observed, with or without a space after @language, for

Leo 6.2.1 final
Leo 6.3-devel, devel branch, build 6a92120f1a

(on a US keyboard).

**Comment by ipofanes** [comment]
fatal: unable to access 'https://github.com/leo-editor/leo-editor/': Failed to connect to github.com port 4
43: Timed out

Sorry, it seems I cannot download into my office environment.

Greetings

Johannes

Von: Edward K. Ream <notifications@github.com>
Gesendet: Freitag, 10. Juli 2020 22:06
An: leo-editor/leo-editor <leo-editor@noreply.github.com>
Cc: Hüsing, Johannes <Johannes.Huesing@med.uni-heidelberg.de>; Author <author@noreply.github.com>
Betreff: Re: [leo-editor/leo-editor] Leo crashes when entering "@language R" in body section of a node (#1614)


I do not see a crash with Leo 6.2.1 final, even with a German keyboard.

Please install the latest development version of Leo using: git clone https://github.com/leo-editor/leo-editor. If Leo crashes, please provide the traceback.

**Comment by edreamleo** [comment]
Perhaps one of your colleagues at work can help you.

**Comment by edreamleo** [comment]
I am going to close this. It does not seem likely that this is a valid bug.
