### ISSUE TITLE
Internal Leo error in createSaxVnode

### ISSUE THREAD

**Issue by rossburnett** [leo-editor/leo-editor#163]
Using Git repo info: branch = master, commit = 42f1065f3e14
Python 3.4.2, PyQt version 4.8.6

Leo.py was downloaded this morning from github leo-editor\leo-editor-contrib

Console:
reading settings in E:\Users\Ross\Documents\Leo\leo-editor-contrib\StudyOutlines\python.leo

Internal Leo error in createSaxVnode
duplicate gnx: 145 in <VNode 7cf7048 PyObject_Call (abstract.c)>
Called from readSaxFile,createSaxChildren,createSaxChildren,createSaxChildren
Please report this error to Leo's developers

**Comment by edreamleo** [comment]
On Sat, Mar 21, 2015 at 8:43 AM, rossburnett <notifications@github.com>
wrote:

> This was downloaded this morning from github leo-editor\leo-editor-contrib
>
> reading settings in
> E:\Users\Ross\Documents\Leo\leo-editor-contrib\StudyOutlines\python.leo
>
> Internal Leo error in createSaxVnode
> duplicate gnx: 145 in
> Called from
> readSaxFile,createSaxChildren,createSaxChildren,createSaxChildren
> Please report this error to Leo's developers
>
​Thanks for this report.  Clearly something is seriously wrong with Leo.
The present strategy is described here
<https://groups.google.com/d/msg/leo-editor/AHKEX6dOp-A/3j1lw2_JE3UJ>.

EKR

**Comment by edreamleo** [comment]
Likely a duplicate #158.  I'll leave it open, though.

**Comment by rossburnett** [comment]
Same error with 5.0 from SF, in case that's any help.

**Comment by edreamleo** [comment]
I am going to close this issue.  Please reopen if there are further problems.  Imo, ripping out the gnx-caching scheme is a complete fix.
