### ISSUE TITLE
Crash in c_oc.moveOutlineRight

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#1639]
The following crash in v._cutParentLinks has been reported in a large .db file.

**Update**: The problem is that two 5660 nodes are not clones in the .db file, but they are clones when the .db file is saved as a .leo file. This looks like a bug in fc.retrieveVnodesFromDb.

k-hen: This large node, X, is/was a root. I added a new root node, Y, then tried to move X under Y which resulted in the attached error.

Call stack: All lines are in leoNodes.py...

moveOutlineRight, 1503
_unlink: 1089
_cutlink: 2537
_cutParentLinks: 2545
_cutParentLinks: 2545
_cutParentLinks: 2542  list.remove(x): x not in list

![LeoNodeMoveError__20200902](https://user-images.githubusercontent.com/592928/91985280-077b8e00-ecf2-11ea-95a9-2414aa9762e8.png)

The file leo_error_test_01 - cleared - Copy.db illustrates the bug. Creating a .leo file does not show the bug.

**Comment by kghenderson** [comment]
I had root nodes like the following: 
A
B
X
D

I selected node B and inserted a new node below, i.e. using insert-node Y.  
Then I attempted to move X under Y using move-outline-right. 

Note that I repeated this multiple times and also tried to move deep nodes within X at lower levels which also resulted in the error.
Node X currently has ~6,700 descendant nodes.

**Comment by edreamleo** [comment]
I am going to close this issue. The .leo file was corrupted, probably because two different kinds of `<@file>` nodes represented the same external file.
