### ISSUE TITLE
vim-open-file command

### ISSUE THREAD

**Issue by ktenney** [leo-editor/leo-editor#165]
The vim.py plugin offers the command 'vim-open-node' which allows editing the current node contents in Vim. 

vim-open-file, if called while in a node associated with an external file, would open the _file_ for editing.

Leo would want to track cursor position, matching current line upon Vim startup, and again in Leo when Vim saves and exits.

Upon returning to Leo, a 'Refresh from disk' would also be required.

**Comment by edreamleo** [comment]
@ktenney As you know, this has been a frequently requested feature in other forms.  This way of doing it should be straightforward.  I've targeted it for b2.

**Comment by ktenney** [comment]
capabilities exist to offer cursor positioning in both directions,
to place the cursor in Vim where it had been in Leo:

vim myfile +10
opens myfile with the cursor at line 10

returning to Leo is a bit convoluted, but seems doable
http://vim.wikia.com/wiki/Restore_cursor_to_file_position_in_previous_editing_session

vim is editing <extfile>, the session data will be saved in /tmp/vim_leo.bridge
$ vim <extfile> -c "set viminfo='1,n/tmp" -i vim_leo.bridge

'1   =  save 1 mark
n/tmp  =  in directory /tmp
-i vim_leo.bridge  =  name the viminfo file vim_leo.bridge

in the file /tmp/vim_leo.bridge we see the following, saying the cursor
was on line 114 when vim exited.

# File marks:
'0  114  0  /tmp/<extfile>

# Jumplist (newest first):
-'  114  0  /tmp/<extfile>

**Comment by edreamleo** [comment]
On Thu, Mar 26, 2015 at 7:02 AM, Kent Tenney <notifications@github.com>
wrote:

> capabilities exist to offer cursor positioning in both directions,
> to place the cursor in Vim where it had been in Leo:
>

​Thanks, Kent.

Edward

**Comment by edreamleo** [comment]
This is too big a project for Leo 5.1.  It will be done early in the 5.2 release cycle.

**Comment by edreamleo** [comment]
Rev e7fce93 implements vim-open-file.  Please reopen if there are problems.
