### ISSUE TITLE
Region Bounds

### ISSUE THREAD

**Issue by kghenderson** [leo-editor/leo-editor#1653]
I use Ctrl+Shift+RtArrow quite a lot and it's not stopping at the next operator. Interestingly, Ctrl+Shift+LtArrow does.

For example, I have:

thing['select_me'] = 'something'.  

If I put my cursor at the beginning of select_me (inside the quote) and hit Ctrl+Shift+RtArrow, then I expect to stop before the matching end quote and select the word, but instead it skips the operators and goes to the s in 'something'. If I put the cursor at the end of select_me and Ctrl+Shift+LtArrow to go back, then it _does_ stop at the quote as expected.

Perhaps I've misconfigured something, but it's been a little frustrating.

**EKR**: By default the bindings are:
```
forward-word-extend-selection = Ctrl-Shift-RtArrow
back-word-extend-selection    = Ctrl-Shift-LtArrow
```

**Comment by edreamleo** [comment]
@kghenderson The bug-1653 branch contains a proposed fix.  Please try it out and report your results in PR #1684 attempts a fix. Thanks.

**Comment by edreamleo** [comment]
The bug-1653 branch has been merged into devel.
