### ISSUE TITLE
Fix icon hooks in plugins, etc.

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#166]
Initial reports by John Lunzer

clone-find-all on ``iconclick[12]`` and ``icon[dr]click[12]`` shows the following plugins use these non-functional event hooks:

- [x] FileActions.py
- [x] active_path.py (docstring / comment references only)
- [x] at_view.py
- [x] expfolder.py
- [x] mime.py
- [x] mnplugins.py
- [x] nodeActions.py
- [x] run_nodes.py
- [x] startfile.py
- [x] textnode.py
- [x] xemacs.py

rev e477f37: fixes all of the above by changing *only* the docstrings of the affected plugins.
Instead of double-clicking the icon box the docstrings now reference the double-click-icon-box command, which *is* functional.

This leaves only the following:

- leo_to_rtf.py throws a bunch of errors.
- leo_pdf.py won't load.

**Comment by tbnorth** [comment]
I made the list of plugins into a checkable todo list, lines just need to start with "- [ ] ".

**Comment by edreamleo** [comment]
On Thu, Mar 26, 2015 at 10:48 AM, tbnorth <notifications@github.com> wrote:

> I made the list of plugins into a checkable todo list, lines just need to
> start with "- [ ] ".
>

​I didn't know that!  Thanks.

EKR

**Comment by tbnorth** [comment]
I wonder how many of these plugins are active / working / maintained.  active_path definitely, but I don't recognize most of the rest.  You can do this:
```
  git log --oneline --follow mnplugins.py
```
to get a list of commits touching each plugin, and from that read the messages to see if there are any that are not part of bulk updates, like "Cleaned init methods of many plugins", "A mass update of plugins...", etc.

**Comment by edreamleo** [comment]
Rev bb94c34 completes work on this issue.  This issue is too minor to warrant further work.

From the checkin log::

Neither leo_pdf.py (not a plugin) nor leo_to_rtf.py plugin appear to work, although both now load without errors. leo_pdf.py is now officially an obsolete plugin.  leo_to_rtf.py is now officially an experimental plugin.
