### ISSUE TITLE
ipython run method like spyder

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#1662]
In spyder, there is a function like below:

![image](https://user-images.githubusercontent.com/2628013/92989069-c6f6ee00-f503-11ea-816e-d70a2790dbef.png)

I think it is a very easy to use.

Now in leoeditor, I need `print(b)` in body panel or input `b` in jupyter QTconcole. Is there a plan to change Leo like Spyder?

**Comment by edreamleo** [comment]
On Sat, Sep 12, 2020 at 1:30 AM wangzhaohe <notifications@github.com> wrote:

> In spyder, there is a function like below:
>
> [image: image]
> <https://user-images.githubusercontent.com/2628013/92989069-c6f6ee00-f503-11ea-816e-d70a2790dbef.png>
>
> I think it is a very easy to use.
>
> Now in leoeditor, I need print(b) in body panel or input b in jupyter
> QTconcole. Is there a plan to change Leo like Spyder?
>

No. As always, contributions are gratefully accepted ;-)

Edward

**Comment by tbpassin** [comment]
It all depends on whether you only want the printed output, or whether you want to interact with the variables like Spyder.  If you only want the printed output inserted into a node, that is easy to get using a script.

**Comment by wangzhaohe** [comment]
> It all depends on whether you only want the printed output, or whether you want to interact with the variables like Spyder. If you only want the printed output inserted into a node, that is easy to get using a script.

It is a greate thing if the printed output can be inserted into a runing node. It is like jupyter notebook feature.

**Comment by tbpassin** [comment]
Here is a script that will run the Python code in a selected node's body and insert the results of print() in the same node.  When you run it again, it will delete the previous output and insert the new.

Paste this text into a new node, either in an outline you want to run it in or in MyLeoSettings.leo.  Change the node's headline to read `eval-insert`, then press the `script button` button.  

To use the command, select a node with some code, press your new button, and see the print() output appear.

```


'''Evaluate the python code in a node and insert the results
at the end of the node.

The inserted results are the last assignment or the
last print statement, whichever comes last.  Any previously
inserted results are deleted.  Results are bracketed by
special lines:

# >>>
..... results here ...
# <<<

This command ignores the following lines:
    - any @language xxx directive lines.
    - any lines following an @language xxx line until the next
      @language python line.
    - lines between lines starting with '@' and '@c'.
    - any other lines starting with '@'.

This script was inspired by the "valuespace" plugin, and some bits of code
were borrowed from that plugin.

This script was created by Thomas B. Passin.
'''

RESULT_START = '# >>>'
RESULT_END = '# <<<'

pos = 0

# Remove previously inserted results
original = c.p.b.split(RESULT_START)[0]

# Ignore Leo "@language" annotations and sections between "@" and @c"
# Ignore lines between @language xxx and @language python, where
# xxx is not python.
orig_lines = original.split('\n')
working_lines = []
in_comment = False
is_python = True

for line in orig_lines:
    if line.startswith('@language'):
        is_python = 'python' in line
    elif line == '@':
        in_comment = True
    elif line == '@c':
        in_comment = False
    elif not in_comment and is_python:
        working_lines.append(line)

working = '\n'.join(working_lines)

leo_globals = {'c':c, 'p':c.p, 'g':g}
locals = {}
exec(working, leo_globals, locals)

# Find the last assignment or print statement to get the result
is_print = is_assignment = False
for line in reversed(working_lines):
    line = line.strip()
    if not line or line[0] in '#@':
        continue
    if len(line.split('=')) > 1:
        is_assignment = True
        break
    if line.startswith('print'):
        is_print = True
        break

if is_assignment:
    var = line.split('=')[0].strip()
    result = str(locals.get(var, ''))
elif is_print:
    print_arg = line.split('print')[1].strip()
    # if it's a print() function, remove the surrounding "()"
    if print_arg[0] == '(' and print_arg[-1] == ')':
        print_arg = print_arg[1:-1]
    result = eval(print_arg, leo_globals, locals)
else:
    result = '# === NO ASSIGNMENT OR PRINT STATEMENT TO EVALUATE ==='

c.p.b = original + f'{RESULT_START}\n{result}\n{RESULT_END}'

c.frame.body.wrapper.setInsertPoint(pos)
c.redraw()
c.bodyWantsFocusNow()
```
