### ISSUE TITLE
Improve Leo's look when newbies first use Leo

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#1663]
See [this post](https://groups.google.com/d/msg/leo-editor/Q973EMV8NRU/tscGdQlfAwAJ).

- [x] Use better default fonts, possibly on a per-platform basis.
    Leo now uses DefaultTheme.leo by default, and this is a dark theme with reasonable fonts.

**Comment by tbpassin** [comment]
Most all editor/IDE type programs open with a usable work area (Pyzo, VS studio, Notepad++, etc.).  It seems to me that a minimum fresh configuration should include:

1. A usable window width and height;
2. A font that looks reasonably good (not blocky (pixelated) or spindly) on larger monitors (I am writing this on a 24-in. HD monitor, and the default font is too big, too thin, and blocky);
3. Workable dock areas (currently the right and left docks are so narrow that they can't be used).
4. An easy way to change the font size, both for the body and outline panes;
5. An easy way to turn on line numbers in the gutter (right now, if you figure out what settings to use and how to change them, you still have to try different gutter spacings and top offsets over and over to get the line numbers to match up with the lines).

I think that the first several tips that show by default on opening default could be:
1.  About dragging the dock partitions;
2. About dragging the dockable panes to new positions;
3. About using --use-docks once you have gotten a layout that you like;
4. About changing the fonts;
5. About setting up gutter numbers.

I think we'll be lucky if a new user gets beyond #1 or #2, but we can at least try to be helpful with them.

**Comment by edreamleo** [comment]
@tbpassin Thanks for these suggestions. My comments: 

- Initial window size is small, but newbies will have no trouble resizing Leo's window.
- I agree that font's are important.
- By default, Leo does not use docks, so dock issues won't *immediately* concern newbies.
- Ditto for Gutter numbers.

Leo presents hints in random order, so there is no way to highlight hints about docks. Instead, Leo should have several new FAQ entries concerning docks and gutters, per your suggestions.

**Comment by tbpassin** [comment]
I hadn't realized that the initial window size with --use-docks is different than with the legacy non-docks mode.  I just discovered that this morning when I tried both ways with a fresh .leo directory.  I would agree with you that the non-docks initial window size is OK.

**Comment by tbpassin** [comment]
>> Instead, Leo should have several new FAQ entries concerning docks and gutters, per 
>> your suggestions.

Then at the very least Leo should have a link to the FAQ in the Help menu.

**Comment by tbpassin** [comment]
I just noticed, for the first time, the menu item Settings/Edit Settings/Fonts/Gutter Fonts. Trying it out, I found that the result inserted certain settings into MyLeoSettings.leo, but it also **deleted all existing settings** that I had already put in there, such as ``gutter-y-adjust``.  The deleted settings were not replaced with new values; they were just removed.

I like the general approach for changing settings, but it is just wrong to delete items that are not being inserted or changed.

**Comment by tbpassin** [comment]
I have found which font is the one that looks so bad, the one that Leo uses by default.  It's ``Droid Sans Mono``.  It's spindly and blocky, at least on my Windows machine with a 24 inch HD monitor.  Actually, it isn't Droid itself but whatever Windows is substituting.

I suggest the following as a good start, because the first two look fairly good (I use Consolas myself) -

``@string font-family =  Consolas, DejaVu Sans Mono, Droid Sans Mono``

I'm assuming that Droid is called for first because it's on most Linux systems. Consolas is a standard Windows font now, so it should be a good choice for the preferred font instead..

**Comment by edreamleo** [comment]
@tbpassin I have just created #1669 to address the issue that "Edit Settings" may delete settings.

**Comment by edreamleo** [comment]
On Sat, Sep 12, 2020 at 11:49 AM tbpassin <notifications@github.com> wrote:

> Most all editor/IDE type programs open with a usable work area (Pyzo, VS
> studio, Notepad++, etc.). It seems to me that a minimum fresh configuration
> should include:
>
>    1. A usable window width and height;
>    2. A font that looks reasonably good (not blocky (pixelated) or
>    spindly) on larger monitors (I am writing this on a 24-in. HD monitor, and
>    the default font is too big, too thin, and blocky);
>    3. Workable dock areas (currently the right and left docks are so
>    narrow that they can't be used).
>    4. An easy way to change the font size, both for the body and outline
>    panes;
>    5. An easy way to turn on line numbers in the gutter (right now, if
>    you figure out what settings to use and how to change them, you still have
>    to try different gutter spacings and top offsets over and over to get the
>    line numbers to match up with the lines).
>
> I think that the first several tips that show by default on opening
> default could be:
>
>    1. About dragging the dock partitions;
>    2. About dragging the dockable panes to new positions;
>    3. About using --use-docks once you have gotten a layout that you like;
>    4. About changing the fonts;
>    5. About setting up gutter numbers.
>
>
Thanks for these. I'd like to continue this conversation after we discuss
whether Qt docks make sense for Leo.

Edward

**Comment by edreamleo** [comment]
I am going to close this issue. Leo now uses DefaultTheme by default.

Other issues should be handled by teaching newbies how Leo is intended to be used, as explained in [this post](https://groups.google.com/d/msg/leo-editor/grgw7jpyPHE/IEZyANg6BQAJ).
