### ISSUE TITLE
highlight current line

### ISSUE THREAD

**Issue by kghenderson** [leo-editor/leo-editor#1664]
I'd like there to be a formatting option for highlighting the current line in the body editor, 
it seems Qt allows this now and it would reduce errors in my coding. 

https://doc.qt.io/qt-5/qtwidgets-widgets-codeeditor-example.html

**Comment by tbpassin** [comment]
This feature has been included in Leo for some time now.  By default it is not turned on.  The setting to turn it on is ``@bool highlight-body-line``.  There is a item in the Help menu about its settings, in *Help/Open Help Topics/Help-For-Highlight-Current-Line*.
