### ISSUE TITLE
settings_finder plugin may delete settings

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#1669]
- [x] Remove settings_finder plugin from recommended plugins.
- [x] Do not enable the plugin by default in leoSettings.leo.

**Thomas** (from #1663): I just noticed, for the first time, the menu item Settings/Edit Settings/Fonts/Gutter Fonts. Trying it out, I found that the result inserted certain settings into myLeoSettings.leo, but it also deleted all existing settings that I had already put in there, such as gutter-y-adjust. The deleted settings were not replaced with new values; they were just removed.

I like the general approach for changing settings, but it is just wrong to delete items that are not being inserted or changed.

**EKR**: The settings_finder plugin creates the Settings:Edit Settings menu.

**Comment by edreamleo** [comment]
@tbpassin: Hi Thomas.  Imo, this plugins is almost worthless as it is. Instead of editing and changing settings, it should simply find settings in either myLeoSettings.leo or leoSettings.leo. The plugin creates long, complex dialogs that I can't understand. I have no idea what a newbie could possibly make of the impossibly-complex choices.

I did not write this plugin. It is not my responsibility to reimagine and redesign this plugin.  I suggest you stop using it.

**Comment by LewisNeal** [comment]
The settings_finder plugin is in the 'recommended plugins list' and enabled by default in leoSettings.leo
Maybe it's status should be updated?

**Comment by edreamleo** [comment]
@LewisNeal: Good catch. I am reopening this issue.
