### ISSUE TITLE
System freeze resulted in "bad .leo file"

### ISSUE THREAD

**Issue by preeset** [leo-editor/leo-editor#1675]
Hello,

I find myself unable to open my .leo file after my system froze.
When I run Leo from my Linux terminal using _leo file.leo_, I receive the message, "**bad .leo file: myfile.leo**"

```
leo SANS.leo 

setting leoID from os.getenv('USER'): 'zero'

bad .leo file: SANS.leo
g.toUnicode: unexpected argument of type ParseError
toUnicode openLeoFile,getLeoFile,readFile,readWithElementTree


Leo 6.2.1 final, master branch, build 49c5e4fa3c
2020-03-30 08:39:10 -0500

bad .leo file: SANS.leo



bad .leo file: SANS.leo


wrote recent file: /home/zero/.leo/.leoRecentFiles.txt

```
The default workbook.leo opens, as does another empty (white) window with my .leo file.
![blank window](https://user-images.githubusercontent.com/29404647/93298907-6eba3780-f7f4-11ea-9b08-4ab7fe4fc5a6.png)

I greatly appreciate your help!

**Comment by edreamleo** [comment]
On Wed, Sep 16, 2020 at 1:13 AM preeset <notifications@github.com> wrote:

> I find myself unable to open my .leo file after my system froze.
>
Do you have backups of your .leo files?  If not, you should run the
following script from time to time:

c.backup_helper(sub_dir='some-directory')

Googling "repair xml file" yields several pages, including this one
<https://www.xmlvalidation.com/>.

HTH.

Edward

**Comment by preeset** [comment]
Thank you very much.

**Comment by edreamleo** [comment]
On Wed, Sep 16, 2020 at 10:11 AM preeset <notifications@github.com> wrote:

> Thank you very much.
>
You're welcome. Glad the repair site helped.

Edward
