### ISSUE TITLE
Is there a graceful way to quit leoeditor?

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#1677]
I run Leo by `python launchleo.py --ipython`

When quit Leo:

1. close Leo, then jupyter QtConsole
2. close jupyter QtConsole, then Leo

Leo can not be closed with either way. I must **kill** `python launchLeo.py --ipython` process by htop.

Is there a graceful way to quit Leo which started with --ipython option?

**EKR**: I see the behavior you describe. Alas, the answer appears to be "no", for the following reasons:

1. The behavior you describe is [ipython issue 2049](https://github.com/ipython/ipython/issues/2049).
2. Leo already calls ileo.cleanup_consoles on shutdown.
    Experiments show neither console.kill() nor console.terminate() works.

I know of nothing else that Leo could possibly do.

**Comment by edreamleo** [comment]
@wangzhaohe I'm not sure this can be fixed. I'll look into it.

**Comment by edreamleo** [comment]
I am going to close this issue and label it "Can'tFix" for the reasons given in the first comment above.
