### ISSUE TITLE
vr3 menu Execute button. Leo crash with input()

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#1679]
The vr3 Execute button works on a node with passive code. However if the code asks for user input the vr3 pane hangs and a force close is needed.
A keyboard interrupt causes Leo to crash. Reproduce with simple code:
`x = input("input x: ")
print(x)`

_Leo Log Window
Leo 6.3-devel, no-docks branch, build 45634c3934
2020-09-17 10:08:39 -0500
Python 3.8.5, PyQt version 5.15.1
Windows 10 AMD64 (build 10.0.18362) SP0_

**Comment by LewisNeal** [comment]
Change input to a LeoGui input:
`x = g.app.gui.runAskOkCancelStringDialog(c,'Title of Box',"input x: ")`

and now the vr3 Execute button works as expected.
_Leo 6.3-devel, no-docks branch, build f34e9199a1_

**Comment by edreamleo** [comment]
This is the expected behavior. input() gets its input from the console.

**Comment by LewisNeal** [comment]
Running Ctrl-B on a node with input() works fine otherwise.
Is this a limitation of the VR3 plugin execute option?
