### ISSUE TITLE
check_gnx error with new 5.1-b1

### ISSUE THREAD

**Issue by rossburnett** [leo-editor/leo-editor#168]
Internal Leo error in check_gnx
getNewIndex: gnx clash 145: v: <VNode 797dcc0 newHeadline> v2: <VNode 7945240 PyObject_Call (abstract.c)>
Called from createSaxChildren,createSaxVnode,__init__(leoNodes.py,line 1961),new_vnode_helper
Please report this error to Leo's developers

There were dozens of similar errors on the console.
I got this when opening the python.leo from the leo-editor-contrib/studyoutlines

Version: 
Leo 5.1-b1, build 20150326104325, Thu Mar 26 10:43:25 CDT 2015
Git repo info: branch = master, commit = 2be4ffb01218
Python 3.4.2, PyQt version 4.8.6
Windows 7 AMD64 (build 6.1.7601) SP1

**Comment by edreamleo** [comment]
On Thu, Mar 26, 2015 at 8:40 PM, rossburnett <notifications@github.com>
wrote:

> Internal Leo error in check_gnx
> getNewIndex: gnx clash 145: v: v2:
> Called from createSaxChildren,createSaxVnode,*init*(leoNodes.py,line
> 1961),new_vnode_helper
> Please report this error to Leo's developers
>
> I got this when opening the python.leo from the
> leo-editor-contrib/studyoutlines
>

​Thanks for this report.  Problems with python.leo were reported before.  I
should have changed it, but didn't.

Edward

**Comment by edreamleo** [comment]
This was fixed several days ago at rev 64d2925 of leo-editor-contrib.
