### ISSUE TITLE
Use a single, global VR3 pane

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#1685]
The desired behavior is:

1.  A VR3 pane is global to all outlines
2. The VR3 pane be default will open as an additional pane inside the Leo window.  A floating window would be an option - presumably available when the splitter bar is right-clicked.

**EKR**: Thomas, I will leave the code entirely to you. However, I ask you to ensure that VR3 layout do not conflict with VR or VR2 layouts. Just use 'viewrendered3_default_layouts' instead of 'viewrendered_default_layouts'.

**Comment by tbpassin** [comment]
What would be this reversion?  Is it the ViewRenderedProvider?

**Comment by tbpassin** [comment]
I restored the old ViewRenderedProvider3 code, but the new behavior is not changed.

**Comment by tbpassin** [comment]
When VR3 is toggled on (or off) , ns_provide() is called many times, but not with the expected id value.  It is expecting to get: ``if id_ == '_leo_viewrendered3':``  (This is with the reverted code for ``ViewRenderedProvider3``). But instead when VR3 is toggled on, it is called repeatedly with the the following stream of id_ values (the "===" is just there so I can easily identify these g.es() statements):
```
=== _leo_pane:outlineFrame

=== _leo_pane:outlineFrame
=== _leo_pane:logFrame
=== _leo_pane:logFrame
=== _leo_pane:bodyFrame
=== _leo_pane:bodyFrame
=== _leo_pane:outlineFrame
=== _leo_pane:outlineFrame
=== _leo_pane:logFrame
=== _leo_pane:logFrame
=== _leo_pane:bodyFrame
=== _leo_pane:bodyFrame
```

Note that `` ns_provide()`` is **never** called with the expected value of ``id_``: `` '_leo_viewrendered3'``.

**Comment by edreamleo** [comment]
@tbpassin I'll say more about all this tomorrow.

**Comment by tbpassin** [comment]
Ah, I see (sort of) - when I use the splitter bar's context menu ``Open Window/Viewrendered3`` menu, then the one and only call to ``ns_provide()`` *does* have the ``id_``  value of ``'_leo_viewrendered3'``.  I guess that's how this part of things are supposed to work.

**Comment by edreamleo** [comment]
I am going to close this. Please reopen as necessary.
