### ISSUE TITLE
Leo-editor forces discrete graphics on OSX

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#1693]
Leo Log Window
Leo 6.3-devel, devel branch, build 8a5715ab3f
2020-09-26 08:06:54 -0500
Python 3.7.3, PyQt version 5.12.1
darwin

macOS Catalina
version 10.15.5

I found Leo forces discrete graphics on macOS after pull 8a5715ab3f.

I'd love to save my battery life when I'm not powered.

one ref: https://github.com/spyder-ide/spyder/issues/9302

**Comment by edreamleo** [comment]
There is nothing that Leo can do about this, and nothing in the rev you mention that affects this issue.
