### ISSUE TITLE
Enhancement request:  Flush stdout as often as performance allows.

### ISSUE THREAD

**Issue by SegundoBob** [leo-editor/leo-editor#17]
I have a Bash script that starts Leo-Editor and captures stdout in one file, stderr in a second file, and both stdout and stderr in a third file.

The only problem I have is that redirecting stdout to a file makes stdout buffered.  Consequently, the stdout output has for me always been appended to the file when Leo-Editor terminates. Consequently, it has always appeared that all errors occurred before any stdout ouput occurred---which has always been untrue.

I believe stdout to the console is unbuffered.  This is almost certainly why this problem was not noted long ago and fixed.

Ideally, Leo-Editor should flush stdout after every burst of output to stdout.  This may be impractically tedious to code. There may be performance issues.  But please, I would appreciate any improvement.

**Comment by edreamleo** [comment]
> Ideally, Leo-Editor should flush stdout after every burst of output to stdout. This may be impractically tedious to code. There may be performance issues. But please, I would appreciate any improvement.

It's easy to kill all output from Leo as follows:

```
def do_nothing(*args, **keys):
    pass

g.es_print = do_nothing
g.es = do_nothing
```

This suggests that monkey-patching g.es_print and g.es, say in a plugin, would allow flushing or redirecting of all of Leo's output, completely at the plugin's discretion.

**Comment by edreamleo** [comment]
I would rather not touch Leo's existing g.es and g.es_print commands. There is no way to know how people are using them, or modifying them.  Monkey-patching them, as described above, seems like a reasonable solution for use cases such as @SegundoBob describes. For this reason, I am going to mark this "Won't Do" and close this item.  Please reopen if you think this is unwise.
