### ISSUE TITLE
Update @<file> trees when corresponding external files change outside Leo

### ISSUE THREAD

**Issue by slzatz** [leo-editor/leo-editor#170]
The request is for a running instance of Leo to have an @settings switch or some other mechanism that causes it to track externally referenced files for changes since the last leo-initiated save and alert the user that a file has been changed outside leo.  The alert should allow the user either to reload the file or ignore the external changes such that they would be over-written the next time Leo did a save.  Vim and a number of editors track external changes to files and behave similarly.  The addition of this feature would make it much easier to simultaneously work on files using Leo and other editors like vim.

**Comment by edreamleo** [comment]
Rev a9ae978 contains the first draft of the implementation. From the checkin log:

- The check for changed files just uses the file's modification date. It could also examine a checksum.
- The code just calls c.refreshFromDisk to do an update.

The code was unexpectedly easy.  Please test and report your experiences.

I'll leave the issue open while I experiment with checksums.

**Comment by edreamleo** [comment]
Rev 3da0f4f now uses checksums to ensure that the file has actually changed when the modification date changes.  This prevents an unnecessary prompt.

This rev also uses the excellent persistent singleton pattern described [here](https://groups.google.com/d/msg/leo-editor/K_cZP23S9U0/XMyf6N3FuCkJ).

This concludes this issue.  Please reopen if you find problems.

**Comment by slzatz** [comment]
I have updated to the latest version but am not seeing any of the expected file modification warnings.  Is there a @settings that is off by default?

**Comment by edreamleo** [comment]
Yes.  ``@bool check_for_changed_external_files = True``. 

I could have sworn I documented this. Oh, I see.  It was in the project notes in leoProjects.txt.  Not exactly public :-) Thanks for pointing out the omission.

**Comment by slzatz** [comment]
Works as expected - thanks.  I can imagine a future enhancement that shows the diff as you do on startup but the key feature is the capability now to edit in either leo or an external editor and be notified of changes to external files.  Thanks for this important addition to leo.

**Comment by edreamleo** [comment]
@slzatz Leo always shows diffs for ``@clean`` nodes.  In this respect, ``@clean`` works better than ``@file``, which only shows diffs for cloned nodes.

This bug may be cleared, but I am about to merge four pieces of code into a new ExternalFiles class in leoApp.py. This will combine open-with code, the code from this issue, the mod_tempfname plugin and editnode_on_idle from the contextmenu plugin. I'll announce the change on leo-editor today.
