### ISSUE TITLE
wishlist: ability for minibuffer commands not to enter command history buffer

### ISSUE THREAD

**Issue by jknGH** [leo-editor/leo-editor#174]
It would be potentially useful to be able to enter a minibuffer command and have it *not* entered into the command history buffer.

In Bash, commands entered with a leading space work this way.

Thanks, Jon N

**Comment by edreamleo** [comment]
This is likely going to be difficult to do.  It is likely to be of less important now that command history works as in other editors.

**Comment by jknGH** [comment]
Hi Edward 

 no sweat - it was only a minor point. I use this
feature occasionally in Bash, but haven't got a real-life use case in
Leo. 

 Best Regards 

 Jon N 

On 02.04.2015 23:35, Edward K. Ream
wrote: 

> This is likely going to be difficult to do. It is likely to
be of less important now that command history works as in other editors.

> 
> --
> Reply to this email directly or view it on GitHub [1].




Links:
------
[1]
https://github.com/leo-editor/leo-editor/issues/174#issuecomment-89065465

**Comment by jknGH** [comment]
Thank you for addressing this wishlist item Edward; I meant to email
you some time ago but didn't get round to it - my apologies. 

 Very
Best Regards 

 Jon N 

On 06.04.2016 17:29, Edward K. Ream wrote: 

>
Closed #174 [1]. 
> 
> --
> You are receiving this because you authored
the thread.
> Reply to this email directly or view it on GitHub [2]




Links:
------
[1]
https://github.com/leo-editor/leo-editor/issues/174
[2]
https://github.com/leo-editor/leo-editor/issues/174#event-617088150

**Comment by edreamleo** [comment]
I am going to close this.  Both the OP and I agree that there is no real need for this.
