### ISSUE TITLE
Leo won't save an external @file sporadically

### ISSUE THREAD

**Issue by gatesphere** [leo-editor/leo-editor#1749]
Leo Log Window
Leo 6.4-devel, devel branch
Python 3.7.4, PyQt version 5.15.1
Windows 10 AMD64 (build 10.0.19041) SP0

Current commit: 69b466e (...)

Noticed today that leo was sporadically not saving dirty files.  No additional output in log or console when this happens -- it's as if Leo just doesn't think the node/file was dirty when the save-file command is run.

I've been able to reproduce this behavior on demand with the following setup:

- Open a .leo file that previously had a child node selected underneath an @file node (in my case, it's a .py file).
- Without doing anything else, the focus on my machine defaults to the body pane.  I type gibberish on the keyboard without changing focus, then run Ctrl+S (save-file).

The log states:

wrote recent file: C:/Users/myusername/.leo/.leoRecentFiles.txt
 saved: leofile.leo

Note, no "written: yourfile.py" notice like usual.  Indeed, the file wasn't written, and remains unchanged on disk.

After backspacing the gibberish, Leo did notice that the file was dirtied, but then since it never wrote the first time, the next save says the contents are unchanged:

unchanged: yourfile.py
finished
 saved: leofile.leo

Which makes sense if it never wrote changes to disk the first time.

This must be a recent change, as I haven't noticed this behavior before today.  I'd say it's somewhere in the past few days' commits.

**Comment by edreamleo** [comment]
@gatesphere I agree. This is a recent bug. It is a critical bug. I'll fix it immediately.

**Comment by edreamleo** [comment]
The ekr_bug_1749 bug has been merged into devel.

**Comment by edreamleo** [comment]
The problems persist. The existing code only calls p.setDirty if it is not already dirty. But apparently this optimization is not correct.
