### ISSUE TITLE
Word/line wrap not wrapping

### ISSUE THREAD

**Issue by JohnLunzer** [leo-editor/leo-editor#175]
I'm running into a situation where even with @wrap selected I'm not getting proper line wrapping. Below is one of my offending lines.
```
runVerbose "${binDir}/RepairEveryHeader ${ini} ${repairedDir} &> ${outDir}/logs/repairEveryHeader_${outGroup}_${rev}_${start_frame}_to_${stop_frame}_atDateTime_${startDateTime}.log"
```
In other editors "words" that are very long and go beyond the wrap margin simply get chopped off when the hit the edge and the remainder sent to the next line, this is not particularly elegant but it's necessary.

**Comment by edreamleo** [comment]
c.frame.body.setWrap (LeoQtBody.setWrap) handles wrapping the body pane.  The present code is:

```python

    def setWrap (self,p):
        if not p: return
        if self.useScintilla: return
        c = self.c
        w = c.frame.body.wrapper.widget
        wrap = g.scanAllAtWrapDirectives(c,p)
        option,qt = QtGui.QTextOption,QtCore.Qt
        w.setHorizontalScrollBarPolicy(
            qt.ScrollBarAlwaysOff if wrap else qt.ScrollBarAsNeeded)
        w.setWordWrapMode(option.WordWrap if wrap else option.NoWrap)
```
w is a QTextBrowser, a subclass of [QTextEdit](http://doc.qt.io/qt-5/qtextedit.html). As you can see, Leo sets only the word-wrapping option.  Perhaps it should set a line-wrap option, documented [here](http://doc.qt.io/qt-5/qtextedit.html#LineWrapMode-enum). Feel free to experiment and suggest changes.

I'm going to close this issue.  It could be called a help item.

**Comment by JohnLunzer** [comment]
It looks like there is a best of both worlds option, "WrapAtWordBoundaryOrAnywhere", seen at http://doc.qt.io/qt-4.8/qtextoption.html

**Comment by JohnLunzer** [comment]
I tested this using the quoted option from my previous post and it's works well. I recommend simply chaning "option.WordWrap" to "option.WrapAtWordBoundaryOrAnywhere".

**Comment by edreamleo** [comment]
Rev c7d543f now uses WrapAtWordBoundaryOrAnywhere when word wrapping is in effect.

@JohnLunzer This is an excellent change.  Thanks for suggesting it.
