### ISSUE TITLE
Ctrl+PgDwn crashes quickmove plugin

### ISSUE THREAD

**Issue by ar-jan** [leo-editor/leo-editor#1751]
I use `Ctrl + Page Down` and `Page Up` for navigating between multiple opened Leo files. When this key combination is used with the Nav tab active, Leo immediately crashes instead of navigating to the next/previous tab in the log pane.

> Leo 6.3, master branch, build e46e9315f6
> 2020-11-10 00:33:16 -0600
> Python 3.7.9, PyQt version 5.9.6
> Windows 10 AMD64 (build 10.0.19041) SP0

I was on v 6.2.1 before, where the same thing also happened so it's not a very recent issue.

**Comment by edreamleo** [comment]
@ar-jan Thanks for this report.

I don't see the crash you describe. Please include it here.

**Comment by ar-jan** [comment]
The error is:

```
Leo 6.3, master branch, build e46e9315f6
2020-11-10 00:33:16 -0600
Traceback (most recent call last):
  File "C:\Programs\Leo\leo\plugins\quicksearch.py", line 733, in onSelectItem
    indent = len(cur.text()) - len(str(cur.text()).lstrip())
AttributeError: 'NoneType' object has no attribute 'text'
```

Is that sufficient information or should I use further debug options? (not sure how/which).

**Comment by edreamleo** [comment]
PR #1756 contains the proposed fix.

**Comment by edreamleo** [comment]
@ar-jan The traceback should suffice. The ekr-quicksearch branch contains the proposed fix. Please test the ekr-quicksearch branch and report your experience.

**Comment by ar-jan** [comment]
Yes, that solves the issue for me.

Curious why/when `cur` would not exist after doing a nav search?

**Comment by edreamleo** [comment]
@ar-jan One of life's mysteries (tm).

**Comment by edreamleo** [comment]
The ekr-quicksearch branch has been merged into devel.

**Comment by ar-jan** [comment]
Thanks!

**Comment by edreamleo** [comment]
@ar-jan You're welcome.
