### ISSUE TITLE
Improve reformat-paragraph, add reformat-selection

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#1754]
PR #1755. The problems with reformat-paragraph become obvious when making repeated changes in markdown or html files.

- [x] reformat-paragraph should make the next paragraph visible.
- [x] reformat-paragraph should *always* select the next paragraph.
- [x] Add reformat-selection command. This works around problems such as:
   - Triple quotes are included in paragraphs.
   - HTML tags, especially `<p>` and `</p`>, are included in paragraphs.

**Comment by tbpassin** [comment]
"Add reformat-selection command. This works around problems such as:
- Triple quotes are included in paragraphs.
- HTML tags, especially \<p> and \</p>, are included in paragraphs."

This isn't clear to me.  Does it mean that these things are **wrongly** being included,  or that it is desired that they should be included but are currently are  not?

**Comment by edreamleo** [comment]
@tbpassin I meant *wrongly* included. However, this could be called a matter of opinion.
