### ISSUE TITLE
Fix bugs in vim mode and vim emulation

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#1757]
**EKR**: The original report now appears at the *end* of this first comment.

**Note**, rev f666402 adds the 'always-indent-region' command. The OP probably would prefer this new command.

- The ekr-vim branch contains the present code.
- There are *two* PR's for this issue:  #1767 and and #1770.

*Important*: This issue concerns vim *emulation*, not vim *mode*. 

- **vim emulation**: `@`keys Vim bindings`
- **vim mode**: `@`bool vim-mode

**Notes**

I plan no changes to the existing bindings for vim emulation. **However**, rev f666402 adds the 'always-indent-region' command. The OP probably would prefer this new command.

Vim **mode** handles all incoming keys in 'command' mode, but vim mode delegates key-handling in 'insert' mode back to k.masterKeyHandler. Therefore, the changes made by this issue *do* affect vim mode. In particular, mode mode now handles auto-completion correctly.

**The problem**

With the default bindings in @keys Vim bindings, all plain keys do have a binding somewhere, which prevents them from being entered.

**What I did**

- k.doBinding inserts the '.' character using the auto-complete command. This is reasonable because:
      - auto-complete always inserts the '.'.
      - auto-complete enters its state handler *only* if auto-completion is enabled.

   There are two subtle consequences of this change:
     - vim-mode automatically supports autocompletion in insert mode.
     - Bindings for auto-complete are no longer needed.
- k.getPaneBinding disallows bindings for all plain keys in 'insert' or 'overwrite' modes. This should be valid because k.masterKeyHandler handles mode bindings before calling k.getPaneBinding.

- Add support for --trace=abbrev:
  - Short traces for abbreviations when *either* 'keys' or 'abbrev' is in g.app.debug.
  - Long traces for abbreviations only when *both* are in g.app.debug.

- Change the look of the cursor in 'command' mode. See #1768.

**Internal error in vim mode**

Fixed in ekr-vim at rev 7cedd9. This was a secondary bug, which came to light during testing.

In vim mode (`@`bool vim-mode=True), in insert mode, typing '.' gave this internal error.

```do_key              : '.'
masterKeyHandler None '.' <KeyStroke: '.'>
check_event not leo event: g.Bunch()
    char: .
    stroke: '.'
    w:  <QTextEditWrapper: 2951083185416 body>
    widget:  <QTextEditWrapper: 2951083185416 body>
, callers: do_state,vim_dot,masterKeyHandler,checkKeyEvent

do_key              : '.'
Internal vim-mode error: bad return_value: None normal None
done                : '.'
```
The trace shown above appears with --trace=keys,verbose. To show this bug, the "dot list" must be non-empty. Typing a character in insert mode is one way to set the dot list.

**Original report**

Leo Log Window
Leo 6.4-devel, devel branch, build 8d51864d61
2020-11-26 12:01:11 -0600
Python 3.7.3, PyQt version 5.12.1
darwin

I can not type char in insert mode. The same problem with checkout master branch.

**Comment by edreamleo** [comment]
@wangzhaohe Everything appears to work with `@vim-mode = True`.

'i' Enters insert mode. 'jj' or 'escape' ends input mode.

**Comment by wangzhaohe** [comment]
> @wangzhaohe Everything appears to work with `@vim-mode = True`.
> 
> 'i' Enters insert mode. 'jj' or 'escape' ends input mode.

Yes, I am still Using Leo’s native vim mode

**Comment by edreamleo** [comment]
@wangzhaohe Are you talking about the vim.py plugin?

**Comment by wangzhaohe** [comment]
> @wangzhaohe Are you talking about the vim.py plugin?

not vim.py

means the following:

<img width="594" alt="image" src="https://user-images.githubusercontent.com/2628013/100876779-ce1a1080-34e2-11eb-93c0-c2ee6123ba29.png">

**Comment by edreamleo** [comment]
@wangzhaohe Thanks for the clarification. I'll look at this issue soon.

**Comment by edreamleo** [comment]
No vim-specific changes to documentation were required, so it's time to close this issue.
