### ISSUE TITLE
DELETE in headline forces change of focus

### ISSUE THREAD

**Issue by largo84** [leo-editor/leo-editor#1763]
1. CTRL-H to edit a node headline.
2. Find any character in the headline to delete.
3. Press DELETE.
4. One character is deleted as expected, then focus immediately goes to node body rather than staying in the headline text.
5. BACKSPACE works as expected.

Configuration:
```
Python 3.7.3, PyQt version 5.9.6
Windows 10 AMD64 (build 10.0.19041) SP0
```

**EKR**: --trace=keys shows:
<Delete> is bound to delete-char.
<Backspace> is bound to backward-delete-char.

**Comment by largo84** [comment]
From the Groups commentary:
`This behavior was present in build b80354f543. It was not present in build d1bd39e14d.`

**Comment by largo84** [comment]
Fixed, thanks.

**Comment by edreamleo** [comment]
@largo84 You're welcome.
