### ISSUE TITLE
leojs: Leo in Javascript for leoInteg.

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#1774]
This issue is a placeholder for Félix's [leojs issue #9](https://github.com/boltex/leojs/issues/9) project, a sub-project of the [leoInteg](https://github.com/boltex/leointeg) project.

Without Félix's encouragement, I would not have the confidence even to consider beginning this project.

**Comment by boltex** [comment]
Checkitout y'all - Gotcha started at https://github.com/boltex/leojs 

Bare minimal functionality showing a working outline with a model made of 'positions nodes' distinct from 'vscode's gui visual nodes'  - not much going on for now, although lots of constants, types and icons and other stuff that will come in handy.

I've kept the files small by removing for now things  related to server, connecting, bridge, leo documents panel and '@buttons' stuff. Easy to add later as as needed & as  we go along.

I'll setup more functionality this weekend, along with a 'dev' branch for collaborators to branch from - and merge back into, to somewhat protect the master branch.

**Comment by edreamleo** [comment]
@boltex leojs.ts is empty. Was that on purpose?

**Comment by edreamleo** [comment]
@boltex Oops. Just pushed directly to master by mistake. The commit adds myLeojs.leo to .gitignore.

**Comment by edreamleo** [comment]
JSON is a big part of any extension, so I would like to make JSON as Leonine as possible. Here is a Leo script that splits the commands node of the "contributes" section into separate nodes.
```python
g.cls()
root = g.findNodeAnywhere(c, 'commands')
print(root.parent().h)
last = c.lastTopLevel()
parent = last.insertAfter()
parent.h = 'command tree'
command_lines, level = [], 0
for i, line in enumerate(g.splitLines(root.b)):
    line_s = line.strip()
    if command_lines:  # Accumulating a new node.
        command_lines.append(line)
        if line_s.endswith(('}', '},')):
            level -= 1
            if level == 0:
                # End of command.
                p = parent.insertAsLastChild()
                h = command_lines[1].strip()
                head = '"command": "leojs.'
                assert h.startswith(head), repr(h)
                if h.endswith(','): h = h[:-1]
                if h.endswith('"'): h = h[:-1]
                p.h = h[len(head):]
                p.b = ''.join(command_lines)
                # g.printObj(command_lines)
                command_lines = []
        elif line_s.endswith('{'):
            level += 1
        else:
            pass
    elif line_s.endswith('{'):
        level = 1
        command_lines = [line]
    elif line_s:
        assert line_s.endswith('[') or line_s.startswith('],'), (i, repr(line))
        # print('OUTSIDE', repr(line))
c.redraw()
```

**Comment by edreamleo** [comment]
I am reopening the issue as a placeholder.

**Comment by edreamleo** [comment]
I am going to close this issue. No further work appears needed in Leo itself.
