### ISSUE TITLE
Search Selected Text  <Wishlist>

### ISSUE THREAD

**Issue by technatica** [leo-editor/leo-editor#179]
Would it be possible to have the selected text in the body pane or headline pasted into the <find pattern here> box when hitting Ctrl-F? This would be incredibly handy for my workflow.

1. Highlight text.

2. Ctrl-F

3. Focus transfers to Find tab with highlighted text already pasted into <find pattern here> box.

4. Execute F3.

You could provide a bool setting to turn #4 on or off, as sometimes it is needed to access the options before each search, but 99% of the time having the command execute the search would be the desired behaviour.

Chris

**Comment by rossburnett** [comment]
I want it too.

**Comment by JohnLunzer** [comment]
In the meantime, to anyone wanting this I would recommend using the quicksearch plugin. It has had a lot of work done on it recently to make it even more useful than it used to be.

**Comment by edreamleo** [comment]
Have you tried setting @bool preload-find-pattern = True?

The comment in leoSettings.leo: True: start-search (F3) automatically loads the Find Pattern.

**Comment by edreamleo** [comment]
Preloading the find pattern completes this issue.
