### ISSUE TITLE
Improve themes for newbies

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#1792]
In the ekr-theme branch. See PR #1793.

- [x] Allow comments after `@settings`.
  - [x]  Remove 'theme' kwarg from LM.createSettingsDicts, pbc.traverse, and config.settingsRoot.
- [x] Use `@string theme-name = None` in leoSettings.leo.
- [x] Add extensive comments to the  `@string theme-name` node.
- [x] Use 10pt or 12pt fonts in all of EKR's theme files in leo/themes.
- [x] Clean *all* themes files.
  - [x] Remove `@theme` organizer node.
  - [x] Remove `@string theme-name` settings from theme files.
    Only myLeoSettings.leo should set this setting to something other than "none".
  - [x] Check for duplicate settings.
  - [x] Theme files should include *only* appearance-related settings.
- [x] When complete, run settings checks in leoSettings.leo.

**Comment by celtic-coder** [comment]
Thanks, this is very useful! 👍

**Comment by edreamleo** [comment]
@celtic-coder Glad you like it. More comments are coming in the settings node itself.

**Comment by edreamleo** [comment]
The following script checks theme files for duplicate settings:
```python
g.cls()
import glob
import os
efc = c.editFileCommands
theme_dir = os.path.join(g.app.loadDir, '..', 'themes')
assert os.path.exists(theme_dir), repr(theme_dir)
paths = glob.glob(f"{theme_dir}{os.sep}*.leo")

def clean(s):
    return s.strip().replace('-','').replace('_','').replace(' ','')
    
for path in paths:
    d = {}
    c = efc.createHiddenCommander(path)
    sfn = c.shortFileName()
    if sfn == 'old_themes.leo':
        continue
    print('checking ', sfn)
    for p in c.all_unique_positions():
        h = clean(p.h)
        if h.startswith('@'):
            if h in d:
                print(f"  {sfn:20}: duplicate {h}")
            else:
                d [h] = True
print('done')
```

**Comment by edreamleo** [comment]
Merged into devel.
