### ISSUE TITLE
no command function for 'beautify-node'

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#1797]
Please teach me How to use this command? Thanks!

no command function for 'beautify-node'

no command function for 'beautify-tree'

**Comment by wangzhaohe** [comment]
** Using beautify-files ?**

Added fstringify-files and diff-fstringify-files commands.

Improved beautify-files command and add diff-beautify-files command.

Removed beautify-node and beautify-tree commands.

Restored Leo's pane commands:
https://github.com/leo-editor/leo-editor/issues/1518
At present, they work only w/o docks.

**Comment by edreamleo** [comment]
@wangzhaohe Thanks for this report. Apparently the beautify-tree and beautify-node commands were deleted by mistake. I'll fix this immediately.
