### ISSUE TITLE
viewrendered3 @html node link css style files

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#1802]
Is there a way to link css files when use viewrendered3 plugins? For example:

    <link rel="stylesheet" href="reset.css">

Sometimes we need to remove browser's default css style, then the html content will be display normaly. Or link a css file in @html node.

[download reset.css](http://meyerweb.com/eric/tools/css/reset/)

[download normalize.css](http://necolas.github.io/normalize.css/)

**Comment by edreamleo** [comment]
On Sun, Jan 3, 2021 at 3:00 AM wangzhaohe <notifications@github.com> wrote:

> Is there a way to link css files when use viewrendered3 plugins?
>
I'm not sure.

> For example:
>
> <link rel="stylesheet" href="reset.css">
>
> Have you tried this? Recall that html is valid in markdown
<https://stackoverflow.com/questions/40335929>.

Edward

**Comment by wangzhaohe** [comment]
Now is ok. The css link must in subnode.
