### ISSUE TITLE
Focus remains in previous file

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#181]
Help > open LeoDocs
Ctrl-F do search for 'line number' select [Find Next: F3] button, until log reads not found 'line number'

Help > open Cheatsheet.leo
Ctrl-F. There is no focus in any pane. If you move the mouse over any pane without clicking, Ctrl-F does not activate in Cheatsheet.leo tab. Click on the Find Tab; the <find pattern here> field is highlighted blue but is not active for text entry.
In fact the focus is still back in LeoDocs.
Now if I enter some new characters via keyboard they land in the <find pattern here> field of LeoDocs.

The procedure above is slightly different than I first reported at https://groups.google.com/forum/?fromgroups#!topic/leo-editor/BAw0q8NsCzs but is highly repeatable.

**Comment by edreamleo** [comment]
Fixed today at 8b02e2d.  The fix was easy.
It's *possible* that this fix might also fix #153, but I wouldn't count on it.
Please reopen if necessary.

**Comment by LewisNeal** [comment]
Edward,
Thanks for fixing this. Verified on commit 0e5fa613f689

Lewis

**Comment by edreamleo** [comment]
On Thu, Jun 25, 2015 at 8:32 AM, LewisNeal <notifications@github.com> wrote:

> Edward,
> Thanks for fixing this. Verified on commit 0e5fa61
> <https://github.com/leo-editor/leo-editor/commit/0e5fa613f689774f1c484d9253d61bd727b5d73c>
>
​You're welcome.  Thanks for the confirmation.  Just to be clear, the fix
happened at 8b02e2d
<https://github.com/leo-editor/leo-editor/commit/8b02e2d9f2a3afb1507ee3f99a65e9896aa71864>
.

Edward
