### ISSUE TITLE
bug in rst code

### ISSUE THREAD

**Issue by stellarpatent** [leo-editor/leo-editor#1815]
leoRst.py has a bug of not returning the OK value in the method createDirectoryForFile when c.config.create_nonexistent_directories is false.  

The method has:
-------------------
def createDirectoryForFile(self, fn):
        ...
        if c and c.config and c.config.create_nonexistent_directories:
            theDir = c.expand_path_expression(theDir)
            ok = g.makeAllNonExistentDirectories(theDir)
            if not ok:
                g.error('did not create:', theDir)
        return ok
-------------------
note: when c.config.create_nonexistent_directories is false, the OK value is not defined.  

The exception I got was 
--------------------------
  File "/home/brian/pyDev/yLeoBook/leo/dev/leo/core/leoRst.py", line 1547, in createDirectoryForFile

    return ok

UnboundLocalError: local variable 'ok' referenced before assignment
-------------------

I'm running CentOS 7, complied Python, used PIP to install everything but Leo, and downloaded the source from Leo.  I've tested with the 6.3 branch, the master, and  devel version.  

I opened leoDocs.leo and browsed to the "Leo's Documentation" node.  Then I did Alt-x - rst3 - enter.  I ran the code through a debugger and I found c.config.create_nonexistent_directories==False

Here is a discussion on the forum: https://groups.google.com/u/2/g/leo-editor/c/2tfPYvPrxt8

**Comment by edreamleo** [comment]
Fixed in devel, per PR #1828.
