### ISSUE TITLE
LeoDocs.leo has hard coded windows path

### ISSUE THREAD

**Issue by stellarpatent** [leo-editor/leo-editor#1816]
This node in LeoDocs has a hard coded Windows path: dir: /home/brian/pyDev/yLeoBook/leo/dev/leo/doc/LeoDocs.leo#Leo's Documentation-->How to...-->How to generate odt/rtf/pdf files-->@rst c:/test/test.html.  

When debugging createDirectoryForFile in leoRst.py, I found that the fn parmeter was being set to: '/home/brian/pyDev/yLeoBook/leo/dev/leo/doc/c:/test/test.html'.  Note the windows path getting added.  I don't think this is a valid Linux Path.  I'm using CentOS 7.  

I discovered this when debugging Leo GitHub bug #1815 

Here is a discussion on the forum: https://groups.google.com/u/2/g/leo-editor/c/2tfPYvPrxt8

**Comment by edreamleo** [comment]
Fixed per PR #1827.
