### ISSUE TITLE
Long filenames do not wrap in notification dialogues

### ISSUE THREAD

**Issue by JohnLunzer** [leo-editor/leo-editor#182]
For example when I get an "Overwrite existing file?" dialogue, if my file name is particularly long it won't wrap within the dialogue, just get cuts off.

I am speaking in particular of file names without spaces. I've tested it with file names with spaces and and the file name wraps correctly, but who uses spaces in their file names ;)

Probably this fix is similar to the previous word wrapping "bug".

**Comment by edreamleo** [comment]
Fixed at 531ad4c.  Various file dialogs now use g.splitLongFileName.
