### ISSUE TITLE
Leo doesn't start with --gui=console

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#1824]
Running python 3.8.6 on Windows 10 AMD64 (build 10.0.18362) SP0

_launchleo.py --gui=console

Empty setting name in False
set parent @settings
Leo 6.4-devel, devel branch, build 99987e8000
2021-02-19 14:32:17 -0600_

Leo hangs at this point, and there is no further activity.

**Comment by LewisNeal** [comment]
using --listen-to-log option, here is log output from the curses gui console:

[snip]
Loaded backend qt5agg version unknown.
Loaded backend Qt5Agg version unknown.
   pr: Can not load session
   pr: Traceback (most recent call last):
   pr:   File "N:\git\leo-editor\leo\core\leoApp.py", line 2400, in doPostPluginsInit
   pr:     g.app.sessionManager.load_session(c1, aList)
   pr:   File "N:\git\leo-editor\leo\core\leoSessions.py", line 80, in load_session
   pr:     g.app.loadManager.loadLocalFile(fn, gui=g.app.gui, old_c=c)
   pr:   File "N:\git\leo-editor\leo\core\leoApp.py", line 3085, in loadLocalFile
   pr:     c = lm.openFileByName(fn, gui, old_c, previousSettings)
   pr:   File "N:\git\leo-editor\leo\core\leoApp.py", line 3106, in openFileByName
   pr:     c = g.app.newCommander(fileName=fn, gui=gui, previousSettings=previousSettings)
   pr:   File "N:\git\leo-editor\leo\core\leoApp.py", line 1616, in newCommander
   pr:     c = leoCommands.Commands(fileName,
   pr:   File "N:\git\leo-editor\leo\core\leoCommands.py", line 79, in __init__
   pr:     c.finishCreate()
   pr:   File "N:\git\leo-editor\leo\core\leoCommands.py", line 411, in finishCreate
   pr:     c.frame.finishCreate()
   pr:   File "N:\git\leo-editor\leo\plugins\cursesGui2.py", line 2166, in finishCreate
   pr:     self.createFindTab()
   pr:   File "N:\git\leo-editor\leo\plugins\cursesGui2.py", line 2177, in createFindTab
   pr:     self.create_find_checkboxes()
   pr:   File "N:\git\leo-editor\leo\plugins\cursesGui2.py", line 2240, in create_find_checkboxes
   pr:     assert getattr(ftm, name) is None
   pr: AttributeError: 'StringFindTabManager' object has no attribute 'check_box_wrap_around'
   pr: Can not create empty workbook
   pr: Traceback (most recent call last):
   pr:   File "N:\git\leo-editor\leo\core\leoApp.py", line 2413, in doPostPluginsInit
   pr:     c1 = lm.openEmptyWorkBook()
   pr:   File "N:\git\leo-editor\leo\core\leoApp.py", line 2456, in openEmptyWorkBook
   pr:     c = lm.loadLocalFile(fn, gui=g.app.gui, old_c=None)
   pr:   File "N:\git\leo-editor\leo\core\leoApp.py", line 3085, in loadLocalFile
   pr:     c = lm.openFileByName(fn, gui, old_c, previousSettings)
   pr:   File "N:\git\leo-editor\leo\core\leoApp.py", line 3106, in openFileByName
   pr:     c = g.app.newCommander(fileName=fn, gui=gui, previousSettings=previousSettings)
   pr:   File "N:\git\leo-editor\leo\core\leoApp.py", line 1616, in newCommander
   pr:     c = leoCommands.Commands(fileName,
   pr:   File "N:\git\leo-editor\leo\core\leoCommands.py", line 79, in __init__
   pr:     c.finishCreate()
   pr:   File "N:\git\leo-editor\leo\core\leoCommands.py", line 411, in finishCreate
   pr:     c.frame.finishCreate()
   pr:   File "N:\git\leo-editor\leo\plugins\cursesGui2.py", line 2166, in finishCreate
   pr:     self.createFindTab()
   pr:   File "N:\git\leo-editor\leo\plugins\cursesGui2.py", line 2177, in createFindTab
   pr:     self.create_find_checkboxes()
   pr:   File "N:\git\leo-editor\leo\plugins\cursesGui2.py", line 2240, in create_find_checkboxes
   pr:     assert getattr(ftm, name) is None
   pr: AttributeError: 'StringFindTabManager' object has no attribute 'check_box_wrap_around'
[end]

**Comment by edreamleo** [comment]
Fixed at ccd43a in devel. This bug was a consequence of eliminating wrapped searches.
