### ISSUE TITLE
Leo does not start with PyQt5-5.15.3

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#1829]
Running python 3.8.6 on Windows 10 AMD64 (build 10.0.18362) SP0
Just updated to PyQt5-5.15.3

>launchleo.py
leoQt.py: can not fully import PyQt5.
Traceback (most recent call last):

  File "N:\git\leo-editor\leo\core\leoQt.py", line 52, in <module>
    from PyQt5 import QtCore

ImportError: DLL load failed while importing QtCore: The specified module could not be found.

name 'QtCore' is not defined

*** Leo could not be started ***
Please verify you've installed the required dependencies:
https://leoeditor.com/installing.html
[end]

It may not be a Leo problem.

**Comment by LewisNeal** [comment]
The issue on PyQt [mailing list](https://www.riverbankcomputing.com/pipermail/pyqt/2021-February/043644.html)

**Comment by edreamleo** [comment]
@LewisNeal Thanks for the research. I'll repeat the workarounds here:

There are two workarounds, remove the old installation first...

pip uninstall PyQt5
pip install PyQt5

...or re-install the wheel containing the Qt libraries...

pip install PyQt5
pip install --force-reinstall PyQt5-Qt
