### ISSUE TITLE
Show gnx in status line

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#1842]
Another support for references involving gnx's.

**Comment by largo84** [comment]
Yes, useful! I assume I can copy the status line?

I often encounter problems w/ mismatched gnx's in @auto files; this should make it easier to troubleshoot.

**Comment by edreamleo** [comment]
On Thu, Mar 11, 2021 at 4:59 PM Rob Keeney ***@***.***> wrote:

> Yes, useful! I assume I can copy the status line?
>

Now you can. Rev e42ac9 in devel shows the gnx in the status line as I
intended, not the minibuffer.

But there is no need to copy the gnx yourself. The command copies the gnx
to the clipboard.

Edward

**Comment by largo84** [comment]
Good!
Rob...

**Comment by edreamleo** [comment]
I am going to close this issue. New-style gnx's should suffice.
