### ISSUE TITLE
rst3: @rst-insert-body and @rst-insert-tree headline commands

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#1843]
**Update**: I am going to close this issue. At best it will add seldom-used features that will clutter the documentation. Instead, the simplified rst3 command will allow Leonistas to focus on tools such as sphinx, sphinx-gallery and jinja.

This enhancement illustrates one way to get the effect of half clones.

Rather than use clones, the rst3 command could refer to the desired node using a reference based on the node's gnx. The rst3 command will search all open outlines for the gnx, starting with the presently selected outline.

`@rst-insert-body <gnx>`

Find the node with the gnx and insert node's body text in the output.

`@rst-insert-head <gnx>`

Find the node with the gnx and insert the node's headline in the output.

`@rst-insert-tree <gnx>`

Find the node with the gnx, and insert an indented representation of the outline's headlines into the output.

**Comment by largo84** [comment]
This enhancement would be useful for my workflow.

**Comment by edreamleo** [comment]
@largo84 Do you use any other rst3 headline commands? I ask because headline commands are an advanced feature.

**Comment by largo84** [comment]
Yes, I also use @rst-no-head and @rst-ignore frequently.

**Comment by edreamleo** [comment]
@largo84 Ok then. I'll do this issue soon.
