### ISSUE TITLE
Easy way to edit leoRecentFiles.txt?

### ISSUE THREAD

**Issue by gatesphere** [leo-editor/leo-editor#185]
There isn't an easy way to delete just a few old entries from Leo's recent files list.  Within Leo, users have the option of clearing it, or sorting it, or 'cleaning' it (no clue what that does, tbh).  The 'clear' option blows the whole file away, meaning you've lost all your history.

I generally resort to closing Leo, opening it in a text editor and pruning the lines I don't want, and then reopening Leo, but I feel there should be an easy way to do this within Leo.  Editing the file within Leo blows away all your changes when the next .leo file is opened -- which leads me to believe that there's a 'recent file history' stored somewhere within Leo's running memory.  Perhaps commands to edit this list should be created?

**Comment by edreamleo** [comment]
On Tue, Apr 21, 2015 at 12:59 PM, Jacob Peck <notifications@github.com>
wrote:

> There isn't an easy way to delete just a few old entries from Leo's recent
> files list. Within Leo, users have the option of clearing it, or sorting
> it, or 'cleaning' it (no clue what that does, tbh). The 'clear' option
> blows the whole file away, meaning you've lost all your history.
>
> I generally resort to closing Leo, opening it in a text editor and pruning
> the lines I don't want, and then reopening Leo, but I feel there should be
> an easy way to do this within Leo. Editing the file within Leo blows away
> all your changes when the next .leo file is opened -- which leads me to
> believe that there's a 'recent file history' stored somewhere within Leo's
> running memory. Perhaps commands to edit this list should be created?
>
​There must be some real bugs lurking here.  Please file a bug report
<https://github.com/leo-editor/leo-editor/issues>.

Edward

**Comment by gatesphere** [comment]
This is the bug report, it came from github 😃

-->Jake

**Comment by edreamleo** [comment]
On Wed, Apr 22, 2015 at 7:16 AM, Jacob Peck <notifications@github.com>
wrote:

> This is the bug report, it came from github [image: 😃]
>

​Hehe.

EKR

**Comment by vitalije** [comment]
Solved at 1def1c3
two new commands were added:
   -  edit-recent-files
   -  write-edited-recent-files

first command will insert as last top node node with the specific headline and 
body that contains currently recent files list. After editing list and while
this node is still selected executing the other command 'write-edited-recent-files'
will write recent files on disk and change accordingly recent files menu.
No default bindings is set for this two commands nor they are added in any menu.
They can be executed as mini-buffer commands: press Alt+x and start writing the
command name. Pressing Tab will auto-complete command name.

**Comment by edreamleo** [comment]
This is a very clever solution.  I like that the created node has a headline that tells the user not to change it.

I think the sort function should ignore case on Windows.  I'll do this soon.

I'll also add documentation for these two new commands.

**Comment by edreamleo** [comment]
Rev 987fea restores the separator between the first three menu items and the generated items. Not sure why this separator was removed...

Rev eae607d completes this item as follows:

- sort-recent-files sorts only the base name: this is what will appear in the headline.  On Windows, sort order ignores case.
- The edit_headline ivar contains the headline of the node, slightly edited from the previous value.
- write-edited-recent-files uses g.findNodeAnywhere to find the node whose headline is self.edit_headline.

**Comment by LewisNeal** [comment]
Docstring for 'edit-recent-files' is Sort the recent files list. 
But when this command is run it edits the current active file. This is not the expected behaviour of a command titled 'edit-recent-files'.  
A better option would be to open a new leo file which can be saved to the HOME ~/.leo directory if required.

**Comment by vitalije** [comment]
Done at  f797b45
