### ISSUE TITLE
leoAST doesn't handle Python 3.7 and later?

### ISSUE THREAD

**Issue by kamahen** [leo-editor/leo-editor#1851]
**EKR**: See PR #1852 and PR #1853. Both have been merged into Leo's devel branch.

These all fail with python 3.7.5, python 3.8.5, python 3.9.2 on Ubuntu 20.04
```python
$ cat /tmp/leo_bug.py
from dataclasses import dataclass

@dataclass(frozen=True)
class F:
    value: str
    start: int
    end: int

f = F('abc', 0, 10)
```
```
$ (export PYTHONPATH=$PYTHONPATH:/home/peter/src/leo-editor && python3.7 -m leo.core.leoAst --fstringify /tmp/leo_bug.py)
fstringify /tmp/leo_bug.py
       file: /tmp/leo_bug.py
     line 6: start: int
Looking for: op.'='
      found: name.'start'
token.index: 30
```
```python
 $cat /tmp/leo_bug2.py
def foo(bar, *, baz,): pass
```
```
$ (export PYTHONPATH=$PYTHONPATH:/home/peter/src/leo-editor && python3.9 -m leo.core.leoAst --orange /tmp/leo_bug2.py)
orange /tmp/leo_bug2.py
Traceback (most recent call last):
  File "/home/peter/.local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/peter/.local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/peter/src/leo-editor/leo/core/leoAst.py", line 6723, in <module>
    main()
  File "/home/peter/src/leo-editor/leo/core/leoAst.py", line 416, in main
    orange_command(files)
  File "/home/peter/src/leo-editor/leo/core/leoAst.py", line 363, in orange_command
    Orange().beautify_file(filename)
  File "/home/peter/src/leo-editor/leo/core/leoAst.py", line 2593, in beautify_file
    contents, encoding, tokens, tree = tog.init_from_file(filename)
  File "/home/peter/src/leo-editor/leo/core/leoAst.py", line 1227, in init_from_file
    list(self.create_links(tokens, tree))
  File "/home/peter/src/leo-editor/leo/core/leoAst.py", line 1206, in create_links
    next(self.visitor(tree))
  File "/home/peter/src/leo-editor/leo/core/leoAst.py", line 1457, in visitor
    yield from method(node)
  File "/home/peter/src/leo-editor/leo/core/leoAst.py", line 1621, in do_Module
    yield from self.gen(node.body)
  File "/home/peter/src/leo-editor/leo/core/leoAst.py", line 1297, in gen
    yield from self.visitor(z)
  File "/home/peter/src/leo-editor/leo/core/leoAst.py", line 1448, in visitor
    yield from self.visitor(z)
  File "/home/peter/src/leo-editor/leo/core/leoAst.py", line 1457, in visitor
    yield from method(node)
  File "/home/peter/src/leo-editor/leo/core/leoAst.py", line 1597, in do_FunctionDef
    yield from self.gen_op(')')
  File "/home/peter/src/leo-editor/leo/core/leoAst.py", line 1303, in gen_op
    yield from self.visitor(self.sync_op(val))
  File "/home/peter/src/leo-editor/leo/core/leoAst.py", line 1431, in sync_op
    self.sync_token('op', val)
  File "/home/peter/src/leo-editor/leo/core/leoAst.py", line 1344, in sync_token
    f"       file: {self.filename}\n"
__main__.AssignLinksError:        file: /tmp/leo_bug2.py
     line 1: def foo(bar, *, baz,): pass
Looking for: op.')'
      found: op.'*'
token.index: 8
```

**Comment by edreamleo** [comment]
@kamahen Thanks for this report. I was aware that there might be problems with annotations. Now I have a good test case.

**Comment by kamahen** [comment]
This bug report is nothing to do with annotations. If you remove the annotations, you'll still get an error. (lib2to3 has been updated to handle this new grammar)
These are examples of new grammar:
```
x: int
def foo(bar, *, baz,): pass
```

**Comment by edreamleo** [comment]
@kamahen Thanks for the clarification.

**Comment by edreamleo** [comment]
[PEP 3102](https://www.python.org/dev/peps/pep-3102/) makes a bare '*' is valid in a ClassDef or FunctionDef. I didn't know this, and the new syntax is far from obvious in the [ast grammar](https://docs.python.org/3/library/ast.html#abstract-grammar), even when looking for it.

The `@dataclass` decorator fails because the dataclass function has a bare '*' in its signature.

**Comment by edreamleo** [comment]
Merged into devel at rev 0851d1.

**Comment by kamahen** [comment]
Is there a way I can verify this change? I did a git pull, but there doesn't seem to be any change, nor are there any branches AFAICT.

Also, a suggestion: make a test case that uses Lib/lib2to3/tests/data/py3_test_grammar.py (from CPython) ... it doesn't do a perfect job of keeping up with all the grammar changes, but it's better than nothing.

I tried it and found another problem:
```
$ (export PYTHONPATH=$PYTHONPATH:/home/peter/src/leo-editor && python3.7 -m leo.core.leoAst --fstringify ~/src/cpython/Lib/lib2to3/tests/data/py3_test_grammar.py )
fstringify /home/peter/src/cpython/Lib/lib2to3/tests/data/py3_test_grammar.py
       file: /home/peter/src/cpython/Lib/lib2to3/tests/data/py3_test_grammar.py
    line 15: from sys import *
Looking for: name.'*'
      found: op.'*'
token.index: 48
```

**Comment by edreamleo** [comment]
@kamahen The new code is in the devel branch of leo-editor.

From PR #1852 you can download leoAst.py directly from the files section.

**Comment by edreamleo** [comment]
Meh. This line in py3_test_grammar.py is invalid in Python 3.6, and I have no idea what the '* is supposed to mean:
```python
def g3(): return 1, *return_list
```
Indeed, `*return_list` does not seem like a valid [3.9.2 expression](https://docs.python.org/3/reference/expressions.html).

**Comment by edreamleo** [comment]
I am going to close this issue. Please create separate issues for any new problems.

I appreciate the desire to use py3_test_grammar.py, but I see no way to do so easily. Perhaps that will change :-)

**Comment by kamahen** [comment]
I'm using py3_test_grammar.py by copying it into my test suite and commenting out the items that aren't Python 3.7 (this is a temporary solution while I upgrade my code to handle Python 3.9 grammar). There seem to be only 2 lines in the Python3.8 test case, plus a few more with Python 3.9 (which doesn't have a test case for the "walrus" operator).
