### ISSUE TITLE
More bugs in leoAst.py

### ISSUE THREAD

**Issue by kamahen** [leo-editor/leo-editor#1857]
See PR #1859. This issue now covers all bugs uncovered by running leoAst.py on py3_test_grammar.py.

[PEP 570](https://www.python.org/dev/peps/pep-0570/) describes keyword-only and position-only args.

**Status (EKR)**:

- All tests pass with Python 3.6 through Python 3.9.
  Some tests are benignly different depending on version.
  The tests pass py3_test_grammar.py.
- All comprehension-related bugs have been fixed, with unit tests.
- Peter's clever fix for position-only args requires Python 3.9.
  Alas, as described in a comment below, this clever fix fails for Python 3.8 *only*.
  I have declared that this bug will not be fixed. The workaround is to use Python 3.9

**Peter's original report**

This line in `py3_test_grammar.py` isn't handled ... AFAIK, it's Python 3.7 grammar (I'm showing the result of running fstringify):
```
fstringify test_data/py3_test_grammar.py
       file: test_data/py3_test_grammar.py
   line 364: self.assertEquals(f(1, x=2, *[3, 4], y=5), ((1, 3, 4),
Looking for: name.'y'
      found: op.'*'
token.index: 2928
```

When I comment out that line, I get:
```
fstringify test_data/py3_test_grammar.py
       file: test_data/py3_test_grammar.py
   line 387: def f(a, b:1, c:2, d, e:3=4, f=5, *g:6, h:7, i=8, j:9=10,
Looking for: op.'*'
      found: name.'e'
token.index: 3269
```

When I comment out that, I get:
```
fstringify test_data/py3_test_grammar.py
       file: test_data/py3_test_grammar.py
   line 947: self.assertEqual(list((x, y) for x in 'abcd' for y in 'abcd'), [(x, y) for x in 'abcd' for y in 'abcd'])
Looking for: name.'y'
      found: name.'for'
token.index: 8484
```
And:
```
fstringify test_data/py3_test_grammar.py
       file: test_data/py3_test_grammar.py
   line 970: x = 10; t = False; g = ((i,j) for i in range(x) if t for j in range(x))
Looking for: name.'j'
      found: name.'for'
token.index: 9076
```
At which point, I gave up.

I suggest you add `py3_test_grammar.py` to your test suite and also run Leo over a representative set of programs, e.g. `find /usr/lib/python3.7 -name '*.py' | xargs python3.9 -m leo.core.leoAst --fstringify-diff`

**Comment by edreamleo** [comment]
@kamahen Thanks for all of these reports.

The most serious problem appears to be deducing the order of arguments in function calls. For example, given the call `f(1, x=2, *[3, 4], y=5)` the Call node contains:

args...
[
  'Num(n=1)'
  'Starred(value=List(elts=[Num(n=3), Num(n=4)], ctx=Load()), ctx=Load())'
]
keywords...
[
  "keyword(arg='x', value=Num(n=2))"
  "keyword(arg='y', value=Num(n=5))"
]

**Comment by edreamleo** [comment]
@kamahen When I awoke this morning I saw a new approach. Since the parse tree does not give the total ordering, start with the python two ordering (args, then kwargs). If that doesn't work, try all other ordering permutations, until one ordering doesn't throw an AssignLinks exceptions.

And Doh! there is no permanent need for py3_test_grammar.py.  The **test_full_grammar** unit tests fails tests a local copy of py3_test_grammar.py. When the test_full_grammar unit test fails (--fail-fast) I'll generate a unit test that fails for that line, then comment out the code in the local copy of py3_test_grammar.py. When all new problems have been found, I'll disable the test_full_grammar test.

**Comment by edreamleo** [comment]
**Update**

1. It's possible that special-casing ast.Starred nodes is just wrong. I'm investigating. I suspect, however, that some backtracking may be required, as discussed above.

2. If backtracking is required, itertools.enumerate is not likely to be useful. Indeed, with 6 arguments in a call, there are 720 to in a full enumeration.  Almost none of these are valid occur because of constraints on the order of arguments.

Let there be Np positional args and Nk kwargs. It looks like starred args appear in the proper order in node.args, so the only possible variations involve allocating kwargs in slots among the positional args. But kwargs must remain in order within slots, so there are only (Np-Nk) factorial ways of allocating slots. It should be straightforward allocate kwargs among the args, assuming, that is, that it is even necessary!

**Comment by edreamleo** [comment]
**Tests**

Here is a Leonine script that shows the parse tree associated with various calls.
```python
import importlib
import leo.core.leoAst as leoAst
importlib.reload(leoAst)

def f(*args, **kwargs):
    print('')
    print('args', args, 'kwargs', kwargs)
    print('')

# Starred args can appear anywhere.
# f(*[3, 4], 1, x=2, y=5)
# f(1, x=2, *[3, 4], y=5)
# f(x=2, y=5, *[3, 4])

# Positional arg can not follow keyword in Python 3.6.
# f(x=2, y=5, *[3, 4], 1)
# f(x=2, y=5, 1)

table = (
    'f(*[3, 4], 1, x=2, y=5)',
    'f(1, x=2, *[3, 4], y=5)',
    'f(x=2, y=5, *[3, 4])',
)
x = leoAst.BaseTest()
for contents in table:
    x.print_full_exception = False
    print(contents)
    exec(contents)
    x.make_data(contents) 
```
Here is the output:
```
f(*[3, 4], 1, x=2, y=5)

args (3, 4, 1) kwargs {'x': 2, 'y': 5}

args...
[
  'Starred(value=List(elts=[Num(n=3), Num(n=4)], ctx=Load()), ctx=Load())'
  'Num(n=1)'
]

keywords...
[
  "keyword(arg='x', value=Num(n=2))"
  "keyword(arg='y', value=Num(n=5))"
]


create_links: Exception...

       file: <module>
     line 1: f(*[3, 4], 1, x=2, y=5)
Looking for: number.'1'
      found: op.'*'
token.index: 3

f(1, x=2, *[3, 4], y=5)

args (1, 3, 4) kwargs {'x': 2, 'y': 5}

args...
[
  'Num(n=1)'
  'Starred(value=List(elts=[Num(n=3), Num(n=4)], ctx=Load()), ctx=Load())'
]
keywords...
[
  "keyword(arg='x', value=Num(n=2))"
  "keyword(arg='y', value=Num(n=5))"
]
create_links: Exception...

       file: <module>
     line 1: f(1, x=2, *[3, 4], y=5)
Looking for: name.'y'
      found: op.'*'
token.index: 11

f(x=2, y=5, *[3, 4])

args (3, 4) kwargs {'x': 2, 'y': 5}

args...
[
  'Starred(value=List(elts=[Num(n=3), Num(n=4)], ctx=Load()), ctx=Load())'
]
keywords...
[
  "keyword(arg='x', value=Num(n=2))"
  "keyword(arg='y', value=Num(n=5))"
]
```

**Comment by kamahen** [comment]
@edreamleo wrote "When all new problems have been found, I'll disable the test_full_grammar test."
Why are you intending to disable the test? It has found some problems, and will probably find more problems in the future when the grammar changes again.

**Comment by kamahen** [comment]
The form of keywords is well known: the `id` can be easily found in the source. So, you can scan the source (as given by enclosing line/column info) for a regexp something like `\b[a-zA-Z_][a-zA-Z_0-9]*\s=` and find the keywords that way.

Can the `_fields` part of a node be used? (Just speculating ... I haven't looked deeply into the `ast` module.)

I suppose we can't file a bug report against the `ast` module because it's an *abstract* syntax tree, not a *concrete* syntax tree. :(

**Comment by kamahen** [comment]
(Correction: a regexp wouldn't work; we'd need a simplified tokenizer, to take care of strings and comments)

**Comment by edreamleo** [comment]
@kamahen "I suppose we can't file a bug report against the ast module."

Of course not. I have always assumed that the ast module is cast in stone. More importantly, changing the ast module would not help leoAst.py *now*. Any changes to the python's ast module would just create *more* problems, not only for leoAst, but for pylint, pyflakes, black, fstringify and all other similar tools.

**Comment by kamahen** [comment]
I did a quick test of `g(a, 1, x=3, *[5, 6], y=4)` using `python3.9 -m ast -m exec -a /tmp/c.py` and noticed that the `args` and `keywords` all have line/column info, so it should be possible to sort the items by position. Also, `ast.walk` (and, I presume, `NodeVisitor`) is specified as "in nor particular order", so if that is used to traverse the tree, the nodes should be sorted by position.

**Comment by edreamleo** [comment]
@kamahen Many thanks for the idea of using line/column info. It should work.

**Comment by edreamleo** [comment]
@kamahen Alas, for python 3.8 *only*, there are no 'lineno' or 'col_offset' attrs for keyword args. These attrs *do* exist for python 3.9.

My plan:

1. Declare (in the docstring for leoAst.py, and in Leo's external docs) that there is a known bug that will not be fixed.  Here is the the relevant part of the docstring:
```
**Known bug**

This file has no known bugs *except* for Python version 3.8.

For Python 3.8, syncing tokens will fail for function call such as:
    
    f(1, x=2, *[3, 4], y=5)
    
that is, for calls where keywords appear before non-keyword args.

There are no plans to fix this bug. The workaround is to use Python version
3.9 or above.
```

2. For Python 3.9 and above, handle args in the order implied by (arg.line_no, arg.col_offset). Experiments confirm that there is no need to use the end_lineno and end_col_offset attrs.

**Comment by edreamleo** [comment]
The ekr-ast-tests branch (PR #1859) has been merged into devel.

Please create a new issue for any new problems in leoAst.py.
