### ISSUE TITLE
Left Gutter Line numbers

### ISSUE THREAD

**Issue by JohnLunzer** [leo-editor/leo-editor#186]
From Edward on the google groups:

>Rev ​72d7740 contains my rewriting of the [line numbers] code. It's LineTextWidget class in plugins/qt_text.py. This file is essentially part of Leo's core.

>The LineTextWidget class is experimental.  It is used nowhere in Leo. Otoh, it is "Leo ready". It passes pylint and imports Qt symbols from leo.core.leoQt. I understand every line of the code, having simplified it :-)

>The goal will be to fold the code into the LeoQTextBrowser class, defined in the same file.  This will not be trivial, but it should be possible.

Here is the original [link](https://john.nachtimwald.com/2009/08/15/qtextedit-with-line-numbers/) to the line numbers code using pyqt.

**Comment by edreamleo** [comment]
Completed at 5a78f7c.  Controlled by the following settings, with defaults as shown::
```
@bool use_gutter = True
@color gutter-bg = @LightSteelBlue1
@color gutter-fg = black
@int gutter-w-adjust = 12
@int gutter-y-adjust = 10
@string gutter-font-family = @font-family
@string gutter-font-size = @small-font-size
@string gutter-font-style = @font-style
@string gutter-font-weight = @font-weight
```
