### ISSUE TITLE
Radically simplify the rst3 command and its code

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#1867]
In the ekr-new-rst branch.  See PR #1870.

The rst3 command should do *nothing* except:

1. Generate rST section references automatically.
2. Support only `@rst-ignore-head` and `@rst-ignore` and `@rst-no-head`.
3. Handle the details of driving docutils.

**Status**

The revised rst3 command should work *exactly* as before for those who don't use features such as code mode, doc only mode, etc. All remaining settings should work as before.

The new [example_rst_filter.py](https://github.com/leo-editor/leo-editor/pull/1870/files#diff-a5baa854c297798822a33a2c20ff58024b575f46aae34275f10b3b7487c399d3) shows how to get the effect of half clones.

**What I did**

- Removed 13 settings. 13 settings remain.
  All remaining settings in leoSettings.leo contain proper explanations.
- Removed all the old option code. reloadSettings now sets ivars.
- Removed all special-purpose write code.
- Removed all evil kwargs! The 'testing' kwarg is a temporary hack.
- Moved the html parser classes to the attic.' Who used these??
- Removed the code_block function. Docutils now uses pygments!
- Added TestRst3 class and removed similar class from unitTest.leo.

**Comment by largo84** [comment]
Perhaps a separate issue or enhancement, I would like an option to send the rst3 command output to the OS clipboard instead of to a text file.

**Comment by edreamleo** [comment]
On Fri, Mar 26, 2021 at 7:45 AM Rob Keeney ***@***.***> wrote:

> Perhaps a separate issue or enhancement, I would like an option to send
> the rst3 command output to the OS clipboard instead of to a text file.
>
I have just created #1869
<https://github.com/leo-editor/leo-editor/issues/1869> for this.

Edward

**Comment by edreamleo** [comment]
Merged into devel.
