### ISSUE TITLE
rst3 optionally outputs to the clipboard

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#1869]
In addition, output should have a single blank line between the output of each nodes.

**Comment by largo84** [comment]
This is great! Curious how you envision this to work. Would that be a different command other than rst3, or via @settings?

**Comment by edreamleo** [comment]
@largo84 Almost nothing would change. The new code will write to a list of strings, so as to avoid having to write unnecessary blank lines. With this structure in place, writing to the clipboard should be easy.

**Comment by edreamleo** [comment]
I am going to close this issue.  In devel, either of the following will do what this issue suggests:

`c.rstCommands.writeNodeToString(p)`

is a (very!) thin wrapper for:

`c.rstCommands.write_rst_tree(p, fn=p.h)`

**Comment by largo84** [comment]
I must be missing something obvious. I created an @button node containing this command (tried both versions). Tried invoking the command from the button on an @rst node. Nothing in the clipboard. What am I missing?

**Comment by edreamleo** [comment]
@largo84 Sorry, I wasn't clear.  Here is tested code:
```python
s = c.rstCommands.writeNodeToString(p)
g.app.gui.replaceClipboardWith(s)
```

**Comment by largo84** [comment]
Perfect, thanks!
