### ISSUE TITLE
@auto-rst Write/Read errors

### ISSUE THREAD

**Issue by largo84** [leo-editor/leo-editor#1872]
`Leo 6.4-devel, devel branch, build 3605785740`
`2021-03-25 07:39:15 -0500`
`Python 3.7.3, PyQt version 5.9.6`
`Windows 10 AMD64 (build 10.0.19041) SP0`

1. Create @auto-rst file with several levels and sublevels.
2. Save the file.
3. It appears to correctly written opened in another text editor (Notepad++ in Windows).
4. Refresh from disk.
5. All levels are flattened.

Perhaps related to recent work on rst3 command.

**Comment by edreamleo** [comment]
@largo84 Thanks for the report. The recent work on the rst3 command should not have affected the devel branch, but we'll see.

**Comment by edreamleo** [comment]
@largo84 I suspect the problem arises from a botched attempt to fix new pylint complaints.

**Comment by edreamleo** [comment]
@largo84 I checked recent revs, and they all appear to work the same. Substantial unit tests work all pass on recent revs in devel.  Are you reporting problems with a new file?

**Comment by largo84** [comment]
@edreamleo , both new and existing files show this behavior. I have a test file I can send, but don't see a way to attach to this report.

**Comment by largo84** [comment]
I think this has been going on for awhile, but didn't take the time to test it thoroughly until this morning. I wanted to make sure it wasn't user error on my part first.

**Comment by edreamleo** [comment]
@largo84 Please send me the file to edreamleo@gmail.com. @auto-rst is confusing for me, and I suspect for everyone :-)

**Comment by largo84** [comment]
Sent the test file and 2 Leo screenshots.

**Comment by largo84** [comment]
This appears to be just a problem with my setup, perhaps a rogue custom setting, closing ticket.

**Comment by edreamleo** [comment]
@largo84 This issue was useful, nonetheless. It exposed some flaws in my testing.

**Comment by largo84** [comment]
Good! Still can't figure out what was going on. It appears to work as expected now despite making no changes to myLeoSettings.leo file. Perhaps blowing up the @persistence node and starting over fixed it, not really sure (I had lots of clones and URL links saved there).
