### ISSUE TITLE
New rst3 command doesn't create file

### ISSUE THREAD

**Issue by largo84** [leo-editor/leo-editor#1884]
Quote from the group:
 ` For most users, the new rst3 command will work exactly as before. Please create an issue if it doesn't.`

Previously, if I had an @rst node with no file extension, the rst3 command created a node_title.txt file which was very useful for me (I suppose it's considered an 'intermediate' file).

Now, I get nothing except this in the log pane:
`rst3: wrote...`
`0 intermediate files`
`0 docutils files`

I can get it to work only if I append .html to the node title. Then rst3 creates 2 files, the html output, which I don't need, and the intermediate file.

This isn't a huge deal as I can simply delete the unwanted .html file. However, I would prefer getting the plain text rst output to a .txt file if possible.

**Comment by edreamleo** [comment]
@largo84 Thanks for the report, Rob. I'll fix it as soon as I get back to fixing bugs.
