### ISSUE TITLE
The "No To All" button in dialogs doesn't work

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#1888]
With leoPy.leo open in devel do `git checkout master`.

A dialog will appear about many changed files. The "No To All" Button doesn't work.

**Comment by boltex** [comment]
Was just fixing leointeg's EFC behavior and noticed this ! => Oh the EFC had some re-do in april! hehe! 

(I was comparing my old EFC code to hendle file changes in leointeg and was trying to make a rewrite/cleanup ans was confused about how I remembered things worked in there!  Makes sense now!)
