### ISSUE TITLE
@path directory trees that start with "~" are created in the wrong place

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#1889]
PR #1897.

Ref an extended discussion of this issue [here](https://groups.google.com/g/leo-editor/c/o7oNnUkq9cU). Briefly, when a subtree that contains "~" in an @path directive, Leo creates a directory tree at a wrong location.  Example:
~~~
-@path ~external-files
    -@path aaa
       -@file test.txt
~~~
This **should** create this file on Linux:

~~~
/home/user/external-files/aaa/test.txt
~~~
but instead it creates
~~~
/<path-to-outline>/~/external-files/aaa/tests.txt
~~~

Ideally on Windows the "~" would expand to the user's home directory, even though the tilde isn't used by convention that way.  Python's _os.path.expanduser()_ does in fact do this.

Adding _os.path.expanduser()_ to the output of _c.expand_path_expression()_ corrects this problem but causes other things in Leo to fail.

**Comment by edreamleo** [comment]
@tbpassin Thanks for creating this issue, Thomas.

**Comment by KingLobo** [comment]
Related to this is handling environment variables in @path and @<file> directives.

EX: $HOME/subdir, $COOL_PROJ/new-file.py

I suggest order of importance to be:

1. Relative path handling
2. Environment variables in path handling
3. “tilde expansion” handling (this issue)

-TK

**Comment by tbpassin** [comment]
I'm not convinced that this issue is the right place for that kind of scope creep.  I'd rather have it focus on the narrow topic as proposed and get that working.  It's not as easy as it seems because there are ripple effects, and possibly several similar routines that might all need to be coordinated.

Once that has all been accomplished - which might even require or suggest some re-architecting - then there could be time to do such an enhancement as you suggest.

**Comment by KingLobo** [comment]
not attempting to introduce any scope creep - merely adding some “precedence” context for where the issue fits in order of desirability IMO. If the implementation of proper tilde expansion were to interfere with the desired functionality of the other two, then that would sub-optimal.

**Comment by edreamleo** [comment]
PR #1897 fixes this issue.
