### ISSUE TITLE
Better support for UNL navigation of Leo's code

### ISSUE THREAD

**Issue by tbnorth** [leo-editor/leo-editor#189]
After an IRC discussion between @gatesphere @edreamleo @tbnorth some useful UNL enhancements were conceived.

When you right click the UNL displayed in the status bar you can toggle the mode to get an UNL starting with file:// that can be pasted into a body and ctrl-clicked to go to that UNL.  A couple of new commands would make this much more efficient / useful.

EKR: Hah.  I didn't know that ;-)

unl-copy: copy the current node's unl (probably the file:// form) to the clipboard, for pasting in irc, email, etc. etc.

unl-goto-clipboard: navigate to the unl on the clipboard, perhaps copied from irc, email, etc.
should have smarts to Leo related paths, so given
/mnt/usr1/usr1/home/tbrown/t/Package/leo/git/leo-editor/leo/config/leoSettings.leo#Startup
(assume file://)
or
file:///mnt/usr1/usr1/home/tbrown/t/Package/leo/git/leo-editor/leo/config/leoSettings.leo#Startup:0
it should be able to find file://c:/stuff/leo-editor/leo/config/leoSettings.leo#Startup:0
if c:/stuff/leo-editor is g.app.leoDir

**Comment by tbnorth** [comment]
Another option would be to have get_UNL replace /some/path/somewhere with {{g.app.leoDir}} as appropriate.

**Comment by edreamleo** [comment]
There is less need for this now that UNL's have been simplified.
