### ISSUE TITLE
Disappearing +/- expansion boxes in outline

### ISSUE THREAD

**Issue by JohnLunzer** [leo-editor/leo-editor#190]
Create a node with a child and then a child to that child. Make sure everything is expanded. Contract only the parent node. Now copy the parent node and paste the parent node. Before expanding the newly pasted parent node change the headline. Now expand the pasted node with the headline changed and you will see a child node that appears to have no child. If you contract and expand this node again you will see all three nodes rather than just the two previously seen.

**Comment by tbnorth** [comment]
On Mon, 11 May 2015 03:23:50 -0700
John Lunzer <notifications@github.com> wrote:

> Create a node with a child and then a child to that child. Make sure
> everything is expanded. Contract only the parent node. Now copy the
> parent node and paste the parent node. Before expanding the newly
> pasted parent node change the headline. Now expand the pasted node
> with the headline changed and you will see a child node that appears
> to have no child. If you contract and expand this node again you will
> see all three nodes rather than just the two previously seen.

Although the recipe was entertaining, it didn't work for me:

Leo Log Window
Leo 5.1-final, build 20150510115755, Sun May 10 11:57:55 CDT 2015
Git repo info: branch = master, commit = 7654f923e811
Python 2.7.6, PyQt version 4.8.6
linux2

Expanding the copied edited parent showed the two levels of children,
expanded.

This is probably really sensitive to OS and Qt versions.

Cheers -Terry

**Comment by JohnLunzer** [comment]
I'm on:

** isPython3: False
Leo 5.1-final, build 20150430065234, Thu Apr 30 06:52:34 CDT 2015
Git repo info: branch = master, commit = 6325d1c54d1b
Python 2.7.8, PyQt version 4.8.6
Windows 7 AMD64 (build 6.1.7601) SP1

This could definitely be isolated to the windows version of Qt.

**Comment by edreamleo** [comment]
On Mon, May 11, 2015 at 5:23 AM, John Lunzer <notifications@github.com>
wrote:

> Create a node with a child and then a child to that child. Make sure
> everything is expanded. Contract only the parent node. Now copy the parent
> node and paste the parent node. Before expanding the newly pasted parent
> node change the headline. Now expand the pasted node with the headline
> changed and you will see a child node that appears to have no child. If you
> contract and expand this node again you will see all three nodes rather
> than just the two previously seen.
>
​Many thanks for this research.  As you know, I've been busy with other Leo
matters lately.  I'll look into this asap.

If it's a Windows only issue it may not be possible to fix directly.  It
may be worth a Qt bug report in that case.

EKR

**Comment by JohnLunzer** [comment]
Not worries. I made a new finding in this which refines the behavior and may help debug it. 

For completeness I'll copy the previous procedure and add in bold which part is slightly different:

Create a node with a child and then a child to that child. Make sure everything is expanded. Contract only the parent node. Now copy the parent node and paste the parent node. Before expanding the newly pasted parent node ~~change~~ ***double click on*** the headline. ***No change is necessary, hit enter or click on another node to end editing headline. Very important, this bug does not occur if you edit the headline via Ctrl-H.*** Now expand the pasted node with the headline changed and you will see a child node that appears to have no child. If you contract and expand this node again you will see all three nodes rather than just the two previously seen.

To further guide debugging efforts. Has anyone ever noticed that there is a visual difference between double clicking on a node and using Ctrl-H? When you double click the entire node line is highlighted. Using Ctrl-H just the headline text is highlighted. Perhaps the quick fix to this bug is to make double clicking on a headline do the same thing as using Ctrl-H. From the behavior it seems like there are two different bits of code responsible for doing the same action.

**Comment by JohnLunzer** [comment]
Another tidbit, this behavior appears to be purely visual and not functional. Using the keyboard I can still navigate into the nodes despite the tree not updating!

**Comment by JohnLunzer** [comment]
This bug no longer occurs based on the directions I've given. Now upon paste the node fully expands with no missing nodes. I'm going to close this until it pops up again.

**Comment by edreamleo** [comment]
On Wed, Nov 18, 2015 at 6:44 AM, John Lunzer <notifications@github.com>
wrote:

> This bug no longer occurs based on the directions I've given. Now upon
> paste the node fully expands with no missing nodes. I'm going to close this
> until it pops up again.
>

​Thanks for following up on this.

EKR
