### ISSUE TITLE
distutils is deprecated and will be removed

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#1909]
I don't know if Leo uses _distutils_ in any way, but in case it is involved in creating install packages, it has been deprecated and will be removed in Python 3.12.  See

[PEP 632 -- Deprecate distutils module](https://www.python.org/dev/peps/pep-0632/)

**Comment by edreamleo** [comment]
On Tue, Apr 27, 2021 at 10:38 PM tbpassin ***@***.***> wrote:

> I don't know if Leo uses *distutils* in any way, but in case it is
> involved in creating install packages, it has been deprecated and will be
> removed in Python 3.12. See
>
> PEP 632 -- Deprecate distutils module
> <https://www.python.org/dev/peps/pep-0632/>
>

Thanks for this link. Afaik, Leo does not use distutils in any way.

Edward

**Comment by maphew** [comment]
I removed the last vestiges of distutils from setup.py a few years ago, so no Leo isn't using it. However `viewrendered.py` has a reference.

```lang-shell
>findstr -s -i "distutil" *
ekr-spellpyx.txt:distutils
leo\dist\leo-install.py:@url http://docs.python.org/2.7/distutils/builtdist.html#creating-windows-installers
leo\doc\LeoReleaseNotes.leo:<t tx="ekr.20150313054219.320">Apparently distutils.file_util is not present in all Python distributions!
leo\doc\LeoReleaseNotes.leo:    - Fall back on code in distutils.file_util if import fails.
leo\plugins\viewrendered.py:from distutils.spawn import find_executable
setup.py:import setuptools # Always prefer setuptools over distutils.
```

**Comment by tbpassin** [comment]
I found out from the Python lists that find_executable was considered for internal use only.  It did some tricky things that were put in for distutils, and no one wanted to try to change it.

**Comment by edreamleo** [comment]
@maphew Good catch re distutils in viewrendered.py. I have just assigned this issue to 6.5.  I'll fix this issue in 6.4 only if the there is a very simple alternative to distutils.find_executable.

**Comment by edreamleo** [comment]
According to the [Migration advice](https://www.python.org/dev/peps/pep-0632/#migration-advice) in PEP 632 the alternative to distutils.spawn.find_executable is shutil.which.

This test script:
```python
import distutils
import shutil
for module in ('asciidoctor', 'asciidoc3', 'pandoc'):
    print(distutils.spawn.find_executable(module))
    print(shutil.which(module))
```
shows that none of the modules are installed on my machine! Usually pylint complains Leo complains if a third-party import does not exist on my machine, but naturally pylint doesn't track calls to distutils.spawn.find_executable.

In any event, I'll go ahead and change to shutil.which in viewrendered.py.

**Comment by edreamleo** [comment]
@tbpassin Thomas, please change VR3 whenever you like.

**Comment by tbpassin** [comment]
Here's something that works.  I wrote it up while working on VR3:

```
def find_exe(exename):
    """Locate an executable and return its path.
    
    Works for Windows and Linux.  Works whether or not a virtual
    environment is in effect.
    
    Finds executables that are in:
        - the Python Scripts directory;
        - the system path.
        
    ARGUMENT
    exename -- the name of the executable file to find.
    
    RETURNS
    the full path to the executable as a string, or None.
    Returns None if the found executable is not marked as executable.
    """

    # Works for Linux and Windows
    venvdir = os.getenv("VIRTUAL_ENV")
    if venvdir:
        scriptsdir = os.path.join(venvdir, 'Scripts')
    else:
        scriptsdir = os.path.join(os.path.dirname(sys.executable), 'Scripts')

    exe = shutil.which(exename, os.X_OK, scriptsdir) or \
          shutil.which(exename, os.X_OK)

    return exe
```

It takes into account if you are running in a virtual environment, and also that some of the programs you want to find may be in the Python Scripts directory.  As I look at it now after a year or two, I see that it could miss scripts that are in the **user's** Scripts directory, but that would be easy to fix (It does find scripts in Python's system Scripts directory).
