### ISSUE TITLE
Leo doesn't start with Python 3.4

### ISSUE THREAD

**Issue by benzolius** [leo-editor/leo-editor#191]
There are 2 problems:

1. print statement - easy to fix:

diff --git a/leo/external/PythonTidy.py b/leo/external/PythonTidy.py
index 760a165..04bc959 100644
--- a/leo/external/PythonTidy.py
+++ b/leo/external/PythonTidy.py
@@ -5519,9 +5519,9 @@ class NodeYield(Node):
 def main():
 
     if DEBUG:
-        print 'Begin doctests.'
+        print('Begin doctests.')
         doctest.testmod()
-        print '  End doctests.'
+        print('  End doctests.')
     if len(sys.argv) > 1:
         file_in = sys.argv[1]
     else:

2. no module 'compiler' - I don't know the solution yet:

zke@nightly:/leo/leo-editor$ python3 launchLeo.py
setting leoID from os.getenv('USER'): 'zke'
reading settings in /home/leo/leo-editor/leo/config/leoSettings.leo
Traceback (most recent call last):
  File "launchLeo.py", line 8, in <module>
    leo.core.runLeo.run()
  File "/home/leo/leo-editor/leo/core/runLeo.py", line 78, in run
    g.app.loadManager.load(fileName,pymacs)
  File "/home/leo/leo-editor/leo/core/leoApp.py", line 2821, in load
    lm.doPrePluginsInit(fileName,pymacs)
  File "/home/leo/leo-editor/leo/core/leoApp.py", line 2885, in doPrePluginsInit
    lm.readGlobalSettingsFiles()
  File "/home/leo/leo-editor/leo/core/leoApp.py", line 2770, in readGlobalSettingsFiles
    commanders = [lm.openSettingsFile(path) for path in paths]
  File "/home/leo/leo-editor/leo/core/leoApp.py", line 2770, in <listcomp>
    commanders = [lm.openSettingsFile(path) for path in paths]
  File "/home/leo/leo-editor/leo/core/leoApp.py", line 2744, in openSettingsFile
    c = g.app.newCommander(fn)
  File "/home/leo/leo-editor/leo/core/leoApp.py", line 1865, in newCommander
    import leo.core.leoCommands as leoCommands
  File "/home/leo/leo-editor/leo/core/leoCommands.py", line 40, in <module>
    import leo.external.PythonTidy as tidy
  File "/home/leo/leo-editor/leo/external/PythonTidy.py", line 143, in <module>
    import compiler
ImportError: No module named 'compiler'

**Comment by edreamleo** [comment]
Fixed at 6aa2937.  That is, Leo now loads with Python 3. The beautify commands are mostly do-nothings with Python 3. 

There may be some tricky issues involved in porting the code to Python 3. Furthermore, it's not clear that Leo should be using PythonTidy at all...

Nobody is downloading PythonTidy these days.  Instead, in the last month there have been 29,194 downloads of [autopep8](https://pypi.python.org/pypi/autopep8/1.1.1) and 828,954 downloads of [pep8](https://pypi.python.org/pypi/pep8).

Otoh, the PythonTidy codes now does almost everything I want it to without requiring that people install other packages.  Stay tuned.

**Comment by benzolius** [comment]
Thanks for the prompt fix.

**Comment by edreamleo** [comment]
Here is the checkin log for rev 234e39c:

    I am going to cut my losses and declare that he port of PythonTidy.py to Python 3 has failed.
    I plan to use PythonTidy to beautify Leo's code and then transition to autopep8 for further work.
    The code now simply issues a warning and does nothing if g.isPython3 is True.

Disappointing that so much recent work will soon be thrown away, but there seems to be no alternative.  Otoh, applying autopep8 to external files rather than outlines seems like a much more elegant way in the long run.

**Comment by tbnorth** [comment]
On Wed, 20 May 2015 08:25:16 -0700
"Edward K. Ream" <notifications@github.com> wrote:

> Disappointing that so much recent work will soon be thrown away, but
> there seems to be no alternative. Otoh, applying autopep8 to external
> files rather than outlines seems like a much more elegant way in the
> long run.

Unfortunate.  So applying autopep8 to external files - that's not
compatible with @file, is it?  Unless Leo's sentinels have no impact on
autopep8, in which case I guess that's fine.  @clean would work, of
course :-)

Cheers -Terry

**Comment by benzolius** [comment]
I think, Leo's sentinels cannot impact autopep8 or any pep8 related tool, because they are only comments without any code on their line.

Cheers
Zoltan

**Comment by edreamleo** [comment]
​​
On Wed, May 20, 2015 at 10:33 AM, tbnorth <notifications@github.com> wrote:

>
> > Disappointing that so much recent work will soon be thrown away, but
> > there seems to be no alternative.
> ​..​
>
>
> Unfortunate. So applying autopep8 to external files - that's not
> compatible with @file, is it?


​autopep8 does work on external files with sentinels. The following fixers
should be disabled because the sentinels themselves count as blank lines:

E301 - Add missing blank line.
E302 - Add missing 2 blank lines.

A surprise: *autopep8 is about 10x slower than PythonTidy*! This
resuscitates my interest in Tidy.

I'm going to make a project out of porting and improving Tidy. This may
take a day or six, but what the heck. It's a project that I'll enjoy. BTW,
2to3 was no help at all.

The class AstFullTraverser class in leoAst.py may be a way to speed up and
simplify the code.  We shall see.  But first, there are some mundane
porting tasks to do.  Patience will be essential.

Edward
