### ISSUE TITLE
at.checkDerivedFile does not expand "~" correctly

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#1910]
The recent changes to expand "\~" in file paths apparently have not rippled through to _at.checkDerivedFile()_.  This method is assigned to the _check-derived-file_ command.  Otherwise the method doesn't seem to be called anywhere in LeoPyRef.  I don't know how the command is used, but it should be fixed to handle "~" correctly unless it really isn't going to be used.

**Comment by edreamleo** [comment]
Renamed the command to be "check-external-file". The term "derived file" is obsolete.
