### ISSUE TITLE
no command function for 'fully-expand-xxx-pane'

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#1921]
Leo Log Window
Leo 6.4-devel, devel branch, build 7aa7adfe0c
2021-05-02 13:10:32 -0500
Python 3.7.3, PyQt version 5.12.1
darwin

```
no command function for 'fully-expand-log-pane'
no command function for 'fully-expand-body-pane'
no command function for 'fully-expand-outline-pane'
no command function for 'fully-expand-pane'
```

**Comment by edreamleo** [comment]
Leo no longer has these commands. Did you perhaps define @command or @button nodes that use them?

**Comment by wangzhaohe** [comment]
oh, I used the old Menu in my-leo-settings.leo.  Thanks for you kind help!
