### ISSUE TITLE
viewrendered3 can not be loaded since ed1a1bd0205b5dded67d39a79d1ab5c24782e5f7

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#1928]
viewrendered3 plugin can not be loaded since ed1a1bd0205b5dded67d39a79d1ab5c24782e5f7

**Comment by edreamleo** [comment]
@wangzhaohe 

The devel branch contains this line in c.scanAllDirectives:

`default_language = g.getLanguageFromAncestorAtFileNode(p) or c.target_language or 'python'`

This should fix the problem.  If not, please run Leo from a console and report any error messages.

**Comment by wangzhaohe** [comment]
Still no viewrendered3 plugin, and no error in shell print message.

Leo Log Window
Leo 6.4-devel, devel branch, build 00481e4fb5
2021-05-10 16:45:10 -0500
Python 3.7.3, PyQt version 5.12.1
darwin

leoAtFile.py debug value:
```
d = c.scanAllDirectives(p)
{'delims': ('#', '', ''), 'comment': None, 'encoding': None, 'language': 'python', 'lang-dict': {}, 'lineending': None, 'pagewidth': 132, 'path': '/Users/swot/.leo', 'tabwidth': -4, 'wrap': None}
```

**Comment by edreamleo** [comment]
@wangzhaohe It's hard to believe that commit the commit you reference could cause any problem:

- The values returned by c.scanAllDirectives look correct. It's hard to see how they could cause problems in VR3.
- VR3 works for me.

Please do a `git bisect` to see what rev first causes the problems you see.

I'll review VR3 for recent changes that might cause it not to load. However, I do not to change VR3. It's not my code.

**Comment by tbpassin** [comment]
It's also working for me on Windows at

```
Leo 6.4-devel, devel branch, build ff646ab77f
2021-05-11 10:22:28 -0500
Python 3.9.5, PyQt version 5.15.2
Windows 10 AMD64 (build 10.0.19042) SP0
```

**Comment by wangzhaohe** [comment]
@tbpassin 

>Do you mean that the VR3 window does not open?

+ Yes. no VR3 command

>How are you trying to open it?

+ Use vr3 command

>Is VR3 listed in the Plugins menu?

+ No. Bellow image is Plugins Menu

<img width="178" alt="image" src="https://user-images.githubusercontent.com/2628013/117916959-c032ac00-b31a-11eb-9542-31daeb80a3ae.png">

>Are you using QT5, and if so what version (the version is not likely to matter, but worth checking anyway)

After `pip install -U pyqt5`
```
Leo Log Window
Leo 6.4-devel, devel branch, build ff646ab77f
2021-05-11 10:22:28 -0500
Python 3.7.3, PyQt version 5.15.2.  
darwin
```

**Comment by wangzhaohe** [comment]
Solved!

Install python 3.9.5
install PyQt 5.15.2
***
Leo Log Window
Leo 6.4-devel, devel branch, build ff646ab77f
2021-05-11 10:22:28 -0500
Python 3.9.5, PyQt version 5.15.2
darwin

**Comment by edreamleo** [comment]
On Wed, May 12, 2021 at 12:12 AM wangzhaohe ***@***.***>
wrote:

> Solved!
>
> Install python 3.9.5
> install PyQt 5.15.2
>
:-)

Edward
-----------------------------------------------------------------
Edward K. Ream: ***@***.***
An old man, crazy about computer programming.
Leo Editor: http://leoeditor.com/
-----------------------------------------------------------------

**Comment by tbpassin** [comment]
I'm glad it's working, but I didn't knowingly use any Python construction that's not in Python 3.7.  I wonder if that means that somewhere else in Leo's code there is such a construct.

**Comment by tbpassin** [comment]
I just installed Python 3.7, and I too found that VR3 didn't load.  That's a surprise to me because it used to.  I hate to spend time in tracking this down, but I also don't think users should be required to use Python 3.9, since there is nothing that really needs it.
