### ISSUE TITLE
goto-global-line doesn't work properly in @clean files

### ISSUE THREAD

**Issue by vitalije** [leo-editor/leo-editor#193]
similar bug as #138 but since it was solved and still is regarding @nosent files, I opened a new one with corrected title.

The same [example file](https://groups.google.com/group/leo-editor/attach/63f325cf79f6b2e9/nosent-goto-line-bug.leo?part=0.1) could demonstrate the problem, just turn @nosent file in @clean and goto-global-line command won't find the requested line.

**Comment by edreamleo** [comment]
Thanks for this.  I'll fix this soon.

**Comment by edreamleo** [comment]
Fixed at 5cab2da.  Please reopen if there are further problems.
