### ISSUE TITLE
Devel Changeset bc81c74c1020cdcfde453ee4a54f78010975ac68 Won't run With Python 3.7

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#1939]
This is today's commit that fixes an error in VR3.

Launching Leo, all I get is a console message ``Can not Import Qt`` and a bare Qt window saying the same.  No Leo window at all.

With Python 3.9, Leo launches normally.

~~~Leo 6.4-devel, devel branch, build bc81c74c10
2021-05-14 15:40:15 -0500
Python 3.9.5, PyQt version 5.15.2
Windows 10 AMD64 (build 10.0.19042) SP0
~~~

The only place this message occurs in the codebase is in ``app.createQtGui``

**Comment by edreamleo** [comment]
@tbpassin Presumably you forgot to install Qt on your Python 3.7 installation.

**Comment by tbpassin** [comment]
Hah!  I had added my Git Leo directory to the PYTHONPATH by force of habit.  I forgot I hadn't actually installed Leo yet to Python37.  When it tried to run and enough loaded to give that error message, I assumed without realizing that Leo had actually been installed.  (Blushes)

So now I have indeed installed Leo, and of course it runs as expected.

**Comment by edreamleo** [comment]
@tbpassin Thanks for the confirmation :-)
