### ISSUE TITLE
Find Next **button** doesn't highlight body text

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#194]
From Lewis: in [leo-editor](https://groups.google.com/d/msg/leo-editor/aYIwGrc2qjw/XVLWUxj0P2IJ)

Find-Next highlights text in a node headline, but fails to find text in the body pane.

1. Open Leo file.
Create a node 'test_node' and add body text 'test_node'.
Search for 'test_node' using mouse-click on button Find Next: F3 highlights 'test_node' headline but not the body pane. 
Using the F3 key works correctly.

2. However the search works if the body text is different from the node headline. Change the body text to be 'test_nodeX'.
Searching for 'test_nodeX' using button Find Next: F3 highlights 'test_nodeX' in the body  pane.
Again, using the F3 key works fine.

Leo Log Window
Leo 5.1-final, build 20150516042024, Sat May 16 04:20:24 CDT 2015
Git repo info: branch = master, commit = b0a56ab68a9b
Python 3.4.3, PyQt version 4.8.6
Windows 7 AMD64 (build 6.1.7601) SP1

**Comment by edreamleo** [comment]
My reply:

Clicking a button causes problems because it destroys focus.  ​I would really like to get rid of the find buttons :-)  Hmm.  Maybe a help button would be useful instead.

**Comment by edreamleo** [comment]
Lewis's reply:

I was about to ask are you sure it's focus? In case 1, where the body text exactly matches the node text, the text is not found. However in case 2 the text is found straight away.

But you may be right about the focus :)
Follow case 1, but with an extra step:
1.  Open Leo file.
Create a node 'test_node' and add body text 'test_node'.
Search for 'test_node' using one mouse-click on button Find Next: F3 highlights 'test_node' headline.
Apply a second mouse-click on button Find Next: F3 'test_node' is not found in the body pane. As the text was not found you are switched from the Find Tab to the Log Tab, and you see a message "not found 'test_node'".
(Extra step) Now switch back to the Find Tab and resume your search with another mouse-click on button Find Next: F3
It has now worked successfully and highlights 'test_node' in the body pane.

This behaviour seems reminiscent to the final comment by Chris George in discussion Ctrl-F focus inconsistent.

**Comment by LewisNeal** [comment]
The Find Previous: F2 **button** does work properly though.

Regards
Lewis

**Comment by edreamleo** [comment]
> F2 button does work properly though.

That is to be expected, due to the order in which Leo searches headlines and bodies.

**Comment by edreamleo** [comment]
I am going to mark this as "won't fix" because there is no obvious way to remember when focus is in the headline *just before* the find-next button is going to be pushed.

The "solution" would be to eliminate the buttons in the find tab and have all uses use F2, F3, etc.

**Comment by edreamleo** [comment]
I am going to close this because it has the wontfix label.
