### ISSUE TITLE
Add mypy annotations and stub files

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#1944]
See PR #1948, the ekr-annotate branch.

**Status**

The ekr-annotate branch contains the *minimal* annotations and suppressions necessary so that mypy will pass all of Leo's core files, including Leo's most important plugins.

**The ekr-annotate branch *will* be merged into devel**. Merging annotations into devel is reasonable now because of the "wax-off" script. See below. 

- [x] Add annotations and suppressions or eliminate all mypy errors.
- [x] Fully annotate leoNodes.py.
- [x] Fully annotate leoAst.py.
- [x] Complete the "wax-off" script. Using this script:
    - [x] Create stub files for those files containing annotations in function/method signatures.
    - [x] Remove all annotations from function/method signatures.

**Won't do now**

- I will **not** use a [mypy plugin](https://mypy.readthedocs.io/en/stable/extending_mypy.html#extending-mypy-using-plugins) to tell mypy about Leo's naming conventions.
- Fully annotate leoGlobals.py.
- Annotate the public entry points in leoCommands.py.
- w should only refer to wrapper (TextMixin) objects.
- qw should refer to widget (QWidget) objects.

Creating all these annotations in the text would be a lot of work:

- cff `^def .*\bs\b` finds 544 nodes.
- cff `^def .*\bw\b` finds 141 nodes.
- cff `^def .*\b(i|j|k|n)\b` finds 291 nodes.

Happily, mypy doesn't need this much help!

**Comment by tbpassin** [comment]
This is the kind of thing that is best done for new code, and old code only when some other work is done on it.

**Comment by edreamleo** [comment]
@tbpassin The forthcoming mypy plugin, leo_mypy_plugin.py, promises to support Leo's common abbreviations without changing Leo's code at all.

We would then use annotations only for rare (or non-existent) special cases.
