### ISSUE TITLE
show-settings does not show F-keys

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#1972]
In certain outlines I set key bindings to F6 - F8.  These bindings are not included in the list of bindings for that outline.  Instead, they are omitted from the listing entirely.  In the list of key bindings for other outlines where these bindings are not set, they appear as "do-nothing", as expected.

Example showing missing keys:

```
  all : Ctrl+F3        double-click-icon-box
  all : Ctrl+F4        close-window
  all : Ctrl+F5        do-nothing
  all : Ctrl+F9        do-nothing
```
Note that Ctrl-F6 through Ctrl-F8 are missing.  The corresponding bindings for another outline where these keys are not assigned:

```
  all : Ctrl+F4        close-window
  all : Ctrl+F5        do-nothing
  all : Ctrl+F6        do-nothing
  all : Ctrl+F7        do-nothing
  all : Ctrl+F8        do-nothing
  all : Ctrl+F9        do-nothing
```

**Comment by edreamleo** [comment]
@tbpassin How did you assign the bindings to Ctrl-F6 through Ctrl-F8?

**Comment by edreamleo** [comment]
I have assigned this for Leo 6.4, but there are no guarantees.

**Comment by tbpassin** [comment]
E.g., in a specific outline in the @settings tree -

`@command my-command @key=Ctrl+F6`

The key assignment works, it's just not getting shown in the listing of bindings.

Clearly it's not a high-priority kind of thing, but at some point it should work right..

**Comment by edreamleo** [comment]
On Fri, Jun 11, 2021 at 1:02 PM tbpassin ***@***.***> wrote:

> E.g., in a specific outline in the @settings tree -
>
> @command my-command @key=Ctrl+F6
>
> The key assignment works, it's just not getting shown in the listing of
> bindings.
>
Thanks, you have confirmed my suspicions. This issue should be fairly easy
to fix.

Edward
