### ISSUE TITLE
Rename of Qt enums in PyQT 6.1

### ISSUE THREAD

**Issue by maparent** [leo-editor/leo-editor#1973]
Unfortunate churn in enum names, basically removing final 's'

QtCore.Qt.DropActions           => QtCore.Qt.DropAction
QtCore.Qt.ItemFlags             => QtCore.Qt.ItemFlag
QtCore.Qt.KeyboardModifiers     => QtCore.Qt.KeyboardModifier
QtCore.Qt.Modifiers             => QtCore.Qt.KeyboardModifier
QtCore.Qt.MouseButtons          => QtCore.Qt.MouseButton
QtCore.Qt.Orientations          => QtCore.Qt.Orientation
QtCore.Qt.TextInteractionFlags  => QtCore.Qt.TextInteractionFlag
QtCore.Qt.ToolBarAreas          => QtCore.Qt.ToolBarArea
QtCore.Qt.WindowFlags           => QtCore.Qt.WindowType
QtCore.Qt.WindowStates          => QtCore.Qt.WindowState

**Comment by edreamleo** [comment]
On Fri, Jun 11, 2021 at 7:58 AM Marc-Antoine Parent <
***@***.***> wrote:

> Unfortunate churn in enum names, basically removing final 's'
>
Thanks for this. The original names were too confusing, so these changes
make some kind of sense.  Still, the Qt people are showing way too little
concern for breaking existing code.

Do you have a link to the announcement? Supporting *both* sets of names is
likely to be ugly.

Edward
