### ISSUE TITLE
Settings/Open A Theme File Fails if Spaces In Path To Python

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#1974]
The line that fails is in `commands/commanderFileCommands/Themes/c_file.open_theme_file`:

`command = f'{g.sys.executable} {g.app.loadDir}/runLeo.py "{fn}"'`

If Python is installed to _Program Files_, as mine is, the line fails because of the spaces in the path to Python.  A version that works is

`command = f'"{g.sys.executable}" "{g.app.loadDir}/runLeo.py" "{fn}"'`

I added quotation marks around the _runLeo_ parameter too, just in case it should contain spaces.  I forget if Linux wants single or double quotes here.

**Comment by tbpassin** [comment]
Python got installed to _Program Files_ on my latest install because I chose to make it available to "All Users". This is on Windows, of course.  If you install for a single user, it goes into _Users\\<user\>\Appdata\Local\Programs\Python\Pythonxx_, which usually would not have spaces in the path.

Note that if Python is in _Program Files_, if you want to pip-install packages so all users can use them, you need to run _pip_ from a console with admin privileges.  That's more or less equivalent to using _sudo_ in Linux.

**Comment by edreamleo** [comment]
@tbpassin Thanks, Thomas.
