### ISSUE TITLE
Find tab 'ignore case' tick box has no effect

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#198]
Using the standard Find panel 'ignore case' tick box has no effect.

Body text:
box
Box
BOX

A search for box only finds box.
A search for boX reports "not found: "boX"

Leo Log Window
Leo 5.1-final, build 20150619193204, Fri Jun 19 19:32:04 CDT 2015
Git repo info: branch = master, commit = 0a37a8212810
Python 3.4.3, PyQt version 5.4.2
Windows 7 AMD64 (build 6.1.7601) SP1

**Comment by edreamleo** [comment]
Thanks for this report!  Rev 5a38f6c fixes several issues, including yours.  Here is the checkin log:

```
 Several improvements re the new Find Dialog.
    1. After further review, imo the Find Dialog should stay visible until the user closes (hides) it.
       As a result, the default for @bool close-find-dialog-after-search is False in leoSettings.leo.
    2. Fixed several problems with auto-set-ignore-case logic:
    - The logic is now in find.update_ivars.  That is, it executes just before running the command.
    - The ignore-case checkbox is turned off only for mixed-case search strings.
      This follows common practice.
```

I'll close this issue now.  Please reopen if you find more problems.

**Comment by LewisNeal** [comment]
Edward,
Thanks for improving this function.
However there is another bug related to using the 'ignore case' tick box.
In the box examples given, a search for boX reports "not found: "boX" but it also immediately switches off the 'ignore case' tick box, and subsequent search conditions are changed without user requesting it.
I don't have rights to reopen issues so I hope you see this.

 Leo 5.1-final, build 20150620103657, Sat Jun 20 10:36:57 CDT 2015
 Git repo info: branch = master, commit = 82edcda7fd6c
 Python 3.4.3, PyQt version 5.4.2
 Windows 7 AMD64 (build 6.1.7601) SP1

Lewis

**Comment by edreamleo** [comment]
@LewisNeal Thanks for this.  I'll fix this.

**Comment by edreamleo** [comment]
Fixed at 18e0de.  There are tricky issues involved, and it's possible that some edge cases remain.  Please reopen if necessary.  However, the present code is a great improvement over the old.

Furthermore, recent revs greatly improve the reporting of both failed and successful searches.  The status line indicates what setters were in effect.  Reporting the settings for *successful* searches is an important improvement.

**Comment by LewisNeal** [comment]
Edward,

The present code is a great improvement over the old :)
Reports in the status line, including the (ignore case) condition are most helpful.
A search for box or BOX works fine.

Here are some of those edge cases ;)
A search for boX , bOx , bOX , BOx or BoX fails. Leo reports not found: "boX", and also immediately switches off the 'ignore case' tick box. So it doesn't cope with mixed capitalisation. 
If I deselect the 'ignore case' tick box and resume the search, leo switches it back on and continues to 'ignore case'.

Leo Log Window
Leo 5.1-final, build 20150623055401, Tue Jun 23 05:54:01 CDT 2015
Git repo info: branch = master, commit = 6cb2cebcba13
Python 2.7.10, PyQt version 4.8.7
Windows Vista x86 (build 6.0.6002) SP2

Regards
Lewis

**Comment by edreamleo** [comment]
@LewisNeal 
> A search for boX , bOx , bOX , BOx or BoX fails. Leo reports not found: "boX", and also immediately switches off the 'ignore case' tick box. So it doesn't cope with mixed capitalization. 

Everything appears to work properly with the present code, so I'm keep this issue closed.

**Comment by LewisNeal** [comment]
What is your windows setup? I'm interested in the PyQt version you are using.
Is it PyQt version 4.8.7 or 5.4.2 ?

**Comment by edreamleo** [comment]
On Sun, Jul 5, 2015 at 5:03 AM, LewisNeal <notifications@github.com> wrote:

> What is your windows setup? I'm interested in the PyQt version you are
> using.
> ​ ​
> Is it PyQt version 4.8.7 or 5.4.2 ?
>
> ​Both:​
​Python 2.7.4, PyQt version 4.8.6
Python 3.4.0, PyQt version 5.3.0

EKR
