### ISSUE TITLE
@bool use-focus-border = True or False has no effect

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#1987]
It seems that @bool `use-focus-border` has no effect with True or False

Is this setting useless?

Leo Log Window
Leo 6.4-devel, devel branch, build 970deeee57
2021-06-17 09:34:04 -0500
Python 3.9.5, PyQt version 5.15.2
darwin

**Comment by edreamleo** [comment]
This setting no longer appears in leoSettings.leo, and no part of Leo's core uses the setting.

There is a comment saying that this setting has been replaced by style sheets.
