### ISSUE TITLE
Change Themes Without Restart

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#1989]
Leo doesn't seem to have a way to change themes without restarting.  You can come close by loading the desired theme outline, but sometimes it seems that some features don't get fully picked up in all tabs.  And anyway, having to find and load a new theme outline into a new tab seems unnecessarily annoying just to change themes.

I think that a new "Apply Theme" menu item or command should present the user with a list of themes in all the places that Leo normally looks for themes, with the possibility for browsing elsewhere in case the user is developing a new theme outside of those locations.

**Comment by wangzhaohe** [comment]
Yes, need a way to refresh theme easily. I use this way

1. open a theme .leo file to change it.
2. use command `open-theme-file` to check the result. Note: I will wait for the splash time pass.
3. close opened theme file in step 2.
4. change theme file in step 1.
5. Again and Again ...

**Comment by tbpassin** [comment]
That's what I do, but if one theme does not set a style that another one does, the old one remains in effect.  For example, I have ended up with the log pane unreadable (dark blue on black)

**Comment by edreamleo** [comment]
I am going to assign this issue to 6.5. It's too late for big changes to 6.4.

**Comment by tbpassin** [comment]
That's fine by me.  It looks like almost all the hooks are there in the code.  The code for Reload Settings/ Reload-Style-Sheets sets it all up but for some reason ends just at the point where the action would actually take place.  I assume there turned out to be something tricky about it.

The other odd thing I have noticed is that if I open the outline for a theme, it seems to take effect except that the log pane colors end up some kind of mix between old and new.

**Comment by edreamleo** [comment]
@tbpassin Thanks for these remarks.  Stylesheets are difficult to debug because to my knowledge there are no Qt tools similar to browser debug windows.

**Comment by tbpassin** [comment]
With a QWebView you can open Chrome's debugging tools, but I don't remember seeing anything like that for other widgets.
