### ISSUE TITLE
Theme color help for QTreeView

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#1992]
I want get help for QTreeView color setting, please teach me how to set them, thanks!

## Below is focused QTreeView

I don't know how to set this focused color.

![image](https://user-images.githubusercontent.com/2628013/122647319-45994f80-d156-11eb-8721-da400e6d9520.png)

## Below is unfocued QTreeView

I don't know how to set unfocused color 1, 2, 3.

![image](https://user-images.githubusercontent.com/2628013/122647382-990b9d80-d156-11eb-9804-d262cff4674b.png)

**Comment by edreamleo** [comment]
@wangzhaohe My apologies for the delay in responding.

In your theme file, create entries for

QTreeView::item:selected and QTreeView::item:active:selected

See the section on QTreeView in the [Qt stylesheet reference](https://doc.qt.io/qt-5/stylesheet-reference.html).

**Comment by edreamleo** [comment]
@wangzhaohe Here is a trick I sometimes use. In the stylesheet, I'll set bright colors, like red, green, yellow etc., for the background color for QWidget, QFrame or any other kind of widget that might influence what you are seeing.
