### ISSUE TITLE
Popup menu in outline pane does not pick theme settings

### ISSUE THREAD

**Issue by toolonely** [leo-editor/leo-editor#1995]
See PR #2079.

See the attached image. Happens in latest stable version (6.3 final).

![menu](https://user-images.githubusercontent.com/77091000/122661848-41d9ed00-d197-11eb-85f6-f4bdb6e1cae5.jpg)

**Comment by tbpassin** [comment]
All I ever get is a message "No Popup Handlers".  I didn't know that there are any right-click items.

**Comment by edreamleo** [comment]
@tbpassin See the contextmenu plugin.

**Comment by edreamleo** [comment]
I may as well fix this issue while fixing related issues.

**Comment by edreamleo** [comment]
Fixing this bug makes Leo look much better!

In general, the fix is to make menus child of, say, c.frame.top. That way the child menu inherits the parent's stylesheet.  However, this doesn't always work directly, because child menus appear in the wrong place.
