### ISSUE TITLE
rst3 Command Should Ensure A Blank Line At The End Of Every Node

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#1996]
ReStructured Text usually requires a blank line between sections and blocks of all kinds.  It one is missing, either the display or some functionality like navigation links may not work right.

It is easy to forget to end a node with a blank line.  The rst3 command does not make sure a body's text ends with a blank line.  In some cases *two* blank lines seem to be needed.  For my own use I have fixed that by writing a body filter that does ensure a blank line, instantiating my own instance of the  command's class, and registering my filter.

I propose that rst3 should always make sure a body ends with a blank line, inserting one into its output if needed.

**Comment by edreamleo** [comment]
@tbpassin I'm surprised that rst3 doesn't already do this.  Imo, it should.

**Comment by tbpassin** [comment]
I am too, but I couldn't get my experimental zettel outline to work right because of it.  It was clear in the .rst output of the command.

**Comment by edreamleo** [comment]
@tbpassin Please send an example outline that illustrates the problem.  As I read the code, the compute_result method should ensure two newlines between every node.

Are you using any user filters?

**Comment by tbpassin** [comment]
I only started using a filter after it didn't work without one.

**Comment by tbpassin** [comment]
I haven't been able to come up with an example.  And I remember that I suspected an incorrect newline character in a few places (Linux vs Windows, for example).  In those places, when I deleted the blank line in question and hit ENTER, that particular problem cleared up.  

I don't know how that could have happened, because this outline I've been working on has only ever been on Windows, and it hasn't even gone through Git.  I also know that after this discover, I went through all the nodes and added blank lines.  Then everything worked.  After I got my filter working, I went back and deleted some of the blank lines for testing.  Everything still worked.

So right now it seems as if some non-Windows blank lines got in there, how being unknown, and now they are gone because of my manual work.  I don't know how to conveniently put some in to verify the guess.

I'm not sure what should happen if there are mix-and-match line endings...

**Comment by tbpassin** [comment]
Aside from this (apparently) non-problem, I'm having a problem with rst3 in which it isn't always choosing title underlining symbols that give the right nesting when run with Sphinx.  This also seems to cause some internal links not to work.  However, VR3 *does* get this right, at least for my example tree.

To help diagnose this, I have added a new command to VR3 to export the generated markup to a text editor.  One can then save it to a file that Sphinx is set up to render, or just inspect the markup as is.

Once I've got my test outlines and examples finalized (and I verify the results), I'll open a new issue about it.

In the meantime I will be doing a PR for this modification to VR3, because it looks like it could be pretty useful in the right circumstances.

**Comment by edreamleo** [comment]
@tbpassin Thanks for your investigations. What I used to call the "cursed newline problem" seems to be less virulent today because of Python's support for [universal newlines.](https://www.python.org/dev/peps/pep-0278/).

For now, I think this issues can be closed.
