### ISSUE TITLE
How to close printing contents in Jupyter QtConsole?

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#1998]
run Leo-editor with `--ipython`

Then when click the headline or type in body, the contents will be printed in the Jupyter QtConsole.

It seems that vr3 do this at line 2450 in viewrender3.py.

    print(result)

I want to know why do this? Only for debug? Or something useful?

**Comment by tbpassin** [comment]
I never noticed that line being still in there!  It should have been removed long ago.  Yes, it would only have been for debugging.  Feel free to remove it, and in the next version (coming soon), it will be gone.

**Comment by tbpassin** [comment]
Fixed in V3.3 with other improvements in devel branch.  See PR  [#1999](https://github.com/leo-editor/leo-editor/pull/1999#event-4929445183)

**Comment by tbpassin** [comment]
This issue has been fixed in devel for some time.

**Comment by edreamleo** [comment]
@tbpassin Thanks!
