### ISSUE TITLE
Documentation/examples: using Leo to manage source projects

### ISSUE THREAD

**Issue by gatesphere** [leo-editor/leo-editor#20]
Just a suggestion for documentation:

Perhaps Leo should include an example directory which has a small Leo-handled project in it (just a few @file nodes, etc) and an example README.me and .gitignore file for github?

I feel like providing a good basis for the .gitignore (and similar) file is more important now that viewrendered2 is slowly taking over for viewrendered, as vr2 puts leo.html, leo.rst, and leo.md files around, which the user most likely does *not* want in their SCM repos.

I know Leo's source and leoPyRef.leo serves as a good example of using Leo to code, but it's scary for first-time users to see such a huge project.  Perhaps just a small hello world application, with some @buttons and @file nodes would be helpful?

I'm imagining something like this for an outline as an example github/python project (bits in parentheses are comments):
```
Startup
    @settings (showing off per-outline settings)
        @string view-rendered-default-kind = md
    Buttons
        @button launch-hello (would run runHello.py below in a console window)
Docs
    @file README.md (showing off viewrendered2.py)
    Useful notes to developers
    To Do
        To Do item 1 (showing off todo.py)
            (clones of applicable code, notes, etc)
        To Do item 2
Auxiliary Files
    @edit .gitignore
Code
    @path hello
        @file __init__.py
        @file world.py
    @file runHello.py
```` 

Would something like this be useful?  The docs could point to this as a stepping-off point for people interested in transitioning to Leo.

**Comment by edreamleo** [comment]
I am going to close this issue.  quickstart.leo renders it moot, imo.
