### ISSUE TITLE
Add more imports to LeoQt6

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#2005]
PR #2048 imported QtSvg. PR #2060 adds the following:

```python
from PyQt6 import QtPrintSupport as printsupport
from PyQt6 import Qsci
import PyQt6.QtSvg as QtSvg
from PyQt6 import uic
```
leoQt6.py no longer even attempts to import webkit-related files.

After `pip install pyqt6` the following imports *do* work, they have been commented out in leoQt6.py:
```python
from PyQt6 import QtDesigner
from PyQt6 import QtOpenGL
from PyQt6 import QtMultimedia
from PyQt6 import QtNetwork
```

**Comment by tbpassin** [comment]
I just found out that even if this import gets fixed, QSvgWidget is not in the library (let's hope this is temporary). I found this out by experimenting, and then found this page which seems to confirm it:

[Missing Bindings](https://wiki.qt.io/Qt_for_Python_Missing_Bindings)

**Comment by edreamleo** [comment]
@tbpassin Thanks for this. It looks like Qt is changing its api about once a month.
