### ISSUE TITLE
pbc.doMenus is mysterious and likely has bugs

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#2009]
mypy highlighted this code. I have no idea what is supposed to do.

At the least, the code must have better comments.

**Comment by LewisNeal** [comment]
Maybe this meassage about doButtons is related.

Leo Log Window
Leo 6.4-devel, devel branch, build 9bfdf909fb
2021-06-27 06:01:45 -0500
Python 3.8.10, PyQt version 5.15.2
Windows 10 AMD64 (build 10.0.19042) SP0
      home: C:\Users\lewisneal
leo-editor: N:\git\leo-editor
      load: N:\git\leo-editor\leo\core
    config: N:\git\leo-editor\leo\config
reading settings in N:\git\leo-editor\leo\config\leoSettings.leo
reading settings in C:\Users\lewisneal\.leo\myLeoSettings.leo
Empty setting name in False
Traceback (most recent call last):

  File "N:\git\leo-editor\leo\core\leoConfig.py", line 2271, in visitNode
return f(p, kind, name, val)

  File "N:\git\leo-editor\leo\core\leoConfig.py", line 173, in doButtons
command_p.rclicks = rclicks

AttributeError: 'Position' object has no attribute 'rclicks'
[snip]
Hope it helps.

**Comment by edreamleo** [comment]
This has been fixed elsewhere.
