### ISSUE TITLE
freewin.py: monkey-patching central_widget.keyPressEvent crashes pylint

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#2010]
The line:
`central_widget.keyPressEvent = self.keyPressEvent`
causes the following crash in pylint, with both python 36 and 39:
```
# Exception on node <FunctionDef.keyPressEvent l.724 at 0x1b16d088518>
# in file 'c:\leo.repo\leo-editor\leo\plugins\freewin.py'
# Traceback (most recent call last):
  # File "<string>", line 1, in <module>
  # File "C:\Users\edreamleo\Python\Python36\lib\site-packages\pylint\lint\run.py", line 381, in __init__
    # linter.check(args)
  # File "C:\Users\edreamleo\Python\Python36\lib\site-packages\pylint\lint\pylinter.py", line 874, in check
    # self.get_ast, self._iterate_file_descrs(files_or_modules)
  # File "C:\Users\edreamleo\Python\Python36\lib\site-packages\pylint\lint\pylinter.py", line 907, in _check_files
    # self._check_file(get_ast, check_astroid_module, name, filepath, modname)
  # File "C:\Users\edreamleo\Python\Python36\lib\site-packages\pylint\lint\pylinter.py", line 933, in _check_file
    # check_astroid_module(ast_node)
  # File "C:\Users\edreamleo\Python\Python36\lib\site-packages\pylint\lint\pylinter.py", line 1068, in check_astroid_module
    # ast_node, walker, rawcheckers, tokencheckers
  # File "C:\Users\edreamleo\Python\Python36\lib\site-packages\pylint\lint\pylinter.py", line 1112, in _check_astroid_module
    # walker.walk(ast_node)
  # File "C:\Users\edreamleo\Python\Python36\lib\site-packages\pylint\utils\ast_walker.py", line 77, in walk
    # self.walk(child)
  # File "C:\Users\edreamleo\Python\Python36\lib\site-packages\pylint\utils\ast_walker.py", line 77, in walk
    # self.walk(child)
  # File "C:\Users\edreamleo\Python\Python36\lib\site-packages\pylint\utils\ast_walker.py", line 74, in walk
    # callback(astroid)
  # File "C:\Users\edreamleo\Python\Python36\lib\site-packages\pylint\checkers\classes.py", line 1002, in visit_functiondef
    # for obj in ancestor.lookup(node.name)[1]:
  # File "C:\Users\edreamleo\Python\Python36\lib\site-packages\astroid\node_classes.py", line 1082, in lookup
    # return self.scope().scope_lookup(self, name)
  # File "C:\Users\edreamleo\Python\Python36\lib\site-packages\astroid\scoped_nodes.py", line 2274, in scope_lookup
    # return frame._scope_lookup(node, name, offset)
  # File "C:\Users\edreamleo\Python\Python36\lib\site-packages\astroid\scoped_nodes.py", line 235, in _scope_lookup
    # stmts = node._filter_stmts(self.locals[name], self, offset)
  # File "C:\Users\edreamleo\Python\Python36\lib\site-packages\astroid\node_classes.py", line 1179, in _filter_stmts
    # node.scope().locals,
# AssertionError: (<EmptyNode.keyPressEvent l.0 at 0x1b16f664160>, ...
```
The full text of the assertion error message is dozens of lines long.

**Comment by tbpassin** [comment]
That's strange.  Pylint gives the file a 10.0/10.0 on my (Python 3.9) system.  I just tried it again with the same result.  Also, the code actually works without crashing.  How could pylint even crash, anyway?  If it found an unfullfillable forward reference it would just complain about an unknown method name, not crash.

I'll try dropping back to to python 3.7, which is the earliest version I have installed.

**Comment by tbpassin** [comment]
I just ran Leo with Pytthon 3.7 on Windows, and Freewin acted normally.  Did you do any updates to pylint recently?  _pip show_ displays this on my system:

```
Name: pylint
Version: 2.8.2
Summary: python code static checker
Home-page: https://github.com/PyCQA/pylint
Author: Python Code Quality Authority
Author-email: code-quality@python.org
License: GPL-2.0-or-later
Location: c:\program files\python39\lib\site-packages
Requires: colorama, mccabe, isort, toml, astroid
Required-by: leo
```

**Comment by tbpassin** [comment]
I tried running pylint outside of Leo on Freewin.py.  I found a lot of complaints - because it's not using Leo's pylint config setup, mostly about snake-case naming - but it didn't crash.  I also checked out the current devel branch and ran pylint on devel's freewin.py outside of Leo.  It didn't crash either.

It would seem there is something abnormal going on with your pylint install somehow.  It might be in the _astroid_ package, since that's where the end of your traceback is.  The most recent version of _astroid_ is later than what I have installed, but now I feel reluctant to try updating.

@edward, would you try running pylint stand-alone on the freewin.py file, outside of Leo, and see if it still crashes?  And if it does, would you post the freewin.py file so I can see if it has something funny about it that isn't in mine?

**Comment by edreamleo** [comment]
On Sun, Jun 27, 2021 at 11:12 AM tbpassin ***@***.***> wrote:

> That's strange. Pylint gives the file a 10.0/10.0 on my (Python 3.9)
> system.
>
Yeah, it's probably something weird on my machine. I'll try reinstalling.

Edward

**Comment by edreamleo** [comment]
I am going to close this issue and fix the problem on my machine.
