### ISSUE TITLE
Does not run or install on Debian jessie

### ISSUE THREAD

**Issue by nrnrnr** [leo-editor/leo-editor#202]
Leo does not run or install on Debian jessie.  Adding the Ubuntu PPA was futile; apt can't find the package.

Cloning the git repo produced this error when trying to set up:

````
: nr@labrador 56016 ; python setup.py install
Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    from setuptools import setup, find_packages
ImportError: No module named setuptools
: nr@labrador 56017 ; 
````

and produced this error when trying to launch directly

````
: nr@labrador 56023 ; ./launchLeo.py 
created directory: /home/nr/.leo
setting leoID from os.getenv('USER'): 'nr'
reading settings in /home/nr/net/leo-editor/leo/config/leoSettings.leo
Traceback (most recent call last):
  File "./launchLeo.py", line 8, in <module>
    leo.core.runLeo.run()
  File "/home/nr/net/leo-editor/leo/core/runLeo.py", line 63, in run
    g.app.loadManager.load(fileName, pymacs)
  File "/home/nr/net/leo-editor/leo/core/leoApp.py", line 2688, in load
    lm.doPrePluginsInit(fileName, pymacs)
  File "/home/nr/net/leo-editor/leo/core/leoApp.py", line 2754, in doPrePluginsInit
    lm.createGui(pymacs)
  File "/home/nr/net/leo-editor/leo/core/leoApp.py", line 2779, in createGui
    lm.createSpecialGui(gui_option, pymacs, script, windowFlag)
  File "/home/nr/net/leo-editor/leo/core/leoApp.py", line 2794, in createSpecialGui
    g.app.createDefaultGui()
  File "/home/nr/net/leo-editor/leo/core/leoApp.py", line 1738, in createDefaultGui
    app.createQtGui(fileName, verbose=verbose)
  File "/home/nr/net/leo-editor/leo/core/leoApp.py", line 1758, in createQtGui
    import leo.plugins.qt_gui as qt_gui
  File "/home/nr/net/leo-editor/leo/plugins/qt_gui.py", line 12, in <module>
    import leo.plugins.qt_big_text as qt_big_text
  File "/home/nr/net/leo-editor/leo/plugins/qt_big_text.py", line 6, in <module>
    import leo.plugins.qt_text as qt_text
  File "/home/nr/net/leo-editor/leo/plugins/qt_text.py", line 434, in <module>
    class LeoLineTextWidget(QtWidgets.QFrame):
AttributeError: 'NoneType' object has no attribute 'QFrame'
: nr@labrador 56024 ;
````

I have commit bbd641500d8a9e1b5b1b836512fe2cd1b0d275d3

**Comment by tbnorth** [comment]
On Tue, 28 Jul 2015 13:49:18 -0700
Norman Ramsey <notifications@github.com> wrote:

> Leo does not run or install on Debian jessie.  Adding the Ubuntu PPA
> was futile; apt can't find the package.

At one point, and maybe still, not sure, setup.py was only used for (a)
building PPAs, and (b) confusing new users :-/

Have you tried these instructions:
http://leoeditor.com/installing.html
- if there are any Debian specific wrinkles we could update the docs.

Cheers -Terry

**Comment by nrnrnr** [comment]
> On Tue, 28 Jul 2015 13:49:18 -0700
 > Norman Ramsey <notifications@github.com> wrote:
 > 
 > > Leo does not run or install on Debian jessie.  Adding the Ubuntu PPA
 > > was futile; apt can't find the package.
 > 
 > At one point, and maybe still, not sure, setup.py was only used for (a)
 > building PPAs, and (b) confusing new users :-/
 > 
 > Have you tried these instructions:
 > http://leoeditor.com/installing.html

Yes, these are exactly the instructions I was trying to follow.
http://leoeditor.com/installing.html#installing-from-sources-linux
lists two ways to do it and both failed.  That's why I filed the bug report.


Norman

**Comment by edreamleo** [comment]
On Tue, Jul 28, 2015 at 3:49 PM, Norman Ramsey <notifications@github.com>
wrote:

> Leo does not run or install on Debian jessie. Adding the Ubuntu PPA was
> futile; apt can't find the package.
>
​I am sorry you are having problems.  Hope they can be resolved soon.

> Cloning the git repo produced this error when trying to set up:
>
> : nr@labrador 56016 ; python setup.py install
> Traceback (most recent call last):
>   File "setup.py", line 7, in <module>
>     from setuptools import setup, find_packages
> ImportError: No module named setuptools
> : nr@labrador 56017 ;
>
>
​Iirc, setuptools is included automatically in Python 3 distributions.
Otherwise,it needs to be installed by hand.  ​

​Having said that, my guess is that git is not installed properly.​


​Have you been able to clone other git repos on your machine?​

and produced this error when trying to launch directly
>
> : nr@labrador 56023 ; ./launchLeo.py
> created directory: /home/nr/.leo
>
> ​[snip]


  File "/home/nr/net/leo-editor/leo/plugins/qt_big_text.py", line 6, in <module>
    import leo.plugins.qt_text as qt_text
  File "/home/nr/net/leo-editor/leo/plugins/qt_text.py", line 434, in <module>
    class LeoLineTextWidget(QtWidgets.QFrame):
AttributeError: 'NoneType' object has no attribute 'QFrame'
: nr@labrador 56024 ;


​This indicates that PyQt is not installed correctly.

HTH.

Edward

P.S. Following noweb's style was one of the best decisions I ever made and
was an important advance in Leo's history.​

​Many thanks for your work.  It would be great to have you on board.

EKR

**Comment by nrnrnr** [comment]
> On Tue, Jul 28, 2015 at 3:49 PM, Norman Ramsey <notifications@github.com>
 > wrote:
 > 
 > > Leo does not run or install on Debian jessie. Adding the Ubuntu PPA was
 > > futile; apt can't find the package.
 > >
 > ​I am sorry you are having problems.  Hope they can be resolved soon.
 > 
 > > Cloning the git repo produced this error when trying to set up:
 > >
 > > : nr@labrador 56016 ; python setup.py install
 > > Traceback (most recent call last):
 > >   File "setup.py", line 7, in <module>
 > >     from setuptools import setup, find_packages
 > > ImportError: No module named setuptools
 > > : nr@labrador 56017 ;
 > >
 > >
 > ​Iirc, setuptools is included automatically in Python 3 distributions.
 > Otherwise,it needs to be installed by hand.  ​

Then please add instructions to your documentation.
Your documentation says Python 2.7 will work, and that's what I have:

: nr@labrador 56351 ; python --version
Python 2.7.9

 > ​Having said that, my guess is that git is not installed properly.​

Highly unlikely.  I use git very heavily, and I clone repos routinely.
I currently have git 2.1.4 installed.

 > ​Have you been able to clone other git repos on your machine?​
 > 
 > and produced this error when trying to launch directly
 > >
 > > : nr@labrador 56023 ; ./launchLeo.py
 > > created directory: /home/nr/.leo
 > >
 > > ​[snip]
 > 
 > 
 >   File "/home/nr/net/leo-editor/leo/plugins/qt_big_text.py", line 6, in
 >   <module>
 >     import leo.plugins.qt_text as qt_text
 >   File "/home/nr/net/leo-editor/leo/plugins/qt_text.py", line 434, in
 >   <module>
 >     class LeoLineTextWidget(QtWidgets.QFrame):
 > AttributeError: 'NoneType' object has no attribute 'QFrame'
 > : nr@labrador 56024 ;
 > 
 > 
 > ​This indicates that PyQt is not installed correctly.

Fine, but again, please update your documentation with instructions
along the lines of "if you launch Leo directly, you will need to be
sure that PyQT is installed."

I use Python rarely, and I just want to try Leo, which I know you have
been working on for many years now.


Norman

**Comment by edreamleo** [comment]
On Thu, Jul 30, 2015 at 10:48 AM, Norman Ramsey <notifications@github.com>
wrote:

> > ​This indicates that PyQt is not installed correctly.
>
> Fine, but again, please update your documentation with instructions
> along the lines of "if you launch Leo directly, you will need to be
> sure that PyQT is installed."
>

​I'm not sure which is more difficult: writing documentation or reading it
;-)

http://leoeditor.com/installing.html#installing-packages

The problem we all have is that we just want to get the dashed thing
working, and reading documentation is the last thing we want to do.

Several people have been suggesting that Leo should have something like a
one-click installer, but it's not so easy to do when external packages are
involved.

Edward

**Comment by tbnorth** [comment]
On Thu, 30 Jul 2015 08:48:20 -0700
Norman Ramsey <notifications@github.com> wrote:

>  > ​Having said that, my guess is that git is not installed properly.​
> 
> Highly unlikely.  I use git very heavily, and I clone repos routinely.
> I currently have git 2.1.4 installed.

I agree that was unlikely to be the problem.

>  > ​This indicates that PyQt is not installed correctly.
> 
> Fine, but again, please update your documentation with instructions
> along the lines of "if you launch Leo directly, you will need to be
> sure that PyQT is installed."

The first few lines of http://leoeditor.com/installing.html are:

  Leo’s minimal dependencies are:
  
  Python 2.6 or later, including all Python 3.x versions.
  PyQt. You may download PyQt4 or PyQt5.

although, a-ha, if you use the Contents box to skip to "Installing from
sources (Linux)", then it's not mentioned, so I guess that's where the
PyQt requirement needs repeating.

I was going to try adding a site specific Google search (e.g.
https://www.google.com/?gws_rd=ssl#q=site:leoeditor.com+%40clean)
I'll add the dependency mentions while I'm there.

Thanks for the feedback Norman.

Cheers -Terry

**Comment by nrnrnr** [comment]
Thanks!  It would be great to add the dependency on setuptools (for Python 2.x).

**Comment by edreamleo** [comment]
I am going to close this, due to several recent improvements:
1. I recommend the Anaconda package for anyone who doesn't use Leo's github repo.
2. Leo now has single-folder installers.
