### ISSUE TITLE
Button background color

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#2024]
**EKR Summary**

Leo does not honor colors defined in, say, `@button test-color @color=green` in buttons defined in the `@buttons` section of myLeoSettings.leo.

Fixed at PR #2066.  This is likely a long-standing bug.

**Original report**

After the recent build 9bfdf90 (where only buttons defined in local files were displayed), I noticed buttons in my menu showed their background colour setting which I had customized. For example, `@button edit-csv @color=green`
However after the fix the background colours do not show.

**Comment by edreamleo** [comment]
@LewisNeal This looks like another slots-related issue. I definitely should be fixed for 6.4

**Comment by LewisNeal** [comment]
I have found that colours display if the Buttons node is at same level as the @settings node.
However colours do not display if the Buttons node is a child of the @settings node.

**Comment by edreamleo** [comment]
@LewisNeal Thanks for this clue.
