### ISSUE TITLE
Put all statements on separate lines

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#2029]
See PR #2189, ekr-single-line branch.

Putting all statements (especially 'if' statements) helps reveal code coverage lapses.

- [x] Enable pylint format,  multiple-statements checkers.
- [x] pylint -c passes for all files.

I used the following regex's:

Find non-whitespace on 'if' line:
```
Find: ^(\s*)(if\s+.*?:)[ ]+(?=.)
Repl: \1\2\n\1(4 blanks)
```
Colon followed by non-whitespace, matching only the ws:
```
Find: (?<=:)[ ]+(?=.)
Repl: \n(8 spaces)
```

**Comment by tbpassin** [comment]
Do you consider multiple assignments on one line to be in the same category?  Leo's source code uses this construction a lot:

`w = self.w = widget()`

For myself, contrary to most recommendations and pylint's ideas, I am fine with certain inline constructions if they are very simple.  Example:

```
if A:
    #... do something
    # ... do some more
else: return
```
To my eyes, this is not only readable but more readable than the two-line `else:` form would be.  However, between @ekr and pylint, I've stopped using it.  I do agree that anything that does much more than this should be on its own line.

**Comment by edreamleo** [comment]
On Fri, Jul 2, 2021 at 7:55 AM tbpassin ***@***.***> wrote:

> Do you consider multiple assignments on one line to be in the same
> category?
>
Not at all. It's a common, perfectly reasonable, idiom.

For myself, contrary to most recommendations and pylint's ideas, I am fine
> with certain inline constructions if they are very simple. Example:
>
> if A:
>     #... do something
>     # ... do some more
> else: return
>
> It's just a feeling I have, and it's changed recently, but I am becoming
more of the opinion that return statements should always be on a separate
line. The "early return" from a function/method should be emphasized.

And here is another idiom which I used to use regularly, but that Leo's
code base now avoids, per pylint:

if a:
    ...
    return x
else:
    ...
    return y

The recommended code is:

if a:
    ...
    return x
...
return y

Again, this is a close call, but it is surprising how often avoiding the
extra indentation in the else clause simplifies matters.  Unless it doesn't
:-)

Edward

**Comment by tbpassin** [comment]
It's a nice balancing act, isn't it?  If you leave the `else:` in, you use up an extra line and have the slight cognitive load of associating the next line with the _else_. If you omit it, you have to infer that the code acts as if it were there.  That's a larger cognitive load, but you do save a line.

**Comment by edreamleo** [comment]
On Fri, Jul 2, 2021 at 8:39 AM tbpassin ***@***.***> wrote:

> It's a nice balancing act, isn't it? If you leave the else: in, you use
> up an extra line and have the slight cognitive load of associating the next
> line with the *else*. If you omit it, you have to infer that the code
> acts as if it were there. That's a larger cognitive load, but you do save a
> line.
>
Yes, sometimes.  But things change when there are serious of elifs.

Imo, being compatible with pylint recommendations tips the scale, but just
slightly.

Edward

**Comment by tbpassin** [comment]
"But things change when there are serious of elifs."

That's for sure!
