### ISSUE TITLE
Moving a node right, is not recognised as a changed file

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#2036]
Moving a node right, to child status is not recognised as a changed file. Test with 2 nodes:
A
B

Change position of node B to:

A
>B

File>Close-Window
Leo closes without asking to Save changes, and does not save the file.

Leo Log Window
Leo 6.4-devel, devel branch, build 90d3046320
2021-07-06 13:49:47 -0500
Python 3.8.10, PyQt version 5.15.2
Windows 10 AMD64 (build 10.0.19042) SP0

**Comment by edreamleo** [comment]
@LewisNeal Wow. Good catch. I'll fix this soon.
