### ISSUE TITLE
Wrong indentation after lines that end with comments

### ISSUE THREAD

**Issue by toolonely** [leo-editor/leo-editor#2040]
leo 6.3 final

When writing python code, I start a function definition with `def`, it ends with `:`, I hit Enter after that, cursor goes to the next line and it gets +4 spaces to indentation, this is pep8 friendly.

However, when the function definition line contains a comment at the end, this does not happen.

**Update**: This issue may be straightforward. I'll attempt a fix for b1.

**Comment by tbpassin** [comment]
I can confirm this, I just tried it out.  I will say that there are other times that Leo doesn't do the indent, or doesn't do enough indenting.  I haven't taken notes as to when, but here is an example.  I type

```
def f(x):
    for z in lines:
```
After hitting ``ENTER`` after ``lines``, the cursor goes even with the ``for``, but it should be indented another indent.
