### ISSUE TITLE
Find Panel Should Recognize <ALT>-X

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#2041]
When I use the Find panel and want to issue the command "replace-all", after I type in the replacement text I naturally hit ``<ALT>-x`` so I can type the command into the minibuffer.  But it does not put me in the minibuffer.  Instead, an "x" gets inserted into the text field the cursor happens to be in.

This behavior is not expected, and often not noticed until too late.  The ``<ALT>-x`` should put the cursor into the minibuffer so I can type in "replace-all".  It should **never** add unexpected text to the line edit boxes.

**EKR**: I'll do this for 6.4 only if it is trivial to do.

Even better would be for the "replace-all" text in the Find panel to be active so that clicking on it would in fact execute the replace-all command.

**Comment by edreamleo** [comment]
In addition to the original request, Ctrl-F and Alt-x work in more places.
