### ISSUE TITLE
@ or @doc does't work perfectly in @clean

### ISSUE THREAD

**Issue by wesley628** [leo-editor/leo-editor#205]
i check this doc of leo, http://leoeditor.com/directives.html#part-5-all-other-directives
in @clean node, the @doc only work like this:
@ aaa
@ bbb
@ ccc
@c 

without @('@ bbb' -> 'bbb'), it will be transfer into comment in file(in '# xxxxx' form).

the @doc does work, but not perfectly, pls fix it.

**Comment by edreamleo** [comment]
On Mon, Aug 17, 2015 at 8:13 PM, Wesley Jiang <notifications@github.com>
wrote:

> i check this doc of leo,
> http://leoeditor.com/directives.html#part-5-all-other-directives
> in @clean <https://github.com/clean> node, the @doc
> <https://github.com/doc> only work like this:
> @ aaa
> @ bbb
> @ ccc
> @c
>
> without @('@ bbb' -> 'bbb'), it will be transfer into comment in file(in
> '# xxxxx' form).
>
> the @doc <https://github.com/doc> does work, but not perfectly, pls fix
> it.
>

​Hmm.  In my test the @doc section does not get written to the external
file, but does appear in the .leo file when reloaded.​

​ I'm not sure how easy this will be to fix.

Edward

**Comment by edreamleo** [comment]
I am going to close this.  Imo, @clean handles doc parts better than I would have expected.
