### ISSUE TITLE
each node content is same when open with gvim or gedit

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#206]
Leo 5.1-final, build 20150817140446, Mon Aug 17 14:04:46 CDT 2015

**head:**

@openwith gvim = Alt+Shift+Ctrl+V

**body:**

ext:
kind: subprocess.Popen
arg: "gvim"

When opening each node, the content is the first content which has been opened. Is this a bug?

**Comment by edreamleo** [comment]
On Fri, Aug 21, 2015 at 2:57 AM, wangzhaohe <notifications@github.com>
wrote:

> Leo 5.1-final, build 20150817140446, Mon Aug 17 14:04:46 CDT 2015
>
> *head:*
>
> @openwith gvim = Alt+Shift+Ctrl+V
>
> *body:*
>
> ext:
> kind: subprocess.Popen
> arg: "gvim"
>
> When opening each node, the content is the first content which has been
> opened. Is this a bug?
>

​Probably.  Iirc, there are some big problems with this feature, which then
got forgotten.  Thanks for the reminder.

Edward

**Comment by wangzhaohe** [comment]
When will you fix it? I like this feature.

**Comment by tbnorth** [comment]
Do you know the last date it was working? That would help identify the problem. 
Cheers -Terry

**Comment by wangzhaohe** [comment]
@tbnorth 
I think it is noting matter to date.
Leo 5.1-final, build 20150817140446, Mon Aug 17 14:04:46 CDT 2015
You can find it easily!

**Comment by tbnorth** [comment]
@wangzhaohe - I just wondered if you knew a date when it was working, to make it easier to find the date when it stopped working.  `git bisect` helped find it.

**Comment by edreamleo** [comment]
On Fri, Aug 21, 2015 at 8:39 PM, tbnorth <notifications@github.com> wrote:

> Do you know the last date it was working? That would help identify the
> problem.
>

​I doubt it ever worked.  I think somehow fixing it got left off the to-do
list, and then I just forgot it.

EKR

**Comment by tbnorth** [comment]
On Sat, 22 Aug 2015 05:02:50 -0700
"Edward K. Ream" <notifications@github.com> wrote:

> On Fri, Aug 21, 2015 at 8:39 PM, tbnorth <notifications@github.com>
> wrote:
> 
> > Do you know the last date it was working? That would help identify
> > the problem.
> >
> 
> ​I doubt it ever worked.  I think somehow fixing it got left off the
> to-do list, and then I just forgot it.

Just for posterity, the reported bug was that "open in <external
editor>" on non-file node A and then non-file node B showed A's body in
both external files.  I fixed that.  I did not test writing /
editing / re-loading the text.  And also only evaluating the wrong body
behavior just described, it was working before 74ad2b85789, generating
a traceback from 74ad2b85789 to c2465dd0f7, and thereafter doing the
wrong body thing I just fixed.  So maybe OP will report problems with
the editing / re-loading phases now.

Cheers -Terry

**Comment by edreamleo** [comment]
On Sat, Aug 22, 2015 at 1:02 PM, tbnorth <notifications@github.com> wrote:

> On Sat, 22 Aug 2015 05:02:50 -0700
> "Edward K. Ream" <notifications@github.com> wrote:
>
> > On Fri, Aug 21, 2015 at 8:39 PM, tbnorth <notifications@github.com>
> > wrote:
> >
> > > Do you know the last date it was working? That would help identify
> > > the problem.
> > >
> >
> > ​I doubt it ever worked. I think somehow fixing it got left off the
> > to-do list, and then I just forgot it.
>
> Just for posterity, the reported bug was that "open in <external
> editor>" on non-file node A and then non-file node B showed A's body in
> both external files. I fixed that. I did not test writing /
> editing / re-loading the text. And also only evaluating the wrong body
> behavior just described, it was working before 74ad2b85789, generating
> a traceback from 74ad2b85789 to c2465dd0f7, and thereafter doing the
> wrong body thing I just fixed. So maybe OP will report problems with
> the editing / re-loading phases now.
>

​Many thanks, Terry, for all your work on this issue.

Edward

**Comment by wangzhaohe** [comment]
Sorry, I forgot the date that run ok with gvim.
OK, I have tested it and it run well.
Thanks!
