### ISSUE TITLE
Protect event handlers with g.callback

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#2069]
See PR #2075.

Crashes inside **unprotected** event handlers will cause Leo to exit! The g.callback decorator protects callbacks (event handlers) by wrapping the decorated function in a try/except block.

*Note*: plugins.callTagHandler protects all *hooks*.

There are hundreds of such callbacks: search for `.connect`. For now, I'll protect only those event handlers in Leo's core and most important plugins.

- [x] Protect event handlers in qt_frame.py.
- [x] Protect event handlers in qt_text.py.
- [x] Protect event handlers in qt_tree.py.
- [x] Protect event handlers in mod_scripting.py. There are no such handlers.
- [x] Protect event handlers in viewrendered.py.

**Comment by tbpassin** [comment]
ALT-drag?  What can we do with ALT-drag? Something good, I hope.

**Comment by edreamleo** [comment]
On Fri, Jul 16, 2021 at 4:59 PM tbpassin ***@***.***> wrote:

> ALT-drag? What can we do with ALT-drag? Something good, I hope.
>
It's a clone move, iirc.

Edward
