### ISSUE TITLE
Bug in Find tab

### ISSUE THREAD

**Issue by rengel-de** [leo-editor/leo-editor#207]
Leo 5.1, build 20150729220224

To reproduce the bug:

1. Activate the Find tab
    (By default, the option 'Ignore case' is deactivated.)

2. Enter an ALLCAPS term into the 'Find' field.

3. Press the button 'Find Next: F3'.

The bug: 
 
    The option 'Ignore case' gets activated automatically, even if I don't want this.
     When I deactivate this option, it gets activated again, the next time I press F3.

**Comment by edreamleo** [comment]
#214 probably fixes this. Please reopen if problems remain.
