### ISSUE TITLE
Several code samples are absent in "Create outline nodes" section of scripting tutorial

### ISSUE THREAD

**Issue by gamtiq** [leo-editor/leo-editor#2072]
No scripts are displayed in [Create outline nodes](http://leoeditor.com/tutorial-scripting.html#create-outline-nodes) section inside "Writing Leo scripts in Python" page.

**Comment by edreamleo** [comment]
@gamtiq Thanks, Denis. This should be fixed for b1.

**Comment by edreamleo** [comment]
Fixed at rev 12002db in devel and on the web.

Fixed by removing `code-block::python` directives.
