### ISSUE TITLE
external change overwrite protection only works once

### ISSUE THREAD

**Issue by tbnorth** [leo-editor/leo-editor#208]
In d66846669 I fixed an unrelated niggle with symbolic links.  While there I noticed what I believe is a moderately serious bug at the end of leo-editor/leo/core/LeoPy.leo#Code-->Core classes-->@file leoApp.py-->class ExternalFilesController-->efc.utilities-->efc.has_changed.  See FIXME there.

Reluctant to change it because I think this code has received a lot of vetting in the past, but basically when a file is found to have changed on disk Leo updates Leo's info. on the file's timestamp, so if the user chooses not to overwrite, but dirties the file again, next time Leo will see the timestamps as matching and overwrite the non-matching file on disk without warning, even though the user specifically chose not to overwrite when asked previously.

I think these two lines at the end of has_changed() should be removed:

        efc.set_time(path, new_time)
        efc.checksum_d[path] = new_sum

**Comment by edreamleo** [comment]
> See FIXME there.

Unrelated? The first time I looked at efc.has_changed, I didn't see the FIXME.  I reloaded using --no-cache just to be sure, but perhaps just reloading would have sufficed.  No way to know now...

> Reluctant to change it because I think this code has received a lot of vetting in the past,

You are giving me *way* too much credit :-)  I may have done a few hand tests during development, but I don't recall *any* related unit tests, which is poor practice for something this important.  Have you tried some preliminary tests after disabling the two dubious lines?

**Comment by tbnorth** [comment]
On Wed, 23 Sep 2015 08:43:34 -0700
"Edward K. Ream" <notifications@github.com> wrote:

> > See FIXME there.
> 
> Unrelated? The first time I looked at efc.has_changed, I didn't see
> the FIXME.  I reloaded using --no-cache just to be sure, but perhaps
> just reloading would have sufficed.  No way to know now...

Surely only related by spooky coincidence :-}

> > Reluctant to change it because I think this code has received a lot
> > of vetting in the past,
> 
> You are giving me *way* too much credit :-)  I may have done a few
> hand tests during development, but I don't recall *any* related unit
> tests, which is poor practice for something this important.  Have you
> tried some preliminary tests after disabling the two dubious lines?

Yes, I confirmed the undesirable behavior exists with the lines in
place and goes away with the lines commented out.

**Comment by edreamleo** [comment]
>> Have you tried some preliminary tests after disabling the two dubious lines?

> Yes, I confirmed the undesirable behavior exists with the lines in place and goes away with the lines commented out.

OK.  Feel free to comment them out.  We'll all test the results.

The lack of unit tests here is my responsibility, but it would be a very good thing to write unit tests that verify that various *sequences* of operations leave the cache in expected states.  Any help in this area would be greatly appreciated.

**Comment by tbnorth** [comment]
On Wed, 23 Sep 2015 08:57:08 -0700
"Edward K. Ream" <notifications@github.com> wrote:

> >> Have you tried some preliminary tests after disabling the two
> >> dubious lines?
> 
> > Yes, I confirmed the undesirable behavior exists with the lines in
> > place and goes away with the lines commented out.
> 
> OK.  Feel free to comment them out.  We'll all test the results.
> 
> The lack of unit tests here is my responsibility, but it would be a
> very good thing to write unit tests that verify that various
> *sequences* of operations leave the cache in expected states.  Any
> help in this area would be greatly appreciated.

I don't see this as a caching related issue, just a timestamp based
detection of external file change where the users answer the first time
("don't overwrite") is forgotten the second time because of a spurious
update of the internal copy of the external modification time.

**Comment by edreamleo** [comment]
On Wed, Sep 23, 2015 at 11:01 AM, tbnorth <notifications@github.com> wrote:

> > The lack of unit tests here is my responsibility, but it would be a
> > very good thing to write unit tests that verify that various
> > *sequences* of operations leave the cache in expected states. Any
> > help in this area would be greatly appreciated.
>
> I don't see this as a caching related issue, just a timestamp based
> detection of external file change where the users answer the first time
> ("don't overwrite") is forgotten the second time because of a spurious
> update of the internal copy of the external modification time.


Thanks for the clarification. Still, the problem arises because of a
particular sequence of actions, and it would be best practice to cover the
relevant sequences with unit tests.  Not that I'm volunteering today ;-)

EKR

**Comment by edreamleo** [comment]
Fixed as per the discussion at rev a0f95fe.
