### ISSUE TITLE
Context Menu Does Not Use External Editor Setting

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#2080]
See PR #2084.

- [x] Pass c to g.guessExternalEditor()

**Won't fix**:
- Launching the external editor fails when the editor path contains spaces. The workaround:
   1. create a .bat file, on a path not containing spaces, that opens the desired editor.
   2. Set `@string external-editor` to that .bat file (without the .bat extension).
- There are two separate entries in the context menu for opening a file with an external editor. One of them shows just the base name of the editor, the other shows the full path. The first is the most desirable form.  **EKR**: Why should I care?

**Original report**

This bug has two parts.  First, the contextmenu.py plugin uses g.guessExternalEditor() a total of *three* times.  It should be called with "c" as an argument but isn't, so that the method does not actually check ``c.config.getString('external-editor')``.

Second, once the "c" argument is corrected, the way the external editor is launched fails when the editor path contains spaces, as mine does.

In addition to calling g.guessExternalEditor() three times, I'm seeing *two* separate entries in the context menu for opening a file with an external editor.  One of them shows just the base name of the editor, the other shows the full path.  The first is the most desirable form.

**Comment by tbpassin** [comment]
I don't see why both _editnode_rclick_  and _openwith_rclick_ are needed.  _editnode_rclick_   seems more general since it can edit a node that is not in an file tree.

**Comment by tbpassin** [comment]
Created PR for this issue: [2083](https://github.com/leo-editor/leo-editor/pull/2083)

**Comment by edreamleo** [comment]
Please don't ask me to do anything more about this plugin.
