### ISSUE TITLE
Child nodes with the same names under different parent nodes cause "orphan node" errors.

### ISSUE THREAD

**Issue by gitly-github** [leo-editor/leo-editor#209]
Hello, this is the format I am going to use to represent a Leo outline:

```
@clean text.text
    <<child 1>>
        <<child 1>>
        <<child 2>>
    <<child 2>>
        <<child 1>>
        <<child 2>>
```

---

In Leo, modeling an `@clean` node in the following ways gives you the following errors:

**1:** _No errors_
```
@clean text.text
    <<a>>
    <<b>>
```

**2:** _No errors_
```
@clean text.text
    <<a>>
        <<a>>
    <<b>>
```

**3:** _errors writing: `/test.text`_
_Orphan node:  `<<b>>`_
_parent node: `@clean test.text`_
_not written: `test.text`_
_saved: `test.leo`_
```
@clean test.text
    <<a>>
        <<b>>
    <<b>>
```

**4:** _No errors_
```
@clean text.text
    <<a>>
    <<b>>
        <<b>>
```

**5:** _No errors_
```
@clean text.text
    <<a>>
    <<b>>
        <<a>>
```

**6:** _errors writing: `/test.text`_
_Orphan node:  `<<b>>`_
_parent node: `@clean test.text`_
_not written: `test.text`_
_saved: `test.leo`_
```
@clean test.text
    <<a>>
        <<c>>
            <<b>>
    <<b>>
```

**7:** _No errors_
```
@clean test.text
    <<a>>
    <<b>>
@clean test2.text
    <<a>>
    <<b>>
```

---

This might be how Leo is supposed to work (I don't know). But this bug is fairly annoying when you try to organize nodes with replica names underneath different parent nodes. A primary example where this bug appears is in this example:

```
@clean example.h
    <<unsigned>>
        <<char>>
        <<int>>
    <<signed>>
        <<char>>
        <<int>>
```

It would be awesome if it could be made so that node names would only throw errors if _sibling nodes_ have the same name.

**Comment by tbnorth** [comment]
On Sun, 20 Sep 2015 17:10:03 -0700
gitly-github <notifications@github.com> wrote:

> 3: errors writing: /test.text
> Orphan node: <<b>>
> parent node: @clean test.text
> not written: test.text
> saved: test.leo
> 
> @clean test.text
>     <<a>>
>         <<b>>
>     <<b>>

I'm not immediately able to reproduce this.  Checking:

a) you have `@others` in the `@clean test.text` node?

b) you're not /actually/ calling your node `<<a>>` etc.?  The << and
the >> will confuse Leo I think, they look like section references.

**Comment by gitly-github** [comment]
a) Nope, I don't have `@others` located in the `@clean test.text` node. All that is in that node is a reference to the `<<a>>` and `<<b>>` sections. Inside of `<<a>>` I have a reference to the `<<b>>` reference, which should only refer to `<<a>>`s child-node `<<b>>`, and not `<<a>>`s sibling-node `<<b>>`.

b) Nope, these examples had no code inside of them, just section references (to showcase the bug).

I have attached the Leo file that I used to produce this bug (I changed the file extension to .jpg so that GitHub would let me upload it, you can change it back to .leo).
![test](https://cloud.githubusercontent.com/assets/11801727/9984447/28ed52be-5fdd-11e5-9a84-3d9fd3c6886c.jpg)

**Comment by gitly-github** [comment]
Instead I'll just post the XML of the Leo file I used since GitHub isn't playing nice with the file I previously uploaded.

```
<?xml version="1.0" encoding="utf-8"?>
<!-- Created by Leo: http://leoeditor.com/leo_toc.html -->
<leo_file xmlns:leo="http://leoeditor.com/namespaces/leo-python-editor/1.1" >
<leo_header file_format="2" tnodes="0" max_tnode_index="0" clone_windows="0"/>
<globals body_outline_ratio="0.5" body_secondary_ratio="0.5">
	<global_window_position top="50" left="50" height="500" width="700"/>
	<global_log_window_position top="0" left="0" height="0" width="0"/>
</globals>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="eve.20150920162155.2" a="EO"><vh>@clean test.text</vh>
<v t="eve.20150920162203.1" a="E"><vh>&lt;&lt;a&gt;&gt;</vh>
<v t="eve.20150920162209.1"><vh>&lt;&lt;b&gt;&gt;</vh></v>
</v>
<v t="eve.20150920162207.1"><vh>&lt;&lt;b&gt;&gt;</vh></v>
</v>
</vnodes>
<tnodes>
<t tx="eve.20150920162155.2">&lt;&lt;a&gt;&gt;

&lt;&lt;b&gt;&gt;</t>
<t tx="eve.20150920162203.1">&lt;&lt;b&gt;&gt;</t>
<t tx="eve.20150920162207.1"></t>
<t tx="eve.20150920162209.1"></t>
</tnodes>
</leo_file>
```

**Comment by tbnorth** [comment]
On Sun, 20 Sep 2015 19:22:27 -0700
gitly-github <notifications@github.com> wrote:

> Instead I'll just post the XML of the Leo file I used since GitHub
> isn't playing nice with the file I previously uploaded.

Ok, I didn't understand what you were trying to do the first time.  I
don't think there's any easy solution to your problem, section
references are only supposed to be defined once in an outline.  I.e.
body text <<foo>> should reference the node called <<foo>> wherever
that node is, so if there's more than one, there are no clear rules to
work out which one is the intended target.

Perhaps there's a different solution for your use case, if you want to
describe what that is.

**Comment by edreamleo** [comment]
On Mon, Sep 21, 2015 at 9:11 AM, tbnorth <notifications@github.com> wrote:

body text <<foo>> should reference the node called <<foo>> wherever
> that node is, so if there's more than one, there are no clear rules to
> work out which one is the intended target.
>

​The rule, probably not stated explicitly anywhere, is that the first
descendant matching definition node is used. The search, as usual, happens
in outline order.  This is the obvious rule.

EKR

**Comment by tbnorth** [comment]
On Mon, 21 Sep 2015 07:46:15 -0700
"Edward K. Ream" <notifications@github.com> wrote:

> On Mon, Sep 21, 2015 at 9:11 AM, tbnorth <notifications@github.com>
> wrote:
> 
> body text <<foo>> should reference the node called <<foo>> wherever
> > that node is, so if there's more than one, there are no clear rules
> > to work out which one is the intended target.
> >
> 
> ​The rule, probably not stated explicitly anywhere, is that the first
> descendant matching definition node is used. The search, as usual,
> happens in outline order.  This is the obvious rule.

Ok, I shouldn't have tried to answer a question about section
references, seeing I don't use them.  So then what the OP's seeing
probably is a bug.

**Comment by edreamleo** [comment]
The .leo file was useful.  It does indeed produce an error, but that error is, imo, correct.

Indeed, under the rules I stated above, both references to section << b >> resolve to the the first section definition node for << b >> in the outline, namely the node whose parent is << a >>.  As a result, the second definition node for << b >> is, in fact, an orphan.

This really, truly, is as expected.  The correct fix is to make a clone of the << b >> node and use that everywhere a definition of << b >> is expected.  Alternatively, simply deleting the second definition node for << b >> will work in this example, but clones should always work.

The point is that all clones are actually the same node, so the code that checks to see whether a node is an orphan will mark the same node as being seen, which suppresses further checks.

HTH.  I'm going to mark this as invalid.
