### ISSUE TITLE
Saving untitled document on window close not working on Qt GUI

### ISSUE THREAD

**Issue by DjMorgul** [leo-editor/leo-editor#211]
After clicking Yes in the dialog asking to save the changes made, the program closes and nothing is saved, leaving the following error:

    Traceback (most recent call last):
      File "/leo-editor/leo/plugins/qt_frame.py", line 1297, in closeEvent
        res = c.exists and g.app.closeLeoWindow(c.frame)
      File "/leo-editor/leo/core/leoApp.py", line 1682, in closeLeoWindow
        veto = frame.promptForSave()
      File "/leo-editor/leo/core/leoFrame.py", line 844, in promptForSave
        defaultextension=".leo")
    TypeError: runSaveFileDialog() takes at least 2 arguments (5 given)

This is the code that ends in line 844 of leoFrame.py:

    c.mFileName = g.app.gui.runSaveFileDialog(
                            initialfile='',
                            title="Save",
                            filetypes=[("Leo files", "*.leo")],
                            defaultextension=".leo")

My guess is that it fails because the call is not giving the c parameter to the runSaveFileDialog on qt_gui.py:

    def runSaveFileDialog(self, c, initialfile='', title='Save', filetypes=[], defaultextension=''):

runSaveFileDialog on some other GUI's doesn't have that c parameter, so I guess adding c to that call on line 844 of leoFrame.py would break them (those other GUI's) with similar negative results (whatever content we created on the new, untitled document, totally lost).

**Comment by tbnorth** [comment]
Confirmed. Ouch.

**Comment by edreamleo** [comment]
Fixed at b5e6da9f.
