### ISSUE TITLE
Leo Linux Launch Script in leo/scripts should be updated to Python3

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#2112]
In the leo/scripts directory of the Leo repo, the Linux launcher script starts with

`#!/usr/bin/env python`

All Linux flavors I have used call Python V3.xx by the alias `python3`.  The current line would launch Python 2.7 on most machines.

I would issue a PR for this but I don't know if it's actually used anywhere, or if there would be any little gotchas I don't know about.

**Comment by edreamleo** [comment]
@tbpassin Good catch: I'm on it. See PR #2114.
