### ISSUE TITLE
Export of a Subtree As Leo Outline

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#2118]
Sometimes I want to select a node and save its subtree as a Leo outline.  There does not seem to be a menu item for this.  _File/Export Files/Export Outline_ does not do this, but only exports an indented text version of the tree's headlines.

Currently I copy the node and then paste it into a text editor.  Saving this with a _.leo_ extension produces a normal Leo outline.

I propose that the _File/Export Files_ menu should include an item to save a subtree as a .leo outline.  The wording of the existing _Export Outline_ item should also be changed to clarify that it doesn't actually export a .leo outline - perhaps _Export Tree As List_.

I realize that it would not be hard to write a new command to do this, but I think it should be available as a standard menu item.

**Comment by tbpassin** [comment]
Here's a simple script that saves the current node with subtree as a Leo outline.  I'd like the capability to be available at least as a standard Leo command, and maybe on the File menu too.  Or it could go into the Scripts directory, but it will get lost there.

Possibly it needs a little polishing, but more than likely it's good as is.

```
c.k.simulateCommand('copy-node')

xml = g.app.gui.getTextFromClipboard()
c.usingClipboard = True

fileName = g.app.gui.runSaveFileDialog(c,
            title="Save To",
            filetypes=[("Leo files", "*.leo"),],
            defaultextension=g.defaultLeoFileExtension(c))

if fileName:
    with open(fileName, 'w') as f:
        f.write(xml)

c.usingClipboard = False
```

Note: no need to invoke endEditing, since a user will either be running the command or  editing a node, but not both.

**Comment by edreamleo** [comment]
@tbpassin I'll be happy to accept a PR for this at any time.

**Comment by boltex** [comment]
Good command suggestion @tbpassin. Thanks for this idea! :) 

I would personnaly change the algorithm given as example above: 

It should **first** get the filename, like the real save-as command, to see first if the requested filename has an extension of .Leo (or none) to get it added and saved in xml format.

This also has the added benefit of being able to save in the proper .db or .leojs format instead of xml if the provided filename ends in .leojs or .db.

Also, the usage of the clipboard is not desired. The save-as command itself show you how it gets it's xml string of the part of the outline as desired. (Just do the same as the regular save-as command, but start with c.p instead of root node to output the given part of outline instead of the whole tree.)

I may try myself at this small addition after Leo 6.6.4 and leointeg 1.0.8 is out. :)

**Comment by tbpassin** [comment]
Good ideas, Felix.  Sure, please go ahead with it.

**Comment by edreamleo** [comment]
@tbpassin I have just cleared this item from the 6.7.0.

Please let me know when this issue is ready for testing.

**Comment by tbpassin** [comment]
This capability appeared in a changeset around ten months ago as a command named _save-node-as-xml_.  That would seem to make this issue moot, and I am going to close it.

I may keep my own version in myLeoSettings.leo - it creates and opens an outline from a copied node without saving the outline first.  Here's how that works - it assumes that you have copied a node into the clipboard first  -

```
from leo.core.leoFileCommands import FastRead as FR
def createOutlineFromClipboard():
    """Create a new outline from the clipboard.

    The clipboard must contain an XML-format Leo outline.
    """

    s  = g.app.gui.getTextFromClipboard()
    if not s.strip():
        g.es('No string in clipboard')
        return

    # Create new outline
    c1 = c.new()

    # Construct tree from outline string
    fr = FR(c1, c1.fileCommands.gnxDict)
    v = fr.readFileFromClipboard(s)
    if not v:
        g.es('Cannot create a node from the clipboard string')
        return

    # Shove new tree into commander of the new outline
    c1.hiddenRootNode = v

    p0 = c1.rootPosition()
    c1.selectPosition(p0)

    # Highlight root node in tree as if we had clicked on it
    g.doHook("headclick1", c=c1, p=p0, event=None)

    c1.setChanged()
    c1.redraw()

createOutlineFromClipboard()
```
