### ISSUE TITLE
leo --ipython fails to connect with python3.5 and jupyter

### ISSUE THREAD

**Issue by afairy** [leo-editor/leo-editor#213]
Error message after Leo tries connecting to ipython:

To connect another client to this kernel, use:
    --existing kernel-86433.json
Traceback (most recent call last):

  File "/Users/lo/Applications/leo-editor/leo/plugins/qt_gui.py", line 923, in runWithIpythonKernel
    ipk.new_qt_console(event=None)

  File "/Users/lo/Applications/leo-editor/leo/core/leoIPython.py", line 120, in new_qt_console
    profile=self.ipkernel.profile)

  File "/usr/local/lib/python3.5/site-packages/ipykernel/connect.py", line 162, in connect_qtconsole
    cf = find_connection_file(connection_file, profile=profile)

  File "/usr/local/lib/python3.5/site-packages/ipykernel/connect.py", line 85, in find_connection_file
    return jupyter_client.find_connection_file(filename, path=['.', security_dir])

  File "/usr/local/lib/python3.5/site-packages/jupyter_client/connect.py", line 185, in find_connection_file
    raise IOError("Could not find %r in %r" % (filename, path))

OSError: Could not find 'kernel-86433.json' in ['.', '/Users/lo/.ipython/profile_default/security']

**Comment by edreamleo** [comment]
Thanks for this report.  Keeping up with IPython can be tricky.  I'll look into this asap.

**Comment by edreamleo** [comment]
Confirmed using the Anaconda3 release, which is specifically geared to IPython, Jupyter, etc. This means that there is virtually no chance that this is an installation issue. It's a real bug in Leo's IPython support.

I probably will not fix this for 5.1.1, but it will be fixed for 5.1.2.

**Comment by edreamleo** [comment]
This thread is relevant: [IPython Kernel Connection File Location](https://groups.google.com/forum/#!searchin/leo-editor/jupyter/leo-editor/fZ5nzs7f0iM/ARaTA0iICAAJ)

**Comment by edreamleo** [comment]
Here is an email from Rafi Bin-Nun 12/21/15:
		
While I'm able to see IPython variables in Leo and Leo variables in IPython and can't seem to get Leo nodes to execute in IPython. When I hit ctrl-shift-i with a Leo node selected, nothing seems to happen. Is this what's supposed to happen?

in Leo: ctrl-shift-i on node with body:  b =100

in IPython:

    In [23]:  b 
    Out[23]: 100

**Comment by edreamleo** [comment]
Rev b662e62af9 begins work on this issue. See the checkin log for details.

Most importantly, Leo's --debug option now enables verbose IPython tracing when --ipython is in effect.

**Comment by edreamleo** [comment]
Recent revs greatly improve logging, issuing warnings even when --debug is not in effect.
For the first time ever, logging makes clear what is happening.
I'll attempt a complete fix asap, but the present code is good enough for 5.2 b1.

**Comment by edreamleo** [comment]
To recap: The fix was so simple: use all the default arguments to connect_qtconsole.
The preliminaries to the fix were at least as important as the fix itself.
- Modernized the imports.
- Added logging methods.
- Tying Leo's --debug option to more verbose IPython logging.
In short, this has been a super successful project.
