### ISSUE TITLE
ignore case won't stay off while searching

### ISSUE THREAD

**Issue by tbnorth** [leo-editor/leo-editor#214]
at least with regexp search, when unchecked, it gets checked again an case is ignored

**Comment by edreamleo** [comment]
This should have been fixed long ago.  It is very annoying.  Imo, the best thing may to kill the mixed-case feature/bug entirely.

**Comment by edreamleo** [comment]
Fixed at e03e20945. All tests pass.

*Note*: The @bool auto-set-ignore-case no longer has any effect.
