### ISSUE TITLE
Document leoserver.py

### ISSUE THREAD

**Issue by boltex** [leo-editor/leo-editor#2151]
See PR #2154. Félix, feel free to change the documentation as you like.

Write some documentation about the usage of leoserver.py either for Leo's website or it's other documentation files or resources.

The addition of support for multiple concurrent connections warrants the writing of some documentation for this (somewhat new) part of the leo-editor project.

**Comment by edreamleo** [comment]
@boltex Good idea!

**Comment by boltex** [comment]
For starters, a revised leoserver's short description could be :

**leoserver.py offers single or multiple concurrent websockets for JSON based remote-procedure-calls to a shared instance of leo.core.leoBridge.**

**Comment by edreamleo** [comment]
@boltex I see you have revised the --help message in leoserver.py. Looks good to me.

Where do you want the short description to appear?
