### ISSUE TITLE
Support for tables

### ISSUE THREAD

**Issue by digulla** [leo-editor/leo-editor#216]
Please add support in Leo for table-based nodes.

Sometimes, you have data which fits the table format best. Editing tables in an ASCII editor is a pain.

To see the power of nested tables, have a look at https://github.com/aardappel/treesheets

**Comment by tbnorth** [comment]
On Wed, 11 Nov 2015 09:04:24 -0800
digulla <notifications@github.com> wrote:

> Please add support in Leo for table-based nodes.
> 
> Sometimes, you have data which fits the table format best. Editing
> tables in an ASCII editor is a pain.

Have you tried the richtext plugin?  It has table editing.  If you need
to access the table data elsewhere, you'd need to parse the HTML, but
if you just want text in a table layout, richtext gives you that.

Cheers -Terry

**Comment by edreamleo** [comment]
@rst-table closes this issue.

**Comment by digulla** [comment]
Can you please add a demo document which shows how to use this node type, especially how a script can access the cells of the table?

Also, I don't see any editor support in the code. Drawing ASCII tables manually is very tedious and error prone. Which is why I suggested to check out treesheets which has an amazing and intuitive table editor.

**Comment by tbnorth** [comment]
On Mon, 18 Apr 2016 12:25:19 -0700
digulla <notifications@github.com> wrote:

> Can you please add a demo document which shows how to use this node
> type, especially how a script can access the cells of the table?
> 
> Also, I don't see any editor support in the code. Drawing ASCII
> tables manually is very tedious and error prone. Which is why I
> suggested to check out treesheets which has an amazing and intuitive
> table editor.

One relatively short route to table editing in Leo would be to leverage
the rich text plugin, use it's table editor and import/export from a
node outside the document tree to a md or rst format in the document
tree.  Depends how fancy you want to get formatting wise, but if it's
just a matter of editing tabular data in a table format, that route
would be quite straight forward.

... which leads to the thought that just as we embed CKEditor for rich
text HTML editing, we could embed one of many javascript spreadsheet
apps. for spreadsheet functionality in Leo :-)

Cheers -Terry

**Comment by edreamleo** [comment]
@digulla Here is the test node I used:
```
<?xml version="1.0" encoding="utf-8"?>
<!-- Created by Leo: http://leoeditor.com/leo_toc.html -->
<leo_file xmlns:leo="http://leoeditor.com/namespaces/leo-python-editor/1.1" >
<leo_header file_format="2"/>
<vnodes>
<v t="ekr.20160414060624.1" a="E"><vh>@rst c:\test\rst-no-nl-test.html</vh>
<v t="ekr.20160414060624.2" a="E"><vh>@rst-table my table</vh>
<v t="ekr.20160414060641.1"><vh>Start</vh></v>
<v t="ekr.20160414060624.3"><vh>field 1</vh></v>
<v t="ekr.20160414060624.4"><vh>field 2</vh></v>
<v t="ekr.20160414060624.5"><vh>end</vh></v>
</v>
</v>
</vnodes>
<tnodes>
<t tx="ekr.20160414060624.1">####
Test
####
</t>
<t tx="ekr.20160414060624.2"></t>
<t tx="ekr.20160414060624.3">prmField1           Integer

</t>
<t tx="ekr.20160414060624.4">------------------- --------
prmField2           Integer</t>
<t tx="ekr.20160414060624.5">=================== ========

</t>
<t tx="ekr.20160414060641.1">Here is a table:

=================== ========
Field Name          Format
=================== ========


</t>
</tnodes>
</leo_file>
```
I'm not sure cutting this and then doing paste-node will work.  I'll try it after I post this.

**Comment by edreamleo** [comment]
> [how can] a script can access the cells of the table?

Assuming p1 points to the @rst node in the example, p1.subtree() visits all of its descendants. For example:
```
for p in p1.subtree():
    g.es(p.h)
```
As another example, to find all @rst nodes in a tree:
```
for p in c.all_unique_positions():
    if p.h.startswith('@rst '):
        g.es(p.h)
```
> I don't see any editor support in the code. Drawing ASCII tables manually is very tedious and error prone. Which is why I suggested to check out treesheets which has an amazing and intuitive table editor.

That's a separate issue, and should be a separate enhancement request. The advantage of the present simple approach is that it supports any of the various styles of creating rST tables. Cutting and pasting separator lines isn't fun, but it's not too difficult either.

**Comment by digulla** [comment]
Sorry, this isn't at all what I'm talking about. A table editor needs to give me direct access to cell contents instead of a plain text dump of the whole table which I then have to parse myself.

What I talk about is:

```
if isinstance(p, TableNode):
    status = p.getCell(1,3)
    if status.text == 'OK':
        status.setBackground('green')
    else:
        status.setBackground('red')
```

I could accept this answer if you would have an API to start the rST parser and give me the parse tree.

But merely dropping unstructured text into my lap doesn't do.

**Comment by edreamleo** [comment]
@digulla Interesting ideas.  Please file a new enhancement requests, giving as many details as you can.

**Comment by digulla** [comment]
After thinking some more about this, I think my initial ideas was ... bad.

The correct solution is using nested nodes like so:

    @table ...options...
         @row ...options...
            @cell ...options...
            content...

that is using the natural nested structure of Leo to represent the table as a nested tree. That way, I can easily shift cells and rows around. Moving columns is a bit more complicated but a script (which can simply get the Nth child node of each row) could fix that. An online HTML renderer could help me see how the table looks like.

Additional bonus: I can put any content in a cell, allowing me to tap into the full power of Leo.
