### ISSUE TITLE
Leo Says It Is 100% Python, But It Isn't Any More

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#2160]
On Leo's main GitHub page there is the statement that Leo is 100% Python.  That was probably true in the Tk/Tcl days, but it's not really the case now that the GUI uses Qt heavily.

I understand that we're using PyQtx, but different PyQt binary libraries are needed for different platforms.

Perhaps the statement could be changed to say that Leo is as cross-platform as Python is, or something of the sort.

**Comment by edreamleo** [comment]
@tbpassin Imo, the statement that Leo is pure python is still correct. In any case, nobody has complained in the 10+ years that Leo has used Qt.
