### ISSUE TITLE
replace-then-find (in headline) can select the wrong text

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#2172]
See PR #2176.

With the proper text selected in the headline, the replace-then-find command can select (wrong!) text in c.p.h without changing c.p.

This bug probably depends on the relative sizes of the replace/find texts.

**Comment by tbpassin** [comment]
I just found unexpected behavior with search-replace in headlines.  I'm not sure if it's the same issue or not.

I had a series of nodes whose headlines were of the form `@rst file1.rst`.  I wanted to remove the `.rst` extension.  The first find did find the first one, and the first replace did replace it.  But then F3 did not seem to do anything.  As I messed around trying things, at one point the F3 command actually started searching in the reverse direction (I don't know what I did to provoke this).

Eventually I found that if I pressed F3 **twice** then the next search would succeed.  It seemed to me that the first F3 unselected the headline text, and then the next F3 succeeded.  Perhaps after replacing, the next search only occurred inside the selected headline (so it could never succeed).
