### ISSUE TITLE
Describe valid values of @string line-highlight-color

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#2175]
Rev fc052e in devel tweaks the highlight-line code and adds two new settings in leoSettings.leo:
```
@bool highlight-body-line = False
@string line-highlight-color = None
```
I'd like to have highlight-body-line False by default, at least for now.

Thomas, please add a comment in the body text of the `@string line-highlight-color` node describing the valid values of this setting, and what the setting does.

`None` does seem to work. For me, with a dark them, the line *is* highlighted, but only faintly. I find this faint highlighting is unpleasant.

**Comment by tbpassin** [comment]
I will do that.  In the meantime, values are standard CSS names, like "red" or "aliceblue", or CSS rgb values like "#1234ad".

I suggest that you try some dramatic like "red" just to verify that the setting does something.  It gets picked up when settings are reloaded.  The first cursor movement after that should show the new color.

Which dark theme are you using?  I'll try it with that.  I ran through all the standard themes in the leo/themes directory, and I thought the highlight color seemed OK for all of them, but I can tweak the algorithm for selecting the highlight color once I can see what you see.

**Comment by tbpassin** [comment]
In testing, setting the color setting worked as expected.  Of course, don't include any quote marks around the color value.  Maybe I should do some defensive programming and remove them.

I did find a little bug.  If you have used the color setting, and the remove it (by deleting the setting node, for example) and reload settings, then the code does not use its own computed color and instead uses black.  I'll fix that.

**Comment by tbpassin** [comment]
Done in devel.

**Comment by edreamleo** [comment]
On Wed, Sep 15, 2021 at 9:05 AM tbpassin ***@***.***> wrote:

> Done in devel.
>

Thanks, Thomas.

Edward
