### ISSUE TITLE
VR3 uses g.adjustTripleString

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#2186]
g.adjustTripleString no longer exists. Please use textwrap.dedent instead. textwrap.dedent isn't an exact replacement, but it should do.

@tbpassin In future, please be sure to run pylint on VR3.

**Comment by tbpassin** [comment]
Would you like the fix to go to the devel or 6.4 branch?

**Comment by edreamleo** [comment]
On Thu, Sep 16, 2021 at 10:14 AM tbpassin ***@***.***> wrote:

> Would you like the fix to go to the devel or 6.4 branch?
>

devel.  I merge devel into 6.4, not  vice versa.

Edward

**Comment by tbpassin** [comment]
Done plus other small improvements with PR submitted: [#2188](https://github.com/leo-editor/leo-editor/pull/2188)

**Comment by tbpassin** [comment]
Done, and in devel.
