### ISSUE TITLE
6.4 Startup Error Error Messages

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#2196]
I don't know if I didn't see these the first time or if they are new, but I've been getting the following:

```
Leo 6.4, 6.4 branch, build b6662ed38e
2021-09-17 10:09:22 -0500
can not open C:/Users/tom/AppData/Roaming/Python/Python39/site-packages/leo_to_html.xsl
can not open C:/Users/tom/AppData/Roaming/Python/Python39/site-packages/run_travis_unit_tests.py
file not found: C:/Users/tom/AppData/Roaming/Python/Python39/site-packages/launchLeo.py
can not open C:/Users/tom/AppData/Roaming/Python/Python39/site-packages/run_pytest_tests.py
can not open C:/Users/tom/AppData/Roaming/Python/Python39/site-packages/setup.py
can not open C:/Users/tom/AppData/Roaming/Python/Python39/site-packages/flake8-leo.py
can not open C:/Users/tom/AppData/Roaming/Python/Python39/site-packages/pyflakes-leo.py
can not open C:/Users/tom/AppData/Roaming/Python/Python39/site-packages/pylint-leo.py
```

I tried saving one @file python file, and Pyflakes was happy, so the message about flake8-leo.py and pylint also worked.

**Comment by edreamleo** [comment]
@tbpassin Please be more specific about what you were doing. I'm guessing you opened LeoPyRef.leo, but I can't be sure.

**Comment by edreamleo** [comment]
I'll assign this to 6.4, but more likely this issue will be assigned to 6.5.

**Comment by tbpassin** [comment]
Sorry, yes, I had LeoPyRef open when I started Leo.  That was on Windows, and I get the same thing on my Linux Mint VM.

**Comment by edreamleo** [comment]
@tbpassin I think this is expected. I assume you had installed Leo using pip, but that does not copy the top-level directory.

**Comment by tbpassin** [comment]
Yes, that's so.  I used the pip command line you had recommended.  For 6.4 final, though, I'd prefer not to see them: we haven't had anything like that for previous pip-installed final releases,.
