### ISSUE TITLE
Clean all lines

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#2206]
See PR #2207.

Leo's clean-all-lines will do the work.

Necessary to fix many pylint complaints.

**Comment by tbpassin** [comment]
If clean-all-lines uses `g.splitlines()`, then shouldn't it use `g.joinLines(`) as well (currently it has `s2 = ''.join(lines)`?

**Comment by edreamleo** [comment]
@tbpassin g.joinLines is an ancient artifact. ''.join(lines) is a standard python idiom.

In contrast, g.splitLines is a bit more useful. Take a look.

**Comment by tbpassin** [comment]
Actually, that's what g.joinLines() is:

```
def joinLines(aList):
    return ''.join(aList)
```

I didn't see why there even is such a method in the first place!

**Comment by edreamleo** [comment]
@tbpassin I don't remember exactly why g.joinLines ever existed. I suspect I created it very early in my Python career. In any case, g.joinLines is gone. I even thought to check in scripts.leo.

**Comment by tbpassin** [comment]
: )
