### ISSUE TITLE
goto-global-line navigating to wrong line reported by PyLint

### ISSUE THREAD

**Issue by JohnLunzer** [leo-editor/leo-editor#221]
I've included my leo file which has a test file in it. After having the outline create the file do right click "Run Pylint" and then get the line number where it complains about "import pudb" and then use that line number in the goto-global-line command. In my most recent version of Leo it brings me to three line above the import line which is exactly the amount of leo directives in that same node. 

Please see leo file at: https://groups.google.com/group/leo-editor/attach/f81de9f69767e/debuggotogloballine.leo?part=0.1&authuser=0

**Comment by edreamleo** [comment]
Fixed at 900715c5.
