### ISSUE TITLE
Edit Commands To Capitalize Words in Body and Headline

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#2212]
The Edit menu should have an item to capitalize all words in a selection.  The edit menu should have an item to capitalize all words (or maybe words in selected text) in a headline.

**Comment by edreamleo** [comment]
@tbpassin This probably won't happen unless you do it. I'll be happy to consider a PR.

**Comment by tbpassin** [comment]
All right, I'll take a look and see if I can penetrate the darkness.

**Comment by edreamleo** [comment]
@tbpassin Feel free to ask for advice.

**Comment by tbpassin** [comment]
The code to capitalize headlines in now in devel.  Code for capitalizing body text coming soon.

**Comment by tbpassin** [comment]
The code for capitalizing body text - or a selection in body text - is now in the devel branch.  Menu items in the Edit menu let you capitalize in headline or body.
