### ISSUE TITLE
Remove deprecated and do-nothing methods and functions

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#2251]
See PR #2254.

| Removed globals  | Recommended alternative | Notes |
| -------------------  | ----------------------------  | ------ |
| `g.alert()` | `c.alert()` | b |
| `g.callback()` | Not needed | d |
| `g.choose(condition, a, b)` | `a if condition else b` | d |
| `g.FileLikeObject()` | `io.StringIO(initial_value='', newline='\n')` | a |
| `g.flatten_list(aList)` | Use list comprehension | f |
| `g.isBytes(obj)` | `isinstance(obj, bytes)` | a |
| `g.isCallable(obj)` | `hasattr(obj, '__call__')` | a |
| `g.isInt(obj)` | `isinstance(obj, int)` | a |
| `g.isList(obj)` | `isinstance(obj, list)` | a |
| `g.isString(obj)` | `isinstance(obj str)` | a |
| `g.isUnicode(obj)` | `isinstance(obj, str)` | a |
| `g.join_list(aList)` | Use list comprehension | f |
| `g.list_to_string(aList)` | Use list comprehension | f |
| `g.os_path_expandExpression(s, c=c)` | `c.os_path_expandExpression(s)` | b |
| `g.u(aString)` | `aString` | a |

| Removed methods    | Recommended alternative | Notes |
| ----------------------  | ----------------------------  | ------- |
| `c.nullPosition()`  | `if p:`  | d |
| `c.os_path_finalize()` | `g.os_path_finalize()`  | c |
| `c.os_path_finalize_join()`  | `g.os_path_finalize_join()` | c |
| `v.getBody()` | `v.bodyString()` | e |
| `LoadManager.adjustSysPath()` | Not needed |

*Notes*
- a: Wrappers to hide differences between Python 2 and 3. No longer necessary.
- b: More appropriate as a Commander method.
- c: More appropriate as a global function. 
- d: A bad idea.
- e: A  synonym.
- f: Old list methods, written when I was a python newbie.

**Removed commands**

- tangle, tangle-all, tangle-marked.
- untangle, untangle-all, untangle-marked.

**Other changes**

- c.recolor takes a 'p' kwarg.
- LeoBody.recolor takes a 'p' positional arg.
- Remove "Executing foreign and external scripts" tree from leoScripts.txt (scripts.leo)

**Won't remove**

- The PosList class will stay. Removing it might cause some people real pain.
- I won't remove various synonyms for methods, functions or class.
  There would be no real value to doing so.

**Comment by tbpassin** [comment]
Here is one could go:

```
LM.adjustSysPath():
    Commented as " no longer needed".  
    Used only in in LM.doPrePluginsInit() -
        lm.adjustSysPath()
            # A do-nothing.
```
