### ISSUE TITLE
Unclear what leo-install.py is for

### ISSUE THREAD

**Issue by MrMormon** [leo-editor/leo-editor#226]
Is it deprecated?

**Comment by edreamleo** [comment]
On Sat, Dec 19, 2015 at 7:22 PM, Joshua Olson <notifications@github.com>
wrote:

> Is it deprecated?
>

​I don't remember myself.  I'll look into it.

EKR

**Comment by MrMormon** [comment]
Thanks.

**Comment by MrMormon** [comment]
INSTALL.TXT still refers to setup.py. Should that file be archived in dist too?

**Comment by edreamleo** [comment]
Good catch.  I am going to change the `Installing Leo on Linux` section of INSTALL.TXT as follows:

    You may download Leo's sources in one of three ways, as described at:
    http://leoeditor.com/download.html If the sources are zipped, unzip them
    into a folder in your home directory, say ~/leo-5.2 (or /usr/bin, etc.)
    
    To gain access to Leo, you have two choices:
    
    A. Add  ~/leo-5.2 to your path.
    B. Create alias for Leo.
    
    I prefer using aliases because they allow me to start Leo using Python 2 or 3,
    or other distributesion, like Anaconda 2 or 3.
