### ISSUE TITLE
setup.py: UserWarning: The version specified ('5.1-final') is an invalid version...see PEP 440

### ISSUE THREAD

**Issue by MrMormon** [leo-editor/leo-editor#227]
Full (Linux, `python` is Python 3 but same output with Python 2):

```
sudo python setup.py install
/usr/lib/python3.5/site-packages/setuptools/dist.py:293: UserWarning: The version specified ('5.1-final') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  "details." % self.metadata.version

```

**Comment by technatica** [comment]
Hello Joshua,

Here is the easiest way I know to install Leo on Linux. This assumes you
have already installed Python, Qt and docutils.

Install git:

> sudo apt-get install git

Then create a directory and change into it.

> mkdir leo
> cd leo

Then clone Leo.

> git clone https://github.com/leo-editor/leo-editor.git

Change into the leo-editor directory and launch leo.

> cd leo-editor
> python launchleo.py

I launch Leo using a script that has me using the latest version all of the
time.

> #!/bin/bash
> cd Working/leo/leo-editor
> git pull
> python launchLeo.py

Hope this helps,

Chris

**Comment by edreamleo** [comment]
I am going to close this.  setup.py isn't meant to install Leo.  Yes, I know this is confusing.  Iirc, there is an another issue related to setup.py, so this is basically a duplicate issue.
