### ISSUE TITLE
Freewin.py Plugin Commented Out in LeoPyRef But Still Exists In Plugins Directory

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#2270]
The headline in LeoPyRef for the Freewin plugin has a double "@":

`@@file ../plugins/freewin.py`

However the file still exists in the plugins directory.  Naturally, as its author, I would prefer that the plugin not be commented out.  Is there a reason for this?  If not, I will put in a PR with the extra "@" removed.

**Comment by edreamleo** [comment]
@tbpassin I think the reason I did that is that (my version of) pylint hangs on freewin.py.

This should be sorted out asap.

**Comment by edreamleo** [comment]
On Wed, Oct 13, 2021 at 4:55 PM tbpassin ***@***.***> wrote:

> After removing the extra "@", on my Windows system, pylint returns 9.97/10
> without hanging.
>
I'll restore freewind.py soon.

Edward
