### ISSUE TITLE
Allow section delimiters to be configurable

### ISSUE THREAD

**Issue by AresAndy** [leo-editor/leo-editor#2276]
See PR: #2303. Section delimiters ``<<`` and ``>>`` should be configurable. 

**EKR**: there **must not** be any setting associated with this issue. Such a setting would be way too dangerous.

**The design of the @section-delims directive**

The `@section-delims` directive (**the directive**, for short) specifies the delimiters to be used in both section references *and* section definitions.

*Only* `@file` nodes may contain this directive. This directive is not valid in `@clean`, `@auto`, etc.

For each external file, this directive must appear:

- only in the body of  the `@file` node itself, not in any descendant node.
- only once in the `@file` node.
- before the first section reference of the `@file` node (or other nodes in the `@file` tree).

The format of the `@section-delims` directive will be:

    @section-delims <opening delim><one or more spaces><closing delim>

Neither blanks nor alphabetic characters are allowed within delims.  Only whitespace will be allowed before the opening delim or after the closing delim.  Correct:

    @section-delims <<<<   >>>>

Wrong. For safety, *nothing* is allowed after the closing delim:

    @section-delims <!< >!>   # Change the delims

**Summary**

The `@section-delims` directive will specify the form of section *references*. Section definitions nodes will remain unchanged. This directive will be valid *only* in `@file` nodes, not in `@auto', `@clean`, etc.

Only Leo's write logic needs to change. The FastAtRead class will not change in any way.

Leo's write logic will refuse to write any `@file` node containing an erroneous or out-of-place `@section-delims` directive.

**Original post: The Problem**

Those chars used that way overlap with so many grammars: bit-wise shifting, heredocs, ... You name them. In some cases breaking the line is doable, however in C (especially when writing firmware) having ``#define``s with bit-wise shifts back and forward is very common. As of now I'm working on huge (and proprietary) projects using Leo's awesomeness, but I just can't find-replace the whole 250 kLOC source-base per project. As of now I can only use ``@clean`` nodes, and a whole lot of sweat and tears both on Leo and mine side.

I also use Python on those projects, and I laughed a bit when I stumbled on the same issue, but this time on py source files

**Comment by edreamleo** [comment]
@AresAndy Thanks for your comments.

I understand your pain, but I'm not sure there is a solution.  I'll look into it.
