### ISSUE TITLE
Delete Editor command doesn't ask confirmation for loosing data

### ISSUE THREAD

**Issue by benzolius** [leo-editor/leo-editor#228]
I worked in two editor panes and finished in the second one. I wanted to delete the second one. Clicked the second editor pane to be sure I delete that one and made the 'Delete Editor' command from the menu.

Unfortunately Leo deleted the first editor pane and I lost all changes there.

There are two issues here:

1. I'd like to have a confirmation dialog as in the case of closing a Leo file, that wasn't saved.

2. The 'Delete Editor' command should delete always the active pane, not the main one. (I tested again and usually works, I don't know why it happened to delete the main editor pane)

My environment:

Kubuntu Linux 14.04
Leo 5.1-final, build 20151207062203, Mon Dec  7 06:22:03 CST 2015
Git repo info: branch = master, commit = 16e3c3e651a0
Python 3.4.3, PyQt version 5.2.1

Thanks

**Comment by edreamleo** [comment]
A confirmation dialog should never be necessary. The situation is similar to that of selecting a new node.  Whatever changes have been made in the body pane must be stored before switching nodes. The bug arises because the relevant code is complex.

**Comment by edreamleo** [comment]
Rev 930f84837 adds defensive code to ensure that p.b is saved before deleting the body editor and switching to a new node.

Please reopen if necessary.
