### ISSUE TITLE
Increase the usage of augmented assignment statements

### ISSUE THREAD

**Issue by elfring** [leo-editor/leo-editor#2304]
:eyes: Some source code analysis tools can help to find opportunities for improving software components.
:thought_balloon: I propose to [increase the usage of augmented assignment statements](https://docs.python.org/3/reference/simple_stmts.html#augmented-assignment-statements "Augmented assignment statements") accordingly.

Would you like to integrate anything from a transformation result which can be generated by a command like the following?
(:point_right: Please check also for questionable change suggestions because of an evolving search pattern.)
```
[Markus_Elfring@fedora lokal]$ perl -p -i.orig -0777 -e 's/^(?<indentation>\s+)(?<target>\S+)\s*=\s*\k<target>\s*(?<operator>[+\-%&|^@]|\*\*?|\/\/?|<<|>>)/$+{indentation}$+{target} $+{operator}=/gm' $(find ~/Projekte/Leo/lokal -name '*.py')
```

:crystal_ball: How will the development interests evolve further also according to update candidates in 139 lines of this software?

**Comment by tbpassin** [comment]
I'm in agreement about the Python versions. The syntax was changed in 3.8, as well.  Plus I'm not liking the potential for additional complexity, and the differences in evaluation rules and order compared with ordinary Python assignment statements.

**Comment by edreamleo** [comment]
I am going to close this issue. There are many parts of Leo's code that could be improved, but the walrus operator will help improve none of them.

**Comment by edreamleo** [comment]
@elfring I am not interested in these minor details. Please don't bother me with these questions.
