### ISSUE TITLE
Current x86 Assembly syntax highlighting rules are for Intel-style only

### ISSUE THREAD

**Issue by JohnLunzer** [leo-editor/leo-editor#231]
Nowhere in the highlighting rules file is it stated but \leo\modes\assembly_x86.py refers specifically to Intel-style syntax. Many assemblers default to Intel-style but one notable assembler, GNU's GAS, defaults to AT&T style.

A separate file for the At&t style syntax should be created and both named accordingly:

```
assembly_x86_intel.py
assembly_x86_att.py
```

What is involved is creating the new rules file as well as adding an entry and modifying and entry in leoApp.py.

**Comment by edreamleo** [comment]
On Thu, Feb 11, 2016 at 9:01 AM, John Lunzer <notifications@github.com>
wrote:

> Nowhere in the highlighting rules file is it stated but
> \leo\modes\assembly_x86.py refers specifically to Intel-style syntax. Many
> assemblers default to Intel-style but one notable assembler, GNU's GAS,
> defaults to AT&T style.
>
> A separate file for the At&t style syntax should be created and both named
> accordingly:
>
> assembly_x86_intel.py
> assembly_x86_att.py
>
> ​Hmm.  I don't like changing names that might break existing programs, so
I am inclined to leave the existing file named as it is.​

​> ​
What is involved is creating the new rules file

​It's a pretty arcane topic, covered here
<http://leoeditor.com/coloring.html#format-of-colorizer-control-files>, in
the advanced topics <http://leoeditor.com/intermediatetopics.html> chapter.

​> ​
as well as adding an entry and modifying and entry in leoApp.py
​.

Should be straightforward. Up it yourself or create a pull request.

Edward

**Comment by JohnLunzer** [comment]
Point taken about renaming, then just the new one could have the clarified file name, assembly_x86_att.py. And for the current just add the clarification into the comments.

**Comment by JohnLunzer** [comment]
I currently do not see myself having time to complete this any time soon. It is likely a very low priority in the community. Not sure how whether to close or what labels might be added to indicate that it won't be attended to in the foreseeable future.

**Comment by edreamleo** [comment]
On Tue, Apr 26, 2016 at 11:30 AM, John Lunzer <notifications@github.com>
wrote:

> I currently do not see myself having time to complete this any time soon.
> It is likely a very low priority in the community. Not sure how whether to
> close or what labels might be added to indicate that it won't be attended
> to in the foreseeable future.
>

​I suggest simply closing the item.

EKR
