### ISSUE TITLE
Import  Error - trying to pop() empty list

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#2313]
While testing the new section ref branch, opening an outline failed with this error:

```
File "c:\Tom\git\leo-editor\leo\core\leoAtFile.py", line 3143, in scan_lines
    gnx, indent, body = stack.pop()

IndexError: pop from empty list
```
This error also is in this morning's devel 4a802ef93ad42def3d12eb57d80058342e909c71.

**Comment by edreamleo** [comment]
Hmm. Please email a copy of leoAtFile.py.

**Comment by tbpassin** [comment]
[leoAtFile.zip](https://github.com/leo-editor/leo-editor/files/7492534/leoAtFile.zip)

**Comment by tbpassin** [comment]
Hah!  The @file that caused the errors was written by an older version of Leo.  Apparently I hadn't opened this file for several years, because its version reads

`#@+leo-ver=4-thin`

So I suppose I can close this one.  @edreamleo, do you remember the script or program you wrote to update version 4 files?  I had used it in the past but don't remember its name.

**Comment by tbpassin** [comment]
Actually, the external file was an @thin, not an @file.  This must have been a long time ago.  I think I'll edit the .leo outline and change all the @thins to @clean, then see if the outline can be opened.

**Comment by edreamleo** [comment]
@tbpassin The script does not seem to be in scripts.leo. This would be an ancient script. I have no clear memory of it.

**Comment by tbpassin** [comment]
Not that ancient.  I remember it.  You worked it up at my suggestion because I had some older outlines I wanted to update.  I used it, and after that I don't remember where it got to.

Changing the @thins to @cleans worked for this outline, anyway.  I could write a little script to remove the sentinel lines, and start restructuring them if I need to.

**Comment by edreamleo** [comment]
@tbpassin I'll attempt to find the script.

**Comment by edreamleo** [comment]
@tbpassin I have just created #2318 :-)

**Comment by edreamleo** [comment]
@tbpassin The first comment in #2318 should contain everything you need.
