### ISSUE TITLE
leoserver should dirty a node when marking/unmarking

### ISSUE THREAD

**Issue by boltex** [leo-editor/leo-editor#2322]
leoserver.py does not seem to 'setDirty' the node, and it's ancertor's @files nodes when toggling marks. (Saw this while using leointeg)

**Comment by edreamleo** [comment]
@boltex server.mark_node calls p.setMarked() and server.unmark_node calls p.clearMarked().  p.setMarked() and p.clearMarked() set ancestor `@<file>` nodes dirty.  In contrast, v.setMarked() and v.clearMarked() are much faster--they only set/clear the marked "bit" in the VNode.

So it looks like server.mark_node and server.unmark_node handle the bits properly. Perhaps a call to c.redraw() is needed?

**Comment by boltex** [comment]
Respectfully, I think you're wrong: I just looked at the code and p.setMarked() seems to just call v.setMarked https://github.com/leo-editor/leo-editor/blob/cf53a1c4af5534d805557e0619db4bd7d6f05283/leo/core/leoNodes.py#L1808

**Comment by edreamleo** [comment]
On Tue, Nov 9, 2021 at 9:10 AM Felix ***@***.***> wrote:

> I just looked at the code and p.setMarked() seems to just call v.setMarked
>
Yes, you are correct.  I was thinking of p.setDirty vs v.setDirty.

Anyway, the server seems to be setting/clearing the marked "bit"
correctly.  What do you think should change?

Edward

**Comment by boltex** [comment]
All right, this pull request makes the call with the commander so that it sets the dirty bits properly, and also creates an undo bead to undo mark/unmark commands properly: https://github.com/leo-editor/leo-editor/pull/2324
