### ISSUE TITLE
Recolor body if edit changes a Leo directive

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#2328]
Inspired by [leoInteg issue #230](https://github.com/boltex/leointeg/issues/230).

**Comment by boltex** [comment]
Leointeg now has this feature! (well in dev at least, will come out with leointeg 1.0.4 in a few days)

**Comment by edreamleo** [comment]
I am going to close this issue for the following reasons:

- The present code works surprisingly well.'
- Trying to improve the code would be extremely complicated, and would likely cause subtle bugs.
- Users can use the 'redraw' command to force a full redraw.
- The redraw code in leointeg or leojs is completely different from Leo's jEdit colorizer.
