### ISSUE TITLE
Old SourceForge links in http://leoeditor.com/installing.html#installing-leo-itself

### ISSUE THREAD

**Issue by MrMormon** [leo-editor/leo-editor#233]
latest stable release (http://sourceforge.net/projects/leo/files/Leo/4.11%20final/)

should be https://sourceforge.net/projects/leo/files/Leo/5.1-final/

**Comment by edreamleo** [comment]
> should be https://sourceforge.net/projects/leo/files/Leo/5.1-final/

I just changed this to should be https://sourceforge.net/projects/leo/files/Leo/
