### ISSUE TITLE
leoColorizer.py - 'QFont' has no attribute 'Bold'

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#2330]
After switching to PyQt6 I get this error in console at startup:

Uncaught exception in Leo...
Traceback (most recent call last):
  File "N:\git\leo-editor\leo\core\leoColorizer.py", line 2440, in highlightBlock
    self.colorizer.recolor(s)
  File "N:\git\leo-editor\leo\core\leoColorizer.py", line 2876, in recolor
    self.mainLoop(s)
  File "N:\git\leo-editor\leo\core\leoColorizer.py", line 2739, in mainLoop
    format = self.getFormat(token, text)
  File "N:\git\leo-editor\leo\core\leoColorizer.py", line 2691, in getPygmentsFormat
    format = self.highlighter._get_format(token)
  File "N:\git\leo-editor\leo\core\leoColorizer.py", line 2489, in _get_format
    result = self._get_format_from_style(token, self._style)
  File "N:\git\leo-editor\leo\core\leoColorizer.py", line 2526, in _get_format_from_style
    result.setFontWeight(QtGui.QFont.Bold)
AttributeError: type object 'QFont' has no attribute 'Bold'

_Leo Log Window
Leo 6.6b2-devel, devel branch, build bb2b99818a
2021-11-13 15:48:53 -0600
Python 3.9.8, PyQt version 6.2.1
Windows 10 AMD64 (build 10.0.19042)_

**Comment by tbpassin** [comment]
I didn't get that error, though it wouldn't be a surprise -

```
Leo 6.6b2-devel, devel branch, build bb2b99818a
2021-11-13 15:48:53 -0600
Python 3.9.5, PyQt version 6.2.1
Windows 10 AMD64 (build 10.0.19043) 
```
The surprise here is that the two of us get different results with the same build...

What language was in effect for the node that was selected when Leo started up?  Maybe it's calling for a colorizer action that mine is not?

**Comment by LewisNeal** [comment]
It does not seem related to startup: the error occurs when I click from one node to another within a Leo file.

**Comment by LewisNeal** [comment]
Q - What language was in effect for the node that was selected when Leo started up?

I tested a separate leo file with @language latex, and @language rapidq nodes, and confirm they cause the error.
However in my leo files there are no such latex or rapidq nodes.

**Comment by edreamleo** [comment]
@LewisNeal Thanks for this report. This looks like yet another Qt6 enum problem.

Imo, the specifics of how this happens are not important. This problem almost certainly arises because you have a language-specific colorizer setting that asks the colorizer to use a bold font for some constructs.

**Comment by tbpassin** [comment]
No doubt at all.  I just wondered if we could pin down @LewisNeal getting it and me not.
