### ISSUE TITLE
hard crash on UnicodeDecodeError

### ISSUE THREAD

**Issue by tuxlifan** [leo-editor/leo-editor#234]
Hello,

After some years I was looking again at learning Leo and going through the Leo Basics until http://leoeditor.com/slides/leo-basics-step-by-step/slide-010.html when I somehow mistyped and must have pressed multiple keys at once (one of them the 'ü' key on my keyboard with German layout) and then Leo crashed.

Unfortunately I was not able to reproduce the crash so far and I do not know yet enough about Leo to make much sense of the terminal output, so please feel free to direct me...
Last output:
[bug_unicodeCrash.txt](https://github.com/leo-editor/leo-editor/files/147157/bug_unicodeCrash.txt)

**Comment by edreamleo** [comment]
Why did you call this a hard crash.  Did Python itself crash? Did Leo exit?

**Comment by tuxlifan** [comment]
Leo was terminated with SIGABRT (my uninformed guess would be due to interaction of the UnicodeDecodeError with PyQt?) which made the window disappear instantly and lost all non-saved changes (nothing valuable at that point).
I put "hard crash" analogue to how it's used in [moneyguru's changelog](https://www.hardcoded.net/moneyguru/help/en/changelog.html) but I'll be happy to reword it if something else makes more sense here :)

I see that I had forgotten to mention the versions used:
Leo 5.1-final, build 20160216124246, Tue Feb 16 12:42:46 CST 2016
Git repo info: branch = master, commit = b42d85c3ac28
Python 2.7.11, PyQt version 5.5.1
(on Void Linux)

Thanks

**Comment by edreamleo** [comment]
Presumably fixed at 29c00a861e.
The new code forces everything to unicode with g.toUnicode.
No way to test the code, but it should work.  Pleases reopen if necessary.
