### ISSUE TITLE
vr3 command error with local variable 'stylefile' referenced before assignment

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#2345]
Leo Log Window
Leo 6.6b2-devel, devel branch, build 18b3eb88ea
2021-11-18 16:29:12 -0600
Python 3.9.5, PyQt version 5.15.2
darwin

***

Traceback (most recent call last):

  File "/Users/swot/app/leo-editor/leo/core/leoCommands.py", line 2157, in doCommand
    return_value = command_func(event)

  File "/Users/swot/app/leo-editor/leo/plugins/viewrendered3.py", line 1301, in toggle_rendering_pane
    vr3 = viewrendered(event)

  File "/Users/swot/app/leo-editor/leo/plugins/viewrendered3.py", line 1193, in viewrendered
    controllers[h] = vr3 = ViewRenderedController3(c)

  File "/Users/swot/app/leo-editor/leo/plugins/viewrendered3.py", line 1577, in __init__
    self.reloadSettings()

  File "/Users/swot/app/leo-editor/leo/plugins/viewrendered3.py", line 1852, in reloadSettings
    self.set_md_stylesheet()

  File "/Users/swot/app/leo-editor/leo/plugins/viewrendered3.py", line 1938, in set_md_stylesheet
    stylefile = stylefile.replace('\\', '/')

UnboundLocalError: local variable 'stylefile' referenced before assignment

**Comment by tbpassin** [comment]
Thanks for the bug report.  I'll track it down.  Funny I didn't hit that one myself.

**Comment by tbpassin** [comment]
@wangzhaoh, could you tell me what stylesheet you are asking for in the settings, or if you are not asking for any specific one?  The setting is _vr3-md-stylesheet_.

**Comment by tbpassin** [comment]
I have submitted a PR fixing this issue.  When it is approved and merged into the devel branch, the new version of VR3 will be 3.61.

**Comment by tbpassin** [comment]
The PR has been accepted.

**Comment by wangzhaohe** [comment]
> @wangzhaoh, could you tell me what stylesheet you are asking for in the settings, or if you are not asking for any specific one? The setting is _vr3-md-stylesheet_.

My md_styles.css:

@string vr3-md-stylesheet = file:/Users/swot/.leo/md_styles.css

**Comment by wangzhaohe** [comment]
Yes, it works well now!  Thanks a lot for you job. I will close this issue.

**Comment by tbpassin** [comment]
I think you need to have either _file:///_ or omit the _file_ protocol completely. It is true that the Markdown processor wants to have the file name prepended by _file:///_.  VR3 strips it off if present when it tries to locate the file (to check on its existence), and adds it back for the MD processor.

_file:/_ will confuse it, though.  I am fairly sure that if you use _file:///_ you will not see that error, even without my bug fix.  Even with the bug fix, VR3 will not be able to use the stylesheet if you use _file:/_.

I will consider doing some defensive programming here, but _file:///_ is actually the correct form even if some software uses different forms (some want only two slashes, for example)..
