### ISSUE TITLE
edit-pane-csv command. 'Qt' has no attribute 'WA_DeleteOnClose'

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#2347]
See PR #2355.

Run the edit-pane-csv command, the pane does not open and gives this error:
```
Traceback (most recent call last):

  File "N:\git\leo-editor\leo\core\leoCommands.py", line 2157, in doCommand
return_value = command_func(event)

  File "N:\git\leo-editor\leo\plugins\editpane\editpane.py", line 69, in edit_pane_csv
w.insert(-1, LeoEditPane(c=c, show_control=False, lep_type='EDITOR-CSV'))

  File "N:\git\leo-editor\leo\plugins\editpane\editpane.py", line 94, in __init__
self.setAttribute(QtConst.WA_DeleteOnClose)

AttributeError: type object 'Qt' has no attribute 'WA_DeleteOnClose'
```

_Leo Log Window
Leo 6.6b2-devel, devel branch, build 5077c3e188
2021-11-26 15:22:04 -0600
Python 3.9.8, PyQt version 6.2.1
Windows 10 AMD64 (build 10.0.19042)_ 

The error only occurs with PyQt6.

**Update**

There were several other crashes caused by missing Qt6 enums.  See the PR for details.

**Comment by edreamleo** [comment]
@LewisNeal The experimental fix is in the ekr-bug-2347 branch.  Please let me know how it works for you.

**Comment by LewisNeal** [comment]
There are no error messages. Message in logpane is: no command function for 'edit-pane-csv'
Running build 5854505b53

**Comment by edreamleo** [comment]
On Thu, Dec 9, 2021 at 5:52 PM LewisNeal ***@***.***> wrote:

> There are no error messages. Message in logpane is: no command function
> for 'edit-pane-csv'
> Running build 5854505
> <https://github.com/leo-editor/leo-editor/commit/5854505b53e6cd44f9e3c39d06fa403904d455de>
>

Strange. My log shows:
Leo 6.6b2-devel, ekr-bug-2347 branch, build 5854505b53
2021-12-09 06:58:43 -0600
LEP: __init__ LEP
LEP: Loaded module: plaintextedit
LEP: Loaded module: plaintextview
LEP: Loaded module: __init__
LEP: Loaded module: clicky_splitter
LEP: Loaded module: csvedit
LEP: Loaded module: editpane
LEP: Loaded module: leotextedit
LEP: Loaded module: markdownview
LEP: ImportError: Module not loaded (unmet dependencies?): pandownview
LEP: ImportError: Module not loaded (unmet dependencies?): vanillascintilla
LEP: Loaded module: webengineview
LEP: ImportError: Module not loaded (unmet dependencies?): webkitview
LEP: build layout
LEP: new edit position
LEP: update editor text
LEP: new view position
LEP: update edit position
LEP: update editor text
LEP: update view position
LEP:
register handlers
LEP: unregister handlers

I plan to merge the fix into devel soon, unless I hear from you.

Edward

**Comment by LewisNeal** [comment]
Here is full log pane:
Leo Log Window
Leo 6.6b2-devel, ekr-bug-2347 branch, build 5854505b53
2021-12-09 06:58:43 -0600
Python 3.9.8, PyQt version 6.2.2
Windows 10 AMD64 (build 10.0.19042) 
no command function for 'edit-pane-test-open'
no command function for 'edit-pane-csv'

Here is the console output:
no command function for 'edit-pane-test-open'
doCommandByName executeScript,executeScriptHelper,<module>,simulateCommand
no command function for 'edit-pane-csv'
doCommandByName executeScript,executeScriptHelper,<module>,executeMinibufferCommand

If I enter the _edit-pane-csv_ command in the minibuffer, it switches to the Completion tab and does not recognise the command as being complete.

**Comment by LewisNeal** [comment]
Thanks Edward, The pane now renders with Leo 6.6b2-devel, devel branch, build 220ba34f2a

**Comment by edreamleo** [comment]
On Fri, Dec 10, 2021 at 6:18 PM LewisNeal ***@***.***> wrote:

> Thanks Edward, The pane now renders with Leo 6.6b2-devel, devel branch,
> build 220ba34
> <https://github.com/leo-editor/leo-editor/commit/220ba34f2a9e0828bf811bb280785aee3d6998ee>
>

You're welcome. Thanks for the confirmation.

Edward
