### ISSUE TITLE
Pylint Does Not Operate On .pyw file

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#2354]
I have an outline with several @clean .py files, and one .pyw file.  Pylint does not find the file when asked to check the .pyw file, though it does find the .py files. .pyw files are common enough (I think) that they should be found too.

**Comment by tbpassin** [comment]
This appears to be happening in checkerCommands.py, in run() of the PylintCommand class.

**Comment by tbpassin** [comment]
Easy enough to add .pyw to the allowable files.  I'd like to know if there are any reasons not to do so.

**Comment by edreamleo** [comment]
Fixed at 8dc620b in devel.
