### ISSUE TITLE
abbrev-write generates different continuations than used in @data

### ISSUE THREAD

**Issue by ktenney** [leo-editor/leo-editor#236]
When defining abbreviations in a @data abbreviations node, 
continuation looks like:
continue;;=line 1
\: line 2
\: line 3

when abbreviations are dumped via abbrev-write they look like:
continue;;=line 1\n line 2\n line 3

I would consider the abbrev-write file more useful if it used the 
same continuation convention as in @data nodes

**Comment by edreamleo** [comment]
I am going to close this. Rev 1b2536c2 provisionally removes the abbrev-* commands in question.
