### ISSUE TITLE
add-editor CHANGE other node's body content to the Main body

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#2366]
Leo Log Window
Leo 6.6b2-devel, devel branch, build c65459bf14
2021-12-06 14:58:32 -0600
Python 3.9.5, PyQt version 5.15.2
darwin
redefining abbreviation date;; 
from '{|{x=time.asctime()}|}' to '{|{x=time.strftime("%Y/%m/%d")}|}'
redefining abbreviation html;; 
from '<html>\n<head>\n<title><|title|></title>\n<style>\n</style>\n</head>\n<body>\n<|content|>\n</body>\n</html>' to '@first <!DOCTYPE html>\n@language html\n@tabwidth -2\n\n<html>\n  <head>\n    <title><|title|></title>\n    <style>\n    </style>\n  </head>\n  <body>\n    <|content|>\n  </body>\n</html>'
redefining abbreviation ,, 
from "{|{x='__NEXT_PLACEHOLDER'}|}" to '__NEXT_PLACEHOLDER'
read 2 files in 0.04 seconds
read outline in 0.06 seconds
reading settings in /Users/swot/.leo/pp.leo

***

After some code write, then suddenly I FOUND the second body's contents had been changed to the Main body when I use `add-editor`.

This accours several times. I still don't known the reason. Lost some data!

**Comment by edreamleo** [comment]
I can not reproduce this problem. I am going to close this issue. Please reopen only if you can provide a way to reliably reproduce the problem.
