### ISSUE TITLE
@path weirdness

### ISSUE THREAD

**Issue by largo84** [leo-editor/leo-editor#2368]
Environment:

`Leo 6.4-devel, ekr-extract branch, build 8633da575c`
`2021-05-24 07:43:27 -0500`
`Python 3.7.3, PyQt version 5.9.6`
`Windows 10 AMD64 (build 10.0.19041) SP0`

1. Create a new node to match a valid path to a folder with subfolders and files, with node headline as: `@path D:\Folder`.
2. Double-click on the node to create child nodes of subfolders and files.
  * Child node headlines take the form of: `\Subfolder1\`, `\Subfolder2\`, etc.
  * This action appears to do almost the same thing as the commands: `active-path-load-recursive` and `active-path-act-on-node`.
3. Notice that after double-clicking the parent `@path D:\Folder` node, the headline text becomes: `D:\Folder` (inexplicably removing the `@path` prefix).
  * `CTRL-z` (undo) restores the correct headline text without removing the created child nodes.
4. Also notice similar behavior when double-clicking on a child node such as `\Subfolder1\`.
  * This creates child nodes of additional subfolders and files as expected.
  * Headline text becomes merely: `Subfolder1` (inexplicably removing the leading and trailing `\'s`).
  * Again, `CTRL-z` (undo) restores the `\'s` without removing the new child nodes.

I noticed this odd behavior began a long time ago, however I don't recall when. A few additional thoughts:

1. Using either the minibuffer commands `active-path-load-recursive` or `active-path-act-on-node`will also create the expected child nodes, but will leave the top-level node intact (doesn't change the headline text).
2. The expected behavior for double-clicking an `@path D:\Folder` node should be the same as the command `active-path-load-recursive`and leave the top-level headline text intact.
3. What is the difference in expected behavior between `active-path-load-recursive` and `active-path-act-on-node`? There is some F11 help information text for the former, none for the latter.

**Comment by tbpassin** [comment]
6.4 is fairly out of date. I suggest you try it with a more current _devel_ version (like 6.6b2) to make sure that it still behaves the same.  It probably will since I don't remember reading about changes to these commands, but it would still be a good idea.

**Comment by largo84** [comment]
`Leo 6.6b2-devel, devel branch, build 7d44a81064`
`2021-12-30 02:11:41 -0600`
`Python 3.7.3, PyQt version 5.9.6`
`Windows 10 AMD64 (build 10.0.19041) SP0`

Sorry, I always try to keep Leo current; must have gotten 'lost' in another branch (I'm not a GitHub expert). Anyway, just pulled in the most current `devel` branch and still see the same behavior as before.

**Comment by edreamleo** [comment]
@largo84 What is the value of `@bool tree-declutter` ? Decluttering munges headlines.

**Comment by edreamleo** [comment]
@largo84 Decluttering changes the *apparent* headlines, based on patterns. Clicking the headline shows the "real" headline. Imo, this is a confusing option. The default value for `@bool tree-declutter` is False in leoSettings.leo.

Hmm. I'm wondering whether decluttering somehow is being enabled by mistake.  I'll investigate.

**Comment by edreamleo** [comment]
I am going to close this issue. Please reopen only if you can provide a reliable way of reproducing the problem.

**Comment by edreamleo** [comment]
@largo84 Thanks for the clarification. I'll reopen this issue and look into it more closely.

**Comment by edreamleo** [comment]
@tbpassin Thomas, would you care to attempt a fix?

**Comment by tbpassin** [comment]
OK - can you give me a hint about finding these double-click events?

**Comment by tbpassin** [comment]
_"Notice that after double-clicking the parent @path D:\Folder node, the headline text becomes: D:\Folder (inexplicably removing the @path prefix)."_

This didn't happen in my quick tests.  Double clicking and the active-path-load-recursive seemed to work the same.

_"What is the difference in expected behavior between active-path-load-recursive and active-path-act-on-node? There is some F11 help information text for the former, none for the latter."_

Both commands have docstrings, and on my system F11 for _active-path-act-on-node_ does show `act_on_node handler for active_path.py`, which is the docstring.  Of course, that doesn't tell us much.

IOW, My system doesn't reproduce the issues that your system does.  I can't make any more progress until we can understand why there is a difference.

My system:

```
Leo 6.6b2-devel, devel branch, build ecac33058f
2022-02-19 08:43:17 -0600
Python 3.9.9, PyQt version 6.2.3
Windows 10 AMD64 (build 10.0.19043) 

```
```
Enabled plugins:
plugins_menu.py
viewrendered3.py
viewrendered.py
active_path.py
contextmenu.py
    # This is required by the vim.py and xemacs.py plugins.
leo_to_html.py
mod_scripting.py
nav_qt.py
python_terminal.py
quicksearch.py
screen_capture.py
freewin.py
```
My _tree-declutter_ setting is the default (set to False in leoSettings.leo)

**Comment by largo84** [comment]
Thanks for looking into it, @tbpassin. Other than a small difference in Python version and PyQt, I don't know what else might cause my experience to differ from yours.

`Python 3.9.7, PyQt version 5.9.7`

I suppose that until/unless others can duplicate the issue we should close it for now. It's not a deal-breaker, just an annoyance and there's a known workaround.

**Comment by edreamleo** [comment]
@largo84 Thanks.  Feel free to reopen if you get more insight :-)
