### ISSUE TITLE
Session-snapshot-load doesn't load network drives

### ISSUE THREAD

**Issue by largo84** [leo-editor/leo-editor#237]
Create a session snapshot including a .leo file on a network drive (not mapped to a drive letter). The command, session-snapshot-load will load all files *except* the network drive files.

Session-restore works as expected, no issues.

(Win10 with latest GitHub release, Python 3.4.3 and PyQt 5.4.1)

**Comment by edreamleo** [comment]
There is/was a related issue about @file not handling network designations properly. Afaik, that was never resolved.

**Comment by edreamleo** [comment]
Have you tried forward slashes, as recommended [here](http://stackoverflow.com/questions/12730025/python-accessing-windows-mapped-network-drive-with-known-url-but-unknown-drive)?

**Comment by largo84** [comment]
Well, actually the paths are auto-generated by Leo via session-refresh, -create or -save, so to change the slashes would require manually changing them I suppose. No, I haven't tried that.

**Comment by edreamleo** [comment]
> the paths are auto-generated by Leo via session-refresh, -create or -save.
Ok.  I'll look into changing them.

**Comment by edreamleo** [comment]
I'd like to fix this asap.  Please give an example of a path that doesn't work.  Thanks.

**Comment by largo84** [comment]
I tried again this morning and the odd thing is that session-restore works to load all entries in the @session node, including network paths. However, session-snapshot-load doesn't load *anything*.

I don't really know the difference between session and session-snapshot.

I'll have more time to experiment when I get home this evening.

**Comment by edreamleo** [comment]
I've added the "Waiting" label until I get more information about this.

**Comment by largo84** [comment]
It appears that it's working. I suggest closing this issue as there isn't a problem loading network paths (not sure why there was a problem previously).

**Comment by edreamleo** [comment]
@largo84 Thanks for the report.  I'll close this now.  Please reopen if need be.
