### ISSUE TITLE
Make Current Line Highlighting The Default?

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#2372]
Currently the feature to highlight the current line in body nodes is turned off by default. I haven't seen any complaints about it, but probably most people don't know it exists.  There is an item in the Help menu that explains how to turn it on but most people will probably not have spotted it.

I suggest that the default should be **on**.  That would require a single line in leoSettings.leo.

The main risk I see is that the highlight color might not be to someone's liking depending on their theme's colors.  The automatic color selection can be overridden, as explained in the Help item, but again people may not realize it.

**Comment by edreamleo** [comment]
When a new feature arrives in Leo, I prefer to make the relevant settings default to legacy behavior. That way nothing changes unless people opt in to the change.
