### ISSUE TITLE
When body text lines more than 100 => body display can not scroll to bottom in vim-mode

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#2374]
Leo Log Window
Leo 6.6b2-devel, devel branch, build bdd9ba7442
2022-01-10 17:30:14 -0500
Python 3.9.5, PyQt version 5.15.2
darwin

***

Use arrow key is ok but j or G.

I find this situation lives in a long time.

Is this pyqt's bug?

**Comment by edreamleo** [comment]
The 'gg' and 'G' keys work for me with:

Python 3.9.6, PyQt version 6.2.3
Windows 10 AMD64 (build 10.0.22000) SP0
