### ISSUE TITLE
unauthenticated git protocol on port 9418 is no longer supported.

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#2375]
I just tried to pull latest devel and received message:
$ git pull
_fatal: remote error:
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information._

At link see heading:
'No more unauthenticated Git'
On the Git protocol side, unencrypted git:// offers no integrity or authentication, making it subject to tampering. We expect very few people are still using this protocol, especially given that you can’t push (it’s read-only on GitHub). We’ll be disabling support for this protocol.
When are these changes effective?
January 11, 2022 
Final brownout.
This is the full brownout period where we’ll temporarily stop accepting the deprecated key and signature types, ciphers, and MACs, and the unencrypted Git protocol. This will help clients discover any lingering use of older keys or old URLs.
[end]

Does this require changes for new leo builds?

**Comment by edreamleo** [comment]
On Tue, Jan 11, 2022 at 12:22 AM LewisNeal ***@***.***> wrote:

> I just tried to pull latest devel and received message:
> $ git pull
>
>
> *fatal: remote error: The unauthenticated git protocol on port 9418 is no
> longer supported. Please see
> https://github.blog/2021-09-01-improving-git-protocol-security-github/
> <https://github.blog/2021-09-01-improving-git-protocol-security-github/>
> for more information.*
>
Iirc, I got this message several months ago. The fix must be on your
end--it has nothing to do with Leo.

> Does this require changes for new leo builds?
>
No, afaik.

Edward

**Comment by LewisNeal** [comment]
The _git pull_ command is working as expected again with
Leo 6.6b2-devel, devel branch, build a492b4814d

**Comment by edreamleo** [comment]
@LewisNeal Thanks for the confirmation.
