### ISSUE TITLE
Add a tip: how to refer to a node from another node.

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#2376]
Add a tip to the [Useful Tips](https://leoeditor.com/tutorial-tips.html) page on Leo's web site.

Note: there seems to be no need to support gnx's in UNL's. The following issues have been marked "Won'tDo":

#1842: show gnx in status line.
#1868: support clickable links based on gnx's.

**Comment by edreamleo** [comment]
Completed at rev 1adc977 in devel.

**Comment by fakio** [comment]
Hi @edreamleo, not sure if this is the right place to comment but the docs [1] say to use "->" as a separator but it seems "-->" is the right separator.

[1] https://leoeditor.com/tutorial-tips.html#ctrl-click-urls-and-unls

**Comment by edreamleo** [comment]
On Mon, Dec 5, 2022 at 8:18 PM Fabricio Watanabe ***@***.***>
wrote:

> Hi @edreamleo <https://github.com/edreamleo>, not sure if this is the
> right place to comment but the docs [1] say to use "->" as a separator but
> it seems "-->" is the right separator.
>
Thanks for this report. The problem arises from typography.  I'll clarify
this line (and others as needed).

See #2995 <https://github.com/leo-editor/leo-editor/issues/2995>.

Edward
