### ISSUE TITLE
Expat Will Need Updating For Security Fixes

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#2379]
The expat xml parser has just had a number of overflow and other security fixes.  Expat is everywhere, and in Leo it's explicitly in the mypy_stubs plugin.  Nothing can be done, probably, until the updated version (2.4.3) makes its way into Pypi, Python distro updates, etc., so this is just a heads up.

See

[Expat 2.4.3 released, includes security fixes](https://blog.hartwork.org/posts/expat-2-4-3-released/)

**Comment by edreamleo** [comment]
On Sun, Jan 16, 2022 at 11:38 AM tbpassin ***@***.***> wrote:

> The expat xml parser has just had a number of overflow and other security
> fixes. Expat is everywhere, and in Leo it's explicitly in the mypy_stubs
> plugin.
>

The only uses I see in Leo are of xml.sax.saxutils.escape and in the
leoOPML.py plugin. There is no such plugin as mypy_stubs.py.

Edward

**Comment by tbpassin** [comment]
That's a little weird.  I did a search with FileLocatorPro and it found a directory of that name within my Git tree for Leo:

`C:\Tom\git\leo-editor\leo\plugins\mypy_stubs`

However, I don't see that _mypy_stubs_ directory in current versions of the devel branch.  It must be left over from something from the past.  It's not something that I ever knowingly added.  I suppose there won't be any harm done if I remove it.
