### ISSUE TITLE
AttributeError message

### ISSUE THREAD

**Issue by largo84** [leo-editor/leo-editor#2383]
Environment:

`Leo Log Window`
`Leo 6.6b2-devel, devel branch, build 84513dfa47`
`2022-01-14 04:25:29 -0500`
`Python 3.7.3, PyQt version 5.9.6`
`Windows 10 AMD64 (build 10.0.19041) SP0`

I started getting this error message a few days ago when Leo launches (don't recall which update first caused it).

`Traceback (most recent call last):`

  `File "...\leo\leo\plugins\qt_gui.py", line 1226, in runMainLoop`
`g.app.gui.show_tips()`

  `File "...\leo\leo\plugins\qt_gui.py", line 1340, in show_tips`
`m = self.DialogWithCheckBox(controller=self, tip=tip)`

  `File "...\leo\leo\plugins\qt_gui.py", line 1317, in __init__`
`cb.setCheckState(QtConst.CheckState.Checked) # #2127.`

`AttributeError: type object 'CheckState' has no attribute 'Checked'`

(... is the path to my current GitHub repo directory.)

**Comment by tbpassin** [comment]
No such problem today on

```
Leo 6.6b2-devel, devel branch, build bfab1372ce
2022-01-19 08:36:14 -0500
Python 3.9.9, PyQt version 5.15.2
Windows 10 AMD64 (build 10.0.19043) 

```

**Comment by tbpassin** [comment]
Also no such problem with the same changeset and Python 3.7.9:

```
Leo 6.6b2-devel, devel branch, build bfab1372ce
2022-01-19 08:36:14 -0500
Python 3.7.9, PyQt version 5.15.2
Windows 10 AMD64 (build 10.0.19041) SP0
```

**Comment by edreamleo** [comment]
@tbpassin How did you test the reported crash?

**Comment by tbpassin** [comment]
The original post says "I started getting this error message a few days ago when Leo launches" so I just looked after launch. After launch, Leo seemed to run normally.

**Comment by largo84** [comment]
To clarify, Leo launches and runs just fine (no crash). The error message shows up in the log pane in red text. It's apparently related to the tool tips window. In the past, a random tip would display at startup. Now, it doesn't.

Just pulled current this morning:

`Leo 6.6b2-devel, devel branch, build e26346f382`
`2022-01-20 05:34:03 -0500`
`Python 3.7.3, PyQt version 5.9.6`
`Windows 10 AMD64 (build 10.0.19041) SP0`

**Comment by tbpassin** [comment]
I turned the tool tips back on (I don't normally use them) and I don't see any log messages like that.  I do get a message printed to the console:

`show_tips <PyQt5.QtWidgets.QPushButton object at 0x0000028BFE81F940>`

I don't think of that as a error message, though.

**Comment by edreamleo** [comment]
I am going to close this issue. I see no problems with python 3.9, with either Qt5 or Qt6.

**Comment by largo84** [comment]
I updated my environment to Python 3.9.7:

`Leo 6.6b2-devel, devel branch, build 464d9fbbe9`
`2022-01-22 08:20:12 -0500`
`Python 3.9.7, PyQt version 5.9.7`
`Windows 10 AMD64 (build 10.0.19043) SP0`

I get a similar error as before (different error, same source file):

`Traceback (most recent call last):`

  `File "...\leo\leo\plugins\qt_gui.py", line 1228, in runMainLoop`
`g.app.gui.show_tips(c)`

  `File "...\leo\leo\plugins\qt_gui.py", line 1343, in show_tips`
`self.update_tips_setting()`

  `File "...\leo\leo\plugins\qt_gui.py", line 1356, in update_tips_setting`
`if c and self.show_tips_flag != c.config.getBool('show-tips', default=False):`

`AttributeError: 'LeoQtGui' object has no attribute 'show_tips_flag'`

Different from before, the tooltips window now opens when Leo launches. There's no other apparent problem as Leo runs fine (as far as I can tell so far). It seems curious that others don't see this; makes me wonder why.

As far as fixing it, it's not a big deal if it isn't since there's no apparent impact on operations, but thought the additional context might be noteworthy.

**Comment by LewisNeal** [comment]
see #2389

**Comment by tbpassin** [comment]
Could be a Qt thing.  My system is using PyQt version 5.15.2.  I wouldn't have thought so, but you never know.

**Comment by edreamleo** [comment]
On Sat, Jan 22, 2022 at 7:03 PM Rob Keeney ***@***.***> wrote:

> I updated my environment to Python 3.9.7:...
>
> I get a similar error as before (different error, same source file):
>
> Traceback (most recent call last):
>
> File "...\leo\leo\plugins\qt_gui.py", line 1228, in runMainLoop
> g.app.gui.show_tips(c)
>
> File "...\leo\leo\plugins\qt_gui.py", line 1343, in show_tips
> self.update_tips_setting()
>
> File "...\leo\leo\plugins\qt_gui.py", line 1356, in update_tips_setting
> if c and self.show_tips_flag != c.config.getBool('show-tips',
> default=False):
>
> AttributeError: 'LeoQtGui' object has no attribute 'show_tips_flag'
>

Thanks for this report. This is a real bug, revealed by recent
refactorings. I have just created #2390
<https://github.com/leo-editor/leo-editor/issues/2390> for it. The fix will
be surprisingly tricky.

Edward

**Comment by edreamleo** [comment]
On Sat, Jan 22, 2022 at 10:54 PM tbpassin ***@***.***> wrote:

> Could be a Qt thing.
>
No. The bugs are clearly in Leo.

Edward
