### ISSUE TITLE
Is thers a plan to support markdown table in vr3?

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#2388]
I think that will be excited to support markdown table in vr3 like this!

```
| Shortcut | Action                |
|----------|-----------------------|
| `<M-x>`  | Normal mode           |
| `<M-c>`  | Quit current terminal |
| `<M-n>`  | Go one window left    |
| `<M-e>`  | Go one window below   |
| `<M-u>`  | Go one window above   |
| `<M-i>`  | Go one window right   |
| `<M-t>`  | Go to previous tab    |
```

| Shortcut | Action                |
|----------|-----------------------|
| `<M-x>`  | Normal mode           |
| `<M-c>`  | Quit current terminal |
| `<M-n>`  | Go one window left    |
| `<M-e>`  | Go one window below   |
| `<M-u>`  | Go one window above   |
| `<M-i>`  | Go one window right   |
| `<M-t>`  | Go to previous tab    |

**Comment by tbpassin** [comment]
VR3 supports Markdown by sending it to a Markdown processor.  Currently I am using _python-markdown_.  This package has an extension that will do tables.  I will see if this does in fact work, and if it does, I will update VR3 to use that extension.

If it does not work, that would mean a different Markdown processor would be needed.  More than likely, it would need different code to perform the conversion.  That would take some additional work, to have two different code branches depending on which Markdown processor is installed and should be used.  But it would be doable if there is such a processor.

**Comment by tbpassin** [comment]
I have got this working.  See the attached screen shot.  If this suits you, I will put in a PR.  Just let me know.
![vr3-md-example](https://user-images.githubusercontent.com/36974235/150648683-8cd629a7-a982-4445-8355-5c7dea3167de.png)

**Comment by wangzhaohe** [comment]
> | Shortcut | Action                |
> |----------|-----------------------|
> | `<M-x>`  | Normal mode           |
> | `<M-c>`  | Quit current terminal |
> | `<M-n>`  | Go one window left    |
> | `<M-e>`  | Go one window below   |
> | `<M-u>`  | Go one window above   |
> | `<M-i>`  | Go one window right   |
> | `<M-t>`  | Go to previous tab    |

Yes, it is wonderful. Thanks a lot!

**Comment by wangzhaohe** [comment]
> I have got this working. See the attached screen shot. If this suits you, I will put in a PR. Just let me know. ![vr3-md-example](https://user-images.githubusercontent.com/36974235/150648683-8cd629a7-a982-4445-8355-5c7dea3167de.png)

Yes, it is wonderful. Thanks a lot!

**Comment by tbpassin** [comment]
All right.  It will be a few more days because I am also improving the support for MathJax math typesetting.

**Comment by tbpassin** [comment]
This work has been done and the PR is waiting for approv al.

**Comment by tbpassin** [comment]
This work has been merged into the devel branch.

**Comment by wangzhaohe** [comment]
I have tested it and run well. Thanks for your good job!

> This work has been merged into the devel branch.

**Comment by tbpassin** [comment]
Thank you :)
