### ISSUE TITLE
cfa fails to find many occurrences of the target string

### ISSUE THREAD

**Issue by SegundoBob** [leo-editor/leo-editor#239]
In general, cfa finds 0 occurrences.  I've succeeded in getting only one find from cfa:  I ran "cff IPython" and it found six matches.  Then I ran "cfa IPython" and it found one match.  This match was the "Found:IPython" node created by the cff command.

This problem is either trivially easy to cause to happen, or something is really messed up on my system, or I seriously misunderstand how cff and cfa are supposed to work.

Test System:
```
Leo 5.1.1-devel, build 20160304101518, Fri Mar  4 10:15:18 CST 2016
Git repo info: branch = None, commit = 14125e9dbaca
Python 3.4.3, PyQt version 5.2.1
linux
```

**Comment by edreamleo** [comment]
Thanks for the report.  I'll look into it.

**Comment by edreamleo** [comment]
This was a simple blunder.

**Comment by SegundoBob** [comment]
Thanks.

I confirm that this problem has been fixed.

I tested:
```
Xubuntu 64-bit 14.04.1
Leo Log Window
Leo 5.1.1-devel, build 20160306181005, Sun Mar  6 18:10:05 CST 2016
Git repo info: branch = None, commit = bc68bc0d5573
Python 3.4.3, PyQt version 5.2.1
linux
```
