### ISSUE TITLE
body won't scroll to end of text

### ISSUE THREAD

**Issue by tbnorth** [leo-editor/leo-editor#240]
See this thread:
https://groups.google.com/forum/#!topic/leo-editor/_J3pgNP7VKo
Probably the redraw and scroll issues area related, not sure.
Scroll problem is hard to reproduce but I think you can do it with a long body, with the bottom scrolled off the view, then inserting something with middle button paste or ctrl-V paste, then a keystroke (like Enter).
Will try and find time to git bisect on my home machine.  @edreamleo @JohnLunzer

**Comment by JohnLunzer** [comment]
I can confirm this as a method to reproduce, this was affecting me heavily today.

**Comment by tbnorth** [comment]
First bisect attempt failed, steps to reproduce require only a few lines not visible at bottom, if more than a few, it doesn't happen.  Second attempt succeeded, coming up where I was afraid it would...

d7fbe36556be7d754d09735eeacbf7c6b31ae668 is the first bad commit
commit d7fbe36556be7d754d09735eeacbf7c6b31ae668
Author: Edward K. Ream <edreamleo@gmail.com>
Date:   Thu Mar 3 04:32:59 2016 -0600

    Use the official Qt way of showing invisibles.
    With a few additions from the discussion at
    https://groups.google.com/forum/#!topic/leo-editor/a65H2X90CHc
    In particular, tabs are now handled properly.

**Comment by edreamleo** [comment]
> Use the official Qt way of showing invisibles.

Thanks for your work on this, Terry.

Not great news, but let's not give up hope just yet...There may be a way to get everything we want.

**Comment by edreamleo** [comment]
I am not seeing any problems.  What platform are you on, and what version of PyQt?

**Comment by edreamleo** [comment]
Terry, or whoever, please send me a .leo file containing detailed instructions about how to see the bug in action, including platform, version of Python and version of PyQt/Qt.  Thanks.

Unless a quick fix can be found, I'll add a g.new_invisibles switch that reverts to the old code when False.

**Comment by edreamleo** [comment]
66fcf27c44 may fix this bug. It uses a considerably simpler scheme.
It reverts to the old setWrap code.  Almost surely this will fix the wrap bug.
The only question is whether wrapping and invisibles play nice. All appears well.

I'll leave this open for now.  Please report your experiences.

**Comment by tbnorth** [comment]
I think it's fixed, bit it would be good to get @JohnLunzer  to confirm. Also I wasn't using the invisibles, so I can't comment on the impact on that.

For posterity, seen in both Win 7 and Ubuntu 14.04 with py 2.7 and qt ~4.8.  To reproduce I did

    HOME=/tmp python launchLeo.py

copy / pasted the log message into the body of a node until I had over 120 lines in the body, then scrolled the last *few* lines off below the view, then copy a ~10 chars., move cursor to end of line, <space>, either middle button or ctrl-v paste, <enter>.

The would be an odd jump in the scroll position, and scrolling down with the mouse wouldn't work, even though more text was known to exist below the view, switching nodes or even just scrolling up then down would allow normal scrolling again.

**Comment by edreamleo** [comment]
On Wed, Mar 9, 2016 at 9:50 AM, Terry Brown <notifications@github.com>
wrote:

​> ​
I think it's fixed, bit it would be good to get @JohnLunzer
<https://github.com/JohnLunzer> to confirm
​.
​
​Thanks, Terry.  And thanks for the recipe for seeing the bug in action.

EKR

**Comment by edreamleo** [comment]
I'll mark this as closed now.  Please reopen if there are problems.

**Comment by JohnLunzer** [comment]
I will try to test this today and if not today then tomorrow.
