### ISSUE TITLE
Quicksearch plugin traceback

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#2402]
Click the Nav Tab and search for a node name which has duplicates.
I'm not completely certain how to reproduce the error, but as you type the node name and the node choices appear, this message is reported in log pane:

Uncaught exception in Leo...
Traceback (most recent call last):
  File "N:\git\leo-editor\leo\plugins\quicksearch.py", line 397, in dumper
    self.throttler.add(out)
  File "N:\git\leo-editor\leo\plugins\threadutil.py", line 138, in add
    QtCore.QTimer.singleShot(self.granularity * 1000, callit)
TypeError: arguments did not match any overloaded call:
  singleShot(int, PYQT_SLOT): argument 1 has unexpected type 'float'
  singleShot(int, Qt.TimerType, PYQT_SLOT): argument 1 has unexpected type 'float'
[end]

_Leo Log Window
Leo 6.6b2-devel, devel branch, build 62272c8861
2022-02-06 19:21:20 -0600
Python 3.10.1, PyQt version 6.2.3
Windows 10 AMD64 (build 10.0.19042) SP0_

**Comment by tbpassin** [comment]
Maybe that's why I got a crash yesterday using the same pane.  I didn't notice an error and just restarted, but Leo just stopped and closed without a message as it displayed the headline hits.

**Comment by edreamleo** [comment]
Rev 6582d5a in devel should fix this problem.
