### ISSUE TITLE
UNL traceback in linked file

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#2407]
When a UNL is activated this traceback appears in the linked file tab:
Leo Log Window
Leo 6.6b2-devel, devel branch, build 50e21a633d
2022-02-07 15:21:06 -0600
Python 3.10.2, PyQt version 6.2.3
Windows 10 AMD64 (build 10.0.19042) SP0
read outline in 0.09 seconds
Traceback (most recent call last):

  File "N:\git\leo-editor\leo\core\leoGlobals.py", line 7783, in openUrlOnClick
return openUrlHelper(event, url)

  File "N:\git\leo-editor\leo\core\leoGlobals.py", line 7821, in openUrlHelper
g.handleUnl(unl, c)

  File "N:\git\leo-editor\leo\core\leoGlobals.py", line 7738, in handleUnl
p = g.findUNL(unl.split("-->"), c2)

AttributeError: 'NoneType' object has no attribute 'split'

**Comment by LewisNeal** [comment]
I just realised this only occurs if the UNL is in body text, which is likely not where the link should be placed :/
No traceback if the UNL is the node headline.

**Comment by tbpassin** [comment]
Not sure what @LewisNeal means by "activated", but when I CTRL-click on a UNL in a node body, it goes correctly to the right node in the referenced file even if that file needs to be opened.  I don't spot any messages. (This is with the same changeset).

**Comment by edreamleo** [comment]
Fixed at ref cf20ab9 in devel.
