### ISSUE TITLE
UNL regex includes trailing quotes, etc in UNL

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#2410]
The current regex for UNLs incorrectly includes trailing characters such as quotes, apostrophes, and backticks (and others) in the matched UNL, which prevents handleUnl() from navigating to the correct location.

The effect is easy to spot since Leo colors UNLs.  The trailing character(s) are seen to also be colored.  The regex for urls does not include these characters.

Why might one use quotes or backticks?  I came across this when writing some notes that I expected to render with VR3, yet still be clickable in the body node.

Here is an example (the backticks look right in the preview, so here's hoping they show up correctly in the final message):

URL (OK):       \``http://www.mit.edu``
UNL (not OK): \``unl://~/.leo.workbook.leo``

Paste these into a node and note the coloration.  Or type an actual UNL into a node, CTRL click on it to verify it goes the the right place, then add the backticks and verify that it does not go to the right place. (To do this properly, after the first CTRL click, select a different node in the target outline, then return to the test node and CTRL click again.  You will go to the correct outline but not the target node).

**Comment by edreamleo** [comment]
Fixed at rev 641d03 in devel.
