### ISSUE TITLE
Leo Forgets To Reopen Outlines, Loads Cheatsheet Then Closes It

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#2412]
When Leo opens, after loading the first file from the previous session (workbook.leo), Leo then opens CheatSheet.leo briefly (which had not been open), then closes it and fails to load any other of the previously open outlines.  The Leo splash screen is visible throughout this process.

This is new behavior.  Deleting the  ~/.leo/db folder did not fix it, but after doing so Leo isn't remembering its previous size, either.

```
Leo 6.6b2-devel, devel branch, build 70d0da6013
2022-02-13 19:27:02 -0600
Python 3.9.9, PyQt version 5.15.2
Windows 10 AMD64 (build 10.0.19043)
```

**Comment by edreamleo** [comment]
PR #2424 closes this issue.
