### ISSUE TITLE
Allow QtWebEngineWidgets in PyQt6

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#2415]
Apparently, in PyQt6, QtWebEngineWidgets must be imported before creating the main Qt app.

Thomas will create a new PR for this issue.

**Comment by tbpassin** [comment]
As I wrote in a Google Groups thread, it can be done more gracefully.  Let's give a bit more aging time before diving in.

[How To Import QtWebEngineWidgets using PyQt6](https://groups.google.com/g/leo-editor/c/3PuBaCztf5A)

**Comment by edreamleo** [comment]
@tbpassin Please create your own PR for this, based on your own branch.  Thanks.

**Comment by edreamleo** [comment]
Fixed at rev 73a343fa9a via a PR from Thomas.
