### ISSUE TITLE
TravisCI: Error: Version 3.6 with arch x64 not found

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#2421]
See: https://github.com/leo-editor/leo-editor/runs/5202493680?check_suite_focus=true

Not sure what this means. Presumably we may need to change the TravisCI arguments.

**Update**: The test fails in 'master' with the 'ekr-test' branch that adds only a comment, so recent commits have nothing to do with this issue.

[This issue](https://github.com/actions/setup-python/issues/162) may be related.

**Comment by tbpassin** [comment]
Could the archx64/python3.6 VM have been automatically updated such that 3.6 was removed or taken off the path?  I could see that happening via an ordinary OS update.

**Comment by edreamleo** [comment]
PR #2429 works around this problem.
