### ISSUE TITLE
Leo Is Inserting The Cheat Sheet into my Workbook On Every Leo Start

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#2423]
Every time I've started Leo for the last few days, a copy of the Cheat Sheet outline is getting inserted into my workbook outline.  Sometimes it gets inserted at the end, sometimes the beginning, sometimes in the middle.  Sometimes some of the child nodes end up at the top level.

I deleted the db folder once but it's still happening.

This is extremely annoying, and in deleting the unwanted nodes I have accidentally deleted a node I wanted.  This started before the latest changeset for devel, but I'm  not sure what changeset was in effect when this started.

**Comment by edreamleo** [comment]
On Tue, Feb 15, 2022 at 10:16 AM tbpassin ***@***.***> wrote:

> Every time I've started Leo for the last few days, a copy of the Cheat
> Sheet outline is getting inserted into my workbook outline.
>
I'm sorry to hear that!

How exactly are you opening the workbook? The following works for me:

python39 c:\leo.repo\leo-editor\launchLeo.py

But something is strange. workbook.leo is (as expected) an empty shell, but
it exists in my home directory, not the home/.leo directory as reported at
the top of the .leo file!

This is surely related to #2412
<https://github.com/leo-editor/leo-editor/issues/2412>. Could you do a git
bisect to find the offending commit? Thanks.

Edward

**Comment by tbpassin** [comment]
There's something else seriously wrong here.  There is nothing in the .leo/db folders.  So where could this phantom worksheet be coming from????  Also, why isn't Leo storing at least its size and open outlines in the db folders?

**Comment by tbpassin** [comment]
I'm beginning to see the light here.  I went back to a commit from 7 months ago, and starting with no workbook, Leo creates one and loads it with starter material.  This starter material is exactly what has been getting added to my own, preexisting workbook in recent builds.

**Comment by tbpassin** [comment]
Found it!  The first commit to devel that has this behavior is:

```
8bfded4a9f481271c447d1740855ff9405d1690f
Rewrite p.get_UNL, ignoring all kwargs
```

The behavior happens whether or not I have deleted the db folder.  But it seems to not happen sometimes the first time after I switch to a different commit - don't know how that can be.  Leo opens the workbook.leo outline, then opens the cheatsheet outline, then apparently copies it into the workbook  and then closes the cheatsheet.

This does not happen if I explicitly  put the workbook.leo on the command line when opening Leo.

**Comment by tbpassin** [comment]
More information: when I've had several outlines open when I closed Leo, then when I re-open it only the workbook outline gets opened, and  the cheatsheet outline inserted into it.  The other files that were open don't get opened.  But  `g.app.sessionManager.load_snapshot()`, which is supposed to be the list of outlines to open, does include the other files (at least, once Leo has staibilized after opening).

So summarize what appears to happen, on startup:

1.  Leo opens the workbook outline if it can find it.
2. Then it wrongly thinks it did not find the workbook and inserts the contents of the cheatsheet outline into the existing workbook outline, as if that workbook were a newly created, empty outline..
3. Then it ignores or does not know about the session manager snapshot, so any other files that used to be open don't get opened.

**Comment by tbpassin** [comment]
I may have found the bug.  In `LM.openEmptyWorkBook()`, we have:

```
    fn = lm.computeWorkbookFileName()
   # ....
    if g.app.batchMode and g.os_path_exists(fn):
        return c
    # Open the cheatsheet.
    fn = g.os_path_finalize_join(g.app.loadDir, '..', 'doc', 'CheatSheet.leo')
    if not g.os_path_exists(fn):
        g.es(f"file not found: {fn}")
        return None
    # Paste the contents of CheetSheet.leo into c.
    old_clipboard = g.app.gui.getTextFromClipboard()  # #933: Save clipboard.
```
 
So even if the workbook file exists, we will go ahead an create one unless we are in  `g.app.batchMode`.  It seems like the _and_ should be an _or_.

Fixing this still leaves the matter of not reopening the other files in the last session even though the session file contains them.

**Comment by edreamleo** [comment]
On Tue, Feb 15, 2022 at 11:25 AM tbpassin ***@***.***> wrote:

> There's something else seriously wrong here. There is nothing in the
> .leo/db folders. So where could this phantom worksheet be coming from????
>
I'm investigating.

Edward

**Comment by edreamleo** [comment]
On Tue, Feb 15, 2022 at 12:16 PM tbpassin ***@***.***> wrote:

> I'm beginning to see the light here. I went back to a commit from 7 months
> ago, and starting with no workbook, Leo creates one and loads it with
> starter material. This starter material is exactly what has been getting
> added to my own, preexisting workbook in recent builds.
>
Yes. That's not surprising.

Edward

**Comment by edreamleo** [comment]
On Tue, Feb 15, 2022 at 11:25 AM tbpassin ***@***.***> wrote:

> There's something else seriously wrong here. There is nothing in the
> .leo/db folders. So where could this phantom worksheet be coming from????
>
leo-editor/leo.session contains a list of UNL's. This may be part of the
problem.

I suspect that the relevant code is in LM.doPostPluginsInit.

As you say in another post, the commit that changed UNL's caused the
problem.  The workaround, for now, is to specify the files you want to open
explicitly, rather than rely on the session machinery.

Expect a fix tomorrow.

Edward

**Comment by edreamleo** [comment]
On Tue, Feb 15, 2022 at 3:14 PM tbpassin ***@***.***> wrote:

> I may have found the bug.
>
Yes.  Looks like you have.

Also, the change in the format of UNL's affects
SessionManager.load_session.  In the loop, just before:

    i = unl.find("#")

it looks like the following two lines should be inserted:

    if unl.startswith('unl://'):  # #2412.
      unl = unl[len('unl://'):]

I've got to go now, but feel free to experiment.

Edward

**Comment by tbpassin** [comment]
Yes, I just found that too.  The UNLs are being treated as file names, so they can't be found by os_path_exists.

I'm more inclined to write

```
      if unl.startswith('unl://'):  
          unl = unl.split('unl://')[1]
```

But that's a trivial matter of taste.

I wonder where else this change might cause similar issues.

**Comment by tbpassin** [comment]
OK, I'm going with
```
        if i > -1:
            fn, unl = unl[:i], unl[i:]
            fn_ = fn.split('unl://')  # #2412.
            if len(fn_) > 1:
                fn = fn_[1]
```

I'll put in a PR for these two fixes.

**Comment by tbpassin** [comment]
I've been getting messages from Github about this PR failing because of the Python 3.6 issue.  I've never gotten PR messages before, and since it's my PR I don't think I should be the one to give approval (if in fact I can even do that) despite the failed CI test.

Edward, how do you suggest I should proceed, or should I just leave it to you?

**Comment by edreamleo** [comment]
@tbpassin The TravisCI failures are annoying, but that's a separate issue. I just merged your work into devel, which also closes this issue.
