### ISSUE TITLE
Distinguish Between Visible and Invisible Changes For Changed Outlines

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#2437]
When Leo thinks an outline has been changed, it shows an asterisk in its tab, and puts up a save dialog if you try to close it.  This is essential behavior ... except that save-worthy changes include invisible things like setting or unsetting marks on nodes, changes that do not involve changed text or outline organization, for example.

I often find I'm not sure if I want to save a changed outline because I don't want to change the text (maybe I typed or deleted something by mistake) and I've forgotten if I've changed which nodes are marked.

The simplest solution I can think of from a UI point of view is to use a different character in the tab if the changes are solely for marks or some other invisible change (I'm not sure if there are other invisible changes or not).  A better solution would add some informatory text to the save dialog.  From an implementation point of view, I don't know how hard these changes would be.

**Comment by edreamleo** [comment]
On Sat, Feb 19, 2022 at 10:44 PM Thomas Passin ***@***.***>
wrote:

> When Leo thinks an outline has been changed, it shows an asterisk in its
> tab, and puts up a save dialog if you try to close it. This is essential
> behavior ... except that save-worthy changes include invisible things like
> setting or unsetting marks on nodes, changes that do not involve changed
> text or outline organization, for example.
>
> I often find I'm not sure if I want to save a changed outline because I
> don't want to change the text (maybe I typed or deleted something by
> mistake) and I've forgotten if I've changed which nodes are marked.
>
> The simplest solution I can think of from a UI point of view is to use a
> different character in the tab if the changes are solely for marks or some
> other invisible change (I'm not sure if there are other invisible changes
> or not). A better solution would add some informatory text to the save
> dialog. From an implementation point of view, I don't know how hard these
> changes would be.
>
The simplest thing is to leave things as they are.

Use the git-diff command to discover what text changes you have made
recently.

I have zero interest in complicating Leo to solve a workflow problem.

Edward
