### ISSUE TITLE
clickable link broken. no attribute 'es_clickable_link'

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#2438]
I get this message when running a script containing a clickable link.

Traceback (most recent call last):

  File "N:\git\leo-editor\leo\core\leoCommands.py", line 723, in executeScript
c.executeScriptHelper(args, define_g, define_name, namespace, script)

  File "N:\git\leo-editor\leo\core\leoCommands.py", line 764, in executeScriptHelper
exec(compile(script, scriptFile, 'exec'), d)

  File "C:/Users/lewis/.leo/scriptFile.py", line 15, in <module>
g.es_clickable_link(c, p, 1, f"{node_name}")

AttributeError: module 'leo.core.leoGlobals' has no attribute 'es_clickable_link'

I checked Leo-Docs and I'm sure the script is correct.

_Leo Log Window
Leo 6.6b2-devel, devel branch, build ecac33058f
2022-02-19 08:43:17 -0600
Python 3.10.2, PyQt version 6.2.3
Windows 10 AMD64 (build 10.0.19042) SP0_

**Comment by edreamleo** [comment]
On Sun, Feb 20, 2022 at 5:45 AM LewisNeal ***@***.***> wrote:

> I get this message when running a script containing a clickable link.
>
...

> File "C:/Users/lewis/.leo/scriptFile.py", line 15, in
> g.es_clickable_link(c, p, 1, f"{node_name}")
>
> AttributeError: module 'leo.core.leoGlobals' has no attribute '
> es_clickable_link'
>
My apologies for the inconvenience. Rev 7a8e3d7
<https://github.com/leo-editor/leo-editor/commit/7a8e3d761a9eb133a92ae789959a33dcf18b4f9f>
in devel restores a new, tested, version of g.es_clickable_link.

g.es_clickable_link borders on a faux helper, but I think it's worthwhile
to retain it for compatibility.

Edward

**Comment by edreamleo** [comment]
Fixed at rev 7a8e3d7 in devel.

**Comment by LewisNeal** [comment]
Thanks Edward. I noticed the two show-clone commands clickable link feature still worked and seemed to use UNL code.
Could the revised UNL code replace the older clickable link feature?

**Comment by edreamleo** [comment]
On Sun, Feb 20, 2022 at 2:05 PM LewisNeal ***@***.***> wrote:

> Thanks Edward.
>
You're welcome.

> I noticed the two show-clone commands clickable link feature still worked
> and seemed to use UNL code.
> Could the revised UNL code replace the older clickable link feature?
>
Yes.  Just do a cff on 'nodeLink' to see the present applications. There
were two main changes to the UNL-related code:

- p.get_UNL() no longer takes any keyword args.
- new-style UNL's can optionally end in '::' followed by a line number.
old-style UNL's end in ':' followed by up to 4 ints.

Edward
