### ISSUE TITLE
Unable to run Leo on MacOS yosemite

### ISSUE THREAD

**Issue by kilon** [leo-editor/leo-editor#244]
I cloned this repo, I installed the dependencies with : 

brew install qt sip pyqt

and tried to run Leo but I got this error

> python launchLeo.py

setting leoID from os.getenv('USER'): 'kilon'
reading settings in /Users/kilon/git/leo-editor/leo/config/leoSettings.leo
Traceback (most recent call last):
  File "launchLeo.py", line 8, in <module>
    leo.core.runLeo.run()
  File "/Users/kilon/git/leo-editor/leo/core/runLeo.py", line 63, in run
    g.app.loadManager.load(fileName, pymacs)
  File "/Users/kilon/git/leo-editor/leo/core/leoApp.py", line 2056, in load
    lm.doPrePluginsInit(fileName, pymacs)
  File "/Users/kilon/git/leo-editor/leo/core/leoApp.py", line 2122, in doPrePluginsInit
    lm.createGui(pymacs)
  File "/Users/kilon/git/leo-editor/leo/core/leoApp.py", line 2147, in createGui
    lm.createSpecialGui(gui_option, pymacs, script, windowFlag)
  File "/Users/kilon/git/leo-editor/leo/core/leoApp.py", line 2162, in createSpecialGui
    g.app.createDefaultGui()
  File "/Users/kilon/git/leo-editor/leo/core/leoApp.py", line 1097, in createDefaultGui
    app.createQtGui(fileName, verbose=verbose)
  File "/Users/kilon/git/leo-editor/leo/core/leoApp.py", line 1117, in createQtGui
    import leo.plugins.qt_gui as qt_gui
  File "/Users/kilon/git/leo-editor/leo/plugins/qt_gui.py", line 12, in <module>
    import leo.plugins.qt_big_text as qt_big_text
  File "/Users/kilon/git/leo-editor/leo/plugins/qt_big_text.py", line 6, in <module>
    import leo.plugins.qt_text as qt_text
  File "/Users/kilon/git/leo-editor/leo/plugins/qt_text.py", line 434, in <module>
    class LeoLineTextWidget(QtWidgets.QFrame):
AttributeError: 'NoneType' object has no attribute 'QFrame'

**Comment by edreamleo** [comment]
In future, please ask for help before reporting a bug. I have tested this code on Yosemite with the Anaconda installation of Python, which is good for supporting IPython and Jupyter notebooks.

`AttributeError: 'NoneType' object has no attribute 'QFrame'` indicates an installation problem with QtWidgets. You might want to do something like `brew upgrade`, but I'm no MacOS expert.

Anyone else have suggestions?

**Comment by edreamleo** [comment]
You can set the `trace` switch to True in leoQt.py.  This will trace the import commands related to Qt.  All of Leo's core, including leo/plugins/qt_text.py, use leoQt.py to do the imports, so to the first approximation the imports in leoQt.py tell the whole story.

**Comment by edreamleo** [comment]
I am going to close this because it's an installation issue and because we are discussing it on leo-editor.

**Comment by kilon** [comment]
yes this is an installation problem with brew and QT , it seems the pyQT is not visible by macos default python

**Comment by edreamleo** [comment]
On Fri, Mar 18, 2016 at 8:12 AM, kilon <notifications@github.com> wrote:

> yes this is an installation problem with brew and QT , it seems the pyQT
> is not visible by macos default python
>
That's good news here. ​ Have you tried installing Anaconda?

Edward

**Comment by kilon** [comment]
For anyone with similar problem the homebrew instruction for adding PyQT to the import path are wrong. Instead edit 
~/.bash_profile

and add this line

export PATH="/usr/local/lib/python2.7/site-packages:${PATH}"

after this leo editor will open with using the default python installation provided by MacOS

There is no need to use Anacoda so no I dont use it. 

You may want to put this into your documentation for other MacOS users to find because as it is , leo editor is no go for the MacOS.

**Comment by edreamleo** [comment]
On Fri, Mar 18, 2016 at 9:43 AM, kilon <notifications@github.com> wrote:

> For anyone with similar problem the homebrew instruction for adding PyQT
> to the import path are wrong. Instead edit
> ~/.bash_profile
>
> and add this line
>
> export PATH="/usr/local/lib/python2.7/site-packages:${PATH}"
>
> after this leo editor will open with using the default python installation
> provided by MacOS
> ​.
>
>
​Thanks for this.  I'll update the docs.

EKR

**Comment by kilon** [comment]
my pleasure and congratulations on your amazing work :) :+1:
