### ISSUE TITLE
Debug the script written in Tcl programming language within `leo-editor`.

### ISSUE THREAD

**Issue by hongyi-zhao** [leo-editor/leo-editor#2443]
Can I debug the script written in [Tcl](https://www.tcl.tk/) programming language within `leo-editor`? Are there any examples/tutorials for this type of work?

Regards,
HZ

**Comment by edreamleo** [comment]
@hongyi-zhao Leo can colorizer tcl scripts, but afaik Leo has no way to execute or debug tcl scripts directly.

It should be straightforward to invoke tcl scripts from Leo using an `@button` script. That script would run tcl in a separate process, say with g.execute_shell_commands. 

Note that scripts.leo contains several old tcl scripts.
