### ISSUE TITLE
g.handleUrl() Fails When Node Headline Ends With Space

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#2448]
To demonstrate:
1. Create a node with some headline.
2. Copy its unl; for example, by selecting and copying from the status line, or by using getUNL().
3. In another node, paste the unl from above.
4. CTRL-click the unl string.
5.  Verify that the target node becomes selected as expected.
6. Add a space to the end of the target node's headline.
7. Repeat steps 2 - 4.
8. Observe that the selected node does not change to the target node.

I have noticed that the string to be CTRL-clicked on *can* contain a trailing space and the navigation will still work.  But the headline cannot.

This bug occurs also using g.handleUnl(), which is no surprise since CRTL-clicking invokes it.

**Comment by tbpassin** [comment]
IMO, `p.get_UNL()` should return the equivalent of unl.strip(), and `g.handleUnl()` should operate on unl.strip().  This way, accidental leading or trailing spaces will not prevent navigating to the target.

**Comment by edreamleo** [comment]
@tbpassin Thanks for this report. I agree that this bug should be fixed. I'm not sure exactly how to do that, but it shouldn't be too difficult.
