### ISSUE TITLE
Wrong Theme Name Reported After Loading a New Theme File

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#2451]
When a new theme outline is opened, the current version of Leo opens it, and then all open tabs change to use the new theme.  That's a desired feature.

However, in the situation, the method `g.app.loadManager.computeThemeFilePath()` returns the original theme, not the one currently in effect.  There seem to be some other theme-related methods that also return the old values.  I can see the effects, though I haven't tracked them down yet.

One of these is the method that the line highlighter computes its settings - the highlight color remains based on the original theme.  I don't think that should be changed.  Instead, the Leo functions that return information about the theme should be reporting on the effective theme instead of the original one in myLeoSettings.leo. or LeoSettings.leo.

```
Leo 6.6-rc1-devel, tbp_vr3 branch, build 657b2f8e22
2022-02-25 11:49:25 -0500
Python 3.9.9, PyQt version 5.15.2
Windows 10 AMD64 (build 10.0.19043) 
```

**Comment by edreamleo** [comment]
@tbpassin Thanks for this report, and your continued careful testing.

**Comment by edreamleo** [comment]
@tbpassin In my tests the syntax colors do change to those specified in the newly-loaded theme file.

Handling theme data is a complex startup issue. I would rather not change anything unless truly necessary.

I am going to close this issue, but I will consider a PR.

**Comment by tbpassin** [comment]
I think I'm getting an understanding here.  Yes, the colors change after a new theme has been loaded, but not because the new theme file has been loaded as a theme.  Instead, all the settings in the file get read as would any settings.  They override the previous settings - that is, there is no distinction between theme settings and any other settings.  In fact, any outline might have settings that override theme settings.

If this is so, Leo cannot know that a new theme file is in use, because a new theme has not been loaded as a theme, but only as an outline.  So the effective theme will be the theme of the most recently opened or reloaded outline.  We can get its name this way:

c1 = g.app.commanders()[-1]
g.es(c1.config.getString('theme-name'))

I tried this and it does work.  So there is no need for any changes to Leo's theme handling code.

For some reason, theme settings in the newly opened outline applied as global settings instead of just locally for that outline.   What I don't understand is this:  If I change the colors by loading a different theme file, the colors in all tabs change as discussed above.  If I then open another outline, the color change to match the theme either the original theme or the theme that was in effect last time that outline had been open, I'm not sure which.  I don't see how this comes about.

However it happens, querying the theme-name setting for the most recently opened commander seems to return the right name.  So I will be able to use that to get the line-highlighting color to update to match the new theme.  Expect a PR for tis in due course.

**Comment by edreamleo** [comment]
@tbpassin Thanks for this update!  It's great news.
