### ISSUE TITLE
Undoing Everything Should Clear The Outline's Dirty Status

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#2458]
In some editors (e.g., EditPlus and VSCode), if you open a file, type into it, and then undo all the typing, the file's "dirty" status gets changed back to "clean".  This is convenient, and helps you avoid getting confused if you really undid everything, or doing an unnecessary save.  Leo does not behave this way.

There are workarounds, such as _Revert To Saved_, but they are less convenient.

I wonder if implementing this would be relatively easy for Leo.  If so, I'd like for Leo to have this behavior.

**Comment by edreamleo** [comment]
Iirc, Leonistas have discussed this or similar issues in the past. Leo's undo state is complex, and there are cases where undoing "everything" might not do what is expected. I'd like to leave things as they are now.
