### ISSUE TITLE
UNSUBSCRIBE

### ISSUE THREAD

**Issue by misdvickysue** [leo-editor/leo-editor#246]
I ACCIDENTALLY SUBSCRIBED TO THIS AND I NEED TO UNSUBSCRIBE FROM GITHUB...TY

**Comment by edreamleo** [comment]
In future, please do not post bugs when asking for help. Afaik, only you can unsubscribe.

**Comment by tbnorth** [comment]
Heh, not sure someone who accidentally subscribes and posts in all caps would be familiar with afaik (As Far As I Know :-)  @edreamleo - can you remove people from the list at:
https://groups.google.com/forum/#!forum/leo-editor ?

**Comment by edreamleo** [comment]
On Wed, Mar 23, 2016 at 9:06 AM, Terry Brown <notifications@github.com>
wrote:

> Heh, not sure someone who accidentally subscribes and posts in all caps
> would be familiar with afaik (As Far As I Know :-) @edreamleo
> <https://github.com/edreamleo> - can you remove people from the list at:
> https://groups.google.com/forum/#!forum/leo-editor ?
>

​I didn't find a way.

EKR

**Comment by misdvickysue** [comment]
I FOUND A WAY....THANK YOU

Sent from Yahoo Mail on Android 
 
  On Wed, Mar 23, 2016 at 10:01 AM, Edward K. Ream<notifications@github.com> wrote:   On Wed, Mar 23, 2016 at 9:06 AM, Terry Brown <notifications@github.com>
wrote:

> Heh, not sure someone who accidentally subscribes and posts in all caps
> would be familiar with afaik (As Far As I Know :-) @edreamleo
> <https://github.com/edreamleo> - can you remove people from the list at:
> https://groups.google.com/forum/#!forum/leo-editor ?
>

​I didn't find a way.

EKR
