### ISSUE TITLE
Freewin Added Comment Re Pylint No Longer Applicable?

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#2461]
A comment has been inserted into plugins/freewin.py just after the docstring:

`# This file hangs pylint.`

It doesn't hang on my machine, Qt5.  In fact, pylint scores it at 9.97.  Can I remove this comment sometime, or is there something I don't know about here?

**Comment by tbpassin** [comment]
Strange it would hang for you but not for me, both with Python 3.9.x.  I'll try it with pyqt6 and see if that makes any difference.

**Comment by tbpassin** [comment]
Using pyqt6, pylint doesn't hang either.  I do get a lot of this kind of comment:

```C:\Tom\git\leo-editor\leo\plugins\freewin.py:714:25: I1101: Module 'PyQt5.QtCore' has no 'QRect' member, but source is unavailable. Consider adding this module to extension-pkg-allow-list if you want to perform analysis based on run-time introspection of living objects. (c-extension-no-member)```

```
Leo 6.6-rc1-devel, tbp_vr3 branch, build c0c73b8d26
2022-03-07 13:18:40 -0500
Python 3.9.9, PyQt version 6.2.3
Windows 10 AMD64 (build 10.0.19043) 
```
Maybe your pylint config file has changed and doesn't agree with mine?

**Comment by edreamleo** [comment]
@tbpassin I agree, this could be a configuration issue. I'm happy to hear that freewin passes your mypy. That should be good enough for now.

**Comment by tbpassin** [comment]
I haven't tried mypy, just pylint.

**Comment by tbpassin** [comment]
I just ran mypy on the freewin.py file.  While it was running it appeared to freeze Leo, but I left it alone and several minutes later it had finished - and Leo still worked.  Pretty good results (using pyqt6):

```
leo\core\leoGlobals.py:4989: error: Library stubs not installed for "requests" (or incompatible with Python 3.9)  [import]
leo\core\leoGlobals.py:4989: note: Hint: "python3 -m pip install types-requests"
leo\core\leoGlobals.py:4989: note: (or run "mypy --install-types" to install all missing stub packages)
leo\core\leoGlobals.py:4989: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
leo\core\leoTips.py:83: error: Library stubs not installed for "requests" (or incompatible with Python 3.9)  [import]
leo\plugins\freewin.py:329: error: Need type annotation for "instances" (hint: "instances: Dict[<type>, <type>] = ...")  [var-annotated]
Found 3 errors in 3 files (checked 1 source file)
mypy: done
```

**Comment by edreamleo** [comment]
@tbpassin Thanks for the mypy report. I ran mypy in various ways (with types-requests installed) and got no errors.
