### ISSUE TITLE
@language c breaks goto-global-line

### ISSUE THREAD

**Issue by jurov** [leo-editor/leo-editor#247]
When I add "@language c" declaration into top node of @file or @clean tree , Goto global line stops working. It sometimes refuses to work even without it, but I haven't figured how else to trigger it. 
"@language python" works. This is both in v5.2 and latest master. 

In 5.1-final it worked (obv. only with @file) but line numbers were off by 1.

**Comment by edreamleo** [comment]
Fixed at cd6c5995c, with a new unit test.
