### ISSUE TITLE
stickynotes.py plugin -- able to open multiple stickynotes for the same node, leads to inconsistent data

### ISSUE THREAD

**Issue by gatesphere** [leo-editor/leo-editor#2471]
See PR #2473.

Create a leo outline with some nodes, which contain some data.  Ensure the stickynotes.py plugin is enabled.

Alt-X stickynote on one of your nodes a few times -- note that it opens multiple windows.

Edit text in one of those note windows.  The other one does not update.  The outline does.  This leads to a confusing state where there are conflicting (and incorrect) views of the data held within the node.

I believe that running the 'stickynote' command on a node with an already existing stickynote should just do a .show() call on that note widget, rather than opening another one.  Allowing only one stickynote widget per vnode would prevent the inconsistent views.

**Comment by gatesphere** [comment]
Thank you for this quick fix.

**Comment by edreamleo** [comment]
@gatesphere You're welcome.
