### ISSUE TITLE
stickynotes.py plugin -- closing an outline with open stickynotes does not close the notes

### ISSUE THREAD

**Issue by gatesphere** [leo-editor/leo-editor#2472]
Create a leo outline with some nodes.  Ensure stickynotes.py plugin is enabled.

Alt-X stickynote on one of your nodes.  Close the outline.

The note window remains open, apparently holding an ephemeral copy of the data that was in the node.

Not sure if this could lead to a crash or data corruption, but at best it's confusing.  Could lead to lost data if a user assumed the outline backing the now-phantom node was still open and saving.

**Comment by edreamleo** [comment]
@gatesphere I don't see the behavior you report.  In fact, I don't see how it's possible for the Qt widgets to persist after g.app goes away.

Please include Leo's signon messages so I can see the system you are using.

**Comment by tbpassin** [comment]
I'm not sure how the stickynote plugin works, but I solved this problem for Freewin (which produces a freefloating editor window tied to a host node) by checking on every update cycle to see if the host node still exists, even if it had been moved:

```
    # Make sure our host node still exists
    if not self.c.p.v == self.v:
        # Find our node
        found_us = False
        for p1 in self.c.all_unique_positions():
            if p1.v == self.v:
                self.p = p1
                found_us = True
                break
        if not found_us:
            self.teardown(tag)
            return
```
The teardown() code is also called if the outline gets closed.

**Comment by tbpassin** [comment]
@edward: "I don't see the behavior you report. In fact, I don't see how it's possible for the Qt widgets to persist after g.app goes away"

He only mentioned closing the outline, not Leo itself.

**Comment by gatesphere** [comment]
> He only mentioned closing the outline, not Leo itself.

This is correct -- sorry, I should have been more precise.  If you have multiple outlines open, stickynote a node, and close just the outline that the stickynote-d node belongs to, the window persists.

My environment, where I just confirmed this behavior (after a fresh pull of your recent work):

Leo Log Window
Leo 6.6-rc1-devel, devel branch
Python 3.7.4, PyQt version 5.15.2
Windows 10 AMD64 (build 10.0.19041) SP0

**Comment by edreamleo** [comment]
@tbpassin Thanks for the clarification. This issues should be relatively easy to fix.

@gatesphere Thanks for the data. Now that I understand the issue, I see that the platform should not matter.

**Comment by edreamleo** [comment]
PR #2474 fixes this issue.

**Comment by gatesphere** [comment]
Thanks for this quick fix too.  Can confirm this fixes the issue.

**Comment by edreamleo** [comment]
@gatesphere You're welcome. Thanks for the testing.
