### ISSUE TITLE
Make Open Outline Work With StringIO

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#2483]
It could be useful to be able to open a Leo outline from a string, presumably using StringIO.  The main use case would be to support reading of remote Leo outlines: the client would receive the outline as a string, and the idea is to load this string as if it were a file (though it wouldn't actually have a file name).

**Comment by edreamleo** [comment]
@tbpassin There is already a (far-from-obvious) way to do this:

    FastRead().readFileFromClipboard(s)

where s is an xml string.  Does this suffice for your purpose?

**Comment by tbpassin** [comment]
How the heck do you use it?  The best I've figured out so far is

```
from leo.core.leoFileCommands import FastRead as FR
v = FR(c, c.fileCommands.gnxDict).readFileFromClipboard(s)
```

but this doesn't seem to do anything except return the hidden root (of the current outline, I presume).  No outline go created, and I don't see that anything  got inserted.

**Comment by edreamleo** [comment]
On Mon, Mar 14, 2022 at 4:53 PM Thomas Passin ***@***.***>
wrote:

> How the heck do you use it? The best I've figured out so far is
>
> from leo.core.leoFileCommands import FastRead as FR
> v = FR(c, c.fileCommands.gnxDict).readFileFromClipboard(s)
>
> I'm not completely sure that readFileFromClipboard is what is needed, but
s must contain the contents of the .leo file.

See fc.getLeoFile for an example of using FastRead.readFile.  Note the init
code and the actual call:

    v = FastRead(c, self.gnxDict).readFile(theFile, fileName)
  if v:
    c.hiddenRootNode = v

The task would be to adapt this code for your purposes.

HTH.  Btw, these are just guesses on my part.

Edward

**Comment by tbpassin** [comment]
Got it working:

```
from leo.core.leoFileCommands import FastRead as FR

# Use workbook as a target for testing
home = g.app.homeLeoDir
fname = g.os_path_finalize_join(home, 'workbook.leo')
with open(fname, encoding = 'utf-8') as f:
    s = f.read()

# Create new outline
c1 = c.new()

# Construct tree from outline string
fr = FR(c1, c1.fileCommands.gnxDict)
v = fr.readFileFromClipboard(s)  # It isn't actually in the clipboard!

# Shove new tree into commander of the new outline
c1.hiddenRootNode = v
c1.redraw()
```

You can also do it using _readFile_ and _StringIO_, but this is a little simpler.

Whew! A lot of effort to come up with something basically simple.  Hard when it's all undocumented.  Coming up with that gnxDict was one of the hard parts.  Getting the right import was another.  And assigning the new hidden root node to the new commander was a pure guess.

There must be something more to do, though, because if I close the newly created outline without saving, I don't get a warning message.  Maybe setting a dirty flag somewhere?

**Comment by edreamleo** [comment]
@tbpassin Call c.setChanged(True) to ensure Leo will warn when closing the outline.

But (big oops!), the code above does not read any external files, nor does it call at.rememberReadPath for any of those files. As a result, Leo might not warn (when saving the .leo file) that a dirty external file has not been saved. 

It looks like my first answer, based on FastRead().readFileFromClipboard(s), was misleading.

Perhaps you should start with fc.getLeoFile, or maybe fc.openLeoFile, which is a thin wrapper for fc.getLeoFile.  Both of these methods take "theFile" and "fileName" positional arguments. I suspect things will work properly if theFile is a StringIO.

**Comment by tbpassin** [comment]
readFile() works too as I said, as long as the _path_ arg is an empty string.  But there is still no file path for the commander to know about.

I don't think the others take an open file-like object, do they?

**Comment by tbpassin** [comment]
That's right, setting c.setChanged(True) did not cause a warning to be issued before closing the unsaved outline.

**Comment by tbpassin** [comment]
I couldn't get the warning on save by doing anything with setting dirty status.  But a little hack works fine - add a space to the end of the top position's body, then remove it.  So here is the current code:

```
from leo.core.leoFileCommands import FastRead as FR

# Get test outline
home = g.app.homeLeoDir
fname = g.os_path_finalize_join(home, 'workbook.leo')
with open(fname, encoding = 'utf-8') as f:
    s = f.read()

# Create new outline
c1 = c.new()

# Construct tree from outline string
fr = FR(c1, c1.fileCommands.gnxDict)
v = fr.readFileFromClipboard(s)

# Shove new tree into commander of the new outline
c1.hiddenRootNode = v

c1.redraw()  # Needed to create positions
p0 = c1.rootPosition()
c1.selectPosition(p0)

# A hack to force warning on save
b = p0.b + ' '
p0.b = b
p0.b = b[:-2]
```

I suppose that none of the new outlines @settings settings will be activated, but I think that's probably all right.  None of any external files (@file, etc) would have content - which might be a problem - but that would happen even if one saved the string to a leo file and opened it from that file.

I'm not really sure how any external files ought to be handled, if at all.

**Comment by edreamleo** [comment]
@tbpassin I am tempted to remove the 6.6 milestone, but I won't pull the plug just yet :-)

**Comment by tbpassin** [comment]
"p0.setDirty() and c.setChanged(True) should work." They don't, though.  Could it be that some hook needs to be run?

Not only external @file  files, but other external resources - like, say, images that are exist in the file system and are referenced in rst trees - wouldn't be carried over.

Yes, let's remove the 6.6 milestone for now.

**Comment by tbpassin** [comment]
I solved the problem of letting the commander know the new outline should be saved - by using the right commander with setChanged() - but there was one last problem. The top node was selected but not highlighted in the tree view.  I couldn't see where that happens in the ordinary code to create a new outline.  Then I realized that it's the same as if the tree item had been clicked, and I looked at that code. The only place I could see that might highlight the item was in the call to `g.doHook("headclick1")` or `g.doHook("headclick2")`.

Turns out that "headclick1" does the job.  So finally, here's working code (though with no error checking):

```
from leo.core.leoFileCommands import FastRead as FR
def openOutlineFromString(s):
    """Create a new outline pane from a string.
    
    The string must contain an XML-format Leo outline.
    """
    # Create new outline
    c1 = c.new()

    # Construct tree from outline string
    fr = FR(c1, c1.fileCommands.gnxDict)
    v = fr.readFileFromClipboard(s)  # Note that we haven't actually used the clipboard

    # Shove new tree into commander of the new outline
    c1.hiddenRootNode = v

    p0 = c1.rootPosition()
    c1.selectPosition(p0)

    # Highlight root node in tree as if we had clicked on it
    g.doHook("headclick1", c=c1, p=p0, event=None)

    c1.setChanged()
    c1.redraw()

```
