### ISSUE TITLE
External Non-Python File Checking On Save

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#2488]
One of the really helpful features of Leo, at least for programming, is the way it checks external python files for common errors before saving them.

Leo would be more useful as a general programming IDE if it could do the same for other languages.  I realize that it probably can't make many of the live checks for other languages that it can for Python, but at least it could do some syntax checking for, e.g., C++, TypeScript, or Java, depending on the tools available, of course.

It sounds as if there should be a general framework for doing this.  There kind of is, since we have the Python checking on Save, the pylint and the mypy checking.

I suggest that a general file checking framework be pulled together, such that existing tools for other languages can be used.

One technique that some IDEs use is having an external server that does much of the work.  Maybe Leo could use one of the existing ones.

**Comment by edreamleo** [comment]
@tbpassin An interesting idea. I have no plans at present to do this myself.
