### ISSUE TITLE
 unauthenticated git protocol on port 9418 is no longer supported

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#2490]
Current devel is build 1662f7a7e9.  Running _git pull_ command I see get:

fatal: remote error:
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.

The last build downloaded was 0e82a46980.

**Comment by LewisNeal** [comment]
From the github link above it appears that temporary changes first noticed Jan 11 (#2375) are now permanent:
<html><body>


March 15, 2022 | Changes made permanent. We’ll permanently stop accepting DSA keys. RSA keys uploaded after  the cut-off point above will work only with SHA-2 signatures (but again,  RSA keys uploaded before this date will continue to work with SHA-1).  The deprecated MACs, ciphers, and unencrypted Git protocol will be  permanently disabled.
-- | --


</body>
</html>

_At the heading **Git protocol troubleshooting**
.....For existing repositories, if you’re having trouble fetching, check that the remote you are fetching from is an ssh:// or https:// URL, or an SSH pseudo-URL starting with git@github.com. You can run git remote -v in the repository to see the URLs for all remotes. If any of them start with git://, you should change the URL to a supported format._

For Leo repository:
$ git remote -v
origin  git://github.com/leo-editor/leo-editor (fetch)
origin  git://github.com/leo-editor/leo-editor (push)

It seems Leo URLs should be updated to a supported format.
Are any other git users having the same problem?

**Comment by LewisNeal** [comment]
I updated my .gitconfig file using command:
$ git config --global url."https://github.com/".insteadOf git://github.com/

So now when I do
$ git remote -v
origin  https://github.com/leo-editor/leo-editor (fetch)
origin  https://github.com/leo-editor/leo-editor (push)

The Leo URLs are now in a supported format _https://_ and git pull works.

**Comment by edreamleo** [comment]
@LewisNeal Thanks for these comments.  I am going to close this issue. Please reopen if something in Leo must change.
