### ISSUE TITLE
PyQt5 vs PyQt6 differences in QtWebEngineCore

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#2498]
In LeoQt5 we have:

```
    try:
        from PyQt5 import QtWebEngineCore as QtWebKit
    except ImportError:
```

Aliasing QtWebEngineCore to QtWebKit has some historical reasons.  And the code goes on to this:

  ```
      import PyQt5.QtWebEngineWidgets as QtWebKitWidgets  # type:ignore
      QtWebKitWidgets.QWebView = QtWebKitWidgets.QWebEngineView
```

In Qt6, some parts of QtWebEngineWidgets  have been split off into PyQt6.QtWebEngineCore. 
 I encountered this with QWebEnginePage, which for Qt6 is in QtWebEngineCore instead of QtWebEngineWidgets.

In the little project where I discovered this issue, I ended up with this:

```
try:
    QWebEnginePage = QtWebEngineWidgets.QWebEnginePage
    navtypeTyped = QWebEnginePage.NavigationTypeTyped
    navtypeLinkClicked = QWebEnginePage.NavigationTypeLinkClicked
except AttributeError:
    from PyQt6.QtWebEngineCore import QWebEnginePage
    navtypeTyped = QWebEnginePage.NavigationType.NavigationTypeTyped
    navtypeLinkClicked = QWebEnginePage.NavigationType.NavigationTypeLinkClicked

QWebEngineView = QtWebEngineWidgets.QWebEngineView
```

Note that this also handles some enums that changed from Qt5 to Qt6.  This works fine, but it would be better if it were not necessary to use PyQt6 specifically by name.

Maybe for now it would be enough for leo.core.leoQt to add QWebEnginePage to the exported names, and later see what else if anything it should also export.  I would also like it to export QWebEngineView by name so we wouldn't have to keep calling it QtWebKitWidgets.QWebEngineView. (We'd need to keep QtWebKitWidgets.QWebEngineView too, for backwards compatibility).

**Comment by edreamleo** [comment]
@tbpassin Thanks for this issue. I've delegated it to you and assigned it to Leo 6.6.1

**Comment by edreamleo** [comment]
@tbpassin What is the status of this issue?  Can it be closed?

**Comment by tbpassin** [comment]
It can be closed after you merge https://github.com/leo-editor/leo-editor/pull/2646.

**Comment by edreamleo** [comment]
@tbpassin Done.  In the future, please make sure you assign the proper milestone to PRs and issues. That way my filters will show them to me.
