### ISSUE TITLE
Leo can't open files if launching terminal is closed

### ISSUE THREAD

**Issue by tbnorth** [leo-editor/leo-editor#25]
I've been suspecting this to be the case for some time, not a new bug, but hard to pin down.  For me, in my setup, if I launch Leo from a command line and then close the terminal session from which Leo was launched, Leo stops opening new files.

  exception opening /home/tbrown/Proj/GlobalGL/ggl.leo

is all you get in the log.

A work around is to launch Leo from something that doesn't generate a closeable terminal session, like the desktop's menu system.  Or just not close the shell of course, but that's hard if the number of shells you have open fluctuates a lot, you don't want to have to remember "can't close that one", particularly if some other app. dies messily there and you have no more use for the window.

Leo Log Window
Leo 4.11 final, build cc9f8a2c9067 (branch: master), 2014-04-28 09:17:51
Python 2.7.5, qt version 4.8.4
linux2

**Comment by edreamleo** [comment]
I am going to close this because it has the wontfix label.

**Comment by tbnorth** [comment]
I think I may have seen this in Windows today, and I habitually dodge it in linux by launching Leo with
```
(cd ~ && nohup leo)
```
Maybe it would be better to poke the assignee with a pointed stick rather than add wontfix and then close sometime later because there's a wontfix label.  Or we could create a new label for some of these fiddly things, um, "fiddly" for example, or something else.  Or if you really don't want these things hanging around open, we could label them "unresolved" or something when they're closed, so we can still find them later.

**Comment by edreamleo** [comment]
@tbnorth Why not say that "wontfix" corresponds to "fiddly"? And consider yourself poked ;-)
