### ISSUE TITLE
equal-sized-panes should resize viewrendered pane

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#250]
[Initial discussion](http://groups.google.com/group/leo-editor/browse_thread/thread/583bc0a31a6c7979) was in June, 2011.

**Comment by tbnorth** [comment]
Glad this is assigned to you ;-) I can't think how equal sized panes wouldn't resize vr.

**Comment by edreamleo** [comment]
@tbnorth I think it is possible to detect, say, a pane created by viewrendered3, but it hardly seems worth the effort.  I am going to mark this "wont' do".
