### ISSUE TITLE
onBodyChanged() Missing

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#2503]
What happened to `c.frame.body.onBodyChanged`?   I don't find  `body.bodyChanged()` either, although `<< About handling events >>` in leoFrame.py refers to it.  What are we supposed to call for the undoer instead of `c.frame.body.onBodyChanged(undoType, oldSel=oldSel)`?

This has messed up some of my scripts.

**Comment by tbpassin** [comment]
Is this the new Undo pattern for body changes?

```
p, u = c.p, c.undoer
bunch = u.beforeChangeBody(p)
# Change the body
u.afterChangeBody(p, 'command-name', bunch)
```
Are these changes to the undo pattern documented somewhere?  I suppose I must have seen something about them when they got changed but it went completely out of my memory.

Also, what is the difference between a body change and a group change?

**Comment by tbpassin** [comment]
Using the above pattern in my modified script, undoing the changes does work, but I  am seeing log messages like this:

```
updateAfterTyping p.b != w.getAllText() p: QWebEngineView - How To Intercept Anchor Clicks
w:  <QTextEditWrapper: 2091032431056 body>
executeScript,executeScriptHelper,<module>,afterChangeBody
```

Is this message claiming that there is something wrong?  If so, what?  Or if nothing is wrong, it would be better not to emit a message.

**Comment by tbpassin** [comment]
Turns out that when I use the script to insert to add text to a node, the text gets added.  But when I select a different node and then select the previous  one, the body text has vanished.  Apparently there is something more to the undo pattern, and I don't know what it is.

**Comment by tbpassin** [comment]
All right, I got it working, but I think it's weird.  I changed from

```
w = c.frame.body.wrapper
w.insert(0, newtext)
```

to

`p.b = newtext`

I say it's weird because it's natural to think that both ways of writing to the body would have the same effect so far as an undoer is concerned.  I would think we've got a bug here.

**Comment by edreamleo** [comment]
On Sun, Mar 20, 2022 at 2:03 PM Thomas Passin ***@***.***>
wrote:

> All right, I got it working, but I think it's weird. I changed from
>
> w = c.frame.body.wrapper
> w.insert(0, newtext)
>
> to
>
> p.b = newtext
>
> I say it's weird because it's natural to think that both ways of writing
> to the body would have the same effect so far as an undoer is concerned. I
> would think we've got a bug here.
>
This is not a bug!  w.insert affects only the text widget. Please see the
docstring for the node p.b property.

See also PR #2252 <https://github.com/leo-editor/leo-editor/pull/2253> (PR
for #1733: remove c.onBodyChanged). Please change any affected scripts.

BTW, from any PR, searching for "is:pr onBodyChanged" will show all the
relevant PR's.

Edward

**Comment by tbpassin** [comment]
I searched leoPyRef, and of course didn't find onBodyChanged anymore.  Then I looked there for code that had undo and used that as a guide.    I didn't think of searching  PRs.

Is there any reason to use `p.b = newtxt` vs `p.v.b = newtext` in this connection?

**Comment by edreamleo** [comment]
On Sun, Mar 20, 2022 at 4:21 PM Thomas Passin ***@***.***>
wrote:

> I searched leoPyRef, and of course didn't find onBodyChanged anymore. Then
> I looked there for code that had undo and used that as a guide. I didn't
> think of searching PRs.
>
Searching PR's and issues is a useful tool to have.

> Is there any reason to use p.b = newtxt vs p.v.b = newtext in this
> connection?
>
Please look at the respective definitions of the p.b and v.b properties. As
I mentioned a few minutes ago, the docstring for p.__set__b is important.

Edward

**Comment by tbpassin** [comment]
I remembered there was a difference - I must have seen that docstring sometime in the past - but not which way.  But now I'm confused by `v.setBodyString()`:

```
def setBodyString(self, s: Any) -> None:
    # pylint: disable=no-else-return
    v = self
    if isinstance(s, str):
        v._bodyString = s
        return
    else:  # pragma: no cover
        v._bodyString = g.toUnicode(s, reportErrors=True)
        self.contentModified()  # #1413.
        signal_manager.emit(self.context, 'body_changed', self)
```
If the "s" arg is already a string, why don't we set contentModified and emit the signal?  In the _else_ branch,  what could "s" be if not a string?  Are we expecting a byte array, perhaps?

**Comment by edreamleo** [comment]
On Sun, Mar 20, 2022 at 5:05 PM Thomas Passin ***@***.***>
wrote:

> I remembered there was a difference - I must have seen that docstring
> sometime in the past - but not which way. But now I'm confused by
> v.setBodyString():
>
> def setBodyString(self, s: Any) -> None:
>     # pylint: disable=no-else-return
>     v = self
>     if isinstance(s, str):
>         v._bodyString = s
>         return
>     else:  # pragma: no cover
>         v._bodyString = g.toUnicode(s, reportErrors=True)
>         self.contentModified()  # #1413.
>         signal_manager.emit(self.context, 'body_changed', self)
>
> If the "s" arg is already a string, why don't we set contentModified and
> emit the signal?
>
I don't remember exactly. Probably somebody wanted this signal for their
plugin.

> In the *else* branch, what could "s" be if not a string?
>
It's defensive code.

> Are we expecting a byte array, perhaps?
>
Perhaps.  It doesn't matter much. I wouldn't over-think this code :-)

Edward
