### ISSUE TITLE
how to visit unl:// from external app

### ISSUE THREAD

**Issue by jabobian** [leo-editor/leo-editor#2507]
I just wondering is it possbile to visit unl from external application using leoserver.
Currently I use AutoHotkey to "WinActivate" Leo, and use minibuffer command (I write a @cmd goto-unl to the leoPy.leo) to handle the unl access. But it is not fluent, as I need to send Ctrl-V and {Enter} to minibuffer. I want some native external unl handler.

**Comment by tbpassin** [comment]
Theoretically it should be easy enough to run a server that listened for a "goto" command on http so that you could enter it into the browser's address bar.  But there is a practical problem - UNLs will usually need url-encoding, and GNXs do not say what outline they are in.

**Comment by tbpassin** [comment]
Actually, if you can get the unl or gnx into the clipboard, then you can write a simple Leo command that goes to that address directly from the clipboard.  No need to use the minibuffer at all.  Something like this:

```
@g.command('goto-unl-clipboard')
def goto_unl_clipboard(event = None):
  if event:
      c = event.c
  unl = g.app.gui.getTextFromClipboard()
  g.handleUnl(unl, c)
```

**Comment by jabobian** [comment]
Thanks tbpassin.
What I want is not to click anything in Leo, and let the background unl handler to do the work. For example, I open leo and another app (e.g. OneNote) side by side, and I just click the links in the second app to view the Leo codes.

**Comment by jabobian** [comment]
I find it is a not bad approach to define a special hotkey for your "goto-unl-clipboard" command, and I will try it first and let you know progress.

**Comment by jabobian** [comment]
@tbpassin,
I just put the following lines in the @command, and it works like a charm.
unl = g.app.gui.getTextFromClipboard()
g.handleUnl(unl, c)

**Comment by tbpassin** [comment]
Excellent!  You could also create a command button instead of using a hotkey.  You could even add it to one of the menus.
