### ISSUE TITLE
Failure Running cover-all Command

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#2508]
Running the command printed this to the console:
```

ERROR: usage: __main__.py [options] [file_or_dir] [file_or_dir] [...]
__main__.py: error: unrecognized arguments: --cov-report --cov-report term-missing --cov
  inifile: None
  rootdir: C:\Tom\git\leo-editor

Could not parse stylesheet of object QFileDialog(0x1534624d1b0)
ERROR: usage: __main__.py [options] [file_or_dir] [file_or_dir] [...]
__main__.py: error: unrecognized arguments: --cov-report --cov-report term-missing --cov
  inifile: None
  rootdir: C:\Tom\git\leo-editor
```

```
Leo 6.6-rc1-devel, devel-clean branch, build 76b6d05e98
2022-03-21 15:26:52 -0500
Python 3.9.9, PyQt version 5.15.2
Windows 10 AMD64 (build 10.0.19043) 
```

**Comment by edreamleo** [comment]
The cover-all command works for me from within Leo itself and from an separate .cmd file.

Clearly, the message indicates only that there is something wrong with your stylesheet.

**Comment by tbpassin** [comment]
Stylesheet?  What stylesheet is that?  Where would I find out what needs to be in it?

**Comment by edreamleo** [comment]
@tbpassin I can't debug this kind of bug remotely. You will have to discover why the arguments are invalid.

The start of the error message `__main__.py__` is suspicious. Perhaps the script that is running cover-all is executing the wrong program ?!?

**Comment by edreamleo** [comment]
@tbpassin This cover-all.cmd is equivalent to 'cover-all':
```
cd leo/unittests
python -m pytest --cov-report html --cov-report term-missing --cov
```
