### ISSUE TITLE
unloadOnePlugin() Did Not Unload Plugin

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#2510]
I was experimenting with variations of the mod_http plugin.  I succeeded in loading it using `loadOnePlugin()`.  But the corresponding `unloadOnePlugin()` did not stop it.  Is this because the plugin is a persistent server, or is it a problem with `unloadOnePlugin()`?

Load:

```
from leo.core.leoPlugins import LeoPluginsController as LPC
mod = 'tp_mod_http'   # system path set to make this visible.
tag = 'tom'
lpc = LPC()
lpc.loadOnePlugin(mod, tag=tag)  # Succeeds
```

Unload:
```
from leo.core.leoPlugins import LeoPluginsController as LPC
mod = 'tp_mod_http'
lpc = LPC()
lpc.unloadOnePlugin(mod)  # Fails
```

**Comment by edreamleo** [comment]
On Mon, Mar 21, 2022 at 10:35 PM Thomas Passin ***@***.***>
wrote:

> I was experimenting with variations of the mod_http plugin. I succeeded in
> loading it using loadOnePlugin(). But the corresponding unloadOnePlugin()
> did not stop it. Is this because the plugin is a persistent server, or is
> it a problem with unloadOnePlugin()?
>
There is a known problem with unloadOnePlugin. It's basically impossible to
actually unload a plugin. Iirc, unloadOnePlugin might unregister some
handlers, but that's probably all.

In short, I wouldn't rely on unloadOnePlugin at all.  Sorry, but this state
of affairs is not likely to change.  Maybe 6.6.1 should retire
unloadOnePlugin.

Edward
