### ISSUE TITLE
File Importer Places @language Directive In Wrong Place

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#2511]
I tried importing a c++ file. The importer decided not to organize the file, and the language and tab width directives ended up at the end of the one and only node:
```
@language c
@tabwidth -4
```
This causes the body not to be colorized.  I know this location happened when the importer was rewritten recently.   But it's the wrong place for the language directive (and, I imagine, the tabwidth directive too).  It needs to be near the top so the colorizer can do its job.

When only a few lines, like a few _# include_ lines, are at the top and the directive comes after them, not much harm is done.  In this case the entire program comes before the directive, and so the colorizer isn't colorizing.

The @language directive, at least, should be located at or near the top of the imported file.

**Comment by edreamleo** [comment]
@tbpassin Thanks for this report. It's surprising, but should be easy to fix.
