### ISSUE TITLE
pyplot_backend Imports backend_qt5agg Even For Qt6

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#2515]
Viewrendered installs a qt graphics backend to render @pyplot nodes. But in the imports, it tries to import a qt5 object even if qt6 is being used:

```
try:
    if isQt5 or isQt6:
        import matplotlib.backends.backend_qt5agg as backend_qt5agg
        FigureCanvasQTAgg = backend_qt5agg.FigureCanvasQTAgg
```

This is now obsolete.  There is a qtagg backend that handles whichever of qt5 or qt6 you have.  The new imports are

```
import matplotlib.backends.backend_qt as backend_qtagg
FigureCanvasQTAgg = backend_qtagg.FigureCanvasQT
```
I have not checked the rest of the code to see if any other similar adjustments need to be made, and I don't know if the pyplot backend helper works after the changes.

**Comment by edreamleo** [comment]
@tbpassin Thanks for this!  Please submit a PR. It should go into 6.6.

**Comment by tbpassin** [comment]
This seems to be a little tricky.  I got the imports working, but nothing appears on the drawing pane except the toolbar.  I am going to have to dig deeper.  I know the existing code used to work, and I even got it, slightly modified, working with VR3 a year ago.  I was able to get both VR and VR3 to do @pyplot nodes, and even got each one to hide and show itself again.  The only problem then was that if you opened and closed VR3 a bunch of times while VR was also opened and closed a few times,  and they were both @pyplotted, sometimes VR3 graphics output would fail, or the VR3 graphics output would start to display in the VR graphics pane..

I never solved that (which may not have been a serious concern because would anyone actually work like that?), and I didn't like trying to author @pyplot nodes anyway, so I dropped that support in VR3. In VR3,  it's easy enough to save the pyplot figure to a file and then to add an @rst section to the node to display it, so I don't feel any capability was really lost.  It's actually better because that way you can mix text and graphics in the same rendering.

As I recall, back then I had to add a few attributes to the DummyWindow because sometimes they were accessed by pyplot even though the window itself did nothing.  I  had to do the same again today, but no visible plotting is happening.

**Comment by edreamleo** [comment]
@tbpassin I have just reassigned this issue for 6.6.1. However, I'll consider adding any changes to 6.6 if you can complete the work in a day or two.  I am going to delay 6.6 for about a week.

**Comment by tbpassin** [comment]
One of the changes is that we are now supposed to use MatPlotLib versions of the various QtWidgets.  Apparently they needed this because of differences between Qt5 and Qt6 widgets that MPL was unable to paper over.

So now we have to do things like this:

```
from matplotlib.backends.qt_compat import QtWidgets
from matplotlib.backends.backend_qtagg import (
    FigureCanvas, NavigationToolbar2QT as NavigationToolbar)
QPushButton = QtWidgets.QPushButton  # These are not importable ...
QDialog = QtWidgets.QDialog          # Use the dotted notation
QVBoxLayout = QtWidgets.QVBoxLayout
QWidget = QtWidgets.QWidget
```
Once I get through rippling these kinds of changes through the backend code, we'll have to see if it will work or whether there will be more to be done.

**Comment by tbpassin** [comment]
All right, I got it working, both for Qt5 and Qt6.  @pyplot nodes plot as expected, and - a nice bonus - Plot Nine plots work too (they use MatPlotLib behind the scenes).

I will need to do some cleanup and more testing, but things look good.

**Comment by tbpassin** [comment]
Surprise!  There seems to be no need for the "DummyWindow".  I set it to None, and everything is still working.

**Comment by tbpassin** [comment]
Too bad vr has to create a new figure and its canvas each time the pyplot backend is called.  I wonder if there might be a way to save the figure and reuse it?  I also wonder if the old figure gets cleaned up completely, or whether there is a figure leak.

**Comment by tbpassin** [comment]
BTW, although supposedly once a @pyplot node has been rendered it is not possible to close VR again, that isn't actually correct.  For example, if you reload the default window layout, the VR pane will go away.  I don't know if it's hidden or destroyed.  You can re-open the VR pane and it will work normally.

I don't know how that works because the workings of the splitter are a mystery to me.  Whether or not there is a resource leak I also don't know.

**Comment by tbpassin** [comment]
It occurs to me that I don't know what is the minimum Python version that can work with these ne MatPlotLib classes.  I'll see if I can find out.

**Comment by tbpassin** [comment]
Resolved by PR https://github.com/leo-editor/leo-editor/pull/2524
