### ISSUE TITLE
Current Devel Showing Many Errors On Opening

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#2516]
Partial console output:

```
scan_lines leoFindScript.py: warning: inserting unexpected line: '#@nonl'
scan_lines leoFindScript.py: warning: inserting unexpected line: '#@-node:EKR.20040502195118.10:reFindAll'
scan_lines leoFindScript.py: warning: inserting unexpected line: '#@+node:EKR.20040502195118.11:reFindNext'
scan_lines leoFindScript.py: warning: inserting unexpected line: '#@nonl'
scan_lines leoFindScript.py: warning: inserting unexpected line: '#@-node:EKR.20040502195118.11:reFindNext'
scan_lines leoFindScript.py: warning: inserting unexpected line: '#@+node:EKR.20040502195118.12:reFindPrev'
scan_lines leoFindScript.py: warning: inserting unexpected line: '#@nonl'
scan_lines leoFindScript.py: warning: inserting unexpected line: '#@-node:EKR.20040502195118.12:
```

**Comment by tbpassin** [comment]
This seems to be something that happened to my workbook outline.  I went back to Leo 6.4 and got the same thing happen.  When I opened Leo with a specific outline on the command line, I didn't get any unusual output.  So it must be my workbook.  But I'm darned if I know what.

**Comment by edreamleo** [comment]
@tbpassin `@nonl` is a sign of an ancient outline.

**Comment by tbpassin** [comment]
That was it.  I had found `scripts/leoFindScript.py` and brought it into my workbook to look at it.  I'll purge it out now, and perhaps it should be removed from `scripts` as well.

**Comment by tbpassin** [comment]
import-legacy-external-files seems to import it without a hitch.  Yea!

**Comment by edreamleo** [comment]
@tbpassin Glad you found the command.
