### ISSUE TITLE
goto-next clone activate chapter view

### ISSUE THREAD

**Issue by JohnLunzer** [leo-editor/leo-editor#252]
Please reference this thread - https://groups.google.com/forum/#!topic/leo-editor/K81S8ASkKm8

The bulk of the request is to make a change so that goto-next clone activates the chapter view of the nearest enclosing chapter.

**Comment by JohnLunzer** [comment]
You may also want to add a bug label to this. If both clones are located in the same @chapter node I am still getting knocked out of my chapter to main after a goto-next-clone command.

**Comment by edreamleo** [comment]
@JohnLunzer I agree. It may as well be called a bug, and it may as well be fixed now, before 5.3-b1.

**Comment by edreamleo** [comment]
This turns out to be a super enhancement.

**Comment by JohnLunzer** [comment]
Just out of curiosity, why unexpectedly great?

**Comment by edreamleo** [comment]
On Wed, Apr 27, 2016 at 5:50 AM, John Lunzer <notifications@github.com>
wrote:

> Just out of curiosity, why unexpectedly great?
>
I just didn't imaging how cool, and useful, the automatic switch would be.
Even now, there is a jolt of surprise that so seemingly simple a change
should have such a great visual, even emotional impact.

Indeed, one could imaging inserting clones into chapters whose only real
purpose is having Alt-N switch chapters.

EKR​

**Comment by JohnLunzer** [comment]
That's great. I am glad that you are also experience this. When I first thought of this I was excited about what it could do in terms of context switching and like you said the great impact that could have. 

It is funny you mention having a clone with the only purpose being to switch chapters. To this extent you could follow a path of clones through chapters, using them as location specific wormholes between chapters, providing context for whatever you needed to provide context for. And you certainly don't need chapters for that (though it makes it cooler). This idea could be employed in general which I had never thought of. 

I honestly believe the new chapters, with this addition, should satisfy a lot what was discussed when the idea of threading came up. 

I think the only thing left related to chapters is clone-marked/copy-marked/move-marked. With these commands it should be a breeze to move around multiple nodes between chapters. This is not a priority, merely a convenience. There is also no issue filed for it, it was discussed in the forum.

Very cool. Definitely nothing like this anywhere else.

**Comment by edreamleo** [comment]
On Wed, Apr 27, 2016 at 9:04 AM, John Lunzer <notifications@github.com>
wrote:

I think the only thing left related to chapters is
> clone-marked/copy-marked/move-marked.


​Please file an enhancement issue.  It's the only way I can keep track of
things.

EKR

**Comment by JohnLunzer** [comment]
Sure
