### ISSUE TITLE
Qt Version Conundrum

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#2525]
I have just installed PyQt6.2.4.  I can verify the version by running this bit of code in a node with CTRL-B:

```
from PyQt6.QtCore import qVersion
g.es(qVersion())  # shows '6.2.4'
```

However, the log pane reports

```
Leo 6.6-rc1-devel, tbp-qt6-1 branch, build 9341fd3da1
2022-03-26 17:39:40 -0400
Python 3.9.9, PyQt version 6.2.3
```

There is no directory on sys.path that has a 6.2.3 version.  How is it possible that the two would be different?

**Comment by tbpassin** [comment]
Looks like it's a Qt buglet.  Leo gets the version to print to the log pane at startup from  `QtCore.QT_VERSION_STR`,  which is returning 6.2.3.  At the same time, `QtCore.qVersion()` is returning 6.2.4.  Huh!  6.2.4 is what is actually installed.

Just for fun, I changed the startup message to include both of them at the same time, with this result:

`PyQt version 6.2.3 -or - 6.2.4`

Funny that `qVersion()` does not simply return `QT_VERSION_STR`!

I wonder if qVersion() is always authoritative.

[Later] Yes, `QT_VERSION_STR` is hard-coded in _QtCoremod.sip_.  Somebody forgot to update it!

```
const char *PYQT_VERSION_STR;
%ModuleCode
static int PYQT_VERSION = 0x060203;
static const char *PYQT_VERSION_STR = "6.2.3";
%End
```

**Comment by tbpassin** [comment]
I would say that `qVersion()` ought to be more reliable.  _PYQT_VERSION_STR_ is declared in a .sip file, which IIUC is a template for constructing the pyqt wrapper.  `qVersion()`, though, is an actual c++ function in Qt itself.  So it returns what QtCore thinks is the version.  That should be more authoritative.

What do you want to bet that someone said "The API hasn't changed so we can use the same .sip file"?

**Comment by edreamleo** [comment]
@tbpassin Thanks for this!  Please file a PR. I think this issue can go into 6.6.
