### ISSUE TITLE
Goto Global line (Alt-G) is inconsistent

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#253]
On a small node of 4 lines
Goto global line: 2
the cursor lands at line 3, one line after expected.

On a small @clean node of 4 lines
Goto global line: 2
the cursor correctly lands at line 2, as expected.

Refer to recent issue [251](https://github.com/leo-editor/leo-editor/issues/251)

**Comment by edreamleo** [comment]
goto-global-line goes the node in the *outline* corresponding to the line with the given line number in the *external file*. So the operation you describe is expected.  Furthermore, for external files containing sentinels, there may be several lines in the external file that correspond to the *same* line in the outline.

In short, F11 goto-global-line needs to be improved :-)  I'll leave this bug open until then.

**Comment by edreamleo** [comment]
Fixed (docstring improved) at 52cf698.
