### ISSUE TITLE
CNTL-click on gnx Navigates To Its Node?

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#2538]
`g.openUrlHelper()` is invoked when the user clicks on a UNL, URL, or section reference in the body.  I would like to add the GNX to the special forms that are recognized by this method.

The following regex will reliably identify when a line contains a GNX.

```
# Example GNX: tom.20210522091147.1
# New user IDs are constructed by NodeIndices.getNewIndex()
USERCHAR = r"""[^.,"'\s]"""  # from LeoApp.cleanLeoID()
USERID = f'{USERCHAR}{{2}}{USERCHAR}+'  # At least three USERCHARs

GNXre = re.compile(rf"""{USERID}\.
    [0-9]+\.                     # timestamp
    [0-9]+""", re.VERBOSE)       # NodeIndices.lastIndex
```

The main use case at present is to support my proposed "zettel-kasten" system, which uses GNXs as cross links between note cards.  Currently I use a little script bound to a hotkey, and CTRL-clicking in the body would be more convenient.  CTRL-clicking on a GNX seems to fit right in with CTRL-clicking on other navigable strings (UNL, URL, section reference, method invocation) so it seems fine to me.

I'm holding off putting in a PR until I know if there is a good reason not to do this.

**Comment by edreamleo** [comment]
@tbpassin Go right ahead with the PR.  I'll merge it into devel after 6.6 is released.

**Comment by tbpassin** [comment]
Thanks, will do.
