### ISSUE TITLE
Fix new pylint warnings

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#2539]
**EKR**: Upgrading to python 3.10 results in more warnings.  I'll fix them all.

pylint found two instances of this type of warning in LeoGlobals.py:

` W1113: Keyword argument before variable positional arguments list in the definition of __init__ function (keyword-arg-before-vararg)`

I am not sure if this could potentially cause a problem or not.  If not, we could clean it up for 6.6.1.  If it could, perhaps it should be done before 6.6 is released.

**Comment by edreamleo** [comment]
@tbpassin 6.6 is frozen. It can wait until 6.6.1.

I don't see this pylint warning. What function is the complaint about?

**Comment by tbpassin** [comment]
I just updated my pylint version yesterday.  Maybe that has something to do with it.

`C:\Tom\git\leo-editor\leo\core\leoGlobals.py:2266:4: W1113: Keyword argument before variable positional arguments list in the definition of __init__ function (keyword-arg-before-vararg)`

Hmm, I thought there were two, but now I only see this one case of it.  It's the __init__ for `class TracingNullObject`

**Comment by edreamleo** [comment]
@tbpassin I just install Python 3.10, and I see many new warnings.  I'll fix them all.

**Comment by tbpassin** [comment]
I'm still on 3.9x, but your new version probably got you the newest version of pylint, too.  Yes, I saw a lot more warnings that I didn't mention, but many or most of them just need to be disabled.

**Comment by edreamleo** [comment]
@tbpassin I agree. I'll just disable the warnings.
