### ISSUE TITLE
Fast marking

### ISSUE THREAD

**Issue by JohnLunzer** [leo-editor/leo-editor#254]
Use the spacebar to execute a "mark and move to next visible" to make marking feel fast and fluid by always moving you forward and also reduces the amount of keystrokes used.

​I believe by default the spacebar is not bound to anything when the outline pane is active.

Please reference this [thread](https://groups.google.com/forum/#!topic/leo-editor/-mv2x_6TAdM) for more context.

**Comment by edreamleo** [comment]
> the spacebar is not bound to anything when the outline pane is active.

True.  The following binding should work, but doesn't:
```
mark ! tree = space
```
The binding shows up in the print-bindings tab as:
```
M tree: Space mark
```
but the binding doesn't "take".  This isn't too surprising. The code is baroque.  I'll see if I can get plain key bindings to work in the outline.  Furthermore, it used to be possible to search for headlines using plain keys.  I'll see if that can happen too.

**Comment by edreamleo** [comment]
Done at c0478a59. Discussion [here](https://groups.google.com/d/msg/leo-editor/q1XKe4mnW9I/MrY7pNHbBAAJ).
