### ISSUE TITLE
File with new node is not seen as changed

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#2552]
Create a new node in a Leo file. Select File>Close and Leo closes the file with no Save Yes/No dialog.

Reproduce with test script:

_g.es("Test creating a new node")
node_name = 'new node A'
p = c.p.insertAfter()  # insert after current node p.
p.h = node_name  # rename the Headline.
c.selectPosition(p)  # select node position and move to it
c.redraw()_

Body text is required to trigger the Save Yes/No dialog. 

_Leo Log Window
Leo 6.6-rc1-devel, devel branch, build 55a9ae46b0
2022-03-27 09:26:48 -0500
Python 3.10.4, PyQt version 6.2.3
Windows 10 AMD64 (build 10.0.19044) SP0_

**Comment by edreamleo** [comment]
This is a programming mistake.  p.insertAfter (and similar position methods) does not (and must not!) set the outline's "changed bit".

To match what is likely your expectations, so:
```
p.setDirty()  # Expensive: it sets all ancestor @<file> nodes dirty.
c.setChanged(True)
```

**Comment by LewisNeal** [comment]
Thanks. Using _c.setChanged()_ gets Leo to see the file as changed.
Can you explain why after I create the node and then change it's name with _p.h = node_name_ the outline is not seen as changed?
Is _p.h_ a position method?
