### ISSUE TITLE
prompt file changed

### ISSUE THREAD

**Issue by maguohe** [leo-editor/leo-editor#256]
1.  I create  a node @clean main.c ( @auto-rst or @auto-markdown or @file ..... )  and save it.
2.  modify the file main.c with other editor and save it.
3. active Leo editor.  if I want to see the change. I must select "Refresh from disk". menu mannuly.

Can Leo auto detect main.c changed  and show a  pop-up dialog like other editor?

**Comment by tbnorth** [comment]
Perhaps using the approach of Notepad++, which checks for updates when it regains focus. Leo's already tracking modification times. Only thing is that I suspect typical editors seldom have more than 20-30 files open, whereas leo probably hits triple digits more often. 
Cheers -Terry

**Comment by edreamleo** [comment]
This capability if part of Leo 5.2-final.

**Comment by edreamleo** [comment]
To enable this feature, set:
```
@bool check_for_changed_external_files = True
```
in myLeoSettings.leo. Perhaps this setting should be True by default.

**Comment by maguohe** [comment]
it's great .  thanks

**Comment by edreamleo** [comment]
On Fri, Apr 8, 2016 at 11:49 PM, maguohe <notifications@github.com> wrote:

> it's great . thanks
>

​You're welcome.

Edward
