### ISSUE TITLE
Pylint Not Working On Current 6.6.1

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#2560]
Pylint seems to do nothing.  It returns control to Leo immediately with no output.  

```
Leo 6.6.1-devel, tbp-freewin branch, build babf5c8b20
2022-04-01 08:24:13 -0500
Python 3.9.9, PyQt version 6.2.4
Windows 10 AMD64 (build 10.0.19043) 
```

When I started using the latest version of Leo, I got a message about pylint using a new directory and not needing a previous  .d file.  However, I don't see a new directory for pylint  in my .leo directory.

**Comment by edreamleo** [comment]
@tbpassin Hmm. Not sure what that is about.  I've just fixed #2557. Please use the latest devel.

Please reopen *this* issue if problems remain.
