### ISSUE TITLE
chapter-select-forward and chapter-select-back

### ISSUE THREAD

**Issue by JohnLunzer** [leo-editor/leo-editor#257]
These would simply switch between chapters as they appear in the list of chapters, going from the current chapter to the next or to the previous.

**Comment by JohnLunzer** [comment]
Adding tab-cycling to chapter-select could resolve this enhancement if the tab-cycling were to start from the currently active chapter. This would remove the need for new commands. Discussed [here](https://groups.google.com/forum/#!topic/leo-editor/HeO72ZLwAeo).

**Comment by edreamleo** [comment]
Completed at efc4fd3f6.

**Comment by JohnLunzer** [comment]
Thanks Edward, I will check this out soon!
