### ISSUE TITLE
URL Recognition For Inline URLs Not Precise Enough

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#2570]
For CTRL-clicking on URLs contained in body text, the current identification method does not correctly recognize the end of some URLs.  A specific example is a URL written in RsT syntax:

~~~
`networkx <https://github.com/networkx/networkx>`_
~~~

The URL highlight starts correctly at "h" in _http_, but overruns the end and includes the trailing non-alphabetic characters.  CTRL-clicking this URL will not send the browser to the intended address.

**Comment by tbpassin** [comment]
A pointer to where these highlighted, clickable URL links are inserted into the body would be helpful.  So far I haven't found it in LeoPyRef.

**Comment by edreamleo** [comment]
On Sun, Apr 3, 2022 at 11:30 PM Thomas Passin ***@***.***>
wrote:

> A pointer to where these highlighted, clickable URL links are inserted
> into the body would be helpful. So far I haven't found it in LeoPyRef.
>
See LeoQtLog.put.  The road to this call can be long.

For debugging, you might put g.trace(g.callers(6)) at the start of this
method.

Edward

**Comment by edreamleo** [comment]
@tbpassin Well done. The url code is complicated, no doubt about that.

**Comment by tbpassin** [comment]
Good grief --- there are *two* places that define _url_regex_, and one is applied at one point and the other is applied an another point in the url handling process.

It was driving me nuts because I got the syntax highlighting working but the dispatch to the browser was not.

I'll have to think if I'd recommend using the same object both places.

**Comment by tbpassin** [comment]
I just submitted PR https://github.com/leo-editor/leo-editor/pull/2576 for this.

**Comment by tbpassin** [comment]
done, in devel.
