### ISSUE TITLE
Pylint Command Reruns Previous File Checks

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#2591]
If I run pylint against file A, and then run it against file B, the second command checks both file A and file B.  A third run against file C checks all three.

I don't think this was intended.

**Comment by edreamleo** [comment]
@tbpassin I've never seen this behavior. Let's see what effect proposed changes to the BPM have.

**Comment by tbpassin** [comment]
On retrying this, I didn't get a rerun of previous results.  The difference that I had removed the duplicate line printing from `bpm.end()` (it duplicated the output lines that ran already in `check_process()`).  I don't know for sure if that made the difference because I don't see how those lines in end() would have retained the output from the previous run.

**Comment by tbpassin** [comment]
I had the same experience as I implemented the threaded bpm processing.  I would get a repeat output from the previous run.  I removed a second set of output lines from bpm.end().  Then I didn't get the duplicates any more.  Here are the removed lines:

```
    if self.wait:
        pass
    else:
        pass
        # n = self.data.number_of_lines
        # for s in self.pid.stdout:
            # n += 1
            # self.put_log(s)
        # if n > 0: g.es_print(f"printed {n} line{g.plural(n)}")
```
It looks as if the bpm design had changed a bit, because there were similar lines in check_process().  One puzzle for me is why these commented-out lines didn't give output until the second run of pylint.

**Comment by tbpassin** [comment]
This problem has been eliminated by the recent background process manager PR, https://github.com/leo-editor/leo-editor/pull/2595.  Once it has been approved, I will close this issue.

**Comment by edreamleo** [comment]
@tbpassin I'm closing this issue for you :-)
