### ISSUE TITLE
Errors with ipynb.py importer

### ISSUE THREAD

**Issue by largo84** [leo-editor/leo-editor#260]
This just showed up today from the latest update. The error is in the terminal window and the log pane. It doesn't appear to cause any problems with my files, though.

leo/plugins/importers/ipynb.py has no importer_dict

This error text shows up 4 times for .leo file that opens (2 times in the log pane).

Environment:
Leo 5.3-devel, build 20160412153848, Tue Apr 12 15:38:48 CDT 2016
Git repo info: branch = master, commit = 8c38a3117112
Python 3.4.3, PyQt version 5.4.1
Windows 8 AMD64 (build 6.2.9200)

**Comment by edreamleo** [comment]
> leo/plugins/importers/ipynb.py has no importer_dict

Thanks for this.  It's guarded with if nbformat.  If you want to use @auto x.ipynb, you have to install nbformat.  I think pip install nbformat will do.

Hmm.  I think defaulting to an empty importer_dict would do, as would having the code silently ignore the lack of importer_dict.  I'll fix this today.

EKR

**Comment by largo84** [comment]
I'm not actually using the importer (don't really know that much about it). That would be good to have a default empty importer_dict and/or simply ignore the warning. Thanks!

**Comment by edreamleo** [comment]
fixed at b83c079. 

The ipynb importer now always defines an importer_dict. If nbformat does not exist, the importer puts the entire file in the parent node's body text.
