### ISSUE TITLE
exception executing equal-sized-panes

### ISSUE THREAD

**Issue by JohnLunzer** [leo-editor/leo-editor#261]
Not much lead in here. When I try to execute-sized-panes I receive the exception detailed below. I should note, it still does make the split panes equal size.

My setup:
Leo 5.3-devel, build 20160411191235, Mon Apr 11 19:12:35 CDT 2016
Git repo info: branch = master, commit = 9351518184c3
Python 2.7.11, PyQt version 4.8.6
Windows 7 AMD64 (build 6.1.7601) SP1

exception executing command
Traceback (most recent call last):

  File "C:\Users\Lunz8748\Documents\sourcetreeapp\leo-editor\leo\core\leoCommands.py", line 5169, in doCommand
    val = command(event)

  File "C:\Users\Lunz8748\Documents\sourcetreeapp\leo-editor\leo\core\leoGlobals.py", line 1703, in wrapper
    func(self, event=event)

  File "C:\Users\Lunz8748\Documents\sourcetreeapp\leo-editor\leo\plugins\qt_frame.py", line 2844, in equalSizedPanes
    frame.resizePanesToRatio(0.5, frame.secondary_ratio)

  File "C:\Users\Lunz8748\Documents\sourcetreeapp\leo-editor\leo\plugins\qt_frame.py", line 2549, in resizePanesToRatio
    f.divideLeoSplitter(not self.splitVerticalFlag, ratio2)

  File "C:\Users\Lunz8748\Documents\sourcetreeapp\leo-editor\leo\plugins\qt_frame.py", line 2559, in divideLeoSplitter
    self.divideLeoSplitter2(frac, verticalFlag)

  File "C:\Users\Lunz8748\Documents\sourcetreeapp\leo-editor\leo\plugins\qt_frame.py", line 2568, in divideLeoSplitter2
    self.divideAnySplitter(frac, self.top.leo_ui.splitter)

  File "C:\Users\Lunz8748\Documents\sourcetreeapp\leo-editor\leo\plugins\qt_frame.py", line 2574, in divideAnySplitter
    sizes = splitter.sizes()

RuntimeError: wrapped C/C++ object of type NestedSplitter has been deleted

**Comment by edreamleo** [comment]
I can't reproduce this.  Does it always happen?

**Comment by JohnLunzer** [comment]
Yes, in all of my outlines. I hadn't been using that command much until recently. I know I've used it long long ago without any issues.

**Comment by technatica** [comment]
It happens to me as well.

Leo 5.3-devel, build 20160412153848, Tue Apr 12 15:38:48 CDT 2016

Git repo info: branch = master, commit = 84eb80dd2a0f

Python 2.7.6, PyQt version 4.8.6
linux2


exception executing command

Traceback (most recent call last):

  File "/working/leo/leo-editor/leo/core/leoCommands.py", line 5169,
in doCommand
    val = command(event)

  File "/working/leo/leo-editor/leo/core/leoGlobals.py", line 1703, in wrapper
    func(self, event=event)

  File "/working/leo/leo-editor/leo/plugins/qt_frame.py", line 2844,
in equalSizedPanes
    frame.resizePanesToRatio(0.5, frame.secondary_ratio)

  File "/working/leo/leo-editor/leo/plugins/qt_frame.py", line 2549,
in resizePanesToRatio
    f.divideLeoSplitter(not self.splitVerticalFlag, ratio2)

  File "/working/leo/leo-editor/leo/plugins/qt_frame.py", line 2559,
in divideLeoSplitter
    self.divideLeoSplitter2(frac, verticalFlag)

  File "/working/leo/leo-editor/leo/plugins/qt_frame.py", line 2568,
in divideLeoSplitter2
    self.divideAnySplitter(frac, self.top.leo_ui.splitter)

  File "/working/leo/leo-editor/leo/plugins/qt_frame.py", line 2574,
in divideAnySplitter
    sizes = splitter.sizes()

RuntimeError: wrapped C/C++ object of type NestedSplitter has been deleted




Chris

**Comment by tbnorth** [comment]
In theory this is a significant problem, in practice it's not, because this is the first time it's come up.

Because of free_layout, *you can not save references to splitters*.

Simple case:
```
              a
              a
    TREE      a
              a
bbbbbbbbbbbbbba     BODY
              a
    LOG       a
              a
```

but that could easily be rearranged to be

```
              a
              a
    TREE      a
              a
bbbbbbbbbbbbbba     SPELL
              a
    LOG       a
              a
cccccccccccccccccccccccccccccc

            BODY

```

so now a reference to splitter `a` is still valid, but not the splitter you meant.

But more to the point, different rearrangements might delete `a` and `b` altogether, which is what I suspect it happening to John.  The rearrangement may be as trivial as the result to Toggle Split Direction, or the equivalent @setting.

It's not hard to fix `equal-sized-panes`, it just needs to act on `c.free_layout.get_top_splitter()`.
Given that the top splitter may have more than 2 parts, it probably needs to divide the space available by n, not 2.

The bigger question is how many other places do we still have reference to splitters.

**Comment by edreamleo** [comment]
Thanks for this overview, Terry.  Could we just convert the splitter ivar to a property that returns c.free_layout.get_top_splitter()?  And perhaps something similar for the splitter_2 ivar?

**Comment by tbnorth** [comment]
Hah, I always forget about properties :-}  That could be a really neat fix.

**Comment by edreamleo** [comment]
> The bigger question is how many other places do we still have reference to splitters.

@tbnorth I'm doing a cff on it now.  Ok, here are the results:

1. Unsurprisingly, the `FreeLayoutController` and `NestedSplitter` classes are safe.  They account for the majority of references to `splitter`.

2. All improper methods are in `qt_frame.py`, in the `LeoQtFrame` and `DynamicWindow` classes.  Specifically, the `LeoQtFrame.divideLeoSplitter?` methods and `dw.setSplitDirection` method reference the stored reference to `splitter`. The `dw.createMainWindow` and `dw.createMainLayout` methods actually create the references.

A cff on `splitter_2` yields the same results, with far fewer hits.

Imo,, the clearest thing would be to replace `splitter` with `c.free_layout.get_top_splitter()`. Yes, a property would work, but there are, in fact, only a few dubious references.  The `splitter` and `splitter_2` ivars clearly must disappear.

Not so sure what to do about the `splitter_2`. Any suggestions?

**Comment by edreamleo** [comment]
> Not so sure what to do about the splitter_2. Any suggestions?

Let's step back a moment. This bug happens as a side effect of Terry's excellent free_layout code, which makes it possible for people to alter the placement of frames.  This has two implications:

1. The free_layout code must implement equal-sized-panes.
2. There may be rare situations in which the equal-sized-panes command becomes meaningless.

My plan is to create flc.equal_sized_panes which will find the splitter (if any) that divides the splitter containing the outline pane from the splitter containing the body text.  It will then resize that splitter.

Reviewing the code, it appears that the expand-x-pane and contract-x-pane commands will need support in free_layout.py. I am looking forward to doing this work.  It will allow me to understand the free_layout code in detail.

**Comment by edreamleo** [comment]
> My plan is to create [helpers] which will find the [desired] splitter.

Oh good.  The following returns a lists of dicts showing the entire splitter organization:
```
top = c.free_layout.get_top_splitter()
d = top.get_saveable_layout()
```
For example, on my layout:
```
{
'splitter': (NestedSplitter) splitter_2 at 107381984,
'orientation': 2, 'sizes': [477, 388],
'content': [
        {
        'splitter': (NestedSplitter) splitter at 107382144,
        'orientation': 1,
        'sizes': [655, 388],
        'content': [
            <PyQt4.QtGui.QFrame object at 0x06668530>,
            <PyQt4.QtGui.QFrame object at 0x06668800>
            ]
        },
        <PyQt4.QtGui.QFrame object at 0x06668E90>
    ]
}
{
'orientation': 2,
'sizes': [477, 388],
'content': [
        {
        'orientation': 1,
        'sizes': [655, 388],
        'content': [
            '_leo_pane:outlineFrame', '_leo_pane:logFrame'
            ]
        }, '_leo_pane:bodyFrame'
    ]
}
```
This, or perhaps an easier-to-use variant, will form the basis of the new code.

**Comment by edreamleo** [comment]
Well, this looks easy. The first line of the dump is:
```
{
'splitter': (NestedSplitter) splitter_2 at 107381984,
...
```
so it should be possible to define flc.find_splitter_2 and use that wherever dw.splitter_2 is presently used.  This might be None, so a guard will be needed.

**Comment by edreamleo** [comment]
So easy.  Here are the free_layout getters:
```
def get_main_splitter(self):
    '''Return the splitter whose name is "splitter".'''
    return self.get_splitter_by_name('splitter')
    
def get_splitter_2(self):
    '''Return the splitter whose name is "splitter_2".'''
    return self.get_splitter_by_name('splitter_2')
    
def get_splitter_by_name(self, name):
    '''Return the splitter with the given objectName().'''
    top = self.get_top_splitter()
    return top.get_splitter_by_name(name) if top else None
```
And here is NestedSplitter.get_splitter_by_name, a much simplified version of ns.get_layout:
```
def get_splitter_by_name(self, name):
    '''Return the splitter with the given objectName().'''
    if self.objectName() == name:
        return self
    for i in range(self.count()):
        w = self.widget(i)
        if isinstance(w, NestedSplitter) and w.objectName() == name:
            return w
    return None
```
All this code passes simple tests.  The last step will be to use them instead of the hard ivars.

**Comment by tbnorth** [comment]
Not sure if you can rely on that splitter_2 being there, it exists in the default situation, because NestedSplitter is a drop in replacement for QSplitter, but it can be arranged out of existence. 
Cheers -Terry

**Comment by edreamleo** [comment]
@tbnorth Right. The code above never assumes the splitter exists. Client code must handle the case in which the getters return None.

Also, ns.get_splitter_by_name must call itself recursively to search for splitters. I'll up that fix soon. I hope to have the code ready today.

**Comment by edreamleo** [comment]
Rev 0ff0b8f completes the first phase of this project. Here is the checkin log:
```
Replaced static dw.splitter and dw.splitter_2 ivars with NestedSplitter and FreeLayout methods.
All tests pass, and splitters appear to be set properly on entry.
Still, this is experimental code.
```
I am particularly concerned that there might be problems with reloading saved sessions.  Please report any problems immediately.

The next phase will be to generalize the expand/contract-pane commands.

**Comment by edreamleo** [comment]
> The next phase will be to generalize the expand/contract-pane commands.

Actually, these commands use the newly-corrected methods, so this item can be closed.
Please reopen if there are problems.

**Comment by tbnorth** [comment]
On Sat, 16 Apr 2016 09:42:59 -0700
"Edward K. Ream" <notifications@github.com> wrote:

> @tbnorth Right. The code above never assumes the splitter exists.
> Client code must handle the case in which the getters return None.
> 
> Also, ns.get_splitter_by_name must call itself recursively to search
> for splitters. I'll up that fix soon. I hope to have the code ready
> today.

Sorry I haven't been able to be more responsive during this work.

For not relying on splitter_2 existing, the problem is that if you go
from the initial layout to a custom layout and then back to
"Default", the copy of the initial layout you saved to easily switch to
the initial layout, you get a layout the *looks* like the default, but
has no splitter 'splitter_2', the splitters are unnamed.

So rather than searching for the splitter called splitter_2, you'd need
to search for the splitter containing the two panes usually separated
by splitter 2.

Also, leo-editor/leo/core/LeoPy.leo#Code-->Qt
gui-->@file ../plugins/nested_splitter.py-->class NestedSplitter (QSplitter)-->find_child
can be used for recursively finding things.

Cheers -Terry

**Comment by edreamleo** [comment]
@tbnorth Thanks for reminding me of the problem of splitter names. I'm dithering about whether to reopen this issue. As you say, there is a bug here, but it's not a crasher :-)

**Comment by edreamleo** [comment]
Dithering over. I've created a new issue to track the additional work that is needed.
