### ISSUE TITLE
clearLog() needs function body

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#2618]
how did this get by all checks without even a 'pass' statement??
```
@log_cmd('clear-log')
def clearLog(self, event=None):
    """Clear the log pane."""
```

in class CoreLog (leoFrame.LeoLog)

**Comment by edreamleo** [comment]
@tbpassin A def needs a statement. A docstring is such a thing. It's valid python, and a fairly common idiom.

**Comment by tbpassin** [comment]
hah! another thing new to me!
