### ISSUE TITLE
@bool check_for_changed_external_files may hang on network files

### ISSUE THREAD

**Issue by JohnLunzer** [leo-editor/leo-editor#262]
With the current implementation Leo can become unresponsive in some environments. Implementing the checking logic in non-blocking threads or a separate process could mitigate any negative performance impact. 

Additionally, if the Leo window is inactive withhold all notifications until Leo becomes active again. 

Please see this Leo conversation for [reference](https://groups.google.com/forum/#!topic/leo-editor/i06nrO9zyfA).

**Comment by edreamleo** [comment]
Rev 4373f88 attempts to fix #262 by checking at most one commander during idle time.

This approach could be extended by checking only one @<file> node at idle time, but that might result in long delays between checks of an @<file> node.

Please let me know if the fix works for you.

**Comment by edreamleo** [comment]
I am reopening this issue and marking it as a bug because of [serious problems when using network drives](https://groups.google.com/forum/#!topic/leo-editor/bRm5LqdKaQM).

**Comment by edreamleo** [comment]
Rev 2a0eca1: set the default setting for @bool check_for_changed_external_files to False. The comment in the body text of the setting's node references this issue.

Given the potential severity of this bug, I think it's important that people must explicitly enable this feature. It will prevent future reports that Leo has become broken.

**Comment by edreamleo** [comment]
It's time to close this issue. I see no reason to leave this issue open indefinitely.

`@bool check_for_changed_external_files` in leoSettings.leo defaults to False, so it can be said to be safe by default.  Furthermore it contains an adequate warning, and references this issue.
