### ISSUE TITLE
Files Missing From Devel

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#2620]
I wanted to update my fork, but got this git error message:

```
error: The following untracked working tree files would be overwritten
by merge:                                                          
        leo/extensions/mdx_math_gi.py                              
        leo/plugins/examples/__init__.py                           
        leo/plugins/obsolete/__init__.py                           
        leo/plugins/picture_viewer.py                              
        leo/plugins/remove_duplicate_pictures.py                   
        leo/plugins/viewrendered3/asciidoc/html5.conf              
        leo/plugins/viewrendered3/asciidoc3/html5.conf             
        leo/plugins/viewrendered3/md_styles_solarized_dark.css     
        leo/plugins/viewrendered3/md_styles_solarized_light.css    
        leo/themes/minimal-ui-tbp_dark_solarized.leo               
        leo/themes/minimal-ui-tbp_light_quasi-solarized.leo        
        leo/themes/minimal-ui-tbp_light_solarized.leo              
        leo/unittests/commands/test_convertCommands.py             
        leo/unittests/test_doctests.py                             
Please move or remove them before you merge.                       
```

I checked and sure enough, they are not in devel.  I thought i remembered all of mine being merged by one pr or another.  I checked one of my linux VMs, where I had the ekr-ann branch checked out, and those files were present.

Many of them but not all were my contributions - the ones in themes/ and plugins/viewrendered3.  not sure at this moment about the mdx_math_gi.py file.

It seems pretty clear that these files were removed in a very recent commit of devel, because yesterday, i think it was, i did not have this problem..

how best will we recover from this?  i can't open a new branch until this is resolved, for one thing, and of course some people might miss their theme or something else.  Not only that, but my clone is stuck on a very old version of Leo, and i can't change that until this is resolved.

**Comment by edreamleo** [comment]
On Sat, Apr 23, 2022 at 12:26 PM Thomas Passin ***@***.***>
wrote:

> I wanted to update my fork, but got this git error message:
>
> error: The following untracked working tree files would be overwritten
> by merge:
>         leo/extensions/mdx_math_gi.py
>         leo/plugins/examples/__init__.py
>         leo/plugins/obsolete/__init__.py
>         leo/plugins/picture_viewer.py
>         leo/plugins/remove_duplicate_pictures.py
>         leo/plugins/viewrendered3/asciidoc/html5.conf
>         leo/plugins/viewrendered3/asciidoc3/html5.conf
>         leo/plugins/viewrendered3/md_styles_solarized_dark.css
>         leo/plugins/viewrendered3/md_styles_solarized_light.css
>         leo/themes/minimal-ui-tbp_dark_solarized.leo
>         leo/themes/minimal-ui-tbp_light_quasi-solarized.leo
>         leo/themes/minimal-ui-tbp_light_solarized.leo
>         leo/unittests/commands/test_convertCommands.py
>         leo/unittests/test_doctests.py
> Please move or remove them before you merge.
>
> I checked and sure enough, they are not in devel.
>
I'm not sure what's going on at your end. For sure the following files *are*
in devel:

leo/plugins/examples/__init__.py
leo/plugins/obsolete/__init__.py
leo/plugins/picture_viewer.py
leo/plugins/remove_duplicate_pictures.pyleo/unittests/commands/test_convertCommands.py
leo/unittests/test_doctests.py

Many of them but not all were my contributions - the ones in themes/ and
> plugins/viewrendered3. not sure at this moment about the mdx_math_gi.py
> file.
>
> It seems pretty clear that these files were removed in a very recent
> commit of devel, because yesterday, i think it was, i did not have this
> problem.
>
I doubt that very much. You can check with gitk <filename>. gitk <filename>
will also tell you who created the file. Heck, the gnx's will tell you that
too. Just look at the node sentinels in the external files.

> how best will we recover from this?
>
Don't panic. It's almost impossible to lose data with git.

In a pinch, just copy and paste code (inside Leo). Do a clean checkout of
devel, then save the files.  Like this:

- In your .leo file: Copy the node ***@***.*** x.py`  to a new `COPY x.py`.
- git checkout devel.
- In your .leo file: Change `COPY x.py` to ***@***.*** x.py`.
- Save your .leo file, and now you have x.py.

I like this way, but of course git stash, git checkout devel, git stash pop
will also work.

Edward

**Comment by tbpassin** [comment]
duh!  when i checked for those files on github, i blindly looked at master, not devel.  they are there in github/devel.  whew!

my concern was that if i temporarily removed/renamed those files before checking out devel, i would end up needing to make a pr to get them back.

this all happened at my end after a failed attempt to rebase one of my branches.  i felt nicely blase about it because i thought that git would just be able to restore everything in case of trouble.  apparently between me and git-extensions we managed to confuse git.

i will close this issue and see what i can do at my end.

**Comment by tbpassin** [comment]
my git data must be really messed up, because when i get what should be a clean checkout of devel, i get leo 6.4.  i'm really not sure what to do next.  i did copy the folders with the files that were in the original error message, but at this point there is  something more that needs to be done.

**Comment by tbpassin** [comment]
`git checkout -f HEAD` was the answer.  Now i have a good checkout of devel.

**Comment by edreamleo** [comment]
@tbpassin Glad you found your way back :-) git is great when it works, hehe.
