### ISSUE TITLE
merge nodes of Recovered Nodes ?

### ISSUE THREAD

**Issue by ZoomQuiet** [leo-editor/leo-editor#263]
![screenshot 2016-04-18 17 56 20](https://cloud.githubusercontent.com/assets/22494/14622370/0cb7bf64-058f-11e6-85c9-f3b9e6d6b53d.png)

- as up snapshot
- after srtup `@bool check_for_changed_external_files = True`
- the `Recovered Nodes` quickly appended so much
- suggest :
    - if already exist `Recovered Nodes`
    - the new nodes, can appended the only one `Recovered Nodes`

**Comment by edreamleo** [comment]
On Mon, Apr 18, 2016 at 6:00 PM, Zoom.Quiet <notifications@github.com>
wrote:

> [image: screenshot 2016-04-18 17 56 20]
> <https://cloud.githubusercontent.com/assets/22494/14622370/0cb7bf64-058f-11e6-85c9-f3b9e6d6b53d.png>
>
>    - as up snapshot
>    - after srtup @bool check_for_changed_external_files = True
>    - the Recovered Nodes quickly appended so much
>    - suggest :
>       - if already exist Recovered Nodes
>       - the new nodes, can appended the only one Recovered Nodes
>
> ​I would rather not do this. The recovered nodes nodes are a warning which
should not be completely ignored (by Leo) but can be deleted by you safely.

Edward

**Comment by ZoomQuiet** [comment]
On Tue, Apr 19, 2016 at 5:19 AM, Edward K. Ream
<notifications@github.com> wrote:
>
> On Mon, Apr 18, 2016 at 6:00 PM, Zoom.Quiet <notifications@github.com>
> wrote:
>
...

> > - the new nodes, can appended the only one Recovered Nodes
> >
> > I would rather not do this. The recovered nodes nodes are a warning which
> should not be completely ignored (by Leo) but can be deleted by you safely.
>

agree, not important, just awoke Leo do what ;-)

can close now ;-)
thanks EKR.

> Edward
>

**Comment by ZoomQuiet** [comment]
CANCEL for overflow ;-( 放弃/转义/过期....
