### ISSUE TITLE
Show-commands and show-keys do not show bindings in @command ... @key settings

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#2631]
See PR #2663. The code is fantastically difficult.

The show-commands and show-bindings commands do not show bindings created by
    `@command xxx @key=yyy`.

**EKR**: Also, the bindings do not show in the completions tab.

**Status**

There seems to be no easy way to associate a single binding with various aliases of commands. I shall not do any more work in this area.

**Comment by edreamleo** [comment]
@tbpassin Do the bindings for the `@command nodes` show up in the show-bindings command?

**Comment by tbpassin** [comment]
No, not if the binding is defined in an outline that is not myLeoSettings.

Here is an example headline that creates the binding but does not show in the show-bindings listing:

`@command bk-open-tab @key = Alt+F5`

**Comment by edreamleo** [comment]
@tbpassin Thanks for the update.
