### ISSUE TITLE
Viewrendered3 does not render math with pyqt6

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#2636]
vr3 also fails to display html files if they depend on remote javascript files, such as Bokeh interactive graphs.  with pyqt5, this behavior was different - it rendered as intended.

the cause is that a particular WebSetting, _LocalContentCanAccessRemoteUrls_, is False by default but needs to be True.  For qt5 it was also documented to be False by default, but QWebEngineView acted as if it were True.

 i have fixed this in proof of principle code.  a complete fix will require minor additions to LeoQt5 and LeoQt6, as well as to vr3. i will submit a pr when this has been accomplished.

**Comment by edreamleo** [comment]
@tbpassin Thanks, Thomas.

**Comment by tbpassin** [comment]
Fixed in devel.
