### ISSUE TITLE
test-all may fail because "python3" is not an alias

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#2638]
run_unit_tests failed on my system:

test-all:
`'python3' is not recognized as an internal or external command, operable program or batch file.`

recommend replacing 'python3' by `sys.executable`

**Comment by tbpassin** [comment]
i don't know why not.  It returns a full path to the python executable that launched leo, so it ought to be exactly what is wanted.

**Comment by edreamleo** [comment]
@tbpassin Hmm. You would think so, but sys.executable is the full path to the *executing* version of python. That might make a difference in some situations.

**Comment by tbpassin** [comment]
But if you leave it as some version of "pythonx", you get whatever the system gives you, if anything, or you have to create a specially-named batch file.  not appealing either way.

**Comment by edreamleo** [comment]
@tbpassin I agree: there is no perfect solution. However, I think `python3` is a reasonable thing to require.

I'm going through much the same problems with unit tests for pylint. There are a surprising number of hidden (not well documented?) assumptions about the environment.

**Comment by tbpassin** [comment]
I agree that Python 3.x is reasonable to require.  But the string "python3" doesn't work on my machine.  "py" does work - the newer "py" launcher was installed some python versions ago. "python 3" and "python -3.9" work with this launcher.

I don't know what python installations have gotten this launcher and which have not.  most linux distros package up new releases their own way and don't have the launcher.

I suggest it would be better to use `sys.executable` - at least as a fallback - than for me not to be able to run `test-all`.

**Comment by edreamleo** [comment]
@tbpassin I'm convinced. Let's try sys.executable for now. We can always change our minds later.

**Comment by edreamleo** [comment]
@tbpassin I almost always run test-all *outside* of Leo using this script, in test-all.cmd:
```console
cd C:\Repos\leo-editor
python -m unittest %*
```
Using a script has significant advantages. In particular, if I have just changed part of Leo, the test-all script is the first check that I'll be able to run Leo after closing it :-)
