### ISSUE TITLE
Solution to #261 needs improvement

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#264]
#261 is fixed: the crash no longer happens. However, Terry points out that more work remains:

> For not relying on splitter_2 existing, the problem is that if you go from the initial layout to a custom layout and then back to "Default", the copy of the initial layout you saved to easily switch to the initial layout, you get a layout the *looks* like the default, but has no splitter 'splitter_2', the splitters are unnamed. So rather than searching for the splitter called splitter_2, you'd need to search for the splitter containing the two panes usually separated by splitter 2.

This issue will track the needed work.

**Comment by edreamleo** [comment]
Hah.  Terry commented somewhere that `free_layout.get_top_splitter().rotate()` might be good enough to handle `toggle-split-direction`.  What he modestly failed to mention is that that `toggle-split-direction` already uses that code, and it works at present. According to `git blame`, Terry updated the code 2014-11-13.

**Comment by edreamleo** [comment]
Recent revs, ending with 2bec2b7, complete the next phase of this project.

It's not entirely clear how this will work with the sessions machinery, but I'll close this for now.

Please reopen if there are problems.

**Comment by edreamleo** [comment]
@tbnorth The heart of the new approach are the `get_main_splitter` and `get_secondary_splitter` methods. Here is get_main_splitter. get_secondary_splitter is similar:
```
def get_main_splitter(self, w=None):
    '''
    Return the splitter the main splitter, or None. The main splitter is a
    NestedSplitter that contains the body pane.
    
    Yes, the user could delete the secondary splitter but if so, there is
    not much we can do here.
    '''
    trace = False and not g.unitTesting
    top = self.get_top_splitter()
    if top:
        w = top.find_child(QtWidgets.QWidget, "bodyFrame")
        while w:
            if isinstance(w, NestedSplitter):
                if trace: g.trace('found splitter', id(w))
                return w
            w = w.parent()
    if trace: g.trace('not found')
    return None
```
As you can see, this simply returns the splitter that contains "bodyFrame" widget. It's not clear how this could be generalized, but for most (all?) common layouts this code should suffice.

**Comment by tbnorth** [comment]
I think that's fine - the key is not to look for splitters themselves,
which are ephemeral, but the content you're interested in.
