### ISSUE TITLE
Make gotoFirstVisible and gotoLastVisible preserve the outline state (Allow setting flag for old behavior)

### ISSUE THREAD

**Issue by boltex** [leo-editor/leo-editor#2640]
GotoFirstVisible and gotoLastVisible are often desired to act as quick navigation commands, and the collapsing is not desired in those common instances. 

A boolean setting, **collapse-on-goto-first-last-visible** should be used to get the behavior that collapses all other nodes when performing those commands.

**Comment by edreamleo** [comment]
@boltex Thanks for opening this issue.

**Comment by boltex** [comment]
No problem at all, I'll close this issue when #2641 is part of the master branch and included in a release. (6.6.2 i guess) so that people searching for this don't expect it to be in the current release.
