### ISSUE TITLE
line edit not read/recognised using --gui=console

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#2642]
launchleo.py --gui=console

select a line to edit, delete characters from the line. However when you [esc] to end editing, the deleted characters reappear.
Highlight the Quit Leo button press enter, Leo closes with no option to save Y/N.

Leo 6.6.2-devel, devel branch, build 5c3fc2f9fe
2022-05-05 09:56:58 -0500
Python 3.10.4, PyQt version 6.3.0
Windows 10 AMD64 (build 10.0.19044) SP

Also confirmed with build 255683a111

**Comment by LewisNeal** [comment]
If characters are added when editing the line,  the edit is recognised.

**Comment by edreamleo** [comment]
@LewisNeal Thanks for this report.
