### ISSUE TITLE
Run pylint correctly!

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#2647]
Leo has been running pylint incorrectly for years! As a result, pylint *appears* to be much slower than it is:

- [x] Update the pylint rc file.
- [x] Remove pylint-leo.py.

**freewin.py**: The latest version of pylint passes freewin.py.

**Running pylint on directories is fast**

pylint (astroid) *does* cache asts, with a large speedup, *provided* that we run pylint on directories, not individual files. [pylint issue #2912](https://github.com/PyCQA/pylint/issues/2912) investigates further speedups, but that would be a huge project, with not that much potential improvement.

Given the following new suppressions in the pylint rc file:
```
# Files or directories matching regex, in Windows or Posix format.
ignore-paths=
    leo\external,
    leo\extensions,
    leo\modes,
    leo\plugins\obsolete,
    leo\plugins\qt_main.py,
        # Auto-generated, with long lines.
    leo\plugins\examples,
    leo\plugins\leo_babel,
    leo\plugins\pygeotag,
    leo\scripts,
    leo\unittests,
```
The following script takes roughly two minutes:
```console
C:\Python\Python3.10\python.exe -m pylint leo
```

**Comment by tbpassin** [comment]
I still think you are barking up the wrong tree here.  I just installed Python 3.10, and I still don't have your problem with pylint on freewin.  I almost never want to run pylint on a directory, just a single file at a time.  i can hardly imagine how i would sort through all that output to find the parts i want for one particular file

So i'd rather have a *new* command (say *pylint-dir*) and have the old one continue to work on just the one file.

**Comment by edreamleo** [comment]
@tbpassin I agree that running pylint on a single file is fast, and that there is no need to suppress freewin.py. The checklist suggests adding the pylint-leo-directory and pylint-plugins-directory commands. So there seems to be no dispute :-)
