### ISSUE TITLE
Spell Tab Missing

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#2649]
After I updated, there is no spell tab on any outline.  None of the minibuffer spell commands I tried do anything, and there have been no error messages. F7 does not open the Spell tab.

Leo 6.6.2-devel, devel branch, build 960f01c311
2022-05-13 15:06:33 -0500
Python 3.10.4, PyQt version 6.3.0
Windows 10 AMD64 (build 10.0.19043) SP0

**Comment by edreamleo** [comment]
Please reopen this issue if `pip install pyenchant` does not work.

**Comment by tbpassin** [comment]
That did it.  I thought there is internal code to use if pyenchant is not present?  is that just dead code now?

This Leo install was a fresh PyPi install, and apparently pyenchant is not one of the requirements.  I for sure had forgotten about it.

**Comment by edreamleo** [comment]
@tbpassin The code isn't dead. However, there is an interesting UI issue. The code *could* say to `pip install pylint`, but that seems too intrusive. Users would get that message every time they started Leo!

**Comment by tbpassin** [comment]
`pip  install pyenchant`, i suppose you meant.  a flag could be set so that the message would be shown when one tries to do any speller command, or perhaps just once per session when a speller command is activated..

without a reminder it's too hard to remember given how infrequently one does a fresh install.  how do you feel about having leo install pyenchant along with all the other dependencies?  there was a time when it wasn't available on windows, but in recent years it seems to be reliably available.

**Comment by edreamleo** [comment]
@tbpassin Yet another setting would be possible, but imo that's an ugly solution, and not all that helpful.

For now, I suggest you make a note to yourself :-)

**Comment by edreamleo** [comment]
@tbpassin FYI: PR #2662 changes setup.py so that `pip install leo` install pyenchant by default.

**Comment by tbpassin** [comment]
Thanks!

**Comment by edreamleo** [comment]
@tbpassin You're welcome. Note, however, that you will still have to remember to install pyenchant when installing Leo from git :-)
