### ISSUE TITLE
A setting to hide the icon bar

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#266]
The gui-iconbar-hide command does this, but there seems to be no way (except @script nodes) to do this on startup. In other words, Leo could use an `@bool show-iconbar = True` setting.

**Comment by ZoomQuiet** [comment]
agree so much

**Comment by edreamleo** [comment]
Rev 143dc2a added support for @bool show_iconbar, and rev a0615f38 added same to leoSettings.leo.
