### ISSUE TITLE
Restore full coverage for leoFind.py

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#2676]
See PR #2677.

Covering the new "File Only" revealed real problems.

**Comment by tbpassin** [comment]
It occurs to me that I did not implement "File Only" for anything except qt.  SOme of the setup and infrastructure code is (I think) in more general levels than the qt level, but I'm not sure how much of it is also used by any non-gui implementations.  This might affect the unit tests, perhaps.

**Comment by edreamleo** [comment]
@tbpassin As you say, coverage tests revealed problems. See the PR. I think all is well now.

I'm annoyed with myself for mistakenly merging your original PR into 6.6.2. Ah well, everything will be fixed in a month, hehe.

**Comment by tbpassin** [comment]
Thanks, Edward.

**Comment by edreamleo** [comment]
@tbpassin You're welcome. I think "File Only" is a good addition.
