### ISSUE TITLE
Fix 'reload-settings' command doc string and general behavior

### ISSUE THREAD

**Issue by boltex** [leo-editor/leo-editor#2682]
1- prevent saving untitled changed documents, to remove surprise of being presented with a sudden 'save as' dialog. (while saving all other changed files as before, requiring no input from the user)

2- modify the doc string from  "**Reload settings for the selected outline, saving it if necessary.**"  to something more like: "**Reload settings for the selected outline, saving any modified files first.**"

**Comment by edreamleo** [comment]
@boltex Imo, this is the best design.

**Comment by boltex** [comment]
Closing this issue as the fix is in devel from commit https://github.com/leo-editor/leo-editor/commit/02f88573cd79368f8d32f11f721a2e21a59aec27
