### ISSUE TITLE
Leo fails to start with --gui=console

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#2684]
See PR #2686.

First noticed running build f00522d.
```console
_Empty setting name in @data in G:/My Drive/editor/myLeoSettings.leo
set parent @settings
Leo 6.6.3-devel, devel branch, build a5c4060053
2022-06-16 11:27:38 -0500
Python 3.10.4, LeoGui: dummy version
Windows 10 AMD64 (build 10.0.19044) SP0
setHomeDirectory.py g.app.homeDir set to c:\_
```

At this point no file loads.
The first line is different - in a previous build it was:
Empty setting name in False
set parent @settings
Leo 6.6.3-devel, devel branch, build be1ca1d6ab

**Comment by edreamleo** [comment]
On Fri, Jun 17, 2022 at 10:00 PM LewisNeal ***@***.***> wrote:

> First noticed running build f00522d
> <https://github.com/leo-editor/leo-editor/commit/f00522db8cbcc8091eb90499b8c209ba2e473609>
> .
>
Thanks for this report. I see similar behavior: the console gui loads with
neither python 3.6 or 3.10.

The problem surely is in some other rev. The rev you mention changes only
the picture_viewer plugin.

Edward
