### ISSUE TITLE
separator bars cannot be dragged using PyQt6 v6.3.1

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#2685]
Fixed via PR #2687. The separator bars between panes cannot be dragged using PyQt6 v6.3.1

Leo Log Window
Leo 6.6.3-devel, devel branch, build a5c4060053
2022-06-16 11:27:38 -0500
Python 3.10.4, PyQt version 6.3.1
Windows 10 AMD64 (build 10.0.19044) SP0

**Comment by edreamleo** [comment]
@LewisNeal Thanks for this report. qt 3.6.1 contains [350(!) bug fixes](https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/6.3.1/release-note.md). Looks like one too many :-)

**Comment by edreamleo** [comment]
@LewisNeal I see the behavior you report. Leo issues no tracebacks, so perhaps an even no longer fires.

**Comment by edreamleo** [comment]
@LewisNeal Renaming NSH.mousePress/ReleaseEvent restores normal function, so presumably there needs to be a call to the super method.
