### ISSUE TITLE
ipyhon noteworthy "Cannot run qtconsole with existing kernel in jupyter-client 7"

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#2688]
ref: [Cannot run qtconsole with existing kernel in jupyter-client 7](https://issuemode.com/issues/jupyter/qtconsole/43008138)

Should:

    pip install jupyter-client==6.1.12

    python launchLeo.py --ipython

Because with `jupyter-client-7.3.4 ` , Only a blank qtconsole display.

**Comment by edreamleo** [comment]
Thanks for this report. I have "delegated" this issue to the Jupyter devs :-)
