### ISSUE TITLE
Remove v.clonedBit, v.topBit and related getters/setters

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#2689]
Félix discovered (and cffs confirm) that Leo uses neither these bits nor the related setters/getters in the vnode and position classes.

**Comment by tbpassin** [comment]
If they do something, like return the cloned state, someone else might be using them.

**Comment by edreamleo** [comment]
@tbpassin I'm willing to live with the risk :-) The bits themselves are low level. v.isCloned is the high-level alternative.
