### ISSUE TITLE
Regression: blank nodes now automatically colorized and auto-indent after lines ending with colons

### ISSUE THREAD

**Issue by gatesphere** [leo-editor/leo-editor#2695]
See PR #2696.

After the work removing GCM, Leo's behavior on plain-text nodes has changed to act as if those nodes were python nodes.  Specifically, previous behavior:

- Open leo with a blank worksheet
- Insert a new plain node (no @directives)
- Enter body text:

```
This is a test node:
this should not be indented
```

The text was not colorized and the line after the : was not automatically indented.

After commit dd63f47a5a7deba9d8f534364f34965032ef1938 (determined with git bisect), new behavior is:

```
This is a test node:
    this should not be indented
```

The 'is' is colorized as if it were python, and the second line is automatically indented after pressing the enter key on the first line.

This is a fairly large change in behavior, and if this is the intended behavior going forward (which I hope is not the case), it will impact my workflow using Leo nodes for containing non-code information.

**Comment by edreamleo** [comment]
Thanks for this report. In the new version of the code, only `@string target-language` controls the default syntax coloring (and other behaviors, such as indentation) of a node.

Does your myLeoSettings.leo file contain an  `@string target-language` setting?

**Comment by edreamleo** [comment]
`@string target-language=rest` does not seem to work.  This is likely the source of the regression.

**Comment by edreamleo** [comment]
Happily, the fix was clean. I also fixed two other buglets involving ivars.

**Comment by gatesphere** [comment]
Definitely appears fixed for me in devel.  Thanks, Edward!

**Comment by edreamleo** [comment]
@gatesphere You're welcome. Thanks for your continued testing.
