### ISSUE TITLE
Load Manager Defines Obsolete "dock" Options

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#2699]
Leo doesn't use docks any more, but LoadManager.scanOptions() still defines a number of docks-related options:

```
    table = (
        '--dock',
        '--global-docks',  # #1643. use --use-docks instead.
        '--init-docks',
        '--no-cache',
        '--no-dock',  # #1171 and #1514: use --use-docks instead.
        '--session-restore',
        '--session-save',
        '--use-docks',
    )
```
Presumably they aren't harmful because they aren't used any more, but perhaps they could be removed at some point.  I haven't checked to verify that they all aren't used somewhere.

**Comment by edreamleo** [comment]
@tbpassin scanOptions uses this table to warn about obsolete options.

**Comment by edreamleo** [comment]
Rev b5094b9f renames 'table' to 'obsolete_options'. The former name was a bit confusing since table wasn't defined in the node in which it was used.
