### ISSUE TITLE
Vim keys don't always work after double Alt+Tab

### ISSUE THREAD

**Issue by benzolius** [leo-editor/leo-editor#270]
Strange behavior when I leave Leo (Alt+Tab) after "Insert" on headline node.
When I come back (Alt+Tab) to Leo only the menu works (Alt+F, ...) and the mouse.
Other unusual behavior:
left-arrow, right-arrow changes between Leo documents (like Ctrl+Tab in normal behavior)

Leo 5.3-devel, build 20160412153848, Tue Apr 12 15:38:48 CDT 2016
Git repo info: branch = master, commit = 31bb38803e24
Python 3.4.3, PyQt version 5.2.1
linux

**Comment by edreamleo** [comment]
I'll fix this before 3.5-b1.

**Comment by edreamleo** [comment]
To quote from the checkin log:

> This is an exceeding strange bug, presumably due to obscure differences in the Qt code. The fix was fairly straightforward in idle_focus_helper, but this means that there is a slight delay before focus is restored. This presumably can't be helped.

**Comment by benzolius** [comment]
Thanks Edward,

Is much better, but unfortunately there is still some strange behavior (though is not very disturbing):

"Insert" on headline node
(Alt+Tab)(Alt+Tab)

The same effect: only the menu works (Alt+F, ...) and the mouse

After (Alt+Tab)(Alt+Tab) again or using (Alt+F, ...) and the mouse, then it works nearly normally.

Only the vim-mode keys doesn't work on headlines.
But after I enter into a body and insert/edit something, it works normally again.


@bool vim-mode = True
Leo 5.4-devel, build 20160412153848, Tue Apr 12 15:38:48 CDT 2016
Git repo info: branch = master, commit = 09e63856f7eb
Python 3.4.3, PyQt version 5.2.1
linux

**Comment by edreamleo** [comment]
I just saw that the problem happens in vim mode (@bool vim-mode = True).  Presumably the Alt-Tab (Focus-out) logic leaves vim mode in a strange state.

**Comment by edreamleo** [comment]
LeoQtGui.onActivateEvent now calls vc.on_activate.  It seems to work well enough. Please reopen if there are further problems.

**Comment by digulla** [comment]
This breaks Leo for me; see #359
