### ISSUE TITLE
Question: default directives

### ISSUE THREAD

**Issue by veksha** [leo-editor/leo-editor#2701]
Hello. How can I change what directives should be default for specified language when I import file using @clean node?
I need add to these to defaults:
```
@nowrap
@nobeautify
```

**Comment by edreamleo** [comment]
You can add these directive to any `@clean` file at any time.

**Comment by veksha** [comment]
but i must do it for every file by hand?

**Comment by edreamleo** [comment]
On Sun, Jul 3, 2022 at 8:53 AM Yuriy Balyuk ***@***.***>
wrote:

> but i must do it for every file by hand?
>
Yes. That should be easy with a search/replace.

Edward
