### ISSUE TITLE
Auto-completion suggestions from words in document

### ISSUE THREAD

**Issue by largo84** [leo-editor/leo-editor#271]
Notepad++ (NPP) has several very useful auto-completion features that could make Leo considerably faster and less prone to typing errors. This enhancement request is for Leo to suggest words in the document (the .leo file) that match the first n letters typed (n is configurable).

Groups discussion [here](https://groups.google.com/forum/#!topic/leo-editor/ygGiqDgW8vM).

**Comment by edreamleo** [comment]
This may become part of #309.  I'll leave it open for now, and target this for 5.5.

**Comment by edreamleo** [comment]
I am not going to do this as a separate issue.  It is implied in various other auto-completion tools.
