### ISSUE TITLE
How to access some body text in myLeoSettings.leo

### ISSUE THREAD

**Issue by jabobian** [leo-editor/leo-editor#2711]
Hello,

with `g.findNodeAnywhere(c, "the string to find")`, I can get node in the current outline. But I want to get the node in myLeoSettings.leo, and then get its body text. 

This feature is wanted as I want to put some test codes in the setting files, rather than in the working leo file.

**Comment by tbpassin** [comment]
Do you mean that you want a method to find a string in myLeoSettings.leo even if that outline is not open in Leo?

If you want to look in myLeoSettings.leo when it is already open, it is possible to get a list of commanders and from that get the commander for any particular open outline.

**Comment by jabobian** [comment]
@tbpassin Many thanks for your help. 
The code to get commanders is helpful during developing, but the ultimate goal is a method to find a string in myLeoSettings.leo even if that outline is not open in Leo.

**Comment by tbpassin** [comment]
If it's not open, you can construct its path, and then open the outline:

```
c_outline = g.openWithFileName(outline)  # c_outline is the commander of the newly opened outline
```

**Comment by jabobian** [comment]
@tbpassin Thanks, this is also acceptable in my case.

**Comment by edreamleo** [comment]
On Sat, Jul 9, 2022 at 10:38 PM jabobian ***@***.***> wrote:

> The code to get commanders is helpful during developing, but the ultimate
> goal is a method to find a string in myLeoSettings.leo even if that outline
> is not open in Leo.


Searching for my-leo-settings will take you to the code for the
my-leo-settings command:

@g.commander_command('open-leo-settings')
@g.commander_command('open-leo-settings-leo')  # #1343.
@g.commander_command('leo-settings')
def openLeoSettings(self, event=None):
    """Open leoSettings.leo in a new Leo window."""
    c, lm = self, g.app.loadManager
    path = lm.computeLeoSettingsPath()
    if path:
        return g.openWithFileName(path, old_c=c)
    g.es('not found: leoSettings.leo')
    return None

*lm.computeLeoSettingsPath* properly computes the path to
myLeoSettings.leo, and *g.openWithFileName* opens the settings file. Notes:

- g.openWithFileName won't reopen leoSettings.leo if it is already open.
- *g.createHiddenCommander(path) *will open a temporary hidden commander
for the given path.

Putting this all together, your script could do something like:

lm = g.app.loadManager
path = lm.computeLeoSettingsPath()
c = g.createHiddenCommander(path)

The main idea is to "mine" Leo's sources for code snippets.

Edward
