### ISSUE TITLE
horizontal Scrollbar for the tree node panel

### ISSUE THREAD

**Issue by jabobian** [leo-editor/leo-editor#2712]
See PR #2713.

When working with deep tree, horizontal scrollbar is most wanted.

Could you please provide some form of settings, and the settings can be activated and deactivated by commands and shortcuts?

**Comment by edreamleo** [comment]
@jabobian A bit of research indicates that neither settings nor qt style sheets will work. Instead, the default QTreeWidget behavior appears to be buggy and/or unhelpful, as shown by googling `qtreeview horizontal scrollbar` I'm not sure what, if anything, can be done.

**Comment by jabobian** [comment]
Will the following [link](https://forum.qt.io/topic/87741/why-is-there-no-horizontal-scrollbar-in-a-qtreeview-with-qfilesystemmodel/6) be helpful?
`void MainWindow::onExpanded(const QModelIndex& index)
{
    ui->treeView->resizeColumnToContents(0);
}`

**Comment by tbpassin** [comment]
Maybe this?

[\[\[FIXED\] How to make PyQt5 QScrollArea horizontal scrollbar show up dynamically?](https://www.pythonfixing.com/2022/03/fixed-how-to-make-pyqt5-qscrollarea.html)

**Comment by edreamleo** [comment]
@tbpassin Well done. Rev 1e579573 looks like it will work on pyqt5/6. More testing needed.

**Comment by edreamleo** [comment]
The code works on both pyqt5 and pyqt6. This issue should not impact leoJS, so I'll merge this into devel for Leo 6.6.3.
