### ISSUE TITLE
Need Help： How to avoid SyntaxError: 'return' outside function

### ISSUE THREAD

**Issue by jabobian** [leo-editor/leo-editor#2714]
When testing the script-button to run some script, I frequently meet the return outside function problem. 
But it will be quite forcing if one can only code the logic without return.

```
current = c.p
if not current:
    return None
c.endEditing()
blabla...
```

**Comment by edreamleo** [comment]
On Sun, Jul 10, 2022 at 4:40 AM jabobian ***@***.***> wrote:

> When testing the script-button to run some script, I frequently meet the
> return outside function problem.
> But it will be quite forcing if one can only code the logic without return.
>
> current = c.p if not current: return None c.endEditing() blabla...
>
Just do the work in a helper function:

def helper():
    if not c.p:
        return
    ...

helper()

Btw, helper has access to c, g and p.

Edward

**Comment by jabobian** [comment]
Thanks!

**Comment by tbpassin** [comment]
Make your whole routine into a function, then execute that function. E.g.,

```
def test_script():
    if not c.p:
        return None
    # other code here
    # function implicitly returns None when finished

test_script()  # Executes when your script button is pressed.
```

**Comment by tbpassin** [comment]
Can we close this issue now?
