### ISSUE TITLE
vr3 - includes dumplicated noded contents by using View Option Entire Tree with asciidoc

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#2715]
When using asciidoc (by asciidoctor), View Option Entire Tree includes dumplicated noded contents.

For example:

```
node1
    node2

vr3 then display:

node1
node1
node2
node1
node2
```

**Comment by tbpassin** [comment]
Please post a small outline that illustrates this issue.

**Comment by wangzhaohe** [comment]
Thanks a lot tbpassin.

It was Fixed.

I am looking for a good presentation like PPT for students while teaching python. I can bear the slow speed. The asciidoctor is the better one translating asciidoc than asciidoc & asciidoc3.

**Comment by tbpassin** [comment]
You are welcome, glad I could help.  I agree with you that if speed isn't an issue, asciidoctor is the best.  Also, I just found that asciidoc3 isn't working any more in VR3, another thing for me to track down.

There is also an extension for Sphinx that can build slides ([Hieroglyph](https://hieroglyph.readthedocs.io/_/downloads/en/latest/pdf/)).  Of course, that wouldn't be using Asciidoc but RestructuredText.
