### ISSUE TITLE
Using chapter-next to get into a chapter instead of the menu needs a 'tree-refresh' to be performed

### ISSUE THREAD

**Issue by boltex** [leo-editor/leo-editor#2718]
See PR #2718.

The chapter commands and selection from the chapters dropdown menu seem slightly broken.

When using the chapter-select dropdown menu in an outline that has chapters, that gets me hoisted into that chapter. So far this is the only chapter related action that seems to work ok in Leo... :/

Using chapter-next and chapter-prev command (via alt+x) just select the node without visually hoisting it. (But then, changing the tab to another opened outline, and coming back forcing a refresh, gets it hoisted properly)

Also, while hoisted in a chapter, doing chapter-next sometimes just yields the  'can not hoist an @chapter node.' message and/or does nothing. 

Maybe this is also related to a missing 'tree-refresh' action that is missing after one of those commands has been issued.

Lastly I feel that doing a de-hoist command while in a chapter should do the equivalent of select-chapter-main... (is it already the case and it's just not refreshing / updating properly?)

(can anyone else confirm those behaviors?)

**Comment by tbpassin** [comment]
I haven't looked at your items, but I just noticed that selecting a chapter in the chapter drop down list does not include the top-level node of the chapter - that is, the node with the "@chapter" headline.  IMO, the top-level should be included in the displayed tree.

**Comment by tbpassin** [comment]
"Lastly I feel that doing a de-hoist command while in a chapter should do the equivalent of select-chapter-main... (is it already the case and it's just not refreshing / updating properly?)"

On my system chapter-select-main does not work the same as the Dehoist menu item.

**Comment by boltex** [comment]
@tbpassin oh i see: perhaps you're refering to the fact that "chapter-select-main" is akin to a 'de-hoist-all-levels' instead of a single 'de-hoist' if hoisted more than once.

On the other hand, I've looked at the code and there seems to be missing c.redraw calls a the end of many chapter related commands. 

Lastly, about the @chapter headline being omitted, it probably was intended... but I also personally feel that it would be nice to have it throne at the top like a regular hoist, (when choosing a chapter with the chapter-related commands).

I'll wait for @edreamleo  to chime in, and I'll propose to fix all the chapter-related issues in one go (shouldn't be long nor hard) upon Edward's say on the matter.

**Comment by boltex** [comment]
oh! 

I noticed that this documentation page is very much deprecated (header says "Leo 4.11") : https://leoeditor.com/outlines.html#using-chapters This contains references to commands that do not exist.

While http://leoeditor.com/commands.html#using-chapters seems to be the correct @chapters info, with only 5 relevant commands.

hehe!

This threw me off a little bit there as I'm trying to make chapters work nicely in leointeg, and I couldn't get them to work in a consistent way that made sense in Leo itself after reading the old deprecated docum!  :)

**Comment by boltex** [comment]
this was somewhat talked about, but not completely resolved in 2017 : https://groups.google.com/g/leo-editor/c/Yskl41H7AfI

**Comment by edreamleo** [comment]
@boltex @tbpassin Thanks for these comments.

I can that there are some missing calls to c.redraw (or similar) in the chapters code. I'll look into this. I'll also look at the documentation.

The `@chapter` node is, on purpose, not shown after selecting a chapter. We don't want users editing such nodes from within a chapter!

**Comment by edreamleo** [comment]
@boltex @tbpassin A simple fix works (apparently). PR #2721 is ready for review.

**Comment by boltex** [comment]
I tested your new fix branch, ekr-chapters2. 

**The good news**: The bug i had originally found is fixed, it redraws properly when using the chapter related commands directly from the minibuffer. 

**But,** it led me to find another one: When "in" a chapter, the 'de-hoist' command is buggy. Once de-hoisted from a chapter, the chapter controller will intercede if navigating the outline and going through the nodes that happened to be part of the previously (still considered active) chapter. (when reaching nodes that are part of the invisibly 'active' chapter, the outline will magically be 'in' the chapter, instead of displaying the whole of the outline.)

The simple solution I propose, is at the very beginning of the de-hoist command, a single line of code could first check to see if the top of the hoist stack P has an '@chapter' headline. If so, Leo should silently execute **chapter-select-main** instead of a regular **de-hoist**. (if the config setting 'use_chapters' is true) 

This would do the naturally expected result for a user's point of view, and eliminate the buggy behavior.

**Comment by boltex** [comment]
In the meantime I'll add some chapter commands to leoserver tonight (this will be the last little update i want to make to the server to merge in devel and release for Leo 6.6.3)

:)

**Comment by boltex** [comment]
Lastly, while you're in the chapters code, the doc string of chapter-select is wrong (it does not create chapters as it previously did in older Leo versions) and the doc string of chapter-select-main is absent.

**Comment by edreamleo** [comment]
@boltex Thanks for your careful testing. I'll update the PR soon.

**Comment by edreamleo** [comment]
@boltex The chapter-next command works for me as expected.

**Comment by edreamleo** [comment]
@boltex rev aa1d27c contains the latest code.

I'm good with the code as it is. Let me know if you can pin down the problem with chapter-next.

**Comment by boltex** [comment]
@edreamleo Thanks! I'll look at the fixes and re-test the chapter related commands tonight after work. 

(one of the problems i had also forgot to mention, is that after selecting a chapter, the selected node ( c.p ) was set to the @chapter node itself, instead of it's first child. (there is even a line that creates a "New Headline" first child in case the @chapter node has no children. )

Maybe you already fixed that - ill check it out tonight :)

thanks again !

**Comment by boltex** [comment]
I found what the bug was with 'chapter-next' : 'sorted' is applied to the chapter list in chapter-back and chapter-next...!

you do  **names = sorted(cc.setAllChapterNames())** instead of **names = cc.setAllChapterNames()** so with my example outline, instead of cycling through ['main', 'firstchapter', 'secondone', 'three'] the sorted array breaks the natural order of the chapters in the outline by listing them alphabetically! 

['firstchapter', 'main', 'secondone', 'three'] and so, makes it that whenever a user goes 'chapter-next' it will select the first one appearing alphabetically after 'main' alphabetically,,, instead of the first one in the outline. 

I'll continue testing other basic features of chapters in Leo itself and their integration via leobridge thorughout the evenig and I'll comment some more if I find other issues.

Thanks again for fixing those 'chapter' issues! :)

**Comment by edreamleo** [comment]
@boltex Good catch. I'll update the PR.

**Comment by edreamleo** [comment]
@boltex rev e3401fd fixes the "sorted" bug in the chapters-next/back commands. I'll wait for your ok before merging this PR.

**Comment by boltex** [comment]
@edreamleo Thanks!!  I'm glad my hands-on testing finds little bugs like this! :)

But, (and I've also noted this in the code review for the PR): One major bug (which affects leobridge, leoserver and leointeg, but is somewhat circumvented in the GUI of leo itself if used with the qt GUI.) still remains with chapters commands such as chapter-next, etc... : it doesn't leave the right node selected after being done. It should be the first child. not the chapter itself. 

If not the 'main' chapter, the first child **is already asserted to exist** by chapterSelectHelper in the chapter class. 

So the last part of selectChapterByNameHelper should be:
```
if chapter.name == 'main': 
    c.selectPosition(chapter.p)  # as normal
else:
    c.selectPosition(chapter.p.firstChild())  # select first node inside
c.redraw()  # #2718.
```

instead of just

```
c.selectPosition(chapter.p)
c.redraw()  # #2718.
```

I just tested it in both Leo and throught leoserver/leointeg. This would make all features work nicely for the chapters.

_(P.S. oh and one last silly thing: modifing @files via leoPyRef, and saving it, scrambles the whole leo file instead of changing nothing, like it's supposed to do! hehe ...)_

**Comment by boltex** [comment]
My last comment should be ignored: As noted in the PR, the real problem was the contractAllHeadlines.

Closing this as it's fixed in devel for 6.6.3 - Many thanks!

**Comment by edreamleo** [comment]
@boltex re your comment "modifying @files via leoPyRef, and saving it, scrambles the whole leo file instead of changing nothing, like it's supposed to do! hehe ...)"

This would be no laughing matter! However, the proper way to update leoPyRef.leo is to use the write-leoPyRef button. I have just done so in devel. The diff is three lines long, with the expected changes.

**Comment by boltex** [comment]
@edreamleo  I just noticed this : 

> The proper way to update leoPyRef.leo is to use the write-leoPyRef button

I Don't know why i just registered this fact, i probably read this too fast skimming over it! 

Thanks for clearing this one up !

**Comment by edreamleo** [comment]
@boltex Glad the comment help. Please let me know if the button doesn't work as expected.
