### ISSUE TITLE
How to disable the blue rectangle (focused panel's blue border), particularly that of the tree panel

### ISSUE THREAD

**Issue by jabobian** [leo-editor/leo-editor#2719]
Currently I am trying to use Leo as a meta outline manager for various URIs, e.g. onenote:, file: etc. I put Leo window on the side of the monitor, with a width of about  300 pixels. 
Everything looks quite nice, except the the blue rectangle is not quite wanted. 
So, any one know how to make the blue rectangle lighter, transparent, or disappear. If possible, only to make the blue rectangle border for the tree panel disappear.

Thanks!

**Comment by tbpassin** [comment]
This is probably a CSS property in the theme file.  I don't know which one just now.

**Comment by tbpassin** [comment]
In your theme file, in qt-gui-plugin-stylesheet, find the node with headline *Borders*.  Change it to read

LeoQTreeWidget#treeWidget {
  border: none;
}

You will have to restart Leo, or at least load another outline, to see if the effect is what you want.

**Comment by edreamleo** [comment]
@jabobian Weird, it seems my reply has gone missing.

There are many settings in leoSettings.leo that relate to borders. You can find them by searching for "focus" or "border". The most important are:

```console
@color focused-border-focus-color = blue
@color focused-border-unfocus-color = white
@string focused-border-style = solid
@string focused-border-width = 3px
```
**Note**: True, the various Qt style sheets have border-related settings, but those settings are (mostly) static. The settings shown above depend on dynamic data, and as a result can not be duplicated exactly by Qt settings.

**Comment by jabobian** [comment]
@edreamleo @tbpassin Many thanks for the guidance.
` @color focused-border-focus-color = white` solved my problem.

**Comment by edreamleo** [comment]
@jabobian You're welcome. Glad you found the solution.

**Comment by edreamleo** [comment]
On Thu, Jul 14, 2022 at 12:43 AM jabobian ***@***.***> wrote:

> Currently I am trying to use Leo as a meta outline manager for various
> URIs, e.g. onenote:, file: etc. I put Leo window on the side of the
> monitor, with a width of about 300 pixels.
> Everything looks quite nice, except the the blue rectangle is not quite
> wanted.
> So, any one know how to make the blue rectangle lighter, transparent, or
> disappear. If possible, only to make the blue rectangle border for the tree
> panel disappear.
>
Good question. You can find the related settings by searching for "border"
in leoSettings.leo, but as it happens searching for "focus" is better. You
will find:

@color focused-border-focus-color = blue
@color focused-border-unfocus-color = white
@string focused-border-style = solid
@string focused-border-width = 3px

Edward
