### ISSUE TITLE
How to move the Chapter plugin's dropdown list to the most left of IconBar

### ISSUE THREAD

**Issue by jabobian** [leo-editor/leo-editor#2722]
I am trying to make Leo a special PIM outline manager, with Leo's window resized to about 300 pixels wide. Use nodeActions plugis to navigate to any uri I attached to the clicked node.

Since the window width is smaller than normal, the Chapter plugin's dropdown list is not visible, and I cannot drag it. But it is very useful for me to focus on a small branch of node tree. So I want to move the dropdown list to the most left of the IconBar. 
I have searched the source code, but it is not clear for the first step. Maybe I can find the answer some day by myself only, but I prefer to ask help here to see if Sir E.K.Ream, tbpassin and other experts can share some clues.

**Comment by edreamleo** [comment]
@jabobian I'm not sure how to do what you want, but here is what a bit of searching tells me:

c.frame.top.iconBar is a [QToolBar](https://doc.qt.io/qt-6/qtoolbar.html).
 
The ChapterController.tt ivar is a LeoQtTreeTab. LeoQtTreeTab.createControl creates a label (a QtWidgets.QLabel) and acombo box (a subclass of QtWidgets.QComboBox) and then calls QtIconBarClass.addWidget to add both the label and the combo box to the icon bar.

In other words, Leo creates both widgets by calling QToolBar.addWidget. The QToolBar documentation says:

"When a toolbar is resized in such a way that it is too small to show all the items it contains, an extension button will appear as the last item in the toolbar. Pressing the extension button will pop up a menu containing the items that do not currently fit in the toolbar."

However, I don't see any such button.  Note that *widgets* are not iconBar *buttons*, which might explain why no extension button is shown.

I suspect that it *is* possible to do something like what you want, but I don't know how. I suggest creating a plugin in which you can do experiments with your own QComboBox widget. If you can find a way to move that experimental widget, you might suggest (say) making leoChapters.py more flexible.

**Comment by tbpassin** [comment]
Isn't there a setting that lets the icon bar display two levels instead of truncating?  I think I vaguely remember someone asking about two-level icon bars some time ago.

**Comment by tbpassin** [comment]
There is a QToolbar method *insertWidget()* that will insert a widget before a given widget.  So if we can find out the existing first widget, we could use *insertWidget()* instead of *addWidget()* to put it first.

**Comment by edreamleo** [comment]
@tbpassin Yes, Kent asked for something like this many moons ago.

**Comment by jabobian** [comment]
@tbpassin 
After reading some of the codes, it seems we need add insertWidget() in \leo\core\leoFrame.py for several classes:
class LeoFrame:
class IconBarAPI:

and in qt_frame.py :: class LeoQtTreeTab :: createControl(), add code for insertWidget according to user settings.

And I don't know how to use the returned QAction class from addwidget() in Python.
[insertWidget](https://doc.qt.io/qt-6/qtoolbar.html#insertWidget)(QAction *before, QWidget *widget)

**Comment by tbpassin** [comment]
If this is more or less what you want, we will want to have a setting for whether to locate the chapter controls on the left or not.  Would that work for you?

**Comment by tbpassin** [comment]
I just discovered that the icon bar can be dragged to become a vertical strip on the left.  This leaves less room for the tree panel, but maybe might fit in with how @jabobian  wants to work ...

![iconbar-left](https://user-images.githubusercontent.com/36974235/179277185-63e4896b-b000-4334-9ba6-32f7d000ed6f.png)

**Comment by jabobian** [comment]
> I think I have got it. This is what you want, isn't it?
> 
> ![chapters-left](https://user-images.githubusercontent.com/36974235/179260113-b61b3d55-690a-48ea-b4bb-cfca7dc36cfe.png)
> 
> The code changes for this are minor, and are all in qt_frame.py (in LeoQtTreeTab)

Dear @tbpassin , This is what I want. The chapter droplist on the top. Could you please update the code with settings? Many thanks!

**Comment by jabobian** [comment]
> 

Dear @tbpassin , this approach is interesting but less usable. I found we can also make the toolbar floating :)

**Comment by tbpassin** [comment]
OK, I should be able to submit a PR on Monday.

**Comment by tbpassin** [comment]
@jabobian, as soon as the PR has been merged, please try it out.

If you would also like the *Forward/Back* Buttons near the left, you can arrange that by changing the plugin order in the *@enabled-plugins* node in your myLeoSettings.leo file.  Just move the line *nav_qt* higher than the line *mod_scripting*.

**Comment by tbpassin** [comment]
Since no one has reported any problems with the change, I'm going to close this issue.
