### ISSUE TITLE
Hoist and de-hoist should not be 'undoable' commands.

### ISSUE THREAD

**Issue by boltex** [leo-editor/leo-editor#2724]
See PR #2725.

Hoist and de-hoist surprised me as being undoable commands when i transliterated Leo's core classes to typescript because they are just 'view change' commands, akin to zooming in/out in, or panning in autocad or photoshop, or scrolling up and down in word, etc. and not undoable 'editing' commands that would change the structure of the outline, or its content.

 I thought nothing more of it at the time because there was no apparent harm for those commands to be undoable, even though they didn't change the outline structure, nor body content at all. Still, felt a bit weird that it was the single and only non-editing command that was undoable.

But lately, it struck me as an anomaly when i reconsidered, thinking about the hoiststack, and that it can be altered by other commands (chapter, etc.) and plugins, that modify it without regards to the undo beads stack (and undo / redo integrity of its bead stack, which may be interleaved with hoists/de-hoists.).

For the undo/redo bead stack to keep 100% forwards / backwards integrity through each state, the most simple and quick solution is to make the hoist and de-hoist commands not undoable, so that the undo-redo stack only contains logically undoable structural, or body-content "changes".

 Concretely, in terms of code-editing, it's a small edit : it would consist of removing the '**afterHoist**, **afterDehoist**' calls in the redo and undo commands, and get rid of those same methods, along with **redoHoistNode** and **redoDehoistNode**, in leoUndo.py. 

This will make hoist/dehoist like any other view-change' action: not undoable. Like scrolling the outline vertically, expanding/collapsing nodes, and navigating in general. 

(Perhaps some unit-tests relating to hoist-dehoist commands would fail, but would only need to be removed, instead of fixed, in any way.)

Félix

**Comment by edreamleo** [comment]
@boltex I agree. You are becoming the "undo guru".

I'll issue a PR later today.
