### ISSUE TITLE
Simplify Leo's importers using python importer as a template

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#2727]
Vitalije's new python importer is contains a brilliantly simple algorithm that uses python's tokenizer module. A generalized version of this algorithm is now the basis for the code in the Importer class.

**Note**: leoJS probably can't use use Vitalije's python importer because python's tokenizer module doesn't exist in typescript. So leo.plugins.importers.python contains two versions of the python importer: one for Leo itself and one for leoJS.

[This post](https://groups.google.com/g/leo-editor/c/doUUtmabvcw) discusses the new importers. To summarize, the generalized importer algorithm in the Importer class separates:
- the detection of **blocks** (functions, classes, and methods) from,
- the allocation of blocks to nodes.

**Importer.gen_lines** is the main line of the Importer class (and subclasses).

**i.get_block** computes the text range for one block and returns a named tuple describing the block's text range (and other data). A prepass in i.gen_lines calls this method repeatedly to detect all blocks.

**i.make_node** allocate blocks to child nodes using *only* text ranges.  This method calculates the indentation of `@others` statements using only the indentation of the newly-allocated nodes.

**Comment by tbpassin** [comment]
Unless the importers don't work right, I'm inclined to go with "If it ain't broken don't fix it".

**Comment by edreamleo** [comment]
@tbpassin The python importer will probably need to be replaced for leoJS. We'll see about the other importers later. It may be that only gen_lines will need to change to make everything simpler.

Remember that strong unit tests exist for most importers, so there is little risk.
