### ISSUE TITLE
AttributeError: 'QWebEnginePage' object has no attribute 'mainFrame'

### ISSUE THREAD

**Issue by andrewchenshx** [leo-editor/leo-editor#2733]
**EKR**: I have just marked this issue "Won'tFix", that this issue will be fixed only if someone else fixes it.

 The workaround, for now, is to use Qt 5.6. Obviously, that's not ideal.

Leo 6.6.3-devel, devel branch, build 4eaacdf7e5
2022-06-29 04:10:01 -0500
Python 3.7.3, PyQt version 5.12.5
Windows 10 AMD64 (build 10.0.19041) SP0
read outline in 0.03 seconds
saved: 111.leo
hook failed: unselect1, <bound method CKEEditor.unselect_node of <leo.plugins.richtext.CKEEditor object at 0x000002AE4EA585E8>>, <no module>
Traceback (most recent call last):
  File "C:\Users\Andrew\Documents\GitHub\leo-editor\leo\core\leoPlugins.py", line 322, in callTagHandler
    result = handler(tag, keywords)
  File "C:\Users\Andrew\Documents\GitHub\leo-editor\leo\plugins\richtext.py", line 185, in unselect_node
    frame = self.webview.page().mainFrame()
AttributeError: 'QWebEnginePage' object has no attribute 'mainFrame'

**Comment by tbpassin** [comment]
It seems that the *mainFrame* object was retired after Qt 5.6 - see

[Python - how to use mainframe\(\) method in QWebEnginePage](https://stackoverflow.com/questions/53221011/python-how-to-use-mainframe-method-in-qwebenginepage-error-of-mainframe)

There is no replacement so far as I can see, but it appears that the ``page()`` itself could be used instead.

**Comment by tbpassin** [comment]
CKEditor is up to v5, but the plugin's ckeditor.js script has an internal date of 2014.  Would this plugin even work as is anymore, even if this particular item were fixed?

**Comment by edreamleo** [comment]
I am going to put this issue on hold until Leo 6.6.5
