### ISSUE TITLE
zoom-in & zoom-out command can not persist again

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#2734]
I remember the font size  will not change when clicking body panel after run zoom-in or zoom-out before several version.

But now the font size in body will change to the default size when clicking the body panel.

Is this a design only for preview, not for edit?

Leo 6.6.4-devel, devel branch, build 9dab5416da
2022-08-12 08:24:43 +0800
Python 3.9.5, PyQt version 5.15.2
darwin

**Comment by tbpassin** [comment]
I don't see that.  What I do see is that the zoomed condition 

1) only affects the outline you were in when issuing the zoom-xx command;

2) does not persist through a restart (which I seem to remember it used to do).

**Comment by wangzhaohe** [comment]
I found it if set this flag.

@bool vim-mode = True
