### ISSUE TITLE
vr3-lock not work

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#2735]
Command `vr3-lock` will not work, but click *freeze in View Options* works.

Leo 6.6.4-devel, devel branch, build 9dab5416da
2022-08-12 08:24:43 +0800
Python 3.9.5, PyQt version 5.15.2
darwin

**Comment by tbpassin** [comment]
I didn't even remember there is such a command.  I'll take a look.

**Comment by tbpassin** [comment]
*vr3-lock* does not do the same thing as *Freeze*.  *Freeze* prevents the VR3 pane from updating while you type.  *vr3-lock* locks the VR3 display to the current subtree.  While it is locked, you can select a node in the subtree and the display will not change to show only that node.  If you edit this newly selected node, the changes will display in the right place in the displayed tree.

*vr3-lock* does the same thing as the *View Options/Lock To Tree Root* menu item.  It only makes sense when *View Options/Entire Tree* has been selected.

However, in checking the commands, *vr3-unlock* does not seem to work correctly, at least if the *Lock To Tree Root* menu item has been selected.  I will look into this.

Also, the corresponding item in the *View Options* menu does not check/uncheck when the *vr3-lock/vr3-unlock* commands are issued.  I will look to see whether it will be feasible to check/uncheck the item when these commands are issued.

**Comment by tbpassin** [comment]
Corrected by PR https://github.com/leo-editor/leo-editor/pull/2740.

**Comment by tbpassin** [comment]
@wangzhaohe, does this fix (and the remarks above) satisfy your issue?  Or do you also want a new minibuffer command to freeze the rendering pane (that is, to not show any updates until unfrozen)?

**Comment by wangzhaohe** [comment]
Sorry for my late reply.

Command Tested!

1. vr3-lock works well. (checkbox is corresponding with the menu item.)
2. vr3-unlock works well. (checkbox is corresponding with the menu item.)
3. vr3-lock-unlock-tree works well. (checkbox is corresponding with the menu item.)

Yes. a new minibuffer command to freeze the rendering pane is welcome.

Thanks for your support in time.

Leo Log Window
Leo 6.6.4-devel, devel branch, build 143ad8878e
2022-08-17 21:52:05 +0800
Python 3.9.5, PyQt version 5.15.2
darwin

**Comment by tbpassin** [comment]
PR https://github.com/leo-editor/leo-editor/pull/2771 adds two new commands: *vr3-freeze*/*vr3-unfreeze*.  Once it is merged, this issue can be closed.
