### ISSUE TITLE
Unnecessary dirtying of @<file> nodes when non-@<file> parent nodes are altered.

### ISSUE THREAD

**Issue by JohnLunzer** [leo-editor/leo-editor#274]
See [this discussion](https://groups.google.com/forum/#!topic/leo-editor/ypc2q710ThU) for background.

When a non-@\<file> parent node is _altered_ (without moving it) any @\<file> child nodes are recursively set to dirty. The term _altered_ includes: marking/unmarking, modifying headline/body, and deleting a clone.  Non-@\<file> nodes are **not** set to dirty. The implications of this can be significant.

Example: Using chapters to organize projects and groups of files. Say there are 40 to 50 files under a single chapter. If I want to rename the chapter or add some notes to the @chapter node body I now have to save ~50 files because all of the @\<file> nodes were set to dirty. This seems unnecessary and avoidable. When files are being accessed over a network this can cause a significant delay/disruption.

Example: Leo's code base. If any of the organization nodes under Code, including Code itself are renamed/marked/altered a large number of @\<file> nodes need to be saved. This is not likely to cause much delay/issue in the local environment but again it seems unnecessary and thus should be avoided.

Please note an exception. If a parent @path node or child of an @path node (to support active-path folders) are altered then it is appropriate to recursively set all @\<file> child nodes to dirty.

**Comment by edreamleo** [comment]
I am going to remove the "bug" label from this.  Imo, marking descendant @<file> nodes dirty is the safest course of action, because the changed ancestor node may affect descendant nodes.

This is a debatable point, but I think there are enough reasons for the present operation not to call this an actual bug.  Once could imagine a setting that modifies the present behaviour, but I would rather not do this.  Please reopen if you disagree strongly.

**Comment by JohnLunzer** [comment]
Sorry to resurrect this. After some time with this I agree with you because this case is often an exception. A compromise to this is to use p.clearDirty() on affected nodes. A button/command can easily be added to p.clearDirty() on all nodes in a sub-tree.
