### ISSUE TITLE
extractSectionNames (extract-names) breaks undos if done on an empty line

### ISSUE THREAD

**Issue by boltex** [leo-editor/leo-editor#2747]
The command **extract-names** can create invalid undo beads. Looking at the code, it's because it starts an `u.beforeChangeGroup(current, undoType)`

without necessarily doing an `u.afterChangeGroup(current, undoType)`... (unlike other undo types, groups have to be closed)

I'll fix it by using the same flag 'found' to initialize (_beforeChangeGroup_) the undo group instead of initializing it regardless of found status flag before the loop, and then close (_afterChangeGroup_) it after, and only if it was opened.

eazy peazy

(btw the regular **extract** command works just fine. although personally, i would just issue a warning in the log pane if the selection was completely empty and done on an empty line...instead of just inserting a new node without even a headline nor body... feels like the user accidentally pressed ctrl+shift+d )

**Comment by boltex** [comment]
@edreamleo 

That same problem appears in 4 other places: (where the afterChangeGroup is conditional and not always performed after a beforeChangeGroup)

"go"  method of To_python class in convertCommands.py
"cleanAtCleanFiles" in editFileCommands.py
"pretty_print_tree" in leoBeautify.py
"urlDrop" in qt_frame.py

I could perform the afterChangeGroup non-conditionally in those 4 methods. but i wonder if a group of zero items is ok? if so it's trivial to fix those 4. i'd just want to make sure first by asking about this for those 4 last ones.

**Comment by edreamleo** [comment]
@boltex Thanks for your investigations. Afaik, calling beforeChangeGroup without calling afterChangeGroup should have no effect whatever. Does that help?

**Comment by boltex** [comment]
looking at the code, u.beforeChangeGroup does change the undos by putting it's "to be closed" bead on the bead stack right before returning. 

so by 'should have no effect' do you mean it should not with the actual code, or it should not as an original intended goal, or something else?

**Comment by edreamleo** [comment]
I am going to close this issue. It is my understanding that the fixes have been merged into devel via the felix-server4 branch.
