### ISSUE TITLE
clone-marked/copy-marked/move-marked

### ISSUE THREAD

**Issue by JohnLunzer** [leo-editor/leo-editor#275]
Please see [this thread](https://groups.google.com/forum/#!topic/leo-editor/-mv2x_6TAdM) for prior discussion.

The collection of proposed commands:
- clone-marked
- copy-marked
- move-marked

are intended to help replace/improve the old chapter commands:
- chapter-clone-node-to
- chapter-copy-node-to
- chapter-move-node-to

In addition, they are intended to provide a mechanism for multiple-selection copy/move/clone in general use. 

They would behave as the current single node copy/move/clone commands in terms of node placement. 

Accurate clarifications from Edward:

1. These commands would move the cloned/moved/copied nodes after c.p, the presently selected node.
2. The command would find _all_ marked nodes, regardless of chapter, and would move the nodes after c.p, regardless of what chapter is in effect.

I propose that clone-marked-nodes be depreciated to avoid confusion.

**Comment by edreamleo** [comment]
Rev fed7e2c completes this item.

- Improved clone-marked-nodes and move-marked-nodes.
- Added copy-marked nodes.

These commands work as follows:

- They create an organizer node after c.p. That's not always possible for move-marked-nodes, in which case the organizer node becomes the last top-level node).

- They find all marked nodes, regardless of chapter, and leave the presently selected chapter selected, if possible.
  
**Note**: The move-marked-nodes command is no longer undoable.
- I'll reject any request to make this undoable: it's not going to be safe.
- A dialog warns that the command is undoable.
- The docstring suggests using clone-marked-nodes, followed by copy/paste.
- Moved the undo/redo methods to the attic.
- Modified @test move-marked-nodes so it doesn't check undo/redo.

Added the following new helper methods:

p.copyWithNewVnodes: it just calls v.copyTree.
v.copyTree: a clearer version of p.copyTreeFromSelfTo.

**Comment by JohnLunzer** [comment]
Awesome work. Have been testing and thus far have not run into any bugs/crashes.

Is it necessary to use an organizer node? My concern is that in my test cases the organizer node is cumbersome. To match the original enhancement request I have to perform two extra commands, ```demote``` followed by ```delete-node```, to place the marked nodes after ```c.p```. My intuition is that people using these commands know their outline well and already know where they want the marked nodes to go making an organizer node unnecessary.

If it is possible I would suggest have an @setting ```marked-create-organizer-node```. If disabled the copy/cloned/moved nodes would be placed after ```c.p```. Enabling this by default will match the former clone-marked-nodes behavior (create an organizer node) so as to not break backwards compatibility if that is a concern.

**Comment by edreamleo** [comment]
On Tue, May 3, 2016 at 9:34 AM, John Lunzer <notifications@github.com>
wrote:

> Awesome work. Have been testing and thus far have not run into any
> bugs/crashes.
>
​Thanks.​

​> ​
Is it necessary to use an organizer node?

​Theoretically no.  Practically yes.

Without an organizer node it becomes difficult to undo the command.  It is
also difficult to see at a glace what the command actually did.​

> My concern is that in my test cases the organizer node is cumbersome. To
> match the original enhancement request I have to perform two extra
> commands, demote followed by delete-node, to place the marked nodes after
> c.p. My intuition is that people using these commands know their outline
> well and already know where they want the marked nodes to go making an
> organizer node unnecessary.
>
​Yes, there are use cases where the two extra keystrokes are inconvenient,
but there may be other cases where the organizer node is useful.

> If it is possible I would suggest have an @setting
> <https://github.com/setting> marked-create-organizer-node. If disabled
> the copy/cloned/moved nodes would be placed after c.p. Enabling this by
> default will match the former clone-marked-nodes behavior (create an
> organizer node) so as to not break backwards compatibility if that is a
> concern.
>
​Such a setting is conceivable, but ​it would greatly complicate the code.
I think you are just going to have to live with the present code. The
problems with undo/redo are difficult enough as they are...

EKR

**Comment by JohnLunzer** [comment]
> ​Such a setting is conceivable, but ​it would greatly complicate the code.
I think you are just going to have to live with the present code. The
problems with undo/redo are difficult enough as they are...

> EKR

Understood. I thought there might have been a good practical reason for this decision.

Out of curiousity, I am trying to make ```@command clone-marked-nodes-flat``` here is my body:
```python
c.k.simulateCommand('clone-marked-nodes')
c.k.simulateCommand('demote')
c.k.simulateCommand('delete-node')
```
But it's not working, it keeps deleting the organizer node... there seems to be some delay preventing the organizer node from being selected. I additionally tried to mix in a ```goto-next-visible```  but that deleted the first child node. I tried a straight ```time.sleep(0.1)``` as well but I think that just paused everything. Any help would be appreciated.

**Comment by edreamleo** [comment]
On Tue, May 3, 2016 at 10:25 AM, John Lunzer <notifications@github.com>
wrote:
>
> I am trying to make @command clone-marked-nodes-flat here is my body:
>
> c.k.simulateCommand('clone-marked-nodes')
> c.k.simulateCommand('demote')
> c.k.simulateCommand('delete-node')
>
> But it's not working, it keeps deleting the organizer node...
>
Don't you want promote instead of demote?  If that doesn't work, remember
that you can call the actual commander methods rather than using
simulateCommand.

EKR

**Comment by JohnLunzer** [comment]
Silly me! Promote is what I wanted. Misread my keybinding (my only point of reference).

Here is my final ```clone-marked-nodes-flat``` command:
```python
@language python
if c.p.hasChildren():
    for child in c.p.children():
        if child.isVisible(c):
            c.k.simulateCommand('goto-next-node')
            break
    
c.k.simulateCommand('clone-marked-nodes')
c.k.simulateCommand('promote')
c.k.simulateCommand('delete-node')
```

This mostly matches the described behavior of the original enhancement request, it's not quite a perfect match to mimic the regular copy/cut/paste/clone behavior.
