### ISSUE TITLE
Find Panel Not Searching Entire Outline

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#2753]
The Find panel is no longer searching the entire outline when the *Entire Outline* button is selected.  It acts as if the *Suboutline Only* button is in effect.  *Suboutline Only* and *File Only* seem to be working as intended.
```
Leo 6.6.4-devel, devel branch, build 92f5493b63
2022-08-18 21:42:14 -0500
Python 3.10.4, PyQt version 5.15.2
Windows 10 AMD64 (build 10.0.19043) SP0
```

**Comment by tbpassin** [comment]
It seems that there is no equivalent command to "find-first".  There is only "find-next". So for a search of the entire outline, *find-first* should check to see if this is the first find operation after the search phrase was changed.  If so, the start position should be set to the first visible node of the outline.

**Comment by edreamleo** [comment]
@tbpassin Thanks for your comment.

**Comment by edreamleo** [comment]
@tbpassin The operation of the Find Panel has not likely changed in over a decade. You are correct that the find-next button is stateless. Imo, that is the most intuitive operation, and should not be changed.

The radio buttons are mostly (solely) for use by the cff, find-all and change-all commands.

For these reasons, I am going to close this issue.
