### ISSUE TITLE
Focus lost when I had clicked Enter key in Nav text input

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#276]
after git pull to Leo 5.3-devel, build 20160412153848, Tue Apr 12 15:38:48 CDT 2016,
Focus lost when I had clicked Enter key in Nav text input

**Comment by wangzhaohe** [comment]
Now I found that the focus go into the node tree.
I still like the focus in Nav result panel. With This  I can use keyboard to move items, and if I select one ,then click enter key. If I want go to node tree, then clikt ctrl+t.

**Comment by edreamleo** [comment]
On Wed, Apr 27, 2016 at 11:10 PM, wangzhaohe <notifications@github.com>
wrote:

> after git pull to Leo 5.3-devel, build 20160412153848, Tue Apr 12 15:38:48
> CDT 2016,
> Focus lost when I had clicked Enter key in Nav text input
>

​Thanks for this report. This new problem is likely the result of the
attempted fix of #270. I'll fix this today.

EKR

**Comment by edreamleo** [comment]
The new code considers only QtTabBarWrapper objects to be "unusual".  It's still not clear why such objects should be a problem, but they are.
