### ISSUE TITLE
Fix the MindMapImporter class

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#2760]
I have marked this issue "Won'tFix", meaning that someone else will have to do it. Perhaps I should disable the importer, but I doubt anyone will notice ;-)

A new unit test, TestLeoImport.test_mind_map_importer, shows that the mindmap importer is likely useless. The test has been "rigged" to pass, but the importer appears to ignore most of the data in the file!

**Comment by tbpassin** [comment]
This Github gist might be useful:  [csv_to_mm.py](https://gist.github.com/gpoulter/2350680). It claims to "Convert CSV table to MindMap format".  This is roughly the inverse of the Leo importer but it includes a function `csv_to_tree()` which is pretty close to what the importer has to do.

**Comment by edreamleo** [comment]
@tbpassin Thanks, Thomas. I can use all the help I can get :-)

**Comment by tbpassin** [comment]
I haven't been able to find any examples on line of csv files from a Mindjet program.  That makes it hard to know exactly how to convert one.  I thought the referenced gist might help with that.

**Comment by edreamleo** [comment]
This issue has been assigned 6.6.5. I'll move the importer to the attic unless someone can find a real mindmap file for testing.

Heh. If nobody can supply a mindmap file then probably nobody is using the importer.
