### ISSUE TITLE
CPrettyPrinter class looks buggy

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#2761]
mypy highlights problems with the types of arguments.

- [x] Add unit tests.
- [x] Change 's' to 'list' where the actual type of 's' was List[str].
    These misnamings were the source of my confusion (bad annotations).
- [x] Resolve the types of arguments passed to various methods.

**Comment by tbpassin** [comment]
This bit will be interesting to annotate:

```
    for s in aList:
        self.put_token(s)
    return self.result if toList else ''.join(self.result)
```

Can mypy work with a type `string or list`?

**Comment by tbpassin** [comment]
```
def prev_token(self, s):
    """Return the previous token, ignoring whitespace and comments."""
```

This method actually returns a bool, not a token.

**Comment by edreamleo** [comment]
On Mon, Aug 22, 2022 at 1:57 PM Thomas Passin ***@***.***>
wrote:

> This bit will be interesting to annotate:
>
>     for s in aList:
>         self.put_token(s)
>     return self.result if toList else ''.join(self.result)
>
> Can mypy work with a type string or list?
>
Of course. It's the Union type. In this case, however, the problem here is
trying to understand whether various args should be annotated str or
List[str]. I'll know soon whether the code makes any sense :-)

Edward
