### ISSUE TITLE
tagged node list stops working after node insertion

### ISSUE THREAD

**Issue by tbnorth** [leo-editor/leo-editor#277]
When the tags pane is showing a list of nodes with a particular tag, insert a new node at the top of the outline.  Now, clicking on one of the nodes listed in the tags pane no longer jumps to the node. Probably because stored positions have been invalidated. A work around is to select a different tag, then select the first tag again. Presumably this regenerates the a list of stored positions.

**Comment by edreamleo** [comment]
On Fri, Jul 22, 2016 at 1:31 PM, Jacob Peck <notifications@github.com>
wrote:

> Closed #277 <https://github.com/leo-editor/leo-editor/issues/277> via
> e7ceef8
> <https://github.com/leo-editor/leo-editor/commit/e7ceef8c4b7a9c536813abd06b538b3287923da5>
> .
>

​Thanks, Jake.

Edward
