### ISSUE TITLE
Pascal Importer Fails Badly

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#2776]
On my test file, I found a procedure nested within another, although they should have been separate procedures at the same level.  *end* statements were misplaced. `@others` contents were misplaced or missing altogether.

There is no possible way I could fix the import with a few edits.

```Leo 6.6.4-devel, tbp_vr3 branch, build 118cfca375
2022-08-24 15:02:07 -0400
Python 3.10.4, PyQt version 5.15.2
Windows 10 AMD64 (build 10.0.19043) SP0
```

Another turbopascal file failed to bring in anything at all, with  this stack trace:

```
Exception importing C:/Tom/TP/GSTAT/WORKING/GSTATOBJ.PAS
Traceback (most recent call last):
  File "c:\Tom\git\leo-editor\leo\core\leoImport.py", line 850, in importFilesCommand
    p = self.createOutline(parent=p)
  File "c:\Tom\git\leo-editor\leo\core\leoImport.py", line 672, in createOutline
    func(c, p, s)
  File "c:\Tom\git\leo-editor\leo\plugins\importers\pascal.py", line 61, in do_import
    Pascal_Importer(c).import_from_string(parent, s)
  File "c:\Tom\git\leo-editor\leo\plugins\importers\linescanner.py", line 136, in import_from_string
    self.gen_lines(lines, parent)
  File "c:\Tom\git\leo-editor\leo\plugins\importers\linescanner.py", line 230, in gen_lines
    aList = [self.get_block(i) for i in range(len(lines))]
  File "c:\Tom\git\leo-editor\leo\plugins\importers\linescanner.py", line 230, in <listcomp>
    aList = [self.get_block(i) for i in range(len(lines))]
  File "c:\Tom\git\leo-editor\leo\plugins\importers\linescanner.py", line 356, in get_block
    i = self.new_skip_block(first_body_line)
  File "c:\Tom\git\leo-editor\leo\plugins\importers\linescanner.py", line 543, in new_skip_block
    lws = self.get_int_lws(lines[i + 1])
IndexError: list index out of range
```
This makes me concerned about other importers as well.

**Comment by edreamleo** [comment]
@tbpassin Thanks for this report. 

I am not concerned about other importers. The Pascal importer handles nesting in a unique, hacky, way. Problems with the Pascal importer are unlikely to exist in any other importer.

**Comment by edreamleo** [comment]
@tbpassin Please send me your test file.

**Comment by tbpassin** [comment]
After trying some more files, it may be that most of the problems fall into the category of splitting up procedures in a way that makes it hard to impossible to know if they are right - and really unpleasant to work with - even though when concatenated they may turn out to be all right.

I have attached several example files.  *GSTATOBJ.PAS* is the one that failed entirely with the stack trace I posted above.

(BTW, these files are *very old* (ca 1993). I dug them out to see how I had implemented certain methods.  Back then I wrote modules that were too long, although with Leo they would be fine to work with - once they import better).



[pascal_examples.zip](https://github.com/leo-editor/leo-editor/files/9440130/pascal_examples.zip)

**Comment by edreamleo** [comment]
On Sun, Aug 28, 2022 at 12:20 PM Thomas Passin ***@***.***>
wrote:

> I have attached several example files. *GSTATOBJ.PAS* is the one that
> failed entirely with the stack trace I posted above.
>
Thanks. I'll attempt a fix for #2776
<https://github.com/leo-editor/leo-editor/issues/2776> for Leo 6.6.4.

Edward

**Comment by edreamleo** [comment]
@tbpassin Update:

- A missing guard in Importer.new_skip_block. caused the crash. It's good you caught this.
- Errors detecting begin/end levels cause the improper splitting of nodes. I'm on it.

**Comment by edreamleo** [comment]
@tbpassin All your test files import reasonably. Almost all the work involved improving Pascal_Importer.gen_lines_prepass.
