### ISSUE TITLE
git-diff and git-diff-pr commands don't create undo beads

### ISSUE THREAD

**Issue by boltex** [leo-editor/leo-editor#2777]
They should create beads in the same manner as git-diff-marked nodes which was fixed for the same issue a few days ago.

**Comment by edreamleo** [comment]
@boltex Please set the milestone to 6.6.4 if you want this issue resolved before the next release.

**Comment by edreamleo** [comment]
@boltex Hehe. Never mind. I've see you created a PR.

In future, I would appreciate it if you would set milestones on all issues and PRs. I use those milestones to filter what I see.
