### ISSUE TITLE
Current Devel Branch - Leo not remembering size from last session

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#2792]
```
Leo 6.6.5-devel, devel branch, build 32477f3758
2022-09-01 05:43:22 -0500
Python 3.10.4, PyQt version 5.15.2
Windows 10 AMD64 (build 10.0.19043) SP0
```

**Comment by edreamleo** [comment]
@tbpassin I am going to close this issue. There is another issue (that isn't going to be fixed) suggesting that Leonistas always close their .leo files when switching branches.

In any event, it will be impossible for me to suggest doing anything except clearing the caches.
