### ISSUE TITLE
Leo Replaced My Workbook With The Default Workbook

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#2797]
I just restarted Leo and found that my Workbook.leo outline  had been replaced with the default workbook.  The old one was not saved with a backup name.  I was able to restore it from my own backup.

I'm not sure what led up to this.  I noticed it after I stopped Leo, restored PyQt6 (I had been using PyQt5), and restarted.  But I'm not sure that's when it happened, and I can't see why that would have mattered.  Regardless, Leo should **never** replace Workbook.leo without saving an existing Workbook as a backup.

**Comment by edreamleo** [comment]
@tbpassin Please supply a way to duplicate this behavior.

**Comment by tbpassin** [comment]
[!] So far, it hasn't recurred.  I'll try removing PyQt6 then restoring it as that is the only thing I'm aware of that may - just may - have been going on at about that time.

**Comment by tbpassin** [comment]
I made the change, removing PyQt6, and did some work in Leo.  Then I closed Leo, restored PyQt6, and restarted Leo.  As we would expect, my workbook was unchanged.

Grrr, this leaves us with no real way to make progress.

**Comment by edreamleo** [comment]
@tbpassin I'll leave this issue open while I take a look at the relevant code.

In the meantime, I suggest you add a backup button to your default workbook.  You can do this with an `@button` node containing one line.  Something like:

    c.backup_helper(sub_dir='workbook')

**Comment by tbpassin** [comment]
I have an idea of what might have happened.  I've had a few computer crashes, and sometimes those damage files and sometimes they don't.  I had to restore some Windows files after one of them.  Maybe a crash killed my Workbook.  When Leo couldn't find one, it created a new Workbook.  Is that plausible?

**Comment by edreamleo** [comment]
@tbpassin Thanks for these further comments.

I was already inclined to believe that something like this happened. There have been no other reports of problems with workbooks.

I am going to close this issue. Please reopen if similar problems happen.
