### ISSUE TITLE
c.endEditing is very slow when many nodes are visible

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#2799]
This issue may be related to Thomas's performance issue.  With 1000+ nodes visible, traces show that c.endEditing takes 12 seconds.  Inserting a node (without an explicit call to c.endEditing) is similarly slow.

The performance hit happens all the time, given the right circumstances.

**Status**

- Sherlock traces(!!) reveal that qt_tree.updateAllIcons is called way too often.
- qt_tree.redraw_after_icons_changed is way too slow. qt_tree.updateVisibleIcons is also involved.

**Comment by tbpassin** [comment]
Another thing in this vein I have noticed is that when I opened a large number of new outlines (~50), even though I closed each one soon after opening it, the time it took to open another new outline got longer and longer.  Eventually it got really slow.  It sounds like some long list that had to get searched each time.

This happened many months go, not on the current version.  I bet it hasn't changed, though.

**Comment by edreamleo** [comment]
On Sat, Sep 3, 2022 at 11:26 AM Thomas Passin ***@***.***>
wrote:

> Another thing in this vein I have noticed is that when I opened a large
> number of new outlines (~50), even though I closed each one soon after
> opening it, the time it took to open another new outline got longer and
> longer. Eventually it got really slow. It sounds like some long list that
> had to get searched each time.
>
With modern machines, searching a list will not be noticeable unless the
list has hundreds (more like thousands) of elements. So something else is
the likely culprit.

I'm talking about a O(N) search of the list. An O(N**2) search could indeed
be noticeable.

Edward

**Comment by tbpassin** [comment]
"With modern machines, searching a list will not be noticeable unless the
list has hundreds (more like thousands) of elements. So something else is
the likely culprit."

I have a script that times how long it takes to visit each node.  On my machine, it takes 18 - 19 ms for LeoPyRef.  Not bad at all, IMHO.

**Comment by edreamleo** [comment]
On Mon, Sep 5, 2022 at 10:09 PM Thomas Passin ***@***.***>
wrote:

> "With modern machines, searching a list will not be noticeable unless the
> list has hundreds (more like thousands) of elements. So something else is
> the likely culprit."
>
> I have a script that times how long it takes to visit each node. On my
> machine, it takes 18 - 19 ms for LeoPyRef. Not bad at all, IMHO.
>
Yes. Slowdowns happen because too much might be happening at each node :-)
Event handlers can cause arbitrarily much to happen "invisibly". I
discovered this while investigating #2804
<https://github.com/leo-editor/leo-editor/issues/2804>. Sherlock showed
lots and lots of unexpected calls in unexpected places. Happily, the issue
was a weird settings botch. No code had to change at all.

Edward
