### ISSUE TITLE
@data qt-scintilla-styles only works in leoSetting.leo

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#280]
The initial report said that this setting doesn't work in myLeoSettings.leo.

Not verified yet.  Not sure who submitted this item.

**Comment by tbnorth** [comment]
Might have been Zoom.Quiet, not sure.

**Comment by edreamleo** [comment]
@tbnorth Ok. Thanks.  This may be part of 5.3.

**Comment by edreamleo** [comment]
I am going to close this.  The actual settings mechanism works fine for @data qt-scintilla-styles.  It can be defined in myLeoSettings.leo or the local .leo file.  According to my comments in myLeoSettings.leo, however, the stylesheet may not work properly, no matter where defined.
