### ISSUE TITLE
The viewrendered plugin is not loaded when using PyQt5 version 5.6.0

### ISSUE THREAD

**Issue by ghost** [leo-editor/leo-editor#281]
When launching Leo (commit c8ae22b7ccd5) using PyQt5 v5.6.0, 
the viewerendered plugin is not loaded.
Here is the traceback:

```
leoID=alacnorr (in C:\Users\alacnorr\.leo)
reading settings in C:\leo-editor\leo\config\leoSettings.leo
reading settings in C:\Users\alacnorr\.leo\myLeoSettings.leo
reading settings in C:\Users\alacnorr\.leo\workbook.leo
loadOnePlugin: can not load enabled plugin: leo.plugins.viewrendered

** isPython3: True
Leo 5.3-b1, build 20160412153848, Tue Apr 12 15:38:48 CDT 2016
Git repo info: branch = master, commit = c8ae22b7ccd5
Python 3.5.1, PyQt version 5.6.0
Windows 10 AMD64 (build 10.0.10586) SP0
wrote recent file: C:\Users\alacnorr\.leo\.leoRecentFiles.txt
```

However, when launchingthe same Leo c8ae22b7ccd5 from another python installation 
using PyQt4 the viewrendered plugin is loaded OK; the traceback is:

```
leoID=alacnorr (in C:\Users\alacnorr\.leo)
reading settings in C:\leo-editor\leo\config\leoSettings.leo
reading settings in C:\Users\alacnorr\.leo\myLeoSettings.leo
reading settings in C:\Users\alacnorr\.leo\workbook.leo

** isPython3: True
Leo 5.3-b1, build 20160412153848, Tue Apr 12 15:38:48 CDT 2016
Git repo info: branch = master, commit = c8ae22b7ccd5
Python 3.5.1, PyQt version 4.8.7
Windows 10 AMD64 (build 10.0.10586) SP0
wrote recent file: C:\Users\alacnorr\.leo\.leoRecentFiles.txt
```

**Comment by edreamleo** [comment]
This is almost certainly an installation problem, specifically a failure to import QtWebKitWidgets.

In future, please ask for help at [Leo's Google Forum](https://groups.google.com/forum/#!forum/leo-editor) before posting bug reports.

**Comment by LewisNeal** [comment]
It may well be an installation problem with PyQt5 importing QtWebKitWidgets but it has known effects on 2 plugins, including viewrendered which is a recommended plugin and enabled by default.
Currently the Leo install guide states: "You may download PyQt4 or PyQt5" and does not report this as a 'known' problem with PyQt5.
Would it be better to leave this issue open until it is understood better and maybe document how a Leo user should respond?

Regards
Lewis

**Comment by edreamleo** [comment]
I'll reopen this issue while we sort out the PyQt5 imports.

**Comment by edreamleo** [comment]
From Sami J:

> Lewis,
> I had the same issue and I noticed that QtWebKit and QtWebKitWidgets had not been installed at all by the current Windows installers for PyQt5 5.6.0.
> They are not even packaged in these installers.
> 
> I followed this up on the PyQt mailing list and I was told that QtWebKit had been deprecated upstream in Qt 5.5 and removed in 5.6, so presumably that's why is not available in the PyQt5  Windows installers anymore. I assume this also applies to QtWebKitWidgets.
> 
> If so, this is an issue for all users of the viewrendered plugin who are using PyQt5 version 5.6.0 on Windows. Perhaps viewrendered should be updated to use QtWebEngine (including QtWebEngineWidgets), which is replacing QtWebKit?

EKR: Thanks for these comments. I agree. Something must be done.  I am not amused by Qt's gratuitous changes to imports that will surely break existing code.  It's amateurish and unnecessary.

**Comment by tbnorth** [comment]
On Tue, 03 May 2016 07:22:01 -0700
"Edward K. Ream" <notifications@github.com> wrote:

> I'll reopen this issue while we sort out the PyQt5 imports.

But see Sami's recent comments on the list, looks like it might be a
QtWebKit -> QtWebEngine transition issue, rather than simply import
names.

**Comment by LewisNeal** [comment]
An update which affects resolution of this PyQt5 v5.6 issue:
PyQt5 v5.7 has been released and instructions for installation are at http://pyqt.sourceforge.net/Docs/PyQt5/installation.html
The .exe files are no longer provided. PyQt5 now uses wheel files which apparently are a new standard of python distribution. Read more about them at http://pythonwheels.com/

**Comment by edreamleo** [comment]
I am going to close this, as viewrendered works with PyQt5 on both Ubuntu and Windows 10.  There are many remaining problems with the VR plugin, which I'll discuss in a new issue.
