### ISSUE TITLE
build 361a855723 Error: UnboundLocalError: local variable 'int_insert' referenced before assignment

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#2822]
After `git pull` build 361a855723, clicking a node in edit mode, then press `cmd-a`, the error displayed like below.

Traceback (most recent call last):
  File "/Users/swot/app/leo-editor/leo/core/leoGlobals.py", line 307, in new_cmd_wrapper
    func(self, event=event)
  File "/Users/swot/app/leo-editor/leo/commands/editCommands.py", line 3083, in selectAllText
    w.selectAllText()
  File "/Users/swot/app/leo-editor/leo/plugins/qt_text.py", line 310, in selectAllText
    self.setSelectionRange(0, self.getLength(s))
  File "/Users/swot/app/leo-editor/leo/plugins/qt_text.py", line 459, in setSelectionRange
    if int_insert < int_j:
UnboundLocalError: local variable 'int_insert' referenced before assignment

***
Leo Log Window
Leo 6.7.0-devel, devel branch, build 361a855723
2022-09-07 17:30:54 +0800
Python 3.9.5, PyQt version 5.15.2
darwin

**Comment by tbpassin** [comment]
What branch is that?  I just fetched *devel* at *8db0148764606fd98040920b52d941a70e62784b* and did not encounter your issue.  Also, the code at this line in this commit is a little different from what your stack trace shows:

```
        if insert < j:
            w.setSelection(j, -length)

```

**Comment by spikethehobbitmage** [comment]
@tbpassin You might want to check that again. I'm looking at devel 8db0148 right now and it matches the traceback.

**Comment by spikethehobbitmage** [comment]
@wangzhaohe I'm pushing a pull request for this bug. Please verify if it fixes the issue. Thx.

**Comment by tbpassin** [comment]
Hmmm, that's funny, I fetched this morning's branch, but now my running copy of Leo say it's build *32477f3758*.  

Must be some kind of operator error.

**Comment by tbpassin** [comment]
I've managed to mess up by git index, but anyway, I see that your changes haven't been merged yet.  That's why I didn't see them on *devel*.

**Comment by tbpassin** [comment]
All right, now that I got the right changeset merged and checked out, I repo'd the error.  And the proposed fix makes sense to me and also works.

**Comment by wangzhaohe** [comment]
@spikethehobbitmage @tbpassin 
The bug has been fixed by the change of `insert = int_j` to `int_insert = int_j`. Thanks!

**Comment by edreamleo** [comment]
@spikethehobbitmage The patch looks good.  Please issue a PR.

**Comment by spikethehobbitmage** [comment]
@edreamleo PR #2823 is in the queue.

**Comment by tbpassin** [comment]
Can this issue be closed now?

**Comment by edreamleo** [comment]
@tbpassin Thanks for the reminder. This issue had no milestone (now it does) so the issue didn't show up on my radar.
