### ISSUE TITLE
desktop integration: Register Leo (Windows) fails to elevate

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#2824]
1.  Leo  menu _Settings >> Open desktop integration >> Push [Register-leo] button_

Says it is relaunching with elevated permissions but nothing happens. No further information emitted.

A fix is forthcoming.

_Hi Everyone! Dunno if I'm back but at least I can do this one small thing. :-)_

**Comment by maphew** [comment]
I skipped creating a PR because the fix is small and self contained. Even if there is a problem it's unlikely to impact anything important. I hope that's okay, given that this is a bolt from nowhere! Leaving the issue open as I read that Edward is currently on vacation and it wouldn't be polite to both drive-by-commit and hide it. ;-)

**Comment by tbpassin** [comment]
I checked my Windows registry entry for the _.leo_ class, and I have it as _leo_auto_file_.  I don't remember setting that up, but the _shell/open/command_ entry points to Leo's git directory on my machine, so it must have been me that did it.  It's just that _leo_auto_file_ doesn't seem like the kind of name I would have made up.  Funny...

**Comment by edreamleo** [comment]
Fixed at [806b08c](https://github.com/leo-editor/leo-editor/commit/806b08c9b454ad4653464359bd13813086bf9894)
