### ISSUE TITLE
Dependabot reports vulnerability

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#2847]
GitHub found 1 vulnerability on leo-editor/leo-editor's default branch (1 moderate).

To find out more, visit: https://github.com/leo-editor/leo-editor/security/dependabot/1

I "fixed" this by going to the URL above and disabling the warning.  This security warning affects only the geotag plugin, which doesn't seem to work.

**Comment by tbpassin** [comment]
Doesn't sound very serious.  It uses JQuery. GitHub warned about versions less than 1.6.3 but the current JQuery's version is 3.6.1.

**Comment by edreamleo** [comment]
@tbpassin Thanks for these comments. How should we resolve this issue?

**Comment by tbpassin** [comment]
I think I see what's behind this.  GitHub's Dependabot must use a package file - the one it says is missing - to find out what version of dependencies are being asked for.  pygeotag doesn't have one so Dependabot can't tell if there's a problem or not.

Dependabot can be used to automatically update the required versions of dependencies (presumably specified in that package.json file) so builds can automatically stay up to date.  I found this post about it:

[Keep all your packages up to date with Dependabot](https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/)

**Comment by tbpassin** [comment]
I'd say that for pyleotag there are two possibilities -

1. Leave everything as is, anyone nowadays will be using a newer version of JQuery anyway;
2. Create a new package.json file, specify the version of JQuery in it, and let Dependabot figure out if in case of a new vulnerability the version should be updated.

The second option will take a bit of research to find out exactly what needs to be put into the package.json file, but I suppose it would be the best way to go.  The thing is, someone should become the manager of that package for future followup, and I'm not that person.

It looks like our old friend @tbrown created the package, and @edward updated it at some point.  I wonder if anyone else has ever used it.

**Comment by edreamleo** [comment]
@tbpassin This looks like a "good first JS" issue. I'll try my luck.

**Comment by edreamleo** [comment]
I am going to close this issue. No net changes were made to Leo's core because I reverted all recent changes.
