### ISSUE TITLE
setup.py Contains An Old Version Number

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#2853]
setup.py contains this line at line 131 -

```
version = '6.6.4'  ##version Should match version in leoVersion.py
```

Of course, we are working on 6.7.0, and leoVersion.py contains this -

```
version = '6.7.0-devel'

```

setup.py should probably have the version updated before the 6.7.0 release.

**Comment by edreamleo** [comment]
This kind of mismatch probably doesn't matter. The distribution checklist in leoDist.leo ensures that I update all the version numbers *before* I create a new distro, not *after* I have just created a distro.
