### ISSUE TITLE
LeoSettings.leo no longer contains a list of available  plugins

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#2857]
LeoSettings.leo does not have a commented-out list of available plugins.  It used to be that one copied that list to one's myLeoSettings.leo, then adjusted it to add more plugins.

But today I see that LeoSettings.leo no longer has that list.  That is very inconvenient for users just starting with a new myLeoSettings, since it will be hard for them to learn about plugins that might interest them.

I suggest that the list be restored.  It should be feasible to generate it automatically.

**Comment by edreamleo** [comment]
@tbpassin I agree with you. I was too hasty in removing the comments.

**Comment by edreamleo** [comment]
Fixed at rev bdb4567:

- [x] Lightly curate the list of recommended plugins.
- [x] Omit the list of experimental plugins.

**Comment by tbpassin** [comment]
Thanks!  That will be a big help, especially for newbies.
