### ISSUE TITLE
@rst-preformat directive is formatted into headline

### ISSUE THREAD

**Issue by Sekenre** [leo-editor/leo-editor#286]
Hilariously it depends on which headline is highlighted when running the rst3 command!

Please see the attached files for a worked example. Remember the output of the rst3 command changes based on which headline is selected.

Examples:
* [rst-preformat-test.leo.txt](https://github.com/leo-editor/leo-editor/files/259042/rst-preformat-test.leo.txt)
* [test.html.txt](https://github.com/leo-editor/leo-editor/files/259044/test.html.txt)

**Comment by Sekenre** [comment]
Awesome, thanks!

**Comment by edreamleo** [comment]
On Thu, Sep 22, 2016 at 4:31 AM, Sekenre <notifications@github.com> wrote:

> Awesome, thanks!
>

​You're welcome.  Thanks for the confirmation.

EKR
