### ISSUE TITLE
LeoBridge seems to require QtWebEngineWidgets but runs fine without it

### ISSUE THREAD

**Issue by boltex** [leo-editor/leo-editor#2866]
Starting leoserver (which is just an instance of leoBridge) now prints this message at startup:

```
No Qt6 QtWebEngineWidgets
pip install PyQt6-WebEngine
```

But otherwise works fine. Would it be possible to not try to import this when Leo runs with a null GUI?

**Comment by edreamleo** [comment]
@boltex A reasonable request :-)

**Comment by edreamleo** [comment]
@boltex Fixed via the PR.

**Comment by boltex** [comment]
Great! No more irrelevant 'missing dependancies' messages! This is now the log at leoInteg's startup in the 'log pane' : 
```
Launching server with command: py -3 c:\prog\leo-editor/leo/core/leoserver.py --port 32125

Starting LeoBridge Server 1.0.3 (Launch with -h for help)
LeoServer: init leoBridge in 0.98 sec.
LeoBridge started at localhost on port: 32125.
Ctrl+c to break
server: User Connected, Total: 1, Limit: 1
Leo 6.7.0-devel, devel branch, build 9dcbff603a
2022-09-17 05:55:12 -0500
Python 3.10.7, LeoGui: dummy version
Windows 10 AMD64 (build 10.0.19044) SP0
```

And as you can tell from this log... I'm currently working under windows to make sure the soon-to-be-released leointeg 1.0.8 update works fine on OSes other than linux! :)

Félix

**Comment by edreamleo** [comment]
@boltex Glad to hear everything is working :-)

**Comment by edreamleo** [comment]
@boltex And glad to hear leoInteg 1.0.8 is coming soon!

Leo issue #2870 is turning out to be stubborn. I expect to complete it in a day or so, at which point Leo 6.7.0 will be code complete.
