### ISSUE TITLE
Fix todo.py crashes and (maybe) improve responsiveness

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#2875]
**Original title**: Leo hangs after saving outline.

See PR #2877.

This behavior has started occurring very recently, maybe on today's or yesterday's pull.  Sometimes after I save an outline , Leo appears to hang for a time of maybe 10 - 20 seconds or longer.  Sometimes the hourglass wait icon appears, or appears partway through. Then it resumes.  

This seems to happen only for PyLeoRef.leo, out of five outlines I have tried so far.  I haven't tried on Linux yet.

**Comment by edreamleo** [comment]
@tbpassin Leo works for me, and apparently for everyone else.

Your machine seems to present idiosyncratic problems. I am going to close this issue. I'll reopen if someone else reports similar problems.

**Comment by edreamleo** [comment]
@tbpassin Does running Leo with --no-plugins make a difference? If so, you might be able to find the culprit.

**Comment by tbpassin** [comment]
That was an inspired thought (I won't say "guess").  Yes, turning off plugins eliminated the behavior.  Right away I thought of the todo plugin, since that recently got turned on for LeoPyRef.  

So I enabled the todo plugin on my Workbook outline, and sure enough, the Workbook also showed the problem, though the delays were shorter. De-enabling the plugin restored normal behavior (Leo stalls but just for the sub-second time while the files and outline get written).

This isn't happening on my Linux VM, BTW

**Comment by edreamleo** [comment]
I am reopening this issue. I would like to eliminate the `@redrawer` decorator.

**Comment by edreamleo** [comment]
I am closing this issue. PR #2877 contains some (presumably minor) improvements. As noted in the PR, I see no evidence of big performance problems.
