### ISSUE TITLE
Shortcut defined in myLeoSettings.leo does not override default setting

### ISSUE THREAD

**Issue by Luxoboy** [leo-editor/leo-editor#288]
Hello there,

I'm very frustrated by an issue I don't understand: I cannot override the shortcut for the clone-node command.

I have a very simple myLeoSettings.leo file saved under HOME/.leo, with a node `@settings/@keys/@shortcuts` which contains:
`clone-node = Shift-Ctrl-m`
However, I simply cannot get it too work.
I tried changing the shortcut in the default settings file and it does work.
I can confirm my personal settings file is being read by Leo as it it appears in the log console.

Thanks for any help you can provide.

PS: I'm running latest version from GitHub repo on Ubuntu 16.04.

EDIT: just tried and Windows 10 and it worked. Would be a Linux related issue then.

**Comment by edreamleo** [comment]
Shift-Ctrl-M is equivalent to Shift-Carriage-Return.  Not sure if this special case might cause problems or conflicts with other settings.

In general, when dealing with settings problems, the first place to start is with the print-bindings command.  This will tell you what each key is bound to, and which settings file created the binding.

HTH.  I'll leave this open for now, but you haven't yet convinced me that this is a bug.

**Comment by Luxoboy** [comment]
I have tried other key combinations and none have worked.

I checked the bindings and it does not get printed.

I tried to override another command and it didn't work either.

The fact that I managed to get it working right away on Windows really points toward a Linux-related issue I would think.

**Comment by Luxoboy** [comment]
Update: tried to modify directly the shortcut in the global settings file. It worked straight away (with Ctrl-Shift-M). The issue is specifically about loading settings in myLeoSettings.leo then.

**Comment by edreamleo** [comment]
On Thu, Jun 16, 2016 at 1:35 PM, Anthony Correia <notifications@github.com>
wrote:

> Update: tried to modify directly the shortcut in the global settings file.
> It worked straight away (with Ctrl-Shift-M). The issue is specifically
> about loading settings in myLeoSettings.leo then.
>
​I suspect that Leo is not using the myLeoSettings.leo that you expect.

What is the path to myLeoSettings.leo reported by Leo in the log pane on
startup?

Do you see any entries marked 'M' in the print-bindings command?
​
Edward

**Comment by Luxoboy** [comment]
When launching Leo, here is the trace in the log pane:
`reading settings in /home/anthony/.leo/myLeoSettings.leo`
I can confirm it is the file I put the overriding shortcut in.

There is no entry marked 'M' in the print-bindings command.

Thanks!

**Comment by edreamleo** [comment]
Please send your myLeoSettings.leo file to me at edreamleo@gmail.com  The problem likely lies there.

I am going to close this item for now.  I'll reopen if your myLeoSettings.leo file convinces me that there is a real problem.
