### ISSUE TITLE
typing of get_directives_dict

### ISSUE THREAD

**Issue by boltex** [leo-editor/leo-editor#2895]
g.get_directives_dict has an annotated return value of  `Dict[str, str]`. but near the end of the method this line occurs:

     d["root"] = 0  # value not important

**EKR Notes**:

- I wonder why mypy didn't complain?
- Hah: The code at the end of g.get_directives_dict is a ancient test involving `@root` nodes.
  That code, the g_noweb_root pattern, and the weird "root" kwarg can just disappear,
  which means that the return value of `Dict[str, str]` is accurate.

Good catch!

**Comment by tbpassin** [comment]
Do you think it would be better to change the type to Dict[str, Any], or change the line in question to `d["root"] = ""`?  Or possibly something else?
