### ISSUE TITLE
Show Bindings Command Labels Outline-Specific Bindings Incorrectly

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#2899]
I have some outlines where I define commands in the @settings tree, like this:
```
@settings
    @command show-xxx @key=Ctrl+F7
```
In the *Show Bindings* listing, these key bindings are listed like this:
```
@  button: Ctrl+F7        @command-show-xxx
```
Note that I have not defined buttons for these commands.  I believe they should be listed like this:
```
F   all: Ctrl+F7        show-xxx
```
I think this version would be all right, too, if it's easier to code for:
```
F   all: Ctrl+F7        @command-show-xxx
```

**Comment by edreamleo** [comment]
Partially fixed via PR #2899. I plan no further work on this issue.
