### ISSUE TITLE
Allow selecting and copying from the Nav pane

### ISSUE THREAD

**Issue by SegundoBob** [leo-editor/leo-editor#290]
A few minutes go I used the Nav pane (quicksearch.py) to find all instances of references to an object in my code that I would like to eliminate.  The search results were great.  So great that I needed to think about them and annotate them and use them for hours in revising my code.  I tried everything I could think of to copy the results, but I failed.

In general, Leo-Editor is very good about allowing almost everything that it displays to be selected and copied to the clipboard.

**Comment by tbnorth** [comment]
On Thu, 16 Jun 2016 16:03:25 -0700
SegundoBob <notifications@github.com> wrote:

> A few minutes go I used the Nav pane to find all instances of
> references to an object in my code that I would like to eliminate.
> The search results were great.  So great that I needed to think about
> them and annotate them and use them for hours in revising my code.  I
> tried everything I could think of to copy the results, but I failed.
> 
> In general, Leo-Editor is very good about allowing almost everything
> that it displays to be selected and copied to the clipboard.
> 
> ## **Please allow the contents of the Nav pane to be selected and
> copied to the clipboard.**

I think John Lunzer was working on that most recently, but a regular
copy / paste type operation there might be tricky.  Even if the styling
disguises it, I think that's a list widget, which are not usually
widgets which allow copying of their text, in any context.

Probably easier to add a command "copy results to clipboard", where a
string representing the results could be built at the same time as the
list widget.  Then there's the discoverability problem, maybe there's a
spot to tuck it into the UI.

Ceers -Terry

**Comment by SegundoBob** [comment]
Terry,
I think you are correct that a straightforward select and copy would be difficult or impossible to implement.

The results text that I want is in a QListWidget.

Here is a simple script that can be executed by Ctrl-B to copy the results text to the log pane where it can be selected and copied to the clipboard.  This script also shows that it is not necessary to make an off-display copy of the results text.
```
import PyQt5.QtWidgets as QtWidgets
for widgx in c.frame.nav.findChildren(QtWidgets.QListWidget):
    cnt = widgx.count()
    for idx in range(cnt):
        widgy = widgx.item(idx)
        g.es(widgy.text())
```
Regards,
Bob

**Comment by edreamleo** [comment]
This isn't going to happen.  The QLineEdit already supports all of Leo's bindings.  The results panes is "live": selecting a line selects the corresponding node, which should be enough.
