### ISSUE TITLE
reference one section in multiple external files?

### ISSUE THREAD

**Issue by andrewchenshx** [leo-editor/leo-editor#2909]
hi all,
how can i reference one section in multiple external files?
for every external file which would like to reference the section, should i need to clone the section into the @file tree?

**Comment by tbpassin** [comment]
It depends on what you have in mind.  If all these external files are in the same outline, then yes, you can use a clone (BUT see below).  It is generally not recommended to try to use a clone in one outline in another.  One reason is that if you make a change to the clone in one outline, the other has no way to know about it.  You end up with nodes with the same identifier, that look like clones, but are out of sync.

Reusing clones in multiple external files within one outline can be tricky.  I've tried it but it hasn't worked as well as I hoped.  Here's what I've experienced:

1. If your cloned node has children, you get the entire subtree along with the cloned parent node.  It's easy to forget this, and this can cause confusion later;
2. When you reuse a node like this, it's easy to edit one of the instances and forget that the changes will show up in the other external files too.  These other places may not work right with your changes.

One way I have experimentally used clones in more than one external file and it seemed to work ok was a case where I wanted to work with the code as an @file tree, but I also wanted to be able to produce a sentinel-free file to send to others.  Leo probably has a better solution, but I cloned the entire tree except for the parent node, and put the clone under both the @file and @clean parents (they had different file names).

But that was a weird thing to do ...

**Comment by tbpassin** [comment]
Can we close this issue now?

**Comment by edreamleo** [comment]
@tbpassin Yes.
