### ISSUE TITLE
mod_autosave.py does not always save ; odd visual glitching while saving

### ISSUE THREAD

**Issue by mystica555** [leo-editor/leo-editor#291]
I need autosave because there is no sort of "saved session state" like there is with Sublime 3 / notepad++ / et al.  (The "saved session" is nothing but a window list; it does not contain the contents of any un-saved buffers and any metadata. Please compare to how sublimetext saves a session, where the session file contains the full contents of any unsaved-yet-modified buffers)

(these, you simply open the program the first time, close it, reopen it, and amazingly you get exactly the same content loaded with whatever unsaved changes you made previous to quitting the program.)

Unfortunately autosave does not always work as expected. 

autosave interval is at 59 seconds; once per minute or so, and should not cause -too- many overlaps with the same 59 second interval if i have 2 copies open, and syncthing notices each is saving a version every minute or so. 

I'll have modified something and go into another program; sometimes MANY minutes have passed. 

**autosave has not saved, there is still an asterisk next to my tab name. **

I don't want to keep having to repeatedly press ctrl-s over and over and over to just make sure it saves in case it crashes. That's the exact reason autosave is supposed to autosave!

Further in diagnosing this, i've found what appears to be the cause of another odd visual glitch, "snapping" of the viewport, and perhaps of the cursor (i could swear its messed up cursor positioning while ive been typing, but maybe its just the viewport snapping causing me to say WTF) 

`      2010/11/16: disable autosave unless focus is in the body or Tree.`
`        w = c.get_focus()`
and a bit further down
`        if c.mFileName and c.changed and (isBody or isTree):`
and finally
`         c.set_focus(w,force=True) # 2010/11/16: save & restore focus.`

1: What "problem" was checking the focus supposed to fix that causes the new bug of "won't actually automatically save"
2: Why is the focus being re-set again? Does saving change the focus?

**Comment by mystica555** [comment]
Well, i've confirmed that the focus being set is because it definitely changes focus on saving... 

Is there any way to avoid this at all? Why does the focus have to change?

Removing ' and (isBody or isTree)'  allows for the proper 'always saves' action.

**Comment by mystica555** [comment]
I can explain the visual glitching more, because it finally affected me when I was typing a headline.

If I am modifying the text of a outline headlne, and the autosave happens, my insertion pointer goes away and I am not longer editing the headline.

Somehow this has got to be changed to not snap viewports when saving and not disrupt the insertion pointer _at all_ while autosaving.

**Comment by edreamleo** [comment]
> If I am modifying the text of a outline headlne, and the autosave happens, my insertion pointer goes away and I am not longer editing the headline.

Not sure if it's possible to restore editing in the headline.  It's a tricky special case.  I'll look into it.

**Comment by mystica555** [comment]
To me, an outsider without the long time of knowing the code as you do, I
end up wondering why the save functionality has any sort of GUI updating
done at all.. I'd assume/expect saving to be a background thread with no
side effects on GUI state, whereas a foreground GUI thread would be
entirely separate.

Is this at all possible with the code as it is now?

**Comment by tbnorth** [comment]
On Tue, 05 Jul 2016 07:20:47 -0700
"Edward K. Ream" <notifications@github.com> wrote:

> On Tue, Jul 5, 2016 at 1:32 AM, mystica555 <notifications@github.com>
> wrote:
> 
> > To me, an outsider without the long time of knowing the code as you
> > do, I end up wondering why the save functionality has any sort of
> > GUI updating done at all.
> 
> ​Saving changes icons that have a black border to icons that have a
> grey border.

Good point, analogous to removing the '*' on a file name many apps
(incl. Leo) use to indicate a modified file, but per node.

OP's issue was save (triggered by autosave) knocking focus about.  I
know how tricky some of the focus special cases are - I wonder if the
simplest way to address that might be to skip the icon update for
autosave triggered saves, but still clear the dirty bit on those nodes
so they're displayed correctly on the next user triggered redraw
(selecting a different node, probably, or manual save, etc.).

Meh, now that I see it written down it doesn't seem like that great a
solution, to have the display showing saved nodes as unsaved.

I'm sure you know Qt can tell you want the focused widget is, I used
that recently for something, any chance that can be used to preserve
focus?

Cheers -Terry

**Comment by edreamleo** [comment]
On Tue, Jul 5, 2016 at 9:44 AM, Terry Brown <notifications@github.com>
wrote:

> On Tue, 05 Jul 2016 07:20:47 -0700
>


> Meh, now that I see it written down it doesn't seem like that great a
> solution, to have the display showing saved nodes as unsaved.
>

​I agree.​


I'm sure you know Qt can tell you want the focused widget is, I used
> that recently for something, any chance that can be used to preserve
> focus?
> ​
>

​I alluded to this obliquely in another reply.  It should be possible, but​
 it's not something that is suitable for a student of the Leo Code Academy
:-) I am going to fix this bug next. It's on the list for later today.

Edward

**Comment by mystica555** [comment]
I have at least a related issue with autosave: 
The autosave interval as loaded in the settings, does not repopulate when the setting changes inside an open file, not even when closing and reopening the file.

It seems only a close and relaunch of leo, allows the new autosave interval to be recognised and acted upon.

**Comment by mystica555** [comment]
also can you please change the bit of code that makes certain whether the body is active or not, and simply just save after (interval) as i often edit in leo, have autosave set for 5 seconds to prevent so much typing jitter, and then in all new git codebases without my change, it ends up not saving once im in a router or ssh session to a server.

**Comment by edreamleo** [comment]
Rev 20f012e solves the most pressing problems in a very simple way.  No save is done if focus is in any QLineEdit widget, which includes the minibuffer and all edit widgets.  I think this will suffice for almost everyone.

In addition, the plugin always waits the full "interval" period after an outline is first changed before doing an autosave.  This was not true in the past.  The full delay gives the user a chance to revert any unwanted changes.

The comments about sessions are not relevant to this issue, or indeed to the entire plugin.

Please reopen this only if there are serious problems remaining.

**Comment by edreamleo** [comment]
The time.clock() method is not suitable on my Ubuntu machine.  I'll attempt a fix asap.

**Comment by edreamleo** [comment]
Rev ed36789 fixes the Ubuntu problem by changing time.clock() to time.time().  Works on both Windows and Ubuntu.
