### ISSUE TITLE
Retire cascade-windows and tiling popups

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#2914]
The cascade-windows command has no effect.

Leo Log Window
Leo 6.7.1-devel, devel branch, build 6ae0d35a26
2022-10-15 11:44:47 -0500
Python 3.10.7, PyQt version 6.4.0
Windows 10 AMD64 (build 10.0.19044) SP0

**Comment by edreamleo** [comment]
@LewisNeal Thanks for this report.

I have no idea what this command is supposed to do, and no reason so believe the command *could* do anything useful.

I wonder if the command is a holdover from the old (Leo 5.7?) SDI windows days?

Do you have any insights?

**Comment by tbpassin** [comment]
Here are images of what most Windows programs with an SDI do for "Cascade" and "Tile" commands.  This particular program also has a menu item for opening a clickable list of its open documents.  It also has optional tabs for the documents, and I usually switch using the tabs.

![cascade](https://user-images.githubusercontent.com/36974235/196034761-bfd14b2e-c0df-400f-aa14-fb282101182b.png)
![tiled](https://user-images.githubusercontent.com/36974235/196034769-4b45abf9-1352-4617-88d4-c8b6c84fb9a8.png)

**Comment by edreamleo** [comment]
@tbpassin Thanks for your comments.

My present plan: move the cascade-windows command to the attic.

**Comment by tbpassin** [comment]
A good plan, I think.  Also consider moving those right-click-on-tab commands for "Horizontal Tile" and "Vertical Tile" to the attic as well.  They do the same thing as "Detach" so they are misleading and unnecessary, so far as I can see.

**Comment by edreamleo** [comment]
@tbpassin Thanks for the heads up about the tiling commands.

**Comment by edreamleo** [comment]
Resolved via PR #2915.
