### ISSUE TITLE
Remove tests that merely exclude Qt4 code

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#2919]
We're trying to flush these out, aren't we? Line 33 of _qtFrame.setQtStyle_:

```
if isQt5 or isQt6:
```

**EKR**: A cff reveals 10 instances of this test. This test excludes only Qt4 code, so the pattern:

```
if isQt5 or isQt6:
    << if clause >>
else:
    << then clause >>
```
can be replaced by the "if" clause.
```

**Comment by edreamleo** [comment]
@tbpassin Good catch.

At present, Leo contains many tests on isQt5 and isQt5. But the code you mention only excludes Qt4, so it can be simplified.

**Comment by tbpassin** [comment]
I'd put it in a try/except block to catch changes that Qt7 may bring in.

**Comment by edreamleo** [comment]
@tbpassin Let's wait to see what changes are necessary before complicating the code.
