### ISSUE TITLE
find-all commands collapse outline

### ISSUE THREAD

**Issue by mystica555** [leo-editor/leo-editor#292]
In your "My last lecture. Part 1: Why Leo is noteworthy" post in October, you enthusiastically mention: 
"Leo is a superb browser for code and data. Unlike many other folding editors, Leo remembers which nodes were expanded when you last saved an outline. This is surprisingly important. And Leo's clones let you organize any data as you want, even if all folds are collapsed."

This seems to be implicitly defining a limitation in the ability for the outline to remember which nodes were expanded - it does not remember them during other actions, namely that of "search all".

Instead of my search result being output to the log window, namely anywhere other than the outline view pane, lo and behold, to my utter shock and surprise, all my nodes that I had in a very specific view state, entirely collapsed, and I was presented with a search result -node-.

This seems like a bug to me. 

I expect the search output to -never- change the view state of my treeview...

My biggest problem in life with computers:

MY BRAIN can halt execution of a task, and once it comes back to it, in THE SAME STATE as before, it can continue without problem.

When THE COMPUTER changes its state without my brain understanding why, MY BRAIN cannot "ctrl-z" and it confuses the hell out of me.

**Comment by tbnorth** [comment]
On Thu, 30 Jun 2016 05:14:20 -0700
mystica555 <notifications@github.com> wrote:

> In your "My last lecture. Part 1: Why Leo is noteworthy" post in
> October, you enthusiastically mention: "Leo is a superb browser for
> code and data. Unlike many other folding editors, Leo remembers which
> nodes were expanded when you last saved an outline. This is
> surprisingly important. And Leo's clones let you organize any data as
> you want, even if all folds are collapsed."
> 
> This seems to be implicitly defining a limitation in the ability for
> the outline to remember which nodes were expanded - it does not
> remember them during other actions, namely that of "search all".

Try changing this setting to False

@bool collapse_nodes_during_finds = True

Cheers -Terry

**Comment by edreamleo** [comment]
@tbnorth Thanks for your comment.  I think the find-all and clone-find-all commands probably should temporarily set this setting to False.  I can't think of a use case where collapsing the outline in such situations is useful or expected.

**Comment by edreamleo** [comment]
Imo, no new setting is needed, though one can image a setting that controls collapse for find-all and clone-find-all commands.  In practice though, the existing setting will likely suffice.
