### ISSUE TITLE
Update unit tests for markdown

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#2922]
The recent change to the markdown code causes several unit tests to fail:
```console
FAIL: test_markdown_github_syntax (leo.unittests.test_importers.TestMarkdown)
FAIL: test_markdown_importer_basic (leo.unittests.test_importers.TestMarkdown)
FAIL: test_md_import (leo.unittests.test_importers.TestMarkdown)
```

**Comment by tbpassin** [comment]
I wonder if any common MD processors will not tolerate the extra space after the headline intoducer.  The usual one installed by pip (and so used by VR3) is happy with it.

**Comment by edreamleo** [comment]
@tbpassin Good question. Let's wait for any complaints :-)

**Comment by tbpassin** [comment]
If there are any complaints, we should add a setting to include/exclude the extra space.

**Comment by edreamleo** [comment]
@tbpassin Such a setting would create serious problems. Let's not make work for ourselves now.

**Comment by largo84** [comment]
FYI, as of testing last night it appears the output file from @auto-md works as expected. Thanks for this fix.

**Comment by tbpassin** [comment]
Thanks for letting us know.
