### ISSUE TITLE
Fix crasher in iSearch_helper

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#2938]
In iSearch_helper, the second-to-last line has an error: w is used before being defined at the line:  `c, binding='BackSpace', char='\b', w=w)`

To see the bug, do <Alt+i> and then type a character not in the text:

```console
  File "/home/felix/leo-editor/leo/core/leoFind.py", line 2697, in iSearch_helper
    c, binding='BackSpace', char='\b', w=w)
UnboundLocalError: local variable 'w' referenced before assignment
```

**Comment by tbpassin** [comment]
LeoDocs.Leo says 

"    Alt+S isearch-forward"

Bu that activates the "Search" menu instead.

**Comment by edreamleo** [comment]
@tbpassin Right. Alt-I activates isearch-forward. Fixed in a recent ref.

**Comment by tbpassin** [comment]
Not fixed in devel today so far.  This change appears to work:  

```
c, binding='BackSpace', char='\b', w=c.miniBufferWidget  # was w=w
```

**Comment by edreamleo** [comment]
@tbpassin PR #2939 contains an even simpler fix. It is waiting for comments.
