### ISSUE TITLE
Remove open-offline-tutorial command

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#2945]
The command _load-offline-tutorial_ wants (on Linux) to load the tutorial from SourceForge:

`"Download tutorial (sbooks.chm) from SourceForge?")`

and

`url = "http://prdownloads.sourceforge.net/leo/sbooks.chm?download"`

Do we want to get any Leo info from SourceForge any more?  Is this doc even being kept up-to-date seeing as how it's on SF?

**Comment by edreamleo** [comment]
@tbpassin Another good catch. I'll remove the command.

**Comment by tbpassin** [comment]
Just so you know, I haven't been trolling through the code base looking for obsolete or incorrect code.  I found this one by looking to see where one of the dialogs for which I was trying to fix the styling was used.  I noticed this usage and got curious, that's all.

Just a matter of luck.

**Comment by edreamleo** [comment]
Completed via rev 86730ce.
