### ISSUE TITLE
Tabbed Apps in Leo

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#2948]
Applets in Leo's Log pane are used to do many things - find functions, command and binding lists, and command completion, for example.  Some plugins also make use of tabs in the Log pane.  It may not be widely realized, but it is not hard to put Gui applets into tabs as well.  This informational issue describes how I have been making GUI applets to display in tabs in the Log pane.

 I find these apps convenient because they don't need to take up a whole panel, as Viewrendered/Viewrendered3 do, and they don't even need to be plugins so they can be simpler.  They are mostly intended to be used in a specific outline; their code can reside in the outline.  An applet would be a PyQt _QWidget_ , to be able to work with Leo's Qt infrastructure.

Typically, an app would have a top-level class derived from _QWidget_.  This widget would contain all the visible UI elements, such as tabbed widgets, entry boxes, and the like.  It would normally be initialized with references to Leo's g and c objects. All this code can be placed into an external Python file.

It is not hard to open these apps in  the Log frame, but the details are not obvious.  Since they are not plugins, they don't load automatically when Leo starts.  I don't find that to be a problem, since it's easy to provide a Leo command, button, or menu item to open them when you want to use them.

I open a tabbed app with the following code:

```
def toggle_app_tab(log, tabname, top_widget):
    """Create or remove our app's tab.
   
    ARGUMENTS
    log -- the log panel object for this outline.
    tabname -- a string to use as the display name of our tab.
    top_widget -- an instance of top level QWidget of our app.
    """
    # If our tab is visible, remove it
    if log.contentsDict.get(f'{tabname}-visible', False):
        log.deleteTab(tabname)
        log.contentsDict[f'{tabname}-visible'] = False
    else:
        # Show our tab, reusing our widget if already loaded
        if log.contentsDict.get(f'{tabname}-loaded', False):
            log.createTab(tabname,
                widget = log.contentsDict[f'{tabname}-widget'],
                createText = False)
            log.contentsDict[f'{tabname}-visible'] = True
            log.selectTab(tabname)
        else:
            # Create our tab for the first time
            log.createTab(tabname, widget = w,
                          createText = False)
            log.selectTab(tabname)
            log.contentsDict[f'{tabname}-loaded'] = True
            log.contentsDict[f'{tabname}-visible'] = True
            log.contentsDict[f'{tabname}-widget'] = w

log = c.frame.log
TABNAME = 'The App'  # Change to suit your application
import theApp  # Change to import your own app
w = theApp.MainWidget(g, c)
toggle_app_tab(log, TABNAME, w)
```

By "widget", I mean the app's top-level class, derived from _QWidget_. The widget does not need to have the signature shown here, but it's an obvious way to get Leo's key objects into the app.

Notice that when we "remove" the app - meaning the app's tab is removed from the Log frame - we keep a reference to the main widget.  This way, when we make the tab visible again, the app will have retained all its state and we can pick up where we left off.

Most of my applets are specialized to a particular outline, and they operate only on data in that outline.  For them, I put the above launching code into an _\@command_ node in the outline's _@settings_ tree.  In some cases I have created a local-to-the-outline menu that runs the command, along with some other local commands specialized for the applet.

For a tabbed applet available for all outlines, the code can go into the _@settings_ tree in myLeoSettings.leo.

As an example, here is the start of the top-level _QWidget_ for one of my tabbed applets:

```
class PanelWidget(QWidget):
    """Contains the View and Controller for a browser bookmark viewer.
    
    The Leo tree nodes amount to the Model of a MVC design.
    """

    def __init__(self, g, c):
        """
        ARGUMENTS
        g -- the Leo Global instance
        c -- the Leo commander for the current outline.
        """

        super().__init__()

        self.c = c
        self.g = g
```

**Comment by edreamleo** [comment]
@tbpassin Thanks for this info issue!
