### ISSUE TITLE
Enhancement request: after-headline-edit hook

### ISSUE THREAD

**Issue by gatesphere** [leo-editor/leo-editor#295]
There is no hook for when a headline edit is complete.  There is 'headkey2' but that fires after each keypress, leading to situations where a potentially intensive hook would be fired multiple times in rapid succession, rather than at the end of headline edition.  There are ugly workarounds, but this could be helpful to have.

**Comment by edreamleo** [comment]
On Fri, Jul 22, 2016 at 1:36 PM, Jacob Peck <notifications@github.com>
wrote:

> There is no hook for when a headline edit is complete. There is 'headkey2'
> but that fires after each keypress, leading to situations where a
> potentially intensive hook would be fired multiple times in rapid
> succession, rather than at the end of headline edition. There are ugly
> workarounds, but this could be helpful to have.
>
​I am going to get back to programming today.  I'll look at this first.

EKR

**Comment by edreamleo** [comment]
Fixed at aca8d41. See the checkin log for details.  The main change was adding a 'changed' item to the keys dictionary.
