### ISSUE TITLE
UnicodeDecodeError when typing Unicode characters in body

### ISSUE THREAD

**Issue by digulla** [leo-editor/leo-editor#298]
Leo 5.4-devel, build 20160412153848

Type this in the body

    «»

to get this exception

```
Traceback (most recent call last):
  File "/home/adigulla/packages/leo/leo-editor/leo/plugins/qt_events.py", line 126, in eventFilter
    k.masterKeyHandler(event)
  File "/home/adigulla/packages/leo/leo-editor/leo/core/leoKeys.py", line 3318, in masterKeyHandler
    k.handleUnboundKeys(event, char, stroke)
  File "/home/adigulla/packages/leo/leo-editor/leo/core/leoKeys.py", line 3538, in handleUnboundKeys
    k.masterCommand(event=event, stroke=stroke)
  File "/home/adigulla/packages/leo/leo-editor/leo/core/leoKeys.py", line 3175, in masterCommand
    expanded = c.abbrevCommands.expandAbbrev(event, stroke)
  File "/home/adigulla/packages/leo/leo-editor/leo/commands/abbrevCommands.py", line 252, in expandAbbrev
    word = g.toUnicode(prefix) + ch
UnicodeDecodeError: 'ascii' codec can't decode byte 0xbb in position 0: ordinal not in range(128)
```

Note: On my keyboard, those symbols are on AltGr-X and AltGr-Y. Cut&paste won't work.

**Comment by karstenw** [comment]
On which platform?


On OSX 10.6 with

Leo 5.4-devel, build 20160412153848, Tue Apr 12 15:38:48 CDT 2016
Git repo info: branch = master, commit = 17b8e4d91f22

I can insert (after deactivating alt-q and alt-shift-q shortcuts; that's where those chars are on osx)

«»

and testing further

«»
äöü»„‰¸˝ˇÁÛÛÁÛØ∏°’ÆŒﬂˆıÓÌÏ™ÍÅ‡ÙÇ◊‹›˘˛÷—


without any errors.

**Comment by user-HR** [comment]
I fixed that one by altering the line mentioned in your log:


< word = g.toUnicode(prefix) + ch

> word = g.toUnicode(prefix) + g.toUnicode(ch)


should be fixed in recent versions, just pull and you should be fine


Am 03.08.2016 um 21:28 schrieb digulla:

**Comment by digulla** [comment]
Yes, I can confirm that.

**Comment by edreamleo** [comment]
Thanks to all that contributed to the fix.

I did a cff on the following regex: `toUnicode(.*)\+`

There were only two matches.  One for this bug, another for this line:

```chars = [g.toUnicode(ch) for ch in (string.ascii_letters + string.digits)]```

So it appears this bug won't happen again.
