### ISSUE TITLE
Support --black-sentinels command-line option

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#2983]
See PR #2985.

- [x] Add the `--black-sentinels` command-line option.
- [x] Improve support for blackened sentinels, as a form of defensive programming.

**Rationale**

Leo *cannot* prevent Leonistas from blackening external files *unintentionally*.
Black's *existence* imposes a burden on Leo.

Leo *should not* prevent Leonistas from blackening external files *intentionally*.
`--black-sentinels` avoids huge diffs in projects mandating Black.

Any change to Leo's read/write code is inherently dangerous, but doing nothing may be more dangerous in the long run.

**Note**: Leo will continue to beautify code using orange, not black.

**Comment by tbpassin** [comment]
If Leo is to patch Black, it would be important to know that the patching works as intended.  IOW, to detect if Black's code has changed in an incompatible way.  The easiest way I can think of is to have Black blacken a small snippet - I suppose it would be a sentinel line - and check to make sure it correctly leaves it alone.

The check could be made once per invocation within Leo, and once per command-line invocation.  That shouldn't slow down blackening noticeably.

**Comment by edreamleo** [comment]
>  it would be important to know that the patching works as intended.

I agree. This issue is speculative at present.

**Comment by edreamleo** [comment]
Closed via PR #2985. **Note**: Patching black is out of the question.
