### ISSUE TITLE
g.findRootsWithPredicate is buggy

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#2989]
​Leo subtree:
```console
@path c:/temp/leo
    @file a.py
    @file b.py
```

1. Select the a.py node.  Neither blacken-files nor blacken-files-diff find any file to blacken.
2. Select the @path node.  Blacken-files-diff only finds a.py, not b.py.

The culprit seems to be g.findRootsWithPredicate(c, c.p).  I put a print statement in to verify 1) and 2).

**Comment by edreamleo** [comment]
Yes. Please file a PR. But delete the commented-out old code. The PR will show the diffs more clearly that way.

**Comment by tbpassin** [comment]
Yes; I just left the commented line there so you could see the change more easily when reading my message in the issue's thread.    I'll be removing it for the PR.

**Comment by tbpassin** [comment]
Fixed by PR https://github.com/leo-editor/leo-editor/pull/2994
