### ISSUE TITLE
Leo loads a deleted file

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#299]
A [deleted](https://groups.google.com/forum/?fromgroups#!topic/leo-editor/gYfw-baH0Tc) file say sample.leo is still loaded by Leo via Recent Files>0 sample.leo

Leo is reading ".leoRecentFiles.txt" which has a record of sample.leo and proceeds to create a new file.
Preferred response would be to present a message 'file not found', 'sample,leo not found' or similar. 

Perhaps Leo should delete no-longer-existing files from this list. 
Also consider asking the user for confirmation that a file should be deleted from the list, or write a list of deleted files to the log.

**Comment by LewisNeal** [comment]
The fix works well, thanks Edward.

**Comment by edreamleo** [comment]
On Sat, Sep 17, 2016 at 5:02 AM, LewisNeal <notifications@github.com> wrote:

​> ​
The fix works well, thanks Edward.

​You're welcome. Thanks for the confirmation.

EKR
