### ISSUE TITLE
abbreviation of <h1></h> Missing number 

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#2990]
abbreviation of `<h1></h>` Missing number while input bellow:

`<h1><;;`  then create code `<h1></h>`. The number **1** is missing.

But `<h1>;;` will create the right code bellow:

```html
<h1>
    
</h1>
```

**Comment by edreamleo** [comment]
@wangzhaohe I don't understand this issue. What abbreviation are you talking about?

**Comment by wangzhaohe** [comment]
@edreamleo Would you please confirm whether it is the default `def close_xml()` function?

<img width="999" alt="image" src="https://user-images.githubusercontent.com/2628013/205667485-2236240e-c469-4038-acea-0d273f60b18e.png">

**Comment by edreamleo** [comment]
@wangzhaohe I'll look into this issue.

**Comment by wangzhaohe** [comment]
@edreamleo Perhaps fixing it is not important. Using abbreviation will be ok.

```html
h1;;=<h1>|<>|</h1>
h2;;=<h2>|<>|</h2>
h3;;=<h3>|<>|</h3>
h4;;=<h4>|<>|</h4>
h5;;=<h5>|<>|</h5>
h6;;=<h6>|<>|</h6>
```

**Comment by edreamleo** [comment]
@wangzhaohe Yes, `@data abbreviations-subst-env` does define the `close_xml` function as shown.

However, Leo does not define `h1;;` through `h6;;` abbreviations.

I am going to close this issue--you seem to have a working set of abbreviations.
