### ISSUE TITLE
Create commands to do rope refactoring

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#3000]
Leo might support [Rope's](https://github.com/python-rope/rope) standard refactorings.

**Comment by wangzhaohe** [comment]
I must be a extraordinary function with leo.

**Comment by edreamleo** [comment]
@wangzhaohe It will be a plugin.

**Comment by edreamleo** [comment]
@wangzhaohe The `leo.core.leoRope` module already exists.

I have no memory of this module or what it does.

I am working as a Rope dev now. I am going to postpone this issue.
