### ISSUE TITLE
Changes to Leo Outline From Outside Don't Get Reloaded

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#3002]
While looking at Issue https://github.com/leo-editor/leo-editor/issues/3001, I noticed that when I opened a Leo node in an external editor (not part of an external file) and saved a change, Leo asked if I wanted to reload the node, but after I clicked "Yes", no change was made.

This happens with the modified code for the dialog that I tried out in the linked issue.

I assume the intended behavior is to change the affected node, and if so this would be a bug.

**Comment by edreamleo** [comment]
@tbpassin The code is working as expected. Did you perhaps make a change that did not actually change the outline?

**Comment by tbpassin** [comment]
I'll try it again.

**Comment by edreamleo** [comment]
@tbpassin Perhaps the fix in PR #3013 indirectly fixed this issue.

**Comment by tbpassin** [comment]
It seems to be working right no, whatever the reason.  I opened a node in the external editor and the node body in Leo picked up my changes as intended.  I tried it both in Windows and Linux, and it worked in both.

So hurray! The issue can remain closed.

**Comment by edreamleo** [comment]
@tbpassin Hurray! Thanks for the investigation.
