### ISSUE TITLE
Use postponed annotations

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#3003]
[PEP 563](https://peps.python.org/pep-0563/) (Postponed Evaluation of Annotations) allows for simpler annotations and better pyflakes checks.

See PR #3004.

**Comment by edreamleo** [comment]
@tbpassin Good catch! I was under the mistaken impression that the PEP had been accepted. So for now I'll leave Leo's annotations alone.

I agree that it makes sense to chance Leo's code only when the PEP has been accepted.

**Comment by edreamleo** [comment]
I have just changed the milestone to "Later" :-)

**Comment by tbpassin** [comment]
I think that the PEP has been "accepted", but it still has to be activated using `from __futures__ import`.  That is, it's not default behavior yet.  The alternative PEP is not there yet but seems will have some real advantages once it gets finalized.

**Comment by edreamleo** [comment]
@tbpassin Ah. I see. I didn't realize there are two PEPs involved. So it looks like it would make sense to play with PEP 563 after all.

**Comment by edreamleo** [comment]
Closed via PR #3004.
