### ISSUE TITLE
leoscripts.leo contains all its scripts in an @file leoScripts.txt text file - is that OK?

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#3015]
All of the scripts in leoscripts.leo are contained in a single text file: `@file leoScripts.txt`.  That seems strange to me.  Why is there such a file?  The text file contains leo sentinels, since it is an _@file_ node.  

I imagine there was some apparently good reason behind this choice at some time in the past, but it's not apparent to me.  Shouldn't the scripts just be in an ordinary organizer node?  What is the value in having them saved outside the Leo outline in a .txt file that contains sentinels?

**Comment by edreamleo** [comment]
@tbpassin Hmm. It's a fair question. I don't recall why I thought the `.txt` file was a good idea. It may have had something to do with reducing git diffs...

**Comment by edreamleo** [comment]
@tbpassin We can leave scripts.leo as it is :-)
