### ISSUE TITLE
Undo Should Restore Clean State

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#3023]
When undoing an operation, if an outline was in a clean state before the operation, then it should be in a clean state after undoing that operation.  Currently undoing an operation will not clear the dirty state if the state was clean before the undone operation.

**Comment by edreamleo** [comment]
@tbpassin This proposal has a long history and would be difficult or impossible to do cleanly.

I am willing to consider a PR, but I don't think it's worth the effort and there is no guarantee that I would accept the PR.

**Comment by tbpassin** [comment]
I'm not surprised.  I was thinking about possible changes that wouldn't invoke undo, like setting marks, but should cause the outline to be marked dirty, and whether they could be taken into account.  I haven't done much with undo do date so I'm not familiar with all the ins and outs, and I hoped someone else would know more.

I'm willing to close this one without action, but would like to think about it for a few days first.

**Comment by tbpassin** [comment]
I'm going to close this one.  There are probably too many special cases to track down and handle, and better to be on the safe side.  If it were only the body editing functions involved that might be practical.  Maybe I will revisit the subject some time.

**Comment by edreamleo** [comment]
@tbpassin I agree with your choice :-)
