### ISSUE TITLE
Remove pylint warning from VR3

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#3025]
@tbpassin Please fix or suppress this warning.
```console
************* Module leo.plugins.viewrendered3
leo\plugins\viewrendered3.py:1248:11: W1510: Using subprocess.run without explicitly set `check` is not recommended. (subprocess-run-check)
```
Environment:
```console
pylint 2.14.4
Python 3.10.5...MSC v.1929 64 bit (AMD64)
```

**Comment by tbpassin** [comment]
Sure.  I knew it wasn't doing a check could elicit a message but I didn't think a check was actually needed here.  I'll review it and take care or it.

**Comment by tbpassin** [comment]
Fixed in PR https://github.com/leo-editor/leo-editor/pull/3026.

**Comment by tbpassin** [comment]
Fixed with https://github.com/leo-editor/leo-editor/pull/3026
