### ISSUE TITLE
cfam and cffm clear marked bits (unmark all nodes) in an non-undoable way.

### ISSUE THREAD

**Issue by boltex** [leo-editor/leo-editor#3028]
The clearing happens in do_find_marked.

~~I propose that the clearing should be done instead in cloneFindByPredicate,~~  ~~(if the predicate is 'isMarked', or with an additional named parameter: clearMarked)~~ by also having, of course, the undo type be changed to an 'undo-group' containing the regular undo bead of the clone-find 'action' and all the 'unMark' beads. So as to undo as one single step.

**Comment by boltex** [comment]
On second thought, maybe the undo group can be do_find_marked in fact. This would make the modification cleaned.

**Comment by edreamleo** [comment]
@boltex Thanks for this. Are you going to submit a PR?

**Comment by boltex** [comment]
@edreamleo Yep, in the next few days.  :)

**Comment by edreamleo** [comment]
Closed via PR #3033.
