### ISSUE TITLE
Support @string rst3-action

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#3038]
See PR #3052.

A **dirty @rst tree** is a tree whose corresponding intermediate or html file would change if it were written.

- [x] Support `@string rst3-action`, whose valid values are:
   'none': (the default) take no extra action.
   'clone': clone all dirty `@rst` trees into an organizer node.
   'mark': mark all dirty `@rst` trees.
- [x] Add g.write_file_if_changed.
- [x] Detect dirty `@rst` trees without help from `git diff`.

**Comment by tbpassin** [comment]
I don't see this as a real issue.  Writing those intermediate files takes place in a flash, and updating the web site is or could be done by a batch process that just uploads all the new files, changed or not.

The only part I don't like is that Sphinx puts some files and even directories into the output tree that don't belong on the web site (like _objects.inv_ and _.doctrees_).  `@rst` can't do anything about that.

IOW, I don't think the benefits would be worth the work :)

**Comment by edreamleo** [comment]
@tbpassin Thanks for your comments. You're probably correct, but I would like to have a closer look.

**Comment by edreamleo** [comment]
@tbpassin Now I remember what I really want :-) I'd like the rst3 command to mark (or clone?) changed `@rst` trees. I think that *would* be useful.

**Comment by tbpassin** [comment]
I would favor marking, not cloning.  Cloning can be really annoying if you are not expecting it.

There is a practical problem with marking, though.  The user might have already marked other nodes.  There would be no way to know which were marked by `rst3` and which were not (aside from being in an `@rst` tree).

**Comment by edreamleo** [comment]
@tbpassin I have given this issue a new title and purpose based on your comments.

**Comment by tbpassin** [comment]
Marking the tree as dirty sounds good.

**Comment by edreamleo** [comment]
@tbpassin I'm not sure which of the three commands will be the most useful. The trick will be discovering the dirty `@rst` nodes. At present there is no mechanism for remembering the previous contents of intermediate (or final) files.

**Comment by edreamleo** [comment]
Closed via PR #3052.
