### ISSUE TITLE
Dragging a File Into A Leo Tree Should Import With "/", Not "\", In @file Headline

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#3039]
See PR #3054.

On Windows, importing a file using the File/"Import Any File" menu item inserts backslashes into the @file path.  These work, but as I understand it, the @path and @file paths are really intended to use forward slashes on all platforms.  Also, with backslashes I am pretty sure they won't work in unl navigation (e.g., by CTRL-clicking).

I suggest that the importers always insert slashes into the headlines, even on Windows.

[Later] - it turns out that the "Import Any File" does insert slashes.  I got the back slashes when I dragged a file from Windows Explorer directly into a Leo tree.  I'm going to change the title of this issue.

**Comment by tbpassin** [comment]
All right, I'll take a look.  It seems like it should be easy enough, once I find the right part of the code - which might be the hardest part.

**Comment by edreamleo** [comment]
@tbpassin Thanks. Feel free to ask for help, but I don't think you will need to do that :-)

**Comment by edreamleo** [comment]
Closed via PR #3054.
