### ISSUE TITLE
In leoFind.py, the 'change' method lacks a call to init_ivars_from_settings

### ISSUE THREAD

**Issue by boltex** [leo-editor/leo-editor#3040]
To test this lack of settings being applied before the actual 'replace' is performed: select some text in the body pane, focus in the 'replace' field of the find panel, type a few letters and hit CTRL+'='. 

The 'replace: empty find pattern' log message is given. 

Any other find related command (like ctrl+'-' ,(replace then find) and other find commands in leoFind.py do call **init_ivars_from_settings** and therefore the settings are reflected in the 'replace' operation. )

**Comment by edreamleo** [comment]
Thanks for this.

**Comment by edreamleo** [comment]
Closed via PR #3048.
