### ISSUE TITLE
vr3 panel using asciidoc create one redundant blank line within code source block

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#3042]
Write the following code in body panel with asciidoc.

```javascript
@language javascript
console.log("Hello World!");
```

There is a redundant blank line after command vr3 run.

<img width="504" alt="image" src="https://user-images.githubusercontent.com/2628013/211719484-15063998-fa0f-4bab-ba23-37454d97b8d7.png">

***

This phenomenon is not very important while only have a little more vr3 panel space.

With some ipdb debug, I found the code is in viewrended3.py (line 4870, 4910 and  4912).

```python
self.text_lines = ['']  # The text as a sequence of lines, free of directives
...
_formatted.extend(self.text_lines)  # ['[source,javascript]', '----', '', 'console.log("Hello World!");', '----']
...
self.formatted = '\n'.join(_formatted)  # '[source,javascript]\n----\n\nconsole.log("Hello World!");\n----' double \n
```

The blank line will disappear if self.text_lines = [].

@tbpassin Please confirm the '' in self.text_lines is necessary when init self.text_lines.

**Comment by tbpassin** [comment]
Hmm, I don't see that extra line using asciidoc.  I'll check using asciidoctor tomorrow (it's very late here in the U.S right now).  

You can see the exact asciidoc markup that VR3 generates with the `vr3-open-markup-in-editor` command, no need for a debugger.

**Comment by wangzhaohe** [comment]
With some extra supplement bellow.

vr3_adoc.adoc content: A blank line is bellow the source block delimiter `----`

```
:source-highlighter: pygments

== newHeadline
[source,javascript]
----

console.log("Hello World!");
----
```

> The command `vr3-open-markup-in-editor` create the same content with the vr3_adoc.adoc file.

**Comment by tbpassin** [comment]
"The blank line will disappear if self.text_lines = []" . I agree - I tried it too.  I will have to try it with an empty page, and also with the asciidoc processor.  If all is well, as I suppose it will be, I will submit a PR for the change.

**Comment by wangzhaohe** [comment]
```
@doc
A little complicated example:

[source,python,linenums,highlight=2]
----
@c
@language python
print("line1"); #<.>
print("line2");
print("line3");

@language asciidoc
@doc
----

- Above is with [red]#self.text_lines = ['']# by vr3 presentation

<.> The highlight number position is here, for the reason of the first blank line.

IMPORTANT: highlight=2 is set


- Run command `adoc`, the result is bellow
+
image::img/adocCreated.png[,300,role=thumb]


- Some explanation
  * @language python -> wanting the code in body panel looks more nice.
  * @language python -> will decide the comment delimiter if saved by @file node if it is the first @language line.

***
*So if `self.text_lines = ['']`, then the vr3 presentation is inconformity with the adoc result.*
```

<img width="854" alt="image" src="https://user-images.githubusercontent.com/2628013/212535785-995ca702-8440-4d11-bf38-f45b0b32df1b.png">
