### ISSUE TITLE
Support gnx's containing UUIDs or KSUIDs

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#3047]
See PR #3053.

- [x] Add `@string gxn-kind = none` to leoSettings.leo.
- [x] Support `@string gxn-kind`:
    - none: (The default) Use Leo's legacy format: <self.userId>.<timestamp>.<unique number withing timestamp>
    - uuid: Use uuid format: See https://docs.python.org/3/library/uuid.html
    - ksuid: Use KSUID format. Requires `pip install ksuid`

**Notes**
- Leo will generate a legacy gnx if the ksuid module does not exist.
- This PR is a newer version of PR #2843.

**Compatibility Notes from PR #2843**

Existing vnodes are not affected by this option, and both timestamp and UUID based gnx strings may safely coexist in the same document.

Older versions of Leo (as far back as 4.1 when the current gnx format was introduced) can read and write such files without difficulty and will simply ignore the new setting. The only impact is to the todo plugin, which will be unable to determine when a UUID node was created. It handles this situation gracefully but the "sort by creation date" feature won't work with UUID nodes.

User written code that depends on the format of gnx strings may misbehave if used with this feature, but code that treats gnx strings as blind data should be unaffected.

UUID based gnx is slightly less version control friendly than timestamp based since newly created nodes will be distributed at random instead of as contiguous blocks, but UUIDs are sort-stable so spurious changes will still be avoided.

**Comment by kghenderson** [comment]
This should be a major improvement. Ideally we'd also have: 
1. a customizable gnx-generation function (e.g. for sortable KSUID's over UUID's or similar) 
2. a way to alias a node so that when the file is being imported the gnx could be `abc123` but the region could be named `some-function-name` and map to that node (e.g. via a unique attribute) - this is how a number of literate programming tools work, by naming markdown blocks/cells.

**Comment by edreamleo** [comment]
@kghenderson Do you feel up to creating a new PR?

**Comment by boltex** [comment]
@kghenderson @edreamleo I'll gladly port this to leojs too when it's done :)

**Comment by edreamleo** [comment]
@boltex Good to know you approve.

**Comment by edreamleo** [comment]
Closed via PR #3053.

@boltex This issue is complete. Have at it :-)

**Comment by edreamleo** [comment]
@kghenderson Previously you said:

QQQ
Ideally we'd also have: 
1. a customizable gnx-generation function (e.g. for sortable KSUID's over UUID's or similar) 
2. a way to alias a node so that when the file is being imported the gnx could be `abc123` but the region could be named `some-function-name` and map to that node (e.g. via a unique attribute)
   this is how a number of literate programming tools work, by naming markdown blocks/cells.

QQQ

I'd rather not do item 1.
I have no idea what item 2 means :-)

Item 2 should be a separate issue. I won't consider it unless you provided more info about why it's important.

**Comment by vitalije** [comment]
I don't know how new gnx are generated when using UUID or KSUID, but inside the function that generates new gnx, one line can be added to store creation time in the c.db. For example:

```python
def new_gnx(kind):
    ... somehow create new gnx value
    # now before returning new gnx, store its creation time
    c.db[gnx] = { 'created_at': datetime.now() }
    return gnx

def created_at(c, gnx):
    return c.db.get(gnx, dict()).get('created_at')
```

One can later retrieve the gnx creation time, even perhaps some other interesting values.

Alternatively, todo plugin may monkey patch this method and store the creation time on its own.

Just my 2c

**Comment by edreamleo** [comment]
@vitalije Thanks for these comments. It's good to know you are still checking in.

**Comment by boltex** [comment]
@kghenderson @edreamleo @vitalije This feature is now part of LeoJS in tonight's beta 0.2.8 release! 😄 
( and also works on vscode on the web ! )
