### ISSUE TITLE
beautify-files-diff command should not enclose each printed line with "'" characters

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#3065]
The printed output from the new _beautify-files-diff_ command encloses each line with single quote signs.  This adds clutter to the printout and makes it hard to know when a line ends with a single quote whether that character is in the code or has been added.

Example:
```
  '-      "calls/second for %s reps on %s" % (reps,host))\n'
  '+      "calls/second for %s reps on %s" % (reps, host),\n'
  '+)\n'
```
In this example, it is very hard to assess whether the proposed changes would be correct (or desired) code or not.  Without the quotes, it's easier to grasp:

```
  -      "calls/second for %s reps on %s" % (reps,host))\n
  +      "calls/second for %s reps on %s" % (reps, host),\n
  +)\n
```

**Comment by edreamleo** [comment]
@tbpassin Thanks for raising these issues.

In fact, the `beautify-files`, `blacken-files`, and `fstringify-files` commands *only* work with external files. This happened ages ago, but never got documented.

There is no need to make these commands undoable: that's what `git checkout` is for :-) Similarly, `git diff`, *including* Leo's `git-diff` command, already show what has been changed.

**To do**

- Remove the `beautify-files-diff`, `blacken-files-diff`, and `fstringify-files-diff` commands.
- Update the corresponding docs, per #3064.

I'll leave open the various issues relating to `beautify-files-diff` until we have had a chance to discuss them thoroughly.

**Comment by edreamleo** [comment]
~~I'll leave open the issues relating to `*-files-diff` until we have discussed them thoroughly.~~

On second thought, I have closed them all. Feel free to comment :-)

**Comment by tbpassin** [comment]
I respectfully disagree with your line of thought about undoable-ness and diffs because I have many external files and Leo outlines that are not in git and never will be.  Some of them are in my own on-disk Mercurial repo, and some of them only get backed up to a backup drive.  There are of course historical reasons for this, but the situation isn't going to change anytime soon if ever.

I'm sure I'm not the only one!

Currently my git repo only contains projects I have on GitHub.  I could start including other projects that are not on GitHub for future work, but that won't help with everything.  Besides, I am thinking of, e.g., scripts and other code that I am developing in workbook.leo, which I don't keep in git.

**Comment by edreamleo** [comment]
@gatesphere @tbpassin

Sure. Everything should always be undoable, but these commands have not been undoable previously and there is no obvious way to make them undoable now.

I might not accept a PR that supposedly made these commands undoable. The PR would require (complex!) code to translate diffs from the external file back into the Leo outline. Kinda like `@clean`. A buggy undo would be worse than no undo at all.

Only devs will likely use these commands. They are responsible if they don't use a SCCS.

**Summary**

This is what comes of talking about an improved command&mdash;people want more, more, more :-)

I'll accept the theoretical argument that these commands need an undo, but I have no plans to make them so.

In the meantime, `git diff`, `git checkout` and Leo's `git-diff` command are adequate workarounds.
