### ISSUE TITLE
beautify-files-diff should put results into a new node instead of printing to terminal

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#3066]
For external files that are much longer than one screen, the _beautify-files-diff_ output in the terminal is very hard to read or work with.  I suggest it would be better if put into a new node or subtree, as some other commands do.

**Comment by edreamleo** [comment]
@tbpassin I am closing this issue per [this comment](https://github.com/leo-editor/leo-editor/issues/3065#issuecomment-1385900092). Leo's git-diff command is already superior to this suggestion.
