### ISSUE TITLE
There should be a beautify-subtree command

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#3068]
The new _beautify-xx_ commands do not include one to beautify a subtree that is not an external file. I would like there to be such a command.  The _beautify-c_ command can operate on a subtree but it is specialized to the C language.

The main use for the proposed command would be to beautify lengthy Leo scripts and commands.

**Comment by edreamleo** [comment]
@tbpassin I am closing this issue per [this comment](https://github.com/leo-editor/leo-editor/issues/3065#issuecomment-1385900092). Leo's `beautify-file` command works on external files. This command is neither undoable nor adaptable to work on subtrees.
