### ISSUE TITLE
New Startup Exception

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#3074]
After updating the to current changeset in devel, I started getting a new error on startup:

```
C:\Users\tom>py-leo-git --theme=tbp_dark %userprofile%\.leo\workbook.leo
Using PYTHONPATH: ;c:\Tom\git\leo-editor

Leo 6.7.2-devel, devel branch, build 1f74c18d50
2023-01-20 09:26:19 -0600
Python 3.10.9, PyQt version 6.4.1
Windows 10 AMD64 (build 10.0.19044) SP0

Uncaught exception in Leo...
Traceback (most recent call last):
  File "c:\Tom\git\leo-editor\leo\plugins\qt_text.py", line 977, in paintEvent
    if w == c.frame.body.widget and \
AttributeError: 'NoneType' object has no attribute 'widget'
```

Leo continues to start up and work, but this is a change.  At the same time, during startup when the session will have many open outlines, parts of Leo panes flash on and off in unusual locations compared with previous versions, where by and large the Leo window was blocked from painting until all outlines were loaded.

**Comment by edreamleo** [comment]
On Fri, Jan 20, 2023 at 10:59 AM Thomas Passin ***@***.***>
wrote:

> After updating the to current changeset in devel, I started getting a new
> error on startup:
>
> C:\Users\tom>py-leo-git --theme=tbp_dark %userprofile%\.leo\workbook.leo
> Using PYTHONPATH: ;c:\Tom\git\leo-editor
>
> Leo 6.7.2-devel, devel branch, build 1f74c18d50
> 2023-01-20 09:26:19 -0600
> Python 3.10.9, PyQt version 6.4.1
> Windows 10 AMD64 (build 10.0.19044) SP0
>
> Uncaught exception in Leo...
> Traceback (most recent call last):
>   File "c:\Tom\git\leo-editor\leo\plugins\qt_text.py", line 977, in paintEvent
>     if w == c.frame.body.widget and \
> AttributeError: 'NoneType' object has no attribute 'widget'
>
> git blame says you are responsible for lines 977 through 1013:

e76b72d197 (tbpassin       2022-04-24 11:19:34 -0400  977)

So this is a long-standing issue, having nothing to do with "the current
changeset", whatever that is supposed to mean.

Please handle this.  Thanks.

Edward

**Comment by tbpassin** [comment]
I don't recall seeing the error message before.  Perhaps I just didn't notice until now ... Okay, I'll check it out.

**Comment by tbpassin** [comment]
This is very weird.  I only see the exception when I use `--theme=` and then only when I ask for one of my older themes, _tbp_dark_.

I don't understand, but I put in a guard to make sure the widget exists.  This cleared up the exception.  PR coming up.

**Comment by tbpassin** [comment]
Fixed by https://github.com/leo-editor/leo-editor/pull/3082.
