### ISSUE TITLE
Missing re-leo.cmd script

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#3085]
I've seeing a startup error for some time:

`not found: C:/Tom/git/leo-editor/leo/scripts/re-leo.cmd`

There is an `@clean` subtree in LeoPyRef.leo for this file, but it's not in my clone of the repo.  Was it removed intentionally?  Its body contents seem to be very specific to one person's hard drive setup:

```
@language batch
echo off
cd c:\Repos\leo-editor
reindent leo

```

If it was removed intentionally,  we should remove the subtree in LeoPyRef.leo.  I didn't want to do this without checking with others first.

If it was not removed intentionally, it needs to get regenerated.  That can be done by adding a space to the outline, saving, and removing the space. This will force Leo to re-create the external file.

**Comment by edreamleo** [comment]
@tbpassin Thanks for this report. I'll fix it soon.

**Comment by edreamleo** [comment]
@tbpassin re-leo.cmd has been renamed reindent.leo.cmd.  I'll update LeoPyRef.leo.
