### ISSUE TITLE
Display Leo's New Splash Screen With SVG Renderer

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#3089]
See PR #3091.

The new SVG splashscreen is being rendered as a pixmap instead of an SVG rendered image. The splash screen looks pixelated and too big on my HD monitor.  

It should be rendered using the [QSvgRenderer](https://doc.qt.io/qt-6/qsvgrenderer.html) instead.  Also, since it is a vector image it should be feasible to scale it to the screen size rather than to a fixed size (currently 600 px).

**Comment by edreamleo** [comment]
@tbpassin Thanks for this report. I'll see what I can do.

I did investigate QSvgRenderer yesterday, but I got sidetracked and then forgot all about it.
