### ISSUE TITLE
Find operations that 'mark' nodes of found or replaced instances should produce undo beads that also undo the marks.

### ISSUE THREAD

**Issue by boltex** [leo-editor/leo-editor#3100]
For find/replace/find all/replace all commands

If the 'mark finds/mark changes'  options are checked, then the commands should make undo beads that effectively revert the marks properly. 

A little bit of if/then logic might be needed:
 - make undo groups if it changes AND marks the node (otherwise the simple 'body-change undo' already in place is ok)
 - an instance may stay marked if it was already marked before the find / match, 
 - etc...

I'll gladly make a fix and a PR for this once the find-all command is fixed with PR #3099

**Comment by edreamleo** [comment]
@boltex I'm looking forward to your PR :-)

**Comment by boltex** [comment]
@edreamleo I fixed for the usual find/replace operations on the https://github.com/leo-editor/leo-editor/tree/boltex/issue3100 branch.

 But i noticed that the '-all' commands (find-all, replace-all) do not even currently honor the "Mark Finds" / "Mark Changes" checkboxes. 

Is this intended? (If not I'll fix this too while I'm at it)

**Comment by edreamleo** [comment]
@boltex I can't speak to ancient intentions. There would seem to be no harm in honoring mark find/changes for find-all/replace-all. So please go ahead if you like. If not, nobody will notice :-)

**Comment by edreamleo** [comment]
Closed via PR #3123.
