### ISSUE TITLE
Command "preview-tree-nodes" Blocks Leo If Printer Off

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#3105]
Trying out the "preview-tree-nodes" command to see what it does, Leo hung.  Also, when I look at the code for the command, it includes
```def preview_doc(self, doc: Any) -> None:
    """Preview the document."""
    # pylint: disable=no-member
    dialog = printsupport.QPrintPreviewDialog()
    dialog.setSizeGripEnabled(True)
    dialog.paintRequested.connect(doc.print)
    dialog.exec_()
```
Isn't `.exec_()` for PyQt5 and `.exec()` for PyQt6?

Not tried, but there are other commands in this family of commands that probably should be checked too.

**Comment by tbpassin** [comment]
This command opens a "Print Preview" printer dialog.  The hang happened when my printer was turned off.  When the printer is turned on, the preview comes up in a fairly short time.  (I normally have my printer turned off).

I will look around and see if it's feasible to check whether a printer is connected or not.

**Comment by tbpassin** [comment]
The problem is that there is no way (at least, with Qt) to check if the printer is connected except by trying to send it a command.  If it's not on, there is a very long time out, in the minutes range.  Eventually the wait will reach the time out and Leo will unhang, but it is a very long time on my Windows system.

At the moment, it seems to me that the only way around this would be to start a thread to try to communicate with the printer.  We'd have to set an idle time hook to check on completion, and a callback to complete the preview dialog if the thread returned quickly. Then the idle time hook would be removed.

It's seems doable, but it's a lot of machinery for a small task.

**Comment by tbpassin** [comment]
Here is an interesting wrinkle.  Apparently the preview is made by the printer driver, not the actual printer.  Once the initial time out has occurred, even though the printer is turned off, the preview dialog will display without a delay.  Maybe Leo's startup actions should include starting a thread just for the purpose of letting the timeout occur.

After time out, the printer can be printed to and the output goes into the printer queue without incurring a time out.  Once the printer is actually turned on, the queued print jobs will be printed (I have tested this on Windows).

This plan will work best if a preview is not requested until several minutes after Leo starts (so the time out period has elapsed), but how often would it happen that someone starts Leo and wants to see a print preview right away?  Not very often, I'm sure.

**Comment by edreamleo** [comment]
@tbpassin I agree. It would be a lot of work to fix this issue. I'm good with closing this issue.

**Comment by tbpassin** [comment]
I've tried doing the job with a Python thread, but it still blocks the Leo GUI.  I'll try using Qt threads.  If that doesn't work in a non-blocking way, then I'll go ahead and close it.

**Comment by tbpassin** [comment]
Even using Qt threads, the first call to the printer blocks.  Leo hasn't really crashed with or without the threads.  It just has to wait for the OS attempt to contact the printer to time out.  I's just so slow on Windows (don't know about Linux).

I'll close this now.

**Comment by edreamleo** [comment]
I approve of closing this issue.
