### ISSUE TITLE
Clickable links for syntax errors don't work properly

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#3107]
See PR #3109.

**Comment by tbpassin** [comment]
I have an application that has started to have some clickable links wrong, too.  I just noticed it last night.

**Comment by tbpassin** [comment]
It's possible that the handling of links by Qt has changed in the most recent version or two - just a speculation.

**Comment by edreamleo** [comment]
Fixed via PR #3109.

**Comment by tbpassin** [comment]
In my app, for UNL links, when I made sure to replace ">" with "%3E" and spaces with "%20" - and then reversed the changes before using `g.handleUnl()`, the test cases I tried navigated correctly.  Until recently, I didn't need to reverse "%3E" and didn't need to encode/decode spaces.

In the past, I needed to encode "-->" to "--%3E" but I didn't have to decode it.  And I didn't need to encode/decode spaces.

I can make these changes in the couple of apps I wrote, but there must be other scripts out there that depend on the old behavior.

It's possible that Qt made some change in their URL handling in the most recent version.  If so, there would not be much we could do except change our own code.

**Comment by tbpassin** [comment]
Another change - previously CTRL-clicking on a UNL that started with 
`unl://c/tom` worked.  Now I need to add a colon to the drive - `unl://c:/tom`

**Comment by tbpassin** [comment]
Good - all my test cases work right again.

**Comment by edreamleo** [comment]
@tbpassin Thanks for testing :-)
