### ISSUE TITLE
Let CTRL-Click On Import Statement Navigate To Its Module

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#3112]
I only envision this working within an outline, not outside it.

Use Case:

I have an external Python file in my outline that contains the line

`from utility import ICONPATH`

I want to navigate to the _utility.py_ file - which is in the same outline - to look at that import more closely, perhaps to refresh my memory on the value of `ICONPATH`.  Currently I would type "utility" or "ICONPATH" into the Nav pane and hope that the results will be easy to work with, which they often are.  But CTRL-clicking would be more convenient and less distracting.

**Comment by edreamleo** [comment]
@tbpassin A reasonable enhancement. I've delegated it to you.

**Comment by tbpassin** [comment]
Thought you might!

**Comment by edreamleo** [comment]
@tbpassin :-)

**Comment by tbpassin** [comment]
Turned out to be easier than I expected.

**Comment by edreamleo** [comment]
Closed via PR #3113.
