### ISSUE TITLE
(leoserver) Implement @killColor, @nocolor & @noColorNode on the server-side

### ISSUE THREAD

**Issue by boltex** [leo-editor/leo-editor#3115]
The coloring of a node and the current node language are 2 different things in Leo, but not in vscode, or other possible clients. 

So make the server specify 'plain' language for a node that has it's coloring turned off, regardless of it's current 'language'.

See: https://www.leoeditor.com/directives.html#part-3-syntax-coloring-directives

Also Close https://github.com/boltex/leointeg/issues/285 when done :)

**Comment by edreamleo** [comment]
@boltex What are your plans for this. Is it alright to push this issue to 6.7.3?

**Comment by boltex** [comment]
This was fixed in my feb7 commit https://github.com/leo-editor/leo-editor/commit/47157344f0eb2d836c2029892bc1ee8572803ace

This is now part of devel, (cant seem to find which pull request was made for this. Maybe you just pulled felix-server-5 into devel around two weeks ago when I had mentionned that I had made many improvements on the server)

**Comment by edreamleo** [comment]
@boltex Thanks for closing this issue.
