### ISSUE TITLE
Should the write-file-from-node Command Write The Entire Subtree?

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#3120]
The command _write-file-from-node_ currently writes the selected node to a file.  It seems to me that it would be preferable for it to write the entire subtree.  Or perhaps there should be a similar command to write the subtree, perhaps _write-file-from-subtree_.

For text nodes, viewrendered3 can export a subtree to the designated editor, so the capability does exist.  But I think it would be good to have a _write-file-from-subtree_ type command.

Comments, suggestions?

**Comment by edreamleo** [comment]
@tbpassin I don't remember why `write-file-from-node` exists. Please don't change it&mdash;doing so may have unintended consequences.

Add `write-file-from-tree` is you like. If you do add this command, please don't change `write-file-from-node` in any way.

**Comment by tbpassin** [comment]
All right ... I thought I'd extract the current code into a method with a parameter `subtree=False`, and call that with or without the parameter for the two versions of the command.  Functionality of the current `write-file-from-node` would be exactly the same.

Sound all right?

**Comment by edreamleo** [comment]
On Wed, Feb 1, 2023 at 12:00 AM Thomas Passin ***@***.***>
wrote:

> All right ... I thought I'd extract the current code into a method with a
> parameter subtree=False, and call that with or without the parameter for
> the two versions of the command. Functionality of the current
> write-file-from-node would be exactly the same.
>
> Sound all right?
>
Please make two completely separate methods. It's the new style. Yes, some
code gets duplicated, but there are fewer "if" statements.

Edward

**Comment by edreamleo** [comment]
Closed via PR #3122.
