### ISSUE TITLE
Fix obsolete links and references to files

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#3133]
See PR #3168. The following pertain to `LeoDocs.leo`:
- [x] Remove the download link pointing to SourceForge for all recent versions,
  retaining the download links for versions for which these links were valid.
- [x] Remove obsolete refs to leoGuiPluginsRef.leo in LeoDocs.leo.
- [x] Revise description of leoPy.leo, the so-called **reference .leo file**.

This item pertains to `README.md` in the **master** branch. @tbpassin Good catch.
- [x] Change all links to `leoeditor.com` to `leo-editor.github.io/leo-editor`. 
    These links appear at the in Leo's main GitHub page: `https://github.com/leo-editor/leo-editor/tree/master`.
    Done directly in master at rev d8a524b.

**Comment by edreamleo** [comment]
@tbpassin Good catch. I'm on it.

**Comment by edreamleo** [comment]
Closed via PR #3168.
