### ISSUE TITLE
Cannot Type Two Consecutive Commas

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#3139]
When I try to type a string starting with two commas, the second comma does not get typed, and instead the cursor backspaces and deletes the initial comma.

I would have thought this behavior was caused by an incorrectly defined abbreviation, but I don't have anything like that in my myLeoSettings.leo file.

**Comment by edreamleo** [comment]
This behavior is expected and is part of Leo's abbreviation logic.

The workaround: type one comma, move the cursor left, type another comma.
