### ISSUE TITLE
Saving A Long Outline Takes Excessive Time When Many Nodes Are Expanded

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#3143]
I noticed that saving some outlines sometimes takes a very long time.  During this time leo is blocked and unresponsive.  For a large outline like LeoPyRef, the time can be 30 seconds or more.  The actual time varies, and if the .leo/db directory is deleted, the next save will be very fast.

I have traced this behavior to the time needed to save the record of expanded nodes to the sqlite database.  In an extreme case, after I expanded all nodes in LeoPyRef.leo, it took well over two minutes before Leo could respond again.  After contracting all nodes, Leo was immediately responsive.

This happens on both Window and Linux.

I consider this behavior to be unacceptable and find it hard to believe that it can possibly require that much time to store the expanded positions.  I don't want to wait 10, 20, 30 seconds or more after each save of LeoPyRef, and it's unreasonable for me to have to remember to contract all nodes before a save, or to make sure that the only  expanded nodes are ones I am currently working with.

I don't know how the mechanics of the expanded position saves works so I am not in a position to offer a solution at this time.  I do see that it is the gnx of an expanded node that gets saved.

**Comment by tbpassin** [comment]
It only takes about 25 ms on my machine to collect all expanded gnx values when LeoPyRef is fully expanded.  Script:
```
import time

def loop_to_time(event = None):
    n = 0
    gnx_list = []
    for p in c.all_positions():
        if p.v.isExpanded():
            gnx_list.append(p.gnx)
        n += 1
    return n

REPS = 100
t0 = time.time_ns()
for n in range(REPS):
    positions = loop_to_time()
t1 = time.time_ns()

g.es((t1 - t0)/(1e6 * REPS), 'ms per rep', '# positions:', positions )

# 27.195731 ms per rep # positions: 13039
```

**Comment by edreamleo** [comment]
@tbpassin I've never seen any significant delay saving leoPy.leo.  Please investigate.

**Comment by tbpassin** [comment]
I've had it happen with Leo on a Linux VM as well as on my Windows box itself.  Originally I thought it was only the Windows version.  After I realized that the problem was related to how many nodes were expanded, then I found it happening on the Linux VM as well.

Would you make this test for me, please?  Select the top node in LeoPyRef and add a space somewhere.  Next, expand all nodes.  Then save the outline.  See if leo remains unresponsive for more than a fraction of a second.  On my systems, the message that the outline has been saved displays right away on the log pane, but the unsaved asterisk in the outline's tab stays visible until Leo becomes unblocked.

If you had a longish delay, then delete that space, contract all nodes, and save again.  See if the delay is much shorter.

**Comment by tbpassin** [comment]
- I've now tried this on a real Linux computer - not a VM.  I have a ten-year-old laptop that I'm running from an external SSD that boots Linux Mint.  It's surprisingly fast given its age.  On this machine, LeoPyRef saves quickly even if I fully expand all the nodes.  

So the question is why the difference between this computer and my everyday Windows laptop - and why is the slow save happening even with Leo running in a VM?  Surely I can't be the only person to have this problem.

I originally expected the problem to be fragmentation of the sqlite database, but since the database file size is pretty small, that doesn't seem likely.  However, I'm going to try to look at that anyway.

**Comment by tbpassin** [comment]
During the outline save process, `c.clearChanged()` is called.  This is where the excessive time is happening.

**Comment by tbpassin** [comment]
Yes, the problem is definitely at `updateIcon()`.  So there are three questions:

1) Why do we need to do anything with icons when the outline is being saved?
2. Why is this slow when nodes are expanded but not when they are contracted?
3) Why is this process slow on my computer but not on everyone's?

If we do not need to update icons during save, there is a simple fix.  We add an _is_saving_ keyword argument to `v.clearDirty()` and then (tested; works):

```
for v in c.all_unique_nodes():
        v.clearDirty(is_saving = True)
```

Or maybe the arg should be called _update_icons_ instead.  At any rate, even if this icon updating doesn't seem to cause slowdowns on everyone's computers, we shouldn't really be doing all that work when we don't have to.  It's not really a hack.

**Comment by tbpassin** [comment]
Aha! I get it.  We update the icons in case there is a visible icon showing that a vnode is dirty.  But if the node is not actually dirty, there is no reason to call `v.updateIcon()`.  Currently the saving code clears the dirty bit (and updates the icons) whether or not they are dirty.  It should only call clear() if a node has the dirty bit set.  The only change needed is nearly trivial:
```
    # Clear all dirty bits _before_ setting the caption.
    for v in c.all_unique_nodes():
        if v.statusBits & v.dirtyBit:  # Only clear if actually dirty
            v.clearDirty()
```
Now we don't update a node's icons unless the node was dirty to begin with.

This change improved the save time for my workbook, but saving an expanded LeoPyRef still takes way to long.  Need to look further.

**Comment by tbpassin** [comment]
Finally!  The simple change above took care of the problem I had seen even with my workbook, which has about 280 nodes.  After that, LeoPyRef still would take minutes to save.  That turned out to be .... the ToDo plugin.  After the above fix, there was a second bottleneck, when doHook('save2') was called. ToDo sets that hook.

This plugin started loaded with LeoPyRef several months ago, IIRC.  I don't know why since it didn't seem to be showing anything useful.  Anyway, when I removed it from the list of loaded plugins, the rest of the excessive unresponsive time went away.

I will file a PR for the above change.  But I'm not about to try debugging the ToDo plugin.

**Comment by tbpassin** [comment]
Resolved by PR https://github.com/leo-editor/leo-editor/pull/3145.
