### ISSUE TITLE
Expand-all Command Shows Top Node Focused But Body Shows Wrong Node

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#3146]
After running the expand-all command, the tree's top node becomes highlighted but the body pane shows the text of the previously-selected body.  This is not only undesired but confusing.

**Comment by tbpassin** [comment]
The problem is that `c.redraw_after_expand()` does not actually redraw the body panel.  Adding a `c.redraw()` fixes that.  So does the fix below, and I think it's better.

In addition, the selected node moves to `c.rootPosition()` after the expansion, but I think that leaving the focus where it was would be preferable.

The proper behavior can be gotten by these two changes to `expandAllHeadlines`:
```
# ...
p0 = c.p  # Capture selected node before expanding
# Expand all nodes
# ...
c.redraw_after_expand(p0)  # was c.redraw_after_expand(c.rootPosition())
```

However, it appears that `c.redraw_after_expand()` does not redraw the body of the new selected node.  This seems like a bug.

**Comment by edreamleo** [comment]
@tbpassin Many thanks for this report. I have seen the effects of this *serious* bug from time to time, without understanding its cause.

I like your fix. Please file a PR.  Thanks again!

**Comment by tbpassin** [comment]
All right, expect a PR later today.

I still think that something is not right about `c.redraw_after_expand()` - because it does not redraw the body if it changes the focus - but it's only used in 5 places in LeoPyRef, and if all the others work right, perhaps we can leave the matter for another time.
