### ISSUE TITLE
Plugins Are Getting Loaded That Are Not In myLeoSettings.leo

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#3152]
I have a list of enabled plugins in my own _myLeoSettings_.leo outline.  However, I have been getting the _todo_ and _nodetags_ plugins loaded even though they are not included in my enabled list.  I do not want them loaded.

My understanding has been that if the _myLeoSetttings.leo_ outline has an _@enabled-plugins_ node then its enabled list will override the list from _LeoSettings.leo_. So I should not be seeing those plugins.

I do not get these plugins loaded on all outlines, but only certain ones, and also on new outlines.

I created a new outline, and put this code in its only node:
```
g.es(g.app.config.getEnabledPlugins())
```

This produced a list of plugins that did **not** include the two unwanted plugins.  Their tabs appeared among the log pane tabs, though.

Whatever is causing these plugins to load but not be listed among the enabled plugins should stop doing so.

[Later] - These plugins seem to get added to outlines loaded after I have loaded _LeoPyRef.leo_.

**Comment by tbpassin** [comment]
Oh, I think I see.  Once a plugin is loaded - by **any** outline - that plugin is already open when a later outline gets opened.

I don't think anything can be done about this without a **major** revamping of the plugin system, so I will close this issue.

**Comment by edreamleo** [comment]
@tbpassin You analysis is correct.
