### ISSUE TITLE
Look For Plugins outside of leo/plugins directory

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#3153]
I'd like for Leo to also look for plugins in a well-known place like ~/.leo/plugins.  This way a user can have private plugins without copying them to Leo's plugins directory.  From the code, it seems that plugins can be loaded from any location on _sys.path_ (if the plugin name is given without a .py extension).  But I think it would be helpful if this could happen without a user needing to change the module search path.

I think this could be done most easily by having the plugin loading code add the new directory to sys.path if it's not already there

**Comment by edreamleo** [comment]
Leo can already do this. Revs a1cd0de3 and d401e5481 improve the relevant documentation as follows:

- Add the word "usually" in the tutorial's discussion of plugins.
- Rewrite the "Enabling plugins" node in LeoDocs.leo using active voice.  The new text is:

QQQ

You can enable plugins by file name or by module name:
- Leo looks in the leo/plugins directory for names ending in .py.
- Leo uses imports a module directly for names that do *not* end in .py, so you can load plugins from any path on PYTHONPATH, including paths given in sitecustomize.py.

QQQ
