### ISSUE TITLE
When outline is saved, checkers only check current node, not entire at-file

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#3162]
This seems to be a new bug.  It's very annoying because to avoid a large listing of spurious errors (functions undefined, no imports, etc.), one must select the top of the at-file tree one has been editing before saving.

**Comment by edreamleo** [comment]
@tbpassin What checkers are you talking about?

**Comment by edreamleo** [comment]
@tbpassin Please do a `git bisect` to find the offending commit. Could this bug be related to your recent work?

**Comment by tbpassin** [comment]
I mean the ones that check for syntax and import errors.

**Comment by tbpassin** [comment]
This is weird.  After seeing the behavior for at least two days, now I can't repeat it.  We'll see - if I can't cause it to happen again I'll close this issue.

**Comment by edreamleo** [comment]
On Tue, Feb 21, 2023 at 9:04 PM Thomas Passin ***@***.***>
wrote:

> This is weird. After seeing the behavior for at least two days, now I
> can't repeat it. We'll see - if I can't cause it to happen again I'll close
> this issue.
>
Whew. This issue would be a release blocker.

Edward

**Comment by edreamleo** [comment]
I'm going to close this issue. I get warnings of syntax errors as expected when I save files.
