### ISSUE TITLE
Viewrendered pane loses live-render feature

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#317]
To observe open leo file, and run vr.
The vr pane opens, attached to leo, and not floating.
Hover over a splitter, 'right-click> remove 1 Right'. The vr pane closes.
Now run vr again, and the vr pane opens in a floating window. However this floating window is static, and does not live-render.

Closing the file and re-opening does not restore the live-rendering. You need to close Leo completely and restart to restore the live-rendering on that file.

To be clear - live render still works on files which have not run 'right-click> remove 1 Right' command.

As a workaround I have found  that the vr-hide and vr-show commands as buttons are most suitable for this; you get the screen space back and keep the live render feature.

**Comment by edreamleo** [comment]
On Wed, Jul 12, 2017 at 1:43 PM, Виталије Милошевић <
notifications@github.com> wrote:

> Closed #317 <https://github.com/leo-editor/leo-editor/issues/317> via
> 27fceed
> <https://github.com/leo-editor/leo-editor/commit/27fceedeb68ef0491908d709dd23989526d9d013>
> .
>
​Many thanks, Vitalije, for this fix and for all your recent work.  A
one-line fix has importance far beyond it's size.

Edward
