### ISSUE TITLE
v.setBodyString() seems inconsistent

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#3172]
`v.setBodyString()` seems to have parts that are not needed since Leo now only supports Python3.  The two branches of the "if" also do not seem consistent with each other.  Annotated:

```
def setBodyString(self, s: Any) -> None:
    # pylint: disable=no-else-return
    v = self
    if isinstance(s, str):
        v._bodyString = s
        v.updateIcon()
        return   # [4]
    else:  # pragma: no cover
        v._bodyString = g.toUnicode(s, reportErrors=True)  # [1]
        self.contentModified()  # #1413.   # [2]
        signal_manager.emit(self.context, 'body_changed', self)  # [3]
        v.updateIcon()
```

[1] The string s will not be a non-unicode string any more, under Python3.  s is claimed to be of type Any, but the case where it is not a string type is not  handled, so presumably this method will not be passed a list or other object.  Therefore it seems that the `else` branch is no longer needed.

[2] `self.contentModified()` should be called in the `if` branch, too.

[3] The signal should be emitted in the `if` branch also.

[4] Instead of the Pylint _disable_ comment, just remove the `return` statement.

Also, why not check to see if `v._bodyString == s` before making any change?

**Comment by edreamleo** [comment]
@tbpassin Thanks for these comments. I'm going to leave `v.setBodyString` exactly as it is:

- Scripts can call this method, so mypy can check the annotations only within Leo's codebase.
  In other words, `v.setBodyString` must not assume anything about `s`.
- I didn't add the call to `contentModified`, so I don't want to change it.
- `v.setBodyString` is fast, so there is no need for the extra test.

**Comment by tbpassin** [comment]
OK... not knowing any of its history, I could only pick up on what I saw.  Still, v.setBodyString _does_ make assumptions about s.  It assumes that if it is not a string then it must be something that can be `toUnicode`-ed.  If it could really be _anything_, that assumption would not be correct.

So I would rather that that assumption be protected, presumably by  try: block. OTOH, in practice we don't see problems here, do we?  And it is probably one of the most used method calls in Leo.

**Comment by edreamleo** [comment]
@tbpassin Thanks for your continued interest in Leo's heart :-)

`g.toUnicode` catches *all* exceptions so in effect `v.setBodyString` does too.
