### ISSUE TITLE
The C/C++ importer fails to recognize the code correcty

### ISSUE THREAD

**Issue by AresAndy** [leo-editor/leo-editor#3174]
I'm trying to use Leo at my workplace, where I mainly do C/C++ code for MCUs. All proprietary stuff that I cannot share.
However the issues I'm facing at work are replicable using a FOSS project: libSDL

![image](https://user-images.githubusercontent.com/9638528/221418390-917b5bca-9d5c-42e9-a18c-e9e76f143347.png)

I've used the `active_path.py` plugin, with `@auto` nodes, and the result is anything but desirable:
- Comments associated with some code get outlined by themselves **without** the related code
- Preprocessor `ifdef` get messy, especially if they are complex
- `extern` blocks get blobbed into a single outline node
- ... and more

At the beginning I was thinking the issue was the presence of not-standard types messing with the parser, but that is not 
the case with SDL. Suffices to say that the current results are (if not unusable) difficult to work with.

I wish I could lend in a hand, but I just don't have spare time for it.
Are there any quick remedies for this?

PS:
- Leo version: `master` checkout
- SDL version: `master`

**Comment by edreamleo** [comment]
@AresAndy Thanks for your report. `C` is a particularly tough language to handle, but I'll see what can be done.

**Comment by edreamleo** [comment]
@AresAndy Leo's importers support post-passes that alter the imported outlines.

As a prototype of a new `C` post-pass, you could create a script that would alter imported `C` code to your liking.

Such a script would help me understand the problems you would like to see fixed. Are you interested in creating such a script?

**Comment by edreamleo** [comment]
@AresAndy I am going to close this issue for now. Please feel free to reopen it.

**Comment by AresAndy** [comment]
> @AresAndy Leo's importers support post-passes that alter the imported outlines.
> 
> As a prototype of a new `C` post-pass, you could create a script that would alter imported `C` code to your liking.
> 
> Such a script would help me understand the problems you would like to see fixed. Are you interested in creating such a script?

Sorry for replying late, but unfortunately I cannot develop the script, let alone figure out my lefts from rights on the Leo code. The interesting parts of the APIs are not well documented, and the outlines do not help a whole lot.

I also tried to figure out if the issue is missing intel on the code (keywords, coding formats like K&R, Java, etc..) and in the process noticed that the parser is laid out similarly to the Python one, and that is of course not ideal. There are many languages that look like Python, and many that do not. Those should get parsed in a python-agnostic manner

As for understanding what is going wrong, just try to load a C/C++ project and navigate around.
The problems will show up in no time, especially with `.c` files :sweat_smile:

Too bad we're not going to see it fixed :disappointed:, this would prove that Leo can be used even for non-Python stuff.
A lot of editors written in Python tend to become "geostationary" to it, I would hate to see Leo become one too

**Comment by edreamleo** [comment]
@AresAndy Imo, the design of the importers does not preclude fixing the problems.

I can attempt a fix if you provide sample code illustrating the problems you see with the `C` importer.
