### ISSUE TITLE
Enhancement - Alternate way to deal with font sizes

### ISSUE THREAD

**Issue by technatica** [leo-editor/leo-editor#319]
I have spent a bit of time looking into smaller IDEs and editors for python to see how they handle things.

http://pyzo.org is an interesting project that I have been using as a platform for learning python. They handle font sizes using a Zoom instead of point sizes. It is immediate and eliminates a large amount of complexity for the end user and the programmers.

This lightweight IDE is written in pure python3 and implements some pretty interesting and simple UI ideas. It struck me that some of those ideas can help provide simplifications for some of the vr/font/stylesheet issues that leo is facing over the next bit.

Having iPython so well integrated into the program is very handy. Their decision to run on top of conda was smart, as it simplifies the setting of an environment for most.

![screenshot_20160924_135121](https://cloud.githubusercontent.com/assets/5809169/18811207/41ab67e2-825e-11e6-9e31-0c22567ee777.png)

**Comment by gazikamel** [comment]
NICE

**Comment by edreamleo** [comment]
On Sat, Sep 24, 2016 at 3:55 PM, Chris George <notifications@github.com>
wrote:

> I have spent a bit of time looking into smaller IDEs and editors for
> python to see how they handle things.
>
> http://pyzo.org is an interesting project that I have been using as a
> platform for learning python.
>
​Thanks for the link.  It does look interesting.

> They handle font sizes using a Zoom instead of point sizes. It is
> immediate and eliminates a large amount of complexity for the end user and
> the programmers.
>
​Did you know you can zoom body text at any time in Leo with Ctrl-+ and
Ctrl-- ?​

> This lightweight IDE is written in pure python3 and implements some pretty
> interesting and simple UI ideas. It struck me that some of those ideas can
> help provide simplifications for some of the vr/font/stylesheet issues that
> leo is facing over the next bit.
>
​A gui isn't flexible enough to handle all of Leo's settings.  I tried such
an approach in the past and it was a failure.

> Having iPython so well integrated into the program is very handy.
>
​Yes, it's cool.​  Apparently pyzo uses yoton
<http://yoton.readthedocs.io/en/latest/>to communicate between
subprocesses.  I'm guessing that's how it embeds IPython.  It's worth a
look.

EKR

**Comment by technatica** [comment]
I have since settled on Spyder/Conda to teach myself python/pyqt. Having multiple ipython environments baked in is handy as it is difficult to find tutorials and examples that exactly match the python version/pyqt version that I have installed. It allows me to pair up the tutorial and the environment (Conda) and work with their code/examples in Spyder/ipython.

What initially interested me about pyzo was their focus on simplicity and how they have chosen to polish the UI rather than add more complexity under the hood. I feel that the complexity of Leo will really begin to shine for users when that complexity can be harnessed to a simpler UI. Perhaps switching to the qtdock perspective will marry simplicity and complexity and unleash more power.

**Comment by edreamleo** [comment]
On Fri, Sep 30, 2016 at 9:39 AM, Chris George <notifications@github.com>
wrote:

> What initially interested me about pyzo was their focus on simplicity and
> how they have chosen to polish the UI rather than add more complexity under
> the hood. I feel that the complexity of Leo will really begin to shine for
> users when that complexity can be harnessed to a simpler UI. Perhaps
> switching to the qtdock perspective will marry simplicity and complexity
> and unleash more power
> ​
>
> ​The only part of Leo's UI that could be said to be complex is the Easter
Egg interface.  Terry and I agree that using QDocWidget would simplify the
interface.

Is there any other part of Leo's UI that see​ms complex to you?

EKR

**Comment by tbnorth** [comment]
On Sat, 01 Oct 2016 07:21:14 -0700
"Edward K. Ream" <notifications@github.com> wrote:

> On Fri, Sep 30, 2016 at 9:39 AM, Chris George
> <notifications@github.com> wrote:
> 
> > What initially interested me about pyzo was their focus on
> > simplicity and how they have chosen to polish the UI rather than
> > add more complexity under the hood. I feel that the complexity of
> > Leo will really begin to shine for users when that complexity can
> > be harnessed to a simpler UI. Perhaps switching to the qtdock
> > perspective will marry simplicity and complexity and unleash more
> > power ​
> >
> > ​The only part of Leo's UI that could be said to be complex is the
> > Easter  
> Egg interface.  Terry and I agree that using QDocWidget would
> simplify the interface.

Actually the style sheet handling that indirectly is involved in font
zooming is /complex/, maybe with some better comments / docs. we can
have it not seem too /complicated/.  There's a payoff for the
complexity in terms of the @my_favorite_color substitution in
stylesheets etc.

Cheers -Terry

> Is there any other part of Leo's UI that see​ms complex to you?
> 
> EKR
> 
>

**Comment by ktenney** [comment]
> Is there any other part of Leo's UI that see​ms complex to you?

Jumping in, completely out of context:

I think there are too many items on the Leo main menu,
they look a bit like 'kitchen sink', daunting. Do others find
themselves using many commands from these menus?

Maybe move more into subtrees, so at first glance they
look simple and inviting.

I also wonder how many of the default bindings are used in
the wild, When I've looked into custom bindings, I find lots
are owned by pretty obscure stuff.

**Comment by edreamleo** [comment]
On Sun, Oct 2, 2016 at 7:40 AM, Kent Tenney <notifications@github.com>
wrote:

> > Is there any other part of Leo's UI that see​ms complex to you?
>
> Jumping in, completely out of context:
>
> I think there are too many items on the Leo main menu,
> they look a bit like 'kitchen sink', daunting. Do others find
> themselves using many commands from these menus?
>

​I only ever use commands in the File menu, and even that is not an optimal
way to use Leo.  Imo, the menus exist almost exclusively to remind people,
especially newbies, what commands exist.  But to actually *use* those
commands it is much better to access them through the minibuffer.

Maybe move more into
> ​[sub menus], so at first glance they
> look simple and inviting.
>

​We want to "advertise" that there are dozens of commands.

Otoh, the biggest Aha I ever had concerning Emacs is that I could *ignore*
all commands except those that were useful to me.  In that sense, having
lots of commands is intimidating and not helpful.

I don't know any way to resolve the dilemma, except to tell newbies that
they can (must) ignore commands at first. I've just made a note to myself
in LeoDocs.leo to tell newbies just that in various places.  The new words
will appear in Leo 5.4b1.

Edward

**Comment by edreamleo** [comment]
There are multiple issues/requests in this item.  I'll separate them and deal with them individually for 5.5.
