### ISSUE TITLE
show-settings Command Fails

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#3190]
PR #3191 fixes the crash by replacing the `assert` with a comment. In general such `assert`s can do more harm than good.

Some recent change seems to have caused this.  Here is the error traceback:
```
Traceback (most recent call last):

  File "c:\Tom\git\leo-editor\leo\core\leoGlobals.py", line 304, in new_cmd_wrapper
    func(self, event=event)

  File "c:\Tom\git\leo-editor\leo\commands\helpCommands.py", line 1152, in showSettings
    self.c.config.printSettings()

  File "c:\Tom\git\leo-editor\leo\core\leoConfig.py", line 1941, in printSettings
    for name, val, _c, letter in g.app.config.config_iter(c):

  File "c:\Tom\git\leo-editor\leo\core\leoConfig.py", line 1240, in config_iter
    assert isinstance(gs, g.GeneralSetting), repr(gs)

AssertionError: None
```

```
Leo 6.7.2-devel, devel branch, build 5f2578c58b
2023-02-27 13:53:28 -0500
Python 3.10.9, PyQt version 6.4.1
Windows 10 AMD64 (build 10.0.19044) SP0
```

**Comment by tbpassin** [comment]
This isn't as simple as it seems.  I got this failure repeatedly, but not when I opened another Leo session and tried with one or two other outlines.

The code at the line pointed to in the error message is:
```
    for key in sorted(list(d.keys())):
        gs = d.get(key)
        assert isinstance(gs, g.GeneralSetting), repr(gs)
        if gs and gs.kind:
```
I'm thinking that `d.get(key)` probably returned None or an empty string.  This probably doesn't happen very often, and could be handled by adding a line:

```    
for key in sorted(list(d.keys())):
        gs = d.get(key)
        if not gs: continue   # <----------
        assert isinstance(gs, g.GeneralSetting), repr(gs)
```

**Comment by edreamleo** [comment]
@tbpassin Thanks for this report. Testing for `None` should suffice. I'll fix this next.

**Comment by edreamleo** [comment]
@tbpassin PR #3191 fixes the original crash.

I'll leave this issue for your further work. Please base that work on `devel`. Or feel free to close this issue :-)

**Comment by tbpassin** [comment]
I think it's OK to close it at this time.  Thanks!
