### ISSUE TITLE
When I post a message to the Google Group Leo-Editor, the message is immediately deleted

### ISSUE THREAD

**Issue by SegundoBob** [leo-editor/leo-editor#3193]
Have I been banned?  Is this a bug in Google Groups?

I tried Firefox and Chrome.  Both had the same bad behavior.

Regards,
SegundoBob

**Comment by edreamleo** [comment]
@SegundoBob No, you haven't been banned. Google Groups has been acting badly lately. Yesterday some of my emails were rejected as spam!
