### ISSUE TITLE
Add c.find_h() and c.find_b()

### ISSUE THREAD

**Issue by SegundoBob** [leo-editor/leo-editor#3194]
See PR #3196.

**Original Report**

I have many scripts that use `c.find_h()` and `c.find_b()`.  They have simple calls and are adequate to my needs.  Yesterday I updated to the latest devel Leo-Editor and I find that they no longer exist.  Instead there seems to be various much more complicated search functions in QuickSearchController in the leoserver.py module.

How about restoring the simple functions cmdr.find_h() and cmdr.find_b()?  Or telling me how best to replace my calls to cmdr.find_h() and cmdr.find_b()?

I tried posting this question on the Leo-Editor forum, but it was repeatedly deleted immediately.   This question is probably more appropriate for the forum.  I don't consider the problem a bug.

Regards,
SegundoBob

**Comment by edreamleo** [comment]
@SegundoBob I apologize for the missing methods. I don't remember deleting them on purpose, though perhaps I did.

I'll put them back later today.

**Comment by edreamleo** [comment]
@SegundoBob Upon further study, I'd like to amend my suggestion. Instead of using functions it would be good to define `c.find_h` and `c.find_b` exactly as shown above.

At present, the `stickynotes.py` plugin and the `leo_babel/tests/lib_test.py` test file call `c.find_h` and `c.find_b`. Apparently Leo's tests (especially pylint) are not covering these files properly.

**Comment by SegundoBob** [comment]
Edward,

c.find_b() and c.find_h() would be great.

I had to poke around leoPyRef.leo awhile to discover how to call the new find_b() and find_h():

`lx = c.frame.nav.scon.find_h('rfd2302', c.all_positions())`

So c.find_h() would be a great improvement.

The old c.find_h() and c.find_b() only had one required argument.  The new c.find_b() and c.find_h() have a second required argument.  If you gave this second argument the default value `c.all_positions()`, then all the existing calls to c.find_b() and c.find_h() would continue to work as before without having to change the calls.  Unfortunately, this would require some change to the existing function definitions or some kludging since `c.all_positions()` must be called when each call is made, not when the function is defined.

Since the two new arguments (positions and options)  are useful, I think they should be retained.

Regards,
SegundoBob

**Comment by tbpassin** [comment]
> ```python
> def find_b(self,
>     regex: str,
>     positions: List[Position],
> ```

Wouldn't that `List[Position]` better be any kind of a sequence?  Then generators (and tuples) could be used as-is too.

**Comment by edreamleo** [comment]
@SegundoBob I agree, there should be a second argument.

@tbpassin I think the annotation for the second arguments `Sequence[Position]` or maybe `Iterable[Position]`.

The new `c.find_h/b` methods won't have all the features of the old `PosList` class, and that's fine with me. In particular, one won't be able to chain results with, say, `c.filter_h(regex2).c.find_h(regex1)`. The workaround: call `c.find_h` with a more explicit regex.

I have never seen a convincing use case the `c.filter_h` methods. A `cff` shows that no such calls exist within Leo. Indeed, the `PosList` class may have predated list comprehensions. Anyway, the following pattern will refine results as necessary:
```python
aList = [z for z in c.find_h(aRegex) if aPredicate(z)]
```
**Summary**

The old `PosList` class was overkill.

I'll submit a PR soon containing new `c.find_h/b` methods. I'll await both your reviews before merging the PR.

**Comment by SegundoBob** [comment]
c.find_b() and c.find_h() and the tests of them look fine to me.

I couldn't make head nor tail of the "batch operations" code which seems completely unrelated to c.find_b() and c.find_h().  If it is completely unrelated, why is it in this change set?

Regards,
SegundoBob

**Comment by edreamleo** [comment]
@SegundoBob The batch operations code didn't change. I just alphabetized the children of the node.

**Comment by edreamleo** [comment]
@SegundoBob Thanks for testing. I'll fix Thomas's suggestions and merge this PR.

**Comment by edreamleo** [comment]
Fixed via PR #3196.
