### ISSUE TITLE
670 words - "Google Groups has been left to die" Andrew Helwer

### ISSUE THREAD

**Issue by SegundoBob** [leo-editor/leo-editor#3197]
[Lnk to post](https://ahelwer.ca/post/2023-03-08-google-groups/)

via Hacker-News-RSS

Where should the formal methods community move?

670 words - 34 sentences - 6 paragraphs
---------

I tried posting this on the Leo-Editor Group at Google Groups, but it was immediately deleted.

Regards,
SegundoBob

**Comment by tbpassin** [comment]
I had a harmless post - a reply within a thread on Leo's Group - get deleted for reasons unknown.  It didn't contain anything negative to Groups or Google.  Unlike the above linked post, though, so far I haven't seen a problem with using Courier font for code.

Maybe we should move over to GitHub discussions.  Yes, I know, the linked post suggests not doing so, but it didn't show me any convincing open-source alternatives.

**Comment by edreamleo** [comment]
Please, let's not panic. Bugs happen.
