### ISSUE TITLE
Upgrade lxml To Avoid Some File Import Exceptions

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#3199]
With lxml 4.8.0, trying to import a .c file, I got this exception:

```
Exception importing FreeMind file nmakehlp.c
Traceback (most recent call last):

  File "c:\Tom\git\leo-editor\leo\core\leoImport.py", line 78, in create_outline
    self.import_file(path)

  File "c:\Tom\git\leo-editor\leo\core\leoImport.py", line 90, in import_file
    htmltree = lxml.html.parse(path)

AttributeError: module 'lxml' has no attribute 'html'
```
I remember reading that something had changed recently with lxml, but I thought that was for newer versions oy Python.  I *think* I recall that it was an accidental change and was being fixed.

I upgraded just now and the version installed from PyPi is 4.9.2.  Now the file import works (and the external file tree looks pretty good, too).

**Comment by edreamleo** [comment]
@tbpassin Thanks for this investigation. What, if anything, do you think we should do?

Would a new `try/except` block be a good idea? I'll leave this issue to you :-)

**Comment by tbpassin** [comment]
> What, if anything, do you think we should do?

I opened this issue was mainly to warn people about it.  I gather from online discussions that a number of projects were hit by this.  The only thing I can see to do in Leo is to update the version in the requirements.

I will cruise through LeoPyRef and see if I can spot anything more that would make sense to do.

**Comment by edreamleo** [comment]
@tbpassin Thanks for your comments.

**Comment by tbpassin** [comment]
I just realized that the error message I posted above is for a Freemind import, but I was importing a C file.  lxml isn't needed for that.  I wonder why Leo thought a C file was a Freemind file, or what was really going on.

**Comment by edreamleo** [comment]
@tbpassin I have removed the milestone and delegated this issue to you. 

Please feel free to close or reopen the issue as you choose.
