### ISSUE TITLE
add freemind and mindjet imports

### ISSUE THREAD

**Issue by tbnorth** [leo-editor/leo-editor#32]
Scripts for importing from Fidel are attached - he points out that integrating them into the import menu would be a big draw for freemind and mindjet users.

Will probably need an example file from each to test with.

**Comment by edreamleo** [comment]
This issue appears complete at rev 1603621.

**Comment by edreamleo** [comment]
**Documentation**

There are two ways to access these commands:

1. Using the general import-files command, via the minibuffer or the File:Import File menu.  This opens a dialog that picks the proper importer based on the file's extension.  mm.html files get the FreeMind importer. csv files get the MindJet importer.

2. If these conventions don't suit you, you can use specific import-free-mind-files or import-mind-jet-files commands. These open a dialog in which the specific extension is pre-selected, but you can pick any file as usual.  In particular, it's possible to use the MindJet importer to open .ipynb files, which have .csv format.

In general, if you pick an invalid file, the importers will fail gracefully.
