### ISSUE TITLE
c.config.getColor() Is Misnamed

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#3203]
`c.config.getColor()` returns more theme symbolic strings than just color.  For example, `c.config.getColor('font-family')` returns the themes's `@font-family` setting.  I haven't explored it fully, but it also works with `@tree-image-closed`, `@bg-gradient `, and `@font-family-ui` (my theme has this one) settings.

I surmise that any symbolic name setting from the current theme can be retrieved.  

I'm actually making use of this in one app I'm working on, so I think it's useful.  I suggest that there be a new method, defined notionally as
```
c.config.getThemeSetting = c.config.getColor
```

**Comment by edreamleo** [comment]
@tbpassin Thanks for this comment! I didn't remember this, if I ever knew it.

I'm deep into #3149 right now. Let's hold off on any new methods until that issue is resolved.
