### ISSUE TITLE
Fix the headline-change undo methods, and create a new 'multiple-headline-changes' set of undo methods.

### ISSUE THREAD

**Issue by boltex** [leo-editor/leo-editor#3219]
Fix the headline-change undo related methods, and l make a new 'multiple-headline-changes' undo set of methods, which will take the very minimum amount of memory space.  ( a dict of old-headline/new-headline tuple, with the gnx-string as key, only for the nodes that changed their headlines) 

Then, replace the proper usage of the headline-change undo method in leo-server, (and other places if need be) and use those new 'multiple-headline-change' undo methods in the headline-numbers related commands that @edreamleo and @wangzhaohe made :)

**Comment by boltex** [comment]
Note: the  'multiple-headline-changes' undo set of methods will NOT use 'group undos', and will only create a single bead, with the simple dict of changed headlines as described above.

**Comment by edreamleo** [comment]
Fixed via PR #3228.
