### ISSUE TITLE
Simplify calls to g.os_path wrappers

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#3235]
**Background**

The `g.os_path_*` wrappers are a legacy of python 2. However, they can *not* be removed from Leo's core because they work differently from the corresponding `os.path` functions:
-  `g.os_path_normslashes` converts backslashes to forward slashes on Windows.
- `g.os_path_join` supports `!!` and `.` args.

**Phase 1: PR #3241 (merged into devel)**

- [x] Use `c.fullPath(x)` instead of `g.fullPath(c, x)`.
- [x] Always call `g.os_path_normslashes` to do convert backslashes to forward slashes.
   This change simplifies future changes.

**Phase 2: (Won't do)**

Making `g.os_path_normslashes` a do-nothing would be an extremely bad idea:
- Making this change would have severe, unpredictable consequences.
- We can rationalize what `g.os_path_normslashes` does by saying that Leo uses POSIX slashes internally.

**Comment by tbpassin** [comment]
I don't favor making serious changes like this for no immediate benefit - as you say, they will be risky.

Instead, I think that new (or code that is being revised anyway) Leo code should start using _pathlib_ methods.  They automatically handle the path separator issue, for one thing.  For another, in some cases their expressions can be more intuitive or natural - something like 

```
from pathlib import PurePath
dir = PurePath(g.app.leoDir) / '..'  # __div__ operator is overloaded - brilliant!
g.es(f'{dir}')  # C:\Tom\git\leo-editor\leo\..

dir_ = PurePath('A')/'B'/'C'
g.es(f'{dir_}')  # A\B\C
```

These paths can be used as is in `file.open()` and similar - they don't need to be converted to strings first.

**Comment by edreamleo** [comment]
@tbpassin Thanks for your comments. I'll try a few experiments and report back.

**Comment by edreamleo** [comment]
@tbpassin I wouldn't say that this issue is without benefit. The hack in `g.os_path_finalize` is a serious blemish. This hack is likely needed only in two or three places.

**Comment by tbpassin** [comment]
`g.os_path_join` enhencements - who even knows about them or uses them?  Not me.

I think that `g.os_path_finalize()` should stay as is - it's working just about where ever it's used, and who knows how many users have code that uses it?

If it is not adequate for some task, then write a new method that is correct and use that.  Or use a few lines of standard methods (e.g., _PathLib_ methods) In the places that need them.

The use of new, better methods is something that can be phased in when and where needed, without the risk of breaking someone's code.

**Comment by edreamleo** [comment]
@tbpassin I agree with you:
- *All* `g.os_path_*' must stay as they are. I have no plans to break anyone's code.
- I'll prefer 'PathLib` methods to `os.path` methods.

**Comment by tbpassin** [comment]
D'accord!

**Comment by edreamleo** [comment]
@tbpassin The first (easy, safe) phase of this project is complete.

Imo, the hack in `g.os_path_normslashes` is intolerable.

Removing all calls to this evil function (in Leo's core) won't be easy, but it is worth lots of work. 

And yes, for compatibility `g.os_path_normslashes` will remain as a do-nothing.

**Comment by edreamleo** [comment]
@tbpassin I am going to close this issue without changing `g.os_path_normslashes`.
