### ISSUE TITLE
Add command to make a .zip file from an outline and its external files

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#3238]
See PR #3255.

Write to the `os.environ['LEO_ARCHIVE']` directory or the directory containing the `.leo` file.

Later or never: add additional resources to the `.zip` file.

**Comment by tbpassin** [comment]
Excellent.  A user can always add more resources to the zip file by hand.

**Comment by edreamleo** [comment]
Completed via PR #3255.
