### ISSUE TITLE
Exception Text Not Reported In Log Pane

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#3244]
See PR #3262.

If a script run with, e.g., CTRL-b, raises an exception, the log pane will show the offending line of code, but not the text of the exception.  The exception is printed to the console. It is very annoying to have to switch windows to the console to read the message.

ISTR that the exception text also got displayed in the log pane until relatively recently (farther ago than the last few weeks or a month, I think).

To reproduce:

1. Create a node in the workbook with the following code:
```
x = 1
g.es(1/0)
```
2. Run the script with the workbook.
3. Observe that the exception text `ZeroDivisionError: division by zero` gets printed to the console but not to the log pane.

**Comment by edreamleo** [comment]
Closed via PR #3262.
