### ISSUE TITLE
`save_as_zipped` saves as .db, not .zip

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#3245]
@tbpassin That's on purpose, I think.

**Comment by tbpassin** [comment]
I didn't edit my issue to read like it does now.  WTF??

Why would it be on purpose to write an SQLite file instead of a zip file when the command clearly says it's going to write a zip file?  We were talking about creating a zip archive of the outline and its external files. Writing a .db file doesn't do that.

**Comment by edreamleo** [comment]
@tbpassin I understand your confusion, but the command's name may at fault. There are issues with `.leo.db` file extensions.

So please chill and consider how the `save-as-zipped` actually works. We can then worry about command names.
