### ISSUE TITLE
Leo should provide a hex view of a file

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#3247]
Some text editors provide a hex view of a file.  This is useful when one needs to examine an unknown or binary file, perhaps to figure out what kind it is.

A traditional hex view shows a block of hex on the left and a block of the equivalent characters on the right, so that any embedded strings can be read.  This new view should have an equivalent display, whether or not it looks like traditional one or not.

Whether Leo should be able to edit this hex view is unclear to me at the moment.

It may be that the easiest way to do this is to display the hex in VR3.

**Comment by tbpassin** [comment]
I'm having second thoughts since I'm not sure how to get a binary file into a node - and I'm not sure we'd really want to.  I have identified a pyqt hex viewer that could be adapted to open in a tab, or to be opened by VR3.  But I don't yet see how to use it.  

The editors I use that have a hex viewer all can - I think - open a file as binary (such as a PDF file, for example).  I presume they re-open the file as binary when one asks for the hex view.  That doesn't fit well with the way that Leo works.

So I need to give this potential enhancement some more thought.

**Comment by edreamleo** [comment]
@tbpassin Good work. A script is the reasonable solution.
