### ISSUE TITLE
CTRL-Click on a method name may find definition in wrong file

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#3248]
A control-click on a function/method may find a method of the same name in a different external file.  This can be confusing and irritating.  The search for the definition should look first in the current external file, if any, and only if that fails should it search the entire outline.

To reproduce:
1. Open LeoPyRef;
2. Find the viewrendered3.py plugin tree and select a node in it;
3. Navigate to the `vr3.contract & expand` node;
4. CTRL-Click on a line reading `self.change_size(100)`;
5. Note that Leo navigates to the `def change_size` line in the `viewrendered.py` file, not the 'viewrendered3.py' file.

**Comment by edreamleo** [comment]
This is likely the same issues as #3181. I'll leave this issue open for now.

**Comment by tbpassin** [comment]
I'm not convinced it's the same issue.  I think it's just about the order of traversal to find the desired def, etc.

**Comment by edreamleo** [comment]
@tbpassin I agree with your analysis.  Imo, the behavior you describe is expected and correct. I'll close this issue now.
