### ISSUE TITLE
Color solarized-purple is missing from themes

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#3252]
All the themes I have looked at have a node with this headline:

`@color url_color = @solarized-purple`

None of those themes define what the color value `@solarized-purple` should be. 

Recent Leo changesets display an error on startup for the missing color.  Does anyone know what this value this color was intended to be in some theme or another?

**Comment by tbpassin** [comment]
I found where it's used.  _url_color_ is predefined as purple in `defineDefaultColorsDict()`.

After looking at the *solarized* website, I was going to try purple as a starting point.  So I probably can close this issue, although a settings node `@color url_color = @solarized-purple` should probably be added to all the themes at some point.

**Comment by edreamleo** [comment]
I'm confused. I am going to reopen this issue until I can understand it better.

- Solarized defines `soloarized-violet`. There is no `solarized-purple`.
- Themes should Tk's `purple` color be default for urls.

**Comment by edreamleo** [comment]
Closed via PR #3254.

**Comment by edreamleo** [comment]
@tbpassin I hope PR #3254 will render this issue moot.
