### ISSUE TITLE
Support images in body text

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#3256]
See [this discussion](https://groups.google.com/g/leo-editor/c/I7ggFqTZLEg).

**Comment by tbpassin** [comment]
One thing I'm fairly sure about - images don't make sense for bodies that contain code.  Or, if they should be allowed, writing those nodes to a scriptfile or external file has to comment them out.  But that would be even more complication, as I see it.

The Qt way seems to be to insert a special unicode character, and use its location to actually insert the image data.  I don't think that character in itself contains any of the data.  It's just a marker.  So editing commands could delete it or move it around, but then its cursor would have to be re-populated with the image.

I can see doing all that, maybe, but persisting the image data and restoring it at the right place is another question.

Perhaps an @image directive can synchronize all that.   The image data would be in an image file somewhere, and the image directive would say where.  When the body gets rendered, the renderer would notice the @image directive and do the Qt magic to display it.  We would need to be careful that this mechanism does not interfere with VR3's use of @image directives.  (VR3 silently converts @image directives into the syntax used by RsT, MD, and asciidoc for images).

I really think that an image capability would be a big plus for some Leo users (including me).

**Comment by edreamleo** [comment]
@tbpassin I agree with your analysis. Bypassing Qt's image marker hack seems prudent too.

**Comment by edreamleo** [comment]
@tbpassin I've just posted [this comment](https://groups.google.com/g/leo-editor/c/I7ggFqTZLEg/m/2pje697AAQAJ) on Leo's forum. To summarize:

- The  `@embedded-image` directive should contain the path to the image.
- I'm agnostic about all other details :-)
