### ISSUE TITLE
Fix misleading comment in setup.py

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#3258]
In setup.py, there is an obsolete - and so misleading - comment:

    `'PyQtWebEngine',  # #1202 QtWebKit needs to be installed separately starting Qt 5.6`

QtWebKit is no longer used by the WebEngine, or even available.

**EKR**: Oh. The dependency remains. Only the comment should go.

**Comment by edreamleo** [comment]
@tbpassin Thanks. I'll do this.
