### ISSUE TITLE
Allow only safe syntax in c.expand_path_expression

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#3260]
See PR #3260.

Path expressions are desirable, but they must be made completely safe. Leo' present path expressions (`c.expand_path_expression`) are serious security violations that virus scanners will never find.

Aha: `c.expand_path_expression` need only use Python's existing `os.path` conventions.
Bye-bye `{{` and `}}`!

**Comment by boltex** [comment]
it's already implemented in leojs. 

can you elaborate as to why it would be a security concern?

**Comment by edreamleo** [comment]
Closed via PR #3264.
