### ISSUE TITLE
Enhance @auto parsing of c file to include Doxygen style comments

### ISSUE THREAD

**Issue by shakfu** [leo-editor/leo-editor#3265]
Hi,

Currently when @auto parses a c-file doxygen-like comments are treated separately from their associated functions.

For example, in the following function, @auto parsing treats these as separate nodes. Can you please point to where this can be fixed in the parser?

```c
/**
 * @brief Post error message to Max console.
 *
 * @param x pointer to object struct
 * @param fmt character string with format codes
 * @param ... other arguments
 */
void py_error(t_py* x, char* fmt, ...)
{
    char msg[PY_MAX_ELEMS];

    va_list va;
    va_start(va, fmt);
    vsnprintf(msg, PY_MAX_ELEMS, fmt, va);
    va_end(va);

    error("[py %s]: %s", x->p_name->s_name, msg);
}
```

**Comment by tbpassin** [comment]
Javascript and java may also have similar style comment blocks.

**Comment by edreamleo** [comment]
@shakfu Leo's new importers probably fix this issue. In c a `Block` starts at the end of the *previous* `Block` and continues to the the `}` that matches the opening `{`. So "leading" comments should be included in the correct block.

I'll close this issue. Please reopen if necessary.

**Comment by shakfu** [comment]
@edreamleo That's great! Thanks very much for your help on this issue.

**Comment by edreamleo** [comment]
@shakfu You're welcome. It was a pleasure working on the new importers.
