### ISSUE TITLE
Leo Does Not Return Memory After A Tab Is CLosed

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#3268]
I have noticed that Leo doesn't reduce its memory footprint after it closes a tab, at least in Windows.  To reproduce (on Windows):

1. Open a Leo instance from a console with only the workbook open;
2. Open the Windows Task Manager program. Identify the Python instance just opened and in the _Processes_ tab note its memory use.
3. Open LeoPyRef in the same Leo instance.  Note the increased  memory use.
4. Close the LeoPyRed outline, leaving Leo open.
5. Note that the memory use doesn't decline much if any.
6. Wait some period of minutes.  Note the memory use still has not decreased.

I don't know if the Qt call deleteLater() really does remove C++ Qt memory allocations, and if it doesn't there may not be much that we can do about this.

I recall reading a post several years ago about dealing with memory leaks in PyQt.  If I can find it again and learn something useful I'll post it here.

**Comment by tbpassin** [comment]
I found the link (thanks, tabbed bookmarks manager!):
[PyQt. How to shoot yourself in the foot.](http://enki-editor.org/2014/08/23/Pyqt_mem_mgmt.html)

It's interesting, probably important, but I'm not so sure that it will help with this particular issue.

**Comment by tbpassin** [comment]
I'll close this now, after discussion with ekr.  There is probably nothing to be done, it doesn't seem harmful, and if possible would take a major effort with no assurance of success.

**Comment by edreamleo** [comment]
@tbpassin I agree with your conclusion.
