### ISSUE TITLE
Create a way to unbind bindings in leoSettings.leo

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#327]
There is a hole in Leo's key-binding machinery. Afaik, there is no way to declare, say in myLeoSettings.leo, that a particular stroke should be treated as a plain key.

The typical key binding has the form:

`command-name = stroke`

The `do-nothing` command is not what we want. It eats the stroke entirely.

The setting `command = None` should remove any existing bindings to `command`.

**Comment by karstenw** [comment]
I think the magic should happen when:

```command-name = None```

is assigned.

That was what I expected would happen.

**Comment by edreamleo** [comment]
@karstenw Thanks for this comment. It's a reasonable thing to expect.  It may be tricky, but I'll try to make it happen.

**Comment by edreamleo** [comment]
Here are some notes copied from the to-do list.  They may not be accurate:

k.getPaneBinding uses only k.masterBindingsDict, so this dict is likely what must be cleared.

k.masterBindingsDict: Keys are scope names (2). Values are interior masterBindingDicts (3)

(2) Scope names are 'all','text',etc.
(3) Interior masterBindingDicts: Keys are strokes; values are ShortcutInfo objects.

So to clear an entry in k.masterBindingsDict, all inner dicts must be scanned.

**Comment by edreamleo** [comment]
**Note**: the commit comment for 34a560a should have referenced #547 instead of this issue.

**Comment by edreamleo** [comment]
Recent work on #510 impacts this issue.  Previously, k.registerCommand attempted the unbinding, but this is misguided.  Instead, unbinding should happen explicitly in Leo's startup logic.

**Comment by edreamleo** [comment]
I have just removed the "lvl:minor" label.  Imo, this issue is important.

My new strategy is to have command-name = none *remove* items from binding dictionaries. This will still require special cases, but would likely be more natural.  We shall see...

**Comment by edreamleo** [comment]
Rev 24da84a completes this item in a straightforward way.

The new k.killedBindings list a list of command names for which command-name = None appears outside of leoSettings.leo or myLeoSettings.leo. ParserBaseClass.doShortcuts adds items to this list. k.masterKeyHandler calls k.handleUnboundKeys if the command returned by k.getPaneBinding is on the list.

**Important**: mode commands have different names from standard command names, so user-defined modes should not be affected in any way by these changes.
