### ISSUE TITLE
Log message over-wrote part of previous error message

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#3271]
The new path-handling code over-wrote part of an error message about an unopened file.  See attached screen shot.

![leo-log-overwrite-screenshot](https://user-images.githubusercontent.com/36974235/230797113-8b194c85-f26a-4541-8443-471ea22964ca.png)

**Comment by edreamleo** [comment]
@tbpassin Thanks for this report.

Imo you probably found an existing problem that the new file code merely exposed. But I'll have a look at the diffs just to be sure :-)

**Comment by edreamleo** [comment]
@tbpassin This is a strange one. A cff shows that all the 'can not open' messages call one of the following:

    at.error, g.error, g.warning, g.es, g.es_print, and g.trace

I doubt that these methods would normally produce the error you show.

I'm going to close this issue. Please reopen if you can show how to reproduce the bug.
