### ISSUE TITLE
New path-handling code did not correctly construct path from `@path` node.

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#3272]
This may or may not be a duplicate of https://github.com/leo-editor/leo-editor/issues/3270.

The outline is in _C:\Tom\devel\leo\tabbed_apps_.  Outline nodes:
```
- @path browser_bookmarks2
    - @file ui.py
    - @file abstract_ui.py
    - @file controller.py
```
Leo seems to be ignoring the `@path` node completely:

```
can not open c:/tom/devel/leo/tabbed_apps/ui.py
can not open c:/tom/devel/leo/tabbed_apps/abstract_ui.py
can not open c:/tom/devel/leo/tabbed_apps/controller.py
```

**Comment by edreamleo** [comment]
@tbpassin I think this issue is a duplicate.

Anyway, PR #3277 contains unit tests that pass both this issue and #3270.
