### ISSUE TITLE
@string theme-name = None setting and --theme=None Do Not Do The Same Thing

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#3288]
If we put this setting into myLeoSettings.leo, we get the original unthemed Leo colors and fonts:

`@string theme-name = None `

 Some people, I think, prefer them.

However, if we specify the _None_ theme on the command line, then Leo uses the theme specified in myLeoSettings:

`leo --theme=None`

This difference is unexpected and therefore confusing.  There are times I would like to get the unthemed appearance, and I should be able to get it with the command line option for _None_, since that is what works in the settings.

**Comment by edreamleo** [comment]
@tbpassin Thanks for discovering yet another qwirp :-)

**Comment by tbpassin** [comment]
I am not sure what has changed , but today, looking at the code for setting themes, and trying out `--theme=None`, the issue does not appear.  With the `--theme=None`, the original no-theme appearance is used.  The code clearly does what I expected it should.

(if nothing has been changed in the theme code, it must have been operator error on my part).

So I'm closing this issue.

**Comment by tbpassin** [comment]
Whoops, spoke too soon.  The command-line setting doesn't over-ride the myLeoSetting value as I had expected
