### ISSUE TITLE
Mode File javascript.py Cannot Be Opened By Dragging Onto Tree Pane ...

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#3293]
... but it *can* be opened with File/Import.  This happens for a few other files, too, forth.py is another.  The error message is not very informative:

`Error reading ..\modes\javascript.py`

At a guess, these are (some of the) the mode files that were modified by the recent colorizer PR.

**Comment by edreamleo** [comment]
@tbpassin I recently converted 5 modes files to `@file` nodes:

    batch.py, forth.py, html.py, javascript.py, julia.py, python.py.

These files do not yet appear in `LeoPyRef.leo`. You can import them using `refresh-from-disk`.

Perhaps Leo's drag-and-drop code has problems with `@file` nodes, but presumably DnD is for files without sentinels.

**Comment by edreamleo** [comment]
@tbpassin Rev 1f0d8cd updates LeoPyRef.leo.  This should suffice to close this issue.
