### ISSUE TITLE
can @clean parse a perl script?

### ISSUE THREAD

**Issue by shizhaojingszj** [leo-editor/leo-editor#331]
Is there any plan to enhance the support for perl scripts?
I am newbie to leo-editor, I want to learn other people's code using leo-editor.
Python support is great, though perl is not.
The following is what i posted on [google groups](https://groups.google.com/forum/#!topic/leo-editor/jtYLG8pZyd0):

I have been using leo for a while and find it great to import and reorganize a python script.
However, when I import a perl file into a node, no subtrees are created, only the node containing all the script content.
1. The @language is properly set to perl, so I guess leo knows this is a perl file. I don't think this is the normal behaviour when importing a perl script. Am i correct about this? Is anybody using leo-editor for perl?
2. I try to see the LeoPyRef.leo for this importation functionality, the only thing seems related is leoImport.py, am i going the right direction?
3. There is a folder named modes, within it there is a perl.py, I guess this is the very script relating to "read" a perl script into leo-editor. In it, there are a lot of functions, so there must be a way to use these functions, why i cannot use them?

Please, give me a clue, any help will be appreciated....

Because GFW, I may not respond in time. Actually, this is my first post in google group, thanks for shadowsocks.

=== cut
Thank you very much, leo-editor is amazing.

**Comment by edreamleo** [comment]
On Wed, Oct 26, 2016 at 8:35 PM, Edward K. Ream <edreamleo@gmail.com> wrote:

> On Tue, Oct 25, 2016 at 10:33 PM, meng zhao <notifications@github.com>
> wrote:
>>
>> Is there any plan to enhance the support for perl scripts
>>
>
> That would require a perl importer.​
> ​ ​
> Please file an enhancement request.
>

​#332 <https://github.com/leo-editor/leo-editor/issues/332> is that
request. I'll get to this asap.

EKR

**Comment by edreamleo** [comment]
On Tue, Oct 25, 2016 at 10:33 PM, meng zhao <notifications@github.com>
wrote:

> Is there any plan to enhance the support for perl scripts?
>
​That would require a perl importer.​ This is easier now that importers
import code line-by-line rather than character-by-character. This new
approach makes writing a javascript importer possible without knowing much
of anything about javascript.  The same approach should work well for perl.

Please file an enhancement request.

> However, when I import a perl file into a node, no subtrees are created,
> only the node containing all the script content.
>
​That's because Leo does not yet have a perl importer.​

> 1. The @language <https://github.com/language> is properly set to perl,
> so I guess leo knows this is a perl file.
>
​@language perl affects only syntax coloring.​

> 2. I try to see the LeoPyRef.leo for this importation functionality, the
> only thing seems related is leoImport.py, am i going the right direction?
>
​leoImport.py contains (complex) infrastructure for importers.  The actual
importer code is in leo/plugins/importers.  You can see the code in
LeoPluginsRef.leo.​


> 3. There is a folder named modes, within it there is a perl.py
> ​.
>
> ​Modes are rules for syntax coloring.​

HTH.

Edward

**Comment by edreamleo** [comment]
On Tue, Oct 25, 2016 at 10:33 PM, meng zhao <notifications@github.com>
wrote:

​> ​
Is there any plan to enhance the support for perl scripts?

​Rev b27084d adds a perl importer. You should be able to do this:

   @auto x.pl

EKR

**Comment by edreamleo** [comment]
I am going to close this.  Please reopen if there are problems with the new perl importer.
