### ISSUE TITLE
Remove 0x9d character from leo/commands/editCommands.py?

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#3315]
Line 2096 of `leo/commands/editCommands.py` contains an `0x9d` character. `git diff` shows the original line as follows:

    ch = 'â€™' if ch == "'" else "â€"

The line appears in Leo as:

    ch = '’' if ch == "'" else "”"

Apparently closing double quotes (unicode code point `201d`) was intended.

Leo reads this file properly, but *perhaps* this character should not be allowed. See [this post](https://stackoverflow.com/questions/45749093).

I am going to close this issue.  The following suffices to read the file:

- Read the file in `rb` mode.
- Convert the resulting bytes to unicode via `g.toUnicode`.

**Comment by edreamleo** [comment]
@tbpassin I discovered this problem while attempting to read the file with 'r' mode:
```python
with open(filename, 'r') as f:
    contents = f.read()
```
This throws a `UnicodeDecodeError`. It's mysterious.  The following works and is (roughly) what Leo does:
```python
with open(path, 'rb') as f:
    source = g.toUnicode(f.read())
```

**Comment by tbpassin** [comment]
I wonder if opening it with the encoding arg would work.  I thought it defaulted to utf-8, but maybe it's not doing that for some reason.  Sometimes I get a warning when I don't use an encoding arg, which seems strange if it has a default.
