### ISSUE TITLE
Check if QtSvg really imported 

### ISSUE THREAD

**Issue by boltex** [leo-editor/leo-editor#3320]
Closed via PR #3323.

Leo should before showing the splash screen at startup and abstain from using the QSvgRenderer to display the splash screen altogether (which hard-crashes) and just act like the `--no-splash` option was set. (maybe print/g.es a message stating this small override happened)

I propose this small change because after experimenting with trying to install Leo-Editor on an official Debian Raspberry Pi OS, this was the only error (Which i circumvented with the `--no-splash` option) that prevented the successful startup after following the installation instructions.

**Comment by edreamleo** [comment]
Closed via #3323.
