### ISSUE TITLE
--no-plugins  option does not disable all plugins

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#3321]
Start Leo with:
>launchleo.py --no-plugins

Leo starts and all plugins are still active.

However start Leo with:
>python launchleo.py --no-plugins

The plugins are disabled. If LeoSettings.leo is used behaviour is the same.

_Leo 6.7.3-devel, devel branch, build 400825e1d2
2023-05-05 05:55:59 -0500
Python 3.11.3, PyQt version 6.5.0
Windows 10 AMD64 (build 10.0.19044) SP0_

**Comment by edreamleo** [comment]
I am going to close this issue. Starting Leo with `python launchLeo.py` is correct.
