### ISSUE TITLE
'launchleo.py' and 'python launchleo.py' behaviour is not consistent

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#3322]
Start Leo with:

    launchleo.py --no-splash

Leo starts and shows splashscreen.

However start Leo with:

    python launchleo.py --no-splash

The splashscreen is disabled. Using python before launchleo.py affects behaviour of other command-line options such as --quit and --help. See #3321

**Comment by tbpassin** [comment]
I don't even have a launchleo.py.  Where does that live?

If launchleo were a batch file, it might be missing higher-numbered command line arguments than 1.  IOW, it could have been written without a "%*" or even a "%1".  But as a .py file that wouldn't be the case.

**Comment by LewisNeal** [comment]
It's in the top level folder: leo-editor. See https://leo-editor.github.io/leo-editor/running.html

**Comment by tbpassin** [comment]
I see it now.  Somehow I missed it yesterday even though I looked there.

I almost always start Leo with 

`python -m leo.core.runLeo`

This picks up all the command line arguments, and uses the method behind launchLeo and some other launchers.  It works from any directory.

For working in Git branches, I use a batch file that sets PYTHONPATH to point to my Git clone, then runs Leo with the above command.  This way I don't have to cd to the clone directory first.

**Comment by edreamleo** [comment]
@LewisNeal I am going to close this issue and the related #3321.

Imo These are installation issues of no significance. On my machine, typing `launchLeo.py` opens the file instead of executing it.

Anyway, the workaround is straightforward, as Thomas explains.
