### ISSUE TITLE
Render asciidoc and pandoc in VR pane

### ISSUE THREAD

**Issue by technatica** [leo-editor/leo-editor#333]
I have been searching for a Sphinx editor with preview, with little success. 

**EKR**: There is no such thing as a Sphinx editor.  Sphinx uses reStructuredText as its markup language. So what you want is a rST editor.

Leo's VR pane already creates a live view of rST. [This post](https://groups.google.com/d/msg/leo-editor/hwE6ZRnjjxc/auevhMIzBwAJ) discusses how to use external programs such as asciidoctor (a Ruby tool) to update the VR pane.  Imo, this should be good enough.

I am going to hide various comments.  I think the VR pane can handle this easily.

**Comment by edreamleo** [comment]
Thanks for the link.  The project looks well worth doing.

**Comment by technatica** [comment]
http://pymolurus.blogspot.ca/2012/01/documentation-viewer-for-sphinx.html

Another way of approaching the matter. I like the standalone 128 lines of code PyQt web browser he uses for the output. Both of these tools run under python2/pyqt 4.8.7.

**Comment by technatica** [comment]
So here is a hack.

1. pip3 install sphinx-autobuild
2. Create Sphinx project directory for the document. eg. mkdir mySphinx
3. Navigate to ../mySphinx
4. Execute sphinx-autobuild source build
5. Import ../mySphinx/source/index.rst into Leo
6. Create node with the following in the body
```
@language html
<a href="http://127.0.0.1:8000/">Link</a> 

```
7. Alt-0 to open vr pane. Click the "Link" to open the webpage.
8. Plugins, viewrendered, vr-lock to lock the vr pane to the url node
9. Make your edits to ../mySphinx/source/index.rst

Everytime you save the document, it refreshes in the vr pane.

This is not live viewing, but it is better than nothing.

**Comment by edreamleo** [comment]
On Sat, Mar 31, 2018 at 12:13 PM, Chris George <notifications@github.com>
wrote:

> So here is a hack.
>
​Thanks for this.  ​Have you created an @button node?  If so, the @button
node would be the prototype for a command. The command would get the
directory from a Leo setting.

Finally the VR plugin could execute that command periodically for (say)
@sphinx nodes.

Edward

**Comment by technatica** [comment]
The viewrendered plugin no longer supports this workflow.

I attempted to use it with the Leo documentation and setup the link node as:

`@language html
<a href="http://127.0.0.1:8000/leo_toc.html">Link</a>`

The link is displayed in the render pane but clicking it does nothing. Back when I was working on this it worked great. The URL displays correctly in a web browser using sphinx-autobuild.

I am going to play with the pyzo browser dock and see what can be accomplished. 

Unlike when I first posted this, there is now exactly one other editor with sphinx live preview ability. Someone wrote an atom plugin to do so.

**Comment by edreamleo** [comment]
I'll reopen this issue.  Recent changes were probably too aggressive in not-rendering unwanted text.

**Comment by edreamleo** [comment]
I suspect sphinx-autobuild is overkill.  Instead, the VR code should be able to rebuild whenever p.b changes.  Failing that, @sphinx could work like @rst, and Leo could have a sphinx command that works like rst3.  The rst3 code is too complex.  the sphinx command should be much simpler.

**Comment by edreamleo** [comment]
I'm going to take this off the "First" list for awhile.  It's time to fix the remaining bugs.

**Comment by technatica** [comment]
I use the rst3 command in LeoDocs.leo to output the *.html.txt files into the html directory.

Then I run `sphinx-autobuild . build` to generate the html files and start the server.

In an open Leo file, I add:

`@language html
<a href="http://127.0.0.1:8000/leo_toc.html">Link</a>
`
The rendered pane remains blank. I hit Alt-0 and it closes the render pane. I hit it again and nothing happens. I right-click the title bar of the body pane and check render to display the pane and it remains blank.

So I save and close the .leo file. Then I open it again and navigate to the node. The render pane now displays `Link`. Clicking the link nets me a blank render pane again.

The previous behavior (back when I created the workflow) would display the leo_toc.html file. Editing the leo_toc.html.txt and saving changes would cause sphinx-autobuild to render the sphinx markup and refresh the leo_toc.html file and display the new content in the render pane.

Conceptually I think that it would be better to use a straight-up web browser widget like the pyzo one for html and family instead of trying to make viewrendered into the swiss army knife.

Or code it to treat sphinx markup the same as rst and markdown. This convert to html and display workflow is an ugly hack that now doesn't work.

Going to http://127.0.0.1:8000/leo_toc.html in a web browser works great.

**Comment by edreamleo** [comment]
On Tue, Sep 24, 2019 at 10:16 AM Chris George <notifications@github.com>
wrote:

>
> @language html <a href="http://127.0.0.1:8000/leo_toc.html">Link</a>
>

These should be on two separate lines:

@language html
>
<a href="http://127.0.0.1:8000/leo_toc.html">Link</a>
>

Edward

**Comment by technatica** [comment]
They are
The @language html is the first line. The link is line three.

**Comment by technatica** [comment]
The pyzo web browser is pretty primitive but it works to display the sphinx-autobuild server page. I can edit the leo_toc.html.txt file and when I save it I have to reload the webpage (no refresh) to see the changes but it works.

**Comment by maphew** [comment]
https://asciidoctor.org/docs/editing-asciidoc-with-live-preview/ describes a couple methods of monitoring the filesystem for changes and auto-reloading the html page. It's focussed on Asciidoc of course but they sound generic enough to apply anywhere.

**Comment by edreamleo** [comment]
Done in recent revs.
