### ISSUE TITLE
find_def() in LeoFind still contains an assert

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#3332]
In case we are still trying to avoid asserts, `find_def()` still has one:
```
    # Check.
    word = self._compute_find_def_word(event)
    if not word:
        return None, None, None
    # Settings...
    self._save_before_find_def(p)  # Save previous settings.
    assert self.find_def_data              # <===========
```

**Comment by edreamleo** [comment]
@tbpassin I've given up trying to delete all asserts, but I welcome being alerted to asserts that seem dubious. I'll take a look at this one.

**Comment by edreamleo** [comment]
I am going to close this issue. The assert is unlikely to fail, and it's a kind of comment.
