### ISSUE TITLE
AtButtonCallback

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#3333]
I see several AtButtonCallback messages in Console:

_registerCommand redefining @button-Show-Clones AtButtonCallback workbook.leo gnx: lewis.20191008120114.1 len(script): 280 -> AtButtonCallback workbook.leo gnx: lewis.20220219160105.1 len(script): 0_

Leo 6.7.4-devel, devel branch, build 4d6ee964f4
2023-05-12 08:33:38 -0500
Python 3.11.3, PyQt version 6.5.0
Windows 10 AMD64 (build 10.0.19044) SP0

**Comment by edreamleo** [comment]
The message is likely correct. Your setup likely contains two definitions of the button.

**Comment by LewisNeal** [comment]
Yes it was due to buttons in myLeoSettings.leo being duplicated in another leo file.

**Comment by edreamleo** [comment]
@LewisNeal Thanks for your feedback.
