### ISSUE TITLE
Unresolved @constants message to Console

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#3334]
#3676 is the same issue.

Running Leo with leoSettings.leo only I get message to console:

_Leo 6.7.4-devel, devel branch, build 4d6ee964f4
2023-05-12 08:33:38 -0500
Python 3.11.3, PyQt version 6.5.0
Windows 10 AMD64 (build 10.0.19044) SP0
expand_css_constants Unresolved @constants
['@screencaset-font-style', '@screencast-font-family', '@screencast-font-weight', '@screencaset-font-size']
expand_css_constants Unresolved @constants
['@screencaset-font-style', '@screencast-font-family', '@screencast-font-weight', '@screencaset-font-size']_

**Comment by edreamleo** [comment]
I don't see this behavior. It is likely an issue with with your theme file.

**Comment by LewisNeal** [comment]
The problem is not with my theme file as I had disabled myLeoSettings.leo and was using leoSettings.leo file.

In leoSettings.leo I found 3 typos of 'screencaset' rather than 'screencast':
1 typo in Qt Gui settings-->Plugins-->screencast.py plugin-->@font screencast
and 2 typos in @data qt-gui-plugin-style-sheet-->Plugins-->Screencast plugin

**Comment by edreamleo** [comment]
@LewisNeal Thanks for this.

**Comment by edreamleo** [comment]
I am going to continue this issue in #3676.
