### ISSUE TITLE
Command edit-settings fails to recognize font settings

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#3337]
See PR #3880.

With this node in a theme outline selected: `@string font-size-ui = 9.5pt`, got this message:

```
Commander 2599950696976: 'C:/Tom/git/leo-editor/leo/themes/tbp_light.leo'
not in a setting node
```
Running the command on an `@color` node opened the color picker.
```
Leo 6.7.4-devel, devel branch, build 4d6ee964f4
2023-05-12 08:33:38 -0500
Python 3.11.3, PyQt version 6.4.3
Windows 10 AMD64 (build 10.0.19044) SP0
```

Maybe 
```
    if p.h.startswith('@string font-family'):
        func = c.commandsDict.get('show-fonts')
```
?

I should have said that I got this after I put in the fix suggested in #3336.

**Comment by edreamleo** [comment]
@Thanks for this report.  I'll investigate.

**Comment by tbpassin** [comment]
> `if p.h.startswith('@string font-family'):`

There are a number of other font-related settings, so maybe it should read

`if p.h.startswith('@string font-'):`
