### ISSUE TITLE
Recent Leo freezes upon startup after multiple ctrl-c

### ISSUE THREAD

**Issue by mystica555** [leo-editor/leo-editor#335]
As posted in the forum, but with no reply at all (I'd have hoped someone atleast would say "same here" or "nope not for me") I'm experiencing freezing issues with Leo. 

This affects 5.4 release as well, but not a 5.4 beta git pull, from July:
Leo 5.4-devel, build 20160722143100, Fri, Jul 22, 2016  2:31:00 PM
Git repo info: branch = master, commit = aca8d416ec35
Python 2.7.10, PyQt version 4.8.7
linux2

So within these 2 months between July 22 and October 22, something has broken. My July22 copy still works fine to this day. 

I'm not seeing anything when searching chronologically in the Group here for "eventfilter" but its been coming up for me me recently as an issue.

As I read a bit earlier on the group, if you ctrl-c, you get traceback data. I did just this, and found that repeatedly pressing ctrl-c lead to the issue progressing forward past the initial 'frozen state'.  If you want, I could take a screencapture video, it just takes a bit to setup but does illustrate the issue a lot better.  Hoping perhaps you've seen it so I'm typing a quick note first. 

I launch Leo,  and the following is the backtrace data during multiple control-C events. I saw more of the GUI show up, but still the end state was a frozen Leo. 
I'll make a video for you a bit later today after I finish some work at the datacenter, but in my attempt to install a new Leo on my new laptop vs an older one on a much worse laptop (although not much older...just horrid lack of enough thermal dissipation causing near constant 200 to 500mhz throttling, down from 1800) I came across this problem.

Confirming on my desktop which works peachy with older Leo:
Leo Log Window

Leo 5.4-devel, build 20160722143100, Fri, Jul 22, 2016  2:31:00 PM

Git repo info: branch = master, commit = aca8d416ec35

Python 2.7.10, PyQt version 4.8.7
linux2

setting leoID from os.getenv('USER'): 'mike'

load dir: /home/mike/leo-editor/leo/core

global config dir: /home/mike/leo-editor/leo/config

home dir: /home/mike

reading settings in /home/mike/leo-editor/leo/config/leoSettings.leo

Using default leo file name:
/home/mike/.leo/workbook.leo

reading settings in /home/mike/leo-editor/leo/doc/CheatSheet.leo

But then with the new Git master, it freezes. Same python.

I'll do a new strace (had older data, and a different scenario of how it failed before updating GIT just today, November 10th.. It seemed to fail slightly differently about 3 days ago when I first started this message)

If I do something like: click away the splash screen, move the window to my other monitor, and then full-screen resize it from a window, pressing ctrl-c a few times in the terminal adjacent to it causes the "frozen" Leo to then resize, and somewhat progress in the continuation of its main loop, but it keeps getting stuck.

It should be noted, that fullscreen capture of this is considerably draining on my CPU on the desktop here, so it was a lot harder to ctrl-c it at the right point in its loop to break out and continue with the GUI updating. Then after the last time, i hit ctrl-c a few times too many, and held it down, and finally Leo caught the interrupt and quit. Without ffmpeg going full-out, I was able to trigger the "continuation" within about 3-4 non-held-down-to-repeat ctrl-c presses.

Here is the problem in action... https://youtu.be/cAgxr-dO74E - Screen recording of the problem in progress.

And the output of all that text you see scrolling by... https://bpaste.net/show/8fe126429c0f

Please let me know what else you may need.

Again, this is affecting everything including the 5.4 release as downloaded from Sourceforge in a ZIP, as well as Github pulls of recent vintage.

**Comment by tbnorth** [comment]
On Fri, 11 Nov 2016 14:00:49 -0800
Mike Hodson <notifications@github.com> wrote:

> As posted in the forum, but with no reply at all (I'd have hoped
> someone atleast would say "same here" or "nope not for me") I'm
> experiencing freezing issues with Leo. 

Hi Mike,

Saw your video, very odd.  Not seeing it with current Leo in Ubuntu
16.04 or Win 7.

Any difference if you launch Leo via

HOME=/tmp python launchLeo.py

?  Also how does Python 3.x go, if that's not too inconvenient to test?

Cheers -Terry

> This affects 5.4 release as well, but not a 5.4 beta git pull, from
> July: Leo 5.4-devel, build 20160722143100, Fri, Jul 22, 2016  2:31:00
> PM Git repo info: branch = master, commit = aca8d416ec35
> Python 2.7.10, PyQt version 4.8.7
> linux2
> 
> So within these 2 months between July 22 and October 22, something
> has broken. My July22 copy still works fine to this day. 
> 
> I'm not seeing anything when searching chronologically in the Group
> here for "eventfilter" but its been coming up for me me recently as
> an issue.
> 
> As I read a bit earlier on the group, if you ctrl-c, you get
> traceback data. I did just this, and found that repeatedly pressing
> ctrl-c lead to the issue progressing forward past the initial 'frozen
> state'.  If you want, I could take a screencapture video, it just
> takes a bit to setup but does illustrate the issue a lot better.
> Hoping perhaps you've seen it so I'm typing a quick note first. 
> 
> I launch Leo,  and the following is the backtrace data during
> multiple control-C events. I saw more of the GUI show up, but still
> the end state was a frozen Leo. I'll make a video for you a bit later
> today after I finish some work at the datacenter, but in my attempt
> to install a new Leo on my new laptop vs an older one on a much worse
> laptop (although not much older...just horrid lack of enough thermal
> dissipation causing near constant 200 to 500mhz throttling, down from
> 1800) I came across this problem.
> 
> Confirming on my desktop which works peachy with older Leo:
> Leo Log Window
> 
> Leo 5.4-devel, build 20160722143100, Fri, Jul 22, 2016  2:31:00 PM
> 
> Git repo info: branch = master, commit = aca8d416ec35
> 
> Python 2.7.10, PyQt version 4.8.7
> linux2
> 
> setting leoID from os.getenv('USER'): 'mike'
> 
> load dir: /home/mike/leo-editor/leo/core
> 
> global config dir: /home/mike/leo-editor/leo/config
> 
> home dir: /home/mike
> 
> reading settings in /home/mike/leo-editor/leo/config/leoSettings.leo
> 
> Using default leo file name:
> /home/mike/.leo/workbook.leo
> 
> reading settings in /home/mike/leo-editor/leo/doc/CheatSheet.leo
> 
> But then with the new Git master, it freezes. Same python.
> 
> I'll do a new strace (had older data, and a different scenario of how
> it failed before updating GIT just today, November 10th.. It seemed
> to fail slightly differently about 3 days ago when I first started
> this message)
> 
> If I do something like: click away the splash screen, move the window
> to my other monitor, and then full-screen resize it from a window,
> pressing ctrl-c a few times in the terminal adjacent to it causes the
> "frozen" Leo to then resize, and somewhat progress in the
> continuation of its main loop, but it keeps getting stuck.
> 
> It should be noted, that fullscreen capture of this is considerably
> draining on my CPU on the desktop here, so it was a lot harder to
> ctrl-c it at the right point in its loop to break out and continue
> with the GUI updating. Then after the last time, i hit ctrl-c a few
> times too many, and held it down, and finally Leo caught the
> interrupt and quit. Without ffmpeg going full-out, I was able to
> trigger the "continuation" within about 3-4 non-held-down-to-repeat
> ctrl-c presses.
> 
> Here is the problem in action... https://youtu.be/cAgxr-dO74E -
> Screen recording of the problem in progress.
> 
> And the output of all that text you see scrolling by...
> https://bpaste.net/show/8fe126429c0f
> 
> Please let me know what else you may need.

**Comment by technatica** [comment]
I just completed a complete reinstall of OS and Leo.

No problems running the bleeding edge Leo on python 3.5.2 and PyQt 5.6.0 in
an Anaconda install with a LXQT desktop environment. I will test your
configuration (Python 2.7.10, PyQt version 4.8.7) when I setup my python2
environment later.

Have you tried upgrading python to 2.7.12? Or is there a requirement for
that version of python?

Chris

**Comment by edreamleo** [comment]
On Fri, Nov 11, 2016 at 4:00 PM, Mike Hodson <notifications@github.com>
wrote:

> As posted in the forum, but with no reply at all (I'd have hoped someone
> atleast would say "same here" or "nope not for me") I'm experiencing
> freezing issues with Leo.
>
​Sorry for the delay in responding.  I haven't had a chance to look at this.

Clearly, Leo does *not* typically freeze during startup.  It it did,
everyone would be screaming.

The title of this post doesn't mention that you must hit Ctrl-C multiple
times. I suspect people looked at the title and thought, "no, that can't be
correct." :-)

There have been changes to eventFilter in the last several months.  Iirc,
they were relating to tracing. It looks like they had unintended
consequences.

Are you willing to do a git bisect to find the offending commit?  That
would be most helpful.

Edward

**Comment by mystica555** [comment]
Hi Edward,

I'll try bisecting later today, considering I don't have to -recompile-
every bisect like I did with LEDE to fix my Wifi, it'll be a much happier
and shorter process for me!

Thanks,

Mike

**Comment by edreamleo** [comment]
I am going to close this item for now.  Please reopen if necessary.
