### ISSUE TITLE
Local plugin enable prevents the appearance of the "Plugins" menu in the menu bar

### ISSUE THREAD

**Issue by SegundoBob** [leo-editor/leo-editor#3352]
### Issue Severity
This is a very low severity problem.  It is a minor inconvenience for me.

### Test File
[local_plugin_enable.leo.zip](https://github.com/leo-editor/leo-editor/files/11502931/local_plugin_enable.leo.zip) contains the very small test file which demonstrates this problem.

### Required Plugin Enable
To see this problem, you must enable in your myLeoSettings.leo  plugin plugins_menu.py, which creates the "Plugins" menu on the menu bar.

### Three Cases
There are three cases:  

1) No Leo-Editor command line options.

2) Leo-Editor command line option "--trace" without its required option specifier. 

3) Leo-Editor command line option "--trace xxxx"

### Cases 1 and 2
It doesn't matter if an existing or non-existent plugin is specified. Add "xxx" to the beginning or end of the plugin-specification line to specify a non-existent plugin.

 If an existent plugin is specified, it is enabled.

If a nonexistent plugin or none at all is specified (Put a "#" at the start of the plugin-specification line.), no error is reported.   But in all the above cases, there is no "Plugins" menu in the menu bar.

### Case 3
But if the "--trace xxxx" Leo-Editor command line option is used where xxxx is any valid or invalid option, then the "Plugins" menu does appear in the menu bars of both files.

Both files because due to another bug which I am reporting, Leo-Editor treats the option specification xxxx as the root name of a Leo-Editor file xxxx.leo, which it opens.

The most useful trace option to use in these tests is "--trace plugins".

**Comment by edreamleo** [comment]
@SegundoBob I don't understand this issue. The format for the `--trace` option is `trace=xxx`, not `trace xxx`.

Furthermore, `--trace=plugins` works as expected.

**Comment by edreamleo** [comment]
@SegundoBob The solution is to add `plugins_menu.py` to the `@enabled_plugins` node.

I am going to close this issue.

**Comment by SegundoBob** [comment]
Edward,

OK.  as I noted, the issue is very minor.  I'm sorry that I my report isn't clear enough for me to now understand the issue.  I'm too busy to spend any time on it now.  Closing it is appropriate.

If --trace is parsed by argparse, then "--trace=xxx" and "--trace xxx" are equivalent.

-----
SegundoBob

**Comment by edreamleo** [comment]
@SegundoBob Thanks for your comment. I didn't know that about argparse!
