### ISSUE TITLE
Optionally store lists of strings in vnodes

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#336]
The new Importer class stores all intermediate results in v._import_lines.  This is *hugely* more efficient than repeatedly calling `p.b = p.b + s`.

Similarly, a `p.lines` (and `v.lines`) properties would be useful.  Instead of doing:

    p.b = ''.join(result)

the code could just do:

    p.lines = result

In some cases, this could eliminate some *large* temporary strings.

The `p.b` and `p.lines` getters and setters must work together so that client code works regardless of whether body text happens to be stored as lines or strings at any instant.

**Comment by vitalije** [comment]
I like this idea very much. I have created branch v-lines and implemented basic properties p/v .lines. I also added one Leo document with few unit tests that are testing new properties. All unit tests pass both in unitTest.leo and new ones.
I believe this properties can simplify greatly Leo's code throughout core. Let us try to invent test case that will make those properties to go out of sync for a week or two and if nothing can be found, maybe we can merge it in core and start simplifying part by part. 

The only way I can imagine (at least for now) to break synchronization between `lines` and `b` properties is by using `v._bodyString` directly. There are some places in Leo's code that use this pattern, but I hope we can hunt them down and set new `v._sync` attribute in those places accordingly.

**Comment by edreamleo** [comment]
On Fri, Jul 14, 2017 at 3:37 PM, Виталије Милошевић <
notifications@github.com> wrote:

> I like this idea very much. I have created branch v-lines and implemented
> basic properties p/v .lines. I also added one Leo document with few unit
> tests that are testing new properties. All unit tests pass both in
> unitTest.leo and new ones.
>
​Thanks for this.​

> I believe this properties can simplify greatly Leo's code throughout core.
> Let us try to invent test case that will make those properties to go out of
> sync for a week or two and if nothing can be found, maybe we can merge it
> in core and start simplifying part by part.
>
​I'm not sure that will work, because...

> The only way I can imagine (at least for now) to break synchronization
> between lines and b properties is by using v._bodyString directly. There
> are some places in Leo's code that use this pattern, but I hope we can hunt
> them down and set new v._sync attribute in those places accordingly.
>
​Replacing v._bodyString in Leo's core would be a start, but other code, of
which we are not aware, ​might use v._bodyString.

In other words, we haven't explicitly promised not to change v._bodyString,
but we might break existing code by doing so.  Maybe we should ask if
anyone would object to that change.

Edward

**Comment by vitalije** [comment]
> Maybe we should ask if anyone would object to that change.

Of course, but whoever uses directly `_bodyString`, and don't use new `lines` property should be pretty safe. The only way to see the problem is if one uses new property `lines` to read lines and someone has set `_bodyString` directly.

**Comment by edreamleo** [comment]
On Fri, Jul 14, 2017 at 4:32 PM, Виталије Милошевић <
notifications@github.com> wrote:

> Maybe we should ask if anyone would object to that change.
>
> Of course, but whoever uses directly _bodyString, and don't use new lines
> property should be pretty safe. The only way to see the problem is if one
> uses new property lines to read lines and someone has set _bodyString
> directly.
>
​Thanks for the clarification.  In that case, the warning you have just
given should suffice.

Edward

**Comment by tbnorth** [comment]
Does `p.b = ''.join(result)` create a temporary string?

If body is stored as lines, does every call to p.b (getter) do the join, or does the first one trigger the join to be computed and stored?

I can see it as a convenient shortand, but not a perf. boost switching internal storage format on the fly.

Ah, unless you're storing both, in-sync.  Then you avoid a split() by using the p.lines getter... but that doesn't seem to be the pattern suggested above.

Perhaps it is that you store both, tracking which is current, and only updating the other on demand?

**Comment by vitalije** [comment]
> Perhaps it is that you store both, tracking which is current, and only updating the other on demand?

That's it. Vnode has two more ivars one is _bodyLines which contains tuple of unicode lines and the second is _sync which can have three values (None, 'body', 'lines'). Synchronization is done one first read access on any property that is not yet synced. Here is one of the tests:
```python
p1 = p.insertAsLastChild()
try:
    assert p1.v._sync is None, '_sync should be None'
    lns = ('1\n', '2\n', '3\n')
    p1.lines = lns
    assert p1.v._sync is 'body', '_sync should be body'
    s = p1.b
    assert p1.v._sync is None, '_sync should be now None'
    p1.b = s
    assert p1.v._sync is None, '_sync should be still None'
    p1.lines = lns
    assert p1.v._sync is None, '_sync should be still None'
    p1.b = s + '4'
    assert p1.v._sync is 'lines', '_sync should be lines'
    lns2 = p1.lines
    assert p1.v._sync is None, '_sync should be now None'
finally:
    p.deleteAllChildren()
```
As you can see. Whenever _bodyString and _bodyLines are in sync, _sync is None. Any set to lines (if value is actually different) turns _sync to 'body' indicating that _bodyString should be synced on next read. Whenever v.b is set then _sync is turned to 'lines' indicating that _bodyLines should be synced on next read.

> but that doesn't seem to be the pattern suggested above.

Maybe I didn't understood the suggestion, but I liked very much idea of having v.lines property.
For all cases where Leo is setting directly _bodyString it will be enough just to add `v._sync='lines'` after and nothing else needs to be changed. Later, however, those two successive lines must be kept together at all times. Perhaps we can use private method `v._setBody` which should do just that set _bodyString and _sync without any checks. That can be replacement for all current uses of `v._bodyString =...`

**Comment by xgid** [comment]
Those are really clever ideas.

Just a minor detail: wouldn't it be better to rename `v._sync` to `v._toSync` or even `v._out_of_sync`? I think it would better express its intent/meaning, don't you?

**Comment by edreamleo** [comment]
On Sat, Jul 15, 2017 at 1:19 AM, Виталије Милошевић <
notifications@github.com> wrote:

Vnode has two more ivars one is _bodyLines which contains tuple of unicode
> lines and the second is _sync which can have three values (None, 'body',
> 'lines').


​I've taken a look at the v-lines branch.  It looks good. And the code is
simpler than the explanations :-)  Two minor suggestions:

1. I don't think it's wise to call g.internalError in v.setBodyString
because scripts could call v.setBodyString.

2. g.isString(s) should always be true on both Python 2 and 3 which may
simplify the code.  The following is completely untested. Use it, adapt it,
or reject it, as you please:

def setBodyString(self, s):
    v = self
    if g.isString(s):
        s = g.toUnicode(s, reportErrors=True)
        if v._bodyString != s or v._sync == 'body':
            v._bodyString = s
            v._sync = 'lines'
    elif not self.body_string_warning_given:
        self.body_string_warning_given = True
        g.es_print(
            'non-string argument to v.setBodyString: %r' % (s),
            color='red',
        )

Edward

**Comment by vitalije** [comment]
> don't think it's wise to call g.internalError in v.setBodyString because scripts could call v.setBodyString.

git blame for this line gives: https://github.com/leo-editor/leo-editor/commit/261a50064ab74d2f274c01d723fcd64d888899d5 (roughly 2 years ago). I just copied this parts in new methods because I didn't know they were unnecessary. I disliked them myself, and thought they have to be present because compatibility with some features from long ago.

@xgid 
> wouldn't it be better to rename v._sync to v._toSync or even v._out_of_sync? 

Perhaps, but I prefer shorter name and it is not intended to be any mention of that attribute anywhere outside VNode class. I believe one comment line would be enough to document its possible values and the rest will be obvious from reading code, I guess.

**Comment by edreamleo** [comment]
On Sun, Jul 16, 2017 at 7:11 AM, Виталије Милошевић <
notifications@github.com> wrote:

> don't think it's wise to call g.internalError in v.setBodyString because
> scripts could call v.setBodyString.
>
> git blame for this line gives: 261a500
> <https://github.com/leo-editor/leo-editor/commit/261a50064ab74d2f274c01d723fcd64d888899d5>
> (roughly 2 years ago).
>
​Huh? What does this commit have to do with v.setBodyString or
g.internalError?

Edward

**Comment by vitalije** [comment]
Sorry, I copied wrong link and didn't explain myself very well. You suggested that it was not wise to call g.internalError inside setBodyString. However, that call was present at the beginning of my changes in this branch. So I have opened leoNodes.py on github page and clicked button 'Blame' and it gives for each line of leoNodes.py commit in which that line appeared. I have just copied wrong link. The correct one is https://github.com/leo-editor/leo-editor/commit/6bf6ae0d9e288dc7ce82caeb9409bf0c1f4e71a7 and it is about 4 months old.

In case I copied again wrong link, to put it simple I haven't write that line and I would be glad to get rid of it :wink:.

**Comment by xgdomingo** [comment]
>     wouldn't it be better to rename v._sync to v._toSync or even
>     v._out_of_sync?
>
> Perhaps, but I prefer shorter name and it is not intended to be any 
> mention of that attribute anywhere outside VNode class. I believe one 
> comment line would be enough to document its possible values and the 
> rest will be obvious from reading code, I guess.
>
OK, maybe I was being too meticulous for a private attribute. I just try 
to make every method or attribute self-explanatory, but sure it's not so 
important if all is properly documented in comments, if you care 
comments don't get out-of-sync with the code! ;-)

**Comment by edreamleo** [comment]
On Sun, Jul 16, 2017 at 8:47 AM, Виталије Милошевић <
notifications@github.com> wrote:

> Sorry, I copied wrong link and didn't explain myself very well. You
> suggested that it was not wise to call g.internalError inside
> setBodyString. However, that call was present at the beginning of my
> changes in this branch.
>
​I see.  My present opinion is that my original call to g.internalError is
misguided.

g.internalError provides a pretty clear traceback.  But the message itself
is misleading because scripts outside of Leo's core could call
v.setBodyString.

In short, in addition to the statement:

    g.es_print(
        'non-string argument to v.setBodyString: %r' % (s),
        color='red',
    )

I recommend adding this line:

    g.es_print(g.callers(6))

Edward

**Comment by vitalije** [comment]
Done at ebe6e7679

**Comment by tbnorth** [comment]
@vitalije thanks for the explanation, makes sense now.  My comment about not following the pattern referred to my interpretation of this current discussion, not the original proposal.  So this all seems fine, I'll assume you and Edward are aware of enough use of body content as lines to make this beneficial, perhaps that's in the read code I haven't look at much.

Hmm, I think I've more than once written code that modifies the Qt widget content directly... but that code either relies on a subsequent regular change (typing) of the widget to make the changes stick, or also calls p.b = x as well, either way, I guess it's not affected by this.

Also in the leo_edit_pane branch I'm emitting a signal from assigns to p.b, but I don't think there's any issue there either, except needing to emit it from assigns to p.lines too.

**Comment by edreamleo** [comment]
On Sun, Jul 16, 2017 at 10:34 AM, Terry Brown <notifications@github.com>
wrote:

> @vitalije <https://github.com/vitalije> thanks for the explanation, makes
> sense now. My comment about not following the pattern referred to my
> interpretation of this current discussion, not the original proposal. So
> this all seems fine, I'll assume you and Edward are aware of enough use of
> body content as lines to make this beneficial, perhaps that's in the read
> code I haven't look at much.
>
​Just for the record, I'm not completely sure the new code is safe.

Things get complicated when state or caching are involved. Sure wouldn't
bet my life that there can be no problems.

I have a nagging feeling that there could be some fool script that is proof
of this fool-proof scheme. Probably a theorem to be stated and proved...

Edward

**Comment by edreamleo** [comment]
On Sun, Jul 16, 2017 at 2:06 PM, Edward K. Ream <edreamleo@gmail.com> wrote:

​
​> ​
Just for the record, I'm not completely sure the new code is safe.

​To clarify, I mean safe for non-malicious scripts that don't, say,
monkey-patch v.setBodyString.

Edward

**Comment by edreamleo** [comment]
I am going to close this, per [this discussion].  The risks are too great, the rewards, not proven.

**Comment by edreamleo** [comment]
I continue to dither about this, so I am going to reopen it.

**Comment by vitalije** [comment]
Just to repeat once more. There is a possibility to implement `lines` property to be read-only or to immediately change `_bodyString` when setting this property, and to cache it when read. That way no one's script can be broken with this feature, and later (if ever) to add full support for both reading and writing to this property.

**Comment by edreamleo** [comment]
On Mon, Aug 14, 2017 at 10:37 AM, Виталије Милошевић <
notifications@github.com> wrote:

> Just to repeat once more. There is a possibility to implement lines
> property to be read-only or to immediately change _bodyString when
> setting this property, and to cache it when read. That way no one's script
> can be broken with this feature, and later (if ever) to add full support
> for both reading and writing to this property.
>
​Thanks for the repetition ;-)

I've just refreshed my memory by checking out the v-lines branch.

Imo, making _bodyString a property would be too big a performance hit.

But how to ensure that v._bodyString is always in sync with v._bodyLines?
It *would* be in sync unless a "foreign" script sets v._bodyString directly.

Yeah, this is unlikely, and we could deprecate it. But it will be very bad
for the user if it ever happens. It feels like this idea is drowning in an
inch of water, but I see no proper way to rescue it.

Your comments, please.

Edward

**Comment by vitalije** [comment]
@edreamleo 
> But how to ensure that v._bodyString is always in sync with v._bodyLines?

It need not to be in perfect sync if we are going to make `lines` just read-only.
```python
def _get_body_lines(self):
      if self._bodyString == self._dontEverTouchThisAttribute:
             return self._lines
      self._dontEverTouchThisAttribute = self._bodyString
      self._lines = tuple(g.splitLines(self._bodyString))
      return self._lines
```
And in `__init__` add initialization for `_dontEverTouchThisAttribute` and `_lines`.
This way we ain't achieve considerable speed benefit, but we'll have more clarity in code and no one's code can be broken by this.

Later (or perhaps right now) it could be announced deprecation of direct use `_bodyString` and after some time just throw away `_dontEverTouchThisAttribute` and use only `_bodyString` in this property and make it work in both directions as it is now in v-lines branch.

**Comment by edreamleo** [comment]
I don't see a big performance benefit from making v._lines read only.  The suggested code is complex, and offers too little benefit. User code can compute g.splitLines(p.b) easily.  Leo's importers do this.  

I am going to close this issue now.  It could be reopened, but imo there are far more important items on the list.
