### ISSUE TITLE
Feature Request: "rename node"

### ISSUE THREAD

**Issue by tangentstorm** [leo-editor/leo-editor#3361]
It would be nice if I could rename `<<this kind of headline>>` in a way that also preserved incoming links, or at least the link from the parent node.

(And then ideally, work in both directions, so you could rename the link in context to rename the actual node.)

In Visual Studio Code, you can press f2 to rename identifiers in this way, so if that key isn't bound, it might be a reasonable default shortcut...

(Obviously, `@others` avoids this situation completely, but when I'm extracting arbitrary sections from a large node (#3360) that's not the right tool.),

**Comment by edreamleo** [comment]
@tangentstorm I'm not sure this feature is worth doing. A cff will find all section references, both in headlines an body text.

**Comment by tangentstorm** [comment]
What does "cff" mean?

**Comment by gatesphere** [comment]
It's an abbreviation (and alias) for the 'clone-find-all-flattened' command.

**Comment by tbpassin** [comment]
And then there's find-and-replace in headline + body.  That's safe enough if you include  the `<<` and `>>` in the search phrase.

**Comment by edreamleo** [comment]
I am going to close this issue. It's not worth doing.
