### ISSUE TITLE
Add support for locked nodes

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#3374]
**Won't do**: #3400 will suffice.

Every so often a file gets deleted from leoPy.leo, and (sometimes) also from leoPyRef.leo. This is annoying.

Something like `@lock` would prevent nodes from being deleted.  Note: we can't prevent the nodes from being moved, because then cloning such nodes would be useless.

**Comment by tbpassin** [comment]
Remember that many scripts and methods look for a headline starting with `@file`, etc., so simply prefixing that headline with `@lock` would break a lot of code.

**Comment by edreamleo** [comment]
@tbpassin I wasn't clear. The `@lock` directive would be allowed only in the body.

**Comment by edreamleo** [comment]
I am going to close this item. The script mentioned in #3400 suffices.
