### ISSUE TITLE
Create a browser-based gui for Leo

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#338]
From [this thread](https://groups.google.com/d/msg/leo-editor/ySwjUw_cA2k/qWjEA16zBQAJ) on leo-editor.

Flex makes it possible to run Leo from a server such that Leo's gui will appear in a browser.

Chris George says:

> I envisioned the python code running on a server and a team using one instance of Leo to work on a project. 
> Or myself keeping my monolithic information Leo file on a running instance on a server and being able to access it from anywhere, anytime, with any device.

**hello_world.py**

```python
from flexx import app, ui
m = app.launch(ui.Widget)  # Main widget
b1 = ui.Button(text='Hello', parent=m)
b2 = ui.Button(text='world', parent=m)
app.run()
```
starts a server:
```
>python3 flex_test.py
INFO flexx.app: Serving apps at http://localhost:49190/
INFO flexx.webruntime: launching XulRuntime
INFO flexx.app: Starting Flexx event loop.
INFO flexx.app: New session Widget VzmlVaAmsPdE1IiuvlnvTefX
```
that serves a page that looks [like this](http://flexx.readthedocs.io/en/stable/ui/examples/example57d19e3d2e848cca1e3922b7d896c87e.html).

I think this project has real promise.  It is certainly worth investigating further.

**Comment by edreamleo** [comment]
Flexx has an extremely simple way of laying out elements in a page.  For example, the [box layout class](http://flexx.readthedocs.io/en/latest/ui/box.html) and the [box layout example](http://flexx.readthedocs.io/en/latest/ui/examples/boxes_src.html#boxes-py). This simplifies layout like python simplifies programming.

**Comment by JohnLunzer** [comment]
Just thought I would add a note here about [workflowy](https://workflowy.com), which is a web-based outlining software.

It is basically a simplified Org-mode. If you believe the claims on their home page it is the best organizational tool ever.

What it tells me is that there is a market for web-based outlining tools. I believe a Flexx-based Leo front-end would fit into this market.

**Comment by xgid** [comment]
I'm very new to Leo and I'm just exploring its possibilities and, despite [some minor starting problems](https://github.com/leo-editor/leo-editor/issues/343), so far I'm quite "excited" about it (in the sense that some of its founders have already expressed)! But one of the things, so far, that I've found could drastically improve the overall experience of the end-user has to do with the _visual representation_ and _navigation_ side of the outline. And Workflowy is a very good example. I'm talking about things like the "subtree-focus" (o whatever they call it) which with a simple double-click focuses the outline in the given node and its sub-nodes, hiding all the rest. Or in ways to instantly _filter_ the visible nodes (hiding the non-matching ones) by just typing a word in the mini-buffer. Or this kind of things...

This should be perfectly _doable_ with Leo, shouldn't it? Is there a way to do it right now? 

Just to clarify, I think it could/should be done _in_ the current Leo GUI, not in a web-based front-end.

What do you think?

**Comment by edreamleo** [comment]
​​
​On Thu, Feb 23, 2017 at 5:18 PM, XGiD <notifications@github.com> wrote:

> I'm talking about things like the "subtree-focus" (o whatever they call
> it) which with a simple double-click focuses the outline in the given node
> and its sub-nodes, hiding all the rest.
>
​We call this hoisting the outline. dehoist undoes a hoist.

The chapter_hoist.py goes farther.  From the docstring:

"This plugin puts two buttons in the icon area: a button called 'Save
> Hoist' and a button called 'Dehoist'. The 'Save Hoist' button hoists the
> presently selected node and creates a button which can later rehoist the
> same node. The 'Dehoist' button performs one level of dehoisting."
>

The Leonine way to execute the hoist command would be to bind a key to it.
Leo has *way *too many commands to use clicks, double-clicks, ctrl-clicks
in general. You could, however, add hoist/dehoist commands to the
right-click menu. The contextmenu.py plugin creates this menu. See the post
script for more about executing commands easily.

> Or in ways to instantly *filter* the visible nodes (hiding the
> non-matching ones) by just typing a word in the mini-buffer. Or this kind
> of things...
>
​The clone-find commands create clones of the matches, which can then
be *reorganized
*as you like *without* affecting the originals.​ This is way more powerful
than a filter.

Newbies sometimes do have truly innovative additions to Leo. If so, it will
be dead easy for to prototype it with @button
<http://leoeditor.com/customizing.html#button>. Welcome aboard :-)

The two post scripts discuss executing commands and writing scripts that
create clone-based filters.

Edward

P. S. *About commands*: It's most convenient to bind your favorite commands
to keys.  However, it's also convenient to execute commands from the
minibuffer
<http://leoeditor.com/commands.html#executing-commands-from-the-minibuffer>.
Typing completion saves typing. Apparently typing completion is missing
from the present docs.  I'll add it back soon.

Once you type a command, it goes into a history list. Alt-x up/down arrow
scrolls through this list. The @data history-list setting "pre-loads" your
favorite commands into the history list. Ctr-P (repeat-complex-command)
repeats the last minibuffer command.

P.P.S *Script-based filters: *Scripts can create their own clone-based
"filters" using the c.cloneFindByPredicate method. Here is the signature
and docstring:

def cloneFindByPredicate(self,
    generator,     # The generator used to traverse the tree.
    predicate,     # A function of one argument p, returning True
                   # if p should be included in the results.
    failMsg=None,  # Failure message. Default is no message.
    flatten=False, # True: Put all matches at the top level.
    iconPath=None, # Full path to icon to attach to all matches.
    redraw=True,   # True: redraw the outline,
    undoType=None, # The undo name, shown in the Edit:Undo menu.
                   # The default is 'clone-find-predicate'
):
    '''
    Traverse the tree given using the generator,
    cloning all positions for which predicate(p) is True.
    Undoably move all clones to a new node, created
    as the last top-level node. Returns the newly-created node.
    Arguments:

    generator,      The generator used to traverse the tree.
    predicate,      A function of one argument p returning true
                    if p should be included.
    failMsg=None,   Message given if nothing found.
                    Default is no message.
    flatten=False,  True: Move all node to be parents of
                    the root node.
    iconPath=None,  Full path to icon to attach to all matches.
    redraw=True,    True: redraw the screen.
    undo_type=None, The undo/redo name for the Edit:Undo menu.
                    The default is 'clone-find-predicate'
    '''

Edward

**Comment by edreamleo** [comment]
On Fri, Feb 24, 2017 at 8:34 AM, Edward K. Ream <edreamleo@gmail.com> wrote:

> ​​
> ​On Thu, Feb 23, 2017 at 5:18 PM, XGiD <notifications@github.com> wrote:
>
>> I'm talking about things like the "subtree-focus" (o whatever they call
>> it) which with a simple double-click focuses the outline in the given node
>> and its sub-nodes, hiding all the rest.
>>
> ​We call this hoisting the outline. dehoist undoes a hoist.
>

​@chapters <http://leoeditor.com/commands.html#using-chapters> is another
form of hoisting. Perhaps not documented very well.  Feel free to ask
questions.

Edward

**Comment by xgid** [comment]
@edreamleo Thanks alot for taking the time to give me a so extens explanation!
The chapter_hoist.py pluguin is great!! Good work! I'll also take a look at the @chapters documentation.

I think I have to take some more time in reading Leo's docs and learning how it works before making any more comments... I'm sorry for the noise!

**Comment by xgid** [comment]
Well, and latter on I'll go for making my own scripts... that's quite advanced for me right now.

**Comment by edreamleo** [comment]
I am going to re-imagine this item.  Joe Orr advocates (plans?) a different approach. There is no need to commit to Flexx here.

**Comment by JohnLunzer** [comment]
I agree that there is no reason to commit to a specific framework/technology. I do, however, still believe that Flexx is strong candidate because it is already mostly Python (the syntax is all Python but you need to have some fundamental understanding of manipulating the DOM (HTML/CSS/Javascript).

**Comment by edreamleo** [comment]
@JohnLunzer As a practical matter, whoever does the work gets to choose the tools.

**Comment by JohnLunzer** [comment]
@edreamleo, of course. This said, I think the hard part is not the viewing but the communication between the front and back end that will pose the largest threat to anyone's effort on any front.

**Comment by edreamleo** [comment]
I am going to close this item.  Joe Orr's LeoVue project already goes far beyond what I had imagined.
