### ISSUE TITLE
VR4 messages not relevant to Leo console GUI

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#3394]
Running Leo with --gui=console when PyQt6-WebEngine is not installed gives these messages which are not relevant to Leo console GUI:

_Leo 6.7.4-devel, devel branch, build 387170f3d9
2023-06-17 00:01:06 -0500
Python 3.11.4, Leo Console Gui (npyscreen)
Windows 10 AMD64 (build 10.0.19045) SP0
vr4: *** limited RsT rendering in effect
vr4" *** For full rendering capability,
vr4:     install QWebEngine using python3 -m pip install PyQt6-WebEngine
vr4:     for PyQt6 or python3 -m pip install PyQtWebEngine for PyQt5
Freewin: limited RsT rendering in effect
vr4: *** limited RsT rendering in effect
vr4" *** For full rendering capability,
vr4:     install QWebEngine using python3 -m pip install PyQt6-WebEngine
vr4:     for PyQt6 or python3 -m pip install PyQtWebEngine for PyQt5
Freewin: limited RsT rendering in effect_

**Comment by tbpassin** [comment]
Oops, those are supposed to read "VR3", not "VR4".  I brought in some code from a private VR4 plugin (which I used to prototype some things), and missed changing the messages.

I'll fix that, but keeping them from being emitted when the gui is not qt, I'm not sure if that is a plugin thing or a Leo core thing.  I'll see if I can sort it out.

**Comment by tbpassin** [comment]
PR #3395 fixes this issue.
