### ISSUE TITLE
Retire --screen-shot. Improve screenshots plugin

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#3396]
See PR #3397.

At present `--screen-shot` crashes. However, it would be better to have `screenshots.py` do all the work:

- [x] Remove all `--screen-shot` logic from Leo's core.
- [x] Define new commands in `screenshots.py`. These wait 5 seconds and then take the screenshot.

**Comment by tbpassin** [comment]
BTW, Windows 10 comes with a "Snipping Tool" which works really well.  You can activate it with <WIN-SHIFT-S>, and it copies the image to the clipboard. Or, if That's not active yet, tap the <WINDOWS> key and type snip.

**Comment by edreamleo** [comment]
Closed via PR #3397.
