### ISSUE TITLE
Enhancement: reload-abbreviations

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#340]
The reload-abbreviations command would allow a dev to modify a test;; abbreviation *without* reloading the local .leo file.

This enhancement, combined with recent Aha's, will make Leo a much better platform for test-driven design. ~~It is hard to overstate the importance of this.~~ Actually, cut/paste of unit tests preambles is good enough.

**Comment by edreamleo** [comment]
**Update**: reload-abbreviations would be good to have, but `@button` nodes would support test-driven design in Leo even better than a test;; abbreviation. Full details [here](https://groups.google.com/d/msg/leo-editor/_4TNCZt6-cA/TeW5yGIUCwAJ).

For this reason, I have removed the "Important" label from this issue

**Comment by JohnLunzer** [comment]
These are the three nodes where I have my abbreviations.
```
@data abbreviations-subst-env
@data abbreviations
@outline-data tree-abbreviations
```
Is it from these three nodes that it is reloading from? Additionally will it reload from myLeoSettings.leo as well as from the local settings? Ie, will it act the same as if you were launching Leo?

**Comment by edreamleo** [comment]
> These are the three nodes where I have my abbreviations.

@data abbreviations-subst-env
@data abbreviations
@outline-data tree-abbreviations

> Is it from these three nodes that it is reloading from? 

Good question.  I haven't given this issue much thought recently.  I guess the safest answer is to say that Leo will do whatever is needed to make reload-abbreviations "just work".

> Additionally will it reload from myLeoSettings.leo as well as from the local settings? Ie, will it act the same as if you were launching Leo?

I think the answer must be "yes".  This will slow down the operation of the command, but that's a small price to pay not to surprise and frustrate the user.

**Comment by edreamleo** [comment]
I am going to remove any milestone from this issue.  TDD design is already feasible.

**Comment by edreamleo** [comment]
Completed at f86046893, by defining the `reload-settings` and `reload-all-settings` commands.

At present, these commands work completely only for abbreviations.  And yes, these commands *do* reload all abbreviation-related settings.

A full discussion of these commands and future work is found [here](https://groups.google.com/d/msg/leo-editor/v4ycmSq4lE4/oIfwyMt-CwAJ).
