### ISSUE TITLE
active file bug in MacOS

### ISSUE THREAD

**Issue by HaveF** [leo-editor/leo-editor#3403]
In version 6.7.3, on MacOS 12, there appears to be an active file bug.

When I open several files, do some actions, it doesn't apply the function to to current active Leo file, but other Leo file.

I have recorded a video to better illustrate the issue. Unfortunately, even after updating Leo to version 6.7.4-devel(Jun 25, 2023), the bug persists. https://www.youtube.com/watch?v=R5L3UShZLsk

**Comment by edreamleo** [comment]
@HaveF Thanks for this report. It appears that clicking the tab doesn't properly change the active commander. I'll look into this.

**Comment by edreamleo** [comment]
@HaveF `qt_gui.onActivateEvent` contains a dubious special case for MacOS.

Does changing `if g.isMac:` to `if False:` fix this issue?

If so, does the reported problem with `replace-then-find` reappear?

Thanks.

Note: Tracing focus with `--trace=focus` might help.

**Comment by HaveF** [comment]
If I change to `if False`, it works for active file.

But, `replace-then-find` and `replace` are not works, `replace-all` could work.

I believe https://github.com/leo-editor/leo-editor/issues/757#issuecomment-379456114 is a hint...
> A reminder since this is a focus issue: on OSX all documents open as separate windows.

I can stand with more separate Leo windows...

**Comment by edreamleo** [comment]
@HaveF Thanks for your testing and comments.

Should we leave Leo's code as it is?

**Comment by HaveF** [comment]
I agree, it is just a Mac only problem and it seems hard to fix

**Comment by edreamleo** [comment]
@HaveF Thanks for your help on this issue. I have added the `Can'tFix` and `UserInfo` labels in the hope that people will find this issue if it bites them.

**Comment by HaveF** [comment]
I believe tagging is useful and hope others see it when they run into issues. You are so kind, thank you for your help. @edreamleo

**Comment by edreamleo** [comment]
On Sun, Jul 9, 2023 at 7:41 PM HaveF ***@***.***> wrote:

> I believe tagging is useful and hope others see it when they run into
> issues.
>
I agree.

> You are so kind, thank you for your help. @edreamleo
> <https://github.com/edreamleo>
>
You're welcome!

Edward
