### ISSUE TITLE
PR #3215 Destroys The Workbook

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#3404]
PR #215 creates this bug and this PR will also fix this bug :-)

As discussed in [Google Groups](https://groups.google.com/g/leo-editor/c/N374jBVLSgw), PR #3215 reproducibly replaces my workbook outline with the default CheatSheet:

<details>

This happens after I check out the branch (ekr-3181-mypy-links branch, through several updates of this branch).  When this happens, other previously-opened outlines that should have gotten opened do not.

0. **Back Up Your workbook**.
1. **Check that the backup exists** and has the right file length.
2. Close Leo.
3. Checkout the ekr-3181-mypy-links branch.
4. Launch Leo using `py -m leo.core.runLeo` (I have not tried this using any other method of launching).
5. Observe **on this first launch** that the workbook survives.
6. Close and restart Leo.
7. Observe that the workbook has changed to the default.
8. Restore the workbook from backup.  Repeat and observe replacement of the workbook.
9. Restore the workbook, check out the devel branch, and re-launch Leo.
10. Observe, **on this first launch**, that the workbook still gets replaced.
11. Restore the workbook and repeat.  Observe that this time the workbook survives untouched.
12. Check out the suspect branch again. Launch Leo. Close Leo and restore the workbook if necessary (probably not if this is the first launch).
13. Launch Leo with the path to the workbook specified on the command line. Observe that the workbook survives unchanged.

This behavior, along with the fact that other outlines should get opened but don't, make me think that Leo writes some resource that it later uses to locate the outlines to open.  In the suspect branch, this resource is wrong or corrupted, so it can't find any of the outlines.  When Leo can't find the workbook it creates a new default workbook. When an outline is specified on the command line, this resource does not get consulted, the workbook gets found, and so the workbook does not get replaced.

After switching away from the suspect branch, the resource is still corrupted so that on the first launch the workbook gets replaced.  After that, the resource is written correctly and normal behavior resumes.

I don't know what this hypothetical resource is.  I know it's not the db or the recent files list because I deleted or cleared them and the behavior continued.

```console
Leo 6.7.4-devel, ekr-3181-mypy-links branch, build c47ab83f17
2023-06-28 09:19:09 -0500
Python 3.11.4, PyQt version 6.4.3
Windows 10 AMD64 (build 10.0.19045) SP0
```

</details>

**Analysis**

This issue is the result of multiple evil hacks in the `SessionManager` class, some of which involve unls. For example, the calculations on the unls do not use the usual unl functions in `leoGlobals.py`. The legacy code was an accident waiting to happen.

@tbpassin The "hypothetical resource" you speak of is likely `~/.leo/leo.session`. I have just added a trace that prints the path to this file when `--trace=startup` is in effect.

**Resolution**

The `SessionManager` class and all related code and commands will be retired.  See [this post](https://groups.google.com/g/leo-editor/c/WqO9u8lqPew/m/aHc4VW1AAQAJ).

**Comment by edreamleo** [comment]
Mystery solved: I get this message when running with `--trace=startup`:

`load_session session file not found: unl:gnx://workbook.leo`.

**Comment by tbpassin** [comment]
Whew!  Long vs short filename confusion?  We sure don't want this result no matter how the user writes that setting.

**Comment by edreamleo** [comment]
@tbpassin :-) There are multiple issues here:

- I see no reason for `~/.leo/leo.session` to exist.
  It should be possible to use the regular cache, but we'll see.
- I see no reason for the `SessionManager` to use unls. This conclusion is more firm.
- At present, the cache stores `c.p` as an archived position, that is, a list of child indices.
  Doh! Use gnxs instead! `g.findGnx` will succeed more often than resolving an archived position.

Rev c3b7ed60 adds 5 new Position methods related to gnxs. I added `p.get_full_gnx_UNL` for completeness, but also because I thought the `SessionManager` would use it. But now I think it won't. I'll change the docstring for `p.get_full_gnx_UNL` once unls are no longer misused during startup.

You suggested adding new `Position` methods a few days ago. Things haven't turned out exactly as either of use expected, but that's expected, hehe. In particular, plugins now call `g.findAnyUnl` instead of `g.findUnl`.  We need a new name for the reason you mentioned earlier: we can't change what existing functions do.

**Comment by edreamleo** [comment]
@tbpassin Hmm. I was forgetting that gnxs do not persist in `@auto` nodes. Perhaps the cache should store both an archived position and a gnx.

**Comment by tbpassin** [comment]
Up til now, Leo remembers and navigates to the last position when an outline has been re-opened.  That's a good feature that would be unfortunate to lose.

**Comment by tbpassin** [comment]
One thing to remember.  When the UNL PR is finally merged, users will probably find that their previously-open outlines won't open, or won't open to the right place, the first time they restart Leo after the change.  This is going to make people unsure about Leo's reliability, at the very least.  That's unless the new machinery can be made backwards compatible.

**Comment by edreamleo** [comment]
@tbpassin Leo will continue to remember where all outlines were last opened, even during the changeover.

**Comment by edreamleo** [comment]
@tbpassin I am going to close this issue. 

`LM.openWorkBook` (previously called `LM.openEmptyWorkBook`) no longer calls `c.fileCommands.saveAs(fn)`,

The PR should be safe now. Please reopen if it isn't!
