### ISSUE TITLE
Markdown import tripping on ```

### ISSUE THREAD

**Issue by tbnorth** [leo-editor/leo-editor#341]
1d16f9c1e - using @auto-md to load a file (its extension is .Rmd, we should probably recognize that as an alias for .md), import looks good until hitting blocks like:

```md
stuff here

`​``python
loads.init = {
    Chloride: 11.5,
    TotalP: 0.002,
}

`​``

more stuff here
```

The `​``python part stays in the correct node (with "stuff here"), but then a new node's started.

Be careful copy pasting this, I used `\<zero-width-space>`` to get \``` into a \``` block in GitHub markdown.

**Comment by tbnorth** [comment]
Bug still in 55e5372c

**Comment by edreamleo** [comment]
​​
On Sat, Nov 26, 2016 at 5:00 PM, Terry Brown <notifications@github.com>
wrote:

> Bug still in 55e5372
> <https://github.com/leo-editor/leo-editor/commit/55e5372c973e3f8b6885ab345a8d2ac64bea5837>
>
The timing your email is perfect. Before I got bogged down in other
matters, I had been planning to simplify several importers, including
markdown, by using multi-line regex patterns.  This implies scrapping
line-by-line scanning​.

The idea is simple.  For languages (file formats) without strings or
comments, there is no point in carefully checking for them in i.scan_table,
so there is no real point in using any variant of v2_scan_line.

I'll have to see whether ``` syntax overly complicates matters for
markdown. If so, I'll retain the existing clumsy line-oriented scan code,
and treat ``` like a comment.

And one more thing.  I have just discovered a bad bug in i.scan_table,
while messing with the pascal importer, of all things. The bug affects
potentially affects any string or comment whose ending delimiter is
different from its starting delimiter.

This has shown itself to be a tricky bug to fix. It's got to be fixed
before I turn to the markdown importer.

EKR

**Comment by edreamleo** [comment]
The ``` syntax part of google's markdown syntax, but not the [official markdown syntax](https://daringfireball.net/projects/markdown/syntax). So this is an enhancement request, not a bug report. Having said that, this is a time to add that support.

**Comment by edreamleo** [comment]
Rev 5f048e49 fixes the scanning problems.

**Comment by edreamleo** [comment]
Fixed at d2141be.  Please reopen if there are further problems.

**Comment by tbnorth** [comment]
On Sun, 27 Nov 2016 15:59:48 -0800
"Edward K. Ream" <notifications@github.com> wrote:

> The ``` syntax part of google's markdown syntax, but not the
> [official markdown
> syntax](https://daringfireball.net/projects/markdown/syntax). So this
> is an enhancement request, not a bug report. Having said that, this
> is a time to add that support.

Excellent, thanks, it seems to be working well now.

You're absolutely correct that the ``` syntax is not part of
`daringfireball` markdown, but I guess that raises the question, where
is vanilla markdown used?  I'm guess GitHub and stackoverflow are two
of the biggest users of md, and they both use ```.  I'd argue for
pandoc as one of the most valuable markdown dialects to support, it
also uses ```.  And in the data science / reproducible research realm,
"R-markdown" is a big target - that uses ``` and also ```{language}.

So I think the majority of in the wild markdowns use ```.

Thanks for the fix.

**Comment by edreamleo** [comment]
On Sun, Nov 27, 2016 at 9:14 PM, Terry Brown <notifications@github.com>
wrote:

Excellent, thanks, it seems to be working well now.
>

​Glad to hear it.  Imo, it's reasonable to support ```.

EKR
