### ISSUE TITLE
Save gnxs to the cache?

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#3410]
Leo writes archived positions to the per-file caches. Writing (full) gnxs result in fewer broken links.

Archived positions *might* be needed for `@auto` nodes: gnxs do not persist for such files.

**Comment by tbpassin** [comment]
This is the kind of change that should go into a new PR, not the PR # 3215 one.

**Comment by edreamleo** [comment]
@tbpassin That's the plan. This is a completely separate issue. It requires substantial testing. It could be delayed to a later release without any problem.

**Comment by edreamleo** [comment]
I am going to close this issue. It will be superseded by the flat-json work.
