### ISSUE TITLE
paste-node should retain gnxs if possible

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#3429]
See PR #3430.

@tbpassin proposes that copy-node or cut-node followed by paste-node shall work as follows.

**Case 1**: the gnx of the pasted node does **not** exist in the target outline:

The pasted node should retain its gnx (as in paste-node-as-clone).

**Case 2**: The gnx of the pasted node *does* exist in the target outline:

The pasted node must get a new gnx.

**Notes**

- paste-as-clone will work as before&ndash;it retains the gnx, creating a clone if necessary.
- EKR: Leo must now have a `paste-reallocating-gnxs` command to force reallocation!

**Comment by tbpassin** [comment]
As I thought more about it, I realized that what applies to a node should apply to its subtree, since the entire subtree gets copied/pasted.

**Comment by edreamleo** [comment]
I am going to close this item, for reasons given [here](https://groups.google.com/g/leo-editor/c/_wAzGsUJcxU/m/WL36jyKKAwAJ).
