### ISSUE TITLE
"Exception creating path" error when evaluating a path with accents in a @clean expression

### ISSUE THREAD

**Issue by xgid** [leo-editor/leo-editor#343]
I've just installed the current version 5.4 and found a problem with @clean path expansion in Windows when the path name has any accent (Latin-1 characters).

I was following the docs about [path expressions](http://leoeditor.com/directives.html#path-expressions) and created an `@clean` node with this headline:
```
@clean {{os.path.abspath(os.curdir)}}/Notas sobre Leo.md
```

and a body like this:
```markdown
# Notas sobre Leo
```

Then, when trying to save the file, the log shows an error:
```
exception creating path: u'C:\\Software y computaci\xf3n\\Python\\IDEs\\{{os.path.abspath(os.curdir)}}'
```

After some further investigation it seems to be a problem with accents in the expanded path (which is `C:\\Software y computación\\Python\\IDEs`). The obvious workaround is to remove any accents in the paths where I store my leo files, but that's not a solution.

> Leo Log Window
> Leo 5.4, Sat Oct 22 06:39:42 2016
> Git commit: after ff
> Python 2.7.12, PyQt version 4.8.6
> Windows 10 AMD64 (build 10.0.14393)

**Comment by xgid** [comment]
Another interesting observation: the workaround I applied was to create a symlink `C:\sw` pointing to `C:\Software y computación` and then opening the original .leo file from that new path, without needing to move it arround. That worked and the resulting `C:\sw\Python\IDEs\Notas sobre Leo.md` file was correctly created when saving the .leo file.

But interestingly, when I open the .leo file **from the original location (the path containing accents)**, Leo manages to open it, but instead of loading the **corresponding `Notas sobre Leo.md` file located in the same folder**, it tries to open a non-existant `C:\dev\Leo-5.4\leo\Notas sobre Leo.md` file. 
And when the .leo file is saved, it creates a new `C:\dev\Leo-5.4\leo\Notas sobre Leo.md` file.

The Log shows this:
```
reading: C:\Software y computación\Python\IDEs\Notas sobre Leo.leo
not found: C:\dev\Leo-5.4\leo\Notas sobre Leo.md
read 1 files in 0.00 seconds
read outline in 0.01 seconds
created: C:\dev\Leo-5.4\leo\Notas sobre Leo.md
saved: Notas sobre Leo.leo
```

**Comment by xgid** [comment]
After trying to reproduce it again to give the full Log for the first attempt to create the file in the original path with accents, I cannot see the "exception creating path" message anymore, but this is the whole log:
```
Leo Log Window
Leo 5.4, Sat Oct 22 06:39:42 2016
Git commit: after ff
Python 2.7.12, PyQt version 4.8.6
Windows 10 AMD64 (build 10.0.14393) 
saved: Notas sobre Leo.leo
Traceback (most recent call last):
  File "C:\dev\Leo-5.4\leo\core\leoGlobals.py", line 5808, in os_path_expandExpression
    s = s[: i] + str(val) + s[j + 2:]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf3 in position 23: ordinal not in range(128)
Traceback (most recent call last):
  File "C:\dev\Leo-5.4\leo\core\leoGlobals.py", line 5808, in os_path_expandExpression
    s = s[: i] + str(val) + s[j + 2:]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf3 in position 23: ordinal not in range(128)
Traceback (most recent call last):
  File "C:\dev\Leo-5.4\leo\core\leoGlobals.py", line 5808, in os_path_expandExpression
    s = s[: i] + str(val) + s[j + 2:]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf3 in position 23: ordinal not in range(128)
Traceback (most recent call last):
  File "C:\dev\Leo-5.4\leo\core\leoGlobals.py", line 5808, in os_path_expandExpression
    s = s[: i] + str(val) + s[j + 2:]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf3 in position 23: ordinal not in range(128)
Traceback (most recent call last):
  File "C:\dev\Leo-5.4\leo\core\leoGlobals.py", line 5808, in os_path_expandExpression
    s = s[: i] + str(val) + s[j + 2:]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf3 in position 23: ordinal not in range(128)
Traceback (most recent call last):
  File "C:\dev\Leo-5.4\leo\core\leoGlobals.py", line 5808, in os_path_expandExpression
    s = s[: i] + str(val) + s[j + 2:]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf3 in position 23: ordinal not in range(128)
Traceback (most recent call last):
  File "C:\dev\Leo-5.4\leo\core\leoGlobals.py", line 5808, in os_path_expandExpression
    s = s[: i] + str(val) + s[j + 2:]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf3 in position 23: ordinal not in range(128)
Traceback (most recent call last):
  File "C:\dev\Leo-5.4\leo\plugins\qt_idle_time.py", line 114, in call_handler
    self.handler(self)
  File "C:\dev\Leo-5.4\leo\core\leoExternalFiles.py", line 151, in on_idle
    self.idle_check_commander(c)
  File "C:\dev\Leo-5.4\leo\core\leoExternalFiles.py", line 186, in idle_check_commander
    self.idle_check_at_file_node(c, p)
  File "C:\dev\Leo-5.4\leo\core\leoExternalFiles.py", line 193, in idle_check_at_file_node
    path = g.fullPath(c, p)
  File "C:\dev\Leo-5.4\leo\core\leoGlobals.py", line 2882, in fullPath
    return c.os_path_finalize_join(path, fn)
  File "C:\dev\Leo-5.4\leo\core\leoCommands.py", line 5266, in os_path_finalize_join
    return g.os_path_finalize_join(*args, **keys)
  File "C:\dev\Leo-5.4\leo\core\leoGlobals.py", line 5842, in os_path_finalize_join
    for z in args if z]
  File "C:\dev\Leo-5.4\leo\core\leoGlobals.py", line 5812, in os_path_expandExpression
    g.es_exception(full=True, c=c)
  File "C:\dev\Leo-5.4\leo\core\leoGlobals.py", line 5180, in es_exception
    g.es_print_error(line, color=color)
  File "C:\dev\Leo-5.4\leo\core\leoGlobals.py", line 5158, in es_print_error
    g.es_print(*args, **keys)
  File "C:\dev\Leo-5.4\leo\core\leoGlobals.py", line 5201, in es_print
    g.pr(*args, **keys)
  File "C:\dev\Leo-5.4\leo\core\leoGlobals.py", line 5327, in pr
    stdout.write(s2)
IOError: [Errno 9] Bad file descriptor
```

Any other info I may provide, just tell me.

**Comment by edreamleo** [comment]
On Fri, Dec 2, 2016 at 10:11 AM, XGiD <notifications@github.com> wrote:

> I've just installed the current version 5.4 and found a problem with
> @clean <https://github.com/clean> path expansion in Windows when the path
> name has any accent (Latin-1 characters).
>
> I was following the docs about path expressions
> <http://leoeditor.com/directives.html#path-expressions> and created an
> @clean node with this headline:
>
> @clean {{os.path.abspath(os.curdir)}}/Notas sobre Leo.md
>
> The Python 2.x os.path functions are problematic with respect to unicode.

Try using g.os_path_abspath instead of os.path.abspath.  Leo's g.os_path_x
wrappers exists to work around Python 2.x unicode problems.

Please let us all know whether this works.

Edward

**Comment by xgid** [comment]
Thanks for your answer. It did'nt work. With the new expression, the log is this other one:
```
Leo Log Window
Leo 5.4, Sat Oct 22 06:39:42 2016
Git commit: after ff
Python 2.7.12, PyQt version 4.8.6
Windows 10 AMD64 (build 10.0.14393) 
reading: C:\Software y computación\Python\IDEs\Notas sobre Leo.leo
Traceback (most recent call last):
  File "C:\dev\Leo-5.4\leo\core\leoGlobals.py", line 5808, in os_path_expandExpression
    s = s[: i] + str(val) + s[j + 2:]
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 23: ordinal not in range(128)
not found: C:\Software y computación\Python\IDEs\{{g.os_path_abspath(os.curdir)}}\Notas sobre Leo.md
read 1 files in 0.00 seconds
read outline in 0.02 seconds
Traceback (most recent call last):
  File "C:\dev\Leo-5.4\leo\core\leoGlobals.py", line 5808, in os_path_expandExpression
    s = s[: i] + str(val) + s[j + 2:]
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 23: ordinal not in range(128)
Traceback (most recent call last):
  File "C:\dev\Leo-5.4\leo\core\leoGlobals.py", line 5808, in os_path_expandExpression
    s = s[: i] + str(val) + s[j + 2:]
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 23: ordinal not in range(128)
Traceback (most recent call last):
  File "C:\dev\Leo-5.4\leo\core\leoGlobals.py", line 5808, in os_path_expandExpression
    s = s[: i] + str(val) + s[j + 2:]
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 23: ordinal not in range(128)
Traceback (most recent call last):
  File "C:\dev\Leo-5.4\leo\core\leoGlobals.py", line 5808, in os_path_expandExpression
    s = s[: i] + str(val) + s[j + 2:]
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 23: ordinal not in range(128)
Traceback (most recent call last):
  File "C:\dev\Leo-5.4\leo\core\leoGlobals.py", line 5808, in os_path_expandExpression
    s = s[: i] + str(val) + s[j + 2:]
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 23: ordinal not in range(128)
Traceback (most recent call last):
  File "C:\dev\Leo-5.4\leo\core\leoGlobals.py", line 5808, in os_path_expandExpression
    s = s[: i] + str(val) + s[j + 2:]
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 23: ordinal not in range(128)
Traceback (most recent call last):
  File "C:\dev\Leo-5.4\leo\plugins\qt_idle_time.py", line 114, in call_handler
    self.handler(self)
  File "C:\dev\Leo-5.4\leo\core\leoExternalFiles.py", line 151, in on_idle
    self.idle_check_commander(c)
  File "C:\dev\Leo-5.4\leo\core\leoExternalFiles.py", line 186, in idle_check_commander
    self.idle_check_at_file_node(c, p)
  File "C:\dev\Leo-5.4\leo\core\leoExternalFiles.py", line 193, in idle_check_at_file_node
    path = g.fullPath(c, p)
  File "C:\dev\Leo-5.4\leo\core\leoGlobals.py", line 2882, in fullPath
    return c.os_path_finalize_join(path, fn)
  File "C:\dev\Leo-5.4\leo\core\leoCommands.py", line 5266, in os_path_finalize_join
    return g.os_path_finalize_join(*args, **keys)
  File "C:\dev\Leo-5.4\leo\core\leoGlobals.py", line 5842, in os_path_finalize_join
    for z in args if z]
  File "C:\dev\Leo-5.4\leo\core\leoGlobals.py", line 5812, in os_path_expandExpression
    g.es_exception(full=True, c=c)
  File "C:\dev\Leo-5.4\leo\core\leoGlobals.py", line 5180, in es_exception
    g.es_print_error(line, color=color)
  File "C:\dev\Leo-5.4\leo\core\leoGlobals.py", line 5158, in es_print_error
    g.es_print(*args, **keys)
  File "C:\dev\Leo-5.4\leo\core\leoGlobals.py", line 5201, in es_print
    g.pr(*args, **keys)
  File "C:\dev\Leo-5.4\leo\core\leoGlobals.py", line 5327, in pr
    stdout.write(s2)
IOError: [Errno 9] Bad file descriptor
Traceback (most recent call last):
  File "C:\dev\Leo-5.4\leo\core\leoGlobals.py", line 5808, in os_path_expandExpression
    s = s[: i] + str(val) + s[j + 2:]
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 23: ordinal not in range(128)
saved: Notas sobre Leo.leo
```

**Comment by xgid** [comment]
Hi, I've made a new test on this with a more recent Leo version after seeing your commit 5 days ago.

Now, when opening (double-click from Windows Explorer) the original `C:\Software y computación\Python\IDEs\Notas sobre Leo.leo` file, the Log pane shows this:

```shell
Leo Log Window
Leo 5.4, build 20170206215239, Mon Feb  6 21:52:39 CST 2017
Git repo info: branch = master, commit = 37ca40b36e3b
Python 2.7.12, PyQt version 4.8.6
Windows 10 AMD64 (build 10.0.14393) 
leoID=xgid (in C:\Users\sysadmin\.leo)
load dir: C:\dev\Leo-5.4\leo\core
global config dir: C:\dev\Leo-5.4\leo\config
home dir: C:\Users\sysadmin
reading settings in C:\dev\Leo-5.4\leo\config\leoSettings.leo
reading settings in C:\Users\sysadmin\myLeoSettings.leo
http serving enabled at 127.0.0.1:8130
loadOnePlugin: error importing plugin: leo.plugins.detect_urls
Traceback (most recent call last):
  File "C:\dev\Leo-5.4\leo\core\leoPlugins.py", line 501, in loadOnePlugin
    __import__(moduleName)
ImportError: No module named detect_urls
loadOnePlugin: can not load enabled plugin: leo.plugins.detect_urls
```

so there are no `UnicodeEncodeError` exceptions, but **the resulting outline in Leo shows only a root node named "Notas sobre Leo.leo"** with an empty body and no childs, which is **not** the original file contents.

On the other hand, if I already have Leo opened (by double-clicking another file from a non-problematic path like `D:\proj\code`), and then open the `C:\Software y computación\Python\IDEs\Notas sobre Leo.leo` file with the **File > Open** menu option, the resulting outline successfully shows the root node:
```shell
@clean {{g.os_path_abspath(os.curdir)}}/Notas sobre Leo.md
```
but the message in the Log pane is this other one:
```shell
Leo Log Window
...
reading: C:\Software y computación\Python\IDEs\Notas sobre Leo.leo
not found: D:\proj\code\Notas sobre Leo.md
read 1 files in 0.00 seconds
read outline in 0.01 seconds
```

So it seems that the `g.os_path_abspath(os.curdir)` is resolving to the last "effective" path `D:\proj\code`. Is this the expected behaviour?

And then, at this point, if I close the other .leo file first, open a New empty file (with **File > New**), close the `Notas sobre Leo.leo`, and finally *open it again* with **File > Open**, the resulting Log pane says instead:
```shell
reading: C:\Software y computación\Python\IDEs\Notas sobre Leo.leo
not found: C:\Software y computación\Python\IDEs\Notas sobre Leo.md
```
showing that the "os.curdir" has effectively changed.

If I now add some more text in the body of the root node and save the file, the Log shows:
```shell
created: C:\Software y computación\Python\IDEs\Notas sobre Leo.md
```
and the file `Notas sobre Leo.md` **is correctly created**! That's a good progress!

So the questions for me are at this moment are:
1. The behaviour of the `g.os_path_abspath(os.curdir)` code is the expected one?
2. Should I better drop the `g.os_path_abspath(os.curdir)` altogether and leave the root node just as `@clean Notas sobre Leo.md`? That seems to do the trick and improve my expected behaviour of creating a `Notas sobre Leo.md` file in the same folder than the `Notas sobre Leo.leo` file.
3. Should I open another issue about the error regarding the `detect_urls` plugin? Is this plugin deprecated?
4. In another order of things, I've also tried to use the **todo.py** plugin without success and I've found that the link present at the [plugins page](http://leoeditor.com/plugins.html#todo-py) that's supposed to point to the [Full docs](http://leo.zwiki.org/tododoc.html) is giving a:
```
I could not find any likely page matching "tododoc.html" 
```
Is this also an outdated plugin? Should I open another issue?

Thanks in advance for your help.

**Comment by edreamleo** [comment]
@xgid Thanks for these lengthy comments. Here are my answers to your list of questions.

**Is the behaviour of the `g.os_path_abspath(os.curdir)` code is the expected one?**

`g.os_path_abspath(os.curdir)` works properly. Whether it works as *you* expect is unclear ;-) Note that `os.curdir` is simply ".".

**Should I better drop the g.os_path_abspath(os.curdir) altogether and leave the root node just as @clean Notas sobre Leo.md?**

Absolutely.  Using `@clean {{g.os_path_abspath(os.curdir)}}` is asking for trouble. It will fail in mysterious ways because `os.curdir` will change depending on how you invoke Leo.

**[I want to create] Notas sobre Leo.md file in the same folder than the Notas sobre Leo.leo file.**

`@clean Notas sobre Leo.md` will do that. That is, file names are resolved to the directory containing the .leo file. Why did you think you needed something fancy to do something so basic?

**Should I open another issue about the error regarding the detect_urls plugin?**
** Is this plugin deprecated? **

I don't see detect_urls.py in leo/plugins. I have no knowledge of it. Have you used it in the past?

Rather than opening an issue, please ask about it on the forum.  More people may see your question there.

**[The links to todo.py are out-of-date**

Yes, please create a separate issue.

Edward

**Comment by edreamleo** [comment]
I am going to close this issue now. The original unicode problems have been fixed.

The following dubious practices complicated this discussion:

1. Using `@clean g.os_path_abspath(os.curdir)/*whatever*` is asking for trouble.

2. Using `os.path.whatever` on Python 2 can throw unicode-related exceptions.  That's why the `g.os_path_whatever` functions exist.

**Comment by xgid** [comment]
@edreamleo, thanks for all your answers and sorry for being so late in answering to your questions.

> `@clean Notas sobre Leo.md` will do that. That is, file names are resolved to the directory containing the .leo file. Why did you think you needed something fancy to do something so basic?

Well, as I already explained in my first comment when creating this issue, I was following the docs and found exactly this example in the [path expressions](http://leoeditor.com/directives.html#path-expressions) section of the *Directives Reference* page:
```bash
@file {{os.path.abspath(os.curdir)}}/abc.py
```
so I just followed your instructions! :-) I now agree with you that this example "_is asking for trouble_".

> I don't see detect_urls.py in leo/plugins. I have no knowledge of it. Have you used it in the past?

No, I've never used it. I was just following Leo's documentation advice of adding any pluguin I wish to use in an `@enabled-plugins` node inside my `myLeoSettings.leo` personal file while taking their names from the **Alphabetical list of all Leo plugins** that's present at 'leoSettings.leo#@settings-->Plugins-->@enabled-plugins`
This pluguin just happens to be included in that list!

> Rather than opening an issue, please ask about it on the forum. More people may see your question there.

OK, thanks, I'll try to do that. 

> *[The links to todo.py are out-of-date]* 
> Yes, please create a separate issue.

Done! #421

**Comment by edreamleo** [comment]
On Fri, Feb 24, 2017 at 10:46 PM, XGiD <notifications@github.com> wrote:

> @edreamleo <https://github.com/edreamleo>, thanks for all your answers
> and sorry for being so late in answering to your questions.
>
> @clean Notas sobre Leo.md will do that. That is, file names are resolved
> to the directory containing the .leo file. Why did you think you needed
> something fancy to do something so basic?
>
> Well, as I already explained in my first comment when creating this issue,
> I was following the docs and found exactly this example in the path
> expressions <http://leoeditor.com/directives.html#path-expressions>
> section of the *Directives Reference* page:
>
> ​​
> @file {{os.path.abspath(os.curdir)}}/abc.py
>
> ​Yikes.  What a terrible example.  I'll change it immediately.​

> I don't see detect_urls.py in leo/plugins. I have no knowledge of it. Have
> you used it in the past?
>
> No, I've never used it. I was just following Leo's documentation advice of
> adding any pluguin I wish to use in an @enabled-plugins node inside my
> myLeoSettings.leo personal file while taking their names from the *Alphabetical
> list of all Leo plugins* that's present at 'leoSettings.leo#@settings-->
> Plugins-->@enabled-plugins`
>
​Alright.  I'll revise this list.​

Edward

**Comment by xgid** [comment]
Thanks for your fast response and for addressing all this. 

A side note on something totally unrelated to Leo but that's driving me crazy: does anybody know why I'm *NOT* receiving notifications by email of your comments to any *of the issues where I'm participating*, while I do receive notifications for *ALL* the rest of comments on other issues at the *leo-editor* repository and all other repositories I'm subscribed to!? I have already tried to remove and re-enable my subscriptions to both leo-editor repository and to these particular issues... without success. I've also revised all my GitHub account settings and checked any available checkbox about notifications. Nothing!

**Comment by edreamleo** [comment]
On Sat, Feb 25, 2017 at 2:02 PM, XGiD <notifications@github.com> wrote:

> Thanks for your fast response and for addressing all this.
>
​You're welcome.​


> does anybody know why I'm *NOT* receiving notifications by email of your
> comments to any *of the issues where I'm participating*, while I do
> receive notifications for *ALL* the rest of comments on other issues at
> the *leo-editor* repository and all other repositories I'm subscribed
> to!?
>
​It sounds like you've done all the obvious things. Have you tried
googling? If that doesn't work, I'd ask for help from the github people.

Edward
