### ISSUE TITLE
undo/redo 'refresh-from-disk' doesn't work

### ISSUE THREAD

**Issue by boltex** [leo-editor/leo-editor#3435]
Closed via PR #3438.

<details><summary>Original Report (edited)</summary>
<br>

To test this behavior, I tried making small text changes *without* changing the structure of the outline in external files. 

**Changes to c.p.b**

For both `@clean` and `@file`:

- `refresh-from-disk` does not update `c.p.b`.
- Undo/redo of `refresh-from-disk` do not undo/redo `c.p.b`.

**Structural changes**

Everything works as expected:

- `refresh-from-disk` for `@file` updates structural changes.
- Undo/redo `refresh-from-disk` work for `@file`.
- `@clean` never updates structure, so there is nothing to test.

</details>

**Summary of changes**

- `refresh-from-disk` and several `read-at-x-nodes` commands are no longer undoable.
  As a result, *the original report is moot*.
- All non-undoable commands and scripts should clear Leo's undo state by calling `u.clearAndWarn`.
- All commands that previously used `u.before/afterChangeTree` now use `u.before/afterInsertNode`.
  This works because the commands only insert one top-level node!

**Comment by edreamleo** [comment]
Closed via PR #3438.
