### ISSUE TITLE
@string view-rendered-default-kind not functional

### ISSUE THREAD

**Issue by ar-jan** [leo-editor/leo-editor#344]
Hi, I have some trouble getting markdown rendering to work as I would like.

The first thing I tried is to have a `@settings` node with a child `@string view-rendered-default-kind = md`. Now when I create a node with some text, when I do `vr-update` I do get a markdown rendering, but not any live updating of the ViewRendered pane.

If I create a tree with `@language md` in the body of the top node, I do get markdown with live updating in the viewrendered pane. Is it possible to get this live updating behavior with a document-wide setting (other than putting all nodes inside a single root node)? I tried adding a `@language md`, as well as a `@string target_language = md` node, under my `@settings`, but these aren't right. Thanks!

**Comment by edreamleo** [comment]
On Mon, Dec 5, 2016 at 12:01 PM, Arjan <notifications@github.com> wrote:

Is it possible to get this live updating behavior with a document-wide
> setting (other than putting all nodes inside a single root node)? I tried
> adding a @language md, as well as a
> ​​
> @string target_language = md node, under my @settings, but these aren't
> right.


​I see the behaviour you describe.  Please file an official bug report here
<https://github.com/leo-editor/leo-editor/issues>.

​EKR

**Comment by edreamleo** [comment]
Searching shows that default_target_language is used nowhere in Leo, so the corresponding setting is surely useless. The fix may not be straightforward, but surely it is needed.

**Comment by edreamleo** [comment]
Please reopen if problems remain.

**Comment by ar-jan** [comment]
Setting `@string target_language = md` under `@settings` in a test.leo works, gets me live markdown rendering - thanks.

I'm not sure if `view-rendered-default-kind` is also supposed to work now?  That still doesn't work (but it is listed as such in viewrendered2.py: `Unless ``@string view-rendered-default-kind`` is set to ``md``, markdown rendering must be specified by putting it in a ``@md`` node.`).

**Comment by edreamleo** [comment]
On Mon, Feb 27, 2017 at 3:05 PM, Arjan <notifications@github.com> wrote:

> Setting @string target_language = md under @settings in a test.leo works,
> gets me live markdown rendering - thanks.
>
​Good.
​


> I'm not sure if view-rendered-default-kind is also supposed to work now?
> That still doesn't work (but it is listed as such in viewrendered2.py: Unless
> ``@string view-rendered-default-kind`` is set to ``md``, markdown rendering
> must be specified by putting it in a ``@md`` node.).
>

​The VR2 plugin is another matter.  I'd rather not dig into that at this
time.

Edward
