### ISSUE TITLE
inconsistency with results of 'show-file-line' and 'goto-global-line' when used with @clean instead of @file

### ISSUE THREAD

**Issue by boltex** [leo-editor/leo-editor#3447]
**Summary**

PR #3477 fixes some bugs and adds an extensive new unit test.

However, `show-file-line` contains a bug that can not be fixed with any reasonable amount of work. The docstring for this command now documents this fact.

@boltex `show-file-line` will remain in Leo, but imo this command isn't needed in leoJS.

**Original report**

The `show-file-line` command gives the proper line numbers for external files derived from `@file`.

But this command shows the same line numbers for `@clean` as is does for `@file`.

**Comment by edreamleo** [comment]
@boltex This is an "interesting" issue. Leo directives (like `@others`)  in an `@clean` tree have no corresponding line in the external files.

**Comment by edreamleo** [comment]
Closed via PR #3477.
