### ISSUE TITLE
Ctrl-click on a Gnx-based UNL gives errors

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#3450]
Here are steps to observe the errors:
Ensure myLeoSettings has setting:
@string unl-status-kind = gnx

I have verified this behaviour with my usual myLeoSettings and a simple myLeoSettings which only contains this @string. 

Create a node TEST_NODE with no body text.
Get the Gnx-based UNL of the node e.g.
unl:gnx://workbook.leo#lewis.20230718202349.1
Ctrl-c the UNL.
Move to another node. Ctrl-v paste the UNL into the body text.
Now Ctrl-click the UNL
Cursor moves to TEST_NODE with no errors.

In TEST_NODE add some body text. Move back to previous node.
Ctrl-click the UNL
Cursor moves to TEST_NODE and gives errors in log pane:
_is_sentinel: can not happen. delims: (None, '')
is_sentinel: can not happen. delims: (None, '')
is_sentinel: can not happen. delims: (None, '')
is_sentinel: can not happen. delims: (None, '')_

It seems that the presence of body text has some effect.

Leo Log Window
Leo 6.7.4-devel, devel branch, build cc627472b3
2023-07-17 22:01:47 -0500
Python 3.11.3, PyQt version 6.5.1
Windows 10 AMD64 (build 10.0.19044) SP0

**Comment by tbpassin** [comment]
I did not get this error when I tried this, but my test had one difference:  my status bar is set to show old-style UNLs.

I also copied the GNX of the test node to the clipboard, using a script which adds the _gnx:_ prefix.  That also worked - that is, when the string was pasted, it highlighted and when CTRL-Clicked, Leo navigated to the target node.

In none of these tests did having text in the node's body change the behavior.

I wonder how we could have gotten such different results?  Nothing comes to mind so far.
```
Leo 6.7.4-devel, devel branch, build 947ea935f5
2023-07-06 08:01:34 -0500
Python 3.11.4, PyQt version 6.4.3
Windows 10 AMD64 (build 10.0.19045) SP0
````

**Comment by LewisNeal** [comment]
To clarify, did you ensure myLeoSettings has setting:
https://github.com/string unl-status-kind = gnx

**Comment by tbpassin** [comment]
No - that's why I said I've set my status bar display for old-style UNLs.  But CTRL-Clicking on the GNX string ought to give the same results as you.

Could you show the GNX string you used that didn't work right when the target node had text?  And were there any error messages in the log pane or console?

**Comment by LewisNeal** [comment]
Found it. I have been testing effect of local settings in the file. It contains _@string target_language = md_
When I remove the setting or change to _@string target_language = plain_  I no longer get errors.

As you said, the unl-status-kind = gnx made no difference.

**Comment by tbpassin** [comment]
Good you could find something definite, but it seems strange to me that the setting would have this effect.

**Comment by edreamleo** [comment]
@LewisNeal Glad you found the problem. I'm going to close this issue.
