### ISSUE TITLE
Ctrl-click on a Gnx-based UNL gives errors (@language cweb)

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#3459]
Ctrl-click on a Gnx-based UNL of a node which has @language directive
@language cweb
gives errors in Log pane:

is_sentinel: can not happen. delims: (None, '@q@', '@>')
is_sentinel: can not happen. delims: (None, '@q@', '@>')
is_sentinel: can not happen. delims: (None, '@q@', '@>')
is_sentinel: can not happen. delims: (None, '@q@', '@>')
is_sentinel: can not happen. delims: (None, '@q@', '@>')

**Comment by edreamleo** [comment]
This issue is a duplicate of issues #3457 and #3458.  The latter contains Thomas's detailed comments, so we'll leave #3458 open.
