### ISSUE TITLE
python importer places @others incorrectly

### ISSUE THREAD

**Issue by tbnorth** [leo-editor/leo-editor#346]
See https://github.com/tbnorth/gdalcomp/blob/15f0b6f/gdalcomp.py#L29,

```
Leo 5.4, build 20161208140632, Thu, Dec 08, 2016  2:06:32 PM
Git repo info: branch = master, commit = 3aac1a86f0bc
```

is importing this as:

```
# copied / adapted from http://pythonhosted.org/six/
if sys.version_info[0] >= 3:
    exec_ = eval('exec')
else:
    @others
```

this indents the entire remainder of the program, rather than just the `def exec_` block. Which would cause the code to do nothing in Py3, humorously it doesn't really impact it in Py2.

**Comment by edreamleo** [comment]
Thanks for this report.  Fixing this may require a major revision to the python importer, namely keeping track of indentation explicitly.  Clearly, this is possible: the old importer did it.

**Comment by edreamleo** [comment]
The strategy for fixing this bug is likely to be to duplicate the old importer's code generation logic in the new importer.  Again, this is clearly possible, but may take considerable effort.

**Comment by edreamleo** [comment]
Rev 655473b3a fixes several bugs in the python importer.  For the first time the importer is on a sound foundation.  In particular, python_i.end_block ends blocks properly.

**Comment by edreamleo** [comment]
I am going to reopen this.  There are multiple problems with the present python importer.  I'll fix them immediately.
