### ISSUE TITLE
"Joe Orr's must see demo." on https://leo-editor.github.io/leo-editor/ is a dead link

### ISSUE THREAD

**Issue by th** [leo-editor/leo-editor#3469]
Hi,

is that "must-see" somewhere available?

**Comment by LewisNeal** [comment]
The link works for me.

**Comment by th** [comment]
It leads to https://kaleguy.github.io/leovue/#/t/2/ where I don't see a video demo, but a landing page for LeoVue.

**Comment by th** [comment]
Where?

There is no video, no play button,. nothing. Just a picture gallery.

![grafik](https://github.com/leo-editor/leo-editor/assets/153996/990913e5-f7bd-4344-8e5d-61f5d2806b3e)

![grafik](https://github.com/leo-editor/leo-editor/assets/153996/fab2478d-57c0-49db-b26a-7c4c72a2119a)

**Comment by edreamleo** [comment]
@th The picture gallery is the demo. Anyway, the link isn't broken.

**Comment by th** [comment]
Okay. "Video" implies something more, but images are fine. Thanks!
