### ISSUE TITLE
Python parsing/reading bug and syntax error bug

### ISSUE THREAD

**Issue by JohnLunzer** [leo-editor/leo-editor#347]
On current master: 

If you clone this repo: https://github.com/scopatz/xo you'll see the program located entirely within xo.py.

When I create an `@clean xo.py` and then do a `refresh-from-disk` command to load in and parse the file (this is how I normally add new files) several functions are read in as section references.

On line 958 there is a lambda function defintion:
```python
ensure_endswith_newline = lambda x: x if x.endswith('\n') else x + '\n'
```

Now, if I move this line to 981, right above the def main, prior to loading in Leo then when I do the `@clean` and `refresh-from-disk` combo the file is parsed more how I would expect it, no section references in site. Note, all I did was move a single lambda definition. To me the fact that the location of this definition causes Leo to parse the file differently screams "bug".

Additionally in this same file, on line 193 Leo insists there is a syntax error but xo.py is interpreted and runs fine in python3.

**Comment by edreamleo** [comment]
I encountered exactly this problem myself, with similar workaround.

If there is a bug here, it is that the lambda doesn't become part of preceding node.  I'm agnostic about how easy this would be to fix.

**Comment by edreamleo** [comment]
Aside. Regardless of `auto` problems, I recommend the following workflow:

1. Change `@auto` to `@file`.
2. Create a git repo for xo.py.

After the first few commits, all changes will be the ones you made. You don't care about Leo sentinels, so there is no need to avoid them.  I'll be doing exactly as I suggest as I study xo.py.

EKR

**Comment by edreamleo** [comment]
Rev ce2ba48: A new unit test for this issue passes, regardless of leo.plugins.importers.python.NEW.

Not sure when this issue was actually fixed.
