### ISSUE TITLE
compareAnyTwoFiles does not update c.fileCommands.gnxDict properly

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#3470]
Make two (small) leo files with a difference in a node's body. 

Open the first one, and execute the compare-two-leo-files command, choosing the other one to compare.

The command will seem to have run successfully, seemingly adding a total of 3 nodes to the outline.

`g.printObj(c.fileCommands.gnxDict` content before and after launching the command.

Only two new gnxs in `c.fileCommands.gnxDict`.

**Comment by boltex** [comment]
Hoping #3471 fits the bill 😄

**Comment by edreamleo** [comment]
Fixed via PR #3471.
