### ISSUE TITLE
diff-marked-nodes creates two undo beads (instead of one.)

### ISSUE THREAD

**Issue by boltex** [leo-editor/leo-editor#3476]
Fixed via PR #3478. The culprit was a duplicate call to `u.afterInsertNode`.

Trying to do 'undo' after issuing this command works, (it removes the main diff node it created) but, obviously, undoing past that point creates an erroneous state eventually (as it tries to remove an _already removed_ node )

**Comment by edreamleo** [comment]
Fixed via PR #3478.
