### ISSUE TITLE
XML CDATA Sections not preserved on round-trip save

### ISSUE THREAD

**Issue by dreftymac** [leo-editor/leo-editor#348]
## Context

![context000](https://cloud.githubusercontent.com/assets/4074354/21118726/0313e2a8-c074-11e6-8b90-859d091ef4b5.png)

## Scenario

* User creates a leo file in the leo GUI.
* User then opens the leo file in a plain old text editor like Vim.
* User then adds a CDATA section to an t element in a tnodes section.
* User then re-opens the file in leo GUI and saves the file

## Problem

* Upon save, Leo editor strips out the XML CDATA
* This is a problem because some users may not want to have their data XML-Escaped, and instead preserved as raw text with absolutely no leo-based modifications.

## Question

Is there a setting or option that preserves the CDATA applied to tnodes/t element in leo?

**Comment by edreamleo** [comment]
Thanks for this report.  Leo uses the [xml.sax](https://docs.python.org/2/library/xml.sax.html) parser, so presumably this is a bug in the cdata handler.  I'll look into this asap.

**Comment by edreamleo** [comment]
[This page](https://docs.python.org/2/library/xml.sax.handler.html#xml.sax.handler.ContentHandler) shows there is no separate cdata handler. Googling "python xml.sax cdata" yields [this page](http://stackoverflow.com/questions/26121303/how-to-read-cdata-from-xml-file-with-python), which indicates that cdata comes in as part of the characters content handler.

Alas, Leo's content handler strips '\r' characters, and converts to unicode if necessary, though that usually is not necessary.  So it appears that preserving cdata unchanged will not be easy.

Happily, neither you nor your scripts should ever need to munge any .leo file by inserting cdata elements.  Instead, you should use [uA's](http://leoeditor.com/customizing.html#adding-extensible-attributes-to-nodes-and-leo-files) to add content to nodes. You can add uA's to any node, regardless of whether the node is in an `@<file>` tree or not. The str_ convention should allow any cdata to come in unchanged. 

I am going to close this issues for now.  Please reopen if there are problems using uA's to do what you want.
