### ISSUE TITLE
(consecutive) Backslashes in Find box are escaped passed the first one.

### ISSUE THREAD

**Issue by boltex** [leo-editor/leo-editor#3503]
Fixed via PR #3507.

The find result is unexpected because they are escaped: 
To reproduce: try finding the following text `a \ b` then try this one: `a \\ b`  in a leo file containing those three text entries.

```
a \ b
a \\ b
a \\\ b
```

_Found when testing find input box with consecutive backslashes in LeoInteg!_ 😄

**Comment by edreamleo** [comment]
Closed via PR #3507.
