### ISSUE TITLE
Enhancment Request: rename or alias the @clean directive, and all other directives that accept a <path>

### ISSUE THREAD

**Issue by dreftymac** [leo-editor/leo-editor#351]
## Context

* leo editor current version

## Problem

* leo editor now has the @clean directive, and this has the potential to greatly increase the adoption by new users, as already noted elsewhere by @edreamleo.

* the problem is, leo has some attributes that can be counter-intuitive for people who have not followed the editor throughout its lifecycle. These counter-intutive aspects make the editor much less approachable as a general-purpose tool. 

* the @clean directive is an example of a term that is counter-intuitive, because it does not clearly specify what it is, or why it has that name, until one has learned how that directive got its name (or unless one simply knows leo from its early beginnings ... which means by definition that is not a new adopter).

## Solution

* rename (or alias) the @clean directive to @file-clean (or something similar) ... and do the same thing for all other directives whose purpose is to output a file.
    * (eg) @clean --> @fileclean
    * (eg) @asis --> @fileasis
    * (eg) @nosent --> @filenosent
    * so forth
* aliasing the directives will have the obvious benefit of backward-compatibility, while still allowing for the documentation and front matter for leo to use less opaque terminology.

## Rationale

* directives like @clean and @nosent increase the apparent complexity of leo to newcomers, because they are path-dependent knowledge items that are difficult to grasp, unless you already know how leo works and its historical background.

**Comment by edreamleo** [comment]
I am not going to do this directly.  Iirc, Terry has written something that allows the user to define headline abbreviations.

Aliasing is possible, but would add another layer of complexity.

Renaming is not possible, as it would break existing outlines.

**Comment by tbnorth** [comment]
Not sure the headline abbreviation thing really addresses the OP's idea, although it could make @clean appear as @fileclean when not being edited.  But for newcomers, that might be more confusing than helpful - if they started entering @fileclean.  It's more typical use is to make @clean appear as an icon, a document with a C on it, to reduce screen space use by directives like @clean.  Maybe that addresses the OP's idea as it's a *file* icon.

Here's instructions for using it I wrote in response to a recent question:

Search for tree-declutter in leoSettings.leo.

set

```
@bool tree-declutter = True
```

then craete a `@settings` node

```
@data tree-declutter-patterns

can contain patterns like:

# remove @clean and use an icon
RULE ^@clean (.*)
REPLACE \1
ICON file_icons/file_clean.png

# show the last part of long filenames
RULE ^.{1,1000}([/\\])(.{25})
REPLACE …\1\2

# if the node name starts with 'peacock node DEMO', make a mess of it
RULE ^(peacock node DEMO)
REPLACE LOOK: \1
ICON Tango/16x16/emotes/face-grin.png
ICON Tango/16x16/emotes/face-wink.png
FG @solarized-magenta
BG white
FONT Times
PX 40
ITALIC 1
WEIGHT Bold
```
