### ISSUE TITLE
Text in QlineEdit#status never show node path

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#3513]
Now only show the node create time there. Is this a special design?

    unl:gnx://learning.leo#swot.20230811213018.1

Perhaps showing node path will be better.

<img width="600" alt="Xnip2023-08-24_04-58-41" src="https://github.com/leo-editor/leo-editor/assets/2628013/1edada9e-3546-4fda-80a5-f9947899e98c">

**Comment by tbpassin** [comment]
Yes, the whole unl machinery has been changed to use gnxs.  You can still see the old-style ones in the status bar by using the new setting

`@string unl-status-kind = legacy`

That's how I have set up myLeoSettings.leo because like you, I find the old path-based string to be much more useful.

**Comment by wangzhaohe** [comment]
@tbpassin Thanks for your @string unl-status-kind = legacy

It works well now!
