### ISSUE TITLE
mark-first-parents and unmark-first-parents should be undoable like other 'mark' related commands.

### ISSUE THREAD

**Issue by boltex** [leo-editor/leo-editor#3519]
See PR #3524.

mark-first-parents and it's unmark-first-parents sibling command should allow undo and redo to be performed. 

EKR: The legacy names are poor. I'll rename the commands to `mark-node-and-parents` and `unmark-node-and-parents`.

**Comment by edreamleo** [comment]
Closed via PR #3524.
