### ISSUE TITLE
'copy-gnx' does not put c.p.gnx on the clipboard.

### ISSUE THREAD

**Issue by boltex** [leo-editor/leo-editor#3528]
The command shortcuts and the docstring suggest that it should show an unl in the log pane, but put c.p.gnx on the clipboard.

It currently puts the unl on both the log pane and the clipboard.

**Comment by boltex** [comment]
Note : By 'log pane' I meant 'status Area'. 

I made a pull request for this small fix: https://github.com/leo-editor/leo-editor/pull/3529

**Comment by edreamleo** [comment]
Closed via PR #3529.
