### ISSUE TITLE
Python importer adds section references after decorator

### ISSUE THREAD

**Issue by tbnorth** [leo-editor/leo-editor#353]
The Python file that GitHub made me wrap in a .zip file: [winbut.zip](https://github.com/leo-editor/leo-editor/files/671310/winbut.zip)

gets `<<exit_>>` and `<<main>>` references after the @command decorator.

I would expect the decorator to get pushed down into the node, and no section references to be generated.

```
Leo Log Window
Leo 5.4, build 20161223095636, Fri Dec 23 09:56:36 EST 2016
Git repo info: branch = master, commit = d43617d6c81c
Python 2.7.5, PyQt version 4.8.5
Windows 7 AMD64 (build 6.1.7601) SP1
111

**Comment by edreamleo** [comment]
Thanks for this report.  I'll fix this next.

**Comment by edreamleo** [comment]
@tbnorth The example file works for me.  Are you sure you are using the latest code? The new code never generates sections references.

**Comment by tbnorth** [comment]
Very strange, it was definitely doing what I described, but I can't reproduce even going back to d43617d6c81c.  Different machine / OS / config. - I'll make myself a note to retest next week when I'm on the other system.  Stays closed for now of course.
