### ISSUE TITLE
When an opened Leo file change is detected, Leo should ask to 'revert' to saved file for that outline, instead of 'restart' the whole app.

### ISSUE THREAD

**Issue by boltex** [leo-editor/leo-editor#3533]
See PR #3535.

( I'm talking about an opened .leo outline itself, not it's external files) 

I think perhaps the 'restart' was originally used after .leo outline change detection because it was used by the Leo developers who were working on leoPyRef to get the new behavior, or, some other reason I can not really imagine...

I would propose that when an opened Leo outline is detected as being changed that the 'revert to saved' command was proposed by the UI instead of the 'restart' command, which is way overkill, and also does not work on some OSes. (e.g. ubuntu 20.) 

I will not do this modification myself right now because I'm not sure what is the reason behind the current behavior, and so I'll wait for the opinion of other people... but nonetheless, the revert command already exists, so it should be trivial to make this modification if it is approved by @edreamleo .

**Comment by edreamleo** [comment]
@boltex I agree, using Leo's `revert` command instead of `restart` should suffice.  I'll create a PR today, unless you have a PR ready to go.

**Comment by boltex** [comment]
I'm working on leojs this weekend :) so I'll leave this one to you hehe!

( I've only looked at it so far as to think g.app.loadManager.revertCommander is the call to make to revert an opened Leo outline )

**Comment by edreamleo** [comment]
On Sun, Sep 3, 2023 at 12:04 PM Felix ***@***.***> wrote:

> I'm working on leojs this weekend :) so I'll leave this one to you hehe!
>

That's fine. I'll create the PR soon.

Edward

**Comment by edreamleo** [comment]
Closed via PR #3535.
