### ISSUE TITLE
Documentation is squished on mobile

### ISSUE THREAD

**Issue by QJKX** [leo-editor/leo-editor#3542]
The documentation is hard to read on a cellphone in portrait on android (firefox).

https://leo-editor.github.io/leo-editor/installing.html

![Screenshot_20230904-121248_Fennec](https://github.com/leo-editor/leo-editor/assets/23462605/ac1865fa-d81e-4039-8702-e12cd5afbcc7)

The sphinx docs don't seem to have this issue:
https://www.sphinx-doc.org/en/master/

**Comment by QJKX** [comment]
The "homepage" looks fine:
https://leo-editor.github.io/leo-editor/
![Screenshot_20230904-125243_Fennec](https://github.com/leo-editor/leo-editor/assets/23462605/586d3ab9-5976-4268-a441-6e8d8e7bd6b2)

**Comment by edreamleo** [comment]
@QJKX There are no plans to fix this issue.
