### ISSUE TITLE
Alt-end perform the wrong command as per workbook.leo

### ISSUE THREAD

**Issue by boltex** [leo-editor/leo-editor#3543]
When trying out each default keybinding to select outline nodes in each of Leo, leojs and leointeg, I discovered that Leo seems to perform the wong command for those two keybindings:

**(Taken from workbook.leo)**
  ```
  Alt-End (goto-last-visible-node)
```

Alt-End is bound to goto-last-sibling instead of last-visible-node

**Maybe it's the documentation in workbook.leo that is wrong**, or, the default keybinding. 

Not sure, so I'll leave it to @edreamleo

**Comment by edreamleo** [comment]
On Mon, Sep 4, 2023 at 9:51 PM Felix ***@***.***> wrote:

> When trying out each default keybinding to select outline nodes in each of
> Leo, leojs and leointeg, I discovered that Leo seems to perform the wong
> command for those two keybindings:
>
The defaults in leoSettings.leo for alt-home and alt-end are:

goto-first-visible-node     = Alt-Home
goto-last-sibling           = Alt-End

But the documentation in CheatSheet.leo says, in the node "Selecting
outline nodes":

Alt-Home (goto-first-visible-node)
Alt-End (goto-last-visible-node)

Imo the default for Alt-home should be as documented, namely
goto-first-visible-node.

I'll change leoSettngs.leo accordingly.

Edward

**Comment by edreamleo** [comment]
PR #3544 changes the binding for `Alt-Home` and removes all mention of `read-outline-only`. All the check buttons in `leoSettings.leo` pass.
