### ISSUE TITLE
Make set-ua, clear-ua, clear-all-ua commands undoable.

### ISSUE THREAD

**Issue by boltex** [leo-editor/leo-editor#3545]
See PR #3732.

**Comment by boltex** [comment]
@edreamleo I went through the changes of this commit, but I don't see how this commit closes this issue..? Was it for some other issue perhaps? or from some other commit?

**Comment by edreamleo** [comment]
@boltex Thanks for the heads up. 

Rev 69e095f merges a PR that was misnamed as "Fixes #3645", which caused the merge to close the wrong issue!

**Comment by edreamleo** [comment]
Closed via PR #3732.
