### ISSUE TITLE
Saving .db files preserve the 'dirty' bit in the saved file, and applies it when opening such file.

### ISSUE THREAD

**Issue by boltex** [leo-editor/leo-editor#3550]
Although it clears it (visually in the outline pane) in Leo after saving, thus appearing as if the save operation cleared the dirty bits. 

Closing and reopening shows that the dirty bits were saved, and, are re-applied when opening the .db file.

(_discovered after implementing and testing .db file support in **leojs** with a simple outline after modifying a few nodes and saving+reopening the .db file_ 😃  )

**Comment by edreamleo** [comment]
@boltex Thanks for this issue, and for #3551. I have no knowledge of the code involved.

If you don't mind, please issue a PR that fixes both. Thanks.

**Comment by edreamleo** [comment]
@boltex On second thought, I will take a look at the code myself.

**Comment by edreamleo** [comment]
Fixed via PR #3552.
