### ISSUE TITLE
Saving .db files once already created on disk and modified asks for reload, as if dirtied externally..

### ISSUE THREAD

**Issue by boltex** [leo-editor/leo-editor#3551]
Hitting ctrl+s on a .db file which was already saved, and modified, makes Leo detect that own file change, erroneously asking if the user wants to reload the .db file - not recognizing that it was itself that just changed it by saving on disk.

The logic for .db files should be the same as .leo files regarding the self-change detection behavior.

**Comment by edreamleo** [comment]
@boltex This issue remains even in the branch that supposedly fixes #3550. I'll track it down.

**Comment by edreamleo** [comment]
Closed via PR #3554.
