### ISSUE TITLE
Scripting documentation for new users of leoeditor

### ISSUE THREAD

**Issue by dreftymac** [leo-editor/leo-editor#356]
### Context
* New adopter of leoeditor using the scripting interface for the first time

### Scenario
* using the tutorial-scripting page
* http://leoeditor.com/tutorial-scripting.html

### Issue
* the tutorial introduces a "hello world" example, which is clear and readily understood, even by non-python programmers, immediately after that however, it goes into fairly abstruse territory: vnodes, positions and other content that assumes familiarity with the internals of leo.
* this makes the tutorial-scripting page quite difficult to follow, even for experienced python programmers.
* moreover, the more abstruse content does not appear to be runnable. pasting the code into the editor and pressing `ctrl+b` does not produce any output.

### Question
* is there a step-by-step guide with easily-understood and *runnable* examples, that goes beyond the g.es `helloworld` example?

* it would seem useful to have an incremental introduction with *runnable* examples, each building upon the previous one, where each incremental step is runnable or capable of producing some kind of comprehensible output, without going into details about the internal guts of leo

* it would seem useful if the introduction included basic concepts that talk more about the end result (using outlines and things that can be done with them) without going into depth about the internal architecture of leo (which has changed in important ways over the years, further compounding difficulty and uptake by new users)

* for example ... a modified tutorial could be something like:
    * your first script ... helloworld
    * next script ... use python to create an outline node ;; with runnable example
    * next script ... use python to duplicate an outline node ;; with runnable example
    * next script ... use python to create five outline nodes, each with a different name
    * next script ... use python to populate node bodies with dynamic values (e.g., current date)
    * next script ... use python to generate an output html or text file of the nodes you just created

Each of the above examples could just gloss over the internal architecture, (but still reference architecture with links elsewhere in the documentation -- for more details see ....). This would give new users exposure to the editor itself without confusing nomenclature that does not make much sense, except to experienced users (or developers) of the tool.

**Comment by tbnorth** [comment]
On Tue, 03 Jan 2017 03:18:53 -0800
Dreftymac <notifications@github.com> wrote:

> ## Problem
> 
> ### Context
> * New adopter of leoeditor using the scripting interface
> 
> ### Scenario
> * using the tutorial-scripting page
> * http://leoeditor.com/tutorial-scripting.html
> 
> ### Issue
> * the tutorial introduces a "hello world" example, which is clear and
> readily understood, even by non-python programmers, immediately after
> that, it goes into fairly abstruse territory: vnodes, positions and

Abstruse you say...

http://abstrusegoose.com/474

:-)  (scroll down to caption at bottom)

Cheers -Terry

> other content that assumes familiarity with the internals of leo
> * moreover, the more abstruse content does not appear to be runnable,
> pasting the code into the editor and pressint `ctrl+b` does not
> produce any output
> 
> ### Question
> * is there a step-by-step guide with easily-understood and *runnable*
> examples, that goes beyond the g.es `helloworld` example?
> 
> 
>

**Comment by dreftymac** [comment]
Having said that, let me not hesitate to add much congrats and appreciation to both you, Ed and all the others who have contributed to this great software. Hats off to you guys.

**Comment by edreamleo** [comment]
I like this issue, if only to remind me that the present tutorials need to be revised, somehow.

The pyzo "wizard" (really, a slideshow, available from the help menu), could be a model for all of Leo's revised tutorials.  It's a model both for content (what the user sees) and implementation (a series of docstrings). Like I said, pyzo is a work of genius, and Leo must beg/borrow/steal as much of it as possible.

**Comment by satishgoda** [comment]
@edreamleo Awesome. 

While I was learning Leo couple of months back, i took some notes and placed them at the github repo below

https://github.com/satishgoda/leo-editor-tutorial/tree/master/reference/scripting
https://github.com/satishgoda/leo-editor-tutorial/tree/master/workflows

I am currently going through an online course on python/matplotlib for dataviz. I am using Leo to document and work out the examples (See image below). As part of the leo distribution we could provide examples Leo files clearly demonstrating the disparate use cases that Leo can be fitted.

![leo_usecase](https://cloud.githubusercontent.com/assets/536008/21877940/b7118392-d8c9-11e6-9a26-7b9bd79eb87e.png)

**Comment by edreamleo** [comment]
@satishgoda Great examples and screenshots.

I'll be turning my attention more to documentation and tutorials as I prepare for 5.5b1. I'll want to include some of the material you reference above.

**Comment by tanstaaf1** [comment]
@dreftymac I think you are proposing what "the world" has been waiting for: a way for a *beginning* python programmer of at least average intelligence to try out Leo in 5 to 15 minutes in a simple but complete context and decide it is a better fit than, say, IDLE or Atom for learning Python.

From a marketing perspective I'm saying there has been a poor understanding of the needs and description of the natural target market for a hierarchical programmers' editor.  Hopefully 2017 will be the year that is finally corrected.  Let us also hope that when Leo is presented at its best it surprises and delights instead of crashes and frustrates.

Personally I'm still waiting for evidence Leo might be something which will help me.  How many other people have looked at Leo in the last 3 months and gone on their way because there wasn't even a *single*, complete useful beginning example to play with?  How long would it take for an experienced Leo user to create such an example?  Maybe 15 minutes for the rough draft and a few hours for a *series* of extended examples?

**Comment by dreftymac** [comment]
@tanstaaf1 Ed can address a lot of these concerns, but from my own perspective, leo has been around for a while now, and it is not surprising that it occupies the niche that it does.

First off, the tool is fairly sophisticated, relative to others in the same space, and on that basis alone, it is not likely to appeal to casual users or developers. Secondly, it is a fairly common phenomenon for open-source software to emphasize the internals more than others, because the culture is one of hackers and technical people expressing their enjoyment of their craft ... which most end-users quite frankly do not care about.

It takes someone with a marketing and communications inclination (or a developer who is not averse to wearing that hat) to make a product like this really shine to end-users and people who do not really want to "hack on the tool" to make it their own.

For me, I am just someone with strong time pressures and I already knew about leo several years ago, and am just coming back to it, so I have relatively fresh eyes, but also knowledge of what the tool can do, and how it has evolved.

**Comment by satishgoda** [comment]
@edreamleo That is great to hear. Feel free to use/reference my examples. Thank you!

**Comment by edreamleo** [comment]
81a2007 contains the new scripting docs.
