### ISSUE TITLE
@auto whitespace sensitivity, nodes not generated

### ISSUE THREAD

**Issue by tbnorth** [leo-editor/leo-editor#357]
When I use @auto to import
<https://raw.githubusercontent.com/tbnorth/sheet_stats/9858ccb/sheet_stats.py>
with

```
Leo 5.4, build 20170102094113, Mon Jan  2 09:41:13 EST 2017
Git repo info: branch = master, commit = 52557743a3d2
Python 2.7.5, PyQt version 4.8.5
Windows 7 AMD64 (build 6.1.7601) SP1
```

all the code gets appended to the AttrDict node.  The source has two few blank lines between blocks, e.g. it needs another blank line before `def make_parser()`, but only for aesthetics.  When the extra lines are added, the file imports correctly.

**Comment by edreamleo** [comment]
I am kinda in a state of shock after studying the Pyzo importer/syntax colorer for Leo.  They work together to produce what looks like a 10x+ speedup over Leo's much more complex code.

I'll look at this issue soon, but a complete rewrite of Leo's python importer (at least) may be in the works.

**Comment by edreamleo** [comment]
I don't see this behavior, either in the old importers or the new. `@auto` works as expected, as does a new unit test.

**Comment by tbnorth** [comment]
I'm not seeing it in current trunk either, no point in testing the old version.

**Comment by edreamleo** [comment]
On Sun, Jan 22, 2017 at 8:37 AM, Terry Brown <notifications@github.com>
wrote:

> I'm not seeing it in current trunk either, no point in testing the old
> version.
>
​Thanks for the confirmation.

EKR
