### ISSUE TITLE
restoreDescendantAttributes error

### ISSUE THREAD

**Issue by rossburnett** [leo-editor/leo-editor#358]
Reading LeoPyRef.leo generates this error:
restoreDescendantAttributes: can not find VNode (expanded): gnx = ekr.20161017044014.1, tref: ekr.20161017044014.1

_Leo 5.4, Sat Oct 22 06:39:42 2016
Git commit: after ff
Python 3.5.2, PyQt version 5.6.0
Windows 10 AMD64 (build 10.0.14393) SP0
reading: C:\Leo-5.4\leo\core\LeoPyRef.leo
reading: @edit load-leo.html_

**Comment by edreamleo** [comment]
This is an informational message.
