### ISSUE TITLE
Add documentation about @rclick method for sub-menus

### ISSUE THREAD

**Issue by boltex** [leo-editor/leo-editor#3586]
Document that the intermediate node has to be empty for sub menus to exist as children of rclick node, and so on. :)

as per https://groups.google.com/g/leo-editor/c/rNTMxpAuFb8/m/rOxkvyGTAQAJ

The actual task: document the `build_rclick_tree` function in mod_scripting.py.

**Comment by edreamleo** [comment]
Closed via PR #4025.
