### ISSUE TITLE
LeoServer: unlock/remove more 'minibuffer' commands from the 'bad' list.

### ISSUE THREAD

**Issue by boltex** [leo-editor/leo-editor#3587]
**in short**, some commands could be removed for the server's 'bad' list. _(with careful testing)_

**Explanation:**
Since the first implementation of the minibuffer in leointeg, and the ability for the server to return acceptable command lists, the cursor position and current text selection has been available for a while now.  (so commands such as 'extract' and other relating to the cursor position and text selection as possible) 

The server's 'bad' list of commands contain text-editing commands that could be made available, and some other commands, the 'eval', 'eval-block'... set of commands could possibly be also made available, among others.

I'll try out some of them in the near future to do some cleanup in that list.

**Comment by boltex** [comment]
The server should also have commands made available to _get_, _add_ to , and _replace_ the minibuffer's command history lists. (on a per-commander basis.)

**Comment by edreamleo** [comment]
@boltex I've reassigned this issue to 6.7.6 because it does not affect leoJS.

**Comment by boltex** [comment]
No need to reassigned: This was fixed by pull #3599 😄 

I had forgot to mention that it fixed #3587 in the commit messages.

**Comment by edreamleo** [comment]
@boltex Thanks for clearing up this issue.
