### ISSUE TITLE
Leo can't read .leo files outside the outline's directory

### ISSUE THREAD

**Issue by boltex** [leo-editor/leo-editor#3590]
See PR #3591.

**Félix**: Opening any project outside of Leo's installation folder breaks all file paths.

<details>

Loading projects from leoPyRef.leo is fine:
![image](https://github.com/leo-editor/leo-editor/assets/847716/2785097a-eb4a-4ff6-a7bd-d95a78fe5da5)

but any project outside of Leo's installation folder has the Leo's folder base path prefixed, so nothing works: 
![image](https://github.com/leo-editor/leo-editor/assets/847716/fe917fd1-f5d7-40eb-99dc-feb53d64e908)

</details>

This is a serious bug. It's been around for a long time.

**Comment by edreamleo** [comment]
@boltex Thanks for this report. I'll fix it asap.

**Comment by edreamleo** [comment]
Fixed via PR #3591.
