### ISSUE TITLE
Retire all eval commands

### ISSUE THREAD

**Issue by boltex** [leo-editor/leo-editor#3598]
**Félix**: The 'eval' commands defined in the mod_scripting plugin do not respect text selection. The commands use the **lines containing the selection** instead of the  selected text. 

The following examples given in mod_scripting does not work:

<details>
<br>

eval-last
---------

Inserts the result of the last eval in the body.
Suppose you have this text::

    The cat is 7 years, or 7*365 days old.

To replace 7*365 with 2555, do the following::

    select 7*367
    eval
    delete 7*365
    do eval-last

eval-replace
------------

Evaluates the expression and replaces it with the computed value.
For example, the example above can be done as follows::

    select 7*367
    eval-replace

</details>

**EKR**: Imo, the `EvalController` class and all its commands should be retired. `execute-script` suffices.

**Comment by boltex** [comment]
Also, another possible bug with 'eval' : the 'eval' command documentation says it selects the next line, **to help in executing line by line**, but doing so it keeps the above line(s) in a selection, therefore re-executing each previous lines when used in this manner.  

(meaning that this adds lines in a selection set, placing the cursor on the next line indeed, but keeping the above lines selected feels like a bug, unless I'm mistaken)

**Comment by edreamleo** [comment]
Closed via PR #3600.
