### ISSUE TITLE
Warn if @path appears in body text in @file nodes

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#3610]
See PR #3611.

 `@path` is not allowed in the body text of `@file` nodes. However, I recently forgot, which lead to the erroneous issue #3609.  Leo's read code should issue the appropriate warning.

Leo's [Directive Reference](https://leo-editor.github.io/leo-editor/directives.html#part-5-all-other-directives) should also be improved.

**Comment by tbpassin** [comment]
Special case: you want to include the string _@path_ in the body text but not as a directive (maybe for documentation purposes).  

I assume you mean an `@path` at the start of a line.  If this is right, your wording needs to be more specific about where the `@path` string is allowed.

**Comment by edreamleo** [comment]
Closed via PR #3611.

**Comment by edreamleo** [comment]
@tbpassin I see no reason to discuss `@path` differently from other Leo directives.

Directives are similar to python decorators. They can only appear at the start of a line. I a dev wants to talk about a directive in (say) a docstring, then the dev must take a bit of care.
