### ISSUE TITLE
Leo's console gui won't run on Python 3.12+ and Windows

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#3615]
On Windows, Leonistas wanting to use Leo's console gui must use Python 3.11 or earlier. Here's why:

Leo's console gui (the cursesGui2 plugin) requires the [curses](https://docs.python.org/3/library/curses.html#module-curses) module in the Python standard library.

On Windows ,the curses module depends on the [windows-curses](https://github.com/zephyrproject-rtos/windows-curses) module, which is *not* part of the Python standard library. 

There are no bindings for windows-curses for Python 3.12. This sad state of affairs will continue for foreseeable future: windows-curses is no longer actively supported.

**Comment by tbpassin** [comment]
The pip install from PyPi fails because windows-curses isn't available.  This affects many or all versions of Leo, not just 6.7.4.

**Comment by edreamleo** [comment]
@tbpassin You are correct. This issue applies to *all* versions of Leo.

**Comment by tbpassin** [comment]
So Leo needs to have a conditional import of windows-curses and to disable the curses GUI if it's not available. And the installer needs to continue the installation even if windows-curses doesn't exist, which it doesn't right now.

**Comment by maphew** [comment]
Upstream windows-curses has been updated to work with python 3.12, https://github.com/zephyrproject-rtos/windows-curses/pull/44
