### ISSUE TITLE
default_path within @rst-options honoured or ignored depending on the node where rst3 command is executed

### ISSUE THREAD

**Issue by ranvik14** [leo-editor/leo-editor#362]
When I use the rst3 command on (or below) the node that defines the `@rst-options` it is honored.

When I use the rst3 command on a node higher up in the outline hierarchy it is ignored.

**Log 1: option honored**

PS C:\Users\Viktor\worklogs> leo wl2017.leo

C:\Users\Viktor\worklogs>C:\Programs\Python36\python.exe C:\Users\Viktor\Programs\Leo-20170106\launchLeo.py wl2017.leo
leoID=VIRA2017 (in C:\Users\Viktor\.leo)
reading settings in C:\Users\Viktor\Programs\Leo-20170106\leo\config\leoSettings.leo
reading settings in C:\Users\Viktor\.leo\myLeoSettings.leo
reading settings in C:\Users\Viktor\worklogs\wl2017.leo

** isPython3: True
Leo 5.4, build 20170105133315, Thu Jan  5 13:33:15 EST 2017
Not running from a git repo
Python 3.6.0, PyQt version 5.7.1
Windows 10 AMD64 (build 10.0.14393) SP0
wrote recent file: C:\Users\Viktor\.leo\.leoRecentFiles.txt
reading settings in C:\Users\Viktor\Documents\leo-asap\mcve-for-rst3-issue-1.leo
created directory: C:\Users\Viktor\Documents\leo-asap\MCVE\Logs\2017\01\CWxx
wrote: C:\Users\Viktor\Documents\leo-asap\MCVE\Logs\2017\01\CWxx\LE-2017-01-dd.html.txt
stylesheet not found
 C:\Users\Viktor\Documents\leo-asap\default.css
@path: C:\Users\Viktor\Documents\leo-asap
open path: C:\Users\Viktor\Documents\leo-asap
wrote: C:\Users\Viktor\Documents\leo-asap\MCVE\Logs\2017\01\CWxx\LE-2017-01-dd.html <- !!!
rst3: 1 files in 0.48 sec.

**Log 2: option not honored**

wrote: C:\Users\Viktor\Documents\leo-asap\LE-2017-01-dd.html.txt
stylesheet not found
 C:\Users\Viktor\Documents\leo-asap\default.css
@path: C:\Users\Viktor\Documents\leo-asap
open path: C:\Users\Viktor\Documents\leo-asap
wrote: C:\Users\Viktor\Documents\leo-asap\LE-2017-01-dd.html <- !!!
wrote: C:\Users\Viktor\Documents\leo-asap\LE-2017-01-dd.html.txt
stylesheet not found
 C:\Users\Viktor\Documents\leo-asap\default.css
@path: C:\Users\Viktor\Documents\leo-asap
open path: C:\Users\Viktor\Documents\leo-asap
wrote: C:\Users\Viktor\Documents\leo-asap\LE-2017-01-dd.html <- !!!
wrote: C:\Users\Viktor\Documents\leo-asap\LE-2017-01-06.html.txt
stylesheet not found
 C:\Users\Viktor\Documents\leo-asap\default.css
@path: C:\Users\Viktor\Documents\leo-asap
open path: C:\Users\Viktor\Documents\leo-asap
wrote: C:\Users\Viktor\Documents\leo-asap\LE-2017-01-06.html <- !!!
rst3: 3 files in 0.17 sec.

**Example**

[This page](https://groups.google.com/forum/?fromgroups=#!topic/leo-editor/AoyZSWfIPFg) contains an attached outline of a simple example. Github does not accept Leo files directly ...

**Comment by edreamleo** [comment]
I have a vague memory that this is actually a docutils bug.

**Comment by edreamleo** [comment]
I've just added the 5.5 milestone, but it may be that the resolution will be to mark this as "Can'tFix".
