### ISSUE TITLE
Vim mode broken?

### ISSUE THREAD

**Issue by ipsod** [leo-editor/leo-editor#3626]
Hi.

I'm new to Leo, so please forgive me if I'm overlooking something obvious.

# I set up vim mode
I copied the `@keys Vim bindings` node as instructed [here](https://leoeditor.com/vimBindings.html#using-leo-s-native-vim-mode) and rebooted Leo.  Then, vim-mode seemed to be working, but after entering insert mode ("Insert State", Leo says, and the cursor changes), it still seems to be  running normal mode commands.

# Some behavior in "Insert State":
* `fi` finds the next instance of 'i'
* `<esc>` toggles back to "Command State"
* `w` goes to end of current word (would usually be `e`, in vim - `w` would go to beginning of next word)

# I tried starting from scratch
I tried deleting ~/.leo, uninstalling, deleting the virtualenv, creating a new virtualenv, installing leo, and setting it up again, but I got the same result.

**Comment by edreamleo** [comment]
@ipsod Thanks for this report. Please ask your question on [Leo's Forum](https://leo-editor.github.io/leo-editor/). That way more people may respond.
