### ISSUE TITLE
Outline "leoPluginRef.leo" is/ seems to be inconsistent on GitHub

### ISSUE THREAD

**Issue by ranvik14** [leo-editor/leo-editor#363]
I updated Leo to the latest ZIP-Archive from GitHub

<Log-1>

C:\Users\Viktor\worklogs>C:\Programs\Python36\python.exe C:\Users\Viktor\Programs\Leo-20170106\launchLeo.py wl2017.leo
leoID=VIRA2017 (in C:\Users\Viktor\.leo)
reading settings in C:\Users\Viktor\Programs\Leo-20170106\leo\config\leoSettings.leo

reading settings in C:\Users\Viktor\.leo\myLeoSettings.leo
reading settings in C:\Users\Viktor\worklogs\wl2017.leo

** isPython3: True
Leo 5.4, build 20170105133315, Thu Jan  5 13:33:15 EST 2017

Not running from a git repo
Python 3.6.0, PyQt version 5.7.1
Windows 10 AMD64 (build 10.0.14393) SP0

</Log-1>

I opened the outline "LeoPluginRef.leo" via Plugin -> open-leo-Plugins-leo

<Log-2>

reading settings in C:\Users\Viktor\Programs\Leo-20170106\leo\plugins\leoPluginsRef.leo
callback *moving* <VNode 19e93f44c88 i. to be retired> 1 <VNode 19e93f44d30 i.scan_table>

resurrected node: i.scan_table
in file: @file importers/linescanner.py
callback *moving* <VNode 19e93f44b70 i.Scanning & scan tables> 0 <VNode 19e93f44c88 i. to be retired>

resurrected node: i. to be retired
in file: @file importers/linescanner.py
wrote recent file: C:\Users\Viktor\.leo\.leoRecentFiles.txt

</Log-2>

I closed the outline "LeoPluginRef.leo". - Note: I did not have to save anything!

Then I re-opend this outline using the same method & received the outline in a modified state.

<Log-3>

reading settings in C:\Users\Viktor\Programs\Leo-20170106\leo\plugins\leoPluginsRef.leo

cached read node changed: class Rst_Importer
PS C:\Users\Viktor\worklogs>

</Log-3>

I closed Leo without making any changes.

In my opinion I should consistently receive every Leo outline in a read-only mode - until - *I* make an explicit change to it.

This issue was previously reported to https://groups.google.com/forum/?fromgroups=#!topic/leo-editor/bY8qBS8YYD4

**Comment by edreamleo** [comment]
I have been taking more care to update leoPyRef.leo.  That should fix this bug.  Please reopen if further problems remain.

**Comment by ranvik14** [comment]
Hello Edward,

2017-01-20 20:35 GMT+01:00 Edward K. Ream <notifications@github.com>:

> I have been taking more care to update leoPyRef.leo. That should fix this
> bug. Please reopen if further problems remain.
>
I do not see the previously reported behaviour anymore.

Neither for leoPyRef nor for leoPluginRef.leo.

Thanks a lot for taking care of this issue!

With kind regards,

VR
