### ISSUE TITLE
Read sentinels more robustly

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#3657]
See PR #3678.

**Leo will continue to support Black-compatible sentinels**

Leo's  `--black-sentinels` (`-b`) command-line option will remain.

**Leo's read code should handle sentinels more robustly**

The legacy code assumed that all sentinels have the same form (blackened or not) as the open `@+leo` sentinel.

This assumption can be incorrect when doing a `git merge`!

PR #3678 make the read code more robust and improves related unit tests.

**There is little need for write Black-compatible sentinels**

Those using Leo in an environment that mandates Black formatting are likely using `@clean` or `@auto` to avoid using sentinels.

Orange (Leo's beautifier) is superior to Black for all my work.

**Comment by tbpassin** [comment]
What about backward compatibility - i.e., working with files made previous to these black-compatible changes?

**Comment by edreamleo** [comment]
For several years now Leo has been able to read external files in either format.

**Comment by edreamleo** [comment]
I am going to close this issue. I've changed my mind. Black is not worth supporting directly, at least for now.

**Comment by edreamleo** [comment]
Fixed via PR #3678.  Please reopen if necessary.
