### ISSUE TITLE
Add better support for jupyter notebooks

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#366]
This item was initially called "Allow Leo nodes to work like Jupyter cells" This [design document](https://groups.google.com/forum/#!topic/leo-editor/5AryK8fvje8) and these [implementation notes](https://groups.google.com/forum/#!topic/leo-editor/cEahcRp0jME) contain the initial ideas.

A year later a much simpler plan has appeared, documented in the post [The road map for 2018: visualization & services](https://groups.google.com/forum/#!topic/leo-editor/5jydZQF26iE).

The following projects come to mind:

- [ ] Improve the VR plugins so the rendered output of a tree of Leo nodes looks like a jupyter notebook.
- [ ] Add convenient access to jupyter kernels.
- [ ] Add or enhance directives to split body text into different rendering regions.
- [ ] #440: Use tags in `@language directives` to improve the rst3 command.
- [ ] Improve support for the valuespace plugin.
- [ ] Better visualization of attributes, the "hidden" part of Leo nodes.

This issue relates to #440 (Allow args to `@language directive) and #447 (VR plugin should be improved).

**Comment by satishgoda** [comment]
@edreamleo During my jupyter exploration (reading documentation) I came across the article below. I thought it might be helpful for this issue.

https://jupyter.readthedocs.io/en/latest/architecture/how_jupyter_ipython_work.html

**Comment by edreamleo** [comment]
I am going to close this.  It has been folded into #797: Summary: jupyter-related issues.
