### ISSUE TITLE
'New' document tabs & window-title are sometimes created with the 'branch name' prefix before the title.

### ISSUE THREAD

**Issue by boltex** [leo-editor/leo-editor#3660]
See PR #3663.

As a context to explain this bug, shown in the this first screenshot, 'small2.leo' does not show the branch name in the tab, only in the 'windows' title bar, as is expected...

But, strangely, sometimes creating a new document with ctrl+N adds a branch info prefix for the untitled new file, (same screenshot below, see the rightmost tab) which should not be assigned to any folder/branch or anything really, as it is a new, unsaved, document. (Note: when this happens, it also has it in the  'windows' title bar instead of just 'untitled'.)

[small2.leo](https://github.com/leo-editor/leo-editor/assets/847716/4b55e888-c95a-43d8-a4de-7fb7572e394e)

After doing a few experiments, after opening leo who also opens the last session files normally, creating new files is ok, but after I manually open another leo file, then after that point the new files are created with the branch-name prefix in both tab and windows title bar.

 (see below where they are arranged from left to right to show the behavior more clearly: From left to right: I start with  'myLeoFile.leo' already opened, and I create 2 new files, so far so good, then I open 'small2.leo', oh-oh, subsequent new files are created with the branch prefix anomaly in the tab and windows title bar. )

[myLeoFile.leo](https://github.com/leo-editor/leo-editor/assets/847716/298e2a9c-e36e-4dc4-a162-69f48c99a62f)

**Comment by edreamleo** [comment]
@boltex Thanks for this report. PR #3663 will soon fix this issue.
