### ISSUE TITLE
_About shortcut specifiers_ contains out-of-date Tk information

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#3665]
See PR #3674.

In LeoSettings.leo. the node `About shortcut specifiers` contains` the following:

> Leo passes all other mult-character names verbatim to Qt, so on some platforms
> you may be able to use any of the following. Most appear on the numeric keypad.
> For example, the following may work on some systems:
>     
> "Ctrl+BackSpace"
> 
> Don't use these if you want to be sure that the binding work on all platforms.
> The complete list of names may be found at:
> http://tcl.activestate.com/man/tcl8.4/TkCmd/keysyms.htm.

Isn't the list of key specifiers obsolete, since Leo isn't using Tcl/Tk? 
**Answer**: The Tk list is a gui-independent *reference*. 

"Don't use these" is not clear. Which ones are we not to use?  Just _Ctrl+BackSpace_ of the list a few lines later?
**Fixed in the PR**

**Comment by edreamleo** [comment]
@tbpassin Leo uses the Tk list for shortcuts even though Leo no longer uses Tk.

This is not bad design, nor can it be changed. Leo has to have a *stable* reference point for *all* guis, now and in the future.

**Comment by tbpassin** [comment]
OK, just wanted to be sure it wasn't an oversight.

**Comment by edreamleo** [comment]
I am going to reopen the issue. Yes, the code should stay as it is, but the documentation needs more work.

**Comment by edreamleo** [comment]
Closed via PR #3674.
