### ISSUE TITLE
unsaved untitled files should not make an entry in sessions. 

### ISSUE THREAD

**Issue by boltex** [leo-editor/leo-editor#3671]
See PR #3675.

When saving session, to be reopened at the next Leo startup, an UNL is saved for each opened window frame that was opened upon closing it... 

But,  unsaved untitled files cannot be reopened and should not be used to create an invalid UNL in the sessions data, which gives those lines in the terminal upon reopening Leo after closing with with any number of unsaved untitled file:

[image](https://github.com/leo-editor/leo-editor/assets/847716/1832740b-7e6b-4199-9f78-31f5961b8a2f)

`SessionManager.get_session` should skip those files.

**Comment by edreamleo** [comment]
Closed via PR #3675.
