### ISSUE TITLE
Leo does not start when using PyQt6.6.1

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#3684]
With PyQt-Qt6 version 6.6.1 installed on Windows Leo does not start.
```console
_Can not load the requested gui: qt
*** Leo could not be started ***

Please verify you've installed the required dependencies:
https://leo-editor.github.io/leo-editor/installing.html_
```

There are no other messages in log.
```
Leo 6.7.6-devel, devel branch, build e8b93df1f2
2023-11-30 20:42:40 -0600
Python 3.12.0
Windows 10 AMD64 (build 10.0.19045) SP0
```
There are no problems with PyQt-Qt6 version 6.6.0.

**EKR Summary**

My experiments show that PyQt 6.6.0 is defective for both Python 3.11 and 3.12.

This appears to be a PyQt bug. There is nothing Leo can do to recover from the failure to import QtCore.

**Comment by tbpassin** [comment]
I can confirm this.  I tried it in a venv.

**Comment by edreamleo** [comment]
@tbpassin @LewisNeal 

Thanks for these reports. I discovered another problem with Python 3.12. After `pip install pyqt6`:
```console
C:\Repos\leo-editor>python
Python 3.12.0 (tags/v3.12.0:0fb18b0, Oct  2 2023, 13:03:39) [MSC v.1935 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import PyQt6
>>> from PyQt6 import QtCore
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: DLL load failed while importing QtCore: The specified procedure could not be found.
>>>
```
Happily, Leo does load with pyqt5 and python 3.12.

**Comment by tbpassin** [comment]
I was just about to post the same thing in a slightly different form:
```
>>> import PyQt6.QtCore
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: DLL load failed while importing QtCore: The specified procedure could not be found.
```

Looks like PyQt 6.1 is defective (possibly just for Python 3.12?).

**Comment by edreamleo** [comment]
@tbpassin Apparently [QAction](https://doc.qt.io/qt-6/qaction.html) is in the QtGui module as of Qt 6.6.1.

**Comment by edreamleo** [comment]
@tbpassin My experiments show that PyQt 6.1 is defective for both Python 3.11 and Python 3.12.

**Comment by edreamleo** [comment]
@tbpassin Furthermore, I am no longer able to run *any* version of PyQt6 with Python 3.11.

`pip list` shows what appear to be conflicting versions of various Qt6-related packages.

I'll attempt to force a clean install (without cached files).

**Comment by edreamleo** [comment]
Alright. PyQt6 runs again on Python 3.11 after `pip install PyQt6-Qt6==6.5.3`. Here is Leo's log:
```
Leo Log Window
Leo 6.7.6-devel, ekr-3684-compatibility branch, build e8b93df1f2
2023-11-30 20:42:40 -0600
Python 3.11.4, PyQt version 6.5.3
Windows 10 AMD64 (build 10.0.22621) SP0
```
`pip list` is now:
```Console
PyQt5                         5.15.10
PyQt5-Qt5                     5.15.2
PyQt5-sip                     12.13.0
PyQt6                         6.5.3  <=== Now matches
PyQt6-Qt6                     6.5.3
PyQt6-sip                     13.6.0
```

**Comment by tbpassin** [comment]
I get the same 6.6.0/6.6.1 mismatch.  I deleted all the pyqt6 dist-info files, reinstalled (in a venv) and again got the same mismatch, even when I told pip to install 6.6.0.  It seems the provisioning for 6.6.x is borked.

**Comment by LewisNeal** [comment]
PyQt6 6.6.1 was released a few days ago and I am running Leo using:

PyQt6             6.6.1
PyQt6-Qt6      6.6.1
PyQt6-WebEngine-Qt6      6.6.1

It seems the staggered release of v6.6.1 caused problems.

**Comment by tbpassin** [comment]
I've verified that 6.6.1 installs and runs for me today.  Don't forget to install pyqt6-webengine too!
