### ISSUE TITLE
leoserver.py passes an incorrect argument to websockets.exceptions.ConnectionClosed

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#3686]
Rev 868a03d suppresses the mypy warnings (see below) pending resolution of this issue.

`ws_handler` (the server main loop) contains this code:

```python
except TerminateServer as e:
    # pylint: disable=no-value-for-parameter,unexpected-keyword-arg
    raise websockets.exceptions.ConnectionClosed(code=1000, reason=e.__str__())
```

As you can see, pylint has always complained about this call.

Recent versions of mypy now also complain:
```console
mypy-leo
leo\core\leoserver.py:5450: error: Unexpected keyword argument "code" for "ConnectionClosed"  [call-arg]
C:\Python\Python3.11\Lib\site-packages\websockets\exceptions.py:91: note: "ConnectionClosed" defined here
leo\core\leoserver.py:5450: error: Unexpected keyword argument "reason" for "ConnectionClosed"  [call-arg]
C:\Python\Python3.11\Lib\site-packages\websockets\exceptions.py:91: note: "ConnectionClosed" defined here
```
It's time to fix this quirp. [Here](https://websockets.readthedocs.io/en/stable/reference/exceptions.html#websockets.exceptions.ConnectionClosed) is a documentation for `ConnectionClosed`.

**Comment by boltex** [comment]
I'm going to look into it right away.

**Comment by boltex** [comment]
Just found out how to use this properly thanks to https://github.com/cderici/python-libjuju/commit/93cd1180db26f5776f8500fc5948daac2a32ea5b

I'll fix it in a better way.
