### ISSUE TITLE
De-selecting a node has no effect in c.getSelectedPositions()

### ISSUE THREAD

**Issue by Armagedoom** [leo-editor/leo-editor#37]
This can be tested with the following:

put this code in a node body:
g.es(c.p)
g.es(c.getSelectedPositions)

Now select another node, hold control, click the node with the code, click on it again.
Now press control+b

It will show the current node as a result of c.p, but the current node wont be either selected in the tree pane or in c.getSelectedPositions

The solution is to make Leo select the last item in c.getSelectedPositions when the user de-selects the current c.p node.

I know multiple-positions support is not intended yet,but I rather keep reporting those in case one day they become helpful.

**Comment by edreamleo** [comment]
I am going to close this item and mark this Won'tDo.  This label will make this and similar issues easy to find should we ever want to revisit this.
