### ISSUE TITLE
Replace Leo's body widget with pyzo's text widget

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#370]
This is a sub-part of #361. The idea is to replace Leo's body text with pyzo's actual text widget, suitably modified for Leo.  This will give Leo pyzo's autocompletion and debugging capabilities.  It might also help integrate Leo with #366, Jupyter cells in Leo. This is a large project, but the recent success integrating pyzo's syntax coloring into Leo encourages me.

**Comment by edreamleo** [comment]
**Imports**

Importing *any* pyzo file starts pyzo's server.  The only workaround that doesn't involve changing pyzo is to copy virtually all of pyzo's source files into leo/external/pyzo.

The drawback is that might want to update these files when pyzo changes, updating the files each time. Let's call this the **updated problem**. Otoh, this keeps Leo's own code stable. Happily, I can proceed with a prototype without worrying about the "update problem."

**Comment by tbnorth** [comment]
On Mon, 16 Jan 2017 03:01:55 -0800
"Edward K. Ream" <notifications@github.com> wrote:

> This is a sub-part of #361. The idea is to replace Leo's body text
> with pyzo's actual text widget, suitably modified for Leo.  This will
> give Leo pyzo's autocompletion and debugging capabilities.  It might
> also help integrate Leo with #366, Jupyter cells in Leo. This is a
> large project, but the recent success integrating pyzo's syntax
> coloring into Leo encourages me.

Sounds interesting.  I'd add - don't try integrating this with the
current body frame widget and add editor machinery, make it a new,
*non-singleton* body editing widget, that's agnostic about its layout
parent / container.

**Comment by edreamleo** [comment]
@tbnorth I doubt that Leo's editor widget itself must be a singleton.  The problem is that there must be only one c.p at a time. As a result, the body editor code must do a very complex switcheroo.

Happily, this switcheroo can be done regardless of the actual class of the body pane.  Or so I hope.

**Comment by edreamleo** [comment]
The present pyzo code uses the "is-a" pattern for classes rather than a "has-a" pattern.  That is, the actual text widget is a subclass of about a dozen parent classes.

In contrast, Leo uses the "has-a" pattern exclusively.  Leo's various classes instantiate helper classes.  This style of class construction posed no problems when prototyping and solving the great colorizing performance bug. I expect relatively minimal problems using pyzo's auto-completer code.  We shall see.

**Comment by tbnorth** [comment]
On Fri, 20 Jan 2017 11:29:53 -0800
"Edward K. Ream" <notifications@github.com> wrote:

> @tbnorth I doubt that Leo's editor widget itself must be a
> singleton.  The problem is that there must be only one c.p at a time.
> As a result, the body editor code must do a very complex switcheroo.
> 
> Happily, this switcheroo can be done regardless of the actual class
> of the body pane.  Or so I hope.

stickynotes plugin is pretty close to the goal of multiple body
editors, but they're just plain QTextEditors, and they don't track the
tree selection.  I think tracking or not tracking the tree selection
should be able to be toggled per editor.  ViewRendered attempted to
support that in one of its incarnations.

**Comment by edreamleo** [comment]
On Fri, Jan 20, 2017 at 9:58 PM, Terry Brown <notifications@github.com>
wrote:

> On Fri, 20 Jan 2017 11:29:53 -0800
> "Edward K. Ream" <notifications@github.com> wrote:
>
> > @tbnorth I doubt that Leo's editor widget itself must be a
> > singleton. The problem is that there must be only one c.p at a time.
> > As a result, the body editor code must do a very complex switcheroo.
> >
> > Happily, this switcheroo can be done regardless of the actual class
> > of the body pane. Or so I hope.
>
> stickynotes plugin is pretty close to the goal of multiple body
> editors, but they're just plain QTextEditors, and they don't track the
> tree selection. I think tracking or not tracking the tree selection
> should be able to be toggled per editor. ViewRendered attempted to
> support that in one of its incarnations.


​Tracking is indeed the big option.​

​ ​
Both the VR code and the multiple-body-editors code are way too complex.

​I've given this some thought.  The present code (and design) hard-wires
the connection between an outline pane and its body panes.  To loosen this
connection, we would have to change how c.selectPosition works.  And
probably also how c.p works.

This would be a huge change to Leo. Switching nodes and/or focus is
inherently complex. And we can't change *to* c.p or c.selectPosition. Such
a project would be highly experimental.

In any case, supporting pyzo operations in Leo's QTextBrowser is a separate
issue.

Edward

**Comment by tbnorth** [comment]
On Sat, 21 Jan 2017 03:11:43 -0800
"Edward K. Ream" <notifications@github.com> wrote:

> In any case, supporting pyzo operations in Leo's QTextBrowser is a
> separate issue.

My thought was that if the pyzo text editing widget was being added to
Leo, it could be treated completely separately as a new body editing
widget, addressing the multiple editor issues etc.  But I don't know if
the pyzo widget's the portable / modular.

Hmmm, maybe I'll have a go at writing viewrendered 4 :-} with the idea
that that might be a place a body editor could live.

**Comment by edreamleo** [comment]
@tbnorth 
> Hmmm, maybe I'll have a go at writing viewrendered 4 :-} with the idea that that might be a place a body editor could live.

Unless I misunderstand you, I don't think this is the correct approach. Writing a VR4 widget is unlikely to improve things.  All by itself, that is.

There is nothing "wrong" with Leo's existing body pane.  In essence, it's just a QTextBrowser.  The reason that switching body panes is difficult has nothing to do with the body pane itself.  The problem is that very complex context switching must be done *outside* the body pane.

As I was thinking about this today, I saw that most people probably do not need the full capabilities of having several "live" body panes.  I hardly ever use multiple body panes, but when I do, it is only to compare two versions of code.  So having a "frozen" body would suffice.  The work flow would be to create a *copy* of a node, that could not change.  Only one body would be "live", that is, connected to the outline.

Not sure that this restriction would actually simplify the code much, but perhaps it's worth exploring.

**Comment by tbnorth** [comment]
On Sat, 21 Jan 2017 15:28:47 -0800
"Edward K. Ream" <notifications@github.com> wrote:

> @tbnorth 
> > Hmmm, maybe I'll have a go at writing viewrendered 4 :-} with the
> > idea that that might be a place a body editor could live.  
> 
> Unless I misunderstand you, I don't think this is the correct
> approach. Writing a VR4 widget is unlikely to improve things.  All by
> itself, that is.

Right, calling what I have in mind VR 4 was inaccurate, although it
attempts to handle focus and tracking in ways various VR iterations
have also attempted.

> There is nothing "wrong" with Leo's existing body pane.  In essence,
> it's just a QTextBrowser.  The reason that switching body panes is
> difficult has nothing to do with the body pane itself.  The problem
> is that very complex context switching must be done *outside* the
> body pane.

Right again :-)  What I'm working on, and progress so far is good, is a
widget that handles the switching, with options to track / not track
the node selected in the tree (c.p) etc.  It delegates the editing (or
viewing, hence the VR 4 comment) of nodes to other widgets.

My plan is to get it working with a vanilla QTextEdit, and a few view
widgets (HTML, markdown, ...).  Then when I can demonstrate it, maybe
you'll be convinced enough of its utility to help get Leo's text
editor widget (whatever that is by then) working in this framework.

> As I was thinking about this today, I saw that most people probably
> do not need the full capabilities of having several "live" body
> panes.  I hardly ever use multiple body panes, but when I do, it is
> only to compare two versions of code.  So having a "frozen" body

Right-ish, although I think being able to edit a top level notes node
on screen while moving around lower level code nodes is desirable.

Currently the multiple body editors code is the only way to get syntax
highlighting and Leo key processing in two windows.  That's quite
limiting, and part of what I'm trying to address.

I'll see where I get to and it can be judged on its own merits.

I would just say that as currently envisioned, it could potentially
make a major contribution to the support of Jupyter cells, so I'd
suggest not forging ahead on that until you've seen this.  Looking at
your timetable in another thread, I'd hope to be able to demo this
before you get to that anyway, so probably no issue unless you start on
that sooner.

> would suffice.  The work flow would be to create a *copy* of a node,
> that could not change.  Only one body would be "live", that is,
> connected to the outline.
> 
> Not sure that this restriction would actually simplify the code much,
> but perhaps it's worth exploring.

I see what you're getting at, but I'm going to go for "as many editors
as you want" initially ;-)

Cheers -Terry

**Comment by edreamleo** [comment]
​​
On Sat, Jan 21, 2017 at 6:06 PM, Terry Brown <notifications@github.com>
wrote:


> What I'm working on, and
> ​progress so far is good, is a
> widget that handles the switching, with options to track / not track
> the node selected in the tree (c.p) etc. It delegates the editing (or
> viewing, hence the VR 4 comment) of nodes to other widgets.
>
> My plan is to get it working with a vanilla QTextEdit, and a few view
> widgets (HTML, markdown, ...). Then when I can demonstrate it, maybe
> you'll be convinced enough of its utility to help get Leo's text
> editor widget (whatever that is by then) working in this framework.
>

​Oh good :-)  That would be super.​


>
> > As I was thinking about this today, I saw that most people probably
> > do not need the full capabilities of having several "live" body
> > panes. I hardly ever use multiple body panes, but when I do, it is
> > only to compare two versions of code. So having a "frozen" body
>
> Right-ish, although I think being able to edit a top level notes node
> on screen while moving around lower level code nodes is desirable.
>

​If your idea works out, we can happily ignore my idea.  It's a special
case that would likely create more complications behind the scenes, not
less.

Currently the multiple body editors code is the only way to get syntax
> highlighting and Leo key processing in two windows. That's quite
> limiting, and part of what I'm trying to address.
>

​I typically just open another copy of Leo and paste one of the nodes to be
compared into the other Leo.​ I do this rarely, so the inconvenience is
slight.


> I'll see where I get to and it can be judged on its own merits.
>
> I would just say that as currently envisioned, it could potentially
> make a major contribution to the support of Jupyter cells,


​Excellent
​


> so I'd
> ​ ​
> suggest not forging ahead on that until you've seen this.


​I have no plans to work on multiple body panes.

Edward

**Comment by tbnorth** [comment]
On Sat, 21 Jan 2017 23:33:30 -0800
"Edward K. Ream" <notifications@github.com> wrote:

> > I would just say that as currently envisioned, it could potentially
> > make a major contribution to the support of Jupyter cells,  
> 
> ​Excellent
> ​
> > so I'd
> > suggest not forging ahead on that until you've seen this.  
> 
> ​I have no plans to work on multiple body panes.

I meant wait to see if my work bears fruit before tackling Jupyter
cells, as the editor/viewer split in the new widget might be a natural
way of representing them.  I think Jupyter cells are far enough down
your timeline I should have something to show before you get to them.

Cheers -Terry

**Comment by edreamleo** [comment]
On Sun, Jan 22, 2017 at 8:33 AM, Terry Brown <notifications@github.com>
wrote:

> ​I have no plans to work on multiple body panes.
>
> I meant wait to see if my work bears fruit before tackling Jupyter
> cells, as the editor/viewer split in the new widget might be a natural
> way of representing them. I think Jupyter cells are far enough down
> your timeline I should have something to show before you get to them.


​Yes.  It will be a month, likely more, before I am ready to tackle Jupyter
cells.  I'll await your work with keen interest.

EKR

**Comment by edreamleo** [comment]
I am going to close this, per [recent discussions](https://groups.google.com/d/msg/leo-editor/OBaaood26dw/hMKqSNupCQAJ).  Terry's EP work, combined with EKR's VR work will be plenty good enough.
