### ISSUE TITLE
At-file generation errors when writing files.

### ISSUE THREAD

**Issue by boltex** [leo-editor/leo-editor#3703]
PR #3704 should fix this issue.

I've spotted some (big) @file generation errors. 

I've narrowed down exactly the commits where this started, four days ago. between:
**6c6068f: Mixed sentinels test pass. More work is needed**
and
**744b775: Add pattern trace**

To reproduce clone the leojs repo and switch to the devel branch. Then select the "Leo" node and press CTRL+SHIFT+W to force writing the at-files contained in that node. (_Check the diffs :  gotoCommands.ts is corrupted._ ) 

Here's a screenshot of me doing the reproducible example stated above:
![image](https://github.com/leo-editor/leo-editor/assets/847716/77aadd85-3467-49ac-b929-cbfe6b5f0afe)

**Comment by edreamleo** [comment]
@boltex Thanks for this report.  Does PR #3704 fix this issue?

**Comment by boltex** [comment]
@edreamleo yes, #3704 this seems to have brought back the external file generation integrity. Thanks for that!

**Comment by edreamleo** [comment]
@boltex Thanks for your review and testing! You have saved me considerable embarrassment.

**Comment by edreamleo** [comment]
Closed via PR #3704.
