### ISSUE TITLE
Headline focus fails using Ctrl-click on a gnx based UNL

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#3706]
This report is for Ctrl-click on a node in same open leo file.
Ensure @string unl-status-kind = gnx

Ctrl-click on a node where body text is a gnx based UNL target (in the same file).
The target node body text displays but the outline pane headline focus remains on the node just Ctrl-clicked, **not** the UNL target node.
A shadowed box remains on the Ctrl-clicked node.

**Comment by tbpassin** [comment]
Using my monkey-patch, the target node gets selected. I just checked.  The same is true for the version in the PR I submitted.

Let's hold off on this one until the PR gets merged, shall we?

**Comment by LewisNeal** [comment]
The monkey-patch code and PR work.
I realise now the shadowed box remains on the Ctrl-clicked node only if I clicked on the node headline, not the body text link.
