### ISSUE TITLE
breakpoint() not work very well in Mac

### ISSUE THREAD

**Issue by HaveF** [leo-editor/leo-editor#3707]
On MacOS Python `breakpoint` function constantly outputs:

[`QCoreApplication::exec: The event loop is already running`](https://github.com/leo-editor/leo-editor/assets/54462/056f2654-15ac-4e4e-b330-b2fbdf04d8fa)

I have tried the newest code([0f9560b0](https://github.com/leo-editor/leo-editor/tree/0f9560b032bf307b39fc56f9478a93f1b3ac3e4a)) in devel branch, but still without luck.

```
Leo Log Window
Leo 6.7.6-devel
Python 3.12.1, PyQt version 5.15.11
darwin
```

**Comment by HaveF** [comment]
I can use `g.pdb()` to start debugger without the constantly output warning

**Comment by edreamleo** [comment]
@HaveF Thanks for the update. Leo's startup code patches Qt so that breakpoint works. Perhaps Leo doesn't call this code for MacOS.

**Comment by HaveF** [comment]
breakpoint works even constantly output `QCoreApplication::exec: The event loop is already running`, I can still type `c` to make it continue

**Comment by edreamleo** [comment]
@HaveF I am glad you found a workaround.

I am going to close this issue. This seems to be an os-specific glitch.

I have no idea why `breakpoint` works for me on Windows but not for you on MacOS.
