### ISSUE TITLE
execute-script fails when a node contains multiple @language directives

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#371]
For example: `execute-script` reports a syntax error in the following:

```python
@language rest
This is a test
@language python
print('hi')
```
This issue comes to mind because emacs babel can extract code sections from a node.  Leo should be able to do the same.

**Comment by LewisNeal** [comment]
The intention being that a @language directive will be followed until over-ridden by the next @language directive?

**Comment by edreamleo** [comment]
@LewisNeal `@language rest` will either be ignored or turned into a comment.  I hadn't thought about multiple "executable" languages, like C and Python.  No real reason to support that.

**Comment by LewisNeal** [comment]
@edreamleo Yes, a single "executable" language but switching back and forth between the "executable" language and the chosen language for comments and other text.

**Comment by LewisNeal** [comment]
This is already possible, as long as the commenting is compatible with the language. I can successfully Ctrl-B the example below. I used python ''' triple quotes.

@language rest

'''
This is a test see https://github.com/leo-editor/leo-editor/issues/371 

Heading A 
----------
- [ ] item

'''

@language python
print('hi')

@language md

'''

Heading B 
----------

- [x] item
- [x] item

'''

@language python
print('hi again')

It can certainly be improved though, as the python quote marks appear in the rendered pane.

**Comment by tbnorth** [comment]
Somewhat tangential, but I use

`@language html javascript`

or

`@language markdown python`

and a button to cycle the order of items of the @language line.  This works currently, as a way of switching syntax highlighting on files that contain mixed languages.

**Comment by edreamleo** [comment]
​​
On Fri, Jan 20, 2017 at 8:39 PM, LewisNeal <notifications@github.com> wrote:

> This is already possible, as long as the commenting is compatible with the
> language.
>
​Not good enough.  To support literate programming as understood in the
org-mode world, the comments should be properly formatted as, say, markdown.

Another workaround would be to use the @doc...@c syntax.

Instead of these workarounds, Leo's script-building machinery should simply
ignore @markdown or @rest sections.

The question of mixed *executable* languages (like intermixed C and Python
in a single node) is more difficult.  The "clever" thing to do is to honor
the first executable language, but that could cause confusion.  Better,
imo, is to reject mixed execution.

That will work, because Leo already can execute only selected text.  So if
a node contains both C and Python code, the user should have to indicate
explicitly which is desired by selecting code.  In practice, this will
seldom be needed.

**Comment by edreamleo** [comment]
@tbnorth 
> I use `@language html javascript`...and a button to cycle the order of items of the @language line. 

Clever. Please post the code on leo-editor.

**Comment by edreamleo** [comment]
Fixed at c31c1b2 by adding `g.extractExecutableString`.

This function simply removes all lines that are in the range of `@language rest/md/markdown`. In addition, it truncates the script, with a warning, if it sees two "executable" `@language` directives.

**Important**: Even if a node contains multiple executable languages, say C and Python, the user can select a range of lines to execute.  All will be well, provided the selected text contains at most one executable language.
