### ISSUE TITLE
Remove an unnecessary class in leoCache.py

### ISSUE THREAD

**Issue by boltex** [leo-editor/leo-editor#3718]
See PR #3721.

<details><summary>hypothesis & explanation</summary>
<br>

**Hypothesis**

One of the two databases in .leo/db/ is unused: The one in .leo/db/global_data. (which is used in Leo as **g.app.commander_cacher**)

_(Confusing name btw because the one with the actual 'global' data is in .leo/db/g_app_db, which is used in Leo as **g.app.db**)_

that **g.app.commander_cacher** seems to be used to keep a link to a db that is common to all opened commanders in leo.

But, It's used only directly to commit+save when closing a document, saving a document or quitting leo. Not to get/set data per say. So do those commit+save serve a purpose if nothing is ever set into it? 

I dont think so because that db is not the one that contains any relevant data. Only the global db known as  **g.app.db** contains data.

**Explanation**

The commanders each keep a link to a db to store their specific (non global) data. This is set by the line :

`c.db = g.app.commander_cacher.get_wrapper(c)`

which happens in the initObjects method of the Commands constructor.

Look at the get_wrapper method. It sets its own db to the main g.app.db, which is the global db. therefore the g.app.commander_cacher serves no purpose.

Félix

</details>

**Comment by boltex** [comment]
To add to the previous post: 

Once that .leo/db/global_data _(g.app.commander_cacher)_ db is removed, the commit+save that was done on it when closing a document, saving a document or quitting leo should be done on g.app.db instead I guess ! :)

Félix

**Comment by edreamleo** [comment]
Closed via PR #3721.
