### ISSUE TITLE
show-clone-ancestors and show-clone-parents are buggy

### ISSUE THREAD

**Issue by boltex** [leo-editor/leo-editor#3723]
See PR #3726.

Unlike show-clone-parents which seems to work fine, show-clone-ancestors unl links do not seem to work properly. (Or I don't understand what they were supposed to be pointing to ) 

**EKR**

I agree: `show-clone-ancestors` does not seem to do what its docstrings says it does.

Both `show-clone-ancestors` and `show-clone-parents` look confusing or buggy. Links can look the same but go to different nodes. The PR will fix this problem for both commands.

**Comment by edreamleo** [comment]
Closed via PR #3726.
