### ISSUE TITLE
Java importer bugs with 'interface', (Java importer have regex without capture group, is it normal?)

### ISSUE THREAD

**Issue by boltex** [leo-editor/leo-editor#3727]
See PR #3728.

The regex to capture blocks in java seem to have one for **interfaces** (the third one):
```java
    block_patterns = (
        ('class', re.compile(r'.*?\bclass\s+(\w+)')),
        ('func', re.compile(r'.*?\b(\w+)\s*\(.*?\)\s*{')),
        ('interface', re.compile(r'\w*\binterface\w*{')),
```

But, it looks for a word before 'interface', and no separation without spaces between that word and 'interface'.
Stepping in the code while debugging Leo, the sample below does not trigger a match. 

Neither does begenning the interface with:
abc interface Animal {
myInterface Animal

so the following file has the interface inserted at the beginning of the class Pig when doing and @auto node for this sample file: 

```java
interface Animal {
  public void animalSound(); // interface method (does not have a body)
  public void sleep(); // interface method (does not have a body)
}

class Pig implements Animal {
  public void animalSound() {
    // The body of animalSound() is provided here
    System.out.println("The pig says: wee wee");
  }
  public void sleep() {
    // The body of sleep() is provided here
    System.out.println("Zzz");
  }
}

class Main {
  public static void main(String[] args) {
    Pig myPig = new Pig();  // Create a Pig object
    myPig.animalSound();
    myPig.sleep();
  }
}
```

Also, when modifying the file on disk externally, when Leo detects the file change and we choose 'yes' to have it refresh the @auto file from disk, this message is printed in the log and the body does not refresh:
```
setCurrentPosition Invalid position <pos 2176939535872 childIndex: 0 lvl: 1 key: 2176872479232:1.2176872480288:0 class Pig> Commander 2176872740240: 'C:/prog/testmarkdown/testmd1.leo'     
Callers: [
     0: '<module>'
     1: 'main'
     2: 'run_file'
     3: 'run_path'
     4: '_run_module_code'    
     5: '_run_code'
     6: '<module>'
     7: 'run'
     8: 'load'
     9: 'runMainLoop'
    10: 'at_idle_time'        
    11: 'call_handler'        
    12: 'on_idle'
    13: 'on_idle'
    14: 'idle_check_commander'
    15: 'redraw'
    16: 'select'
    17: 'selectHelper'
    18: 'select_new_node'
    19: 'set_body_text_after_select'
]

setCurrentPosition Invalid position <pos 2176939535872 childIndex: 0 lvl: 1 key: 2176872479232:1.2176872480288:0 class Pig> Commander 2176872740240: 'C:/prog/testmarkdown/testmd1.leo'     
Callers: [
     0: '_run_module_as_main'
     1: '_run_code'
     2: '<module>'
     3: 'main'
     4: 'run_file'
     5: 'run_path'
     6: '_run_module_code'
     7: '_run_code'
     8: '<module>'
     9: 'run'
    10: 'load'
    11: 'runMainLoop'
    12: 'at_idle_time'
    13: 'call_handler'
    14: 'on_idle'
    15: 'on_idle'
    16: 'idle_check_commander'
    17: 'redraw'
    18: 'full_redraw'
]

setCurrentPosition Invalid position <pos 2176939535872 childIndex: 0 lvl: 1 key: 2176872479232:1.2176872480288:0 class Pig> Commander 2176872740240: 'C:/prog/testmarkdown/testmd1.leo'     
Callers: [
     0: 'main'
     1: 'run_file'
     2: 'run_path'
     3: '_run_module_code'
     4: '_run_code'
     5: '<module>'
     6: 'run'
     7: 'load'
     8: 'runMainLoop'
     9: 'at_idle_time'
    10: 'call_handler'
    11: 'on_idle'
    12: 'on_idle'
    13: 'idle_check_commander'
    14: 'redraw'
    15: 'selectPosition'
    16: 'select'
    17: 'selectHelper'
    18: 'select_new_node'
    19: 'set_body_text_after_select'
]

setCurrentPosition Invalid position <pos 2176939535872 childIndex: 0 lvl: 1 key: 2176872479232:1.2176872480288:0 class Pig> Commander 2176872740240: 'C:/prog/testmarkdown/testmd1.leo'     
Callers: [
     0: '_run_module_as_main'
     1: '_run_code'
     2: '<module>'
     3: 'main'
     4: 'run_file'
     5: 'run_path'
     6: '_run_module_code'
     7: '_run_code'
     8: '<module>'
     9: 'run'
    10: 'load'
    11: 'runMainLoop'
    12: 'at_idle_time'
    13: 'call_handler'
    14: 'on_idle'
    15: 'on_idle'
    16: 'idle_check_commander'
    17: 'redraw'
    18: 'selectPosition'
]
```

Lastly, Java and ~ini~ importers have regex without capture groups, is it normal?

**Comment by boltex** [comment]
Note about regex without capture groups: the **rust** importer also has a regex without capture groups, but it handles it. (it even has a comment adressing the fact that it wont yield an m.group(1).)
```python
    ('use', re.compile(r'\s*use.*?\{')),  # No m.group(1).
```
On the other hand the Ini and java importers use the base_importer's default find_blocks method that needs a` m.group(1)` when it matches.

**Comment by boltex** [comment]
This is surely related to this LeoJS bug that @tbpassin reported : https://github.com/boltex/leojs/issues/94

Fixing either of those issues will automatically show how to fix the other probably! 😄

**Comment by boltex** [comment]
Would something like this be better? (I just tried it and it fixes the importing/ writing bug ! )
```python
('interface', re.compile(r'\s*interface\s+(\w+)\s*{')),
```

But the error about selecting an invalid node remains when refreshing from disk.

**Comment by boltex** [comment]
This one with a non-capturing group at the start before the 'interface' would allow for the keywords 'public' or 'private' to be present before the 'interface' keyword:
```python
r'\s*(?:\w+\s+)?interface\s+(\w+)\s*{'
```
**I tested it, Seems to work fine!** 

Lastly, I just discovered that the writing process of java writer seems to have the opposite bug of the .md writter ! :)  it 'eats' new lines between the parts:

Original being read:
![image](https://github.com/leo-editor/leo-editor/assets/847716/498579b2-8457-4225-9d66-8eb69c161072)
and after writing the newlines are missing:
![image](https://github.com/leo-editor/leo-editor/assets/847716/81ae8fa8-6214-4e23-999d-9f5f738305c5)

**Comment by boltex** [comment]
Nevermind the mention of the ini importer. I had a mistranlation in leojs for the ini importer which I thought was related to the java importer/writer.

**Comment by edreamleo** [comment]
@boltex The PR uses a simpler regex.

Note: `BaseImporter.find_blocks` looks only for m.group(1). Another `BaseImporter` method looks for `m.group(0)`.  In short, the PR's regex should work for `@auto`.

**Comment by boltex** [comment]
@edreamleo After playing with it for a while I came to wonder that maybe the missing newlines when writing, are in fact newlines the should have been added in when reading, so that when writing it would be ok! :)

**Comment by tanzilmatjarplay** [comment]
*   [إنشاء حساب جيميل بدون رقم هاتف 2024](https://www.tanzilmatjarplay.com/2023/12/create-gmail-account-whitout-number-phone.html)
*   [انشاء حساب جيميل بدون رقم هاتف](https://www.tanzilmatjarplay.com/2023/12/create-gmail-account-whitout-number-phone.html)
*   [إنشاء حساب جي ميل بدزن رقم الهاتف](https://www.tanzilmatjarplay.com/2023/12/create-gmail-account-whitout-number-phone.html)
*   [انشاء حساب الجيميل بدون رقم جوال](https://www.tanzilmatjarplay.com/2023/12/create-gmail-account-whitout-number-phone.html)
*   [إنشاء حساب جي ميل بدزن رقم الجوال](https://www.tanzilmatjarplay.com/2023/12/create-gmail-account-whitout-number-phone.html)
