### ISSUE TITLE
Spell check Traceback error

### ISSUE THREAD

**Issue by largo84** [leo-editor/leo-editor#3741]
I don't know which recent update broke the spell checker, but I get this Traceback error after clicking on the 'Find' button:

`Traceback (most recent call last):`
`File "D:\Synced\github repos\leo\leo\plugins\qt_frame.py", line 107, in doSpellBtn button()`
`File "D:\Synced\github repos\leo\leo\plugins\qt_frame.py", line 3768, in onFindButton`
`self.handler.find()`
`File "D:\Synced\github repos\leo\leo\commands\spellCommands.py", line 832, in find`
`alts: list[str] = sc.process_word(word)`
`AttributeError: 'DefaultWrapper' object has no attribute 'process_word'`

FWIW, I have a dictionary installed and this has worked well in the past. Here's my system info:

`Leo 6.7.7-devel, devel branch, build 8bd9984c61`
`2023-12-27 22:34:33 -0600`
`Python 3.9.7, PyQt version 5.9.7`
`Windows 10 AMD64 (build 10.0.19045) SP0`

**Comment by tbpassin** [comment]
Hmmm, that isn't happening on mine.  I'm on a branch based on that changeset. I'm using Python 3.12.  I wonder if it's specific to Python 3.9.

**Comment by largo84** [comment]
I get the same error in multiple outlines and nodes. Wonder if anyone other me has seen this error. If not, it makes me wonder what's wrong with my setup and what changed?

**Comment by tbpassin** [comment]
Sorry to mention the obvious, but if you close Leo and restart, do you continue to see the errors?  And if you do, would you be willing to shut down your computer and restart?

I mention this because my computer has an intermittent memory problem that seems to occasionally strike my Python instance.  Sometimes it seems that a restart of Python loads into the same memory location, sometimes not.  OTOH, in my case the problem usually manifests itself by crashing Python.  Worth checking, though.

**Comment by largo84** [comment]
That's funny as that's often the same advice I give my wife when she has trouble with her computer and it works often enough to be worth repeating:-)

However, I tried both and still get the error in multiple outlines and nodes.

**Comment by tbpassin** [comment]
Oh, well, worth trying.  This is making me wonder if there's a problem with the pyenchant spell-checking library.  You could try updating it.  The latest version is 3.2.2.

**Comment by largo84** [comment]
Hmm, looks like this is going to involve more research on my end as I can't locate the proper pyenchant library. I'll close this issue for now as it appears to be localized to my setup.

**Comment by tbpassin** [comment]
At least on Windows, it looks like 3.2.2 should be available:
```
C:\Users\tom>py -3.9 -m pip install --upgrade --user pyenchant==
ERROR: Could not find a version that satisfies the requirement pyenchant== (from versions: 1.1.4, 1.1.5, 1.2.0, 1.3.0, 1.3.1, 1.4.2, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.6.6, 1.6.7, 1.6.8, 1.6.9, 1.6.10, 1.6.11, 2.0.0, 3.0.0a1, 3.0.0a2, 3.0.0rc1, 3.0.0rc2, 3.0.0rc3, 3.0.0rc4, 3.0.0, 3.0.1, 3.1.0, 3.1.1, 3.2.0, 3.2.1, 3.2.2, 3.3.0rc1)
ERROR: No matching distribution found for pyenchant==
```
Note that this is the easiest way to find out the available versions (make sure to scroll right as far as possible to see the highest versions).  `pip install pyenchant==3.1.0` would try to install v3.1.0, but an empty version (nothing after the "==") doesn't match any available one and you get the whole list.

So 3.2.2 should get installed for Python 3.9.

**Comment by largo84** [comment]
Well, I installed PyEnchant v3.2.2 via Anaconda, which is also how I installed Python 3.9. I don't know what to do next as Leo doesn't seem to know it's there. Do I also need to explicitly tell Leo where the dictionaries are?

**Comment by tbpassin** [comment]
> Do I also need to explicitly tell Leo where the dictionaries are?

Not that I remember.  You probably need to restart Leo after installing pyenchant (I'm guessing that you did).

I'd open a Python session in a console, then try to import pyenchant, like this:
```
C:\Users\tom>py
Python 3.12.0 (tags/v3.12.0:0fb18b0, Oct  2 2023, 13:03:39) [MSC v.1935 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import enchant
>>>
```
With Ananconda, you probably use a different command to launch Python than "py".  If you get an import error, then Leo won't be able to import it either.  Just make sure you launch the same version of Python as is used to run Leo.

If there is an import error, then that's what needs to be fixed somehow.  If there is no import error but Leo's spell checker still isn't working for you, then that would be mysterious and we'd have to think of some way to troubleshoot.

When you wrote that Leo "doesn't seem to know it's there", what happened when you tried to spell check a node?

**Comment by largo84** [comment]
`(Leo-Main) PS D:\Synced\github repos\leo> python.exe`
`Python 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32`
`Type "help", "copyright", "credits" or "license" for more information.`
`>>> import enchant`
`Traceback (most recent call last):`
`  File "<stdin>", line 1, in <module>`
`ModuleNotFoundError: No module named 'enchant'`
`>>>`

That's odd because the Anaconda installation of PyEnchant was successful.

I get the same Traceback error message as before.

**Comment by tbpassin** [comment]
Well, that explains why Leo's spell checker isn't working.  `import enchant` is how Leo does it. But it doesn't explain why enchant won't import. 

I don't know how Anaconda packages and imports anything, so I probably won't be of much help.  In my (non-Anaconda) experience, installing into the wrong version of Python is the most common cause of this kind of problem.  This can happen if there is more than one version of Python on a machine.

Here's a post that may help -

https://stackoverflow.com/questions/39811929/package-installed-by-conda-python-cannot-find-it
