### ISSUE TITLE
wikiview plugin. 'QTextCursor' object has no attribute 'PreviousCharacter'

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#3749]
Traceback using wikiview plugin:

Leo 6.7.7-devel, devel branch, build ed5cfd3146
2024-01-02 04:48:27 -0600
Python 3.12.1, PyQt version 6.6.1
Windows 10 AMD64 (build 10.0.19045) SP0
[snip]
onTextChanged *** LOCKOUT doPlugins,doHandlersForTag,callTagHandler,hide
onTextChanged *** LOCKOUT doPlugins,doHandlersForTag,callTagHandler,hide

Uncaught exception in Leo...
Traceback (most recent call last):
  File "N:\git\leo-editor\leo\plugins\wikiview.py", line 179, in unhide
    cursor.movePosition(cursor.PreviousCharacter) and
                        ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'QTextCursor' object has no attribute 'PreviousCharacter'

**Comment by LewisNeal** [comment]
To reproduce create 2 nodes both with body text https://leo-editor.github.io/leo-editor/
Search for https://leo-editor.github.io/leo-editor/ works and displays correctly.
Message _onTextChanged *** LOCKOUT doPlugins,doHandlersForTag,callTagHandler,hide_ is shown in console.

Now use Find panel to search for text: leo-editor
Focus moves to node and the text displays correctly.
Then press F3 (Find Next), focus moves to next node but the font is extremely small and unreadable, as are the line numbers. 

AttributeError and font size problem is caused by searching for text within URLs.

**Comment by tbpassin** [comment]
_PreviousCharacter_ is now an enumeration that affects how move operations take place.  I don't know when this change happened but it must have been after this plugin was written.

**Comment by edreamleo** [comment]
Fixed via PR #3802.
