### ISSUE TITLE
M1 macOS 14.3 re-install Leo under miniconda error

### ISSUE THREAD

**Issue by ZoomQuiet** [leo-editor/leo-editor#3769]
base: [Installing Leo — Leo 6.7.1 documentation](https://leoeditor.com/installing.html#installing-leo-on-macos-10-7-lion-and-later)

- installed miniconda
- create leo3912 for install leo
- usage miniconda installed PyQt5-sip
- active leo3912 try : pip install leo
- block Preparing metadata (pyproject.toml)

![zshot 2024-01-24 10 38 08](https://github.com/leo-editor/leo-editor/assets/22494/5dc5338f-e9d5-47c0-8e44-2f954a8be1cb)

PS:
in fact already installed all need under homebrew:
```
brew install qt sip pyqt
==> Downloading https://mirrors.ustc.edu.cn/homebrew-bottles/api/formula.jws.json
-=O#-   #      #       #
==> Downloading https://mirrors.ustc.edu.cn/homebrew-bottles/api/cask.jws.json
-=O#-   #      #       #
Warning: Treating sip as a formula. For the cask, use homebrew/cask/sip
Warning: qt 6.6.1 is already installed and up-to-date.
To reinstall 6.6.1, run:
  brew reinstall qt
Warning: sip 6.8.1 is already installed and up-to-date.
To reinstall 6.8.1, run:
  brew reinstall sip
Warning: pyqt 6.6.1 is already installed and up-to-date.
To reinstall 6.6.1, run:
  brew reinstall pyqt
```

so what error in PyQt5?
how to clean and run leo again?

or, these another tools can write .leo files?

**Comment by edreamleo** [comment]
I am going to close this issue. Please reopen this issue if problems installing Leo 6.7.8 remain (when 6.7.8 is released officially).

- Installing Python 3.12 is straightforward on MacOS. Just download and run [this file](https://www.python.org/ftp/python/3.12.2/python-3.12.2-macos11.pkg). This installs Python 3.12 (and pip) in the Applications folder.

- Once pip is installed, `python -m pip install pyqt6` will install pyqt6.

As of Leo 6.7.8, Leo's PyPi and GitHub installers will work properly assuming that Python 3.9+ is available.
