### ISSUE TITLE
Back Arrow Does Not Always Return To The Last Position

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#3800]
See PR #3806. This PR changes the logic of *all* the methods of the `NodeHistory` class.

In the forward/back arrows, clicking the back arrow does not always return to the last position.  This seems to be a change to me, probably a fairly recent change or I would have noticed.

To verify:
Use an open outline, such as the Workbook, that has a good number of nodes.
1. Navigate to the last node (this is for convenience; the behavior does not depend on it);
2. Pick some node higher up the screen, and in the Nav tab, type part or all of its headline.  This will navigate to the chosen node;
3. Use the back arrow to move back to the starting node.
4. Pick some other node and repeat steps 2 and 3. Notice that the back arrow did not return you to the starting node.  Instead, it first visited the 2nd node.

You can keep navigating (using the Nav tab) to other nodes, and the back arrow will navigate to all of them in turn before getting back to the previous node.  

Expected behavior:  The back arrow will actually take you back to the previous position.

The current behavior is very inconvenient.

**Comment by edreamleo** [comment]
@tbpassin Thanks for this report.

Somehow I have been putting up with this annoying hangnail. Thanks for reminding me of it.

**Comment by tbpassin** [comment]
I had been suffering with it without really noticing.  Then one day I was doing a lot of hops back to the starting point but they didn't go right there. It became really annoying.
