### ISSUE TITLE
decorators sometimes duplicated in @clean files

### ISSUE THREAD

**Issue by JohnLunzer** [leo-editor/leo-editor#382]
I'm not sure if anyone has noticed this but I've noticed it twice now in two separate files. I think it happened after I updated yesterday. Wondering if it has something to do with other issues related to the new python importer.

Here is my build version:
Leo 5.4, build 20170124041427, Tue Jan 24 04:14:27 CST 2017
Git repo info: branch = master, commit = fe645854ad09

I don't have a way to test or replicate this yet, just wanted to throw it out there. I'd say if you don't hear anything on this in say... three weeks, then you can close this. It can always be reopened after that.

**Comment by edreamleo** [comment]
> Wondering if it has something to do with other issues related to the new python importer.

@JohnLunzer Thanks for the report.  The screw-up with recognizing Leo's directives could indeed mess up the python importer.  Let's leave this issue open for now.  Please report any problems after upgrading to the recent code. Rev f31e6973f or after should do.

**Comment by edreamleo** [comment]
@JohnLunzer What is the status of this issue?

**Comment by JohnLunzer** [comment]
I believe the fixes you referenced worked. After updating Leo, restarting, and reloading the files in question the decorators did not duplicate again. Should be safe to close this.
