### ISSUE TITLE
dragdropgoodies.py plugin seems to have wrong docstring

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#3820]
This plugin seems to have somehow acquired the wrong docstring.  Ironically this is most likely to have happened by an accidental drag.

The docstring reads in part:
```
"""Adds "Back" and "Forward" buttons (Qt only).

Creates "back" and "forward" buttons on button bar. These navigate
the node history.
```
The code seems very experimental and in development and does not do anything like what the docstring says.

**Comment by edreamleo** [comment]
Fixed at rev 71b2c1b.
