### ISSUE TITLE
New Mac Install Directions Refer To Python 2.7

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#3833]
This is in the link on Github for installing on a Mac:

https://leo-editor.github.io/leo-editor/installing.html

The part I noticed said:
```
"Add the following lines to your ~/.bash_profile (or ~/.profile on Leopard). This is the default for LION:

export PATH=/usr/local/bin:$PATH
# This is for SIP (and PyQt) as suggested by Homebrew
export PYTHONPATH=/usr/local/lib/python2.7/site-packages:$PYTHONPATH"
```
I realize it's just an example but Leo requires 3.9+ these days. Leaving it as "2.7" will tend to be confusing to new users who are not too Python-savvy.

**Comment by edreamleo** [comment]
Closed via rev d04e495.
