### ISSUE TITLE
open files with very long path

### ISSUE THREAD

**Issue by cerimis** [leo-editor/leo-editor#384]
Files with very long paths cannot be opend by  g.openUrl(p) under windows because of path length limitations.
This issue can be overcome by adding the string ur"\\\\\\\\?\\\\" in front of the path.
See: http://stackoverflow.com/questions/3555527/python-win32-filename-length-workaround

**Comment by edreamleo** [comment]
I am not going to fix this supposed problem for the following reasons.

1.  Apparently the proposed fix doesn't work, as shown by this test:

```python
import os
# s is the result of copy address as text from the innermost directory
s = 'C:\Test\long-path-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\long-path-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\long-path-ccccccccccccccccccccccccccccccccccccccccccccccc'
assert g.os_path_exists(s)

# Now add the file name.
s += r'\ddddddddddddddd.txt'
print(len(s))
print(g.os_path_exists(s))
print(os.path.exists(s))
s2 = g.u(r"\\\\?\\") + s
print(g.os_path_exists(s2))
print(os.path.exists(s2))
```

The output was:

```
267
False
False
False
False
````

2. It is possible to open the file from mozilla.  Doing so shows the following url:

file:///C:/Test/LONG-P~1/LONG-P~1/LONG-P~1/DDDDDD~1.TXT

I suggest copying and pasting this url into your browser.
