### ISSUE TITLE
Use g.bytesToStr and g.strToBytes where possible

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#3849]
PR #3846 adds these functions. Now it's time to use them.

#3845 (Improve mypy annotations) *might* also add these functions.

**Comment by LewisNeal** [comment]
I ran g.bytesToStr and received this error:

_exception executing script
Traceback (most recent call last):
  File "N:\git\leo-editor\leo\core\leoCommands.py", line 1212, in executeScript
c.executeScriptHelper(args, define_g, define_name, namespace, script)
  File "N:\git\leo-editor\leo\core\leoCommands.py", line 1257, in executeScriptHelper
exec(compile(script, scriptFile, 'exec'), d)
  File "C:/Users/lewisneal/.leo/scriptFile.py", line 16, in <module>
bu = g.bytesToStr(my_byte)
^^^^^^^^^^^^^^^^^^^^^
  File "N:\git\leo-editor\leo\core\leoGlobals.py", line 4861, in bytesToStr
assert isinstance(b, bytes), g.callers()
AssertionError: executeScriptFromButton,executeScript,executeScriptHelper,<module>
only 27 lines
--------------------
  line 4860: """Convert bytes to unicode."""
* line 4861: assert isinstance(b, bytes), g.callers()
  line 4862: tag = 'g.bytesToStr'
  line 4863: encoding = 'utf-8'_

Leo Log Window
Leo 6.7.9-devel, devel branch, build 64ee73219a
2024-03-26 04:10:55 -0500
Python 3.12.2, PyQt version 6.6.2
Windows 10 AMD64 (build 10.0.19045) SP0

**Comment by edreamleo** [comment]
@LewisNeal Why are you surprised? bytesToStr works only for arguments that are bytes. It is not a general replacement for either g.toEncodedString or g.toUnicode.

**Comment by LewisNeal** [comment]
Ah thanks.

**Comment by edreamleo** [comment]
@LewisNeal No problem :-)

**Comment by edreamleo** [comment]
I am going to close this issue for now:
- There is no further need to improve mypy annotations.
- Using these functions could easily create hard-to-find bugs.
