### ISSUE TITLE
Color emphasis syntax in markdown colorizer

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#386]
At present, the markdown colorizer handles html only, not emphasis like *x*, **x**, _x_ and __x__.

Adding colorizing for these constructs will be straightforward.

**Comment by tbnorth** [comment]
Not sure about Sphinx, but markdown seems to be more widely used than rest to me these days.  I'd like to see this fixed.

**Comment by edreamleo** [comment]
On Tue, Feb 28, 2017 at 1:07 PM, Terry Brown <notifications@github.com>
wrote:

> Not sure about Sphinx, but markdown seems to be more widely used than rest
> to me these days. I'd like to see this fixed.
>

​Me too.  I've just assigned it for Leo 5.6. It's too late, imo, for 5.5.

Edward

**Comment by xgid** [comment]
I use Markdown for everything I can. Even for recipes! :-) So I also vote for this one... although it's clearly not a high priority. 

For me, a good colorizing scheme of Markdown documents is the one used by [ghostwriter](https://wereturtle.github.io/ghostwriter/) which I use intensively (at this moment, side-by-side with Leo thanks to the great @clean directive).

**Comment by edreamleo** [comment]
I updated the title of this item.  The markdown colorize has never been "kinda useless". A primary goal of markdown has always been to allow embedded html.

**Comment by edreamleo** [comment]
Rev 2f9c60e completes this issue.

**Comment by tbnorth** [comment]
I think there are other targets for syntax highlighting in markdown.

```markdown
# Headings would be
## an example
```

[links](https://daringfireball.net/projects/markdown/syntax#link) would be another.

Can't actually google a good list, because results for syntax highlighting of code in markdown keep hijacking the results.  But \`literals\` etc. could all be highlighted.

**Comment by edreamleo** [comment]
Links would indeed be good to highlight.  

I'm not so sure about headings.  The point of `@auto-md` is that headlines generate the right number of `#` automatically. But yes, `@nosent x.md` is possible, so perhaps that isn't terrible. 

I don't want to encourage the underlining style of headers. Indeed, `@auto-md` made the (correct) choice *not* to support that underlined headers, on the grounds that the writer will never produce underlines. But, sigh, an argument could be made for colorizing underlining

**Comment by edreamleo** [comment]
Rev 7ee161d adds support for all requested features. All hand tests of highlighting look good.  Please reopen if there are problems.
