### ISSUE TITLE
New file is marked as changed

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#387]
Create a new leo file. Select File>Close. Despite no input or changes the dialog box requests input:
[ Confirm. Save changes to untitled before closing? Yes/No/Cancel ]

Dialog box should only appear if input/changes are actually made.

Leo 5.4, build 20170129073103, Sun Jan 29 07:31:03 CST 2017
Git repo info: branch = master, commit = 1c28e916c371
Python 3.6.0, PyQt version 5.7.1
Windows 10 AMD64 (build 10.0.14393) SP0

**Comment by edreamleo** [comment]
Fixed at rev 3fedb71 in the demo branch and 7ae114a in the master (via git cherry pick).

All tests pass in master and demo.
