### ISSUE TITLE
Searching for the definition should not alter the user's search options

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#3871]
See PR #3872. This is an irritating hangnail.

**Comment by boltex** [comment]
@edreamleo Leo and LeoInteg codebases are structured enough that it took me only about an hour to implement this in LeoInteg with https://github.com/boltex/leointeg/commit/0480148115d291fe1c812b156a1a151b3b1f5c56 , and in leoserver.py with https://github.com/leo-editor/leo-editor/pull/3943 

🦁  Leo Rules!
