### ISSUE TITLE
wikiview.py plugin problem with new colorizing code

### ISSUE THREAD

**Issue by tbnorth** [leo-editor/leo-editor#388]
Given an url like

```
http://blah/blah/blah/blah/blah/blah/blah/blah/something.html
```

wikiview sets the font point size on everything up to the last `/` to 0.1 so the user just sees `./something.html`, where the `.` is the shrunken text.  I don't think I'm the only user.  This allows in-body-text wiki like links, e.g. 

```
D:\local\leo-editor\leo\plugins\leoPlugins.leo#Plugins-->User interface-->@file wikiview.py-->class WikiView-->__init__
```

can appear as `__init__`.  So it's a feature with some value - without it, Leo can't display wiki like behavior, a feature of many competing environments.

20180420: am seeing this currently, I think it's just more noticeable with some files than others.  In most recent case I noticed that the space for the missing text exists in the body pane in terms of the scroll bar / apparent length of the body area, it's just the text itself which is not visible.

**EKR**: I agree.

But it seems that in the new colorizer code wikiview triggers something akin to the old Qt large text bug.  Given an @edit node for [this file](https://github.com/heroku/heroku-django-template/blob/master/project_name/settings.py) rendering is ok down to around the first entry in AUTH_PASSWORD_VALIDATORS, after which only the urls following that point (in comments) show up.

So somehow wikiview.py is clashing with other colorizing in a way it didn't before.

TB: I wonder if it's a race condition with two separate threads trying to colorize the same text?  Just guessing at this point.

**Comment by tbnorth** [comment]
One possible fix would be to merge the wikiview behavior into the core colorizing code.

**Comment by tbnorth** [comment]
Just observed, based on the line/col display, that the missing text is present, just invisible.  Also, the last line of the file, STATICFILES_STORAGE, is visible.

I suspect wikiview and the core colorizer are both fiddling around on the text with overlapping cursors - a new "colorizing_done" hook might also be a solution.

**Comment by edreamleo** [comment]
I suspect this is related to #383, which will block the release of Leo 3.5b1.

**Comment by tbnorth** [comment]
Following the discussion in #396 it seems the hiding functionality of wikiview should move in to the colorizer, but the revealing functionality probably needs to be handled separately, maybe by wikiview, maybe it would already work once the conflict between colorizers (i.e. Leo's colorizer and wikiview) is fixed by moving the hiding phase to Leo's colorizer.

**Comment by edreamleo** [comment]
@tbnorth I agree that wikiview's functionality should move into the core. I'll be working on this immediately. 

Tiny point size is good enough for now for hiding text.  I'm a bit surprised that there is no obvious, direct, way of doing this in Qt. Googling hasn't found any so far.

**Comment by tbnorth** [comment]
I thought you just referenced one on #396:

[This page](http://stackoverflow.com/questions/8994502/hiding-text-with-qsyntaxhighlighter) shows how to hide lines in a QTextEdit using [QTextCursor](http://doc.qt.io/qt-4.8/qtextcursor.html).block().setVisible(False).

**Comment by edreamleo** [comment]
@tbnorth The block.setVisible(False) hides the entire line. That doesn't do us any good, unless we add a line containing the actual image.  That would get complicated in a hurry.

**Comment by edreamleo** [comment]
Rev a38589fa8 in the color branch fixes two confusing problems with wikiview plugin:

1. wikiview-toggle was broken.  It must pass 'event' to show/hide, not 'c'.
2. WikiView.active was inited to c.config.getBool('wikiview-active')

That's right out of the Department of Redundancy Department.  I set it to True, and now things start to work. Toggle works, for instance.

However, the "hidden" view is squished at the left. Not sure what is going on. I'd like to include a screenshot, but I am having troubles.  I'll try again after posting this.

**Comment by edreamleo** [comment]
Rev 2c5a80f in master also fixes the crasher in wikiview-toggle.  Somehow that got dropped out when merging branches.

**Comment by edreamleo** [comment]
**Status**

This wikiview plugin works poorly with the new colorizer. The "hidden" parts of url's appear with all the characters overlapping each other in one place, like a colorized blob.  Apparently I can't show a picture here, but you can see for yourself.

**Plans**

The plugin interferes with the colorizer, so the colorizer will have to do all the work. I don't expect huge problems, but this project will be done in a resuscitated color branch.

I'll feel free to require new settings if that simplifies the colorizer's code.

**Comment by edreamleo** [comment]
Imo, rev dc16430 of the color branch shows that the problem must lie in `WikiView.hide`. Indeed, the new `jedit.match_wiki_pattern` method simply returns n, which disables all other matchers.

Traces confirm that no other patterns match. *This is a change*. Code at the end of `jedit.colorRangeWithTag` was firing unexpectedly.  Now it doesn't.

As a result, the colorizer does *no* coloring for any wikiview pattern.  I conclude that the appearance of hidden url's is due *only* to `WikiView.hide`. I won't rest until this method works properly.

**Comment by edreamleo** [comment]
I have just verified that the "hiding" code creates blobs even when *all* syntax coloring is disabled, either by disabling `jedit.recolor` or by setting `jedit.highlighter` to None(1).

There is no doubt about it. The title of this issue is incorrect.  Leo's colorizer is not to blame.

**Comment by edreamleo** [comment]
**Breaking news**: These values hide text as desired in the wikiview plugin:
```python
self.pts=1  # hidden text size: 0.1 does not work!
self.pct=1  # hidden text letter spacing
```
A few rough edges remain.  I expect to close this item later today.

**Comment by tbnorth** [comment]
The colorizer wasn't being blamed, but wikiview (its toggle command side) was working as expected until the recent colorizer changes. Seeing wikiview was itself essentially a colorizer, it's hardly surprising they conflicted, more luck that they didn't in the past.

**Comment by edreamleo** [comment]
Rev 44d6346 in the color branch now works as expected:
- Minimal changes made to the wikiview plugin and colorizer.
- Simplified wikiview settings so they have unique lead-ins.
- Most importantly, the wikiview plugin remains optional, and need not be part of Leo's core.
I'll close this after merging the color branch into master.

**Comment by edreamleo** [comment]
Rev 8030060a1 of master completes this item. The color branch is no more.

**Comment by tbnorth** [comment]
Unfortunately I have to re-open this, have seen it twice in the last couple of weeks in different .leo files.  Basically a body text with a shortened URL, e.g. `http:.1072212` for `http://stackoverflow.com/a/26744533/1072212`, will have some number of lines cut off, possibly many lines below the URL.  I'm not sure how easily this leads to corruption, if they're just invisible then they might not be lost if the node's edited, but they easily could be.

I will try and make a minimal example, but I think it's a race condition and really hard to reproduce reliably, even in the large complex files where I'm seeing it.

**Comment by edreamleo** [comment]
Terry, please use git-bisect to show the change to the colorizer that enables this problem.

As I look at the colorizer code, it looks completely benign.  I know of no way that the colorizer could cause data loss.  Ditto for the actual wikiview hind/unhide code.

**Comment by tbnorth** [comment]
On Fri, 27 Apr 2018 04:48:42 -0700
"Edward K. Ream" <notifications@github.com> wrote:

> Terry, please use git-bisect to show the change to the colorizer that
> enables this problem.
> 
> As I look at the colorizer code, it looks completely benign.  I know
> of no way that the colorizer could cause data loss.  Ditto for the
> actual wikiview hind/unhide code.

I can try git bisect, although it can be a difficult bug to reproduce
reliably, which would make sense if my hypothesis that it's a race
condition is correct.  Am I right that the colorizing code runs in a
different thread?

Most recent observations have suggested it doesn't cause data loss, it
just leaves text invisible, which can cause the user to cause data loss.

Trying to restore dock layout in the dock layout branch I've seen Qt
quite consistently produce inconsistent results with some gui
manipulations, although in that particular case I've found a better way
of doing it.

Cheers -Terry

**Comment by edreamleo** [comment]
On Fri, Apr 27, 2018 at 9:17 AM, Terry Brown <notifications@github.com>
wrote:

I can try git bisect, although it can be a difficult bug to reproduce
> reliably, which would make sense if my hypothesis that it's a race
> condition is correct. Am I right that the colorizing code runs in a
> different thread?
>

​Not to my knowledge. All of *Leo's* colorizing code runs in the main
thread.

Most recent observations have suggested it doesn't cause data loss, it
> just leaves text invisible, which can cause the user to cause data loss.
>

​Ouch.​


​Rev 066f4afb1e in devel adds support for --trace-coloring.  This will show
the calls to url-related colorizing code.  For example, my tests generates
this trace:

colorRangeWithTag    python.url   0  51 'https://github....'
wiki_rule,match_wiki_pattern
​


> Trying to restore dock layout in the dock layout branch I've seen Qt
> quite
> ​​
> consistently produce inconsistent results with some gui
> manipulations, although in that particular case I've found a better way
> of doing it.


​Heh.  "​
​consistently produce inconsistent results"​

Let's see what we can find in the next few days.

Edward

**Comment by edreamleo** [comment]
I am going to assign this to 5.7.3 for now.  Terry, let me know if you discover anything.
