### ISSUE TITLE
Allow VR3-style rendering overlaid on standard editing nodes.

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#3887]
This enhancement would allow Leo to optionally render non-text nodes in the same place as the current textual display.  Some other software such as Trillium do this, but currently Leo can only render such nodes in a separate frame or tab, as the viewrendered and viewrendered3 plugins do.

One way to do this might be to have VR/VR3 render to a new target that overlays the text node frame rather to a separate frame as they currently do.

Another approach would be to have nodes display in a tabbed widget rather than an editing widget.  If the users chooses to display a rendering, the tabbed widget would switch to the rendering tab. 

With either approach we could reuse most of the existing VR/VR3 code.  Note that VR3 can deal with multiple languages in a single node, which can provide a lot of flexibility.

The _freewin_ plugin already does this kind of dual rendering in a limited way.

**Comment by edreamleo** [comment]
@tbpassin I have changed the title of this issue, assigned it to you, and given it the 6.7.9 milestone.

I shall be working on #3892, which now applies only to the VR plugin.

**Comment by edreamleo** [comment]
@tbpassin I see no reason to create a plugin architecture for the VR/VR3 plugins at this time. We can discuss it later if you like.

**Comment by edreamleo** [comment]
@tbpassin Both the VR and VR3 plugins face a fundamental problem: the is no extra screen space! That's why using a separate window for the VR or VR3 panes is a reasonable thing to continue.

Without creating a separate window, the VR and VR3 plugins can only take space from the body, outline and log panes.  It's straightforward to overlay any of these panes without using the nested splitter plugin.

I'll approve any PR you submit that changes only the VR3 plugin.

There's no rush. I've assigned this issue to 6.7.9 only to indicate that I'm willing to consider a PR now.

**Comment by tbpassin** [comment]
Here is a script that causes VR3 to display in the same panel as the body editor.  It's a toggle so the command in effect changes between the body editor view and the VR3 view.  No changes to VR3 code were required, although I expect to add it as a VR3 command in the future.  With this script, I will close this issue.
```
"""Toggles the body frame between the body editor and
a Viewrendered3 rendered view.

Works with new-style (post 6.7.8) splitters.
"""
import leo.plugins.viewrendered3 as v3

def toggle_vr3_in_body(c):
    gui = g.app.gui
    body_stacked_widget = gui.find_widget_by_name(c, 'bodyStackedWidget')
    stacked_layout = body_stacked_widget.children()[0]

    h = c.hash()
    old_vr3 = v3.controllers.get(h)
    if old_vr3:
        vr3_index = stacked_layout.indexOf(old_vr3)
        if vr3_index > -1:
            vr3 = old_vr3
        else:
            v3.controllers[h] = vr3 = v3.ViewRenderedController3(c)
            vr3_index = stacked_layout.addWidget(vr3)
            old_vr3.deactivate()
            old_vr3.deleteLater()
    else:
        v3.controllers[h] = vr3 = v3.ViewRenderedController3(c)
        vr3_index = stacked_layout.addWidget(vr3)

    if stacked_layout.currentIndex() != vr3_index:
        stacked_layout.setCurrentIndex(vr3_index)
        vr3.set_unfreeze()
    else:
        stacked_layout.setCurrentIndex(0)  # Body editor should always be here
        vr3.set_freeze()

toggle_vr3_in_body(c)
```

**Comment by edreamleo** [comment]
On Thu, Jun 13, 2024 at 3:47 PM Thomas Passin ***@***.***>
wrote:

> Here is a script that causes VR3 to display in the same panel as the body
> editor. It's a toggle so the command in effect changes between the body
> editor view and the VR3 view. No changes to VR3 code were required,
> although I expect to add it as a VR3 command in the future. With this
> script, I will close this issue.
>
Thanks for this. I suggest adding this script (and others like it) to
scripts.leo via a PR.

Edward
