### ISSUE TITLE
Control-Click on Class Name May Return String Instance Instead Of Class Definition

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#3890]
When I CONTROL-Clicked _Commands_ on this line:
`c = leoCommands.Commands(fileName,`

Leo navigated me to the following instead of the actual class definition:
```
    return {
        'ChapterCommandsClass': ['class ChapterController'],
        'EditCommandsClass': [
            'EditCommandsClass',
            'class Commands',
            'class LeoQtFrame',
            'class LeoBody',
        ],
```

IMHO, Leo should have navigated to the actual class definition line, not to the target in a quoted string.  At a minimum, the target could be `class Commands\s*[:(]`, but preferably there would be a check for surrounding quotations.

**Comment by edreamleo** [comment]
@tbpassin Aha! Don't ever change search settings.  See #3871 for details.
