### ISSUE TITLE
LeoServer.py: Add current commander info in get_ui_states command

### ISSUE THREAD

**Issue by boltex** [leo-editor/leo-editor#3898]
For leoserver : Add the current commander info to the get_ui_states command return data.  This will enable more flexible UI interaction in LeoInteg or any other clients connected to it.

**Comment by edreamleo** [comment]
@boltex I'll do this issue immediately.

**Comment by boltex** [comment]
@edreamleo I'll make some more additions to the server. I spoke to soon in thinking those modifications were enough to implement detached body panes in LeoInteg. (or other external clients) This will take me a day or so. 

(I'll make a new branch and pull request.)

**Comment by edreamleo** [comment]
@boltex No problem. Take as much time as you want.
