### ISSUE TITLE
if __name__ == '__main__' parsed incorrectly

### ISSUE THREAD

**Issue by ktenney** [leo-editor/leo-editor#390]
commit 1c28e916c37153df427e93c8cb97b635f58f5cbd
declaration appended to class definition, this looks like a bug.

a minimal version of what I'm seeing, file test.py:
###########################
import sys
class Foo():
    pass
    def __init__(self):
        pass
       
if __name__ == '__main__':
    '''
    >>> print('ok?'')
    '''
    print('__main__')
###########################

When the above is added to a Leo file via @auto test.py,
the parsed version shows in the 'Declarations' node:
import sys

and shows in the 'Class foo' node:

class Foo():
     pass
     @others
if __name__ == '__main__':
     '''
     >>> print('ok?')
     '''
     print('__main__')

**Comment by edreamleo** [comment]
Strictly speaking, the problem is not a parsing problem. Furthermore, the perfect import checks pass.

But as you imply, it would be preferable to have the trailing lines of the last node be promoted to the top-level node. This should be relatively easy to do.
