### ISSUE TITLE
VR Plugin Shows Blank Pane in Windows But Works In Linux

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#3908]
I'm working with the newly merged VR code, `Leo 6.7.9-devel, devel branch, build 15f6b5fa8d`.

I adapted my script for toggling VR3 in the body pane so that it would toggle VR instead.  In Windows the pane is toggled but no rendering is displayed.  In Linux (XUbuntu) the rendering is displayed as expected.

I think this must be the same problem that causes a blank window frame to appear when I toggle VR with the usual commands (e.g., _vr-toggle_).  I have that happen pretty consistently in my Windows OS.  I have to close those blank windows using the task manager. I have checked the Windows event logs about those events, and they do show up but with no information except "Application Hang".

The blank window behavior does not depend on whether VR3 is enabled or not.  However, it is eliminated if I run my script that toggles VR in the body pane.  After I run that, then the _vr-toggle_ command does not create that blank window but moves the focus to the body pane.  However, the expected messages are emitted:

1. When I issue the _vr-toggle_ command with Leo newly open, I get the blank window.  I also get the message `VR pane on` in the log pane.
2. If I then run my script to toggle VR in the body pane, nothing displays but I get the messages `rendering pane locked` and `rendering pane unlocked` as I toggle it that way.
3. In a newly opened Leo session if I run my script to toggle VR in the body pane, I see it toggles but has no rendered content.  I get the same messages `rendering pane unlocked` and `rendering pane locked`.  If I then use the _vr-toggle_ command, I see nothing happen (except for focusing the body), and I get those same `VR pane on`/`VR pane off` messages.

Recall that my script imports VR but does not create a provider instance and (of course) the provider's `init()` method does not get called.

This should all be diagnostic if I can get it properly into my head.

**Comment by tbpassin** [comment]
My version of PyQt is 6.6.2.  What version is yours?

**Comment by tbpassin** [comment]
The blank window problem occurs when `vr.show()` is called.  Several of the vr-xx minibuffer commands call it.

**Comment by tbpassin** [comment]
> My version of PyQt is 6.6.2

That's interesting.  Pypi doesn't list 6.6.2 among the available versions of PyQt6.  It lists 6.6.0, 6.6.1, and 6.7.0.  I wonder if there is something wrong with 6.6.2.  I'll upgrade it in a venv and see if that makes a difference.

**Comment by tbpassin** [comment]
There's a minor bug in `vr.__init__()`.  It calls `create_pane(parent)`.  _parent_ is supposed to be a _QWidget_,  but the method's signature is actually

`def create_pane(self, parent: Position) -> None`

In practice this this doesn't matter because the `parent` argument isn't used by `create_pane()` anyway.

**Comment by tbpassin** [comment]
In this command:
```
@g.command('vr-show')
def show_rendering_pane(event: Event) -> None:
    """Show the rendering pane."""
    global controllers
    if g.app.gui.guiName() != 'qt':
        return
    c = event.get('c')
    if not c:
        return
    vr = controllers.get(c.hash())
    if not vr:
        vr = viewrendered(event)

    vr.show()
    vr.is_visible = True
    c.bodyWantsFocusNow()
```
`vr.parent()` is None.  In versions of VR before the recent changes, `vr.parent()` is a nested splitter.  Perhaps vr.show() doesn't work right if vr doesn't have a parent?

**Comment by edreamleo** [comment]
@tbpassin I am going to close this issue as probably already fixed.

Please create a new issue for any further VR problems.
