### ISSUE TITLE
VR3 Embedded Images With Relative Paths May Not Show In Exported File 

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#3917]
The problem is that a relative path to an image will not be correct relative to the exported HTML file.  So the image display correctly in VR3 if the image path is relative to the outline, but it won't necessarily be relative to the exported file.  This will also happen if the node is subject to an `@path` directive.

The solution is to check when updated for relative paths for images and replace them with the absolute paths.  This will have to be done separately for RsT, MD, and Asciidoc formats.

**Comment by tbpassin** [comment]
Fixed in PR https://github.com/leo-editor/leo-editor/pull/3923

**Comment by edreamleo** [comment]
Closed via PR #3924.
