### ISSUE TITLE
@auto-rst file.txt: -rst ignored on read

### ISSUE THREAD

**Issue by RagBlufThim** [leo-editor/leo-editor#392]
If I select a node, enter the headline ``@auto-rst file.txt`` and then do ``File`` > ``Read/Write`` > ``Read @auto Nodes`` on that node, the content of ``file.txt`` (which is reST with many headlines) is read completely into the body of the ``@auto-rst``-Node (with a line ``@nocolor`` prepended). No subnodes are created.

If I change the file extension to ``.rst``, change the headline accordingly and retry the read, many subnodes are created according to the section titles in the file.

Further experiments with various combinations of ``@auto`` vs. ``@auto-rst``, ``.txt`` vs. ``.rst``, data and read vs. write show:
* On read, only the file extension determines how the data is read. ``-rst`` in ``@auto-rst`` is ignored.
* On write, the ``-rst`` is honoured. Only with ``@auto`` (without ``-rst``) the file extension determines the write method.

As a consequence, reading and afterwards writing a file with ``@auto-rst file.txt`` **deletes the file content**:  The file content is read into the body of the main node, but writing rst ignores the body content of the main node.

Using

    Leo 5.4, build 20170129073103, Sun Jan 29 07:31:03 CST 2017
    Not running from a git repo
    Python 3.4.4, PyQt version 4.8.7
    Windows 7 AMD64 (build 6.1.7601) SP1

Cheers  
r..m

**Comment by edreamleo** [comment]
Thanks for this report. I'll fix it before Leo 5.5b1.

**Comment by RagBlufThim** [comment]
When I had a look at the importers and writers (for reasons not connected to this issue), I noticed that many of them have a ``'auto'``-line in a dict near the end. Especially the rst writer has one, and the markdown importer as well, but **not** the rst importer.

I had the idea that this might be the cause of this issue, and ``leo/plugins/importers/howto.txt`` seems to point in the same direction.

When I insert the line I found in the rst writer into the rst importer, ``@auto-rst file.txt`` works as expected. I don't know whether that's a proper fix or more has to be done, but at least it might serve as a pointer to the cause of the issue.

Here is my patch to ``leo/plugins/importers/leo_rst.py``:

    @@ -228,6 +228,7 @@
         #@-others
     #@-others
     importer_dict = {
    +    '@auto': ['@auto-rst',],
         'class': Rst_Importer,
         'extensions': ['.rst', '.rest'],
     }

HTH  
r..m

**Comment by edreamleo** [comment]
@RagBlufThim Many thanks for your help.

Fixed in master at 7a66ccd.

Please reopen if there are further problems.
