### ISSUE TITLE
Port the richtext plugin so it works with PyQt6.

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#3930]
I'll reinstate the richtext.py plugin, but I am not willing to do anything else.

**Comment by tbpassin** [comment]
I've been looking at this plugin and I'm not convinced I want to put in the effort. I'm sure the Qt bits can be updated, probably without much trouble. I suspect that they are Qt4, assome of the method names are different from what they are in Qt6.  But the CKEditor seems to have been changed:

1. It has to be sourced from a web server.  I think (just guessing) that an earlier version could be loaded from the file system (the whole thing is an HTML/javascript application). I happen to run a web server on my machine for local testing, but how many Leo users are going to want to do that?
2. The basic editor can be gotten free, and is claimed to be open source.  But there are a lot of add-ons that provide most of the things a person would actually like to do, and you have to pay for them.  I haven't been able to work out what you get without paying for the extras, but it looks pretty basic.

I might be willing to get further into it but only if there is some strong indication of interest, preferably by more than one person.

**Comment by edreamleo** [comment]
@tbpassin Thanks for your review. I would be happy to move this plugin to the attic.

Shall we close this issue?

**Comment by tbpassin** [comment]
Yes, let's do that. If someone cares enough they can make a request.
