### ISSUE TITLE
Keyboard shortcuts for todo priorities delete headline text during editing

### ISSUE THREAD

**Issue by maarli** [leo-editor/leo-editor#3932]
If you have a keyboard shortcut for instance for todo-inc-pri in the newest Leo branch and you edit the headline from a new node in the outline, if you then press the corresponding key for todo-inc-pri during editing, your headline text you were editing vanishes and instead "newHeadline" appears. After pressing Enter the todo icon appears. The expected behaviour would be that the editing is ended with the text you just entered and the appropriate todo icon appears on the edited node immediately. With the buttons in the GUI this works like expected, but not with a keyboard shortcut which is at least unintuitive in my opinion and smells like a bug to me. Besides that, I loose a lot of times my headline text with Leo 6.7.7 because I am so used to add a todo icon with a key stroke directly after typing.

This worked out of the box in about version 4. In version 6.1, it did not work any more but could be regained by reintroducing `c.treeFocusHelper()` in `change_current_position()` in core/leoFrame.py. In the newest version of Leo, this hack does not work any more because the code changed too much two years ago. I figured this out only now because I only update my Leo every couple of years. Now I would like to use the newest version and I am not that deep in the development of the core of Leo so that I decided to post this issue.

**Comment by edreamleo** [comment]
Fixed via PR #4004.
