### ISSUE TITLE
the cloneToAtSpot command doesnt undo the 'spot' node when undoing

### ISSUE THREAD

**Issue by boltex** [leo-editor/leo-editor#3934]
The `clone-to-at-spot` command doesn't undo the 'spot' node when undoing: It undoes the 'clone', but forgets the 'spot' node it may have created.

The undo code should use `u.beforeUndoGroup` and `u.afterUndoGroup`.

**Comment by edreamleo** [comment]
@boltex Thanks for your report. I'll fix this immediately.

**Comment by edreamleo** [comment]
Closed via PR #3937.
