### ISSUE TITLE
Script Elements In HTML Pages Should Be Treated Like Code, Not Markup

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#3966]
The contents of _script_ elements in HTML pages should be treated as the code it is, usually javascript or typescript.  This goes beyond syntax coloring to, for example, add and remove comments.  

As a specific example, given the following script element:
```
    <script type="module">
        import convert from "https://cdn.skypack.dev/convert@5";
        // Make "convert()" available to other code
        window.convert_ns = {};
        window.convert_ns.convert = convert;
    </script>
```
If I put the cursor on the last line of javascript and run the `add-comment` command, the line changes to 
`        <!-- window.convert_ns.convert = convert; -->` 
but it should have changed to
`        //window.convert_ns.convert = convert`

**Comment by tbpassin** [comment]
A corollary is that the contents of _style_ elements should also be treated as their language ... which is not always CSS ...

**Comment by edreamleo** [comment]
@tbpassin The only way to do this would be to add `@language` directives to the code.
