### ISSUE TITLE
Request: add GLSL support to colorizer

### ISSUE THREAD

**Issue by gatesphere** [leo-editor/leo-editor#3967]
See PR #4198.

Add a [GLSL](https://www.khronos.org/opengl/wiki/OpenGL_Shading_Language) colorizer definition to Leo.  Should be trivial, GLSL is very C-like, with a few additional keywords.  Common file extensions:  `.vert, .tesc, .tese, .geom, .frag, .comp, .glsl`.

**Comment by edreamleo** [comment]
Closed via PR #4198.
