### ISSUE TITLE
Command save-file-as-zipped Saves as SQLite database file,  not as a zipped file

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#3977]
See PR #3979.

This command does not do what it says, going either by the command name or by its docstring. A .db file is not a "zipped" file, by any normal use of the term.

**Comment by edreamleo** [comment]
@tbpassin Thanks for this report. I'll investigate.

**Comment by edreamleo** [comment]
@tbpassin The obvious fix is to change the name of the command so it ends in `-db` rather than `-zipped`, with the corresponding change to the docstring.

This change could be called a (minor!) breaking change, so I'll document it in the `What's New` section.

**Comment by boltex** [comment]
I second Thomas on that one. Indeed all mention of 'zipped' in this node should be 'sqlite' :
![image](https://github.com/leo-editor/leo-editor/assets/847716/c5785214-8aeb-4588-9203-15eeb27536ee)

**Comment by boltex** [comment]
... or 'db' .... but defenitely not 'zipped' !  😄

**Comment by boltex** [comment]
Note that in this node, 'zipped' does refer to actual 'zip' files. (Making this whole save-as-zipped nomenclature really confusing!)
![image](https://github.com/leo-editor/leo-editor/assets/847716/bbd8e1cd-586f-49af-86e4-73040ee6aff7)

**Comment by edreamleo** [comment]
@boltex @tbpassin PR #3979 is ready for review :-)

**Comment by boltex** [comment]
As soon as this is done, I'll modify LeoInteg to handle this command name change so that the next release of LeoInteg for Leo 6.8.0 handles this properly.

**Comment by edreamleo** [comment]
Closed via PR #3979.
