### ISSUE TITLE
TODO icons (and possibly all uas?) are not persisted on @edit notes

### ISSUE THREAD

**Issue by gatesphere** [leo-editor/leo-editor#3990]
Adding a todo icon to an `@edit` node (via right click->task->status) adds the icon to the current working display of the file.  Saving, quitting, and reopening the .leo workbook shows that this information did not persist.

I assume this is because `@edit` nodes read their entire state from external files on disk when loading, meaning this data is simply lost because there's no specific code to save it in the outline.  Perhaps this is intended behavior, but it is inconsistent at best -- icons (and other ua info) is properly persisted on other file node types, and this presents a confusion point for the user.

("Just use `@clean`" isn't always an option, `@edit` nodes fill a niche that I have very frequent use for.)

**Comment by tbpassin** [comment]
I set an "Enhancement" label on this issue, but let me know if you think it should be "Bug" instead.  If a label and milestone date aren't set, Edward might not notice a new issue for a time.

**Comment by edreamleo** [comment]
Closed via PR #4005.

**Comment by gatesphere** [comment]
Thank you!

**Comment by boltex** [comment]
@edreamleo I applied this and all the last commits since 6.8.0 to LeoJS 😁

**Comment by edreamleo** [comment]
@gatesphere You're welcome. It was good to fix this issue.

**Comment by edreamleo** [comment]
@boltex Thanks for keeping LeoJS in sync. It's amazing that these bugs have stuck around in Leo for decades.
