### ISSUE TITLE
Documentation update at leoeditor.com

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#401]
Delete the section 'Installing Leo itself' ( http://leoeditor.com/installing.html#installing-leo-itself )
It is an obsolete duplicate of Downloading Leo ( http://leoeditor.com/download.html )
Some of it's links are very out of date.

**Comment by edreamleo** [comment]
Thanks for this.  Done at 9122049 and uploaded to Leo's web site.
