### ISSUE TITLE
VR Docstring Display Flashes Off Immediately

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#4028]
When only VR is enabled and not VR3 and a user uses F11 to view the docstring for a command, VR only displays it for a fraction of a second and then returns to the display of the node.  This also happens when the "About" menu item in the Plugins menu is clicked.

When VR3 is enabled the docstring message remains displayed until the user selects another node or edits the existing one, as desired.

I noticed the behavior with the current version of devel but I'm pretty sure it has been there for some time.

**Comment by edreamleo** [comment]
@tbpassin This must wait for 6.8.2. I'm going to release 6.8.1 today.

**Comment by edreamleo** [comment]
@tbpassin PR #4017 will fix this.
