### ISSUE TITLE
reload-outline command

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#4037]
See PR #4038.

A new `reload-outline` command will close then reopen *one* outline *without* restarting Leo.

Changing `@string qt-layout-name` will execute  `reload-outline` rather than `restart-leo`.

**Comment by edreamleo** [comment]
@tbpassin This issue will be a preliminary to our work on layouts.

**Comment by tbpassin** [comment]
I'm not giving up on switching to any layout without a reload, not yet.

**Comment by edreamleo** [comment]
@tbpassin Fair enough. The `reload-outline` command should be straightforward and I plan to add it whatever else happens.

**Comment by tbpassin** [comment]
D'accord. It should be useful aside from any layout usage.

**Comment by edreamleo** [comment]
Closed via PR #4038.
