### ISSUE TITLE
Leo deleting certain decorators in python source files

### ISSUE THREAD

**Issue by JohnLunzer** [leo-editor/leo-editor#404]
I'm on:
Leo 5.4, build 20170125092926, Wed Jan 25 09:29:26 CST 2017
Git repo info: branch = master, commit = 4efb5f58ac71
Python 2.7.11, PyQt version 4.8.6

I opened one of my Leo files and I found that most of my @property, @staticmethod and @classmethod. There were a few instances where a @classmethod was split from its function node, which saved it from being deleted. Makes me think this is related to #360. 

I'm pretty sloppy about following pep8 guidelines for spacing between functions because Leo doesn't insert spacing automatically between nodes. So I think in most of those cases there were no empty lines between the end of a previous function and the start of the next.

Please let me know if this issue has been address since my build, seems pretty serious. Set me back about 45 minutes finding and fixing all spots where the decorators were wiped out.

**Comment by JohnLunzer** [comment]
Same build, I opened up these files again and the decorators were intact. I'll close this, if I have a problem again I'll reopen.

**Comment by edreamleo** [comment]
On Thu, Feb 9, 2017 at 12:09 PM, John Lunzer <notifications@github.com>
wrote:

> Closed #404 <https://github.com/leo-editor/leo-editor/issues/404>.
>

​Thanks for this.

Edward
