### ISSUE TITLE
Plugin > About launches VR3 but shows current node

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#4040]
Plugins> Freewin> About> launches a VR3 pane but it displays the current node, not the Docstring of the plugin.
Thre is an initial flash display but it is then replaced by the current node.
I need to toggle VR3 off then repeat the request, then the plugin Docstring displays.

Leo 6.8.2-devel, devel branch, build 4329b05534
2024-08-13 21:28:19 -0500
Python 3.12.5, PyQt version 6.7.2
Windows 10 AMD64 (build 10.0.19045) SP0

**Comment by tbpassin** [comment]
Hmm, that doesn't happen on my system. I have seen the same thing with VR in the past when used with F11 to get the docstring for a command.  The remedy is to get VR3 showing first, then use the plugin menu.

I suspect that the code that sends the docstring to VR/VR3 is making some assumption that isn't quite right.

Once we get a system for creating/restoring layouts and put it into the VR/VR3 code the problem should go away.

**Comment by LewisNeal** [comment]
Fixed with #4060
