### ISSUE TITLE
Error in mySettings.leo

### ISSUE THREAD

**Issue by rengel-de** [leo-editor/leo-editor#4042]
In **@settings/@keys/@shortcuts** the note reads:

`You can define keyboard shortcuts here of the form **some-command Shift-F5**`

It should read (note the equal sign!): 

`You can define keyboard shortcuts here of the form: **some-command = Shift-F5**`

**Comment by edreamleo** [comment]
@rengel-de Good catch. Fixed at rev [80504c](https://github.com/leo-editor/leo-editor/commit/80504c7685746d132655336f4c27812f464ce0e2).
