### ISSUE TITLE
Second Body Editor Added By Add/Delete Body Editor Corrupts Text

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#4046]
See PR #4047.

After a second body editor is added by the menu item to Add-Editor, the new editor is selected, and a different node (Node B) is selected, then when text is typed into the added editor, the view shown by the second editor switches back to a view of the first node (Node A) even though that node isn't selected anymore. Focusing the second editor, selecting another node, and then selecting Node B still shows the text of Node A in the added editor, which should be showing the edited text of Node B.

The intended view of Node B can be restored by issuing CTRL-z in the added editor.

First reported in [Broken Add/Delete Body Editor](https://groups.google.com/g/leo-editor/c/hmN4bfM082A)

```
Leo 6.8.2-devel, devel branch, build 8257ccf8f0
2024-08-20 05:03:33 -0500
Python 3.12.3, PyQt version 6.7.2
Windows 10 AMD64 (build 10.0.19045) SP0
```
Confirmed by two users so far.

**Comment by edreamleo** [comment]
Completed via PR #4047.
