### ISSUE TITLE
Quicksearch Plugin's Docstring is out of date

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#4048]
The docstring as displayed by the plugin manager is rather out of date.  It says that only headlines are searched, which is only the case if the user does not press <ENTER>.  It does not know about the incremental search of headlines as characters are typed in. It says you have to press <ENTER> to get the search, but that causes a search of all text, not just headlines.

The current behavior is better than the description in the docstring, and I suppose that most people will learn pretty quickly how it really works.  But still, the docstring should be updated.

**Comment by edreamleo** [comment]
@tbpassin I am closing this issue as probably fixed. Please reopen if necessary.
