### ISSUE TITLE
"Already Open Files" bug in Leo-5.4?

### ISSUE THREAD

**Issue by whatacold** [leo-editor/leo-editor#405]
Yesterday I upgrade Leo from 5.3-final to 5.4 on Windows 7, then I find a possible bug about "Already Open Files" warnings dialog introduced in 5.4, because 5.3-final doesn't have this problem.

I've create a shortcut for Leo with options `--session-save --session-restore`

Here is the steps to reproduce this bug:
1. Launch a Leo-5.4 instance for the first time, and there is no any other Leo instance.
2. Open some files, say foo.leo and bar.leo
3. Press `Ctrl+Q` to quit
4. Launch leo again, this time it will pops up a dialog about `Already Open Files` of foo.leo and bar.leo

If I close the files to quit Leo, there will be no such dialog, that is:
1. same as above
2. same as above
3. Press `Ctrl+F4` twice to close foo.leo and bar.leo
4. Lauch leo again, everything is ok.

**Comment by whatacold** [comment]
This can't be reproduced on Linux.

**Comment by edreamleo** [comment]
I don't see this behavior. It looks like a problem with your Windows environment.

If you like, please discuss this at leo-editor. You'll probably have a large audience.
