### ISSUE TITLE
After Trying To Change Layout, Minibuffer Tab Completion Does Not Open The Completion Pane.

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#4053]
After trying to change the layout as described in https://github.com/leo-editor/leo-editor/issues/4052, using tab completion in the minibuffer does not open the Completion pane.

**Comment by edreamleo** [comment]
@tbpassin Tab completion works for me in both the "devel" and "ekr-4054-add-at-string-node" branches.

However, I see now that the "reload-outline" branch leaves the old outline open. That's can't be good.

**Comment by tbpassin** [comment]
This happens to me when I only had one outline open and reloaded it, and also when I had several outlines open and reloaded one of them. Before a reload tab completion works as intended.  The missing Completion panel only happens in the reloaded outline.  I think that typing in the minibuffer works as it did.  It's just the Completion pane that's missing.

**Comment by tbpassin** [comment]
When I run one of the `use-xxx` commands I still get the completion pane.  I don't get it after running `dw.change_layout()` directly.

**Comment by tbpassin** [comment]
I'm starting to see. The _qt-layout-name_ settings node has to be in the @settings tree. I've been calling the `dw.change_layout()` method in my script, and it looks for the setting anywhere in the outline.  If I execute one of the _use-xxx_ minibuffer commands, it all works as intended.

Very confusing.

**Comment by tbpassin** [comment]
After added the _use-xxx_ commands to a custom menu, I think more strongly that the change_layout command should create its setting node in the outline's `@settings` tree.

**Comment by edreamleo** [comment]
@tbpassin That's what PR #4055 does. Please approve it.
