### ISSUE TITLE
reload-outline leaves the old outline visible

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#4056]
PR #4058 retires `reload-outline`, rendering this issue moot.

Alas, it looks like the `reload-outline` command is thoroughly broken.

I'll probably retire the code and use `restart-leo` instead.

**Comment by LewisNeal** [comment]
Related issue https://github.com/leo-editor/leo-editor/issues/4049

**Comment by edreamleo** [comment]
@LewisNeal @tbpassin I'm going to retire `reload-outline`, replacing it as needed with `restart-leo` and moving the old code to the attic.

I have zero desire to fix this issue, but I'll be happy to consider a PR that brings `reload-outline` back. I'll say more in an ENB.

**Comment by edreamleo** [comment]
Closed via PR #4058. I would welcome a PR that successfully reinstates `reload-outline`.
