### ISSUE TITLE
vr3-toggle command turns a vr3 pane off, but not back on.

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#4057]
Test with 2 scenarios:
1. After the _vr3_ command is given, _vr3-toggle_ command turns a vr3 pane off, but not back on.

2. If the _vr3-toggle_ command is given first, the vr3 pane launches. Again the _vr3-toggle_ command turns a vr3 pane off, but not back on.

Also the _vr3-show_ command does not work. Maybe it is obsolete.
The _vr3-show_ command is still in the menu: Plugins> viewrendered3> vr3-show.
F11 : vr3-show  reports "Show the rendering pane."
However the VR3 docstring Commands list does not include _vr3-show_.

Leo 6.8.2-devel, devel branch, build 12f06b69ea
2024-08-28 10:58:09 -0500
Python 3.12.5, PyQt version 6.7.2
Windows 10 AMD64

**Comment by tbpassin** [comment]
This all has to do with the new layout commands.  Edward changed how some of the VR3 commands work but without coordination with me. I have started to think out what changes I should make to harmonize everything better. I wanted to wait until I was sure the new layout code was fairly stable.

I have been controlling VR3 using a custom menu and that's probably why I didn't spot the problems you are reporting. I have attached a Leo outline that contains the settings for this custom menu so you can add it to myLeoSettings.leo if you want.  

There are two nodes under the top `@settings` node.  The "VR3 Settings" node contains some VR3 settings I use. The  "Menus" node defines the new menu. The node "tp- commands" contains the scripts that the menu items use. 

I'm not sure that these new menu items will completely overcome all layout-related oddities but if not they still do what I want. After I figure out how I want to change VR3, some of these commands may need to be updated but we can dealt with that when the time comes.

There is an item named "Restore Default Layout".  That means the basic layout I like.  It's not related to Edward's new named layouts. You will be able to see right away how it works and change it if you don't like my starting point.

In the meantime, please give this custom menu a try and let me know if you would like any changes to be made to it.
[tp-vr3-menus_and_settings.zip](https://github.com/user-attachments/files/16817799/tp-vr3-menus_and_settings.zip)
