### ISSUE TITLE
failed to launch Leo on Linux due to line break of launchLeo.py in Leo-5.4.zip is DOS

### ISSUE THREAD

**Issue by whatacold** [leo-editor/leo-editor#406]
I don't know where it's DOS format or not in previous versions, but it is in Leo-5.4.zip.
I downloaded it at [SourceForge](https://sourceforge.net/projects/leo/files/Leo/5.4-final/Leo-5.4.zip/download).

The DOS format will cause error like `/usr/bin/env: ‘python\r’: No such file or directory` if I invoke launchLeo.py directly, i.e. without specifying the python interpreter. Pay attention to the `\r` in the output.

But I've checked it's unix format in GitHub repo. Maybe something goes wrong when packaging it?

**Comment by edreamleo** [comment]
> The DOS format will cause error like /usr/bin/env: ‘python\r’: No such file or directory.

This looks like a problem in your installation. It has nothing to do with launchLeo.py itself.
