### ISSUE TITLE
Control position of the nav_Qt <--> buttons in icon bar

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#407]
Request to add ability to control the icon bar position of the nav_Qt <--> buttons and the Chapters 'main' button.
Currently when @buttons are added they are pushed off to the right.

Also please add ability to allow multiple lines of buttons/controls.
There is a wrap **>>** arrow at the RH end of the button list, but this would work better as an on/off toggle. If your cursor drifts away the button list recedes and you have to press the wrap **>>** arrow again.

**Comment by edreamleo** [comment]
A worthy goal, but it won't happen in Leo 5.5.

**Comment by LewisNeal** [comment]
There already appears to be some variability in the position of the nav_Qt <--> buttons.
Test scenario:
Create a new leo file. The nav_Qt <--> buttons are at the LHS of the buttons.
Do not make any changes to the file. Save the file with a name, reopen it and you will see that the nav_Qt <--> buttons location has changed to the RHS.

**Comment by vitalije** [comment]
With current version of nav_qt plugin it is possible to put navigation buttons at the beginning of toolbar by placing nav_qt.py before mod_scripting.py in `@enabled-plugins`.

@LewisNeal here is script that simulates expanding toolbar. 
```python
from leo.core.leoQt import Qt
pos = Qt.QPointF(0, 0)
button = Qt.Qt.LeftButton
btns = Qt.Qt.MouseButtons(0)
mods = Qt.Qt.KeyboardModifiers(0)
e1 = Qt.QMouseEvent(Qt.QEvent.MouseButtonPress, pos, button, btns, mods)
e2 = Qt.QMouseEvent(Qt.QEvent.MouseButtonRelease, pos, button, btns, mods)
for w in c.frame.iconBar.w.children():
    if w.objectName() == 'qt_toolbar_ext_button':
        Qt.QApplication.sendEvent(w, e1)
        Qt.QApplication.sendEvent(w, e2)
        break
```
You can put that in `@button expand-toolbar` node in your myLeoSettings.leo under `@buttons` node.
If it is first child of `@buttons` then this button will be on left side of toolbar and it will be easier to click this button and then to find button you need. 
HTH Vitalije

**Comment by edreamleo** [comment]
On Fri, Jul 14, 2017 at 6:56 AM, Виталије Милошевић <
notifications@github.com> wrote:

> With current version of nav_qt plugin it is possible to put navigation
> buttons at the beginning of toolbar by placing nav_qt.py before
> mod_scripting.py in @enabled-plugins.
>
​A clever solution.  Please update the nav_qt.py docstring if you have not
already done so.  Otherwise, this will become a hard-to-find Easter Egg​.

Edward

**Comment by vitalije** [comment]
> ​A clever solution.  Please update the nav_qt.py docstring if you have not
  already done so.  Otherwise, this will become a hard-to-find Easter Egg​.
Done at 0b763b4.
Here is another script that will live reorder mod_scripting and nav_qt. I am not 100% sure of any side effects (are those plugins really reloadable), but it does swap buttons in toolbar.

```python
c.frame.iconBar.clear()
pc = g.app.pluginsController
ms = pc.getPluginModule('leo.plugins.mod_scripting')
nq = pc.getPluginModule('leo.plugins.nav_qt')
if c.hash() in nq.controllers:
    del nq.controllers[c.hash()]
del c.chapterController.tt
nq.onCreate('new', {'c':c})
ms.onCreate('new', {'c':c})
c.chapterController.tt =  c.frame.iconBar.createChaptersIcon()
```
