### ISSUE TITLE
ctrl-F broken

### ISSUE THREAD

**Issue by dalcolmo** [leo-editor/leo-editor#4070]
When pressing crtl-F, instead of opening the Find tab, I get a new log window and:

Traceback (most recent call last):
  File "/home/dalcolmo/programs/leo-editor/leo/core/leoGlobals.py", line 318, in new_cmd_wrapper
    func(self, event=event)
  File "/home/dalcolmo/programs/leo-editor/leo/core/leoFind.py", line 1837, in start_search
    self.open_find_tab(event)
  File "/home/dalcolmo/programs/leo-editor/leo/core/leoFind.py", line 895, in open_find_tab
    c.frame.log.selectTab('Find')
  File "/home/dalcolmo/programs/leo-editor/leo/plugins/qt_frame.py", line 2672, in selectTab
    self.finishCreateTab(tabName)
  File "/home/dalcolmo/programs/leo-editor/leo/plugins/qt_frame.py", line 2699, in finishCreateTab
    if hasattr(widget, 'ensureWidgetVisible'):
               ^^^^^^
UnboundLocalError: cannot access local variable 'widget' where it is not associated with a value

Leo Log Window
Leo 6.8.2-devel, devel branch, build aa1c30137e
2024-09-26 03:33:39 -0500
Python 3.12.5, PyQt version 6.7.2
linux

This is under Manjaro. The same setup worked fine under Kubuntu with Qt 5

**Comment by tbpassin** [comment]
I do not get this problem either on Manjaro/xfce or on EndeavourOS/Cinnamon, which is another Arch-based distro.
However, I'm on a more recent revision: build b593bcc1c6.  Please update to the latest devel version and see of you still have the problem (I doubt that this issue has been touched between the two revisions but might as well make sure).

**Comment by edreamleo** [comment]
@tbpassin Thanks for your investigations.
@dalcolmo I agree with Thomas. This is almost certainly an installation issue.

**Comment by dalcolmo** [comment]
Hmm. I use Manjaro with Plasma (KDE). I simply copied the git repo from Kubuntu. Everything else seems to work fine and I use a lot of different programs, so it is surprising that this is the only issue I have, but agree, that this is likely an installation issuue. I will try installing again from scratch.

**Comment by edreamleo** [comment]
@dalcolmo I am going to close this issue because it is likely an installation issue.
