### ISSUE TITLE
Improve And Add Flexibility To The Layout System

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#4076]
Leo's current layout system has several disadvantages: a restart of the current outline is needed to change layouts, and it is hard for a user to create new ones in case none of the built-in ones seem satisfactory.

This issue proposes changing the layout system so that it  is more flexible for users, does not require a restart, and is simpler for users with only minor scripting skills to create new ones.

**Comment by edreamleo** [comment]
Fixed via PR #4077 and follow-on PRs.
