### ISSUE TITLE
c.recursiveImport uncaught exception on broken (linux) symlinks

### ISSUE THREAD

**Issue by daveuu** [leo-editor/leo-editor#408]
If c.recursiveImport() encounters a symlink that points to a non-existent location, an OSError error is raised and recursive import stops:
```
OSError: [Errno 2] No such file or directory: ...
```
It seems a warning to the user and completion of the recursive import would be preferable? And [enhancement?] possibly creation of a node corresponding to the broken symlink with an indication that it pointed nowhere?

**Comment by edreamleo** [comment]
Rev 8e167a6 attempts to catch all exceptions in the recursive import controller.

Please reopen if problems remain.
