### ISSUE TITLE
Introducing Leo Guru on Gurubase.io

### ISSUE THREAD

**Issue by kursataktas** [leo-editor/leo-editor#4082]
Hello Leo team,

I wanted to update you that I've added the Leo Guru to Gurubase. Gurubase is a platform that aggregates open-source tools to help developers find information quickly. Leo Guru uses the data from this repo and the data from [docs](https://leo-editor.github.io/leo-editor/leo_toc.html) to answer questions. I hope you find it useful.

Here is the link to the Leo Guru: https://gurubase.io/g/leo

I believe Leo users or new starters would find it useful to have a badge or a link to Gurubase in the README.md. I've prepared two examples below:

Example 1 - Just a badge: 
--
[![](https://img.shields.io/badge/Gurubase-ASK%20LEO%20GURU-006BFF)](https://gurubase.io/g/leo)

Example 2 - Separate Section:
--
### ✨ Ask Leo Guru
If you don’t want to get lost in the documentation, you can ask [Leo Guru](https://gurubase.io/g/leo) directly. It’s an AI that focuses on addressing your questions about Leo.
[![](https://img.shields.io/badge/Gurubase-ASK%20LEO%20GURU-006BFF)](https://gurubase.io/g/leo)

If you find it useful, I would be happy to open a PR for this.

Additionally, if you want me to disable Leo Guru in Gurubase, just let me know that's totally fine.

**Comment by edreamleo** [comment]
I am closing this issue as off topic. If you want to discuss Leo Guru please do so at https://groups.google.com/g/leo-editor.
