### ISSUE TITLE
"execute-external-file" command fails on some Linux systems

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#4091]
The `execute-external-file` command launches a node or subtree in an external terminal and leaves the terminal open after the program has finished running so any printed output can be seen. Making the command work on as many Linux systems as possible was a challenge because different distros use different terminal emulators and some of them use different syntax to launch programs.

I have found a few distros for which the command failed. One common terminal emulator, gnome-terminal, may change its syntax in the future in a way that may not work.

The problem is that to discover the right syntax, the command parses the terminal's help message.  But differences in the help output can make it hard to do this correctly although it works for most cases. Even `xterm` is not universally available, and even when it is, often its appearance and readability is poor.

The determination of the correct terminal syntax to use can be improved by hard-coding the right syntax for the most common cases known. The ones I know about so far are
`('konsole', 'xfce4-terminal', 'mate-terminal', 'gnome-terminal', 'xterm')`. If anyone knows others that should be included along with the right syntax, please add the information in a comment. An example of the syntax comes from the xterm help string:
```
$ xterm -help |grep execute
    -e command args ...          command to execute
```
Here the option to use is `-e`.

 I will wait a few days to see if there are any suggestions, then go ahead with a pull request.

**Comment by edreamleo** [comment]
@tbpassin Thanks for your detailed report.

**Comment by edreamleo** [comment]
Completed via PR #4100.
