### ISSUE TITLE
"execute-external-file" Command Bug Prevents Honoring Of Terminal Specification

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#4097]
The _execute-external-file_ command is supposed to read the path to a terminal emulator program form an optional `@data` node if it exists.  However, a bug in the code that processes the `@data` node prevents that from succeeding.

This should be fixed before the next release of Leo.

**Comment by edreamleo** [comment]
@tbpassin Thanks for this report. I agree that this issue should be fixed for 6.8.2.

**Comment by tbpassin** [comment]
In the PR to come, I will also include code to address https://github.com/leo-editor/leo-editor/issues/4091, since it is all about the same command.

I expect to be ready for a PR sometime tomorrow.

**Comment by edreamleo** [comment]
On Mon, Oct 14, 2024 at 9:47 AM Thomas Passin ***@***.***>
wrote:

> In the PR to come, I will also include code to address #4091
> <https://github.com/leo-editor/leo-editor/issues/4091>, since it is all
> about the same command.
>
> I expect to be ready for a PR sometime tomorrow.
>
Many thanks for this work. I'll look forward to the PR.

Edward

**Comment by edreamleo** [comment]
Closed via PR #4100.
