### ISSUE TITLE
Current commit will not start on Win 7 Python 2.7.6 PyQt 4.8.5

### ISSUE THREAD

**Issue by gatesphere** [leo-editor/leo-editor#410]
It appears that commit 0cda77588ab95d9004b533d64e1c9a4787b0fe61 broke Leo for me -- the most working commit on my desktop is it's parent.  Here's the log pane from the most recent working version:

```
Leo Log Window
Leo 5.4, build 20170206081934, Mon Feb  6 08:19:34 CST 2017
Git repo info: branch = None, commit = 22a74c2db4bd
Python 2.7.6, PyQt version 4.8.5
Windows 7 x86 (build 6.1.7601) SP1
```

Here's the traceback on 0cda775 and newer:

```
leoID=peckj (in C:\Users\PeckJ\.leo)
reading settings in C:\cygwin\home\PeckJ\repos\leo\leo-editor\leo\config\leoSettings.leo
Traceback (most recent call last):
  File "C:\cygwin\home\PeckJ\repos\leo\leo-editor\launchLeo.py", line 8, in <module>
    leo.core.runLeo.run()
  File "C:\cygwin\home\PeckJ\repos\leo\leo-editor\leo\core\runLeo.py", line 63, in run
    g.app.loadManager.load(fileName, pymacs)
  File "C:\cygwin\home\PeckJ\repos\leo\leo-editor\leo\core\leoApp.py", line 1966
, in load
    lm.doPrePluginsInit(fileName, pymacs)
  File "C:\cygwin\home\PeckJ\repos\leo\leo-editor\leo\core\leoApp.py", line 2020
, in doPrePluginsInit
    lm.readGlobalSettingsFiles()
  File "C:\cygwin\home\PeckJ\repos\leo\leo-editor\leo\core\leoApp.py", line 1917
, in readGlobalSettingsFiles
    commanders = [lm.openSettingsFile(path) for path in paths]
  File "C:\cygwin\home\PeckJ\repos\leo\leo-editor\leo\core\leoApp.py", line 1891
, in openSettingsFile
    c = g.app.newCommander(fn)
  File "C:\cygwin\home\PeckJ\repos\leo\leo-editor\leo\core\leoApp.py", line 1107
, in newCommander
    import leo.core.leoCommands as leoCommands
  File "C:\cygwin\home\PeckJ\repos\leo\leo-editor\leo\core\leoCommands.py", line
 889
    exec(compile(script, scriptFile, 'exec'), d)
SyntaxError: unqualified exec is not allowed in function 'executeScriptHelper' it contains a nested function with free variables
```

**Comment by edreamleo** [comment]
On Tue, Feb 14, 2017 at 1:18 PM, Jacob Peck <notifications@github.com>
wrote:

> It appears that commit 0cda775
> <https://github.com/leo-editor/leo-editor/commit/0cda77588ab95d9004b533d64e1c9a4787b0fe61>
> broke Leo for me
>
​...

>   File "C:\cygwin\home\PeckJ\repos\leo\leo-editor\leo\core\leoCommands.py", line
>  889
>     exec(compile(script, scriptFile, 'exec'), d)
> SyntaxError: unqualified exec is not allowed in function 'executeScriptHelper' it contains a nested function with free variables
>
> ​Bizarre. ​

​It looks like the code should give this error
<http://stackoverflow.com/questions/4484872/in-python-why-doesnt-exec-work-in-a-function-with-a-subfunction>
​
​but I have never gotten it with on Windows 10 with:
Python 2.7.12, PyQt version 4.8.7

I'll fix this immediately.

Edward

**Comment by gatesphere** [comment]
Thanks Edward, current master works again on my machine.
