### ISSUE TITLE
g.cls should work on Linux

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#4104]
Thomas: the Linux shell command is `clear`.

See PR #4133.

**Comment by tbpassin** [comment]
What is this?  I don't find it in LeoPyRef.

**Comment by edreamleo** [comment]
@tbpassin Typo!  Should be `g.cls()`, defined in `leoGlobals.py`.

**Comment by tbpassin** [comment]
The Linux shell command is "clear".

**Comment by edreamleo** [comment]
Closed via PR #4133.
