### ISSUE TITLE
Remove 'restart-leo' command restrictions

### ISSUE THREAD

**Issue by ranvik14** [leo-editor/leo-editor#4109]
In this [thread](https://groups.google.com/g/leo-editor/c/xii7Zbkn_Y0) the restrictions are documented - and - confirmation has been given that this is not a Linux-specific issue.

**Comment by edreamleo** [comment]
I am going to close this issue. The `restart-leo` does exactly what it is supposed to do.

In particular, this command restarts Leo roughly as follows:
```python
os.chdir(g.app.initial_cwd)   # the cwd in effect when Leo started.
...
subprocess.run([sys.executable] + sys_args)
```
It is *not* the command's responsibility to do anything else.
