### ISSUE TITLE
Enhancement: allow cross-file chapters

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#411]
Create a new leo file - The nav_Qt <--> and [Chapters: 'main'] buttons are at the LHS of the buttons.
Create another new leo file - Only the [Chapters: 'main'] buttons are at the LHS of the buttons. The nav_Qt <--> buttons do not load.
Any new leo files created in this session will only load the [Chapters: 'main'] buttons.

If you restart leo the same pattern is observed.
This behaviour is confirmed running both default global and personal settings.

_Leo Log Window
Leo 5.4, build 20170213155242, Mon Feb 13 15:52:42 CST 2017
Git repo info: branch = master, commit = 0faa9a28c82d
Python 3.6.0, PyQt version 5.7.1
Windows 10 AMD64 (build 10.0.14393) SP0_

**Comment by edreamleo** [comment]
> Any new leo files created in this session will only load the [Chapters: 'main'] buttons.

That is the expected behavior.  Chapters are local to the outline containing them.

This could be called an enhancement request. I've changed the title accordingly.

At present, this is a low priority item.
