### ISSUE TITLE
qt_frames shows hundreds of mypy messages

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#4110]
In testing an upcoming PR, I ran mypy on qt_frames.py. It generated hundreds of messages.  This is true of devel - it is not related to my PR.  Many if not most of the messages are "[attr-defined]".   These are usually spurious because mypy isn't smart enough.  For example,

`g.app.gui.find_widget_by_name()` causes an "[attr-defined]" message despite the method actually existing.  In this case, pymy apparently doesn't know the type of g, or maybe of g.app.gui.  Without knowing its type, mypy can't know if there is such and attribute or method.

Fixing these should not be combined with any other PR - it would be very confusing and time-consuming to work through.  Since these changes have no immediate functional effect, and new PRs that affect qt_frame are coming immediately, I suggest that the addressing the mypy issues be postponed until after 6.8.2.

**Comment by edreamleo** [comment]
I am going to close this issue. These messages arose because of an environment issue.
