### ISSUE TITLE
Stickynotes> Tabula error

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#412]
I see this traceback running
Plugins- Stickynotes> Tabula

Leo Log Window
Leo 5.4, build 20170217113839, Fri Feb 17 11:38:39 CST 2017
Git repo info: branch = master, commit = ea642c970625
Python 3.6.0, PyQt version 5.8.0
Windows 10 AMD64 (build 10.0.14393) SP0
exception executing command
Traceback (most recent call last):
  File "N:\git\leo-editor\leo\core\leoCommands.py", line 5422, in doCommand
    val = command(event)
  File "N:\git\leo-editor\leo\plugins\stickynotes.py", line 539, in tabula_f
    t.add_note(p)
  File "N:\git\leo-editor\leo\plugins\stickynotes.py", line 608, in add_note
    sw.setAttribute(Qt.WA_DeleteOnClose, False)
AttributeError: module 'PyQt5.Qt' has no attribute 'WA_DeleteOnClose' #

**Comment by edreamleo** [comment]
Thanks for this report.  I have a note in my main test file saying that the stickynotes plugin is not ready for prime time. 

This plugin is low priority.  I am not going to get to this any time soon.

I would be willing to answer questions if you or anyone else would like to work on the plugin.

**Comment by LewisNeal** [comment]
All fixed with commit 331dbad.
Thanks

**Comment by edreamleo** [comment]
On Sun, Apr 23, 2017 at 5:34 PM, LewisNeal <notifications@github.com> wrote:

> All fixed with commit 331dbad
> <https://github.com/leo-editor/leo-editor/commit/331dbad2d2d0e5ec0217c85799650ebdd7864887>
> .
>

​Thanks for the feedback.

Edward
