### ISSUE TITLE
Do Not Scan For Local Settings For leoSettings.leo and myLeoSettings.leo

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#4122]
When an outline is opened, after the two settings files have been scanned for settings, the outline's own `@settings` tree is scanned for local settings.

When the outline is one of Leo's two settings files, this scanning for local settings finds all and only settings that have already been scanned. For each setting in the outline's local settings tree that replaces a setting from one of the settings outlines, a message is emitted.  Since every setting that is in one of these settings outline has already been scanned, this results in many spurious redefinition messages being generated.  

These spurious messages are not harmful, and the intended settings are not actually changed, but they are annoying.

Leo should omit the step of scanning an outline for local settings when the outline is one of (leoSettings.leo, myLeoSettings.leo).

**Comment by edreamleo** [comment]
@tbpassin I open `myLeoSettings.leo` and `LeoSettings.leo` frequently, either individually or from another `.leo` file. I do not see the behavior you describe.

**Comment by tbpassin** [comment]
I *think* it only happens when custom menus are defined in local settings trees. I don't always see these messages but sometimes there are more of them.  Here's one example:

`set over-riding setting: menus from C:/Tom/leo_projects/browser_bookmarks/browser_bookmarks.leo`

This outline builds a local menu starting with

`@menuat help before`

myLeoSettings.leo also defines a menu starting with a node with the same headline.

I thought these messages only happened when myLeoSettings.leo got opened.  That seems to be so but there is more to the story.

I just opened myLeoSettings.leo after Leo was already open.  Here are the messages about menus that were emitted:

```
createMenusFromConfigList no menu &Check Files
createMenusFromConfigList no menu &Text
createMenusFromConfigList no menu &Utilities
createMenusFromConfigList no menu Layouts
createMenusFromConfigList no menu &Local
```

Although the messages all say "no menu for...", those menus actually exist; they are defined in myLeoSettings.leo.

**Comment by edreamleo** [comment]
@tbpassin Please reopen this issue only if a) you know exactly how the messages arise and b) you know that the messages are incorrect.
