### ISSUE TITLE
Outline response slower than it used to be

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#4124]
Leo Log Window
Leo 6.8.2-devel, devel branch, build https://github.com/leo-editor/leo-editor/commit/ef8105daa3b97725ec658243bcba56ea7ad5c9a6
2024-10-22 11:02:35 -0500
Python 3.12.0, PyQt version 6.5.3
darwin

After git pull to ef8105daa3b97725ec658243bcba56ea7ad5c9a6

1. When I click on the outline with the mouse, the response is slower than it used to be.
2. Using the keyboard to navigate up and down the outline is slower than it used to be.

Then use Alt + 0 to show vr3，again use Alt + 0 hide vr3.  The outline turns to normal speed response.

**Comment by wangzhaohe** [comment]
I need to watch it for several days.

**Comment by tbpassin** [comment]
It sounds as if at startup, when VR3 gets created it's active even though it's not on view in any pane. So it's converting every node to RsT (or Asciidoc which would be even slower) even though it can't be seen. The toggle command makes sure it's not active when hidden so those unwanted conversions don't happen.

I will look at fixing this for the next VR3-related PR I submit.  One will be coming up soon, once the current layout  PR has been accepted. It will change the fore- and background- colors of the rendered output to match the current theme.

**Comment by wangzhaohe** [comment]
Thanks! Please let me known if the next VR3-related PR be accepted. I will try to test it.

**Comment by wangzhaohe** [comment]
Frist run command `vr3-freeze` when open a .leo file. It will be faster.

**Comment by tbpassin** [comment]
vr3.set_freeze() should be run when a VR3 instance is first created.  After that the vr3-toggle command makes sure to freeze when VR3 is toggled off. I'll fix that for the next PR of VR3.

You suggestion will work as a workaround, or you can just restore the layout.

**Comment by tbpassin** [comment]
Fixed in PR https://github.com/leo-editor/leo-editor/pull/4176, now in devel. Please close this issue after you satisfy yourself that the problem no longer happens.

**Comment by tbpassin** [comment]
Can we close this issue now?

**Comment by tbpassin** [comment]
Closed as completed.
