### ISSUE TITLE
Help: Is there a way to change Body's letter-spacing and line-height?

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#4125]
Leo Log Window
Leo 6.8.2-devel, devel branch, build ef8105daa3
2024-10-22 11:02:35 -0500
Python 3.12.0, PyQt version 6.5.3
darwin

In PyQt6,  It seems that the QTextEdit style sheet does not directly support the letter-spacing and line-height properties.

```
/* The body pane */
QTextEdit {
  background: @dark-base03;
  color: @text-foreground;
  font-family: @font-family-body;
  font-size: @font-size-body;
  font-weight: normal; /* normal,bold,100,..,900 */
  font-style: normal; /* normal,italic,oblique */
  padding-left: 3px;
  padding-top: 3px;
  padding-bottom: 3px;
  padding-right: 3px;
  height: 200%;
  letter-spacing: 0.5px; 
  line-height: 1.5; 
```

It takes no effect.

**Comment by tbpassin** [comment]
I'm not sure what theme file you are using, but it's better to refer to `LeoQTextBrowser` because that's what the body editor is.  `QTextEdit` is closely related and a stylesheet selector using that latter selector will work too, but I like to use the class name of the actual class being styled.

You don't have to work with the theme file, though.  Here's example code to change the editor styles on the fly.  Put it into a node and run with CTRL-B:

```
editor = c.frame.body.wrapper.widget
editor.setStyleSheet("""\
QTextBrowser {
    font-family: Corbel, Verdana, "Open Sans", Sans-serif; 
    font-size: 10.5pt;
}""")
```

To set it back to the theme's settings, use this:

`editor.setStyleSheet('')`

Actually, for setting the stylesheet on a specific component you can just use "*" instead of the widget's class name.

It's hard to find a definitive listing of supported CSS properties, but I just tried both line-height and letter-spacing and didn't see any difference.  BTW, for some properties you might have to use "pt" or "px" units.  "em" may not always work.

**Comment by tbpassin** [comment]
Here's what is supposed to be the CSS properties supported for a QTextEdit:

https://doc.qt.io/qt-6/richtext-html-subset.html

Line-height is listed there, but as I wrote, it doesn't actually change anything when I try it.

**Comment by wangzhaohe** [comment]
@tbpassin Thanks a lot for your help!

With the following code, letter spacing and line height both take effect.

```python
@language python
from PyQt6.QtGui import QFont, QTextCursor, QTextBlockFormat

editor = c.frame.body.wrapper.widget

# Get the current font and set font properties
font = editor.font()
font.setFamily("JetBrains Mono")
font.setPointSize(16)

# Set letter spacing as a percentage increase for each letter
font.setLetterSpacing(QFont.SpacingType.PercentageSpacing, 110)  # 110 means the letter spacing is 110% of the original

# Apply the font to the editor
editor.setFont(font)

# Set line spacing
cursor = editor.textCursor()
cursor.select(QTextCursor.SelectionType.Document)

# Create QTextBlockFormat and set line spacing
block_format = QTextBlockFormat()
block_format.setLineHeight(150, 1)  # Use 1 to represent FixedHeight type

# Apply to all text in the document
cursor.setBlockFormat(block_format)
editor.setTextCursor(cursor)
```

![ok](https://github.com/user-attachments/assets/efaf9719-9a7c-4044-8621-5d19b3f59408)



However, when clicking on other outlines, the letter spacing remains, but the line height does not stay; it goes back to the original line height.

![notok](https://github.com/user-attachments/assets/850bcb46-2837-464c-b065-95db04e5d00a)

**Comment by tbpassin** [comment]
> @tbpassin Is there a way to make the line height stay?

That was well done!  I don't know how to make that happen or why it doesn't stay.

You could turn the script into a command and execute it from a button. The  you could have the new spacing and height values whenever you want.

**Comment by tbpassin** [comment]
It might be possible to write a tiny plugin to make the changes.  It would register a callback with the "open1" hook so that it will change the font settings whenever an outline is opened.

**Comment by wangzhaohe** [comment]
> It might be possible to write a tiny plugin to make the changes. It would register a callback with the "open1" hook so that it will change the font settings whenever an outline is opened.

It is great! And with some config data in my-leo-settings.leo file.

**Comment by wangzhaohe** [comment]
I would like to learn how to write a Leo plugin. Is there any documentation available for reference?

**Comment by edreamleo** [comment]
Closing issue as complete.

**Comment by tbpassin** [comment]
Yes, in leodocs.leo in the section titled "Writing Plugins".   leodocs didn't open for me from the Help Menu, but you can open the leo file and navigate right to the right place with this UNL:

`unl:gnx://LeoDocs.leo#ekr.20060612103240`

Paste it into a node and CTRL-click on it.  BTW, reading this part of LeoDocs  is easier with VR3.  Select the top node of the section, open VR3, and from its "View Options" menu select "Entire Tree".

**Comment by wangzhaohe** [comment]
@tbpassin Thanks! I am starting to learn it step by step.

**Comment by tbpassin** [comment]
There are also some skeleton plugins and notes on writing them in LeoPyRef.leo:

unl:gnx://LeoPyRef.leo#ekr.20050303051035

These nodes are in the "Plugins" tree at Code-->Plugins-->Templates.

Really, your plugin will not need much machinery. You have to have an init() function at the module level that returns `True`.  This is needed by the plugins manager.

You do not need to have your plugin file in Leo's `leo/plugins`  directory. It can be placed anywhere on Python's sys.path.  If it's not in the plugins directory, then don't include the ".py" extension in the entry in your *enabled plugins* settings.  It will get imported as a module, as if you had used `python -m module_name`.

**Comment by tbpassin** [comment]
Try calling ` setUpdatesEnabled(False) `  on the editor widget before making your changes, then  `setUpdatesEnabled(True)` afterwards.  You probably won't need the timer if you do this.
