### ISSUE TITLE
[post draft] Leo with Jupyter(jupytext)

### ISSUE THREAD

**Issue by HaveF** [leo-editor/leo-editor#4131]
> This is just a rough draft, I just put it here because I thought it would be easier for Leonine to modify it.

> `@jupytext` feature is not release yet, but will be soon. https://github.com/leo-editor/leo-editor/pull/4135

Ever heard of the [Lindy Effect](https://en.wikipedia.org/wiki/Lindy_effect)? It says that the longer something non-perishable (like an idea or a technology) sticks around, the longer it’s likely to stay. Essentially, if something has lasted for a long time already, chances are it's here for the long haul. And that's exactly what’s happening with Leo Editor—or just Leo for short—a tool that Edward K. Ream has been developing for over 20 years. You’d think it might be outdated by now, right? But nope—Leo still feels full of life, fresh, and even groundbreaking. Although it is not so well known.

So what exactly is Leo Editor? Well, it's hard to compare it to anything. If your first thought is that it's just another IDE or text editor, think again—it's way more than that. Leo describes itself as a [PIM](https://en.wikipedia.org/wiki/Personal_information_manager), an [IDE](https://en.wikipedia.org/wiki/Integrated_development_environment), and an outliner all rolled into one. It helps programmers, authors, and web designers organize their work like never before. In Leo, outline nodes can exist in multiple places, letting you organize data in all sorts of creative ways.

Now, outlining is definitely a core feature of Leo, but it’s just scratching the surface. Imagine an editor that has the ability to program itself. Sounds wild, right? If you’ve used VS Code, you know there are a ton of plugins to add extra features. But with Leo, adding features can be as simple as writing a script directly in the editor. No need to learn an entire plugin system—just control the nodes, write a Python script, run it, and voila! You've got a new feature.

If you've used Jupyter notebooks, you might have a love-hate relationship with .ipynb files. They make it super easy to write code and see the results, but the JSON format can be tough to manage in version control (although GitHub does now offer some comparison tools for .ipynb files). That's where jupytext comes in—it lets you convert .ipynb files to a more version-control-friendly .py file format, and vice versa. Jupyter supports kernels beyond just Python, which means jupytext isn't limited to converting Python-based .ipynb files to .py. It also supports other kernels, such as Go with [gonb](https://github.com/janpfeifer/gonb), and many others that I won't go into here. Maybe you don't like Jupyter either, thinking it's not suitable for serious software development. Honestly, I'm not here to argue that—it really depends on your context. But there's no denying that it's a core tool in data science. If you haven't seen Jeremy Howard's (FastAI) video, I highly recommend checking it out: "[Someone told me not to use notebooks for 'serious' software development!](https://nbdev.fast.ai/getting_started.html#q-someone-told-me-not-to-use-notebooks-for-serious-software-development)" So far, so good, right?

Then one day, Edward K. Ream found a brilliant way to integrate jupytext with Leo. Essentially, you can store the text content(jupytext's output) of your notebooks directly in Leo, use Leo's powerful outlining capabilities to manage them, and when you save, Leo converts it right back to an `.ipynb`.

And this is huge. Imagine having a Jupyter notebook, let's call it A, that you're using for some kind of step-by-step workflow (in this case, let's say a machine learning example)—gathering data, cleaning data, training a model, and validating results. Now imagine you have another notebook, B, which follows a similar flow but isn't quite the same. The part where you clean the data (step 2) is identical. Without Leo, you'd need to copy all the relevant cells from A to B and hope nothing changes later. But if you update A, you also need to go back and manually update B. It’s a headache. Now imagine you have five similar notebooks. Ouch.

With Leo, this becomes a breeze. You make an edit to the cleaning part of one notebook, save it, and boom—every notebook that shares that content is automatically updated. Leo’s nodes can be cloned and reused—no fuss, no hassle. **That's block-level syncing**, and it's completely flexible. Honestly, it’s something you just won’t find in any other editor.(Btw, If you do this in the context of a Version Control Systems (VCS) like git, you will feel very safe and confident.)

![SCR-20241027-qqer](https://github.com/user-attachments/assets/e29d4b27-48d9-4006-ab94-d4e8276c2e79)

You might say, "But wait, isn’t it better to abstract repeated code into reusable modules?" Sure, in an ideal world, everything should be neatly abstracted. But when you’re in the early stages of experimentation, abstraction can feel like premature optimization—it just adds overhead. With Leo, you can reuse content with zero effort or cost and feel free to abstract later.

For example, in the screenshot above, `exp_A.ipynb` and `exp_B.ipynb` share some common code by coping in jupyter lab, but we are not sure whether we need to abstract this part into another module (there may be more files that need this part later, but we are not sure for now). When we are not sure whether to abstract this part of the code, let Leo be responsible for synchronizing the code in the two ipynb files(we still use jupyter lab to write code and conduct experiments, but use Leo's `@jupytext node` to organize all related ipynb files). Once we decide to abstract this part, we only need to change the code in one file directly (for example, this part is reduced to a simple function call), and then use Leo to synchronize the changes to all ipynb files.

You can understand it this way: Leo uses the characteristics of jupytext to achieve very powerful collaboration between ipynb files. Leo did not change the workflow we were used to, we just used its outline feature to enhance our process, manipulating sections between multiple ipynb files at once.

And just to make things sweeter, Thomas (another Leo contributor) added a rendering feature for jupytext files in Leo, so you can even see the rendered content directly within the tool.

So if you're using Jupyter, you should definitely give jupytext a try. If you’re using jupytext, try out Leo's @jupytext nodes. Even if you’re not using Jupyter, I’d say give Leo a shot. Sure, IDEs come and go—VS Code, JetBrains, Vim, you name it—but there’s really nothing quite like Leo in some aspects. I’m not suggesting you replace those editors with Leo, but rather, consider using Leo alongside them. It’s genuinely unique in this world. You can even try the javascript version of Leo in VS code -- [LeoJS](https://boltex.github.io/leojs/).

Yes, Leo does have a bit of a learning curve, but mastering the basics is easier than you’d think, and you’ll quickly be leveraging its outlining power. It’s the kind of investment that pays off big time. Leo is definitely an underrated gem.

Big thanks to Edward, Thomas, Felix boltex(Author of LeoJS and leointeg), and all the other contributors—you guys are truly amazing, and Leo is living proof of that!

**Comment by edreamleo** [comment]
@HaveF Many thanks for this documentation. It will be part of #4132.

**Comment by HaveF** [comment]
Hi, @mwouts
Edward has used your Jupytext and Leo features to deepen Jupytext's organization of ipynb.
I guess you may not have heard of Leo, but I think you can give it a try. I guess after you try it, you may want your Jupytext users to experience this convenience.

I am so happy that your Jupytext works with Leo. I hope you can experience this great experience soon.

**Comment by mwouts** [comment]
Hey @HaveF , thanks for reaching out! Yes I had a look at the above, that was an interesting read.

> You might say, "But wait, isn’t it better to abstract repeated code into reusable modules?" 

I would have said that exactly :wink: 

> Sure, in an ideal world, everything should be neatly abstracted. But when you’re in the early stages of experimentation, abstraction can feel like premature optimization—it just adds overhead. With Leo, you can reuse content with zero effort or cost and feel free to abstract later.

Yes that's fair and I would be curious to see how Leo handles that. Also let me know if you need anything from Jupytext - I guess you are aware of Jupytext's "sync" option already?

**Comment by HaveF** [comment]
@mwouts Thanks for your comments! I think you might be the first person to see this feature from a non-Leo perspective. This feature is going to be released in the next few days by Edward.

> I would be curious to see how Leo handles that. 

I think I may not have made it clear. For example, in the screenshot above, `exp_A.ipynb` and `exp_B.ipynb` share some common code by coping, but we are not sure whether we need to abstract this part into another module (there may be more files that need this part). When we are not sure whether to abstract this part of the code, let Leo be responsible for synchronizing the code in the two ipynb files(we still use jupyter lab to write code and conduct experiments, but use Leo's `@jupytext node` to organize all related ipynb files). Once we decide to abstract this part, we only need to change the code in one file directly, and then use Leo to synchronize the changes to all ipynb files.

You can understand it this way: Leo uses the characteristics of jupytext to achieve very powerful collaboration between ipynb files. Leo did not change the workflow we were used to, we just used its outline feature to enhance our process, manipulating sections between multiple ipynb files at once.

Did I make myself clear?

> I guess you are aware of Jupytext's "sync" option already?

Yes, I love jupytext ❤️. Works great for syncing a single ipynb and its corresponding py (or other type of file).

@edreamleo Edward, I'm glad that the author of jupytext responded to our content. He's a very enthusiastic guy! I contacted him before, and he and the author of gonb jointly supported the go notebook for jupytext. If you have any jupytext questions, I believe he has great insights

**Comment by edreamleo** [comment]
@HaveF @mwouts Hi, this is Edward, Leo's author.

Many thanks to the jupytext devs for their work. Without jupytext, Leo had no chance of working with .ipynb files. Once I learned about jupytext, a week of work fulfilled one of my ancient dreams.

Leo's `@jupytext` feature works like `@clean`. It is a thin wrapper around one **external file**. Such files are distinct from a Leo outline. Organizing .ipynb files within a Leo outline can be helpful for .ipynb files containing more than just a few cells.

The issue of sharing data pertains neither to the jupytext library nor to `@jupytext`.

You may try out `@jupytext` *now* from Leo's "devel" branch: https://github.com/leo-editor/leo-editor. This new feature will be a prominent part of Leo 6.8.2, coming this Friday, November 8.

**Comment by edreamleo** [comment]
I am going to close this issue. Rev 37e1cb2db includes this post in full in the acknowledgements and in a shorter form in the documentation for `@jupytext`. These writings will be part of Leo 6.8.2.

Thanks again to @HaveF.

**Comment by HaveF** [comment]
@edreamleo You're welcome. You did most of the heavy lifting and amazing work, and I should thank you!
