### ISSUE TITLE
Many Scripts In leo/scripts Will Not Work In Linux

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#4143]
Many scripts in leo/scripts contain a line:

`python = 'py' if isWindows else 'python'`

Most if not all Linux distros now use `python3`, not `python`. All these scripts should be updated if they are to be run on Linux.

**Comment by jknGH** [comment]
My incomplete impression on this is 'YMMV'. I have 'python' on Windows FWI, I have never used 'py' (it might also work...)

I wonder about having an environment variable to specify this? LEOPYTHON=python3 or whatever

**Comment by tbpassin** [comment]
YMMV, for sure.  I just discovered that on at least one of my Linux VMs, `python` is symlinked to `python3`.  I wonder how widespread that practice is.  I got gunshy about python3 vs python a few years ago when many distros still used python 2.x for system things even when python3.x was installed.  Those days are mostly (or entirely?) gone.

OTOH, the *version* of python 3 is likely to be up for grabs. My EndeavourOS VM is using 3.12.3, but my Mint VM is still using 3.8.10.

I think most if not all of these scripts could just use `sys.executable` for both platforms.

**Comment by tbpassin** [comment]
> I have 'python' on Windows FWI, I have never used 'py' (it might also work...)

Using `python` on Windows can be iffy.  On my Windows 10 system `python` runs 3.9.9 while `py` runs 3.12.3.  One nice thing about the `py` command:  it can run any installed version like this:

`py -3.10`

**Comment by edreamleo** [comment]
Or just add `alias py=python3` to your `.bashrc` file.
