### ISSUE TITLE
Freewin - Fix Cursor Behavior In Editing Mode

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#4151]
Somewhere along the line an unpleasant behavior has crept into the Freewin editor view. After typing any text or character, the cursor jumps back to the start of the page. The same happens when a block of text is pasted.

I have a 1-line fix and will submit a PR after some more testing.

**Comment by edreamleo** [comment]
@tbpassin Thanks for your testing, your report, and your upcoming PR.

**Comment by edreamleo** [comment]
Fixed via PR #4157.

**Comment by edreamleo** [comment]
@tbpassin pylint complained about a too-long line during my after-pull testing . Did you run pylint??

I fixed this complaint via rev ef52b6e.

Please pull from "devel" so you will have the latest code.

**Comment by edreamleo** [comment]
@tbpassin In the future, run *all* tests as if your life depended on them.

**Comment by tbpassin** [comment]
> Did you run pylint??

I ran full_test_leo.py. It runs ruff_leo in lieu of pylint:

```
for command in [
    fr'{python} -m "leo.scripts.beautify_all_leo',
    fr'{python} -m "leo.scripts.run_test_leo',
    fr'{python} -m "leo.scripts.mypy_leo',
    fr'{python} -m "leo.scripts.ruff_leo',
    # fr'{python} -m "leo.scripts.pylint_leo',
]
```

Since mypy gives different results when run from the minibuffer than when run in full_test.py, and you told me to use full_test and not the minibuffer for these tests, no I didn't run pylint.

**Comment by tbpassin** [comment]
> In the future, run _all_ tests as if your life depended on them.

I did what you told me to. You blew off the mypy-from-minibuffer messages I keep getting. full_test.py doesn't even run pylint any more. So why would I even consider running pylint from the minibuffer any more?

**Comment by edreamleo** [comment]
@tbpassin I don't suggest you run tests from the minibuffer. I run pylint from `pylint-leo.cmd`:

```console
@echo off

cd c:\Repos\leo-editor

echo pylint-leo.cmd
time /T
rem pylint checks that the rcfile exists.
rem call python -m leo.scripts.pylint_leo  --rcfile C:\Users\Dev\.leo\.pylintrc %*
call python -m leo.scripts.pylint_leo
time /T
```

Please do something similar.

**Comment by tbpassin** [comment]
```
C:\Tom\git\leo-editor\leo\scripts>pylint_leo.py
pylint_leo.py
The config file C:\Users\Dev\.leo\.pylintrc doesn't exist!
```

**Comment by edreamleo** [comment]
@tbpassin Think man. Modify the .cmd file for your environment.

**Comment by tbpassin** [comment]
I see that you hard-coded a path specific to your machine again. Gotta stop doing that!

**Comment by tbpassin** [comment]
> I see that you hard-coded a path specific to your machine again. Gotta stop doing that!

So the next pull might change the script again and re-apply the wrong path.  Fix the script already!

**Comment by edreamleo** [comment]
@tbpassin Thomas, `pylint-leo.cmd` is *my local script*.

That script won't break unless the path to `leo/scripts/pylint_leo.py` changes. That's never going to happen.

Clear?

**Comment by tbpassin** [comment]
pylint_leo.py is in LeoPyRef.leo. It's **not** just your local script. It happens that I do have a pylint-leo-rc.txt file in my .leo directory but who knows if it's the same as the one you use? If it isn't the same then running the edited script would be pointless for the purpose of blessing a PR.

To illustrate this point, I just reran pylint_leo.py after changing the rc path to the one in my .leo directory.  It didn't give any messages, and in particular there was no message about a line that was too long in freewin.py or anywhere else.

Bite the bullet, put the rc file you want everyone to use in leo/scripts or somewhere in the Leo repo - get it into the git repo and LeoPyRef.leo so it's source-controlled - and revise the pylint script to use it. You can even have the script use a command-line parameter to override the standard location so that the script could also be invoked with a different config file.

**Comment by tbpassin** [comment]
I just pulled from devel and found the too-long line.  I actually knew about it (not from pylint) and ignored it because it's in a docstring that will only ever be seen via VR/VR3. When rendered the line length will make no difference and will not affect the user.

**Comment by edreamleo** [comment]
@tbpassin Thomas, you have consistently *misread* my remarks. You can do better.

> pylint_leo.py is in LeoPyRef.leo. It's not just your local script. 

Correct, but `pylint-leo.cmd` *is* my local script:

- One has a `.py` extension and an underscore in its name.
- The other has a `.cmd` extension and a dash in its name.
