### ISSUE TITLE
windows-curses does not exist for Python 3.13

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#4155]
For now, I have removed the requirement from both `requirements.txt` and `pyproject.toml`.

A better solution: use [Uni-Curses](https://pypi.org/project/Uni-Curses/).

Closed in favor of #4214.

**Comment by tbpassin** [comment]
Maybe https://pypi.org/project/UniCurses/?

**Comment by edreamleo** [comment]
@tbpassin Thanks for the link. I'll give Unicurses a try.

**Comment by GiorgosXou** [comment]
@edreamleo You should try [Uni-Curses](https://pypi.org/project/Uni-Curses/), not [UniCurses](https://pypi.org/project/UniCurses/) <-- this one is totally outdated.

**Comment by edreamleo** [comment]
Closed in favor of #4214.
