### ISSUE TITLE
Use code-block throughout LeoDocs.leo

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#4161]
Use the following pattern throughout LeoDocs.leo to syntax color code snippets:
```
.. code-block:: python
  <indented code>
```

**Comment by tbpassin** [comment]
The pages are generated by sphinx, are they not?  Doesn't that automatically use pygments?

**Comment by edreamleo** [comment]
@tbpassin Good question. New markup is required. See [this page](https://sublime-and-sphinx-guide.readthedocs.io/en/latest/code_blocks.html).

**Comment by tbpassin** [comment]
That's nothing new.  I've been using `.. code-block::` for years,

**Comment by edreamleo** [comment]
@tbpassin Right. I guess I stopped using it when silvercity went missing. It will be good to have syntax coloring restored.

**Comment by edreamleo** [comment]
I am closing this issue as completed:

- `LeoDocs.leo` contained all the changes. It has been merged into devel.
- Using the ``make-sphinx`` button while in ``gh-pages`` branch generated all the ``.html`` files.
- The results have been pushed to Leo's website.
