### ISSUE TITLE
Complete reload-settings

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#417]
This is a continuation of #340, (reload-bindings). [This post](https://groups.google.com/d/msg/leo-editor/v4ycmSq4lE4/oIfwyMt-CwAJ) is an Engineering Notebook entry discussing **reload settings methods**, that is, methods whose names are `reloadSettings`.  Newer classes that follow PEP 8 alias reloadSettings to be reload_settings.

**This project is complete**

The reload-settings command reloads both abbreviations and style sheets.  There is a separate style-reload command, but no reload-abbreviations command.

The reload-settings command does the following:

1. Saves the outline if needed.  Not doing so is way too confusing.

2. Completely reloads the settings files and updates all settings dicts.

3. c.reloadConfigurableSettings calls the `reloadSettings` methods using c.subCommanders, c.configurables and several other official classes. All assignments to ivars from c.config.get* methods now take place in these reloadSettings methods.
  **Note**:c.initObjects creates all subcommanders and the c.subCommanders list.

4. Classes that are *not* subCommanders should start their reloadSettings method as follows: *No other registration is needed.*
```python
def reloadSettings(self):
    c = self.c
    if self not in c.configurables:
        c.configurables.append(self)
    # Code to re-init ivars using c.config.get* methods
```

**Comment by edreamleo** [comment]
A cff on the regex `self\.(.*)\=(.*)config\.get` matches 39 nodes in Leo's core and 18 nodes in leoPlugins.leo.

I envisage registering all methods that caches config ivars. The reload command would call such methods, in no particular order.

**Comment by edreamleo** [comment]
This script uses g.cmd_instance_dict to discover reload settings methods:
```python
g.cls()
d = {'c':c, 'g':g, 'k':c.k}
for key, aList in g.cmd_instance_dict.items():
    obj = None
    # print('%25s %s' % (key, aList))
    for ivar in aList:
        obj = d.get(ivar) if ivar in d else getattr(obj, ivar)
    assert key == obj.__class__.__name__, (key, obj.__class__.__name__)
    f = getattr(obj, 'reload_settings', None) or getattr(obj, 'reloadSettings', None)
    if f:
        print('found %s.%s' % (key, f.__name__))
```

**Comment by tbnorth** [comment]
On Mon, 13 Nov 2017 10:35:54 +0000 (UTC)
"Edward K. Ream" <notifications@github.com> wrote:

> A cff on the regex `self\.(.*)\=(.*)config\.get` matches 39 nodes in
> Leo's core and 18 nodes in leoPlugins.leo.
> 
> I envisage registering all methods that caches config ivars. The
> reload command would call such methods, in no particular order.

For the very few the actually need to.  I imagine almost all of them can
be replaced with direct calls to c.config.get*?  For those that must,
registering is a good idea.

**Comment by edreamleo** [comment]
On Mon, Nov 13, 2017 at 1:27 PM, Terry Brown <notifications@github.com>
wrote:

On Mon, 13 Nov 2017 10:35:54 +0000 (UTC)
> "Edward K. Ream" <notifications@github.com> wrote:
>
> > A cff on the regex `self\.(.*)\=(.*)config\.get` matches 39 nodes in
> > Leo's core and 18 nodes in leoPlugins.leo.
> >
> > I envisage registering all methods that caches config ivars. The
> > reload command would call such methods, in no particular order.
>
> For the very few the actually need to. I imagine almost all of them can
> be replaced with direct calls to c.config.get*? For those that must,
> registering is a good idea.
>

​My remarks were mistaken and I have updated the To do section as follows:

Reload settings methods should be created for most/all of the nodes found
by the cff command above. *No registration is needed*:
c.reloadSubcommanderSettings calls all reload settings methods in
subcommanders.

In other words, if a subcommander has a reload_settings or reloadSettings
method, that method will be called by the reload-settings command.
Furthermore, ctors can just call their reload settings method to init their
ivars.

​Testing on Python 3 has just shown that the select3 hook in the
attrib_edit_Controller class causes the updateEditorInt method to generate
Trying to create a QVariant instance of QMetaType messages.

Here is the trace:

reloading settings in AbbrevCommandsClass
init_tree_abbrev_helper calling c.selectPosition per-commander-plugin;;
init_tree_abbrev_helper calling c.selectPosition importer;;
Trying to create a QVariant instance of QMetaType::Void type, an invalid
QVariant will be constructed instead
init_tree_abbrev_helper calling c.selectPosition demo;;
Trying to create a QVariant instance of QMetaType::Void type, an invalid
QVariant will be constructed instead
Trying to create a QVariant instance of QMetaType::Void type, an invalid
QVariant will be constructed instead
init_tree_abbrev_helper calling c.selectPosition mdfile;;
Trying to create a QVariant instance of QMetaType::Void type, an invalid
QVariant will be constructed instead
Trying to create a QVariant instance of QMetaType::Void type, an invalid
QVariant will be constructed instead
Trying to create a QVariant instance of QMetaType::Void type, an invalid
QVariant will be constructed instead
Trying to create a QVariant instance of QMetaType::Void type, an invalid
QVariant will be constructed instead
Trying to create a QVariant instance of QMetaType::Void type, an invalid
QVariant will be constructed instead
Trying to create a QVariant instance of QMetaType::Void type, an invalid
QVariant will be constructed instead
Trying to create a QVariant instance of QMetaType::Void type, an invalid
QVariant will be constructed instead
reloading settings in LeoImportCommands
reloading settings in RstCommands
reloading settings in ShadowController
reloading settings in TangleCommands
reloading settings in StyleSheetManager

As you can see, first one message is generated, then two, then three...

Please look into this.

Edward

**Comment by tbnorth** [comment]
On Mon, 13 Nov 2017 21:09:54 +0000 (UTC)
"Edward K. Ream" <notifications@github.com> wrote:

> On Mon, Nov 13, 2017 at 1:27 PM, Terry Brown
> <notifications@github.com> wrote:
> 
> On Mon, 13 Nov 2017 10:35:54 +0000 (UTC)
> > "Edward K. Ream" <notifications@github.com> wrote:
> >
> > > A cff on the regex `self\.(.*)\=(.*)config\.get` matches 39 nodes
> > > in Leo's core and 18 nodes in leoPlugins.leo.
> > >
> > > I envisage registering all methods that caches config ivars. The
> > > reload command would call such methods, in no particular order.
> >
> > For the very few the actually need to. I imagine almost all of them
> > can be replaced with direct calls to c.config.get*? For those that
> > must, registering is a good idea.
> 
> ​My remarks were mistaken and I have updated the To do section as
> follows:
> 
> Reload settings methods should be created for most/all of the nodes
> found by the cff command above. *No registration is needed*:
> c.reloadSubcommanderSettings calls all reload settings methods in
> subcommanders.
> 
> In other words, if a subcommander has a reload_settings or
> reloadSettings method, that method will be called by the
> reload-settings command. Furthermore, ctors can just call their
> reload settings method to init their ivars.

So two questions:

 - is it not the case that most of the calls can be replaced with
   direct calls to c.config.get*?
 - what's a subcommander?  I think I can guess but I've never seen
   it as a formal concept before, and wonder how Leo can locate all the
   things that might fall into my gussed definition.

> ​Testing on Python 3 has just shown that the select3 hook in the
> attrib_edit_Controller class causes the updateEditorInt method to
> generate Trying to create a QVariant instance of QMetaType messages.

I'll have a look.

Cheers -Terry

> Here is the trace:
> 
> reloading settings in AbbrevCommandsClass
> init_tree_abbrev_helper calling c.selectPosition
> per-commander-plugin;; init_tree_abbrev_helper calling
> c.selectPosition importer;; Trying to create a QVariant instance of
> QMetaType::Void type, an invalid QVariant will be constructed instead
> init_tree_abbrev_helper calling c.selectPosition demo;;
> Trying to create a QVariant instance of QMetaType::Void type, an
> invalid QVariant will be constructed instead
> Trying to create a QVariant instance of QMetaType::Void type, an
> invalid QVariant will be constructed instead
> init_tree_abbrev_helper calling c.selectPosition mdfile;;
> Trying to create a QVariant instance of QMetaType::Void type, an
> invalid QVariant will be constructed instead
> Trying to create a QVariant instance of QMetaType::Void type, an
> invalid QVariant will be constructed instead
> Trying to create a QVariant instance of QMetaType::Void type, an
> invalid QVariant will be constructed instead
> Trying to create a QVariant instance of QMetaType::Void type, an
> invalid QVariant will be constructed instead
> Trying to create a QVariant instance of QMetaType::Void type, an
> invalid QVariant will be constructed instead
> Trying to create a QVariant instance of QMetaType::Void type, an
> invalid QVariant will be constructed instead
> Trying to create a QVariant instance of QMetaType::Void type, an
> invalid QVariant will be constructed instead
> reloading settings in LeoImportCommands
> reloading settings in RstCommands
> reloading settings in ShadowController
> reloading settings in TangleCommands
> reloading settings in StyleSheetManager
> 
> As you can see, first one message is generated, then two, then
> three...
> 
> Please look into this.
> 
> Edward

**Comment by tbnorth** [comment]
On Mon, 13 Nov 2017 15:40:25 -0600
Terry Brown <terrynbrown@gmail.com> wrote:

> > ​Testing on Python 3 has just shown that the select3 hook in the
> > attrib_edit_Controller class causes the updateEditorInt method to
> > generate Trying to create a QVariant instance of QMetaType
> > messages.  
> 
> I'll have a look.

How do you trigger it?  I'm not seeing it with:

Leo 5.6, build 20171113035523, Mon Nov 13 03:55:23 CST 2017
Git repo info: branch = tmp_master, commit = ec259ee38918
Python 3.5.2, PyQt version 5.5.1
linux
isPython3: True

(ignore the tmp_master thing, that's just while I wait for the unit
test issue to be resolved)

Cheers -Terry

**Comment by edreamleo** [comment]
On Mon, Nov 13, 2017 at 3:40 PM, Terry Brown <notifications@github.com>
wrote:


>
> So two questions:
>
> - is it not the case that most of the calls can be replaced with
> direct calls to c.config.get*?
>

​The reloadSettings (or reload_settings) method call c.config.get.

That is, these calls move from the ctor to the reloadSettings.
​

> - what's a subcommander? I think I can guess but I've never seen
> it as a formal concept before, and wonder how Leo can locate all the
> things
>

​It's way passed time you knew this ;-) It's really important that you
understand how Leo creates all the objects it does during startup.

c.initObjects instantiates a whole bunch of classes, after first importing
all the necessary modules.  Doing the imports in c.initObjects simplifies
matters.

c.initObjects populates the c.subCommanders list with all the
subcommanders.  So the answer to your question is, "the contents of
c.subCommanders".

Please have a look at c.initObjects.  You may want to create, say,
c.editPaneController as a subcommander. This might avoid problems involved
with imports at the top level.

Not all objects can be (or should be) subcommanders.  This includes the
following objects: g.app.pluginsController, c.frame, c.frame.body,
c.frame.log, c.frame.tree.

The (now slightly misnamed) c.reloadSubcommanderSettings is now:

def reloadSubcommanderSettings(self):
    '''
    Reload settings in all subcommanders that have either a
    reload_settings or reloadSettings method.
    '''
    trace = True and not g.unitTesting
    c = self
    classes = c.subCommanders[:]
    table = [
        g.app.pluginsController,
        c.frame, c.frame.body, c.frame.log, c.frame.tree,
    ]
    classes.extend([z for z in table if z])
    classes.sort(key=lambda obj: obj.__class__.__name__)
    for obj in classes:
        for ivar in ('reloadSettings', 'reload_settings'):
            func = getattr(obj, ivar, None)
            if func:
                # pylint: disable=not-callable
                if trace:
                    g.es_print('reloading settings in',
                        obj.__class__.__name__)
                func()

HTH.

Edward

**Comment by edreamleo** [comment]
On Mon, Nov 13, 2017 at 5:27 PM, Edward K. Ream <edreamleo@gmail.com> wrote:

​As of 36cd05c, ​the script:

    c.reloadSubcommanderSettings()

Produces this output (the trace is on in reloadSubcommanderSettings):

​reloading settings in AbbrevCommandsClass
reloading settings in AtFile
reloading settings in KillBufferCommandsClass
reloading settings in LeoFind
reloading settings in LeoImportCommands
reloading settings in LeoPluginsController
reloading settings in LeoQtBody
reloading settings in LeoQtFrame
reloading settings in LeoQtLog
reloading settings in LeoQtTree
reloading settings in PrintingController
reloading settings in RstCommands
reloading settings in ShadowController
reloading settings in SpellCommandsClass
reloading settings in StyleSheetManager
reloading settings in TangleCommands
reloading settings in Undoer

Edward

**Comment by tbnorth** [comment]
On Mon, 13 Nov 2017 23:27:59 +0000 (UTC)
"Edward K. Ream" <notifications@github.com> wrote:

> > So two questions:
> >
> > - is it not the case that most of the calls can be replaced with
> > direct calls to c.config.get*?
> 
> ​The reloadSettings (or reload_settings) method call c.config.get.
> 
> That is, these calls move from the ctor to the reloadSettings.

Right, but how many are cases like:

def __init__(self):
    self.default_format = c.config.getString("default-format")

when the caching is really not needed (c.config.get* has been tested
before and found to be fast enough for almost all applications, I
recall).  So instead of setting self.default_format in a reload
function, the code that actually uses self.default_format should just
use c.config.getString("default-format") directly instead, eliminating
self.default_format.

> > - what's a subcommander? I think I can guess but I've never seen
> > it as a formal concept before, and wonder how Leo can locate all the
> > things
> 
> ​It's way passed time you knew this ;-) It's really important that you
> understand how Leo creates all the objects it does during startup.

Ok :-), sort of what I thought.  I wonder if a more generic solution
might be to use a hook or signal that anything can subscribe / connect
to.

Cheers -Terry

**Comment by edreamleo** [comment]
On Mon, Nov 13, 2017 at 10:30 PM, Terry Brown <notifications@github.com>
wrote:

> That is, these calls move from the ctor to the reloadSettings.
>
> Right, but how many are cases like:
>
> def __init__(self):
> ​    ​
> self.default_format = c.config.getString("default-format")
>
> when the caching is really not needed


​Excellent question. I had forgotten
​that not caching was even an option.


There are about a dozen new reloadSettings methods.  Each could, in theory,
be eliminated by using c.config.get* methods throughout the class's code.
In practice, replacing all config-related ivars would be error prone. So
for now the localized solution appears simpler and safer.

​Today's work will involve reloading more "interesting" settings, of two
kinds:

1. Colorizer settings can be handled by making reloadSubcommanderSettings
aware of c.frame.body.colorizer and c.frame.body.colorizer.highlighter. The
reloadSettings methods for these classes may have to call some kind of init
methods to update subsidiary settings.

2. Similarly, Leo's widget classes require more work.  It's not enough just
to update widget-related settings.  The widgets themselves must be
updated--their color, font or other attributes.  This is where the
reloadSettings methods will be most useful.

The pattern is to call the reloadSettings both from the ctor and the
reload-settings command, so these methods must check that the widgets
actually exist.  Doing so avoids having to use finishCreate methods.

Edward

**Comment by edreamleo** [comment]
d159469 completes this project.  See the opening comment in this issue for a complete summary of this project.

Amazingly, DynamicWindow.reloadSettings is the *only* code that contains code that updates the gui.

You can test it out by toggling the value of @bool show_iconbar and then doing reload-settings.

Presumably the style-sheet manager handles all other gui-related settings.
