### ISSUE TITLE
Freewin message

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#4184]
On any node the z-open-freewin command opens the FW window and this message appears in log pane:
        _body, th, td, pre.literal-block, pre.doctest-block,
pre.math, pre.code, blockquote, div.topic, blockquote > table,
div.topic > table, blockquote p.attribution,
div.topic p.attribution {
color: #b8cac8;
background: #202020;
}_

Subsequent z-open-freewin commands on the node do not give the message.
Change to another node. Again, the first z-open-freewin command gives the message but subsequent commands do not.

Leo 6.8.3-devel, build 9862614477
Python 3.12.7, PyQt version 6.7.3
Windows 10 AMD64 (build 10.0.19045)

**Comment by tbpassin** [comment]
Sounds like I forgot to take out a diagnostic message.  I'll chase it down pronto .. though I haven't noticed it myself yet.

It would only happen once on a node because even if you close the window it's still there waiting to be made visible again.

**Comment by tbpassin** [comment]
That's what it was, harmless but annoying. I've filed a PR for the fix.
