### ISSUE TITLE
execute-script should require selected text unless @language python is in effect

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#4193]
See PR #4197.

`Ctrl-B` should execute text in languages other than python only there is *explicitly selected* text.

For example, executing all markdown text will almost always throw a SyntaxError.

**Comment by tbpassin** [comment]
The ability of the command to execute selected lines with Python is handy and I hope we won't lose it.

**Comment by edreamleo** [comment]
Fixed via PR #4197.
