### ISSUE TITLE
runLeo.py can run different versions of Leo depending on how it is invoked.

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#4199]
Context: The working directory is the leo-editor directory in my git clone of Leo. The checked-out branch is based on 6.8.3 devel. I want to run the git version of Leo. The latest installed version of Python is 3.12.3. The OS is a recent update to Windows 10.

Run Method 1 (runs the intended version of Leo):
```
C:\Tom\git\leo-editor>py -m leo.core.runLeo %USERPROFILE%\.leo\workbook.leo
Leo 6.8.3-devel, tbp-restart branch, build 804a840d59
Python 3.12.3, PyQt version 6.7.3
```

Run Method 2 (runs the wrong version (the pip-installed version) of Leo):
```
C:\Tom\git\leo-editor>%LOCALAPPDATA%\Programs\Python\Python312\python.exe  leo\core\runLeo.py %USERPROFILE%\.leo\workbook.leo
Leo 6.8.1
Python 3.12.3, PyQt version 6.7.3
```

Run Method 3 should give the same result as Method 2 but runs a different version of python (!):
```
C:\Tom\git\leo-editor>py leo\core\runLeo.py %USERPROFILE%\.leo\workbook.leo
Leo 6.8.1
Python 3.9.9, PyQt version 6.6.2
```

Method 3 could happen if runLeo.py relaunches with plain "python.exe" because on my system, "python.exe" is linked to python3.9.9.  If this does indeed happen, it is another bug. On Windows, you cannot assume that "python.exe" will run the version you want.

The apparent restart-leo bug seems to be caused by this problem.

**Comment by edreamleo** [comment]
@tbpassin Thanks Thomas. At last we are making progress.

I would like to fix this issue.

**Comment by edreamleo** [comment]
I am going to close this issue. Two posts explain why:

The [first](https://groups.google.com/g/leo-editor/c/xii7Zbkn_Y0/m/AfNEyh3ZCgAJ) post shows that everything works as expected on my machine.

The [second](https://groups.google.com/g/leo-editor/c/xii7Zbkn_Y0/m/zvlfe9HjCgAJ) post shows that using the python launcher (`py`) is the likely cause of the confusion.

I'll reopen this issue only if a new PR fixes `runLeo.py` or the `restart-leo` command. As explained [here](https://groups.google.com/g/leo-editor/c/xii7Zbkn_Y0/m/_ODSgpfQCgAJ), these two are too simple to expect bugs.
