### ISSUE TITLE
viewrendered does not render some nodes

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#420]
Viewrendered does not always render a node. To reproduce open LeoDocs.leo#*** Leo and org mode

open a vr window and select nodes in order:
 Introduction
 What is Leo
 Consider using Leo if...
 Underlying technologies     <=== this node does not render, it's blank
 Leo as a compendium
 ...
 [snip]

You can see that nodes are rendered in the vr pane, except for the 'Underlying technologies' node.
I have noticed this behaviour before in some of my own files and have simply attributed it to @ language directives etc.
But here in LeoDocs.leo the @setting default _@string target_language = rest_ covers all the nodes. And I can't see any reason why. I even tried 'show invisibles'

** isPython3: True
Leo 5.4, build 20170224065006, Fri Feb 24 06:50:06 CST 2017
Git repo info: branch = master, commit = e3910ae85d16
Python 3.6.0, PyQt version 5.8.0
Windows 10 AMD64 (build 10.0.14393) SP0
reading settings in N:\git\leo-editor\leo\doc\LeoDocs.leo

**Comment by edreamleo** [comment]
On Fri, Feb 24, 2017 at 8:06 AM, LewisNeal <notifications@github.com> wrote:

> Viewrendered does not always render a node.
>
​That's on purpose, usually ;-)​ If you want VR to render a node, make sure
@language rest is in effect.  Or markdown, or md.

Edward

**Comment by LewisNeal** [comment]
But the default @string target_language = rest
sets this and so nodes render as rest. However that one node 'Underlying technologies' remains blank in the render pane.
Did you try to reproduce as I described?

**Comment by edreamleo** [comment]
On Fri, Feb 24, 2017 at 8:50 AM, LewisNeal <notifications@github.com> wrote:

> But the default @string <https://github.com/string> target_language = rest
> sets this and so nodes render as rest. However that one node 'Underlying
> technologies' remains blank in the render pane.
> Did you try to reproduce as I described?
>
​Yes.  That particular node has multiple @language directives. ​

​You could say this is a recent change. To activate the VR pane, make sure
@language rest is the first directive.

Edward

**Comment by LewisNeal** [comment]
You may be right, but it still feels wrong to me though. As Leo is written in python, it should be the easiest to work with.
Consider the Doc_party.leo file attached: You can see that Node A does not render in a VR pane. The presence of '@language python' in the body text causes the rendering to fail. The other nodes B and C are fine, contain python code, and render as expected.

I see that in LeoDocs you have added a '@language rest' directive to compensate for the node containing '@language python'. The other nodes don't need that special treatment.

When Leo 5.5 is challenging Org-mode it will be need to be smooth, and seamless to use. Minor UI issues like this may well detract from that feel.

[Doc_party.txt](https://github.com/leo-editor/leo-editor/files/801049/Doc_party.txt)

**Comment by edreamleo** [comment]
On Sat, Feb 25, 2017 at 3:05 AM, LewisNeal <notifications@github.com> wrote:

> You may be right, but it still feels wrong to me though. As Leo is written
> in python, it should be the easiest to work with.
>
​I'm convinced. The behavior you described is relatively new.  I'll revert
to the old behavior today.

Edward

**Comment by edreamleo** [comment]
On Sat, Feb 25, 2017 at 7:36 AM, Edward K. Ream <edreamleo@gmail.com> wrote:

On Sat, Feb 25, 2017 at 3:05 AM, LewisNeal <notifications@github.com> wrote:
>
>> You may be right, but it still feels wrong to me though. As Leo is
>> written in python, it should be the easiest to work with.
>>
> ​I'm convinced. The behavior you described is relatively new.  I'll revert
> to the old behavior today.
>

​Done at a17f1d3.

EKR

**Comment by LewisNeal** [comment]
Working fine now, thank you for the fix.
Lewis
