### ISSUE TITLE
Outdated ToDo plugin documentation

### ISSUE THREAD

**Issue by xgid** [leo-editor/leo-editor#421]
While trying to use the **todo.py** plugin, I've found that the link present at the [plugins page](http://leoeditor.com/plugins.html#todo-py) that's supposed to point to the [Full docs](http://leo.zwiki.org/tododoc.html) of the plugin is giving an:
```text
I could not find any likely page matching "tododoc.html" 
```

Could someone point me to the right URL? Could someone update the **pluguins page**?

**Comment by LewisNeal** [comment]
The link is http://leo.zwiki.org/Tododoc (without .html)

I found this by the Leo menu Plugins> todo> About

**Comment by edreamleo** [comment]
@xgid My apologies for all the problems you are having with the docs.  The [docs for the todo plugin](http://leoeditor.com/plugins.html#todo-py) now have the correct link.

@LewisNeal Thanks for finding the correct link.

**Comment by xgid** [comment]
@LewisNeal Thanks for your fast answer with the link! Now I'm gonna try to understand how does that plugin work...

@edreamleo Thanks for your fast fix!
