### ISSUE TITLE
LeoDocs page on LeoJS Needs To Be Updated

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#4217]
The page is [A web viewer page for .leo files](https://leo-editor.github.io/leo-editor/load-leo.html).

Currently the page reads:

> Coming soon: the [leoJS](https://github.com/boltex/leojs) plugin for [vs-code](https://code.visualstudio.com/) will bring all of Leo to vs-code.
> 
> Right now you can run vs-code in your browser with [vscode.dev](https://vscode.dev/) (Edge or Chrome only).
> 
> When leoJS becomes available later this summer you'll be able to browse, edit, and save your Leo outlines directly in your browser!

This greatly short-changes LeoJS!

**Comment by edreamleo** [comment]
Fixed via PR #4222.
