### ISSUE TITLE
Error when opening the help

### ISSUE THREAD

**Issue by xgid** [leo-editor/leo-editor#422]
With the current version of Leo, when I open the help page (F1), the following error is shown at the Log Pane (before the "**Welcome to Leo's help system.**" and rest of the help is shown, also at the Log Pane):

```text
loadOnePlugin: error importing plugin: leo.plugins.viewrendered3Traceback (most recent call last):
  File "C:\dev\Leo-5.4\leo\core\leoPlugins.py", line 501, in loadOnePlugin
    __import__(moduleName)
ImportError: No module named 'leo.plugins.viewrendered3'
loadOnePlugin: can not load enabled plugin: leo.plugins.viewrendered3
```

My current Leo version:
```text
Leo 5.4, build 20170224165051, Fri Feb 24 16:50:51 CST 2017
Git repo info: branch = master, commit = b710c488b6c1
Python 3.5.2, PyQt version 5.6.0
Windows 10 AMD64 (build 10.0.14393) SP0
```

**Comment by xgid** [comment]
Just to clarify: I have **not** included by myself any "**viewrendered3.py**" in an @enabled-plugins node nor anything else of that kind. 

What I can see is the line "**viewrendered.py**" uncommented at the @enabled-plugins node of the `leoSettings.leo` file, as expected.

**Comment by edreamleo** [comment]
On Fri, Feb 24, 2017 at 10:57 PM, XGiD <notifications@github.com> wrote:

> With the current version of Leo, when I open the help page (F1), the
> following error is shown at the Log Pane (before the "*Welcome to Leo's
> help system.*" and rest of the help is shown, also at the Log Pane):
>
> loadOnePlugin: error importing plugin: leo.plugins.viewrendered3Traceback (most recent call last):
>   File "C:\dev\Leo-5.4\leo\core\leoPlugins.py", line 501, in loadOnePlugin
>     __import__(moduleName)
> ImportError: No module named 'leo.plugins.viewrendered3'
> loadOnePlugin: can not load enabled plugin: leo.plugins.viewrendered3
>
> ​Thanks for this report.  Fixed at 4b16123.

Edward

**Comment by edreamleo** [comment]
On Fri, Feb 24, 2017 at 11:02 PM, XGiD <notifications@github.com> wrote:

> Just to clarify: I have *not* included by myself any "*viewrendered3.py*"
> in an @enabled-plugins node nor anything else of that kind.
>
> What I can see is the line "*viewrendered.py*" uncommented at the
> @enabled-plugins node of the leoSettings.leo file, as expected.
>
​The only way to have gotten this message is to have used an
@enabled-plugins node in myLeoSettings.leo that enabled no viewrendered
plugin at all.​

Still, it's an embarrassing bug.  I'm glad you found it.

Edward

**Comment by xgid** [comment]
> ​The only way to have gotten this message is to have used an @enabled-plugins node in myLeoSettings.leo that enabled no viewrendered plugin at all.​

OK, now I've come to understand the explanation at `leoSettings.leo#About this file, leoSettings.leo-->\@enabled-plugins` thanks to your tip. The previous two times I read it, it's clear that I did not *fully* understand it.

The first part that confused me was this one:
```text
If x.leo contains no @enabled-plugins node, you could put an empty @enabled-plugins node in myLeoSettings.leo.
```
I thought that the "@enabled-plugins node in myLeoSettings.leo" **had to be empty** to disable all the plugins present at leoSettings.leo. There's nothing there stating that "_whenever you put an @enabled-plugins node at myLeoSettings.leo (or at x.leo), its contents **overrides** all that was previously set at the @enabled-plugins node in leoSettings.leo_".

I think the problem is that the explanation talks about @enabled-plugins nodes at x.leo, y.leo and myLeoSettings.leo, but says nothing about leoSettings.leo node contents.

Now I think I got it! Thanks.

**Comment by edreamleo** [comment]
​​On Sat, Feb 25, 2017 at 2:57 PM, XGiD <notifications@github.com> wrote:

​> ​
There's nothing there stating that "*whenever you put an @enabled-plugins
node at myLeoSettings.leo (or at x.leo), its contents overrides all that
was previously set at the @enabled-plugins node in leoSettings.leo*".
​​

​Good catch.  Furthermore, @enabled-plugins nodes in "local" .leo files
only *add* to the enabled plugins in myLeoSettings.leo.

I'll add language to this effect in several places.

Edward
