### ISSUE TITLE
Is meta an essential requirement for leo? (it seems broken on python-3.12)

### ISSUE THREAD

**Issue by brobr** [leo-editor/leo-editor#4229]
Hi after upgrading leo in Slackware64-current (python-3.12) to 6.8.2; the log shows an error.
```
..
  File "/usr/lib/python3.12/site-packages/meta/decompiler/instructions.py", line 9, in <module>
    from meta.decompiler.control_flow_instructions import CtrlFlowInstructions

  File "/usr/lib/python3.12/site-packages/meta/decompiler/control_flow_instructions.py", line 15, in <module>
    JUMP_OPS = [opcode.opmap[name] for name in JUMPS]
                ~~~~~~~~~~~~^^^^^^

KeyError: 'JUMP_IF_FALSE_OR_POP'
```

This error is linked to the dependency 'meta'; also reproduced with the example snippet of meta on pypi.org (https://pypi.org/project/meta/) and could relate to a list-comprehension issue: https://github.com/srossross/Meta/issues/42. 

Same fault obtained in a clean virtual env with a pip-install of leo, incorporating the following modules:

> Installing collected packages: tk, snowballstemmer, PyQt6-WebEngineSubwheel-Qt6, PyQt6-Qt6, pscript, nh3, meta, fastjsonschema, dialite, webruntime, urllib3, typing-extensions, types-six, types-PyYAML, types-Markdown, types-docutils, traitlets, tornado, tomlkit, sphinxcontrib-serializinghtml, sphinxcontrib-qthelp, sphinxcontrib-jsmath, sphinxcontrib-htmlhelp, sphinxcontrib-devhelp, sphinxcontrib-applehelp, soupsieve, six, ruff, rpds-py, rfc3986, pyyaml, PyQt6-WebEngine-Qt6, PyQt6-sip, pyproject_hooks, pyparsing, Pygments, pyflakes, pyenchant, pycparser, pluggy, platformdirs, pkginfo, pillow, pathspec, parso, packaging, numpy, mypy-extensions, more-itertools, mdurl, mccabe, MarkupSafe, markdown, kiwisolver, jeepney, jaraco.context, isort, iniconfig, imagesize, idna, fonttools, docutils, dill, cycler, coverage, click, charset-normalizer, certifi, babel, attrs, asttokens, astroid, alabaster, types-requests, requests, referencing, readme-renderer, python-dateutil, pytest, PyQt6, pylint, mypy, markdown-it-py, jupyter-core, Jinja2, jedi, jaraco.functools, jaraco.classes, flexx, contourpy, cffi, build, black, beautifulsoup4, sphinx, rich, requests-toolbelt, pytest-cov, PyQt6-WebEngine, PyQt6-QScintilla, mdit-py-plugins, matplotlib, jsonschema-specifications, cryptography, types-paramiko, SecretStorage, jsonschema, nbformat, keyring, twine, jupytext, leo

**Comment by tbpassin** [comment]
The meta import is only used by the livecode plugin as far as I can see.  I've never used that plugin.

**Comment by tbpassin** [comment]
The error in the VR pane isn't from livecode or the meta package, though, it's from docutils which is trying to deal with incorrect syntax (the block that should have been indented but wasn't).  I don't know how livecode would be able to execute code that's in an RsT block.  Viewrendered3 can, though.

**Comment by tbpassin** [comment]
> It is likely a slackware issue

No, I get the same error on Windows 3.12.3. It will only happen if the livecode plugin is enabled.

> making documentation with sphinx 

Leo is really good for this, BTW.

**Comment by edreamleo** [comment]
@tbpassin Thanks for your testing. #4233 suggests removing meta from Leo's requirements files.

**Comment by edreamleo** [comment]
@brobr The livecode plugin isn't representative of Leo as a whole. I never use it. Instead I use Python's breakpoint statement.

**Comment by edreamleo** [comment]
@brobr The livecode plugin isn't representative of Leo as a whole. I never use it. Instead I use Python's breakpoint statement.
