### ISSUE TITLE
Simplify key handling with a better KeyStroke class

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#423]
​These are the first new ideas I've had about key handling in over 20 years. They were stimulated by [this discussion](https://groups.google.com/forum/#!msg/leo-editor/GVhSNoMEUcU/G6CWjcatCwAJ).

**Status**

This project is now complete.  No further work is planned, except for bug fixes.

Remarkably, the only major changes are to:

- LeoQtEventFilter.eventFilter (and helpers).
- The KeyStroke class.
- k.masterKeyHandler.

**Details**

The crucial eventFilter method has collapsed in complexity. This is a huge step forward.

The g.KeyStroke class now contains ks.finalize, which sets ks.s to **canonical form**.  ks.finalize contains the dicts that used to found throughout leoKeys.py. This clarifies the code significantly. **Non-canonical settings strings no longer exist**.

ks.__hash__ and the KeyStroke rich comparison methods guarantee that all "equivalent" KeyStroke objects will hash to the same key in any dict.

k.masterKeyHandler has been refactored using several new methods. The top-level code is now straightforward.  No real changes have been made to helpers, but new consistency checks are in place.

**Comment by jknGH** [comment]
Hi Edward
    This is a really interesting area for you to be re-looking, to me ;-)
In a tangential area, can I remind you of this related request from some years ago:

    [https://groups.google.com/d/msg/leo-editor/Tz_HUo7VWkc/FJCsBf9tmn8J]
    "can I specify key bindings using the Numeric keypad keys?"

I raised a wishlist item at the time, but I think this would have been in Launchpad and I am not sure how these have been carried forward to Github.

    Thanks muchly
    Jon N

**Comment by edreamleo** [comment]
On Sun, Feb 26, 2017 at 3:35 PM, jknGH <notifications@github.com> wrote:

> Hi Edward
> This is a really interesting area for you to be re-looking, to me ;-)
> In a tangential area, can I remind you of this related request from some
> years ago:
>
> [https://groups.google.com/d/msg/leo-editor/Tz_HUo7VWkc/FJCsBf9tmn8J]
> "can I specify key bindings using the Numeric keypad keys?"
>
> I raised a wishlist item at the time, but I think this would have been in
> Launchpad and I am not sure how these have been carried forward to Github.
>
​It depends on whether Qt key events can distinguish between keypad keys.
I'll look into this when I start this project.

Edward

**Comment by edreamleo** [comment]
I am going to close this issue now, rather than waiting to merge "keys2" into "devel".

Please reopen if any problems arise.
