### ISSUE TITLE
Broken links in Webpage https://leo-editor.github.io/leo-editor/tutorial-rst3.html

### ISSUE THREAD

**Issue by viki-t-s** [leo-editor/leo-editor#4235]
Fixed via PR #4242.

The above webpage has two broken links to sphinx-doc.org. Please replace the website from http://sphinx-doc.org/ to https://www.sphinx-doc.org/ in the following two places.

In first paragraph,
or [Sphinx](http://sphinx-doc.org/) markup to HTML, PDF, ..

and in the second paragraph
For full information about Sphinx, please read the [Sphinx documentation](http://sphinx-doc.org/contents.html).

**Comment by edreamleo** [comment]
@viki-t-s Thanks for your report. LeoDocs.leo has a button that is supposed to find broken links.  I'll investigate.

**Comment by edreamleo** [comment]
Fixed via PR #4242.

Mystery solved: `find-bad-links` script should be run *after* generating the new files.

**Comment by edreamleo** [comment]
Fixed via PR #4242.

Mystery solved: `find-bad-links` script should be run *after* generating the new files.
