### ISSUE TITLE
Issue with log pane when executing scripts

### ISSUE THREAD

**Issue by viki-t-s** [leo-editor/leo-editor#4236]
Fixed via PR #4238.

I am using the latest version of Leo 6.8.3

As per leo quickstart guide when executing a script with ctrl+b, it should do two things:
1. display list of nodes that have a headline starting with @ in the log pane.
2. Append the summary as a new node under itself.

When I tried out, Action 2 happened but not Action 1. 

![2024-12-06_15-58-25](https://github.com/user-attachments/assets/203d9b5f-247d-49fe-9600-13170781bf3c)

**Comment by edreamleo** [comment]
@viki-t-s Thanks for this report. I had forgotten that `quickstart.leo` exists!

To print the expected text to the log pane, insert a call to `g.es(n.h)`. Like this:
```
for n in nodes:
    # .b gets the body text, .h is headline
    body = n.b
    res.append("- " + n.h)
    res.append("   " + str(body.count('\n')) + " lines")
    g.es(n.h)  # <---
```
I'll update quickstart Leo accordingly.

**Comment by edreamleo** [comment]
See PR #4238.
