### ISSUE TITLE
Support LaTex rendering in VR plugin

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#4239]
Consider using the [latex-render](https://pypi.org/project/latex-render/) or [pandoc](https://pandoc.org/) packages.

**Comment by tbpassin** [comment]
1. It appears to possibly convert equations, not arbitrary markdown content, to LaTeX. 
2. It supposedly can use either of two on-line providers for the conversion, but one of the cited URLs no longer exists.

pandocs can produce LaTeX from markdown; that would probably be a better solution.

**Comment by edreamleo** [comment]
@tbpassin Thanks for your comment. I'll look into pandocs.

**Comment by tbpassin** [comment]
https://pandoc.org/

I sometimes use pandoc so I can write drafts of Libreoffice documents in Leo. It's much better than trying to write them in the word processsor.

**Comment by edreamleo** [comment]
@tbpassin Good to know. I'm revising my workflow substantially these days.

**Comment by tbpassin** [comment]
To be more definite, I write the draft in markdown, and use pandoc to convert that to LibreOffice format.  I can use VR3 to see what the MD looks like as I work on it.

I don't know how it could be round-tripped, though.  You could have pandoc convert the LibreOffice document to markdown, but you would lose the original structure it had in Leo.  And you might lose important word processor formatting too, such as page headers.

**Comment by tbpassin** [comment]
Here's a script I used to convert an md file to LibreOffice with pandoc.   The md file to be converted was _off-server-database.md_.  I created a LO template for the .odt output file:

```
@language python
# see https://opensource.com/article/19/5/convert-markdown-to-word-pandoc
import subprocess
cmd = ['pandoc', '-t', 'odt', r'off-server-database.md',
        '--reference-doc=base-template.ott',
        '-o', r'off-server-database.odt']
cmd = ' '.join(cmd)
subprocess.run(cmd, shell = True)
```

This script is fairly old.  If I were to do it again I probably wouldn't join `cmd` into one string.

**Comment by edreamleo** [comment]
@tbpassin I am going to close this issue. The [overleaf](https://www.overleaf.com) online editor and renderer is far superior to my dreams for the VR plugin.
