### ISSUE TITLE
rst importer ignores titles with ' as underline character

### ISSUE THREAD

**Issue by RagBlufThim** [leo-editor/leo-editor#424]
When reading a rst file (@auto filename.rst) that contains a title with ``'`` as underline character, that title is not turned into a node.
Instead the title including underlining '''' becomes part of the body of the previous (non-') title.

``'`` titles used to work some time ago.

Looking into it I found at lines 11 to 13 of ``leo\plugins\importers\leo_rst.py``:

    # Used by writers.leo_rst as well as in this file.
    underlines = '*=-^~"+!$%&(),./:;<>?@[\\]_`{|}#'
        # All valid rst underlines, with '#' *last*, so it is effectively reserved.

This used to be:

    # Used by writers.leo_rst as well as in this file.
    underlines = "!\"$%&'()*+,-./:;<=>?@[\\]^_`{|}~#"
        # All valid rst underlines, with '#' *last*, so it is effectively reserved.

The change occurred around 4th of February. The characters were reordered, and in the process the ``'`` was dropped - probably unintentionally.

According to http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#sections ``'`` is a valid section title adornment character, it's even in the list of recommended characters.

If I add the ``'`` to the ``underlines`` (escaped by ``\`` as the string is delimited by ``'``), it works again.

Cheers  
r..m

**Comment by edreamleo** [comment]
Thanks for the clear report.  Fixed at 8be0a3b.
