### ISSUE TITLE
Use show-buttons command to show sources of each @button or @command node

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#4245]
See PR #4251.

There is no need to change the `show-commands` command. The existing `show-buttons` command suffices!

**Comment by tbpassin** [comment]
This sounds related to https://github.com/leo-editor/leo-editor/issues/3236.

**Comment by edreamleo** [comment]
@tbpassin Yes, I think these two commands are related, but I'm not sure that will help @3236.

**Comment by edreamleo** [comment]
Closed via PR #4251.
