### ISSUE TITLE
Allow VR and VR3 to be visible simultaneously

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#4246]
This might be possible for some layouts, but it is not yet true for the legacy layout.

**Comment by tbpassin** [comment]
One way to accomplish this using the Layout data structure is to provide a splitter position for each.  Currently the standard layouts use a placeholder _VRX_PLACEHOLDER_NAME_. When the layout is applied, the placeholder is replaced with one of 
```
VR_MODULE_NAME = 'viewrendered.py'
VR3_MODULE_NAME = 'viewrendered3.py'
```
depending on whether VR3 has been enabled or not. Instead, a place could be provided for each.  We would have to try it out but it should work.  For the legacy layout as an example,

```
LEGACY_LAYOUT = {
    'SPLITTERS': OrderedDict(
        (
            ('bodyFrame', 'secondary_splitter'),
            (VR3_MODULE_NAME, 'secondary_splitter'),
            (VR_MODULE_NAME, 'secondary_splitter'),
            ('outlineFrame', 'outline-log-splitter'),
            ('logFrame', 'outline-log-splitter'),
            ('outline-log-splitter', 'main_splitter'),
            ('secondary_splitter', 'main_splitter'),
        )
    ),
    'ORIENTATIONS': {
        'outline-log-splitter': Orientation.Horizontal,
        'secondary_splitter': Orientation.Horizontal,
        'main_splitter': Orientation.Vertical,
    }
}
```

Another way is to have the vr-show command insert VR into the same splitter as the body, and then equalize the splitter panes.  Exactly which splitter to put VR into should probably depend on whether the splitter's orientation were horizontal or vertical.

**Comment by tbpassin** [comment]
I just tried this using the vertical-thirds layout and it works as intended:

```
from leo.core.leoQt import Orientation
VR3_PLACEHOLDER_NAME = 'viewrendered3_pane'
VR_PLACEHOLDER_NAME = 'viewrendered_pane'

LAYOUT = {
    'SPLITTERS': dict(
            (('outlineFrame', 'secondary_splitter'),
            ('logFrame', 'secondary_splitter'),
            ('secondary_splitter', 'main_splitter'),
            ('bodyFrame', 'main_splitter'),
            (VR3_PLACEHOLDER_NAME, 'main_splitter'),
            (VR_PLACEHOLDER_NAME, 'main_splitter'))
        ),
    'ORIENTATIONS': {
        'secondary_splitter': Orientation.Vertical,
        'main_splitter': Orientation.Horizontal
    }
}

dw = c.frame.top
cache = dw.layout_cache
cache.restoreFromLayout(LAYOUT)
```

Put the code into a node and run it with CTRL-b to try it out.

Score one for the design of the layout data structure! I meant for it to have a lot of flexibility, including for cases like this.

**Comment by tbpassin** [comment]
With better names for the VR/VR3 slots (these constants are already defined in _qt_layout.py_):
```
VR3_OBJ_NAME = 'viewrendered3_pane'
VR_OBJ_NAME = 'viewrendered_pane'

LAYOUT = {
    'SPLITTERS': dict(
            (('outlineFrame', 'secondary_splitter'),
            ('logFrame', 'secondary_splitter'),
            ('secondary_splitter', 'main_splitter'),
            ('bodyFrame', 'main_splitter'),
            (VR3_OBJ_NAME, 'main_splitter'),
            (VR_OBJ_NAME, 'main_splitter'))
        ),
    'ORIENTATIONS': {
        'secondary_splitter': Orientation.Vertical,
        'main_splitter': Orientation.Horizontal
    }
}
```

**Comment by edreamleo** [comment]
@tbpassin Thanks for all your help. It's great to have you for a mentor :-)

**Comment by edreamleo** [comment]
@tbpassin I am going to close this issue. I shall be using the overleaf renderer, so I do not foresee a need to have VR and VR3 open simultaneously.

**Comment by edreamleo** [comment]
@tbpassin I am going to close this issue. I shall be using the overleaf renderer, so I do not foresee a need to have VR and VR3 open simultaneously.
