### ISSUE TITLE
Leo hangs on exit

### ISSUE THREAD

**Issue by RagBlufThim** [leo-editor/leo-editor#425]
I encounter two sorts of problems. Currently I use:

    Leo 5.4, build 20170226102909, Sun Feb 26 10:29:09 CST 2017
    Not running from a git repo
    Python 3.4.4, PyQt version 4.8.7
    Windows 7 AMD64 (build 6.1.7601) SP1

Python was installed using ``python-3.4.4.amd64.msi`` from www.python.org.  
PyQt was installed using ``PyQt4-4.11.4-cp34-none-win_amd64.whl`` from http://www.lfd.uci.edu/~gohlke/pythonlibs/.

I have been noticing the problems for some weeks, so they were not introduced with the aforementioned build.

The problems are:

1. Start leo. As soon as the startup completes and the leo window with workbook.leo shows, immediately exit using key ``Ctrl-Q`` or menu ``File`` > ``Exit``.  
=> Leo stops to react, a few seconds later the title bar says "not responding". Clicking in the window makes it look somewhat grayish. Clicking the close button (in Win7: The red button with the white x at the top right corner of the window frame) brings up a message box "pythonw doesn't react", offering to close the program or to wait for a reponse.  
... If I start leo, **do some work and then** exit using ``Ctrl-Q``, leo exits properly. I didn't explore in depth how much work is necessary, but just creating a new tab with ``Ctrl-N`` before ``Ctrl-Q`` is not enough.

2. Open a cmd window, start leo from the command prompt using ``py -3 path\to\launchLeo.py``. To exit click on the close button of the leo (Qt?) window (in Win7: The red button with the white x at the top right corner of the window frame).  
=> The leo (Qt?) window closes, but in the cmd window the prompt doesn't reappear. The keys ``Return``, ``Esc``, ``Ctrl-C`` don't help. The MS-Windows task manager shows that python is still running. To stop it, I have to close the cmd window or kill python using the task manager.

I can't offer a guess as to what is happening, as I know hardly anything about GUI programming and nothing about Qt.

If you can't reproduce the problem and need further details or would like me to run leo with some debug settings, please feel free to ask.

Cheers
r..m

P.S.: If I create a second tab and detach it, I get two windows that (nearly) look alike. However, they behave differently: When I click on the window close button of the detached window, only it closes. When I click on the window close button of the main window, all windows close. That sounds logical, but given the minimal differences in appearance of the windows the behaviour can be surprising.

**Comment by edreamleo** [comment]
> Leo 5.4, build 20170226102909, Sun Feb 26 10:29:09 CST 2017
Not running from a git repo
Python 3.4.4, PyQt version 4.8.7
Windows 7 AMD64 (build 6.1.7601) SP1

Is it possible for you to upgrade to Python 3 and/or Qt 5.x? This is going to be hard for me to diagnose, due to the differences in machines and versions.

Edward

**Comment by RagBlufThim** [comment]
> Is it possible for you to upgrade to Python 3 

Python 3.4.4 is Python 3 ... did you mean Python 3.6?  
I plan to upgrade to 3.6 once 3.6.1 is out, all libraries I use are available for 3.6 (at least one is missing at the moment) and I find the time to do the upgrade and necessary tests. That may be awhile.

> and/or Qt 5.x? 

PyQt 5 is not available for Python 3.4. However I think to remember that I saw a package of PyQt4 + Qt5 (not the latest one) on sourceforge somewhere. I will have a look, but not today (and probably not tomorrow).

> This is going to be hard for me to diagnose, due to the differences in machines and versions.

I can understand that. Thanks for your effort anyway.  
I'll come back with news once I found the time to play with Qt versions.

**Comment by edreamleo** [comment]
On Mon, Feb 27, 2017 at 3:25 PM, RagBlufThim <notifications@github.com>
wrote:

> Is it possible for you to upgrade to Python 3
>
> Python 3.4.4 is Python 3 ... did you mean Python 3.6?
>
​Actually, I meant Python 3.5 or 3.6. Iirc, 3.4 had lots of problems.

> I'll come back with news once I found the time to play with Qt versions.
>
​Good. This isn't a release blocker, but I would like to resolve it asap.

Edward

**Comment by vitalije** [comment]
While fixing some other issues today, I have noticed similar symptom. In those few cases that I have encountered today, problem was not properly deactivating of some plugins. @RagBlufThim can you check against latest commit and see if the behavior you reported is still happening or not.

If it does happen, can you disable all plugins and check what happen without plugins.

**Comment by edreamleo** [comment]
On Wed, Jul 12, 2017 at 1:16 PM, Виталије Милошевић <
notifications@github.com> wrote:

> While fixing some other issues today, I have noticed similar symptom.
>
​And I too have noticed this, but sporadically.

Edward
