### ISSUE TITLE
Leo 6.8.3 runs but devel does not

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#4250]
My linux system just upgraded from Python 3.12.3 to 3.12.7.  After this, I created a new venv for Leo and installed the dependencies using `pip install -r requirements.txt`. The devel branch failed to start, displaying the default message box saying that qt could not start.  

I then pip-installed Leo 6.8.3 from pip and it starts normally, running in the same venv.

It seems that devel needs some library that isn't in requirements.txt.  Unfortunately there is no further diagnostic information to go on.  Also unfortunately, my Windows computer is out of action so I cannot compare the installed libraries.Leo 6.8.3
Python 3.12.7, PyQt version 6.7.3
linux

If someone would create  a fresh install that contains only the minimal set of dependencies that will let devel run, I could compare with what I've got here.

The one that works:
```
Leo 6.8.3
Python 3.12.7, PyQt version 6.7.3
linux
```

**Comment by tbpassin** [comment]
Note that devel ran successfully before the system Python upgrade from 3.12.3 to 3.12.7.

**Comment by LewisNeal** [comment]
Is it possible the staggered release of PyQt6 version 6.8.1 has caused the problem?
This typically occurs when PyQt6-Qt6 is released before PyQt6.
See https://riverbankcomputing.com/pipermail/pyqt/2024-December/046083.html

If I update to PyQt6-Qt6 v6.81 Leo will not start as PyQt6 is at version 6.7.3

**Comment by tbpassin** [comment]
I don't think that can be it because Leo 6.8.3 runs successfully but devel does not.  The venv has PyQt6 versions 6.7.x for all the PyQt components including the QWebEngine.

The system's upgraded installation does have some version of  PyQt 6.8 (6.8.0.dev2411221125) but it's not used by Leo in the venv:

```
Leo 6.8.3
Python 3.12.7, PyQt version 6.7.3
```

It seems (at least on this Linux OS) that some library isn't available or doesn't work right under Python 3.12.7 that did work or was present under 3.12.3. I haven't seen any error messages that even hint what that might be.  The only message is `Can not load the requested gui: qt`.

**Comment by LewisNeal** [comment]
Leo and Python 3.12.7 are working on wsl openSUSE.
```
Leo 6.8.4-devel, devel branch, build 7fcb201f24
Python 3.12.7, PyQt version 6.7.3
```
Let me know if you want me to upgrade to PyQt6-Qt6 6.8.1 and report the error.

**Comment by tbpassin** [comment]
Mystery solved. Somehow some extra text was inadvertently pasted into qt_text.py. I have no idea how.  That raised a syntax error, but the exception that causes a failure to start isn't printed out by the startup code. I added a print statement for the exception, which gave me the line number of the syntax error.   After verifying the error, I reset the branch, and then devel ran as it should.  

I'm closing this issue.
