### ISSUE TITLE
Goto global line number -> "can not execute multiple languages"

### ISSUE THREAD

**Issue by tbnorth** [leo-editor/leo-editor#429]
Alt-G <number> or Alt-X <number> is giving "can not execute multiple languages", file name ends in .coffee, it's a `@clean` node, and there's `@language coffeescript` at the top.  No other `@language` in file.

Full log output is
```
can not execute multiple languages
ignoring @language coffeescript and all following lines
only 0 lines
```

```
Leo Log Window
Leo 5.4, build 20170215101048, Wed Feb 15 10:10:47 CST 2017
Git repo info: branch = master, commit = 658d7c960e06
Python 2.7.5, PyQt version 4.8.5
Windows 7 AMD64 (build 6.1.7601) SP1
```

**Comment by edreamleo** [comment]
On Mon, Feb 27, 2017 at 1:19 PM, Terry Brown <notifications@github.com>
wrote:

> Alt-G or Alt-X is giving "can not execute multiple languages", file name
> ends in .coffee, it's a @clean node, and there's @language coffeescript
> at the top. No other @language in file.
>
​Welcome back, Terry.  I'll fix this today.

Edward
