### ISSUE TITLE
rst import: titles with different underline characters on same level

### ISSUE THREAD

**Issue by RagBlufThim** [leo-editor/leo-editor#430]
I noticed this behaviour during my first experiments with leo. I wasn't sure whether I was doing something wrong, but by now I think leo could be doing better.

## Example to demonstrate the effect

1. Start leo. ``workbook.leo`` will open.
2. Within ``workbook.leo`` select the node ``~/myDocument.html.txt`` (subnode of ``The rst3 tutorial``) and copy the body text into a new file, say ``test.rst``.
3. Open a new tab with ``Ctrl-N``.
4. Rename the top level node to ``@auto test.rst`` (add path as necessary to point to the file created in step 2).
5. While the node is selected, do ``File`` > ``Read/Write`` > ``Read @auto Nodes``.

Expected result: Nodes "Chapter I" and "Chapter XII" are subnodes of "War and Peace".

Observed result: Nodes "Chapter I" and "Chapter XII" are on the same level as "War and Peace"!

## Cause

The level of a title is calculated by the method ``ch_level()`` of class ``Rst_Importer``. The method uses the dict ``rst_seen`` to map known underline characters to node levels. The method also uses the integer ``rst_level`` as the highest level recorded in ``rst_seen``. 

``rst_seen`` is initialized with ``{'#': 1,}``, ``rst_level`` with 0.

Thus "War and Peace" is assigned to level 1 because it uses # and according to ``rst_seen`` that's level 1.  
"Chapter I" uses +, which is not in ``rst_seen``. Thus ``ch_level()`` adds + to ``rst_seen`` with level ``rst_level``+1, which is also level 1.

In general # titles are always level 1 (regardless of where in the text they appear first), as are titles with the (non-#) underline character that appears first in the text. Thus importing

    A Section Title
    ===============
    Some text
    
    A Subsection Title
    ------------------
    More text
    
    An Intended Subsubsection Title using #
    #######################################
    Even more text

    Fourth Level Title
    ++++++++++++++++++
    text text text

will give a node hierarchy of

    A Section Title
        A Subsection Title
    An Intended Subsubsection Title using #
        placeholder
            Fourth Level Title    

## How to fix

The obvious fix is to initialize ``rst_seen`` with ``{}``. (Line 175 of ``leo\plugins\importers\leo_rst.py``)

I noticed that # is special cased in many places. The rst3 tutorial mentions a special use of #, so that might be the origin. However, rst3 only writes rst files, doesn't read them. And as shown above, the current rst importer with special treatment of # doesn't import rst3 generated text correctly.

Thus I think ``{}`` is ok, as long as no rst3 expert has a different opinion.

Cheers
r..m

**Comment by edreamleo** [comment]
On Mon, Feb 27, 2017 at 3:36 PM, RagBlufThim <notifications@github.com>
wrote:

> I noticed this behaviour during my first experiments with leo. I wasn't
> sure whether I was doing something wrong, but by now I think leo could be
> doing better.
>
​Excellent analysis and sleuthing.  ​Please commit your proposed fix. I'll
happily grant you git write access if you need it.

Edward
