### ISSUE TITLE
Escape `\n` in abbreviations

### ISSUE THREAD

**Issue by largo84** [leo-editor/leo-editor#432]
Suppose I create an abbreviation for a LaTex construct such as:

newcom;;=\newcommand{\<|SomethingNew|>}{<|INSERT-TEXT|>}

When the abbreviation is expanded (executed), the `\n` in \newcommand is interpreted as a Python line feed and I end up with:

ewcommand{\<|SomethingNew|>}{<|INSERT-TEXT|>}

How can I escape the `\n` so that it doesn't create a line feed, but the string literal value of `\n`?

**Comment by edreamleo** [comment]
Thanks, Terry.  That was fast.

**Comment by largo84** [comment]
Still not working after pulling the latest commit.

**Comment by tbnorth** [comment]
```
newcom;;=\\newcommand{\SomethingNew}{<|INSERT-TEXT|>}
```

(note double \\\\) is working for me in

```
Leo 5.4, build 20170228111832, Tue, Feb 28, 2017 11:18:31 AM
Git repo info: branch = master, commit = 9e9539d7f845
Python 2.7.5, PyQt version 4.8.5
Windows 7 AMD64 (build 6.1.7601) SP1
```

If you have a non-working abbrev. can you post it here?

**Comment by largo84** [comment]
Sorry, it wasn't obvious to me to use `\\n` to escape. I suppose I should have inferred that from your post in the group. It works and I'm closing the issue. Thanks for fixing!
