### ISSUE TITLE
Retire the tables.py plugin

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#433]
Terry has created a csv editor in plugins/editpane/editpane.py, described [here](https://groups.google.com/d/msg/leo-editor/vmCusVz21fk/oYUFFwhuBgAJ), with a [demo video](https://www.youtube.com/watch?v=hca3x5SXNqs&feature=youtu.be).

I am going to close this issue. There is no great need for the plugin.

**Comment by tbnorth** [comment]
@edreamleo points out the edit pane csv editor might handle this, I need to look at org mode tables, but that's probably true.

**Comment by edreamleo** [comment]
The VR3 plugin makes the tables.py plugin unnecessary.
