### ISSUE TITLE
Upgrade to PyQt 5.8.0 breaks appearance settings

### ISSUE THREAD

**Issue by alacnorr** [leo-editor/leo-editor#435]
Since upgrading to PyQt 5.8.0, several appearance settings are broken, such as font settings, line numbers, some colors, etc. 

 I attach three same-scale screenshots of Leo started with exactly the same settings but using three different PyQt versions, namely 4.87, 5.6.2 and 5.8.0. The three windows in the screenshots were of roughly the same size and all screenshots are taken at the same scale. 

Fonts, gutter, liner number and outline node open/close images, among the other things, are affected when using PyQt 5.8.0.

![pyqt 4 8 7](https://cloud.githubusercontent.com/assets/19180454/23694604/1f5a12f0-041e-11e7-91c6-c6489d37e8c9.png)
![pyqt 5 6 2](https://cloud.githubusercontent.com/assets/19180454/23694492/8b564efc-041d-11e7-824e-18effb476597.png)
![pyqt 5 8 0](https://cloud.githubusercontent.com/assets/19180454/23694508/9ba939e0-041d-11e7-89ff-ec62b43397b2.png)

System:
Windows 10 AMD64 (build 10.0.14393) SP0, Python 3.6.0

**Comment by edreamleo** [comment]
On Wed, Mar 8, 2017 at 1:43 AM, alacnorr <notifications@github.com> wrote:

> Since upgrading to PyQt 5.8.0, several appearance settings are broken,
> such as font settings, line numbers, some colors, etc.
>

​Surely this must be an issue with PyQt.  Have you discussed this with the
Qt people?

Edward

**Comment by edreamleo** [comment]
I'm going to close this.  Please reopen if you have reason to believe that it is somehow a Leo problem.

**Comment by alacnorr** [comment]
Edward,
I agree it's not a Leo problem per se, but the reason I opened this issue was that I had noticed you were making changes in the theming strategy for Leo, so I thought you should be aware of this issue, since the new Qt 5.8 may have changed the way style sheets are handled (I haven't had time to investigate yet) and that would have repercussions on the way style sheets are handled in Leo. As far as I can see, my style sheet settings do not work anymore, so perhaps any changes in the way Leo handles them should be updated so as to reflect the changes brought about by Qt 5.8, lest users upgrading their PyQt version might have the same problem and would not be able to fix it, which is a bit frustrating. That's all. Many thanks for your all your great efforts.
