### ISSUE TITLE
Upgrade to PyQt 5.8.0 breaks appearance settings (follow-up of closed issue #435)

### ISSUE THREAD

**Issue by alacnorr** [leo-editor/leo-editor#436]
Edward,
sorry for reopening this issue (#435), but I have been able to localize many of the problems in LeoSettings.leo#@settings-->Appearance (change these first)-->Qt Gui settings-->Fonts-->Outline pane fonts

It seems outline pane font/color settings do not work with PyQt 5.8, even though they work fine in version 5.7.1.; I attach two screenshots of a pristine, vanilla Leo installation with untouched LeoSettings.leo and no myLeoSettings.leo, for comparison. I don't think it's a PyQt issue, I haven't found any info around yet that can confirm that. 

I was thinking, perhaps something has been changed in the way Leo handles the outline pane settings (or even its Qt widgets), so that these changes might be conflicting with the new PyQt version? I cannot verify this since I don't know the relevant Leo code, so I just wanted to bring this issue to your attention.

I'll leave it to you to determine whether this information is of any relevance, but I think the issue should be understood in order to be able to make working, complete themes for Leo (incidentally, it seems the themes provided with Leo all suffer from outline pane style issues).

Thanks again for you attention.

![pyqt 5 7 1](https://cloud.githubusercontent.com/assets/19180454/23774972/b5b414f2-0569-11e7-8b3b-340a67f9fb78.png)
![pyqt 5 8 0](https://cloud.githubusercontent.com/assets/19180454/23774975/b7b687bc-0569-11e7-8d1f-6281b9672110.png)

**Comment by edreamleo** [comment]
On Thu, Mar 9, 2017 at 5:16 PM, alacnorr <notifications@github.com> wrote:

> Edward,
> sorry for reopening this issue (#435
> <https://github.com/leo-editor/leo-editor/issues/435>), but I have been
> able to localize many of the problems in LeoSettings.leo#@settings-->Appearance
> (change these first)-->Qt Gui settings-->Fonts-->Outline pane fonts
>
​Nevertheless, this can not be a Leo issue.  The only parts of Leo that
depend on the Qt version are in leo/core/leoQt.py, and they deal only with
imports.

To my knowledge, there is no way to distinguish between Qt versions within
stylesheets, and Leo certainly does not do so.

Happily, the workaround is straightforward. Just change these settings in
your theme:

@theme my theme-->settings-->style sheet settings-->fonts

If you are not using a theme, change the corresponding settings in
myLeoSettings.leo.

Edward

**Comment by alacnorr** [comment]
Thanks for your feedback, Edward,
Unfortunately changing font settings in either leoSettings.leo or myLeoSettings.leo as per instructions has no effect on the outline pane fonts when using PyQt 5.8 (most other settings, but not all, seem to work though, and can be changed). Everything else being equal, just using PyQt version 5.8 does seem to have an effect on several appearance settings in a way that cannot be fixed by manual changes, at least I haven't found a way to do so (as a consequence, I am currently running Leo in a dedicated python installation with PyQt 5.6). I will investigate further and only comment further on this issue if I find a relevant explanation.

**Comment by LewisNeal** [comment]
I have exactly the same myLeoSettings.leo file on 2 PC's both running commit = 51b3d984000e. The selected theme is 'base dark theme'.

On Vista PC with Python 3.5.2, PyQt version 5.6.0 installed, the theme is dark all over as expected.

However on win10 PC with Python 3.6.0, PyQt version 5.8.0 installed, the outline pane and body panes have a light background.  If I select a menu bar item, the text displayed is not readable - almost no contrast.

This has happened this several times over the last few days but I haven't reported it as the themes have been changing so often. So I have used identical myLeoSettings.leo files to rule out any other effects.
I can confirm the same changes occur with 'ekr dark theme'.
Interestingly the most recently deprecated 'leo_dark theme 1' does not change behaviour like the new themes do.

**Comment by jaccarmac** [comment]
I'm using a dark WM theme on Linux and see the problem with light and unreadable text in Leo. I haven't changed any settings in Leo, this is purely an interaction with the desktop's theming system. This is with PyQt 5.6.

**Comment by tbnorth** [comment]
On Fri, 16 Feb 2018 05:53:45 +0000 (UTC)
Jacob MacDonald <notifications@github.com> wrote:

> I'm using a dark WM theme on Linux and see the problem with light and
> unreadable text in Leo. I haven't changed any settings in Leo, this
> is purely an interaction with the desktop's theming system. This is
> with PyQt 5.6.

Try the .zip file attached to this issue:

https://github.com/leo-editor/leo-editor/issues/706

The themes could do with some maintenance, but it would be
nice if this bug:
https://bugreports.qt.io/browse/QTBUG-59533
showed some sign of getting fixed.

Cheers -Terry

**Comment by jaccarmac** [comment]
It works, thank you!
