### ISSUE TITLE
execute-script should execute unselected code between @language directives

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#439]
If there is no text selection, execute-script should use only the code from the present insert point back to the previous `@language` directive (in the node) and forward to the next `@language` directive.  In effect, this will make `@language` directives work like org-mode's [#+BEGIN_SRC <language>](http://orgmode.org/manual/Working-With-Source-Code.html) lines.

**Comment by vitalije** [comment]
Done at 551016a. All unit test pass. However, I didn't try to check if previous language directive is for python or not. It strictly uses text between previous at-language directive (or beginning of node) up to the next at-language (or end of node).

**Comment by edreamleo** [comment]
On Thu, Jul 13, 2017 at 4:14 PM, Виталије Милошевић <
notifications@github.com> wrote:

> Done at 551016a
> <https://github.com/leo-editor/leo-editor/commit/551016a5871fc1df9e10fc232bd9d31d4bbba957>.
> All unit test pass. However, I didn't try to check if previous language
> directive is for python or not. It strictly uses text between previous
> at-language directive (or beginning of node) up to the next at-language (or
> end of node).
>
​​I'm not sure what I think not checking.  I'll play with this when I have
time.

Edward

**Comment by edreamleo** [comment]
Rev 911001d reverts  551016a.  This code should be thoroughly tested, with new unit tests, in a new branch.

**Comment by edreamleo** [comment]
The fix for #1071 does this, in effect.
