### ISSUE TITLE
Support json (.leojs) files in addition to xml (.leo) files

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#442]
See PR #1850.

[leoInteg issue 125](https://github.com/boltex/leointeg/issues/125) suggests adding support for a .leojs [JSON](https://www.json.org/) Leo file format in addition to Leo's standard .leo xml file format.

- [x] Create save-as-leojs command.
- [x] Rename save-as-unzipped to save-as-xml.
- [x] Reorganize and clean leoFileCommands.py.
  - [x] Deprecate g.FileLikeObject. Use io.StringIO instead.
  - [x] Remove unnecessary helpers.
  - [x] Remove c.isZipped flag. Use file extensions instead.
- [x] fc.getLeoFile special cases .leojs and .db files.
- [x] fc.writeOutline special cases .leojs and .db files.
- [x] fc.read_leojs creates an outline from a .leojs file.
- [x] fc.write_leojs writes the outline as JSON.'

**Description of .leojs files**

The following is the format suggested by Félix.  The comments are mine.

```typescript
interface ILeoHeader {
    fileFormat: number;  // should always be 2
}

interface IPosition {
    top: number;
    left: number;
    height: number;
    width: number;
}

// Leo only writes an empty 'globals' key:  'globals': {}
// At present, Leo assumes the 'globals' dict has the 'top', 'left', 'height' and 'width' keys.
// See the scan_leojs_globals function.

interface IGlobals {
    bodyOutlineRatio?: number;  // Not used. Leo will cache this value.
    globalWindowPosition?: IPosition;  // Used only if Leo has not cached this value.
    globalLogWindowPosition?: IPosition;  // Never used.
}

interface ITNode {
    tx: string;
    body: string;
}

interface IVNode {
    vh?: string;
    a?: string;
    t: string;
    children: IVNode[];
}

export interface ILeoFile {
    leoHeader: ILeoHeader;
    globals: IGlobals;
    vnodes: IVNode[];
    tnodes: ITNode[];
}
```

**Comment by edreamleo** [comment]
This isn't even remotely worth doing.

**Comment by boltex** [comment]
Oops! I Had a typo in my issue: its intended to be named ".leojs", not ".lsojs"  🤦

**Comment by edreamleo** [comment]
The ekr-json branch has been merged into devel.

**Comment by boltex** [comment]
Looking at the generated output, this looks perfect except for the 'status' member of vnodes, which is absent regular of .leo files... was this desired/intended?

Anyhow, thanks again for this nice 'JSON' file format support!! :+1:
