### ISSUE TITLE
Adapt Quiver look and feel to Leo?

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#443]
[​This page](https://github.com/HappenApps/Quiver/wiki/Getting-Started) is the Quiver overview.

Related issues:

- [#338: Use Flexx to create a browser-based gui for Leo](https://github.com/leo-editor/leo-editor/issues/338)
- [#361: Use pyzo code to improve Leo](https://github.com/leo-editor/leo-editor/issues/361)
- [#366: Allow Leo nodes to work like Jupyter cells](https://github.com/leo-editor/leo-editor/issues/366)
- [#369: Highlight various whitespace](https://github.com/leo-editor/leo-editor/issues/369)
- [#370: Replace Leo's body widget with pyzo's text widget](https://github.com/leo-editor/leo-editor/issues/370)
- [#396: Show images in Leo's body pane](https://github.com/leo-editor/leo-editor/issues/396)
- [#442: Support json files instead of xml](https://github.com/leo-editor/leo-editor/issues/442)

**Cells:** Cells correspond to Leo nodes, though perhaps the correspondence isn't exactly.  I'm not sure whether quiver cells form a tree.

**Cell types**: Quiver follows the Jupyter design. Each cell has a single type:

> A "Text Cell" lets you edit rich-text in-place. It supports images and links too.
> A "Code Cell" packs the awesome ACE code editor, with syntax highlighting support for 120+ languages, 20+ themes, automatic indent and outdent, code completion, and much more.
> A "Markdown Cell" lets you write in Markdown with inline formatting and custom CSS options.
> A "LaTeX Cell” uses MathJax to typeset mathematical equations in your notes.
> A “Diagram Cell” lets you create sequence diagrams and flowcharts from text.

One might say that Leo's @language directives assign a type until the next @language directive (in that node). For sure, we aren't going to remove @language directives. Another option would be to use uA's to indicate cell type. Once Leo supports drawers (p.drawer, implemented via uA), the _only_ natural thing would be to have a cell-type attribute in the drawer:

**Cell operations**: Insert cell (Leo: Ctrl-I), change cell type, merge cells. All straightforward in Leo. Exactly what they do will depend on whether Leo nodes can contain one cell, or multiple cells.

**Images, files and links**: Leo already has support for drag and drop, url's, etc., so this section implies minimal changes to Leo.

**Preview and presentation**: Live preview (side-by-side view) is how Leo works at present. The body pane contains "raw" markup, the viewrendered pane contains the rendered result. Presentation mode (start-presentation) would work like Leo's demo.py plugin.

**Team collaboration**: Quiver has no special features here.

**Import and export: Quiver uses json**: Leo could use a PDF importer. Leo has a rudimentary rST to PDF writer.

**Preferences**: No changes will be made to Leo.

**Comment by technatica** [comment]
I stumbled across this markdown editor a while ago. Their idea might be of
interest.

https://typora.io/

Chris

**Comment by edreamleo** [comment]
On Tue, Mar 21, 2017 at 11:14 AM, Chris George <notifications@github.com>
wrote:

> I stumbled across this markdown editor a while ago. Their idea might be of
> interest.
>
> https://typora.io/


​Thanks for the link.

Edward

**Comment by edreamleo** [comment]
[This post](https://groups.google.com/d/msg/leo-editor/x0C0Ge8kw4k/B0jz-i8TCQAJ) contains ideas relating to unifying the outline and body panes.

**Comment by offray** [comment]
I think that the look and feel could have outlines and body panes separated or integrated as a way of viewing and editing them. I wouldn't like to sacrifice outline view for integrated view.

**Comment by xgid** [comment]
> I think that the look and feel could have outlines and body panes separated or integrated as a way of viewing and editing them. I wouldn't like to sacrifice outline view for integrated view.

Totally agree! There should be an easy way to switch from one to the other, but have both. The integrated view is exactly one of the main things in my wish list for Leo, so you've literally read my mind! (or maybe I have read yours?)

**Comment by edreamleo** [comment]
I am going to close this item, per recent discussions.
