### ISSUE TITLE
Add the vr-toggle-full-screen command

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#446]
The present vr-expand command expands by a relatively small amount into the body pane. 

The vr-toggle-full-screen command would alternatively replace all of the outline with the VR pane, and restore the VR pane to its previous location.

**Comment by xgdomingo** [comment]
This is also working great for me!

Thanks, Vitalije.

**Comment by edreamleo** [comment]
Thanks, Vitalije.  I have changed the name of this item to reflect the actual name of the new command.
