### ISSUE TITLE
VR plugin should be improved

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#447]
1. It should render "pieces" from several `@language` directives.

2. It should support `@treeview` directives.

**Comment by xgid** [comment]
> 2. It should support `@treeview` directives.

Hi, I made a comment about this at the Google group, but I think I was not enough clear and may be this is a better place. The main question is: how is this directive supposed to work? 

In particular, I'm interested in Markdown language trees (with or without an @auto directive at the top). What would be the workflow you have in mind if I want to see a tree of nodes redered as a whole at the VR pane, but I also want to be able to move down the tree to see just some parts of it (sub-trees or just nodes) rendered instead?

**Comment by tbnorth** [comment]
The slowly approaching Leo Edit Pane component does this, so one option's to wait for that.

**Comment by edreamleo** [comment]
@xgid Rendering markdown trees is clearly a high priority item for the VR pane. It was a major reason for the VR2 plugin.  My hope is that this issue, along with Terry's EP work will (eventually) make VR2 obsolete.

**Comment by xgid** [comment]
Thanks to both, glad to know that you already have this in mind! So nothing more to say from my side... except "Keep up the Good Work!" 👏 😃

**Comment by edreamleo** [comment]
I am not going to do this.  It will happen only if somebody else does this.

**Comment by edreamleo** [comment]
The VR3 plugin makes this issue moot.
