### ISSUE TITLE
Fix rare @auto bugs

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#449]
- ~Cancelling @auto write creates orphan nodes.~ This should be a separate issue.
- Cloned @auto nodes duplicates section references.

**Comment by xgid** [comment]
Hi Eduard,

As you know I work intensively with Markdown files and was looking at some features that I've found already present for [reStructuredText files](http://leoeditor.com/tutorial-rst3.html#other-topics) like @rst-no-head, @rst-ignore and @rst-ignore-tree. I searched for "[Markdown](http://leoeditor.com/search.html?q=markdown)" and "[auto-md](http://leoeditor.com/search.html?q=auto-md)" at the documentation and found nothing. So I started reading the code of the MarkdownWriter and found [this comment](https://github.com/leo-editor/leo-editor/blob/master/leo/plugins/writers/markdown.py#L18):

> \# New in Leo 5.5: Skip !headlines. Convert all others to '#' sections.

So I tried it! Defined an @auto Markdown file with various levels of nodes, saved the file (generating the .md file outside) and just then added a `!` as first character of one of my headlines. Saved the file again and, as expected, the headline was now **not** saved in the .md file, but only the body of that node. So far, so good.
But then I made a "Refresh from disk" at the @auto node and... the node with the `!` headline disappeared (and it's body text was added to it's parent)! I thought that the original outline structure was going to be held as is the case with the @clean and the great Mulder/Ream update algorithm. Is this a bug?

If it is not, how could I achieve my expected result of having a node whose headline is ignored by the writer but held in the tree even after "Refresh from disk"?

**Comment by edreamleo** [comment]
On Mon, Mar 27, 2017 at 10:13 AM, XGiD <notifications@github.com> wrote:

> As you know I work intensively with Markdown files and was looking at some
> features that I've found already present for reStructuredText files
> <http://leoeditor.com/tutorial-rst3.html#other-topics> like @rst-no-head,
> @rst-ignore and @rst-ignore-tree. I searched for "Markdown
> <http://leoeditor.com/search.html?q=markdown>" and "auto-md
> <http://leoeditor.com/search.html?q=auto-md>" at the documentation and
> found nothing. So I started reading the code of the MarkdownWriter and
> found this comment
> <https://github.com/leo-editor/leo-editor/blob/master/leo/plugins/writers/markdown.py#L18>:
>
>
> # New in Leo 5.5: Skip !headlines. Convert all others to '#' sections.
>
> So I tried it! Defined an @auto <https://github.com/auto> Markdown file
> with various levels of nodes, saved the file (generating the .md file
> outside) and just then added a ! as first character of one of my
> headlines. Saved the file again and, as expected, the headline was now
> *not* saved in the .md file, but only the body of that node. So far, so
> good.
>
​Thanks for reminding me of the ! convention.  I had completely forgotten
it, and now I understand the somewhat cryptic complaint starting with "!".​
Hehe.

> But then I made a "Refresh from disk" at the @auto
> <https://github.com/auto> node and... the node with the ! headline
> disappeared (and it's body text was added to it's parent)! I thought that
> the original outline structure was going to be held as is the case with the
> @clean <https://github.com/clean> and the great Mulder/Ream update
> algorithm. Is this a bug?
>
​It's likely a bug involving the coordination (or lack of it) between
leo.plugins.importers.markdown.py and leo.plugins.writers.markdown.py.  The
update algorithm is never used with @auto files.

> If it is not, how could I achieve my expected result of having a node
> whose headline is ignored by the writer but held in the tree even after
> "Refresh from disk"?
>
​I don't know yet, but this is exactly the correct question to ask.  It may
require some changes to either the importer or writer. There is also a
small possibility that the '!' convention can't be made to work with
refresh-from-disk. We shall see.

Edward

**Comment by xgid** [comment]
>  The update algorithm is never used with @auto files.

I understand from your words that this is by design and cannot be changed. Is this the case? 

If that's the case, then I think the proper route to follow would be to stick to the @clean directive and have a kind of "@others-with-headlines" directive or the like that does the same than the currently existing @others **but including also the headlines** in the result! What do you think? Does it make sense? Would it be possible? 

Or should instead the @others directive change its behaviour depending on the @language currently in effect?

**Comment by edreamleo** [comment]
On Mon, Mar 27, 2017 at 10:23 PM, XGiD <notifications@github.com> wrote:

> The update algorithm is never used with @auto <https://github.com/auto>
> files.
>
> I understand from your words that this is by design and cannot be changed.
> Is this the case?
>
​You could say that, I suppose.  All @auto trees use importers that simply
split incoming code into nodes.​

> If that's the case, then I think the proper route to follow would be to
> stick to the @clean <https://github.com/clean> directive and have a kind
> of "@others-with-headlines" directive or the like that does the same than
> the currently existing @others <https://github.com/others> *but including
> also the headlines* in the result!
>
You can change an @auto tree to an @clean tree after the first import. But
this doesn't give you what @auto-md gives you: the automatic generation of
section headers.

There have been proposals to make @nosent optionally write headlines. I am
willing to consider this, but I am not going to change @others nor do
anything else drastic with Leo's fundamental read/write code.

Edward

**Comment by edreamleo** [comment]
Rev 09236df fixes this issue.  In fact, this was a very serious matter.  Happily, the fix was straightforward.

**Comment by xgid** [comment]
Hi Edward,

I'm sorry I have not been able to follow up with this talk for so long! I've had really really hard months both at home (with my wife in a wheelchair) and at work. But I'm now (kind of) back again, at least for a while. Anyway, I've been following close all the great progress you all have made in Leo this months (curses gui, reload-leo, .leo.db! and so on). Congratulations for all the hard work!

The questions which remained open in this thread were these:

> You can change an @auto tree to an @clean tree after the first import. But this doesn't give you what @auto-md gives you: the automatic generation of section headers. 

> There have been proposals to make @nosent optionally write headlines. I am willing to consider this, but I am not going to change @others nor do anything else drastic with Leo's fundamental read/write code.

As this GH issue is now closed and it has nothing to do with those questions, I think it would be better to follow up those points through Google Groups. What do you think?

**Comment by edreamleo** [comment]
@xgid: Google groups is a good place for discussions.  It will reach the most people.
