### ISSUE TITLE
goto-global-lines can fail if there is no @language directive

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#452]
[This message](https://groups.google.com/d/msg/leo-editor/tJpKTPs045Y/GViBgWEzCwAJ) links to a file illustrating a problem with re Alt-G, goto-global-line.  This file contains no `@language` directive.

In my tests, Alt-G works properly, with both `@clean` and `@nosent` **only** if I add `@language javascript` to the root node. Without this directive, Alt-G probably uses the language given by:

     `@string target_language`

which for me is Python.  This mismatch in comment delimiters completely confuses Alt-G. It fails to find *any* line.  That is, Alt-G <anything> selects the line after the `@others` in the root node.

**Comment by vitalije** [comment]
I don't know what c.target_language is and how important is to be preserved. I have enclosed it in try/finally block and assign temporarily computed language for given position and after getting delimiters restore it in previous value. @edreamleo - perhaps there is better way to find delimiters when language is already known?

**Comment by vitalije** [comment]
no objections to close this? @edreamleo please look at the previous message regarding importance of c.target_language.

**Comment by edreamleo** [comment]
​On Mon, Jul 3, 2017 at 2:01 AM, Виталије Милошевић <
notifications@github.com> wrote:

> no objections to close this? @edreamleo <https://github.com/edreamleo>
> please look at the previous message regarding importance of
> c.target_language.
>
​Your solution seems reasonable. This is tricky.  One might want
g.getLanguageAtPosition to preserve c.target_language, but I wouldn't be my
life on it. All things considered, your code may be best.

Edward
