### ISSUE TITLE
Focus jumps to de body pane when expanding an abbreviation in a headline

### ISSUE THREAD

**Issue by xgid** [leo-editor/leo-editor#453]
When an abbreviation is expanded while editing a headline, the focus always jumps to the body pane, getting me out of the headline I was editing. So I have to press Ctrl-h to get back and go on with the edition.

Is there a chance for this to be fixed?

I was thinking that maybe you could "trigger" a "focus in headline + start edition" after the expansion has ended... it sounds easy, doesn't it? 😉

**Comment by edreamleo** [comment]
This is either going to be straightforward, or practically impossible.

**Comment by edreamleo** [comment]
Rev d39563a fixes this.

**Comment by xgid** [comment]
> Rev d39563a fixes this.

Uau! This is good news. 
Works perfectly!  Thanks
