### ISSUE TITLE
Focus jumps to position 2,4 of body pane when pressing "Tab" key

### ISSUE THREAD

**Issue by xgid** [leo-editor/leo-editor#454]
Focus jumps to position 2,4 (line: 2, col: 4) of the body pane if I press "Tab" key when the cursor is at the tree pane of a node with an empty body. I would expect it to jump to the position 1,1.

**Comment by edreamleo** [comment]
I don't believe this is a problem with Leo.  Leo's default key bindings do nothing when tab is pressed in the outline (tree) pane.

Please enable the traces in k.masterKeyHandler and report the results.

**Comment by edreamleo** [comment]
I am going to close this unless I can be convinced there is a real problem.

**Comment by xgid** [comment]
OK, the requested traces show this:
```
masterKeyHandler stroke: <KeyStroke: 'Tab'> char: u'\t' ch: u'\t' state None state2 insert
masterKeyHandler plain key in tree
masterKeyHandler    bound <KeyStroke: 'Tab'> wrapper: newline-and-indent
```

So I've checked the ouput of the `print-bindings` command and this binding is effectively shown under the `Plain Keys` section:
```
***** Plain Keys...
  (               show-calltips
  .               auto-complete
  text: BackSpace backward-delete-char
  tree: BackSpace delete-node
  text: Delete    delete-char
  tree: Delete    delete-node
  tree: Down      goto-next-visible
  text: Down      next-line
  End             end-of-line
  F1              help
  F10             do-nothing
  F11             help-for-command
  F12             help-for-python
  F2              find-prev
  F3              find-next
  F4              do-nothing
  F5              do-nothing
  F6              do-nothing
  F7              spell-tab-open
  F8              do-nothing
  F9              do-nothing
  Home            back-to-home
  text: Insert    insert-newline
  tree: Insert    insert-node
  text: Left      back-char
  tree: Left      contract-or-go-left
  text: Next      forward-page
  tree: Next      scroll-down-page
  text: Prior     back-page
  tree: Prior     scroll-up-page
  tree: Return    end-edit-headline
  body: Return    insert-newline
  tree: Right     expand-and-go-right
  text: Right     forward-char
  Tab             newline-and-indent
  tree: Up        goto-prev-visible
  text: Up        previous-line
```

I've also reviewed my `myLeoSettings.leo` file and I have only this custom binding defined:
```
# Hoist plugin
save-hoist ! tree = Ctrl+Shift+H
```

P.S.: BTW, this custom binding is **not shown at all** at the ouput of the `print-bindings` command, although the binding is working as expected. Is this normal?

**Comment by edreamleo** [comment]
Thanks for this.  I'll look into it.

**Comment by edreamleo** [comment]
Thanks, Vitalije, for tracking this down.   However, it's best to use pane-dependent bindings for Tab, as shown in efb0b66.
