### ISSUE TITLE
Broken layout after doing vr-toggle twice

### ISSUE THREAD

**Issue by xgid** [leo-editor/leo-editor#455]
This is best visually explained with images:

The initial layout (with the VR pane at the right-bottom):
![layout_with_vr_pane](https://cloud.githubusercontent.com/assets/12764559/24581637/a1965dca-16f5-11e7-8461-3d1fdc7bfce6.png)

The final layout after invoking vr-toggle twice:
![layout_with_vr_pane_after_toggle_twice](https://cloud.githubusercontent.com/assets/12764559/24581640/aaf2cd86-16f5-11e7-89b7-5d8c7739810c.png)

**Comment by edreamleo** [comment]
This does not happen for me, regardless of layout.

**Comment by LewisNeal** [comment]
Note I have initial_split_orientation = horizontal
Try this procedure:
Open LeoDocs, <alt-x> vr, drag the vertical bars to far left, to increase space for the vr pane, in a user set proportion.
Do <alt-x> vr-toggle
The outline body and vr panes now always open in a 1/3 proportion

So vr-toggle doesn't keep the users pane size preference.

**Comment by vitalije** [comment]
This bug tortured me for years. I prefer horizontal layout and in that case using vr was really annoying. It used to break layout every time it opens or closes rendering pane. Any command such as about-some-plugin or help would break layout. Finally, I can use vr and see what it offers. :smile:

**Comment by xgdomingo** [comment]
I'm sorry, but the fix is not working for me. I see the same exact 
behaviour than reported.

Config:
Leo 5.5, build 20170712142037, Wed Jul 12 14:20:37 CDT 2017
Git repo info: branch = master, commit = 840c257d1084
Python 3.5.2, PyQt version 5.6.2
Windows 10 AMD64 (build 10.0.15063) SP0
isPython3: True
caching enabled

**Comment by vitalije** [comment]
There are several versions of viewrendered plugin. I have fixed viewrendered.py. @xgid please, check that in at-enabled_plugins you have viewrendered.py not viewrendered2 or viewrendered3.

**Comment by xgid** [comment]
I have viewrendered.py. My full list of enabled plugins is:

plugins_menu.py
attrib_edit.py
contextmenu.py
leo_to_html.py
livecode.py
mod_scripting.py
nav_qt.py
nodetags.py
quicksearch.py
stickynotes.py
todo.py
viewrendered.py

backlink.py
bookmarks.py
chapter_hoist.py
mod_http.py
quickMove.py
startfile.py
wikiview.py

Any other info you may need?

**Comment by vitalije** [comment]
@xgid does it work for you? On my machine, when I first time execute vr command, vr pane appears to the right of body and all panes are equal  sized, but when I adjust them as I want, then later vr-hide and vr-open retain that layout. As I write this, I've just realized that perhaps it would be better when first opened that ratio between body and tree stays the same, vr pane should take just half of body space and should not move splitter between body and tree. Do you agree? Maybe that is what you expect and that is why it doesn't work for you?

**Comment by xgid** [comment]
> @xgid does it work for you? 

No, it does not! I'm **xgdomingo** also.

> On my machine, when I first time execute vr command, vr pane appears to the right of body and all panes are equal sized, but when I adjust them as I want, then later vr-hide and vr-open retain that layout. 

Mmmm, now I see that maybe I was not clear enought when I first reported the issue, in my first comment: I start with a layout where the vr pane is below the body pane. I have already adjusted the vr pane to my desired position. Then, if I run the vr-toggle twice (which is the same than vr-hide + vr-show) the vr pane appers again but this time **at the right of the body pane**, not below it as it should!! So this totally changes my layout disposition, it gets broken.

> As I write this, I've just realized that perhaps it would be better when first opened that ratio between body and tree stays the same, vr pane should take just half of body space and should not move splitter between body and tree. Do you agree? Maybe that is what you expect and that is why it doesn't work for you?

That seems as a good idea, but it does not have anything to do with my problem (described above).

Going to sleep now, will go on tomorrow.

**Comment by vitalije** [comment]
I have added menu command in context menu that is shown when right click in splitter handle. Its label is **Toggle split/dir. just this**. It takes two adjacent components and rotates them. If they were left and right of handle, they become above and below handle, and vice versa.

This command respects ratios both between two adjacent components and between them and rest of the layout.
HTH Vitalije

**Comment by xgid** [comment]
Thanks Vitalije.

The new command is working as expected for me, so I can regain my initial layout after vr-toggling twice. The good news are that from that moment on, any use of the vr-toggle command again *does NOT break* my layout any more! The split direction between the body pane and the vr pane are kept for the rest of the edition session for that file, even if I close and reopen the file without closing Leo. 
The bad news are that all this *good behaviour* is lost when I close and reopen Leo.

For the record: saving the layout *again* with its original name when everything is working right does not make any difference.

So it seems we are near...

Current config:
Leo 5.5, build 20170713051223, Thu Jul 13 05:12:23 CDT 2017
Git repo info: branch = master, commit = cc86d25ee2bd
Python 3.5.2, PyQt version 5.6.2
Windows 10 AMD64 (build 10.0.15063) SP0
isPython3: True
caching enabled

**Comment by vitalije** [comment]
I started to write to you @xgid that it won't be possible to solve this without another setting, and then I realized that this is something that can be easily stored in cache and restored when needed. In 	23c3d03, Leo will store vr layouts when user adjusts them in cache, and in next sessions cached versions will be used  as starting layouts. So your adjustments can survive closing and reopening Leo. 
I am personally very pleased with this solution. As I said this issue made me hate viewrendered plugin for years. Now I can enjoy using it. Thank you @xgid for giving me enough reason to refine it to this state. 
Vitalije

**Comment by tbnorth** [comment]
@vitalije - sounds like you're basically saving a nameless layout whenever the layout is adjusted, and then re-applying that next time Leo's loaded?  Great idea.  Just to keep the terminology clear, I wouldn't call them vr layouts unless you mean something by that I'm missing?  vr is supposed to just be a widget that presents rendered views of things.  I know it has some layout specific code associated with that, hopefully to be removed when QDocks take over.

**Comment by vitalije** [comment]
@tbnorth what I call layout is dict that you get from nested splitter using method get_saveable_layout.
Tuple of those *layouts* one when vr pane is not shown and the other when it is shown is stored in cache under the key `viewrendered_default_layouts`. When vr command is executed first time it needs a dict to send to nested splitter load_layout method. That value is retrieved from cache and applied. When vr-hide or vr-toggle is executed it stores current saveable layout in cache.

**Comment by xgid** [comment]
> I started to write to you @xgid that it won't be possible to solve this without another setting, and then I realized that this is something that can be easily stored in cache and restored when needed. 

Great idea!

> In 23c3d03, Leo will store vr layouts when user adjusts them in cache, and in next sessions cached versions will be used as starting layouts. So your adjustments can survive closing and reopening Leo.

I've made a test with the new code and as soon as I try to execute vr-toggle for the first time after opening Leo I get this Traceback:
```python
Traceback (most recent call last):
  File "C:\dev\Leo-5.4\leo\core\leoCommands.py", line 5578, in doCommand
    val = command(event)
  File "C:\dev\Leo-5.4\leo\plugins\viewrendered.py", line 483, in toggle_rendering_pane
    hide_rendering_pane(event)
  File "C:\dev\Leo-5.4\leo\plugins\viewrendered.py", line 422, in hide_rendering_pane
    vr.store_layout('open')
  File "C:\dev\Leo-5.4\leo\plugins\viewrendered.py", line 1358, in store_layout
    c.cacher.db['viewrendered_default_layouts'] = layouts[h]
KeyError: 'd:\\proj\\code\\coding\\coding.leo'
```

Do I have to clean all my current cache before opening Leo with the new code? Shouldn't it be handled in a backwards-compatible way by Leo?

> I am personally very pleased with this solution. As I said this issue made me hate viewrendered plugin for years. Now I can enjoy using it. Thank you @xgid for giving me enough reason to refine it to this state.

I'm glad to here it! But in fact it's been the culmination of a collaborative effort: it started with Edward's determination to fix all "[fit and finish problems](https://groups.google.com/d/msg/leo-editor/tJpKTPs045Y/rBV0fSH2CgAJ)" some months ago, then I put my "*beta tester*" hat on and opened 6 bugs in 30 minutes two days later (including this one) and finally you've added your qualities to the mix by "fixing bugs as a mad man" :laughing: and fixing like 10 bugs in three days!?

I seriously think that the main ingredients for the success in this case have been the quest for **Excellence** (which is not the same than Perfection), a good **Teamwork** and high doses of **[Determination](http://www.thefreedictionary.com/determination)**.

Let's keep up the good work!
Xavier

**Comment by tbnorth** [comment]
@vitalije ah, ok, then "vr layouts" makes sense.  Clever fix but hopefully wouldn't be needed with better pane management api.  Also historical equivocation between vr widget being singleton or not.  Anyway, clever fix.

**Comment by vitalije** [comment]
@xgid try witho 3564f1b. It should fix the issue. It is required that cache is enabled which I presume is by default. There should be a line in Log pane during initialization that says: `caching enabled`

**Comment by xgid** [comment]
> @xgid try witho 3564f1b. It should fix the issue. It is required that cache is enabled which I presume is by default. There should be a line in Log pane during initialization that says: caching enabled

Perfect! It's working now. Yes, I have caching enabled.

The only thing is that I have to repair the layout of every single Leo file I have... but at least is a one-time fix and it get's solved for ever.

Many thanks for your determination!
Xavier
