### ISSUE TITLE
Chapters drop-down list is not automatically resized

### ISSUE THREAD

**Issue by xgid** [leo-editor/leo-editor#458]
The size of the Chapters drop-down list is not resized when new "@chapter" directives are added to headlines which are longer than the previously existing ones, so the new chapter names cannot be read:
![Chapters drop-down list after some new @chapter directives added](https://cloud.githubusercontent.com/assets/12764559/24581839/6ff64196-16f9-11e7-90be-338e7e1de05d.png)

This is only fixed by closing and opening again the .leo file.

**Comment by edreamleo** [comment]
You may have to click the combo box twice to get the resize to happen, but that's a Qt bug...

**Comment by xgid** [comment]
Perfect! It's working for me. Thanks

> You may have to click the combo box twice to get the resize to happen

Yes, I have to. No problem.
