### ISSUE TITLE
Missing end-of-line characters at the Log Pane

### ISSUE THREAD

**Issue by xgid** [leo-editor/leo-editor#459]
Another minor issue one can live with, but which would preferably be also solved:
There are many messages appearing at the Log Pane that do not have the EOL character. That makes them concatenate in long strings which are quite difficult to read.

An example:
> reading settings in D:\proj\code\leo\Pruebas de Leo.leowrote recent file: C:\Users\sysadmin\.leo\.leoRecentFiles.txtsaved: Bugs de Leo.leo

Should be:
> reading settings in D:\proj\code\leo\Pruebas de Leo.leo
> wrote recent file: C:\Users\sysadmin\.leo\.leoRecentFiles.txt
> saved: Bugs de Leo.leo

This is my current configuration:
```
Leo Log Window
Leo 5.5, build 20170328155245, Tue Mar 28 15:52:45 CDT 2017
Git repo info: branch = master, commit = fa7ebc9a6515
Python 3.5.2, PyQt version 5.6.2
Windows 10 AMD64 (build 10.0.14393) SP0
```

**Comment by edreamleo** [comment]
Strange.  Such problems have never been reported before on any platform.  They do not happen for me.

**Comment by xgid** [comment]
I've been able to get some time to dive into this issue by making some code exploration and have found kind of a pattern: the function that is working properly for me (in the sense that prints messages with correct EOL characters) is `g.es`. Other functions, like `g.pr` or `message` are not printing the EOL.

I've found this after looking at the code that is printing the following three messages:
1. saved: xxxx.leo
2. wrote recent file: C:\\Users\\xxxx\\.leo\\.leoRecentFiles.txt
3. reading settings in xxxx.leo

The first one is always printed **with correct EOL**, and it happens to be using this code:
```python
def putSavedMessage(self, fileName):
    c = self.c
    zipMark = '[zipped] ' if c.isZipped else ''
    g.es("saved:", "%s%s" % (zipMark, g.shortFileName(fileName)))
```

The other two messages which are always printed **WITHOUT proper EOL** are using these other codes:
```python
if not g.app.silentMode:
    g.pr('wrote recent file: %s' % fileName
```

```python
if theFile:
    message('reading settings in %s' % (fn))
```

I've also tried changing both `g.pr` and `message` to `g.es` and **the problem gets fixed**!... but I'm not in a position to know if this is the correct fix. I supose other uses of g.pr and message should be reviewed also. Can they all be safely changed to use `g.es`?

**Comment by edreamleo** [comment]
@xgid: > I've also tried changing both g.pr and message to g.es and the problem gets fixed!... but I'm not in a position to know if this is the correct fix.

Thanks for your sleuthing.  g.pr is supposed to be a wrapper around Python's print statement, but things are complicated during startup, when the log pane does not exit.  What "should" happen depends on context.  I'll look at this today.

**Comment by edreamleo** [comment]
This has turned into a project.  I have created the [signon branch](https://github.com/leo-editor/leo-editor/tree/signon) to work on this.

The g.es method has little choice but to queue messages during startup, but the same can not be said of g.pr and the "g.pr" parts of g.red and g.es_print, both of which call g.pr.  As I see it now, **g.pr should "print" immediately using sys.stdout.**

Actually, this is what g.pr has been doing (at least recently) because the print_immediately switch in g.pr has been set to True.  But imo, g.pr should *always* print immediately.

Following the "explicit is better than implicit" principle, the startup logic should call g.pr when the print statements should actually be printed.  That is, g.pr should never do any queuing.  This will complicate the startup logic, but imo it is the best way.

Furthermore, g.pr and g.es share considerable logic.  It may be time to create a new helper.

All of the above is a bit speculative, but I think simplifying g.pr is the right thing to do.  There have been a lot of bugs reported against g.pr.  It's time to make it work more reliably.

**Comment by edreamleo** [comment]
Rev e31382d in the signon branch attempts a fix for this item.

**Comment by xgid** [comment]
Hi Edward and thanks for your fast answer!

I've checked out the signon branch and given it a try, but there are situations in that the EOLs are still missing. At least with the "reading settings in..." message, I got this after opening several files:

```
read outline in 0.04 seconds
reading settings in D:\proj\code\pyprojects\Libs.leo
reading settings in D:\proj\code\pyprojects\graphene.leoreading settings in D:\proj\code\pyprojects\Leo.leoreading settings in C:\dev\Leo-5.4\leo\doc\LeoDocs.leo
```

So sometimes the same message is printed with the EOL and sometimes not! Ups...

**Comment by edreamleo** [comment]
> with the "reading settings in..." message, I got this after opening several files:
> reading settings in <file 1>reading settings in <file 2>...

Thanks.  It should be possible to track this down.

**Comment by edreamleo** [comment]
Please try rev 1e6058c of the signon branch.

The code looks messier than before, because it contains several experiments. In fact, the code is significantly simpler.  Indeed, the `from_redirect` keyword arg in `LeoQtLog.put` is no longer an evil switch.  Now, the code only does one thing, namely convert all '\n' characters to `<br>` html elements.

It there are still problems, please set `trace = True` in `LeoQtLog.put` and report the full contents of the *console* traces.

**Comment by xgid** [comment]
Ha! It's going to be funnier than I thought: with the latest commit in the signon branch it is still failing, but... when I have set `trace = True` in `LeoQtLog.put` it has worked like a charm!! Arrrrgg!

Here are the requested traces, although I don't think they will be of any use:
```
C:\dev\Leo-5.4>python.exe launchLeo.py

reading settings in C:\dev\Leo-5.4\leo\config\leoSettings.leo
reading settings in C:\Users\sysadmin\.leo\myLeoSettings.leo

Leo 5.5, build 20170706102121, Thu Jul  6 10:21:21 CDT 2017
Git repo info: branch = signon, commit = c87c5e8c2547
Python 3.5.2, PyQt version 5.6.2
Windows 10 AMD64 (build 10.0.14393) SP0
** isPython3: True
** caching enabled

reading settings in C:\Users\sysadmin\.leo\workbook.leo
LeoQtLog.log.put: 'Leo Log Window\n'
LeoQtLog.log.put: 'Leo 5.5, build 20170706102121, Thu Jul  6 10:21:21 CDT 2017\n'
LeoQtLog.log.put: 'Git repo info: branch = signon, commit = c87c5e8c2547\n'
LeoQtLog.log.put: 'Python 3.5.2, PyQt version 5.6.2\nWindows 10 AMD64 (build 10.0.14393) SP0\n'
LeoQtLog.log.put: 'isPython3: True\n'
LeoQtLog.log.put: 'caching enabled\n'
LeoQtLog.log.put: "leoID='xgid'\n"
LeoQtLog.log.put: 'load dir: C:\\dev\\Leo-5.4\\leo\\core\n'
LeoQtLog.log.put: 'global config dir: C:\\dev\\Leo-5.4\\leo\\config\n'
LeoQtLog.log.put: 'home dir: C:\\Users\\sysadmin\n'
LeoQtLog.log.put: 'reading settings in C:\\dev\\Leo-5.4\\leo\\config\\leoSettings.leo\n'
LeoQtLog.log.put: 'reading settings in C:\\Users\\sysadmin\\.leo\\myLeoSettings.leo\n'
LeoQtLog.log.put: 'http serving enabled at 127.0.0.1:8130\n'
LeoQtLog.log.put: 'reading settings in C:\\Users\\sysadmin\\.leo\\workbook.leo\n'
LeoQtLog.log.put: 'reading: C:\\Users\\sysadmin\\.leo\\workbook.leo\n'
LeoQtLog.log.put: 'not found: C:\\Users\\sysadmin\\.leo\\prueba3.md\n'
LeoQtLog.log.put: 'read 1 files in 0.00 seconds\n'
LeoQtLog.log.put: 'read outline in 0.02 seconds\n'
LeoQtLog.log.put: '\n'
reading settings in C:\dev\Leo-5.4\leo\doc\CheatSheet.leo
LeoQtLog.log.put: 'reading settings in C:\\dev\\Leo-5.4\\leo\\doc\\CheatSheet.leo\n'
LeoQtLog.log.put: 'Leo Log Window\n'
LeoQtLog.log.put: 'Leo 5.5, build 20170706102121, Thu Jul  6 10:21:21 CDT 2017\n'
LeoQtLog.log.put: 'Git repo info: branch = signon, commit = c87c5e8c2547\n'
LeoQtLog.log.put: 'Python 3.5.2, PyQt version 5.6.2\nWindows 10 AMD64 (build 10.0.14393) SP0\n'
LeoQtLog.log.put: 'isPython3: True\n'
LeoQtLog.log.put: 'caching enabled\n'
LeoQtLog.log.put: 'reading: C:\\dev\\Leo-5.4\\leo\\doc\\CheatSheet.leo\n'
LeoQtLog.log.put: 'read outline in 0.02 seconds\n'
wrote recent file: C:\Users\sysadmin\.leo\.leoRecentFiles.txt
LeoQtLog.log.put: 'wrote recent file: C:\\Users\\sysadmin\\.leo\\.leoRecentFiles.txt\n'
reading settings in C:\Users\sysadmin\.leo\myLeoSettings.leo
LeoQtLog.log.put: 'reading settings in C:\\Users\\sysadmin\\.leo\\myLeoSettings.leo\n'
LeoQtLog.log.put: 'Leo Log Window\n'
LeoQtLog.log.put: 'Leo 5.5, build 20170706102121, Thu Jul  6 10:21:21 CDT 2017\n'
LeoQtLog.log.put: 'Git repo info: branch = signon, commit = c87c5e8c2547\n'
LeoQtLog.log.put: 'Python 3.5.2, PyQt version 5.6.2\nWindows 10 AMD64 (build 10.0.14393) SP0\n'
LeoQtLog.log.put: 'isPython3: True\n'
LeoQtLog.log.put: 'caching enabled\n'
LeoQtLog.log.put: 'reading: C:\\Users\\sysadmin\\.leo\\myLeoSettings.leo\n'
LeoQtLog.log.put: 'read outline in 0.03 seconds\n'
reading settings in C:\dev\Leo-5.4\leo\doc\quickstart.leo
LeoQtLog.log.put: 'reading settings in C:\\dev\\Leo-5.4\\leo\\doc\\quickstart.leo\n'
LeoQtLog.log.put: 'Leo Log Window\n'
LeoQtLog.log.put: 'Leo 5.5, build 20170706102121, Thu Jul  6 10:21:21 CDT 2017\n'
LeoQtLog.log.put: 'Git repo info: branch = signon, commit = c87c5e8c2547\n'
LeoQtLog.log.put: 'Python 3.5.2, PyQt version 5.6.2\nWindows 10 AMD64 (build 10.0.14393) SP0\n'
LeoQtLog.log.put: 'isPython3: True\n'
LeoQtLog.log.put: 'caching enabled\n'
LeoQtLog.log.put: 'reading: C:\\dev\\Leo-5.4\\leo\\doc\\quickstart.leo\n'
LeoQtLog.log.put: 'read outline in 0.02 seconds\n'
LeoQtLog.log.put: 'saved: workbook.leo\n'
```

Anything else I can do from my side?

**Comment by xgid** [comment]
Uau!! I've found the "reason" why it failed for me before and it worked when I activated the trace: it has nothing to do with the trace flag, it has to do with the fact that when it fails is when I launch Leo using `pythonw.exe`!! 
When I lauch Leo using `python.exe` (as was the case to get the full _console_ traces), it works perfectly!

That seems really weird to me!! Any idea about why that could change the way that messages are sent to the Log pane?

**Comment by edreamleo** [comment]
On Thu, Jul 6, 2017 at 2:20 PM, XGiD <notifications@github.com> wrote:

> Ha! It's going to be funnier than I thought: with the latest commit in the
> signon branch it is still failing, but... when I have set trace = True in
> LeoQtLog.put it has worked like a charm!! Arrrrgg!
>
​The traces show that all lines end with a newline.

You can try setting ​trace_s = True in LeoQtLog.put to see the resulting
html.  Hmm.  I wonder whether all html escapes are done properly...

It should be possible to see the entire resulting html string after each
call.  It might be possible to check the html for validity.

I really like the work done in this branch.  I'm going to clean it up and
merge it sooner rather than later.

Edward

**Comment by edreamleo** [comment]
On Thu, Jul 6, 2017 at 3:27 PM, XGiD <notifications@github.com> wrote:

> Uau!! I've found the "reason" why it failed for me before and it worked
> when I activated the trace: it has nothing to do with the trace flag, it
> has to do with the fact that when it fails is when I launch Leo using
> pythonw.exe!!
>
​Thanks for this sleuthing. I wonder whether it has something to do with
different definitions of sys.stdout.

What happens when you disable all plugins with --no-plugins?

Edward

**Comment by xgid** [comment]
> What happens when you disable all plugins with --no-plugins? 

FYI, nothing changes. It fails in the same way when using "pythonw.exe".

**Comment by xgid** [comment]
> You can try setting ​trace_s = True in LeoQtLog.put to see the resulting html. Hmm. I wonder whether all html escapes are done properly...

The problem is that even if I set that traces I cannot see them when I run Leo with `pythonw.exe`. Well, in fact I cannot even start Leo in that case because it closes right after opening!

**Comment by edreamleo** [comment]
On Thu, Jul 6, 2017 at 7:55 PM, XGiD <notifications@github.com> wrote:

> You can try setting ​trace_s = True in LeoQtLog.put to see the resulting
> html. Hmm. I wonder whether all html escapes are done properly...
>
> The problem is that even if I set that traces I cannot see them when I run
> Leo with pythonw.exe. Well, in fact I cannot even start Leo in that case
> because it closes right after opening!
>
​Something is clearly amiss on your end.​
 I just ran Leo with pythonw.exe (the Anaconda version) from a console and
all went well. As expected, there was no output to the console, but all
output to Leo's log pane looks good.

Edward

**Comment by xgid** [comment]
>  I just ran Leo with pythonw.exe (the Anaconda version) from a console and all went well.

OK, that's an important test. So I think that the work done so far in this issue is more than enough. There are more important issues to work at the moment!! I think you may close the issue. 

I'll try to make a clean install of Anaconda (this time with 3.6 version) and see what I get, but that's clearly something on my side.

Thanks for all your attention, Edward.

**Comment by edreamleo** [comment]
On Thu, Jul 6, 2017 at 9:51 PM, XGiD <notifications@github.com> wrote:

> I'll try to make a clean install of Anaconda (this time with 3.6 version)
> and see what I get, but that's clearly something on my side.
>
> Thanks for all your attention, Edward.
>
​You're welcome.  The cleanups were worth it.

Edward
