### ISSUE TITLE
"insertKeyEvent XX <...>" messages appearing at the Log pane

### ISSUE THREAD

**Issue by xgid** [leo-editor/leo-editor#461]
For some time now, whenever I insert a character whose key combination includes `Alt Gr` (as for example, `Alt Gr-1` to insert `|`, `Alt Gr-2` to insert `@` and so on), a message like the following one appears at the Log pane:

> insertKeyEvent 36 <PyQt5.QtCore.KeyboardModifiers object at 0x0B002830> |

This has been so for quite a long time, quite before 5.5 release, but I cannot say from when. Or even if it's been always this way since I installed Leo 5.4.

**Comment by edreamleo** [comment]
Fixed at 0c57725 by removing a trace.  Such things are easy to fix.  Too bad you waited so long ;-)
