### ISSUE TITLE
File-open-by-name command: Add a setting to define preferred directory

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#467]
Request to add a setting to define a preferred directory path for the 'File-open-by-name' command
Possibilties:
1. linked to the path of last file opened as per leoRecentFiles.txt
or
2. a quick setting in the menu area of Cmds> Files-and-Directories>

Also consider the same path setting for the menu items:
Cmds> Files-and-Directories> Directory-Make and Directory-Remove
         > Files-and-Directories> (all 'File' commands)

Would this setting be made in myLeoSettings.leo ?

**Comment by edreamleo** [comment]
> Would this setting be made in myLeoSettings.leo ?

@LewisNeal The setting itself would appear both in leoSettings.leo and myLeoSettings.leo. The user would change the latter.

**Comment by tbnorth** [comment]
I think it's more useful to start from the last directory used. I.e. just store that in c.db (or g.db, but c.db seems much more helpful).

The tricky part with Leo is that you can associate a directory with c.p, so there as 2-3 candidates for the starting directory for open file by name, the last directory the user used (my first choice), the directory associated with c.p, or a static setting.

It would be nice if OS file dialog API's included a way to add some directories the user could jump between, in addition to the way they usually give quick links to Desktop, $HOME, etc.
