### ISSUE TITLE
Toggling find settings destroys selection in minibuffer

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#469]
For example:

- `Alt-X cff` shows `<find pattern here>` in minibuffer, selected.
- `Alt-Ctrl-W` toggles "word" match, but also clears selection in minibuffer.

This is an annoying fit and finish issue.

**Comment by LewisNeal** [comment]
This is not limited to Alt-Ctrl-W
Anytime you run <Alt-x> activating the minibuffer ready for entry, then <Alt-Tab> toggle to any other window (e.g. "File explorer"), then <Alt-Tab> back to Leo, it always cancels the minibuffer, with the cursor resuming in the body pane.

**Comment by edreamleo** [comment]
On Fri, Apr 7, 2017 at 5:38 AM, LewisNeal <notifications@github.com> wrote:

> This is not limited to Alt-Ctrl-W
> Anytime you run activating the minibuffer ready for entry, then toggle to
> any other window (e.g. "File explorer"), then back to Leo, it always
> cancels the minibuffer, with the cursor resuming in the body pane.
>
​That's by design.  The behavior described is a problem only when using the
minibuffer-based Find commands, that is, when @bool minibuffer_find_mode is
True.

Edward

**Comment by edreamleo** [comment]
Rev 5d5eb8b fixes a recent crasher on loading unitTest.leo.  Did you run unit tests?

**Comment by vitalije** [comment]
@edreamleo I almost always run unit test before final commit. I can't guarantee that I did for this particular commit, however, this morning I checked out this commit 576c84c and ran unit test without any failure or exception. 
```
End of plugins unit tests
.@test print redraw count: 641
..all unit tests done
..
----------------------------------------------------------------------
Ran 916 tests in 95.157s

OK (skipped=45)
```

I have noticed throughout gui code lots of those checks whether we are unit testing or not, and I suppose they make sense. What I don't understand is when they are in effect? This is how I was recently explained to do unit tests:

1. open leo/test/unitTest.leo, a node `active unit tests` is selected by default
2. press `Alt-4` (run unit tests locally)
3. wait for tests to finish

Are there some other tests that I should be executing? Perhaps, some externally-ran-tests?

**Comment by edreamleo** [comment]
On Fri, Jul 14, 2017 at 12:32 AM, Виталије Милошевић <
notifications@github.com> wrote:

> @edreamleo <https://github.com/edreamleo> I almost always run unit test
> before final commit. I can't guarantee that I did for this particular
> commit, however, this morning I checked out this commit 576c84c
> <https://github.com/leo-editor/leo-editor/commit/576c84c8186366baf82c28d9f9a3691b83b8a211>
> and ran unit test without any failure or exception.
>
​That's fine.  I can't ask for anything more.  I was just checking that you
typically run unit tests.

Many thanks for the care with which you approach your tasks. Your work is
exemplary.

I have noticed throughout gui code lots of those checks whether we are unit
> testing or not, and I suppose they make sense. What I don't understand is
> when they are in effect


​​I​ just ran a cff on g.unitTesting, limited to ​the qt gui files. There
were 138 matches. ​


​Most tests on g.unitTesting affect only traces during unit testing.​

​I typically don't want traces cluttering unit tests.  Otoh, sometimes I
want traces only *during* unit tests.​


​Here is the complete list of all the other tests against g.unitTesting in
the qt code:

1. Suppress splash screen, dialogs, alerts, etc during unit tests:

  qt_gui.__init__: suppress splash screen.
  qt_gui.dismiss_splash_screen:
  qt_gui.alert:
  qt_gui.openFindDialog
  qt_gui.run*Dialog

2. qt_gui.put_help: don't alter the vr pane.

3. Alter or suppress redraw during unit tests.  I'm not sure why these
exist, and I'm not sure they are a good idea.  I may look at these as part
of #503 <https://github.com/leo-editor/leo-editor/issues/503>.

  qtree.afterSelectHint: not sure why this test is a good idea.
  qtree.onHeadChanged: a comment about a "crucial shortcut"

4. Miscellaneous:

  qtFrame.minimizeAll: do nothing during unit tests
​  qtFrame.resizeToScreen: ditto​
  ssm.set selected_style_sheet: ditto

> This is how I was recently explained to do unit tests:
>
>    1. open leo/test/unitTest.leo, a node active unit tests is selected by
>    default
>    2. press Alt-4 (run unit tests locally)
>    3. wait for tests to finish
>
> ​Correct.​


>
>
> Are there some other tests that I should be executing? Perhaps, some
> externally-ran-tests?
>
​No.  No need to do this.

Edward

**Comment by vitalije** [comment]
Thanks for confirmation and detailed explanation.

**Comment by edreamleo** [comment]
On Fri, Jul 14, 2017 at 7:02 AM, Виталије Милошевић <
notifications@github.com> wrote:

> Thanks for confirmation and detailed explanation.
>

​You're welcome.

Edward
