### ISSUE TITLE
UnicodeDecodeError in writeRecentFilesFileHelper

### ISSUE THREAD

**Issue by whatacold** [leo-editor/leo-editor#471]
There is a file encoding bug in Leo, I first noticed this bug in Leo 5.4, and confirm that it's still in Leo 5.5.

I'm using Leo 5.5 on Windows 7 professional, Simplified Chinese version, with Python 3.5.
Here is in the log panel:

    Leo Log Window
    Leo 5.5, build 20170322112633, Wed Mar 22 11:26:33 CDT 2017
    Not running from a git repo
    Python 3.5.2, PyQt version 5.7.0
    Windows 7 AMD64 (build 6.1.7601) SP1

If I create a plain leo file, and then save it to, say test.leo, in a folder named 'D:\test域外\', it works well.
Then I do some editing and save it again, this time it will throw out a trackback:

    Traceback (most recent call last):
      File "D:\tools\Leo-5.5\leo\core\leoGlobals.py", line 1733, in wrapper
        func(self, event=event)
      File "D:\tools\Leo-5.5\leo\core\leoCommands.py", line 2354, in save
        c.fileCommands.save(c.mFileName)
      File "D:\tools\Leo-5.5\leo\core\leoFileCommands.py", line 1401, in save
        ok = self.write_Leo_file(fileName, False) # outlineOnlyFlag
      File "D:\tools\Leo-5.5\leo\core\leoFileCommands.py", line 1817, in write_Leo_file
        g.app.recentFilesManager.writeRecentFilesFile(c)
      File "D:\tools\Leo-5.5\leo\core\leoApp.py", line 3412, in writeRecentFilesFile
        rf.writeRecentFilesFileHelper(fileName)
      File "D:\tools\Leo-5.5\leo\core\leoApp.py", line 3421, in writeRecentFilesFileHelper
        lines = theFile.readlines()
    UnicodeDecodeError: 'gbk' codec can't decode byte 0xa4 in position 11: illegal multibyte sequence

At this time, saving any file is not possible.

With Notepad++'s help, I find that .leoRecentFiles.txt is encoded in UTF-8, as opposed to GBK, which is expected by Leo as in the traceback.

Also, there is another bug after this exception: If I try to close the file by click the X icon of that file, the Leo program quits.

**Comment by edreamleo** [comment]
Thanks for this report.  I'll attempt a fix immediately.

**Comment by edreamleo** [comment]
Rev 6826481 attempts a fix. As noted in the checkin log, these changes are speculative because I have not been able to duplicate the problem.

**Comment by whatacold** [comment]
Just confirmed that this is fixed with today's build:

    Leo Log Window
    Leo 5.5, build 20170416090704, Sun Apr 16 09:07:04 CDT 2017
    Not running from a git repo
    Python 3.5.2, PyQt version 5.7.0
    Windows 7 AMD64 (build 6.1.7601) SP1

Thanks for your work!

**Comment by edreamleo** [comment]
On Mon, Apr 17, 2017 at 8:33 AM, whatacold <notifications@github.com> wrote:

> Just confirmed that this is fixed with today's build:
>
> Leo Log Window
> Leo 5.5, build 20170416090704, Sun Apr 16 09:07:04 CDT 2017
> Not running from a git repo
> Python 3.5.2, PyQt version 5.7.0
> Windows 7 AMD64 (build 6.1.7601) SP1
>
> Thanks for your work!
>

​You're welcome.  Thanks for the confirmation.

Edward
