### ISSUE TITLE
nav_qt buttons do not reload if file is re-opened

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#473]
To reproduce:
open Leodocs.leo, the Nav_qt arrows appear
close the file, keep Leo running.
re-open LeoDocs.leo, the Nav_qt arrows don't appear.

This occurs with any leo file.

Leo 5.5, build 20170416090704, Sun Apr 16 09:07:04 CDT 2017
Git repo info: branch = master, commit = 543f52dfb090
Python 3.6.1, PyQt version 5.8.0
Windows 10 AMD64 (build 10.0.14393) SP0

**Comment by devadrian1** [comment]
Although I am very new to Leo, this appears to be related to behavior I noticed.  Triggering an action that opens up the 'viewrendered' pane, will successfully do so the first time an outline is open.

If you close and re-open the outline, that same option has no effect.  The viewrended pane will not open.

**Comment by edreamleo** [comment]
On Wed, Jul 12, 2017 at 12:39 PM, Виталије Милошевић <
notifications@github.com> wrote:

> Closed #473 <https://github.com/leo-editor/leo-editor/issues/473> via
> 844f219
> <https://github.com/leo-editor/leo-editor/commit/844f21992cb79d1465f582dc3a3826a0666331b1>
> .
>
​Once again, many thanks to you, Vitalije, for this fix.  Your fixes are
brilliantly simple.

Edward

**Comment by LewisNeal** [comment]
And again, thanks Vitalije.
Lewis
