### ISSUE TITLE
contract-log-pane and expand-log-pane not working

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#476]
Commands contract-log-pane, expand-log-pane and fully-expand-log-pane are not working.

Also, if I put focus in the log pane, the contract-pane and expand-pane commands don't work.
Just reporting  - I don't use the log-pane commands.

Leo 5.5, build 20170426053947, Wed Apr 26 05:39:47 CDT 2017
Git repo info: branch = master, commit = b39641226228
Python 3.6.1, PyQt version 5.8.0
Windows 10 AMD64 (build 10.0.14393) SP0

**Comment by tbnorth** [comment]
On Wed, 26 Apr 2017 04:11:45 -0700
LewisNeal <notifications@github.com> wrote:

> Commands contract-log-pane and expand-log-pane are not working.
> Also, if I put focus in the log pane, the contract-pane and
> expand-pane commands don't work. Just reporting  - I don't use the
> log-pane commands.

free-layout-zoom toggles full expansion of the selected pane.
contract-log-pane and expand-log-pane are different of course -
free-layout-zoom is probably more equivalent to fully-epand-log-pane,
although that only expands against the tree, not the whole window.

All this will need revisiting if the qt_docks UI moves forward.

All that said, none of this is directly relevant to Lewis's bug, and
just to further complicate, they seem to work for me:

Leo 5.5, build 20170425071323, Tue Apr 25 07:13:23 CDT 2017
Git repo info: branch = master, commit = 023713edf66d
Python 2.7.12, PyQt version 5.5.1
linux2

**Comment by LewisNeal** [comment]
The contract-log-pane, expand-log-pane and fully-expand-log-pane commands seem to be affected by a LEP script I had in a leo file. I can't explain exactly what's going on as if I change to another leo file the behaviour is different. I can't describe the behaviour with certainty so feel free to close my original comment.
I played with the 'free-layout-zoom' command and created a button. The button works on first press, but not on the second press. You need to issue the second 'free-layout-zoom' cmd in the minibuffer.
Why is that?
Let me know if I should move this free-layout discussion to another issue or the group discussion.

**Comment by tbnorth** [comment]
On Thu, 27 Apr 2017 03:53:37 -0700
LewisNeal <notifications@github.com> wrote:

> The contract-log-pane, expand-log-pane and fully-expand-log-pane
> commands seem to be affected by a LEP script I had in a leo file. I
> can't explain exactly what's going on as if I change to another leo
> file the behaviour is different. I can't describe the behaviour with
> certainty so feel free to close my original comment. I played with
> the 'free-layout-zoom' command and created a button. The button works
> on first press, but not on the second press. You need to issue the
> second 'free-layout-zoom' cmd in the minibuffer. Why is that? Let me
> know if I should move this free-layout discussion to another issue or
> the group discussion.

The LEP script is probably having an effect simply by adding a pane to
the layout - assuming it does that.  The free layout system, accessed
via the "easter egg" context menu on the splitter dividers, has
probably never fully supported the Leo's previous pane manipulation
commands.  Not sure about the zoom issue, I have it bound to a key,
works as expected there.

Although the time line is unclear, the plan is to replace the
free_layout system with QtDocks, the project is currently at proof of
concept stage.  So unless any of these issues are disrupting workflow,
they could probably be closed as "Won't fix" or maybe "Deprecated"?

**Comment by edreamleo** [comment]
I am going to close this issue.  These commands work now.

Terry, feel free to add an info label and reopen if this helps you.
