### ISSUE TITLE
Host Leo's web site on GitHub

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#480]
My brother Speed approves.

**Comment by edreamleo** [comment]
We would use [GitHub pages](https://pages.github.com/). The introductory video mentions [jekyll](https://jekyllrb.com/). The summary of jekyll: transform plain text into static web sites. Jekyll is optional.

A big advantage of GitHub pages is that the web site is part of a separate GitHub repo, so all of git's features apply. I plan to do this asap.

**Comment by edreamleo** [comment]
**Update**: My brother Speed redirected leo-editor.com yesterday. At present I do not see the change, but it may take up to 24 hours to propagate.

**Comment by LewisNeal** [comment]
Leo 5.6 is released, however the new site http://leo-editor.github.io/leo-editor/ still refers to 'Leo 5.5 documentation'

**Comment by edreamleo** [comment]
@LewisNeal Thanks for the heads up about version numbers.  At present, the github.io site is in limbo.  Not sure when this is going to change.

**Comment by technatica** [comment]
I would be willing to take a run at this.

I just moved my personal site (chrisgeorge.ca) to github pages. The trickiest part was figuring out where to change the A records for the domain.

I use Nikola (like Jekyll, but python instead of ruby) to publish my site. It uses rst as its default markup. It would be relatively easy (I think) to have Leo output the docs in a way that Nikola could use as raw material.

**Comment by tbnorth** [comment]
On Sat, 13 Jul 2019 06:05:31 -0700
Chris George <notifications@github.com> wrote:

> I would be willing to take a run at this.
> 
> I just moved my personal site (chrisgeorge.ca) to github pages. The
> trickiest part was figuring out where to change the A records for the
> domain.
> 
> I use Nikola (like Jekyll, but python instead of ruby) to publish my
> site. It uses rst as its default markup. It would be relatively easy
> (I think) to have Leo output the docs in a way that Nikola could use
> as raw material.

Sphinx seems to be hanging in there as the leading Python doc.
generator.  But I'm curious to look at Nikola, I've used Pelican which
is sometimes put forward as an alternative to Jekyll, but seems a
little light weight to me sometimes.

Cheers -Terry

**Comment by tbnorth** [comment]
p.s. Liking the look of Nikola for as a static site generator, it uses
doit and jinja2 both of which I've used a bit.

Still think Sphinx might be hard to hard to go past for the domain
specific role of documenting Python software.

Cheers -Terry

**Comment by technatica** [comment]
I think rst and Sphinx are unbeatable for documentation and see no reason to change that.

Given that the website currently runs off of it I simply envision moving it from where it is now to github.

**Comment by maphew** [comment]
I just enabled GH pages for master branch. The effect is a 1 page website rendered from `/Readme.md`, see http://leo-editor.github.io/leo-editor/. Cleaner would be to create a `/docs` folder in _master_ branch and begin putting website content in it. (This way it's always clear what's published to the website and what's just another file somewhere in Leo.)

There's a Nikola [asciidoc plugin](https://plugins.getnikola.com/v8/asciidoc/), so moving on this issue could harmonize well with #1147 of using asciidoc generally, or at least not be at cross purposes.

There is some overlap between Nikola and Leo's new adoc command, in that they both create html from a text file source. Being focused on publishing I imagine Nikola has more power tools to bring to the table. Incremental builds comes to mind.

I just learned that GH supports asciidoc already:
https://gist.github.com/dcode/0cfbf2699a1fe9b46ff04c41721dda74
so maybe neither Leo's adoc command or Nikola are required (for purpose of hosting Leo's documentation website).

Also
http://leo-editor.github.io/ is currently home to a forgotten shared Leo blog. Repo here at https://github.com/leo-editor/leo-editor.github.io. I'll look into what's needed to move that out of the way so http://leo-editor.github.io/leo-editor/ can use the bare domain url. (Unless you are already familiar with that Chris?)

After `http://leo-editor.github.io/` is publishing docs to Edward's satisfaction we can look at the changing the domain records for leo-editor.com. Sound like a plan?

**Comment by maphew** [comment]
> I just enabled GH pages for master branch

For repo's which are organizations, like Leo, these are the only supported source configurations:
- `master` branch
- `/docs` folder in `master` branch 
- a branch named `gh-pages`

I think we should use the last while in development phase. That way the master branch history will stay clean.

**Comment by edreamleo** [comment]
On Sun, Jul 14, 2019 at 3:49 AM matt wilkie <notifications@github.com>
wrote:

> I just enabled GH pages for master branch
>
> For repo's which are organizations, like Leo, these are the only supported
> source configurations:
>
>    - master branch
>    - /docs folder in master branch
>    - a branch named gh-pages
>
> I think we should use the last while in development phase. That way the
> master branch history will stay clean.
>
I agree.

Edward

**Comment by technatica** [comment]
Okey dokey.

The website is now up on github and live at http://leo-editor.github.io/leo-editor

That was fun.

Now for the rest of it.

I do a little webhosting on the side. I use custom nameservers for all of my domains so making the changes to DNS was a bit more complex than the instructions were prepared to cover when I setup my personal site.

I am not anticipating that it will be difficult to switch the DNS zone info as it is unlikely that you use a custom nameserver for your hosting. 

Edward: Easiest would be to give me the login/password for the domain registrar so I can make the changes. The password can then be changed after I am done. Harder would be to play tag with you/Speed/domain registrar/github until it works. 

Let me know.

Chris

**Comment by technatica** [comment]
The gh-pages branch is a permanent thing. No merging into anything required.

**Comment by edreamleo** [comment]
On Sun, Jul 14, 2019 at 10:31 AM Chris George <notifications@github.com>
wrote:

> Okey dokey.
>
> The website is now up on github and live at
> http://leo-editor.github.io/leo-editor
>

Well done!  I'll investigate when I have time.

Edward

**Comment by maphew** [comment]
Looks great!

So all content within _gh-pages_ is the result, correct?
Where does or will the files to create the results live and be managed?

**Comment by technatica** [comment]
The website is generated from a few @file nodes and LeoDocs.leo using the
rst3 command and Sphinx to produce the html.

It will live in the gh-pages branch for as long as it is hosted at github.

Chris

**Comment by maphew** [comment]
What's the workflow to update the website? 

My understanding looks something like this:
```
git checkout master
leo leo\doc\LeoDocs.leo
# <<run rst3 command>>
# <<move output html somewhere>>
git checkout gh-pages
# <<move output html to top of gh-pages>>
git commit -m "website update for ..."
git push
```

**Comment by technatica** [comment]
Pretty much exactly that.

Chris

**Comment by maphew** [comment]
http://leo-editor.github.io/ is cleaned up.

**Comment by edreamleo** [comment]
@technatica I'll have to check with Speed.  It's his password you will need.

> Easiest would be to give me the login/password for the domain registrar so I can make the changes. The password can then be changed after I am done. Harder would be to play tag with you/Speed/domain registrar/github until it works.

**Comment by edreamleo** [comment]
Closing this issue because #3019 continues it.
