### ISSUE TITLE
Bug in PyQt 5.8 re: ~= state indicators in style sheets

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#485]
Terry filed [this qt bug](https://bugreports.qt.io/browse/QTBUG-59533) to report the problem.

The workaround is to use an earlier version of PyQt. We could try to rearrange Leo's style sheets, but that might cause other problems.

**Comment by technatica** [comment]
#894 and #804 are both a continuation of this issue.
Terry's suggestions in #804 would provide a clean fix. As it is the workaround allows stylesheets to load, but the status line does not work correctly.

**Comment by edreamleo** [comment]
@technatica Chris, I'm going to delegate this to Terry.  I haven't been keeping up with the complexities.
