### ISSUE TITLE
Workaround: Ctrl-) binding may not work on Windows 10

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#486]
This could be called a Windows 10 bug.  Leo can do nothing about it, because the bug causes Windows 10 not to pass the Ctrl-).  Apparently Windows 10 binds `Ctrl-)` to something, but I can not find out what.

The workaround: define new bindings.

At one time there was a workaround involving, iirc, a change to the windows registry, but just now googling does not turn up anything.

**Comment by edreamleo** [comment]
I am going to close this item.  It's a bit silly because there is an easy workaround: define new bindings!

**Comment by technatica** [comment]
Even easier!

Stop using a toy operating system.😁

Chris
