### ISSUE TITLE
Create a curses/npyscreen front end for Leo

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#488]
This was endorsed in Ashland. The cursesGui2.py plugin contains the present work, as discussed in several recent posts on leo-editor.

**Comment by edreamleo** [comment]
After almost two months of work, this plugin is ready for real testing.

Please use caution: data loss is a real possibility.

**Comment by edreamleo** [comment]
I am going to close this project.  Please feel free to reopen as you find bugs.  Please report bugs *here* rather than in new items.

**Comment by LewisNeal** [comment]
These commands in the minibuffer cause a hard crash [python has stopped working] with a single line in the log "QWidget: Must construct a QApplication before a QWidget" :
help-for-find-commands
help-for-minibuffer
help-for-regular-expressions
help-for-scripting

Command 'help-for-sessions' in the minibuffer survives, with no output to log.
Running commit = 4749d0995595

**Comment by edreamleo** [comment]
On Sun, Jun 11, 2017 at 7:34 PM, LewisNeal <notifications@github.com> wrote:

> These commands in the minibuffer cause a hard crash [python has stopped
> working] with a single line in the log "QWidget: Must construct a
> QApplication before a QWidget" :
> help-for-find-commands
> help-for-minibuffer
> help-for-regular-expressions
> help-for-scripting
>
> Command 'help-for-sessions' in the minibuffer survives, with no output to
> log.
> Running commit = 4749d09
> <https://github.com/leo-editor/leo-editor/commit/4749d09955952331f5c689e5c6d835f81b55c370>
>
​These work for me. This may be an issue with plugins.  Please report the
platform (don't assume I remember what you are using) and what plugins are
enabled.​

Edward

**Comment by LewisNeal** [comment]
Platform is Python 3.6.1, PyQt version 5.8.0 Windows 10 AMD64 (build 10.0.15063) SP0
I'll post a list of plugins later.

**Comment by LewisNeal** [comment]
I disabled myLeoSettings and switched to using the default leoSettings. So the list is:
contextmenu.py
leo_to_html.py
livecode.py
mod_scripting.py
nav_qt.py
nodetags.py
quicksearch.py
screen_capture.py
settings_finder.py
stickynotes.py
todo.py
viewrendered.py
plus free_layout and nested_splitter

When I give the 'help-for-scripting' command I still get the same crash.
Are you running a settings version for the Curses gui?

**Comment by edreamleo** [comment]
On Sun, Jun 11, 2017 at 7:34 PM, LewisNeal <notifications@github.com> wrote:

> These commands in the minibuffer cause a hard crash [python has stopped
> working] with a single line in the log "QWidget: Must construct a
> QApplication before a QWidget" :
>
​Oh.  I see from the subject that you are using the curses gui. This bug
will be easily fixed, now that I know the proper context.

Edward

**Comment by edreamleo** [comment]
On Mon, Jun 12, 2017 at 6:26 AM, Edward K. Ream <edreamleo@gmail.com> wrote:

> These commands in the minibuffer cause a hard crash [python has stopped
>> working] with a single line in the log "QWidget: Must construct a
>> QApplication before a QWidget" :
>>
> ​Oh.  I see from the subject that you are using the curses gui. This bug
> will be easily fixed, now that I know the proper context.
>

​Fixed (mostly) at 902674d.  Here is the checkin log:

Added special case for curses gui in c.putHelpFor and the corresponding
code in the curses gui.

This works only for help messages that do not require further user input.
For example, help-for-command probably does not work, or does not work
intuitively.

Edward

**Comment by edreamleo** [comment]
Rev f6b2824 adds a new gui method, put_help to eliminate gui-specific code in c.putHelpFor.  From the checkin log:

c.putHelpFor now just calls g.app.gui.put_help. Created do-nothing LeoGui.put_help, qt_gui.put_help and curses_gui.put_help. All tests pass and pylint is happy.

**Comment by LewisNeal** [comment]
I tried the same commands on a laptop but did not see the same crash. For example command 'help-for-find-commands' works fine. Output to log pane is a single line, 'Finding & replacing text ---- Alt 0 (vr-toggle)'

Still running commit = 4749d09
Python 3.6.1 32 bit, Windows Vista. It does not have PyQt version 5.8.2 installed.

**Comment by LewisNeal** [comment]
Rev f6b2824 fixes the crash. The 'help-for-' series commands now launch a 7-line dialog box containing the help text. With the exception of 'help-for-sessions' which doesn't give any output.
Git repo info: branch = master, commit = f6b2824bdcf7
Python 3.6.1, LeoGui: dummy version Windows 10 AMD64 (build 10.0.15063)

**Comment by tbnorth** [comment]
I understand that using this issue for all curses issues keeps things together and keeps the open issue count down, but seems a bit limiting - if there were two or more issues being discussed at once for example.  Anyway, my issue is...

## Curses GUI red lines CPU

```
│ │ Leo 5.5, build 20170613082028, Tue Jun 13 08:20:28 CDT 2017
│ │ Git repo info: branch = master, commit = 87e3a450f933
│ │ Python 2.7.12, LeoGui: dummy version linux2
Ubuntu 16.04, 16 Gb, 4GHz CPU, Gnome Terminal
```

If I tab to the tree pane and hit downarrow ten times, it takes about 15 seconds for the tree selection to move down through those ten positions, during which time the CPU is maxed out (well, one core, anyway).  Down arrow in the log pane seems ok.  This is with my large default 'workbook.leo' outline.  This isn't a high priority issue for me, just an observation that a gui you'd expect to be really fast is not.  Down arrow ten times in Qt gui keeps up.

**Comment by edreamleo** [comment]
On Tue, Jun 13, 2017 at 9:41 AM, Terry Brown <notifications@github.com>
wrote:

> I understand that using this issue for all curses issues keeps things
> together and keeps the open issue count down, but seems a bit limiting - if
> there were two or more issues being discussed at once for example.
>
​We can consider opening other related issues if they arise.  In my
experience, however, have multiple related issues open creates
administrative problems.​

​It's always a judgement call.​

> Anyway, my issue is...
> Curses GUI red lines CPU
>
> │ │ Leo 5.5, build 20170613082028, Tue Jun 13 08:20:28 CDT 2017
> │ │ Git repo info: branch = master, commit = 87e3a450f933
> │ │ Python 2.7.12, LeoGui: dummy version linux2
> Ubuntu 16.04, 16 Gb, 4GHz CPU, Gnome Terminal
>
> If I tab to the tree pane and hit downarrow ten times, it takes about 15
> seconds for the tree selection to move down through those ten positions,
> during which time the CPU is maxed out (well, one core, anyway). Down arrow
> in the log pane seems ok. This is with my large default 'workbook.leo'
> outline. This isn't a high priority issue for me, just an observation that
> a gui you'd expect to be really fast is not. Down arrow ten times in Qt gui
> keeps up.
>
​Thanks for this report.  I don't see anything like this on Windows.  Will
test on Linux soon.

Edward

**Comment by edreamleo** [comment]
I see serious performance problems on Linux after the expand-all command.  But it's rare to have so many visible nodes.

As a next step, I'll ensure that tracing can be completely turned off when running the curses gui.  This will ensure that listen-to-log command is not required, and that not issuing this command will have no effect on performance.

**Comment by Ewaznazari** [comment]
Om

**Comment by LewisNeal** [comment]
Backlink.py gives this minor traceback:

Running
Git repo info: branch = master, commit = cbeba2fd3baa
Python 3.6.1, LeoGui: dummy version Windows 10 AMD64 (build 10.0.15063)
[snip]
hook failed: after-create-leo-frame, <function onCreate at 0x00000201E
Traceback (most recent call last):
File "N:\git\leo-editor\leo\core\leoPlugins.py", line 341, in callTa
File "N:\git\leo-editor\leo\plugins\backlink.py", line 828, in onCre
File "N:\git\leo-editor\leo\plugins\backlink.py", line 101, in __ini
File "N:\git\leo-editor\leo\plugins\backlink.py", line 384, in loadL
File "N:\git\leo-editor\leo\plugins\backlink.py", line 539, in showM
AttributeError: 'backlinkController' object has no attribute 'ui'

I'm not sure I have captured the full log as not all of the line is visible in the curses log pane.
Also upon exit, all traces of the log are wiped from the console. Is there some way to view the session log?

**Comment by edreamleo** [comment]
> Is there some way to view the session log?

Run Leo from *another* console, and issue the listen-to-log command.  Now most curses output should go to the console from which Leo was launched.

**Comment by LewisNeal** [comment]
'listen-to-log' command works fine and is very clever.

Running commit = d5ad094e269a there is no output to the log pane from 'print-settings' command
I expected to see a 7-line dialog box launch containing the settings data.

'print-cmd-docstrings' and 'print-bindings' no output lo log pane.

For these commands the output to log pane is not formatted correctly. Only the first few lines are readable with tab separation. Maybe missing line-breaks? :
'print-commands'
'print-plugin-handlers'
'print-plugins-info'
Again I expected to see a 7-line dialog box launch. I had the listener running but there was no data sent either.

**Comment by edreamleo** [comment]
On Fri, Jun 16, 2017 at 9:29 PM, LewisNeal <notifications@github.com> wrote:

> 'listen-to-log' command works fine and is very clever.
>
​The project could not have happened without it.​

> Running commit = d5ad094
> <https://github.com/leo-editor/leo-editor/commit/d5ad094e269a2af7665b2dd75807dda731bbd8a9>
> there is no output to the log pane from 'print-settings' command
>
​The output is in the log pane, but you have to scroll to it.​​


> I expected to see a 7-line dialog box launch containing the settings data.
>
​Why did you expect that? I'm not going to change Leo's core needlessly.

> 'print-cmd-docstrings' and 'print-bindings' no output lo log pane.
>
​Again, they do output to the log pane, but the log pane doesn't scroll
automatically.  It should be possible...​


> For these commands the output to log pane is not formatted correctly. Only
> the first few lines are readable with tab separation. Maybe missing
> line-breaks? :
> 'print-commands'
> 'print-plugin-handlers'
> 'print-plugins-info'
>
​I see the problem as you report. The distinction between g.pr,
g.app.log.put and print may be important. The fix may require changes to
the core code.

Edward​

**Comment by edreamleo** [comment]
I am going to close this item now.  Please create a *new* issue for any serious bug against this code.
