### ISSUE TITLE
wikiview plugin docs / patterns / function

### ISSUE THREAD

**Issue by tbnorth** [leo-editor/leo-editor#489]
UPDATE: just confirmed enabling wikiview.py can lead to data loss, which is (a) what I thought, and (b) means that the question is, is the old wikiview functionality (pattern hiding) now in core, and if not - did it never really get fixed?

Orginal report:

wikiview.py plugin might need a bit of polish.

Originally it was a plugin that made things like

    http://example.org/something/here/page.html

appear as

    .page.html

where the . is the missing text shrunk to 0.1 px or something.

After the syntax highlighting update wikiview.py became incompatible with the core.  When regular text was interleaved with target patterns, regular text towards the end of a node could be hidden.

I *thought* wikiviews.py function was to be moved into core, but what I'm seeing currently is:

 - .../leoSettings.leo#@settings-->Plugins-->wikiview plugin-->@data wikiview-link-patterns
   says "Only 'groups' parts of the pattern in parentheses will be shown." but the opposite seems
   to be true (and perhaps preferred).
 - nothing happens without wikiview.py being enabled, making me thing the action's not all in
   core now.
 - although I don't see a problem with the patterns in leoSettings.leo, the original disappearing
  text issue still occurs with a pattern like `((https?|file)://(\S+)?(-->|[/#])(?=[.%/a-zA-Z0-9_]))`
 - I don't understand the significance of the lead in character.  Is it's absence in the above pattern
   causing the problem?

Hmm, not a very clear path here - more analysis needed, but any comments on what the current state of play is supposed to be would be good.

**Comment by tbnorth** [comment]
I now understand the colorizer a little bit better, at least enough to understand the significance of the lead in character.  I'll have a shot at getting the hiding behavior into core, which will fix the data loss issue.

**Comment by edreamleo** [comment]
@tbnorth Glad to hear you are making progress.

**Comment by edreamleo** [comment]
Terry indicates that he has had no problems with the wikiview plugin recently.

I'm going to close the issue now.  Please create a *new* issue if problems are found.  That way the issue can start off with a new, concise, summary.
