### ISSUE TITLE
Slow Memory Leak:  Instances of IdleTime objects accumulate in the g.app.idle_timers list forever.

### ISSUE THREAD

**Issue by SegundoBob** [leo-editor/leo-editor#491]
When an IdleTime instance is created by g.IdleTime(), it is put in the list g.app.idle_timers.  There is a destroy_self() method of the IdleTime class that would remove entries from g.app.idle_timers, but I can find no calls to destroy_self().

A simple program based on the documentation of how to use IdleTime shows the problem.

http://leoeditor.com/scripting-miscellany.html#id19

It only documents the IdleTime methods:
```    
    ito = g.IdleTime() - create
    ito.start()  - Start
    ito.stop()   - Stop
```
Perhaps the intention was to have the user call destroy_self()?  If so, how to make this call needs to be documented.  And Since there are no calls to destroy_self() in the Leo-Editor core, either all the core uses of IdleTime are never ending or calls to destroy_self() need to be added.

The following seems to work:
```
    ito.destroy_self()
```
This seems to remove ito from g.app.idle_timers and hence seems to prevent the slow memory leak.

Test System:
```
Leo 5.5, build 20170516160922, Tue May 16 16:09:22 CDT 2017
Git repo info: branch = master, commit = f96a025f8c4e
Python 3.5.2, PyQt version 5.5.1
linux
Xubuntu 16.04
i3 Window Manager
```

**Comment by edreamleo** [comment]
@SegundoBob Imo, client code should not have to call destroy_self(). In other words, this is a real bug.

**Comment by edreamleo** [comment]
Upon further review, it seems that the present code is reasonable.  I am going to close this issue for the following reasons.

1. Calling aTimer.stop() should *not* automatically kill (recycle it). The g.app.idle_timers list exists precisely to maintain references to timers so they *won't* be recycled after being stopped.  This allows any timer to be restarted safely.

2. In practice, this "leak" will be inconsequential unless one is doing something bizarre. In that case it is all the more reasonable to require that user code call time.destroySelf explicitly.

3. User code (not Leo) must take responsibility for calling timer.destroySelf. Accessing a timer after calling timer.destroySelf could (will?) lead to a hard crash in Qt.

**Comment by SegundoBob** [comment]
I agree with all three of your points.

I hope you will add some mention of ito.destroy_self() to the documentation at

[Running Code at Idle Time](http://leoeditor.com/scripting-miscellany.html#running-code-at-idle-time)

While nothing serious happens if you don't destroy a timer when you are done with it, it would be a good programming practice to destroy the timer.

**Comment by edreamleo** [comment]
@SegundoBob Thanks for your documentation suggestion. The [Running Code at Idle Time](http://leoeditor.com/scripting-miscellany.html#running-code-at-idle-time) section now contains the following:

> **Recycling timers**
> 
> The g.app.idle_timers list retrains references to all timers so they *won't* be recycled after being stopped.  This allows timers to be restarted safely.
> 
> There is seldom a need to recycle a timer, but if you must, you can its destroySelf method. This removes the reference to the timer in g.app.idle_timers. **Warning**: Accessing a timer after calling its destroySelf method can lead to a hard crash.
