### ISSUE TITLE
Leo GUI window not repositioning properly with changing monitor configuration

### ISSUE THREAD

**Issue by alsoeric** [leo-editor/leo-editor#493]
I work in three different monitor setups and I'm having trouble keeping the Leo screen visible.

Set up 1: standalone laptop
set up 2: laptop with secondary monitor, extended display, desktops join on right side of laptop screen 
set up 3: laptop with secondary monitor, extended display, desktops join on top side of laptop screen 

If I've been working and left Leo displaying the Leo GUI window on the secondary monitor, when I try to run Leo on the laptop by itself, the Leo GUI window is not visible. I can usually recover the the Leo GUI window by right clicking on the taskbar icon and selecting the move option. I kinda have to guess which direction to move the window but eventually I can bring it onto my laptop screen.

**Comment by tbnorth** [comment]
On Fri, 19 May 2017 06:59:20 -0700
"Eric S. Johansson" <notifications@github.com> wrote:

> I work in three different monitor setups and I'm having trouble
> keeping the Leo screen visible.

OS?

**Comment by alsoeric** [comment]
Windows 10.

**Comment by alsoeric** [comment]
** isPython3: True
Leo 5.4, build 20170129073103, Sun Jan 29 07:31:03 CST 2017
Git repo info: branch = master, commit = 1c28e916c371
Python 3.6.0, PyQt version 5.6.2
Windows 10 AMD64 (build 10.0.15063) SP0

**Comment by alsoeric** [comment]
one more observation.  If I reset the position of the Leo GUI window it normally sticks and shows up in the same place the next time I start leo.  *but* if I'm running Teamviewer (to show off how cool leo is), the Leo GUI window always starts up off screen

**Comment by edreamleo** [comment]
The solution is to set the desired window position in each environment with:

```
@bool fixed_window = True
@data fixedWindowPosition
```
The body text of the `@data` node contains the desired window coordinates.

As noted in the comments, place these in myLeoSettings.leo, not in individual .leo files.

**Comment by tbnorth** [comment]
On Fri, 10 Nov 2017 10:25:37 +0000 (UTC)
"Edward K. Ream" <notifications@github.com> wrote:

> The solution is to set the desired window position in each
> environment with:
> 
> @bool fixed_window = True
> @data fixedWindowPosition
> The body text of the @data node contains the desired window
> coordinates.
> 
> As noted in the comments, place these in myLeoSettings.leo, not in
> individual .leo files.

Don't think the OP said whether they were using three setups with three
independent myLeoSettings.leo files, or a shared (always sync'ed)
myLeoSettings.leo.  Either's possible, depending on workflow /
networking, so if the same myLeoSettings.leo is in use in each case,
@data fixedWindowPosition should go in <machine-name>LeoSettings.leo
rather than myLeoSettings.leo, with three files, one for each machine.

**Comment by edreamleo** [comment]
On Fri, Nov 10, 2017 at 2:55 PM, Terry Brown <notifications@github.com>
wrote:

Don't think the OP said whether they were using three setups with three
> independent myLeoSettings.leo files, or a shared (always sync'ed)
> myLeoSettings.leo.


​The hint to use the two settings should suffice.

Edward
