### ISSUE TITLE
Losing syntax colors when adding body editor

### ISSUE THREAD

**Issue by alsoeric** [leo-editor/leo-editor#494]
Adding a body editor so I can look at two sections causes the leftmost window to lose its syntax highlighting. Deleting the right side body editor does not restore the syntax highlighting.

Windows 10, latest Leo from git hub main branch
![image](https://cloud.githubusercontent.com/assets/8798037/26257699/a8fb3c92-3c8f-11e7-8747-efc58dabc814.png)

**Comment by edreamleo** [comment]
This works for me on Windows 10.  What platform are you using?

**Comment by alsoeric** [comment]
Windows 10

**Comment by tbnorth** [comment]
> On Fri, 19 May 2017 10:32:10 -0700
> "Edward K. Ream" <notifications@github.com> wrote:
> 
> > This works for me on Windows 10.  What platform are you using?
> >
On Fri, 19 May 2017 10:39:25 -0700
"Eric S. Johansson" <notifications@github.com> wrote:

> Windows 10
> 

:-) What about Python version and PyQt version?  That and OS is all
given in the first few lines of the Leo log window, like:

Leo Log Window
Leo 5.5, build 20170518090143, Thu May 18 09:01:42 CDT 2017
Git repo info: branch = master, commit = 290bfe96ed5f
Python 2.7.12, PyQt version 5.5.1
linux2

Cheers -Terry

**Comment by alsoeric** [comment]
see my edited comment. It occurred to me to add that info after I hit comment.

**Comment by edreamleo** [comment]
I do not see this problem, on a very similar machine.
