### ISSUE TITLE
Adding mark and point

### ISSUE THREAD

**Issue by alsoeric** [leo-editor/leo-editor#495]
This is a request to add mark and point functionality to Leo. At a minimum, I would need what Emacs does. A command to leave a"mark" in a section. then via navigation commands, define the other end of the region a.k.a. point. 

Another layer to this enhancement might be the ability to save matched sets the mark and point for use later. one way of holding these matched sets would be to put them in a dictionary so that commands like:

Save region as <name>
Use region <name>
indent region named <name>

can be implemented.

**Comment by edreamleo** [comment]
Leo already supports the point and mark. The "point" is called the insert point, the "mark" is the other end of the selection range.

LeoEditCommands.exchangePointMark, implement the exchange-point-mark command. It delegates the real work to QTextEditWrapper.leoMoveCursorHelper. 

Let wrapper = c.frame.body.wrapper and s = wrapper.getAllText() Then after:

    i, j = wrapper.getSelectionRange()

i will be the "point" and j will be the "mark".  Both will be integers between 0 and len(s).

**Comment by edreamleo** [comment]
I am going to close this.  Please reopen if there is something about this issue that I have misunderstood.

**Comment by edreamleo** [comment]
> Another layer to this enhancement might be the ability to save matched sets the mark and point for use later. one way of holding these matched sets would be to put them in a dictionary.

This can easily be done in the code that implements save-region-as, use-region, indent-region.  There should be no need for further support in Leo.
