### ISSUE TITLE
add "<jump|push> to <beginning | start | finish | end> of line"

### ISSUE THREAD

**Issue by alsoeric** [leo-editor/leo-editor#496]
beginning of line is before first character in line
start of line is first nonwhite space text
finish of line is last nonwhite space text
end of line is after last character in line

navigating to these points is useful when using speech recognition and is frequently useful when creating macros to operate on text.  Jump means you go to the location without remembering where you were. Push means remembering, in a stack, where you were and being able to return to that location with a pop command.

The push/pop model works well with speech recognition becaause you don't have to give explicit navigation commands. You just go back to where you were

**Comment by edreamleo** [comment]
Rev 9fde355 completes the project by documenting these commands. 

push-cursor: Saves the location of the cursor, including node(position) on a stack.
pop-cursor: Restores the cursor position from the stack.
start-of-line: Puts cursor at first non-blank character of the line.
start-of-line-extend-selection.  Same as above, extending the selection range.
finish-line: Puts the cursor at before the last non-blank character of the line.
finish-line-extend-selection.  Same as above, extending the selection range.

It would be easy to have finish-line put the cursor after the last non-blank character of the line, but that's pretty much what end-of-line does.
