### ISSUE TITLE
--session-restore option fails if no leo.session exists

### ISSUE THREAD

**Issue by largo84** [leo-editor/leo-editor#498]
With a new installation of Leo there is no leo.session file . It is apparently created only after using the --session-save command line option. If the --session-restore option is also used before that file is created, then Leo fails to open (splash screen displays, then nothing else happens).

Mentioned in [groups thread here](https://groups.google.com/d/msg/leo-editor/JZsGSwPRW6k/1sZ5WzUDBQAJ).

**Comment by edreamleo** [comment]
I am unable to duplicate this problem.  Please provide the platform/version info at the beginning of the log pane.

**Comment by largo84** [comment]
Leo 5.5, build 20170530035342, Tue May 30 03:53:42 CDT 2017
Git repo info: branch = master, commit = e571c43ec07e
Python 3.6.0, PyQt version 5.6.2
Windows 10 AMD64 (build 10.0.14393) SP0

**Comment by largo84** [comment]
I can't replicate it either on my home PC:
Leo 5.5, build 20170530101144, Tue May 30 10:11:44 CDT 2017
Git repo info: branch = master, commit = 5b96cdaba17b
Python 3.4.3, PyQt version 5.4.1
Windows 8 AMD64 (build 6.2.9200) 

Next time I'm in the office, I will try to replicate the problem (might be a week or so).

**Comment by edreamleo** [comment]
On Tue, May 30, 2017 at 5:46 PM, Rob Keeney <notifications@github.com>
wrote:

> I can't replicate it either on my home PC:
> Leo 5.5, build 20170530101144, Tue May 30 10:11:44 CDT 2017
> Git repo info: branch = master, commit = 5b96cda
> <https://github.com/leo-editor/leo-editor/commit/5b96cdaba17b90a556e5cb066d80922d4f2baa2b>
> Python 3.4.3, PyQt version 5.4.1
> Windows 8 AMD64 (build 6.2.9200)
>
> Next time I'm in the office, I will try to replicate the problem (might be
> a week or so).
>

​No problem.  Nobody else is complaining about this issue.

Edward

**Comment by largo84** [comment]
I can't replicate it on the machine I first saw it. I don't really know what happened, so I guess it's best to close this for now and reopen if it happens again.
