### ISSUE TITLE
Enhance backlinks.py plugin

### ISSUE THREAD

**Issue by largo84** [leo-editor/leo-editor#499]
Group discussion [here](https://groups.google.com/d/msg/leo-editor/H_3VvShKuHo/dwkJiqEFAQAJ). Request to enhance the backlinks.py plugin to create links to just about anything, at the least to nodes in external .leo files.
- Link addresses not visible in the node body text, but as attributes of the node (uA's).
- No limit to the number of links or type (UNLs, URLs, even files and directories).

**Comment by tbnorth** [comment]
I think d5ad094e2 fixes this.
