### ISSUE TITLE
Making front page of leo-editor more nice

### ISSUE THREAD

**Issue by HaveF** [leo-editor/leo-editor#5]
As we all know, github will render README when it has proper extension(*.rst in our case).
So I just rename the file name, and pull #2 , but @maphew remind me that not the leo way to manage file, and he changed the *.rst already in 96b0560b.

1. After a quick search, I find `dist\leoDist.leo` link the `README.txt`, we also need to change the file there, I suppose.

2. the content of README(like the word `final` and etc.) may misleading people `Leo 4.11 final November 6, 2013`, if we want the user use that steady version, I suggest make the `master` as the place where people download the steady version, and make another branch, like `dev` as daily develop branch.

**Comment by edreamleo** [comment]
I am going to close this.  It seems out of date.
