### ISSUE TITLE
always crash by Qt plugin from Leo 5.4

### ISSUE THREAD

**Issue by ZoomQuiet** [leo-editor/leo-editor#506]
## log

[QtGui error dump for Leo 5.4](https://gist.github.com/ZoomQuiet/98f154bfc5dc149f04b2c6b383a8a2e6)

## env
MacBook Pro (Retina, 13-inch, Early 2015)

- macOS 10.12.5 (16F73)
    + 3.1Ghz i7
    + 16 GB 1867 MHz DDR3
    + Intel Iris Graphics 6100 1536 MB
- Leo 5.4, Sat Oct 22 06:39:42 2016
    + Git commit: after ff
- Python 2.7.10, PyQt version 4.8.7 darwin

what happen?
how to fix it?

**Comment by edreamleo** [comment]
On Thu, Jun 22, 2017 at 3:33 PM, Zoom.Quiet <notifications@github.com>
wrote:

> log
>
> QtGui error dump for Leo 5.4
> <https://gist.github.com/ZoomQuiet/98f154bfc5dc149f04b2c6b383a8a2e6>
> env
>
> MacBook Pro (Retina, 13-inch, Early 2015)
>
>    - macOS 10.12.5 (16F73)
>       - 3.1Ghz i7
>       - 16 GB 1867 MHz DDR3
>       - Intel Iris Graphics 6100 1536 MB
>    - Leo 5.4, Sat Oct 22 06:39:42 2016
>       - Git commit: after ff
>    - Python 2.7.10, PyQt version 4.8.7 darwin
>
> what happen?
> how to fix it?
>

​I don't know what happened.  Please upgrade to Leo 5.5, or better, use git
to get the latest version of Leo.

Edward

**Comment by edreamleo** [comment]
I am going to close this issue.  It is clearly an installation problem with an obsolete version of Leo

**Comment by ZoomQuiet** [comment]
On Fri, Jun 23, 2017 at 9:34 AM, Edward K. Ream
<notifications@github.com> wrote:
>
> I am going to close this issue. It is clearly an installation problem with an obsolete version of Leo
>

sure, understood ;-)
