### ISSUE TITLE
console gui: print-cmd-docstrings

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#508]
The debug command print-cmd-docstrings gives no output. A blank Completion Tab starts in the log pane.

Leo 5.5, build 20170624181042, Sat Jun 24 18:10:42 CDT 2017
Git repo info: branch = master, commit = 1e6da9e97999
Python 3.6.1, PyQt version 5.8.0
Windows 10 AMD64 (build 10.0.15063) SP0

**Comment by edreamleo** [comment]
On Sun, Jun 25, 2017 at 3:28 AM, LewisNeal <notifications@github.com> wrote:

> The debug command p_rint-cmd-docstrings_ gives no output. A blank
> Completion Tab starts in the log pane.
>
​Thanks for this report.

Edward

**Comment by edreamleo** [comment]
How did you get @command print-cmd-docstrings?  I have it in myLeoSettings.leo, but it does not appear in leoSettings.leo?

**Comment by edreamleo** [comment]
This is a strange one.  The command is not being executed at all with the curses gui.

**Comment by edreamleo** [comment]
I am going to close this.  There is no particular reason to run this `@command` script using the console gui.

There may be a more general problem with `@command` scripts in the console gui, gut if so, please report it in a separate issue.

**Comment by LewisNeal** [comment]
The print-cmd-docstrings command is listed at http://leoeditor.com/commands.html (Printing settings and other data)
The name suggests it gives a summary of all command docstrings. However it's either broken or just obsolete. Same result running Leo or Leo with console gui; there is no printed information to Leo's log pane.

The log scrolling to the end on startup is an improvement.

**Comment by edreamleo** [comment]
Fixed at bd5067.  As stated earlier, the command isn't broken, it simply doesn't exist for most people.  It is one of my private `@command` nodes.  The change was to LeoDocs.leo and has been pushed to the web.
