### ISSUE TITLE
console gui problems

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#509]
**Status**

- *All major items have been completed*. 
- *The minibuffer is functional and supports tab completion*.
- The [console gui docs](http://leoeditor.com/console-gui.html) tell how to develop the curses2.py plugin.
- #599 discusses *unlikely* improvements to the console gui.

Focus:
- [x] ConsoleGui.set_focus blanks out the pane with the previous focus.
- [x] The log pane gets focus after a find.

General:
- [x] Add a status line showing Find options or the UNL to c.p.
- [x] Support the --listen-to-log command-line option.

Commands:
- [x] Support tab completion in the minibuffer.
- [x] Support repeat-complex-command.
- [x] Show find options when executing `toggle-find-*-option` and `set-find-*` commands.
- [x] Highlight the line containing the (start of) a successful Find command.
- [x] Fix the toggle-find-*-option commands.
- [x] Fix the set-find-* commands.

Drawing:
- [x] Show prompts in the minibuffer's label.
- [x] Show the name of the .leo file in the main window's title.
- [x] Highlight the '*' line in the tree when the tree has focus.
- [x] Inserting or deleting a headline node does not mark c changed.
- [x] Inserting a headline did not select the proper node.
- [x] Scrolling past the last line of the log pane hides all preceding lines.

**Comment by edreamleo** [comment]
On Sun, Jun 25, 2017 at 4:39 AM, LewisNeal <notifications@github.com> wrote:

> Ctrl-F command is not working with the Console Gui.
> I included Ctrl-F in Supported Ctrl commands in the user guide
> <http://leoeditor.com/console-gui.html> , but oops, I had not verified.
>

​Thanks for this report. I'm not sure when I'll get to this.  #505 probably
has to be resolved before I'll be able to switch easily between unrelated
git branches.  I expect that this will happen in a day or two.

Edward

**Comment by LewisNeal** [comment]
Ctrl-F is not working for me running Leo with windows cmd.exe, or ConsoleZ. I tried with focus in both body pane and minibuffer.

Leo Log Window
Leo 5.5, build 20170825091228, Fri Aug 25 09:12:28 CDT 2017
Git repo info: branch = master, commit = 65b9bb665ada
Python 3.6.2, LeoGui: dummy version Windows 10 AMD64 (build 10.0.15063) SP0       
isPython3: True
caching enabled
hook failed: after-create-leo-frame, <function onCreate at 0x000001D516BBEC80>,   Traceback (most recent call last):
File "N:\git\leo-editor\leo\core\leoPlugins.py", line 341, in callTagHandler
File "N:\git\leo-editor\leo\plugins\backlink.py", line 964, in onCreate     ba
File "N:\git\leo-editor\leo\plugins\backlink.py", line 108, in __init__     se
File "N:\git\leo-editor\leo\plugins\backlink.py", line 667, in updateTabInt
AttributeError: 'NoneType' object has no attribute 'enableDelete'
[end]

I can confirm _--session-save --session-restore_ work with console gui.

**Comment by edreamleo** [comment]
On Fri, Aug 25, 2017 at 7:17 PM, LewisNeal <notifications@github.com> wrote:

> Ctrl-F is not working for me running Leo with windows cmd.exe, or
> ConsoleZ. I tried with focus in both body pane and minibuffer.
>
> Leo Log Window
> Leo 5.5, build 20170825091228, Fri Aug 25 09:12:28 CDT 2017
> Git repo info: branch = master, commit = 65b9bb6
> <https://github.com/leo-editor/leo-editor/commit/65b9bb665adace191bb4fbb3c5325e75f332649e>
> Python 3.6.2, LeoGui: dummy version Windows 10 AMD64 (build 10.0.15063) SP0
> isPython3: True
> caching enabled
> hook failed: after-create-leo-frame, <function onCreate at
> 0x000001D516BBEC80>, Traceback (most recent call last):
> File "N:\git\leo-editor\leo\core\leoPlugins.py", line 341, in
> callTagHandler
> File "N:\git\leo-editor\leo\plugins\backlink.py", line 964, in onCreate ba
> File "N:\git\leo-editor\leo\plugins\backlink.py", line 108, in *init* se
>


> File "N:\git\leo-editor\leo\plugins\backlink.py", line 667, in
> updateTabInt
> AttributeError: 'NoneType' object has no attribute 'enableDelete'
>
​Fixed at 07ee47e, by binding ​backlinkController.ui to g.NullObject. This
is an elegant and general solution, provided that none of the ui methods
are actually needed.

Edward

**Comment by LewisNeal** [comment]
The backlink.py traceback is fixed. I'm not sure if the original Ctrl-F issue is fixed. I still can't get it working using Ctrl-F directly.
Can you describe exactly the steps that work for you? Maybe:
1. focus in minibuffer
2. type alt-x
3. type Ctrl-F

**Comment by edreamleo** [comment]
On Wed, Sep 6, 2017 at 6:48 AM, LewisNeal <notifications@github.com> wrote:

> The backlink.py traceback is fixed. I'm not sure if the original Ctrl-F
> issue is fixed. I still can't get it working using Ctrl-F directly.
>
​That's because it doesn't work yet.

Edward

**Comment by edreamleo** [comment]
Rev 03ec50d  completes this project by properly redisplaying the entire tree with c.p shown in context after executing any command.   This redisplay code might needed elsewhere, but the present code is good enough for now.

I have no plans for further work on the console gui, but I am willing to clean up any nits in the new code.

**Comment by edreamleo** [comment]
I am reopening this issue.  A new to-do list appears as the first comment of this issue.

**Comment by edreamleo** [comment]
I am going to close this issue. Rev  ba68a0c fixes all the check boxes in first comment.

I have added one more item to #599, discussing focus problems arising from bugs in CGui.set_focus.  This is very difficult code.  I will consider fixing is particular bug only if people are severely impacted by it.
