### ISSUE TITLE
Improve how Leo handles settings

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#510]
The **settings branch** will deal with the following issues:

**Bug**: (Fixed in #579) After unbinding Shift-Ctrl-F in the quicksearch plugin, binding Shift-Ctrl-F to find-quick-selected in the usual way does not work. See [this discussion](https://groups.google.com/forum/#!topic/leo-editor/ELGwNEmZ2Ho).

**Command-line options**

- [x] **--trace-setting=setting**: `--trace-setting=http-port`

- [x] **--trace-binding=binding**:  `--trace-binding=shift-ctrl-f`

**Comment by edreamleo** [comment]
As part of this project I plan to add the `--trace-config=setting` command-line option.

**Comment by edreamleo** [comment]
Rev 7f532ca completes this issue.

The problem was that the quicksearch plugin calls k.registerCommand too late to allow any hard binding to be overridden.  The solution is to bind in leoSettings.leo, which allows the binding to be overridden in myLeoSettings.leo.

The --trace-settings and --trace-bindings command-line options provide a bit more detail than the print-settings and print-bindings commands.  They probably should remain.

**Comment by tbnorth** [comment]
@edreamleo - the only way I can get the original behavior back is with the @commands --> @command fquick-selected work around.  Binding the find-quick-selected command in myLeoSettings.leo doesn't work.

Does this jive with your recollection of how this was resolved?  I really miss the original behavior, have been living without it for ages because every time I tried to get it working again I assumed I was missing some detail.  The @commands workaround works, but seems it should be simpler than that.  Thakns.

**Comment by SegundoBob** [comment]
Edward's workaround (which works for me) is:

Create the following @command node as a child of the @commands ​node in myLeoSettings.leo

- @settings
   - @commands
      - @command fquick-selected @key=Shift-Ctrl-F

The body is:

>     c.k.simulateCommand('find-quick-selected')

**Comment by tbnorth** [comment]
On Mon, 28 Aug 2017 15:57:31 -0700
SegundoBob <notifications@github.com> wrote:

> Edward's workaround (which works for me) is:
> 
> Create the following @command node as a child of the @commands ​node
> in myLeoSettings.leo
> 
> - @settings
>    - @commands
>       - @command fquick-selected @key=Shift-Ctrl-F
> 
> The body is:
> 
> >     c.k.simulateCommand('find-quick-selected')

Yes, thanks, I've deployed that and it works, but just want to know if
there really is some odd reason stopping the regular mechanism from
working.  Assuming that any unhelpful binding from the plugin itself is
gone, surely this command should be bind able like any other, or is
there something odd about it, perhaps because it uses selected range or
something.

Cheers -Terry

**Comment by edreamleo** [comment]
On Mon, Aug 28, 2017 at 4:50 PM, Terry Brown <notifications@github.com>
wrote:

> @edreamleo <https://github.com/edreamleo> - the only way I can get the
> original behavior back is with the @commands <https://github.com/commands>
> --> @command <https://github.com/command> fquick-selected work around.
> Binding the find-quick-selected command in myLeoSettings.leo doesn't work.
>
> Does this jive with your recollection of how this was resolved?
>
​So you're saying that

c.k.registerCommand('find-quick-selected',None,find_selected)
        # was 'Ctrl-Shift-f'

doesn't honor the user's bindings for the find-quick-select command.  This
is news to me, but not terribly surprising.

I'll reopen this issue, but it has a low priority, imo.

**Comment by tbnorth** [comment]
On Tue, 29 Aug 2017 00:45:34 +0000 (UTC)
"Edward K. Ream" <notifications@github.com> wrote:

> On Mon, Aug 28, 2017 at 4:50 PM, Terry Brown
> <notifications@github.com> wrote:
> 
> > @edreamleo <https://github.com/edreamleo> - the only way I can get
> > the original behavior back is with the @commands
> > <https://github.com/commands> --> @command
> > <https://github.com/command> fquick-selected work around. Binding
> > the find-quick-selected command in myLeoSettings.leo doesn't work.
> >
> > Does this jive with your recollection of how this was resolved?
> >
> ​So you're saying that
> 
> c.k.registerCommand('find-quick-selected',None,find_selected)
>         # was 'Ctrl-Shift-f'
> 
> doesn't honor the user's bindings for the find-quick-select command.
> This is news to me, but not terribly surprising.
> 
> I'll reopen this issue, but it has a low priority, imo.

No, I'm saying that

@settings
  @keys
    @shortcuts
      find-quick-selected = Ctrl-Shift-F

doesn't work, the above typed from memory, but the actual setting
accurate as far as I know.

Cheers -Terry

**Comment by edreamleo** [comment]
On Mon, Aug 28, 2017 at 8:40 PM, Terry Brown <notifications@github.com>
wrote:

>
> > ​So you're saying that
> >
> > c.k.registerCommand('find-quick-selected',None,find_selected)
> > # was 'Ctrl-Shift-f'
> >
> > doesn't honor the user's bindings for the find-quick-select command.
> > This is news to me, but not terribly surprising.
>
> No, I'm saying that
>
> @settings
> @keys
> @shortcuts
> find-quick-selected = Ctrl-Shift-F
>
> doesn't work, the above typed from memory, but the actual setting
> accurate as far as I know.
>

​I think these are two different ways of saying the same thing.

I'll attempt a fix today.  BTW, the @command workaround proves, I think,
that a fix is possible.

Edward

**Comment by tbnorth** [comment]
On Tue, 29 Aug 2017 04:18:42 -0700
"Edward K. Ream" <notifications@github.com> wrote:

> > find-quick-selected = Ctrl-Shift-F
> >
> > doesn't work, the above typed from memory, but the actual setting
> > accurate as far as I know.
> >
> 
> ​I think these are two different ways of saying the same thing.

Ok, I just double checked with HOME=/tmp vanilla Leo that the above
doesn't work.  Thanks for looking into it.

**Comment by edreamleo** [comment]
On Tue, Aug 29, 2017 at 8:51 AM, Terry Brown <notifications@github.com>
wrote:

>
> > > find-quick-selected = Ctrl-Shift-F


​This is a nasty one, and I am quite sure it is real.

Per #327 <https://github.com/leo-editor/leo-editor/issues/327>, a line

   a-command = None

in an @shortcuts node is supposed to clear the shortcut.  Such lines can
appear in leoSettings.leo, myLeoSettings.leo and other (local) .leo files.

Worse, k.registerCommand is being asked to do too much. It can be called to
handle settings, as above, but it is also called from plugins, and
indirectly when handling @command and @button nodes.

​At present, k.registerCommand ​it is supposed to unbind existing bindings
in some situations!  That's not going to turn out well, imo.

I'm not sure how we got to the present situation, but I'm likely entirely
responsible.

Imo, the solution is likely to make k.registerCommand simpler.  It probably
shouldn't handle bindings at all.  Instead, two new methods, say
k.bindCommand and k.killBinding should be called explicitly in the
appropriate situations. This may have a few small compatibility impacts.
I'll just have to deal with those as they arise...

​Edward​

**Comment by tbnorth** [comment]
I'm still not seeing why this is a special case.  Any code in the plugin that tries to register a keybinding should be removed, and replaced with

```
@settings
  @keys
    @shortcuts
      find-quick-selected = Ctrl-Shift-F
```

in **`leoSettings.leo`**, if the consensus is the command deserves a default binding, which I think it does.

But *quick* glance I don't see any keybinding in the plugin code, so I don't know why this command seems to behave differently.

**Comment by edreamleo** [comment]
On Tue, Aug 29, 2017 at 11:04 AM, Terry Brown <notifications@github.com>
wrote:

> I'm still not seeing why this is a special case. Any code in the plugin
> that tries to register a keybinding should be removed
>
​I agree, it shouldn't be a special case.  But the fix to #327 created one
too many constraints on k.registerCommand. The code is at the edge of my
ability to understand it...

Edward

**Comment by tbnorth** [comment]
Ok, now I understand, in effect `k.registerCommand` is irrevocably binding None as the shortcut for that command.  So `k.registerCommand` needs fixing, but alternatively could it be deprecated, and the plugin re-written to use `g.command()` or whatever's appropriate?

**Comment by edreamleo** [comment]
On Tue, Aug 29, 2017 at 3:24 PM, Terry Brown <notifications@github.com>
wrote:

> Ok, now I understand, in effect k.registerCommand is irrevocably binding
> None as the shortcut for that command. So k.registerCommand needs fixing,
> but alternatively could it be deprecated, and the plugin re-written to use
> g.command() or whatever's appropriate?
>
​Yes, that's the plan. I will do this asap, but it may not happen until
tomorrow.

Edward

**Comment by edreamleo** [comment]
I am going to close this issue.  Afaik, #579 fixes everything discussed here.

**Note**: At present k.registerCommand calls the do-nothing k.killBinding.  #327 may make k.killBinding functional.  It's not clear what the effect would be on k.registerCommand, but that's for #327 to handle.
