### ISSUE TITLE
quicksearch can freeze Leo if there are too many results

### ISSUE THREAD

**Issue by vitalije** [leo-editor/leo-editor#515]
Today I was working on quicksearch.py plugin and while testing I used to open leo/test/unitTest.leo and start quick search for some words. There were lot of words that freeze Leo. Try global, start, loop, ...
and Leo would struggle. I had to kill it several times.

I have tried to put some upper bound on number of items in result lists in find_h and find_b, but the result was not good enough. Even with the upper limit of 100 items it can freeze Leo. I don't know whether it freezes while searching or while adding Qt list items. Maybe we can limit the number of list items displayed.

**Comment by edreamleo** [comment]
On Mon, Jul 3, 2017 at 8:18 AM, Виталије Милошевић <notifications@github.com
> wrote:

> Today I was working on quicksearch.py plugin and while testing I used to
> open leo/test/unitTest.leo and start quick search for some words. There
> were lot of words that freeze Leo. Try global, start, loop, ...
> and Leo would struggle. I had to kill it several times.
>
> I have tried to put some upper bound on number of items in result lists in
> find_h and find_b, but the result was not good enough. Even with the upper
> limit of 100 items it can freeze Leo. I don't know whether it freezes while
> searching or while adding Qt list items. Maybe we can limit the number of
> list items displayed.
>
​Hmm.  I would look first within quicksearch.py.  Maybe there is some
O(n**3) code there.  I doubt the problem is in Qt.

Edward

**Comment by vitalije** [comment]
Fixed at  de999cc.
As I have suspected it was too many items in QListWidget. Adding new items is fast, but later when it comes to rendering large number it freezes Leo.

**Comment by edreamleo** [comment]
Thanks for this investigation.
