### ISSUE TITLE
content of find tab can disappear

### ISSUE THREAD

**Issue by vitalije** [leo-editor/leo-editor#516]
To reproduce:

1. open new Leo window (initially Log tab is selected)
2. press Ctrl+F (it opens find dialog)
3. close the dialog
4. select Find tab in Log pane and it is empty

Ubuntu 14.04
```
** isPython3: False
Leo 5.5, build 20170703160304, Mon Jul  3 16:03:04 CDT 2017
Git repo info: branch = master, commit = de999cce727e
Python 2.7.6, PyQt version 4.8.6
linux2
```

**Comment by vitalije** [comment]
Same in Python3
```
** isPython3: True
Leo 5.5, build 20170703160304, Mon Jul  3 16:03:04 CDT 2017
Git repo info: branch = master, commit = de999cce727e
Python 3.4.3, PyQt version 5.2.1
linux
```

**Comment by edreamleo** [comment]
Is this a significant problem for you? This never happens with minibuffer-based find:
```
@bool minibuffer_find_mode = True
```
A bigger problem lurks here.  Re-opening the Find dialog creates a dialog with default (system?) fonts rather than user fonts.

**Comment by vitalije** [comment]
Don't know if it is significant for me. I don't use find commands. I prefer quicksearch. I was trying to solve issue  #457 when I have noticed this strange behavior.
Though it can be considered significant if some newbie presses Ctrl+F and then naively closes dialog. But then again newbie would press Ctrl+F and dialog reappears. Maybe the best thing is to remove tab when dialog closes. So nobody would notice what happened.

**Comment by vitalije** [comment]
I didn't notice change in fonts. My fonts are perhaps same as system default.

**Comment by edreamleo** [comment]
On Thu, Jul 6, 2017 at 3:05 AM, Виталије Милошевић <notifications@github.com
> wrote:

>
> Though it can be considered significant if some newbie presses Ctrl+F and
> then naively closes dialog. But then again newbie would press Ctrl+F and
> dialog reappears. Maybe the best thing is to remove tab when dialog closes.
> So nobody would notice what happened.
>
​I agree.  I'll get to this when I can.

Edward

**Comment by edreamleo** [comment]
Rev 924ab0 fixes all aspects of this bug:

Step 1: Leo does not create a log Tab in the Log pane when using Find dialogs.
Step 2: Leo hides the Find dialog when the user "closes" it.  This preserves styling when the user later re-opens it.

**Comment by edreamleo** [comment]
Heh.  My tests were faulty and the new code is much worse than before.  This is no longer a minor issue.

**Comment by edreamleo** [comment]
There are two settings involved:

`@bool minibuffer_find_mode` and `@bool use_find_dialog`. I have, I think, tried all combinations of these.  Please reopen if problems remain.
