### ISSUE TITLE
Add @bool report_unchanged_files

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#518]
[Here](https://groups.google.com/forum/#!topic/leo-editor/kg9STI2Gd8o) is the initial request.

**Comment by wangzhaohe** [comment]
I like it. I want this feature。

**Comment by edreamleo** [comment]
On Thu, Jul 6, 2017 at 7:38 AM, wangzhaohe <notifications@github.com> wrote:

> I like it. I want this feature。
>
​It's labeled "First".  I'll get to it asap.

Edward

**Comment by edreamleo** [comment]
Rev bac1ae5 completes this item.  I'm not sure that it will be as useful as one might think.  When many files are written, Leo appears to hang.  Leo does report the total number of unchanged files when the write-at-file-nodes command completes, but the effect is a bit unnerving
