### ISSUE TITLE
Non-break spaces not preserved in body

### ISSUE THREAD

**Issue by tbnorth** [leo-editor/leo-editor#520]
This is a very obscure thing, and possibly a Qt trait, but [non break spaces](https://en.wikipedia.org/wiki/Non-breaking_space) don't survive body editing.  This script demonstrates:

```
if not p.hasChildren():
    nd = p.insertAsLastChild()
    nd.b = u"42\u00A0m"
nd = p.firstChild()
c.selectPosition(nd)
c.redraw()
g.es("Node has %d nbsp" % len([i for i in nd.b if i == u"\u00A0"]))
c.bodyWantsFocusNow()
```
The first time it's run it creates a child node which contains one non break space.  Subsequent runs of the script just report the number of non break spaces in the child node.  It reports one until the child node's edited, after which it reports zero.

My use case is to write, in markdown say, "Dropped from 42 m to the ground" where the space between 42 and 'm' is non breaking, so that 'm' is never wrapped on to the next line separate from the '42'.  Of course to be useful Leo also needs to highlight non-breaking spaces, that's what I was working on when I discovered they don't survive editing.

FWIW non break spaces do survive save / load cycles.

**Comment by tbnorth** [comment]
This can be explained by the difference between `w.toPlainText()` and `w.toHtml()`, the former converts non break spaces to regular, the latter doesn't.  So, more a curiosity than anything, I don't think there's any obvious solution.  Well, using `w.setHtml()` with "plain text" might work, but it's probably non worth the effort.

**Comment by edreamleo** [comment]
On Fri, Jul 7, 2017 at 4:32 PM, Terry Brown <notifications@github.com>
wrote:

> This can be explained by the difference between w.toPlainText() and
> w.toHtml(), the former converts non break spaces to regular, the latter
> doesn't. So, more a curiosity than anything, I don't think there's any
> obvious solution. Well, using w.setHtml() with "plain text" might work,
> but it's probably non worth the effort.
>
​Just today I futzed with similar code. LeoQtLog.putnl now *always* calls
w.setHtml.  Something similar might work in the body pane...

Edward

**Comment by edreamleo** [comment]
The following experimental code in `qtew.setAllText` correctly shows text, but breaks syntax coloring:
```python
if 1: # Try to fix #520
    s = s.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
    if not c.frame.log.wrap:
        # Use &nbsp; only when not wrapping!
        s = s.replace(' ', '&nbsp;')
    s = s.replace('\n', '<br>')
        # The caller is responsible for newlines!
    # s = '<font color="%s">%s</font>' % (color, s)
    w.setHtml(s)
else: # legacy code
    w.setPlainText(s)
```
The conclusion is that it's not possible to fix this item. I am going to close it. Feel free to reopen if you find a way forward.

**Comment by tbnorth** [comment]
Fine with closing it, embedded non break spaces are, ha ha, fragile.  The tools I'm using also support &nbsp; which is ugly but now I think I understand syntax highlighting enough to fix issues with wikiview which will address that.

**Comment by edreamleo** [comment]
Just googled "qt non-breaking space" and got [this](https://stackoverflow.com/questions/843035/). Looks like I gave up way too easily.

**Comment by edreamleo** [comment]
There is only one call to QTextEdit.toPlainText in Leo, in wrapper.getAllText.  This code passes all unit tests:

```python
 def getAllText(self):
    '''QTextEditWrapper.'''
    w = self.widget
    if 1:
        # #520: Use the document to get plain text that preserves non-breaking spaces.
        s = g.u(w.document().toPlainText())
    else:
        s = g.u(w.toPlainText())
    return s
```
However, non-breaking characters still do not survive editing.  Not sure why.  I'll investigate later.

**Comment by tbnorth** [comment]
Appreciate the effort, but really not sure this is a high priority issue. Nbsp's are going to be trouble wherever they're used, so probably best avoided.

**Comment by edreamleo** [comment]
Disappointing.  I am going to close this item.  Feel free to explore further if you like.  I am out of ideas.
