### ISSUE TITLE
show-fonts command

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#521]
show-fonts command used to launch a font picker, but now gives traceback.

Leo Log Window
Leo 5.5, build 20170708183326, Sat Jul  8 18:33:26 CDT 2017
Git repo info: branch = master, commit = ac22a155d79f
Python 3.6.1, PyQt version 5.9.1
Windows 10 AMD64 (build 10.0.15063) SP0
isPython3: True
caching enabled
Traceback (most recent call last):

  File "N:\git\leo-editor\leo\core\leoKeys.py", line 2648, in callAltXFunction
    func(event)

  File "N:\git\leo-editor\leo\plugins\qt_commands.py", line 177, in showFonts
    if family: font.setFamily(family)

UnboundLocalError: local variable 'family' referenced before assignment

**Comment by vitalije** [comment]
Should be fixed at b31f965. Reopen if it doesn't work.

**Comment by edreamleo** [comment]
Thanks, Виталије.  Works for me.

**Comment by LewisNeal** [comment]
Thanks Vitalije, the fix for show-fonts works fine.

However the Find tab has disappeared from the log pane with b31f965.
If I Ctrl-F the find pane appears but it is blank.

**Comment by edreamleo** [comment]
On Sun, Jul 9, 2017 at 8:32 AM, LewisNeal <notifications@github.com> wrote:

> Thanks Vitalije, the fix for show-fonts works fine.
>
> However the Find tab has disappeared from the log pane with b31f965
> <https://github.com/leo-editor/leo-editor/commit/b31f965798105e68bf8fcb4209872adfe05c629f>
> .
> If I Ctrl-F the find pane appears but it is blank.
>
​This is a separate issue, namely #516
<https://github.com/leo-editor/leo-editor/issues/516>.

I am responsible for the fixes, and all appears to work at rev a03df8.

When @bool minibuffer_find_mode is False (the default) Leo creates no Find
tab at all. Instead, Ctrl-F, start-search, shows a find dialog containing
what used to be in the find tab.

Is this the behavior you see?

Edward

**Comment by vitalije** [comment]
It is separate issue. See #516. Edward claims that to be fixed at 924ab0. I haven't tried it yet, but check it maybe related.

**Comment by LewisNeal** [comment]
Ctrl-F, start-search show a Find dialog tab, but it remains blank, with no fields to enter search criteria.

Leo Log Window
Leo 5.5, build 20170709082545, Sun Jul  9 08:25:45 CDT 2017
Git repo info: branch = master, commit = def6f8161b32
Python 3.6.1, PyQt version 5.9.1
Windows 10 AMD64 (build 10.0.15063) SP0
isPython3: True
caching enabled

**Comment by edreamleo** [comment]
On Sun, Jul 9, 2017 at 8:59 AM, LewisNeal <notifications@github.com> wrote:

> Ctrl-F, start-search show a Find dialog tab, but it remains blank, with no
> fields to enter search criteria.
>
​Drat.  My tests were faulty. My apologies.

I'll fix this asap, but it may be awhile.

Edward

**Comment by LewisNeal** [comment]
@edreamleo wrote: When @bool minibuffer_find_mode is False (the default) Leo creates no Find tab at all.

I knew I wasn't dreaming...
The log pane has a Find tab loaded by default. I don't have to Ctrl-F for it to display. Running commit = 0d899a9f2033

**Comment by edreamleo** [comment]
@LewisNeal: There are two settings involved here, with the defaults as shown:
```
@bool minibuffer_find_mode = False
@bool use_find_dialog = False
```
By default, a log Tab *is* created in the Log Pane.

**Comment by vitalije** [comment]
Am I wrong to believe that the troubles with find tab and dialog have nothing to do with show-fonts? And that it should be discussed in #516 ?

Should we reopen this issue or redirect discussion to #516 ?

**Comment by edreamleo** [comment]
On Mon, Jul 10, 2017 at 6:24 AM, Виталије Милошевић <
notifications@github.com> wrote:

> Am I wrong to believe that the troubles with find tab and dialog have
> nothing to do with show-fonts? And that it should be discussed in #516
> <https://github.com/leo-editor/leo-editor/issues/516> ?
>
​Imo, this issue is complete, and has nothing to do with show-fonts.

Edward

**Comment by LewisNeal** [comment]
Yes you are correct Vitalije, the find tab and dialog are not related to this show-fonts issue. I only tacked on the comment about the find tab. The Find tab is back in action.

**Comment by edreamleo** [comment]
On Mon, Jul 10, 2017 at 9:04 AM, LewisNeal <notifications@github.com> wrote:

> Yes you are correct Vitalije, the find tab and dialog are not related to
> this show-fonts issue. I only tacked on the comment about the find tab. The
> Find tab is back in action.
>

​Oh good.  Glad to hear it.

Edward
