### ISSUE TITLE
@persistence doesn't retain tags and links (uA's)

### ISSUE THREAD

**Issue by largo84** [leo-editor/leo-editor#526]
1. myLeoSettings.leo sets the following to override defaults:
    `@bool enable-persistence = True`
    `@bool create-at-persistence-nodes-automatically = True`
2. Create `@auto-md` node.
    * Create several nodes.
    * Tag nodes using nodetags plugin.
    * Create links using backlink plugin.
3. Save and close the xxx.leo file.
    * `@persistence node` is created if it was not there already.
4. Re-open the xxx.leo file. *All of the tags and links are missing.*

The attached example files should illustrate behavior. Discussion of this on the forum [here](https://groups.google.com/d/msg/leo-editor/TzDyhUDCNUI/pyMAsSuDAgAJ).
Environment:
Leo 5.5, build 20170712062357, Wed Jul 12 06:23:57 CDT 2017
Git repo info: branch = master, commit = bec5e2651aec
Python 3.4.3, PyQt version 5.4.1
Windows 8 AMD64 (build 6.2.9200) 
isPython3: True
caching enabled

**Comment by largo84** [comment]
Tried to attach a .leo and .md file, but got an error about file type not supported.

**Comment by tbnorth** [comment]
Links and I assume tags rely on `v.u`.  Links also rely on persistence of gnxs, i.e. nodes in an auto file would need the same gnx to remain link targets.  Just background for those that know how persistence works ;-)

**Comment by edreamleo** [comment]
On Thu, Jul 13, 2017 at 8:21 AM, Rob Keeney <notifications@github.com>
wrote:

>
>    1. myLeoSettings.leo sets the following to override defaults:
>    @Bool <https://github.com/bool> enable-persistence = True
>    @Bool <https://github.com/bool> create-at-persistence-nodes-automatically
>    = True
>    2. Create @auto-md node.
>       - Create several nodes.
>       - Tag nodes using nodetags plugin.
>       - Create links using backlink plugin.
>    3. Save and close the xxx.leo file.
>       - @persistence <https://github.com/persistence> node is created if
>       it was not there already.
>    4. Re-open the xxx.leo file. *All of the tags and links are missing.*
>
> The attached example files should illustrate behavior. Discussion of this
> on the forum here
> <https://groups.google.com/d/msg/leo-editor/TzDyhUDCNUI/pyMAsSuDAgAJ>.
>

​Thanks for this report.  I'll put it on the list and mark it "First".

Edward

**Comment by edreamleo** [comment]
This looks like a fairly simple botch that has been around for months, if not years.  I expect to fix this later today.

**Comment by edreamleo** [comment]
f302ae8 in the "persist" branch  looks like it fixes this issue.  However, more testing is needed.  I'll leave this item open and will delay merging into master for a day at least.

**Comment by largo84** [comment]
Not sure how to test this. I don't understand GitHub well enough (using GH Desktop for Windows) to know how to get this on my machine to try it. Also, I'll be traveling for the next several weeks, so testing will be intermittent at best.

**Comment by edreamleo** [comment]
On Fri, Jul 14, 2017 at 10:57 AM, Rob Keeney <notifications@github.com>
wrote:

​> ​
Not sure how to test this. I don't understand GitHub well enough (using GH
Desktop for Windows) to know how to get this on my machine to try it.

​ git fetch
 git checkout persist
 git pull

Now you should have the latest version.  Test as usual.

> Also, I'll be traveling for the next several weeks, so testing will be
intermittent at best.

That will be no problem.  We'll have lots of testers after merging persist
into master.

Edward

**Comment by largo84** [comment]
First test of this branch looks good so far. All tags appear to be retained as expected.

**Comment by edreamleo** [comment]
On Fri, Jul 14, 2017 at 4:03 PM, Rob Keeney <notifications@github.com>
wrote:

> First test of this branch looks good so far. All tags appear to be
> retained as expected.
>
​Oh good.  Thanks for the confirmation.

This was a strange one.  It appears that @persistence has been broken a
long time, perhaps even before the changeover to git.

Edward

**Comment by largo84** [comment]
Hmm, wondering if I'm the only one who uses it.

**Comment by edreamleo** [comment]
On Fri, Jul 14, 2017 at 5:25 PM, Rob Keeney <notifications@github.com>
wrote:

> Hmm, wondering if I'm the only one who uses it.
>
​Heh. More might start using it now :-)

Edward

**Comment by xgdomingo** [comment]
El 14/07/2017 a las 19:25, Rob Keeney escribió:
>
> Hmm, wondering if I'm the only one who uses it.
>
I tried to use tags in nodes under @auto trees some months ago but 
discovered that they did not persist, so I thought it was not possible. 
I didn't know about @persistence at that time... and I didn't ask!

Thanks for reporting this so we can now get the benefits!
Xavier
