### ISSUE TITLE
@menuat duplicates menus when myLeoSettings is opened

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#528]
I have added a small menuat tree to myLeoSettings to add a custom menu. At first opening of Leo the custom menu appears as expected. If I open myLeoSettings during this session, a duplicate set of custom menu items appears. Every time I open myLeoSettings during this session, it adds another set of custom menu items. 

Close Leo completely and reopen any file, the menus appear correctly.

Leo 5.5, build 20170715081418, Sat Jul 15 08:14:18 CDT 2017
Git repo info: branch = master, commit = 15cd7bf1e42a
Python 3.6.1, PyQt version 5.9.1
Windows 10 AMD64 (build 10.0.15063) SP0

**Comment by edreamleo** [comment]
On Sun, Jul 16, 2017 at 4:59 AM, LewisNeal <notifications@github.com> wrote:

> I have added a small menuat tree to myLeoSettings to add a custom menu. At
> first opening of Leo the custom menu appears as expected. If I open
> myLeoSettings during this session, a duplicate set of custom menu items
> appears. Every time I open myLeoSettings during this session, it adds
> another set of custom menu items.
>
> Close Leo completely and reopen any file, the menus appear correctly.
>
​Sounds interesting.  Care to share the code?

Edward

**Comment by LewisNeal** [comment]
Here is the simple myLeoSettings file. When I open myLeoSettings during this session I get log message
menu already exists: &Extra
menu already exists: &SpecCmds
menu already exists: &Level2

Lewis

[myLeoSettings.txt](https://github.com/leo-editor/leo-editor/files/1151442/myLeoSettings.txt)

**Comment by edreamleo** [comment]
On Sun, Jul 16, 2017 at 7:44 PM, LewisNeal <notifications@github.com> wrote:

> Here is the simple myLeoSettings file. When I open myLeoSettings during
> this session I get log message
> menu already exists: &Extra
> menu already exists: &SpecCmds
> menu already exists: &Level2
>
​I am not able to access myLeoSettings.txt.  Please cut/paste it into this
issue.

Edward

**Comment by LewisNeal** [comment]
I was able to right-click > save link as

OK here is the file in text editor:

<?xml version="1.0" encoding="utf-8"?>

<leo_file xmlns:leo="http://leoeditor.com/namespaces/leo-python-editor/1.1" >
<leo_header file_format="2" tnodes="0" max_tnode_index="0" clone_windows="0"/>
<globals body_outline_ratio="0.5" body_secondary_ratio="0.5">
	<global_window_position top="50" left="50" height="500" width="700"/>
	<global_log_window_position top="0" left="0" height="0" width="0"/>
</globals>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="ekr.20070622214401"><vh>Startup</vh></v>
<v t="lewis.20131123111241.4356"><vh>About myLeoSettings.leo</vh></v>
<v t="ekr.20041119034357.1" a="E"><vh>@settings</vh>
<v t="lewis.20170717083607.1" a="E"><vh>@menuat /help/ after</vh>
<v t="lewis.20170717083607.2" a="E"><vh>@menu &amp;Extra</vh>
<v t="lewis.20170717083607.4"><vh>@item listen-to-log</vh></v>
<v t="lewis.20170717083607.5" a="E"><vh>@menu &amp;SpecCmds</vh>
<v t="lewis.20170717083607.6" a="E"><vh>@menu &amp;Level2</vh>
<v t="lewis.20170717083607.7"><vh>@item close-window</vh></v>
</v>
</v>
</v>
</v>
<v t="ekr.20051123100536"><vh>Plugins</vh>
<v t="ekr.20070417071249"><vh>@bool trace_plugins = True</vh></v>
<v t="ekr.20070224073109.1"><vh>@enabled-plugins</vh></v>
</v>
</v>
</vnodes>
<tnodes>
<t tx="ekr.20041119034357.1">@language rest

This @settings tree contains all active settings.

Settings outside this tree have no effect.
</t>
<t tx="ekr.20051123100536">Note: These settings have effect only if the corresponding plugin has been enabled.</t>
<t tx="ekr.20070224073109.1"># Leo loads plugins in the order they appear here.
# Highly-recommended plugins:

plugins_menu.py

# free_layout.py
    # Now loaded automatically.
    # needs to be early
    # if enabled the viewrendered pane is locked, not free

# All other plugins.
# Order is important for enabled plugins that
# add items to the icon area.
redirect_to_log.py

</t>
<t tx="ekr.20070417071249">True: show info as plugins are loaded.</t>
<t tx="ekr.20070622214401"></t>
<t tx="lewis.20131123111241.4356">@language rest

This BARE-BONES myLeoSettings.leo is for testing only.

</t>
<t tx="lewis.20170717083607.1">see http://leoeditor.com/customizing.html#menuat</t>
<t tx="lewis.20170717083607.2"></t>
<t tx="lewis.20170717083607.4">&amp;listen-to-log</t>
<t tx="lewis.20170717083607.5"></t>
<t tx="lewis.20170717083607.6"></t>
<t tx="lewis.20170717083607.7">&amp;Close</t>
</tnodes>
</leo_file>

**Comment by LewisNeal** [comment]
All fixed. Thanks :)

**Comment by edreamleo** [comment]
On Wed, Aug 23, 2017 at 5:14 PM, LewisNeal <notifications@github.com> wrote:

> All fixed. Thanks :)
>

​You're welcome.​ I could find no solution for the menu warning except to
disable it entirely.

Edward
