### ISSUE TITLE
print-commands possible garbage output and more output than the log pane can hold

### ISSUE THREAD

**Issue by SegundoBob** [leo-editor/leo-editor#530]
Is the initial output correct or garbage?  ":!" ":%s" etc.

There needs to be a way to redirect the output to a file or a way to increase the total number of lines or bytes that the log pane saves.  Printing information that the user can't read isn't helpful.

**Test System**

> Leo Log Window
> Leo 5.5, build 20170526124207, Fri May 26 12:42:07 CDT 2017
> Git repo info: branch = close-git-files, commit = 4ab3854c4619
> Python 3.5.2, PyQt version 5.5.1
> linux
> 

and 

> Leo Log Window
> Leo 5.5, build 20170715081418, Sat Jul 15 08:14:18 CDT 2017
> Git repo info: branch = master, commit = 15cd7bf1e42a
> Python 3.5.2, PyQt version 5.5.1
> linux
> 

**print-commands output saved in log pane**

>                   :!
>                   :%s
>                   :e
>                   :e!
>                   :gT
>                   :gt
>                   :print-dot
>                   :q
>                   :q!
>                   :qa
>                   :r
>                   :s
>                   :tabnew
>                   :toggle-vim-mode
>                   :toggle-vim-trace
>                   :toggle-vim-trainer-mode
>                   :w
>                   :wq
>                   :xa
>                   @command-bob-abandoned
>                   @command-bob-babel
>                   @command-bob-childcount
>                   @command-bob-day
>                   @command-bob-deferred
>                   @command-bob-deletetrailingwhitespace
>                   @command-bob-done
>                   @command-bob-full
>                   @command-bob-google-it
> button: Alt+=     @command-bob-goto-last-child
>                   @command-bob-later
>                   @command-bob-meld-childs
>                   @command-bob-meld-marked
>                   @command-bob-mp-es-pr-log
>                   @command-bob-mp-es-pr-std
>                   @command-bob-mp-es-pr-time
>                   @command-bob-nnc-day
>                   @command-bob-nnc-full
>                   @command-bob-nnc-time
>                   @command-bob-nnc-yesterday
>                   @command-bob-nns-day
>                   @command-bob-nns-full
>                   @command-bob-nns-time
>                   @command-bob-nns-yesterday
>                   @command-bob-pgnx
>                   @command-bob-reconsider
>                   @command-bob-remove-line-breaks
>                   @command-bob-reverse-siblings
>                   @command-bob-subtreecount
>                   @command-bob-time
>                   @command-bob-xxdiff-childs
>                   @command-bob-xxdiff-marked
>                   @command-bob-yesterday
>                   abbrev-kill-all
>                   abbrev-list
>                   abort-edit-headline
>                   about-leo
>                   act-on-node
>                   activate-cmds-menu
>                   activate-edit-menu
>                   activate-file-menu
>                   activate-help-menu
>                   activate-outline-menu
>                   activate-plugins-menu
>                   activate-window-menu
> Ctrl+(            add-comments
>                   add-editor
>                   add-space-to-lines
>                   add-tab-to-lines
>                   at-file-to-at-auto
>                   attrib-edit-create
>                   attrib-edit-manage
>                   attrib-edit-modes
>                   attrib-edit-scan
> .                 auto-complete
> Ctrl+Space        auto-complete-force
>                   back-char
>                   back-char-extend-selection
>                   back-page
>                   back-page-extend-selection
>                   back-paragraph
>                   back-paragraph-extend-selection
>                   back-sentence
>                   back-sentence-extend-selection
> Home              back-to-home
>                   back-to-home-extend-selection
>                   back-to-indentation
> Ctrl+Left         back-word
> Ctrl+Shift+Left   back-word-extend-selection
>                   back-word-smart
>                   back-word-smart-extend-selection
> Shift+BackSpace   backward-delete-char
> Ctrl+BackSpace    backward-delete-word
>                   backward-delete-word-smart
> Alt+Q             backward-find-character
> Alt+Shift+Q       backward-find-character-extend-selection
>                   backward-kill-paragraph
>                   backward-kill-sentence
> Alt+BackSpace     backward-kill-word
>                   beautify-c
>                   beautify-node
>                   beautify-tree
> Ctrl+Home         beginning-of-buffer
> Ctrl+Shift+Home   beginning-of-buffer-extend-selection
>                   beginning-of-line
> Ctrl+Shift+A      beginning-of-line-extend-selection
>                   bob-abandoned
>                   bob-babel
>                   bob-childcount
>                   bob-day
>                   bob-deferred
>                   bob-deletetrailingwhitespace
>                   bob-done
>                   bob-full
>                   bob-google-it
>                   bob-goto-last-child
>                   bob-later
>                   bob-meld-childs
>                   bob-meld-marked
>                   bob-mp-es-pr-log
>                   bob-mp-es-pr-std
>                   bob-mp-es-pr-time
>                   bob-nnc-day
>                   bob-nnc-full
>                   bob-nnc-time
>                   bob-nnc-yesterday
>                   bob-nns-day
>                   bob-nns-full
>                   bob-nns-time
>                   bob-nns-yesterday
>                   bob-pgnx
>                   bob-reconsider
>                   bob-remove-line-breaks
>                   bob-reverse-siblings
>                   bob-subtreecount
>                   bob-time
>                   bob-xxdiff-childs
>                   bob-xxdiff-marked
>                   bob-yesterday
>                   bookmarks-bookmark
>                   bookmarks-bookmark-child
>                   bookmarks-bookmark-find-flat
>                   bookmarks-bookmark-organizer
>                   bookmarks-level-decrease
>                   bookmarks-level-increase
>                   bookmarks-mark-as-target
>                   bookmarks-open-bookmark
>                   bookmarks-open-node
>                   bookmarks-show
>                   bookmarks-switch
>                   bookmarks-use-other-outline
>                   c-to-python
>                   capitalize-word
>                   cascade-windows
>                   center-line
>                   center-region
>                   cfa
>                   cfam
>                   cff
>                   cffm
>                   cft
>                   chapter-back
>                   chapter-next
>                   chapter-select
>                   chapter-select-main
>                   cheat-sheet
>                   check-derived-file
>                   check-leo-file
>                   check-outline
>                   cke-text-close
>                   cke-text-open
>                   cke-text-switch
>                   cke-text-toggle-autosave
>                   clean-all-lines
>                   clean-at-clean-files
>                   clean-at-clean-tree
>                   clean-lines
>                   clean-persistence
>                   clean-recent-files
>                   clear-all-caches
>                   clear-all-uas
>                   clear-cache
>                   clear-extend-mode
>                   clear-kill-ring
>                   clear-log
>                   clear-node-uas
>                   clear-recent-files
>                   clear-selected-text
>                   click-click-box
>                   click-headline
>                   click-icon-box
>                   clone-find-all
>                   clone-find-all-flattened
>                   clone-find-all-flattened-marked
>                   clone-find-all-marked
>                   clone-find-parents
>                   clone-find-tag
>                   clone-marked-nodes
> Ctrl+`            clone-node
>                   clone-node-to-last-node
>                   clone-to-at-spot
>                   close-others
> Ctrl+F4           close-window
>                   cls
>                   cm-external-editor
>                   code-to-rst
>                   context-menu-open
> Alt+-             contract-all
>                   contract-all-other-nodes
>                   contract-body-pane
>                   contract-log-pane
>                   contract-node
> Alt+Left          contract-or-go-left
>                   contract-outline-pane
> Alt+Ctrl+-        contract-pane
>                   contract-parent
>                   convert-all-blanks
>                   convert-all-tabs
>                   convert-blanks
>                   convert-tabs
>                   copy-marked-nodes
> Ctrl+Shift+C      copy-node
> Ctrl+C            copy-text
>                   count-region
>                   ctrl-click-at-cursor
>                   ctrl-click-icon
> Ctrl+Shift+X      cut-node
> Ctrl+X            cut-text
>                   cycle-editor-focus
>                   cycle-focus
>                   cycle-tab-focus
> Alt+Ctrl+/        dabbrev-completion
> Alt+/             dabbrev-expands
>                   de-hoist
>                   debug
>                   dehoist
> Shift+Delete      delete-char
> Ctrl+Shift+0      delete-comments
>                   delete-editor
>                   delete-first-icon
>                   delete-indentation
>                   delete-last-icon
>                   delete-marked-nodes
> text: Delete      delete-node
> tree: Delete      delete-node
>                   delete-node-icons
>                   delete-script-button-button
>                   delete-spaces
> Ctrl+Delete       delete-word
>                   delete-word-smart
> Ctrl+]            demote
>                   detach-editor-toggle
>                   detach-editor-toggle-max
>                   diff-marked-nodes
>                   directory-make
>                   directory-remove
>                   disable-autocompleter
>                   disable-calltips
>                   disable-idle-time-events
> Shift+F4          do-nothing
>                   double-click-headline
> Ctrl+F3           double-click-icon-box
>                   downcase-region
>                   downcase-word
>                   dump-outline
> Ctrl+H            edit-headline
>                   editor-add
>                   editor-cycle-focus
>                   editor-delete
>                   enable-autocompleter
>                   enable-calltips
>                   enable-idle-time-events
>                   end-edit-headline
> Ctrl+End          end-of-buffer
> Ctrl+Shift+End    end-of-buffer-extend-selection
> End               end-of-line
> Shift+End         end-of-line-extend-selection
>                   enter-quick-command-mode
>                   equal-sized-panes
>                   escape
>                   eval-expression
> Alt+M             exchange-point-mark
> Ctrl+B            execute-script
> Ctrl+Q            exit-leo
>                   exit-named-mode
>                   expand-all
>                   expand-all-subheads
>                   expand-ancestors-only
> Alt+Right         expand-and-go-right
>                   expand-body-pane
>                   expand-log-pane
>                   expand-next-level
> Alt+]             expand-node
>                   expand-or-go-right
>                   expand-outline-pane
> Alt+Ctrl+=        expand-pane
>                   expand-prev-level
>                   expand-to-level-1
>                   expand-to-level-2
>                   expand-to-level-3
>                   expand-to-level-4
>                   expand-to-level-5
>                   expand-to-level-6
>                   expand-to-level-7
>                   expand-to-level-8
>                   expand-to-level-9
>                   export-headlines
>                   export-html
>                   export-html-bullet
>                   export-html-head
>                   export-html-node
>                   export-html-node-bullet
>                   export-html-node-head
>                   export-html-node-number
>                   export-html-number
>                   export-jupyter-notebook
> Alt+L             extend-to-line
>                   extend-to-paragraph
>                   extend-to-sentence
> Ctrl+W            extend-to-word
> Ctrl+Shift+D      extract
> Ctrl+Shift+N      extract-names
>                   file-compare-leo-files
>                   file-delete
>                   file-diff-files
>                   file-insert
>                   file-open-by-name
>                   file-save
>                   fill-paragraph
>                   fill-region
>                   fill-region-as-paragraph
>                   find-all
>                   find-character
>                   find-character-extend-selection
>                   find-clone-all
>                   find-clone-all-flattened
>                   find-clone-tag
>                   find-def
> F3                find-next
>                   find-next-clone
> F2                find-prev
>                   find-quick
>                   find-quick-changed
> Ctrl+Shift+F      find-quick-selected
>                   find-quick-test-failures
>                   find-quick-timeline
>                   find-tab-hide
>                   find-tab-open
>                   find-var
>                   find-word
>                   find-word-in-line
>                   flake8
>                   flatten-outline
>                   flatten-outline-to-node
>                   flush-lines
> Alt+D             focus-to-body
>                   focus-to-find
>                   focus-to-log
>                   focus-to-minibuffer
>                   focus-to-nav
>                   focus-to-spell-tab
> Alt+T             focus-to-tree
> tree: Right       forward-char
> text: Right       forward-char
>                   forward-char-extend-selection
>                   forward-end-word
>                   forward-end-word-extend-selection
>                   forward-page
>                   forward-page-extend-selection
> Alt+}             forward-paragraph
> Alt+Shift+}       forward-paragraph-extend-selection
>                   forward-sentence
>                   forward-sentence-extend-selection
> Ctrl+Right        forward-word
> Ctrl+Shift+Right  forward-word-extend-selection
>                   forward-word-smart
>                   forward-word-smart-extend-selection
>                   free-layout-context-menu
>                   free-layout-load
>                   free-layout-load-default
>                   free-layout-restore
>                   free-layout-zoom
> Alt+X             full-command
>                   fully-expand-body-pane
>                   fully-expand-log-pane
>                   fully-expand-outline-pane
>                   fully-expand-pane
>                   gc-collect-garbage
>                   gc-dump-all-objects
>                   gc-dump-new-objects
>                   gc-dump-objects-verbose
>                   gc-print-summary
>                   gc-trace-disable
>                   gc-trace-enable
>                   go-anywhere
>                   go-back
>                   go-forward
>                   goto-any-clone
>                   goto-char
>                   goto-first-node
>                   goto-first-sibling
> Alt+Home          goto-first-visible-node
> Alt+G             goto-global-line
>                   goto-last-node
> Alt+End           goto-last-sibling
>                   goto-last-visible-node
>                   goto-line
>                   goto-next-changed
> Alt+N             goto-next-clone
>                   goto-next-history-node
> Ctrl+Shift+M      goto-next-marked
>                   goto-next-node
>                   goto-next-sibling
> Alt+Down          goto-next-visible
>                   goto-parent
>                   goto-prev-history-node
>                   goto-prev-node
>                   goto-prev-sibling
> Alt+Up            goto-prev-visible
>                   gui-all-hide
>                   gui-all-show
>                   gui-all-toggle
>                   gui-iconbar-hide
>                   gui-iconbar-show
>                   gui-iconbar-toggle
>                   gui-menu-hide
>                   gui-menu-show
>                   gui-menu-toggle
>                   gui-minibuffer-hide
>                   gui-minibuffer-show
>                   gui-minibuffer-toggle
>                   gui-statusbar-hide
>                   gui-statusbar-show
>                   gui-statusbar-toggle
>                   gui-tabbar-hide
>                   gui-tabbar-show
>                   gui-tabbar-toggle
>                   head-to-prev-node
> F1                help
>                   help-for-abbreviations
>                   help-for-autocompletion
>                   help-for-bindings
> F11               help-for-command
>                   help-for-creating-external-files
>                   help-for-debugging-commands
>                   help-for-drag-and-drop
>                   help-for-dynamic-abbreviations
>                   help-for-find-commands
>                   help-for-keystroke
>                   help-for-minibuffer
> F12               help-for-python
>                   help-for-regular-expressions
>                   help-for-scripting
>                   hide-body-pane
>                   hide-invisibles
>                   hide-log-pane
>                   hide-outline-pane
>                   hide-pane
>                   history
>                   hoist
>                   iconify-frame
>                   import-MORE-files
>                   import-file
>                   import-free-mind-files
>                   import-jupyter-notebook
>                   import-mind-jet-files
>                   import-tabbed-files
>                   import-zim-folder
> Ctrl+>            indent-region
>                   indent-relative
>                   indent-rigidly
>                   indent-to-comment-column
>                   insert-body-time
> Ctrl+Insert       insert-child
>                   insert-file-name
>                   insert-hard-tab
>                   insert-headline-time
>                   insert-icon
> tree: Return      insert-newline
> body: Return      insert-newline
> Shift+Insert      insert-node
>                   insert-node-before
>                   insert-parentheses
>                   insert-soft-tab
> Alt+R             isearch-backward
>                   isearch-backward-regexp
> Alt+I             isearch-forward
>                   isearch-forward-regexp
>                   isearch-with-present-options
>                   join-leo-irc
>                   justify-toggle-auto
>                   keep-lines
> Ctrl+G            keyboard-quit
> Ctrl+K            kill-line
>                   kill-log-listener
>                   kill-paragraph
>                   kill-pylint
>                   kill-region
>                   kill-region-save
>                   kill-sentence
>                   kill-to-end-of-line
>                   kill-word
>                   kill-ws
>                   leo-cheat-sheet
>                   leo-dist-leo
>                   leo-docs-leo
>                   leo-plugins-leo
>                   leo-py-leo
>                   leo-quickstart-leo
>                   leo-scripts-leo
>                   leo-settings-leo
>                   leo-unittest-leo
>                   line-number
>                   listen-to-log
>                   log-kill-listener
>                   log-listen
>                   make-stub-files
> Ctrl+M            mark
>                   mark-changed-items
>                   mark-subheads
>                   marked-list
>                   match-brackets
> Alt+P             menu-shortcut
>                   minimize-all
>                   mode-help
> tree: Ctrl+Down   move-lines-down
> body: Ctrl+Down   move-lines-down
> tree: Ctrl+Up     move-lines-up
> body: Ctrl+Up     move-lines-up
>                   move-marked-nodes
> Ctrl+D            move-outline-down
> Alt+Shift+Left    move-outline-left
> text: Shift+Right move-outline-right
> tree: Shift+Right move-outline-right
> Alt+Shift+Up      move-outline-up
> Alt+)             move-past-close
>                   move-past-close-extend-selection
>                   my-leo-settings-leo
> Ctrl+N            new
> Tab               newline-and-indent
> tree: Down        next-line
> text: Down        next-line
> tree: Shift+Down  next-line-extend-selection
> text: Shift+Down  next-line-extend-selection
>                   open-cheat-sheet-leo
>                   open-leo-dist-leo
>                   open-leo-docs-leo
>                   open-leo-plugins-leo
>                   open-leo-py-leo
>                   open-leo-settings-leo
>                   open-local-settings
>                   open-myLeoSettings-leo
>                   open-offline-tutorial
>                   open-online-home
>                   open-online-toc
>                   open-online-tutorials
>                   open-online-videos
> Ctrl+O            open-outline
>                   open-python-window
>                   open-quickstart-leo
>                   open-scripts-leo
>                   open-unittest-leo
> Alt+F3            open-url
>                   open-url-under-cursor
>                   open-users-guide
> Alt+Ctrl+Shift+E  open-with-emacs
>                   outline-to-cweb
>                   outline-to-noweb
>                   parse-body
> Ctrl+Shift+V      paste-node
> Alt+Shift+V       paste-retaining-clones
> Ctrl+V            paste-text
>                   pdb
>                   pretty-print-c
>                   pretty-print-node
>                   pretty-print-tree
>                   preview-body
>                   preview-expanded-body
>                   preview-expanded-html
>                   preview-html
>                   preview-marked-bodies
>                   preview-marked-html
>                   preview-marked-nodes
>                   preview-node
>                   preview-tree-bodies
>                   preview-tree-html
>                   preview-tree-nodes
> tree: Up          previous-line
> text: Up          previous-line
> tree: Shift+Up    previous-line-extend-selection
> text: Shift+Up    previous-line-extend-selection
>                   print-all-uas
>                   print-bindings
>                   print-body
>                   print-buttons
>                   print-commands
>                   print-expanded-body
>                   print-expanded-html
>                   print-focus
>                   print-html
>                   print-marked-bodies
>                   print-marked-html
>                   print-marked-nodes
>                   print-node
>                   print-node-uas
>                   print-plugin-handlers
>                   print-plugins-info
>                   print-settings
>                   print-style-sheet
>                   print-tree-bodies
>                   print-tree-html
>                   print-tree-nodes
> Ctrl+{            promote
>                   pyflakes
>                   pylint
>                   pylint-kill
>                   python-to-coffeescript
>                   quickmove_bookmark_to_first_child
>                   quickmove_bookmark_to_last_child
>                   quickmove_bookmark_to_next_sibling
>                   quickmove_bookmark_to_prev_sibling
>                   quickmove_clone_to_first_child
>                   quickmove_clone_to_last_child
>                   quickmove_clone_to_next_sibling
>                   quickmove_clone_to_prev_sibling
>                   quickmove_copy_to_first_child
>                   quickmove_copy_to_last_child
>                   quickmove_copy_to_next_sibling
>                   quickmove_copy_to_prev_sibling
>                   quickmove_jump_to
>                   quickmove_keyboard_action
>                   quickmove_keyboard_popup
>                   quickmove_link_from
>                   quickmove_link_to
>                   quickmove_move_to_first_child
>                   quickmove_move_to_last_child
>                   quickmove_move_to_next_sibling
>                   quickmove_move_to_prev_sibling
>                   quickmove_visit_next_target
>                   re-search-backward
>                   re-search-forward
>                   read-at-auto-nodes
>                   read-at-file-nodes
>                   read-at-shadow-nodes
>                   read-file-into-node
>                   read-outline-only
>                   recolor
>                   rectangle-clear
>                   rectangle-close
>                   rectangle-delete
>                   rectangle-kill
>                   rectangle-open
>                   rectangle-string
>                   rectangle-yank
> Ctrl+Shift+Z      redo
> Ctrl+Shift+P      reformat-paragraph
>                   refresh-from-disk
>                   reload-all-settings
>                   reload-settings
>                   remove-blank-lines
>                   remove-sentinels
>                   remove-space-from-lines
>                   remove-tab-from-lines
> Ctrl+P            repeat-complex-command
> Ctrl+=            replace
>                   replace-all
>                   replace-current-character
> Ctrl+-            replace-then-find
>                   resize-to-screen
>                   reverse-region
>                   reverse-sort-lines
>                   reverse-sort-lines-ignoring-case
>                   revert
>                   right-click-headline
>                   right-click-icon
>                   rst3
>                   run-all-unit-tests-externally
>                   run-all-unit-tests-locally
>                   run-marked-unit-tests-externally
>                   run-marked-unit-tests-locally
>                   run-selected-unit-tests-externally
>                   run-selected-unit-tests-locally
>                   save-all
>                   save-buffers-kill-leo
> Ctrl+S            save-file
>                   save-file-as
>                   save-file-as-unzipped
>                   save-file-as-zipped
>                   save-file-to
>                   script-button
> text: Shift+Next  scroll-down-half-page
> tree: Shift+Next  scroll-down-half-page
>                   scroll-down-line
> text: Next        scroll-down-page
> tree: Next        scroll-down-page
>                   scroll-outline-down-line
>                   scroll-outline-down-page
>                   scroll-outline-left
>                   scroll-outline-right
>                   scroll-outline-up-line
>                   scroll-outline-up-page
> text: Shift+Prior scroll-up-half-page
> tree: Shift+Prior scroll-up-half-page
>                   scroll-up-line
> text: Prior       scroll-up-page
> tree: Prior       scroll-up-page
>                   search-backward
>                   search-forward
> Ctrl+A            select-all
>                   select-to-matching-bracket
>                   session-clear
>                   session-create
>                   session-refresh
>                   session-restore
>                   session-snapshot-load
>                   session-snapshot-save
>                   set-colors
>                   set-command-state
>                   set-comment-column
>                   set-extend-mode
>                   set-fill-column
>                   set-fill-prefix
> Alt+Ctrl+E        set-find-everywhere
> Alt+Ctrl+N        set-find-node-only
> Alt+Ctrl+S        set-find-suboutline-only
>                   set-font
>                   set-insert-state
>                   set-overwrite-state
>                   set-replace-string
>                   set-search-string
>                   set-silent-mode
>                   set-ua
>                   settings
>                   shell-command
>                   shell-command-on-region
> (                 show-calltips
>                   show-calltips-force
>                   show-color-names
>                   show-color-wheel
>                   show-find-options
>                   show-fonts
>                   show-html
>                   show-html-bullet
>                   show-html-head
>                   show-html-node
>                   show-html-node-bullet
>                   show-html-node-head
>                   show-html-node-number
>                   show-html-number
>                   show-invisibles
>                   simulate-begin-drag
>                   simulate-end-drag
>                   sort-children
>                   sort-columns
>                   sort-fields
>                   sort-lines
>                   sort-lines-ignoring-case
>                   sort-recent-files
> Alt+A             sort-siblings
>                   spell-as-you-type-next
>                   spell-as-you-type-toggle
>                   spell-as-you-type-undo
>                   spell-as-you-type-wrap
>                   spell-change
>                   spell-change-then-find
>                   spell-find
>                   spell-ignore
>                   spell-tab-hide
> F7                spell-tab-open
>                   split-line
> Ctrl+F            start-search
>                   stickynote
>                   stickynote-new
>                   stickynoter
>                   style-reload
>                   style-set-selected
>                   suspend
> Ctrl+Tab          tab-cycle-next
> Ctrl+Prior        tab-cycle-previous
>                   tab-detach
>                   tabify
>                   tabula
>                   tabula-marked
>                   tabula-show
>                   tabula-subtree
>                   tag-children
>                   tail-to-next-node
>                   tangle
>                   tangle-all
>                   tangle-marked
>                   toggle-abbrev-mode
> Ctrl+T            toggle-active-pane
>                   toggle-angle-brackets
> Alt+1             toggle-autocompleter
> Alt+2             toggle-calltips
>                   toggle-case-region
> Alt+3             toggle-extend-mode
>                   toggle-find-collapses-nodes
> Alt+Ctrl+I        toggle-find-ignore-case-option
> Alt+Ctrl+B        toggle-find-in-body-option
> Alt+Ctrl+H        toggle-find-in-headline-option
> Alt+Ctrl+C        toggle-find-mark-changes-option
> Alt+Ctrl+F        toggle-find-mark-finds-option
> Alt+Ctrl+X        toggle-find-regex-option
> Alt+Ctrl+W        toggle-find-word-option
> Alt+Ctrl+A        toggle-find-wrap-around-option
>                   toggle-idle-time-events
>                   toggle-input-state
>                   toggle-invisibles
>                   toggle-sparse-move
>                   toggle-split-direction
>                   transpose-chars
>                   transpose-lines
>                   transpose-words
>                   typescript-to-py
> Ctrl+Z            undo
> Ctrl+Shift+U      unformat-paragraph
> Shift+Tab         unindent-region
>                   unmark-all
>                   untabify
>                   untangle
>                   untangle-all
>                   untangle-marked
>                   upcase-region
>                   upcase-word
>                   view-lossage
>                   vs-create-tree
>                   vs-dump
>                   vs-eval
>                   vs-eval-block
>                   vs-last
>                   vs-last-pretty
>                   vs-reset
>                   vs-update
>                   weave
>                   what-line
>                   word-search-backward
>                   word-search-forward
>                   write-at-auto-nodes
> Ctrl+Shift+W      write-at-file-nodes
>                   write-at-shadow-nodes
>                   write-dirty-at-auto-nodes
> Ctrl+Shift+Q      write-dirty-at-file-nodes
>                   write-dirty-at-shadow-nodes
>                   write-file-from-node
>                   write-missing-at-file-nodes
>                   write-outline-only
> Ctrl+Y            yank
> Alt+Y             yank-pop
> Alt+Z             zap-to-character
>                   zoom-in
>                   zoom-out
>

**Comment by SegundoBob** [comment]
I no longer see this problem:

**Test System**
> Leo Log Window
> Leo 5.5, build 20170718062026, Tue Jul 18 06:20:26 CDT 2017
> Git repo info: branch = master, commit = 911001d30f73
> Python 3.5.2, PyQt version 5.5.1
> linux
> isPython3: True
> caching enabled

**Comment by vitalije** [comment]
I am not sure, but all except `:%s` looks like vim commands. I don't use vim but if I remember correct by pressing `:` vim enters command mode (next letter is command).  If that's the case then this is not garbage output.

**Comment by edreamleo** [comment]
The output of the print-commands command is correct.

Recent revs use g.es_print instead of g.es for this and similar commands, so output also goes to the console, if present.

I am going to close this item.  The request to redirect output from these commands would be too minor a feature.  Copy/paste suffices.
