### ISSUE TITLE
Optionally report timestamp when issuing file-related messages

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#531]
Requested [here](https://groups.google.com/forum/#!topic/leo-editor/EwjKGZWgloQ).  For example,

```
    07:31:20 wrote: base.py
    07:31:20 wrote: test_views.py
    07:31:20 saved: joyroost.leo
    07:38:20 wrote: test_views.py
    07:38:20 saved: joyroost.leo
    07:42:18 wrote: test_views.py
    07:42:18 saved: joyroost.leo
```
Leo's write code in leoFileCommands.py and leoAtFile.py issue these messages.  They, not g.es, should be responsible for computing the timestamp.

**Settings**
```
    @bool log_show_save_time = False
    @string log_timestamp_format = %H:%M:%S
```
The format argument to [strftime](https://docs.python.org/2/library/time.html#time.strftime).

**Comment by edreamleo** [comment]
Rev 3806c39 in master completes this item.  To enable, set `@bool log_show_save_time = True` in myLeoSettings.leo.

**Comment by tbnorth** [comment]
@edreamleo just wondering why do this in the write code vs. g.es() - time stamping log messages seems like a logging function to me, and done at the g.es() level (with with_time=True) puts it in place for anything else people want timestamped in the future.  (replace g.es() with the relevant logging method if it's not g.es()).

**Comment by edreamleo** [comment]
On Tue, Jul 18, 2017 at 7:02 AM, Terry Brown <notifications@github.com>
wrote:

> @edreamleo <https://github.com/edreamleo> just wondering why do this in
> the write code vs. g.es() - time stamping log messages seems like a
> logging function to me, and done at the g.es() level (with
> with_time=True) puts it in place for anything else people want timestamped
> in the future. (replace g.es() with the relevant logging method if it's
> not g.es()).
>
​Glad you asked.  I would prefer to keep g.es as simple as possible.  It's
already unexpectedly difficult.

As written, the calling code has full control over format. That's not
possible with your proposal unless calling code also passes "c" to g.es, or
a format string.  And really, not even then.  Your proposal would bake in
too many specifics.

To me, this decision is a no-brainer.  Callers are responsible for *what*
g.es prints.  g.es is responsible only for *how* printing happens. This is
the essence of separation of concerns, my primary design criterion.

Edward

**Comment by tbnorth** [comment]
No big deal.  I just think recording timestamps is a logging system's concern - Python's logging module and most others I can think off accept messages and report them with the time they were received, they don't expect every caller to include a timestamp.

**Comment by edreamleo** [comment]
On Tue, Jul 18, 2017 at 8:08 AM, Terry Brown <notifications@github.com>
wrote:

> No big deal. I just think recording timestamps is a logging system's
> concern - Python's logging module and most others I can think off accept
> messages and report them with the time they were received, they don't
> expect every caller to include a timestamp.
>
​An interesting point of view.  In this case, however, I don't want to make
g.es part of a logging system.  It just writes to the log pane ;-)

Edward
