### ISSUE TITLE
Plugin menu 'About' generates errors

### ISSUE THREAD

**Issue by largo84** [leo-editor/leo-editor#536]
Environment:
Leo 5.5, build 20170721094758, Fri Jul 21 09:47:58 CDT 2017
Git repo info: branch = master, commit = a1043408d36f
Python 3.4.3, PyQt version 5.4.1
Windows 8 AMD64 (build 6.2.9200) 
isPython3: True

From the Plugins menu, select any Plugin>About and this happens:

exception executing command
Traceback (most recent call last):

  File "D:\Synced\github repos\leo\leo\core\leoCommands.py", line 5578, in doCommand
    val = command(event)
  File "D:\Synced\github repos\leo\leo\plugins\plugins_menu.py", line 279, in about
    c.putHelpFor(msg, short_title=self.name)
  File "D:\Synced\github repos\leo\leo\core\leoCommands.py", line 7035, in putHelpFor
    g.app.gui.put_help(c, s, short_title)
  File "D:\Synced\github repos\leo\leo\plugins\qt_gui.py", line 1047, in put_help
    vr.show_scrolled_message(tag='Apropos', kw=kw)
  File "D:\Synced\github repos\leo\leo\plugins\viewrendered.py", line 322, in show_scrolled_message
    vr = viewrendered(event=kw)
  File "D:\Synced\github repos\leo\leo\plugins\viewrendered.py", line 372, in viewrendered
    vr.store_layout('closed')
  File "D:\Synced\github repos\leo\leo\plugins\viewrendered.py", line 1356, in store_layout
    (loc, loo) = layouts.get(c.hash(), deflo)
TypeError: 'NoneType' object is not iterable

**Comment by tbnorth** [comment]
I think this is another facet of the same bug Lewis just reported, as a
non-cache client of c.db/g.db bookmarks.py has been derailed by the new
SQLite backend, but again, odd I hadn't seen it in my testing, makes me
wonder if it's a Python 3 thing.

Vitalije, hoping you're able to take a look at this, although I'm just
about to pull latest Leo and effectively re-test here.

Cheers -Terry

**Comment by vitalije** [comment]
I think I know what the problem is. It is related also with new switch to sqlite3 cache. I'll look immediately into it.

**Comment by technatica** [comment]
1. Opening "About" on any plugin causes the reported traceback.

2. Current "master" lost my window position settings on load.

3. Attempting to use the "Window/Layout/Load Pane Layout" caused:


exception executing command
Traceback (most recent call last):

  File "/home/chris/leo-editor/leo/core/leoCommands.py", line 5578, in doCommand
    val = command(event)

  File "/home/chris/leo-editor/leo/plugins/free_layout.py", line 428,
in free_layout_load
    for k in d:

TypeError: 'NoneType' object is not iterable




Leo 5.5, build 20170721094758, Fri Jul 21 09:47:58 CDT 2017
Git repo info: branch = master, commit = a1043408d36f
Python 3.5.2, PyQt version 5.6.0
linux
isPython3: True
caching enabled


Using the latest Linux Mint, KDE, Anaconda.


Chris

**Comment by vitalije** [comment]
It was my mistake in `SqlitePickleShare.__get_item__` method. It didn't raise KeyError for non existent keys, which lead to errors in applying default value. Sorry for the inconvenience it may caused.
 
> Current "master" lost my window position settings on load.

@technatica, we have switched to new implementation of cache and it starts with the empty cache. So your window position and layouts that were kept in old cache, will be empty. Hopefully, once you adjust them again, they will be persisted.

**Comment by technatica** [comment]
Thanks. It all works as it should now.

Chris

**Comment by vitalije** [comment]
Glad to here that :-)
