### ISSUE TITLE
Non-ascii characters in leo.core.commit_timestamp.json crashes Leo

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#537]
The following in commit_timestamp.json crashes Leo during startup:

`"asctime": "Ð¿Ð¾Ð½, 31. Ñ˜ÑƒÐ» 2017.  19:20:22 CEST",`

Occurs at rev 754cf6 with either Python 2 or 3. Here is the console:

```
reading settings in C:\leo.repo\leo-editor\leo\config\leoSettings.leo
reading settings in C:\Users\edreamleo\.leo\myLeoSettings.leo

Traceback (most recent call last):
  File "launchLeo.py", line 8, in <module>
    leo.core.runLeo.run()
  File "c:\leo.repo\leo-editor\leo\core\runLeo.py", line 63, in run
    g.app.loadManager.load(fileName, pymacs)
  File "c:\leo.repo\leo-editor\leo\core\leoApp.py", line 2087, in load
    lm.doPrePluginsInit(fileName, pymacs)
  File "c:\leo.repo\leo-editor\leo\core\leoApp.py", line 2153, in doPrePluginsInit
    g.app.computeSignon() # Set app.signon/signon2 for commanders.
  File "c:\leo.repo\leo-editor\leo\core\leoApp.py", line 1012, in computeSignon
    print(app.signon)
  File "c:\Anaconda3\lib\encodings\cp437.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\xd0' in position 31: character maps to <undefined>
```

**Comment by vitalije** [comment]
I am responsible for cyrillic characters in commit_timestamp.json. I had just installed git hooks and apparently it used `date` program to get `asctime` value, but it returned localized value. I have changed hook script since and it should not happen again. 

I didn't realize it would cause crashes, otherwise I would have changed it by hand immediately.

**Comment by edreamleo** [comment]
On Tue, Aug 1, 2017 at 6:36 AM, Виталије Милошевић <notifications@github.com
> wrote:

> I am responsible for cyrillic characters in commit_timestamp.json. I had
> just installed git hooks and apparently it used date program to get
> asctime value, but it returned localized value. I have changed hook
> script since and it should not happen again.
>
> I didn't realize it would cause crashes, otherwise I would have changed it
> by hand immediately.
>
​Leo ought to be able to handle ​non-ascii characters in the .json file.

Something subtle is happening in app.computeSignon(). The date var is
already unicode, but still print(app.signon) crashes.  I am surprised that
that can happen.  Calling g.toUnicode(date) has no chance of helping,
because date is already unicode.

Edward

**Comment by vitalije** [comment]
It seems, according to the given traceback that python tried to encode unicode value using cp437, which can't encode cyrillic characters. I believe that setting environment variable `PYTHONIOENCODING` to `'utf-8'` would solve the issue, or setting default encoding in site.py module.

**Comment by vitalije** [comment]
Here is something that can enforce utf-8 encoding on sys.stdout in Python3:
```python
if g.isPython3 and sys.stdout.encoding != 'UTF-8':
    import _io
    sys.stdout = _io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
```

**Comment by xgid** [comment]
FYI, I have been using exactly that revision recently without crashes:
```
Leo Log Window
Leo 5.5, build 20170731192022, Ð¿Ð¾Ð½, 31. Ñ˜ÑƒÐ» 2017.  19:20:22 CEST
Git repo info: branch = master, commit = 754cf6957439
Python 3.6.1, PyQt version 5.6.2
Windows 10 AMD64 (build 10.0.15063) SP0
isPython3: True
```

I have `PYTHONIOENCODING=UTF-8` in my Windows environment, so that may be the reason it is working for me, as suggested by Vitalije.

**Comment by vitalije** [comment]
Hm, this log suggests that app.signon is not properly converted to unicode.

**Comment by tbnorth** [comment]
On Tue, 01 Aug 2017 06:58:55 -0700
XGiD <notifications@github.com> wrote:

> FYI, I have been using exactly that revision recently without crashes:
> ```
> Leo Log Window
> Leo 5.5, build 20170731192022, Ð¿Ð¾Ð½, 31. Ñ˜ÑƒÐ» 2017.  19:20:22 CEST
> Git repo info: branch = master, commit = 754cf6957439
> Python 3.6.1, PyQt version 5.6.2
> Windows 10 AMD64 (build 10.0.15063) SP0
> isPython3: True
> ```
> 
> I have `PYTHONIOENCODING=UTF-8` in my Windows environment, so that
> may be the reason it is working for me, as suggested by Vitalije.

My Leo setup (not the one I have access to right now) also worked fine
with the Cyrillic date appearing correctly in the log.  I think it's
the cp437 encoding issue.  I don't think I have PYTHONIOENCODING set.

Cheers -Terry

**Comment by edreamleo** [comment]
On Tue, Aug 1, 2017 at 9:19 AM, Terry Brown <notifications@github.com>
wrote:

> On Tue, 01 Aug 2017 06:58:55 -0700
> XGiD <notifications@github.com> wrote:
>
>
> My Leo setup (not the one I have access to right now) also worked fine
> with the Cyrillic date appearing correctly in the log. I think it's
> the cp437 encoding issue. I don't think I have PYTHONIOENCODING set.
>

​On my Windows 10 system, setting PYTHONIOENCODING=UTF-8 does indeed
prevent the crash.  However, two problems remain.  First, the console shows
byte hash instead of a proper date.  Second, Leo's log says "not running
from any git repo."

Using io.TextIOWrapper for sys.stdout might work, but it might still show
byte hash.

This problem seems mysterious to me.  I have always assumed that once an
encoded string was converted to unicode that most (all?) representational
problems must have been solved.  Apparently not, though I don't see why.​


​Edward

**Comment by vitalije** [comment]
I vaguely remember that in Windows terminal (cmd.exe) there used to be a command for choosing codepage. If sys.stdout in python uses UTF-8 encoding then it is safe to print any unicode text to stdout. However, user won't be able to correctly see unicode text printed in console unless console is set to use utf8 codepage and also to use some unicode font. Both of those settings were by default something else when I used windows for programming (it used to be Windows XP). I don't know if this still applies with newer versions of Windows. 
Vitalije

**Comment by edreamleo** [comment]
>I vaguely remember that in Windows terminal (cmd.exe) there used to be a command for choosing codepage. 

[This discussion](https://stackoverflow.com/questions/14109024) seems pretty complete. This should be part of the documentation.

Still not sure what, if anything, should be done about this issue...

**Comment by vitalije** [comment]
Regarding crash issue, it is caused with bad default python io encoding. Leo can check `sys.stdout.encoding` value and issue a warning if it is not `'UTF-8'`, providing link to documentation page that explains how to set `PYTHONIOENCODING=UTF-8`, and also if on windows platform how to configure console.
Furthermore in `leo.bat` file it can be explicitly set before launching Leo.

If this warning was given before writing `signon` text, it would be clear to user what really caused crash.

**Comment by edreamleo** [comment]
On Wed, Aug 2, 2017 at 7:26 AM, Виталије Милошевић <notifications@github.com
> wrote:

> Regarding crash issue, it is caused with bad default python io encoding.
> Leo can check
> ​​
> sys.stdout.encoding value and issue a warning if it is not 'UTF-8',
> providing link to documentation page that explains how to set
> PYTHONIOENCODING=UTF-8, and also if on windows platform how to configure
> console.
>
> ​Good idea. ​ Rev 2d1bc79 adds a warning, referring to
https://stackoverflow.com/questions/14109024.

> Furthermore in leo.bat file it can be explicitly set before launching Leo.
>
​For me, the easy way is to ​set target of the console shortcut to:

    %windir%\system32\cmd.exe /K chcp 65001

This should close this issue.

Edward
