### ISSUE TITLE
Let's have a special temporary(non-peristent) node in outline

### ISSUE THREAD

**Issue by vitalije** [leo-editor/leo-editor#538]
It would be useful to have some special node (for example last top node with headline `@workbench`) which by convention would never be written in Leo document, but instead kept in cache. During save operation Leo would skip such node and its sub-tree. During open operation Leo would add such node as last top node (and possibly if it is found in cache restore last known sub-tree of this node).

In essence following is required to achieve this:
1. Change `FileCommands.write_Leo_file` to skip this special node and store it in cache.
2. Change `FileCommands.getLeoFile` to add this special node and possibly restore it from cache.
3. Document the convention about this special node (what it is, what is it good for, warning about its non-persistence).

Why I believe it would be useful to have this feature? Here are some examples:

* Right now we have LeoPyRef.leo which is not supposed to be used directly but copied in personal document. I would imagine every project where developers are collaborating need to have this convention. It is simple enough for a new developer to join the team and start using this convention. However, it can happen that some major updates to reference outline are not reflected in the personal copies. For example if some new file is added to reference outline. My personal copy won't have this node and it becomes out-dated. If I try to manually add such file to my outline I have a problem with
differences in top-level gnx or headline that will change the external file during save command. If we all edit one reference document it can never get out of sync. Our personal changes that are not meant to be shared in repository can be located under `@workbench` node.
* when opening Leo sometimes we get resurrected nodes, which make Leo file dirty even before user can touch its content. `@workbench` node would be perfect place to put resurrected nodes and outline won't get dirty. 
* when using new git-diff command or some other commands that need to show user temporary tree, again, `@workbench` node would be perfect place to put such tree.

This can be implemented as a plugin. Before `save` Leo will temporarily delete `@workbench` node and store it in the cache, after `save` and `open` Leo will bring it back from the cache. However, if implemented in a plugin it can happen that for whatever reason plugin fail and content of this node gets out and maybe even get pushed in public repository. Also it can create conflict if user with this plugin enabled tries to open Leo document of another user which did not enable this plugin and so have a `@workbench` node inside Leo document. Implementing this in the core is much cleaner.

If needed, I would be glad to implement this feature, myself.

**Comment by edreamleo** [comment]
On Sun, Aug 6, 2017 at 8:09 AM, Виталије Милошевић <notifications@github.com
> wrote:

> It would be useful to have some special node (for example last top node
> with headline @workbench) which by convention would never be written in
> Leo document, but instead kept in cache.
>
​Please don't do this. There may be problems with using LeoPyRef.leo, but
this is not the way to solve those problems.

We *must not* add special cases in the outline, in Leo's read/write code,
and in Leo's caches.

I have spent considerable time thinking about this reply. In the end, I
have decided not to try to explain my reasoning further.  Instead, the
newly created #539 <https://github.com/leo-editor/leo-editor/issues/539>
discusses problems with another special case that is causing big problems
just now.

I'll leave this issue open while we discuss it further.

Edward

**Comment by edreamleo** [comment]
I am going to close this issue. #540 proposes an explicit solution to the problems discussed here, without affecting Leo's core in any way.
