### ISSUE TITLE
Leo's redraw code should be redesigned

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#539]
**The problem**

c.selectPosition (and possibly other "small", often-used methods) may redraw the outline pane as a side effect. This can cause a cascade of unintended redraws, resulting in highly annoying screen flash.  This is a design blunder. `git blame` indicates I am solely responsible for this mess. As a workaround, the present code passes various "redraw" flags to various methods.  These flags are highly problematic.

**The solution**

1. Redrawing the screen happens *only* as the result of an explicit call to c.redraw.  In particular, neither c.selectPosition nor its helpers redraw the screen.

2. c.redraw_later() sets a flag requesting that c.outerUpdate call c.redraw if necessary.  Any call to c.redraw resets this flag. cc.selectChapterForPosition calls c.redraw_later.

3. c.disable_redraw() sets a flag disabling all outline redraws. c.enable_redraw() re-enables redrawing. This is similar to the old begin_update/end_update scheme, but simpler and more explicit. Use this as follows:
```python
try:
    c.disable_redraw()
    # Code that might otherwise redraw the tree.
finally:
    c.enable_redraw()
```

4. c.outerUpdate has been drastically simplified.  It no longer handles requests for redraws, recoloring, bring-to-front or de-iconification. It now handles requests for delayed focus changes and delayed redraws. It also handles "childrenModified" and "contentModified" hooks.

**Comment by edreamleo** [comment]
The new code is in the redraw branch, and everything is going much more smoothly than expected.

For example, it's easy to remove unused keyword args using the following pattern:
```python
# Was def recolor_now(self, p=None, incremental=False, interruptable=False):
def recolor_now(self, **kwargs):
    # Support QScintillaColorizer.colorize.
    c = self
    p = kwargs.get('p')
    for name in ('incremental', 'interruptable'):
        if name in kwargs:
            print('c.recolor_now: "%s" keyword arg is deprecated' % name)

**Comment by vitalije** [comment]
I don't have a knowledge about this part of code at all, but without looking at code, I would expect to find recoloring trigger as a consequence of  change in body content. Change in position (`c.selectPosition`) causes usually change in body content and recoloring is triggered. I would be surprised if for example recoloring is triggered when moving selection from one clone to another, because they have same body content and should be syntax colored in the same way.

**Comment by edreamleo** [comment]
On Tue, Aug 8, 2017 at 2:31 AM, Виталије Милошевић <notifications@github.com
> wrote:

> I don't have a knowledge about this part of code at all, but without
> looking at code, I would expect to find recoloring trigger as a consequence
> of change in body content. Change in position (c.selectPosition) causes
> usually change in body content and recoloring is triggered. I would be
> surprised if for example recoloring is triggered when moving selection from
> one clone to another, because they have same body content and should be
> syntax colored in the same way.
>
​Usually, but not always.  The clones could be under the effect of
different @language directives.

Anyway, the redraw branch actually only deals with redrawing the outline.

Your timing was perfect.  I was just going to announce that the redraw
branch is ready for testing.

Edward

**Comment by edreamleo** [comment]
The redraw branch has been merged into master without incident, so I am going to close this issue.
