### ISSUE TITLE
Create an update-this-leo-file command

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#540]
The **update-this-leo-file** command will add all`@<file>` nodes from a **master .leo file** (LeoPyRef.leo) to the **subsidiary .leo file** (leoPy.leo) that do not already exist in the subsidiary file.  This command could also copy other data from the master to the subsidiary file, say all @public-data trees.

All copied nodes would appear as direct children of an **updated nodes** node, created as the last top-level node. Devs could then move the child nodes anywhere they like.

This command solves the problems discussed in [#538](https://github.com/leo-editor/leo-editor/issues/538) explicitly, without affecting Leo's core or cache in any way, and without mandating any particular organization of .leo files.  All difficulties will confined to the command itself.

Subsidiary files indicate their master file with the setting: `@string <master-file>`.  For example, leoPy.leo would contain `@string LeoPyRef.leo`, assuming the two files are in the same directory, or a longer path if not.

**Comment by edreamleo** [comment]
@vitalije Please free to design the command as you like, including the command's name and what it does.  Perhaps two commands would be good: one to update the subsidiary file, and one to update the master file. I'll leave everything to your discretion.

While Leo's core should be free of special cases, that restriction does not apply to commands. Leo's core should not mandate any particular organization of outlines, but commands routinely use special outline nodes.

**Comment by vitalije** [comment]
> Please free to design the command as you like,

@edreamleo I have felt free to design it as I like. This is something like I have earlier suggested with the special type of node that separates public (referenced) and private part of outline. I have taken care not to change anything in core commands and the way they work. There are three new commands:

1. `set-reference-file` which allows user to select reference Leo file that this outline will be connected to. In essence it adds special node if it doesn't exists or changes its reference filename if it already existed.
2. `read-ref-file` which reads public part of this outline from reference Leo file
3. `update-ref-file` which writes public part of this outline to reference Leo file

**Comment by vitalije** [comment]
@edreamleo if you agree with this solution, I will write about these commands in forum to let other users know about new commands.

**Comment by edreamleo** [comment]
On Thu, Aug 31, 2017 at 9:11 AM, Виталије Милошевић <
notifications@github.com> wrote:

> @edreamleo <https://github.com/edreamleo> if you agree with this
> solution, I will write about these commands in forum to let other users
> know about new commands.
>

​Sounds reasonable.  Please do publicize your work in leo-editor.  That way
more people will see the discussion.

Edward

**Comment by vitalije** [comment]
ok
