### ISSUE TITLE
Display of plugin documentation is broken

### ISSUE THREAD

**Issue by SegundoBob** [leo-editor/leo-editor#543]
Instead of displaying the plugin documentation via the "view rendered" plugin, the documentation is printed as plain text to the log pane after the error message:

loadOnePlugin: can not load enabled plugin: leo.plugins.viewrendered

## For example:

> loadOnePlugin: can not load enabled plugin: leo.plugins.viewrendered
> richtext.py - Rich text editing
> ===============================
> 
> This plugin allows you to use CKEditor__ to edit rich text
> in Leo.  Text is stored as HTML in Leo nodes.
> 
> __ http://ckeditor.com/
> 
> ``richtext.py`` provides these ``Alt-X`` commands (also available from
> Plugins -> richtext menu):
> 
>   cke-text-close
>     Close the rich text editor, unhide the regular editor.
>   cke-text-open
>     Open the rich text editor, hide the regular editor.
>   cke-text-switch
>     Switch between regular and rich text editor.
>   cke-text-toggle-autosave
>     Toggle autosaving of changes when you leave a node.
>     Be careful not to convert plain text (e.g. source code) to rich
>     text unintentionally.  As long as you make no edits, the original
>     text will not be changed.
> 
> Unless autosaving is enabled, you must confirm saving of edits
> each time you edit a node with the rich text editor.
> 
> ``@rich`` in the headline or first few lines (1000 characters) of a node or its
> ancestors will automatically open the rich text editor. ``@norich`` cancels this
> action.  Manually opened editors are not affected.
> 
> ``richtext.py`` uses these ``@settings``:
> 
>   @bool richtext_cke_autosave = False
>     Set this to True for rich text edits to be saved automatically.
> 
>     *BE CAREFUL* - plain-text nodes will be converted to rich text
>     without confirmation if you edit them in rich text mode when
>     this is True.
> 
>   @data richtext_cke_config Configuration info. for CKEditor, see
>     http://docs.ckeditor.com/#!/guide/dev_configuration the content of this node
>     is the javascript object passed to ``CKEDITOR.replace()`` as it's second
>     argument. The version supplied in LeoSettings.leo sets up a sensible
>     toolbar. To enable *all* CKEditor toolbar features copy this setting to
>     myLeoSettings.leo and remove the default content, i.e. make this node blank,
>     then CKEditor will generate a toolbar with all available features.
> 
> To make a button to toggle the editor on and off, use::
> 
>     @button rich
>       c.k.simulateCommand('cke-text-switch')
> 

## Test Systems:

> Leo 5.5, build 20170721094758, Fri Jul 21 09:47:58 CDT 2017
> Git repo info: branch = master, commit = 821c750de356
> Python 3.5.2, PyQt version 5.5.1
> linux
> isPython3: True
> caching enabled
> 

and 

> Leo 5.5, build 20170816073453, Wed Aug 16 07:34:53 UTC 2017
> Git repo info: branch = master, commit = 546047bfd20e
> Python 3.5.2, PyQt version 5.5.1
> linux
> isPython3: True
> caching enabled
>

**Comment by edreamleo** [comment]
On Wed, Aug 16, 2017 at 11:50 AM, SegundoBob <notifications@github.com>
wrote:

> Instead of displaying the plugin documentation via the "view rendered"
> plugin, the documentation is printed as plain text to the log pane after
> the error message:
>
​I am having a hard time following all this.

I do know the following.  The is no problem printing plugin documentation
on Windows, with either Python 2 or 3.  On Linux, I get the following
traceback (Python 2 only):

Traceback (most recent call last):

  File "/home/edward/leo.repo/leo-editor/leo/core/leoCommands.py", line
5577, in doCommand
    val = command(event)

  File "/home/edward/leo.repo/leo-editor/leo/plugins/plugins_menu.py", line
279, in about
    c.putHelpFor(msg, short_title=self.name)

  File "/home/edward/leo.repo/leo-editor/leo/core/leoCommands.py", line
7036, in putHelpFor
    g.app.gui.put_help(c, s, short_title)

  File "/home/edward/leo.repo/leo-editor/leo/plugins/qt_gui.py", line 1046,
in put_help
    vr.show_scrolled_message(tag='Apropos', kw=kw)

  File "/home/edward/leo.repo/leo-editor/leo/plugins/viewrendered.py", line
322, in show_scrolled_message
    vr = viewrendered(event=kw)

  File "/home/edward/leo.repo/leo-editor/leo/plugins/viewrendered.py", line
365, in viewrendered
    layouts[h] = c.cacher.db.get('viewrendered_default_layouts', (None,
None))

  File "/home/edward/leo.repo/leo-editor/leo/core/leoCache.py", line 933,
in get
    val = self[key]

  File "/home/edward/leo.repo/leo-editor/leo/core/leoCache.py", line 844,
in __getitem__
    obj = self.loader(row[0])

  File "/home/edward/leo.repo/leo-editor/leo/core/leoCache.py", line 804,
in loadz
    val = pickle.loads(zlib.decompress(data))

TypeError: ('must be string, not unicode', <built-in function
_unpickle_enum>, (u'PyQt5.QtCore', u'Orientation', 1))

This is likely a recent problem.  I'll attempt a fix next.

Edward​

**Comment by edreamleo** [comment]
Rev 6f2fb6f is a partial fix.  The problem seems to be a mismatch between Python 2/3 pickle formats.

Even with this partial fix, you must clear all caches in order not to take an additional crash in the caching logic.  Vitalije is responsible for these recent changes, so I have assigned a complete fix to him.

**Comment by SegundoBob** [comment]
Edward K. Ream wrote:

> I do know the following. The is no problem printing plugin documentation on Windows, with either Python 2 or 3. On Linux, I get the following traceback (Python 2 only):

Thanks, this was a good clue for me.  That is, you were not seeing the same problem that I was seeing, so there was something wrong with my installation.  I immediately suspected that I had failed to install a package that viewrendered.py needs.  Determining the crucial package was moderately difficult and time consuming. 

### Why can't plugins print error messages indicating the missing packages?

I don't know which modules are required.  I only know the last module that I installed before the problem went away.

I installed packages in the following order:

1. docutils (i.e., python-docutils and python3-docutils)
2. markdown (i.e., python-markdown and python3-markdown)
3. QtSvg (i.e., python-pyqt5.qtsvg and python3-pyqt5.qtsvg)

I believe the Leo-Editor documentation on the Internet only mentions docutils as a requirement of viewrendered.

Before I installed QtSvg I observed that the viewrendered.py init() function was called twice and both times it returned False because its QtSvg variable was None.  After the second call to the viewrendered init(), this error message was displayed:

> loadOnePlugin: can not load enabled plugin: leo.plugins.viewrendered

Then the viewrendered onCreate() function was called and seemed to do everything it would if viewrendered was loaded successfully.

As a plugin writer I would expect that if the init() function fails, then onCreate() would **NOT** be called. Is the call to onCreate() a bug?

**Comment by edreamleo** [comment]
On Thu, Aug 17, 2017 at 4:41 PM, SegundoBob <notifications@github.com>
wrote:

I immediately suspected that I had failed to install a package that
> viewrendered.py needs. Determining the crucial package was moderately
> difficult and time consuming. Why can't plugins print error messages
> indicating the missing packages?

​They can, but that might be annoying in some cases.

> As a plugin writer I would expect that if the init() function fails, then
> onCreate() would *NOT* be called. Is the call to onCreate() a bug?
>
​This is a bug in init, fixed at 5379528.
  Nothing should happen if ok is False.

However, the vr plugin is, at present, afflicted with caching problems when
mixing Python 2 and 3.  For example, running ekr.leo with Python 2 after
opening with Python 3, and then attempting to show any plugin's
documentation throws this:


Traceback (most recent call last):

  File "c:\leo.repo\leo-editor\leo\core\leoCommands.py", line 5577, in
doCommand
    val = command(event)

  File "c:\leo.repo\leo-editor\leo\plugins\plugins_menu.py", line 279, in
about
    c.putHelpFor(msg, short_title=self.name)

  File "c:\leo.repo\leo-editor\leo\core\leoCommands.py", line 7036, in
putHelpFor
    g.app.gui.put_help(c, s, short_title)

  File "c:\leo.repo\leo-editor\leo\plugins\qt_gui.py", line 1046, in
put_help
    vr.show_scrolled_message(tag='Apropos', kw=kw)

  File "c:\leo.repo\leo-editor\leo\plugins\viewrendered.py", line 325, in
show_scrolled_message
    vr = viewrendered(event=kw)

  File "c:\leo.repo\leo-editor\leo\plugins\viewrendered.py", line 375, in
viewrendered
    vr.store_layout('closed')

  File "c:\leo.repo\leo-editor\leo\plugins\viewrendered.py", line 1359, in
store_layout
    (loc, loo) = layouts.get(c.hash(), deflo)

TypeError: 'NoneType' object is not iterable


This might be tricky to fix, and I did not write the code that is crashing.


Edward

**Comment by edreamleo** [comment]
On Fri, Aug 18, 2017 at 3:43 AM, Edward K. Ream <edreamleo@gmail.com> wrote:


> However, the vr plugin is, at present, afflicted with caching problems
> when mixing Python 2 and 3.  For example, running ekr.leo with Python 2
> after opening with Python 3, and then attempting to show any plugin's
> documentation throws this:
> ​ [snip]
>

​Vitalije fixed this at c94ebe.  It looks like you must also clear all the
caches in .leo/db to make this fix effective.

Edward

**Comment by edreamleo** [comment]
I am going to close this.  Please reopen if there are more problems.
