### ISSUE TITLE
C imports broken

### ISSUE THREAD

**Issue by curtiscarlsen** [leo-editor/leo-editor#545]
in older versions of leo, c source code was imported mostly correctly, with a few problems that requred some editting.  In the last few releases, large numbers of functions are not recognized, and node labels leave off function and variable names.  Below is an example of an imported c file.  You can see from the sentinels that most of the functions in the file were not recognized or placed into nodes.  Also, the node labels contain the attribute and type info, but not the name of the variable or function.

//@+leo-ver=5-thin
//@+node:curtis.20170824155527.14: * @file C:/Sandbox/XL624/trunk/source/utilities/source/ui/menu/scr_node.c
/**  file: scr_node.c
 * base class to define the minimum set of functions to be supported by menu_tree nodes
**/

#include "stdbool.h"
#include "scr_node.h"
#include "menu_tree.h"
#include "string.h"

scr_exec_status_t scr_node_execute(scr_node_t const *self,
                                   menu_tree_t const *tree,
                                   scr_exec_code_t exec_code,
                                   uint16_t * returnVal);
uint16_t scr_node_getAttributes(scr_node_t const *self,
                                struct menu_tree_s const *tree);
   ...

//@+others
//@+node:curtis.20170824155527.15: ** const scr_node_api_t
const scr_node_api_t scr_node_api = {
  .execute = scr_node_execute,
  .getNodeId = scr_node_getNodeId,
  .getAttributes = scr_node_getAttributes,
  .getHeadline = scr_node_getHeadline,
  .isEnabled = scr_node_isEnabled,
//  .enter = scr_node_enter,
  .update = scr_node_update,
  .exit = scr_node_exit
};

scr_exec_status_t scr_node_execute(scr_node_t const *self,
                                   menu_tree_t const *tree,
                                   scr_exec_code_t exec_code,
                                   uint16_t * returnVal)
{
  return (scr_exec_status_idle);
}

uint16_t scr_node_getAttributes(scr_node_t const *self,
                                struct menu_tree_s const *tree)
{
  return (self->attributes);
}

uint8_t scr_node_getNodeId(scr_node_t const *self, menu_tree_t const *tree)
{
  return (self - tree->nodes);
}

_Bool scr_node_getHeadline(scr_node_t const *self, uint8_t * buff,
                           uint8_t buffSize)
{
  strncpy((char *) buff, (char *) self->headline, buffSize);
  return (buffSize < strlen((char *) self->headline));
}

_Bool scr_node_isEnabled(scr_node_t const *self)
{
  return (1);
}

_Bool scr_node_isEnabled_false(scr_node_t const *self)
{
  return (0);
}

scr_enter_status_t scr_node_enter(scr_node_t const *self,
                                  struct menu_tree_s const *tree)
{
  return (scr_enter_allowEntry);
}

//remove this and use execute instead?
scr_update_status_t scr_node_update(scr_node_t const *self)
{
  return (scr_update_error);
}

scr_exit_status_t scr_node_exit(scr_node_t const *self,
                                struct menu_tree_s const *tree)
{
  return (scr_exit_status_allowExit);
}
//@-others
//@@language c
//@@tabwidth -2
//@-leo

**Comment by curtiscarlsen** [comment]
the leo version was 5.5 final, and the import was made using the file|import menu

**Comment by edreamleo** [comment]
On Thu, Aug 24, 2017 at 6:02 PM, curtiscarlsen <notifications@github.com>
wrote:

> in older versions of leo, c source code was imported mostly correctly,
> with a few problems that required some editing. In the last few releases,
> large numbers of functions are not recognized, and node labels leave off
> function and variable names.
>

​Thanks for this report.  I'll fix this before the next official release.

Edward

**Comment by edreamleo** [comment]
On Fri, Aug 25, 2017 at 5:58 AM, Edward K. Ream <edreamleo@gmail.com> wrote:

>
>
> On Thu, Aug 24, 2017 at 6:02 PM, curtiscarlsen <notifications@github.com>
> wrote:
>
>> in older versions of leo, c source code was imported mostly correctly,
>> with a few problems that required some editing. In the last few releases,
>> large numbers of functions are not recognized, and node labels leave off
>> function and variable names.
>>
>
​Fixed at 65b9bb6 by adding support for ​@data c_import_typedefs.

The body text of this node should be a list of typedefs used in the
imported file.  The example in leoSettings.leo shows the following
(commented out):

_Bool
scr_enter_status_t
scr_exec_status_t
scr_exit_status_t
scr_node_api_t
scr_update_status_t
uint16_t
uint8_t

With these definitions, your example outline now imports as expected.

Edward

**Comment by edreamleo** [comment]
One could consider adding support `@string c_import_typedef_regex` as well.  In your case, a value of `*_t` might work.  But `@data c_import_typedefs` is probably good enough. I'm going to close this issue.
