### ISSUE TITLE
Leo fails to start with command-line option --minimized 

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#547]
Leo fails to start with launchleo.py --minimized
I have to do Ctrl-C to stop, and python stops working.

Here is log from console:
N:\git\leo-editor>launchleo.py --minimized

reading settings in N:\git\leo-editor\leo\config\leoSettings.leo
reading settings in C:\Users\lewisneal\.leo\myLeoSettings.leo
Empty setting name in False
set parent @settings

Leo 5.5, build 20170824093736, Thu Aug 24 09:37:36 CDT 2017
Git repo info: branch = master, commit = 32c81ac6b37d
Python 3.6.2, PyQt version 5.9.1
Windows 10 AMD64 (build 10.0.15063) SP0
** isPython3: True
** caching enabled

reading settings in C:\Users\lewisneal\.leo\workbook.leo
trace_idle_focus 1 no focus
trace_idle_focus 2 no focus
trace_idle_focus 3 no focus
[snip]
trace_idle_focus 29 no focus
trace_idle_focus 30 no focus
trace_idle_focus 31 no focus
Traceback (most recent call last):
  File "N:\git\leo-editor\leo\plugins\qt_idle_time.py", line 91, in at_idle_time
    def at_idle_time(self):
KeyboardInterrupt

**Comment by edreamleo** [comment]
Rev 34a560a disables the trace, which is the only real problem.  Indeed, Leo is running minimized, and un-minimizing it works.

**Comment by LewisNeal** [comment]
Thanks, option works fine now.
