### ISSUE TITLE
[From Launchpad] Cut / Paste / Insert Hotkey

### ISSUE THREAD

**Issue by Armagedoom** [leo-editor/leo-editor#55]
Launchpad link:
https://bugs.launchpad.net/leo-editor/+bug/1215603

Thread:
Sumarizing the post https://groups.google.com/forum/#!topic/leo-editor/3RQsBxkYqUw

We could switch cut/paste/insert to the standard hotkeys used by every other software.

For this to be possible, cut/paste commands should first pick up if:
-There is currently a selected text (either in currently selected header, body, or pane whatsoever)
-There is a node/outline on the clipboard (is there a way to check that?)

Then, for the cut command:
- If there is text selected, does cut text
- If there is not selected text, does cut node

Then, for the paste command:
- If text on clipboard is a node, do paste node
- If text on clipboard is text, do paste text

For the cases that the user wants to paste the node in the clipboard as text (which I think might be fewer but maybe thats only my case) then the user can do control+shift+paste.

**Comment by edreamleo** [comment]
> the current request would be to have two separate clipboards, one for nodes, one for raw text.

This would be the effect, anyway.

**Comment by edreamleo** [comment]
Sometimes we might want to copy a node (as text) and then paste into the body pane.  This proposal would prevent that.
