### ISSUE TITLE
Refresh from disc not working for @shadow nodes

### ISSUE THREAD

**Issue by thomper** [leo-editor/leo-editor#550]
The check for node type has an extraneous space after `@shadow` which causes the following if statement to always execute the else clause for `@shadow` nodes: https://github.com/leo-editor/leo-editor/blob/449d67587c832b3218019131690be3151ba279aa/leo/core/leoCommands.py#L2339

Changing the line to:

`elif word == '@shadow':`

makes it work again.

**Comment by tbnorth** [comment]
Thanks for the fix!

**Comment by edreamleo** [comment]
On Wed, Sep 20, 2017 at 8:29 PM, Thomas <notifications@github.com> wrote:

> The check for node type has an extraneous space after @shadow
> <https://github.com/shadow> which causes the following if statement to
> always execute the else clause for @shadow <https://github.com/shadow>
> nodes: https://github.com/leo-editor/leo-editor/blob/
> 449d67587c832b3218019131690be3151ba279aa/leo/core/leoCommands.py#L2339
>
> Changing the line to:
>
> elif word == '@shadow <https://github.com/shadow>':
>
> makes it work again.
>

​Good catch, and thanks, Terry, for the actual fix.

Edward
