### ISSUE TITLE
How to make .leo files happy in git repository?

### ISSUE THREAD

**Issue by exaos** [leo-editor/leo-editor#551]
I put some .leo files into a git repo. I open a .leo file and change nothing but save it again, it will be marked as changed in the repo. `git diff` shows that many lines have changed. I checked the diffs, and typically these changes are about accessing time etc.
How to make .leo files happy in a git reposity? I mean, if nothing about the content changes, these files will keep clean to a git repo. Or could I use git only to trace the changes of outline nodes?

**Comment by edreamleo** [comment]
On Fri, Sep 22, 2017 at 2:18 AM, Exaos Lee <notifications@github.com> wrote:

> I put some .leo files into a git repo. I open a .leo file and change
> nothing but save it again, it will be marked as changed in the repo. git
> diff shows that many lines have changed. I checked the diffs, and
> typically these changes are about accessing time etc.
>
​There are several answers.

1. This FAQ entry
<http://leoeditor.com/FAQ.html#how-should-i-use-leo-with-git-etc>.​

2. This setting affects .leo files:

    @bool put_expansion_bits_in_leo_files = True

Setting this to False will suppress changes that depend only on expansion
state of nodes.

Edward
