### ISSUE TITLE
@clean is not compatible with org mode files

### ISSUE THREAD

**Issue by exaos** [leo-editor/leo-editor#552]
**Update by EKR**:  In my tests both `@auto` and `@clean` *do* work properly with .org mode files, and probably with .rst files too.  But it's tricky to change `@auto myFile.org` to `@clean myFile.org`, for several reasons:

1. The root of `@clean myFile.org` must contain an `@others` directive.
2. Changing `@auto myFile.org` to `@clean myFile.org` *removes* the org-mode sentinels from the file.

I tried to view my personal information files in org-mode within Leo-Editor, but the org files are not parsed properly. 

My org files are Chinese contents with UTF-8 encoding.
For example, the following lines should be parsed as 3-levels headlines:
```
* Events
  :PROPERTIES:
  :CATEGORY: events
  :END:
** 整理个人生活
*** 每周惯例
```
But the headline "Events" will look like this in Leo:
```
:PROPERTIES:
  :CATEGORY: events
  :END:
** 整理个人生活
*** 每周惯例
```
It also seems the last headline is omitted.

----

I encounter the same issue with Markdown files: If I use `@clean` to load external files, the next node will appear in the previous node's content. If I use `@auto`, thing looks well.

**Comment by exaos** [comment]
I tried to change ` org_pattern = re.compile(r'^(\*+)(.*)$')` to ` org_pattern = re.compile(r'^(\*+)(\s+)(.*)$')`, the issue is still there.

**Comment by edreamleo** [comment]
On Fri, Oct 6, 2017 at 5:20 AM, Exaos Lee <notifications@github.com> wrote:

> I tried to change org_pattern = re.compile(r'^(\*+)(.*)$') to org_pattern
> = re.compile(r'^(\*+)(\s+)(.*)$'), the issue is still there.
>
​Thanks for this report.  I'll fix it soon.

Edward

**Comment by edreamleo** [comment]
I see the behavior described.  `@auto` works, `@clean` does not.

At present `@clean` is incompatible with org mode files. "Normal" `@clean` files contain *no* node delimiters/sentinels.  The `@clean` algorithm assigns lines of the external files to outline nodes based on diffs.  But org mode files *do* contain sentinels.

In short, handling org-mode files with `@clean` would require significant changes to the Mulder/Ream update algorithm.  I am going to change this to a "might do" enhancement.

**Comment by edreamleo** [comment]
It might be reasonable to support `@org-mode` files, treating org-mode "sentinels" like Leo sentinels.

However, org-mode sentinels do not carry gnx's, so whether this would really be useful remains to be seen.

**Comment by edreamleo** [comment]
I am going to close this item.  The org-mode importer works properly, but not after removing org-mode sentinels (* lines) after using `@clean`.
