### ISSUE TITLE
ipython leo window blank (Not Responding)

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#554]
Start Leo with
>launchleo.py --ipython
This launches a functional Jupyter QtConsole. However the workbook.leo window is blank with a (Not Responding) heading.
Have I missed some required step here?

Leo Log Window
Leo 5.6, build 20171003105033, Tue Oct  3 10:50:33 CDT 2017
Git repo info: branch = master, commit = acc50f94095c
Python 3.6.3, PyQt version 5.9.1
Windows 10 AMD64 (build 10.0.15063) SP0
isPython3: True
caching enabled

QtConsole details:
Jupyter QtConsole 4.3.1
Python 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)]
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

**Comment by LewisNeal** [comment]
Can anyone run _launchleo.py --ipython_ with Python 2.7, and confirm if the behaviour is different than if using Python 3.6.3 ?

**Comment by AG4GitHub** [comment]
Hi,

Do you mean you can run the pYthon bridge with PYthon 3.6? If so, maybe you
can help me with my issues, please refer to my posting.

Thanks

On 17 Oct 2017 5:18 PM, "LewisNeal" <notifications@github.com> wrote:

Can anyone run *launchleo.py --ipython* with Python 2.7, and confirm if the
behaviour is different than if using Python 3.6.3 ?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/leo-editor/leo-editor/issues/554#issuecomment-337170952>,
or mute the thread

**Comment by edreamleo** [comment]
The ipython/jupyter bridge works as expected for me only on Linux.  On Windows 10 (Anaconda distribution) I am not able to enter any data into the Jupyter Qt console, nor do I see any data in that window.  This is not the behavior reported by Lewis, but clearly something is seriously amiss.

**Comment by edreamleo** [comment]
On Tue, Oct 17, 2017 at 7:57 PM, Andreas Gehrmann <notifications@github.com>
wrote:

> Hi,
>
> Do you mean you can run the pYthon bridge with PYthon 3.6? If so, maybe you
> can help me with my issues, please refer to my posting.
>

​I see the behavior you report on both my Anaconda 2 and 3 distros on
Windows 10.  Everything works as expected on Linux.  I'll look into this
asap.

Edward

**Comment by brobr** [comment]
I found this thread as I could not get leo to function when starting with the ipython bridge. This was on python2.7. It turned out that in my case the dead window was related to matplotlib (intilialised with ipython) which did not start-up properly. In the terminal where I started leo, I had this error: 

> GUI event loop or pylab initialization failed

By running ipython by itself in a console I got better info with respect to the source of the error (namely a font-permission issue that made matplotlib stumble)

So, apart from checking the leo-log; one could check the output in the consule where leo is started from and check whether ipython can run by itself.

**Comment by edreamleo** [comment]
On Sat, Oct 28, 2017 at 9:50 AM, brobr <notifications@github.com> wrote:

> I found this thread as I could not get leo to function when starting with
> the ipython bridge. This was on python2.7. It turned out that in my case
> the dead window was related to matplotlib (intilialised with ipython) which
> did not start-up properly. In the terminal where I started leo, I had this
> error:
>
> GUI event loop or pylab initialization failed
>
> By running ipython by itself in a console I got better info with respect
> to the source of the error (namely a font-permission issue that made
> matplotlib stumble)
>
> So, apart from checking the leo-log; one could check the output in the
> consule where leo is started from and check whether ipython can run by
> itself.
>
​Thanks for this.  I'm backed up with work at present.  I'll get to this
asap.

Edward

**Comment by edreamleo** [comment]
@brobr The failure on my machine does not seem to be related to the message

"GUI event loop or pylab initialization failed"

Indeed, tracing reveals that this message would come from the InteractiveShellApp.init_gui_pylab method in C:\Anaconda2\Lib\site-packages\IPython\core\shellapp.py

For me all, goes well in this method, but the qtconsole is still not responsive.

BTW, g.trace works well in this file, but the output from g.pdb gets swallowed.

**Comment by edreamleo** [comment]
Imo, there is likely a bug in the Windows version of IPython/Jupyter code that Leo uses.

Perhaps Leo can sidestep this problem using a different/newer API.  I'll be asking for help from the IPython and/or Jupyter people.

**Comment by edreamleo** [comment]
I have just filed [ipython issue #10902](https://github.com/ipython/ipython/issues/10902). It contains the following stand-alone test program illustrating the problem:
```python
from ipykernel.connect import connect_qtconsole
from ipykernel.kernelapp import IPKernelApp
app = IPKernelApp.instance()
args = ['python', '--pylab=qt', '--log-level=20']
app.initialize(args)
connect_qtconsole()
app.start()
```
Further progress depends on a response from the IPython folks.

Edward

**Comment by xgid** [comment]
> I have just filed ipython issue #10902. It contains the following stand-alone test program illustrating the problem

FYI, I've tested your example code in my Anaconda 3.6 installation in Windows 10 and I have a Jupyter QtConsole open up and fully functional, showing this:
```python
Jupyter QtConsole 4.3.0
Python 3.6.2 |Anaconda custom (32-bit)| (default, Jul 20 2017, 13:00:41) [MSC v.1900 32 bit (Intel)]
Type 'copyright', 'credits' or 'license' for more information
IPython 6.1.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: a = 'Hello'

In [2]: print(a)
Hello
```

Do you want any other info from my environment?

**Comment by edreamleo** [comment]
On Thu, Nov 16, 2017 at 9:35 AM, XGiD <notifications@github.com> wrote:

> I have just filed ipython issue #10902. It contains the following
> stand-alone test program illustrating the problem
>
> FYI, I've tested your example code in my Anaconda 3.6 installation in
> Windows 10 and I have a Jupyter QtConsole open up and fully functional,
> showing this:
>
> Jupyter QtConsole 4.3.0
> Python 3.6.2 |Anaconda custom (32-bit)| (default, Jul 20 2017, 13:00:41) [MSC v.1900 32 bit (Intel)]
> Type 'copyright', 'credits' or 'license' for more information
> IPython 6.1.0 -- An enhanced Interactive Python. Type '?' for help.
>
> In [1]: a = 'Hello'
>
> In [2]: print(a)
> Hello
>
> Do you want any other info from my environment?
>
​Thanks for this.  Exactly how did you create this working console?

Edward

**Comment by xgid** [comment]
By using your ipython_test.py example from the command-line:

```cmd
D:\proj\code\leo\scripts>python.exe ipython_test.py
[IPKernelApp] Starting the kernel at pid: 4588
[IPKernelApp] To connect another client to this kernel, use:
[IPKernelApp]     --existing kernel-4588.json
NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049


To connect another client to this kernel, use:
    --existing kernel-4588.json
[IPKernelApp] WARNING | Eventloop or matplotlib integration failed. Is matplotlib installed?
[IPKernelApp] Loading IPython extension: storemagic
```

**Comment by edreamleo** [comment]
On Thu, Nov 16, 2017 at 9:53 AM, XGiD <notifications@github.com> wrote:

> xgid: ipython_test.py works with Anaconda 3.6 on Windows 10

​Ok.  I have just closed [ipython issue #10902](https://github.com/ipython/ipython/issues/10902) and will this issue, [Leo issue #554](https://github.com/leo-editor/leo-editor/issues/554).

Many thanks for your help.​

To summarize, you must install Anaconda 3.6 to fix this issue on Windows 10.

**Comment by edreamleo** [comment]
The following worked to upgrade Anaconda for me, and now the qtconsole works for 2 and 3.
conda2 update --all # python 2
conda update --all # python
See: https://stackoverflow.com/questions/45197777/how-do-i-update-anaconda

**Comment by edreamleo** [comment]
> The following worked to upgrade Anaconda for me, and now the qtconsole works for 2 and 3.
**Update**: for reasons I don't understand, pylint is not updated automatically.  Importing it fails in astroid.

The following makes updates pylint as well as astroid:
```
    conda2 install astroid
    conda install astroid
```
It would probably also work to install/upgrade pylint instead, but I haven't tested that.
