### ISSUE TITLE
@path exception

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#555]
Originally reported [here](https://groups.google.com/d/msg/leo-editor/BuoSFuKAwAQ/_0cgayjOBAAJ).

```Leo Log Window
Leo 5.6, build 20170927102346, Wed, Sep 27, 2017 10:23:46 AM
Git repo info: branch = master, commit = fb9f38601881
Python 3.5.2, PyQt version 5.9.1
linux
isPython3: True
caching enabled
```
- create node @path /to/the/dir
- double click the icon:  files and dirs appear
- right click node @path /to/the/dir
- choosing path=>active-path-set-path-to-absolute-path-recursive crashes:

```
Traceback (most recent call last):
  File "/opt/fetching/leo-editor/leo/plugins/active_path.py", line 186, in active_path_wrapper
    command(event)
  File "/opt/fetching/leo-editor/leo/plugins/active_path.py", line 712, in cmd_SetNodeToAbsolutePathRecursive
    cmd_SetNodeToAbsolutePath(c, p=s)
  File "/opt/fetching/leo-editor/leo/plugins/active_path.py", line 717, in cmd_SetNodeToAbsolutePath
    c = event.get('c')
AttributeError: 'Commands' object has no attribute 'get'
```

**Comment by ktenney** [comment]
The problem is caused by running against nodes whos
files have not been loaded ...

**Comment by edreamleo** [comment]
The fix was to pass "event", not "c" as the first arg to cmd_SetNodeToAbsolutePath.  Neither pyflakes nor pylint catches this error.  Given Leo's argument naming conventions, you would think it would have been possible to catch this...
