### ISSUE TITLE
Redirecting python output of print() from a python script to Leo

### ISSUE THREAD

**Issue by AG4GitHub** [leo-editor/leo-editor#557]
Hi, I am new to Leo and try to get around, but I still struggling with things I guess are basic, please be patient with me. 
I am not sure if this is the right place for such questions, if not, please let me know where I should place such question.

I run a python script in the python shell (cmds/debugging/open python shell)
And generate an output from Print() command. 
How can I redirect the output to a new or existing node / header?

Additional explanation: actually I read an word file with python docx and like to generate nodes based on the content of the word file.

Thanks for your attention, Andreas

**Comment by edreamleo** [comment]
On Mon, Oct 23, 2017 at 7:37 AM, Andreas Gehrmann <notifications@github.com>
wrote:

> I run a python script in the python shell (cmds/debugging/open python
> shell)And generate an output from Print() command.
> How can I redirect the output to a new or existing node / header?
>
​You can run shell commands from within Leo using Python's popen module.
This should work well for programs that complete quickly.  For longer
programs, you can use Leo's BackgroundProcessManager class.  See
leoBackground.py for details, especially the class's docstring.

As another alternative, you can use Leo's IPython bridge
<http://leoeditor.com/IPythonBridge.html> to transfer results to Leo.

Either way, given a result string s, you can set p.b = s, where p is a node
that is to contain the results.

Edward
