### ISSUE TITLE
Making Leo a client of Jupyter, by communicating with its kernel

### ISSUE THREAD

**Issue by offray** [leo-editor/leo-editor#561]
Leo has an advanced DOM with capabilities beyond the current Jupyter HTML interface and [notebook format][notebook], that can be useful to Jupyter users. Particularly, the Leo outllining interface allows a document suited for the emergent structure of Jupyter exploratory computing (as has been [argued since several years][leo-ipython]), with arbitrary deepness layers, and self-referential and programmable notebook. Also, Jupyter has interactive features useful for Leo current or potential Leo users, including multiple languages, persistent objects between cell definitions, interactive graphics, etc.

Leo has been too focused in playing well by interchanging files back and forth with others, and is time to think in playing well by communicating well with others (services). This has been mostly unexplored until now is showing to be critical for the Jupyter integration. The idea is to make Leo a Jupyter client by using the [Jupyter messaging protocol](https://jupyter-client.readthedocs.io/en/latest/) and implementing the interactions discussed on the mailing list [here](https://groups.google.com/forum/#!topic/leo-editor/5AryK8fvje8) and [here](https://groups.google.com/forum/#!topic/leo-editor/ukOK2Mj2TGM/discussion). 

[leo-ipython]: http://mutabit.com/offray/static/blog/output/posts/on-deepness-and-complexity-of-ipython-documents.html
[notebook]: https://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/What%20is%20the%20Jupyter%20Notebook.html#Notebook-documents

**Sub Projects**
Given the scope of this projects, numerous sub-projects will be needed. I'll keep links here:

- [#566:](https://github.com/leo-editor/leo-editor/issues/566) Design: what exactly are we trying to do?
- [#567:](https://github.com/leo-editor/leo-editor/issues/567) Jupyter imports: issues relating to code reuse and initialization.
- [#568:](https://github.com/leo-editor/leo-editor/issues/568) Use [pygments](http://pygments.org/) in Leo itself.
- [#569:](https://github.com/leo-editor/leo-editor/issues/569) Use live objects in Leo itself. It would help code completion, inspection and history.

**Comment by edreamleo** [comment]
From [this post](https://groups.google.com/d/msg/leo-editor/hrM_EvRHu5M/nlgjc5jRBgAJ)

> So what, exactly, does dealing with the jupyter server add to Leo?

Terry: About 100% of the computational power of Jupyter.  This includes Jupyter's *existing* ability to run multiple languages, to move data between those languages, e.g. some data cleanup in Python then some statistical analysis in R before kicking over to javascript for plotting.  I haven't used Jupyter that much, but I think it also has adapters for accessing potentially huge datasets through cloud services and
interfaces to distributed computing platforms like Hadoop and Spark. And I think data persistence between sessions.  Plus a whole lot of things I don't know about - I know there are some esoteric integrations like the doit dependency management system for example.

All of that could be emulated in Leo, just as all of Leo could be emulated in assembly language :-)  I don't think Leo has the developer hours to ever emulate a worthwhile amount of that though.

EKR: OK, I'm convinced.

Terry: The little I have used Jupyter though, I wasn't really very impressed with its interface.  I think it has some limited support for hierarchy, but nothing like Leo.  So the primary benefit of #561 is bringing all the power of Jupyter to Leo users, but secondarily I think Leo might be a better interface to Jupyter.

EKR: There are big questions lurking here:

1. Would `jupyter` support `@others`? This implies tree-structured cells.

2. How to "flatten" Leo `@jupyter` trees for export.  This could be done using nested .json elements, but Jupyter itself does not support same.  And Jupyter does not support `@others`.

**Comment by edreamleo** [comment]
@offray Thanks for this.  The link to the Jupyter messaging protocol was most helpful.​ As I understand it, you idea is quite simple.  It has two parts:

1. Using the Jupyter kernel, we allow people to do in Leo what they might otherwise do in the Jupyter notebook itself.

2. After their work is done, we provide a way of writing the work done in Leo to a Jupyter notebook (.ipynb) file.  This is similar, but not the same as, using Leo's existing .ipynb writer.

Does this vision match yours? Here are some initial thoughts.

#1 above is non-trivial. As I understand it, the most important part of the messaging protocol, as far as Leo is concerned, is the client - communicating with kernels part. The execute, execute_interactive, complete, inspect and history messages have implications for users' work flow.

Must Leo emulate Jupyter's QtConsole window directly in the body pane?  Previous investigates indicate that that might be quite difficult, even given the source code for the console.

Alternatively, the user could mark some body text (say @jupyter) as input to Jupyter. Leo would then direct the output to a "jupyter capable" vr-pane. But perhaps direct emulation of Jupyter's QtConsole in the body pane might be preferable, no matter what the implementation cost.

**Update** from the leo-editor discussion.  The Jupyter QtConsole code is very complex.  It's not clear whether the code can even be adopted for Leo.

**Comment by edreamleo** [comment]
From [this post](https://groups.google.com/d/msg/leo-editor/hrM_EvRHu5M/oxgZLcqbBAAJ)

Terry: My thoughts, which include a lot of groundless assumptions about how
Jupyter works, would be that we have a new node type:

`@jupyter` jupt://127.0.0.1:8123/some/jupyter/protocol/thing

or possibly just

`@jupyter` short_name

with connection details in the body

I'm not really sure if we're talking about IPython or Jupyter, although I think Jupyter is probably correct.  So, on that really shaky footing:

- jupyter-read-all - replace all nodes under the `@jupyter` node with content from the jupyter server
- jupyter-write-all - write all nodes to the jupyter server
- jupyter-execute-all - execute all nodes (cells) to the jupyter server
- jupyter-read-node - single node version
- jupyter-write-node - single node version
- jupyter-execute-node - single node version

EKR: I'm not sure this model makes sense, but it's a good starting point.

Terry: Hopefully Jupyter cells have some sort of invariant ID we can use to manage things.

Jupyter's cells seem to be comprised of a plain text part, the input, which will be the Leo node body, and a rendered result, which is HTML. So nothing tricky here, we can just show the HTML, viewrendered and
leo_edit_pane both support that.

EKR: I agree.

Terry: The rendered result part of the cell could be stored on the node transiently (p.v._jupyter_html) or persistently (p.v.u['jupyter']['html']).

The above just acts as an interface to Jupyter.  I think moving actual data into and out of Leo will be doable via JSON, but I'd make that stage 2.

Terry: Notably absent - .ipynb files.

EKR: Dealing with .ipynb files will be useful as a design exercise, at the very least.

**Comment by edreamleo** [comment]
I have removed the milestone from this item.  This item is unlikely to make it into 5.7.4. The "Best" label should suffice for now.

**Comment by edreamleo** [comment]
Leo isn't going to work with Jupyter.
