### ISSUE TITLE
starting slide show

### ISSUE THREAD

**Issue by AG4GitHub** [leo-editor/leo-editor#563]
Hi, I just cannot find out how to start a slide show. I marked   node with @slideshow with the plugin enabled. What to do then? 

Thanks for help, Andreas

**Comment by edreamleo** [comment]
On Thu, Oct 26, 2017 at 9:32 AM, Andreas Gehrmann <notifications@github.com>
wrote:

> Hi, I just cannot find out how to start a slide show. I marked node with
> @slideshow <https://github.com/slideshow> with the plugin enabled. What
> to do then?
>
​Did you look at the documentation?  It's in the docstring of the
slideshow.py plugin.  You can see this by choosing the Plugins:slideshow
menu, assuming you have enabled the slideshow.py plugin in an
@enabled-plugins setting node.

The plugin creates 4 new commands, which you can execute from the
minibuffer:

- next-slide-show:  move to the start of the next slide show,
  or the first slide show if no slide show has been seen yet.
- prev-slide-show:  move to the start of the previous slide show,
  or the first slide show if no slide show has been seen yet.
- next-slide: move to the next slide of a present slide show.
- prev-slide: move to the previous slide of the present slide show.​

You can repeat any command (not just these commands) using Ctrl-P,
repeat-complex-command.

I created the following tree for testing:

@slideshow my slideshow
  @slide
  This is slide 1. (body text)
  @slide
  This is slide 2

HTH.  Please feel free to ask more questions.

Edward

**Comment by AG4GitHub** [comment]
Thanks  a lot , will test
