### ISSUE TITLE
#561 Sub-Project: Design of Jupyter project

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#566]
It's not clear what is intended by making Leo a Jupyter client.

**Comment by tbnorth** [comment]
Just in case it adds anything, my thought for the Jupyter stuff is that Jupyter and Leo will **not** share a Python interpreter.  The Juypyter and Leo instances need not be on the same computer.  Or continent.  I'd expect all communication to be via messaging over some transport (probably HTTP).  I'm assuming this is where ZeroMQ comies in, but then again, I'm assuming almost everything :-)

**Comment by edreamleo** [comment]
@tbnorth Thanks for these comments.

I have, on purpose, not set a due date for this project because I am not convinced this project makes sense.

Imo, it does not suffice merely to access the Jupyter kernels via Jupyter-like (flat) cells within Leo.  That would add almost nothing to Jupyter notebooks.

The big question is, **can we devise/design a way to add Leo's outline structure (DOM) to the Jupyter environment?**

For example, suppose we allow Jupyter-like cells (within Leo) to contain `@others`.  Surely that's possible, but what good does that do for scientist who eventually wants to present their results using Jupyter? If we can't answer that question, then this (top-level) project will fail. (Sub-projects, especially using pygments in Leo, are mostly self contained, and can continue.)

**Comment by tbnorth** [comment]
On Tue, 31 Oct 2017 15:05:01 +0000 (UTC)
"Edward K. Ream" <notifications@github.com> wrote:

> @tbnorth Thanks for these comments.
> 
> I have, on purpose, not set a due date for this project because I am
> not convinced this project makes sense.
> 
> Imo, it does not suffice merely to access the Jupyter kernels via
> Jupyter-like (flat) cells within Leo.  That would add almost nothing
> to Jupyter notebooks.
> 
> The big question is, **can we devise/design a way to add Leo's
> outline structure (DOM) to the Jupyter environment?**
> 
> For example, suppose we allow Jupyter-like cells (within Leo) to
> contain `@others`.  Surely that's possible, but what good does that
> do for scientist who eventually wants to present their results using
> Jupyter? If we can't answer that question, then this (top-level)
> project will fail. (Sub-projects, especially using pygments in Leo,
> are mostly self contained, and can continue.)

I'm not sure (and am probably speculating too much) that Jupyter has no
support for hierarchy, it may just have a poor interface which prevents
people from using hierarchy.  But assuming it has no support, we could
still have hierarchy in Leo as long as there's something we can use for
node/cell identity.  We'd just write them to Jupyter in thread order.

Hierarchy on the Leo side could be organizer nodes like @clean or @file
allows.  Although generating an external file wouldn't necessarily be
necessary.

**Comment by edreamleo** [comment]
On Tue, Oct 31, 2017 at 10:32 AM, Terry Brown <notifications@github.com>
wrote:

> On Tue, 31 Oct 2017 15:05:01 +0000 (UTC)
>

I'm not sure (and am probably speculating too much) that Jupyter has no
> support for hierarchy, it may just have a poor interface which prevents
> people from using hierarchy.


​.ipynb files are .json, so there *could* be support within Jupyter.

At present, I know of no such thing.  There is a plugin that supports code
folding, but that's not the same thing.
​

> But assuming it has no support, we could
> still have hierarchy in Leo as long as there's something we can use for
> node/cell identity. We'd just write them to Jupyter in thread order.
>

​Yes, we could flatten a cell when writing/sending to Jupyter.​ I'm not
sure this is good enough, but I suppose it might be...

Hierarchy on the Leo side could be organizer nodes like @clean or @file
> allows. Although generating an external file wouldn't necessarily be
> necessary.


​Yes.

Thanks for your comments.  Perhaps your approach is enough to get us
going...

Edward

**Comment by technatica** [comment]
From the Jupyter docs:

Notebooks consist of a linear sequence of cells. There are four basic cell
types:

Code cells: Input and output of live code that is run in the kernel
Markdown cells: Narrative text with embedded LaTeX equations
Heading cells: 6 levels of hierarchical organization and formatting
Raw cells: Unformatted text that is included, without modification, when
notebooks are converted to different formats using nbconvert

http://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/What%20is%20the%20Jupyter%20Notebook.html

Chris

**Comment by edreamleo** [comment]
On Tue, Oct 31, 2017 at 10:44 AM, Chris George <notifications@github.com>
wrote:

> From the Jupyter docs:
>
> Notebooks consist of a linear sequence of cells. There are four basic cell
> types:
> ​[Snip]​
>

​Yes, we know that.  The questions we are discussing are:

1. Is there a Jupyter plugin that supports hierarchical cells?  Imo, it's
likely not going to happen, but the .json format of .ipynb files means that
it's conceivable.

2. What kind of back-and-forth interaction do we envisage between Leo and
Jupyter? Converting Leo scripts to a (single) flat Jupyter cell does not
seem attractive, but it may get us started.

Edward

**Comment by tbnorth** [comment]
On Tue, 31 Oct 2017 15:51:07 +0000 (UTC)
"Edward K. Ream" <notifications@github.com> wrote:

> On Tue, Oct 31, 2017 at 10:44 AM, Chris George
> <notifications@github.com> wrote:
> 
> > From the Jupyter docs:
> >
> > Notebooks consist of a linear sequence of cells. There are four
> > basic cell types:
> > ​[Snip]​
> >
> 
> ​Yes, we know that.  The questions we are discussing are:

Actually I think by pointing out Jupyter's header cells Chris has
identified a way of representing hierarchy on both sides of the pipe.

Also, should have said this sooner, I don't think managing hierarchy is
the first step - a simple linear set of cells that added one to x in a
series f languages and brought the result back to Leo would be a good
start.

**Comment by edreamleo** [comment]
On Tue, Oct 31, 2017 at 11:27 AM, Terry Brown <notifications@github.com>
wrote:

Actually I think by pointing out Jupyter's header cells Chris has
> identified a way of representing hierarchy on both sides of the pipe.
>

​Really?  Can you explain?​

Also, should have said this sooner, I don't think managing hierarchy is
> the first step - a simple linear set of cells that added one to x in a
> series f languages and brought the result back to Leo would be a good
> start.


​Thanks for this.  It allows us to move forward now.

This brings me back to #651 Sub-Project: Imports, code reuse and
initialization <https://github.com/leo-editor/leo-editor/issues/567>. It
seems to me that finding the minimal way to start up a kernel would be a
good first step.  I'll be playing with imports later today.

Edward

**Comment by tbnorth** [comment]
On Tue, 31 Oct 2017 20:16:56 +0000 (UTC)
"Edward K. Ream" <notifications@github.com> wrote:

> On Tue, Oct 31, 2017 at 11:27 AM, Terry Brown
> <notifications@github.com> wrote:
> 
> Actually I think by pointing out Jupyter's header cells Chris has
> > identified a way of representing hierarchy on both sides of the
> > pipe.
> 
> ​Really?  Can you explain?​

So Chris said:

Code cells: Input and output of live code that is run in the kernel
Markdown cells: Narrative text with embedded LaTeX equations
Heading cells: 6 levels of hierarchical organization and formatting
Raw cells: Unformatted text that is included, without modification, when
notebooks are converted to different formats using nbconvert

"Heading cells: 6 levels"

Sounds to me like the way HTML handles hierarchy:

```
<h1>Top</h1>
<p>Stuff stuff stuff</p>
<h2>Sub stuff</h2>
<p>here</p>
<p>hthis too</p>
<h2>More sub stuff</h2>
<p>here</p>
```

Similar to what markdown does with #, ##, ###

> Also, should have said this sooner, I don't think managing hierarchy
> is
> > the first step - a simple linear set of cells that added one to x
> > in a series f languages and brought the result back to Leo would be
> > a good start.
> 
> ​Thanks for this.  It allows us to move forward now.
> 
> This brings me back to #651 Sub-Project: Imports, code reuse and
> initialization <https://github.com/leo-editor/leo-editor/issues/567>.
> It seems to me that finding the minimal way to start up a kernel
> would be a good first step.  I'll be playing with imports later today.
> 
> Edward

**Comment by edreamleo** [comment]
On Tue, Oct 31, 2017 at 3:25 PM, Terry Brown <notifications@github.com>
wrote:

"Heading cells: 6 levels"
>
> Sounds to me like the way HTML handles hierarchy:
>

​This does not handle @others, and never will.  Furthermore, as I have just
verified in a Jupyter notebook, changing a markdown cell to heading level n
merely inserts n "#" characters in the cell. This is pure text hierarchy.

Anyway, this conversation has already been productive because you, Terry,
have suggested a important strategy, namely proceeding with important
code-level experimentation while noodling about how best to make Leo
interact with Jupyter.

Edward

**Comment by tbnorth** [comment]
On Wed, 01 Nov 2017 10:08:47 +0000 (UTC)
"Edward K. Ream" <notifications@github.com> wrote:

> "Heading cells: 6 levels"
> >
> > Sounds to me like the way HTML handles hierarchy:
> >
> 
> ​This does not handle @others, and never will. Furthermore, as I have
> just verified in a Jupyter notebook, changing a markdown cell to
> heading level n merely inserts n "#" characters in the cell. This is
> pure text hierarchy.

I guess I'm not sure what you mean by "handle @others".  Leo can handle
@others on the Leo end of the pipe.  Stuff being pushed to the Jupyter
end of the pipe can represent that hierarchy using these nodes.  When
Leo is pulling cells/nodes from Jupyter Leo can reconstruct the
hierarchy from these nodes.  These nodes provide the representation of
hierarchy in notebooks stored on the server.

Maybe it's a perspective issue.  Some of my perspectives:

- no alteration to Jupyter code, Leo should be able to use any
  Jupyter server, including those out of the Leo users control
- the fact the Jupyter is written in Python is almost completely
  irrelevant
- an example of the model I have in mind is what @leo_cloud does.  It
  stores a subtree somehow somewhere.  The user can load that substree
  de novo from the somewhere.  The user can edit the subtree, and
  replace the subtree in the cloud with their edited version.  When the
  user saves the Leo file the subtree is saved in the .leo file, but the
  cloud version is the canonical version.  The difference for Jupyter
  is that we want more granularity than all or nothing subtree.
  @leo_cloud stores the subtrees as JSON.  It supports hierarchy, but
  has no knowledge of @others.

**Comment by edreamleo** [comment]
On Wed, Nov 1, 2017 at 7:51 AM, Terry Brown <notifications@github.com>
wrote:

I guess I'm not sure what you mean by "handle @others". Leo can handle
> @others on the Leo end of the pipe. Stuff being pushed to the Jupyter
> end of the pipe can represent that hierarchy using these nodes. When
> Leo is pulling cells/nodes from Jupyter Leo can reconstruct the
> hierarchy from these nodes. These nodes provide the representation of
> hierarchy in notebooks stored on the server.
>

​Oh.  So the markdown nodes indicate hierarchy.  I suppose it's possible...​

>
> Maybe it's a perspective issue. Some of my perspectives:
>
> - no alteration to Jupyter code, Leo should be able to use any
> Jupyter server, including those out of the Leo users control
> - the fact the Jupyter is written in Python is almost completely
> irrelevant
> - an example of the model I have in mind is what @leo_cloud does. It
> stores a subtree somehow somewhere. The user can load that substree
> de novo from the somewhere. The user can edit the subtree, and
> replace the subtree in the cloud with their edited version. When the
> user saves the Leo file the subtree is saved in the .leo file, but the
> cloud version is the canonical version. The difference for Jupyter
> is that we want more granularity than all or nothing subtree.
> @leo_cloud stores the subtrees as JSON. It supports hierarchy, but
> has no knowledge of @others.


​Not sure I understand all the implications, but you are convincing me that
cooperating/communicating with the jupyter server ​should come first.  Once
that works we can tackle other issues.  I'm good with this approach.

Now that I am not so freaked out about Jupyter imports and packages, the
next task is to modify the jupyter_console code so that can run from Leo.

For prototyping, I would prefer to Leo's code base (and especially its
startup code) unchanged. So the task is to modify the jupyter_console code
so it runs with the existing Qt app. The goal is to be able to fire up a
kernel from a running Leo instance.

Edward

**Comment by tbnorth** [comment]
On Wed, 01 Nov 2017 19:17:17 +0000 (UTC)
"Edward K. Ream" <notifications@github.com> wrote:

> Now that I am not so freaked out about Jupyter imports and packages,
> the next task is to modify the jupyter_console code so that can run
> from Leo.

I guess that's not where I'd start, but once again, I haven't used
Jupyter enough to be sure about any of this.

I'd expect to start by asking Jupyter to execute some code like

  import math
  a = math.sin(1)

and then send me back either (a) some kind of JSON representation of
the result, or (b) the HTML that that code would have generated if it
was executed in the Jupyter notebook web interface.

In the latter case, a leo_edit_pane pane could display the above code
in the edit half (p.b), and the rendered HTML in the view half.

Cheers -Terry

**Comment by tbnorth** [comment]
On Wed, 01 Nov 2017 19:17:17 +0000 (UTC)
"Edward K. Ream" <notifications@github.com> wrote:

> The goal is to be able to fire up a
> kernel from a running Leo instance

p.s. again allowing for all the assumptions I'm making, I would say no,
the goal is the communicate with a running Jupyter server (kernel) via
ZeroMQ or whatever it is that it uses.

Totally made up:

  connection = zeromq.connect("http://127.0.0.1:8901/notebooks/book2")
  cell_id = connection.add_cell(type='code')
  connection.set_content(cell_id, "import math\na=math.sin(1)")
  connection.run_cell(cell_id)
  html = connection.get_html(cell_id)

See, this is soooo easy when you're just making it up :-)

Important point, while we'd be (separately) launching Jupyter on the
local machine (127.0.0.1), this approach also works when the Jupyter
server is on a remote machine with potentially all kinds of valuable
assets you want to leverage, like local access to large databases etc.

**Comment by edreamleo** [comment]
On Wed, Nov 1, 2017 at 2:37 PM, Terry Brown <notifications@github.com>
wrote:

> On Wed, 01 Nov 2017 19:17:17 +0000 (UTC)
> "Edward K. Ream" <notifications@github.com> wrote:
>
> > Now that I am not so freaked out about Jupyter imports and packages,
> > the next task is to modify the jupyter_console code so that can run
> > from Leo.
>
> I guess that's not where I'd start, but once again, I haven't used
> Jupyter enough to be sure about any of this.
>
> I'd expect to start by asking Jupyter to execute some code like
>
> import math
> a = math.sin(1)
>

​Fair enough, but how do you propose to do this?  I only started with the
jupyter_console code because it shows a Qt pane that does what you want
(and more).

​Do you know of an easier way to start?

Here is what I have done so far, for the jupyter_console, jupyter_client,
qtconsole and traitlets packages:

- git init in the relevant directories, so I can be sure of the changes
made.
- added a reasonable .gitignore file.
- git add *
- git commit -m "initial checkin"

Now I am safe :-) I can mess with the code at will.

- Use the recursive import script to import all files of the package,
including subdirectories, into @clean nodes.
- Save the files and check the diffs. @clean can clean cruft from blank
lines.
- Commit all changed files.

Now I can add traces as I like. git diff will show me where they all are.

Once in awhile importing will fail the perfect import test.  I massage the
results by hand and remove the @ignore directive.  I then check the diffs,
and recommit the changed files.  The acid test is to reload my .leo file,
rewrite the @clean node and recheck the diffs.

I recommend this process to anyone who really wants to dig into the code.
However, I'll be happy to take any suggestions for starting points if just
eyeballing the code suggests a better way to get started.

Edward​

**Comment by edreamleo** [comment]
On Wed, Nov 1, 2017 at 2:47 PM, Terry Brown <notifications@github.com>
wrote:

> On Wed, 01 Nov 2017 19:17:17 +0000 (UTC)
> "Edward K. Ream" <notifications@github.com> wrote:
>
> > The goal is to be able to fire up a
> > kernel from a running Leo instance
>
> p.s. again allowing for all the assumptions I'm making, I would say no,
> the goal is the communicate with a running Jupyter server (kernel) via
> ZeroMQ or whatever it is that it uses.
>
> Totally made up:
>
> connection = zeromq.connect("http://127.0.0.1:8901/notebooks/book2")
> cell_id = connection.add_cell(type='code')
> connection.set_content(cell_id, "import math\na=math.sin(1)")
> connection.run_cell(cell_id)
> html = connection.get_html(cell_id)
>
> See, this is soooo easy when you're just making it up :-)
>

​I like the simplicity of your suggestion, but...​

​You appear to be suggesting handling the communication from "first
principles".  That could be much simpler than using the jupyter code, but I
wonder whether using the jupyter code might not be better in the long run...

Also, doesn't Leo need to be able to start jupyter kernels as appropriate?

Edward

**Comment by tbnorth** [comment]
On Wed, 01 Nov 2017 20:09:34 +0000 (UTC)
"Edward K. Ream" <notifications@github.com> wrote:

> ​Do you know of an easier way to start?

I'd start here:
http://jupyter-client.readthedocs.io/en/latest/messaging.html

Cheers -Terry

**Comment by edreamleo** [comment]
On Wed, Nov 1, 2017 at 3:27 PM, Terry Brown <notifications@github.com>
wrote:

> On Wed, 01 Nov 2017 20:09:34 +0000 (UTC)
> "Edward K. Ream" <notifications@github.com> wrote:
>
> > ​Do you know of an easier way to start?
>
> I'd start here:
> http://jupyter-client.readthedocs.io/en/latest/messaging.html


​I've read this several times, but it's not suggesting real code to me. Any
help you could give would be appreciated.

Edward

**Comment by tbnorth** [comment]
On Wed, 01 Nov 2017 20:26:44 +0000 (UTC)
"Edward K. Ream" <notifications@github.com> wrote:

> Also, doesn't Leo need to be able to start jupyter kernels as
> appropriate?

As a trivial convenience function, maybe.  I'd use subprocess.Popen to
launch a local server/kernel if there's not one running already,
detaching it to the greatest extent possible.  I have some code
somewhere for making that work in Windows.  But for initial
experimentation I'd just start it manually.

> ​You appear to be suggesting handling the communication from "first
> principles". That could be much simpler than using the jupyter code,
> but I wonder whether using the jupyter code might not be better in
> the long run...

I don't think it's first principles, I think it's how Jupyter expects
communication to work.  My made up code was the answer to your other
question:

> > I'd start here:
> > http://jupyter-client.readthedocs.io/en/latest/messaging.html
> 
> ​I've read this several times, but it's not suggesting real code to me. Any
> help you could give would be appreciated.

Remember I think that Jupyter and Leo both being written in Python is
irrelevant.  Or at least it's irrelevant in terms of the Leo / Jupyter
interface.  The fact that Python's the primary language used in Jupyter
makes connectivity attractive to Leo's Python centric users.

I would:

 - start a Jupyter kernel/server on my machine, manually.
 - connect to it via its web interface and confirm its working (I have
   done that much in the past myself)
 - try and write a Python script that talks to the server via ZeroMQ

Cheers -Terry

**Comment by xgid** [comment]
If it may be of any use, my two cents after a minimal walk through the Jupyter sub-projects and docs (there may be interpretation errors, so take it with a pinch of salt):

- Any "normal" installation of Jupyter (like `ipython` or `jupyter-console`) comes with the Python kernel by default. If you want other kernels (for R, Scala, ...), you have to add them to Jupyter.
- This command shows the available kernels:
```dos
(jupytcon36) D:\proj\external\jupyter_console>jupyter kernelspec list
Available kernels:
  python3    c:\dev\anaconda3\envs\jupytcon36\share\jupyter\kernels\python3
```
- The communication with the kernel is more basic than what you suggested above, because **the kernel** knows nothing about cells, hierarchy, whatever. You may better see it just as a "remote" (or detached) interpreter: you send it the code to execute and get a result message with an status indication ('ok' or 'error'). You may also capture the output, if any. 
- You can see a good minimal example at the following adaptation of [this test of the jupyter_client](https://github.com/jupyter/jupyter_client/blob/master/jupyter_client/tests/test_client.py#L35-L41) (where `kc` is the kernel object):
```python
        with capture_output() as io:
            reply = kc.execute_interactive("a = 'hello'\nprint(a)", timeout=TIMEOUT)
        assert 'hello' in io.stdout
        assert reply['content']['status'] == 'ok'

        with capture_output() as io:
            reply2 = kc.execute_interactive("a = a + ' world'\nprint(a)", timeout=TIMEOUT)
        assert 'hello world' in io.stdout
```
The modification is just to show that the kernel (interpreter) keeps the global context for the code executed so far.
- To have kernels other than Python easily installed and running, one of the best options is to use any of the [docker-stacks](https://github.com/jupyter/docker-stacks) like:
```cmd
docker run -it --rm -p 8888:8888 jupyter/all-spark-notebook
```

This is what I got so far.
Xavier

**Comment by xgid** [comment]
I have still not seen how do Jupyter notebooks do to get HTML or images out of the kernel...

**Comment by edreamleo** [comment]
On Wed, Nov 1, 2017 at 3:44 PM, Terry Brown <notifications@github.com>
wrote:

> On Wed, 01 Nov 2017 20:26:44 +0000 (UTC)
> "Edward K. Ream" <notifications@github.com> wrote:
>
> > Also, doesn't Leo need to be able to start jupyter kernels as
> > appropriate?
>
> As a trivial convenience function, maybe. I'd use subprocess.Popen to
> launch a local server/kernel if there's not one running already,
> detaching it to the greatest extent possible. I have some code
> somewhere for making that work in Windows. But for initial
> experimentation I'd just start it manually.
>

​I'm all for quick experimentation.  Otoh, ​eventually I think it would
make sense to use corresponding Jupyter code where possible.  There are
several reasons for this.  First, there may be subtle, undocumented,
subtleties in various protocols.  Second, using Jupyter code is more likely
to work if protocols change.  And finally, using Jupyter code should be
easier.

The following modules in the jupyter_client package relate to connections,
with their docstrings:

*Adapter.py*
"""Adapters for Jupyter msg spec versions."""

*channels.py*
"""Base classes to manage a Client's interaction with a running kernel"""

*connect.py*
"""Utilities for connecting to jupyter kernels

The :class:`ConnectionFileMixin` class in this module encapsulates the logic
related to writing and reading connections files.
"""

*json_util.py*
"""Utilities to manipulate JSON objects."""

*launcher.py*
"""Utilities for launching kernels"""

*localinterfaces.py*
"""Utilities for identifying local IP addresses."""

*manager.py*
"""Base class to manage a running kernel"""

*mutikernelmanager.py*
"""A kernel manager for multiple kernels"""

*restarter.py*
"""A basic kernel monitor with autorestarting.

This watches a kernel's state using KernelManager.is_alive and auto
restarts the kernel if it dies.

It is an incomplete base class, and must be subclassed.
"""

*session.py*
"""Session object for building, serializing, sending, and receiving
messages.

The Session object supports serialization, HMAC signatures,
and metadata on messages.

Also defined here are utilities for working with Sessions:
* A SessionFactory to be used as a base class for configurables that work
with
Sessions.
* A Message object for convenience that allows attribute-access to the msg
dict.
"""

*threaded.py*
""" Defines a KernelClient that provides thread-safe sockets with async
callbacks on message replies.
"""

*win_interrupt.py*
"""Use a Windows event to interrupt a child process like SIGINT.

The child needs to explicitly listen for this - see
ipykernel.parentpoller.ParentPollerWindows for a Python implementation.
"""

*Summary*

Simple-as-possible prototype code is often a great idea.  Terry, feel free
:-)

The files discussed above a more complex, but they also almost surely
robust and well tested. Imo, we will eventually want to use the
jupyter_client code whenever possible.  For example, the calls to Popen in
these files are far from trivial.

Finally, the class structure of these utility classes seems mostly
independent of the more complex class structure of jupyter client apps.
This may be important.  The only worrying dependency is the
LoggingConfigurable class, part of the traitlets system.

Edward

**Comment by tbnorth** [comment]
Perhaps we'd drifted onto two different pages.  For sure using existing
Python code that implements a Jupyter *client* makes sense, as long as
it's on the client side of the network pipeline.  The direction I was
arguing against was anything that had Leo invoke / interact with the
Jupyter kernel in a way that depended on being on the same machine or
sharing a Python process.  I think Leo needs to be able to run stuff on
remote Jupyter installs because I often see that being used as a way to
provide access to particular large datasets or distributed computing
resources.

Also I was hoping / still hope there's a way Leo can get the HTML that
renders results as used by the Jupyter web client, just because the
immediately gives you a huge glob of rich outputs with minimal work on
our end.  Send code (text), get results ready to display (HTML /
javascript).

If we can't find that pathway, I'd start with send code (text), get
results as data (JSON) as the first step before worrying about getting
some Jupyter specific PyQt console widget thing working.

So apologies if basing my advice on nothing but assumptions and
conjecture somehow yielded confusion - how could that happen? :-)

XGiD mentions the kernel knowing nothing about cells etc., which makes
me wonder if there's another layer to target which does understand them
and might manage running them and returning HTML - OTOH hard to know
how much of that component is written in Javascript.  Somewhere there's
a layer that allows you to save notebooks on the server, so that must
understand cells - perhaps using the terms server and kernel
interchangeably is wrong.

Heh - I guess one option would be to run a captive web interface client
in a QWebView and use Qt's hooks to get stuff in and out of that - not
sure it's the best idea, but it would preserve the "Leo can do anything
the web client can do" goal, including rendered results.

Cheers -Terry

**Comment by edreamleo** [comment]
On Thu, Nov 2, 2017 at 8:20 AM, Terry Brown <notifications@github.com>
wrote:

> Perhaps we'd drifted onto two different pages. For sure using existing
> Python code that implements a Jupyter *client* makes sense, as long as
> it's on the client side of the network pipeline. The direction I was
> arguing against was anything that had Leo invoke / interact with the
> Jupyter kernel in a way that depended on being on the same machine or
> sharing a Python process. I think Leo needs to be able to run stuff on
> remote Jupyter installs because I often see that being used as a way to
> provide access to particular large datasets or distributed computing
> resources.
>

​That's fine with me.​

Also I was hoping / still hope there's a way Leo can get the HTML that
> renders results as used by the Jupyter web client, just because the
> immediately gives you a huge glob of rich outputs with minimal work on
> our end. Send code (text), get results ready to display (HTML /
> javascript).
>

​This is a big project, and I had forgotten all about this goal.

If we can't find that pathway, I'd start with send code (text), get
> results as data (JSON) as the first step before worrying about getting
> some Jupyter specific PyQt console widget thing working.
>

> So apologies if basing my advice on nothing but assumptions and
> conjecture somehow yielded confusion - how could that happen? :-)
>

​It's not a problem. We are picking our way through largely unknown
territory.​

XGiD mentions the kernel knowing nothing about cells etc., which makes
> me wonder if there's another layer to target which does understand them
> and might manage running them and returning HTML - OTOH hard to know
> how much of that component is written in Javascript. Somewhere there's
> a layer that allows you to save notebooks on the server, so that must
> understand cells - perhaps using the terms server and kernel
> interchangeably is wrong.
>

​The code exists somewhere.​ Reading the sources may be the most efficient
way to find it.

Heh - I guess one option would be to run a captive web interface client
> in a QWebView and use Qt's hooks to get stuff in and out of that - not
> sure it's the best idea, but it would preserve the "Leo can do anything
> the web client can do" goal, including rendered results.
>

​Anything that helps prototyping and investigation is worth considering.

This morning I'm going to read I discussed early this morning as if it were
a novel.  I want to see what the code is doing and how, even if large parts
are only dimly understood.

Edward

**Comment by edreamleo** [comment]
@tbnorth >The direction I was arguing against was anything that had Leo invoke / interact with the Jupyter kernel in a way that depended on being on the same machine or sharing a Python process. 

Here is the info for the tunnel_to_kernel function in jupyter_client.connect.py:
```python
def tunnel_to_kernel(connection_info, sshserver, sshkey=None):
    """tunnel connections to a kernel via ssh

    This will open four SSH tunnels from localhost on this machine to the
    ports associated with the kernel.  They can be either direct
    localhost-localhost tunnels, or if an intermediate server is necessary,
    the kernel must be listening on a public IP.
    Parameters
    ----------
    connection_info : dict or str (path)
        Either a connection dict, or the path to a JSON connection file
    sshserver : str
        The ssh sever to use to tunnel to the kernel. Can be a full
        `user@server:port` string. ssh config aliases are respected.
    sshkey : str [optional]
        Path to file containing ssh key to use for authentication.
        Only necessary if your ssh config does not already associate
        a keyfile with the host.

    Returns
    -------

    (shell, iopub, stdin, hb) : ints
        The four ports on localhost that have been forwarded to the kernel.
    """
```

**Comment by edreamleo** [comment]
Earlier I said:
> the class structure of these utility classes seems mostly independent of the more complex class structure of jupyter client apps...The only worrying dependency is the LoggingConfigurable class, part of the traitlets system.

After skimming through http://traitlets.readthedocs.io/en/stable/ and http://traitlets.readthedocs.io/en/stable/config.html it seems that it should be possible to use Configurable objects without much fuss.

**Comment by edreamleo** [comment]
I am going to close this issue/thread. It has gotten too long to be useful. [Recent work] has resulted in a working prototype.
