### ISSUE TITLE
Permanently remove files from Leo git repo history

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#572]
Eeek! I recently pushed a commit that accidentally included a 24mb binary file
6a9d73f6db03756ab3c4db2cf2b32d37ac5668e2  -- that's horrible :(

After some research it looks like a good tool to clean up my mess is [BFG Repo-Cleaner][0]

Given that a fresh clone of Leo takes 6 minutes on a >500 KiB/s connection maybe there are other things that could be pruned from the history too? This issue here to collect those, if they exist.

Group threads:

* https://groups.google.com/forum/#!topic/leo-editor/SpyemNJgH1Q
* https://groups.google.com/forum/#!topic/leo-editor/dL288Tofe90

[0]: https://rtyley.github.io/bfg-repo-cleaner/

**Comment by ktenney** [comment]
For those wanting to run from trunk, but not needing history,
I recommend

git clone --depth=1 <repo>

which doesn't fetch any history: big time saver

**Comment by tbnorth** [comment]
On Thu, 02 Nov 2017 19:39:57 +0000 (UTC)
matt wilkie <notifications@github.com> wrote:

> Eeek! I recently pushed a commit that accidentally included a 24mb
> binary file 6a9d73f6db03756ab3c4db2cf2b32d37ac5668e2  -- that's
> horrible :(
> 
> After some research it looks like a good tool to clean up my mess is
> BFG Repo-Cleaner

Given how recent it was you could just fix it by hand.

git reset --hard e312165e1

and then the icky bit - you're going to have to 

git push --force

I assume, can't imagine how any tool can avoid that.  Maybe email the
list with a schedule for when you're going to do that, so people know
it's coming.

If it was longer ago, you can also use `git filter-branch` to eliminate
a file from history, BFG repo. cleaner must do something similar.

> Given that a fresh clone of Leo takes 6 minutes on a >500 KiB/s
> connection maybe there are other things that could be pruned from the
> history too? This issue here to collect those, if they exist.

Not keen on that idea.  It would break references to historic commits.
Maybe take a quick look and see if there's something huge lurking in
there, but I suspect not, and people who really need to clone in a
hurry can always use a shallow clone.

Cheers -Terry

**Comment by maphew** [comment]
Terry cleaned up my mess and forced push that eliminated the large file from GitHub's history. If you've made no commits / changes to the leo-editor repository since then, you can either (a) delete your local clone and clone fresh OR (b):

    git reset --hard e312165e19342
    git pull

in your local clone. What **you don't want to do is just pull as usual**, even if you don't usually commit to Leo, git will see the two extra commits as new work and want to merge / push them back. 
 -- https://groups.google.com/d/msg/leo-editor/dL288Tofe90/kAo2HAMFBAAJ
