### ISSUE TITLE
leoDist: some external files missing when installed by pip

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#573]
When Leo is installed via pip into site-packages external files referenced in leoDist.leo are missing:

~~~
Leo Log Window
Leo 5.6, build 20171105131700, Sun Nov  5 13:17:00 PST 2017
Not running from a git repo
Python 3.6.3, PyQt version 5.9.2
Windows 7 AMD64 (build 6.1.7601) SP1
isPython3: True
caching enabled
loadOnePlugin: can not load enabled plugin: leo.plugins.viewrendered
reading: C:\apps\miniconda3\lib\site-packages\leo\dist\leoDist.leo
can not open: '@file C:\apps\miniconda3\lib\site-packages\leo_assoc.nsi'
can not open: '@file C:\apps\miniconda3\lib\site-packages\leo.nsi'
read 2 files in 0.02 seconds
read outline in 0.08 seconds
~~~

The immediate fix would be to just name them in `MANIFEST.in`. Would that cause issues with the nsis installer? (or anything else?)

**Comment by edreamleo** [comment]
On Wed, Nov 8, 2017 at 8:38 PM, matt wilkie <notifications@github.com>
wrote:

> When Leo is installed via pip into site-packages external files referenced
> in leoDist.leo are missing:
> ​ [snip]
>
The immediate fix would be to just name them in MANIFEST.in. Would that
> cause issues with the nsis installer? (or anything else?)


​Probably not.  However, @button make leo (in leoDist.leo) creates
manifest.in. This script may need to change...

Edward

**Comment by maphew** [comment]
> ​Probably not. However, @button make leo (in leoDist.leo) creates
> manifest.in. This script may need to change...
>

Oh! that would revert some of the other changes I made earlier too.

...[later]  I see several places in the button node where
`git-manifest.txt` is mentioned, but the only `manifest.in` reference I see
is in `.git-attributes`

**Comment by edreamleo** [comment]
@maphew In my copy of nsi-install-files.txt the following entries exist:

File "leo.nsi"
File "leo_assoc.nsi"

Git tracks these files, as `gitk leo.nsi` shows.  Do you see them in nsi-install-files.txt?

**Comment by maphew** [comment]
Yes, both files are in my nsi-install-files.txt -- in my development repo. They don't exist in a pip-installed Leo deployment though (`PYTHONHOME\Lib\site-packages\leo`)

I've been doing a lot of reading and asking questions. Here's my current understanding. Our current structure more or less:
~~~
\---app
    \---docs
    \---py-modules
        \---core
    \---extras
~~~

When we build a _source distribution_ (`python setup.py sdist`) that entire structure and contents are stuffed into a tar archive. (At least it does now with the setup.py post ~Oct-2017)

**However** after `pip install app-0.1.tar.gz` this is what is received:
~~~
PYTHONHOME\Lib\site-packages
                  \---py-modules
                      \---core
~~~

A _wheel_ has the same result (a wheel basically the above two steps combined into one and pre-compiled for distribution).

I asked https://gitter.im/pypa/setuptools if there was a way to just have pip use `app` as the root parent instead of `py-modules`, since if we manually copy the whole folder tree everything will just work. (Modulo cumbersome mechanism of having to start with `python path\to\app\launch.py`.)

The answer? **You just can't do that. `extras` must live under `app`.**

(You can fake it by putting an empty `__init__.py` in `extra`, but then it will get put into `PYTHONHOME\Lib\site-packages` along side `app` at same level, polluting the name space.)

...

So where does this leave us?

- Do nothing. In it's current state pip install Leo succeeds, the end user has a fully functioning application (so far as we know, given the light testing to date), but some (developer-specific?) files are unavailable.

- Follow recommendation, move everything in the root folder outside of Readme, License and Setup into `leo/something`, and then update all of Leo's internal link references and workflows to match.

- ...?

--> Moving conversation to email list, otherwise this issue is going to get way too long and hard to make sense of!

**Comment by maphew** [comment]
https://groups.google.com/forum/#!topic/leo-editor/XLQiJhGnZfY

**Comment by edreamleo** [comment]
Let's close this issue.  Doing nothing gets my vote.

Please reopen if more serious problems arise.

**Comment by maphew** [comment]
Also see #604
