### ISSUE TITLE
Body pane enhancement: Multiple cursors

### ISSUE THREAD

**Issue by boltex** [leo-editor/leo-editor#575]
Hello, 

This is some kind of feature request:

Popular editors offer the feature of 'multiple cursors', often made available by CTRL+clicking in the text of the editor to insert an aditional cursor. 

This feature also often suports copy/pasting at multiple places in parallel if the number of cursors match. (If they dont match then all copied snipets are concatenated.)

I'm wondering if Leo now supports a way to have multiple simultaneous cursors? 

If not could someone point me in the general direction of how to modify the behavior of the body pane to add this kind of feature?

Thanks!

**Comment by edreamleo** [comment]
> I'm wondering if Leo now supports a way to have multiple simultaneous cursors?

I'm not sure anything like this is possible with Qt text widgets.  Furthermore, the notion of a single selection range is baked into Leo's code.  It does not seem feasible without a big effort.

**Comment by edreamleo** [comment]
This isn't going to happen.
