### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'QObject'

### ISSUE THREAD

**Issue by AG4GitHub** [leo-editor/leo-editor#576]
Hi, I needed to reinstall my Leo in win 10 Pro after I downgraded my Anaconda python installation to 3.4.5  from 3.6.

Now Leo is not starting anymore and stops with an error: AttributeError: 'NoneType' object has no attribute 'QObject'.

Would be great to get any hint. Andreas

for details see below.

C:\Program Files\Leo-5.6> python launchleo.py

reading settings in C:\Program Files\Leo-5.6\leo\config\leoSettings.leo
reading settings in C:\Users\ag\.leo\myLeoSettings.leo
Traceback (most recent call last):
  File "launchleo.py", line 8, in <module>
    leo.core.runLeo.run()
  File "C:\Program Files\Leo-5.6\leo\core\runLeo.py", line 71, in run
    g.app.loadManager.load(fileName, pymacs)
  File "C:\Program Files\Leo-5.6\leo\core\leoApp.py", line 2105, in load
    lm.doPrePluginsInit(fileName, pymacs)
  File "C:\Program Files\Leo-5.6\leo\core\leoApp.py", line 2172, in doPrePluginsInit
    lm.createGui(pymacs)
  File "C:\Program Files\Leo-5.6\leo\core\leoApp.py", line 2343, in createGui
    lm.createSpecialGui(gui_option, pymacs, script, windowFlag)
  File "C:\Program Files\Leo-5.6\leo\core\leoApp.py", line 2358, in createSpecialGui
    g.app.createDefaultGui()
  File "C:\Program Files\Leo-5.6\leo\core\leoApp.py", line 1046, in createDefaultGui
    app.createQtGui(fileName, verbose=verbose)
  File "C:\Program Files\Leo-5.6\leo\core\leoApp.py", line 1068, in createQtGui
    import leo.plugins.qt_gui as qt_gui
  File "C:\Program Files\Leo-5.6\leo\plugins\qt_gui.py", line 12, in <module>
    import leo.plugins.qt_events as qt_events
  File "C:\Program Files\Leo-5.6\leo\plugins\qt_events.py", line 46, in <module>
    class LeoQtEventFilter(QtCore.QObject):
AttributeError: 'NoneType' object has no attribute 'QObject'

**Comment by edreamleo** [comment]
On Wed, Nov 15, 2017 at 3:46 AM, Andreas Gehrmann <notifications@github.com>
wrote:

> Hi, I needed to reinstall my Leo in win 10 Pro after I downgraded my
> Anaconda python installation to 3.4.5 from 3.6.
>
> Now Leo is not starting anymore and stops with an error: AttributeError:
> 'NoneType' object has no attribute 'QObject'.
>
​File "C:\Program Files\Leo-5.6\leo\plugins\qt_events.py", line 46, in
class LeoQtEventFilter(QtCore.QObject):
AttributeError: 'NoneType' object has no attribute 'QObject'
​
​This indicates that Qt (in particular, QtCore) has not been installed
properly.

HTH.

Edward

**Comment by AG4GitHub** [comment]
thanks, but it is installed. 

I  up-graded to qt: 5.6.2-vc14_3  --> 5.6.2-vc10_5 , but same error message. Any other hint?

cheers

**Comment by edreamleo** [comment]
On Wed, Nov 15, 2017 at 6:16 AM, Andreas Gehrmann <notifications@github.com>
wrote:

> thanks, but it is installed.
>
​The trace says that Leo doesn't think so.

Please insert the statement g.pdb() in leoQt.py, just after the line:

import leo.core.leoGlobals as g

Single-step through the file, looking for anything strange.

Edward

**Comment by AG4GitHub** [comment]
Thanks

did so and got:

PS C:\Program Files\Leo-5.6> python launchleo.py
--Return--
> c:\program files\leo-5.6\leo\core\leoglobals.py(1822)pdb()->None
-> pdb.set_trace()
(Pdb)

What should I do now?

**Comment by edreamleo** [comment]
On Wed, Nov 15, 2017 at 9:13 AM, Andreas Gehrmann <notifications@github.com>
wrote:

> Thanks
>
> did so and got:
>
> PS C:\Program Files\Leo-5.6> python launchleo.py
> --Return--
>

​Oh good.  You have an adventure ahead of you.

First, skim through the docs for pdb at
https://docs.python.org/2/library/pdb.html

The main commands are:

c: continue
n: single step, treating function calls as a single statement.
s: single step, stepping *into* function calls
p <expression>: print expression

The great advantage of single stepping is that pdb will report exceptions
immediately.

So single step (n) through the code and see what happens.  When done, hit
'c'.

Edward

**Comment by tbnorth** [comment]
On Wed, 15 Nov 2017 15:57:50 +0000 (UTC)
"Edward K. Ream" <notifications@github.com> wrote:

> On Wed, Nov 15, 2017 at 9:13 AM, Andreas Gehrmann
> <notifications@github.com> wrote:
> 
> > Thanks
> >
> > did so and got:
> >
> > PS C:\Program Files\Leo-5.6> python launchleo.py
> > --Return--
> 
> ​Oh good. You have an adventure ahead of you.

This assumes that Andreas wants / has any need to learn how to use
pdb.  I guess we know he uses Python because he mentioned Anaconda, but
this same issue could be faced by someone wanting to use Leo to write a
book or something.

I guess I'd suggest

python
from PyQt5 import QtCore

and report the result from that - that's where I'd start diagnosing Qt
installation.  Just sayin' ;-)

Cheers -Terry

**Comment by edreamleo** [comment]
On Wed, Nov 15, 2017 at 10:23 AM, Terry Brown <notifications@github.com>
wrote:

I guess I'd suggest
>
> python
> from PyQt5 import QtCore
>
> and report the result from that - that's where I'd start diagnosing Qt
> installation. Just sayin' ;-)
>

​Yes, that's certainly a reasonable alternative.

Edward

**Comment by technatica** [comment]
As someone who uses Leo strictly for writing... This may help. Or it may
not.

I recently switched Linux distributions and reinstalled everything.

I installed the latest Anaconda and the rest of the prerequisites
 and installed Leo using git.

Leo wasn't happy and stalled loading QT. I had a lovely hung window that
displayed nothing. I could move it using the mouse (the window displayed
whatever was under it when Leo started up) and I could close it.

I assumed a QT issue and started stepping back versions using the excellent
navigator utility in Anaconda.

That didn't work. I reset to QT 5.6.2.

Having a history with Linux, Python and Leo, I then started stepping back
python versions.

The magic (for Leo) happened at python 3.5.4.

Caring little about which python version I run, this worked for me. Hope it
helps.

Chris

**Comment by tbnorth** [comment]
On Wed, 15 Nov 2017 17:02:42 +0000 (UTC)
Chris George <notifications@github.com> wrote:

> I assumed a QT issue and started stepping back versions using the
> excellent navigator utility in Anaconda.
> 
> That didn't work. I reset to QT 5.6.2.
> 
> Having a history with Linux, Python and Leo, I then started stepping
> back python versions.
> 
> The magic (for Leo) happened at python 3.5.4.

Hmm, do you remember which Python didn't work?  3.5.x or 3.6?

Edward which Python 3 do you test?  There are changes in 3.6
like "Windows filesystem and console encoding changed to UTF-8"
which could potentially bite.

Cheers -Terry

**Comment by technatica** [comment]
The install used 3.6.

Chris

**Comment by tbnorth** [comment]
So, Edward, I think this means Chris saw a break between 3.5 and 3.6 -
might pay to check we're running on both, if not routinely, at least as
a one off thing.

Cheers -Terry

**Comment by edreamleo** [comment]
On Wed, Nov 15, 2017 at 1:00 PM, Terry Brown <notifications@github.com>
wrote:

> So, Edward, I think this means Chris saw a break between 3.5 and 3.6 -
> might pay to check we're running on both, if not routinely, at least as
> a one off thing.
>

​Thanks for this summary.  On Windows 10 I use:

Python 3.5.2, PyQt version 5.6.2 or
Python 2.7.12, PyQt version 4.8.7

​On Linux I use:

Python 3.5.1, PyQt 5.7.0 or
Python 2.7.11, PyQt 4.8.7.

Edward

**Comment by AG4GitHub** [comment]
Thanks for the hint with the debugger, before stepping in at this level  I  installed  Python 3.5.2, PyQt version 5.6.2, and tried to launch again now I got a different message.

Does this provide a new insight??

C:\Program Files (x86)\Leo-5.6>python launchleo.py

reading settings in C:\Program Files (x86)\Leo-5.6\leo\config\leoSettings.leo
reading settings in C:\Users\ag\.leo\myLeoSettings.leo
Traceback (most recent call last):
  File "launchleo.py", line 8, in <module>
    leo.core.runLeo.run()
  File "C:\Program Files (x86)\Leo-5.6\leo\core\runLeo.py", line 71, in run
    g.app.loadManager.load(fileName, pymacs)
  File "C:\Program Files (x86)\Leo-5.6\leo\core\leoApp.py", line 2105, in load
    lm.doPrePluginsInit(fileName, pymacs)
  File "C:\Program Files (x86)\Leo-5.6\leo\core\leoApp.py", line 2172, in doPrePluginsInit
    lm.createGui(pymacs)
  File "C:\Program Files (x86)\Leo-5.6\leo\core\leoApp.py", line 2343, in createGui
    lm.createSpecialGui(gui_option, pymacs, script, windowFlag)
  File "C:\Program Files (x86)\Leo-5.6\leo\core\leoApp.py", line 2358, in createSpecialGui
    g.app.createDefaultGui()
  File "C:\Program Files (x86)\Leo-5.6\leo\core\leoApp.py", line 1046, in createDefaultGui
    app.createQtGui(fileName, verbose=verbose)
  File "C:\Program Files (x86)\Leo-5.6\leo\core\leoApp.py", line 1068, in createQtGui
    import leo.plugins.qt_gui as qt_gui
  File "C:\Program Files (x86)\Leo-5.6\leo\plugins\qt_gui.py", line 12, in <module>
    import leo.plugins.qt_events as qt_events
  File "C:\Program Files (x86)\Leo-5.6\leo\plugins\qt_events.py", line 46, in <module>
    class LeoQtEventFilter(QtCore.QObject):
AttributeError: 'NoneType' object has no attribute 'QObject'

**Comment by edreamleo** [comment]
On Thu, Nov 16, 2017 at 3:03 AM, Andreas Gehrmann <notifications@github.com>
wrote:

> Thanks for the hint with the debugger, before stepping in at this level I
> installed Python 3.5.2, PyQt version 5.6.2, and tried to launch again now I
> got a different message.
>
> Does this provide a new insight??
>
​It looks like the same issue in a slightly different guise.  The question
still remains, why aren't the Qt imports working?

Edward

**Comment by tbnorth** [comment]
On Wed, 15 Nov 2017 20:23:17 +0000 (UTC)
"Edward K. Ream" <notifications@github.com> wrote:

> On Wed, Nov 15, 2017 at 1:00 PM, Terry Brown
> <notifications@github.com> wrote:
> 
> > So, Edward, I think this means Chris saw a break between 3.5 and
> > 3.6 - might pay to check we're running on both, if not routinely,
> > at least as a one off thing.
> >
> 
> ​Thanks for this summary.  On Windows 10 I use:
> 
> Python 3.5.2, PyQt version 5.6.2 or
> Python 2.7.12, PyQt version 4.8.7
> 
> ​On Linux I use:
> 
> Python 3.5.1, PyQt 5.7.0 or
> Python 2.7.11, PyQt 4.8.7.

Just tried Leo *in Ubuntu* with Python 3.6 (miniconda) and didn't see
any problems.

Cheers -Terry

**Comment by edreamleo** [comment]
On Thu, Nov 16, 2017 at 7:34 AM, Terry Brown <notifications@github.com>
wrote:

Just tried Leo *in Ubuntu* with Python 3.6 (miniconda) and didn't see
> any problems.
>

​Thanks for this.  I'm pretty sure this is some kind of strange issue with
the OP's machine.

Edward

**Comment by technatica** [comment]
I just updated the index in anaconda-navigator.

It gave me python 3.63 as an option, so I took it. The original install had
3.6.2 as the default.

Now Leo starts properly.

Chris

**Comment by edreamleo** [comment]
On Thu, Nov 16, 2017 at 9:59 AM, Chris George <notifications@github.com>
wrote:

> I just updated the index in anaconda-navigator.
>
> It gave me python 3.63 as an option, so I took it. The original install had
> 3.6.2 as the default.
>
> Now Leo starts properly.
>

​Excellent.  I'm glad you have found a way out of install hell.

I'll close this issue.

Edward
