### ISSUE TITLE
Create a new TestCase subclass for reformatting unit tests

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#577]
From a [recent discussion](https://groups.google.com/d/msg/leo-editor/LgjkkiGiYRg/hHLB_HQWCQAJ).

> for example a test of paragraph rejustification might be easier to write if you didn't have to account for different user preferences on text width - that sort of thing.

​I agree​.  Happily, there is a straightforward way.

The @test reformat-paragraph* tests all look like:
```python
# Required when running tests externally
@language plain
@pagewidth 40
@tabwidth 8

c.testManager.runEditCommandTest(p)
```
where the children of these nodes specify the actual tests. We should be a able to simplify this to, say,
```python
c.testManager.runReformatCommandTest(p)
```
The new runReformatCommandTest method would instantiate a new subclass of Unittest.TestCase, say ReformatTestCase, whose setup/teardown methods would handle user settings.

**Comment by edreamleo** [comment]
From the checkin log for 1ff599d 

Added "Required for reformat-paragraph tests" node to unitTest.leo, containing:
```
    @int page_width = 80
    @int tab_width = -4
```
This may allow unit tests to be run in more environments.

Terry, please report any further problems.

**Comment by tbnorth** [comment]
On Sun, 26 Nov 2017 21:55:46 +0000 (UTC)
"Edward K. Ream" <notifications@github.com> wrote:

> >From the checkin log for 1ff599d   
> 
> Added "Required for reformat-paragraph tests" node to unitTest.leo,
> containing: ```
>     @int page_width = 80
>     @int tab_width = -4
> ```
> This may allow unit tests to be run in more environments.
> 
> Terry, please report any further problems.

Um, this was never an actual problem for me, just a hypothetical
problem.  I thought unit tests should be run with vanilla
leoSettings.leo settings rather than modified myLeoSettings.leo, and
used paragraph reformatting as an example of the kind of situation
where a naive unit test might fail because the expected outcome
depended on an assumed page width setting.

So kind of odd that you found a problem in this specific case.

If I do python launchLeo.py leo/test/unitTest.leo ... Alt-4

Leo essentially crashes, there's a lot of 

Trying to create a QVariant instance of QMetaType::Void type, an invalid QVariant will be constructed instead

and no outcome in any reasonable amount of time.

If I do python launchLeo.py --no-plugins leo/test/unitTest.leo ... Alt-4

I get
    
    ERROR: runTest (leo.core.leoTest.GeneralTestCase)
    @test x.makeShadowDirectory
    
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/mnt/usr1/usr1/home/tbrown/t/Package/leo/git/leo-editor/leo/core/leoTest.py", line 211, in runTest
        builtins.execfile(scriptFile, d)
      File "/home/tbrown/.leo/scriptFile.py", line 29, in <module>
        deleteShadowDir(shadow_dir)
      File "/home/tbrown/.leo/scriptFile.py", line 18, in deleteShadowDir
        os.rmdir(shadow_dir)
    OSError: [Errno 39] Directory not empty: '/home/tbrown/.leo/shadow'
    
    ======================================================================
    FAIL: runTest (leo.core.leoTest.EditBodyTestCase)
    EditBodyTestCase: addComments
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/mnt/usr1/usr1/home/tbrown/t/Package/leo/git/leo-editor/leo/core/leoTest.py", line 105, in runTest
        self.editBody()
      File "/mnt/usr1/usr1/home/tbrown/t/Package/leo/git/leo-editor/leo/core/leoTest.py", line 85, in editBody
        compareHeadlines=False), '%s: before undo1' % commandName
    AssertionError: addComments: before undo1
    
    ----------------------------------------------------------------------
    Ran 917 tests in 21.207s
    
    FAILED (failures=1, errors=1, skipped=57)

which doesn't seem too bad :-)

So my impression is that, with the exception of plugins, the unit tests
are quite robust against myLeoSettings.leo.

Cheers -Terry

**Comment by edreamleo** [comment]
On Sun, Nov 26, 2017 at 7:07 PM, Terry Brown <notifications@github.com>
wrote:

> On Sun, 26 Nov 2017 21:55:46 +0000 (UTC)
> "Edward K. Ream" <notifications@github.com> wrote:
>
> > >From the checkin log for 1ff599d
> >
> > Added "Required for reformat-paragraph tests" node to unitTest.leo,
> > containing: ```
> > @int page_width = 80
> > @int tab_width = -4
> > ```
> > This may allow unit tests to be run in more environments.
> >
> > Terry, please report any further problems.
>
> Um, this was never an actual problem for me, just a hypothetical
> problem. I thought unit tests should be run with vanilla
> leoSettings.leo settings rather than modified myLeoSettings.leo, and
> used paragraph reformatting as an example of the kind of situation
> where a naive unit test might fail because the expected outcome
> depended on an assumed page width setting.
>
> So kind of odd that you found a problem in this specific case.
>

​The problem arises, iirc, when running unit tests externally.  However,
running tests externally is not needed for Leo devs now that running unit
tests locally uses the null gui with string widgets.

I'm not going to eliminate the ability to run unit tests externally.  It
may be useful for some Leo users.  My memory is foggy, but I may have done
so when developing external tools.

In any event, it's good to know that we can keep this issue closed.

Edward
