### ISSUE TITLE
Support for org-mode tags on import

### ISSUE THREAD

**Issue by huilen** [leo-editor/leo-editor#578]
Emacs org-mode supports [tags](http://orgmode.org/manual/Tags.html). You can set tags to headlines thus:

* headline 1       :tag1:tag2:tag3:
* headline 2       :tag2:tag4:

Right now, when you import org files to Leo, org tags are being read as part of the headlines, and not as tags. So in this case you will get in Leo two headlines with the following names:

headline 1 :tag1:tag2:tag3:
headline 2 :tag2:tag4:

Since tags are really important in org mode, it would be great if Leo could interpret them properly as Leo tags.

**Comment by edreamleo** [comment]
On Thu, Nov 16, 2017 at 6:49 PM, Huilén <notifications@github.com> wrote:

> Emacs org-mode support tags. You can set tags to headlines thus:
>
>    - headline 1 :tag1:tag2:tag3:
>    - headline 2 :tag2:tag4:
>
> Right now, when you import org files to Leo, org tags are being read as
> part of the headlines, and not as tags. So in this case you will get in Leo
> two headlines with the following names:
>
> headline 1 :tag1:tag2:tag3:
> headline 2 :tag2:tag4:
>
> Since tags are really important in org mode, it would be great if Leo
> could interpret them properly as Leo tags.
>
​Thanks for this.  Better coordination with org-mode always has a high
priority for me.

Edward

**Comment by edreamleo** [comment]
I'm going to call this a bug, and fix it asap.

**Comment by edreamleo** [comment]
@huilen Two questions:

1. I assume that you want org-mode tag to create the kind of tags made by the nodetags plugin.  Is that correct?
2. When the org-mode importer sees an org-mode tag in a headline, should the importer automatically activate the nodetags plugin if necessary?

**Comment by edreamleo** [comment]
@huilen One more question:

3. If I understand correctly, org-mode shows tags in each headline. Do you want the importer to remove tags from headlines? That seems strange.

**Comment by huilen** [comment]
Hello Edward, thank you very much for the rediness!

1. Yes, I'm talking about nodetags plugin. I understand that there is not native Leo feature for this, right?
2. It would be great, but I'm not familiarized with Leo design conventions regarding plugins, maybe you should decide about this.
3. Yes, absolutelly, I think they should be removed from headlines.

**Comment by edreamleo** [comment]
On Mon, Nov 20, 2017 at 6:45 AM, Huilén <notifications@github.com> wrote:

> Hello Edward, thank you very much for the rediness!
>
>    1. Yes, I'm talking about nodetags plugin. I understand that there is
>    not native Leo feature for this, right?
>
> ​Correct. ​


>
>    1. It would be great, but I'm not familiarized with Leo design
>    conventions regarding plugins, maybe you should decide about this.
>
> ​The org-mode importer can easily load the nodetags plugin if necessary.​

>
>    1. Yes, absolutely, I think they should be removed from headlines.
>
> ​I'm surprised.  Does org mode remove tags from headlines?  If not, why
should Leo do so?


Edward

**Comment by tbnorth** [comment]
On Mon, 20 Nov 2017 13:21:46 +0000 (UTC)
"Edward K. Ream" <notifications@github.com> wrote:

> >    1. Yes, absolutely, I think they should be removed from
> > headlines.
> >
> ​I'm surprised.  Does org mode remove tags from headlines?  If not,
> why should Leo do so?

To reduce visual clutter?  Same reason you might want to replace @file
and @clean etc. with icons ;-)

Cheers -Terry

**Comment by edreamleo** [comment]
On Mon, Nov 20, 2017 at 7:37 AM, Terry Brown <notifications@github.com>
wrote:

On Mon, 20 Nov 2017 13:21:46 +0000 (UTC)
> "Edward K. Ream" <notifications@github.com> wrote:
>
> > ​I'm surprised. Does org mode remove tags from headlines? If not,
> > why should Leo do so?
>
> To reduce visual clutter? Same reason you might want to replace @file
> and @clean etc. with icons ;-)
>

​There must be something basic I don't understand.  If you remove the tags
from the headlines, how do you know where the tags were defined?

I'll create a Leo setting for this option in any case.

Edward

**Comment by tbnorth** [comment]
On Mon, 20 Nov 2017 15:51:59 +0000 (UTC)
"Edward K. Ream" <notifications@github.com> wrote:

> On Mon, Nov 20, 2017 at 7:37 AM, Terry Brown
> <notifications@github.com> wrote:
> 
> On Mon, 20 Nov 2017 13:21:46 +0000 (UTC)
> > "Edward K. Ream" <notifications@github.com> wrote:
> >  
> > > ​I'm surprised. Does org mode remove tags from headlines? If not,
> > > why should Leo do so?  
> >
> > To reduce visual clutter? Same reason you might want to replace
> > @file and @clean etc. with icons ;-)
> >  
> 
> ​There must be something basic I don't understand.  If you remove the
> tags from the headlines, how do you know where the tags were defined?
> 
> I'll create a Leo setting for this option in any case.

Tag applies to the node, being in the headline represents that, but
nodetags also associates tags with specific nodes - there's no finer
grain than that, AFAIK.

Cheers -Terry

**Comment by huilen** [comment]
Maybe I'm not understanding something basic neither (I'm new to Leo!), but with removing tags from headlines I meant only the following:

When I have an org file with this content:

* Headline 1 :tag1:tag2:

It should be imported into Leo as:

A node with headline "Headline 1", associated with two tags: "tag1" and "tag2".

(Right now, it is being imported as a node with headline "Headline 1 :tag1:tag2:".)

**Comment by huilen** [comment]
Just a clarification: in org you don't need to declare tags anywhere. You just ser the tags you want to headlines, using the format that I described above.

**Comment by xgid** [comment]
>  **Edward**: ​I'm surprised.  Does org mode remove tags from headlines?  If not, why should Leo do so?

> **Terry**: To reduce visual clutter? Same reason you might want to replace @file and @clean etc. with icons ;-)

I agree with Terry that sometimes you want to reduce visual clutter by removing things from the headlines, but sometimes you want just the opposite, specially for tags (that's me! 😄 ).

The point here is that Emacs org-mode internally treats tags as a metadata which is separate from the headline, but happens to **show** them along the headlines (some "tabs" away or right-aligned). At the same time, org-mode allows you to edit them inline, **just because everything is plain-text in org-mode**. So they can be set using the `org-set-tags-command` (`C-c C-q`) or directly adding an space and a colon followed by the tag(s). This is Org-mode's dual-way in action 😉.

In this regard, this issue is directly related to the discussion we had at issue [#414](https://github.com/leo-editor/leo-editor/issues/414): sometimes there's the need to have metadata shown right/near the headline of a node and to be able to edit it easyly, as in org-mode and others.

> Tag applies to the node, being in the headline represents that, but nodetags also associates tags with specific nodes - there's no finer grain than that, AFAIK. Cheers -Terry

Exactly. You can later use those tags (stored by nodetags in uAs) to reconstruct the org-mode file on export. I think this is the correct approach in this regard. 

So, as a first step, I would just strip the tags out of the headline and store them with nodetags. I would treat the tag's visualization issue as a further enhancement in another issue.

**Comment by edreamleo** [comment]
Imo, the issue of whether to show/hide tags is separate from associating headline tags with uA's.  Here is the first draft of the code to recognize tags, in org_i.clean_headline:
```python
tag_pattern = re.compile(r':([\w_@]+:)+\s*$')

def clean_headline(self, s, p=None):
    '''
    Return a cleaned up headline for p.
    Also parses org-mode tags.
    '''
    trace = True and not g.unitTesting
    # Support for #578: org-mode tags.
    m = self.tag_pattern.search(s)
    if m:
        i = m.start()
        head = s[:i].strip()
        tail = s[i+1:-1].strip()
        tags = tail.split(':')
        if trace: g.trace('head:', head, 'tags:', tags)
    return s
```
The hard part was the regex ;-)  Given the headline: `Section 3 :tag1:tag2:`
the tags array will be ['tag1', 'tag2']. I'll be pushing this code soon.

**Note**: at present the code never changes the headline.  It could strip the headline, depending on a user option.  In that case the writer code would have to restore the tags, using the `:tag:` format.

**Comment by edreamleo** [comment]
On Mon, Nov 20, 2017 at 11:15 AM, XGiD <notifications@github.com> wrote:

> So, as a first step, I would just strip the tags out of the headline and
> store them with nodetags. I would treat the tag's visualization issue as a
> further enhancement in another issue.
>
​The simplest thing that could possibly work is to leave headlines
unchanged, scan for tags, and the uA's​.  This requires no change to the
writer.  That's where I will start.


Edward

**Comment by xgid** [comment]
> The simplest thing that could possibly work is to leave headlines unchanged, scan for tags, and the uA's​.
That's the simplest thing, yes, but I'm not sure that this fits into @huilen's [idea](https://github.com/leo-editor/leo-editor/issues/578#issuecomment-345758899).

**Comment by tbnorth** [comment]
On Mon, 20 Nov 2017 21:36:22 +0000 (UTC)
XGiD <notifications@github.com> wrote:

> > The simplest thing that could possibly work is to leave headlines
> > unchanged, scan for tags, and the uA's​.  
> That's the simplest thing, yes, but I'm not sure that this fits into
> @huilen's
> [idea](https://github.com/leo-editor/leo-editor/issues/578#issuecomment-345758899).

I think this is potentially a good application for the declutter
mechanism.  I thought it was a plugin, but turns out it's not.  Which
makes sense, really.

Search for declutter in leoSettings.py

The headline will be

Some Thing :red:blue:lime:

but it will appear as

Some Thing

until you go to edit it, when it will turn out to be

Some Thing :red:blue:lime:

again.

Of course this doesn't display the tags, except in the status bar at
the bottom that shows you where you are in the outline.

**Comment by edreamleo** [comment]
Rev 9b7395 provides a prototype.  It leaves headlines unchanged and uses the nodetags plugin to set headline tags.  Please give it a try.

**Comment by edreamleo** [comment]
I've deleted the discussions of whether tags should be deleted or not because the org-mode reader and writer both support `@bool org-mode-removes-tags = True`, with the default as shown in leoSettings.leo.

I don't think deleting comments can be undone, and I apologize if I have deleted too much, but I wanted to experiment with pruning lengthy discussions.  Perhaps I should have first marked to-be-deleted comments, so people could have objected ;-)  Let me know if what you think...

**Comment by edreamleo** [comment]
I am going to close this issue.  Please reopen if more work is needed.

As a *separate* issue, the nodetags plugin could be enhanced to report whether a particular tag is set in a node or one of its ancestors.  org-mode "inherits" tags in this manner.  If you think this is important, please file an enhancement request for the nodetags plugin.

**Comment by tbnorth** [comment]
On Tue, 21 Nov 2017 08:43:05 +0000 (UTC)
"Edward K. Ream" <notifications@github.com> wrote:

> I've deleted the discussions of whether tags should be deleted or not
> because the org-mode reader and writer both support `@bool
> org-mode-removes-tags = True`, with the default as shown in
> leoSettings.leo.
> 
> I don't think deleting comments can be undone, and I apologize if I
> have deleted too much, but I wanted to experiment with pruning
> lengthy discussions.  Perhaps I should have first marked
> to-be-deleted comments, so people could have objected ;-)  Let me
> know if what you think...

In general I probably wouldn't delete discussion, at best it's time
consuming busy work to do so, at worst sooner or later someone will be
upset / exasperated by it.

If the desire is to keep issues succinct, what about editing the issue
itself?  I mean the top text - I'm not sure who can do that, I can, so
I assume at least all committers plus the original reporter can, which
is probably the right set.

See https://github.com/tbnorth/leo-dev-tbnorth/issues for a silly
example, it uses

 - [x] to do
 - [ ] items

so summarize things, which gives you the "1 of 3" sub-issue
granularity.  Those check boxes can be checked just by clicking on
them, no need to edit the source.  And it demos a link from top comment
(issue) to lower comment.  The link is made by copy/pasting the url
from the *date* of the target comment.

Maybe no need to edit the original request so much as add the 
"From discussion:" section below it.

My 2c worth.  I'd say in general long discussions on issues don't
bother me, but I can see the need for a concise running summary
somewhere - this is how I'd do it.

Cheers -Terry

**Comment by edreamleo** [comment]
On Tue, Nov 21, 2017 at 8:18 AM, Terry Brown <notifications@github.com>
wrote:

In general I probably wouldn't delete discussion, at best it's time
> consuming busy work to do so, at worst sooner or later someone will be
> upset / exasperated by it.
>

​I think this is a good general policy,​ but I also think that editing
comments, including perhaps merging them, is also sometimes reasonable.

If the desire is to keep issues succinct, what about editing the issue
> itself? I mean the top text


​This is what I typically do.

Edward
