### ISSUE TITLE
Define all commands using a LeoCommand class?

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#581]
Perhaps all command methods should be defined in subclasses of a new LeoCommand class. This class might be decorated with, say,

`@command_class('class name', 'optional_commander_ivar')`

The optional arg would inject the class's command method into the appropriate commanders, This would remove a long-standing hangnail.

The g.command decorator creates most classes, but there are too many behind-the-scenes complications, including g.cmd_instance_dict. The LeoCommand class might hide such details.  Or not.

**Comment by tbnorth** [comment]
On Sun, 19 Nov 2017 12:54:07 +0000 (UTC)
"Edward K. Ream" <notifications@github.com> wrote:

> Perhaps all command methods should be defined in subclasses of a new
> LeoCommand class. This class might be decorated with, say,
> 
> `@command_class('class name', 'optional_commander_ivar')`

`@command_class('*command name*', 'optional_commander_ivar')`?
 
> The optional arg would inject the class's command method into the
> appropriate commanders, This would remove a long-standing hangnail.
> 
> The g.command decorator creates most classes, but there are too many
> behind-the-scenes complications, including g.cmd_instance_dict. The
> LeoCommand class might hide such details.  Or not.

Without understanding it better, I'd vote -1 on this.  If I read
correctly,

```python
g.command('my-command')
def my_command(event):
    event['c'].my_command_handler.do_thing()
```

becomes

```python
g.command_class('my-command')
class MyCommandClass(LeoCommand):
    def command(event):
        event['c'].my_command_handler.do_thing()
```

If the class's only member is command() I can't see a need for the class.

If optional_commander_ivar causes command() to become an instance method
of c.getattr(optional_commander_ivar), well, I guess that could be neat,
but I'm not sure that's what you meant, and still don't see a need for
the class.

**Comment by edreamleo** [comment]
On Sun, Nov 19, 2017 at 10:48 AM, Terry Brown <notifications@github.com>
wrote:

Without understanding it better, I'd vote -1 on this.


​Your comments are well taken.  Let me play around with

​g.command_class('my-command')
class ​class MyCommandClass(LeoCommand):
   ...

to see if there is *any* advantage in this pattern.

Alternatively, perhaps the g.command decorator can be hacked to allow
automatic injection of the defined command into the commands class.  This
is what I really want to do, and I am prepared for even some additional
behind-the-scenes complications to make it happen.

Edward

**Comment by edreamleo** [comment]
I am going to close this issue.  At was a bad idea.  Furthermore, #589 accomplishes even more, and more simply.
