### ISSUE TITLE
css syntax coloring (@language css)

### ISSUE THREAD

**Issue by boltex** [leo-editor/leo-editor#585]
wrong/inconsistent syntax coloring. Classes, starting with a dot, are not recognised and spaces are not allowed it seems. see screenshot below.

![image](https://user-images.githubusercontent.com/847716/32993926-90558bd2-cd2d-11e7-8bc1-2cf5c44279d6.png)

**Comment by edreamleo** [comment]
This is an interesting one.  ':' appears at the start of some css keywords, but a trailing ':' suppresses coloring of most keywords.

**Comment by edreamleo** [comment]
Rev adds some new rules and allows spaces before selectors.

Please report any further problems.
