### ISSUE TITLE
Dynamic display of node attributes

### ISSUE THREAD

**Issue by technatica** [leo-editor/leo-editor#587]
The current discussions about tagging and org mode spurred an idea.

Where to display tagging information: Would it not make sense to create a body "headline" to display the current nodes path in the outline, along with tags? I envision a title bar just above the body (and the actual title bar on a floating editor window) that contains the path "File.db#RootNode-->Node-->Node Tag1 Tag2".

This would remove the clutter from the headline while providing a visual cue to the user.

**Comment by tbnorth** [comment]
Heh, thoughts along these lines came up recently, from Xavier, and to
keep track I started this: https://github.com/orgs/leo-editor/projects/2
which it just took me 10 minutes to find :-}

I think the general idea is to show indicators of a nodes attributes (whether defined in uA or hidden in a decluttered headline or whatever) in some dynamic way that doesn't require switching tabs etc.  So tags in a headline, maybe more things in the tree etc.  There's also the status line.

XGiD's comments here:
https://github.com/leo-editor/leo-editor/issues/414#issuecomment-339731105

Additional gleanings - icons in tree pane launch relevant uA editing pane, command to cycle relevant editing panes, reveal relevant editing panes as a kind of drawer / dialog thing.

**Comment by edreamleo** [comment]
On Tue, Nov 21, 2017 at 10:21 AM, Chris George <notifications@github.com>
wrote:

I envision a title bar just above the body (and the actual title bar on a
> floating editor window) that contains the path
> "File.db#RootNode-->Node-->Node Tag1 Tag2".

​
That's exactly what is shown at the bottom of the Leo outline window.

Edward

**Comment by technatica** [comment]
Hmmm, mine doesn't display the tags.

Chris

**Comment by edreamleo** [comment]
On Tue, Nov 21, 2017 at 11:00 AM, Edward K. Ream <edreamleo@gmail.com>
wrote:

> On Tue, Nov 21, 2017 at 10:21 AM, Chris George <notifications@github.com>
> wrote:
>
> I envision a title bar just above the body (and the actual title bar on a
>> floating editor window) that contains the path "File.db#RootNode-->Node-->Node
>> Tag1 Tag2".
>
> ​
> That's exactly what is shown at the bottom of the Leo outline window.
>

​> ...mine doesn't display the tags.​

​This conversation is really messed up.  I didn't see your recent comment
in my email, but anyway...

Please pull the most recent revs.  The status line should display the tags
because they won't be deleted.  This should be true regardless of your
declutter settings.

Edward

**Comment by technatica** [comment]
Leo 5.6, build 20171121022137, Tue Nov 21 02:21:37 CST 2017
Git repo info: branch = master, commit = 6a5f13b6d4c0
Python 3.6.3, PyQt version 5.6.2
linux
isPython3: True
caching enabled


The status line displays the path, the file, the RootNode, and the node,
but does not display the tags.


Chris

**Comment by edreamleo** [comment]
> Git repo info: branch = master, commit = 6a5f13b

This commit is out of date.  Please pull 370c82420, 2017-11-21 11:18:15

I am going to close this issue.  Leo's present behavior is as requested.

**Comment by tbnorth** [comment]
I didn't really intend this issue to be solely limited to the display of headline tags - well, it was Chris's issue, but his ideas seemed to tie with Xavier's ideas re the need for displaying auxiliary info. about nodes more dynamically than having to have all the relevant panes (tags, todo, attrib_edit, drawers?) open and laid out all the time.  I'll transfer these thoughts to a new issue. (#588, I predict ;-)

**Comment by technatica** [comment]
Do you have any ideas what I could try next to get it to work for me? This
is a brand new install of Leo. Like I deleted my leo-editor folder and
cloned fresh code from github.

Leo 5.6, build 20171121142505, Tue Nov 21 14:25:05 CST 2017
Git repo info: branch = master, commit = 444760ff6c80
Python 3.6.3, PyQt version 5.6.2
linux
isPython3: True
caching enabled



​

Chris

**Comment by tbnorth** [comment]
On Tue, 21 Nov 2017 21:43:55 +0000 (UTC)
Chris George <notifications@github.com> wrote:

> Do you have any ideas what I could try next to get it to work for me?
> This is a brand new install of Leo. Like I deleted my leo-editor
> folder and cloned fresh code from github.

Are we all talking about the same thing?

Edward observes that org. mode tags in a headline:

To Do
  Cleaner headlines :enhancement:ms5.7:gui:

can be hidden (in the tree) by the declutter code, but will be
displayed in the status line, at the bottom of the Leo window, as

/mnt/edata/edata/edata.leo#To Do-->Cleaner headlines :enhancement:ms5.7:gui:

this only applies to the :blah: org. mode tags in headlines, it doesn't
have any bearing on tags displayed by the nodetags plugin.

Same page?

Cheers -Terry

> Leo 5.6, build 20171121142505, Tue Nov 21 14:25:05 CST 2017
> Git repo info: branch = master, commit = 444760ff6c80
> Python 3.6.3, PyQt version 5.6.2
> linux
> isPython3: True
> caching enabled
> 
> ​
> 
> Chris
> 
> On Tue, Nov 21, 2017 at 12:19 PM, Terry Brown

**Comment by technatica** [comment]
Oh.

Exactly the problem. I was using the nodetags plugin as I don't use
org-mode. I created the issue as an enhancement request pointed at
nodetags.py and wondered if I had missed something.

Chris

**Comment by tbnorth** [comment]
On Tue, 21 Nov 2017 22:42:37 +0000 (UTC)
Chris George <notifications@github.com> wrote:

> Exactly the problem. I was using the nodetags plugin as I don't use
> org-mode. I created the issue as an enhancement request pointed at
> nodetags.py and wondered if I had missed something.

I'd consider some additional less screen consumptive display of nodetag
nodes part of the ideas in #588, so not off the table.

**Comment by edreamleo** [comment]
On Tue, Nov 21, 2017 at 4:29 PM, Terry Brown <notifications@github.com>
wrote:

Are we all talking about the same thing?
>

​At last I understand.  The status line could show tags other than org-mode
tags. Apologies for my confusion.

Edward

**Comment by edreamleo** [comment]
I am going to mark this item "Won'tDo".  Please create a *new* issue, with a short summary of this thread, if you think more work is required.  Thanks.

**Comment by tbnorth** [comment]
This issue is referenced by #588, so I think there's a path back to these ideas should anyone feel they're being lost.

**Comment by edreamleo** [comment]
On Thu, Jan 25, 2018 at 8:53 AM, Terry Brown <notifications@github.com>
wrote:

> This issue is referenced by #588
> <https://github.com/leo-editor/leo-editor/issues/588>, so I think there's
> a path back to these ideas should anyone feel they're being lost.
>
​Thanks for this.  I wasn't sure myself whether I should have closed 587.

Edward

**Comment by tbnorth** [comment]
On Thu, 25 Jan 2018 09:11:42 -0800
"Edward K. Ream" <notifications@github.com> wrote:

> On Thu, Jan 25, 2018 at 8:53 AM, Terry Brown
> <notifications@github.com> wrote:
> 
> > This issue is referenced by #588
> > <https://github.com/leo-editor/leo-editor/issues/588>, so I think
> > there's a path back to these ideas should anyone feel they're being
> > lost. 
> ​Thanks for this.  I wasn't sure myself whether I should have closed
> 587.
> 
> Edward

It's tricky using issues to track more than bugs, it's hard to be
comfortable with a high open count, but I think we have to be.
Interesting that github has an is:issue filter, not really clear what
else could be there.  It would be nice to have a top level split of
"issues" (bugs etc.), and other things like sub-projects and proposals
and enhancements.

The label system is sufficient to represent any scheme, but the 'open'
count is a psychological burden - we know that only issues with the
'bug' label are "negative", but we don't know that people browsing the
issues list casually know that.

The only thing we can do that I can think of would be to create
separate repo.s just to get separate issue lists for non-bug items.
But that seems far from ideal, having to re-file all the time, not to
mention looking in more than one place.  So, we just have to remember
it's good to be open :-}

Cheers -Terry

**Comment by edreamleo** [comment]
On Thu, Jan 25, 2018 at 11:26 AM, Terry Brown <notifications@github.com>
wrote:

It's tricky using issues to track more than bugs, it's hard to be
> comfortable with a high open count, but I think we have to be.
>

​I now have a labeling system that works well for me. It is comforting
rather than stressful.  I have tried to describe it recently, but
apparently the gist hasn't come through.

I don't much care how many enhancement requests, although in fact ​the
"is:issue is:open label:Enhancement" filter shows there are only 48
<https://github.com/leo-editor/leo-editor/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3AEnhancement+>
.

I further narrow these down using the First and EKR labels.  I start from
one of several *bookmarked filters*:

My *work list for 5.7b1*:
is:issue is:open milestone:5.7

My *overall to-do list*:
is:issue is:open label:EKR -label:info -label:BackBurner
-label:Can'tFix -label:Waiting -label:Can'tDo -label:lvl:minor

These
*suppressor labels* (BackBurner, Can'tFix, Waiting, Can'tDo, info,
lvl:minor ​
​) suffice to limit what I see.
Bookmarking them is the key psychological trick.

From the second list I can just click any "First" label to get the next
items I am considering.

Interesting that github has an is:issue filter, not really clear what
> else could be there.


​Apparently pull requests can also be filtered.
​


> It would be nice to have a top level split of
> "issues" (bugs etc.), and other things like sub-projects and proposals
> and enhancements.
>

​The workflow described above does this effortlessly.​


The label system is sufficient to represent any scheme, but the 'open'
> count is a psychological burden - we know that only issues with the
> 'bug' label are "negative", but we don't know that people browsing the
> issues list casually know that.
>

​I'm not worried about the bug count at all.  Indeed, starting from my
bookmarked overall todo list and changing label:Enhancement to label:Bug
yields exactly one bug
<https://github.com/leo-editor/leo-editor/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3ABug+-label%3Ainfo+-label%3ABackBurner+-label%3ACan%27tFix+-label%3AWaiting+-label%3ACan%27tDo+-label%3Alvl%3Aminor+>.
Sure, we would like to clean this up, but it's not affecting many people.


> The only thing we can do that I can think of would be to create
> separate repo.s just to get separate issue lists for non-bug items.
> But that seems far from ideal, having to re-file all the time, not to
> mention looking in more than one place. So, we just have to remember
> it's good to be open :-}
>

​Not needed.  The labels I have just described suffice.

I attach Won'tDo and Won'tFix labels to *closed* items.  There aren't many
of these, but they are spread over many years.  These labels allows
somebody to revisit these potentially controversial items effortlessly.

The Help labels denote items that are neither Bugs nor Enhancements, but
just questions.

*Summary*: I don't use any other labels except those described here. Imo,
these should suffice for a long, long time.

Edward

**Comment by tbnorth** [comment]
Sounds good. I had perhaps interpreted a couple of recent closures as a desire to push down the open count. For example I made a note for myself to fix #37.

Cheers - Terry 

On January 25, 2018 5:35:42 PM CST, "Edward K. Ream" <notifications@github.com> wrote:
>On Thu, Jan 25, 2018 at 11:26 AM, Terry Brown
><notifications@github.com>
>wrote:
>
>It's tricky using issues to track more than bugs, it's hard to be
>> comfortable with a high open count, but I think we have to be.
>>
>
>​I now have a labeling system that works well for me. It is comforting
>rather than stressful.  I have tried to describe it recently, but
>apparently the gist hasn't come through.
>
>I don't much care how many enhancement requests, although in fact ​the
>"is:issue is:open label:Enhancement" filter shows there are only 48
><https://github.com/leo-editor/leo-editor/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3AEnhancement+>
>.
>
>I further narrow these down using the First and EKR labels.  I start
>from
>one of several *bookmarked filters*:
>
>My *work list for 5.7b1*:
>is:issue is:open milestone:5.7
>
>My *overall to-do list*:
>is:issue is:open label:EKR -label:info -label:BackBurner
>-label:Can'tFix -label:Waiting -label:Can'tDo -label:lvl:minor
>
>These
>*suppressor labels* (BackBurner, Can'tFix, Waiting, Can'tDo, info,
>lvl:minor ​
>​) suffice to limit what I see.
>Bookmarking them is the key psychological trick.
>
>From the second list I can just click any "First" label to get the next
>items I am considering.
>
>Interesting that github has an is:issue filter, not really clear what
>> else could be there.
>
>
>​Apparently pull requests can also be filtered.
>​
>
>
>> It would be nice to have a top level split of
>> "issues" (bugs etc.), and other things like sub-projects and
>proposals
>> and enhancements.
>>
>
>​The workflow described above does this effortlessly.​
>
>
>The label system is sufficient to represent any scheme, but the 'open'
>> count is a psychological burden - we know that only issues with the
>> 'bug' label are "negative", but we don't know that people browsing
>the
>> issues list casually know that.
>>
>
>​I'm not worried about the bug count at all.  Indeed, starting from my
>bookmarked overall todo list and changing label:Enhancement to
>label:Bug
>yields exactly one bug
><https://github.com/leo-editor/leo-editor/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3ABug+-label%3Ainfo+-label%3ABackBurner+-label%3ACan%27tFix+-label%3AWaiting+-label%3ACan%27tDo+-label%3Alvl%3Aminor+>.
>Sure, we would like to clean this up, but it's not affecting many
>people.
>
>
>> The only thing we can do that I can think of would be to create
>> separate repo.s just to get separate issue lists for non-bug items.
>> But that seems far from ideal, having to re-file all the time, not to
>> mention looking in more than one place. So, we just have to remember
>> it's good to be open :-}
>>
>
>​Not needed.  The labels I have just described suffice.
>
>I attach Won'tDo and Won'tFix labels to *closed* items.  There aren't
>many
>of these, but they are spread over many years.  These labels allows
>somebody to revisit these potentially controversial items effortlessly.
>
>The Help labels denote items that are neither Bugs nor Enhancements,
>but
>just questions.
>
>*Summary*: I don't use any other labels except those described here.
>Imo,
>these should suffice for a long, long time.
>
>Edward
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/leo-editor/leo-editor/issues/587#issuecomment-360636764

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by edreamleo** [comment]
On Thu, Jan 25, 2018 at 7:13 PM, Terry Brown <notifications@github.com>
wrote:

Sounds good. I had perhaps interpreted a couple of recent closures as a
> desire to push down the open count.

​
My primary motivation is to do the most important items first.  From time
to time I also want to step back and consider the bigger picture.
​

> For example I made a note for myself to fix #37.
>

​Thanks!

Edward
