### ISSUE TITLE
Make node attributes visible, with support in Leo's core

### ISSUE THREAD

**Issue by tbnorth** [leo-editor/leo-editor#588]
Leo should show nodes attributes (whether defined in uA or hidden in a decluttered headline or whatever) in some dynamic way that doesn't require switching tabs, laying out panes, etc. So tags in a headline, maybe more things in the tree etc. There's also the status line.

EKR's summary: Make node attributes visible, and supported by Leo's core.

[XGiD's comments](https://github.com/leo-editor/leo-editor/issues/414#issuecomment-339731105)

Chris's idea in #587 could also be relevant, in some sort of integrated display.

Additional gleanings - icons in tree pane launch relevant uA editing pane, command to cycle relevant editing panes, reveal relevant editing panes as a kind of drawer / dialog thing.

**Comment by edreamleo** [comment]
On Tue, Nov 21, 2017 at 10:41 AM, Terry Brown <notifications@github.com>
wrote:

> #414 (comment)
> <https://github.com/leo-editor/leo-editor/issues/414#issuecomment-339731105>
>
​This is a bit too short.  I have no idea what you are talking about ;-)​

Edward

**Comment by edreamleo** [comment]
Clones are an important part of Leo's DOM, but many people are uncomfortable with them.  I use cff to create *temporary* views.

Many people find tags to be more intuitive, flexible and permanent.  `@rst` should probably support abstracting pieces of code using tags.

It would be natural to show tags in the info area, optionally, instead of UNL's.

**Comment by edreamleo** [comment]
I personally am not going to do this, for the following reasons:

1. Tags are just not good enough. The user can simply insert their own markers as needed, like tag: whatever, or :whatever:, or anything else.

2. Putting tags in headlines is kinda pointless.  They are distracting, and too long.  Decluttering them hides them too much.

3. It would be possible to show tags in a status area, possibly even a dedicated status area, but that would make them *almost* invisible.

4. cff is just a much much better way.

Having said this, I won't stand in the way of somebody doing something along these lines.  Please make it optional if it has a major visual impact.
