### ISSUE TITLE
Beginner on linux... Label: help wanted

### ISSUE THREAD

**Issue by brobr** [leo-editor/leo-editor#592]
Hi,
I have been installing leo in python2.7/site-packages/ on linux Slackware using a build script from SlackBuilds.org that uses leo/dist/setup.py. 

This works and leo is fine to use as a planner/organizer etc and in that respect it feels as a very powerful tool which I would like to learn as good as possible. I also would like to use leo with python programming. But I seem to run into problems and some annoyances. Mostly because some basic concepts of how the program operates with respect to its settings I found baffling. Below some observations/annoyances... Hope they help to improve the program (to beginners)

1) during the install the 'test' and 'extensions' are not ending up in the python/site_packages/leo folder with the result that pylint won't work by lack of a config. Guided by the error messages I copied this from leo/test from the source and edited the name to pylint-leo-rc.txt which, in the end I put in ~/.leo. That worked.

2) menu items that are not for, or not working in linux:
'Open with -> Idle' calls a windows-specific path and executable and -thus- does not do a thing on linux
'Open  with -> Word/Wordpad ' is not relevant at all

3) contextual menu 'Edit with gedit', which can only be relevant when gedit is on the system. I could not find a way to change this to e.g. vim, gvim, nano, geany, or spyder. 

Possibly these observations are supposed to be repaired by changing the @settings; but how? At the moment I get lost in all the nodes and where/how to apply changes or how to get this properly translated into myLeoSettings.leo without copying the lot (which I understand is not advised/needed; correct me if I am wrong) to make these permanent. 

4) going through leoSettings/Plugins/ I found Inkscape options, but again with a windows-specific path/executable: '@string inkscape-bin = "c:\Program Files (x86)\Inkscape\inkscape.exe"'. In the program itself I could not find any plugin-reference to inkscape, so this did not support my understanding of how leo operates. I would love to link inkscape files to related nodes in my work-overview-leo file, but how?

As adapting the paths to executables and menu items would be needed for every linux user is it not feasible to include a linux-friendly 'myLeoLinuxSettings.leo' file that provides at least an example for this? 

I found an exampleSettings.leo hidden in the leo/config folder (it's not in the menu of 'File/Open Leo File) but this did not help to understand how to repair unwanted (contextual) menu-items.

In the end I could change the Open-with menu with a diff before compilation of leo 5.6:
[Leo-linuxmenu-diff.txt](https://github.com/leo-editor/leo-editor/files/1503353/Leo-linuxmenu-diff.txt)

At least I got rid of Word and the 'Open File with Idle' working but is it normal that two idle windows open, one with the script behind the menu-item and one with the file one wants to apply this to??? Or did my diff introduced this as an artefact??

PS how can you get the label properly displayed???

**Comment by edreamleo** [comment]
On Sat, Nov 25, 2017 at 2:21 PM, brobr <notifications@github.com> wrote:

​> ​
I have been installing leo in python2.7/site-packages/ on linux Slackware
using a build script from SlackBuilds.org that uses leo/dist/setup.py.

​There has been recent work re setup.py.

See https://groups.google.com/forum/#!topic/leo-editor/cb3olsXP9tQ
I'm not sure whether this applies to you.

In the past (not sure about now) setup.py has confused people mightily.  If
you have installation problems, you can install Leo from sources, as
described here
<http://leoeditor.com/installing.html#installing-from-sources-linux>.

> I seem to run into problems and some annoyances.
> [snip]
>
> ​
> Hope they help to improve the program (to beginners)
>
>
>    1.
>
>    during the install the 'test' and 'extensions' are not ending up in
>    the python/site_packages/leo folder with the result that pylint won't work
>    by lack of a config. Guided by the error messages I copied this from
>    leo/test from the source and edited the name to pylint-leo-rc.txt which, in
>    the end I put in ~/.leo. That worked.
>
> ​See the above comments about installation.  I'm not sure they are a
complete response.​


>
>    1. menu items that are not for, or not working in linux:
>
>    'Open with -> Idle' calls a windows-specific path and executable and
>    -thus- does not do a thing on linux
>    'Open with -> Word/Wordpad ' is not relevant at all
>    2.
>
>    contextual menu 'Edit with gedit', which can only be relevant when
>    gedit is on the system. I could not find a way to change this to e.g. vim,
>    gvim, nano, geany, or spyder.
>
> ​The default settings apply to Windows, as you say.  You can change them
by copying the tree:


leoSettings.leo#@settings-->Menus-->Open With menu

to myLeoSettings.leo and making the appropriate changes.​


​> Possibly these observations are supposed to be repaired by changing the
@settings; but how? At the moment I get lost in all the nodes and where/how
to apply changes or how to get this properly translated into
myLeoSettings.leo without copying the lot (which I understand is not
advised/needed; correct me if I am wrong) to make these permanent.​

No, you *should* copy settings to myLeoSettings.leo.  That way they will
permanently override settings in leoSettings.leo, even if leoSettings.leo
changes in a later release.

>
>    1. going through leoSettings/Plugins/ I found Inkscape options, but
>    again with a windows-specific path/executable: '@string
>    <https://github.com/string> inkscape-bin = "c:\Program Files
>    (x86)\Inkscape\inkscape.exe"'. In the program itself I could not find any
>    plugin-reference to inkscape, so this did not support my understanding of
>    how leo operates. I would love to link inkscape files to related nodes in
>    my work-overview-leo file, but how?
>
> ​Again, copy the appropriate settings to your myLeoSettings.leo.


>
> As adapting the paths to executables and menu items would be needed for
> every linux user is it not feasible to include a linux-friendly
> 'myLeoLinuxSettings.leo' file that provides at least an example for this?
>
​An excellent idea.  ​I have just created #596
<https://github.com/leo-editor/leo-editor/issues/596> for this.


Thanks for your comments.  Please feel free to ask more questions.


Edward

**Comment by edreamleo** [comment]
I'm going to close this issue now.  If you have more questions, please ask on the [leo-editor forum](https://groups.google.com/forum/#!forum/leo-editor): That way more people will see the discussion.
