### ISSUE TITLE
File --> RecentFiles can not work

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#593]
After git pull to Leo 5.6, build 20171125153313, Sat Nov 25 15:33:13 CST 2017

File --> RecentFiles can not work. Showing in log panel:

Leo Log Window
Leo 5.6, build 20171125153313, Sat Nov 25 15:33:13 CST 2017
Git repo info: branch = master, commit = 5ce3ec801895
Python 2.7.12, PyQt version 4.8.7
linux2
isPython3: False
caching enabled
redefining abbreviation ,, 
from u"{|{x='__NEXT_PLACEHOLDER'}|}" to u'__NEXT_PLACEHOLDER'
reading: @edit XService
**can not open @edit /home/swot/pyenv/Xservice/XService**

**Comment by LewisNeal** [comment]
Confirm same problem with python3. File --> RecentFiles some_file.leo.
A new file opens called leo-editor:

Leo Log Window
Leo 5.6, build 20171125185314, Sat Nov 25 18:53:14 CST 2017
Git repo info: branch = master, commit = e7c3abd69d4a
Python 3.6.3, PyQt version 5.9.2
Windows 10 AMD64 (build 10.0.15063) SP0
isPython3: True
caching enabled
reading: @edit leo-editor
can not open @edit N:\git\leo-editor

**Comment by edreamleo** [comment]
Thanks for this report.  Rev [bf7e454](https://github.com/leo-editor/leo-editor/commit/bf7e45418bee0d53a78c17533a70eeb322cdc81c) fixes the bug, and improves the error reporting so that the confusing message:
```
can not open @edit N:\git\leo-editor
```
would become something like:
```
readFileIntoString: not a file: N:\git\leo-editor
readFileIntoString: <list of calling methods>
```

**Comment by wangzhaohe** [comment]
Bug fixed! Thanks a lot!!!

**Comment by edreamleo** [comment]
On Sun, Nov 26, 2017 at 5:13 PM, wangzhaohe <notifications@github.com>
wrote:

> Bug fixed! Thanks a lot!!!
>
​You're welcome.


Edward
