### ISSUE TITLE
The dark theme is broken on Windows

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#595]
Enabling the subtree `@theme windows ekr dark` in leoSettings.leo look horrible.

**Comment by tbnorth** [comment]
Attached [darkleo.leo.zip](https://github.com/leo-editor/leo-editor/files/1504154/darkleo.leo.zip) as a workaround, unzip, copy node, paste at end of @settings.

**Comment by edreamleo** [comment]
I am going to close this.  Here are some tips, from a recent email:

Initially, [Terry's theme] didn't work for me, but it was a good clue.

I moved various theme-related tress to before the `@settings` tree, ensuring that they could not possibly affect settings.  After doing that, both Terry's theme, `@theme leo_dark theme 0`, and mine, `@theme windows ekr dark theme`, worked.

In short: to completely disable settings, *move them in front of the @settings node*.
