### ISSUE TITLE
Use @ifplatform to create platform-specific settings in leoSettings.leo

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#596]
Leo could load settings in the following order, with later settings overriding previous:

- leoSettings.leo
- LinuxSettings.leo, WindowsSettings.leo or MacSettings.leo, depending on platform.
- myLeoSettings.leo.

Suggested by #592.

Alas, this would slow down startup.  Perhaps it would suffice to have example settings to be moved to myLeoSettings.leo.

**Comment by brobr** [comment]
Hi, thanks for this and the original reply, that helped. I have now a standard leo install with mySettings putting the linux-specific bits in place. The File/Open With Idle/ node reads now:
> 
> ext:    .py
> kind:   subprocess.Popen
> arg:    idle
> arg:	"/usr/lib64/python2.7/idlelib/idle.pyw"
> #arg:    "%PYTHONHOME%/idlelib/idle.pyw"

But that's with python2.7 as home on a x86_64 system and not usable for python3 users or those on 32bit; ideally these settings would be found by scripts that find the correct path during install. 

Maybe that's too complicated and could be done by the user by means of some scripts/@buttons in -say- a buildMyLeoSettings file/node which would be part of the workbook that opens up on each run. This would possibly keep it more manageable than providing these settings for all possible set-ups.....

I found the quickstart-node instruction about setting the contextual editor using the .bashrc which works fine. But is this not something that should be set using an @settings instruction to provide a consistent leo-ui? Or is that also quite cumbersome to do?? Or could this be addressed in the same manner as @settings gets changed depending on os/python-version?

Oh, something I should have started with, thanks for the awesome program; it helps me to keep better track of what I am up to at work ;-)

**Comment by edreamleo** [comment]
On Sun, Nov 26, 2017 at 4:25 PM, brobr <notifications@github.com> wrote:

> Hi, thanks for this and the original reply, that helped. I have now a
> standard leo install with mySettings putting the linux-specific bits in
> place. The File/Open With Idle/ node reads now:
>
> ext: .py
> kind: subprocess.Popen
> arg: idle
> arg: "/usr/lib64/python2.7/idlelib/idle.pyw"
> #arg: "%PYTHONHOME%/idlelib/idle.pyw"
>
> But that's with python2.7 as home on a x86_64 system and not usable for
> python3 users or those on 32bit; ideally these settings would be found by
> scripts that find the correct path during install.
>
​Much easier said than done. For example, one installation technique is
simply to unpack the leo folder and place it somewhere. There are a number
of other ways to install Leo, including git clone, and all would have to be
aware of the script.  ​

> Maybe that's too complicated and could be done by the user by means of
> some scripts/@buttons <https://github.com/buttons> in -say- a
> buildMyLeoSettings file/node which would be part of the workbook that opens
> up on each run. This would possibly keep it more manageable than providing
> these settings for all possible set-ups.....
>
​
I like this idea.  Btw, the workbook opens when the user specifies no other
file on the command line.  ​


> I found the quickstart-node instruction about setting the contextual
> editor using the .bashrc which works fine. But is this not something that
> should be set using an @settings instruction to provide a consistent
> leo-ui? Or is that also quite cumbersome to do?? Or could this be addressed
> in the same manner as @settings gets changed depending on os/python-version?
>
​Again, a button in the workbook should work.​


​I have just changed the name of this item to "Use buttons in workbook.leo
to create platform-specific settings in myLeoSettings.leo".​

> Oh, something I should have started with, thanks for the awesome program;
> it helps me to keep better track of what I am up to at work ;-)
>
​Glad to hear it.  Welcome aboard.


Edward

**Comment by vitalije** [comment]
IIRC in Leo settings syntax there is a way to make some settings conditional (`@if` nodes). Those platform and/or architectural dependent settings should be defined in leoSettings.leo using this `@if` nodes for every platform/architecture to some reasonable defaults. That way, more of settings would work out of box, and new users would have less to tweak those settings.

I know that is impossible to make those settings to work for every computer, but if such Windows specific paths are already in leoSettings.leo then I don't see why Linux paths should not be defined also.

**Comment by edreamleo** [comment]
On Mon, Nov 27, 2017 at 8:21 AM, Виталије Милошевић <
notifications@github.com> wrote:

> IIRC in Leo settings syntax there is a way to make some settings
> conditional (@if nodes).
>
​@ifplatform and ​@ifhostname are documented.

If these work as advertised they will be the easy way of resolving this
issue.

Thanks for the reminder!

Edward

**Comment by edreamleo** [comment]
Rev 22099fb and earlier revs appear to complete this project.

Please reopen if problems appear.
