### ISSUE TITLE
Show tips when Leo starts up

### ISSUE THREAD

**Issue by vitalije** [leo-editor/leo-editor#597]
[Vitalije's initial post](https://groups.google.com/forum/#!searchin/leo-editor/vitalije%7Csort:date/leo-editor/zakK-j8f7mU/g_vmFzlLAwAJ). The [tips branch](https://github.com/leo-editor/leo-editor/tree/tips).

On every start Leo would show a dialog giving some useful tip on some not so obvious editor functions, shortcuts, best practices... Even Leo's core devs don't know all of them.

**To create a tip**

- Create a new issue here, in Leo's issue tracker, with the "Tip" label.
  Tips should contain one or more tags in the opening comment of the issue.
  **Do not create an issue label for each tag!**  Just mention the tags the tip should have.
- Any user can suggest a new tip by adding an issue.
- We can close each tip issue when it has been approved (added to the code that displays tips) or rejected.

The Tip label marks all existing tips.

**To do**
- [x] Write the code to display tips on startup.
- [x] Settings to specify the tags to be shown on startup.
- [x] Generalize settings code to allow the user to set any setting.

**Not likely**
- [ ] Convert markdown tips in these tips to some other form.
- [ ] Allow users to rate each tip: 1 to 5 stars.
- [ ] (Maybe) Show highly-rated useful tips more often.

**Comment by edreamleo** [comment]
Following [Terry's lead](https://github.com/leo-editor/snippets/blob/master/scripts/misc/get_tips.py) here is revised code, in `@button get-tips` in LeoDocs.leo,  It shows both open and closed tips, and includes each tip's issue number. It also strips off confusing '[]' cruft.

```python
@language python

"""
get_tips.py - download current tips from GitHub
NOTE: if the list of tips gets long enough, GitHub may stop serving them
all in a single request, and serve them page by page - not hard to
handle if it happens.
Terry Brown, terrynbrown@gmail.com, Thu Dec  7 09:10:54 2017
"""

from collections import namedtuple
import requests
Tip = namedtuple('Tip', 'number title tip tags')
base_url = 'https://api.github.com/repos/leo-editor/leo-editor/issues?labels=Tip&state='

def get_tips(data):
    """get_tips - get tips from GitHub issues
    :param dict data: GitHub API issues list
    :return: list of Tips
    """
    tips = []
    for issue in data:
        if '\n' in issue['body']:
            tip, tags = issue['body'].strip().rsplit('\n', 1)
        else:
            tip, tags = issue['body'].strip(), ''
        if tags.lower().startswith('tags:'):
            tags = [i.strip().strip('.') for i in tags[5:].split(',')]
        else:
            tags = []
            tip = "%s\n%s" % (tip, tags)
        if isinstance(tip, (tuple, list)):
            tip = (z for z in tip if z and z.strip())
        tips.append(Tip(issue['number'], issue['title'], tip, tags))
    return tips

def main():
    g.cls()
    for kind in 'open', 'closed':
        URL = base_url+kind
        data = requests.get(URL).json()
        for tip in get_tips(data):
            print('%s %s tip #%s %s...' % (('-'*10), kind, tip.number, tip.title))
            print('')
            print("TAGS: %s" % tip.tags or "**NO TAGS**")
            print('')
            print(tip.tip.strip().strip('[]').strip())
            print('')

if __name__ == '__main__':
    main()
```

**Comment by edreamleo** [comment]
I am going to remove the "Tip" label from this item, because this item is not itself a tip.  This will make it easier to see this item while suppressing actual tips.

**Comment by edreamleo** [comment]
I am going to close this item.  I plan no further work on it.
