### ISSUE TITLE
Enhancement Request: Spell Check - Add ability to modify dictionary

### ISSUE THREAD

**Issue by technatica** [leo-editor/leo-editor#602]
I would like to be able to have the spellchecker add words to the dictionary as one of the options when it comes across an unknown word.

For example: I use a lot of URLs in my weekly column for a local media outlet. While spellchecking an article, I end up having to click past http, www, etc. etc. numerous times in the spellchecker. I would like to be able to add these common bits of jargon to the dictionary so I am not constantly prompted to do something about them when running the spellchecker.

When writing fiction, the ability to add jargon and created words on the fly would also be a huge help. Right now I am hacking the dictionary outside of Leo (when I remember to) and it would be way convenient to do it "inhouse".

Pyenchant includes this functionality.

**Comment by edreamleo** [comment]
The "add" button in the find tab does this. Rev 5dace4d adds the spell-add command.
