### ISSUE TITLE
Missing files when installing Leo from PyPI using "pip install leo"

### ISSUE THREAD

**Issue by ranvik14** [leo-editor/leo-editor#603]
After installing Leo with `pip` there may be some warning messages in the log pane window when opening certain .leo files distributed with Leo. (_File >> Open Leo File >> ..._)

*LeoDocs.leo:*

    Leo Log Window
    Leo 5.6, build 20171129062306, Wed Nov 29 06:23:05 CST 2017
    Not running from a git repo
    ...snip...
    reading: C:\users\viktor\leo-57-usr\lib\site-packages\leo\doc\LeoDocs.leo
    reading: @edit conf.py
    file not found: C:\users\viktor\leo-57-usr\lib\site-packages\leo\doc\html\conf.py
    can not open: '@file C:\users\viktor\leo-57-usr\lib\site-packages\leo\doc\html\index.html'

This is a known issue, but yet to be documented up front where people see it. Basically anything in the root folder of the leo-editor code repository is not installed when using pip. This is because they need to be relative to `./leo-editor/leo` folder, which make them at the top of `./site-packages`, and thus in the global namespace and not part of leo (as far as python is concerned).

Before (source code repository view):

    leo-editor/leo/*             # <-- this is actually Leo
    leo-editor/pyflakes-leo.py   # <-- this is an extra

After (pip installed):

    PYTHON/Lib/site-packages/leo/*            # <-- this is actually Leo

One solution is to restructure the whole repository into what's called the "src layout" (https://blog.ionelmc.ro/2014/05/25/python-packaging/). That's a big change.

Alternatively we could move pyflakes and friends into a `./leo/tools` subfolder. That's a smaller change, but I don't know how it would impact workflow of the people who use them; the change might not be small to them.
​
For the purposes of this issue the remedy for is to tell
* Users that the warnings are not serious and may be ignored, and
* Leo developers should fetch a git clone or export and install from that.
~~~
     git clone https://github.com/leo-editor/leo-editor.git
     pip install --editable code/leo-editor
~~~

Original issue report follows
-----

Using leo-57-usr (installed using "pip install leo")

Open all Leo-related outlines using "File >> Open Leo File >>"

* CheatSheet.leo -> OK.
* LeoDocs.leo -> Not OK.
* LeoDist.leo -> Not OK.
* leoPlugins.leo -> leoPluginsRef.leo -> Not OK.
* leoPy.leo -> LeoPyRef.leo -> Not OK.
* myLeoSettings.leo -> OK.
* quickstart.leo -> OK.
* scripts.leo -> OK.
* leoSettings.leo -> OK.
* unittest.leo -> Not found !!!

*LeoDocs.leo:*

Leo Log Window
Leo 5.6, build 20171129062306, Wed Nov 29 06:23:05 CST 2017
Not running from a git repo
Python 3.6.3, PyQt version 5.9.3
Windows 10 AMD64 (build 10.0.16299) SP0
isPython3: True
caching enabled
reading: C:\users\viktor\leo-57-usr\lib\site-packages\leo\doc\LeoDocs.leo
reading: @edit conf.py
file not found: C:\users\viktor\leo-57-usr\lib\site-packages\leo\doc\html\conf.py
can not open: '@file C:\users\viktor\leo-57-usr\lib\site-packages\leo\doc\html\index.html'
read 8 files in 2.20 seconds
read outline in 2.64 seconds

*LeoDist.leo:*

Leo Log Window
Leo 5.6, build 20171129062306, Wed Nov 29 06:23:05 CST 2017
Not running from a git repo
Python 3.6.3, PyQt version 5.9.3
Windows 10 AMD64 (build 10.0.16299) SP0
isPython3: True
caching enabled
reading: C:\users\viktor\leo-57-usr\lib\site-packages\leo\dist\leoDist.leo
can not open: '@file C:\users\viktor\leo-57-usr\lib\site-packages\leo_assoc.nsi'
can not open: '@file C:\users\viktor\leo-57-usr\lib\site-packages\leo.nsi'
read 2 files in 0.25 seconds
read outline in 0.48 seconds

*leoPlugins.leo:*

Leo Log Window
Leo 5.6, build 20171129062306, Wed Nov 29 06:23:05 CST 2017
Not running from a git repo
Python 3.6.3, PyQt version 5.9.3
Windows 10 AMD64 (build 10.0.16299) SP0
isPython3: True
caching enabled
reading: C:\users\viktor\leo-57-usr\lib\site-packages\leo\plugins\leoPluginsRef.leo
can not open: '@file C:\users\viktor\leo-57-usr\lib\site-packages\leo\plugins\test\ekr_test.py'
can not open: '@file C:\users\viktor\leo-57-usr\lib\site-packages\leo\plugins\test\failed_to_load_plugin.py'
reading: @edit QNCalendarWidget.py
read 174 files in 4.58 seconds
read outline in 4.86 seconds

*leoPy.leo:*

Leo Log Window
Leo 5.6, build 20171129062306, Wed Nov 29 06:23:05 CST 2017
Not running from a git repo
Python 3.6.3, PyQt version 5.9.3
Windows 10 AMD64 (build 10.0.16299) SP0
isPython3: True
caching enabled
reading: C:\users\viktor\leo-57-usr\lib\site-packages\leo\core\LeoPyRef.leo
reading: @edit qt_quicksearch.py
reading: @edit qt_quicksearch_sub.py
can not open: '@file C:\users\viktor\leo-57-usr\lib\site-packages\launchLeo-unified.spec'
not found: C:\users\viktor\leo-57-usr\lib\site-packages\leo_to_html.xsl
can not open: '@file C:\users\viktor\leo-57-usr\lib\site-packages\flake8-leo.py'
can not open: '@file C:\users\viktor\leo-57-usr\lib\site-packages\pyflakes-leo.py'
can not open: '@file C:\users\viktor\leo-57-usr\lib\site-packages\pylint-leo.py'
can not open: '@file C:\users\viktor\leo-57-usr\lib\site-packages\leo\test\leo-bridge-test.py'
reading: @edit README.MD
file not found: C:\users\viktor\leo-57-usr\lib\site-packages\README.MD
read 167 files in 5.25 seconds
read outline in 5.64 seconds

*unittest.leo:*

Leo Log Window
Leo 5.6, build 20171129062306, Wed Nov 29 06:23:05 CST 2017
Not running from a git repo
Python 3.6.3, PyQt version 5.9.3
Windows 10 AMD64 (build 10.0.16299) SP0
isPython3: True
caching enabled
leoID='VIRA2017'
load dir: C:\users\viktor\leo-57-usr\lib\site-packages\leo\core
global config dir: C:\users\viktor\leo-57-usr\lib\site-packages\leo\config
home dir: C:\Users\Viktor
reading settings in C:\users\viktor\leo-57-usr\lib\site-packages\leo\config\leoSettings.leo
reading settings in C:\Users\Viktor\.leo\myLeoSettings.leo
Using default leo file name:
C:\Users\Viktor\.leo\workbook.leo
reading settings in C:\users\viktor\leo-57-usr\lib\site-packages\leo\doc\CheatSheet.leo
...
reading settings in C:\users\viktor\leo-57-usr\lib\site-packages\leo\dist\leoDist.leo
reading settings in C:\users\viktor\leo-57-usr\lib\site-packages\leo\plugins\leoPluginsRef.leo
reading settings in C:\users\viktor\leo-57-usr\lib\site-packages\leo\core\LeoPyRef.leo
not found: C:\users\viktor\leo-57-usr\lib\site-packages\leo\test\unitTest.leo

**Comment by maphew** [comment]
Fixed:
* LeoDocs, LeoPlugins

Not fixed:
* unittest, LeoPy, LeoDist

The not fixed ones can't be addressed the same way (including those files in MANIFEST.in), since they're either "developer only" or would place themselves in root of `site-packages`.

The fix for these could be a warning message when not being started from a git checkout?
Or just not showing those in the "Open Leo File" menu when not running from git checkout? (I think I favour this approach).

_@edreamleo, @tbnorth help-wanted_

**Comment by maphew** [comment]
The opening comment has been edited to explain what's going on and the current remedy. I think with that we can close the issue. 

The deep fix is to move the referenced files out of the source code root folder. There are several reasons to do that beyond these log messages, but is out of scope for #603. Perhaps a new issue along the lines of _"Root source code folder cleanup: justify your existence or be banished!"_ ;-)

**Comment by edreamleo** [comment]
On Thu, Dec 7, 2017 at 11:03 PM, matt wilkie <notifications@github.com>
wrote:

> The opening comment has been edited to explain what's going on and the
> current remedy. I think with that we can close the issue.
>
​Many thanks for your work on this issue.

I like the remedy's pragmatic approach. I am unwilling to change the
location of Leo's files and directories.  That would almost surely break
the make-leo button in leoDist.leo.

Edward
