### ISSUE TITLE
Missing files when installing Leo from PyPI using "pip install leo[develop]"

### ISSUE THREAD

**Issue by ranvik14** [leo-editor/leo-editor#604]
Using leo-57-dev (installed using "pip install leo[develop]")

Open all Leo-related outlines using "File >> Open Leo File >>"

* CheatSheet.leo -> OK.
* LeoDocs.leo -> Not OK.
* LeoDist.leo -> Not OK.
* leoPlugins.leo -> leoPluginsRef.leo -> Not OK.
* leoPy.leo -> LeoPyRef.leo -> Not OK.
* myLeoSettings.leo -> OK.
* quickstart.leo -> OK.
* scripts.leo -> OK.
* leoSettings.leo -> OK.
* unittest.leo -> Not found !!!

*LeoDocs.leo:*

Leo Log Window
Leo 5.6, build 20171129062306, Wed Nov 29 06:23:05 CST 2017
Not running from a git repo
Python 3.6.3, PyQt version 5.9.3
Windows 10 AMD64 (build 10.0.16299) SP0
isPython3: True
caching enabled
reading: C:\users\viktor\leo-57-dev\lib\site-packages\leo\doc\LeoDocs.leo
reading: @edit conf.py
file not found: C:\users\viktor\leo-57-dev\lib\site-packages\leo\doc\html\conf.py
can not open: '@file C:\users\viktor\leo-57-dev\lib\site-packages\leo\doc\html\index.html'
read 8 files in 2.03 seconds
read outline in 2.41 seconds

*LeoDist.leo:*

Leo Log Window
Leo 5.6, build 20171129062306, Wed Nov 29 06:23:05 CST 2017
Not running from a git repo
Python 3.6.3, PyQt version 5.9.3
Windows 10 AMD64 (build 10.0.16299) SP0
isPython3: True
caching enabled
reading: C:\users\viktor\leo-57-dev\lib\site-packages\leo\dist\leoDist.leo
can not open: '@file C:\users\viktor\leo-57-dev\lib\site-packages\leo_assoc.nsi'
can not open: '@file C:\users\viktor\leo-57-dev\lib\site-packages\leo.nsi'
read 2 files in 0.25 seconds
read outline in 0.41 seconds

*leoPlugins.leo:*

Leo Log Window
Leo 5.6, build 20171129062306, Wed Nov 29 06:23:05 CST 2017
Not running from a git repo
Python 3.6.3, PyQt version 5.9.3
Windows 10 AMD64 (build 10.0.16299) SP0
isPython3: True
caching enabled
reading: C:\users\viktor\leo-57-dev\lib\site-packages\leo\plugins\leoPluginsRef.leo
can not open: '@file C:\users\viktor\leo-57-dev\lib\site-packages\leo\plugins\test\ekr_test.py'
can not open: '@file C:\users\viktor\leo-57-dev\lib\site-packages\leo\plugins\test\failed_to_load_plugin.py'
reading: @edit QNCalendarWidget.py
read 174 files in 4.16 seconds
read outline in 4.39 seconds

*leoPy.leo:*

Leo Log Window
Leo 5.6, build 20171129062306, Wed Nov 29 06:23:05 CST 2017
Not running from a git repo
Python 3.6.3, PyQt version 5.9.3
Windows 10 AMD64 (build 10.0.16299) SP0
isPython3: True
caching enabled
reading: C:\users\viktor\leo-57-dev\lib\site-packages\leo\core\LeoPyRef.leo
reading: @edit qt_quicksearch.py
reading: @edit qt_quicksearch_sub.py
can not open: '@file C:\users\viktor\leo-57-dev\lib\site-packages\launchLeo-unified.spec'
not found: C:\users\viktor\leo-57-dev\lib\site-packages\leo_to_html.xsl
can not open: '@file C:\users\viktor\leo-57-dev\lib\site-packages\flake8-leo.py'
can not open: '@file C:\users\viktor\leo-57-dev\lib\site-packages\pyflakes-leo.py'
can not open: '@file C:\users\viktor\leo-57-dev\lib\site-packages\pylint-leo.py'
can not open: '@file C:\users\viktor\leo-57-dev\lib\site-packages\leo\test\leo-bridge-test.py'
reading: @edit README.MD
file not found: C:\users\viktor\leo-57-dev\lib\site-packages\README.MD
read 167 files in 3.73 seconds
read outline in 4.11 seconds

*unittest.leo:*

Leo Log Window
Leo 5.6, build 20171129062306, Wed Nov 29 06:23:05 CST 2017
Not running from a git repo
Python 3.6.3, PyQt version 5.9.3
Windows 10 AMD64 (build 10.0.16299) SP0
isPython3: True
caching enabled
leoID='VIRA2017'
load dir: C:\users\viktor\leo-57-dev\lib\site-packages\leo\core
global config dir: C:\users\viktor\leo-57-dev\lib\site-packages\leo\config
home dir: C:\Users\Viktor
reading settings in C:\users\viktor\leo-57-dev\lib\site-packages\leo\config\leoSettings.leo
reading settings in C:\Users\Viktor\.leo\myLeoSettings.leo
Using default leo file name:
C:\Users\Viktor\.leo\workbook.leo
reading settings in C:\users\viktor\leo-57-dev\lib\site-packages\leo\doc\CheatSheet.leo
...
reading settings in C:\users\viktor\leo-57-dev\lib\site-packages\leo\dist\leoDist.leo
reading settings in C:\users\viktor\leo-57-dev\lib\site-packages\leo\plugins\leoPluginsRef.leo
reading settings in C:\users\viktor\leo-57-dev\lib\site-packages\leo\core\LeoPyRef.leo
not found: C:\users\viktor\leo-57-dev\lib\site-packages\leo\test\unitTest.leo

**Comment by maphew** [comment]
LeoDocs and LeoPlugins are fixed with recent commits addressing #603. Likewise LeoDist, LeoPy and Unittest can't be fixed separately. 

I'm beginning to think it isn't a good idea have `leo[develop]` at all. User and git checkout are enough. If there are people who do want the middle path, those extra packages are a simple `pip install x` away.

**Comment by maphew** [comment]
Given that there is a mere 8mb between a user and develop pip install, a mere 2% difference overall. I don't think `leo[develop]` is worth maintaining. Just do a git checkout.

https://groups.google.com/forum/#!topic/leo-editor/2dTOkC3VON0

**Comment by edreamleo** [comment]
On Thu, Dec 7, 2017 at 3:01 PM, matt wilkie <notifications@github.com>
wrote:

> I'm beginning to think it isn't a good idea have leo[develop] at all.
>
​I agree.

Edward

**Comment by ranvik14** [comment]
2017-12-08 5:24 GMT+01:00 matt wilkie <notifications@github.com>:

> Closed #604 <https://github.com/leo-editor/leo-editor/issues/604> via
> e751d56
> <https://github.com/leo-editor/leo-editor/commit/e751d564da301616fb01afe0d3122fd7eae4c7e5>
> .
>

I agree with the rationale & the decision to offer only "pip install leo"
in the future.

With kind regards,

Viktor
