### ISSUE TITLE
Support patching of Leo's colorizer tables

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#613]
The initial question is [here](https://groups.google.com/forum/#!topic/leo-editor/IEHf4SyqEnY).

**Update**: There is a buglet involving python_rule21.  It must be the *last* rule in any rules list.  See the last comment for a complete answer.  A plugin could do the patch dynamically.  I'll post an example later.

**Comment by ZoomQuiet** [comment]
@edreamleo sateahoo!-)

thanx for explain, but

## how to debug modes/python.py?

i try to insert as :


    def python_rule_global(colorer, s, i):
        print colorer, s, i
        pass

    # Rules dict for python_main ruleset.
    rulesDict1 = {
        ...
        "F": [python_rule_f_url,python_rule21,],
        "G": [python_rule21, python_rule_global],
        "H": [ python_rule_h_url,python_rule21,],


but when i reboot leo,
as `python /opt/bin/leo/launchLeo.py`

the terminal not any debug print info.

### env.

- DDarwin Kernel Version 16.7.0: Wed Oct  4 00:17:00 PDT 2017; root:xnu-3789.71.6~1/RELEASE_X86_64 x86_64
- Leo 5.4, Sat Oct 22 06:39:42 2016
- Git commit: after ff
- Python 2.7.10, PyQt version 4.8.7

### want

if i can debug with live Leo,
i can make self Rule:

- all `G` start global variable 
- as `keyword4` colorizer rule

so i can define:

- new `python_rule_global()` bind `G`
- and dynamic insert new word into `python_main_keywords_dict` as:
    + python_main_keywords_dict["G_zoomq"] = "keyword4"
    + ...
- so means under runtime, i can make Leo colorizer all `G` start words ?

**Comment by edreamleo** [comment]
On Thu, Dec 7, 2017 at 2:59 AM, Zoom.Quiet <notifications@github.com> wrote:

> @edreamleo <https://github.com/edreamleo> sateahoo!-)
>
> thanx for explain, but
> how to debug modes/python.py?

​I'll make similar changes and investigate.

Edward

**Comment by edreamleo** [comment]
Here is the answer to your question:
```python
def python_rule_global(colorer, s, i):
    import re
    pattern = re.compile(r'\b(G[A-Z0-9_]*)')
    self = colorer
    kind = 'keyword4'
    for m in re.finditer(pattern,s):
        if m.start() == i:
            g.trace(i, repr(s), m.group(0))
            # Similar to jedit.match_keywords
            j = i + len(m.group(0))
            self.colorRangeWithTag(s, i, j, kind, delegate=None)
            self.prev = (i, j, kind)
            self.trace_match(kind, s, i, j)
            break
    else:
        j = i
    return j - i

rulesDict1 = {
...
"G": [python_rule_global,python_rule21], # rule 21 must be last in the list.
...
}
```

**Comment by edreamleo** [comment]
Here is the present version of leo/plugins/@file patch_python_colorizer.py, without sentinels. This should be sufficient to close this item.

```python
'''
Shows how to patch python colorizer.
'''
import leo.core.leoGlobals as g
assert g
import re

def init ():
    ok = g.app.gui.guiName() in ('qt','qttabs')
    if ok:
        g.registerHandler('after-create-leo-frame',onCreate)
        g.plugin_signon(__file__)
    return ok

def onCreate (tag, keys):
    c = keys.get('c')
    if c:
        patch_colorizer(c)

def patch_colorizer(c):
    colorizer = c.frame.body.colorizer
    mode = colorizer.modes.get('python_main')
    d = mode.get('rulesDict')
    aList = d.get('G', [])
    aList.insert(0, python_rule_global)
    d['G'] = aList
    # g.printObj(rulesDict.get('G'))
    # Force a full recolor.
    c.frame.body.wrapper.setAllText(c.p.b)

def python_rule_global(colorer, s, i):
    trace = False
    pattern = re.compile(r'\b(G[A-Z0-9_]*)')
    self = colorer
    kind = 'keyword1'
    for m in re.finditer(pattern,s):
        if m.start() == i:
            if trace: g.trace(i, repr(s), m.group(0))
            j = i + len(m.group(0))
            self.colorRangeWithTag(s, i, j, kind, delegate=None)
            self.prev = (i, j, kind)
            self.trace_match(kind, s, i, j)
            break
    else:
        j = i
    return j - i
```
