### ISSUE TITLE
Syntax @color settings don't dereference

### ISSUE THREAD

**Issue by gatesphere** [leo-editor/leo-editor#62]
Unlike the stylesheet @colors, the syntax @color settings don't dereference.  For example:

@color mycomment = #586E76
@color comment1_color = @mycomment
@color comment2_color = @mycomment
@color comment3_color = @mycomment
@color comment4_color = @mycomment

Result:
Errors in the console (see below) and uncolored comments in code (same as normal fg color).

Console output:
*\* isPython3: False
Leo 4.11 final, build 20140922060345, Mon Sep 22 06:03:44 CDT 2014
Git repo info: branch = master, commit = c93bd173f05d
Python 2.7.6, PyQt version 4.8.5
Windows 7 x86 (build 6.1.7601) SP1
leoID=peckj (in C:\Users\PeckJ.leo)
reading settings in C:\cygwin\home\PeckJ\repos\leo\leo-editor\leo\config\leoSettings.leo
reading settings in C:\Users\PeckJ.leo\myLeoSettings.leo
reading settings in C:\Users\PeckJ.leo\workbook.leo
setTag unknown color name @mycomment mainLoop,python_rule0,match_eol_span,colorRangeWithTag
setTag unknown color name @mycomment mainLoop,python_rule0,match_eol_span,colorRangeWithTag

**Comment by edreamleo** [comment]
Not sure how feasible this is, but I'd like to resolve this one way or the other for 5.5.

**Comment by edreamleo** [comment]
Vitalije, I feel that a burden has been lifted from me with all your excellent fixes.  They are greatly appreciated.
