### ISSUE TITLE
Tip: run pyflakes automatically

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#624]
[pyflakes](https://pypi.python.org/pypi/pyflakes) is EKR's favorite programming tool. It checks even large .py files almost instantly.

These settings cause Leo to run pyflakes whenever saving a .py file and to raise a dialog if any errors are found:

    @bool run-pyflakes-on-write = True
    @bool syntax-error-popup = True

Tags: Settings, Scripting.

**Comment by ktenney** [comment]
I set these, and get the popup, which says only
Python errors in:
<filename>

I'm assuming there's an explanation somewhere ...

Thanks,
Kent

**Comment by edreamleo** [comment]
On Thu, Dec 7, 2017 at 4:15 PM, Kent Tenney <notifications@github.com>
wrote:

I set these, and get the popup, which says only
> Python errors in:
> <filename>
>
> I'm assuming there's an explanation somewhere ...
>

​Hehe.  That's the reason there is a popup.  It's so easy miss the messages
that appear both in the log window and in the console, if you start Leo
from a console.

Edward

**Comment by ktenney** [comment]
Arghhh
For some reason, when I wrote that, the report wasn't
appearing in the log or terminal. It is now of course, and
it's very useful.

**Comment by edreamleo** [comment]
On Fri, Dec 8, 2017 at 5:16 PM, Kent Tenney <notifications@github.com>
wrote:

> Arghhh
> For some reason, when I wrote that, the report wasn't
> appearing in the log or terminal. It is now of course, and
> it's very useful.
>

​Oh good. pyflakes will change your life.

Edward

**Comment by edreamleo** [comment]
Closed: transferred to leoTips.leo.
