### ISSUE TITLE
Tip: universal shortcut for your scripts

### ISSUE THREAD

**Issue by vitalije** [leo-editor/leo-editor#629]
You can have a personal shortcut to run script while developing it. For example: put `@key=Alt-4` in headline and click the `script-button` button. Now, every time you press `Alt-4`, Leo will execute your script.
If your script grows to several subnodes, you won't have to select top node every time you wish to run script. It would be enough to just press your universal shortcut.

Tags: Scripting

**Comment by edreamleo** [comment]
Closed: transferred to leoTips.leo.
