### ISSUE TITLE
Do we need both rst-ignore-tree and rst-ignore?

### ISSUE THREAD

**Issue by vitalije** [leo-editor/leo-editor#630]
In the [documentation](http://leoeditor.com/rstplugin3.html#headline-commands) both of this commands are mentioned and it seems that one of them should suffice.

**Comment by edreamleo** [comment]
Yes, we need them both.  `rst-ignore is useful when we want to make comments about a tree that will not be part of the docs.  There is no reason to change things and a very good reason (compatibility) not to change things.

**Comment by vitalije** [comment]
I am sorry, but I still don't get it. What is the difference between the two? Documentation claims that they have identical meaning. If there is a difference perhaps the documentation should be updated to explain it.

**Comment by edreamleo** [comment]
On Wed, Dec 6, 2017 at 3:10 PM, Виталије Милошевић <notifications@github.com
> wrote:

> I am sorry, but I still don't get it. What is the difference between the
> two? Documentation claims that they have identical meaning.
>
​Where, exactly, are the confusing words?
​
​There are several places in LeoDocs.leo that state that the two are
different.  For example,

LeoDocs.leo#Leo's Documentation-->Tutorials-->@rst
html\tutorial-rst3.html-->Other topics-->\@rst-ignore & @rst-ignore-tree
ignore text

QQQ
It is often useful to put reference material in your @rst tree that will
*not* be included in the actual output. To have the rst3 command ignore a
single node, type this in the node's headline::

    @rst-ignore <ignored-text>

Neither the headline nor body text will be part of the output file.

To have the rst3 command ignore a node and all its descendants, type this
in the node's headline::

    @rst-ignore-tree <ignored-text>
QQQ

Edward

**Comment by vitalije** [comment]
Please check the above link to documentation [page](http://leoeditor.com/rstplugin3.html#headline-commands). First item in the list is at-rst-ignore and the third is at-rst-ignore-tree stating:

```
@rst-ignore <ignored-text>
    Ignore the node and its descendants.
@rst-ignore-node <ignored-text>
    Ignore the node, but not its descendants.
@rst-ignore-tree <ignored-text>  
    Same as @rst-ignore. Ignore the node and its descendants.
```

**Comment by vitalije** [comment]
As I understand your citation `@rst-ignore` should work like `@rst-ignore-node` i.e. it affects a single node, but the page that I pointed out claims it will affect all its descendants.

**Comment by vitalije** [comment]
It seems rst3 tutorial page is in conflict with the rst3-plugin page. Assuming the first is correct, the other page should be fixed and the title of this issue should be:

### Do we need both `@rst-ignore` and `@rst-ignore-node`?

**Comment by edreamleo** [comment]
On Wed, Dec 6, 2017 at 6:09 PM, Виталије Милошевић <notifications@github.com
> wrote:

> Please check the above link to documentation page
> <http://leoeditor.com/rstplugin3.html#headline-commands>. First item in
> the list is at-rst-ignore and the third is at-rst-ignore-tree stating:
>
> @rst-ignore <ignored-text>
>     Ignore the node and its descendants.
> @rst-ignore-node <ignored-text>
>     Ignore the node, but not its descendants.
> @rst-ignore-tree <ignored-text>
>     Same as @rst-ignore. Ignore the node and its descendants.
>
> ​Thanks for this.  The documentation should be made consistent with itself
and the facts ;-)  However, we *can not* remove existing "directives"
because that might break existing documents of which we have no knowledge.

Edward

**Comment by edreamleo** [comment]
Rev f4c7c70 contains changes to both actual code and the documentation. Afaik, they now both agree.

I would have preferred not to change how the rst3 command worked, but I don't think there was any real choice.  The code was inconsistent both with itself and with the docs. Only time will tell whether the code changes at f4c7c70 will cause any distress.

Previously, (again, afaik) `@rst-ignore` *may* have worked like `@rst-ignore-tree`. The code is very hard to understand.
