### ISSUE TITLE
Use jedi as the basis for the check-conventions command

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#632]
**Summary**

The check-conventions (aka cc) command checks that names are used in ways that comply with user-supplied coding conventions. The tool should be able to detect the error that reopened #627. Neither pylint nor pyflakes detected this error.

**Important**: At present the cc command knows only about Leo's naming conventions.  At minimum, users should be able to supply their own naming conventions using `@data nodes`.

It's not clear whether this tool will every be very useful.  If it ever does become useful, it will almost certainly be fast enough to run automatically when saving files. This would be done only if the far-more-useful pyflakes checks pass.

[The initial post](https://groups.google.com/forum/#!topic/leo-editor/yzh-SVz3qmQ) contains initial notes about the prototype. [A second post](https://groups.google.com/forum/#!topic/leo-editor/By-YAfgtC-E) discusses how to complete the prototype. [A third post](https://groups.google.com/forum/#!topic/leo-editor/5pYJyB4rp3k) discusses what's next. 

**Status**

[This post](https://groups.google.com/forum/#!topic/leo-editor/WjP9ekT_zgw) discusses the present state of the project.  I am likely to delay further work on this project.  Many more important projects await.

As of rev 5e8e1c9, the prototype detects the following errors, neither of which pylint nor pyflakes will detect.  

Test 1: (Difficult)

```python
class TC:
    def __init__(self, c):
        c.tc = self
    def add_tag(self, p):
        print(p.v) # Throws AttributeError if p is a vnode.

class Test:
    def __init__(self,c):
        self.c = c
            # An instance of Commands, by convention.
        self.tc = self.c.tc
            # An instance of TC, **by inference**.
    def add_tag(self):
        p = self.c.p
        self.tc.add_tag(p.v) # WRONG: the arg should be p, not p.v
```
Test 2: (Easier)
```python
class C1:
      
    def f1(self, p):
        print(p.v)
       
    def f2(self, p):
        self.f1(p.v) # WRONG
```

**Comment by tbnorth** [comment]
On Wed, 06 Dec 2017 22:30:52 +0000 (UTC)
"Edward K. Ream" <notifications@github.com> wrote:

> It drives me crazy that there is no easy way to detect the blunder
> that reopened #627. A vnode was passed into a method when a position
> was expected.​ It's not as if Leo doesn't have clear coding
> conventions.
> 
> Despite years of failure, I remain convinced that detecting such
> blunders should be possible in speed approaching that of pyflakes. I
> intend to do this in 2018.

:-}  Rather than trying that again, I wonder if there's a way to use
Python 3.6 type hinting for Leo's code base and then somehow translate
it away (automatically) to make a Python 2 version?  Or any other way
to run type hinted code in Python 2?

Then we could just use mypy to check types.  And I may be over
inflating the 2 vs 3 issue, not sure about that.

https://stackoverflow.com/questions/35230635/type-hinting-in-python-2

maybe?

Cheers -Terry

**Comment by edreamleo** [comment]
On Wed, Dec 6, 2017 at 5:12 PM, Terry Brown <notifications@github.com>
wrote:

> It drives me crazy that there is no easy way to detect the blunder
> > that reopened #627. A vnode was passed into a method when a position
> > was expected.​ It's not as if Leo doesn't have clear coding
> ​ ​
> conventions.
> >
> > Despite years of failure, I remain convinced that detecting such
> > blunders should be possible in speed approaching that of pyflakes. I
> > intend to do this in 2018.
>
> :-} Rather than trying that again, I wonder if there's a way to use
> Python 3.6 type hinting for Leo's code base and then somehow translate
> it away (automatically) to make a Python 2 version? Or any other way
> to run type hinted code in Python 2?


> Then we could just use mypy to check types.


​No.  I don't intend to use type hinting or anything like that.

It's funny, but when I see actual type hints I want to run away screaming
:-)

I am thinking of something much, much simpler. The idea is to replace *type*
checking with *convention *checking. c is a commander, p is a position, v
is a vnode.  That kind of thing.

Let's see if this plan survives first contact with the enemy...

Rev a78a63 says "Fixed another aspect of #627"

This checkin involves only one file, nodetags.py, so in *this case* no
cross-file checking was needed.  So we have hope that, just as with
pyflakes, the blunder *might *be caught extremely quickly.

The offending line was in the LeoTagWidget class, in the local callback
function of the LeoTagWidget.callback_factory method.

The fix was to change:

    tc.remove_tag(p.v,tag)

to:

    tc.remove_tag(p,tag)

The key question is, *how much information does the convention checker need
to detect this bug*?

In this case, tc is an instance of the TagController class, *not* the
LeoTagWidget that contained the actually buggy lines.  But still,
nodetags.py contains all the needed information.

As always, the general problem requires type checking to discover that
remove_tag is a method of the TagController class.

We could try to "cheat" and say that remove_tag must be a member of the
TagController class, since there is no other remove_tag method in the file.
However, long experience tells me that such hacks won't work. They
instantly propagate throughout the code in the worst way.

Instead, we have to look at this line in TagController.callback_factory:

    tc = c.theTagController

This is the information the convention checker needs to know!  That is, the
convention checker need *only* know that tc is an instance of the
TagController class.  With *only *that information, it can detect/remember
that the signature of tc.remove_tag is:

    def remove_tag(self, p, tag):

So the convention checker sees that remove_tag expects a position, but was
passed p.v instead. The convention checker will also know about p and p.v,
and that will suffice to detect the error.
​

> And I may be over
> ​ ​
> inflating the 2 vs 3 issue, not sure about that.
>
> https://stackoverflow.com/questions/35230635/type-hinting-in-python-2


​I don't want *any *kind of type hints polluting Leo's code base​!

Instead, the checker will know about p, v, p.v, p.h, etc, as well as the
types of c.x where x is a subcommander.

To repeat, the key question is, how much information does the convention
checker need to detect this bug?  I think the answer is, not much, but we
shall see...

Edward

**Comment by edreamleo** [comment]
> To repeat, the key question is, how much information does the convention checker need to detect this bug? I think the answer is, not much, but we shall see...

Imo, it should be possible to detect the bug just discussed with about a week's work.  I have no interest in a year-long project.

I've learned from past mistakes.  I'll use simple AST parsing code, not the fastest possible code.  After creating the parse tree for the to-be-checked module, the code will have two passes:

1. Discover signatures of all functions and methods defined in the file.
2. Check those signatures against all local calls.

Later, we could build a database of all of Leo's core files, and use that to check non-local calls.

**Comment by tbnorth** [comment]
On Thu, 07 Dec 2017 12:25:55 +0000 (UTC)
"Edward K. Ream" <notifications@github.com> wrote:

> I am thinking of something much, much simpler. The idea is to replace
> *type* checking with *convention *checking. c is a commander, p is a
> position, v is a vnode.  That kind of thing.

Given the size of Leo's code base, a Leo specific solution isn't
unreasonable.  But I think it would be misleading (should this bear
fruit) to start to say Leo has some kind of type checking.  This sort
of happened with Leo's Leo centric code auto-completion.  I know Leo
has some other options for auto-completion, but I think it's a mistake
to think that major feature is well covered if it only applies to Leo's
own code base.

Along those lines, it would be cool if your convention checker could be
a completely Leo free library which isolates all it's code base specific
knowledge in a config. file.  Then if Leo uses this library, people
could supply their own config. files for their own code bases.

Cheers -Terry

**Comment by edreamleo** [comment]
On Thu, Dec 7, 2017 at 9:08 AM, Terry Brown <notifications@github.com>
wrote:

​> ​
I think it's a mistake
​ ​
to think that major feature is well covered if it only applies to Leo's
​
​
own code base.

​I agree completely.​

Along those lines, it would be cool if your convention checker could be
> a completely Leo free library which isolates all it's code base specific
> knowledge in a config. file. Then if Leo uses this library, people
> could supply their own config. files for their own code bases.


​Yes. In Leo's case, we want to tell the checker about Leo's official
ivars, expressed as chains.  Like c.frame.body, c.frame.body.wrapper,
c.frame.body.wrapper.widget, etc.  And also c, g, p, p.v, s, etc. There
aren't many!

Other programs should be able to provide the same kind of conventions.

I want experiments that can be done in *hours*, not days.​ The first will
do the following:

1. Parse the file into an ast tree.
2. Format each outer-level statement as text.
3. Write only those statements that match one or more regex's.

The result will be a *visual narrative* of checks I envisage.

Existing tools in leoAst.py and leoCheck.py will do the heavy lifting.

Edward
