### ISSUE TITLE
Link to nodes from log

### ISSUE THREAD

**Issue by tbnorth** [leo-editor/leo-editor#635]
It would be useful if references to specific nodes / line numbers that appear in the log were clickable links to select the corresponding node / line number in the outline.  Pyflakes output would be one example where this would be useful, but there are many more.

I'm not sure if the log widget uses HTML or colorized Qt text, and how that factors in to the implementation.

I've had this idea in my head for some time and don't seem to be getting any closer to having time to pursue it, so hoping someone will pick it up, although if it turns out to be future me, that's ok.

**Comment by edreamleo** [comment]
I like this.  Kent asked for something like this back in the Paleozoic era.

**Comment by tbnorth** [comment]
I have this mostly done, will push something soon.

**Comment by edreamleo** [comment]
I am going to close this.  Many thanks for this, Terry.
