### ISSUE TITLE
Installing pyenchant fails for Windows 64 bit python

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#636]
_Strictly speaking this is an upstream issue and isn't Leo's problem, but prospective Leo users run into it, so lets document the problem and the workarounds. From mailing list:_

    VR> PyEnchant is now also available as a wheel for Python 2.7 as well as Python 3.x. - See
    VR>
    VR> * https://pypi.python.org/pypi/pyenchant/2.0.0

Unfortunately pyenchant binaries via pip are not available for all platforms, most notably missing is Windows 64bit Python. The issue is 3 years old so a solution doesn't seem to be imminent.

I could add an IF-THEN to setup.py to install it for supported platforms, but have hesitated this far because it would add yet another special case to the install instructions.

~~~
> python --version
Python 3.6.3 :: Anaconda, Inc.

> pip install pyenchant
Collecting pyenchant
  Downloading pyenchant-2.0.0.tar.gz (64kB)
    100% |████████████████████████████████| 71kB 607kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\matt\AppData\Local\Temp\pip-build-bzioz5jr\pyenchant\setup.py", line 212, in <module>
        import enchant
      File "C:\Users\matt\AppData\Local\Temp\pip-build-bzioz5jr\pyenchant\enchant\__init__.py", line 92, in <module>
        from enchant import _enchant as _e
      File "C:\Users\matt\AppData\Local\Temp\pip-build-bzioz5jr\pyenchant\enchant\_enchant.py", line 145, in <module>
        raise ImportError(msg)
    ImportError: The 'enchant' C library was not found. Please install it via your OS package manager, or use a pre-built binary wheel from PyPI.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\matt\AppData\Local\Temp\pip-build-bzioz5jr\pyenchant\
~~~

Also see 
* https://github.com/leo-editor/leo-editor/issues/324
* https://stackoverflow.com/questions/29381919/importerror-the-enchant-c-library-was-not-found-please-install-it-via-your-o
* https://github.com/rfk/pyenchant/issues/42

**Comment by LewisNeal** [comment]
From my win64 system: 
C:\~\AppData\Local\Programs\Python\Python36\Lib\site-packages>pip list --outdated --format columns
Package     Version Latest Type
----------- ------- ------ -----
pyenchant   1.6.8   2.0.0  sdist

It seems pyenchant is available as a whl type but only up to v1.6.8
Maybe one option is to specify v1.6.8 via pip command, but as you said, that's another special instruction for the install instructions.

**Comment by maphew** [comment]
Oh! That actually wouldn't need install instructions. We can put in a special case to use only that version for win64. I don't know if that's wise, but it's possible.

http://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-platform-specific-dependencies

Unested:
~~~
install_requires=[
        'pyenchant >= 1.6.8;platform_system=="Windows" and platform_machine=="amd_64"'
        ]
~~~

**Comment by edreamleo** [comment]
On Tue, Dec 12, 2017 at 3:46 PM, matt wilkie <notifications@github.com>
wrote:

Unfortunately pyenchant binaries via pip are not available for all
> platforms, most notably missing is Windows 64bit Python. The issue is 3
> years old so a solution doesn't seem to be imminent.
>

​That's why I use a 32-bit version of Python on Windows.

I'll defer all questions on this top to you and Lewis Neal.

Edward

**Comment by maphew** [comment]
Re: "Build pre-compiled libs for win64"
> As you all have undoubtedly noticed, I am no longer actively maintaining this project, and I've no reason to believe that will change. Thanks to everyone who dived in to try to help resolve this issue, but in order to make appearances match reality, I'm going to move this project into archive mode:
> 
> https://rfk.id.au/blog/entry/archiving-open-source-projects/
> 
> If anyone is interested in forking and taking over maintenance of this project, please reach out via the link above and I'll be happy to help coordinate a handoff.

-- https://github.com/rfk/pyenchant/issues/42

**Comment by edreamleo** [comment]
On Thu, Mar 8, 2018 at 12:41 AM, matt wilkie <notifications@github.com>
wrote:

> Re: "Build pre-compiled libs for win64"
>
> As you all have undoubtedly noticed, I am no longer actively maintaining
> this project, and I've no reason to believe that will change. Thanks to
> everyone who dived in to try to help resolve this issue, but in order to
> make appearances match reality, I'm going to move this project into archive
> mode:
>
> https://rfk.id.au/blog/entry/archiving-open-source-projects/
>
> If anyone is interested in forking and taking over maintenance of this
> project, please reach out via the link above and I'll be happy to help
> coordinate a handoff.
>
> -- rfk/pyenchant#42 <https://github.com/rfk/pyenchant/issues/42>
>

​Thanks for this update.  I am going to mark this issue "Can't Fix".

Edward

**Comment by edreamleo** [comment]
I see no reason to leave this open, so I'll close it.

**Comment by maphew** [comment]
Fixed upstream. There are new active pyenchant maintainers

**Comment by edreamleo** [comment]
@maphew Thanks for this update. It's good news.
