### ISSUE TITLE
Javascript importer should use @others everywhere

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#639]
The **[js-imp branch](https://github.com/leo-editor/leo-editor/tree/js-imp)** contains the work on this item.

The thread [ENB: Code generation for javascript](https://groups.google.com/d/msg/leo-editor/umsIIt-O2bw/gfbVOriCCQAJ) discusses the present plans. **Summary**: using multiple `@others` directives can be done, but it will be tricky.

**The colorizer is not to blame**

This is an importer issue, not a colorizer issue. It is unreasonable to expect the colorizer to colorize huge nodes quickly. The file rpg_objects.js imports to a top-level node containing 1394 section references. [This reply](https://groups.google.com/d/msg/leo-editor/i6LQdY69SwQ/1Byn16Q2BQAJ) contains a link to this files. The post[#639: rpg_objects.leo (was: why I believe...)](https://groups.google.com/forum/#!topic/leo-editor/lgkGTqRrdcg) contains an attached .leo file that refactors the huge top-level nodes into about 24 child nodes.  This solves the performance "bug".

**Comment by edreamleo** [comment]
I am going to close this item.  It is unreasonable to expect Leo's colorizer to handle huge nodes containing thousands of section references.  The .leo file referenced [here](https://groups.google.com/forum/#!topic/leo-editor/lgkGTqRrdcg) is a reasonable workaround.

**Comment by edreamleo** [comment]
Rev b64ed3 adds support for the force_at_others keyword in recursive import scripts.  Now the following Leo script passes the perfect import test while generating `@others` in the top-level node.
```python
c.recursiveImport(
    dir_ = r'c:\test\rpg_objects.js',
    kind = '@clean',
    recursive = False,
    safe_at_file = True,
    theTypes = ['.js',],
    force_at_others = True, # Only has effect for javascript
)
```

**Comment by vitalije** [comment]
> I am going to close this item. It is unreasonable to expect Leo's colorizer to handle huge nodes containing thousands of section references.

I'm Ok with this decision if this issue is just about syntax colorizer. However, originally problem was about importing file. Perhaps, a new issue should be opened or this can be renamed. I don't think that original problem is solved. Suppose that some JavaScript developer learns about Leo and decides to give it a try. Runs `leo rpg_objects.js` and sees unresponsive application for 16 or more seconds. I am afraid that expecting such user to write or even search and use script to change outline, or to use another script to import file is a bit too unrealistic.

@edreamleo, please have a look at my `import_file` function for JavaScript. It creates optimal outline and very fast too (* about 250ms on my machine). It is only 238 lines of code long.

**Comment by edreamleo** [comment]
On Wed, Dec 20, 2017 at 9:35 AM, Виталије Милошевић <
notifications@github.com> wrote:

@edreamleo <https://github.com/edreamleo>, please have a look at my
> import_file function for JavaScript. It creates optimal outline and very
> fast too (* about 250ms on my machine). It is only 238 lines of code long.
>

​I don't see this. Where is it?

Edward

**Comment by vitalije** [comment]
It's [here](http://computingart.net/fpfproto-2.html).
That is the second part of three part discussion about using functional programming for prototyping.

**Comment by edreamleo** [comment]
On Wed, Dec 20, 2017 at 10:54 AM, Виталије Милошевић <
notifications@github.com> wrote:

> It's here <http://computingart.net/fpfproto-2.html>.
> That is the second part of three part discussion about using functional
> programming for prototyping.
>
​> isn’t it success?

Not necessarily. I don't have time to look at this code in detail. The
following are some initial comments.

> Let alone fact that files were imported in far better form than the
original Leo import gives.​

I have not looked at the nodes generated from your code.  Leo's import code
looks reasonable to me when the force_at_others switch is True.

Unless I am missing something, @others can not be used for arbitrary
javascript files.  Instead, sections references are required.

Furthermore, parsing javascript correctly is not easy and almost certainly
can not be done using regex's.  See js_i.scan_line & helpers.

Finally, it's not clear that your code could be adapted to pass the various
javascript unit tests.

Edward

**Comment by edreamleo** [comment]
On Wed, Dec 20, 2017 at 1:54 PM, Terry Brown <notifications@github.com>
wrote:

> On Wed, 20 Dec 2017 10:50:28 -0800
> "Edward K. Ream" <notifications@github.com> wrote:
>
> > Unless I am missing something, @others can not be used for arbitrary
> > javascript files. Instead, sections references are required.
>
> I think it can, just because any file can be seen as a series of blocks
> of lines of text, and @others can represent that. If the indentation's
> weird, it might mean bodies that are wholly indented, but it's
> certainly possible.
>

​Thanks for this.  Imo, this is the heart of the present discussion.  ​

Perhaps I was setting too high a bar for the js importer.  I'll reconsider
the approach I was taking.

I wouldn't use any importer that created section references, when that
> happens I use @clean and manual splitting instead.
>

​Good to know. Certainly @others is preferred. Perhaps there is a clever
way to use it always.

Edward

**Comment by edreamleo** [comment]
I am going to reopen this and give it the "First" and "EKR" labels. Indeed, several new interesting design issues present themselves. These seem orthogonal to Vitalije's coding suggestions, which are interesting in their own right.
