### ISSUE TITLE
invalid syntax after git pull

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#641]
swot@pp:~/leo-editor$ git pull
remote: Counting objects: 73, done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 73 (delta 48), reused 51 (delta 36), pack-reused 10
展开对象中: 100% (73/73), 完成.
来自 https://github.com/leo-editor/leo-editor
   3f6ea1e..b28c296  master     -> origin/master
更新 3f6ea1e..b28c296
Fast-forward
 leo/commands/abbrevCommands.py  |  2 +-
 leo/commands/convertCommands.py |  2 +-
 leo/commands/editCommands.py    |  8 ++++----
 leo/core/commit_timestamp.json  |  4 ++--
 leo/core/leoApp.py              |  2 +-
 leo/core/leoCheck.py            |  2 +-
 leo/core/leoCommands.py         |  4 ++--
 leo/core/leoTest.py             |  2 ++
 leo/core/runLeo.py              |  2 +-
 leo/plugins/graphcanvas.py      |  2 +-
 leo/plugins/macros.py           |  4 ++--
 pylint-leo.py                   | 16 +++++++++++++---
 12 files changed, 31 insertions(+), 19 deletions(-)
swot@pp:~/leo-editor$ python launchLeo.py 
Traceback (most recent call last):
  File "launchLeo.py", line 7, in <module>
    import leo.core.runLeo
  File "/home/swot/leo-editor/leo/core/runLeo.py", line 67
    def run(*args, fileName=None, pymacs=None, **keywords):
                          ^
SyntaxError: invalid syntax
swot@pp:~/leo-editor$

**Comment by wangzhaohe** [comment]
run in python2.7

**Comment by edreamleo** [comment]
On Wed, Dec 27, 2017 at 3:26 PM, wangzhaohe <notifications@github.com>
wrote:

> Traceback (most recent call last):
> File "launchLeo.py", line 7, in
> import leo.core.runLeo
> File "/home/swot/leo-editor/leo/core/runLeo.py", line 67
> def run(*args, fileName=None, pymacs=None, **keywords):
> ^
> SyntaxError: invalid syntax
>

​Fixed at a582fed4a. Some more recent changes must also be undone.  I'll do
that next.

My apologies. This all comes from a new pylint warning​, which clearly has
its down side...

Edward

**Comment by edreamleo** [comment]
Rev 73a20f803 should undo all the recent damage.
