### ISSUE TITLE
phonon/movie playback does not work with PyQt 5.6

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#643]
The VR plugin reports "no movie player", both on Python 2 and 3.

**Update**: The following works from within Leo. The fix to retain a Python reference to `player`. See the penultimate line:
```
import PyQt5.QtCore as C
import PyQt5.QtMultimedia as M
import os
path = 'c:/users/edreamleo/GayaneBalletSuite.mp3'
assert os.path.exists(path), repr(path)
url= C.QUrl.fromLocalFile(path)
content= M.QMediaContent(url)
player = M.QMediaPlayer()
player.setMedia(content)
# Retain a permanent reference to the player, so the GC won't destroy it.
g.app.permanentScriptDict['player'] = player
player.play()
```

**Comment by edreamleo** [comment]
This should either be resolved or closed and labeled Can'tFix.

**Comment by edreamleo** [comment]
I have added the label "Waiting", indicating that I do not know how to continue.

**Comment by LewisNeal** [comment]
Doesn't play with PyQt5 v5.10 either.
Leo 5.7b1, build 20180203163829, Sat Feb  3 16:38:29 CST 2018
Git repo info: branch = master, commit = ef381c893583
Python 3.6.4, PyQt version 5.10.0
Windows 10 AMD64 (build 10.0.16299) SP0

**Comment by LewisNeal** [comment]
Using the Python Console, executing the script line by line, the player starts and plays an mp3 after executing line
player.play()

It seems that lines 11 or 12:
app = g.app.gui.qtApp
player.stateChanged.connect(app.quit)
are maybe quitting the app before it starts? I'll try to see which line kills the player.

**Comment by edreamleo** [comment]
@LewisNeal Many thanks for this sleuthing, Lewis.  You have uncovered an important clue.

**Comment by edreamleo** [comment]
Won't play .mp4 files: https://bugreports.qt.io/browse/QTBUG-32783
