### ISSUE TITLE
Calltips - stay on top

### ISSUE THREAD

**Issue by tscv13** [leo-editor/leo-editor#647]
Ever since I started using Leo the calltips haven't worked, except for a (very) few times - I see no pattern to it. In summation it's popped up about as often as a four-leaf clover in my front yard.

**Comment by tbnorth** [comment]
I haven't seen them not work, although I do see an inconsistency in whether the pop-up list or log pane list is used for completion.  I don't know a key binding for accessing call-tips directly, so I always use the completion key binding followed by ? to get the call tip.  Also, a lot of functions don't have call tips.  So for example I type

```
c.selectPosition<Ctrl-Space>?
```

and the `Info` tab in the log pane displays the call tip.  When I hit `Esc` to remove the pop-up list, the Info tab is deselected in favor of the `Log` tab, which is annoying, but expected.

Can you give a key by key example of them not working for something known to have a call-tip, like `c.selectPosition`?

**Comment by tscv13** [comment]
No, it works as you say. I never saw an explanation of how to do it like that, though. Maybe it needs to be added to the documentation?

Thanks for the solution!

tsc

**Comment by tscv13** [comment]
I believe I found the answer (the script runs again). In the end I had
to disable "import leo.core.leoGlobals as g" and put "App()" back
where it was. Whew! Thanks for your time, I really appreciate it!

tsc
