### ISSUE TITLE
Undoer class problem

### ISSUE THREAD

**Issue by devadrian1** [leo-editor/leo-editor#654]
(Transposed from google group)
Hello,

I have undo granularity set to "**word**".  According to the embedded docs, this should occasionally trigger "**recognizeStartOfTypingWord**".
 
 ok "**setUndoTypingParams**" gets called frequently, of course, but "**recognizeStartOfTypingWord**" NEVER gets called which would explain why "word" granularity seems identical to "**char**" granularity.

Relevant Info:
**Python 3.6.1**
**PyQT5**
**Version**: 5.6
**File**: leoUndo.py
**Methods** (That seem relevant): 
    **_setUndoTypingParams_**
    **_recognizeStartOfTypingWord_** (supposed to be called by above when using 'word' granularity, never happens for me.)

The effect of this 'issue' is that 'word' granularity acts like 'char' granularity, which even Leo documentation notes is un-usable and wasteful (paraphrasing).

**Original File:** [leoUndo.py.txt](https://github.com/leo-editor/leo-editor/files/1643194/leoUndo.py.txt)

**Comment by edreamleo** [comment]
The bug was a misuse of the ternary operator when tuples are involved.

**Comment by devadrian1** [comment]
I can confirm that this works. Thanks, Edward.
