### ISSUE TITLE
@buttons defined in local myLeoSettings.leo not appearing in work files

### ISSUE THREAD

**Issue by ktenney** [leo-editor/leo-editor#656]
I see the following: in a directory containing 2 files, 
myLeoSettings.leo: defines one @button test-mlsb
test.leo: skeleton leo file

1. open test.leo, no @button test-mlsb
2. run command print-buttons, no buttons defined
3. open myLeoSettings.leo in a tab
4. return to test.leo: print-buttons shows test-mlsb, button not visible

Attached are the files.

[test-leo.zip](https://github.com/leo-editor/leo-editor/files/1649831/test-leo.zip)

Leo Log Window
Leo 5.6, build 20180120082008, Sat Jan 20 08:20:08 CST 2018
Git repo info: branch = master, commit = 20a0ae6ad3f1
Python 3.6.3, PyQt version 5.9.3
linux
isPython3: True
caching enabled
setting leoID from os.getenv('USER'): 'ktenney'
load dir: /opt/fetching/leo-editor/leo/core
global config dir: /opt/fetching/leo-editor/leo/config
home dir: /home/ktenney
reading settings in /opt/fetching/leo-editor/leo/config/leoSettings.leo
reading settings in /home/ktenney/test-leo/myLeoSettings.leo
reading settings in /home/ktenney/test-leo/test.leo
reading: /home/ktenney/test-leo/test.leo
read outline in 0.11 seconds

**Comment by edreamleo** [comment]
On Sun, Jan 21, 2018 at 8:50 AM, Kent Tenney <notifications@github.com>
wrote:

> I see the following: in a directory containing 2 files,
> myLeoSettings.leo: defines one @button <https://github.com/button>
> test-mlsb
> test.leo: skeleton leo file
>
>    1. open test.leo, no @button <https://github.com/button> test-mslb
>    2. run command print-buttons, no buttons defined
>    3. open myLeoSettings.leo in a tab
>    4. return to test.leo: print-buttons shows test-mslb, button not
>    visible
>
> Attached are the files.
>

​Thanks.  I'll look into this soon.

Edward

**Comment by edreamleo** [comment]
I am going to close this item. I see the expected behavior.

Make sure you put any **shared** `@button` nodes in myLeoSettings.leo in an `@buttons` node.  Like this:
```
- @settings
  - @buttons
    - @button my-button
```
Any `@button` node outside the `@buttons` tree will be local to myLeoSettings.leo.

Opening myLeoSettings.leo might have some side effect, but I think that's too small to worry about.

**Comment by ktenney** [comment]
DOH!

Next: behaviour of  @rclick @buttons

given the node
- @button rclick-parent
   - @rclick rclick-node

The rclick feature works as expected
if it is moved under a @buttons node, it doesn't

- @buttons
   - @button rclick-parent
      - @rclick rclick-node

so rclick nodes can't be shared.

Probably more an enhancement request than a bug,
file an issue or no?

Thanks,
Kent

**Comment by edreamleo** [comment]
On Mon, Jan 22, 2018 at 8:57 AM, Kent Tenney <notifications@github.com>
wrote:

> DOH!
>

​No problem​

>
> Next: behaviour of @rclick @buttons
>
> given the node
> - @button rclick-parent
> - @rclick rclick-node
>
> The rclick feature works as expected
> if it is moved under a @buttons node, it doesn't
>
> - @buttons
> - @button rclick-parent
> - @rclick rclick-node
>
> so rclick nodes can't be shared.
>
> Probably more an enhancement request than a bug,
> file an issue or no?
>

​Please do.  I like keeping things separated when possible.

Edward
