### ISSUE TITLE
@rclick button-name not working if under @buttons node

### ISSUE THREAD

**Issue by ktenney** [leo-editor/leo-editor#657]
Buttons defined in myLeoSettings.leo will be shared to work
files if under a @buttons node, however the @rclick construct
doesn't work if under a @buttons node 

given the node
  - @button rclick-parent
     - @rclick rclick-node

 The rclick feature works as expected
 if it is moved under a @buttons node, it doesn't

 - @buttons
   - @button rclick-parent
     - @rclick rclick-node

 so rclick nodes can't be shared.

**Comment by tbnorth** [comment]
The @rclick code is both hairy and invaluable :-S

**Comment by ktenney** [comment]
Not surprising. The price paid for "Buttons are great: more! more!" ;-]

**Comment by ktenney** [comment]
I can live without shared @rclick buttons, there are bigger fish to fry.

I'll consider this as motivation to work more with @commands.

Thanks,
Kent

**Comment by ktenney** [comment]
Then I see it's EKRs #1 bug ... good luck!

**Comment by edreamleo** [comment]
Rev 75ec573 attempts a fix.  This is fantastically complicated code, and I have not really tested it.

Please reopen if problems remain.

**Comment by ktenney** [comment]
Yeah, please revert this one. 

@settings @buttons @button @rclick not improved, and
right clicking on a button and selecting 'Go to Script' gives the dialog
"Create myLeoSettings.leo in /home/ktenney/.leo?"
Then opens a myLeoSettings.leo, tab, closes it ...

I can live with the previous behaviour, I doubt anyone else cares.

**Comment by edreamleo** [comment]
@ktenney I was way too lazy yesterday.  This should be fixable.

**Comment by edreamleo** [comment]
The fix was surprisingly easy.  Everything works in my tests.

createCommonButton now calls iconBar.setCommandForButton with command_p = p and p.copy(). That's all that is needed to preserve p's position indefinitely!

**Comment by ktenney** [comment]
Looking good! off to the races!

I was able to provoke a bug:
bad code in an @rclick button crashes Leo hard.
one of the @rclick buttons consisted of:
g.es(gnx)

the traceback:

exception executing script
Traceback (most recent call last):

  File "/opt/fetching/leo-editor/leo/core/leoCommands.py", line 643, in
executeScript
    c.executeScriptHelper(args, define_g, define_name, namespace, script)

  File "/opt/fetching/leo-editor/leo/core/leoCommands.py", line 690, in
executeScriptHelper
    exec(compile(script, scriptFile, 'exec'), d)

  File "/opt/fetching/leo-editor/leo/test/scriptFile.py", line 3, in
<module>
    g.es(gnx)

NameError: name 'gnx' is not defined

Traceback (most recent call last):
  File "/opt/fetching/leo-editor/leo/core/leoCommands.py", line 643, in
executeScript
    c.executeScriptHelper(args, define_g, define_name, namespace, script)
  File "/opt/fetching/leo-editor/leo/core/leoCommands.py", line 690, in
executeScriptHelper
    exec(compile(script, scriptFile, 'exec'), d)
  File "/opt/fetching/leo-editor/leo/test/scriptFile.py", line 3, in
<module>
    g.es(gnx)
NameError: name 'gnx' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/fetching/leo-editor/leo/plugins/qt_frame.py", line 2512, in cb
    script=script,
  File "/opt/fetching/leo-editor/leo/plugins/mod_scripting.py", line 597,
in executeScriptFromButton
    c.executeScript(args=args, p=p, script=script, silent=True)
  File "/opt/fetching/leo-editor/leo/core/leoCommands.py", line 648, in
executeScript
    g.handleScriptException(c, script_p, script, script1)
  File "/opt/fetching/leo-editor/leo/core/leoGlobals.py", line 6742, in
handleScriptException
    c.goToScriptLineNumber(n, p)
  File "/opt/fetching/leo-editor/leo/core/leoCommands.py", line 1696, in
goToScriptLineNumber
    c.gotoCommands.find_script_line(n, p)
  File "/opt/fetching/leo-editor/leo/commands/gotoCommands.py", line 126,
in find_script_line
    self.success(lines, n, offset, p)
  File "/opt/fetching/leo-editor/leo/commands/gotoCommands.py", line 384,
in success
    c.redraw(p)
  File "/opt/fetching/leo-editor/leo/core/leoCommands.py", line 2541, in
redraw
    c.frame.tree.select(p)
  File "/opt/fetching/leo-editor/leo/core/leoFrame.py", line 1525, in select
    val = self.selectHelper(p, scroll=scroll)
  File "/opt/fetching/leo-editor/leo/core/leoFrame.py", line 1551, in
selectHelper
    assert p.v.context == c
AssertionError

**Comment by edreamleo** [comment]
On Wed, Jan 24, 2018 at 9:52 AM, Kent Tenney <notifications@github.com>
wrote:

> Looking good! off to the races!
>
> I was able to provoke a bug:
> bad code in an @rclick button crashes Leo hard.
>

​Wow.  You have found a very weird path through what was supposed to be
fully protected code.  I'll fix this soon.

Edward

**Comment by edreamleo** [comment]
On Wed, Jan 24, 2018 at 2:24 PM, Edward K. Ream <edreamleo@gmail.com> wrote:

Wow.  You have found a very weird path through what was supposed to be
> fully protected code.  I'll fix this soon.
>

​This is a new kind of crash--p.v.context is not always c with global
buttons. Rev 46df3da should fix it.  Let me know if it doesn't.

Edward
