### ISSUE TITLE
--session-restore causes failure on first launch

### ISSUE THREAD

**Issue by ktenney** [leo-editor/leo-editor#659]
I run Leo from a script with the options --session-save --session-restore
I find myself deleting ~/.leo to troubleshoot what might be cache related issues.
Leo fails to start with the script, assuming an existing session save,
after starting via
 launchLeo.py workfile.leo --save-session
my start script works

**Comment by edreamleo** [comment]
On Fri, Jan 26, 2018 at 12:20 PM, Kent Tenney <notifications@github.com>
wrote:

> I run Leo from a script with the options --session-save --session-restore
> I find myself deleting ~/.leo to troubleshoot what might be cache related
> issues.
> Leo fails to start with the script, assuming an existing session save,
> after starting via
> ​​
> launchLeo.py workfile.leo --save-session
> my start script works
>
> ​The proper line be:

​
    launchLeo.py workfile.leo --session-save

not:

​
    launchLeo.py workfile.leo --save-session ​

​The following works for me with the workbook.leo cache cleared:

    leo --session-save

If you still have problems, please run from a console and report the entire
contents of the console. When I run leo --save-session from a console I get:

c:...\launchLeo.py --gui=qttabs  --gui=qttabs --save-session

Usage: launchLeo.py [options] file1, file2, ...

launchLeo.py: error: no such option: --save-session

Edward

**Comment by edreamleo** [comment]
I am going to close this.  Please reopen if the problem persists with --session-save.

**Comment by ktenney** [comment]
Sorry, I mistakenly thought it would be easy to reproduce.
This is the traceback I get:

Leo 5.6, build 20180126083839, Fri Jan 26 08:38:39 CST 2018
Git repo info: branch = master, commit = 5d7ac069c8b1
Python 3.6.3, PyQt version 5.9.3
linux
** isPython3: True
** caching disabled

Traceback (most recent call last):
  File "/opt/fetching/leo-editor/launchLeo.py", line 8, in <module>
    leo.core.runLeo.run()
  File "/opt/fetching/leo-editor/leo/core/runLeo.py", line 74, in run
    g.app.loadManager.load(fileName, pymacs)
  File "/opt/fetching/leo-editor/leo/core/leoApp.py", line 2204, in load
    ok = lm.doPostPluginsInit()
  File "/opt/fetching/leo-editor/leo/core/leoApp.py", line 2830, in
doPostPluginsInit
    c = c1 = g.app.windowList[0].c
IndexError: list index out of range

**Comment by edreamleo** [comment]
On Sat, Jan 27, 2018 at 8:13 AM, Kent Tenney <notifications@github.com>
wrote:

> Sorry, I mistakenly thought it would be easy to reproduce.
> This is the traceback I get:
>
​[snip]

> File "/opt/fetching/leo-editor/leo/core/leoApp.py", line 2830, in
> doPostPluginsInit
> c = c1 = g.app.windowList[0].c
> IndexError: list index out of range
>

​I don't see this, but I'll add a guard nevertheless.

Edward

**Comment by edreamleo** [comment]
Rev 91f4bcb adds the guard.  Please reopen if problems remain.

**Comment by edreamleo** [comment]
On Sat, Jan 27, 2018 at 8:45 AM, Kent Tenney <notifications@github.com>
wrote:

>
> The 'show tips' feature is great, I find myself restarting
> Leo to see them!
>

​Glad you like them.

You can see them all in LeoDocs.leo or on Leo's Tips Page
<http://leoeditor.com/tutorial-tips.html>.

Edward
