### ISSUE TITLE
Feature Request - Tips

### ISSUE THREAD

**Issue by technatica** [leo-editor/leo-editor#660]
Would it be possible to have a "See Next Tip" button in the tip window?

**Comment by edreamleo** [comment]
On Sat, Jan 27, 2018 at 9:46 AM, Chris George <notifications@github.com>
wrote:

> Would it be possible to have a "See Next Tip" button in the tip window?
>
​Try 3179fc0.

Edward

**Comment by technatica** [comment]
Perfect, thanks.

Chris
