### ISSUE TITLE
Using leoBridge from script should not affect global cache data

### ISSUE THREAD

**Issue by vitalije** [leo-editor/leo-editor#661]
While experimenting with another issue #658, I have discovered that my recent files list was cut short. It seems to me that opening file from a bridge should be excluded from the list of recent files. I don't know if it changes any other part of global Leo usage data. In my opinion running a script that uses leoBridge should leave no traces on personal Leo usage data.

**Comment by edreamleo** [comment]
Please reopen if problems remain.
