### ISSUE TITLE
Support searches spanning multiple .leo files

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#670]
[This post](https://groups.google.com/forum/#!topic/leo-editor/z1q1TymmwSg) by @tbnorth contains a script to search across multiple Leo files.  It should be generalized and made part of Leo's core, as with c.recursiveImport. This would be an important new capability.

**Comment by tbnorth** [comment]
My approach doesn't search @<file>s though.  Ville's plugin bigdash does, it generates an index of files for really fast searching with web search like results.  Not sure if it's still working / dependencies... well at least the search function is working, I forget the exact process for updating the index.

It has a dependency on `whoosh`... installing python[3]-whoosh fixes that.  Looks like it has a bug in search in Python 3 now.  But still works in Python 2.  So this is a pretty comprehensive solution, already done, worth fixing / doc'ing / promoting.

**Comment by tbnorth** [comment]
Ok, it needs a little TLC, I guess there's a crash when you click a link, but it's definitely worth resurrecting, it's a very complete search solution.  Even gives results for offline files.

**Comment by edreamleo** [comment]
This issue isn't so interesting now that LepPluginsRef.leo has been merged into LeoPyRef.leo.
