### ISSUE TITLE
Create a Leo version of pyfilesystem

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#676]
Leo could become a file system using [pyfilesystem](https://docs.pyfilesystem.org/en/latest/).

**Comment by ktenney** [comment]
OK, this one I remember and still understand.

pyfilesystem (now pyfilesystem2)
https://github.com/PyFilesystem/pyfilesystem2

provides tooling such that a Leo file could be treated thusly:
# cd myfile.leo
# ls .
 top level node
# cd top level node
# ls .
# node1
   node2
   node3
# cat node2
This is the body of the node with the headline node2 ...

To do that requires defining a few methods:
https://pyfilesystem2.readthedocs.io/en/latest/implementers.html#essential-methods

Opens up possibilities ...

**Comment by edreamleo** [comment]
@ktenney Thanks for these helpful comments.

**Comment by edreamleo** [comment]
I am going to close this issue.

The Won'tDo label now tracks those issues that have too little interest for me.  This label makes it easy to track such things.
