### ISSUE TITLE
Added new file modification attributes to vnodes

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#677]
ctime, atime, mtime.

**Comment by ktenney** [comment]
OK, that's what the timestamp.py plugin does, I've been using
it for years without problems. Have yet to make use of the timestamps:
things like: list nodes in order of creation, access, modification

**Comment by tbnorth** [comment]
See also `find-quick-timeline` which lists nodes in reverse creation order in the Nav pane based on creation time / ordering implied by gnx.

**Comment by edreamleo** [comment]
Thanks for these comments.  I'll close this issue.
