### ISSUE TITLE
Use the tools that Leo supports

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#681]
There is much to be learned this way.

- [ ] [atom](https://atom.io/docs) is built on electron.
- [ ] [cmap](http://cmap.ihmc.us/): **To do**.
- [ ] [docear](http://www.docear.org/): **To do**.
- [ ] [electron](https://electronjs.org/docs): **To do**. 
- [ ] [jupyter](http://jupyter.org/) and [IPython](https://ipython.org/): In progress.
- [ ] [org mode](https://orgmode.org/): In progress.
- [ ] [LaTex](https://www.latex-tutorial.com/tutorials/): In progress.
- [ ] [PanDoc](https://pandoc.org/): **To do**.
- [ ] [TiddlyWiki](https://tiddlywiki.com/): In progress
- [ ] [xiki](http://xiki.org/): **To do**. See #671 and the leoscreen.py plugin.

And plugins, especially those mentioned recently:

- [ ] backlink.py: Allows arbitrary links between nodes.
- [ ] leoscreen.py: Allows interaction with shell apps via screen.
- [ ] valuespace.py: Supports per-Leo-outline namespaces.
      This plugin creates live objects.  Would it be possible to use them for auto-completion?

And essential python tools:

- [x] [virtualenv](https://virtualenv.pypa.io/en/stable/): This has destroyed my previous Anaconda3 environment.
- [ ] Use Anaconda's conda manager to [manage separate environments](https://conda.io/docs/user-guide/tasks/manage-environments.html)
    This is proper way to set up environments in the Anaconda world.

**Comment by technatica** [comment]
FYI, Docear is dead. No further development, no bug fixing.

The one killer feature it had was the ability to extract metadata (notes, highlighting etc.) from pdf files and somewhat organize the information. It took them a while to solve the basic problem which was that there was no one pdf reader that was available on all three major platforms that wrote this metadata in a consistent manner that allowed them to extract it.

The workflow was for a researcher to be able to read and annotate a pdf and then later bring that pdf into docear and have the annotations available for searching.

It might make for an interesting plugin to duplicate that functionality but it applies to a pretty small group of users (university students/professor types).

**Comment by tbnorth** [comment]
On Thu, 04 Jul 2019 08:27:05 -0700
Chris George <notifications@github.com> wrote:

> FYI, Docear is dead. No further development, no bug fixing.
> 
> The one killer feature it had was the ability to extract metadata
> (notes, highlighting etc.) from pdf files and somewhat organize the
> information. It took them a while to solve the basic problem which
> was that there was no one pdf reader that was available on all three
> major platforms that wrote this metadata in a consistent manner that
> allowed them to extract it.
> 
> The workflow was for a researcher to be able to read and annotate a
> pdf and then later bring that pdf into docear and have the
> annotations available for searching.
> 
> It might make for an interesting plugin to duplicate that
> functionality but it applies to a pretty small group of users
> (university students/professor types).

I've written a stand alone app. for that that maybe I should clean up
and share.  It depends on qt bindings to poppler, I'm not sure how
widely available they are - i.e. Ubuntu package vs. anaconda install on
windows etc.  Full dependencies:

import bibtexparser
from bibtexparser.bparser import BibTexParser
import popplerqt5
import PyQt5
from lxml import etree as ET
from lxml.builder import E

It uses PyQt for base types, it has no interface, just parses a PDF or
PDFs listed in a bibtex file for annotations.  Output to HTML with
links back to the PDFs, or JSON output, which of course Leo could take
in.

Cheers -Terry

**Comment by edreamleo** [comment]
On Thu, Jul 4, 2019 at 8:27 AM Chris George <notifications@github.com>
wrote:

> FYI, Docear is dead. No further development, no bug fixing.
>
Heh.  I had forgotten about docear and #681.

Edward
