### ISSUE TITLE
pylint with django

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#683]
After `cp pylint-leo-rc-ref.txt  .leo/pylint-leo-rc.txt`

I wrote django code. When I run `pylint` in command line, then some other error displayed:

>E:319,31: Class 'SpareName' has no 'objects' member (no-member)
E:332,41: Class 'Spare' has no 'objects' member (no-member)
E:356,28: Class 'Spare' has no 'objects' member (no-member)
E:379,37: Class 'Spare' has no 'objects' member (no-member)
E:386,24: Class 'Spare' has no 'objects' member (no-member)
E:413,41: Class 'Spare' has no 'objects' member (no-member)
E:441,37: Class 'Spare' has no 'objects' member (no-member)

Should I `pip install pylint-django`

Would you teach me how to configure or run it?

How to run with --load-plugins pylint_django?

Thanks a lot!

**Comment by edreamleo** [comment]
On Thu, Feb 1, 2018 at 7:02 PM, wangzhaohe <notifications@github.com> wrote:

> After cp pylint-leo-rc-ref.txt .leo/pylint-leo-rc.txt
>
> I wrote django code. When I run pylint in command line, then some other
> error displayed:
>
> E:319,31: Class 'SpareName' has no 'objects' member (no-member)
> E:332,41:
> ​​
> Class 'Spare' has no 'objects' member (no-member)
> E:356,28: Class 'Spare' has no 'objects' member (no-member)
> E:379,37: Class 'Spare' has no 'objects' member (no-member)
> E:386,24: Class 'Spare' has no 'objects' member (no-member)
> E:413,41: Class 'Spare' has no 'objects' member (no-member)
> E:441,37: Class 'Spare' has no 'objects' member (no-member)
>
> Should I pip install pylint-django
>
> Would you teach me how to configure or run it?
>
> How to run with --load-plugins pylint_django?
>
​Googling:

    pylint django ​ Class 'Spare' has no 'objects' member (no-member)

yields:

    https://stackoverflow.com/questions/45135263/class-has-no-objects-member

Do any of the answers help? This is all I know.

Edward

**Comment by edreamleo** [comment]
I am going to close this issue.  It's not really a Leo problem.

If the answer above doesn't help, please ask your question again at [leo-editor](http://leoeditor.com/).

**Comment by wangzhaohe** [comment]
ok, thanks!

I can run `pylint --load-plugins pylint_django` in console.

I only want to konwn how to add `--load-plugins pylint_django` parameter in leo-editor.

This is not important, thanks for your answer.
