### ISSUE TITLE
The viewrendered2 plugin is not compatible with PyQt5

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#687]
Leo Log Window
Leo 5.7b1, build 20180202062051, Fri Feb  2 06:20:51 CST 2018
Git repo info: branch = master, commit = 9057d5b38c18
Python 3.5.2, PyQt version 5.5.1
linux
isPython3: True
caching enabled
setting leoID from os.getenv('USER'): 'swot'
load dir: /home/swot/leo-editor/leo/core
global config dir: /home/swot/leo-editor/leo/config
home dir: /home/swot
reading settings in /home/swot/leo-editor/leo/config/leoSettings.leo
reading settings in /home/swot/.leo/myLeoSettings.leo
conflicting key bindings in myLeoSettings.leo
   all BackSpace do-nothing
  text BackSpace backward-delete-char
conflicting key bindings in myLeoSettings.leo
   all Delete do-nothing
  text Delete delete-char
**The viewrendered2 plugin is not compatible with PyQt5**
http serving enabled at 127.0.0.1:8130
reading settings in /home/swot/.leo/workbook.leo
redefining abbreviation ,, 
from "{|{x='__NEXT_PLACEHOLDER'}|}" to '__NEXT_PLACEHOLDER'
The viewrendered2 plugin is not compatible with PyQt5
loadOnePlugin: can not load enabled plugin: leo.plugins.viewrendered2
reading: /home/swot/.leo/workbook.leo
read 6 files in 0.34 seconds
read outline in 0.58 seconds

**Comment by wangzhaohe** [comment]
after use viewrendered.py, but Warning: viewrendered.py running without docutils.

docutils has been install by pip3

Leo Log Window
Leo 5.7b1, build 20180202062051, Fri Feb  2 06:20:51 CST 2018
Git repo info: branch = master, commit = 9057d5b38c18
Python 3.5.2, PyQt version 5.5.1
linux
isPython3: True
caching enabled
setting leoID from os.getenv('USER'): 'swot'
load dir: /home/swot/leo-editor/leo/core
global config dir: /home/swot/leo-editor/leo/config
home dir: /home/swot
reading settings in /home/swot/leo-editor/leo/config/leoSettings.leo
reading settings in /home/swot/.leo/myLeoSettings.leo
conflicting key bindings in myLeoSettings.leo
  text BackSpace backward-delete-char
   all BackSpace do-nothing
conflicting key bindings in myLeoSettings.leo
  text Delete delete-char
   all Delete do-nothing
Warning: viewrendered.py running without docutils.
http serving enabled at 127.0.0.1:8130
reading settings in /home/swot/.leo/workbook.leo
redefining abbreviation ,, 
from "{|{x='__NEXT_PLACEHOLDER'}|}" to '__NEXT_PLACEHOLDER'
reading: /home/swot/.leo/workbook.leo
read 6 files in 0.38 seconds
read outline in 0.58 seconds

**Comment by edreamleo** [comment]
On Fri, Feb 2, 2018 at 9:03 PM, wangzhaohe <notifications@github.com> wrote:

> after use viewrendered.py, but Warning: viewrendered.py running without
> docutils.
>
> docutils has been install by pip3
>
​Thanks for this.  I'd like to fix this for Leo 5.7 final.

Edward

**Comment by edreamleo** [comment]
The message "The viewrendered2 plugin is not compatible with PyQt5" is issued by the VR2 plugin itself.

This is a known issue. It is not scheduled for any particular release at this time.

**Comment by edreamleo** [comment]
This is not my plugin and am not committed to it.

**Comment by edreamleo** [comment]
I am going to close this issue. The VR2 plugin is deprecated.
