### ISSUE TITLE
line number disappear after add-editor

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#690]
line number disapaer after run command add-editor

Could any tell me how to config this?

Thanks!

**Comment by edreamleo** [comment]
I see this behavior.  It is now scheduled for Leo 5.8.

**Comment by vitalije** [comment]
5417f87 fixes disappearance of line numbers, however, when switching editors line numbers are changing but they are still attached to first body editor. Perhaps they should move to the active editor.

Fixing this possibly would require more time than I can spend now.
