### ISSUE TITLE
setup.py and g.gitDescribe() broken: "list index out of range"

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#692]
```
(leo-minimal) C:\test\leo-editor
>pip install -e .
Obtaining file:///C:/test/leo-editor
    Complete output from command python setup.py egg_info:
    fatal: No names found, cannot describe anything.
    Removing build and dist directories
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\test\leo-editor\setup.py", line 101, in <module>
        version=git_version(),
      File "C:\test\leo-editor\setup.py", line 32, in git_version
        tag, distance, commit = g.gitDescribe(root)
      File "C:\test\leo-editor\leo\core\leoGlobals.py", line 4468, in gitDescribe
        tag, distance, commit = describe[0].split('-')
    IndexError: list index out of range

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\test\leo-editor\
```

**Comment by edreamleo** [comment]
On Sat, Feb 3, 2018 at 5:31 PM, matt wilkie <notifications@github.com>
wrote:

>       File "C:\test\leo-editor\leo\core\leoGlobals.py", line 4468, in gitDescribe
>         tag, distance, commit = describe[0].split('-')
>     IndexError: list index out of range
>
> ​I'll fix this crash immediately.

Edward

**Comment by maphew** [comment]
it's just not robust enough to handle either dot or dash as delimiters. I think using [semantic_version](https://github.com/rbarrois/python-semanticversion) module to handle the parsing is a better approach. It's lightweight and didn't take me too long to figure out. See #691

**Comment by edreamleo** [comment]
@maphew Ok.  I'll wait for your work.

**Comment by maphew** [comment]
Believe to be fixed. Please re-open if any problems found

**Comment by edreamleo** [comment]
Thanks for this work, Matt.
