### ISSUE TITLE
show-next-tip display overlapped in Python 2.7.12, PyQt version 4.8.7

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#693]
show-next-tip

![image](https://user-images.githubusercontent.com/2628013/35773416-a9e4fbb4-098c-11e8-974f-913e22abd743.png)

>Leo Log Window
Leo 5.7b1, build 20180203163829, Sat Feb  3 16:38:29 CST 2018
Git repo info: branch = master, commit = ef381c893583
Python 2.7.12, PyQt version 4.8.7
linux2
isPython3: False
caching enabled
setting leoID from os.getenv('USER'): 'swot'
load dir: /home/swot/leo-editor/leo/core
global config dir: /home/swot/leo-editor/leo/config
home dir: /home/swot
reading settings in /home/swot/leo-editor/leo/config/leoSettings.leo
reading settings in /home/swot/.leo/myLeoSettings.leo
conflicting key bindings in myLeoSettings.leo
  text BackSpace backward-delete-char
   all BackSpace do-nothing
conflicting key bindings in myLeoSettings.leo
  text Delete delete-char
   all Delete do-nothing
http serving enabled at 127.0.0.1:8130
reading settings in /home/swot/.leo/workbook.leo
redefining abbreviation ,, 
from u"{|{x='__NEXT_PLACEHOLDER'}|}" to u'__NEXT_PLACEHOLDER'
reading: /home/swot/.leo/workbook.leo
read 6 files in 0.39 seconds
read outline in 0.58 seconds

**Comment by edreamleo** [comment]
Different code may be needed depending on Qt version.  Simpler code can be use in PyQt5.

**Comment by edreamleo** [comment]
Rev aae86c2 works around this issue by not showing the checkbox for Qt4 installations.

This is surprisingly difficult to fix.  I am going to close this issue.  All contributions gratefully accepted ;-)
