### ISSUE TITLE
show-next-tip dialog's close icon doesn't work

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#694]
Both in PyQt version 4.8.7 and PyQt version 5.5.1

![image](https://user-images.githubusercontent.com/2628013/35773483-060731bc-098f-11e8-8aab-641760f0ef84.png)

Leo 5.7b1, build 20180203163829, Sat Feb  3 16:38:29 CST 2018
Git repo info: branch = master, commit = ef381c893583
Python 3.5.2, PyQt version 5.5.1
linux
isPython3: True

**Comment by edreamleo** [comment]
The windowCloseButtonCheckBox needs to be enabled. See [this page](http://doc.qt.io/archives/qt-4.8/qt-widgets-windowflags-example.html)

**Comment by technatica** [comment]
Is this a Windows thing?

The original tip box, for me, included an OK button that would close the
tip box. The X in the corner of the window also worked to close the tip box.

Then I requested the "Show Next Tip" button and my next session showed that
it worked great. Both methods of closing the tip box continued to work.

Now I have "Show Next Tip", "OK" and "Close".

OK and Close both appear to have the exact same function, namely to close
the tip window.

Or, more likely, I am totally confused again.

Chris

Leo 5.7b1, build 20180205161155, Mon Feb  5 16:11:55 CST 2018
Git repo info: branch = master, commit = 5371be1c7205
Python 3.6.3, PyQt version 5.6.2
linux
isPython3: True
caching enabled

**Comment by edreamleo** [comment]
On Mon, Feb 5, 2018 at 4:34 PM, Chris George <notifications@github.com>
wrote:

> Is this a Windows thing?
>

​Maybe.  I didn't check Linux.

>
> The original tip box, for me, included an OK button that would close the
> tip box. The X in the corner of the window also worked to close the tip
> box.
>
> Then I requested the "Show Next Tip" button and my next session showed that
> it worked great. Both methods of closing the tip box continued to work.
>
> Now I have "Show Next Tip", "OK" and "Close".
>

​Oops.  I see this on Linux and Windows.​


OK and Close both appear to have the exact same function, namely to close
> the tip window.
>
> Or, more likely, I am totally confused again.
>

​It's not you ;-)  ​I'm going to revert the change as not being
worthwhile.  There may be a way, but several hours of work have not
revealed it.

Edward

**Comment by edreamleo** [comment]
I am not going to work more on this. It's a nit, and very hard to get right.  All contributions gratefully accepted.
