### ISSUE TITLE
ImportError: No module named 'PyQt4'

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#696]
use abbreviations like below:

    {if spare_init_queryset};;

Traceback (most recent call last):

  File "/home/swot/leo-editor/leo/plugins/qt_events.py", line 131, in eventFilter
    k.masterKeyHandler(event)

  File "/home/swot/leo-editor/leo/core/leoKeys.py", line 3332, in masterKeyHandler
    k.handleUnboundKeys(event, char, stroke)

  File "/home/swot/leo-editor/leo/core/leoKeys.py", line 3670, in handleUnboundKeys
    k.masterCommand(event=event, stroke=stroke)

  File "/home/swot/leo-editor/leo/core/leoKeys.py", line 3761, in masterCommand
    expanded = c.abbrevCommands.expandAbbrev(event, stroke)

  File "/home/swot/leo-editor/leo/commands/abbrevCommands.py", line 285, in expandAbbrev
    self.expand_text(w, i, j, val, word, expand_search)

  File "/home/swot/leo-editor/leo/commands/abbrevCommands.py", line 313, in expand_text
    val, do_placeholder = self.make_script_substitutions(i, j, val)

  File "/home/swot/leo-editor/leo/commands/abbrevCommands.py", line 452, in make_script_substitutions
    exec(content, c.abbrev_subst_env, c.abbrev_subst_env)

  File "<string>", line 1, in <module>

  File "<string>", line 84, in django_tag

ImportError: No module named 'PyQt4'

***

>Abbreviations...
""";;=@language python\n"""\n<||>{|{x=file_name()}|} - <|describe|>\n\n{|{x=user_name()}|}, {|{x=time.asctime()}|}\n"""\n\nimport os\nimport sys\n\ndef main():\n    <|code|>\n\nif __name__ == '__main__':\n    main()\n
,,=__NEXT_PLACEHOLDER
;;;={|{x=long_word()}|}
<;;={|{x=close_xml()}|}
>;;={|{x=html_tag()}|}
class;;=class {|{\nx=ask("Class name",default=c.p.h.replace('class ',''))}|}(object):\n    """{|{x=get("Class name")}|} - <|describe class|>\n    """\n\n    def __init__(self{|{\nx = ask("__init__ params, comma sep.");\nif x: x = ", " + x}|}):\n        """<|describe init|>{|{x=param_doc("__init__ params, comma sep.")}|}\n        """\n        <|code|>\n\n    @others
csv-table;;=.. csv-table::\n   :header: "<|col 1|>", "", "", ""\n   :widths: 1, 1, 1, 1\n\n   <|data|>
date;;={|{x=time.asctime()}|}
def;;=def {|{x=ask("function name",default=c.p.h)}|}({|{x=in_class()}|}{|{x=ask("Params, comma sep.")}|}):\n    """{|{x=get("function name")}|} - Return <|return|>{|{x=param_doc()}|}\n    """\n\n    <|code|>
html;;=<html>\n<head>\n<title><|title|></title>\n<style>\n</style>\n</head>\n<body>\n<|content|>\n</body>\n</html>
python;;=@first #! /usr/bin/env python\n@first # -*- coding: utf-8 -*-\n@language python\n@tabwidth -4\n@others
ts;;={|{x=time.strftime("%Y%m%d%H%M%S")}|}
tss;;={|{x=time.strftime("%Y%m%d")}|}
};;={|{django_tag();x=''}|}

***

>Leo Log Window
Leo 5.7b1, build 20180203163829, Sat Feb  3 16:38:29 CST 2018
Git repo info: branch = master, commit = ef381c893583
Python 3.5.2, PyQt version 5.5.1
linux
isPython3: True
caching enabled
setting leoID from os.getenv('USER'): 'swot'
load dir: /home/swot/leo-editor/leo/core
global config dir: /home/swot/leo-editor/leo/config
home dir: /home/swot
reading settings in /home/swot/leo-editor/leo/config/leoSettings.leo
reading settings in /home/swot/.leo/myLeoSettings.leo
conflicting key bindings in myLeoSettings.leo
  text BackSpace backward-delete-char
   all BackSpace do-nothing
conflicting key bindings in myLeoSettings.leo
  text Delete delete-char
   all Delete do-nothing
Warning: viewrendered.py running without docutils.
http serving enabled at 127.0.0.1:8130
reading settings in /home/swot/.leo/workbook.leo
redefining abbreviation ,, 
from "{|{x='__NEXT_PLACEHOLDER'}|}" to '__NEXT_PLACEHOLDER'
reading: /home/swot/.leo/workbook.leo
read 6 files in 0.37 seconds
read outline in 0.55 seconds

**Comment by wangzhaohe** [comment]
only
};;={|{django_tag();x=''}|}
report error

**Comment by tbnorth** [comment]
I've pushed a fix to the 5.8-dev branch, 5428907.  This issue will be closed automatically when that branch is merged into master.  You can fix your local setup by searching leoSettings.leo and myLeoSettings.leo for
```python
from PyQt4 import QtCore
```
and replacing with
```python
from leo.core.leoQt import QtCore
```

**Comment by wangzhaohe** [comment]
Thanks a lot!

Only change myLeoSettings.leo, it can work well.

If change leoSettings.leo, next `git pull` will report error.
