### ISSUE TITLE
can not load enabled plugin: leo.plugins.startfile

### ISSUE THREAD

**Issue by tscv11** [leo-editor/leo-editor#698]
This started happening when I switched to linux but I don't know if that's what caused the problem.
I guess it's self-explanatory.

Leo Log Window
Leo 5.7b1, build 20180129114713, Mon Jan 29 11:47:13 CST 2018
Not running from a git repo
Python 3.5.2, PyQt version 5.5.1
linux
isPython3: True
caching enabled
loadOnePlugin: can not load enabled plugin: leo.plugins.startfile
reading: /home/tsc/.leo/myLeoSettings.leo
read outline in 0.65 seconds
wrote recent file: /home/tsc/.leo/.leoRecentFiles.txt
saved: myLeoSettings.leo

tscv11

**Comment by edreamleo** [comment]
This plugin works only if os.startfile is available, that is, only on Windows.  Rev c0dfcd6 adds a message to this effect.
