### ISSUE TITLE
loadOnePlugin: can not load enabled plugin: leo.plugins.viewrendered

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#702]
Leo Log Window
Leo 5.7b1, build 20180205170654, Mon Feb  5 17:06:54 CST 2018
Git repo info: branch = master, commit = c8e13c3bccdc
Python 2.7.12, PyQt version 4.8.7
linux2
isPython3: False
caching enabled
setting leoID from os.getenv('USER'): 'swot'
load dir: /home/swot/leo-editor/leo/core
global config dir: /home/swot/leo-editor/leo/config
home dir: /home/swot
reading settings in /home/swot/leo-editor/leo/config/leoSettings.leo
reading settings in /home/swot/.leo/myLeoSettings.leo
conflicting key bindings in myLeoSettings.leo
  text BackSpace backward-delete-char
   all BackSpace do-nothing
conflicting key bindings in myLeoSettings.leo
  text Delete delete-char
   all Delete do-nothing
http serving enabled at 127.0.0.1:8130
reading settings in /home/swot/.leo/workbook.leo
redefining abbreviation ,, 
from u"{|{x='__NEXT_PLACEHOLDER'}|}" to u'__NEXT_PLACEHOLDER'
loadOnePlugin: error importing plugin: leo.plugins.viewrendered
Traceback (most recent call last):

  File "/home/swot/leo-editor/leo/core/leoPlugins.py", line 514, in loadOnePlugin
    __import__(moduleName)

  File "/home/swot/leo-editor/leo/plugins/viewrendered.py", line 197, in <module>
    from leo.core.leoQt import phonon, QtMultimedia, QtSvg, QtWebKitWidgets

ImportError: cannot import name QtMultimedia

loadOnePlugin: can not load enabled plugin: leo.plugins.viewrendered
reading: /home/swot/.leo/workbook.leo
read 6 files in 0.37 seconds
read outline in 0.55 seconds

**Comment by wangzhaohe** [comment]
https://stackoverflow.com/questions/19642960/qmediaplayer-not-available-in-pyqt4

**Comment by edreamleo** [comment]
d0983fa likely fixed this.  Please reopen if problems remain.
