### ISSUE TITLE
update_md markdown not available: using rst

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#705]
@enabled-plugins --> viewrendered.py

when use `@language md`

***

Leo 5.7b1, build 20180207025238, Wed Feb  7 02:52:38 PST 2018
Git repo info: branch = master, commit = ef164adf9e76
Python 3.5.2, PyQt version 5.5.1
linux
** isPython3: True
** caching enabled

reading settings in /home/swot/.leo/workbook.leo
redefining abbreviation ,, 
from "{|{x='__NEXT_PLACEHOLDER'}|}" to '__NEXT_PLACEHOLDER'
redefining abbreviation ,, 
from "{|{x='__NEXT_PLACEHOLDER'}|}" to '__NEXT_PLACEHOLDER'
`update_md markdown not available: using rst`
QXcbWindow: Unhandled client message: "_COMPIZ_TOOLKIT_ACTION"

**Comment by edreamleo** [comment]
On Wed, Feb 7, 2018 at 5:30 AM, wangzhaohe <notifications@github.com> wrote:


> update_md markdown not available: using rst
>

​The message means that markdown has not been installed on your machine.
Using restructured text instead is a reasonable fallback.

Edward

**Comment by wangzhaohe** [comment]
ok, thanks!
After `pip3 install markdown` and restart `python launchLeo.py`
It run well.
