### ISSUE TITLE
@theme leo_dark theme 0 Outline Pane with white background color in python3.6 pyqt5.10

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#706]
**Python 3.6.4, PyQt version 5.10.0**

![python36pyqt510](https://user-images.githubusercontent.com/2628013/35952252-1ee75120-0cba-11e8-9988-d43d3021e737.png)

**Should I install some modules?**

***

Leo Log Window
Leo 5.7b1, build 20180207025238, Wed Feb  7 02:52:38 PST 2018
Git repo info: branch = master, commit = 76ef88eac5eb
**Python 3.6.4, PyQt version 5.10.0**
linux
isPython3: True
caching enabled
redefining abbreviation ,, 
from "{|{x='__NEXT_PLACEHOLDER'}|}" to '__NEXT_PLACEHOLDER'
reading: /home/swot/.leo/myLeoSettings.leo
read outline in 0.21 seconds
10:15:45 saved: myLeoSettings.leo

**Comment by tbnorth** [comment]
Try the theme attached to this issue:
https://github.com/leo-editor/leo-editor/issues/595

**Comment by wangzhaohe** [comment]
After used darkleo.leo.zip, it worked fine.

Thanks a lot!

[darkleo.leo.zip](https://github.com/leo-editor/leo-editor/files/1705902/darkleo.leo.zip)

**Comment by edreamleo** [comment]
@tbnorth Thanks Terry.
