### ISSUE TITLE
LeoBridge not explicitly closing the Leo-Editor file leaves the Leo-Editor file open

### ISSUE THREAD

**Issue by SegundoBob** [leo-editor/leo-editor#716]
### Issue
If LeoBridge opens a Leo-Editor file and then does not explicitly close the Leo-Editor file, then the Leo-Editor file is left marked "open" and the next time the file is opened, Leo-Editor displays a warning such as:
```
The following files may already be open
in another copy of Leo:

/pri/git/leo_bug_demos/2018-02-06-leoBridge-left-open/x.le
```
### [Related Issue 658](https://github.com/leo-editor/leo-editor/issues/658)

vitalije's work around for Issue 658 is to never explicitly close a Leo-Editor file opened by LeoBridge.  This new issue shows that his work around is not ideal.

### [Gist to Reproduce this Issue](https://gist.github.com/SegundoBob/674c39504e987ffd53c544b92f86126e)

The command lines for these scripts are:
```
python open_and_close.py path-to-Leo-Editor-file
python open_no_close.py path-to-Leo-Editor-file
```
### Guess

I noticed this problem when a script I've been using for several years began to cause the open file warnings.  I use the script every few months, so my guess is that this problem started some time between 2017-10 and 2018-02.

### Test System
```
Leo 5.7b1, build 20180211171008, Sun Feb 11 17:10:08 CST 2018
Git repo info: branch = master, commit = 556f1de79c86
Python 2.7.12, LeoGui: dummy version
linux2
** isPython3: False
** caching enabled
----------------------------------------------------------------------
$ python3 open_no_close.py x.leo
setting leoID from os.getenv('USER'): 'bob'

Leo 5.7b1, build 20180211171008, Sun Feb 11 17:10:08 CST 2018
Git repo info: branch = master, commit = 556f1de79c86
Python 3.5.2, LeoGui: dummy version
linux
** isPython3: True
** caching enabled

Opening "x.leo"
reading settings in /pri/git/leo_bug_demos/2018-02-11-LeoBridge-no-explicit-close/x.leo
2018-02-11 16:26:18 /pri/git/leo_bug_demos/2018-02-06-leoBridge-left-open

**Comment by edreamleo** [comment]
On Sun, Feb 11, 2018 at 6:31 PM, SegundoBob <notifications@github.com>
wrote:

> Issue
>
> If LeoBridge opens a Leo-Editor file and then does not explicitly close
> the Leo-Editor file, then the Leo-Editor file is left marked "open" and the
> next time the file is opened, Leo-Editor displays a warning
>
​...

> vitalije's work around for Issue 658 is to never explicitly close a
> Leo-Editor file opened by LeoBridge.
>
​Iirc, the workaround was not to close .leo files until the bridge itself
is ready to close.

Edward

**Comment by SegundoBob** [comment]
On 02/11/2018 10:46 PM, Edward K. Ream wrote:
>> vitalije's work around for Issue 658 is to never explicitly close a
>> Leo-Editor file opened by LeoBridge.
>>
> ​Iirc, the workaround was not to close .leo files until the bridge itself
> is ready to close.

That was vitalije's first suggestion, but it did not work.  See

https://github.com/leo-editor/leo-editor/issues/658#issuecomment-361008594

vigtalije's second suggestion

https://github.com/leo-editor/leo-editor/issues/658#issuecomment-361057407

"For now, my advice is just to skip call to cmdrX.close(). I don't
expect anything bad to happen if you just skip it."

-- 
Segundo Bob
SegundoBob@gmail.com

**Comment by edreamleo** [comment]
@SegundoBob I'd like to fix this for 5.7 final.

**Comment by vitalije** [comment]
I have added a guard to prevent remembering open Leo documents when using leoBridge. This fixes this issue.

**Comment by edreamleo** [comment]
On Fri, Feb 23, 2018 at 6:56 AM, Виталије Милошевић <
notifications@github.com> wrote:

> I have added a guard to prevent remembering open Leo documents when using
> leoBridge. This fixes this issue.
>

​Many thanks for this, Vitalije.  I had no idea what the problem was.

And thanks for your other recent work. It is greatly appreciated.

Edward

**Comment by vitalije** [comment]
@edreamleo don't mention it. It was my pleasure.

**Comment by SegundoBob** [comment]
vitalije,

Thank you for fixing this bug.  I value the warnings against concurrent, multiple opens of a Leo-Editor file, but this bug rendered the warnings meaningless for me.

I verified the fix for
### Test System
```
Leo 5.7b2, build 20180223195002, Fri Feb 23 19:50:02 UTC 2018
Git repo info: branch = master, commit = b50029bc4e72
Python 3.5.2, PyQt version 5.5.1
linux
```

**Comment by edreamleo** [comment]
On Fri, Feb 23, 2018 at 5:34 PM, SegundoBob <notifications@github.com>
wrote:

> Thank you for fixing this bug.
>
​And thanks for the confirmation.

Edward
