### ISSUE TITLE
clean-recent-files does nothing by default

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#719]
rf.cleanRecentFiles does nothing if c.config.getData('path-demangle') is empty, which it is by default.

That *is* ok because Leo's startup logic removes files from the recent files list if they no longer exist.

**Comment by tbnorth** [comment]
On Mon, 12 Feb 2018 11:56:26 -0800
"Edward K. Ream" <notifications@github.com> wrote:

> rf.cleanRecentFiles starts with:
> 
> ```python
> def cleanRecentFiles(self, c):
>     '''Remove items from the recent files list that are no longer
> valid.''' dat = c.config.getData('path-demangle')
>     if not dat:
>         g.es('No @data path-demangle setting')
>         return
> ```
> This can't be right. Instead, cleaning recent files should remove
> files that no longer exists.

Sure, although that's a different functionality.

the de-mangle thing, which I know you asked me to doc. and which I know
I didn't get to yet, converts paths like

/mnt/usr1/usr1/tbrown/Packages/leo

to

/home/tbrown/Packages/leo

fixing the problem arising when Leo or I suspect in some hard to fix
cases OS functions convert the path the user accessed / wants to see to
a more canonical form (perhaps without symlinks etc.).

So I think (trying to get this reply to you before it's too late ;-)
current clean files does the demangle thing and removes resulting
dupes.  Checking for existing files and removing if not would be
something new, I think.

**Comment by edreamleo** [comment]
Rev 3998154 closes this item, with a minor refactoring.

It would good to document the exact form of `@data path-demangle`, but that can and should be done in comments in the `@data node itself`.

**Comment by tbnorth** [comment]
On Mon, 12 Feb 2018 20:30:26 +0000 (UTC)
"Edward K. Ream" <notifications@github.com> wrote:

> Rev 3998154 closes this item, with a minor refactoring.
> 
> It would good to document the exact form of `@data path-demangle`,
> but that can and should be done in comments in the `@data node
> itself`.

Heh, turns out this was done in
https://github.com/leo-editor/leo-editor/commit/462b08d57c77 - do you
not remember May 9, 2008? :)  Unfortunately it was immediately deleted
by a subsequent merge (by me), perhaps not too surprising given the
number of branches and merges happening at the time.

**Comment by edreamleo** [comment]
On Mon, Feb 12, 2018 at 2:52 PM, Terry Brown <notifications@github.com>
wrote:

> It would good to document the exact form of `@data path-demangle`,
> > but that can and should be done in comments in the `@data node
> > itself`.
>
> Heh, turns out this was done in
> https://github.com/leo-editor/leo-editor/commit/462b08d57c77 - do you
> not remember May 9, 2008? :) Unfortunately it was immediately deleted
> by a subsequent merge (by me), perhaps not too surprising given the
> number of branches and merges happening at the time.
>

​I now see the comments in leoSettings.leo.  Thanks for getting rid of this
hangnail.

Edward
