### ISSUE TITLE
setup.py broken when installing from zipball: execGitCommand not available

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#720]
```
>pip install --upgrade https://github.com/leo-editor/leo-editor/archive/5.7b2.zip
Collecting https://github.com/leo-editor/leo-editor/archive/5.7b2.zip
  Downloading https://github.com/leo-editor/leo-editor/archive/5.7b2.zip
     \ 11.4MB 4.9MB/s
    Complete output from command python setup.py egg_info:
    Removing build and dist directories
    execGitCommand not found: C:\Users\mattw\AppData\Local\Temp\pip-usj2xnee-build\.git
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\mattw\AppData\Local\Temp\pip-usj2xnee-build\setup.py", line 115, in <module>
        version=git_version(__file__),
      File "C:\Users\mattw\AppData\Local\Temp\pip-usj2xnee-build\setup.py", line 30, in git_version
        tag, distance, commit = g.gitDescribe(root)
      File "C:\Users\mattw\AppData\Local\Temp\pip-usj2xnee-build\leo\core\leoGlobals.py", line 4468, in gitDescribe
        tag, distance, commit = describe[0].rsplit('-',2)
    TypeError: 'NoneType' object is not subscriptable
```

I didn't run into this before because my tests (since working in the git version feature) from a folder with Leo source in it. Note to self: test all access points! They are not equivalent.

**Comment by edreamleo** [comment]
On Tue, Feb 13, 2018 at 1:15 AM, matt wilkie <notifications@github.com>
wrote:

> I didn't run into this before because my tests (since working in the git
> version feature) from a folder with Leo source in it. Note to self: test
> all access points! They are not equivalent.
>
​Does this need to be fixed before 5.7 final?  That is, should it have the
Blocker label? Or can it be fixed later?

Edward

**Comment by maphew** [comment]
I added blocker. It's breaks installing with pip on clean or new environments.

**Comment by maphew** [comment]
I started on a fix but it's not clean yet, pushed into a separate branch. I don't know if I'll be able to finish by friday.

**Comment by edreamleo** [comment]
On Thu, Feb 15, 2018 at 12:48 AM, matt wilkie <notifications@github.com>
wrote:

> I started on a fix but it's not clean yet, pushed into a separate branch.
> I don't know if I'll be able to finish by friday.
>
​Thanks for this heads up. Given your description, I agree that we should
delay 5.7.  That's not a problem.  Please commit your work to master I'll
create a 5.8-dev branch for all ​other work.

Edward

**Comment by maphew** [comment]
I think this issue is closed. I've uploaded a package to PyPi, `leo-5.7b2.dev27`, which installs successfully on Win7x64 for Python 3.6 and Python 2.7, miniconda environments.
