### ISSUE TITLE
replace-all can not be saved with crtl + s

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#722]
In **Find** tab, input search string and replaced string, click **Replace All**, then it run success.
But after saved files with **Ctrl + S**, only .leo file saved, other @files can not be saved.

Please have a check about this phenomenon, thanks!

Leo Log Window
Leo 5.7b2, build 20180213093313, Tue Feb 13 09:33:13 CST 2018
Git repo info: branch = master, commit = 7d4fd35a615a
Python 2.7.12, PyQt version 4.8.7
linux2
isPython3: False
caching enabled
redefining abbreviation ,, 
from u"{|{x='__NEXT_PLACEHOLDER'}|}" to u'__NEXT_PLACEHOLDER'
reading: /home/swot/pyenv/xservice36/code/XService.leo
read 73 files in 0.80 seconds
read outline in 1.06 seconds
**changed 3 instances in 0.06 sec.**
wrote recent file: /home/swot/.leo/.leoRecentFiles.txt
**13:42:32 saved: XService.leo**

**Comment by edreamleo** [comment]
On Wed, Feb 14, 2018 at 11:48 PM, wangzhaohe <notifications@github.com>
wrote:

> In *Find* tab, input search string and replaced string, click *Replace
> All*, then it run success.
> But after saved files with *Ctrl + S*, only .leo file saved, other @files
> can not be saved.
>
​The problem is likely that the replace-all command does not set @<file>​
nodes dirty.

This will be easy to fix, but it will have to wait until after 5.7 final.

Edward

**Comment by edreamleo** [comment]
@vitalije Thanks for fixing this.

**Comment by wangzhaohe** [comment]
replace-all can not be saved with crtl + s

This BUG appear again. Please have a check, thanks!

***

Leo 5.7.4 devel, build 20180727113027, Fri, Jul 27, 2018 11:30:27 AM
Git repo info: branch = devel, commit = 2f9bab64a9f1
Python 3.6.5, PyQt version 5.10.1
linux
** isPython3: True

reading settings in /home/swot/.leo/workbook.leo
