### ISSUE TITLE
Setting put_expansion_bits_in_leo_files in a non-settings Leo-Editor file is always ignored.

### ISSUE THREAD

**Issue by SegundoBob** [leo-editor/leo-editor#732]
Setting put_expansion_bits_in_leo_files in a non-settings Leo-Editor file is always ignored.

Setting put_expansion_bits_in_leo_files in leoSettings.leo and in myLeoSettings.leo work, but in all other Leo-Editor files this setting is ignored.

I noticed this because I wanted to save the expansion bits in only one or two Leo-Editor files.

This may be the way it must be.  Maybe it is considered not work fixing.  But on the Leo-Editor forum EKR claimed that it worked. See [Forum Post by EKR](https://groups.google.com/d/msg/leo-editor/h0COPCr_UaQ/PGP_M6SYDgAJ)

### Test System
```
Leo 5.7b1, build 20180211171008, Sun Feb 11 17:10:08 CST 2018
Git repo info: branch = master, commit = 556f1de79c86
Python 3.5.2, PyQt version 5.5.1
linux
isPython3: True
```[](url)

**Comment by edreamleo** [comment]
On Sat, Feb 17, 2018 at 6:11 PM, SegundoBob <notifications@github.com>
wrote:

> Setting put_expansion_bits_in_leo_files in a non-settings Leo-Editor file
> is always ignored.
>
​Thanks for this report.  It's on the list for early 5.8 devel.​

Edward

**Comment by vitalije** [comment]
If put_expansion_bits_in_leo_files is set to False in myLeoSettings.leo and you add in one of your outlines local setting `@bool put_expansion_bits_in_leo_files=True`, and save outline, the changed settings value will be used next time you open this file.

Solution would be to execute command `reload-settings` before saving your outline. 
Perhaps 'save' command can be changed to update local settings before actually doing save, but that may hurt 'save' command performance.

**Comment by SegundoBob** [comment]
Thanks for explaining something that I should have realized for myself.

Now that I understand how settings work in general.  I think put_expansion_bits_in_leo_files works correctly; and I see no need to change how it works.

I doubt that it would be helpful to note somewhere in the documentation that changing a setting does not have an immediate effect because settings are only processed on file open and when minibuffer commands reload-settings and reload-all-settings are executed.  This level of detail will only be absorbed by an ordinary reader when the reader is focused on the issue of when settings changes take effect.  That is, an ordinary reader 99.99% of the time would not absorb the information.

**Comment by edreamleo** [comment]
> I doubt that it would be helpful [to document this].

I agree.  I am closing this issue.
