### ISSUE TITLE
Predefine script_p and script_gnx values in Leo scripts

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#736]
c.executeScriptHelper could optionally predefine script_p and script_gnx symbols for Leo scripts.

A new keyword arg, say script_p, would be added to c.executeScript, c.executeScriptHelper and g.executeScript.  The relevant code in c.executeScript helper would become:
```
    d = {'c': c, 'g': g, 'input': g.input_, 'p': p} if define_g else {}
    if define_name: d['__name__'] = define_name
    d['script_args'] = args or []
    if script_p:
        d['script_p'] = script_p.copy()
        d['script_gnx'] = script_p.v.gnx
    if namespace: d.update(namespace)
```
cff's show that there are:

- Maybe 4 significant calls to c.executeScript in leoPy.leo
- Maybe a dozen calls to c.executeScript or g.executeScript (a thin wrapper) in leoPlugins.leo.

Imo, these new predefined symbols have very little chance of breaking existing scripts.  If problems do arise, this feature could be disabled with a user setting.

**Comment by vitalije** [comment]
798497c adds script_gnx to list of predefined variables. Its value is gnx of the node that defined script. One should keep in mind that it can happen that the current commander doesn't have node with such gnx  (buttons defined in settings outlines for example).

To find position (if it exists in current outline), one can use:
```python
script_v = c.fileCommands.gnxDict.get(script_gnx)
script_p = c.vnode2position(script_v) if script_v else None
# before using script_p, check if it is not None
```

**Comment by edreamleo** [comment]
798497c does not affect Leo's execute-script command.  I'll fix this today.

**Comment by vitalije** [comment]
>  I'll fix this today (@edreamleo )
Sorry, I've got this one first :smile:

**Comment by edreamleo** [comment]
On Fri, Feb 23, 2018 at 1:23 PM, Виталије Милошевић <
notifications@github.com> wrote:

> I'll fix this today (@edreamleo <https://github.com/edreamleo> )
> Sorry, I've got this one first 😄
>
> ​Thanks for this.  All this last-minute work is helpful.

Edward
