### ISSUE TITLE
Allow turning off icon in headline of @<file type> 

### ISSUE THREAD

**Issue by ktenney** [leo-editor/leo-editor#737]
Leo replaces @auto etc. with an icon, which is stored in the UA for the node.

It 'de-clutters' the headline in Leo, but adds ~2000 characters to the UA for the node.
I would prefer the headline be plain text, the icon data not in the UA.

Thanks,
Kent

**Comment by edreamleo** [comment]
On Wed, Feb 21, 2018 at 12:20 PM, Kent Tenney <notifications@github.com>
wrote:

> Leo replaces @auto <https://github.com/auto> etc. with an icon, which is
> stored in the UA for the node.
>
> It 'de-clutters' the headline in Leo, but adds ~2000 characters to the UA
> for the node.
> I would prefer the headline be plain text, the icon data not in the UA.
>
Try searching for "clutter" in leoSettings.leo.

Edward

**Comment by edreamleo** [comment]
No changes needed to Leo's settings or Leo's code.

**Comment by ktenney** [comment]
Well, that's embarrassing. I had a stray @bool tree-declutter = True in
myLeoSettings.leo

Next attempt to be annoying:

@rclick buttons defined in myLeoSettings.leo work fine in work files,
and <alt-x> <@rclick command name> works fine in the myLeoSettings.leo
file, but in the work files, <alt-x> <@rclick command name> is unknown.

Now, I'm quite sure this has worked in the past, but I could be mistaken,
I often am.

Thanks,
Kent

**Comment by ktenney** [comment]
Excellent!
