### ISSUE TITLE
Links in "Leo Tips" dialog should be clickable

### ISSUE THREAD

**Issue by satishgoda** [leo-editor/leo-editor#738]
The "Leo Tips" dialog is a very welcome feature and is great for reiterating some of the core and useful features of Leo. Some of the tips have links to further reading but at the moment, cannot be clicked or copied.

To improve the utility of the information presented by the dialog, can we please make the text selectable and hyperlinks to be clickable.

**Comment by edreamleo** [comment]
a907fc5 completes this item by using html in all tips using links.

**Comment by SatishGodaPearl** [comment]
Awesome, Thank you @edreamleo :)

**Comment by edreamleo** [comment]
On Wed, Jun 13, 2018 at 1:56 AM, Satish Goda <notifications@github.com>
wrote:

> Awesome, Thank you @edreamleo <https://github.com/edreamleo> :)
>
​You're welcome.

Edward
