### ISSUE TITLE
@rclick buttons not generating commands in work files

### ISSUE THREAD

**Issue by ktenney** [leo-editor/leo-editor#739]
@rclick *buttons* defined in myLeoSettings.leo work fine in work files,
and <alt-x> <@rclick command name> works fine in the myLeoSettings.leo
file, but in the work files, <alt-x> <@rclick command name> is unknown.

**Comment by vitalije** [comment]
I don't know how to reproduce this problem. I have never used '@rclick'. @ktenney can you please provide step by step procedure how someone like me (who never used '@rclick') can see the issue.

The only thing that I have noticed is that you spell it 'RClick' but I don't expect that capitalization would make problem. Yet, you may try with lower case letters.

**Comment by vitalije** [comment]
@edreamleo while I was looking in this issue, I have noticed that ScriptingController.registerAllCommands receives tag argument but it never uses it. All other methods that make call to registerAllCommands provide different values for the tag argument but this method doesn't use it. It is strange that pyflakes doesn't complain about it.

**Comment by ktenney** [comment]
Hmm, not finding the documentation for @rclick

given the following
@settings
  @buttons
    @button multicommand
       @rclick doathing
           <python code>
       @rclick doanotherthing
           <python code>

There will be a button 'multicommand'
which does nothing when clicked

A right click on the button 'multicommand'
presents a drop-down with the choice of
'doathing'
'doanotherthing'

Someone please correct me if I'm wrong in my description,
and point to the proper documentation

**Comment by LewisNeal** [comment]
I didn't find any documentation for @rclick, but your example code is well written and quite suitable for use in LeoDocs :)
Used you instructions and constructed a set of 2 buttons using @rclick. They work fine for me when present in a work file.
I wasn't able to reproduce the problem you had.

Leo 5.7b2, build 20180223195002, Fri Feb 23 19:50:02 UTC 2018
Git repo info: branch = master, commit = b50029bc4e72
Python 3.6.4, PyQt version 5.10.0
Windows 10 AMD64 (build 10.0.16299) SP0

**Comment by vitalije** [comment]
789d64b should fix the issue. Please check and reopen if it didn't.

**Comment by vitalije** [comment]
9a53a5c1f contains some improvements. Leo now won't register commands for at-rclick organizer nodes (=nodes with empty body). That makes list of registered at-rclick commands shorter, easier to navigate.

**Comment by LewisNeal** [comment]
Hi  Vitalije,
I didn't have any problem with commit = b50029b
But now running 789d64b the @rclick buttons have stopped working.

**Comment by vitalije** [comment]
@LewisNeal how do you mean stop working? Please give me some more details.

**Comment by LewisNeal** [comment]
If I right-clicked over the menu button, it didn't display the multi-level command options. This only occurred with 789d64b
However I have just updated to 9a53a5c and right-click over the menu button displays the multi-level command options, which work again.

**Comment by edreamleo** [comment]
On Fri, Feb 23, 2018 at 2:03 PM, Виталије Милошевић <
notifications@github.com> wrote:

> @edreamleo <https://github.com/edreamleo> while I was looking in this
> issue, I have noticed that ScriptingController.registerAllCommands
> receives tag argument but it never uses it. All other methods that make
> call to registerAllCommands provide different values for the tag argument
> but this method doesn't use it. It is strange that pyflakes doesn't
> complain about it.
>
​Afaik, pyflakes never complains about unused keyword arguments.  I think
this is wise.

Edward

**Comment by edreamleo** [comment]
On Fri, Feb 23, 2018 at 2:48 PM, Kent Tenney <notifications@github.com>
wrote:

> Hmm, not finding the documentation for @rclick
>

leoSettings.leo documents all the nodes used there: About this file,
leoSettings.leo.

Rev d2a7ed5 copies this node to LeoDocs.leo:

  Leo's Documentation-->Users Guide-->Customizing Leo-->
  @rst html\customizing.html-->Specifying settings-->
  Complex settings nodes-->\@rclick

Lewis, feel free to edit as you like :-)

Edward

**Comment by vitalije** [comment]
It is not just unused parameter but the method overwrite the value of this parameter before using it. That perhaps can be considered a bug, or it deserves a warning. For example:
```python
def meth1(self, arg1, arg2='something'):
     for arg2 in [ 'something else',]:
           ....
```

**Comment by edreamleo** [comment]
On Sat, Feb 24, 2018 at 5:08 AM, Виталије Милошевић <
notifications@github.com> wrote:

> It is not just unused parameter but the method overwrite the value of this
> parameter before using it.
>
​Rev cf39804 fixes this.  The tag keyword argument is almost always used
for debugging, telling the context of the call.  The actual use of tag was
separate.  The fix was to change tag to prefix in the actual code.

And all tests pass ;-)

Edward
