### ISSUE TITLE
Execute leo_startup.py on startup

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#740]
Most programmable editors allow users to execute scripts at startup.

**Status**

The startup branch contains working code.  However, I wonder whether this issue is even worth documenting.  It smacks of featuritis.  This feature is not really needed. Users already can use plugins to customize Leo in any conceivable way.  This is a bit clumsy, but #296: "Support private plugin directories" might ease the pain.

**Notes**

1. leo_startup.py is not a serious security risk because the new code looks for leo_startup.py only in ~ and ~./leo.

2. Leo's startup code executes leo_startup.py as early as possible, with the following bindings:

    {'c': None, 'g': g, 'p': None}

2. It's easy to schedule code to be executed later:
```python
def hook(tag, keys):
     g.trace(tag, keys)
g.registerHandler('open1', hook)
```

**Comment by ktenney** [comment]
Could @scripting nodes require granting permission the first time,
optionally showing the code to be run?

The hash of the code is then stored as 'safe'

When code has a hash which is deemed safe, it is allowed.

**Comment by tbnorth** [comment]
On Sat, 24 Feb 2018 11:32:23 +0000 (UTC)
"Edward K. Ream" <notifications@github.com> wrote:

> Most programmable editors allow users to execute scripts at startup.
> 
> We have discussed this before, but I think it's time to do this.
> There are at present two ways to work around the lack of this feature:
> 
> 1. Write a plugin: too clumsy.
> 2. Enable `@scripting` nodes: way too dangerous.

Does the OP know about @script nodes?  I'm not sure the existing
mechanism wouldn't be enough, maybe they just don't know how to set it
up?

Cheers -Terry

**Comment by edreamleo** [comment]
On Sat, Feb 24, 2018 at 7:48 AM, Kent Tenney <notifications@github.com>
wrote:

> Could @scripting nodes require granting permission the first time,
> optionally showing the code to be run?
>
> The hash of the code is then stored as 'safe'
>
> When code has a hash which is deemed safe, it is allowed.
>

​An excellent idea.  ​I have just created #741
<https://github.com/leo-editor/leo-editor/issues/741> as a separate
enhancement.

Edward

**Comment by edreamleo** [comment]
The startup branch contains working code. 

There should be no serious security issues, because the code looks for leo_startup.py only in ~ and ~./leo.

However, I am dithering whether this issues is worth documenting.  It smacks of featuritis.  #296: Support private plugin directories might be a better solution.

**Comment by edreamleo** [comment]
I am going to close this.  Imo, it's probably not worth doing.
