### ISSUE TITLE
Body panel title not changed after add-editor

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#751]
There is a little problem atfer `add-editor`.

![add-editor-bug](https://user-images.githubusercontent.com/2628013/36788929-c1abfcd8-1cca-11e8-95f0-ddc6e1ad5e02.png)

**Comment by tbnorth** [comment]
I'm seeing the bug as worse than headline not changing, leftmost editor just never gets focus properly or changes at all.  Git bisect:
```
cd2a067e4a1795cf6497ab7cbe60f39fc3d39374 is the first bad commit
commit cd2a067e4a1795cf6497ab7cbe60f39fc3d39374
Author: Edward K. Ream <edreamleo@gmail.com>
Date:   Wed Nov 22 11:45:02 2017 -0600

    updated declutter docs in leoSettings.leo
    
    Leo build: 20171122114502
```
that only touches leoSettings.leo, hard to believe it's responsible. Will keep looking.

**Comment by edreamleo** [comment]
On Fri, Mar 2, 2018 at 3:16 PM, Terry Brown <notifications@github.com>
wrote:

> I'm seeing the bug as worse than headline not changing, leftmost editor
> just never gets focus properly or changes at all. Git bisect:
>
> cd2a067e4a1795cf6497ab7cbe60f39fc3d39374 is the first bad commit
> commit cd2a067e4a1795cf6497ab7cbe60f39fc3d39374
> Author: Edward K. Ream <edreamleo@gmail.com>
> Date:   Wed Nov 22 11:45:02 2017 -0600
>
>     updated declutter docs in leoSettings.leo
>
>     Leo build: 20171122114502
>
> that only touches leoSettings.leo, hard to believe it's responsible. Will
> keep looking.
>
​Thanks for these investigations.  I agree, it's hard to believe that
particular commit is responsible.

Edward

**Comment by tbnorth** [comment]
Ok, now
```
dc2eb786bde437029d010b279478bd278148b2be is the first bad commit
commit dc2eb786bde437029d010b279478bd278148b2be
Author: Edward K. Ream <edreamleo@gmail.com>
Date:   Fri Feb 9 17:09:40 2018 -0600

    Improved show-spell-info
    
    Leo build: 20180209170940
```

**Comment by edreamleo** [comment]
On Fri, Mar 2, 2018 at 4:35 PM, Terry Brown <notifications@github.com>
wrote:

> Ok, now
>
> dc2eb786bde437029d010b279478bd278148b2be is the first bad commit
> commit dc2eb786bde437029d010b279478bd278148b2be
> Author: Edward K. Ream <edreamleo@gmail.com>
> Date:   Fri Feb 9 17:09:40 2018 -0600
>
>     Improved show-spell-info
>
>     Leo build: 20180209170940
>
>
​Still mysterious.  Hard to believe that an spelling command that is not
executed could affect this issue. And still harder to believe that changing
what g.es_print prints is involved.

Edward

**Comment by tbnorth** [comment]
Finger now pointing at 2881fedd9dd36735d911413fbe5ba5325af9579b is the first bad commit

**Comment by edreamleo** [comment]
On Fri, Mar 2, 2018 at 8:05 PM, Terry Brown <notifications@github.com>
wrote:

> Finger now pointing at 2881fed
> <https://github.com/leo-editor/leo-editor/commit/2881fedd9dd36735d911413fbe5ba5325af9579b>
> is the first bad commit
>
​Thanks for this.  Still weird, but I'll investigate asap.

Edward

**Comment by tbnorth** [comment]
I don't think 2881fed is it either, for some reason git bisect just doesn't seem to work on this.  It may be that triggering the bug is even more tricky, required step wise, then I realized with the "bug only manifests after you've changed the selected node in the rightmost editor" observation.  So it shows up fairly inevitably as you're using multiple editors, but it's easy to fail to realize what you're doing to trigger it when  just trying to get it to show as quickly as possible during bisect.

Inclined to suspect ad24917a, but only because it touches the relevant code recently - found by git blame, not git bisect.

**Comment by edreamleo** [comment]
On Sun, Mar 4, 2018 at 4:14 PM, Terry Brown <notifications@github.com>
wrote:

> I don't think 2881fed
> <https://github.com/leo-editor/leo-editor/commit/2881fedd9dd36735d911413fbe5ba5325af9579b>
> is it either, for some reason git bisect just doesn't seem to work on this.
> It may be that triggering the bug is even more tricky, required step wise,
> then I realized with the "bug only manifests after you've changed the
> selected node in the rightmost editor" observation. So it shows up fairly
> inevitably as you're using multiple editors, but it's easy to fail to
> realize what you're doing to trigger it when just trying to get it to show
> as quickly as possible during bisect.
>
> Inclined to suspect ad24917
> <https://github.com/leo-editor/leo-editor/commit/ad24917adcb7bae1accc16c6607be8b1736540b2>,
> but only because it touches the relevant code recently - found by git
> blame, not git bisect.
>

​Thanks for these investigations.

Edward

**Comment by vitalije** [comment]
It seems I am to blame for this issue. When I fixed #690 I have introduced this issue. Now, ef853f0 should fix both.

However, #690 is just partially solved. It prevents disappearance of line numbers, but line numbers are still attached only to first editor.

**Comment by edreamleo** [comment]
On Sat, Apr 28, 2018 at 3:29 PM, Виталије Милошевић <
notifications@github.com> wrote:

> However, #690 <https://github.com/leo-editor/leo-editor/issues/690> is
> just partially solved. It prevents disappearance of line numbers, but line
> numbers are still attached only to first editor.
>
​Do we need a new issue for this?

Edward

**Comment by edreamleo** [comment]
I've just created #881 for this. It's not urgent, but we may as well remember this issue.
