### ISSUE TITLE
line-to-headline command

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#753]
Cut the presently selected body line and replace the headline with it.

Surprisingly useful in some situations.

**Comment by tscv11** [comment]
I would be happy to give this a shot but I can't seem to assign it to myself as suggested - something is preventing it.

**Comment by edreamleo** [comment]
On Fri, Mar 23, 2018 at 2:01 AM, tscv11 <notifications@github.com> wrote:

> I would be happy to give this a shot but I can't seem to assign it to
> myself as suggested - something is preventing it.
>
​I've just sent an invitation for you to join the team.

Edward

**Comment by edreamleo** [comment]
Completed at rev 234852 and documented at rev dd503b.
