### ISSUE TITLE
Improve the Cmds menu

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#765]
- [x] The Cmds menu and submenus should contain more links to help items.
    Be sure to mention all of Leo's major features.

- [x] Leo's menu entries should focus on tasks, not features.
    I am going to decline to do this.
    I've looked at the pycharm menus, and they seem pretty much like Leo's.

Original suggestion:

Users are more interested in what they can do. For a good model, see [pycharm menus](https://www.jetbrains.com/pycharm/), especially their wording of menu entries and their 'Tools' menu.

**Comment by edreamleo** [comment]
Rev a7bb60d completes all the work on this that I am willing to do.

Recommendations for specific changes are always welcome.

**Comment by LewisNeal** [comment]
I just loaded 378d811 and noticed the File>Open Recent Files is blank and not reading .leoRecentFiles.txt

**Comment by technatica** [comment]
Arrgh.

Now I will need to actually remember where the files are. :-)

Chris

**Comment by LewisNeal** [comment]
FYI my leo log pane:
wrote recent file: C:/Users/lewisneal/.leo/.leoRecentFiles.txt

**Comment by edreamleo** [comment]
On Tue, Apr 3, 2018 at 8:46 PM, LewisNeal <notifications@github.com> wrote:

> I just loaded 378d811
> <https://github.com/leo-editor/leo-editor/commit/378d811ab4adf21f30f2b84471b9574a98a10e2a>
> and noticed the File>Open Recent Files is blank and not reading
> .leoRecentFiles.txt
>
​Fixed at b166778be. Sorry about that.  The Recent Files menu is a special
case, and it must have a specific name.

Hmm.  This is going to cause a problem with other languages.

Edward
