### ISSUE TITLE
Valuespace plugin - SyntaxError: EOF while scanning triple-quoted string literal

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#772]
If I run vs-eval on a node it copes with 2 types of comments:
# comments
and triple-quoted comments in the form:
'''test EOF on this line'''

However if triple-quoted comments are used in the form
'''
test EOF on this line
'''
it reports error
SyntaxError: EOF while scanning triple-quoted string literal

**Comment by tbnorth** [comment]
On Sat, 03 Mar 2018 02:04:50 +0000 (UTC)
LewisNeal <notifications@github.com> wrote:

> If I run vs-eval on a node it copes with 2 types of comments:
> # comments
> and triple-quoted comments in the form:
> '''test EOF on this line'''
> 
> However if triple-quoted comments are used in the form
> '''
> test EOF on this line
> '''
> it reports error
> SyntaxError: EOF while scanning triple-quoted string literal

To execute multiple lines you have to select them first - should be
doc'ed.

Cheers -Terry

**Comment by LewisNeal** [comment]
The hash symbol became active in my post and made comments bold :(

My point is that it copes quite well with multi-line comments using the hash-symbol, but not multi-line comments using triple-quotes.

**Comment by tbnorth** [comment]
On Sat, 03 Mar 2018 02:25:10 +0000 (UTC)
LewisNeal <notifications@github.com> wrote:

> The hash symbol became active in my post and made comments bold :(
> 
> My point is that it copes quite well with multi-line comments using
> the hash-symbol, but not multi-line comments using triple-quotes.

Because each hash comment line is valid python by itself, whereas the
''' ''' comment is only valid when taken all together.  It would be a
nice enhancement for it to find the end of the next block - file a
enhancement issue if you want, it would be worth doing.

Cheers -Terry
