### ISSUE TITLE
QDock layout project

### ISSUE THREAD

**Issue by tbnorth** [leo-editor/leo-editor#777]
Use QDocks rather than NestedSplitter to manage pane layout.  qdock-layout branch (qt_docks branch is an older attempt which tries to redo startup code, keeping for reference for now).

Todo:

- [x] create JSON representation of layout
- [x] restore JSON layout
- [x] decide how to ID widgets.  dock_widget.widget()._ns_id vs. object name etc.
     - go with dock_widget.widget()._ns_id just because it avoids conflicts with other uses of .name()
- [ ] manage adding new panes like NestedSplitter provider registration system
- [x] menus for loading / saving different layouts, toggle headings, etc.
- [ ] handle finding of Log, Find, Spell tabs
- [ ] restore layout on load, timing issue?
- [ ] remove NestedSplitter / free_layout
- [ ] save / restore floating windows
- [ ] style splitters with / without titles
- [ ] low pri. / later, support nested docking in floating windows.  Tabbing is supported, but nested docks aren't, and would need a QMainWindow as a wrapper.

**Comment by edreamleo** [comment]
@tbnorth Again, thanks for this. And again, I've added the "Info" and "EKR" labels so I can see it easily.

**Comment by edreamleo** [comment]
I will do nothing further with this project.
