### ISSUE TITLE
Remove Leo directives in style sheets before doing @ constant substitutions

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#780]
Previously, Leo would crash on startup if `@data qt-gui-plugin-style-sheet` contains `@tabwidth -2`.

Rev 8499020 on devel avoids the crash. However, the relevant code should probably remove Leo directives before doing settings substitutions.

Here is an excerpt from the original crash:
```
Traceback (most recent call last):
  ...
  File "c:\leo.repo\leo-editor\leo\plugins\qt_gui.py", line 1899, in set_style_sheets
    sheet = self.expand_css_constants(sheet)
  File "c:\leo.repo\leo-editor\leo\plugins\qt_gui.py", line 1540, in expand_css_constants
    sheet,
  File "c:\Anaconda3\lib\re.py", line 191, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "c:\Anaconda3\lib\re.py", line 326, in _subx
    template = _compile_repl(template, pattern)
  File "c:\Anaconda3\lib\re.py", line 317, in _compile_repl
    return sre_parse.parse_template(repl, pattern)
  File "c:\Anaconda3\lib\sre_parse.py", line 879, in parse_template
    s = Tokenizer(source)
  File "c:\Anaconda3\lib\sre_parse.py", line 227, in __init__
    string = str(string, 'latin1')
TypeError: decoding to str: need a bytes-like object, int found
```

**Comment by edreamleo** [comment]
**Update**: Rev 8499020 on devel avoids the crash.  However, the relevant code should probably remove Leo directives before doing settings substitutions.

**Comment by tbnorth** [comment]
Is g.getScript() insufficient for this?  Will the @constants confuse it?  Personally I'd just keep Leo @directives out of @data nodes, but I guess they can be supported there.  Is the issue a lack of a global list of directives to remove, when you can't just target @.*?

**Comment by edreamleo** [comment]
On Mon, Mar 12, 2018 at 4:07 PM, Terry Brown <notifications@github.com>
wrote:

> Is g.getScript() insufficient for this?
>
​Why do you ask?  We are talking about stylesheets, not python scripts.

In other words, the crash happens in Qt.  Not too slick on Qt's part, but
surely we should catch the exception.

Edward

**Comment by tbnorth** [comment]
On Tue, 13 Mar 2018 13:57:08 -0700
"Edward K. Ream" <notifications@github.com> wrote:

> On Mon, Mar 12, 2018 at 4:07 PM, Terry Brown
> <notifications@github.com> wrote:
> 
> > Is g.getScript() insufficient for this?
> >  
> ​Why do you ask?  We are talking about stylesheets, not python
> scripts.
> 
> In other words, the crash happens in Qt.  Not too slick on Qt's part,
> but surely we should catch the exception.

I guess I thought g.setScript() basically removed Leo directives and
handled @others, which seems appropriate - Leo directives not being
valid in Python scripts or style sheets.

**Comment by edreamleo** [comment]
Probably a bad idea.  The present code is too complex as it is.
