### ISSUE TITLE
ViewRendered Plugin fails on Python 2.7 (Bad Import Statement)

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#781]
In Leo 5.7, Windows 10, 64-bit Python 2.7, the ViewRendered plugin fails because of an incorrect import statement:

# Current code:
from urllib.request import urlopen
>>> from urllib.request import urlopen
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named request

# Works on my system:
from urllib import urlopen

I believe this is a difference between urllib between python 2.7 and 3.x, but I don't have a machine with Python 3.x to try it.  A conditional import should fix this:

try:
    from urllib.request import urlopen
except ImportError:
    from urllib import urlopen

**Comment by edreamleo** [comment]
Rev dfc0487 does the following:
```python
try:
    from urllib.request import urlopen
except ImportError:
    urlopen = None
```
The new code will allow nbconvert to be imported independently of urllib.

Googling shows no difference between python 2/3 imports for urllib.  This may be an installation issue on your machine.

I am going to close this.  Please reopen only if you are sure there is something wrong with the present code.

**Comment by tbpassin** [comment]
Please put the import patch back in.  From the Python 2.7  docs:

    Note
    The urllib module has been split into parts and renamed in Python 3 to urllib.request, urllib.parse, and     urllib.error. The 2to3 tool will automatically adapt imports when converting your sources to Python 3. Also note that the urllib.request.urlopen() function in Python 3 is equivalent to urllib2.urlopen() and that urllib.urlopen() has been removed. 

I have verified this difference between V2.7 and V3.5 on linux Mint (in a virtual machine).  The import failed on v2.7 and succeeded on v3.5.

I imagine there are other places in the code base where this arises, too, but at least we can do this one now that we know about it.

"Rev 9befec8 does the following:

try:
    from urllib.request import urlopen
except ImportError:
    urlopen = None

The new code will allow nbconvert to be imported independently of urllib.

Googling shows no difference between python 2/3 imports for urllib. This may be an installation issue on your machine.

I am going to close this. Please reopen only if you are sure there is something wrong with the present code."

**Comment by edreamleo** [comment]
On Sun, Mar 18, 2018 at 9:15 AM, tbpassin <notifications@github.com> wrote:

> Please put the import patch back in.
>
​Would you do this for me?  I would appreciate it.  Thanks.

Edward
