### ISSUE TITLE
<img src="UNL"> in markdown

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#782]
Blue sky, not too important.  Inspired by question of embedding images in Leo.

A prepass might look for Leo UNL's in the src fields of `<img>` and other items, replacing them.  But by what?

**Comment by tbnorth** [comment]
There's also the background thought about associating BLOBs with nodes, so maybe UNLs can reference the BLOBs associated with nodes somehow, which will probably be clearer when that association is clearer.
