### ISSUE TITLE
Settings/Print Binding Command Fails When Leo Runs Under pythonw

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#783]
Problem:

When running under pythonw, Print Bindings, Print Commands, and Print Settings fail with 

     IOError: [Errno 9] Bad file descriptor

Under running under python, these commands work as expected.  This occurs both from the Settings menu and when using the <alt-x> commands.  However, Print Plugin-info works correctly.

It would seem that the code handles stdout wrongly.

Observed on Leo 5.7b2, Windows 10, 64-bit python 2.7

**Comment by edreamleo** [comment]
Exactly how did you invoke Leo? The following works for me from within Leo:

import os
os.system("leow")

Where leow.bat is:

c:\Anaconda3\pythonw.exe  c:\leo.repo\leo-editor\launchLeo.py --gui=qttabs %*

Invoking leow from a console also works.

**Comment by edreamleo** [comment]
Rev 41c1b1b catches an IOError in g.pr.  Does that help?

**Comment by tbpassin** [comment]
I launched it three different ways with the same result (they are probably really all the same thing):

1) Using the leo.exe file in the Scripts directory.  This actually uses pythonw to run Leo, I believe.
2) pythonw leo\core\runLeo.py
3) pythonw -m leo.core.runLeo

Using python runLeo.py the bindings, etc., print correctly, both to the log pane and to the console.  I'm guessing that under pythonw, these functions try to write to the non-existent console too.

**Comment by tbpassin** [comment]
"Rev 41c1b1b catches an IOError in g.pr. Does that help?"

Yes, that fixes it.  All four "Print XXX" menu items in the Settings menu printed correctly.  A little inelegant, but what the heck!

BTW, the lines above the fix are:

    # Python's print statement *can* handle unicode, but
    # sitecustomize.py must have sys.setdefaultencoding('utf-8')

On Windows, the console won't handle utf-8 - the non-ascii characters - unless it is set to code page 65001.  But the codec module (at least for v2.7, don't know about 3.x) doesn't recognize that code page designation as a proper encoding.  There is a simple patch to work around this, and it might be a good thing to use in Leo, but even then the console can't handle *all* the unicode characters because it isn't a complete utf-8 terminal.  Unicode is *hard*!

**Comment by edreamleo** [comment]
@tbpassin Thanks for the confirmation.  Rev 5a95937 catches all exceptions at the end of g.pr, not just IOError.  I'll close this issue now.
