### ISSUE TITLE
leo_cloud FS type throws KeyError for 'remote'

### ISSUE THREAD

**Issue by tbnorth** [leo-editor/leo-editor#787]

**Comment by edreamleo** [comment]
On Tue, Mar 6, 2018 at 7:16 AM, Terry Brown <notifications@github.com>
wrote:

> Closed #787 <https://github.com/leo-editor/leo-editor/issues/787>.
>

​Thanks for opening and closing this so quickly.

I endorse this work flow.  It's a marker for what has been done, and it
provides an easily found place for further discussions should they become
necessary.

Edward

**Comment by tbnorth** [comment]
On Tue, 06 Mar 2018 13:27:18 +0000 (UTC)
"Edward K. Ream" <notifications@github.com> wrote:

> On Tue, Mar 6, 2018 at 7:16 AM, Terry Brown <notifications@github.com>
> wrote:
> 
> > Closed #787 <https://github.com/leo-editor/leo-editor/issues/787>.
> 
> ​Thanks for opening and closing this so quickly.
> 
> I endorse this work flow.  It's a marker for what has been done, and
> it provides an easily found place for further discussions should they
> become necessary.
> 
> Edward

Really it was just to note it in passing without losing my present
train of thought, and not forget it.  Wasn't sure if I was going to get
to it immediately or not.

Cheers -Terry
