### ISSUE TITLE
Support @load-themes setting

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#790]
The body will contain a list of paths to themes.

Search path will be: 1. User's home directory, 2. leo/themes directory.

Order matters: Later paths on the list will modify earlier themes.  This will allow us to separate syntax coloring and log pane colors from "basic themes".  Something like this:

   LeoBlackTheme.leo
   LeoSolarizedConsoleText.leo
   LeoSolarizedSyntaxColoring.leo.

This will be the foundation upon which Leo's Theme menu will be built.

**Comment by technatica** [comment]
Would it be possible to have an @bool to allow/disallow sandboxing a page's theme to itself only? This would allow an option in the settings tree of the file to call a theme and not have it apply to ALL open files or subsequently opened files in the editor. Files with no theme preference could default to a setting in myLeoSettings.leo.

I can think of applications. Programming files use <theme1>, writing projects use <theme2>, etc.

**Comment by edreamleo** [comment]
On Sun, Mar 11, 2018 at 4:30 PM, Chris George <notifications@github.com>
wrote:

> Would it be possible to have an @Bool <https://github.com/bool> to
> allow/disallow sandboxing a page's theme to itself only?
>
​Do you mean an option to apply a theme to the presently open outline?

Edward

**Comment by technatica** [comment]
I mean that currently when I load a .leo file that contains a theme, it
immediately applies that theme to the entire UI.

I envision being able to have a theme that lives in myLeoSettings.leo that
applies to the entire UI and every open file and every subsequent open
file. (status quo)

Then when I load a file with a theme, it applies ONLY to that file. So I
could have a pink theme that would apply to writing project files, a yellow
theme that applies to programming project files, a green theme that applies
to my collection of recipes file etc. etc.

So the only thing new would be a setting that says @bool-theme-sandbox True
when the new scheme applies and False to keep the status quo.

Under "True" each file on load would be scanned for the existence of an
@load-theme node. If present, it would apply only to that file. If not
present, it would load the theme from myLeoSettings.leo.

This could also allow partial theming. ie. On load the file could load the
myLeoSettings.leo theme and then load an additional stylesheet in the file
to modify certain parts of the UI that would apply only to that file
without having those modifications bleed to all other open files and
subsequently opened files.

Hope that is clearer.

Chris

**Comment by edreamleo** [comment]
I am going to close this issue:

- Leo now users `@string theme-name` to load themes by name.
  This replaces `@load-themes`, which will not be done.
- Recent revs use the `@string theme-name` setting from the first loaded file, or from myLeoSettings.leo, in that order.  That should suffice to Chri's concern.  If not, we probably should open another issue.
