### ISSUE TITLE
recent-log-content

### ISSUE THREAD

**Issue by tbnorth** [leo-editor/leo-editor#791]
Not sure about this.  First thought was that it would be nice to be able to get the things dumped in the log into a node easily, without having to select them in the log and copy / paste.  Biggest reason not to do this is that having to select them in the log and copy / paste just isn't that big a deal.

`recent-log-content`, inserts the last content sent to the log in the body at the cursor position.  Repeated invocations insert the previous content sent to the log at the cursor position, so content ordering is preserved.  So if "a", "b", and "c" had been sent to the log, in that order, "c", "b", and "a" would be inserted, with later insertions pushing earlier insertions down in the body.

### Implementation

A circular buffer of the last 100? 500? items sent to the log.  Track current item, and last item inserted, and move backwards on repeated invocations, re-setting as soon as something new is logged. Not great for thins logged some time ago, but typical usage would be to insert what was just logged now.

**Comment by technatica** [comment]
How hard would it be to do the exact same thing for content dumped to the
terminal?

Or can that be easily done now and I just don't know how?

Chris

**Comment by tbnorth** [comment]
On Wed, 07 Mar 2018 17:46:02 +0000 (UTC)
Chris George <notifications@github.com> wrote:

> How hard would it be to do the exact same thing for content dumped to
> the terminal?

For stuff dumped to the terminal *by Leo*, I guess you could write a
command to pull that in the same way.

For stuff dumped to the terminal by programs Leo invokes (as well as
stuff dumped to the terminal by Leo), you can use the leoscreen.py
plugin, which is *nix only, and requires you run Gnu screen, the
terminal multiplexer, in the terminal.  leoscreen.py can also push
content from the body to the terminal, making any body text an
interactive terminal for any command like program like R or psql etc.

Cheers -Terry

**Comment by tbnorth** [comment]
On Wed, 07 Mar 2018 21:22:38 +0000 (UTC)
Chris George <notifications@github.com> wrote:

> Could it be because of python2/python3?

Looks like there are some issue there.  I used leoscreen a lot when I
was using psql a lot, but that was all Python 2 era.

I think screen needs to be running before you start Leo, and you can
include a newline in what you send to the terminal, but I suspect that
beyond that there will be Py 2/3 issues to resolve.  Will try and have
a look at it at some point.

**Comment by tbnorth** [comment]
On Wed, 07 Mar 2018 21:22:38 +0000 (UTC)
Chris George <notifications@github.com> wrote:

> TypeError: a bytes-like object is required, not 'str'

Actually this seemed to be a fairly isolated problem which is now fixed
in devel.  So leoscreen's working for me in 2/3, not exhaustively
tested, but pushing text to / from the terminal ok.

Cheers -Terry

**Comment by technatica** [comment]
It works flawlessly if I leoscreen-run-all-here. The command is entered
into the screen and responds.

When I use leoscreen-run-text, the command is delivered to the screen, but
not entered.

Chris

**Comment by edreamleo** [comment]
I am not going to do this.  It could be done in a plugin.
