### ISSUE TITLE
Clicking Find Tab should do exactly what pushing Ctrl-F does.

### ISSUE THREAD

**Issue by technatica** [leo-editor/leo-editor#794]
I will often click the "Find" tab to deal with text that is already in the clipboard. As nice as it would be to have the clipboard automatically loaded into the search field, I would be happy with the Ctrl-F behaviour. Clicking Find leaves the focus wherever it is. Ctrl-F switches to the tab and puts the cursor in the box.

I keep clicking the tab and pasting into wherever the cursor was expecting the focus to come with the click of the tab.

**Comment by edreamleo** [comment]
On Thu, Mar 8, 2018 at 2:10 PM, Chris George <notifications@github.com>
wrote:

> I would be happy with the Ctrl-F behaviour. Clicking Find leaves the focus
> wherever it is. Ctrl-F switches to the tab and puts the cursor in the box.
>
​The workaround is to use @bool minibuffer_find_mode = True.

Try it. You might come to like it.

There is an Easter Egg.  After entering the Find text, a tab will let you
enter the replacement text.

Edward​

**Comment by technatica** [comment]
I do like the minibuffer_find_mode. I figured out what is bugging me about clicking the Find tab with the mouse:

When the find pane opens after clicking the tab, the text <find pattern here> is already selected but the cursor is nowhere to be seen. It is initially confusing, then just annoying.

**Comment by edreamleo** [comment]
I am not going to do this.  Mouse clicks in the Find tab have many uses.  It would be difficult to determine exactly what clicks you intend to have special meaning.

Furthermore, as you say yourself, Ctrl-F what you want.  This is not just a workaround, it is the preferred way of doing things.

**Comment by technatica** [comment]
Can you at least remove the deceptive "selected text" when clicking the
find tab with the mouse? At least then it would be clear that a second
click is required to enter the "Find" field.

It is the inconsistent UI aspect that bugs me more than anything.

Chris

**Comment by edreamleo** [comment]
On Wed, Apr 11, 2018 at 8:14 AM, Chris George <notifications@github.com>
wrote:

> Can you at least remove the deceptive "selected text" when clicking the
> find tab with the mouse? At least then it would be clear that a second
> click is required to enter the "Find" field.
>

​I wonder whether we are talking about the same thing.  The Find Tab works
exactly as I expect.

As I understand it, you want a click *anywhere* in an inactive Find tab to
select the Find Text.  But that's not how mouse clicks are supposed to
work.  If you click in the Change Text field you will set in insertion
point.  Double clicks extend the selection.​

​etc. etc.​


It is the inconsistent UI aspect that bugs me more than anything.
>

​Leo does not have any code that handles mouse clicks in the Find Tab. In
other words, you are getting default Qt UI behavior. How is that
inconsistent with anything?

Perhaps I am still misunderstanding your complaint, but unless that is so I
suggest you get more comfortable with Ctrl-F.

Edward

**Comment by tbnorth** [comment]
I think the issue is that clicking on the actual tab,
 ____
/Find\

appears to focus the input text (which is what you'd expect), but
doesn't really.  I agree it needs fixing.  I think there are also some
focus issues with Ctrl-F, although I'd have to remind myself of the
details.

Cheers -Terry

**Comment by technatica** [comment]
Okay, I will try to be clearer.

When I am working in the body pane and click once on the Find tab in the
log pane, it opens the find dialogue with the text <find pattern here>
already selected ie. the foreground text and background are consistent with
selections everywhere in Leo's UI.

Except the insertion point is right where I left it in the body pane, so no
amount of typing my search term reaches the Find field within the Find tab.
In fact, it clutters my work in the body pane, requiring me to not only
clean it up, but then to click again in the Find field three times; once to
set the insertion point and twice quickly to select the <find pattern here>
before typing in my search term.

My original "solution" was to have the insertion point moved to the Find
field at the same time as the click on the Find tab, exactly as Ctrl-F
does. Barring that, removal of the highlighted signal (foreground text and
background style) would remove the deceptive visual cue and be more
consistent with the rest of the UI.

Chris

**Comment by edreamleo** [comment]
Rev 0d125d524 fixes this issue. When you click on the 'Find' tab *itself*, thereby showing the Find tab, Leo now executes the start-search command.

Don't ask for anything more.  I won't do it ;-)

**Comment by edreamleo** [comment]
On Wed, Apr 11, 2018 at 8:57 AM, Terry Brown <notifications@github.com>
wrote:

> I think the issue is that clicking on the actual tab,
>

​Thanks.  At last I see. Fixed at 0d125d52483e.

Edward

**Comment by technatica** [comment]
Here is what I am seeing:

1. Select the outline pane. Don't edit a headline or anything, just select
it.
2. Click the Find tab. One click, with the mouse.

The insertion point is put into the Find dialogue box, complete with the
first word found in the body. The code ignores " " and selects only the
first word itself. If another word is selected in the body text, that word
is inserted into the Find dialogue, which is okay, I guess. But when no
word is selected at all and the focus isn't even in the body pane,
selecting the first word is rather unintuitive.

Chris

**Comment by edreamleo** [comment]
@technatica I'm not seeing this, either on Windows or Linux.  There is no way that start-search command searches the body or outline for anything.  I'm totally confused.

**Comment by technatica** [comment]
Leo 5.7.2 devel, build 20180408225138, Sun Apr 8 22:51:38 PDT 2018
Git repo info: branch = devel, commit = 8d6868edf968
Python 3.6.4, PyQt version 5.10.1
linux
isPython3: True
caching enabled

There are two images attached. before.png and after.png

Before shows the outline pane with the focus. The only thing I did between
this and the after image was to click the mouse once on the Find tab in the
log pane.

The after image shows the first word in the body pane selected and pasted
into the Find dialogue box with the insertion point after it.

If I do not select a string to search, the action of clicking the mouse
selects the first word and pastes it into the box. If I select a string in
the body text it pastes that word into the box with the insertion point
after it. If there is no body text at all in the visible node whether the
focus is on the outline or on the body, the intended action occurs. The
insertion point is placed at the end of the <find pattern here> string and
that string is selected.

This behaviour is exactly the same using python 3.6.4 and pyQt 5.6.2, the
only other python3 environment I have handy.

Using Python 2.7.14, PyQt version 5.10.0, the old behaviour exactly as
detailed in the original issue prevails. The <find pattern here> shows as
being selected, but the insertion point remains in the outline pane or in
the body pane if that is what had the focus before clicking the Find tab.

I hope this can be replicated. I suppose I could setup a VM for further
testing, but my current environment has been pretty robust lately.

Chris

**Comment by technatica** [comment]
Further testing this morning shows that Ctrl-F does the exact same thing as clicking the Find tab.

If there is no string selected and the body contains text, the first word in the body is selected and transferred to the Find dialogue box with the insertion point. If there is no body text in the current node (whether the focus is in the body or the outline), the intended behaviour happens. ie. the <find pattern here> is selected and the insertion point is at the end of that selection.

If a string is selected in the body it is transferred to the Find dialogue box.

Ctrl-F using Python2 displays the original behaviour, the <find pattern here> is selected, but the insertion point is nowhere to be found.
