### ISSUE TITLE
Up Arrow - Select Line in QEditLine

### ISSUE THREAD

**Issue by technatica** [leo-editor/leo-editor#795]
When in single line dialogs it would be helpful if the up arrow selected the line from right to left.

**Comment by technatica** [comment]
Solved with existing commands and key shortcuts.

**Comment by edreamleo** [comment]
@technatica Good.

**Comment by technatica** [comment]
Except the workaround conflicts with default uses for uparrow while in the tree.

The pane mechanism for shortcuts is a good step in the right direction but would only work if the behaviour can be restricted to the QLineEdit widgets.

**Comment by technatica** [comment]
beginning-of-line-extend-selection ! text = Shift-uparrow
move-outline-up             ! tree = Shift-UpArrow

No conflicts. And the intended behaviour.

Closed.

**Comment by edreamleo** [comment]
On Wed, Mar 21, 2018 at 10:17 PM, Chris George <notifications@github.com>
wrote:

> beginning-of-line-extend-selection ! text = Shift-uparrow
> move-outline-up ! tree = Shift-UpArrow
>
> No conflicts. And the intended behaviour.
>
​Thank you for this.

Edward
