### ISSUE TITLE
c.redraw shouldnt change Qt multiple selection state

### ISSUE THREAD

**Issue by Armagedoom** [leo-editor/leo-editor#8]
Leo wipes Qt multiple nodes selection when c.redraw() is called.
This behaviour keeps causing problems, and can happen in different scenarios.
Quoting Terry in this post: http://goo.gl/2nQUN1

"
Create an outline with three top level nodes, A, B, and C 

In the body of node A, put 

nd = g.findNodeAnywhere(c, "C") 
c.selectPosition(nd) 
# c.redraw() 
g.es(len(c.getSelectedPositions())) 

Run (Ctrl-B) this node with and without the commenting out of the 
c.redraw().  Commented out, both nodes are selected as Fidel describes, 
and length of selected nodes is 2.  c.redraw() active, the expected 
behavior is seen, only node C is selected after the code has run. 
"

But I just came back to this bug because, even if the c.redraw() line is commented, this script is still not compatible with Leo buttons.

If you make a script-button of the node "A" (With c.redraw commented), and run the script from the button, the undesired behaviour will happen, thus limiting c.selectPosition() to just being used with "control+B"

Also, I think this bzr bug is somewhat related, just for extra information:

http://goo.gl/13zst6

**Comment by edreamleo** [comment]
I am going to close this issue.  It would be difficult/impossible to maintain the scrolling state after a redraw because the purpose of a redraw is to update the outline.  Neither positions nor scroll state are likely to be preserved, or even meaningful after a redraw.
