### ISSUE TITLE
@color @image display in vr pane

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#802]
There are 2 code examples recently where the vr pane does not display as expected:

Color swatch example:

@color dark-base0 = #fdffdd
  with body:

@language md

<style>div#bg {background:#fdffdd}</style>
<div id="bg"></div><br>
<div id="bg"></div><br>
<div id="bg"></div><br>

and
[How to make Outlines which contains images and can display those images?](https://groups.google.com/forum/#!topic/leo-editor/Gj75Zb0zeY8)

@image
  with body:
  
@ language md

 img style="float:right;" src="<full path to>SplashScreen.ico" alt="Splash"

In the header, if I use the @ symbol for @color and @image respectively, the vr pane does not display the color swatch or image.
Is this a bug, or a recent code change where the use of the @ is not required?

I'm sure the change is recent because the @image code example was working prior to 6c2eef2.

**Comment by edreamleo** [comment]
This has been fixed by eliminating the stylesheet in the VR plugins.
