### ISSUE TITLE
Missing pages on leo-editor

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#805]
​I found and fixed two missing links in LeoDocs.leo:

**fixed**: http://leoeditor.com/tutorial-programming.html
**fixed**: http://leoeditor.com/tutorial-scripting

None of the following links appear in LeoDocs.leo.  They may exist in unreachable pages, but I'm not going to do anything about them unless they cause real problems.

http://leoeditor.com/front.html

Images

http://leoeditor.com/images/newlist.html
http://leoeditor.com/images/openlist.html
http://leoeditor.com/images/delete.html
http://leoeditor.com/images/page_setup.html
http://leoeditor.com/images/print.html
http://leoeditor.com/images/printprev.html
http://leoeditor.com/images/editcut.html
http://leoeditor.com/images/editcopy.html
http://leoeditor.com/images/editpaste.html
http://leoeditor.com/images/find.html
http://leoeditor.com/images/new_item.html
http://leoeditor.com/images/complete.html
http://leoeditor.com/images/owners.html
http://leoeditor.com/images/duedate.html
http://leoeditor.com/images/edit_note.html
http://leoeditor.com/images/mail_item.html
http://leoeditor.com/images/refresh.html
http://leoeditor.com/images/toolbar.html

Slides?

http://leoeditor.com/slides/installation/_static/underscore.html
http://leoeditor.com/slides/installation/index.html
http://leoeditor.com/slides/leo-basics-step-by-step/index.html
http://leoeditor.com/slides/external-files/index.html
http://leoeditor.com/slides/clones-and-views/index.html
http://leoeditor.com/slides/using-leos-minibuffer/index.html
http://leoeditor.com/slides/scripting-leo/index.html
http://leoeditor.com/slides/leo-basics-step-by-step/_sources/slide-010.html

**Comment by edreamleo** [comment]
I am going to close this.  Afaik, the remaining "missing" pages are not accessible via Leo's home page.

**Comment by drmikecrowe** [comment]
@edreamleo 

LMK if you want this as a new issue.  It explains why I was seeing a lot of 404's and couldn't track them down.

[Search for "paste"](http://leoeditor.com/search.html?q=paste&check_keywords=yes&area=default) and click on any link.

Links have an additional '.txt.hml' added to the URL:

* Currently: http://leoeditor.com/cheatsheet.html.txt.html?highlight=paste
* Correct:  http://leoeditor.com/cheatsheet.html?highlight=paste

**Comment by edreamleo** [comment]
On Thu, Mar 15, 2018 at 12:24 PM, drmikecrowe <notifications@github.com>
wrote:

> @edreamleo <https://github.com/edreamleo>
>
> LMK if you want this as a new issue. It explains why I was seeing a lot of
> 404's and couldn't track them down.
>
> Search for "paste"
> <http://leoeditor.com/search.html?q=paste&check_keywords=yes&area=default>
> and click on any link.
>
​Ah. At last I understand. This is related to #789: Searching on LeoEditor
site is broken <https://github.com/leo-editor/leo-editor/issues/789> ​

> ​​
> Links have an additional '.txt.hml' added to the URL:
>
>
>    - Currently: http://leoeditor.com/cheatsheet.html.txt.html?
>    highlight=paste
>    - Correct: http://leoeditor.com/cheatsheet.html?highlight=paste
>
> ​Very helpful clue. I have update the leading comment in #789 with this
info.

Edward
