### ISSUE TITLE
Tip: Maximize Windows

### ISSUE THREAD

**Issue by technatica** [leo-editor/leo-editor#807]
You can maximize the windows. Middle mouse click on the window divider (splitter) to minimize all windows to the left of vertical splitters and below horizontal splitters. 

Using this with "Toggle Split Direction" allows a maximized body, tree or even log window.

**Comment by edreamleo** [comment]
On Tue, Mar 13, 2018 at 12:18 PM, Chris George <notifications@github.com>
wrote:

> You can maximize the windows. Middle mouse click on the window divider
> (splitter) to minimize all windows to the left of vertical splitters and
> below horizontal splitters.
>
> Using this with "Toggle Split Direction" allows a maximized body, tree or
> even log window.
>
​There are automatic ways to size windows at startup.

Two or three command-line options:

    --maximized
    --window-size=500x600   (height x width)
    --session-restore and --session-save (Not sure about this)

And this pair of settings:

    @bool fixedwindow = True
    @data fixedWindowPositionData

And maybe more ;-)

Edward

**Comment by edreamleo** [comment]
Added at 500961033.
