### ISSUE TITLE
Themes dialog doesn't always start in leo/themes

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#809]
Terry reports this. 

The fix was to qt_gui.runOpenFileDialog.  In some cases it was using os.curdir instead of the given startpath argument. The new code if generally simpler.

**Comment by tbnorth** [comment]
I think what I reported was the the file selection dialog didn't start in .../leo/themes, not that it didn't start at all.  I wondered if it appeared to be working for you because you happened to be in .../leo/themes when you ran Leo or something.

**Comment by technatica** [comment]
When I try "Open Theme" the open file dialogue places me in the last
directory that I happened to open a file from.

Chris

**Comment by edreamleo** [comment]
Fixed at e0615b0.
