### ISSUE TITLE
"python setup.py install" does not complete

### ISSUE THREAD

**Issue by brobr** [leo-editor/leo-editor#810]
Hi,

Thanks for the new release of Leo. With the pip-install, however, Leo-5.7 breaks with the previous possibility to create a distribution-specific package.

For creating a distribution package one could -in versions prior to 5.7- copy the files 'leo/dist/leo-install.py' and 'leo/dist/setup.py'  to the main directory and from there run
` "python setup.py install --root=$PKG"` with as target the folder in which the package is created ($PKG).

There is no longer a 'leo/dist/setup.py'; instead the pip-focused setup.py in the main directory, which, when run by its own -after installing 'semantic-version-2.3.0'- yields this error:

> copying leo/plugins/importers/howto.txt -> build/lib/leo/plugins/importers
running build_scripts
creating build/scripts-2.7
error: file '/tmp/SBo/leo-editor-5.7/leo-install.py' does not exist

When run in combination with the requested leo-install.py, copied over from 'leo/dist/', compilation fails; I got this error:

> .....
byte-compiling /tmp/SBo/package-leo/usr/lib64/python2.7/site-packages/leo/plugins/xemacs.py to xemacs.pyc
byte-compiling /tmp/SBo/package-leo/usr/lib64/python2.7/site-packages/leo/plugins/xml_edit.py to xml_edit.pyc
byte-compiling /tmp/SBo/package-leo/usr/lib64/python2.7/site-packages/leo/plugins/xsltWithNodes.py to xsltWithNodes.pyc
byte-compiling /tmp/SBo/package-leo/usr/lib64/python2.7/site-packages/leo/plugins/zenity_file_dialogs.py to zenity_file_dialogs.pyc
byte-compiling /tmp/SBo/package-leo/usr/lib64/python2.7/site-packages/leo/__init__.py to __init__.pyc
running install_egg_info
Copying leo.egg-info to /tmp/SBo/package-leo/usr/lib64/python2.7/site-packages/leo-5.7_final-py2.7.egg-info
running install_scripts
Traceback (most recent call last):
  File "setup.py", line 150, in <module>
    'gui_scripts': ['leo = leo.core.runLeo:run']
  File "/usr/lib64/python2.7/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib64/python2.7/site-packages/setuptools/command/install.py", line 61, in run
    return orig.install.run(self)
  File "/usr/lib64/python2.7/distutils/command/install.py", line 575, in run
    self.run_command(cmd_name)
  File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib64/python2.7/site-packages/setuptools/command/install_scripts.py", line 35, in run
    bw_cmd = self.get_finalized_command("bdist_wininst")
  File "/usr/lib64/python2.7/distutils/cmd.py", line 312, in get_finalized_command
    cmd_obj.ensure_finalized()
  File "/usr/lib64/python2.7/distutils/cmd.py", line 109, in ensure_finalized
    self.finalize_options()
  File "/usr/lib64/python2.7/distutils/command/bdist_wininst.py", line 112, in finalize_options
    for script in self.distribution.scripts:
TypeError: 'NoneType' object is not iterable

When instead of the 5.7-shipped setup.py the 'leo/dist/setup.py' from leo-5.6  is used, the 5.7-package compiles fine in combination with leo-install.py (And also without having 'semantic-version' installed - which seems a pip-dependency). 

Could such a setup.py be restored in the 'leo/dist/' folder of 5.7 for those who like to create distribution-specific packages (and want to bypass pip)? 

Cheers,

Rob

**Comment by edreamleo** [comment]
Matt is on vacation now.  I've assigned this item to him.

**Comment by maphew** [comment]
Would the pip `--target` parameter work for this scenario? https://pip.pypa.io/en/stable/reference/pip_install/#cmdoption-t

> Install packages into <dir>. By default this will not replace existing files/folders in <dir>. 
> Use --upgrade to replace existing packages in <dir> with new versions.

...
The semantic-version circular dependency problem has been worked around in #847, though I'm not sure that solution works here too.

**Comment by maphew** [comment]
> Could such a setup.py be restored in the 'leo/dist/' folder of 5.7 [...}

The 5.6 setup.py and friends can be found at https://github.com/leo-editor/leo-editor/tree/5.6/leo/dist and will be there for as long as Github is. Copying from the Github tag to root of a local Leo folder is functionally equivalent to copying from local dist folder to root:

    wget https://raw.githubusercontent.com/leo-editor/leo-editor/5.6/leo/dist/setup.py \
    -O=~/my-leo-distrib/setup.py

> ...for those who like to create distribution-specific packages (and want to bypass pip)?

There have a been changes in setup.py since 5.6 not specifically related to pip. Sooner or later using the old version will probably stop working. [Pip solves a lot of problems](https://stackoverflow.com/a/15731459/14420), are you sure you can't use it? If there are specific reasons you can't, re-open this issue and we can explore what might be done. I'll need information and feedback though as I don't know about building distribution packages.
