### ISSUE TITLE
launchLeo.py missing, runLeo.py present

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#813]
From another issue (783), ekr wrote:

"Exactly how did you invoke Leo? The following works for me from within Leo:

import os
os.system("leow")

Where leow.bat is:

c:\Anaconda3\pythonw.exe c:\leo.repo\leo-editor\launchLeo.py --gui=qttabs %*"

My installation does not have launchLeo.py.  Instead, it has runLeo.py in /core.  How could you have *launchLeo* but I have *runLeo*?  And the docs labeled for v5.7 talk about "launchLeo", not runLeo.  I  installed Leo 5.7 using

pip install -U leo

The launcher should be named consistently, especially because the way it is now will confuse new would-be users.

Observed on Leo 5.7b2, python 2.7 64-bit, Windows 10.

**Comment by edreamleo** [comment]
On Thu, Mar 15, 2018 at 7:38 AM, tbpassin <notifications@github.com> wrote:

​> ​
How could you have *launchLeo* but I have *runLeo*?
​...
> I installed Leo 5.7 using ​
​​
pip install -U leo

​Presumably that's your answer :-)

Edward
