### ISSUE TITLE
Display Panel for "Print Bindings" Lacks Scroll Bar

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#814]
The display panel for the four "Print xxx" menu items in the Settings menu lacks a scroll bar.  Those commands more than fill the display area.  They can be selected using <ctrl-A> and copied, but that is not convenient.  The display pane needs to be configured to have a scroll bar.

Observed on Leo 5.7b2, Python 2.7 64-bit, Qt 4.xx, Windows 10.

**Comment by tbpassin** [comment]
Although I have experienced this before, my current running instance of Leo *does* have a scroll bar in the panel.  It is true that the scrollbar thumb when down at the bottom is very small and unobtrusive (with my dark theme).  So until I get the problem again, I suppose this is a "non-repro" report.

**Comment by tbnorth** [comment]
On Thu, 15 Mar 2018 12:59:43 +0000 (UTC)
tbpassin <notifications@github.com> wrote:

> The display panel for the four "Print xxx" menu items in the Settings
> menu lacks a scroll bar.  Those commands more than fill the display
> area.  They can be selected using <ctrl-A> and copied, but that is
> not convenient.  The display pane needs to be configured to have a
> scroll bar.
> 
> Observed on Leo 5.7b2, Python 2.7 64-bit, Qt 4.xx, Windows 10.

There's a scroll bar with

Leo 5.8 devel, build 20180314225915, Wed Mar 14 22:59:15 CDT 2018
Git repo info: branch = qdock-layout, commit = d587b78e77db
Python 3.5.2, PyQt version 5.8.0
linux

so it might be some fun OS / Qt version combination thing.
