### ISSUE TITLE
LeoU: Think process, not knowledge

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#817]
Many of Leo's most important devs made major contributions to Leo without asking me a single question.  Do they have super powers?  No, they don't.

But they do know the secret of programming: **Simple processes, endlessly repeated, suffice to find, understand and change *any* software**.  And Leo simplifies these techniques even further.  Here they are...

**Basic skill/process 1: Familiarize yourself with the code**

For any project you want to know what files exist.  When studying other people's code I use a [recursive import script](https://github.com/leo-editor/leo-editor/issues/846) to create a tree of files. The goal is just to have a *vague* understanding of what files are involved. Don't even think about remember details.

It's even easier with Leo.  LeoPy.py contains Leo's sources.  Peruse this outline, seeing what `@file` nodes it contains.

*Don't make a big deal about this step*. It should just take 5 or 10 minutes. Look *only* at files that interest you. In those files you will probably want to look briefly at the top-level classes in the files that interest you. You will likely repeat this step many times, adding a little to your understanding each time.

**Basic skill/process 2: Learn what to search for**

We devs often want to change how commands work.  You can usually find the top-level code for a command simply by searching for the command's name, in single quotes.

To find the definition of a method, function or class, simply control-click on it.  That will start a search for def x and class x.  If that doesn't work, a cff (clone-find-all-flattened) search on a name will find all uses of that name in the present outline.

**Basic skill/process 3: Look for helpers in child nodes**

With Leo outlines **it's natural to put a method's helpers in child nodes**. I usually forget implementation details, but the children of a node usually contain most of the details.

**Basic skill/process 4: Use clones to organize and remember your work**

When working on a project I make create an organizer node as the last top-level node of the outline.  This node will typically contain a link to the github issue.  I make clones of all relevant nodes and move them so they are clones of the organizer node.  For complex projects I may create subsidiary organizer nodes, like "changed", "reference", etc.

When a project is done (or suspended), I move the project's organizer node so it is the last child of *another* organizer node called "Recent Code". This hides all work except the what I am, this minute, working on.  This is important: it hides details and lessens distractions.

**Summary**

The easy processes just described form the basis for programming workflow.

*Expect to repeat these processes many times*.  Don't worry if not everything is clear at first.

**Comment by wangzhaohe** [comment]
Basic skill/process 2: Learn what to search for

This is an **excellent** function.

**Comment by wangzhaohe** [comment]
I usually create two basic nodes:
+ codes: actual code structure with @path and @files  
+ func: classifying function with paste-retaining-clones

I usually work on func node.

**Comment by wangzhaohe** [comment]
Now I am confusing at how to write document with @code and @doc from source code node.
Would you teach me how to implement this thought？

**Comment by wangzhaohe** [comment]
I like write Markdown doc, but Markdown **can not be save to html** from leo-editor.

And another disadvantage is that Markdown **can not use relative path** to show picture from leo-editor viewrenderd2 plugin.

**Comment by tbpassin** [comment]
"I like write Markdown doc, but Markdown can not be save to html from leo-editor."

Viewrendered2 is getting a few mods and it will save a @md tree to html (by exporting it to the browser). The current devel version can also be set to render only (python) code, so you will be able to make a part of a page be markdown text and the rest be python code, and save only the code to html.

Currently it only works this way for python code, but if people want more languages to be treated as "code", that could be done.

This is assuming these changes in the devel branch make it into the release branch.

**Comment by tbnorth** [comment]
On Fri, 16 Mar 2018 16:37:12 -0700
tbpassin <notifications@github.com> wrote:

> "I like write Markdown doc, but Markdown can not be save to html from
> leo-editor."
> 
> Viewrendered2 is getting a few mods and it will save a @md tree to
> html (by exporting it to the browser). The current devel version can
> also be set to render only (python) code, so you will be able to make
> a part of a page be markdown text and the rest be python code, and
> save only the code to html.
> 
> Currently it only works this way for python code, but if people want
> more languages to be treated as "code", that could be done.
> 
> This is assuming these changes in the devel branch make it into the
> release branch.

Just a heads up the my goal is to replace viewrendered* with the
leo-edit-pane system.  It's not super imminent, and of course the
viewrendered plugins can persist as long as people want them.  The
leo-edit-pane system tries to be more modular and better separate the
interaction with the outline (follow / don't follow the tree selection,
update always / on demand, render recursively etc.) from the different
view (md / html / svg / rst / csv) and edit modes.  It's probably more
a framework change than anything, any valuable viewers in viewrendered*
can probably be used by the leo-edit-pane system too.

Cheers -Terry

**Comment by edreamleo** [comment]
On Fri, Mar 16, 2018 at 12:05 PM, wangzhaohe <notifications@github.com>
wrote:

> Now I am confusing at how to write document with @code
> <https://github.com/code> and @doc <https://github.com/doc> from source
> code node.
> Would you teach me how to implement this thought？
>
​These are old-style literate programming features which you can (and
should) ignore.  Instead, you should use python docstrings.

To answer your question, the idea is to write longer comments this way:

@doc
A multi-line comment
@code

@ and @c are abbreviations.  Leo's present code base probably doesn't use
@doc or @code at all.  In a few places you will see:

@
A multi-line comment
@c

To repeat, in Python the following is better style:

def spam():
    '''
    A multi-line comment.
    '''
​
​Edward​

**Comment by edreamleo** [comment]
On Fri, Mar 16, 2018 at 12:12 PM, wangzhaohe <notifications@github.com>
wrote:

> I like write Markdown doc, b
> ​​
> ut Markdown *can not be save to html* from leo-editor.
>
> And another disadvantage is that Markdown *can not use relative path* to
> show picture from leo-editor viewrenderd2 plugin.
>
​#767 Add markdown command similar to rst3 command
<https://github.com/leo-editor/leo-editor/issues/767> intends to fix these
and similar problems.​

I have added your requests to the first comment of #767.

Note that it *is* possible to create .md from Leo now.  LeoDocs.md contains
the sources for three such files.

Here is how to use @auto-md nodes:

1. Create an @auto-md x.md node.  For example, @auto-md ../doc/demo.md.

2. Write your documentation with outline structure indicating outline
section levels.

3. Optional.  Run the @button make-md-toc script to create the table of
contents.  This script prints the TOC to the console.  Paste the TOC where
desired.  You can even create a new node for it.

4. Save the file.  Now it contains the desired markup.

*Important*: Leo's @auto-md logic handles section markup automatically.

- The markdown *importer *plugin removes *all* section markup, including
the preferred '#' markup and the deprecated underline/overline markup.

- The markup *writer *writes '#' markup for all headlines, except for
headlines that start with "!".

- LeoDocs.leo contain an @button make-md-heads script, but that I have just
disabled it.  It is no longer needed.

*Summary*

@auto-md allows you to write any kind of markup you want.

@button make-md-toc writes an updated TOC to the console.

​#767 <https://github.com/leo-editor/leo-editor/issues/767> will generate
toc's automatically, and to support @md-ignore, etc.

Edward

**Comment by edreamleo** [comment]
It *is* possible to create .md from Leo now.  LeoDocs.md contains the sources for three such files.

Here is how to use @auto-md nodes:

1. Create an @auto-md x.md node.  For example, @auto-md ../doc/demo.md.

2. Write your documentation with outline structure indicating outline
section levels.

3. Optional.  Run the @button make-md-toc script to create the table of
contents.  This script prints the TOC to the console.  Paste the TOC where
desired.  You can even create a new node for it.

4. Save the file.  Now it contains the desired markup.

*Important*: Leo's @auto-md logic handles section markup automatically:

- The markdown *importer* plugin removes *all* section markup, including the preferred '#' markup and the deprecated underline/overline markup.

- The markup *writer* writes '#' markup for all headlines, except for headlines that start with "!".

**Summary**

- `@auto-md` allows you to write any kind of markup you want.

- `@button make-md-toc` writes an updated TOC to the console.

​#767 will generate toc's automatically, and support `@md-ignore`, etc.

**Comment by edreamleo** [comment]
**EKR**: rewriting this Q&A so that markup works.

**wangzhaohe**:  I am confused about using `@code` and `@doc`.

​**EKR**: These are old-style literate programming features which you can (and should) ignore.  Instead, you should use python docstrings.

To answer your question, the idea is to write longer comments this way:

    @doc
    A multi-line comment
    @code

`@` and `@c` are abbreviations.  Leo's present code base probably doesn't use `@doc` or `@code` at all.  In a few places you will see:

    @
    A multi-line comment
    @c

To repeat, in Python the following is better style:
```python
def spam():
    '''
    A multi-line comment.
    '''

**Comment by tbpassin** [comment]
"wangzhaohe: I am confused about using @code and @doc.

​EKR: These are old-style literate programming features which you can (and should) ignore. Instead, you should use python docstrings."

Using the docstring is good. And I see that more people are writing markdown in them.  I'm still interested in more literate programming-style mixing of commentary and code than you can get with just using the docstring.  That's the main reason I spent some time on enhancing viewrendered2.  

Another way to approximate this mixing of commentary and code is to clone the program nodes into a commentary tree, and place the commentary in additional nodes inserted before (or after) program nodes.  That's not as useful as inserting commentary right into the middle of code, but if you break down your code far enough into child nodes, you could get close.  Hurray for Leo's clones!

Maybe putting a commentary tree under a @auto-md parent node would do this job well.  I'll have to try it.

**Comment by technatica** [comment]
"When studying other people's code I use a recursive import script to create a tree of files."

That would be a handy script to have. Hint, hint.

I have been reading through spyder and pyface code to see how they implement jedi and pygments. The recursive import script would save me a lot of grep querying.

**Comment by edreamleo** [comment]
On Sat, Mar 31, 2018 at 8:01 PM, Chris George <notifications@github.com>
wrote:

> "When studying other people's code I use a recursive import script to
> create a tree of files."
>
> That would be a handy script to have. Hint, hint.
>
​See c.recursiveImport.  ​
​You could have found that by doing a regex cff (ignoring case) on ​

​recursive?import. ​
​For example:

c.recursiveImport(
    dir_ = << path to root directory >>,
    add_path=True,
    kind = '@clean', # '@clean', #'@nosent','@auto','@file',
    recursive = True,
    safe_at_file = False,
    theTypes = ['.py',],
)

I like to import to @clean and set safe_at_file = False, but *before doing
that* I create a git repo for the to-be-imported directory and check in all
the .py files.  That way I can track any changes that get made, and revert
them if need be.

Edward

**Comment by technatica** [comment]
Thanks for this. It took a minute or two to figure out how to make it work,
but it is much, much easier to explore in Leo than using grep.

This is another one of those places where ~/ doesn't work but a full
/home/chris does.

Chris

**Comment by edreamleo** [comment]
On Sun, Apr 1, 2018 at 7:06 AM, Chris George <notifications@github.com>
wrote:

> Thanks for
> ​[the explanation of c.recursiveImport]. It took a minute or two to figure
> out how to make it work, but it is much, much easier to explore in Leo than
> using grep.
>

​I have just created a separate lesson for this discussion LeoU:
c.recursiveImport imports files recursively
<https://github.com/leo-editor/leo-editor/issues/846>​ and have removed the
comments from the first lesson.

Edward
