### ISSUE TITLE
Drag and drop does not preserve encoding

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#819]
I have a leo outline that has an headline with a @clean directive
and whose headline body  contains this:

    @language txt
    @tabwidth -4
    @encoding iso-8859-1
    Comité des communications
    @others

The text of the other node names and node text contains accented French letters.

If I clone a sub-node whose title contains diacritical letters either or both in title and in the body, and move the clone elsewhere in the outline tree, the accents remain.  If I copy that same sub-node and then move the copy thus created elsewhere in the outline tree, (shift-arrow) the accents remain.

However, if I drag and drop the same node containing accents with the left mouse button, the dropped copy sees its accents changed to a UTF-8 multi-character equivalent, both in the node name and also in the text body of that mouse-moved node.  The same drag and drop of a cloned node also results in the substitution of the accented letters into their UTF-8 equivalent.

Example:   La fréquence, once dragged and dropped, creates a duplicate now labelled: La frÃ©quence

**Terry:**     I've noticed you can drag nodes into the body, pasting xml. I wonder if what seems like an intra-file drag becomes inter file (xml from clipboard) if the mouse moves out of the tree widget?

**EKR**: ​I had forgotten that.  This may be the what the OP did.

**Comment by tscv11** [comment]
I'm not sure what to think because this has the label "First" (which I thought was for good "First Issues" for students)  _but_ is also already assigned to _you_. Maybe that's just so it's covered until someone else comes along. I'll give it a shot if you like - just let me know, or maybe point me to something else that would be a good "First!". Thanks.

**Comment by tbnorth** [comment]
I think Edward uses First for first on his list. There's another tag for good first issue, "good first issue" or something like that. 

On March 17, 2018 5:27:55 PM CDT, tscv11 <notifications@github.com> wrote:
>I'm not sure what to think because this has the label "First" (which I
>thought was for good "First Issues" for students)  _but_ is also
>already assigned to _you_. Maybe that's just so it's covered until
>someone else comes along. I'll give it a shot if you like - just let me
>know, or maybe point me to something else that would be a good
>"First!". Thanks.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/leo-editor/leo-editor/issues/819#issuecomment-373957467

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by edreamleo** [comment]
On Sat, Mar 17, 2018 at 5:46 PM, Terry Brown <notifications@github.com>
wrote:

> I think Edward uses First for first on his list. There's another tag for
> good first issue, "good first issue" or something like that.
>

​Yes.

I assign most issues to myself, but help is always welcome. Feel free to
assign yourself to any issue.  This alerts me that someone else is
interested and that someone else may be working on the issue simultaneously.

Edward

**Comment by edreamleo** [comment]
I am going to close this issue.  Please reopen if there are further problems.
