### ISSUE TITLE
Replacement for Valuespace Plugin Block Evaluation 

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#820]
I tried out the valuespace plugin's block evaluation command, but I wanted some changes in how it works.  

The *vs-eval-block* command evaluates a node (or a tree that has been delimited with special markers) and inserts the (string) result into the node, something like what a jupyter notebook cell can do. 

Since I am interested in literate programming, I have various files that have Leo directives in the page, and I may also have sections that are commented out by "@"...."@c" directives.  I would like to respect them.

So I wrote a new plugin to do those things.  It's simpler than vs, since vs does way more.  But for rendering a single node, the new one is more functional, at least for my purposes.  The code is also pretty straightforward.

What's different from *vs-eval-block*:

   1. Respects @...@c/
   2. Only collects lines of code that follow an _@language python_ directive.  Any other _@language_ directive causes lines to be skipped until  another _@language python_ directive is encountered.
   3. Ignores all other directive lines so they don't get evaluated by mistake (causing an error). 
   4. Only evaluates the current node, but no end-of-block markers are needed.

The thing can be implemented in a @command node, but I've attached a plugin version.   If there is some interest by others, I'd like to get this into the code base, whether as a stand-alone plugin or merged into valuespace.

[vs2-eval-insert-node.zip](https://github.com/leo-editor/leo-editor/files/1821048/vs2-eval-insert-node.zip)

**Comment by tbnorth** [comment]
On Fri, 16 Mar 2018 23:58:21 +0000 (UTC)
tbpassin <notifications@github.com> wrote:

> I tried out the valuespace plugin's block evaluation command, but I
> wanted some changes in how it works.  
> 
> The *vs-eval-block* command evaluates a node (or a tree that has been
> delimited with special markers) and inserts the (string) result into
> the node, something like what a jupyter notebook cell can do. 

vs-eval-block doesn't deal with trees, although other vs-* commands
do.  The valuespace plugin should probably be split into two plugins,
one with all the complex tree evaluation stuff Ville wrote, and a
separate plugin with the vs-eval-* commands I added.  I've often
regretted putting them in there.

The new evaluation focused plugin would probably be a good place for
the variation you describe.

The point of the # >>> / # <<< delimiters used by vs-eval-block is that
you can have a series of blocks in one node:

a = 11
2 * a
# >>>
22
# <<<
3*a
# >>> *
51
# <<<

(* indicates a stale output, `a` was originally 17, and I only
re-executed the first block after changing it to 11).

Cheers -Terry

> Since I am interested in literate programming, I have various files
> that have Leo directives in the page, and I may also have sections
> that are commented out by "@"...."@c" directives.  I would like to
> respect them.
> 
> So I wrote a new plugin to do those things.  It's simpler than vs,
> since vs does way more.  But for rendering a single node, the new one
> is more functional, at least for my purposes.  The code is also
> pretty straightforward.
> 
> What's different from *vs-eval-block*:
> 
>    1. Respects @...@c/
>    2. Only collects lines of code that follow an _@language python_
> directive.  Any other _@language_ directive causes lines to be
> skipped until  another _@language python_ directive is encountered.
> 3. Ignores all other directive lines so they don't get evaluated by
> mistake (causing an error). 4. Only evaluates the current node, but
> no end-of-block markers are needed.
> 
> The thing can be implemented in a @command node, but I've attached a
> plugin version.   If there is some interest by others, I'd like to
> get this into the code base, whether as a stand-alone plugin or
> merged into valuespace.
> 
> [vs2-eval-insert-node.zip](https://github.com/leo-editor/leo-editor/files/1821048/vs2-eval-insert-node.zip)
> 
> 
>

**Comment by tbpassin** [comment]
From my point of view, the output delimiters are needed so the code can find and replace stale output.  In my version, the old results just get replaced, but one could do it the other way instead.

**Comment by tbnorth** [comment]
On Fri, 16 Mar 2018 18:05:32 -0700
tbpassin <notifications@github.com> wrote:

> From my point of view, the output delimiters are needed so the code
> can find and replace stale output.  In my version, the old results
> just get replaced, but one could do it the other way instead.  

The staleness indicator is really just an embellishment, the delimiters
are to allow multiple in / out blocks in a sequence in the body.

Cheers -Terry
