### ISSUE TITLE
Stickynotes> Tabula-subtree can crash Leo

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#823]
Select a node with several child nodes.
Plugins> Stickynotes> Tabula-subtree
The tabula tree displays with child panes. Add some text to a body pane. Close the entire Tabula window by pressing the X.
Leo then crashes with a dialog box [python has stopped working]
Here is the traceback:

Traceback (most recent call last):
  File "N:\git\leo-editor\leo\plugins\stickynotes.py", line 615, in closeEvent
    self.save_states()
  File "N:\git\leo-editor\leo\plugins\stickynotes.py", line 733, in save_states
    for (gnx, n) in self.notes.items() if n.isVisible())
  File "N:\git\leo-editor\leo\plugins\stickynotes.py", line 733, in <genexpr>
    for (gnx, n) in self.notes.items() if n.isVisible())
RuntimeError: wrapped C/C++ object of type FocusingPlaintextEdit has been deleted
[end]

Leo Log Window
Leo 5.8 devel, build 20180307231313, Wed Mar 7 23:13:13 PST 2018
Git repo info: branch = devel, commit = 1b4de66172e8
Python 3.6.5, PyQt version 5.10.1
Windows 10 AMD64 (build 10.0.16299) SP0
isPython3: True
caching enabled

**Comment by technatica** [comment]
The same procedure works for me without the crash.

Leo 5.8 devel, build 20180307231313, Wed Mar 7 23:13:13 PST 2018

Git repo info: branch = devel, commit = bb744c3a6389

Python 3.6.4, PyQt version 5.10.0

linux

isPython3: True

caching enabled


It could be python version, pyqt version, or os.

Chris

**Comment by LewisNeal** [comment]
This is a repeatable method of crashing Leo: If you close one or more of the child Tabula panes, then close the entire Tabula window by pressing the X.

I think my statement "add some text to a body pane" was incorrect. I most likely also deleted a child Tab pane, and I mistakenly attributed the edit to the crash.

**Comment by LewisNeal** [comment]
This crash using the Tabula-subtree command was still a problem up until commit c0c1195.
Your work on #940 has fixed this bug.

**Comment by edreamleo** [comment]
On Wed, Aug 22, 2018 at 7:00 PM LewisNeal <notifications@github.com> wrote:

> This crash using the Tabula-subtree command was still a problem up until
> commit c0c1195
> <https://github.com/leo-editor/leo-editor/commit/c0c11957861a1e783c8656703a14320f7dd83fc3>
> .
> Your work on #940 <https://github.com/leo-editor/leo-editor/issues/940>
> has fixed this bug.
>
Thanks for this report.
  I had forgotten all about #823.
Edward
