### ISSUE TITLE
Scrolling headlines.

### ISSUE THREAD

**Issue by technatica** [leo-editor/leo-editor#824]
Not a solution. Barely a workaround.

But it would be handy for headlines that are longer than the current viewport to show a tooltip of the contents of the headline. It won't be live, so no editing feedback, but it'll save time resizing the tree pane when all you want is a look.

**Comment by edreamleo** [comment]
@technatica Good idea.

**Comment by technatica** [comment]
Another way to potentially handle this:

When transcribing a document recently, I ran across a two-line headline. Would it be possible to assign an inline marker to split a long headline into two-lines and display it?

ie. Instead of a long headline, like this:

Hero: Slavery to Greater Slavery to Freedom World: Slavery to Greater Slavery to Freedom

place a mark where you want the break and have this displayed instead:

Hero: Slavery to Greater Slavery to Freedom
World: Slavery to Greater Slavery to Freedom

This is the actual heading in the document. When pondering if it would be a useful enhancement (if it is even possible) it occurred to me that it would partly solve the non-scrolling headline problem at least as well as the tooltip idea.

**Comment by tbnorth** [comment]
There is an edit-headline-long command that is more of a workaround than a 
solution, but it helps a bit.

**Comment by technatica** [comment]
Is that attached to a particular plugin?

It doesn't appear when I use tab completion, just edit-headline.

Chris

**Comment by tbnorth** [comment]
Well duh, I've had it in my settings files for so long I didn't realize it 
was a @command node.  Here's the implementation:

txt = g.app.gui.runAskOkCancelStringDialog(
   c, 'Edit headline', 'Edit headline', default=p.h, wide=True)
if txt and txt.strip(): p.h = txt

Cheers -Terry
