### ISSUE TITLE
Output to Status Line

### ISSUE THREAD

**Issue by technatica** [leo-editor/leo-editor#828]
I write in Leo, fullscreen.

How would I go about having the word count display in the statusbar1 widget right justified?

The word_count plugin outputs to the log pane and reports too much information to fit comfortably in the status line. Word count alone is what I am after. It shouldn't take up too much space and if it had an on off setting it wouldn't bug people who don't care.

../leo-editor/leo/core/LeoPyRef.leo#Code-->Qt gui-->@file ../plugins/qt_frame.py-->class LeoQtFrame (leoFrame)-->qtFrame.class QtStatusLineClass-->QtStatusLineClass.update & helper

It seems this would be the node, and I have a rough idea of how to generate the word count (word_count.py). 

`s = c.p.b`
`    wordNum = len(s.split(None))`

Am I looking in the right place? Or am I barking up the wrong tree?

**Comment by edreamleo** [comment]
On Mon, Mar 19, 2018 at 9:44 PM, Chris George <notifications@github.com>
wrote:

> How would I go about having the word count display in the statusbar1
> widget right justified?
>
> ​QtStatusLineClass.update
> ​ ​
> ​[seems to be the] ​
> node,
>
> ​I agree.​

I have a rough idea of how to generate the word count (word_count.py).
>
​Always a good idea to start with existing code, when it's available.​

Edward

**Comment by technatica** [comment]
Works great.

Now I just need to figure out how to right align the output while leaving the rest left aligned. :-)

**Comment by edreamleo** [comment]
On Tue, Mar 20, 2018 at 8:08 AM, Chris George <notifications@github.com>
wrote:

> Works great.
>
​Glad to hear it.​


> Now I just need to figure out how to right align the output while leaving
> the rest left aligned. :-)
>
​That's not likely to be easy.​

Presumably right aligning text depends on window size.  I'd try to think of
an alternative.

Edward

**Comment by tbnorth** [comment]
On Tue, 20 Mar 2018 13:54:29 +0000 (UTC)
"Edward K. Ream" <notifications@github.com> wrote:

> On Tue, Mar 20, 2018 at 8:08 AM, Chris George
> <notifications@github.com> wrote:
> 
> > Works great.
> >  
> ​Glad to hear it.​
> 
> > Now I just need to figure out how to right align the output while
> > leaving the rest left aligned. :-)
> >  
> ​That's not likely to be easy.​
> 
> Presumably right aligning text depends on window size.  I'd try to
> think of an alternative.
> 
> Edward

If the word count is in its own QLabel in a QHBoxLayout you can just a
QStretch to push it over to the right, Q?  :) I think you can add
multiple separate widgets to toolbars, if that's what you're doing.

Cheers -Terry

**Comment by technatica** [comment]
So far I have just "monkey see, monkey do" based on how line, col, and fcol
have been handled.

Looking at the output I don't know if right alignment matters.

I am looking into making it its own @bool setting, default false. I am
puzzling out how best to wrap that around the changes I have already made
that I know work.

if not c.config.getBool('word-count', default=False):

        return

Chris

**Comment by tbnorth** [comment]
On Tue, 20 Mar 2018 14:11:03 +0000 (UTC)
Chris George <notifications@github.com> wrote:

> I am looking into making it its own @bool setting, default false. I am
> puzzling out how best to wrap that around the changes I have already
> made that I know work.
> 
> if not c.config.getBool('word-count', default=False):
> 
>         return

Without looking at the code I'd expect

...
if c.config.getBool('word-count', default=False):
    <your stuff>
...

but maybe there's a reason that doesn't work?

Cheers -Terry

**Comment by technatica** [comment]
My stuff is currently interspersed throughout a bunch of existing stuff.

I worked it out. Leo doesn't crash and the @bool word-count = True/False
toggles the output.

I wouldn't know a unit test if it bit me. All I did was add the if near the
top of the code and a return at the bottom of my changes.

What is the procedure for committing this? How do I document it? Do I add
the @bool to leoSettings.leo set to False?

Chris

**Comment by edreamleo** [comment]
On Tue, Mar 20, 2018 at 9:55 AM, Chris George <notifications@github.com>
wrote:

What is the procedure for committing this?


​1. ​
Run all the unit tests. You must learn to do this before you are ready to
commit anything:

    - Open leo/test/unitTest.leo in a console.
    - The "Active Unit Tests" node should already be selected. If not,
select it.
    - Do Alt-4. It is bound in the file to run-selected-unit-tests-locally.

2. Use git add to add the changed files.  Then git commit to commit the
changes.

How do I document it?


​Document everything in the git commit message. That should suffice for
this change.


> Do I add
> ​ ​
> the @bool to leoSettings.leo set t
> ​​
> o False?
>

​Yes.  Always preserve legacy operation unless all devs agree otherwise.

Edward

**Comment by technatica** [comment]
Okay.

The test returned one fail, 43 skipped.

Here is the fail. What does it mean?

======================================================================
FAIL: runTest (leo.core.leoTest.GeneralTestCase)
@test c.theScriptingController.atScriptNodes

----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/chris/leo-editor/leo/core/leoTest.py", line 208, in runTest
    exec(compile(script, scriptFile, 'exec'), d)
  File "/home/chris/.leo/scriptFile.py", line 7, in <module>
    assert c.theScriptingController.atScriptNodes == val
AssertionError

----------------------------------------------------------------------

Chris

**Comment by edreamleo** [comment]
On Tue, Mar 20, 2018 at 10:27 AM, Chris George <notifications@github.com>
wrote:

>
> The test returned one fail, 43 skipped.
>
> Here is the fail. What does it mean?
>

​Probably nothing.

You can save your changes using git stash, then rerun the tests.  If you
get the same failure then your work is not to blame and you can ignore the
failure.

Edward

**Comment by technatica** [comment]
Changed at a5b93276fb21.

A search for wordNum takes you to the affected node.

I would appreciate feedback. There must be a much more elegant way of doing this than the brute force method. :-)

**Comment by edreamleo** [comment]
On Tue, Mar 20, 2018 at 11:42 AM, Chris George <notifications@github.com>
wrote:

I would appreciate feedback
> ​.
>

​Hey!  I like it.

A reminder: to enable this feature, set @bool word-count = True
​


> ​
> There must be a much more elegant way of doing this than the brute force
> method. :-)


​A quick *glance *at your code ​reveals nothing too unexpected. The notion
of what the expected complexity of code is only comes with more
experience.  For now it suffices that the code works without an obvious
performance hit.

Edward

**Comment by edreamleo** [comment]
I think this issue has been successfully completed.
