### ISSUE TITLE
Docs. typo for pip install

### ISSUE THREAD

**Issue by tbnorth** [leo-editor/leo-editor#830]
http://leoeditor.com/installing.html#installing-leo-with-pip

```
Python 2 with Anaconda

conda install pyqt pip install leo
```
should be
```
Python 2 with Anaconda

conda install pyqt
pip install leo
```

Also maybe add "enter `leo` on the command line after installation to run Leo"

**Comment by edreamleo** [comment]
Fixed at 2c1fa7a. This was a markup mistake.
