### ISSUE TITLE
Larger tree icons

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#833]
I have created icons with a gray background for the EKRDark theme. It may be a bit better, but I suddenly realized the real problem with contrast is that the icon box is way too small.  It would be better to have larger, separate, icons for marked, cloned and "has text" states.

**Comment by tbnorth** [comment]
On Thu, 22 Mar 2018 21:07:32 +0000 (UTC)
"Edward K. Ream" <notifications@github.com> wrote:

> I have created icons with a gray background for the EKRDark theme. It
> may be a bit better, but I suddenly realized the real problem with
> contrast is that the icon box is way too small.  It would be better
> to have larger, separate, icons for marked, cloned and "has text"
> states.

Would they need to be separate?  I ask because it's simpler to be
flexible style wise if we keep them together, just make them wider, so
they *look* like three separate icons.  Which I'd suggest just to make
it easy to keep the current "all on top of each other" icons for
people who want to conserve horizontal space. 

So pretending that each line of text that follows has a single *wide*
icon image:

◌ ☐  no text, no clone, no mark
◉ ☐  text, no clone, no mark
◌ ☑  no text, no clone, mark
◉ ☑  text, no clone, mark
◌☠☐  no text, clone, no mark
◉☠☐  text, clone, no mark
◌☠☑  no text, clone, mark
◉☠☑  text, clone, mark

;-)

that looks like three icons but is really just one wide one?

Cheers -Terry

**Comment by edreamleo** [comment]
On Thu, Mar 22, 2018 at 4:18 PM, Terry Brown <notifications@github.com>
wrote:

So pretending that each line of text that follows has a single *wide*
> icon image:
>
> ◌ ☐ no text, no clone, no mark
> ◉ ☐ text, no clone, no mark
> ◌ ☑ no text, no clone, mark
> ◉ ☑ text, no clone, mark
> ◌☠☐ no text, clone, no mark
> ◉☠☐ text, clone, no mark
> ◌☠☑ no text, clone, mark
> ◉☠☑ text, clone, mark
>

​This scheme is reasonable, and has another advantage, namely that icon
boxes could have the same width.

Otoh, it's also reasonable to support separate icons, and Leo already has
considerable support for that, as you know from your todo.py work.

Edward

**Comment by tbnorth** [comment]
On Thu, 22 Mar 2018 14:56:09 -0700
"Edward K. Ream" <notifications@github.com> wrote:

> Otoh, it's also reasonable to support separate icons, and Leo already
> has considerable support for that, as you know from your todo.py work.

Yes but I'm thinking specifically of how the 16 states represented
by the boxXX.png icons are handled.

To support both separate and combined icons is more work than just
supporting combined icons which can look like separate icons if you
want them to (by being wide).  And I don't want to lose support for the
combined icons, because I value their compactness.

Cheers -Terry

**Comment by technatica** [comment]
The boxes used by Breeze Dark are 50% larger than the default boxes.

Terry, you have detailed the 8 different states. What is the difference between a light border on the box and a dark border? ie. What is different between boxes 00 to 07 as compared to 08 to 15?

Chris

**Comment by technatica** [comment]
Figured it out. Dark is clean, light is dirty.

So we have 8 states and a toggle which makes 16. 

The boxes that I made bigger look good beside 16px text in the tree. They are 25px by 14px compared to the 20px by 11px of the original boxes. So a 30px by 15px icon would be about the most we could reasonably go.

I will play with this for a while and see what I can come up with. It is a very small space.

**Comment by technatica** [comment]
It is too small for icons to be usable.

The maximum display size of an icon box is 55px by 15px. This is no matter how big the font is. You can squeeze 3 icons into 55px, but anything under 20px tall is simply unintelligible. 

I created a png to scale: 550px by 150 px. I stuck three icons into it. Leo resized it to 55px by 15px and the icons are simply too small to be made out, even with no border.

The current approach seems to be about the best we can expect at that resolution. That still leaves a lot of room for creativity.

**Comment by technatica** [comment]
Hmmm, perhaps 1px icons inside a 2px box. The contrast will be critical. 

Transparency is a good feature as it only requires one set of icons for all themes, but as Edward has already solved for himself, the current bunch lack contrast with dark themes. The solid, solarized icons are a bit better but are glaring with light themes.

Perhaps it would be best to provide guidance for theme devs about the 8 states and the toggle and leave it up to them to provide appropriate icons to fit their theme. Having the larger (25px by 14px) transparent icons as a sane default in both the light and dark directories under ../leo/Icons as a fallback for themes without custom icons would suffice. These icons could use a redesign, but size is a serious constraint.

**Comment by edreamleo** [comment]
I'm going to put this on the back burner. 

As for guidance, see qtree.getCompositeIconImage, called only from qtree.getIcon.   p.v.computeIcon() computes an index between 0 and 15, depending on status bits in p.v

**Comment by technatica** [comment]
The constraint on icon size is hardcoded into this file: LeoPyRef.leo#Code-->Qt gui-->@file ../plugins/qt_tree.py-->class LeoQtTree-->qtree.Birth-->qtree.__init__

I changed it from (160, 16) to (160, 20). I plan to use 64 of the 160 for my theme boxes to cover the 8 states and the clean/dirty toggle, leaving 96 for other uses. This could, of course, be bumped up  to accommodate.

The image below shows the result. This is with 22px body text and 20px in the tree. The boxes are 35px by 20px. Icons are scaled based on which constraint is first to reach a limit. It maintains 

All unit tests pass. Unless there are objections I will push this.

Chris

![2018-03-23_1](https://user-images.githubusercontent.com/5809169/37845288-5a1fea92-2e87-11e8-8901-abbe304fd997.png)

**Comment by technatica** [comment]
Here is a first take.

Icons are 57px by 20px.

Blue 1px border for clean, grey 1px border for dirty. This might need to be a little more noticeable.

Red, green and yellow icons on a transparent background.

![2018-03-23_2](https://user-images.githubusercontent.com/5809169/37856974-b6bb6240-2eb4-11e8-812a-103f67d74e7c.png)

Chris

**Comment by technatica** [comment]
I suppose this could become an @int setting. Is there a reason it shouldn't?

"The constraint on icon size is hardcoded into this file: LeoPyRef.leo#Code-->Qt gui-->@file ../plugins/qt_tree.py-->class LeoQtTree-->qtree.Birth-->qtree.init

I changed it from (160, 16) to (160, 20). I plan to use 64 of the 160 for my theme boxes to cover the 8 states and the clean/dirty toggle, leaving 96 for other uses. This could, of course, be bumped up to accommodate."

**Comment by edreamleo** [comment]
On Fri, Mar 23, 2018 at 6:13 PM, Chris George <notifications@github.com>
wrote:

> Here is a first take.
>
​Excellent start! I like the larger icon box and the general idea. However,
the icon box for the selected node is almost invisible. This isn't true in
the EKRDark theme.

Edward

**Comment by edreamleo** [comment]
On Fri, Mar 23, 2018 at 6:37 PM, Chris George <notifications@github.com>
wrote:

> I suppose this could become an @int <http:///int> setting. Is there a
> reason it shouldn't?
>
​​Can't think of any.

Edward

**Comment by technatica** [comment]
Done at 06639b5b0.

Default is 16. Images will scale up or down. ie. If the image is 20px high and the setting is 30px, it will distort. Best practice would be to design for realistic maximums. 30px is pretty big, but making all icons this big has little to no downside other than file size.

**Comment by edreamleo** [comment]
On Sat, Mar 24, 2018 at 10:04 AM, Chris George <notifications@github.com>
wrote:

> Done at 06639b5
> <https://github.com/leo-editor/leo-editor/commit/06639b5b06c45dfe3b789a2eacd16915c7129236>
> .
>
> Default is 16. Images will scale up or down. ie. If the image is 20px high
> and the setting is 30px, it will distort. Best practice would be to design
> for realistic maximums. 30px is pretty big, but making all icons this big
> has little to no downside other than file size.
>
​Thanks for this.  Bigger icon boxes will be useful for my geriatric eyes.

Edward

**Comment by technatica** [comment]
Here is another take.

No border, separate icons and a white indicator for a dirty node.

Icons are all 30px high. This screenshot is with @int icon-height = 24 and a tree font size of 20.

Feedback?

![2018-03-25](https://user-images.githubusercontent.com/5809169/37875961-f8e8948e-2ffa-11e8-9e8b-54f38b8439af.png)

**Comment by technatica** [comment]
Here is an image with 20px tree font and default (16px) icon-height.

I am going to upload these as the icons for BreezeDark. I will likely tinker with the colours to better match, but the design is good enough.

A question: Is there a place for resources somewhere in the leo-editor folder? I have a handful of Gimp files that were used to create these icons that would save future theme devs time and effort.

![2018-03-25_3](https://user-images.githubusercontent.com/5809169/37876499-fba86c6a-3001-11e8-8389-7b90befdb95b.png)

**Comment by technatica** [comment]
The new icons are legible and usable between @int icon-height = 12 to @int icon-height = 30. Status quo height is maintained at 16px high.

Closed at 43472ee0f.

**Comment by edreamleo** [comment]
On Sun, Mar 25, 2018 at 9:07 AM, Chris George <notifications@github.com>
wrote:

> Here is another take.
>
> No border, separate icons and a white indicator for a dirty node.
>
> Icons are all 30px high. This screenshot is with @int
> <https://github.com/int> icon-height = 24 and a tree font size of 20.
>
> Feedback?
>
​Good work. A step in the right direction. Much better contrast for the
selected node.

I would prefer a check mark for marked nodes instead of a bull's eye, and
maybe something more akin to Leo's traditional clone marker.

And I think I like have variable-width icons. Am I correct in assuming that
the change of width isn't jarring? It might even draw *welcome* attention
to the change.

Edward

**Comment by edreamleo** [comment]
On Sun, Mar 25, 2018 at 9:56 AM, Chris George <notifications@github.com>
wrote:

> I am going to upload these as the icons for BreezeDark. I will likely
> tinker with the colours to better match, but the design is good enough.
>
​I agree.  This is already more than good enough.

> A question: Is there a place for resources somewhere in the leo-editor
> folder? I have a handful of Gimp files that were used to create these icons
> that would save future theme devs time and effort.
>
​The leo/Icon folder seems like a reasonable catchall.

Edward

**Comment by tbnorth** [comment]
On Sun, 25 Mar 2018 11:41:19 -0700
"Edward K. Ream" <notifications@github.com> wrote:

> ​The leo/Icon folder seems like a reasonable catchall.

Or at least a sub folder therein :-)  leo/Icons/img_src...

but should the source files be in

.../leo/themes/BreezeDark/img_src/...

or some such?

Cheers -Terry

**Comment by technatica** [comment]
".../leo/themes/BreezeDark/img_src/..."

That is where I will put them.

Chris
