### ISSUE TITLE
Split valuespace plugin in two

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#839]
**Terry Brown**: The valuespace plugin urgently needs to be split in two.

**Update**: Done.  The new commands are eval, eval-block, eval-last, eval-last-pretty and eval-replace, corresponding to the old vs-* commands.

**Terry**: I point to valuespace very time someone's looking for Jupyter/IPython functionality. Most likely they get lost in all the completely separate complexity. Imo, the eval commands are the most generally useful Python evaluation commands in Leo.  Unlike execute-script, results are persistent.  Because you do the work directly in the body pane, autocomplete works and you have syntax highlighting (missing in the Python console)

**Background**

Ville Vainio wrote the original valuespace plugin.  It was a complex and complicated system for spreading bits of information through a Leo tree and then collecting them together, with various levels of evaluation, and then formatting the results into output nodes.  Like a free form database/spreadsheet interspersed with whatever else you were using the outline for.   It defines a namespace, **c.vs** (a Python dict), where
results are stored between runs and available to other scripts.

I wanted to write some expression evaluation commands with persistent results and didn't want to add yet another plugin for something relatively simple, so I added four new commands the valuespace
plugin: vs-eval, vs-last, vs-last-pretty and (more recently) vs-eval-block. (See documentation below).

**To do**

- [x] Create the EvalController class in mod_scripting.py that supports the eval-* commands.
- [x] The [plugins tip](https://github.com/leo-editor/leo-editor/issues/617) should promote the mod_scripting plugin for these commands.
- [x] Document the eval commands in mod_scripting.py

**The eval commands**

**eval**

- Evaluate the selected text, if any, and remember the result.
  For example, `a = 10` sets c.vs['a'] = 10.
- Print the result of the last expression or assignment in the log pane.
- Select the next line of the body pane. This is handy for executing line by line.

**eval-last**: Insert the result of the last vs-eval in the body.

Suppose you have this text:

    The cat is 7 years, or 7*365 days old.

To replace `7*365` with `2555`, do the following:

- select 7*367
- eval
- delete `7*365`
- do eval-last

**eval-last-pretty**: as vs-last, but format with pprint.pformat.

**eval-block**: Evaluate series of blocks of code in the body, separated like this:
```
# >>>
code to run
# <<<
output of code
# >>>
code to run
# <<<
output of code
...
```
For example:
```
import datetime
datetime.datetime.now()
# >>>
2018-03-21 21:46:13.582835
# <<<
datetime.datetime.now()+datetime.timedelta(days=1000)
# >>>
2020-12-15 21:46:34.403814
# <<<
```
vs-eval-block inserts the separators, blocks can be re-run by placing the cursor in them and doing vs-eval-block, and the cursor is placed in the next block, so you can go back up, change something, then quickly
re-execute everything.

**Comment by tbnorth** [comment]
On Mon, 26 Mar 2018 01:52:53 -0700
"Edward K. Ream" <notifications@github.com> wrote:

> To replace 7*365 with 2555, select 7*367, then do vs-eval, delete
> 7*365 and then do vs-last.
> 
> **EKR**: This throws an exception if the valuespace plugin is not
> enabled.  I'll fix this first.

Strange, if it's not enabled there should be no 'vs-eval' command?

**Comment by edreamleo** [comment]
On Mon, Mar 26, 2018 at 7:49 AM, Terry Brown <notifications@github.com>
wrote:

> On Mon, 26 Mar 2018 01:52:53 -0700
> "Edward K. Ream" <notifications@github.com> wrote:
>
> > To replace 7*365 with 2555, select 7*367, then do vs-eval, delete
> > 7*365 and then do vs-last.
> >
> > **EKR**: This throws an exception if the valuespace plugin is not
> > enabled. I'll fix this first.
>
> Strange, if it's not enabled there should be no 'vs-eval' command?
>

One would think so, because @g.command defines each command only if
valuespace.py has been imported.  Perhaps the VS plugin can be imported in
other situations.  I'll look into it.

Edward

**Comment by edreamleo** [comment]
Rev c5c43ec91 completes this item.
