### ISSUE TITLE
Update Docs to Refer To "runLeo" instead of "launchLeo".

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#845]
Leo 5.7 uses `runLeo` instead of `launchLeo` to open Leo.  But the various documentation still refers to using `launchLeo`.  One example is the Cheat Sheet, at http://leoeditor.com/cheatsheet.html.

New users are going to be very frustrated by this if they try to use the command line instead of a launch icon.  They will have no way to know how to get it running.  Even running `pydoc` on `leo` won't help (though I suppose not many new people would know to do this anyway):
```
C:\Users\tom>python -m pydoc leo
Help on package leo:

NAME
    leo - # This file makes the leo directory a package.

FILE
    c:\python27\lib\site-packages\leo\__init__.py

PACKAGE CONTENTS
    commands (package)
    core (package)
    extensions (package)
    external (package)
    modes (package)
    plugins (package)

FUNCTIONS
    run(*args, **keys)
```

I haven't looked around to try to find all the references yet, but at least we could add it to the package doc string and correct the cheat sheet.  Or maybe it would be better to create a new launchLeo file that delegates to runLeo.  Then existing docs and batch files would be OK as is.

**Comment by edreamleo** [comment]
On Thu, Mar 29, 2018 at 9:07 AM, tbpassin <notifications@github.com> wrote:

> Leo 5.7 uses runLeo instead of launchLeo to open Leo. But the various
> documentation still refers to using launchLeo. One example is the Cheat
> Sheet, at http://leoeditor.com/cheatsheet.html.
>
​In both the master and devel branches, the leo-editor folder contains
launchLeo.py​, not runLeo.py.

Afaik, runLeo.py exists only in the pip install version of Leo.  Imo, the
fix involves using launchLeo.py everywhere.

In short, this is not a documentation problem.

Edward
