### ISSUE TITLE
quickstart.leo

### ISSUE THREAD

**Issue by technatica** [leo-editor/leo-editor#855]
/leo-editor/leo/doc/quickstart.leo#Programming-->External files

A clear discussion of @thin, @auto and @shadow including exercises.

No mention of @clean.

My guess, and I could be wrong, is that this is a little dated.

**Comment by edreamleo** [comment]
On Mon, Apr 9, 2018 at 10:56 PM, Chris George <notifications@github.com>
wrote:

> /leo-editor/leo/doc/quickstart.leo#Programming-->External files
>
> A clear discussion of @thin <https://github.com/thin>, @auto
> <https://github.com/auto> and @shadow <https://github.com/shadow>
> including exercises.
>
> No mention of @clean <https://github.com/clean>.
>
> My guess, and I could be wrong, is that this is a little dated.
>
​Good catch.  Rev 4cb249f52 contains the fix.

Edward

**Comment by technatica** [comment]
Reading on a little further it seems that the bit about stylesheets could be updated to reflect recent work on themes.

/leo-editor/leo/doc/quickstart.leo#Configuration (enabling plugins etc.)-->@@settings-->suggested style sheets

**Comment by edreamleo** [comment]
Completed at f5b4d6a9d in devel.
