### ISSUE TITLE
Why tabs are above menus

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#861]
_Why is the tab bar with the open files right below the title bar, but above the menu bar and the tool bar? This is different from other IDE's and text editors and is confusing._

Leo uses tabs to switch workspaces (contexts). Each .leo file can define or redefine what menus, settings, plugins and so on are available within it's context. So tabs are the highest level of containment.

**Comment by maphew** [comment]
Cribbed from https://groups.google.com/d/topic/leo-editor/tac0SaJAekM/discussion

**Comment by rengel-de** [comment]
> Leo uses tabs to switch workspaces (contexts). Each .leo file can define or redefine what menus, settings, plugins and so on are available within it's context. So tabs are the highest level of containment.

IMO this is only partly true. There are always menus, menu items, and functions that are globally used (i.e. File, Help, View, the arrangement of panes/windows) AND items that are context-specific, so it's not an either-or question. Other IDEs (i.e. PyCharm) solve this dilemma by providing two menus: one global menu bar and - within a tab - a context-specific menu bar, sometimes even with an additional toolbar. I.e. in the Web Development world this is exemplified by CKEditor (https://docs.ckeditor.com/).

Reinhard

Reinhard
