### ISSUE TITLE
Serious problems changing branches

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#863]
When changing branches somehow the structure of the external file gets over-ridden by the .leo.

Work will be done in the "switch-branches" branch.

**Acid test**

With rev 077587 (or descendants containing an organizer node in g.KeyStoke):

- Select `@`file leoGlobals.leo.
- Remove all children.
- refresh-from-disk.

Because of the organizer, unwanted clones are created.  These clones are the heart of the problem.

**Comment by edreamleo** [comment]
On Fri, Apr 20, 2018 at 1:19 PM, Виталије Милошевић <
notifications@github.com> wrote:

> I can't help much now but this issue could be related with the #542
> <https://github.com/leo-editor/leo-editor/issues/542>. Is the
> createOutlineFromCacheList still as I have left it at the time of fixing
> #542 <https://github.com/leo-editor/leo-editor/issues/542>? AFAIR the fix
> was not very obvious and I wasn't sure that the fix covered all corner
> cases.
>
​Thanks for this information.  I'm happy to fix this.  It may be simply a
matter of deleting all children of the root @<file> node.  If not, it will
be time for me to understand the code thoroughly.  Either way, I'm
confident that a fix will be relatively straightforward.

Edward

**Comment by edreamleo** [comment]
I now have a reproducible situation in which caching appears to be the culprit.

In devel, writing leoKeys.py after loading leoPy.leo with caching will change the file! This does not happen if I load leoPy.leo with the --no-cache.

In my copy of leoPy.leo, there are no clones in the `@`file leoKeys.py tree, so it does not seem possible that clone conflicts are involved.

**Comment by vitalije** [comment]
can you share what is the difference between the two versions of leoKeys.py?

**Comment by edreamleo** [comment]
On Wed, Apr 25, 2018 at 12:27 PM, Виталије Милошевић <
notifications@github.com> wrote:

> can you share what is the difference between the two versions of
> leoKeys.py?
>
​It's primarily a different outline organization.  My notes, which may be
out of date, say that the differences involve k.doMode and
k.callStateFunction.​


​Edward

**Comment by vitalije** [comment]
If you still have the ability to reproduce the bug, please test with this rev e8fcca6

**Comment by vitalije** [comment]
Here is a leo file I have made to reproduce the bug myself. 
[leoBug863.zip](https://github.com/leo-editor/leo-editor/files/1953030/leoBug863.zip)

It contains one at-file node whose one child is cloned. The script saves the outline with the children of cloned node sorted in reverse order, keep the content of the external file and then sort the children in natural order and save file again. Then it replaces the content of the external file with the old content.

When opened again Leo has nodes in wrong order and it overwrite  the file even if user makes no changes at all.

**Comment by edreamleo** [comment]
On Thu, Apr 26, 2018 at 4:28 PM, Виталије Милошевић <
notifications@github.com> wrote:

> Here is a leo file I have made to reproduce the bug myself.
> leoBug863.zip
> <https://github.com/leo-editor/leo-editor/files/1953030/leoBug863.zip>
>
​Thanks for this.  I'll test with it soon.

Edward

**Comment by edreamleo** [comment]
Ok.  I have looked at leoBug863.zip.  It seems like a reasonable test.

I'll close this issue.  Please reopen if necessary.
