### ISSUE TITLE
Detach: AttributeError: 'LeoQtGui' object has no attribute 'getImageImageFinder'

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#864]
Leo Log Window
Leo 5.7.1, build 20180402204423, Mon Apr  2 20:44:23 CDT 2018
Git repo info: branch = master, commit = 5b09e43929bc
Python 3.6.5, PyQt version 5.10.1
linux
isPython3: True
caching enabled
setting leoID from os.getenv('USER'): 'swot'
current dir: /home/swot/leo-editor_bak
load dir: /home/swot/leo-editor_bak/leo/core
global config dir: /home/swot/leo-editor_bak/leo/config
home dir: /home/swot
reading settings in /home/swot/leo-editor_bak/leo/config/leoSettings.leo
reading settings in /home/swot/.leo/myLeoSettings.leo

***

After click tabbar Detach, Show AttributeError and abort.

Traceback (most recent call last):
  File "/home/swot/leo-editor_bak/leo/plugins/qt_frame.py", line 1213, in <lambda>
    a.triggered.connect(lambda checked: self.detach(index))
  File "/home/swot/leo-editor_bak/leo/plugins/qt_frame.py", line 1240, in detach
    icon = g.app.gui.getImageImageFinder("application-x-leo-outline.png")
AttributeError: 'LeoQtGui' object has no attribute 'getImageImageFinder'

**Comment by wangzhaohe** [comment]
Thanks! It runs well now!

But I found another problem in **branch devel**:

/home/swot/.leo/myLeoSettings.leo#@settings-->Menus-->@menus-->@menu &File-->@menu Recent &Files

Recent &Files: F can not be pressed. But it run well in branch master.

**Comment by tbnorth** [comment]
On Thu, 19 Apr 2018 14:13:33 +0000 (UTC)
wangzhaohe <notifications@github.com> wrote:

> Thanks! It runs well now!
> 
> But I found another problem in **branch devel**:
> 
> /home/swot/.leo/myLeoSettings.leo#@settings-->Menus-->@menus-->@menu
> &File-->@menu Recent &Files
> 
> Recent &Files: F can not be pressed. But it run well in branch master.

Not sure I exactly understand the problem.  In both devel and master it
seems that *F*ile-open-by-name is using F, so Recent Files can't.

But Edward has changed some things in the menus recently so maybe he
can see the difference.

He also added / changed the way to translate the "Recent Files" text,
not sure if that's involved.

Cheers -Terry

**Comment by wangzhaohe** [comment]
After some tests I found that:

myLeoSettings.leo: Only one **&** take actions
    @item file-open-by-name
    @menu Recent &Files

or change leoSettings.leo:  Both **&** take actions
    @item &file-open-by-name
    @menu Recent &Files
