### ISSUE TITLE
rst3 changes the html format

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#867]
Today! I run `rst3` in leo minibuffer.  But I found the created html file format has been changed.

The following is html in chrome browser:

code:

1: url info
2:
3: https://work.weixin.qq.com/#indexDownload
4:
5: some description
6:
7: .. image:: pic/mo/wxqy_login_1.jpg
8:    :width: 300 px
9:    :alt: login
10:
11: .. image:: pic/mo/index_call.png
12:    :width: 300 px
13:    :alt: login

Please teach me how to correct this issue.

***

Leo Log Window
Leo 5.7.1, build 20180402204423, Mon Apr  2 20:44:23 CDT 2018
Git repo info: branch = master, commit = 5b09e43929bc
Python 3.5.2, PyQt version 5.5.1
linux
isPython3: True
caching enabled
redefining abbreviation ,, 
from "{|{x='__NEXT_PLACEHOLDER'}|}" to '__NEXT_PLACEHOLDER'
reading: /home/swot/pyenv/xservice36/code/XService.leo
creating recovered node: doc
creating recovered node: doc not used
read 89 files in 1.10 seconds
read outline in 1.27 seconds
09:34:39 wrote: views.py
09:34:39 wrote: admin.py
09:34:39 saved: XService.leo
09:35:50 saved: XService.leo
09:35:58 saved: XService.leo
wrote: /home/swot/pyenv/xservice36/code/manual/engineer.html.txt
wrote: /home/swot/pyenv/xservice36/code/manual/engineer.html
rst3: 1 files in 0.13 sec.

**Comment by wangzhaohe** [comment]
I solved it. After set

@bool rst3_code_mode = False

It runs ok now.

**Comment by edreamleo** [comment]
On Sat, Apr 21, 2018 at 10:06 PM, wangzhaohe <notifications@github.com>
wrote:

> I solved it. After set
>
> @Bool <https://github.com/Bool>
> ​​
> rst3_code_mode = False
>
> It runs ok now.
>
Glad to hear it.  I just checked that this setting is False in
leoSettings.leo, as it should be.

Edward
