### ISSUE TITLE
Special design for Enter Key?

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#869]
with @bool vim-mode = True in myLeoSettings.leo

When focus is on outline, pressing **Enter** key can not enter body pane.
When focus in **find-quick** input, after input some search text, then press **Enter**, log pane displayed with 
```
ignoring  # <===== EKR: a return character.
 in normal mode after 
```

**EKR**: The problem was that vim mode was not recognizing the 'Return' character properly.

**Comment by wangzhaohe** [comment]
After git pull in branch dev, the problem still exist.

When body pane is in **insert** state and focus on outline : press Enter key can focus on body pane.
When body pane is in **command** state and focus on outline : press Enter key can **not** focus on body pane.

Input search text in nav, then press **Enter** key, the focus skip to log pane.

**Comment by edreamleo** [comment]
On Mon, Apr 23, 2018 at 5:14 PM, wangzhaohe <notifications@github.com>
wrote:

> After git pull in branch dev, the problem still exist.
>
> When body pane is in *insert* state and focus on outline : press Enter
> key can focus on body pane.
> When body pane is in *command* state and focus on outline : press Enter
> key can *not* focus on body pane.
>
> Input search text in nav, then press *Enter* key, the focus skip to log
> pane.
>
​I don't see anything amiss, so I'll need your help.

Recent revs in the keys3 branch enable tracing in the vim code by default.

Please show the traces for the cases that don't work for you.

Edward

**Comment by edreamleo** [comment]
On Wed, Apr 25, 2018 at 6:24 PM, wangzhaohe <notifications@github.com>
wrote:

> with @Bool <https://github.com/Bool> vim-mode = True in myLeoSettings.leo
>
> When focus is on outline, pressing Enter key *can focus to body pane* now
> with branch=keys3.
>
​Thanks for this confirmation.

Edward

**Comment by edreamleo** [comment]
Fixed at f76ab4119b in devel.

**Comment by edreamleo** [comment]
I am going to reopen this.  It now fails.  Don't know why.

**Comment by edreamleo** [comment]
Mystery solved.  The --trace-* settings force focus to the log pane.
