### ISSUE TITLE
Seems like yes to all is broken for external file change?

### ISSUE THREAD

**Issue by tbnorth** [leo-editor/leo-editor#873]
Broken in that it keeps asking for each file, not that files aren't loaded properly etc.

Update: while relocating implementation for this issue I saw it both work and not work, makes me wonder if it's a timing issue.  `ExternalFilesController.ask()` has a hard coded 3 second time to live for a "Yes to all" answer, if reloading a single file somehow takes longer than that, it would start asking again.  Only started to notice it recently though.

**Comment by edreamleo** [comment]
I haven't noticed this.

**Comment by edreamleo** [comment]
I am going to close this.  Please reopen if necessary.
