### ISSUE TITLE
For the life of me, I cannot get a @command node to work!

### ISSUE THREAD

**Issue by beetleb** [leo-editor/leo-editor#878]
Hi,

I'm just a beginner at Leo scripting. I can write code, and have it execute with Ctrl-B. Now I want to make a command out of it.

I have a node whose headline is `@command helloworld` and whose body is:

    @language python
    g.es("Hello world!")

How do I access this command? If I do Alt x and type it, it does not see it. If I do Alt x and type @c and press TAB, nothing comes up (as described [here](http://leoeditor.com/FAQ.html#how-can-i-make-commonly-used-scripts-widely-accessible)). 

Note that if I make it a `@button node`, it does work just fine - I can make a button out of it and get it to run, and there is a `@button-helloworld` command.

Finally, I do want to create a command that takes in an argument. I'm confused with the [snippet](http://leoeditor.com/scripting-miscellany.html#getting-interactive-input-in-scripts-and-commands). It invokes a decorater `@cmd`, but that doesn't seem to exist. Furthermore, the functions have `self` as the argument, implying this is part of a class. Where is the rest of the class?

Please help!

Thanks!

**Comment by technatica** [comment]
Hi,

Commands become available when they are loaded from an @settings tree. If
you wish to have the command available to all files in Leo, add a node
called @commands to mySettingsLeo.leo under @settings. Then under that node
create a node called @command helloworld. Close Leo. Reopen Leo and the
command can now be accessed via Alt-x, helloworld.

HTH,

Chris

**Comment by beetleb** [comment]
@technatica,

Thanks. I had tried the @commands node in the settings, but did not realize I have to quit and restart. Is there no way to get it to work without having to close and reopen Leo? It would make development much faster if I didn't have to quit every time I made a change just to test out my change.

In the FAQ, it suggests putting under @commands node in settings if you want the function to exist in other nodes, which made me think that at least within the @command node it would work, but it didn't.

Also, I'm curious about why this behaves differently from @button (which is available immediately without restarting or editing the settings). Most of the docs mention both of them at the same time ("scripting Leo with Python", "Leo in 10 minutes", etc). Probably they should have the disclaimer that one of them needs to be in settings and require a restart.

I don't know if I should open another issue but my other question is still open: How do I make a command that will prompt for a value? The snippet in the docs I linked to in my original question doesn't work.

Thanks again.

**Comment by tbnorth** [comment]
On Tue, 01 May 2018 16:07:06 -0700
beetleb <notifications@github.com> wrote:

> How do I make a command that will prompt for a value?

a_value = g.app.gui.runAskOkCancelStringDialog(
    c, 'Enter a value', 'Please enter a value')
g.log(a_value)

Cheers -Terry

**Comment by edreamleo** [comment]
On Tue, May 1, 2018 at 9:19 PM, beetleb <notifications@github.com> wrote:

> Thanks, but I want a prompt in the command minibuffer. Similarly to, say,
> the prompt we get with the cff command. I don't want a GUI popup.
>
Perhaps CheatSheet.leo should discuss this, with examples.

The GetArg class, in leoKeys.py, handles prompting for input. This class
creates simple state machines. k.masterKeyHandler is aware of these state
machines and dispatches incoming key events accordingly.

The best documentation is well hidden:

leoPy.leo#Code-->Gui base classes-->@file leoKeys.py-->
class KeyHandlerClass-->k.Externally visible helpers-->
Wrappers for GetArg methods--><< docstring for k.get1arg >>

Happily, the docstring is pretty good.  Here it is:

QQQQQ
k.get1Arg: Handle the next character the user types when accumulating a
user argument from the minibuffer. Ctrl-G will abort this processing at any
time.

Commands should use k.get1Arg to get the first minibuffer argument and
k.getNextArg to get all other arguments.

Before going into the many details, let's look at some examples. This
code will work in any class having a 'c' ivar bound to a commander.

*Example 1*: get one argument from the user:

    @cmd('my-command')
    def myCommand(self, event):
        k = self.c.k
        k.setLabelBlue('prompt: ')
        k.get1Arg(event, handler=self.myCommand1)

    def myCommand1(self, event):
        k = self.c.k
        # k.arg contains the argument.
        # Finish the command.
        ...
        # Reset the minibuffer.
        k.clearState()
        k.resetLabel()
        k.showStateAndMode()

*Example 2*: get two arguments from the user:

    @cmd('my-command')
    def myCommand(self, event):
        k = self.c.k
        k.setLabelBlue('first prompt: ')
        k.get1Arg(event, handler=self.myCommand1)

    def myCommand1(self, event):
        k = self.c.k
        self.arg1 = k.arg
        k.setLabelBlue('second prompt: ')
        k.getNextArg(handler=self.myCommand2)

    def myCommand2(self, event):
        k = self.c.k
        # k.arg contains second argument.
        # Finish the command, using self.arg1 and k.arg.
        ...
        # Reset the minibuffer.
        k.clearState()
        k.resetLabel()
        k.showStateAndMode()

*Discussion*

k.get1Arg and k.getNextArg are a convenience methods. They simply pass
their arguments to the get_arg method of the singleton GetArg instance.
This docstring describes k.get1arg and k.getNextArg as if they were the
corresponding methods of the GetArg class.

k.get1Arg is a state machine. Logically, states are tuples (kind, n,
handler) though they aren't represented that way. When the state machine in
the GetArg class is active, the kind is 'getArg'.  This constant has
special meaning to Leo's key-handling code.

The arguments to k.get1Arg are as follows:

[snip: read the actual docstring for details]
QQQQQ


*Actual examples*
To see actual examples, do cff on get1arg in leoPy.leo (or use the Nav pane)

There are about 20 commands that use this pattern. All the examples are
similar.

Two commands are marked with "doesn't work". Perhaps these command should
be removed.

HTH.  Please feel free to ask more questions.

Edward

**Comment by beetleb** [comment]
@edreamleo,

Thanks - this is more or less similar to the link I already found on Leo's page, but with a bit more context and knowing where the code resides, I may be able to figure it out. 

Some quick questions:

I assume get1Arg gets just a keystroke? Or does it get a whole word? I'm guessing  the former and the handler is responsible for maintaining the state machine, and building up the actual text the user is writing and presumably storing it in a member variable?

I'll probably look at cff to understand it in more detail.

Is it not normal for Leo users to need this? Do most go the GUI popup route? I'm coming from Emacs where prompting in the minibuffer is the norm and I'd like to do things that way. I understand the power of the full state machine where every keystroke can have its own function (along with the context of what was typed before it), but I imagine a simple helper function for what I need would be great - where the user of the function does not need to manipulate the state machine. The helper does it for you, waits till Enter is pressed, and simply returns the text the user entered.

Kind of the philosophy of "Have very flexible methods, but then create much simpler classes/methods that handle the 80-90% use cases". Usually full flexibility leads to complexity, but only about 10% of the use cases need that flexibility - hence the utility of helper functions.

**Comment by edreamleo** [comment]
On Wed, May 2, 2018 at 2:59 AM, Edward K. Ream <edreamleo@gmail.com> wrote:

Perhaps CheatSheet.leo should discuss this, with examples.
>

​Done in both "devel" and "5.7.2" branches, with some improved code and
docs.

Edward

**Comment by edreamleo** [comment]
On Wed, May 2, 2018 at 2:11 PM, Edward K. Ream <edreamleo@gmail.com> wrote:
>
> Kind of the philosophy of "Have very flexible methods, but then create
>> much simpler classes/methods that handle the 80-90% use cases". Usually
>> full flexibility leads to complexity, but only about 10% of the use cases
>> need that flexibility - hence the utility of helper functions.
>>
> ​That's what k.get1arg and k.getNextArg do.​ But you could add your own
> convenience methods if you find you are duplicating lots of code.
>

​The new issue: #886: Add c.interactive1/2/3 methods
<https://github.com/leo-editor/leo-editor/issues/886> will add these
convenience methods for you.  They will be part of Leo 5.7.2.

Edward

**Comment by beetleb** [comment]
@edreamleo,

I got it working finally using your original example (k.get1arg). What was tripping me over was the `event` argument. I see it all over the code base, but I don't know where it is for. So I hacked it by passing in `None` as I saw that `get1arg` does not make use of it. Below is the full content of my node.

```
def say_hello(event): 
    g.es("Hello %s" % c.k.arg) 
    c.k.clearState() 
    c.k.resetLabel() 
    c.k.showStateAndMode()

c.k.setLabelBlue('prompt: ') 
c.k.get1Arg(None, handler=say_hello) 
```

I'm now veering off topic, but is there an easy way to note where the focus and cursor is before entering the command, and then restoring it when you exit? The snippet above takes focus away from where it was. 

Thanks for making even easier helper functions - I hope to use them in 5.7.2. Any hope to have @command take effect immediately (like @button does)? Right now I have to close the file and reopen. 

Also, is it OK if I ask all my queries using Github (as opposed to Google Groups)? It's easier for me to track and not worry about too much email.

Thanks.

**Comment by edreamleo** [comment]
On Fri, May 4, 2018 at 6:45 PM, beetleb <notifications@github.com> wrote:

> @edreamleo <https://github.com/edreamleo>,
>
> I got it working finally using your original example (k.get1arg). What was
> tripping me over was the event argument. I see it all over the code base,
> but I don't know where it is for. So I hacked it by passing in None as I
> saw that get1arg does not make use of it. Below is the full content of my
> node.
>
> def say_hello(event):
>     g.es("Hello %s" % c.k.arg)
>     c.k.clearState()
>     c.k.resetLabel()
>     c.k.showStateAndMode()
>
> c.k.setLabelBlue('prompt: ')
> c.k.get1Arg(None, handler=say_hello)
>
>
​Glad to hear it.
​


> I'm now veering off topic, but is there an easy way to note where the
> focus and cursor is before entering the command, and then restoring it when
> you exit? The snippet above takes focus away from where it was.


​This question is completely on topic. If you know where you want the focus
to end up, you can use one of the following:

c.bodyWantsFocus()
c.treeWantsFocus()
c.logWnatsFocus()

etc.  ​These will set the focus properly in most contexts.  You can add the
"Now" suffix to force the focus:

c.bodyWantsFocusNow(), etc.

To get the widget with the present focus, use

w = c.get_focus() # A wrapper for g.app.gui.get_focus.

You can restore focus with either:

c.request_focus(w)
c.set_focus(w)

The former delays the request, which is sometimes useful. The latter sets
the focus immediately.

Getting the focus just right is one of the toughest tasks in Leo.

> Thanks for making even easier helper functions - I hope to use them in
> 5.7.2. Any hope to have @command <https://github.com/command> take effect
> immediately (like @button <https://github.com/button> does)? Right now I
> have to close the file and reopen.
>
​I usually use an @button for prototyping, then use @g.command to create
the command when all is finished.​


> Also, is it OK if I ask all my queries using Github (as opposed to Google
> Groups)? It's easier for me to track and not worry about too much email.
>
​No problem. Many projects use GitHub Issues in addition to, or even a
replacement for, Google Groups.

Edward

**Comment by beetleb** [comment]
@edreamleo,

I think it is safe to close this ticket for now. I did implement the function I wanted, but never had time to try the focus suggestions. Also, I just went through a lot of the keybindings and found that Leo already has a command to do what I want: "extract" (bound to Ctrl-Shift-d). It's not 100% the same as what I had, but close enough. 

If I ever revisit and have more questions related to this, I assume I can reopen the ticket.

**Comment by edreamleo** [comment]
On Fri, Aug 10, 2018 at 4:06 PM, beetleb <notifications@github.com> wrote:

> @edreamleo <https://github.com/edreamleo>,
>
> I think it is safe to close this ticket for now. I did implement the
> function I wanted, but never had time to try the focus suggestions. Also, I
> just went through a lot of the keybindings and found that Leo already has a
> command to do what I want: "extract" (bound to Ctrl-Shift-d). It's not 100%
> the same as what I had, but close enough.
>
> If I ever revisit and have more questions related to this, I assume I can
> reopen the ticket.
>
Sure.  No problem.  Tickets are a good way to communicate.

Edward
