### ISSUE TITLE
g.es can be too slow

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#879]
From [this entry on leo-editor](https://groups.google.com/d/msg/leo-editor/gHfuTvgzTG0/JC2XRySrAQAJ):

I'm working through the slide tutorial scripting leo, and noticed 2 issues.
```python
for p in c.all_positions():
    g.es(' '*p.level(),p.h)
```

1. Log output

I ran the script above on LeoDocs.leo and a small test file. On both LeoDocs and the test file, the output is flat (suggesting all nodes are level 0) not indented position p: 0 for top-level nodes, 1 for their children, as the tutorial states.

**EKR**: For me, the output is properly indented.

2. Performance 'Not responding'

Run the script on LeoDocs: after the log output completes, it hangs with a not responding for ~65seconds.

**EKR** I see this behavior.

**Comment by edreamleo** [comment]
**Note**: There are performance problems when writing many strings to Leo's log pane. The following will hang Leo when run within large .leo files:

    for p in c.all_positions():
        g.es(' '*p.level(), p.h)
 Fixed at c823cc3e2141c (5.7.2 branch) by adding this note:

The workaround is to precompute a single string, and pass it to c.frame.log.put:
```python
    s = ''.join([
        '%s%s\n' % (' '*p.level(), p.h) for p in c.all_positions()
    ])
    c.frame.log.put(s)
```

**Comment by LewisNeal** [comment]
The workaround is very fast.
I still get output which is flat (suggesting all nodes are level 0) and not indented. Will investigate.

**Comment by LewisNeal** [comment]
Mmmm, on a different PC the output to log pane is properly indented.
Leo Log Window
Leo 5.7.2 devel, build 20180423091843, Mon, Apr 23, 2018  9:18:43 AM
Git repo info: branch = devel, commit = 1cfd23379ed0
Python 3.6.5, PyQt version 5.10.1
Windows 10 AMD64 (build 10.0.16299) SP0

**Comment by edreamleo** [comment]
On Tue, May 1, 2018 at 6:41 PM, LewisNeal <notifications@github.com> wrote:

> Mmmm, on a different PC the output to log pane is properly indented.
>
Sounds like a Qt issue.

Edward

**Comment by LewisNeal** [comment]
Test of indented headline to log pane with myLeoSettings.leo enabled, there is no indentation:
_node_number_1
1A
node_number2
2A_

Now running default LeoSettings.leo the indentation appears.
_node_number_1
  1A
node_number2
  2A_
  
Leo 5.7.2 devel, build 20180423091843, Mon, Apr 23, 2018 9:18:43 AM
Git repo info: branch = devel, commit = e09b7148b2a6
Python 3.6.5, PyQt version 5.10.1
Windows 10 AMD64 (build 10.0.16299) SP0

Is there a setting which may suppress the indentation?

**Comment by edreamleo** [comment]
On Wed, May 2, 2018 at 6:00 AM, LewisNeal <notifications@github.com> wrote:

> Test of indented headline to log pane with myLeoSettings.leo enabled,
> there is no indentation:
>
>
>
> *node_number_1 1A node_number2 2A*
>
> Now running default LeoSettings.leo the indentation appears.
>
>
>
> *node_number_1 1A node_number2 2A*
>
> Leo 5.7.2 devel, build 20180423091843, Mon, Apr 23, 2018 9:18:43 AM
> Git repo info: branch = devel, commit = e09b714
> <https://github.com/leo-editor/leo-editor/commit/e09b7148b2a6790e3b0a49838766003d560613ae>
> Python 3.6.5, PyQt version 5.10.1
> Windows 10 AMD64 (build 10.0.16299) SP0
>
> Is there a setting which may suppress the indentation?
>

​Yes.  @bool log_pane_wraps = True

Edward
