### ISSUE TITLE
Replace command does not set @<file> nodes dirty

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#880]
According to my tests, the dirty bit *is* set correctly.

However, it's almost impossible to see this in the EKRDark theme.

**Comment by edreamleo** [comment]
I am going to close this.  Everything appears to be working properly.

**Comment by technatica** [comment]
'<?xml version="1.0" encoding="utf-8"?>

<leo_file xmlns:leo="http://leoeditor.com/namespaces/leo-python-editor/1.1" >
<leo_header file_format="2"/>
<vnodes>
<v t="chris.20180430120602.1" a="E"><vh>@file ~/Working/test.txt</vh>
<v t="chris.20180430120609.1"><vh>node1.txt</vh></v>
<v t="chris.20180430120616.1"><vh>node2.txt</vh></v>
</v>
</vnodes>
<tnodes>
<t tx="chris.20180430120602.1">@others
</t>
<t tx="chris.20180430120609.1">pickle</t>
<t tx="chris.20180430120616.1">chicken</t>
</tnodes>
</leo_file>
'

**Comment by edreamleo** [comment]
On Tue, May 1, 2018 at 9:19 AM, Chris George <notifications@github.com>
wrote:

> I am still seeing the exact behaviour described in the original report.
>

​Thanks for this report.  I'll fix it asap.

Edward

**Comment by edreamleo** [comment]
Fixed at 4a6285ae (devel) by calling c.redraw().
