### ISSUE TITLE
Ctrl+( and Ctrl+) can not work for comments code

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#882]
Ctrl+( and Ctrl+) can not work. After add @shortcuts in myLeoSettings.leo, still can not work.

add-comments = Ctrl-Shift-9
delete-comments = Ctrl-Shift-0

***
Python 3.6.5, PyQt version 5.10.1
linux
isPython3: True
caching enabled
import-jupyter-notebook requires nbformat package
setting leoID from os.getenv('USER'): 'swot'
current dir: /home/swot/leo-editor
load dir: /home/swot/leo-editor/leo/core
global config dir: /home/swot/leo-editor/leo/config
home dir: /home/swot
reading settings in /home/swot/leo-editor/leo/config/leoSettings.leo
reading settings in /home/swot/.leo/myLeoSettings.leo
http serving enabled at 127.0.0.1:8130
reading settings in /home/swot/.leo/workbook.leo
redefining abbreviation ,, 
from "{|{x='__NEXT_PLACEHOLDER'}|}" to '__NEXT_PLACEHOLDER'
reading: /home/swot/.leo/workbook.leo

**Comment by edreamleo** [comment]
On Tue, May 1, 2018 at 5:26 PM, wangzhaohe <notifications@github.com> wrote:

> Ctrl+( and Ctrl+) can not work. After add @shortcuts
> <https://github.com/shortcuts> in myLeoSettings.leo, still can not work.
>
> add-comments =
> ​ ​
> Ctrl-Shift-9
> ​
>
> ​
> delete-comments = Ctrl-Shift-0
>
> ​Rev e9dd842ec (devel) attempts a fix.  Does it work for you?

Edward

**Comment by wangzhaohe** [comment]
With or without
add-comments = Ctrl-Shift-9
delete-comments = Ctrl-Shift-0

Still can not work!

**Comment by edreamleo** [comment]
On Wed, May 2, 2018 at 8:03 AM, wangzhaohe <notifications@github.com> wrote:

> With or without
> add-comments = Ctrl-Shift-9
> delete-comments = Ctrl-Shift-0
>
> Still can not work!
>
​Ok.  You will probably have to try other key bindings.

On my Windows 10 machine, Ctrl-Shift-9 generates Ctrl-Shift-(
Ctrl-Shift-0 generates no key event at all!

I now use the following bindings:

add-comments = Ctrl-[
delete-comments = Ctrl-]

HTH.

Edward

**Comment by edreamleo** [comment]
I am going to close this issue.  I know of no way to improve the present code.

**Comment by tbnorth** [comment]
I assume this didn't work before the new keys code?

**Comment by edreamleo** [comment]
On Wed, May 2, 2018 at 9:12 AM, Terry Brown <notifications@github.com>
wrote:

> I assume this didn't work before the new keys code?
>

I'm not so sure myself.  I think ks.finalize_char needs more work.

Edward

**Comment by edreamleo** [comment]
Please try recent revs in devel.  It's fine to reopen this issue if problems remain.  There is still plenty of time to get everything exactly right.

**Comment by wangzhaohe** [comment]
Now it works after **git pull** to 5aa64f91cadb

Leo Log Window
Leo 5.7.2 devel, build 20180423091843, Mon, Apr 23, 2018  9:18:43 AM
Git repo info: branch = devel, commit = 5aa64f91cadb
Python 3.6.5, PyQt version 5.10.1
linux
isPython3: True
caching enabled

**Comment by edreamleo** [comment]
On Wed, May 2, 2018 at 9:32 PM, wangzhaohe <notifications@github.com> wrote:

> Now it works after *git pull* to 5aa64f9
> <https://github.com/leo-editor/leo-editor/commit/5aa64f91cadbb64efa934c8fc4b6fbc87b305136>
>
​Many thanks for this confirmation. Recent changes were non-trivial.

Edward
