### ISSUE TITLE
Log pane does not handle leading whitespace properly

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#884]
First noticed at #879 
Indentation does not show in log pane when @bool log_pane_wraps = True
Is there a problem with the setting? Wrapping a line should not affect the indentation status of the next line.

**Comment by edreamleo** [comment]
On Thu, May 3, 2018 at 12:17 AM, LewisNeal <notifications@github.com> wrote:

> First noticed at #879
> <https://github.com/leo-editor/leo-editor/issues/879>
> Indentation does not show in log pane when @Bool <https://github.com/Bool>
> log_pane_wraps = True
>
Is there a problem with the setting?
>
​No. There is a problem with the code in LeoQtLog.put that converts the
incoming string to html for the Qt log widget.  I'll attempt a fix
immediately.

Edward

**Comment by edreamleo** [comment]
Fixed in devel at 67aaedb77.
