### ISSUE TITLE
Crash in checkForChangedNodes when switching git branches

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#892]
Here is the traceback:
```
[a64] c:\leo.repo\leo-editor>rem leo.bat

[a64] c:\leo.repo\leo-editor>python c:\leo.repo\leo-editor\launchLeo.py --gui=qttabs --gui=qttabs leo\core\leoPy.leo leo\plugins\leoPlugins.leo c:\Users\edreamleo\ekr-projects.leo leo\doc\LeoDocs.leo

reading settings in C:/leo.repo/leo-editor/leo/config/leoSettings.leo
reading settings in C:/Users/edreamleo/.leo/myLeoSettings.leo
reading settings in c:/leo.repo/leo-editor/leo/core/leoPy.leo
reading settings in C:/leo.repo/leo-editor/leo/themes/EKRDark.leo

Leo 5.7.2 devel, build 20180423091843, Mon, Apr 23, 2018  9:18:43 AM
Git repo info: branch = devel, commit = cb0abffb9c28
Python 3.6.3, PyQt version 5.6.2
Windows 10 AMD64 (build 10.0.16299) SP0
** isPython3: True
** caching enabled

reading settings in c:/leo.repo/leo-editor/leo/core/leoPy.leo
creating recovered node: g.execGitCommand
creating recovered node: gdc.__init__ & helper
creating recovered node: gdc.find_git_working_directory
Traceback (most recent call last):
  File "c:\leo.repo\leo-editor\launchLeo.py", line 8, in <module>
    leo.core.runLeo.run()
  File "c:\leo.repo\leo-editor\leo\core\runLeo.py", line 74, in run
    g.app.loadManager.load(fileName, pymacs)
  File "c:\leo.repo\leo-editor\leo\core\leoApp.py", line 2285, in load
    ok = lm.doPostPluginsInit()
  File "c:\leo.repo\leo-editor\leo\core\leoApp.py", line 2325, in doPostPluginsInit
    c = lm.loadLocalFile(fn, gui=g.app.gui, old_c=None)
  File "c:\leo.repo\leo-editor\leo\core\leoApp.py", line 3159, in loadLocalFile
    c = lm.openFileByName(fn, gui, old_c, previousSettings)
  File "c:\leo.repo\leo-editor\leo\core\leoApp.py", line 3200, in openFileByName
    ok = lm.readOpenedLeoFile(c, fn, readAtFileNodesFlag, theFile)
  File "c:\leo.repo\leo-editor\leo\core\leoApp.py", line 3375, in readOpenedLeoFile
    readAtFileNodesFlag=readAtFileNodesFlag)
  File "c:\leo.repo\leo-editor\leo\core\leoFileCommands.py", line 884, in openLeoFile
    silent=silent,
  File "c:\leo.repo\leo-editor\leo\core\leoFileCommands.py", line 710, in getLeoFile
    recoveryNode = fc.readExternalFiles(fileName)
  File "c:\leo.repo\leo-editor\leo\core\leoFileCommands.py", line 844, in readExternalFiles
    c.atFileCommands.readAll(c.rootVnode(), force=False)
  File "c:\leo.repo\leo-editor\leo\core\leoAtFile.py", line 758, in readAll
    at.read(p, force=force)
  File "c:\leo.repo\leo-editor\leo\core\leoAtFile.py", line 505, in read
    s, loaded, fileKey = c.cacher.readFile(fileName, root)
  File "c:\leo.repo\leo-editor\leo\core\leoCache.py", line 393, in readFile
    self.createOutlineFromCacheList(root.v, aList, fileName=fileName)
  File "c:\leo.repo\leo-editor\leo\core\leoCache.py", line 172, in createOutlineFromCacheList
    self.checkForChangedNodes(child_tuple, fileName, parent_v)
  File "c:\leo.repo\leo-editor\leo\core\leoCache.py", line 199, in checkForChangedNodes
    child_v.children[i] = self.c.fileCommands.gnxDict.get(gnx)
IndexError: list assignment index out of range
```

**Comment by edreamleo** [comment]
Imo, this need not delay 5.7.2. It seem rare, it will likely affect only devs, it can't be ignored (Leo fails to start) and the workaround is clear: restart with --no-cache. More importantly, this is not as serious a problem as was fixed in #863.  The structure of the outline never is in jeopardy.

This is a very strange bug. The last lines of the traceback are:
```
File "c:\leo.repo\leo-editor\leo\core\leoCache.py", line 199,
in checkForChangedNodes
    child_v.children[i] = self.c.fileCommands.gnxDict.get(gnx)
IndexError: list assignment index out of range
```
The crash happens in the last line below:
```python
for i, grand_child in enumerate(grand_children):
    gnx = grand_child[2]
    child_v.children[i] = self.c.fileCommands.gnxDict.get(gnx)
```
But how can i get out of range?  Regardless of the relative lengths of grand_children and child.v.children[], enumerate will yield i = 0, 1, 2...
```
   child_v.children[0] = object1
   child_v.children[1] = object2
   ...
```
I can find nothing wrong with the code above.

Git blame says Vitalije write this code. Vitalije, do have any ideas?

**Comment by edreamleo** [comment]
Hmm.  I just found an unexpected clone (of the node gdc.run & helpers) in the file (commands/editFileCommands) that appears to have caused the crash.

I'm not sure whether this clone was a cause or effect of the bug.

**Comment by edreamleo** [comment]
Oh joy.  I got this crash again after doing the following:

- Delete the unexpected clone in commands/editFileCommands.
- Save the outline, which updates commands/editFileCommands.
- gco (git checkout) leo, to revert commands/editFileCommands.

Leo prompts me to reload commands/editFileCommands. I say yes and the crash occurs.

This is excellent, because now I can add code in leoCache.py to see exactly what happens when an IndexError happens.  Stay tuned.

**Comment by edreamleo** [comment]
Mystery solved. Here is a simple test:

a = [1, 2, 3]
a[2]=6 # Ok
a[3] = 4 # Index error

So array[i] = x will raise IndexError if len(array) <= i.  An assignment does *not* extend the array.

**Comment by edreamleo** [comment]
Rev e6d926531 (devel) adds a hack, as follows:
```python
for i, grand_child in enumerate(grand_children):
    gnx = grand_child[2]
    v = self.c.fileCommands.gnxDict.get(gnx)
    if i < len(child_v.children):
        child_v.children[i] = v
    elif i == len(child_v.children):
        child_v.children.append(v)
    else:
        g.trace('Corrupted cache. Use --no-cache')
        g.printObj(child_v.children)
        raise IndexError
```
Imo, we can't add empty entries in child_v.children, so warning and re-raising IndexError seems appropriate.

This issue is **not** fully resolved.  The extra clone in commands/editFileCommands may have caused data loss.  The nodes "gdc.diff_two_branches (NEW)" and "gdc.get_file_from_branch" seem to have been deleted, although I'm not quite sure.

**Comment by edreamleo** [comment]
I am close to concluding that cacher.createOutlineFromCacheList is unsound.

Certainly cacher.checkForChangedNodes is dubious.  I particularly dislike this comment, which according to git blame is mine:
 ```
# If the outline is out of sync, there may be write errors later,
# but the user should be handle them easily enough.
```

**Comment by vitalije** [comment]
I have rewritten cacher.readFile. Previously, cacher.createOulineFromCacheList performed two separate tasks one was recreating outline and the other was collecting informations on changed clones to be reported later. Now those two tasks are performed in two separate methods. I can't reproduce the initial bug to test whether new code will fix it. If you can please check with 8ce10fa

**Comment by edreamleo** [comment]
On Mon, May 7, 2018 at 6:32 AM, Виталије Милошевић <notifications@github.com
> wrote:

> I have rewritten cacher.readFile. Previously, cacher.createOulineFromCacheList
> performed two separate tasks one was recreating outline and the other was
> collecting informations on changed clones to be reported later. Now those
> two tasks are performed in two separate methods. I can't reproduce the
> initial bug to test whether new code will fix it. If you can please check
> with 8ce10fa
> <https://github.com/leo-editor/leo-editor/commit/8ce10fab7142952579c255efccea9948302e78e5>
>
​Many thanks for this work.  We can leave this item open until it is tested
thoroughly.

Edward

**Comment by edreamleo** [comment]
I shall close this item.  Please reopen if any problems remain.  We have until late in the 5.7.3 release cycle continue testing.
