### ISSUE TITLE
Python Console gets stuck on IndentationError

### ISSUE THREAD

**Issue by dannyob** [leo-editor/leo-editor#893]
**Status**:

- EKR is responsible for the multiLine hack in PyInterp.doEnter.
- A complete rethink of PyInterp.doEnter will be required.
- The multiLine hack was intended to fix #792: python_console plugin doesn't handle copy/paste properly,
  but it has just created more problems.

**Initial report**

If you type an if ... statement into the Python console tab, and continue the line, the console will throw an IndentationError exception, but it's not clear how to either reset the indentation, or correctly add new indentation.
```
Type !hist for a history view and !hist(n) history index recall
Type !clear to clear this pane
>>> if (1):
 ...   print("hello")
  File "<input>", line 2
    ...   print("hello")
    ^
IndentationError: expected an indented block
... 
  File "<input>", line 2
    ...   print("hello")
    ^
IndentationError: expected an indented block
... 
```

**Comment by edreamleo** [comment]
Fixed at 53da5e0 in devel.
