### ISSUE TITLE
Copy expanded node to clipboard

### ISSUE THREAD

**Issue by largo84** [leo-editor/leo-editor#900]
Copy selected node text and all expansions (@others and << Section >> refs) to the clipboard. This would accomplish the same thing as creating an @clean file, opening the file in another text editor, copy all.

Discussed [here in the forum](https://groups.google.com/d/msg/leo-editor/7B9tlI-Ko_M/p66LUVtfCgAJ).
The copied text would:
- include @language specific comments from between @/@c doc parts.
- *not* include @other and << Section >> ref text.
- look exactly like an external @clean file.

The benefits would be making it easier to copy entire code blocks to external applications such as VBA scripts and HTML (perhaps others as well) without the need to create external files and have to use external editors. This then, would make cloning possible.

**Comment by edreamleo** [comment]
As Vitalije points out, the following suffices. It can be executed as is, or made the body of an `@button` node:
```python
s = g.getScript(c,p,useSentinels=False)
g.app.gui.replaceClipboardWith(s)
```
