### ISSUE TITLE
Global and local @outline-data tree-abbreviations

### ISSUE THREAD

**Issue by largo84** [leo-editor/leo-editor#904]
Discussed [here](https://groups.google.com/d/msg/leo-editor/EIGXJpW5MpI/MZTpPqrwBwAJ) in the forum. Feature request to allow local (user) xxx.leo files to append tree abbreviations to what is already in global myLeoSettings.leo.

Currently, if there is an @outline-data tree-abbreviations setting in a local file, they override the global abbreviations.

Rob...

Comment from Terry: I realize I was thinking of regular `@data` `@settings` nodes when I commented in the above thread, but I think this idea can be extended to `@outline-data` nodes.

**Comment by edreamleo** [comment]
This is indeed feasible. It will require special-case code.  I'll do it soon.

**Comment by edreamleo** [comment]
Rev be87a4aa2 in devel completes this item.  Please reopen if you discover any problems.
