### ISSUE TITLE
Dubious major projects

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#906]
The following projects are **highly risky** and may be **less useful** than might appear at first.  If you are interested in either project, please make yourself known to Leo's core devs **before** doing any programming work. See the post [Leo can be embedded in VS Code if...](https://groups.google.com/forum/#!topic/leo-editor/uESWp-eL8AY) for more details.

**Update**: Embedding Leo in another IDE/Editor *is* feasible.

[leoInteg](https://github.com/boltex/leointeg/tree/master) has EKR's full support. It defines a server that can be used as the starting point for embedding Leo in pyzo, vim, or emacs. tfer has expressed interest in embedding Leo vim

The post [ENB: Serious doubts about embedding Leo](https://groups.google.com/d/msg/leo-editor/4kYSK-aIHRg/o0ejILh1AgAJ). However, my thinking is that embedding Leo in emacs, say, would give Leonistas the chance to cooperate *and* compete with org mode.

**Dubious Project**: Leo can be rewritten in JavaScript (or other language) if:

a) Somebody (not one of Leo's present devs) takes full responsibility for doing so.
b) All appropriate unit tests pass.
c) Leo's python API remains completely unchanged.
d) EKR approves.

The post [ENB: Why python will remain Leo's future](https://groups.google.com/forum/#!msg/leo-editor/EaAX7R3_3N0/jKuCjwcuCgAJ) tells why rewriting Leo's core would likely be a mistake. Python is:

- Best for users as the simplest and most flexible scripting language.
- The basis for Leo's API.
- Able to support scripting in any language.

**Comment by maphew** [comment]
IMO the phrase "about Leo's future" should be used for the interesting and cools things which core devs **do** wish to see, a vision of the possible desirable future(s).  ...that said I failed to come up with a suitable reformulation for this thread's subject. "Future paths unlikely to follow" perhaps?

**Comment by edreamleo** [comment]
On Tue, May 22, 2018 at 2:23 PM, matt wilkie <notifications@github.com>
wrote:

> IMO the phrase "about Leo's future" should be used for the interesting and
> cools things which core devs *do* wish to see, a vision of the possible
> desirable future(s). ...that said I failed to come up with a suitable
> reformulation for this thread's subject. "Future paths unlikely to follow"
> perhaps?
>
​I'm not too concerned about the title, or the contents.  There are many
other info and enhancement items that pretty much do the job.


Edward
