### ISSUE TITLE
Create summary of Leo's features

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#908]
To do: create a list/matrix of essential Leo features, compared to other IDE's.  This should be useful for everyone: Leo's devs, power users, and newbies.

**Comment by edreamleo** [comment]
I am not sure this is a good idea.  Leo's FAQ already provides such a summary.  Do we really need yet more documentation?

**Comment by LewisNeal** [comment]
'Do we really need yet more documentation? '
Often not, but it is always useful to review and improve the Leo docs. The FAQ really doesn't present a list/matrix of essential Leo features in comparison to other IDE's. 
If such a table existed it may be most suited the preface 'A brief summary of Leo.'

**Comment by edreamleo** [comment]
On Sun, May 27, 2018 at 8:09 AM, LewisNeal <notifications@github.com> wrote:

> 'Do we really need yet more documentation? '
> Often not, but it is always useful to review and improve the Leo docs. The
> FAQ really doesn't present a list/matrix of essential Leo features in
> comparison to other IDE's.
> If such a table existed it may be most suited the preface 'A brief summary
> of Leo.'
>

​Thanks for these comments. Still dithering about what, if anything, is
needed.

Edward

**Comment by edreamleo** [comment]
I think the FAQ is the right place for this kind of thing.  We could have one or more entries comparing Leo to other editors, and especially discussing Leonine alternatives to features in other editors.
