### ISSUE TITLE
How to use LaTex with Leo

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#909]
It's easy to use LaTex with Leo. This info item tells how.

**Create external files**: `@clean` create an external file without Leo sentinels, that is, without extra LaTex/tex comment lines.  Leo will automagically incorporate changes you make outside Leo into the `@clean` outline.

Leo may place newly-added lines at the boundary of two nodes in the "wrong" node. If that happens, just move the line to the correct node and save the outline.  Leo will remember what you did.  The next time you open the outline, the moved line will be in the correct node.

**Automate your work flow**: g.execute_shell_commands executes commands without hanging Leo. For example:
```python
g.execute_shell_commands([
    '"C:\Program Files (x86)\SumatraPDF\SumatraPDF.exe",
    'latex_test.pdf'
]) 
```
The argument to g.execute_shell_commands can be a string containing a *single* command, or a list one or more commands, as shown above. 

You can put calls to g.execute_shell_commands into an `@button` or `@command` node to create visible buttons and/or commands that you can execute by name from the minibuffer.

**Comment by dalcolmo** [comment]
Hello Edward,

I still would like to see the possibility to have @clean nodes inside other @clean nodes. The descendant @clean nodes should read/write only to their own file specified in the descendant node, not to the ancestor node. This way it would be possible to place @file nodes as children of any node which contains an \input statement, thereby keeping the @file and the related \input statement close together, which I find better than using links (what I do now  as a workaround).

In addition, I would appreciate if @ignore nodes would be doing what they are supposed to do as descendants of @clean nodes. This would facilitate notes, links to binary files etc. The workaround for me is to use urls only in the head of such descendant nodes, and to comment out the body, which is often only a note to myself anyway.

The next thing would then be a latex importer ...  - Josef
