### ISSUE TITLE
Shadow filenames collide

### ISSUE THREAD

**Issue by tbnorth** [leo-editor/leo-editor#91]
Not very high priority and not a blocker for a release, but nice to get this cleaned up sometime.

With
```
@string shadow_subdir = ~/.leo/shadow
```
to keep shadow files out of a project's working directory, @shadow filenames will collide.  A specific use case is the Django web application framework (for which Leo is otherwise extremely well suited as an IDE) which has multiple directories with contents named the same way, but pretty much any common filename will cause collisions, readme.txt for example.  I don't think this is specifically related to #89

The only solution that springs to mind is using a hash of the file's path for that shadow filename in ~/.leo/shadow.  That would break when the path changes.  Perhaps something like
```
da39a3ee5e6b4b0d3255bfef95601890afd80709_32275_20141105113754_readme.txt
```
with the four fields being:

 1. a hash of the file's path
 2. the file's length
 3. the file's modification date
 4. the file's name

with the last three being used only to guide recovery when the first one fails.

That would mean a new file name every time the file's modified, so deleting older shadow files with the same hash would be needed, and safe.

**Comment by edreamleo** [comment]
This issue will become moot in the near future when @nosent replaces both @auto and @shadow.
