### ISSUE TITLE
Drag and Drop Node on Node to Create Clone

### ISSUE THREAD

**Issue by technatica** [leo-editor/leo-editor#919]
Before I discovered Leo (has it really been ten years?) I used a program called piggydb. The one feature I used a lot was creating what it called a relationship between two nodes. You could drag a node onto another node and it would create a child node which was a one-way copy of the dropped node. ie. Clicking "Edit" on the child node brings up the original node in the editor. "Relationship" views are updated when saving the original in the editor.

Needless to say that as useful as this was for me then, Leo is far more flexible.

But I miss the drag and drop. Is there a way (I know, there is always a way, I just don't know it yet) to have a dropped node kick up a context menu (like file managers do) and have a few options presented (move, copy, drop clone)? Such a feature would have to be entirely configurable of course. An @bool to turn on/off and the ability to choose what shows on the menu would do it.

Better yet; a setting to determine default action for drag and drop with the ability to choose drop copy, move, or clone.

It just struck me that this might be possible with a shortcut key/mouse button combo.

And sure enough, click-drag-Ctrl drops a clone.

Sometimes all we need is someplace to think out loud. :-)

**Comment by edreamleo** [comment]
On Mon, Jun 4, 2018 at 12:56 PM, Chris George <notifications@github.com>
wrote:

Is there a way
> ​..to have a dropped node kick up a context menu (like file managers do)
> and have a few options presented (move, copy, drop clone)?
>

​I'm pretty sure there is, but I'm having trouble finding it.  Look for
@popup_menus and @rclick in leoSettings.leo, and perhaps other places.

Edward

**Comment by technatica** [comment]
Having modifier keys change the default drop works.

But I couldn't really find where the modifiers are defined in the settings/docs. Experimenting found it for me. It also informs me that Alt and Shift do nothing. Using them nets the default "move".

So click-drag-Ctrl drops a clone, click-drag-Shift and click-drag-Alt do not change from click-drag. The only option that might be useful is copy and it is not readily apparent how to make that happen.
