### ISSUE TITLE
Enhancement Request:  @readonly file-pathname

### ISSUE THREAD

**Issue by SegundoBob** [leo-editor/leo-editor#920]
Several times over the years I've wanted this directive.  I want it to use sentinels just like @file. I've always been able to make do with the current facilities.  I'm making this request because the need, though no necessity, keeps recurring.  That is, the current options do not completely cover the reasonable use cases.

My need now is that I want a standard menu in only a few (4 to 10) Leo-Editor files, not all of them.  This requires the same @settings subtree in those 4 to 10 Leo-Editor files.  Of course, I want to source control the menu.  I do this as follows:
```
/pri/git/leo_database
    code.leo
        @file py-txt/leo_database_menu.txt
            @settings
```
Other files where the menu is not source controlled but the menu is used:
```
    books.leo
        @file '/pri/git/leo_database/py-txt/leo_database_menu.txt'
```
This works, but it exposes my standard menu file to being changed by any of the files that use it.  It would be much better to only allow it to be changed by '/pri/git/leo_database/code.leo'.  That is, it would be better to have:
```
    books.leo
        @readonly '/pri/git/leo_database/py-txt/leo_database_menu.txt'
```
Ideally Leo-Editor would disable editing in the @readonly subtree.  But I think it would be acceptable to display an error message and **NOT** write the file whenever normal file writing would occur.

SegundoBob

**Comment by edreamleo** [comment]
I am not going to do this.  It would be complex, dangerous, and of limited use for most people.
