### ISSUE TITLE
Enhancement Request: @settings-file Specify a Leo-Editor file containing settings

### ISSUE THREAD

**Issue by SegundoBob** [leo-editor/leo-editor#923]
Last night going to sleep, this idea occurred to me.  It would make enhancement requests https://github.com/leo-editor/leo-editor/issues/920 and https://github.com/leo-editor/leo-editor/issues/921 unnecessary; and I  prefer this idea.

The idea is to allow any Leo-Editor file to contain any number of nodes whose headlines specify a Leo-Editor file containing settings.  The specified Leo-Editor file would be processed like LeoSettings.leo and myLeoSettings.leo.  The contents of the settings file would not be displayed.

Since any Leo-Editor file can contain any number of @settings nodes, it seems reasonable to hope that implementing @settings-file would not be too hard.

I don't care what the directive is named.  @settings-file is just a suggestion.

**Comment by largo84** [comment]
I have similar issues trying to synchronize settings among multiple Leo installations in multiple locations on multiple platforms (Win10 and OSX). Something like this could possibly make that much easier to do. Currently, I have no solution that works without losing sync. I tried the clone thing, but that doesn't work.

**Comment by tbnorth** [comment]
On Wed, 06 Jun 2018 19:21:22 -0700
Rob Keeney <notifications@github.com> wrote:

> I have similar issues trying to synchronize settings among multiple
> Leo installations in multiple locations on multiple platforms (Win10
> and OSX). Something like this could possibly make that much easier to
> do. Currently, I have no solution that works without losing sync. I
> tried the clone thing, but that doesn't work.

The leo_cloud plugin solves this moderately well.  It's not perfect,
but depending on your workflow it might help.

Cheers -Terry

**Comment by largo84** [comment]
Just starting to experiment w/ the plugin. It seems to work locally using FileSystem (Dropbox). However, I don't see any files added to the Dropbox location. Where/how is the plugin saving the data?

**Comment by tbnorth** [comment]
On Wed, 06 Jun 2018 20:57:06 -0700
Rob Keeney <notifications@github.com> wrote:

> Just starting to experiment w/ the plugin. It seems to work locally
> using FileSystem (Dropbox). However, I don't see any files added to
> the Dropbox location. Where/how is the plugin saving the data?

I just tried this based on the doc. string:

type: FileSystem
root: ~/r/leo_cloud
ID: my_notes
read_on_load: ask
write_on_save: ask

but didn't see output until I changed it to:

root: /home/tbrown/r/leo_cloud

which suggests it's not doing ~ substitution properly, which is odd,
I'm sure that's working for Git based backends.  That might be your
immediate problem.  It also seemed to be wanting to reload when no
changes were present, I'll look into that.

Cheers -Terry

**Comment by tbnorth** [comment]
I've fixed the failure to expand "~", and realize it was always asking because that's what `ask` does, for general use `background` is a more sensible setting.

**Comment by largo84** [comment]
Seems to be working now. Will experiment more when I get home from traveling next week. It appears this will do exactly what I was looking for. Not sure if addresses @SegundoBob concerns.

**Comment by edreamleo** [comment]
This would be a difficult project.  Leo's settings are too complicated as they are.
