### ISSUE TITLE
Add goto-prev-marked command

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#927]
The [OP](https://groups.google.com/forum/#!topic/leo-editor/3JxpM6ypU9I) asks: "Does Leo have the ability to go back to the "previous edited line" or "marked line"?  Leo's prev/back buttons (nav_qt.py) select the previous/next node.  These are the same as the goto-next/prev-history-node commands.

There is a goto-next-marked command, so adding a goto-prev-marked node command is natural.

**Comment by tbpassin** [comment]
EditPlus uses F9 to toggle a bookmark on and off; F4 to go to the next bookmark.  These work very well, and I have rarely regretted not having a "go-to-prev-bookmark" command.  

Currently, Leo does not seem to have a "toggle bookmark" command, and I find that is more convenient than just having "set bookmark" and "clear bookmark" commands (one less key assignment to remember).  OTOH, I can see the bookmarks with Editplus and I haven't found a way to get visible bookmarks with Leo yet (is that a pyQt4 vs pyQt5 thing?).  So I wouldn't want to get rid of a "clear all bookmarks" command.
