### ISSUE TITLE
Index of top Launchpad wishlist items

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#93]
The following have been transferred from #73 in order to mark them as wishlist items.

Won't do
------------

https://bugs.launchpad.net/leo-editor/+bug/1259974
Leo should watch @ node contents for external updates

This request is infeasible.  Suppose that the external files has changed.  It would be unwise and unsafe to reload the entire file.

Completed
-------------------

[Fixed, using leoExternalFiles.py]

https://bugs.launchpad.net/leo-editor/+bug/1259755
Leo should keep the external editor's temp file up to date

[Fixed at rev 1f1a110] https://bugs.launchpad.net/leo-editor/+bug/1159490
"Open with" fails to copy changes by external editor back to Leo-Editor node
The solution simply to change the default of the following setting as shown::
    
    @bool open_with_save_on_update = True

[Done at rev b0f5e55] https://bugs.launchpad.net/leo-editor/+bug/1247140
Wishlist: Command History in minibuffer

**Comment by misdvickysue** [comment]
How do I delete all of this  github 

Sent from Yahoo Mail on Android 
 
  On Mon, Apr 4, 2016 at 9:28 PM, Edward K. Ream<notifications@github.com> wrote:   
Closed #93.

**Comment by edreamleo** [comment]
For any bug, click on the unsubscribe in the right panel.
