### ISSUE TITLE
Toggle Behaviour: Home and End

### ISSUE THREAD

**Issue by ghost** [leo-editor/leo-editor#931]
When editing I often want to move to the beginning of the current visible line. "Home" moves the cursor to the beginning of the line which in my case is usually the beginning of the paragraph, several lines up. "End" does the same in the opposite direction.

The behaviour I describe is the default for many editors including LibreOffice Writer and Kate.

Having this behaviour available as an @bool option would be great.

**Comment by edreamleo** [comment]
@ghost I doubt that this issue can be fixed directly. But I'll delegate it to you :-)
