### ISSUE TITLE
Leo clears the user's clipboard on first time startup

### ISSUE THREAD

**Issue by tbnorth** [leo-editor/leo-editor#933]
Kind of a nit, but when Leo creates workbook.leo, it replaces the contents of the system clipboard with XML of a Leo node. It's bad form to change the clipboard content without the user explicitly triggering that change.  E.g. I copied a code snippet I wanted to paste into Leo, but when Leo opened my snippet was gone.  And I'd closed the app. that I'd copied it from.

Steps:

 - delete ~/.leo/workbook.leo
 - copy some text to clipboard
 - python3 /home/tbrown/leo-editor/launchLeo.py --no-splash
 - Ctrl-V paste in new workbook.leo
 - rather than copied text, see xml, starting with:
```
    <?xml version="1.0" encoding="utf-8"?>
```
**EKR**: I see this behavior on both Windows 10 and Ubuntu.  That's good news.

**Comment by edreamleo** [comment]
On Tue, Jun 26, 2018 at 8:51 AM, Terry Brown <notifications@github.com>
wrote:

> Kind of a nit, but when Leo creates workbook.leo, it replaces the contents
> of the system clipboard with XML of a Leo node.
>

​Really​?  Doesn't happen for me on Windows or Linux, with either devel or
fast-read.

Edward

**Comment by tbnorth** [comment]
Reproduced in

Leo 5.7.4 devel, build 20180607085129, Thu Jun  7 08:51:29 CDT 2018
Git repo info: branch = fast-read, commit = 90537765338e
Python 3.6.5, PyQt version 5.9.5
linux

Ubuntu 18.04 / i3 window manager ... clipboard stuff is highly variable.  Steps:

 - delete ~/.leo/workbook.leo
 - copy some text to clipboard
 - python3 /home/tbrown/leo-editor/launchLeo.py --no-splash
 - Ctrl-V paste in new workbook.leo
 - rather than copied text, see 
```
<?xml version="1.0" encoding="utf-8"?>
<!-- Created by Leo: http://leoeditor.com/leo_toc.html -->
<leo_file xmlns:leo="http://leoeditor.com/namespaces/leo-python-editor/1.1" >
<leo_header file_format="2"/>
<vnodes>
...
```

**Comment by edreamleo** [comment]
Rev 43a2672b5 not only fixes this issue, but improves clipboard handling in other ways:

- LM.openEmptyWorkBook now saves/restores clipboard.
- Deleted qt_gui.setClipboardSelection. It is now a synonym for replaceClipboardWith.
- qtew.setSelectionRange now sets the selection only if there is selected text.
