### ISSUE TITLE
Hang on Session Start

### ISSUE THREAD

**Issue by technatica** [leo-editor/leo-editor#936]
I have a music collection. I use Picard to manage file and folder names. I use @path to read the folders and files into Leo where I can then load lyrics and my own personal notes into a searchable database that mirrors my file system. I can launch files using Leo's launch URL function so this has been a very productive way for me to manage my music collection.

I currently have 50,244 files residing in 2,644 folders.

First, some stats on the fast-read branch compared to devel and how it impacts the time to load the Leo file. Using devel it takes 17.24 seconds to load the file. Using fast-read it takes 15.55 seconds.

The problem I am experiencing has to do with loading this file if it is part of a saved session. Leo simply hangs. It gets far enough into loading to draw the outline of the main window but that is it. Hitting Ctrl-C from the command prompt where I launched Leo yields the following clues.

^CTraceback (most recent call last):
  File "./launchLeo.py", line 8, in <module>
    leo.core.runLeo.run()
  File "/home/chris/leo-editor/leo/core/runLeo.py", line 72, in run
    g.app.loadManager.load(fileName, pymacs)
  File "/home/chris/leo-editor/leo/core/leoApp.py", line 2216, in load
    ok = lm.doPostPluginsInit()
  File "/home/chris/leo-editor/leo/core/leoApp.py", line 2261, in doPostPluginsInit
    m.load_session(c1, aList)
  File "/home/chris/leo-editor/leo/core/leoSessions.py", line 77, in load_session
    c2 = g.app.loadManager.loadLocalFile(fn, gui=g.app.gui, old_c=c)
  File "/home/chris/leo-editor/leo/core/leoApp.py", line 3041, in loadLocalFile
    c = lm.openFileByName(fn, gui, old_c, previousSettings)
  File "/home/chris/leo-editor/leo/core/leoApp.py", line 3080, in openFileByName
    ok = lm.readOpenedLeoFile(c, fn, readAtFileNodesFlag, theFile)
  File "/home/chris/leo-editor/leo/core/leoApp.py", line 3255, in readOpenedLeoFile
    readAtFileNodesFlag=readAtFileNodesFlag)
  File "/home/chris/leo-editor/leo/core/leoFileCommands.py", line 859, in openLeoFile
    silent=silent,
  File "/home/chris/leo-editor/leo/core/leoFileCommands.py", line 688, in getLeoFile
    recoveryNode = fc.readExternalFiles(fileName)
  File "/home/chris/leo-editor/leo/core/leoFileCommands.py", line 819, in readExternalFiles
    c.atFileCommands.readAll(c.rootVnode(), force=False)
  File "/home/chris/leo-editor/leo/core/leoAtFile.py", line 701, in readAll
    data = (p.gnx, g.fullPath(c, p))
  File "/home/chris/leo-editor/leo/core/leoGlobals.py", line 3483, in fullPath
    aList = g.get_directives_dict_list(p)
  File "/home/chris/leo-editor/leo/core/leoGlobals.py", line 3002, in get_directives_dict_list
    result.append(g.get_directives_dict(p, root=root))
  File "/home/chris/leo-editor/leo/core/leoGlobals.py", line 2949, in get_directives_dict
    pat = g.compute_directives_re()
  File "/home/chris/leo-editor/leo/core/leoGlobals.py", line 2990, in compute_directives_re
    return "^@(%s)" % "|".join(aList)
KeyboardInterrupt

**Comment by edreamleo** [comment]
On Thu, Jun 28, 2018 at 12:01 PM, Chris George <notifications@github.com>
wrote:

The problem I am experiencing has to do with loading this file if it is
> part of a saved session. Leo simply hangs.
>
​Does this happen in devel as well as fast-read?

Edward

**Comment by technatica** [comment]
Yes. I first noticed it in devel and then thought that it might have to do with the speed of reading the data so I tried it in fast-read as well.

**Comment by edreamleo** [comment]
What do you see when you use the --trace-drawing command-line arg?

**Comment by technatica** [comment]
./launchLeo.py --session-save --session-restore
Open music.leo, close all other files. Close Leo.
./launchLeo.py --session-save --session-restore --trace-draw
Wait for seven minutes.
Ctrl-C in terminal.

Leo 5.7.4 devel, build 20180815095610, Wed, Aug 15, 2018  9:56:10 AM
Git repo info: branch = devel, commit = 2120b6bbb522
Python 3.6.5, PyQt version 5.11.1
linux
** isPython3: True

reading settings in /home/chris/writing/LeoFiles/Music.leo
loadOnePlugin: leo.plugins.livecode.init() returned False
drawTopTree  0.00 sec.
drawTopTree  2.81 sec.

^CTraceback (most recent call last):
  File "./launchLeo.py", line 8, in <module>
    leo.core.runLeo.run()
  File "/home/chris/leo-editor/leo/core/runLeo.py", line 72, in run
    g.app.loadManager.load(fileName, pymacs)
  File "/home/chris/leo-editor/leo/core/leoApp.py", line 2241, in load
    ok = lm.doPostPluginsInit()
  File "/home/chris/leo-editor/leo/core/leoApp.py", line 2286, in
doPostPluginsInit
    m.load_session(c1, aList)
  File "/home/chris/leo-editor/leo/core/leoSessions.py", line 79, in
load_session
    if p.get_UNL() == unl:
  File "/home/chris/leo-editor/leo/core/leoNodes.py", line 755, in get_UNL
    if i.h == p.h:
  File "/home/chris/leo-editor/leo/core/leoNodes.py", line 1622, in __get_h
    return p.headString()
  File "/home/chris/leo-editor/leo/core/leoNodes.py", line 654, in
headString
    return self.v.headString()
  File "/home/chris/leo-editor/leo/core/leoNodes.py", line 2249, in
headString
    if not g.isString(self._headString):
  File "/home/chris/leo-editor/leo/core/leoGlobals.py", line 5563, in
isString
    return isinstance(s, str)
KeyboardInterrupt

**Comment by technatica** [comment]
Opening the file in Leo with --draw-trace enabled:

Leo Log Window

Leo 5.7.4 devel, build 20180815095610, Wed, Aug 15, 2018 9:56:10 AM

Git repo info: branch = devel, commit = 2120b6bbb522

Python 3.6.5, PyQt version 5.11.1

linux

isPython3: True

loadOnePlugin: leo.plugins.livecode.init() returned False

/home/chris/writing/LeoFiles/Music.leo

read outline in 20.75 seconds


Terminal

reading settings in /home/chris/writing/LeoFiles/Music.leo
loadOnePlugin: leo.plugins.livecode.init() returned False
drawTopTree 0.00 sec.
drawTopTree 2.67 sec.
drawTopTree 2.70 sec.

**Comment by technatica** [comment]
music.leo

File references 2,644 subdirectories and  71,240 files using the active
path plugin. The outline tree has a mix of expanded and contracted nodes
with the majority being contracted.

The file opens fine during a regular session ie. I open Leo and then open
the file. The forever hang (I have waited 30+ minutes in the past) only
occurs when music.leo is part of leo.session. ie. one of or the only file
referenced.

**Comment by technatica** [comment]
Here is the terminal output using fast-draw4.

Leo 5.7.4 devel, build 20180815095610, Wed, Aug 15, 2018  9:56:10 AM
Git repo info: branch = fast-draw4, commit = 8b40f0eeda4f
Python 3.6.5, PyQt version 5.11.1
linux
** isPython3: True

reading settings in /home/chris/writing/LeoFiles/InfoTel.leo
loadOnePlugin: leo.plugins.livecode.init() returned False
loadOnePlugin: loaded: leo.plugins.mod_autosave
reading settings in /home/chris/writing/LeoFiles/Music.leo
loadOnePlugin: leo.plugins.livecode.init() returned False
^CTraceback (most recent call last):
  File "./launchLeo.py", line 8, in <module>
    leo.core.runLeo.run()
  File "/home/chris/leo-editor/leo/core/runLeo.py", line 72, in run
    g.app.loadManager.load(fileName, pymacs)
  File "/home/chris/leo-editor/leo/core/leoApp.py", line 2244, in load
    ok = lm.doPostPluginsInit()
  File "/home/chris/leo-editor/leo/core/leoApp.py", line 2289, in doPostPluginsInit
    m.load_session(c1, aList)
  File "/home/chris/leo-editor/leo/core/leoSessions.py", line 79, in load_session
    if p.get_UNL() == unl:
  File "/home/chris/leo-editor/leo/core/leoNodes.py", line 755, in get_UNL
    if i.h == p.h:
  File "/home/chris/leo-editor/leo/core/leoNodes.py", line 1622, in __get_h
    return p.headString()
  File "/home/chris/leo-editor/leo/core/leoNodes.py", line 654, in headString
    return self.v.headString()
  File "/home/chris/leo-editor/leo/core/leoNodes.py", line 2249, in headString
    if not g.isString(self._headString):
KeyboardInterrupt

**Comment by edreamleo** [comment]
@technatica Thanks, Chris, for all this data.  Now that the redraw code is settling down I'll turn my attention to the session-related startup code.  Presumably there is a serious performance bug lurking.  I'll add traces enabled by --trace-startup to figure out what is happening.

**Comment by edreamleo** [comment]
@technatica Rev b4500ba9c in devel adds support for --trace-startup.  Please try this option when trying to load the hanging session.

**Comment by edreamleo** [comment]
On Mon, Aug 20, 2018 at 9:23 PM Chris George <notifications@github.com>
wrote:

> ~ $ leod --trace-startup
> Already up-to-date.
>
> setting leoID from os.getenv('USER'): 'chris'
> reading settings in /home/chris/leo-editor/leo/config/leoSettings.leo
> reading settings in /home/chris/.leo/myLeoSettings.leo
> reading settings in /home/chris/.leo/themes/BreezeDarkThemeLocal.leo
>
> Leo 5.7.4 devel, build 20180815095610, Wed, Aug 15, 2018 9:56:10 AM
> Git repo info: branch = devel, commit = b4500ba
> <https://github.com/leo-editor/leo-editor/commit/b4500ba9c824e8bf9286a4e5493969e465443551>
> Python 3.6.5, PyQt version 5.11.1
> linux
> ** isPython3: True
>
> load_session loading: /home/chris/writing/LeoFiles/Music.leo
> reading settings in /home/chris/writing/LeoFiles/Music.leo
> loadOnePlugin: leo.plugins.livecode.init() returned False
> ^CTraceback (most recent call last):
> File "./launchLeo.py", line 8, in
> leo.core.runLeo.run()
> File "/home/chris/leo-editor/leo/core/runLeo.py", line 72, in run
> g.app.loadManager.load(fileName, pymacs)
> File "/home/chris/leo-editor/leo/core/leoApp.py", line 2244, in load
> ok = lm.doPostPluginsInit()
> File "/home/chris/leo-editor/leo/core/leoApp.py", line 2289, in
> doPostPluginsInit
> m.load_session(c1, aList)
> File "/home/chris/leo-editor/leo/core/leoSessions.py", line 85, in
> load_session
> if p.get_UNL() == unl:
> File "/home/chris/leo-editor/leo/core/leoNodes.py", line 754, in get_UNL
> p.moveToBack()
> File "/home/chris/leo-editor/leo/core/leoNodes.py", line 1127, in
> moveToBack
> p.v = parent_v.children[n - 1]
> KeyboardInterrupt
>

I suspected as much.  After loading the file the sessions code attempts to
restore c.p with this loop:

for p in c2.all_positions():
    if p.get_UNL() == unl:
        c2.setCurrentPosition(p)
        break
This will be very slow for large files. Typical unls are:

#Startup:0  matches a top-level position
#Recent settings:1  matches a direct child of a top-level position.

The "session" branch disables the search.  Please report what you see. If
all goes well I'll devise a faster search.

Edward

**Comment by edreamleo** [comment]
> If all goes well I'll devise a faster search.

Happily, it turns out that the slow code isn't needed at all! Or so my tests show.

**Comment by technatica** [comment]
Okay, that works.

Chris

**Comment by edreamleo** [comment]
Fixed at 5ee9f31e in devel.
