### ISSUE TITLE
run add-editor command with EKRDark or LeoBlackSolarized

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#939]
set myLeoSettings.leo:
    @string theme-name = EKRDark
or:
    @string theme-name =    LeoBlackSolarized

The leftmost editor is blank(no content displayed), after run command `add-editor`. Then `cycle-editor-focus` command can't focus to the leftmost editor. And all the nodes contents are blank displayed.

But EKRLight and BreezeDarkTheme both are ok!

***
Leo Log Window
Leo 5.7.4 devel, build 20180607085129, Thu Jun  7 08:51:29 CDT 2018
Git repo info: branch = devel, commit = 8a366eac74bd
Python 3.6.5, PyQt version 5.10.1
linux
isPython3: True
redefining abbreviation ,, 
from "{|{x='__NEXT_PLACEHOLDER'}|}" to '__NEXT_PLACEHOLDER'
loadOnePlugin: leo.plugins.livecode.init() returned False
read outline in 0.88 seconds

**Comment by technatica** [comment]
This is likely the issue.

https://github.com/leo-editor/leo-editor/issues/804

Read the comments for the workaround. A fix will either be new code in Leo
to handle notifications or QT fixing the bug.

Another workaround would be to use =<QT5.7.

Chris

**Comment by wangzhaohe** [comment]
Thanks for your reply!

Now I use BreezeDarkTheme.

**Comment by edreamleo** [comment]
Recent revs probably fix this.
