### ISSUE TITLE
Crashes in stickynotes.py after tabula commands

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#940]
(venv) swot@pp:~/leo-editor$ python launchLeo.py 

setting leoID from os.getenv('USER'): 'swot'
reading settings in /home/swot/leo-editor/leo/config/leoSettings.leo
reading settings in /home/swot/.leo/myLeoSettings.leo
reading settings in /home/swot/leo-editor/leo/themes/use_BreezeDarkTheme.leo
redefining abbreviation ,, 
from "{|{x='__NEXT_PLACEHOLDER'}|}" to '__NEXT_PLACEHOLDER'

Leo 5.7.4 devel, build 20180607085129, Thu Jun  7 08:51:29 CDT 2018
Git repo info: branch = devel, commit = 66f6001b178c
Python 3.6.5, PyQt version 5.10.1
linux
** isPython3: True

reading settings in /home/swot/.leo/workbook.leo
redefining abbreviation ,, 
from "{|{x='__NEXT_PLACEHOLDER'}|}" to '__NEXT_PLACEHOLDER'
redefining abbreviation ,, 
from "{|{x='__NEXT_PLACEHOLDER'}|}" to '__NEXT_PLACEHOLDER'
loadOnePlugin: leo.plugins.livecode.init() returned False
reading settings in /home/swot/pp/zlhopesun/XService.leo
redefining abbreviation ,, 
from "{|{x='__NEXT_PLACEHOLDER'}|}" to '__NEXT_PLACEHOLDER'
redefining abbreviation ,, 
from "{|{x='__NEXT_PLACEHOLDER'}|}" to '__NEXT_PLACEHOLDER'
loadOnePlugin: leo.plugins.livecode.init() returned False
Traceback (most recent call last):
  File "/home/swot/leo-editor/leo/plugins/stickynotes.py", line 616, in closeEvent
    self.save_states()
  File "/home/swot/leo-editor/leo/plugins/stickynotes.py", line 734, in save_states
    for (gnx, n) in self.notes.items() if n.isVisible())
  File "/home/swot/leo-editor/leo/plugins/stickynotes.py", line 734, in <genexpr>
    for (gnx, n) in self.notes.items() if n.isVisible())
RuntimeError: wrapped C/C++ object of type FocusingPlaintextEdit has been deleted
已杀死

**Comment by edreamleo** [comment]
There are multiple problems with the tabula-* commands.

**Comment by edreamleo** [comment]
Fixed at 5904b217b.
