### ISSUE TITLE
Errors Using Reload-All-Settings

### ISSUE THREAD

**Issue by technatica** [leo-editor/leo-editor#943]
Open any .leo file.

Settings, Reload Settings, Reload-All-Settings

`Leo Log Window
Leo 5.7.4 devel, build 20180607085129, Thu Jun 7 08:51:29 CDT 2018
Git repo info: branch = devel, commit = dc44fca26cc2
Python 3.6.5, PyQt version 5.9.4
linux
isPython3: True
setting leoID from os.getenv('USER'): 'chris'
current dir: /home/chris/leo-editor
load dir: /home/chris/leo-editor/leo/core
global config dir: /home/chris/leo-editor/leo/config
home dir: /home/chris
reading settings in /home/chris/leo-editor/leo/config/leoSettings.leo
reading settings in /home/chris/.leo/myLeoSettings.leo
reading settings in /home/chris/.leo/themes/BreezeDarkThemeLocal.leo
http serving enabled at 127.0.0.1:8130
reading settings in /home/chris/Dropbox/LeoFiles/Meta.leo
loadOnePlugin: leo.plugins.livecode.init() returned False
read outline in 0.21 seconds

wrote recent file: /home/chris/.leo/.leoRecentFiles.txt
saved: Meta.leo
saved: Meta.leo
saved: Meta.leo
reading settings in /home/chris/leo-editor/leo/config/leoSettings.leo
reading settings in /home/chris/.leo/myLeoSettings.leo
reading settings in /home/chris/.leo/themes/BreezeDarkThemeLocal.leo
reading settings in /home/chris/Dropbox/LeoFiles/Meta.leo
  Internal Leo error in check_gnx
getNewIndex: gnx clash chris.20170316104149.20
v: <VNode chris.20170316104149.20 newHeadline>
v2: <VNode chris.20170316104149.20 @outline-data tree-abbreviations>
Called from masterStaticMenuCallback, masterCommand, doCommand, executeAnyCommand, commander_command_wrapper, reloadAllSettings, reloadSettingsHelper, reloadConfigurableSettings, reload_settings, init_tree_abbrev, init_tree_abbrev_helper, getPosFromClipboard, getVnodeFromClipboard, readFile, readWithElementTree, scanVnodes, v_element_visitor, __init__, new_vnode_helper
Please report this error to Leo's developers
  Internal Leo error in check_gnx
getNewIndex: gnx clash chris.20170714082527.1
v: <VNode chris.20170714082527.1 newHeadline>
v2: <VNode chris.20170714082527.1 article;;>
Called from masterCommand, doCommand, executeAnyCommand, commander_command_wrapper, reloadAllSettings, reloadSettingsHelper, reloadConfigurableSettings, reload_settings, init_tree_abbrev, init_tree_abbrev_helper, getPosFromClipboard, getVnodeFromClipboard, readFile, readWithElementTree, scanVnodes, v_element_visitor, v_element_visitor, __init__, new_vnode_helper
Please report this error to Leo's developers
  Internal Leo error in check_gnx
getNewIndex: gnx clash chris.20170714082545.1
v: <VNode chris.20170714082545.1 newHeadline>
v2: <VNode chris.20170714082545.1 @clean /home/chris/writing/InfoTel/<|title|>.txt>
Called from doCommand, executeAnyCommand, commander_command_wrapper, reloadAllSettings, reloadSettingsHelper, reloadConfigurableSettings, reload_settings, init_tree_abbrev, init_tree_abbrev_helper, getPosFromClipboard, getVnodeFromClipboard, readFile, readWithElementTree, scanVnodes, v_element_visitor, v_element_visitor, v_element_visitor, __init__, new_vnode_helper
Please report this error to Leo's developers
  Internal Leo error in check_gnx
getNewIndex: gnx clash chris.20180210205804.1
v: <VNode chris.20180210205804.1 newHeadline>
v2: <VNode chris.20180210205804.1 re:Fiction;;>
Called from masterCommand, doCommand, executeAnyCommand, commander_command_wrapper, reloadAllSettings, reloadSettingsHelper, reloadConfigurableSettings, reload_settings, init_tree_abbrev, init_tree_abbrev_helper, getPosFromClipboard, getVnodeFromClipboard, readFile, readWithElementTree, scanVnodes, v_element_visitor, v_element_visitor, __init__, new_vnode_helper
Please report this error to Leo's developers
  Internal Leo error in check_gnx
getNewIndex: gnx clash chris.20180210205828.1
v: <VNode chris.20180210205828.1 newHeadline>
v2: <VNode chris.20180210205828.1 @clean /home/chris/writing/re:Fiction/<|title|>.txt>
Called from doCommand, executeAnyCommand, commander_command_wrapper, reloadAllSettings, reloadSettingsHelper, reloadConfigurableSettings, reload_settings, init_tree_abbrev, init_tree_abbrev_helper, getPosFromClipboard, getVnodeFromClipboard, readFile, readWithElementTree, scanVnodes, v_element_visitor, v_element_visitor, v_element_visitor, __init__, new_vnode_helper
Please report this error to Leo's developers
  Internal Leo error in check_gnx
getNewIndex: gnx clash chris.20170605151836.1
v: <VNode chris.20170605151836.1 newHeadline>
v2: <VNode chris.20170605151836.1 post;;>
Called from masterCommand, doCommand, executeAnyCommand, commander_command_wrapper, reloadAllSettings, reloadSettingsHelper, reloadConfigurableSettings, reload_settings, init_tree_abbrev, init_tree_abbrev_helper, getPosFromClipboard, getVnodeFromClipboard, readFile, readWithElementTree, scanVnodes, v_element_visitor, v_element_visitor, __init__, new_vnode_helper
Please report this error to Leo's developers
  Internal Leo error in check_gnx
getNewIndex: gnx clash chris.20170605151858.1
v: <VNode chris.20170605151858.1 newHeadline>
v2: <VNode chris.20170605151858.1 @clean <|title|>.rst>
Called from doCommand, executeAnyCommand, commander_command_wrapper, reloadAllSettings, reloadSettingsHelper, reloadConfigurableSettings, reload_settings, init_tree_abbrev, init_tree_abbrev_helper, getPosFromClipboard, getVnodeFromClipboard, readFile, readWithElementTree, scanVnodes, v_element_visitor, v_element_visitor, v_element_visitor, __init__, new_vnode_helper
Please report this error to Leo's developers
  Internal Leo error in check_gnx
getNewIndex: gnx clash chris.20170317190034.1
v: <VNode chris.20170317190034.1 newHeadline>
v2: <VNode chris.20170317190034.1 mdfile;;>
Called from masterCommand, doCommand, executeAnyCommand, commander_command_wrapper, reloadAllSettings, reloadSettingsHelper, reloadConfigurableSettings, reload_settings, init_tree_abbrev, init_tree_abbrev_helper, getPosFromClipboard, getVnodeFromClipboard, readFile, readWithElementTree, scanVnodes, v_element_visitor, v_element_visitor, __init__, new_vnode_helper
Please report this error to Leo's developers
  Internal Leo error in check_gnx
getNewIndex: gnx clash chris.20170317190047.1
v: <VNode chris.20170317190047.1 newHeadline>
v2: <VNode chris.20170317190047.1 @<|type|> <|filename|>.md>
Called from doCommand, executeAnyCommand, commander_command_wrapper, reloadAllSettings, reloadSettingsHelper, reloadConfigurableSettings, reload_settings, init_tree_abbrev, init_tree_abbrev_helper, getPosFromClipboard, getVnodeFromClipboard, readFile, readWithElementTree, scanVnodes, v_element_visitor, v_element_visitor, v_element_visitor, __init__, new_vnode_helper
Please report this error to Leo's developers
  Internal Leo error in check_gnx
getNewIndex: gnx clash chris.20170316104149.21
v: <VNode chris.20170316104149.21 newHeadline>
v2: <VNode chris.20170316104149.21 per-commander-plugin;;>
Called from masterCommand, doCommand, executeAnyCommand, commander_command_wrapper, reloadAllSettings, reloadSettingsHelper, reloadConfigurableSettings, reload_settings, init_tree_abbrev, init_tree_abbrev_helper, getPosFromClipboard, getVnodeFromClipboard, readFile, readWithElementTree, scanVnodes, v_element_visitor, v_element_visitor, __init__, new_vnode_helper
Please report this error to Leo's developers
  Internal Leo error in check_gnx
getNewIndex: gnx clash chris.20170316104149.22
v: <VNode chris.20170316104149.22 newHeadline>
v2: <VNode chris.20170316104149.22 @@file pluginname.py>
Called from doCommand, executeAnyCommand, commander_command_wrapper, reloadAllSettings, reloadSettingsHelper, reloadConfigurableSettings, reload_settings, init_tree_abbrev, init_tree_abbrev_helper, getPosFromClipboard, getVnodeFromClipboard, readFile, readWithElementTree, scanVnodes, v_element_visitor, v_element_visitor, v_element_visitor, __init__, new_vnode_helper
Please report this error to Leo's developers
  Internal Leo error in check_gnx
getNewIndex: gnx clash chris.20170316104149.23
v: <VNode chris.20170316104149.23 newHeadline>
v2: <VNode chris.20170316104149.23 << docstring >>>
Called from executeAnyCommand, commander_command_wrapper, reloadAllSettings, reloadSettingsHelper, reloadConfigurableSettings, reload_settings, init_tree_abbrev, init_tree_abbrev_helper, getPosFromClipboard, getVnodeFromClipboard, readFile, readWithElementTree, scanVnodes, v_element_visitor, v_element_visitor, v_element_visitor, v_element_visitor, __init__, new_vnode_helper
Please report this error to Leo's developers
  Internal Leo error in check_gnx
getNewIndex: gnx clash chris.20170316104149.24
v: <VNode chris.20170316104149.24 newHeadline>
v2: <VNode chris.20170316104149.24 << version history >>>
Called from executeAnyCommand, commander_command_wrapper, reloadAllSettings, reloadSettingsHelper, reloadConfigurableSettings, reload_settings, init_tree_abbrev, init_tree_abbrev_helper, getPosFromClipboard, getVnodeFromClipboard, readFile, readWithElementTree, scanVnodes, v_element_visitor, v_element_visitor, v_element_visitor, v_element_visitor, __init__, new_vnode_helper
Please report this error to Leo's developers
  Internal Leo error in check_gnx
getNewIndex: gnx clash chris.20170316104149.25
v: <VNode chris.20170316104149.25 newHeadline>
v2: <VNode chris.20170316104149.25 << imports >>>
Called from executeAnyCommand, commander_command_wrapper, reloadAllSettings, reloadSettingsHelper, reloadConfigurableSettings, reload_settings, init_tree_abbrev, init_tree_abbrev_helper, getPosFromClipboard, getVnodeFromClipboard, readFile, readWithElementTree, scanVnodes, v_element_visitor, v_element_visitor, v_element_visitor, v_element_visitor, __init__, new_vnode_helper
Please report this error to Leo's developers
  Internal Leo error in check_gnx
getNewIndex: gnx clash chris.20170316104149.26
v: <VNode chris.20170316104149.26 newHeadline>
v2: <VNode chris.20170316104149.26 init>
Called from executeAnyCommand, commander_command_wrapper, reloadAllSettings, reloadSettingsHelper, reloadConfigurableSettings, reload_settings, init_tree_abbrev, init_tree_abbrev_helper, getPosFromClipboard, getVnodeFromClipboard, readFile, readWithElementTree, scanVnodes, v_element_visitor, v_element_visitor, v_element_visitor, v_element_visitor, __init__, new_vnode_helper
Please report this error to Leo's developers
  Internal Leo error in check_gnx
getNewIndex: gnx clash chris.20170316104149.27
v: <VNode chris.20170316104149.27 newHeadline>
v2: <VNode chris.20170316104149.27 onCreate>
Called from executeAnyCommand, commander_command_wrapper, reloadAllSettings, reloadSettingsHelper, reloadConfigurableSettings, reload_settings, init_tree_abbrev, init_tree_abbrev_helper, getPosFromClipboard, getVnodeFromClipboard, readFile, readWithElementTree, scanVnodes, v_element_visitor, v_element_visitor, v_element_visitor, v_element_visitor, __init__, new_vnode_helper
Please report this error to Leo's developers
  Internal Leo error in check_gnx
getNewIndex: gnx clash chris.20170316104149.28
v: <VNode chris.20170316104149.28 newHeadline>
v2: <VNode chris.20170316104149.28 class pluginController>
Called from executeAnyCommand, commander_command_wrapper, reloadAllSettings, reloadSettingsHelper, reloadConfigurableSettings, reload_settings, init_tree_abbrev, init_tree_abbrev_helper, getPosFromClipboard, getVnodeFromClipboard, readFile, readWithElementTree, scanVnodes, v_element_visitor, v_element_visitor, v_element_visitor, v_element_visitor, __init__, new_vnode_helper
Please report this error to Leo's developers
  Internal Leo error in check_gnx
getNewIndex: gnx clash chris.20170316104149.29
v: <VNode chris.20170316104149.29 newHeadline>
v2: <VNode chris.20170316104149.29 __init__>
Called from commander_command_wrapper, reloadAllSettings, reloadSettingsHelper, reloadConfigurableSettings, reload_settings, init_tree_abbrev, init_tree_abbrev_helper, getPosFromClipboard, getVnodeFromClipboard, readFile, readWithElementTree, scanVnodes, v_element_visitor, v_element_visitor, v_element_visitor, v_element_visitor, v_element_visitor, __init__, new_vnode_helper
Please report this error to Leo's developers`

The file level @settings node contains one setting "@enabled-plugins", the body is identical to the setting in myLeoSettings.leo except for the addition of mod_autosave.py.

Chris

**Comment by technatica** [comment]
@outline-data tree-abbreviations in myLeoSettings.leo really wants to be the only clone in the entire file. I copy/paste copy then delete the clone, save the settings file and restart Leo and it is a clone again.

This is a different manifestation of the same problem I was having earlier.

Chris

**Comment by edreamleo** [comment]
Fixed at 7be25ff.
