### ISSUE TITLE
replace-all can not be saved with crtl + s   --- Appear Again

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#947]
Leo 5.7.4 devel, build 20180727113027, Fri, Jul 27, 2018 11:30:27 AM
Git repo info: branch = devel, commit = 2f9bab6
Python 3.6.5, PyQt version 5.10.1
linux
** isPython3: True

reading settings in /home/swot/.leo/workbook.leo

**Comment by edreamleo** [comment]
Fixed at 5c02c72.  This should, at long last, fix this problem for all time.
