### ISSUE TITLE
Section references in @clean trees do not work in @doc parts

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#950]
The following does not work an `@clean` tree:
```
@
<< description >>
@c
```
The apparent section reference is not recognized as such.

This prevents clones from being used as wanted in #946.

**Comment by XCaminhante** [comment]
I'm having a similar issue using section references inside @clean trees, I will file a ticket for it.

**Comment by edreamleo** [comment]
This is not likely to be feasible.
