### ISSUE TITLE
Leo XML content isn't in Leo namespace.

### ISSUE THREAD

**Issue by tbnorth** [leo-editor/leo-editor#951]
Just noticed last night, .leo files do:
```xml
<leo_file xmlns:leo="http://leoeditor.com/namespaces/leo-python-editor/1.1" >
```
which I'm fairly sure means there's a namespace with shortname leo defined that's not used for anything.
I think just leaving out the ':leo' would fix it.  OTOH, that might break tools that look parse .leo files in a non-namespace aware way.

**Comment by edreamleo** [comment]
Imo, there is no need to changed this.  True, the namespace itself is unused, but apparently the xmlns attribute is good practice.  I am going to close this item.  Please reopen if there is a real problem.
