### ISSUE TITLE
Scroll body text without leaving outline pane

### ISSUE THREAD

**Issue by beetleb** [leo-editor/leo-editor#952]
There's a behavior in Emacs that I'm used to. Sometimes I have two buffers open side by side. My cursor is in one buffer, but I want to scroll the other buffer without switching to it. This can be done with Alt-PgUp and Alt-PgDn.

I want something similar in Leo. When I'm in the outline pane, I would like those keybindings to scroll through the body pane. 

My first attempt was to make this keybinding in @settings:

    back-page                       ! text = PageUp 
    back-page                       ! tree = Alt-Prior
    forward-page                    ! text = PageDn
    forward-page                    ! tree = Alt-Next

This almost works - the problem is that the focus remains on the body pane. 

My next thought was: Let's use macros! This [page](http://leoeditor.com/commands.html#id124) indicates Leo has macros, but I couldn't find the commands. This [post](https://groups.google.com/forum/#!searchin/leo-editor/macro|sort:date/leo-editor/udsN3yvJzgk/ZhZoA6qSCQAJ) from the mailing list suggests that macros has likely been deleted? If so, I'm really sad as I'm a heavy user of them in Emacs - I can't imagine writing a script being at all efficient for many tasks easily solved by macros. But that's a whole issue for another day - it may be a good idea to remove references to macros from Leo's docs.

So next attempt: Write a script and make use of the focus commands Edward had provided in this other issue: #878 

First step, though: How do I simulate a `forward-page` in Python code? It seems I need to invoke the `c.editCommands.forwardPage` function, but I need to provide it an _event_ argument, and I have no idea what that would be.

Am I barking up the wrong tree? How can I do this?

(Sorry, but I can't resist: This would be trivial with a saved macro.)

Any help would be appreciated. 

Thanks.

**Comment by btheado** [comment]
`c.executeMinibufferCommand('forward-page')` should work.

**Comment by beetleb** [comment]
Perfect! Thanks! So this is what I have:

In my `@settings`, I declared a node `@command scroll-other-forward` and its contents are:

    @language python

    c.executeMinibufferCommand('forward-page')
    c.treeWantsFocus()

Then I pointed my keybinding to `scroll-other-forward`.

Similar for backward. 

This does assume I'm in the tree to begin with (and not in the Log). I think it's good enough for me. If later I find that I often need this from the log window I'll make it more intelligent.

Closing issue unless someone wants to point out a flaw in my approach.

**Comment by technatica** [comment]
Keybindings can be restricted based on where the focus is.

For example I use shift-uparrow to select text from end of line to
beginning of line when in a text box (including headlines) and the same
keybinding to move nodes when I am in the tree.

Here is the example from myLeoSettings.leo

@shortcuts
    beginning-of-line-extend-selection ! text = Shift-uparrow

move-outline-up ! tree = Shift-uparrow


HTH,


Chris
