### ISSUE TITLE
Leo 5.7 freezes with Python2 and PyQt4 in vim-mode

### ISSUE THREAD

**Issue by bfloch** [leo-editor/leo-editor#958]
Linux: Fedora 28 / Centos7 x64_86

Setting `@bool vim-mode = True` cause a freeze on start up. 

Hitting Ctrl-C reveals:
~~~
 File "leo/plugins/qt_events.py", line 66, in eventFilter
    def eventFilter(self, obj, event):
~~~

I tried on Python3 / PyQt5 on the Fedora machine and it fixed it.
This is however no option on the Centos machine.

**Comment by edreamleo** [comment]
I am going to close this.  Presumably this is an installation problem.

**Comment by bfloch** [comment]
Any hints on what I am doing wrong? I was able to replicate this on two distinct distros.
The only thing I noticed is that the PyQt4 versions are build against KDE's Qt.
Thanks.

**Comment by technatica** [comment]
I have been using Leo for a decade and have installed it on a dozen or so
different distros. I have been using the KDE desktop the entire time.

I eventually learned that while it is possible to hunt down exactly why Leo
won't work with distro XXXX and make it work it was time better spent
writing.

So I started placing anaconda/miniconda first in my prerequisites. I have
never had to troubleshoot the python/Qt install since. But then I am
version agnostic as I am not a programmer. I tend to use the highest
versions of both python3 and Qt that are available via anaconda unless
there is a specific conflict with Leo.

Chris

**Comment by bfloch** [comment]
Thanks @technatica 
Yes, like I said Python3 and PyQt5 seem to work.
However that (and anaconda) is not an option on my work computer on CentOS 7, with limited options to install software.

I still believe it might be a bug, in fact I don't see why this report seems to be treated differently then e.g. https://github.com/leo-editor/leo-editor/issues/359 which had **exactly** the same symptoms.

But if everyone but me can install it and run the vim-mode on any Distro with Python2 and PyQt4 then I assume that this in fact is not a bug but I cause flipbits on any Python2/PyQt4 distro only that seem to cause Leo to malfunction in vim-mode :-)

Since the ticket is closed I guess that's all there is to it now. Thanks.

**Comment by edreamleo** [comment]
On Wed, Aug 22, 2018 at 10:54 PM Blazej Floch <notifications@github.com>
wrote:

> I still believe it might be a bug, in fact I don't see why this report
> seems to be treated differently then e.g. #359
> <https://github.com/leo-editor/leo-editor/issues/359> which had *exactly*
> the same symptoms.
>
What happens when you run with --trace-events?

> Since the ticket is closed I guess that's all there is to it now. Thanks.
>
Tickets can always be reopened. I frequently change my mind.

Edward

**Comment by edreamleo** [comment]
The #958 branch attempts a fix by adding a new onFocusIn event handler.

Please report whether this helps.

**Comment by bfloch** [comment]
Sorry to report it does not yet fix it.

**Comment by edreamleo** [comment]
On Fri, Aug 24, 2018 at 9:17 PM Blazej Floch <notifications@github.com>
wrote:

> Sorry to report it does not yet fix it.
>

Did --trace-events change in any significant way?

Edward

**Comment by bfloch** [comment]
Looks the same:
~~~
traceWidget             focus-in <class 'leo.plugins.qt_text.LeoQTextBrowser'>                                         │
traceWidget                  106 <class 'leo.plugins.qt_text.LeoQTextBrowser'>                                         │
traceWidget             focus-in <class 'leo.plugins.qt_text.LeoQTextBrowser'>                                         │
traceWidget                  106 <class 'leo.plugins.qt_text.LeoQTextBrowser'>                                         │
traceWidget             focus-in <class 'leo.plugins.qt_text.LeoQTextBrowser'>
~~~

**Comment by edreamleo** [comment]
On Sat, Aug 25, 2018 at 12:55 PM Blazej Floch <notifications@github.com>
wrote:

> Looks the same:
>
> Ok.  I'll investigate further.


Edward

**Comment by edreamleo** [comment]
I can only attempt a fix if I can reproduce it.  That's the first essential step.

**Comment by edreamleo** [comment]
There is no way me to attempt a fix.
