### ISSUE TITLE
"Recent Files" changed to "A placeholder for the actual menu."?

### ISSUE THREAD

**Issue by frakel** [leo-editor/leo-editor#959]
This is certainly a minor issue and maybe due to my dumbness ;) But when I got my latest Leo update a few days ago the menu label for `Recent Files` changed to `A placeholder for the actual menu.`.
I did not change any of my leoSettings files. I don't know how to get rid of this and how to restore the normal menu entry name. Any ideas? Thank you.

**Comment by edreamleo** [comment]
On Fri, Aug 17, 2018 at 4:09 AM, franz kelnreiter <notifications@github.com>
wrote:

> when I got my latest Leo update a few days ago the menu label for Recent
> Files changed to A
> placeholder for the actual menu..
>
> Do you have an @menus item in your copy of myLeoSettings.leo?

What happens (to menus) if you disable (rename or remove) your
myLeoSettings.leo?

Edward

**Comment by frakel** [comment]
Thank you, Edward, this did the trick. Seems that I(?) have changed something unintentionally. I will try to find where...

**Comment by frakel** [comment]
to be more precise:
> this did the trick. 

= *renaming the ~/.leo/myLeoSettings.leo* . The file has all the mandatory entries (`@menu`), though, as far as I see comparing it with the in `...Lib/site-packages/leo-editor/leo/config`. So I am not clear about the error, but it is - as I mentioned - of minor priority and maybe loss of time to invest more. Thank you.

**Comment by edreamleo** [comment]
@frakel Thanks for the follow up.  Let me know if I can help in any way.
