### ISSUE TITLE
LP bug 1245111: Can't get the viewrendered pane back next to the editor

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#96]
https://bugs.launchpad.net/leo-editor/+bug/1245111
Creating a new item so I can close #73.

**Comment by tbnorth** [comment]
Bug from Launchpad:

> If you right click on the pane divider between the editor body and the outline, you get a menu. In that menu's "open window" submenu you can open a window for the nav tab or the viewrendered pane. If you choose nav, the nav tab disappears (fine) and a nav window appears. When you close the nav window, the nav tab reappears (even better). For viewrendered, once the viewrendered window is open, I have found no way to 1) get the pane back or 2) display automatically an outline node in the viewrendered window. The only way that I can get a node in the viewrendered window is to use vr-update.

This bug does not appear to be present for viewrendered2.py

Hmm, I don't see it for viewrendered.py - I'll mark it closed, but added a note to #154.

**Comment by edreamleo** [comment]
On Mon, May 4, 2015 at 7:44 PM, tbnorth <notifications@github.com> wrote:

> Bug from Launchpad:
> ​ [snip]​
>
> Hmm, I don't see it for viewrendered.py - I'll mark it closed, but added a
> note to #154 <https://github.com/leo-editor/leo-editor/issues/154>.
>
​Thanks for this investigation, Terry, I appreciate it.

EKR
