### ISSUE TITLE
Named sessions

### ISSUE THREAD

**Issue by technatica** [leo-editor/leo-editor#962]
I would find it helpful to have a command line argument to load arbitrary sessions.

ie. ./launchLeo.py --session-save --session-restore --session ~/writing/novel.session
or  ./launchLeo.py --session-save --session-restore --session ~/music/music.session
or  ./launchLeo.py --session-save --session-restore --session ~/writing/other_novel.session
etc.

**Comment by edreamleo** [comment]
On Sat, Aug 18, 2018 at 11:03 AM Chris George <notifications@github.com>
wrote:

> I would find it helpful to have a command line argument to load arbitrary
> sessions.
>
> ie. ./launchLeo.py --session-save --session-restore --session
> ~/writing/novel.session
> or ./launchLeo.py --session-save --session-restore --session
> ~/music/music.session
> or ./launchLeo.py --session-save --session-restore --session
> ~/writing/other_novel.session
> etc.
>
I like this idea.  The timing is good because fixing #936 is rising to the
top of the list.

Edward

**Comment by edreamleo** [comment]
I've changed my mind.  I am going to close this and mark it "Won't Do".

Imo, sessions are one of the least valuable part of Leo.  At present, they just remember what people were last doing.  That's fine, but extending that to something more permanent isn't remotely worth the effort.  Instead, users can define .bat file (or Linux equivalents) to open a fixed set of files.

**Comment by ktenney** [comment]
Darn.

I think of sessions as 'projects', of which I have (too) many, each
consisting of a set of related files, they are valuable to me.
I was hoping named sessions would become native to Leo.
I do seem to recall however that implementing them was to be non-trivial.
I don't want to maintain a set of scripts to emulate them, I'll stick with
making Leo files named for the project, opening them with --save/restore
session,

Thanks,
Kent

**Comment by edreamleo** [comment]
On Tue, Aug 21, 2018 at 8:55 AM Kent Tenney <notifications@github.com>
wrote:

> Darn.
>
> I think of sessions as 'projects', of which I have (too) many, each
> consisting of a set of related files, they are valuable to me.
> I was hoping named sessions would become native to Leo.
>

On Linus, it's so easy to add an alias to your .bashrc (or other startup)
file.  Leo doesn't need yet another seldom-used feature, which then has to
be documented and supported.

Edward
