### ISSUE TITLE
Themes do not load - incorrect FAQ

### ISSUE THREAD

**Issue by paulrd** [leo-editor/leo-editor#963]
I tried to use the method of loading themes as described it the FAQ, but the theme will not load. No errors show in the logging pane or the terminal (I run from the terminal). I'm using python3, leo 5.7.3, pyqt 5.9.5, ubuntu linux.

I was able to get the theme to load by including an '=' in the directive. So instead of:
```@string theme-name <theme file, without the .leo extension>```

I put ```@string theme-name = <theme file, without the .leo extension>```

Is this a bug in the FAQ?

**Comment by edreamleo** [comment]
On Sun, Aug 19, 2018 at 11:22 AM, Chris George <notifications@github.com>
wrote:

> Good catch.
>
> Fixed at 63a2ef8
> <https://github.com/leo-editor/leo-editor/commit/63a2ef83c9e9064b2d0a831f9f586a4e81797ab6>
> in devel.
>

Thanks for the fix.

Edward
