### ISSUE TITLE
Allow abbreviations to set the insertion point and selection range

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#964]
Paul Stevenson would like an abbreviation that would insert text (especially in headlines) and also set the insertion point.  Something like this, perhaps: ` th;;={|{x="TODO"+" :Home:"; set_cursor(5)}|}`

As discussed below, this is not easy to do.  Instead, the following (tested) Leonine @button node works:
```python
@button todo
p = c.insertHeadline()
p.h = 'todo :HOME:'
c.editHeadline()
w = c.edit_widget(p)
w.setInsertPoint(5)
```

**Abbreviations can't set the cursor**

The following does not work, for at least three reasons:
```python
def set_cursor(n):
    w = c.abbrevCommands.w
    if w:
         w.setInsertPoint()
 ```
1. The abbreviation code saves/restores the insert point.
2. w.setInsertPoint(n) doesn't work immediately, which hinders coordination with the abbreviation code.
3. w.setInsertPoint(n) doesn't exist when editing headlines.

As a desperation measure, it might be possible to set the values at the next idle time, but point 3 above complicates everything.

**Comment by edreamleo** [comment]
I am going to close this issue. The abbreviation code is already way too complex, and there is an easy workaround.

**Comment by tbnorth** [comment]
As noted on the list, an abbreviation of the form
```
th;;=TODO<||> :Home:
```
places the insertion point after the O.  It works in the body and in the headline of a previously existing node(*), but not in the headline of a node just created by Insert, which is apparently different.

* I see now it only works if the headline content is selected, so basically it nearly works but fails because the headline text edit widget is not providing quite the same behavior as the body text edit widget.

**Comment by edreamleo** [comment]
I spent several hours wrestling with this.  As stated above, the abbreviation code is way too complex.  I don't believe the headline text widget *can* provide exactly the same behavior as the body text.

**Comment by tbnorth** [comment]
On Mon, 27 Aug 2018 07:37:05 -0700
"Edward K. Ream" <notifications@github.com> wrote:

> I spent several hours wrestling with this.  As stated above, the
> abbreviation code is way too complex.  I don't believe the headline
> text widget *can* provide exactly the same behavior as the body text.

I guess I'm just pointing out that the headline widget does support the
same cursor placement strategy that works in the body, but only in
previously existing nodes, not nodes just created, and only if the
headline text is selected.  Both of these suggest different code
paths / hidden states in the headline edit code.

**Comment by edreamleo** [comment]
On Mon, Aug 27, 2018 at 9:54 AM Terry Brown <notifications@github.com>
wrote:

I guess I'm just pointing out that the headline widget does support the
> same cursor placement strategy that works in the body, but only in
> previously existing nodes, not nodes just created, and only if the
> headline text is selected. Both of these suggest different code
> paths / hidden states in the headline edit code.
>

The code is very different.  Qt does not generate the same events for
headline widgets as for the body text.  onHeadChanged is super super tricky.

Edward

**Comment by edreamleo** [comment]
On Mon, Aug 27, 2018 at 9:56 AM Edward K. Ream <edreamleo@gmail.com> wrote:

>
>
> The code is very different.  Qt does not generate the same events for
> headline widgets as for the body text.  onHeadChanged is super super tricky.
>

And welcome back :-)

Edward
