### ISSUE TITLE
Clojurescript file support (and cljc, edn)

### ISSUE THREAD

**Issue by paulrd** [leo-editor/leo-editor#966]
Hi, I'm wondering if it would be hard to adapt the clojure colorizer code and @auto importing mechanism to clojurescript files. This would include files with the .cljs, .cljc and .edn file extentions. Edn is actually a clojure-based serialized data format (like JSON) but could be colorized like clojure. Cljc files are both clojure and clojurescript code.

**Comment by edreamleo** [comment]
@paulrd I'm not sure how closely related clojure is to clojurescript.

**Comment by edreamleo** [comment]
Rev 80b48f133 adds some support for `@auto x.cljs` and `@auto x.cljc`, using Leo's existing elisp importer.

I'm not sure whether the elisp importer actually works.

Please report any problems.  I'll close this issue now, but  (as always) feel free to reopen.

**Comment by paulrd** [comment]
Hi thanks @edreamleo ! It doesn't quite work yet. The elisp importer shoud be modified to use 'defn' instead of 'defun' as a basis for creating function definition nodes. I also noticed an ommission in your change to ```'extensions': ['.el', '.cljs', '.cljc',],``` line in importers/elisp.py. It should include the .clj (extension for standard clojure files).

Also, I did a change in my verison of leo to created nodes based on defn instead of defun and it seems to work, but I noticed the clojure colorization no longer works. Perhaps the elisp importer applies elisp colorization? In any case a clojure-specific importer should be made with just that minor change probably. 

I'm not a python programmer, but I might be able to make these changes as a pull request if you prefer that to doing it yourself. Thanks for everything!

**Comment by edreamleo** [comment]
On Sun, Aug 26, 2018 at 11:18 AM Paul <notifications@github.com> wrote:

> The elisp importer shoud be modified to use 'defn' instead of 'defun' as a
> basis for creating function definition nodes.
>
The fix is simply to use the clojure colorizer in modes/clojure.py.  I had
mistakenly delegated clojure colorizing to the elisp colorizer.

> I also noticed an ommission in your change to 'extensions': ['.el',
> '.cljs', '.cljc',], line in importers/elisp.py. It should include the
> .clj (extension for standard clojure files).
>
Both these fixes are in devel at 6be9213c2.

Thanks for testing this.  Let me know if there are other problems.

Edward
