### ISSUE TITLE
Cross-file backlink errors

### ISSUE THREAD

**Issue by largo84** [leo-editor/leo-editor#967]
1. Using the backlink plugin, add a link from Node A to Node B.
2. Copy Node A and paste to a different xxx.leo file (Node B does not exist here).
3. This generates the following error whenever you select Node A in the new xxx.leo file:
`hook failed: select3, <bound method backlinkController.updateTab of <leo.plugins.backlink.backlinkController object at 0x17B2DA30>>, leo.plugins.backlink
Traceback (most recent call last):
   File "D:\Synced\github repos\leo\leo\core\leoPlugins.py", line 325, in callTagHandler
result = handler(tag, keywords)
   File "D:\Synced\github repos\leo\leo\plugins\backlink.py", line 661, in updateTab
self.updateTabInt()
   File "D:\Synced\github repos\leo\leo\plugins\backlink.py", line 685, in updateTabInt
otherV = self.vnode[other]
KeyError: 'largo84.20180717094348.1'`
4. Close the new xxx.leo file and reopen.
5. The traceback error is gone, but now we get:
`backlink: link to Node A from ??? lost`
6. This error never goes away and there doesn't appear to be a way to delete the offending missing link.

The only apparent workaround is to first copy Node A locally, then delete the links, then copy to the new xxx.leo file.

**Comment by edreamleo** [comment]
I'll have a look.

**Comment by edreamleo** [comment]
Fixed, I think, in devel at 10742e68f.  Please reopen if necessary.

**Comment by largo84** [comment]
Looks like that works, thanks!

**Comment by edreamleo** [comment]
@largo84 Thanks for the confirmation.
