### ISSUE TITLE
Chapter button not working

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#969]
The chapter menu button is not working.
If I select a chapter with the Chapters button, focus does not switch to the chapter and all the other nodes remain visible.

Leo Log Window
Leo 5.8 b1 devel, build 20180815095610, Wed, Aug 15, 2018 9:56:10 AM
Git repo info: branch = devel, commit = 93f4366
Python 3.7.0, PyQt version 5.11.1
Windows 10 AMD64 (build 10.0.17134) SP0
isPython3: True

**Comment by edreamleo** [comment]
Fixed at c3f1d224a in devel.

This is why we have "official" releases.  No matter how long we test "devel", more people will test an official release.

**Comment by LewisNeal** [comment]
Working fine now. Thanks
