### ISSUE TITLE
Leo 5.8.1b fails to open core Leo files, shows xml.etree.ElementTree.ParseError

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#970]
_Not sure if this is leo bug or my machine. I just spent a lot of time cleaning up mixed system, .local, and conda env python packages and have just gotten back to 'the real work'._

1. create new conda environment
2. conda install pip
3. git checkout master
4. pip install .
5. run leo
6. File >> Open specific leo file >> LeoDist (or Doc or ...)

Document doesn't open. _"Reading settings from .... LeoDist.leo"_ shows in log pane. Terminal shows error below. Repeating the above recipe using `git checkout devel` instead of master: no problem, everything works.

Machine is Linux Mint 18.2

```
setting leoID from os.getenv('USER'): 'matt'
reading settings in /home/matt/miniconda3/envs/leo/lib/python3.6/site-packages/leo/config/leoSettings.leo
reading settings in /home/matt/.leo/myLeoSettings.leo
QApplication: invalid style override passed, ignoring it.

Leo 5.8 b1, build 20180815095610, Wed, Aug 15, 2018  9:56:10 AM
Not running from a git repo
Python 3.6.6, PyQt version 5.11.1
linux
** isPython3: True

reading settings in /home/matt/.leo/workbook.leo
loadOnePlugin: leo.plugins.livecode.init() returned False
reading settings in /home/matt/code/leo-editor/leo/dist/leoDist.leo
Traceback (most recent call last):

  File "/home/matt/miniconda3/envs/leo/lib/python3.6/site-packages/leo/core/leoCommands.py", line 2072, in executeAnyCommand
    return command(event)

  File "/home/matt/miniconda3/envs/leo/lib/python3.6/site-packages/leo/core/leoGlobals.py", line 269, in commander_command_wrapper
    method(event=event)

  File "/home/matt/miniconda3/envs/leo/lib/python3.6/site-packages/leo/commands/commanderFileCommands.py", line 214, in open
    c2 = g.openWithFileName(fileName, old_c=c)

  File "/home/matt/miniconda3/envs/leo/lib/python3.6/site-packages/leo/core/leoGlobals.py", line 3682, in openWithFileName
    return g.app.loadManager.loadLocalFile(fileName, gui, old_c)

  File "/home/matt/miniconda3/envs/leo/lib/python3.6/site-packages/leo/core/leoApp.py", line 3059, in loadLocalFile
    previousSettings = lm.getPreviousSettings(fn)

  File "/home/matt/miniconda3/envs/leo/lib/python3.6/site-packages/leo/core/leoApp.py", line 1973, in getPreviousSettings
    c = lm.openSettingsFile(fn)

  File "/home/matt/miniconda3/envs/leo/lib/python3.6/site-packages/leo/core/leoApp.py", line 2139, in openSettingsFile
    readAtFileNodesFlag=False, silent=True)

  File "/home/matt/miniconda3/envs/leo/lib/python3.6/site-packages/leo/core/leoFileCommands.py", line 631, in openLeoFile
    silent=silent,

  File "/home/matt/miniconda3/envs/leo/lib/python3.6/site-packages/leo/core/leoFileCommands.py", line 494, in getLeoFile
    v = FastRead(c, self.gnxDict).readFile(fileName)

  File "/home/matt/miniconda3/envs/leo/lib/python3.6/site-packages/leo/core/leoFileCommands.py", line 68, in readFile
    return self.readWithElementTree(s)

  File "/home/matt/miniconda3/envs/leo/lib/python3.6/site-packages/leo/core/leoFileCommands.py", line 73, in readWithElementTree
    xroot = ElementTree.fromstring(contents)

  File "/home/matt/miniconda3/envs/leo/lib/python3.6/xml/etree/ElementTree.py", line 1314, in XML
    parser.feed(text)

  File "<string>", line None

xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 189, column 1
```

**Comment by edreamleo** [comment]
On Tue, Aug 28, 2018 at 11:34 PM matt wilkie <notifications@github.com>
wrote:

> *Not sure if this is leo bug or my machine. I just spent a lot of time
> cleaning up mixed system, .local, and conda env python packages and have
> just gotten back to 'the real work'.*
>
I have seen something like this myself.  It's urgent that this be fixed in
master.

Clearly, my testing protocol for master is deficient. For now, master can
not be recommended.

The culprit was likely unexpected problems merging devel into master.  In
future, I'll abort the merge rather than trying to fix it by hand.

Edward

**Comment by edreamleo** [comment]
This is an urgent bug.  Leo does not catch the exception!

**Comment by edreamleo** [comment]
On Wed, Aug 29, 2018 at 6:02 AM Edward K. Ream <edreamleo@gmail.com> wrote:

The culprit was likely unexpected problems merging devel into master.  In
> future, I'll abort the merge rather than trying to fix it by hand.
>

leoDist.leo (in master) contains this at line 189:

<<<<<<< HEAD

This is the git merge conflict marker!  Clearly, resolving the merge as I
did was a  big mistake.  There were lots of files involved, and apparently
I missed this one, and perhaps others.

It looks like there were several mistakes involved.

1. Somehow commits happened in master that should not have happened,
resulting, *much later*, in the merge conflict.

2. I should have resolved the merge conflicts in devel first, and then done
much more thorough testing in devel.

I may have made other mistakes as well.

Edward

**Comment by edreamleo** [comment]
EKR: I just did a grep -r "<<<<<<<" for leo-editor.  The only match was in leoDist.leo, which I have just corrected.

**Comment by edreamleo** [comment]
Fixed in devel at fb1a74.  Leo opens a minimal .leo file instead of the erroneous files.

This could cause problems if the user ignores the error message and then saves the file, but that seem doubly unlikely.  First, mal-formed .leo files are rare.  Second, the user is unlikely to start editing an empty outline.

**Comment by tbnorth** [comment]
On Wed, 29 Aug 2018 06:36:29 -0700
"Edward K. Ream" <notifications@github.com> wrote:

> Fixed in devel at fb1a74.  Leo opens a minimal .leo file instead of
> the erroneous files.
> 
> This could cause problems if the user ignores the error message and
> then saves the file, but that seem doubly unlikely.  First,
> mal-formed .leo files are rare.  Second, the user is unlikely to
> start editing an empty outline.

I guess saving the minimal file seems exactly like what a novice /
casual user might do to me.  Would it be hard to just change the same
of the minimal file, so if allMyNotes.leo fails to load you end up
viewing allMyNotes_load_fail.leo which contains some informative
instructions about the failure?

Cheers -Terry

**Comment by edreamleo** [comment]
On Wed, Aug 29, 2018 at 9:41 AM Terry Brown <notifications@github.com>
wrote:

I guess saving the minimal file seems exactly like what a novice /
> casual user might do
> .
>

I agree, but there is no easy way, at the point where the failure is found,
to do much about it.  The present approach longer crashes, but to my
knowledge Leo has never recovered in any reasonable way.

Would it be hard to just change the same
> of the minimal file, so if allMyNotes.leo fails to load you end up
> viewing allMyNotes_load_fail.leo which contains some informative
> instructions about the failure?
>

Yes.

Edward

**Comment by edreamleo** [comment]
On Wed, Aug 29, 2018 at 4:18 PM Edward K. Ream <edreamleo@gmail.com> wrote:

> On Wed, Aug 29, 2018 at 9:41 AM Terry Brown <notifications@github.com>
> wrote:
>
> I guess saving the minimal file seems exactly like what a novice /
>> casual user might do
>> .
>>
>
> I agree, but there is no easy way, at the point where the failure is
> found, to do much about it.
>

On second thought, I think the proper way to indicate failure is to return
None, not to gin up a dummy file.  This will cause a ripple effect later,
but it's better to fail cleanly, as you suggest.  I'll work on this
tomorrow.

Edward

**Comment by edreamleo** [comment]
Rev c92fc2d fixes the problem by ignoring (with a message) any mal-formed .leo file.  If no valid .leo files are loaded (from the command line or a session), Leo automatically opens workbook.leo.  Let's hope this file loads correctly...
