### ISSUE TITLE
@clean parsing error: some functions are empty!

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#973]
I've come across a weird parsing bug where some functions are shown as empty inside Leo. Just a screenshot for now to raise the alert. I can't share the script as it contains private info. I'll try and reduce it to it's simplest reproducible form.

![image](https://user-images.githubusercontent.com/486200/44962272-90c51380-aed2-11e8-984f-1114828efd69.png)

**Comment by tbnorth** [comment]
On Sun, 02 Sep 2018 17:07:33 -0700
matt wilkie <notifications@github.com> wrote:

> I've come across a weird parsing bug where some functions are shown
> as empty inside Leo. Just a screenshot for now to raise the alert. I
> can't share the script as it contains private info. I'll try and
> reduce it to it's simplest reproducible form.
> 
> ![image](https://user-images.githubusercontent.com/486200/44962272-90c51380-aed2-11e8-984f-1114828efd69.png)

Reminds me of
https://groups.google.com/d/topic/leo-editor/mNCnqG6QLes/discussion
although maybe just similar, not the same, that was always just one
node, and that was the node selected in the tree after load.

I assume the node content is actually missing and not just being loaded
in an adjacent node?

**Comment by maphew** [comment]
Hmm, content is not actually missing. It's all lumped into another node, basically all functions after `def main:` and before `if __name__ == "__main__":` are lumped into 'main' and visible as nodes in name only.

Compare the function list and order of appearance in Notepad++ to Leo in the first screenshot:
![image](https://user-images.githubusercontent.com/486200/45261068-2bc75d00-b3ad-11e8-82ab-bbaafb6a207d.png)

Refresh from disk doesn't change anything.  

I'm having trouble replicating reliably. It's doesn't appear related to file content and seems specific to the .leo workbook I encountered it in: when I save the file under a different name and load in a new Leo session it works as expected, every `def ...` is a different node.

**Comment by maphew** [comment]
Tagged back-burner until I can replicate it reliably

**Comment by edreamleo** [comment]
I am going to close this issue.  I do not believe this is a parser issue. .leo files are kinda like global variables as far as git branches are concerned.
