### ISSUE TITLE
"Open in ${EDTIOR}" does not always use the latest node contents

### ISSUE THREAD

**Issue by ShadowKyogre** [leo-editor/leo-editor#977]
### Expected behavior

Opening a node in an external editor should always have the latest content.

### What actually happens

It doesn't if the node isn't modified before exiting the external program.

### Steps to reproduce

0. Open a node in your editor of choice with the right click menu entry "Edit in ${EDITOR}"
0. Close the editor without writing anything to the file.
0. Type some text in the node.
0. Open the same node in your editor of choice with the right click menu entry "Edit in ${EDITOR}"
0. The external editor will show the file data at the time you opened it the first time, but not the second.

### Notes

Tested with gvim set as EDITOR. Not sure if this is editor specific, but will do further testing.

I think the main cause of the bug is that Leo isn't always updating the node data in the temporary file before having EDITOR open said file.

### Updates

Further investigation of the behavior points to [efc.open_with_helper](https://github.com/leo-editor/leo-editor/blob/master/leo/core/leoExternalFiles.py#L266-L283). It looks like the code currently doesn't check if the node's been updated since the temporary file was created.

**Comment by edreamleo** [comment]
Similar, or the same as, #981.
