### ISSUE TITLE
@bool rst3_code_mode = True

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#979]
# True: generate rst markup from @code and @doc parts.

The content in body pane is still under code line, after I used @ and @c in body pane.

**code:**

    1:@ 
    2:This descripting text , not code.
    3:@c 

I hope that this will be taken effect, I like this function. Thanks a lot!

***

Leo Log Window
Leo 5.8 b1 devel, build 20180902142730, Sun Sep  2 14:27:30 PDT 2018
Git repo info: branch = devel, commit = 89c45c577659
Python 3.6.6, PyQt version 5.11.1
linux
isPython3: True

**Comment by edreamleo** [comment]
The comment isn't perfectly clear.  `@` and `@c` are abbreviations for `@doc` and `@code`, so no change in behavior is expected.
