### ISSUE TITLE
Remove pypandoc & semantic_version dependencies for installing

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#980]
> As of March 16, 2018, PyPI.org aka Warehouse (finally) supports Markdown in long descriptions. Warehouse replaced the old legacy PyPI implementation in April 2018.
-- https://stackoverflow.com/a/26737258/14420
-- https://github.com/pypa/packaging-problems/issues/46
-- https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi

This means we can get rid of the pypandoc foofaraw in setup.py and keep it in plugins where it belongs (and can be incredibly useful).

**Comment by maphew** [comment]
applied in 0ac02d72b313324c1a8c189a7412f1b03d9908d6. Travis is happy, but it's not until we try a PyPi release that we'll know

**Comment by maphew** [comment]
Other post successful-pypi-from-travis todo:
- remove semantic_version dependency from `pyproject.toml`, `setup.py` (in several places)

**Comment by edreamleo** [comment]
On Sun, Oct 14, 2018 at 5:39 PM matt wilkie <notifications@github.com>
wrote:

> Other post successful-pypi-from-travis todo:
>
>    - remove semantic_version dependency from pyproject.toml, setup.py (in
>    several places)
>
> Thanks for this continuing work.  Do you have any idea why removing
leo/external/rope would cause TravisCI to fail?  All of Leo's unit tests
pass.

Edward

**Comment by maphew** [comment]
Closing. Pypandoc was removed a few months ago and semantic_version this week.
