### ISSUE TITLE
Going to a line number doesn't work

### ISSUE THREAD

**Issue by tbnorth** [leo-editor/leo-editor#985]
I do `man date | cat -n >test.txt` to create a text files with numbered lines.  Numbering starts at one, same as Python traceback numbering.

Editing the file in a single @edit node,

`Alt-X 12` goes to line 10 of the body editor (gutter numbering), which is line 9 of the external file, because the body text has a @nocolor line.

`Alt-X goto-global-line 12` does the same thing.

`Alt-X goto-line 12` goes to line 12 of the body, which is line 11 of the external file.

So maybe `goto-line`'s working as intended, but `goto-global-line` isn't?

**Comment by edreamleo** [comment]
@tbnorth I don't remember why there are two commands, or whether `@edit` is handled differently in either command.  I'll fix this soon.

**Comment by edreamleo** [comment]
goto-line goes to the n'th line of the buffer (body pane).  goto-global-line goes to the n'th line of the file.  Simple as that.
