### ISSUE TITLE
Remove Readme conversion from setup.py; Simplify build dependencies

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#987]
* With PEP 566 pypi.org can now read Markdown, so we can rip out all the extra work and associated dependencies (pypandoc) in setup.py to convert from md to restructured text. ([ref](https://pypi.org/project/markdown-description-example/))
* With [PEP 518](https://www.python.org/dev/peps/pep-0518/) we can move the dependencies needed only for package building out of the install for normal users

Discovered while troubleshooting #810. There's no point in waiting for that to get fixed before using these simplifications though.

**Comment by maphew** [comment]
x-ref: https://github.com/pypa/setuptools/issues/1495#issuecomment-423655919

**Comment by edreamleo** [comment]
Thanks, Matt, for handling all of this.

**Comment by edreamleo** [comment]
I am going to close this now that devel passes TravisCI.  Please reopen if necessary.
