### ISSUE TITLE
comm bridge between Leo and neovim

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#990]
This would allow:

- two-way conversions between vim outlines (in neovim) and Leo outlines (in the Leo bridge).
- Executing Leo commands (in neovim) on Leo outlines (in the Leo bridge).

**Aha**: we want *the neovim plugin* to convert between vim outlines and .leo outlines.

Leo should provide **vimoutline converters** to help the org mode code.

**Background**

**​gar**: Afaik, neovim can work as a completely background server an interact with frontend program by HTTP or something like this. Need to read more about it.

More thoughts in [this thread](https://groups.google.com/forum/#!topic/leo-editor/2WeLu4DiUZI).

The C++ sources for the stand-alone neovim-qt app are [here](https://github.com/equalsraf/neovim-qt).  [mainwindow.cpp](https://github.com/equalsraf/neovim-qt/blob/master/src/gui/mainwindow.cpp) is probably a good starting point for creating a nvim window in Leo.  I don't see any other reasonable starting point.

See the posts in [this thread](https://groups.google.com/forum/#!topic/leo-editor/jwhrq-ot9SA).

**Links**

- [pyqt wrapper](https://gitlab.com/Muream/neovim-pyqt)
  - quick test it just opens a white featureless window which does nothing, no error output
- [neovim home](https://neovim.io/) and [repo](https://github.com/neovim/neovim).
- [pynvim](https://github.com/neovim/python-client), **a Python client for neovim**.
- [MessagePack](https://msgpack.org/index.html).
- [python bindings for MessagePack](https://pypi.org/project/msgpack/).

**Installation**

- pip install msgpack
- pip install neovim

**Kent**: You can embed neovim into your python application instead of binding to a running neovim instance:
```python
from neovim import attach
nvim = attach('child', argv=["/bin/env", "nvim", "--embed"])
```
Not sure if that works with QT. [neovim-pyqt](https://gitlab.com/Muream/neovim-pyqt) subclasses a QT class to provide neovim in a QT window.

**Tom**: Using Neovim is hampered by it not being equally well supported on Windows as on Unix-y systems.  There  windows support consists of the core running with a Qt front end.  Terminal based Neovim only works well on Unix-y systems.

I believe the embedded switch is meant to be run with the terminal, it uses stdio/stderr as the communication channel between the parent and the embedded Neovim.

Even with the caveats I've mentioned, Neovim should be one of the easiest to put into Leo.  On non window systems you could embed the terminal version into the n-curses like version of Leo.  For all systems you'd take the Qt front end version of Neovim and get it to take the place of the editor pane, (i.e. the screen location).   Then, add msg-pack to Leo and use that to complete the integration.  Note that you can already detach and close the Leo;'s editor pane. This has the advantage of leaving Leo's log and outline pane and code in place.

**EKR**: Embedding the terminal version of neovim into Leo's curses gui code is not going to be useful, because Leo's curses gui is feeble.

**Comment by tbnorth** [comment]
You could look at making a neovim editor in the edit_pane machinery - that's basically what edit_pane's for, handling alternate editors, I had the Scintilla / Scite editor thing working there once.  edit_pane handles text changes from both ends of the pipe (Leo / the editor).  I assume handling Leo keys isn't a priority in this case.

**Comment by edreamleo** [comment]
I am going to reopen this issue.  The pyzo project has convinced me of the value of bringing the best features of other editors into Leo.  The pynvim project provides a starting point for investigations.

There are no guarantees, but I suspect some way can be found to use vim as a server for Leo's body panes.

**Comment by ktenney** [comment]
Really compelling pitch for the Vim Way.
https://www.youtube.com/watch?v=wlR5gYd6um0

Great free vids at https://thoughtbot.com/upcase/practice

**Comment by edreamleo** [comment]
On Mon, Mar 18, 2019 at 8:27 AM Kent Tenney <notifications@github.com>
wrote:

> Really compelling pitch for the Vim Way.
>

Imo, all we have to know is that some people prefer vim.  That's reason
enough to support it in Leo, if we can.

Edward

**Comment by edreamleo** [comment]
There is no need for this issue now that we have leoInteg.
