### ISSUE TITLE
replace-all can replace string, but can not save to file

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#991]
Leo Log Window
Leo 5.8.1 devel, build 20181008131522, Mon Oct  8 13:15:22 PDT 2018
Git repo info: branch = devel, commit = 25f330a1b59e
Python 3.6.6, PyQt version 5.11.1
linux
isPython3: True

**Comment by edreamleo** [comment]
I'm not sure what you mean by this.  Replace all works for me, and it's
possible to save the resulting outline.

Edward

**Comment by wangzhaohe** [comment]
I have tested **replace-all** Today, but it run well.
So please close this issue. Thanks!

**Comment by edreamleo** [comment]
@wangzhaohe Thanks for the update.
