### ISSUE TITLE
Plug holes in the tutorials

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#992]
From [this comment](https://groups.google.com/d/msg/leo-editor/jwhrq-ot9SA/ACcaFC77AgAJ) in the "Dreaming Big Dreams" discussion.

**Fixed**: In the main tutorial page, the script in Accessing Outline Data doesn't work - it's missing a parenthesis.

**Fixed** It's not clear to me how to even run the script. I happen to know Ctrl-B, but is it in the tutorial? I took the script and put it in a @button node, and the button didn't show up. I'm not sure if something is wrong with my Leo or the docs. It may be obvious, but it would be nice for that code snippet to have @language python.

**Fixed**: In the scripting tutorial, it would be nice if it pointed out that .h and .b refer to the headline and body. I know most will figure it out, but I think it should be spelled out explicitly.

Will any command I create that manipulates texts/nodes automatically be undo-able?

**EKR**: no.

If not, what do I need to do to ensure it is?

**EKR**: undo is beyond the scope of any tutorial.  I have added a new "Undoing commands" section to CheatSheet.leo.

A lot of stuff in the cheat sheet with regards to scripting is just a list with no explanation. Asking people to look at the source code to figure it out is not documenting anything. If all these classes/functions had good docstrings, one could autogenerate the docs using a script.

**EKR**: The lists document the *existence* of various features.  People can easily find the corresponding code by searching leoPy.leo, their local copy of LeoPyRef.leo.

**Fixed**: What is an ivar?  An ivar is an instance variable.  It's standard terminology.

I could not get unit testing to work in a way that is useful for me (see my other email on the mailing list).

The Miscellany of Scripts page used to have scripts that didn't work. I think the ones I complained about may have been fixed. In general, though, I think all the scripting docs are disorganized. Some of it is in one page, some in another, with no clear structure. I have to keep going to various pages and hitting Ctrl-F.

**EKR**: Specific suggestions only, please.

The commands reference page mentions macros. Do they work? Last time I tried they did not. 

**EKR**: These commands no longer exist.  They have been removed from LeoDocs.leo and will be removed from Leo's web site soon.

That page mentions Emacs behavior commands like kill and yank. Yet yank does *not* behave like it does in Emacs. In Emacs, if you yank, and then yank again, it will replace the region. Here it keeps appending.

**EKR**: This is [issue #337](https://github.com/leo-editor/leo-editor/issues/337).

How do I comment and uncomment multiple lines? 

**EKR**: Use Ctrl-[, add-comments, and Ctrl-], delete-comments.

Is that documented?

**EKR**: Yes.

I recently went through all the settings in Leo, and wow, there's quite a bit of good stuff there. How much of that is in the docs? Had I not decided to look at *all* the settings, I would not have discovered many of them. I'd like a page that lists all the settings, with descriptions. 

**EKR**: leoSettings.leo *is* the documentation for Leo's settings.  Leo's on-line documentation is kinda like an advert.  LeoDocs.leo and leoSettings.leo are far easier to use.

Many @settings nodes have descriptions, and many others do not, so I have little idea as to what they do.
Part of the documentation effort should be to put a good description of each one.

**EKR**: most should be self explanatory.

Is Leo "aware" of all its settings?

**EKR**: The answer is "yes and no".  Leo's startup code scans `@settings` trees, creating a global list of all settings.  But Leo has no idea what the actual settings are.

Is it not possible then to have a script that will generate documentation for all Leo's settings as an HTML (or part of the docs' rst) - and make sure this is on the web site. Trust me, it would make Leo a lot more usable if people had a page where they could see all the settings and just search for what they want.

**EKR**: The easiest way to find a setting is to search leoSettings.leo, not some huge web page.

Oh, and some settings appear to be "fake" - as in they are in the settings file, but when I do a cff in the code base all references to those settings are commented out. Staleness is a common problem. I would even argue that there should be a script to ensure that all the settings in @settings actually ARE settings. And in the other direction, if Leo has a setting, ensure it exists in the main settings file.

**EKR**: This is an ongoing problem.  Many recent stale settings have been removed.

We have various directives. Can I create my own? This may well be documented, but I don't know if it is.

**EKR**: Any script or plugin can create new directives by adding to `g.globalDirectiveList`.

Quite a lot of functions in the code base have no docstring. And the code is not that easy to read as so many variables are short single letter variables. I think good docstrings on functions would help a lot.

**EKR**: This is an ongoing project.  There is a script that ensures/ensured that all commands have a docstring.

I want to add support for a new language (syntax highlighting, etc). How well is this documented? Does it just say to look at the source code?

**EKR**: See the [Customizing Leo](http://leoeditor.com/customizing.html) chapter.

Are all the default keybindings documented?

**EKR**: Yes, in leoSettings.leo.

Leo is almost tragic in how powerful it is, and how much its adoption is held back by poor documentation. Good documentation will be a major endeavour, but well worth it.

**EKR**: I always welcome *specific* suggestions for improvements.  Leo's online docs are voluminous, but they are much less useful than searching leoSettings.leo or LeoDocs.leo.  Leo's docs are not poor, they are simply unusual.  We want outline structure everywhere to organized what would otherwise be endless words, words, words.

**Comment by edreamleo** [comment]
I am going to close this item.  Please feel free to make specific suggestions or ask questions on leo-editor.

**Comment by metaperl** [comment]
The [directives part of the tutorial](https://leoeditor.com/tutorial-basics.html#leo-directives) says 

> The @language directive tells which language is in effect:

and it should link to [the language directive](https://leoeditor.com/directives.html) when doing so.

**Comment by edreamleo** [comment]
@metaperl Similar comments could be made about many other references.

I'm going to defer this until we switch to asciidoc.
